SUBMODULE (MODD_CONVPAREXT) MODD_CONVPAREXT_CONVPAREXT_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE CRC64_CONVPAREXT (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (CONVPAREXT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%JCVEXB), CDPATH//'%JCVEXB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%JCVEXT), CDPATH//'%JCVEXT'

END SUBROUTINE

END SUBMODULE
