MODULE YOMPERTPAR
!
! Purpose :
! ---------
! Define bounds of perturbations range for
! parameters to be perturbed in Random Parameter scheme
! in PEARP

! Interface :
! ----------
! Empty

! External :
! --------
! None

! Method :
! -------
! See documentation

! Author:
! -------
! Original : L.descamps - 2021-04-26 
!-----------------------------------------------------------
!
USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

LOGICAL :: LPERTPAR
INTEGER(KIND=JPIM) :: NSEED_MBR
!
! Perturbed parameters for TDK cv scheme
!
LOGICAL::LPERT_RMFDEPS
REAL(KIND=JPRB)::RMFDEPS_MAX
REAL(KIND=JPRB)::RMFDEPS_MIN
!
LOGICAL::LPERT_RPRCON
REAL(KIND=JPRB)::RPRCON_MAX
REAL(KIND=JPRB)::RPRCON_MIN
!
LOGICAL::LPERT_ENTRORG
REAL(KIND=JPRB)::ENTRORG_MAX
REAL(KIND=JPRB)::ENTRORG_MIN
!
LOGICAL::LPERT_DETRPEN
REAL(KIND=JPRB)::DETRPEN_MAX
REAL(KIND=JPRB)::DETRPEN_MIN
!
LOGICAL::LPERT_RTAUFAC
REAL(KIND=JPRB)::RTAUFAC_MAX
REAL(KIND=JPRB)::RTAUFAC_MIN
!
LOGICAL::LPERT_CUDUV
REAL(KIND=JPRB)::CUDU_MOD
REAL(KIND=JPRB)::CUDV_MOD
REAL(KIND=JPRB)::CUDUV_MAX
REAL(KIND=JPRB)::CUDUV_MIN
!
! For PCMT deep cv scheme
LOGICAL::LPERT_GCVRE
REAL(KIND=JPRB)::GCVRE_MAX
REAL(KIND=JPRB)::GCVRE_MIN
!
LOGICAL::LPERT_GCVEZ
REAL(KIND=JPRB)::GCVEZ_MAX
REAL(KIND=JPRB)::GCVEZ_MIN
!
LOGICAL::LPERT_GCVUV
REAL(KIND=JPRB)::GCVUV_MAX
REAL(KIND=JPRB)::GCVUV_MIN
!
! For Turbulence
!
LOGICAL::LPERT_AKN
REAL(KIND=JPRB)::AKN_MAX
REAL(KIND=JPRB)::AKN_MIN
!
LOGICAL::LPERT_ALD
REAL(KIND=JPRB)::ALD_MAX
REAL(KIND=JPRB)::ALD_MIN
!
LOGICAL::LPERT_ALPHAT
REAL(KIND=JPRB)::ALPHAT_MAX
REAL(KIND=JPRB)::ALPHAT_MIN
!
LOGICAL::LPERT_ALMAVE
REAL(KIND=JPRB)::ALMAVE_MAX
REAL(KIND=JPRB)::ALMAVE_MIN
!
! For Microphysic scheme
!
LOGICAL::LPERT_TFVL
REAL(KIND=JPRB)::TFVL_MIN
REAL(KIND=JPRB)::TFVL_MAX
!
LOGICAL::LPERT_TFVR
REAL(KIND=JPRB)::TFVR_MIN
REAL(KIND=JPRB)::TFVR_MAX
!
LOGICAL::LPERT_TFVS
REAL(KIND=JPRB)::TFVS_MIN
REAL(KIND=JPRB)::TFVS_MAX
!
LOGICAL::LPERT_TFVI
REAL(KIND=JPRB)::TFVI_MIN
REAL(KIND=JPRB)::TFVI_MAX
!
LOGICAL::LPERT_RAUTEFR
REAL(KIND=JPRB)::RAUTEFR_MIN
REAL(KIND=JPRB)::RAUTEFR_MAX
!
LOGICAL::LPERT_RAUTEFS
REAL(KIND=JPRB)::RAUTEFS_MIN
REAL(KIND=JPRB)::RAUTEFS_MAX
!
LOGICAL::LPERT_RQICRMIN
REAL(KIND=JPRB)::RQICRMIN_MIN
REAL(KIND=JPRB)::RQICRMIN_MAX
!
LOGICAL::LPERT_RQICRMAX
REAL(KIND=JPRB)::RQICRMAX_MIN
REAL(KIND=JPRB)::RQICRMAX_MAX
!
LOGICAL::LPERT_RQLCR
REAL(KIND=JPRB)::RQLCR_MIN
REAL(KIND=JPRB)::RQLCR_MAX
!
LOGICAL::LPERT_RACCEF
REAL(KIND=JPRB)::RACCEF_MIN
REAL(KIND=JPRB)::RACCEF_MAX
!
LOGICAL::LPERT_RRIMEF
REAL(KIND=JPRB)::RRIMEF_MIN
REAL(KIND=JPRB)::RRIMEF_MAX
!
LOGICAL::LPERT_RAGGEF
REAL(KIND=JPRB)::RAGGEF_MIN
REAL(KIND=JPRB)::RAGGEF_MAX
!
LOGICAL::LPERT_REVASX
REAL(KIND=JPRB)::REVASX_MIN
REAL(KIND=JPRB)::REVASX_MAX
!
LOGICAL::LPERT_RDTFAC
REAL(KIND=JPRB)::RDTFAC_MIN
REAL(KIND=JPRB)::RDTFAC_MAX
!
LOGICAL::LPERT_RHCRIT1
REAL(KIND=JPRB)::RHCRIT1_MIN
REAL(KIND=JPRB)::RHCRIT1_MAX
!
LOGICAL::LPERT_GRHCMOD
REAL(KIND=JPRB)::GRHCMOD_MIN
REAL(KIND=JPRB)::GRHCMOD_MAX
!
! For GWD scheme
!
LOGICAL::LPERT_GWDCD
REAL(KIND=JPRB)::GWDCD_MIN
REAL(KIND=JPRB)::GWDCD_MAX
!
LOGICAL::LPERT_GWDSE
REAL(KIND=JPRB)::GWDSE_MIN
REAL(KIND=JPRB)::GWDSE_MAX
!
LOGICAL::LPERT_HOBST
REAL(KIND=JPRB)::HOBST_MIN
REAL(KIND=JPRB)::HOBST_MAX
!
! For SRTM radiation scheme
!
LOGICAL::LPERT_RRATSEA
REAL(KIND=JPRB)::RRATSEA_MIN
REAL(KIND=JPRB)::RRATSEA_MAX
!
LOGICAL::LPERT_RRATLAND
REAL(KIND=JPRB)::RRATLAND_MIN
REAL(KIND=JPRB)::RRATLAND_MAX
!
LOGICAL::LPERT_RRATDRI
REAL(KIND=JPRB)::RRATDRI_MAX
REAL(KIND=JPRB)::RRATDRI_MIN
!
LOGICAL::LPERT_RCADECOR
REAL(KIND=JPRB)::RCADECOR_MAX
REAL(KIND=JPRB)::RCADECOR_MIN
!
LOGICAL::LPERT_RCBDECOR
REAL(KIND=JPRB)::RCBDECOR_MAX
REAL(KIND=JPRB)::RCBDECOR_MIN
!

LOGICAL::LPERT_RSIGMA2
REAL(KIND=JPRB)::RSIGMA2_MAX
REAL(KIND=JPRB)::RSIGMA2_MIN
!
LOGICAL::LPERT_RFACDICE
REAL(KIND=JPRB)::RFACDICE_MAX
REAL(KIND=JPRB)::RFACDICE_MIN
!
! For surface scheme
!
LOGICAL::LPERT_XRIMAX
REAL(KIND=JPRB)::XRIMAX_MIN
REAL(KIND=JPRB)::XRIMAX_MAX
!
LOGICAL::LPERT_XFRACZ0
REAL(KIND=JPRB)::XFRACZ0_MIN
REAL(KIND=JPRB)::XFRACZ0_MAX
!
! For shallow cv scheme
!
LOGICAL::LPERT_OTADJS
REAL(KIND=JPRB)::OTADJS_MIN
REAL(KIND=JPRB)::OTADJS_MAX
!
LOGICAL::LPERT_XENTR
REAL(KIND=JPRB)::XENTR_MIN
REAL(KIND=JPRB)::XENTR_MAX
!
LOGICAL::LPERT_XATPERT
REAL(KIND=JPRB)::XATPERT_MIN
REAL(KIND=JPRB)::XATPERT_MAX
!
LOGICAL::LPERT_XBTPERT
REAL(KIND=JPRB)::XBTPERT_MIN
REAL(KIND=JPRB)::XBTPERT_MAX
!
LOGICAL::LPERT_XDTPERT
REAL(KIND=JPRB)::XDTPERT_MIN
REAL(KIND=JPRB)::XDTPERT_MAX
!
LOGICAL::LPERT_XAW
REAL(KIND=JPRB)::XAW_MIN
REAL(KIND=JPRB)::XAW_MAX
!
LOGICAL::LPERT_XBW
REAL(KIND=JPRB)::XBW_MIN
REAL(KIND=JPRB)::XBW_MAX
!
LOGICAL::LPERT_RKFBTAU
REAL(KIND=JPRB)::RKFBTAU_MIN
REAL(KIND=JPRB)::RKFBTAU_MAX
!
LOGICAL::LPERT_RKFBNBX
REAL(KIND=JPRB)::RKFBNBX_MIN
REAL(KIND=JPRB)::RKFBNBX_MAX
!
! For ECUME scheme
LOGICAL::LPERT_XPERTFLUX
REAL(KIND=JPRB)::XPERTFLUX_MAX
REAL(KIND=JPRB)::XPERTFLUX_MIN


END MODULE YOMPERTPAR
