SUBROUTINE CTVTOT_EXPL (YDCST, YDGEOMETRY, YDVARS, YDCPG_OPTS, YDCPG_BNDS)

!$ACDC outline1    


USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : DR_HOOK, JPHOOK, LHOOK
USE YOMCST             , ONLY : TCST
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES

IMPLICIT NONE

TYPE(TCST)            ,INTENT(IN)     :: YDCST
TYPE(GEOMETRY)        ,INTENT(IN)     :: YDGEOMETRY
TYPE(CPG_OPTS_TYPE)   ,INTENT(IN)     :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE)   ,INTENT(IN)     :: YDCPG_BNDS
TYPE(FIELD_VARIABLES) ,INTENT(INOUT)  :: YDVARS

#include "gprcp_expl.intfb.h"

REAL(KIND=JPRB) :: ZR(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)

INTEGER(KIND=JPIM) :: JLEV, JROF

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CTVTOT_EXPL',0,ZHOOK_HANDLE)

ASSOCIATE (YDDIM=>YDGEOMETRY%YRDIM, YDDIMV=>YDGEOMETRY%YRDIMV)
ASSOCIATE (NPROMA=>YDDIM%NPROMA, NFLEVG=>YDDIMV%NFLEVG)

CALL GPRCP_EXPL (YDCST, YDCPG_BNDS, YDCPG_OPTS, YDVARS=YDVARS, PR=ZR)

!$ACDC PARALLEL, TARGET=OpenMP/OpenMPSingleColumn/OpenACCSingleColumn {

DO JLEV = 1, NFLEVG
  DO JROF = YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    YDVARS%T%T0(JROF,JLEV)=YDCST%RD*YDVARS%T%T0(JROF,JLEV)/ZR(JROF,JLEV)
  ENDDO
ENDDO

!$ACDC }

END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('CTVTOT_EXPL',1,ZHOOK_HANDLE)

END SUBROUTINE CTVTOT_EXPL

