INTERFACE
SUBROUTINE CPTENDS ( YDCST, YDML_PHY_MF,KLON, KIDIA, KFDIA, KFLEV, KCSS, PDT,&
& PFPLCL, PFPLSL, PFPLCN, PFPLSN,&
& PFRSO, PFRTH,&
& PALBNS1 ,PCT, PC1, PC2,&
& PFCHSP, PFCLL, PFCLN, PFCS, PFEVI, PFEVL, PFEVN,&
& PFEVV , PFGEL, PFGELS, PFLWSP, PFONTE, PFTR,&
& PLSM, PRHONS1, PRUISL, PRUISP, PRUISS, PSNS1, PVEG,&
& PTDTS, PTDTP, PTDWS, PTDWSI, PTDWP, PTDWPI, PTDWL, PTDSNS,&
& PTDALBNS, PTDRHONS )
USE MODEL_PHYSICS_MF_MOD, ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1            , ONLY : JPIM, JPRB
USE YOMCST              , ONLY : TCST
IMPLICIT NONE
TYPE(TCST)                  ,INTENT(IN)   :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE) ,INTENT(IN)   :: YDML_PHY_MF
INTEGER(KIND=JPIM)          ,INTENT(IN)   :: KLON
INTEGER(KIND=JPIM)          ,INTENT(IN)   :: KIDIA
INTEGER(KIND=JPIM)          ,INTENT(IN)   :: KFDIA
INTEGER(KIND=JPIM)          ,INTENT(IN)   :: KFLEV
INTEGER(KIND=JPIM)          ,INTENT(IN)   :: KCSS
REAL(KIND=JPRB)             ,INTENT(IN)   :: PDT
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFPLCL(KLON,0:KFLEV)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFPLSL(KLON,0:KFLEV)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFPLCN(KLON,0:KFLEV)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFPLSN(KLON,0:KFLEV)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFRSO(KLON,0:KFLEV)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFRTH(KLON,0:KFLEV)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PALBNS1(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PCT(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PC1(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PC2(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFCHSP(KLON,KCSS)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFCLL(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFCLN(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFCS(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFEVI(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFEVL(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFEVN(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFEVV(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFGEL(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFGELS(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFLWSP(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFONTE(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PFTR(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PLSM(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PRHONS1(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PRUISL(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PRUISP(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PRUISS(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PSNS1(KLON)
REAL(KIND=JPRB)             ,INTENT(IN)   :: PVEG(KLON)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDTS(KLON)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDTP(KLON,KCSS)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDWS(KLON)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDWSI(KLON)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDWP(KLON)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDWPI(KLON)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDWL(KLON)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDSNS(KLON)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDALBNS(KLON)
REAL(KIND=JPRB)             ,INTENT(OUT)  :: PTDRHONS(KLON)
END SUBROUTINE CPTENDS







END INTERFACE
