MODULE UTIL_FLUXES_DESCRIPTOR_MOD

USE TYPE_FLUXES, ONLY : FLUXES_DESCRIPTOR



INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_FLUXES_DESCRIPTOR
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_FLUXES_DESCRIPTOR
END INTERFACE



INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_FLUXES_DESCRIPTOR
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_FLUXES_DESCRIPTOR
END INTERFACE

CONTAINS





SUBROUTINE ACDC_COPY_FLUXES_DESCRIPTOR (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (FLUXES_DESCRIPTOR), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_FLUXES_DESCRIPTOR (SELF)

IMPLICIT NONE
TYPE (FLUXES_DESCRIPTOR), TARGET :: SELF


END SUBROUTINE





SUBROUTINE ACDC_WIPE_FLUXES_DESCRIPTOR (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (FLUXES_DESCRIPTOR), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_FLUXES_DESCRIPTOR (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (FLUXES_DESCRIPTOR),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%CLPREF) * SIZE (SELF%CLPREF) * LEN (SELF%CLPREF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CLPREF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CLSUFF) * LEN (SELF%CLSUFF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CLSUFF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%INUMLEV) * SIZE (SELF%INUMLEV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%INUMLEV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ILEV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ILEV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IPARITY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IPARITY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LACTIVE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LACTIVE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ILEVBOT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ILEVBOT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IOFFSET)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IOFFSET'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
