MODULE UTIL_TYPE_AERO_WVL_DIAG_MOD

USE YOE_AERODIAG, ONLY : TYPE_AERO_WVL_DIAG

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE ACDC_LEGACY
MODULE PROCEDURE ACDC_LEGACY_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TYPE_AERO_WVL_DIAG
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TYPE_AERO_WVL_DIAG
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TYPE_AERO_WVL_DIAG (SELF, KLUN)

IMPLICIT NONE
TYPE (TYPE_AERO_WVL_DIAG), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%IWVL
WRITE (KLUN) SELF%IGRIBDIAG
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TYPE_AERO_WVL_DIAG (SELF, KLUN)

IMPLICIT NONE
TYPE (TYPE_AERO_WVL_DIAG), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%IWVL
READ (KLUN) SELF%IGRIBDIAG
END SUBROUTINE

SUBROUTINE ACDC_COPY_TYPE_AERO_WVL_DIAG (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TYPE_AERO_WVL_DIAG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TYPE_AERO_WVL_DIAG (SELF)

IMPLICIT NONE
TYPE (TYPE_AERO_WVL_DIAG), TARGET :: SELF


END SUBROUTINE

SUBROUTINE ACDC_LEGACY_TYPE_AERO_WVL_DIAG (SELF, KADDRL, KADDRU, KDIR)

IMPLICIT NONE
TYPE (TYPE_AERO_WVL_DIAG), TARGET :: SELF
INTEGER*8, INTENT (IN) :: KADDRL
INTEGER*8, INTENT (IN) :: KADDRU
INTEGER, INTENT (IN) :: KDIR


END SUBROUTINE

SUBROUTINE ACDC_CRC64_TYPE_AERO_WVL_DIAG (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TYPE_AERO_WVL_DIAG), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IWVL), CDPATH//'%IWVL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IGRIBDIAG), CDPATH//'%IGRIBDIAG'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TYPE_AERO_WVL_DIAG (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TYPE_AERO_WVL_DIAG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TYPE_AERO_WVL_DIAG (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TYPE_AERO_WVL_DIAG),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%IWVL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IWVL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IGRIBDIAG) * SIZE (SELF%IGRIBDIAG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IGRIBDIAG'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
