MODULE UTIL_TLOUIS_MOD

USE YOMLOUIS, ONLY : TLOUIS

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TLOUIS
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TLOUIS
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TLOUIS
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TLOUIS
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TLOUIS
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TLOUIS
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TLOUIS
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TLOUIS (SELF, KLUN)

IMPLICIT NONE
TYPE (TLOUIS), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%RLOUIS_S0
WRITE (KLUN) SELF%PLOUIS_S0
WRITE (KLUN) SELF%RLOUIS_GU1
WRITE (KLUN) SELF%RLOUIS_GU2
WRITE (KLUN) SELF%PLOUIS_GU1
WRITE (KLUN) SELF%PLOUIS_GU2
WRITE (KLUN) SELF%RLOUIS_GS1
WRITE (KLUN) SELF%RLOUIS_GS2
WRITE (KLUN) SELF%RLOUIS_GS3
WRITE (KLUN) SELF%RLOUIS_GS4
WRITE (KLUN) SELF%PLOUIS_GS1
WRITE (KLUN) SELF%PLOUIS_GS2
WRITE (KLUN) SELF%PLOUIS_GS3
WRITE (KLUN) SELF%PLOUIS_GS4
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TLOUIS (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TLOUIS), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%RLOUIS_S0 = ZTMP0
READ (KLUN) ZTMP0
SELF%PLOUIS_S0 = ZTMP0
READ (KLUN) ZTMP0
SELF%RLOUIS_GU1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RLOUIS_GU2 = ZTMP0
READ (KLUN) ZTMP0
SELF%PLOUIS_GU1 = ZTMP0
READ (KLUN) ZTMP0
SELF%PLOUIS_GU2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RLOUIS_GS1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RLOUIS_GS2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RLOUIS_GS3 = ZTMP0
READ (KLUN) ZTMP0
SELF%RLOUIS_GS4 = ZTMP0
READ (KLUN) ZTMP0
SELF%PLOUIS_GS1 = ZTMP0
READ (KLUN) ZTMP0
SELF%PLOUIS_GS2 = ZTMP0
READ (KLUN) ZTMP0
SELF%PLOUIS_GS3 = ZTMP0
READ (KLUN) ZTMP0
SELF%PLOUIS_GS4 = ZTMP0
END SUBROUTINE

SUBROUTINE ACDC_COPY_TLOUIS (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLOUIS), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TLOUIS (SELF)

IMPLICIT NONE
TYPE (TLOUIS), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TLOUIS (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TLOUIS), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLOUIS_S0), CDPATH//'%RLOUIS_S0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PLOUIS_S0), CDPATH//'%PLOUIS_S0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLOUIS_GU1), CDPATH//'%RLOUIS_GU1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLOUIS_GU2), CDPATH//'%RLOUIS_GU2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PLOUIS_GU1), CDPATH//'%PLOUIS_GU1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PLOUIS_GU2), CDPATH//'%PLOUIS_GU2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLOUIS_GS1), CDPATH//'%RLOUIS_GS1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLOUIS_GS2), CDPATH//'%RLOUIS_GS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLOUIS_GS3), CDPATH//'%RLOUIS_GS3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLOUIS_GS4), CDPATH//'%RLOUIS_GS4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PLOUIS_GS1), CDPATH//'%PLOUIS_GS1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PLOUIS_GS2), CDPATH//'%PLOUIS_GS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PLOUIS_GS3), CDPATH//'%PLOUIS_GS3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PLOUIS_GS4), CDPATH//'%PLOUIS_GS4'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TLOUIS (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLOUIS), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TLOUIS (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TLOUIS),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%RLOUIS_S0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLOUIS_S0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%PLOUIS_S0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%PLOUIS_S0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLOUIS_GU1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLOUIS_GU1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLOUIS_GU2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLOUIS_GU2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%PLOUIS_GU1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%PLOUIS_GU1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%PLOUIS_GU2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%PLOUIS_GU2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLOUIS_GS1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLOUIS_GS1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLOUIS_GS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLOUIS_GS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLOUIS_GS3)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLOUIS_GS3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLOUIS_GS4)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLOUIS_GS4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%PLOUIS_GS1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%PLOUIS_GS1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%PLOUIS_GS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%PLOUIS_GS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%PLOUIS_GS3)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%PLOUIS_GS3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%PLOUIS_GS4)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%PLOUIS_GS4'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
