MODULE UTIL_TVDF_MOD

USE YOEVDF, ONLY : TVDF

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TVDF
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TVDF
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TVDF
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TVDF
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TVDF
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TVDF
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TVDF
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TVDF (SELF, KLUN)

IMPLICIT NONE
TYPE (TVDF), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%RLAM
WRITE (KLUN) SELF%RVDIFTS
WRITE (KLUN) SELF%LWDS
WRITE (KLUN) SELF%REPS1WDS
WRITE (KLUN) SELF%REPS2WDS
WRITE (KLUN) SELF%RETAWDS
WRITE (KLUN) SELF%RTOFDALPHA
WRITE (KLUN) SELF%REISTHSC
WRITE (KLUN) SELF%NSUBST
WRITE (KLUN) SELF%RFAC_TWO_COEF
WRITE (KLUN) SELF%RZC_H
WRITE (KLUN) SELF%RZL_INF
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TVDF (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TVDF), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%RLAM = ZTMP0
READ (KLUN) ZTMP0
SELF%RVDIFTS = ZTMP0
READ (KLUN) SELF%LWDS
READ (KLUN) ZTMP0
SELF%REPS1WDS = ZTMP0
READ (KLUN) ZTMP0
SELF%REPS2WDS = ZTMP0
READ (KLUN) ZTMP0
SELF%RETAWDS = ZTMP0
READ (KLUN) ZTMP0
SELF%RTOFDALPHA = ZTMP0
READ (KLUN) ZTMP0
SELF%REISTHSC = ZTMP0
READ (KLUN) SELF%NSUBST
READ (KLUN) ZTMP0
SELF%RFAC_TWO_COEF = ZTMP0
READ (KLUN) ZTMP0
SELF%RZC_H = ZTMP0
READ (KLUN) ZTMP0
SELF%RZL_INF = ZTMP0
END SUBROUTINE

SUBROUTINE ACDC_COPY_TVDF (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TVDF), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TVDF (SELF)

IMPLICIT NONE
TYPE (TVDF), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TVDF (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TVDF), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLAM), CDPATH//'%RLAM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RVDIFTS), CDPATH//'%RVDIFTS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LWDS), CDPATH//'%LWDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REPS1WDS), CDPATH//'%REPS1WDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REPS2WDS), CDPATH//'%REPS2WDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RETAWDS), CDPATH//'%RETAWDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTOFDALPHA), CDPATH//'%RTOFDALPHA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REISTHSC), CDPATH//'%REISTHSC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSUBST), CDPATH//'%NSUBST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFAC_TWO_COEF), CDPATH//'%RFAC_TWO_COEF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RZC_H), CDPATH//'%RZC_H'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RZL_INF), CDPATH//'%RZL_INF'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TVDF (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TVDF), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TVDF (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TVDF),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%RLAM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLAM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RVDIFTS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RVDIFTS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LWDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LWDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REPS1WDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REPS1WDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REPS2WDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REPS2WDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RETAWDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RETAWDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RTOFDALPHA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTOFDALPHA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REISTHSC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REISTHSC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSUBST)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSUBST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RFAC_TWO_COEF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RFAC_TWO_COEF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RZC_H)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RZC_H'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RZL_INF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RZL_INF'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
