MODULE UTIL_TCOMPO_EMIS_AUX_MOD

USE YOMCOMPO, ONLY : TCOMPO_EMIS_AUX

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TCOMPO_EMIS_AUX
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TCOMPO_EMIS_AUX
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TCOMPO_EMIS_AUX (SELF, KLUN)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%PARAMID
WRITE (KLUN) SELF%TEMPORALITY
WRITE (KLUN) SELF%CNAME
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TCOMPO_EMIS_AUX (SELF, KLUN)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%PARAMID
READ (KLUN) SELF%TEMPORALITY
READ (KLUN) SELF%CNAME
END SUBROUTINE

SUBROUTINE ACDC_COPY_TCOMPO_EMIS_AUX (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TCOMPO_EMIS_AUX (SELF)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TCOMPO_EMIS_AUX (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PARAMID), CDPATH//'%PARAMID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TEMPORALITY), CDPATH//'%TEMPORALITY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CNAME), CDPATH//'%CNAME'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TCOMPO_EMIS_AUX (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TCOMPO_EMIS_AUX (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%PARAMID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%PARAMID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TEMPORALITY) * LEN (SELF%TEMPORALITY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TEMPORALITY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CNAME) * LEN (SELF%CNAME)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CNAME'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
