MODULE UTIL_TECND_MOD

USE YOECND, ONLY : TECND

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TECND
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TECND
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TECND
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TECND
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TECND
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TECND
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TECND
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TECND (SELF, KLUN)

IMPLICIT NONE
TYPE (TECND), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%REPFLM
WRITE (KLUN) SELF%REPQMI
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TECND (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TECND), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%REPFLM = ZTMP0
READ (KLUN) ZTMP0
SELF%REPQMI = ZTMP0
END SUBROUTINE

SUBROUTINE ACDC_COPY_TECND (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TECND), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TECND (SELF)

IMPLICIT NONE
TYPE (TECND), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TECND (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TECND), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REPFLM), CDPATH//'%REPFLM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REPQMI), CDPATH//'%REPQMI'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TECND (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TECND), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TECND (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TECND),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%REPFLM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REPFLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REPQMI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REPQMI'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
