MODULE UTIL_TMSE_MOD

USE YOMMSE, ONLY : TMSE

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TMSE
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TMSE
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TMSE
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TMSE
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TMSE
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TMSE
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TMSE
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TMSE (SELF, KLUN)

IMPLICIT NONE
TYPE (TMSE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LPGDFWR
WRITE (KLUN) SELF%LHISFWR
WRITE (KLUN) SELF%LFTZERO
WRITE (KLUN) SELF%NSURFEXCTLMAX
WRITE (KLUN) SELF%NSURFEXCTL
WRITE (KLUN) SELF%NSTEP_DUMP_STATE
WRITE (KLUN) SELF%CPREFIX_SFX1
WRITE (KLUN) SELF%CPREFIX_SFX2
WRITE (KLUN) SELF%XZSEPS
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TMSE (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TMSE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%LPGDFWR
READ (KLUN) SELF%LHISFWR
READ (KLUN) SELF%LFTZERO
READ (KLUN) SELF%NSURFEXCTLMAX
READ (KLUN) SELF%NSURFEXCTL
READ (KLUN) SELF%NSTEP_DUMP_STATE
READ (KLUN) SELF%CPREFIX_SFX1
READ (KLUN) SELF%CPREFIX_SFX2
READ (KLUN) ZTMP0
SELF%XZSEPS = ZTMP0
END SUBROUTINE

SUBROUTINE ACDC_COPY_TMSE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TMSE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TMSE (SELF)

IMPLICIT NONE
TYPE (TMSE), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TMSE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TMSE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPGDFWR), CDPATH//'%LPGDFWR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHISFWR), CDPATH//'%LHISFWR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LFTZERO), CDPATH//'%LFTZERO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSURFEXCTLMAX), CDPATH//'%NSURFEXCTLMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSURFEXCTL), CDPATH//'%NSURFEXCTL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSTEP_DUMP_STATE), CDPATH//'%NSTEP_DUMP_STATE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CPREFIX_SFX1), CDPATH//'%CPREFIX_SFX1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CPREFIX_SFX2), CDPATH//'%CPREFIX_SFX2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XZSEPS), CDPATH//'%XZSEPS'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TMSE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TMSE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TMSE (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TMSE),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%LPGDFWR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPGDFWR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHISFWR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHISFWR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LFTZERO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LFTZERO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSURFEXCTLMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSURFEXCTLMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSURFEXCTL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSURFEXCTL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSTEP_DUMP_STATE) * SIZE (SELF%NSTEP_DUMP_STATE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSTEP_DUMP_STATE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CPREFIX_SFX1) * LEN (SELF%CPREFIX_SFX1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CPREFIX_SFX1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CPREFIX_SFX2) * LEN (SELF%CPREFIX_SFX2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CPREFIX_SFX2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XZSEPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XZSEPS'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
