MODULE UTIL_TYPE_GFL_NAML_MOD

USE YOM_YGFL, ONLY : TYPE_GFL_NAML

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TYPE_GFL_NAML
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TYPE_GFL_NAML
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TYPE_GFL_NAML
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TYPE_GFL_NAML
END INTERFACE

INTERFACE ACDC_LEGACY
MODULE PROCEDURE ACDC_LEGACY_TYPE_GFL_NAML
END INTERFACE

INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TYPE_GFL_NAML
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TYPE_GFL_NAML
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TYPE_GFL_NAML
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TYPE_GFL_NAML (SELF, KLUN)

IMPLICIT NONE
TYPE (TYPE_GFL_NAML), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%CNAME
WRITE (KLUN) SELF%IGRBCODE
WRITE (KLUN) SELF%NREQIN
WRITE (KLUN) SELF%REFVALI
WRITE (KLUN) SELF%LREQOUT
WRITE (KLUN) SELF%LGPINGP
WRITE (KLUN) SELF%LMGRID
WRITE (KLUN) SELF%LGP
WRITE (KLUN) SELF%LSP
WRITE (KLUN) SELF%LCDERS
WRITE (KLUN) SELF%LT9
WRITE (KLUN) SELF%LT1
WRITE (KLUN) SELF%LT5
WRITE (KLUN) SELF%LPHY
WRITE (KLUN) SELF%LPT
WRITE (KLUN) SELF%LTRAJIO
WRITE (KLUN) SELF%LDIAG
WRITE (KLUN) SELF%LPC
WRITE (KLUN) SELF%LADV
WRITE (KLUN) SELF%LADV5
WRITE (KLUN) SELF%LINTLIN
WRITE (KLUN) SELF%LTDIABLIN
WRITE (KLUN) SELF%LHORTURB
WRITE (KLUN) SELF%LQM
WRITE (KLUN) SELF%LQMH
WRITE (KLUN) SELF%LQM3D
WRITE (KLUN) SELF%LQML3D
WRITE (KLUN) SELF%LVWENO
WRITE (KLUN) SELF%WENO_ALPHA
WRITE (KLUN) SELF%LSLHD
WRITE (KLUN) SELF%LCOMAD
WRITE (KLUN) SELF%LHV
WRITE (KLUN) SELF%LVSPLIP
WRITE (KLUN) SELF%NCOUPLING
WRITE (KLUN) SELF%REFVALC
WRITE (KLUN) SELF%NCOUPLO4
WRITE (KLUN) SELF%LASSIM
WRITE (KLUN) SELF%IGRIBDV
WRITE (KLUN) SELF%IGRIBTC
WRITE (KLUN) SELF%IGRBFLXO
WRITE (KLUN) SELF%IGRBWDFLX
WRITE (KLUN) SELF%IGRBDDFLX
WRITE (KLUN) SELF%LDIFF
WRITE (KLUN) SELF%LCONV
WRITE (KLUN) SELF%LNEGFIX
WRITE (KLUN) SELF%LMASSFIX
WRITE (KLUN) SELF%BETAMFBC
WRITE (KLUN) SELF%RMOLMASS
WRITE (KLUN) SELF%REFOLD
WRITE (KLUN) SELF%HENRYA
WRITE (KLUN) SELF%HENRYB
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TYPE_GFL_NAML (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TYPE_GFL_NAML), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%CNAME
READ (KLUN) SELF%IGRBCODE
READ (KLUN) SELF%NREQIN
READ (KLUN) ZTMP0
SELF%REFVALI = ZTMP0
READ (KLUN) SELF%LREQOUT
READ (KLUN) SELF%LGPINGP
READ (KLUN) SELF%LMGRID
READ (KLUN) SELF%LGP
READ (KLUN) SELF%LSP
READ (KLUN) SELF%LCDERS
READ (KLUN) SELF%LT9
READ (KLUN) SELF%LT1
READ (KLUN) SELF%LT5
READ (KLUN) SELF%LPHY
READ (KLUN) SELF%LPT
READ (KLUN) SELF%LTRAJIO
READ (KLUN) SELF%LDIAG
READ (KLUN) SELF%LPC
READ (KLUN) SELF%LADV
READ (KLUN) SELF%LADV5
READ (KLUN) SELF%LINTLIN
READ (KLUN) SELF%LTDIABLIN
READ (KLUN) SELF%LHORTURB
READ (KLUN) SELF%LQM
READ (KLUN) SELF%LQMH
READ (KLUN) SELF%LQM3D
READ (KLUN) SELF%LQML3D
READ (KLUN) SELF%LVWENO
READ (KLUN) ZTMP0
SELF%WENO_ALPHA = ZTMP0
READ (KLUN) SELF%LSLHD
READ (KLUN) SELF%LCOMAD
READ (KLUN) SELF%LHV
READ (KLUN) SELF%LVSPLIP
READ (KLUN) SELF%NCOUPLING
READ (KLUN) ZTMP0
SELF%REFVALC = ZTMP0
READ (KLUN) SELF%NCOUPLO4
READ (KLUN) SELF%LASSIM
READ (KLUN) SELF%IGRIBDV
READ (KLUN) SELF%IGRIBTC
READ (KLUN) SELF%IGRBFLXO
READ (KLUN) SELF%IGRBWDFLX
READ (KLUN) SELF%IGRBDDFLX
READ (KLUN) SELF%LDIFF
READ (KLUN) SELF%LCONV
READ (KLUN) SELF%LNEGFIX
READ (KLUN) SELF%LMASSFIX
READ (KLUN) ZTMP0
SELF%BETAMFBC = ZTMP0
READ (KLUN) ZTMP0
SELF%RMOLMASS = ZTMP0
READ (KLUN) ZTMP0
SELF%REFOLD = ZTMP0
READ (KLUN) ZTMP0
SELF%HENRYA = ZTMP0
READ (KLUN) ZTMP0
SELF%HENRYB = ZTMP0
END SUBROUTINE

SUBROUTINE ACDC_COPY_TYPE_GFL_NAML (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TYPE_GFL_NAML), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TYPE_GFL_NAML (SELF)

IMPLICIT NONE
TYPE (TYPE_GFL_NAML), TARGET :: SELF


END SUBROUTINE

SUBROUTINE ACDC_LEGACY_TYPE_GFL_NAML (SELF, KADDRL, KADDRU, KDIR)

IMPLICIT NONE
TYPE (TYPE_GFL_NAML), TARGET :: SELF
INTEGER*8, INTENT (IN) :: KADDRL
INTEGER*8, INTENT (IN) :: KADDRU
INTEGER, INTENT (IN) :: KDIR


END SUBROUTINE

SUBROUTINE ACDC_CRC64_TYPE_GFL_NAML (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TYPE_GFL_NAML), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CNAME), CDPATH//'%CNAME'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IGRBCODE), CDPATH//'%IGRBCODE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NREQIN), CDPATH//'%NREQIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REFVALI), CDPATH//'%REFVALI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LREQOUT), CDPATH//'%LREQOUT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LGPINGP), CDPATH//'%LGPINGP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMGRID), CDPATH//'%LMGRID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LGP), CDPATH//'%LGP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LSP), CDPATH//'%LSP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCDERS), CDPATH//'%LCDERS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LT9), CDPATH//'%LT9'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LT1), CDPATH//'%LT1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LT5), CDPATH//'%LT5'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPHY), CDPATH//'%LPHY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPT), CDPATH//'%LPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LTRAJIO), CDPATH//'%LTRAJIO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LDIAG), CDPATH//'%LDIAG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPC), CDPATH//'%LPC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LADV), CDPATH//'%LADV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LADV5), CDPATH//'%LADV5'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LINTLIN), CDPATH//'%LINTLIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LTDIABLIN), CDPATH//'%LTDIABLIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHORTURB), CDPATH//'%LHORTURB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LQM), CDPATH//'%LQM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LQMH), CDPATH//'%LQMH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LQM3D), CDPATH//'%LQM3D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LQML3D), CDPATH//'%LQML3D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LVWENO), CDPATH//'%LVWENO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%WENO_ALPHA), CDPATH//'%WENO_ALPHA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LSLHD), CDPATH//'%LSLHD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCOMAD), CDPATH//'%LCOMAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHV), CDPATH//'%LHV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LVSPLIP), CDPATH//'%LVSPLIP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCOUPLING), CDPATH//'%NCOUPLING'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REFVALC), CDPATH//'%REFVALC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCOUPLO4), CDPATH//'%NCOUPLO4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LASSIM), CDPATH//'%LASSIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IGRIBDV), CDPATH//'%IGRIBDV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IGRIBTC), CDPATH//'%IGRIBTC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IGRBFLXO), CDPATH//'%IGRBFLXO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IGRBWDFLX), CDPATH//'%IGRBWDFLX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IGRBDDFLX), CDPATH//'%IGRBDDFLX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LDIFF), CDPATH//'%LDIFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCONV), CDPATH//'%LCONV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEGFIX), CDPATH//'%LNEGFIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMASSFIX), CDPATH//'%LMASSFIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BETAMFBC), CDPATH//'%BETAMFBC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMOLMASS), CDPATH//'%RMOLMASS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REFOLD), CDPATH//'%REFOLD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%HENRYA), CDPATH//'%HENRYA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%HENRYB), CDPATH//'%HENRYB'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TYPE_GFL_NAML (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TYPE_GFL_NAML), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TYPE_GFL_NAML (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TYPE_GFL_NAML),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%CNAME) * LEN (SELF%CNAME)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CNAME'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IGRBCODE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IGRBCODE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NREQIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NREQIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REFVALI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REFVALI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LREQOUT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LREQOUT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LGPINGP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGPINGP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMGRID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMGRID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LGP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LSP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCDERS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCDERS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LT9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LT9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LT1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LT1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LT5)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LT5'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPHY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPHY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LTRAJIO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LTRAJIO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LDIAG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDIAG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LADV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LADV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LADV5)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LADV5'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LINTLIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LINTLIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LTDIABLIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LTDIABLIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHORTURB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHORTURB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LQM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LQM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LQMH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LQMH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LQM3D)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LQM3D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LQML3D)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LQML3D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LVWENO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LVWENO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%WENO_ALPHA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WENO_ALPHA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LSLHD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSLHD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCOMAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOMAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LVSPLIP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LVSPLIP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NCOUPLING)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCOUPLING'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REFVALC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REFVALC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NCOUPLO4)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCOUPLO4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LASSIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LASSIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IGRIBDV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IGRIBDV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IGRIBTC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IGRIBTC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IGRBFLXO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IGRBFLXO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IGRBWDFLX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IGRBWDFLX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IGRBDDFLX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IGRBDDFLX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LDIFF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDIFF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCONV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCONV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEGFIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEGFIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMASSFIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMASSFIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%BETAMFBC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%BETAMFBC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RMOLMASS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RMOLMASS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REFOLD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REFOLD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%HENRYA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%HENRYA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%HENRYB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%HENRYB'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
