MODULE UTIL_TPERTPAR_MOD

USE YOMPERTPAR, ONLY : TPERTPAR

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TPERTPAR
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TPERTPAR
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TPERTPAR
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TPERTPAR
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TPERTPAR
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TPERTPAR
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TPERTPAR
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TPERTPAR (SELF, KLUN)

IMPLICIT NONE
TYPE (TPERTPAR), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LPERTPAR
WRITE (KLUN) SELF%NSEED_MBR
WRITE (KLUN) SELF%LPERT_RMFDEPS
WRITE (KLUN) SELF%RMFDEPS_MAX
WRITE (KLUN) SELF%RMFDEPS_MIN
WRITE (KLUN) SELF%LPERT_RPRCON
WRITE (KLUN) SELF%RPRCON_MAX
WRITE (KLUN) SELF%RPRCON_MIN
WRITE (KLUN) SELF%LPERT_ENTRORG
WRITE (KLUN) SELF%ENTRORG_MAX
WRITE (KLUN) SELF%ENTRORG_MIN
WRITE (KLUN) SELF%LPERT_DETRPEN
WRITE (KLUN) SELF%DETRPEN_MAX
WRITE (KLUN) SELF%DETRPEN_MIN
WRITE (KLUN) SELF%LPERT_RTAUFAC
WRITE (KLUN) SELF%RTAUFAC_MAX
WRITE (KLUN) SELF%RTAUFAC_MIN
WRITE (KLUN) SELF%LPERT_CUDUV
WRITE (KLUN) SELF%CUDU_MOD
WRITE (KLUN) SELF%CUDV_MOD
WRITE (KLUN) SELF%CUDUV_MAX
WRITE (KLUN) SELF%CUDUV_MIN
WRITE (KLUN) SELF%LPERT_GCVRE
WRITE (KLUN) SELF%GCVRE_MAX
WRITE (KLUN) SELF%GCVRE_MIN
WRITE (KLUN) SELF%LPERT_GCVEZ
WRITE (KLUN) SELF%GCVEZ_MAX
WRITE (KLUN) SELF%GCVEZ_MIN
WRITE (KLUN) SELF%LPERT_GCVUV
WRITE (KLUN) SELF%GCVUV_MAX
WRITE (KLUN) SELF%GCVUV_MIN
WRITE (KLUN) SELF%LPERT_AKN
WRITE (KLUN) SELF%AKN_MAX
WRITE (KLUN) SELF%AKN_MIN
WRITE (KLUN) SELF%LPERT_ALD
WRITE (KLUN) SELF%ALD_MAX
WRITE (KLUN) SELF%ALD_MIN
WRITE (KLUN) SELF%LPERT_ALPHAT
WRITE (KLUN) SELF%ALPHAT_MAX
WRITE (KLUN) SELF%ALPHAT_MIN
WRITE (KLUN) SELF%LPERT_ALMAVE
WRITE (KLUN) SELF%ALMAVE_MAX
WRITE (KLUN) SELF%ALMAVE_MIN
WRITE (KLUN) SELF%LPERT_TFVL
WRITE (KLUN) SELF%TFVL_MIN
WRITE (KLUN) SELF%TFVL_MAX
WRITE (KLUN) SELF%LPERT_TFVR
WRITE (KLUN) SELF%TFVR_MIN
WRITE (KLUN) SELF%TFVR_MAX
WRITE (KLUN) SELF%LPERT_TFVS
WRITE (KLUN) SELF%TFVS_MIN
WRITE (KLUN) SELF%TFVS_MAX
WRITE (KLUN) SELF%LPERT_TFVI
WRITE (KLUN) SELF%TFVI_MIN
WRITE (KLUN) SELF%TFVI_MAX
WRITE (KLUN) SELF%LPERT_RAUTEFR
WRITE (KLUN) SELF%RAUTEFR_MIN
WRITE (KLUN) SELF%RAUTEFR_MAX
WRITE (KLUN) SELF%LPERT_RAUTEFS
WRITE (KLUN) SELF%RAUTEFS_MIN
WRITE (KLUN) SELF%RAUTEFS_MAX
WRITE (KLUN) SELF%LPERT_RQICRMIN
WRITE (KLUN) SELF%RQICRMIN_MIN
WRITE (KLUN) SELF%RQICRMIN_MAX
WRITE (KLUN) SELF%LPERT_RQICRMAX
WRITE (KLUN) SELF%RQICRMAX_MIN
WRITE (KLUN) SELF%RQICRMAX_MAX
WRITE (KLUN) SELF%LPERT_RQLCR
WRITE (KLUN) SELF%RQLCR_MIN
WRITE (KLUN) SELF%RQLCR_MAX
WRITE (KLUN) SELF%LPERT_RACCEF
WRITE (KLUN) SELF%RACCEF_MIN
WRITE (KLUN) SELF%RACCEF_MAX
WRITE (KLUN) SELF%LPERT_RRIMEF
WRITE (KLUN) SELF%RRIMEF_MIN
WRITE (KLUN) SELF%RRIMEF_MAX
WRITE (KLUN) SELF%LPERT_RAGGEF
WRITE (KLUN) SELF%RAGGEF_MIN
WRITE (KLUN) SELF%RAGGEF_MAX
WRITE (KLUN) SELF%LPERT_REVASX
WRITE (KLUN) SELF%REVASX_MIN
WRITE (KLUN) SELF%REVASX_MAX
WRITE (KLUN) SELF%LPERT_RDTFAC
WRITE (KLUN) SELF%RDTFAC_MIN
WRITE (KLUN) SELF%RDTFAC_MAX
WRITE (KLUN) SELF%LPERT_RHCRIT1
WRITE (KLUN) SELF%RHCRIT1_MIN
WRITE (KLUN) SELF%RHCRIT1_MAX
WRITE (KLUN) SELF%LPERT_GRHCMOD
WRITE (KLUN) SELF%GRHCMOD_MIN
WRITE (KLUN) SELF%GRHCMOD_MAX
WRITE (KLUN) SELF%LPERT_GWDCD
WRITE (KLUN) SELF%GWDCD_MIN
WRITE (KLUN) SELF%GWDCD_MAX
WRITE (KLUN) SELF%LPERT_GWDSE
WRITE (KLUN) SELF%GWDSE_MIN
WRITE (KLUN) SELF%GWDSE_MAX
WRITE (KLUN) SELF%LPERT_HOBST
WRITE (KLUN) SELF%HOBST_MIN
WRITE (KLUN) SELF%HOBST_MAX
WRITE (KLUN) SELF%LPERT_RRATSEA
WRITE (KLUN) SELF%RRATSEA_MIN
WRITE (KLUN) SELF%RRATSEA_MAX
WRITE (KLUN) SELF%LPERT_RRATLAND
WRITE (KLUN) SELF%RRATLAND_MIN
WRITE (KLUN) SELF%RRATLAND_MAX
WRITE (KLUN) SELF%LPERT_RRATDRI
WRITE (KLUN) SELF%RRATDRI_MAX
WRITE (KLUN) SELF%RRATDRI_MIN
WRITE (KLUN) SELF%LPERT_RCADECOR
WRITE (KLUN) SELF%RCADECOR_MAX
WRITE (KLUN) SELF%RCADECOR_MIN
WRITE (KLUN) SELF%LPERT_RCBDECOR
WRITE (KLUN) SELF%RCBDECOR_MAX
WRITE (KLUN) SELF%RCBDECOR_MIN
WRITE (KLUN) SELF%LPERT_RSIGMA2
WRITE (KLUN) SELF%RSIGMA2_MAX
WRITE (KLUN) SELF%RSIGMA2_MIN
WRITE (KLUN) SELF%LPERT_RFACDICE
WRITE (KLUN) SELF%RFACDICE_MAX
WRITE (KLUN) SELF%RFACDICE_MIN
WRITE (KLUN) SELF%LPERT_XRIMAX
WRITE (KLUN) SELF%XRIMAX_MIN
WRITE (KLUN) SELF%XRIMAX_MAX
WRITE (KLUN) SELF%LPERT_XFRACZ0
WRITE (KLUN) SELF%XFRACZ0_MIN
WRITE (KLUN) SELF%XFRACZ0_MAX
WRITE (KLUN) SELF%LPERT_OTADJS
WRITE (KLUN) SELF%OTADJS_MIN
WRITE (KLUN) SELF%OTADJS_MAX
WRITE (KLUN) SELF%LPERT_XENTR
WRITE (KLUN) SELF%XENTR_MIN
WRITE (KLUN) SELF%XENTR_MAX
WRITE (KLUN) SELF%LPERT_XATPERT
WRITE (KLUN) SELF%XATPERT_MIN
WRITE (KLUN) SELF%XATPERT_MAX
WRITE (KLUN) SELF%LPERT_XBTPERT
WRITE (KLUN) SELF%XBTPERT_MIN
WRITE (KLUN) SELF%XBTPERT_MAX
WRITE (KLUN) SELF%LPERT_XDTPERT
WRITE (KLUN) SELF%XDTPERT_MIN
WRITE (KLUN) SELF%XDTPERT_MAX
WRITE (KLUN) SELF%LPERT_XAW
WRITE (KLUN) SELF%XAW_MIN
WRITE (KLUN) SELF%XAW_MAX
WRITE (KLUN) SELF%LPERT_XBW
WRITE (KLUN) SELF%XBW_MIN
WRITE (KLUN) SELF%XBW_MAX
WRITE (KLUN) SELF%LPERT_RKFBTAU
WRITE (KLUN) SELF%RKFBTAU_MIN
WRITE (KLUN) SELF%RKFBTAU_MAX
WRITE (KLUN) SELF%LPERT_RKFBNBX
WRITE (KLUN) SELF%RKFBNBX_MIN
WRITE (KLUN) SELF%RKFBNBX_MAX
WRITE (KLUN) SELF%LPERT_XPERTFLUX
WRITE (KLUN) SELF%XPERTFLUX_MAX
WRITE (KLUN) SELF%XPERTFLUX_MIN
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TPERTPAR (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TPERTPAR), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%LPERTPAR
READ (KLUN) SELF%NSEED_MBR
READ (KLUN) SELF%LPERT_RMFDEPS
READ (KLUN) ZTMP0
SELF%RMFDEPS_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RMFDEPS_MIN = ZTMP0
READ (KLUN) SELF%LPERT_RPRCON
READ (KLUN) ZTMP0
SELF%RPRCON_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RPRCON_MIN = ZTMP0
READ (KLUN) SELF%LPERT_ENTRORG
READ (KLUN) ZTMP0
SELF%ENTRORG_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%ENTRORG_MIN = ZTMP0
READ (KLUN) SELF%LPERT_DETRPEN
READ (KLUN) ZTMP0
SELF%DETRPEN_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%DETRPEN_MIN = ZTMP0
READ (KLUN) SELF%LPERT_RTAUFAC
READ (KLUN) ZTMP0
SELF%RTAUFAC_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RTAUFAC_MIN = ZTMP0
READ (KLUN) SELF%LPERT_CUDUV
READ (KLUN) ZTMP0
SELF%CUDU_MOD = ZTMP0
READ (KLUN) ZTMP0
SELF%CUDV_MOD = ZTMP0
READ (KLUN) ZTMP0
SELF%CUDUV_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%CUDUV_MIN = ZTMP0
READ (KLUN) SELF%LPERT_GCVRE
READ (KLUN) ZTMP0
SELF%GCVRE_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVRE_MIN = ZTMP0
READ (KLUN) SELF%LPERT_GCVEZ
READ (KLUN) ZTMP0
SELF%GCVEZ_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVEZ_MIN = ZTMP0
READ (KLUN) SELF%LPERT_GCVUV
READ (KLUN) ZTMP0
SELF%GCVUV_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVUV_MIN = ZTMP0
READ (KLUN) SELF%LPERT_AKN
READ (KLUN) ZTMP0
SELF%AKN_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%AKN_MIN = ZTMP0
READ (KLUN) SELF%LPERT_ALD
READ (KLUN) ZTMP0
SELF%ALD_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%ALD_MIN = ZTMP0
READ (KLUN) SELF%LPERT_ALPHAT
READ (KLUN) ZTMP0
SELF%ALPHAT_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%ALPHAT_MIN = ZTMP0
READ (KLUN) SELF%LPERT_ALMAVE
READ (KLUN) ZTMP0
SELF%ALMAVE_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%ALMAVE_MIN = ZTMP0
READ (KLUN) SELF%LPERT_TFVL
READ (KLUN) ZTMP0
SELF%TFVL_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%TFVL_MAX = ZTMP0
READ (KLUN) SELF%LPERT_TFVR
READ (KLUN) ZTMP0
SELF%TFVR_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%TFVR_MAX = ZTMP0
READ (KLUN) SELF%LPERT_TFVS
READ (KLUN) ZTMP0
SELF%TFVS_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%TFVS_MAX = ZTMP0
READ (KLUN) SELF%LPERT_TFVI
READ (KLUN) ZTMP0
SELF%TFVI_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%TFVI_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RAUTEFR
READ (KLUN) ZTMP0
SELF%RAUTEFR_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RAUTEFR_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RAUTEFS
READ (KLUN) ZTMP0
SELF%RAUTEFS_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RAUTEFS_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RQICRMIN
READ (KLUN) ZTMP0
SELF%RQICRMIN_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RQICRMIN_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RQICRMAX
READ (KLUN) ZTMP0
SELF%RQICRMAX_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RQICRMAX_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RQLCR
READ (KLUN) ZTMP0
SELF%RQLCR_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RQLCR_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RACCEF
READ (KLUN) ZTMP0
SELF%RACCEF_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RACCEF_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RRIMEF
READ (KLUN) ZTMP0
SELF%RRIMEF_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RRIMEF_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RAGGEF
READ (KLUN) ZTMP0
SELF%RAGGEF_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RAGGEF_MAX = ZTMP0
READ (KLUN) SELF%LPERT_REVASX
READ (KLUN) ZTMP0
SELF%REVASX_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%REVASX_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RDTFAC
READ (KLUN) ZTMP0
SELF%RDTFAC_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RDTFAC_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RHCRIT1
READ (KLUN) ZTMP0
SELF%RHCRIT1_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RHCRIT1_MAX = ZTMP0
READ (KLUN) SELF%LPERT_GRHCMOD
READ (KLUN) ZTMP0
SELF%GRHCMOD_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GRHCMOD_MAX = ZTMP0
READ (KLUN) SELF%LPERT_GWDCD
READ (KLUN) ZTMP0
SELF%GWDCD_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDCD_MAX = ZTMP0
READ (KLUN) SELF%LPERT_GWDSE
READ (KLUN) ZTMP0
SELF%GWDSE_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDSE_MAX = ZTMP0
READ (KLUN) SELF%LPERT_HOBST
READ (KLUN) ZTMP0
SELF%HOBST_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%HOBST_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RRATSEA
READ (KLUN) ZTMP0
SELF%RRATSEA_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RRATSEA_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RRATLAND
READ (KLUN) ZTMP0
SELF%RRATLAND_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RRATLAND_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RRATDRI
READ (KLUN) ZTMP0
SELF%RRATDRI_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RRATDRI_MIN = ZTMP0
READ (KLUN) SELF%LPERT_RCADECOR
READ (KLUN) ZTMP0
SELF%RCADECOR_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RCADECOR_MIN = ZTMP0
READ (KLUN) SELF%LPERT_RCBDECOR
READ (KLUN) ZTMP0
SELF%RCBDECOR_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RCBDECOR_MIN = ZTMP0
READ (KLUN) SELF%LPERT_RSIGMA2
READ (KLUN) ZTMP0
SELF%RSIGMA2_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RSIGMA2_MIN = ZTMP0
READ (KLUN) SELF%LPERT_RFACDICE
READ (KLUN) ZTMP0
SELF%RFACDICE_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RFACDICE_MIN = ZTMP0
READ (KLUN) SELF%LPERT_XRIMAX
READ (KLUN) ZTMP0
SELF%XRIMAX_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%XRIMAX_MAX = ZTMP0
READ (KLUN) SELF%LPERT_XFRACZ0
READ (KLUN) ZTMP0
SELF%XFRACZ0_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%XFRACZ0_MAX = ZTMP0
READ (KLUN) SELF%LPERT_OTADJS
READ (KLUN) ZTMP0
SELF%OTADJS_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%OTADJS_MAX = ZTMP0
READ (KLUN) SELF%LPERT_XENTR
READ (KLUN) ZTMP0
SELF%XENTR_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%XENTR_MAX = ZTMP0
READ (KLUN) SELF%LPERT_XATPERT
READ (KLUN) ZTMP0
SELF%XATPERT_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%XATPERT_MAX = ZTMP0
READ (KLUN) SELF%LPERT_XBTPERT
READ (KLUN) ZTMP0
SELF%XBTPERT_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%XBTPERT_MAX = ZTMP0
READ (KLUN) SELF%LPERT_XDTPERT
READ (KLUN) ZTMP0
SELF%XDTPERT_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%XDTPERT_MAX = ZTMP0
READ (KLUN) SELF%LPERT_XAW
READ (KLUN) ZTMP0
SELF%XAW_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%XAW_MAX = ZTMP0
READ (KLUN) SELF%LPERT_XBW
READ (KLUN) ZTMP0
SELF%XBW_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%XBW_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RKFBTAU
READ (KLUN) ZTMP0
SELF%RKFBTAU_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RKFBTAU_MAX = ZTMP0
READ (KLUN) SELF%LPERT_RKFBNBX
READ (KLUN) ZTMP0
SELF%RKFBNBX_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RKFBNBX_MAX = ZTMP0
READ (KLUN) SELF%LPERT_XPERTFLUX
READ (KLUN) ZTMP0
SELF%XPERTFLUX_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%XPERTFLUX_MIN = ZTMP0
END SUBROUTINE

SUBROUTINE ACDC_COPY_TPERTPAR (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPERTPAR), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TPERTPAR (SELF)

IMPLICIT NONE
TYPE (TPERTPAR), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TPERTPAR (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TPERTPAR), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERTPAR), CDPATH//'%LPERTPAR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSEED_MBR), CDPATH//'%NSEED_MBR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RMFDEPS), CDPATH//'%LPERT_RMFDEPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMFDEPS_MAX), CDPATH//'%RMFDEPS_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMFDEPS_MIN), CDPATH//'%RMFDEPS_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RPRCON), CDPATH//'%LPERT_RPRCON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPRCON_MAX), CDPATH//'%RPRCON_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPRCON_MIN), CDPATH//'%RPRCON_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_ENTRORG), CDPATH//'%LPERT_ENTRORG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ENTRORG_MAX), CDPATH//'%ENTRORG_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ENTRORG_MIN), CDPATH//'%ENTRORG_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_DETRPEN), CDPATH//'%LPERT_DETRPEN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%DETRPEN_MAX), CDPATH//'%DETRPEN_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%DETRPEN_MIN), CDPATH//'%DETRPEN_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RTAUFAC), CDPATH//'%LPERT_RTAUFAC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTAUFAC_MAX), CDPATH//'%RTAUFAC_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTAUFAC_MIN), CDPATH//'%RTAUFAC_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_CUDUV), CDPATH//'%LPERT_CUDUV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CUDU_MOD), CDPATH//'%CUDU_MOD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CUDV_MOD), CDPATH//'%CUDV_MOD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CUDUV_MAX), CDPATH//'%CUDUV_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CUDUV_MIN), CDPATH//'%CUDUV_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_GCVRE), CDPATH//'%LPERT_GCVRE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCVRE_MAX), CDPATH//'%GCVRE_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCVRE_MIN), CDPATH//'%GCVRE_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_GCVEZ), CDPATH//'%LPERT_GCVEZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCVEZ_MAX), CDPATH//'%GCVEZ_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCVEZ_MIN), CDPATH//'%GCVEZ_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_GCVUV), CDPATH//'%LPERT_GCVUV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCVUV_MAX), CDPATH//'%GCVUV_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCVUV_MIN), CDPATH//'%GCVUV_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_AKN), CDPATH//'%LPERT_AKN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%AKN_MAX), CDPATH//'%AKN_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%AKN_MIN), CDPATH//'%AKN_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_ALD), CDPATH//'%LPERT_ALD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALD_MAX), CDPATH//'%ALD_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALD_MIN), CDPATH//'%ALD_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_ALPHAT), CDPATH//'%LPERT_ALPHAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALPHAT_MAX), CDPATH//'%ALPHAT_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALPHAT_MIN), CDPATH//'%ALPHAT_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_ALMAVE), CDPATH//'%LPERT_ALMAVE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALMAVE_MAX), CDPATH//'%ALMAVE_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALMAVE_MIN), CDPATH//'%ALMAVE_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_TFVL), CDPATH//'%LPERT_TFVL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TFVL_MIN), CDPATH//'%TFVL_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TFVL_MAX), CDPATH//'%TFVL_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_TFVR), CDPATH//'%LPERT_TFVR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TFVR_MIN), CDPATH//'%TFVR_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TFVR_MAX), CDPATH//'%TFVR_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_TFVS), CDPATH//'%LPERT_TFVS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TFVS_MIN), CDPATH//'%TFVS_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TFVS_MAX), CDPATH//'%TFVS_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_TFVI), CDPATH//'%LPERT_TFVI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TFVI_MIN), CDPATH//'%TFVI_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TFVI_MAX), CDPATH//'%TFVI_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RAUTEFR), CDPATH//'%LPERT_RAUTEFR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAUTEFR_MIN), CDPATH//'%RAUTEFR_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAUTEFR_MAX), CDPATH//'%RAUTEFR_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RAUTEFS), CDPATH//'%LPERT_RAUTEFS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAUTEFS_MIN), CDPATH//'%RAUTEFS_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAUTEFS_MAX), CDPATH//'%RAUTEFS_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RQICRMIN), CDPATH//'%LPERT_RQICRMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RQICRMIN_MIN), CDPATH//'%RQICRMIN_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RQICRMIN_MAX), CDPATH//'%RQICRMIN_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RQICRMAX), CDPATH//'%LPERT_RQICRMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RQICRMAX_MIN), CDPATH//'%RQICRMAX_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RQICRMAX_MAX), CDPATH//'%RQICRMAX_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RQLCR), CDPATH//'%LPERT_RQLCR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RQLCR_MIN), CDPATH//'%RQLCR_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RQLCR_MAX), CDPATH//'%RQLCR_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RACCEF), CDPATH//'%LPERT_RACCEF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RACCEF_MIN), CDPATH//'%RACCEF_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RACCEF_MAX), CDPATH//'%RACCEF_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RRIMEF), CDPATH//'%LPERT_RRIMEF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRIMEF_MIN), CDPATH//'%RRIMEF_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRIMEF_MAX), CDPATH//'%RRIMEF_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RAGGEF), CDPATH//'%LPERT_RAGGEF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAGGEF_MIN), CDPATH//'%RAGGEF_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAGGEF_MAX), CDPATH//'%RAGGEF_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_REVASX), CDPATH//'%LPERT_REVASX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REVASX_MIN), CDPATH//'%REVASX_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REVASX_MAX), CDPATH//'%REVASX_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RDTFAC), CDPATH//'%LPERT_RDTFAC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDTFAC_MIN), CDPATH//'%RDTFAC_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDTFAC_MAX), CDPATH//'%RDTFAC_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RHCRIT1), CDPATH//'%LPERT_RHCRIT1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHCRIT1_MIN), CDPATH//'%RHCRIT1_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHCRIT1_MAX), CDPATH//'%RHCRIT1_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_GRHCMOD), CDPATH//'%LPERT_GRHCMOD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GRHCMOD_MIN), CDPATH//'%GRHCMOD_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GRHCMOD_MAX), CDPATH//'%GRHCMOD_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_GWDCD), CDPATH//'%LPERT_GWDCD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GWDCD_MIN), CDPATH//'%GWDCD_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GWDCD_MAX), CDPATH//'%GWDCD_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_GWDSE), CDPATH//'%LPERT_GWDSE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GWDSE_MIN), CDPATH//'%GWDSE_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GWDSE_MAX), CDPATH//'%GWDSE_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_HOBST), CDPATH//'%LPERT_HOBST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%HOBST_MIN), CDPATH//'%HOBST_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%HOBST_MAX), CDPATH//'%HOBST_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RRATSEA), CDPATH//'%LPERT_RRATSEA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRATSEA_MIN), CDPATH//'%RRATSEA_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRATSEA_MAX), CDPATH//'%RRATSEA_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RRATLAND), CDPATH//'%LPERT_RRATLAND'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRATLAND_MIN), CDPATH//'%RRATLAND_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRATLAND_MAX), CDPATH//'%RRATLAND_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RRATDRI), CDPATH//'%LPERT_RRATDRI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRATDRI_MAX), CDPATH//'%RRATDRI_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRATDRI_MIN), CDPATH//'%RRATDRI_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RCADECOR), CDPATH//'%LPERT_RCADECOR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCADECOR_MAX), CDPATH//'%RCADECOR_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCADECOR_MIN), CDPATH//'%RCADECOR_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RCBDECOR), CDPATH//'%LPERT_RCBDECOR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCBDECOR_MAX), CDPATH//'%RCBDECOR_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCBDECOR_MIN), CDPATH//'%RCBDECOR_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RSIGMA2), CDPATH//'%LPERT_RSIGMA2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSIGMA2_MAX), CDPATH//'%RSIGMA2_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSIGMA2_MIN), CDPATH//'%RSIGMA2_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RFACDICE), CDPATH//'%LPERT_RFACDICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFACDICE_MAX), CDPATH//'%RFACDICE_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFACDICE_MIN), CDPATH//'%RFACDICE_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_XRIMAX), CDPATH//'%LPERT_XRIMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRIMAX_MIN), CDPATH//'%XRIMAX_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRIMAX_MAX), CDPATH//'%XRIMAX_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_XFRACZ0), CDPATH//'%LPERT_XFRACZ0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XFRACZ0_MIN), CDPATH//'%XFRACZ0_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XFRACZ0_MAX), CDPATH//'%XFRACZ0_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_OTADJS), CDPATH//'%LPERT_OTADJS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%OTADJS_MIN), CDPATH//'%OTADJS_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%OTADJS_MAX), CDPATH//'%OTADJS_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_XENTR), CDPATH//'%LPERT_XENTR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XENTR_MIN), CDPATH//'%XENTR_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XENTR_MAX), CDPATH//'%XENTR_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_XATPERT), CDPATH//'%LPERT_XATPERT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XATPERT_MIN), CDPATH//'%XATPERT_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XATPERT_MAX), CDPATH//'%XATPERT_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_XBTPERT), CDPATH//'%LPERT_XBTPERT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XBTPERT_MIN), CDPATH//'%XBTPERT_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XBTPERT_MAX), CDPATH//'%XBTPERT_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_XDTPERT), CDPATH//'%LPERT_XDTPERT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XDTPERT_MIN), CDPATH//'%XDTPERT_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XDTPERT_MAX), CDPATH//'%XDTPERT_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_XAW), CDPATH//'%LPERT_XAW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XAW_MIN), CDPATH//'%XAW_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XAW_MAX), CDPATH//'%XAW_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_XBW), CDPATH//'%LPERT_XBW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XBW_MIN), CDPATH//'%XBW_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XBW_MAX), CDPATH//'%XBW_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RKFBTAU), CDPATH//'%LPERT_RKFBTAU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKFBTAU_MIN), CDPATH//'%RKFBTAU_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKFBTAU_MAX), CDPATH//'%RKFBTAU_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_RKFBNBX), CDPATH//'%LPERT_RKFBNBX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKFBNBX_MIN), CDPATH//'%RKFBNBX_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKFBNBX_MAX), CDPATH//'%RKFBNBX_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LPERT_XPERTFLUX), CDPATH//'%LPERT_XPERTFLUX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XPERTFLUX_MAX), CDPATH//'%XPERTFLUX_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XPERTFLUX_MIN), CDPATH//'%XPERTFLUX_MIN'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TPERTPAR (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPERTPAR), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TPERTPAR (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TPERTPAR),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%LPERTPAR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERTPAR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSEED_MBR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSEED_MBR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RMFDEPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RMFDEPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RMFDEPS_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RMFDEPS_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RMFDEPS_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RMFDEPS_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RPRCON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RPRCON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RPRCON_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPRCON_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RPRCON_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPRCON_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_ENTRORG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_ENTRORG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ENTRORG_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ENTRORG_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ENTRORG_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ENTRORG_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_DETRPEN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_DETRPEN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%DETRPEN_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%DETRPEN_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%DETRPEN_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%DETRPEN_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RTAUFAC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RTAUFAC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RTAUFAC_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTAUFAC_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RTAUFAC_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTAUFAC_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_CUDUV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_CUDUV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CUDU_MOD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CUDU_MOD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CUDV_MOD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CUDV_MOD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CUDUV_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CUDUV_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CUDUV_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CUDUV_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_GCVRE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_GCVRE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GCVRE_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GCVRE_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GCVRE_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GCVRE_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_GCVEZ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_GCVEZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GCVEZ_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GCVEZ_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GCVEZ_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GCVEZ_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_GCVUV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_GCVUV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GCVUV_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GCVUV_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GCVUV_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GCVUV_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_AKN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_AKN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%AKN_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%AKN_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%AKN_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%AKN_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_ALD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_ALD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ALD_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ALD_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ALD_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ALD_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_ALPHAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_ALPHAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ALPHAT_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ALPHAT_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ALPHAT_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ALPHAT_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_ALMAVE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_ALMAVE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ALMAVE_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ALMAVE_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ALMAVE_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ALMAVE_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_TFVL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_TFVL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TFVL_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TFVL_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TFVL_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TFVL_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_TFVR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_TFVR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TFVR_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TFVR_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TFVR_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TFVR_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_TFVS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_TFVS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TFVS_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TFVS_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TFVS_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TFVS_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_TFVI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_TFVI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TFVI_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TFVI_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TFVI_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TFVI_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RAUTEFR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RAUTEFR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RAUTEFR_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAUTEFR_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RAUTEFR_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAUTEFR_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RAUTEFS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RAUTEFS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RAUTEFS_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAUTEFS_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RAUTEFS_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAUTEFS_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RQICRMIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RQICRMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RQICRMIN_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RQICRMIN_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RQICRMIN_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RQICRMIN_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RQICRMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RQICRMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RQICRMAX_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RQICRMAX_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RQICRMAX_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RQICRMAX_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RQLCR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RQLCR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RQLCR_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RQLCR_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RQLCR_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RQLCR_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RACCEF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RACCEF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RACCEF_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RACCEF_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RACCEF_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RACCEF_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RRIMEF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RRIMEF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRIMEF_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRIMEF_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRIMEF_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRIMEF_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RAGGEF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RAGGEF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RAGGEF_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAGGEF_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RAGGEF_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAGGEF_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_REVASX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_REVASX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REVASX_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REVASX_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REVASX_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REVASX_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RDTFAC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RDTFAC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDTFAC_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDTFAC_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDTFAC_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDTFAC_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RHCRIT1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RHCRIT1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RHCRIT1_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RHCRIT1_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RHCRIT1_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RHCRIT1_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_GRHCMOD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_GRHCMOD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GRHCMOD_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GRHCMOD_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GRHCMOD_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GRHCMOD_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_GWDCD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_GWDCD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GWDCD_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GWDCD_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GWDCD_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GWDCD_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_GWDSE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_GWDSE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GWDSE_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GWDSE_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GWDSE_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GWDSE_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_HOBST)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_HOBST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%HOBST_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%HOBST_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%HOBST_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%HOBST_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RRATSEA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RRATSEA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRATSEA_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRATSEA_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRATSEA_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRATSEA_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RRATLAND)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RRATLAND'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRATLAND_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRATLAND_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRATLAND_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRATLAND_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RRATDRI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RRATDRI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRATDRI_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRATDRI_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRATDRI_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRATDRI_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RCADECOR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RCADECOR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCADECOR_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCADECOR_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCADECOR_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCADECOR_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RCBDECOR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RCBDECOR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCBDECOR_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCBDECOR_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCBDECOR_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCBDECOR_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RSIGMA2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RSIGMA2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIGMA2_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIGMA2_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIGMA2_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIGMA2_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RFACDICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RFACDICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RFACDICE_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RFACDICE_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RFACDICE_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RFACDICE_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_XRIMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_XRIMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRIMAX_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRIMAX_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRIMAX_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRIMAX_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_XFRACZ0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_XFRACZ0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XFRACZ0_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFRACZ0_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XFRACZ0_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFRACZ0_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_OTADJS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_OTADJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%OTADJS_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%OTADJS_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%OTADJS_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%OTADJS_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_XENTR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_XENTR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XENTR_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XENTR_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XENTR_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XENTR_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_XATPERT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_XATPERT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XATPERT_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XATPERT_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XATPERT_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XATPERT_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_XBTPERT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_XBTPERT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XBTPERT_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBTPERT_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XBTPERT_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBTPERT_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_XDTPERT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_XDTPERT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XDTPERT_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XDTPERT_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XDTPERT_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XDTPERT_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_XAW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_XAW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XAW_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAW_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XAW_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAW_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_XBW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_XBW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XBW_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBW_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XBW_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBW_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RKFBTAU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RKFBTAU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RKFBTAU_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RKFBTAU_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RKFBTAU_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RKFBTAU_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_RKFBNBX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_RKFBNBX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RKFBNBX_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RKFBNBX_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RKFBNBX_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RKFBNBX_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LPERT_XPERTFLUX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPERT_XPERTFLUX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XPERTFLUX_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XPERTFLUX_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XPERTFLUX_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XPERTFLUX_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
