SUBMODULE (MODD_TURB_N) MODD_TURB_N_TURB_T_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_TURB_T (SELF)

IMPLICIT NONE
CLASS (TURB_T), TARGET :: SELF
LOGICAL :: LXDISS, LXDYP, LXLEM, LXSSRFL_C, LXSSTFL_C, LXSSUFL_C, LXSSVFL_C, LXTHP, LXTR

END SUBROUTINE

END SUBMODULE
