#!/usr/bin/perl -w

use Data::Dumper;
use FileHandle;
use FindBin qw ($Bin);

use lib "$Bin/fxtran-merge";

use lib '/home/marguina/perl5/lib/perl5';
use lib '/home/marguina/perl5/lib/perl5/x86_64-linux-gnu-thread-multi';

use fxtran;
use fxtran::parser;
use fxtran::xpath;

use strict;

use Fxtran::Beautifier;

my ($base, $local, $remote, $merged) = @ARGV;

&Fxtran::Beautifier::expand ($_) for ($base, $local, $remote);

&Fxtran::Beautifier::runCommand (cmd => ['kdiff3', -o => $merged, $base, $local, $remote], debug => 0);

&Fxtran::Beautifier::repack ($merged);

exit (0);

