#!/usr/bin/perl -w

use Data::Dumper;
use Getopt::Long;
use FileHandle;
use FindBin qw ($Bin);

use lib "$Bin/fxtran-merge";

use lib '/home/marguina/perl5/lib/perl5';
use lib '/home/marguina/perl5/lib/perl5/x86_64-linux-gnu-thread-multi';

use fxtran;
use fxtran::parser;
use fxtran::xpath;

use strict;

use Fxtran::Formatter;
use Fxtran::MergeTool;

my %opts = qw (mergetool kdiff3 simplify-associate-blocks 1);
my @opts_f = qw (simplify-associate-blocks);
my @opts_s = qw (mergetool);

&GetOptions
(
  (map { ("$_!", \$opts{$_}) } @opts_f),
  (map { ("$_=s", \$opts{$_}) } @opts_s),
);

my ($base, $local, $remote, $merged) = @ARGV;

'Fxtran::Formatter'->prepareFileForMerging ($_, %opts) 
  for ($base, $local, $remote);

'Fxtran::MergeTool'->merge ($base, $local, $remote, $merged, %opts);

'Fxtran::Formatter'->repackStatementsAfterMerge ($merged, %opts);

exit (0);

