INTERFACE

SUBROUTINE RECMWF_PARALLEL (YDDIMV, YDMODEL, YDCPG_OPTS, YDCPG_BNDS, KOZOCL, KMACCAERO, KAERO&
&, YD_PALBD, YD_PALBP, YD_PAPRS, YD_PAPRSF, YD_PNEB, YD_PQO3, YD_PQCO2, YD_PQCH4, YD_PQN2O,&
& YD_PQNO2, YD_PQC11, YD_PQC12, YD_PQC22, YD_PQCL4, YD_PAER, YD_PAERO, YD_PAEROCPL, YD_PDELP&
&, YD_PEMIS, YD_PMU0M, YD_PQ, YD_PQSAT, YD_PQICE, YD_PQLIQ, YD_PS, YD_PRR, YD_PLSM, YD_PT, YD_PTS&
&, YD_PEMTD, YD_PEMTU, YD_PTRSO, YD_PLWFC, YD_PLWFT, YD_PSWFC, YD_PSWFT, YD_PSFSWDIR, YD_PSFSWDIF&
&, YD_PFSDNN, YD_PFSDNV, YD_PCTRSO, YD_PCEMTR, YD_PTRSOD, YD_PTRSODIR, YD_PTRSODIF, YD_PPIZA_DST&
&, YD_PCGA_DST, YD_PTAUREL_DST, YD_PAERINDS, YD_PGELAM, YD_PGEMU, YD_PSWDIR, YD_PSWDIF, YD_PMU0LU&
&, YD_PALB, YD_PVRMOON, YD_PCLDROP, YSPP_RSWINHF, YSPP_RLWINHF)
USE TYPE_MODEL,ONLY:MODEL
USE YOMDIMV,ONLY:TDIMV
USE SPP_MOD_TYPE,ONLY:APPLY_SPP, TSPP_CONFIG_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE PARKIND1
USE FXTRAN_ACDC_ARRAY_COPY_MOD
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE
TYPE (TDIMV), INTENT (IN)::YDDIMV
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
INTEGER (KIND=JPIM), INTENT (IN)::KOZOCL
INTEGER (KIND=JPIM), INTENT (IN)::KMACCAERO
INTEGER (KIND=JPIM), INTENT (IN)::KAERO
CLASS (FIELD_2RB), POINTER :: YD_PGELAM
CLASS (FIELD_2RB), POINTER :: YD_PGEMU
CLASS (FIELD_3RB), POINTER :: YD_PALBD
CLASS (FIELD_3RB), POINTER :: YD_PALBP
CLASS (FIELD_3RB), POINTER :: YD_PAPRS
CLASS (FIELD_3RB), POINTER :: YD_PAPRSF
CLASS (FIELD_3RB), POINTER :: YD_PNEB
CLASS (FIELD_3RB), POINTER :: YD_PQO3
CLASS (FIELD_3RB), POINTER :: YD_PQCO2
CLASS (FIELD_3RB), POINTER :: YD_PQCH4
CLASS (FIELD_3RB), POINTER :: YD_PQN2O
CLASS (FIELD_3RB), POINTER :: YD_PQNO2
CLASS (FIELD_3RB), POINTER :: YD_PQC11
CLASS (FIELD_3RB), POINTER :: YD_PQC12
CLASS (FIELD_3RB), POINTER :: YD_PQC22
CLASS (FIELD_3RB), POINTER :: YD_PQCL4
CLASS (FIELD_4RB), POINTER :: YD_PAER
CLASS (FIELD_4RB), POINTER :: YD_PAERO
CLASS (FIELD_5RB), POINTER :: YD_PAEROCPL
CLASS (FIELD_3RB), POINTER :: YD_PAERINDS
CLASS (FIELD_3RB), POINTER :: YD_PDELP
CLASS (FIELD_2RB), POINTER :: YD_PEMIS
CLASS (FIELD_2RB), POINTER :: YD_PMU0M
CLASS (FIELD_3RB), POINTER :: YD_PQ
CLASS (FIELD_3RB), POINTER :: YD_PQSAT
CLASS (FIELD_3RB), POINTER :: YD_PQICE
CLASS (FIELD_3RB), POINTER :: YD_PQLIQ
CLASS (FIELD_2RB), POINTER :: YD_PLSM
CLASS (FIELD_3RB), POINTER :: YD_PT
CLASS (FIELD_2RB), POINTER :: YD_PTS
CLASS (FIELD_4RB), POINTER :: YD_PPIZA_DST
CLASS (FIELD_4RB), POINTER :: YD_PCGA_DST
CLASS (FIELD_4RB), POINTER :: YD_PTAUREL_DST
CLASS (FIELD_3RB), POINTER :: YD_PEMTD
CLASS (FIELD_3RB), POINTER :: YD_PEMTU
CLASS (FIELD_3RB), POINTER :: YD_PTRSO
CLASS (FIELD_3RB), POINTER :: YD_PCTRSO
CLASS (FIELD_3RB), POINTER :: YD_PCEMTR
CLASS (FIELD_2RB), POINTER :: YD_PTRSOD
CLASS (FIELD_3RB), POINTER :: YD_PLWFC
CLASS (FIELD_4RB), POINTER :: YD_PLWFT
CLASS (FIELD_3RB), POINTER :: YD_PSWFC
CLASS (FIELD_4RB), POINTER :: YD_PSWFT
CLASS (FIELD_3RB), POINTER :: YD_PSFSWDIR
CLASS (FIELD_3RB), POINTER :: YD_PSFSWDIF
CLASS (FIELD_2RB), POINTER :: YD_PFSDNN
CLASS (FIELD_2RB), POINTER :: YD_PFSDNV
CLASS (FIELD_3RB), POINTER :: YD_PTRSODIR
CLASS (FIELD_3RB), POINTER :: YD_PTRSODIF
CLASS (FIELD_3RB), POINTER :: YD_PS
CLASS (FIELD_3RB), POINTER :: YD_PRR
CLASS (FIELD_3RB), POINTER :: YD_PSWDIR
CLASS (FIELD_3RB), POINTER :: YD_PSWDIF
CLASS (FIELD_2RB), POINTER :: YD_PMU0LU
CLASS (FIELD_2RB), POINTER :: YD_PALB
CLASS (FIELD_2RB), POINTER :: YD_PVRMOON
CLASS (FIELD_3RB), POINTER, OPTIONAL  :: YD_PCLDROP
TYPE (TSPP_CONFIG_TYPE), INTENT (INOUT), OPTIONAL::YSPP_RLWINHF
TYPE (TSPP_CONFIG_TYPE), INTENT (INOUT), OPTIONAL::YSPP_RSWINHF
END SUBROUTINE RECMWF_PARALLEL


END INTERFACE
