INTERFACE

SUBROUTINE CUADJTQ &
& (YDTHF, YDCST, YDEPHLI,KIDIA,    KFDIA,    KLON,    KLEV,     KK,&
&  PSP,      PT,       PQ,      LDFLAG,   KCALL,   LDOFLAG)
USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMCST   , ONLY : TCST
USE YOETHF   , ONLY : TTHF
USE YOEPHLI  , ONLY : TEPHLI
IMPLICIT NONE
TYPE(TTHF)         ,INTENT(IN)               :: YDTHF
TYPE(TCST)         ,INTENT(IN)               :: YDCST
TYPE(TEPHLI)       ,INTENT(IN)               :: YDEPHLI
INTEGER(KIND=JPIM) ,INTENT(IN)               :: KIDIA
INTEGER(KIND=JPIM) ,INTENT(IN)               :: KFDIA
INTEGER(KIND=JPIM) ,INTENT(IN)               :: KLON
INTEGER(KIND=JPIM) ,INTENT(IN)               :: KLEV
INTEGER(KIND=JPIM) ,INTENT(IN)               :: KK
REAL(KIND=JPRB)    ,INTENT(IN)               :: PSP(KLON)
REAL(KIND=JPRB)    ,INTENT(INOUT)            :: PT(KLON,KLEV)
REAL(KIND=JPRB)    ,INTENT(INOUT)            :: PQ(KLON,KLEV)
LOGICAL            ,INTENT(IN)               :: LDFLAG(KLON)
INTEGER(KIND=JPIM) ,INTENT(IN)               :: KCALL
LOGICAL            ,INTENT(IN)    ,OPTIONAL  :: LDOFLAG(KLON)
END SUBROUTINE CUADJTQ


SUBROUTINE CUADJTQ_OPENACC (YDTHF, YDCST, YDEPHLI, KIDIA, KFDIA, KLON&
&, KLEV, KK, PSP, PT, PQ, LDFLAG, KCALL, LDOFLAG, YDSTACK)
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOEPHLI,ONLY:TEPHLI
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
!$ACC ROUTINE (CUADJTQ_OPENACC) SEQ
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KK
REAL (KIND=JPRB), INTENT (IN)::PSP (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQ (KLON, KLEV)
LOGICAL, INTENT (IN)::LDFLAG (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCALL
LOGICAL, INTENT (IN), OPTIONAL::LDOFLAG (KLON)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK

END SUBROUTINE CUADJTQ_OPENACC






END INTERFACE
