SUBROUTINE CUDTDQN_SINGLE_COLUMN (YDTHF, YDCST, YDEPHLI, YDPHNC, YDECUMF, YDEPHY, KIDIA, KFDIA&
&, KLON, KLEV, KTOPM2, KTYPE, KCTOP, KDTOP, LDTDKMF, LDCUM, LDDRAF, PTSPHY, PAPH, PAP, PGEOH&
&, PGEO, PTEN, PTENH, PQEN, PQENH, PQSEN, PLGLAC, PLUDE, PLUDELI, PSNDE, PMFU, PMFD, PMFUS&
&, PMFDS, PMFUQ, PMFDQ, PMFUL, PDMFUP, PDPMEL, PTENT, PTENQ, PENTH, YDSTACK)
!$acc routine (CUDTDQN_SINGLE_COLUMN) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE YOEPHY,ONLY:TEPHY
USE YOEPHLI,ONLY:TEPHLI
USE YOPHNC,ONLY:TPHNC
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
TYPE (TEPHY), INTENT (IN)::YDEPHY
TYPE (TPHNC), INTENT (IN)::YDPHNC
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTOPM2
INTEGER (KIND=JPIM), INTENT (IN)::KTYPE (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KDTOP (KLON)
LOGICAL, INTENT (INOUT)::LDCUM (KLON)
LOGICAL, INTENT (IN)::LDDRAF (KLON)
LOGICAL, INTENT (IN)::LDTDKMF
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PLGLAC (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLUDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLUDELI (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (INOUT)::PSNDE (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (IN)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFDS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFDQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDMFUP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDPMEL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PENTH (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK
LOGICAL::LLTEST

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::IM
INTEGER (KIND=JPIM)::IK
INTEGER (KIND=JPIM)::JK

REAL (KIND=JPRB)::ZQ
REAL (KIND=JPRB)::ZS
REAL (KIND=JPRB)::ZGH
REAL (KIND=JPRB)::ZGS
REAL (KIND=JPRB)::ZGQ
REAL (KIND=JPRB)::ZZP
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZALV
REAL (KIND=JPRB)::ZORCPD
REAL (KIND=JPRB)::ZIMP
REAL (KIND=JPRB)::ZTSPHY

REAL (KIND=JPRB)::ZADVW 
temp (REAL (KIND=JPRB), ZMFDQ, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFDS, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUQ, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZMFUS, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZDP, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDQDT, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZDTDT, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZR2, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZR1, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZB, (KLON, KLEV))
temp (LOGICAL, LLCUMBAS, (KLON, KLEV))

#include "cubidiag_single_column.intfb.h"
#include "fcttre.func.h"

YLSTACK = YDSTACK

alloc (ZMFDQ)
alloc (ZMFDS)
alloc (ZMFUQ)
alloc (ZMFUS)
alloc (ZDP)
alloc (ZDQDT)
alloc (ZDTDT)
alloc (ZR2)
alloc (ZR1)
alloc (ZB)
alloc (LLCUMBAS)



JLON = KIDIA


ZIMP=1.0_JPRB-YDECUMF%RMFSOLTQ
ZTSPHY=1.0_JPRB/PTSPHY
ZORCPD=1.0_JPRB/YDCST%RCPD

ZADVW =0.0_JPRB

IF (KTYPE (JLON)==1)  THEN
    ZADVW =YDECUMF%RMFADVW
ENDIF



DO JK=1, KLEV
  
  PENTH (JLON, JK)=0.0_JPRB
  
ENDDO



IF (KTYPE (JLON)/=1.AND.YDEPHLI%LPHYLIN)  THEN
    LDCUM (JLON)=.FALSE.
ENDIF


LLTEST=(.NOT.YDEPHY%LEPCLD.AND..NOT.YDPHNC%LENCLD2).OR.(YDEPHLI%LPHYLIN.AND..NOT.YDPHNC%LENCLD2)

IF (LLTEST) THEN

  DO JK=1, KLEV
    
    PLUDE (JLON, JK)=0.0_JPRB
    PLUDELI (JLON, JK, 1)=0.0_JPRB
    PLUDELI (JLON, JK, 2)=0.0_JPRB
  
  ENDDO

ENDIF


DO JK=1, KLEV

  

  IF (LDCUM (JLON)) THEN
    ZDP (JLON, JK)=YDCST%RG/(PAPH (JLON, JK+1)-PAPH (JLON, JK))
    ZMFUS (JLON, JK)=PMFUS (JLON, JK)
    ZMFDS (JLON, JK)=PMFDS (JLON, JK)
    ZMFUQ (JLON, JK)=PMFUQ (JLON, JK)
    ZMFDQ (JLON, JK)=PMFDQ (JLON, JK)
  ENDIF

  
ENDDO


IF (YDECUMF%RMFSOLTQ>0.0_JPRB) THEN

  DO JK=KTOPM2, KLEV
    IK=JK-1

    

    IF (LDCUM (JLON).AND.JK>=KCTOP (JLON)-1) THEN
      ZGQ=(PQENH (JLON, JK)-PQEN (JLON, IK))/PQSEN (JLON, JK)
      ZGH=YDCST%RCPD*PTEN (JLON, JK)+PGEO (JLON, JK)
      ZGS=(YDCST%RCPD*(PTENH (JLON, JK)-PTEN (JLON, IK))+PGEOH (JLON, JK)-PGEO (JLON, IK))/ZGH
      ZS=YDCST%RCPD*(ZIMP*PTEN (JLON, IK)+ZGS*PTEN (JLON, JK))+PGEO (JLON, IK)+ZGS*PGEO (JLON, JK)
      ZQ=ZIMP*PQEN (JLON, IK)+ZGQ*PQSEN (JLON, JK)
      ZMFUS (JLON, JK)=PMFUS (JLON, JK)-PMFU (JLON, JK)*ZS
      ZMFUQ (JLON, JK)=PMFUQ (JLON, JK)-PMFU (JLON, JK)*ZQ

      IF (LDDRAF (JLON).AND.JK>=KDTOP (JLON)) THEN
        ZMFDS (JLON, JK)=PMFDS (JLON, JK)-PMFD (JLON, JK)*ZS
        ZMFDQ (JLON, JK)=PMFDQ (JLON, JK)-PMFD (JLON, JK)*ZQ
      ENDIF

    ENDIF

  
  ENDDO

ENDIF


DO JK=KTOPM2, KLEV

  IF (JK<KLEV) THEN

    

    IF (LDCUM (JLON)) THEN

      IF (YDEPHLI%LPHYLIN) THEN
        ZTARG=PTEN (JLON, JK)
        ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
        ZALV=ZOEALFA*YDCST%RLVTT+(1.0_JPRB-ZOEALFA)*YDCST%RLSTT
      ELSE
        ZALV=FOELHMCU (PTEN (JLON, JK))
      ENDIF


      IF (LDTDKMF) THEN
        ZDTDT (JLON, JK)=ZDP (JLON, JK)*ZORCPD*(ZMFUS (JLON, JK+1)-ZMFUS (JLON, JK)+ZMFDS (JLON&
        &, JK+1)-ZMFDS (JLON, JK)+YDCST%RLMLT*PLGLAC (JLON, JK)-YDCST%RLMLT*PDPMEL (JLON, JK)&
        &-ZALV*(PMFUL (JLON, JK+1)-PMFUL (JLON, JK)-PLUDE (JLON, JK)-PDMFUP (JLON, JK)))
        ZDQDT (JLON, JK)=ZDP (JLON, JK)*(ZMFUQ (JLON, JK+1)-ZMFUQ (JLON, JK)+ZMFDQ (JLON, JK+1)-ZMFDQ&
        & (JLON, JK)+PMFUL (JLON, JK+1)-PMFUL (JLON, JK)-PLUDE (JLON, JK)-PDMFUP (JLON, JK))
      ELSE
        ZDTDT (JLON, JK)=ZDP (JLON, JK)*ZORCPD*(ZMFUS (JLON, JK+1)-ZMFUS (JLON, JK)+ZMFDS&
        & (JLON, JK+1)-ZMFDS (JLON, JK)+YDCST%RLMLT*PLGLAC (JLON, JK)-YDCST%RLMLT*PDPMEL&
        & (JLON, JK)-ZALV*(PMFUL (JLON, JK+1)-PMFUL (JLON, JK)-PDMFUP (JLON, JK))+YDCST&
        &%RLVTT*PLUDELI (JLON, JK, 1)+YDCST%RLSTT*PLUDELI (JLON, JK, 2))
        ZDQDT (JLON, JK)=ZDP (JLON, JK)*(ZMFUQ (JLON, JK+1)-ZMFUQ (JLON, JK)+ZMFDQ&
        & (JLON, JK+1)-ZMFDQ (JLON, JK)+PMFUL (JLON, JK+1)-PMFUL (JLON, JK)-PLUDE &
        &(JLON, JK)-PDMFUP (JLON, JK)-PSNDE (JLON, JK, 1)-PSNDE (JLON, JK, 2))
      ENDIF

    ENDIF

  
  ELSE

    

    IF (LDCUM (JLON)) THEN

      IF (YDEPHLI%LPHYLIN) THEN
        ZTARG=PTEN (JLON, JK)
        ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
        ZALV=ZOEALFA*YDCST%RLVTT+(1.0_JPRB-ZOEALFA)*YDCST%RLSTT
      ELSE
        ZALV=FOELHMCU (PTEN (JLON, JK))
      ENDIF

      ZDTDT (JLON, JK)=-ZDP (JLON, JK)*ZORCPD*(ZMFUS (JLON, JK)+ZMFDS (JLON, JK)+YDCST&
      &%RLMLT*PDPMEL (JLON, JK)-ZALV*(PMFUL (JLON, JK)+PDMFUP (JLON, JK)))
      ZDQDT (JLON, JK)=-ZDP (JLON, JK)*(ZMFUQ (JLON, JK)+ZMFDQ&
      & (JLON, JK)+(PMFUL (JLON, JK)+PDMFUP (JLON, JK)))
    ENDIF

  
  ENDIF

ENDDO


IF (YDECUMF%RMFSOLTQ==0.0_JPRB) THEN

  DO JK=KTOPM2, KLEV

    

    IF (LDCUM (JLON)) THEN
      PTENT (JLON, JK)=PTENT (JLON, JK)+ZDTDT (JLON, JK)
      PTENQ (JLON, JK)=PTENQ (JLON, JK)+ZDQDT (JLON, JK)
      PENTH (JLON, JK)=ZDTDT (JLON, JK)*YDCST%RCPD
    ENDIF

  
  ENDDO

ELSE
  LLCUMBAS (JLON,:)=.FALSE.
  ZB (JLON,:)=1.0_JPRB
  ZMFUS (JLON,:)=0.0_JPRB

  DO JK=KTOPM2, KLEV
    IK=JK+1
    IM=JK-1
    
    LLCUMBAS (JLON, JK)=LDCUM (JLON).AND.JK>=KCTOP (JLON)-1

    IF (LLCUMBAS (JLON, JK)) THEN
      ZZP=YDECUMF%RMFSOLTQ*ZDP (JLON, JK)*PTSPHY
      ZMFUS (JLON, JK)=-ZZP*(PMFU (JLON, JK)+PMFD (JLON, JK))

      IF (JK<KLEV) THEN
        ZB (JLON, JK)=1.0_JPRB+ZZP*(PMFU (JLON, IK)+PMFD (JLON, IK))
      ELSE
        ZB (JLON, JK)=1.0_JPRB
      ENDIF


      IF (LDTDKMF) THEN
        ZDTDT (JLON, JK)=ZDTDT (JLON, JK)*PTSPHY+PTEN (JLON, JK)
        ZDQDT (JLON, JK)=ZDQDT (JLON, JK)*PTSPHY+PQEN (JLON, JK)
      ELSE
        ZZP=YDCST%RG*(PMFU (JLON, JK)+YDECUMF%RMFADVWDD*PMFD (JLON&
        &, JK))/(PAP (JLON, JK)-PAP (JLON, IM))*PTSPHY*ZADVW 
        ZS=ZZP*(PTEN (JLON, IM)-PTEN (JLON, JK)+ZORCPD*(PGEO (JLON, IM)-PGEO (JLON, JK)))
        ZQ=ZZP*(PQEN (JLON, IM)-PQEN (JLON, JK))
        ZDTDT (JLON, JK)=(ZDTDT (JLON, JK)+PTENT (JLON, JK)*YDECUMF%RMFSOLRHS)*PTSPHY+PTEN (JLON, JK)-ZS
        ZDQDT (JLON, JK)=(ZDQDT (JLON, JK)+PTENQ (JLON, JK)*YDECUMF%RMFSOLRHS)*PTSPHY+PQEN (JLON, JK)-ZQ
      ENDIF

    ENDIF

  
  ENDDO

  CALL CUBIDIAG_SINGLE_COLUMN (KIDIA, KFDIA, KLON, KLEV, KCTOP&
  &, LLCUMBAS, ZMFUS, ZB, ZDTDT, ZR1, YDSTACK=YLSTACK)
  CALL CUBIDIAG_SINGLE_COLUMN (KIDIA, KFDIA, KLON, KLEV, KCTOP&
  &, LLCUMBAS, ZMFUS, ZB, ZDQDT, ZR2, YDSTACK=YLSTACK)

  DO JK=KTOPM2, KLEV

    

    IF (LLCUMBAS (JLON, JK)) THEN

      IF (LDTDKMF) THEN
        PTENT (JLON, JK)=PTENT (JLON, JK)+(ZR1 (JLON, JK)-PTEN (JLON, JK))*ZTSPHY
        PTENQ (JLON, JK)=PTENQ (JLON, JK)+(ZR2 (JLON, JK)-PQEN (JLON, JK))*ZTSPHY
      ELSE
        PTENT (JLON, JK)=PTENT (JLON, JK)*(1.0_JPRB-YDECUMF%RMFSOLRHS&
        &)+(ZR1 (JLON, JK)-PTEN (JLON, JK))*ZTSPHY
        PTENQ (JLON, JK)=PTENQ (JLON, JK)*(1.0_JPRB-YDECUMF%RMFSOLRHS&
        &)+(ZR2 (JLON, JK)-PQEN (JLON, JK))*ZTSPHY
      ENDIF

      PENTH (JLON, JK)=(ZR1 (JLON, JK)-PTEN (JLON, JK))*ZTSPHY
    ENDIF

  
  ENDDO

ENDIF



ENDSUBROUTINE CUDTDQN_SINGLE_COLUMN

