INTERFACE
SUBROUTINE SATUR_SINGLE_COLUMN (YDTHF, YDCST, KIDIA, KFDIA, KLON&
&, KTDIA, KLEV, LDPHYLIN, PAPRSF, PT, PQSAT, KFLAG, YDSTACK)
!$acc routine (SATUR_SINGLE_COLUMN) seq
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE STACK_MOD
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
LOGICAL, INTENT (IN)::LDPHYLIN
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQSAT (KLON, KLEV)
INTEGER (KIND=JPIM), INTENT (IN)::KFLAG
TYPE(STACK) :: YDSTACK
ENDSUBROUTINE SATUR_SINGLE_COLUMN

END INTERFACE
