INTERFACE
SUBROUTINE VERDER_OPENACC (KPROMA, KST, KEND, KLEVIN, KLEVOUT, PDERI, PIN, POUT, YDSTACK)
!$ACC ROUTINE (VERDER_OPENACC) SEQ
USE PARKIND1,ONLY:JPRD, JPIM, JPRB
USE STACK_MOD
USE ABOR1_ACC_MOD
IMPLICIT NONE
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KLEVIN
INTEGER (KIND=JPIM), INTENT (IN)::KLEVOUT
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
REAL (KIND=JPRD), INTENT (IN)::PDERI (KLEVOUT, KLEVIN)
REAL (KIND=JPRB), INTENT (IN), TARGET::PIN (KPROMA, KLEVIN)
REAL (KIND=JPRB), INTENT (OUT), TARGET::POUT (KPROMA, KLEVOUT)
TYPE(STACK), INTENT (IN) :: YDSTACK
ENDSUBROUTINE VERDER_OPENACC


END INTERFACE
