SUBROUTINE SIGAM_NH_SINGLEBLOCK (YDCST, YDGEOMETRY, YDDYN&
&, KLON, KLEV, KIDIA, KFDIA, PD, PRNH, LDACC)
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE YOMCST,ONLY:TCST
USE YOMDYN,ONLY:TDYN
USE FXTRAN_ACDC_STACK_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (TDYN), INTENT (IN)::YDDYN
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (OUT)::PD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRNH (KLON, KLEV)
LOGICAL, INTENT (IN) :: LDACC
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
CHARACTER (LEN=4)::CLOPER
REAL (KIND=JPRB)::ZSPHI (KLON, 0:KLEV+1)
REAL (KIND=JPRB)::ZOUT (KLON, KLEV)
REAL (KIND=JPRB)::ZSPHIX (KLON)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
#include "verdisint.intfb.h"
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK

!$ACC DATA &
!$ACC&CREATE (ZOUT, ZSPHI, ZSPHIX) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (PD, PRNH, YDCST, YDDYN, YDGEOMETRY) 

IF (LHOOK) CALL DR_HOOK ('SIGAM_NH_SINGLEBLOCK', 0, ZHOOK_HANDLE)





IF (YDGEOMETRY%YRVERT_GEOM%YRCVER%LVERTFE) THEN
  CLOPER='IBOT'

  IF (YDGEOMETRY%YRVERT_GEOM%YRCVER%LVFE_COMPATIBLE)  THEN
    CLOPER='INTG'
  ENDIF

  
  !$ACC PARALLEL LOOP GANG VECTOR &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, KFDIA

    DO JLEV=1, KLEV
      
      ZSPHI (JLON, JLEV)=-YDCST%RD*(YDDYN%SITRM (JLEV)/YDDYN%SITR)*(PRNH (JLON, JLEV&
      &)*YDDYN%SILNPR(JLEV)*YDGEOMETRY%YRVERT_GEOM%YRVETA%VFE_RDETAH (JLEV))
    
    ENDDO

    ZSPHI (JLON, 0)=0.0_JPRB
    ZSPHI (JLON, KLEV+1)=0.0_JPRB
  ENDDO

  
  
  CALL VERDISINT_SINGLEBLOCK (YDGEOMETRY%YRVERT_GEOM%YRVFE, YDGEOMETRY%YRVERT_GEOM%YRCVER, CLOPER&
  &,'11', KLON, KIDIA, KFDIA, KLEV, ZSPHI, ZOUT, KCHUNK=YDGEOMETRY%YRDIM%NPROMA, LDACC=LDACC)
  
  !$ACC PARALLEL LOOP GANG VECTOR &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, KFDIA

    DO JLEV=1, KLEV
      
      PD (JLON, JLEV)=ZOUT (JLON, JLEV)
    
    ENDDO

  ENDDO

ELSE
  
  !$ACC PARALLEL LOOP GANG VECTOR &
  !$ACC&IF (LDACC) &
  !$ACC&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, KFDIA
    
    ZSPHIX (JLON)=0.0_JPRB

    DO JLEV=KLEV, 1,-1
      PD (JLON, JLEV)=ZSPHIX (JLON)+YDDYN%SIALPH(JLEV)*YDCST%RD&
      &*(YDDYN%SITRM (JLEV)/YDDYN%SITR)*PRNH (JLON, JLEV)
      ZSPHIX (JLON)=ZSPHIX (JLON)+YDCST%RD*(YDDYN%SITRM (JLEV&
      &)/YDDYN%SITR)*PRNH (JLON, JLEV)*YDDYN%SILNPR(JLEV)
    ENDDO

  
  ENDDO

ENDIF



IF (LHOOK) CALL DR_HOOK ('SIGAM_NH_SINGLEBLOCK', 1, ZHOOK_HANDLE)
!$ACC END DATA

ENDSUBROUTINE SIGAM_NH_SINGLEBLOCK
