MODULE UTIL_SURFACE_VIEW_GROUP_VCLIA_MOD

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_VCLIA



INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_SURFACE_VIEW_GROUP_VCLIA
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_SURFACE_VIEW_GROUP_VCLIA
END INTERFACE



INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_SURFACE_VIEW_GROUP_VCLIA
END INTERFACE


CONTAINS





SUBROUTINE ACDC_COPY_SURFACE_VIEW_GROUP_VCLIA (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VCLIA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_DES, LF_LAN, LF_SEA, LF_SOO, LF_SUL, LF_VOL
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LF_SEA = ASSOCIATED (SELF%F_SEA)
IF (LF_SEA .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_SEA)
  !$ACC ENTER DATA ATTACH (SELF%F_SEA)
ENDIF

LF_LAN = ASSOCIATED (SELF%F_LAN)
IF (LF_LAN .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_LAN)
  !$ACC ENTER DATA ATTACH (SELF%F_LAN)
ENDIF

LF_SOO = ASSOCIATED (SELF%F_SOO)
IF (LF_SOO .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_SOO)
  !$ACC ENTER DATA ATTACH (SELF%F_SOO)
ENDIF

LF_DES = ASSOCIATED (SELF%F_DES)
IF (LF_DES .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_DES)
  !$ACC ENTER DATA ATTACH (SELF%F_DES)
ENDIF

LF_SUL = ASSOCIATED (SELF%F_SUL)
IF (LF_SUL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_SUL)
  !$ACC ENTER DATA ATTACH (SELF%F_SUL)
ENDIF

LF_VOL = ASSOCIATED (SELF%F_VOL)
IF (LF_VOL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_VOL)
  !$ACC ENTER DATA ATTACH (SELF%F_VOL)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_SURFACE_VIEW_GROUP_VCLIA (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VCLIA), TARGET :: SELF
LOGICAL :: LF_DES, LF_LAN, LF_SEA, LF_SOO, LF_SUL, LF_VOL
LF_SEA = ASSOCIATED (SELF%F_SEA)
IF (LF_SEA) THEN
  CALL HOST_FIELD_2RB (SELF%F_SEA)
ENDIF

LF_LAN = ASSOCIATED (SELF%F_LAN)
IF (LF_LAN) THEN
  CALL HOST_FIELD_2RB (SELF%F_LAN)
ENDIF

LF_SOO = ASSOCIATED (SELF%F_SOO)
IF (LF_SOO) THEN
  CALL HOST_FIELD_2RB (SELF%F_SOO)
ENDIF

LF_DES = ASSOCIATED (SELF%F_DES)
IF (LF_DES) THEN
  CALL HOST_FIELD_2RB (SELF%F_DES)
ENDIF

LF_SUL = ASSOCIATED (SELF%F_SUL)
IF (LF_SUL) THEN
  CALL HOST_FIELD_2RB (SELF%F_SUL)
ENDIF

LF_VOL = ASSOCIATED (SELF%F_VOL)
IF (LF_VOL) THEN
  CALL HOST_FIELD_2RB (SELF%F_VOL)
ENDIF

END SUBROUTINE





SUBROUTINE ACDC_WIPE_SURFACE_VIEW_GROUP_VCLIA (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VCLIA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_DES, LF_LAN, LF_SEA, LF_SOO, LF_SUL, LF_VOL
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_SEA = ASSOCIATED (SELF%F_SEA)
IF (LF_SEA .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_SEA)
ENDIF

LF_LAN = ASSOCIATED (SELF%F_LAN)
IF (LF_LAN .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_LAN)
ENDIF

LF_SOO = ASSOCIATED (SELF%F_SOO)
IF (LF_SOO .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_SOO)
ENDIF

LF_DES = ASSOCIATED (SELF%F_DES)
IF (LF_DES .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_DES)
ENDIF

LF_SUL = ASSOCIATED (SELF%F_SUL)
IF (LF_SUL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_SUL)
ENDIF

LF_VOL = ASSOCIATED (SELF%F_VOL)
IF (LF_VOL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_VOL)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
