MODULE UTIL_SURFACE_VIEW_GROUP_VCLIK_MOD

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_VCLIK



INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_SURFACE_VIEW_GROUP_VCLIK
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_SURFACE_VIEW_GROUP_VCLIK
END INTERFACE



INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_SURFACE_VIEW_GROUP_VCLIK
END INTERFACE


CONTAINS





SUBROUTINE ACDC_COPY_SURFACE_VIEW_GROUP_VCLIK (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VCLIK), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_UDGRO
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LF_UDGRO = ASSOCIATED (SELF%F_UDGRO)
IF (LF_UDGRO .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_UDGRO)
  !$ACC ENTER DATA ATTACH (SELF%F_UDGRO)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_SURFACE_VIEW_GROUP_VCLIK (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VCLIK), TARGET :: SELF
LOGICAL :: LF_UDGRO
LF_UDGRO = ASSOCIATED (SELF%F_UDGRO)
IF (LF_UDGRO) THEN
  CALL HOST_FIELD_2RB (SELF%F_UDGRO)
ENDIF

END SUBROUTINE





SUBROUTINE ACDC_WIPE_SURFACE_VIEW_GROUP_VCLIK (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VCLIK), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_UDGRO
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_UDGRO = ASSOCIATED (SELF%F_UDGRO)
IF (LF_UDGRO .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_UDGRO)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
