MODULE UTIL_CPG_SL1F_1RB_MOD

USE CPG_SL1_TYPE_MOD, ONLY : CPG_SL1F_1RB



INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_CPG_SL1F_1RB
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_CPG_SL1F_1RB
END INTERFACE



INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_CPG_SL1F_1RB
END INTERFACE


CONTAINS





SUBROUTINE ACDC_COPY_CPG_SL1F_1RB (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (CPG_SL1F_1RB), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_P
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LF_P = ASSOCIATED (SELF%F_P)
IF (LF_P .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_1RB (SELF%F_P)
  !$ACC ENTER DATA ATTACH (SELF%F_P)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_CPG_SL1F_1RB (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (CPG_SL1F_1RB), TARGET :: SELF
LOGICAL :: LF_P
LF_P = ASSOCIATED (SELF%F_P)
IF (LF_P) THEN
  CALL HOST_FIELD_1RB (SELF%F_P)
ENDIF

END SUBROUTINE





SUBROUTINE ACDC_WIPE_CPG_SL1F_1RB (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (CPG_SL1F_1RB), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_P
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_P = ASSOCIATED (SELF%F_P)
IF (LF_P .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_1RB (SELF%F_P)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
