MODULE UTIL_CPG_SURF_VND_OPTS_TYPE_MOD

USE CPG_OPTS_TYPE_MOD, ONLY : CPG_SURF_VND_OPTS_TYPE

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_CPG_SURF_VND_OPTS_TYPE
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_CPG_SURF_VND_OPTS_TYPE
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_CPG_SURF_VND_OPTS_TYPE
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_CPG_SURF_VND_OPTS_TYPE
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_CPG_SURF_VND_OPTS_TYPE
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_CPG_SURF_VND_OPTS_TYPE
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_CPG_SURF_VND_OPTS_TYPE (SELF, KLUN)
USE UTIL_CPG_SURF_VN_ACCPR5D_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACCPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_BASD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_TOPD_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_VND_OPTS_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL ACDC_SAVE_CPG_SURF_VN_TOPD_OPTS_TYPE (SELF%YTOP, KLUN)
CALL ACDC_SAVE_CPG_SURF_VN_BASD_OPTS_TYPE (SELF%YBAS, KLUN)
CALL ACDC_SAVE_CPG_SURF_VN_ACPRD_OPTS_TYPE (SELF%YACPR, KLUN)
CALL ACDC_SAVE_CPG_SURF_VN_ACCPRD_OPTS_TYPE (SELF%YACCPR, KLUN)
CALL ACDC_SAVE_CPG_SURF_VN_ACCPR5D_OPTS_TYPE (SELF%YACCPR5, KLUN)
END SUBROUTINE

SUBROUTINE ACDC_LOAD_CPG_SURF_VND_OPTS_TYPE (SELF, KLUN)
USE UTIL_CPG_SURF_VN_ACCPR5D_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACCPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_BASD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_TOPD_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_VND_OPTS_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL ACDC_LOAD_CPG_SURF_VN_TOPD_OPTS_TYPE (SELF%YTOP, KLUN)
CALL ACDC_LOAD_CPG_SURF_VN_BASD_OPTS_TYPE (SELF%YBAS, KLUN)
CALL ACDC_LOAD_CPG_SURF_VN_ACPRD_OPTS_TYPE (SELF%YACPR, KLUN)
CALL ACDC_LOAD_CPG_SURF_VN_ACCPRD_OPTS_TYPE (SELF%YACCPR, KLUN)
CALL ACDC_LOAD_CPG_SURF_VN_ACCPR5D_OPTS_TYPE (SELF%YACCPR5, KLUN)
END SUBROUTINE

SUBROUTINE ACDC_COPY_CPG_SURF_VND_OPTS_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_CPG_SURF_VN_ACCPR5D_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACCPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_BASD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_TOPD_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_VND_OPTS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
CALL ACDC_COPY_CPG_SURF_VN_TOPD_OPTS_TYPE (SELF%YTOP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_CPG_SURF_VN_BASD_OPTS_TYPE (SELF%YBAS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_CPG_SURF_VN_ACPRD_OPTS_TYPE (SELF%YACPR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_CPG_SURF_VN_ACCPRD_OPTS_TYPE (SELF%YACCPR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_CPG_SURF_VN_ACCPR5D_OPTS_TYPE (SELF%YACCPR5, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

SUBROUTINE ACDC_HOST_CPG_SURF_VND_OPTS_TYPE (SELF)
USE UTIL_CPG_SURF_VN_ACCPR5D_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACCPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_BASD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_TOPD_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_VND_OPTS_TYPE), TARGET :: SELF

CALL ACDC_HOST_CPG_SURF_VN_TOPD_OPTS_TYPE (SELF%YTOP)

CALL ACDC_HOST_CPG_SURF_VN_BASD_OPTS_TYPE (SELF%YBAS)

CALL ACDC_HOST_CPG_SURF_VN_ACPRD_OPTS_TYPE (SELF%YACPR)

CALL ACDC_HOST_CPG_SURF_VN_ACCPRD_OPTS_TYPE (SELF%YACCPR)

CALL ACDC_HOST_CPG_SURF_VN_ACCPR5D_OPTS_TYPE (SELF%YACCPR5)

END SUBROUTINE



SUBROUTINE ACDC_CRC64_CPG_SURF_VND_OPTS_TYPE (SELF, KLUN, CDPATH)
USE UTIL_CPG_SURF_VN_ACCPR5D_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACCPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_BASD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_TOPD_OPTS_TYPE_MOD
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (CPG_SURF_VND_OPTS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL ACDC_CRC64_CPG_SURF_VN_TOPD_OPTS_TYPE (SELF%YTOP, KLUN, CDPATH//'%YTOP'//TRIM(CLIND))

CLIND = ''
CALL ACDC_CRC64_CPG_SURF_VN_BASD_OPTS_TYPE (SELF%YBAS, KLUN, CDPATH//'%YBAS'//TRIM(CLIND))

CLIND = ''
CALL ACDC_CRC64_CPG_SURF_VN_ACPRD_OPTS_TYPE (SELF%YACPR, KLUN, CDPATH//'%YACPR'//TRIM(CLIND))

CLIND = ''
CALL ACDC_CRC64_CPG_SURF_VN_ACCPRD_OPTS_TYPE (SELF%YACCPR, KLUN, CDPATH//'%YACCPR'//TRIM(CLIND))

CLIND = ''
CALL ACDC_CRC64_CPG_SURF_VN_ACCPR5D_OPTS_TYPE (SELF%YACCPR5, KLUN, CDPATH//'%YACCPR5'//TRIM(CLIND))

END SUBROUTINE

SUBROUTINE ACDC_WIPE_CPG_SURF_VND_OPTS_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_CPG_SURF_VN_ACCPR5D_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACCPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_ACPRD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_BASD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VN_TOPD_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_VND_OPTS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL ACDC_WIPE_CPG_SURF_VN_TOPD_OPTS_TYPE (SELF%YTOP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_CPG_SURF_VN_BASD_OPTS_TYPE (SELF%YBAS, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_CPG_SURF_VN_ACPRD_OPTS_TYPE (SELF%YACPR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_CPG_SURF_VN_ACCPRD_OPTS_TYPE (SELF%YACCPR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_CPG_SURF_VN_ACCPR5D_OPTS_TYPE (SELF%YACCPR5, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
