MODULE UTIL_CPG_GMV_TYPE_MOD

USE CPG_GMV_TYPE_MOD, ONLY : CPG_GMV_TYPE



INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_CPG_GMV_TYPE
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_CPG_GMV_TYPE
END INTERFACE



INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_CPG_GMV_TYPE
END INTERFACE


CONTAINS





SUBROUTINE ACDC_COPY_CPG_GMV_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_CPG_GMV_3D_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_GMV_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LGMV
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

CALL ACDC_COPY_CPG_GMV_3D_TYPE (SELF%U, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_CPG_GMV_3D_TYPE (SELF%V, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_CPG_GMV_3D_TYPE (SELF%T, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_CPG_GMV_3D_TYPE (SELF%SPD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_CPG_GMV_3D_TYPE (SELF%SVD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_CPG_GMV_3D_TYPE (SELF%NHX, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LGMV = ALLOCATED (SELF%GMV)
IF (LGMV) THEN
  !$ACC ENTER DATA CREATE (SELF%GMV)
  !$ACC UPDATE DEVICE (SELF%GMV)
  DO J1 = LBOUND (SELF%GMV, 1), UBOUND (SELF%GMV, 1)
    CALL ACDC_COPY_CPG_GMV_3D_TYPE (SELF%GMV (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%GMV)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_CPG_GMV_TYPE (SELF)
USE UTIL_CPG_GMV_3D_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_GMV_TYPE), TARGET :: SELF
INTEGER :: J1
LOGICAL :: LGMV

CALL ACDC_HOST_CPG_GMV_3D_TYPE (SELF%U)

CALL ACDC_HOST_CPG_GMV_3D_TYPE (SELF%V)

CALL ACDC_HOST_CPG_GMV_3D_TYPE (SELF%T)

CALL ACDC_HOST_CPG_GMV_3D_TYPE (SELF%SPD)

CALL ACDC_HOST_CPG_GMV_3D_TYPE (SELF%SVD)

CALL ACDC_HOST_CPG_GMV_3D_TYPE (SELF%NHX)

LGMV = ALLOCATED (SELF%GMV)
IF (LGMV) THEN
  DO J1 = LBOUND (SELF%GMV, 1), UBOUND (SELF%GMV, 1)
    CALL ACDC_HOST_CPG_GMV_3D_TYPE (SELF%GMV (J1))
  ENDDO
ENDIF

END SUBROUTINE





SUBROUTINE ACDC_WIPE_CPG_GMV_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_CPG_GMV_3D_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_GMV_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LGMV
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL ACDC_WIPE_CPG_GMV_3D_TYPE (SELF%U, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_CPG_GMV_3D_TYPE (SELF%V, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_CPG_GMV_3D_TYPE (SELF%T, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_CPG_GMV_3D_TYPE (SELF%SPD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_CPG_GMV_3D_TYPE (SELF%SVD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_CPG_GMV_3D_TYPE (SELF%NHX, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LGMV = ALLOCATED (SELF%GMV)
IF (LGMV) THEN
  !$ACC EXIT DATA DETACH (SELF%GMV)
  DO J1 = LBOUND (SELF%GMV, 1), UBOUND (SELF%GMV, 1)
    CALL ACDC_WIPE_CPG_GMV_3D_TYPE (SELF%GMV (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DELETE (SELF%GMV)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
