MODULE UTIL_SURFACE_VARIABLE_GROUP_VO3ABC_MOD

USE SURFACE_VARIABLES_MOD, ONLY : SURFACE_VARIABLE_GROUP_VO3ABC



INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_SURFACE_VARIABLE_GROUP_VO3ABC
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_SURFACE_VARIABLE_GROUP_VO3ABC
END INTERFACE



INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_SURFACE_VARIABLE_GROUP_VO3ABC
END INTERFACE


CONTAINS





SUBROUTINE ACDC_COPY_SURFACE_VARIABLE_GROUP_VO3ABC (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_2RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_VO3ABC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
CALL ACDC_COPY_VARIABLE_2RB (SELF%VA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%VB, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%VC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_GROUP)
  !$ACC ENTER DATA ATTACH (SELF%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_SURFACE_VARIABLE_GROUP_VO3ABC (SELF)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_2RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_VO3ABC), TARGET :: SELF
LOGICAL :: LF_GROUP
CALL ACDC_HOST_VARIABLE_2RB (SELF%VA)

CALL ACDC_HOST_VARIABLE_2RB (SELF%VB)

CALL ACDC_HOST_VARIABLE_2RB (SELF%VC)

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (SELF%F_GROUP)
ENDIF

END SUBROUTINE





SUBROUTINE ACDC_WIPE_SURFACE_VARIABLE_GROUP_VO3ABC (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_2RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_VO3ABC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL ACDC_WIPE_VARIABLE_2RB (SELF%VA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_VARIABLE_2RB (SELF%VB, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_VARIABLE_2RB (SELF%VC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
