MODULE UTIL_SURFACE_VARIABLE_GROUP_VCLIA_MOD

USE SURFACE_VARIABLES_MOD, ONLY : SURFACE_VARIABLE_GROUP_VCLIA



INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_SURFACE_VARIABLE_GROUP_VCLIA
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_SURFACE_VARIABLE_GROUP_VCLIA
END INTERFACE



INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_SURFACE_VARIABLE_GROUP_VCLIA
END INTERFACE


CONTAINS





SUBROUTINE ACDC_COPY_SURFACE_VARIABLE_GROUP_VCLIA (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_2RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_VCLIA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
CALL ACDC_COPY_VARIABLE_2RB (SELF%VSEA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%VLAN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%VSOO, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%VDES, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%VSUL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%VVOL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_GROUP)
  !$ACC ENTER DATA ATTACH (SELF%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_SURFACE_VARIABLE_GROUP_VCLIA (SELF)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_2RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_VCLIA), TARGET :: SELF
LOGICAL :: LF_GROUP
CALL ACDC_HOST_VARIABLE_2RB (SELF%VSEA)

CALL ACDC_HOST_VARIABLE_2RB (SELF%VLAN)

CALL ACDC_HOST_VARIABLE_2RB (SELF%VSOO)

CALL ACDC_HOST_VARIABLE_2RB (SELF%VDES)

CALL ACDC_HOST_VARIABLE_2RB (SELF%VSUL)

CALL ACDC_HOST_VARIABLE_2RB (SELF%VVOL)

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (SELF%F_GROUP)
ENDIF

END SUBROUTINE





SUBROUTINE ACDC_WIPE_SURFACE_VARIABLE_GROUP_VCLIA (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_2RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_VCLIA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL ACDC_WIPE_VARIABLE_2RB (SELF%VSEA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_VARIABLE_2RB (SELF%VLAN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_VARIABLE_2RB (SELF%VSOO, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_VARIABLE_2RB (SELF%VDES, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_VARIABLE_2RB (SELF%VSUL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_VARIABLE_2RB (SELF%VVOL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
