INTERFACE
SUBROUTINE ACCTND0 (YDCST, LDT1, YDCPG_OPTS, YDCPG_BNDS, PRCP, PACC, PTND)
USE PARKIND1 , ONLY : JPIM, JPRB
USE CPG_OPTS_TYPE_MOD&
 & , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE 
USE YOMCST , ONLY : TCST
TYPE (TCST), INTENT (IN) :: YDCST
LOGICAL, INTENT (IN) :: LDT1
TYPE (CPG_OPTS_TYPE),INTENT (IN) :: YDCPG_OPTS
TYPE (CPG_BNDS_TYPE),INTENT (IN) :: YDCPG_BNDS
REAL (KIND=JPRB), INTENT (IN) :: PRCP
REAL (KIND=JPRB), INTENT (INOUT) :: PACC (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN) :: PTND (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
END SUBROUTINE ACCTND0
END INTERFACE
