INTERFACE
SUBROUTINE ACDROV ( YDCST, YDML_PHY_MF,KIDIA,KFDIA,KLON,KLEV,KCSS,&
 & PFPLCL,PFPLCN,PFPLSL,PFPLSN,PFRSO,PFRTH,&
 & PC1,PC2,PC3,PCN,PCT,PD2,PFEVV,PFTR,PLAI,PNEIJ,&
 & PVEG,PWFC,PWPMX,PWL,PWLMX,PWSEQ,PWSMX,&
 & PFCHSP,PFCLL,PFCLN,PFCS,PFEVI,PFEVL,PFEVN,&
 & PLSM,PSNS,&
 & PTP,PTS,PWP,PWPI,PWS,PWSI,&
 & PFGEL,PFGELS,PFLWSP,PFONTE,PRUISP,PRUISL,PRUISS) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCST , ONLY : TCST
TYPE (TCST), INTENT (IN) :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KCSS
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSO(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PC1(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PC2(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PC3(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PD2(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVV(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFTR(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAI(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJ(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEG(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWFC(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWPMX(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWLMX(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSEQ(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSMX(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCHSP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVI(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTP(KLON,KCSS)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWPI(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSI(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFGEL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFGELS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFLWSP(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFONTE(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRUISP(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRUISL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRUISS(KLON)
END SUBROUTINE ACDROV
END INTERFACE
