INTERFACE
SUBROUTINE QNGCOR ( YDCST, YDPHY2,KIDIA, KFDIA, KLON, KTDIA, KLEV,&
 & PQ, PQL, PQI, PRDELP,&
 & PDIFCQ , PDIFCQI, PDIFCQL, PDIFTQ , PDIFTQI, PDIFTQL,&
 & PFESL , PFESN , PFECL , PFECN ,&
 & PFASL , PFASN , PFACL , PFACN ,&
 & PFCCQL , PFCCQN , PFCSQL , PFCSQN , PFCQNG ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMPHY2 , ONLY : TPHY2
USE YOMCST , ONLY : TCST
TYPE (TCST), INTENT (IN) :: YDCST
TYPE(TPHY2) ,INTENT(IN) :: YDPHY2
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PQ (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQL (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQI (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQ (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQ (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFESL (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFESN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFECL (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFECN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFASL (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFASN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFACL (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFACN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQL (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCSQL (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCSQN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQNG (KLON,0:KLEV)
END SUBROUTINE QNGCOR
END INTERFACE
