INTERFACE
SUBROUTINE VERINT(KPROMA,KST,KEND,KLEVIN,KLEVOUT,PINTE,PIN,POUT,KTYPE,KCHUNK,POUTS,PINS)
USE PARKIND1 , ONLY : JPRD, JPIM, JPRB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA,KLEVIN,KLEVOUT,KST,KEND,KTYPE,KCHUNK
REAL(KIND=JPRD) ,INTENT(IN) :: PINTE(KLEVOUT,KLEVIN)
REAL(KIND=JPRB) ,INTENT(IN) ,TARGET :: PIN(KPROMA,KLEVIN)
REAL(KIND=JPRB) ,INTENT(OUT) ,TARGET :: POUT(KPROMA,KLEVOUT-1)
REAL(KIND=JPRD) ,INTENT(IN) ,OPTIONAL ,TARGET :: POUTS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PINS(KPROMA)
END SUBROUTINE VERINT
END INTERFACE
