SUBMODULE (CPG_SLMISC_TYPE_MOD) CPG_SLMISC_TYPE_MOD_CPG_SLMISC_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_CPG_SLMISC_TYPE (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (CPG_SLMISC_TYPE), TARGET :: SELF
LOGICAL :: LF_ISETTLOFF, LF_SLHDA, LF_SLHDD0
LF_SLHDA = ASSOCIATED (SELF%F_SLHDA)
IF (LF_SLHDA) THEN
  CALL HOST_FIELD_2RB (SELF%F_SLHDA)
ENDIF

LF_SLHDD0 = ASSOCIATED (SELF%F_SLHDD0)
IF (LF_SLHDD0) THEN
  CALL HOST_FIELD_2RB (SELF%F_SLHDD0)
ENDIF

LF_ISETTLOFF = ASSOCIATED (SELF%F_ISETTLOFF)
IF (LF_ISETTLOFF) THEN
  CALL HOST_FIELD_3IM (SELF%F_ISETTLOFF)
ENDIF

END SUBROUTINE

END SUBMODULE
