SUBMODULE (INTDYN_MOD) INTDYN_MOD_TGFLT_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TGFLT (SELF, KLUN)

IMPLICIT NONE
CLASS (TGFLT), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_Q
WRITE (KLUN) SELF%M_L
WRITE (KLUN) SELF%M_I
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

END SUBMODULE
