SUBMODULE (MODEL_PHYSICS_ECMWF_MOD) MODEL_PHYSICS_ECMWF_MOD_MODEL_PHYSICS_ECMWF_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE HOST_MODEL_PHYSICS_ECMWF_TYPE (SELF)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_ECMWF_TYPE), TARGET :: SELF

CALL SELF%YREPHY%HOST ()

CALL SELF%YRECLD%HOST ()

CALL SELF%YRECLDP%HOST ()

CALL SELF%YRECND%HOST ()

CALL SELF%YRECUMF%HOST ()

CALL SELF%YRECUCONVCA%HOST ()

CALL SELF%YREGWD%HOST ()

CALL SELF%YREGWWMS%HOST ()

CALL SELF%YRTHF%HOST ()

END SUBROUTINE

END SUBMODULE
