SUBMODULE (MODEL_DYNAMICS_MOD) MODEL_DYNAMICS_MOD_MODEL_DYNAMICS_TYPE_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_MODEL_DYNAMICS_TYPE (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (MODEL_DYNAMICS_TYPE),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
JSIZE = 0
ISIZE = SELF%YRDYNA%ACDC_SIZE (CLPATH//'%YRDYNA', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDYNA'
ENDIF
JSIZE = 0
ISIZE = SELF%YRDYN%ACDC_SIZE (CLPATH//'%YRDYN', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDYN'
ENDIF
JSIZE = 0
ISIZE = SELF%YREDYN%ACDC_SIZE (CLPATH//'%YREDYN', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREDYN'
ENDIF
JSIZE = 0
ISIZE = SELF%YRSPNG%ACDC_SIZE (CLPATH//'%YRSPNG', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSPNG'
ENDIF
JSIZE = 0
ISIZE = SELF%YRPTRGPPC%ACDC_SIZE (CLPATH//'%YRPTRGPPC', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRPTRGPPC'
ENDIF
JSIZE = 0
ISIZE = SELF%YYTLSCAW%ACDC_SIZE (CLPATH//'%YYTLSCAW', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTLSCAW'
ENDIF
JSIZE = 0
ISIZE = SELF%YYTLSCAWH%ACDC_SIZE (CLPATH//'%YYTLSCAWH', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTLSCAWH'
ENDIF
JSIZE = 0
ISIZE = SELF%YYTRSCAW%ACDC_SIZE (CLPATH//'%YYTRSCAW', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTRSCAW'
ENDIF
JSIZE = 0
ISIZE = SELF%YYTRSCAWH%ACDC_SIZE (CLPATH//'%YYTRSCAWH', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTRSCAWH'
ENDIF
JSIZE = 0
ISIZE = SELF%YYTSCO%ACDC_SIZE (CLPATH//'%YYTSCO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTSCO'
ENDIF
JSIZE = 0
ISIZE = SELF%YYTCCO%ACDC_SIZE (CLPATH//'%YYTCCO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTCCO'
ENDIF
JSIZE = 0
ISIZE = SELF%YRSLREP%ACDC_SIZE (CLPATH//'%YRSLREP', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSLREP'
ENDIF
JSIZE = 0
ISIZE = SELF%YRSLINT%ACDC_SIZE (CLPATH//'%YRSLINT', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSLINT'
ENDIF
JSIZE = 0
ISIZE = SELF%YRPTRSLB1%ACDC_SIZE (CLPATH//'%YRPTRSLB1', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRPTRSLB1'
ENDIF
JSIZE = 0
ISIZE = SELF%YRPTRSLB2%ACDC_SIZE (CLPATH//'%YRPTRSLB2', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRPTRSLB2'
ENDIF
JSIZE = 0
ISIZE = SELF%YRPTRSLB15%ACDC_SIZE (CLPATH//'%YRPTRSLB15', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRPTRSLB15'
ENDIF
JSIZE = 0
ISIZE = SELF%YRTNH%ACDC_SIZE (CLPATH//'%YRTNH', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRTNH'
ENDIF
JSIZE = 0
ISIZE = SELF%YRSL%ACDC_SIZE (CLPATH//'%YRSL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSL'
ENDIF
JSIZE = 0
ISIZE = SELF%YRAD%ACDC_SIZE (CLPATH//'%YRAD', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRAD'
ENDIF
END FUNCTION

END SUBMODULE
