SUBMODULE (MODEL_PHYSICS_ECMWF_MOD) MODEL_PHYSICS_ECMWF_MOD_MODEL_PHYSICS_ECMWF_TYPE_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_MODEL_PHYSICS_ECMWF_TYPE (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_ECMWF_TYPE),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
JSIZE = 0
ISIZE = SELF%YREPHY%ACDC_SIZE (CLPATH//'%YREPHY', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREPHY'
ENDIF
JSIZE = 0
ISIZE = SELF%YRECLD%ACDC_SIZE (CLPATH//'%YRECLD', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRECLD'
ENDIF
JSIZE = 0
ISIZE = SELF%YRECLDP%ACDC_SIZE (CLPATH//'%YRECLDP', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRECLDP'
ENDIF
JSIZE = 0
ISIZE = SELF%YRECND%ACDC_SIZE (CLPATH//'%YRECND', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRECND'
ENDIF
JSIZE = 0
ISIZE = SELF%YRECUMF%ACDC_SIZE (CLPATH//'%YRECUMF', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRECUMF'
ENDIF
JSIZE = 0
ISIZE = SELF%YRECUCONVCA%ACDC_SIZE (CLPATH//'%YRECUCONVCA', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRECUCONVCA'
ENDIF
JSIZE = 0
ISIZE = SELF%YREGWD%ACDC_SIZE (CLPATH//'%YREGWD', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREGWD'
ENDIF
JSIZE = 0
ISIZE = SELF%YREGWWMS%ACDC_SIZE (CLPATH//'%YREGWWMS', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREGWWMS'
ENDIF
JSIZE = 0
ISIZE = SELF%YRTHF%ACDC_SIZE (CLPATH//'%YRTHF', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRTHF'
ENDIF
END FUNCTION

END SUBMODULE
