SUBMODULE (MODEL_PHYSICS_RADIATION_MOD) MODEL_PHYSICS_RADIATION_MOD_MODEL_PHYSICS_RADIATION_TYPE_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_MODEL_PHYSICS_RADIATION_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_RADIATION_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM
CALL SELF%YRERAD%ACDC_SAVE (KLUN)
CALL SELF%YRESWRT%ACDC_SAVE (KLUN)
CALL SELF%YREOVLP%ACDC_SAVE (KLUN)
CALL SELF%YRENEUR%ACDC_SAVE (KLUN)
CALL SELF%YRELWRAD%ACDC_SAVE (KLUN)
CALL SELF%YREAERD%ACDC_SAVE (KLUN)
CALL SELF%YREAERATM%ACDC_SAVE (KLUN)
CALL SELF%YREUVRAD%ACDC_SAVE (KLUN)
CALL SELF%YRERDI%ACDC_SAVE (KLUN)
CALL SELF%YREMCICA%ACDC_SAVE (KLUN)
CALL SELF%YRRCOEF%ACDC_SAVE (KLUN)
CALL SELF%YRTRC%ACDC_SAVE (KLUN)
CALL SELF%RADGRID%ACDC_SAVE (KLUN)
LYRAD_GSGEOM = ASSOCIATED (SELF%YRAD_GSGEOM)
WRITE (KLUN) LYRAD_GSGEOM
IF (LYRAD_GSGEOM) THEN
  WRITE (KLUN) LBOUND (SELF%YRAD_GSGEOM)
  WRITE (KLUN) UBOUND (SELF%YRAD_GSGEOM)
  DO J1 = LBOUND (SELF%YRAD_GSGEOM, 1), UBOUND (SELF%YRAD_GSGEOM, 1)
    CALL SELF%YRAD_GSGEOM (J1)%ACDC_SAVE (KLUN)
  ENDDO
ENDIF
CALL SELF%YRERIP%ACDC_SAVE (KLUN)
CALL SELF%YRADIATION%ACDC_SAVE (KLUN)
CALL SELF%YRRI%ACDC_SAVE (KLUN)
CALL SELF%YRRO%ACDC_SAVE (KLUN)
END SUBROUTINE

END SUBMODULE
