MODULE MODEL_PHYSICS_MF_MOD

!$ACDC methods 

  USE YOMPHY   , ONLY : TPHY
  USE YOMPHY0  , ONLY : TPHY0
  USE YOMPHY1  , ONLY : TPHY1
  USE YOMPHY2  , ONLY : TPHY2
  USE YOMPHY3  , ONLY : TPHY3
  USE YOMPHYDS , ONLY : TPHYDS
  USE YOMCVMNH , ONLY : TCVMNH
  USE YOMTOPH  , ONLY : TTOPH
  USE YOMVDOZ  , ONLY : TVDOZ
  USE YOMSIMPHL, ONLY : TSIMPHL
  USE YOMARPHY , ONLY : TARPHY
  USE YOMPARAR , ONLY : TPARAR
  USE YOMMSE   , ONLY : TMSE
  USE YOMLOUIS , ONLY : TLOUIS
  USE YOMNORGWD, ONLY : TNORGWD
  USE YOMNRTAER, ONLY : TNRTAER
  USE YOAIOP   , ONLY : TAIOP
  USE EINT_MOD , ONLY : SL_STRUCT
  USE YOMDGRADIENT , ONLY : TGRADIENT
  IMPLICIT NONE
  
  TYPE MODEL_PHYSICS_MF_TYPE

  TYPE(TPHY)    :: YRPHY !! (french) physics
  TYPE(TPHY0)   :: YRPHY0 !! atmospheric parameters
  TYPE(TPHY1)   :: YRPHY1 !! surface parameters
  TYPE(TPHY2)   :: YRPHY2 !! expt parameters
  TYPE(TPHY3)   :: YRPHY3 !! radiation-related parameters
  TYPE(TPHYDS)  :: YRPHYDS
  TYPE(TCVMNH)  :: YRCVMNH
  TYPE(TTOPH)   :: YRTOPH
  TYPE(TVDOZ)   :: YRVDOZ
  TYPE(TSIMPHL) :: YRSIMPHL
  TYPE(TARPHY)  :: YRARPHY
  TYPE(TPARAR)  :: YRPARAR
  TYPE(TMSE)    :: YRMSE
  TYPE(TLOUIS)  :: YRLOUIS
  TYPE(TNORGWD) :: YRNORGWD !! non-orographic GWD scheme parameters
  TYPE(SL_STRUCT) :: YRGR ! horizontal gradients halo manager
  TYPE(TGRADIENT) :: YGRAD ! horizontal gradients output
  TYPE(TNRTAER) :: YRNRTAER !! near real time aerosols
  TYPE(TAIOP)   :: YRAIOP   !! aerosol inherent optical properties

    CONTAINS

    PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 

  PROCEDURE :: ACDC_COPY => ACDC_COPY_MODEL_PHYSICS_MF_TYPE
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_MODEL_PHYSICS_MF_TYPE
PROCEDURE :: ACDC_HOST => ACDC_HOST_MODEL_PHYSICS_MF_TYPE
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_MODEL_PHYSICS_MF_TYPE
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_MODEL_PHYSICS_MF_TYPE
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_MODEL_PHYSICS_MF_TYPE
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_MODEL_PHYSICS_MF_TYPE
END TYPE MODEL_PHYSICS_MF_TYPE

  !---------------------------------------------------------------------

  INTERFACE

MODULE SUBROUTINE ACDC_COPY_MODEL_PHYSICS_MF_TYPE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_MODEL_PHYSICS_MF_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (MODEL_PHYSICS_MF_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_MODEL_PHYSICS_MF_TYPE (SELF)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_MF_TYPE), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_MODEL_PHYSICS_MF_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_MF_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_MODEL_PHYSICS_MF_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_MODEL_PHYSICS_MF_TYPE (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_MF_TYPE),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_MODEL_PHYSICS_MF_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

CONTAINS 

  SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  USE PARKIND1  ,ONLY : JPIM
  IMPLICIT NONE
  CLASS(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: SELF
  INTEGER(KIND=JPIM)          , INTENT(IN) :: KDEPTH
  INTEGER(KIND=JPIM)          , INTENT(IN) :: KOUTNO

  WRITE(KOUTNO,*) REPEAT(' ',KDEPTH) // 'model%yrml_phy_mf : not yet printable'
 
  END SUBROUTINE PRINT_CONFIGURATION

END MODULE MODEL_PHYSICS_MF_MOD
