MODULE MODEL_DIAGNOSTICS_MOD

!$ACDC methods 

  USE YOMCDDH , ONLY : TCDDH
  USE YOMLDDH , ONLY : TLDDH
  USE YOMMDDH , ONLY : TMDDH
  USE YOMSDDH , ONLY : TSDDH
  USE YOMTDDH , ONLY : TTDDH
  USE YOMGPDDH, ONLY : TGPDDH
  USE YOMPADDH, ONLY : TPADDH
  USE YOMSPDDH, ONLY : TSPDDH
  IMPLICIT NONE

  TYPE MODEL_DIAGNOSTICS_TYPE

!!  TYPE(GRIDPOINT_BUFFER)   :: GFUBUF, XFUBUF, GPPCBUF
  TYPE(TCDDH)              :: YRCDDH
  TYPE(TLDDH)              :: YRLDDH
  TYPE(TMDDH)              :: YRMDDH
  TYPE(TSDDH)              :: YRSDDH
  TYPE(TTDDH)              :: YRTDDH
  TYPE(TGPDDH)             :: YRGPDDH
  TYPE(TPADDH)             :: YRPADDH
  TYPE(TSPDDH)             :: YRSPDDH

CONTAINS
  
  PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
    
  PROCEDURE :: COPY => COPY_MODEL_DIAGNOSTICS_TYPE
PROCEDURE :: CRC64 => CRC64_MODEL_DIAGNOSTICS_TYPE
PROCEDURE :: HOST => HOST_MODEL_DIAGNOSTICS_TYPE
PROCEDURE :: LOAD => LOAD_MODEL_DIAGNOSTICS_TYPE
PROCEDURE :: SAVE => SAVE_MODEL_DIAGNOSTICS_TYPE
PROCEDURE :: SIZE => SIZE_MODEL_DIAGNOSTICS_TYPE
PROCEDURE :: WIPE => WIPE_MODEL_DIAGNOSTICS_TYPE
END TYPE MODEL_DIAGNOSTICS_TYPE

  !---------------------------------------------------------------------

  INTERFACE

MODULE SUBROUTINE COPY_MODEL_DIAGNOSTICS_TYPE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (MODEL_DIAGNOSTICS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE CRC64_MODEL_DIAGNOSTICS_TYPE (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (MODEL_DIAGNOSTICS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE HOST_MODEL_DIAGNOSTICS_TYPE (SELF)

IMPLICIT NONE
CLASS (MODEL_DIAGNOSTICS_TYPE), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE LOAD_MODEL_DIAGNOSTICS_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_DIAGNOSTICS_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE SAVE_MODEL_DIAGNOSTICS_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_DIAGNOSTICS_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION SIZE_MODEL_DIAGNOSTICS_TYPE (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (MODEL_DIAGNOSTICS_TYPE),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE WIPE_MODEL_DIAGNOSTICS_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (MODEL_DIAGNOSTICS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

CONTAINS 

  SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  IMPLICIT NONE
  CLASS(MODEL_DIAGNOSTICS_TYPE), INTENT(IN) :: SELF
  INTEGER                      , INTENT(IN) :: KDEPTH
  INTEGER                      , INTENT(IN) :: KOUTNO

  WRITE(KOUTNO,*) REPEAT(' ',KDEPTH) // 'model%yrml_phy_diag : not yet printable'

  END SUBROUTINE PRINT_CONFIGURATION

END MODULE MODEL_DIAGNOSTICS_MOD
