SUBMODULE (MODEL_PHYSICS_GENERAL_MOD) MODEL_PHYSICS_GENERAL_MOD_MODEL_PHYSICS_GENERAL_TYPE_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_MODEL_PHYSICS_GENERAL_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_GENERAL_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SELF%YRDPHY%ACDC_SAVE (KLUN)
CALL SELF%YRSLPHY%ACDC_SAVE (KLUN)
CALL SELF%YRVDF%ACDC_SAVE (KLUN)
END SUBROUTINE

END SUBMODULE
