SUBMODULE (MODEL_PHYSICS_STOCHAST_MOD) MODEL_PHYSICS_STOCHAST_MOD_MODEL_PHYSICS_STOCHAST_TYPE_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_MODEL_PHYSICS_STOCHAST_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_STOCHAST_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SELF%YRPERTPAR%ACDC_LOAD (KLUN)
CALL SELF%YRSTOPH%ACDC_LOAD (KLUN)
END SUBROUTINE

END SUBMODULE
