SUBMODULE (MODEL_PHYSICS_ECMWF_MOD) MODEL_PHYSICS_ECMWF_MOD_MODEL_PHYSICS_ECMWF_TYPE_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_MODEL_PHYSICS_ECMWF_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_ECMWF_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SELF%YREPHY%ACDC_LOAD (KLUN)
CALL SELF%YRECLD%ACDC_LOAD (KLUN)
CALL SELF%YRECLDP%ACDC_LOAD (KLUN)
CALL SELF%YRECND%ACDC_LOAD (KLUN)
CALL SELF%YRECUMF%ACDC_LOAD (KLUN)
CALL SELF%YRECUCONVCA%ACDC_LOAD (KLUN)
CALL SELF%YREGWD%ACDC_LOAD (KLUN)
CALL SELF%YREGWWMS%ACDC_LOAD (KLUN)
CALL SELF%YRTHF%ACDC_LOAD (KLUN)
END SUBROUTINE

END SUBMODULE
