SUBMODULE (MODEL_GENERAL_CONF_MOD) MODEL_GENERAL_CONF_MOD_MODEL_GENERAL_CONF_TYPE_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_MODEL_GENERAL_CONF_TYPE (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (MODEL_GENERAL_CONF_TYPE),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LGEOM
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LGEOM = ASSOCIATED (SELF%GEOM)
IF (LGEOM) THEN
  JSIZE = 0
  ISIZE = SELF%GEOM%ACDC_SIZE (CLPATH//'%GEOM', .FALSE.)
  JSIZE = JSIZE + ISIZE
  KSIZE = KSIZE + ISIZE
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
    WRITE (*, *) TRIM (CLPATH)//'%GEOM'
  ENDIF
ENDIF
JSIZE = 0
ISIZE = SELF%YRDIMF%ACDC_SIZE (CLPATH//'%YRDIMF', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDIMF'
ENDIF
JSIZE = 0
ISIZE = SELF%YGFL%ACDC_SIZE (CLPATH//'%YGFL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YGFL'
ENDIF
JSIZE = 0
ISIZE = SELF%YRRIP%ACDC_SIZE (CLPATH//'%YRRIP', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRRIP'
ENDIF
JSIZE = 0
ISIZE = SELF%YRDIMECV%ACDC_SIZE (CLPATH//'%YRDIMECV', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDIMECV'
ENDIF
JSIZE = 0
ISIZE = SELF%YRMODERR%ACDC_SIZE (CLPATH//'%YRMODERR', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRMODERR'
ENDIF
JSIZE = 0
ISIZE = SELF%YRSPPT_CONFIG%ACDC_SIZE (CLPATH//'%YRSPPT_CONFIG', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSPPT_CONFIG'
ENDIF
JSIZE = 0
ISIZE = SELF%YRSPP_CONFIG%ACDC_SIZE (CLPATH//'%YRSPP_CONFIG', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSPP_CONFIG'
ENDIF
END FUNCTION

END SUBMODULE
