SUBMODULE (MODEL_PHYSICS_GENERAL_MOD) MODEL_PHYSICS_GENERAL_MOD_MODEL_PHYSICS_GENERAL_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE CRC64_MODEL_PHYSICS_GENERAL_TYPE (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (MODEL_PHYSICS_GENERAL_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YRDPHY%CRC64 (KLUN, CDPATH//'%YRDPHY'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRSLPHY%CRC64 (KLUN, CDPATH//'%YRSLPHY'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRVDF%CRC64 (KLUN, CDPATH//'%YRVDF'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
