SUBMODULE (SPP_DEF_MOD) SPP_DEF_MOD_SPP_PERT_POINTER_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_SPP_PERT_POINTER (SELF, KLUN)

IMPLICIT NONE
CLASS (SPP_PERT_POINTER), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%CFM
WRITE (KLUN) SELF%CFM1
WRITE (KLUN) SELF%CFM2
WRITE (KLUN) SELF%CFM3
WRITE (KLUN) SELF%RKAP
WRITE (KLUN) SELF%RKAP1
WRITE (KLUN) SELF%RKAP2
WRITE (KLUN) SELF%RKAP3
WRITE (KLUN) SELF%TOFDC
WRITE (KLUN) SELF%HSDT
WRITE (KLUN) SELF%VDEXC
WRITE (KLUN) SELF%ENTRORG
WRITE (KLUN) SELF%ENTSHALP
WRITE (KLUN) SELF%ENTSTPC1
WRITE (KLUN) SELF%DETRPEN
WRITE (KLUN) SELF%RPRCON
WRITE (KLUN) SELF%RTAU
WRITE (KLUN) SELF%CUDUDV
WRITE (KLUN) SELF%CUDUDVS
WRITE (KLUN) SELF%RAMID
WRITE (KLUN) SELF%RCLDIFF
WRITE (KLUN) SELF%RCLCRIT
WRITE (KLUN) SELF%RLCRITSNOW
WRITE (KLUN) SELF%RAINEVAP
WRITE (KLUN) SELF%SNOWSUBLIM
WRITE (KLUN) SELF%CLOUDINHOM
WRITE (KLUN) SELF%QSATVERVEL
WRITE (KLUN) SELF%ZDECORR
WRITE (KLUN) SELF%ZSIGQCW
WRITE (KLUN) SELF%ZRADEFFL
WRITE (KLUN) SELF%ZRADEFFI
WRITE (KLUN) SELF%PHR
WRITE (KLUN) SELF%ZHS_VDAERO
WRITE (KLUN) SELF%DELTA_AERO
WRITE (KLUN) SELF%PSIGQSAT
WRITE (KLUN) SELF%CLDDPTH
WRITE (KLUN) SELF%CLDDPTHDP
WRITE (KLUN) SELF%ICE_CLD_WGT
WRITE (KLUN) SELF%ICENU
WRITE (KLUN) SELF%KGN_ACON
WRITE (KLUN) SELF%KGN_SBGR
WRITE (KLUN) SELF%RADGR
WRITE (KLUN) SELF%RADSN
WRITE (KLUN) SELF%RFAC_TWOC
WRITE (KLUN) SELF%RZC_H
WRITE (KLUN) SELF%RZL_INF
WRITE (KLUN) SELF%RSWINHF
WRITE (KLUN) SELF%RLWINHF
WRITE (KLUN) SELF%ALPHA
WRITE (KLUN) SELF%RZNUC
WRITE (KLUN) SELF%RZMFDRY
WRITE (KLUN) SELF%RZMBCLOSURE
WRITE (KLUN) SELF%SLWIND
END SUBROUTINE

END SUBMODULE
