SUBMODULE (SURFACE_FIELDS_MIX) SURFACE_FIELDS_MIX_TYPE_SURF_GEN_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TYPE_SURF_GEN (SELF, KLUN)

IMPLICIT NONE
CLASS (TYPE_SURF_GEN), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NUMFLDS
READ (KLUN) SELF%NDIM
READ (KLUN) SELF%NLEVS
READ (KLUN) SELF%IPTR
READ (KLUN) SELF%IPTR5
READ (KLUN) SELF%NDIM5
READ (KLUN) SELF%NOFFTRAJ
READ (KLUN) SELF%NOFFTRAJ_CST
READ (KLUN) SELF%CGRPNAME
READ (KLUN) SELF%L3D
READ (KLUN) SELF%LMTL
READ (KLUN) SELF%FINALISED
END SUBROUTINE

END SUBMODULE
