SUBMODULE (TYPE_ECV) TYPE_ECV_TECV_CONFIG_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TECV_CONFIG (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TECV_CONFIG), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
INTEGER :: J1
LOGICAL :: LYRCONFIG
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NECV), CDPATH//'%NECV'

LYRCONFIG = ALLOCATED (SELF%YRCONFIG)
IF (LYRCONFIG) THEN
  DO J1 = LBOUND (SELF%YRCONFIG, 1), UBOUND (SELF%YRCONFIG, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%YRCONFIG (J1)%ACDC_CRC64 (KLUN, CDPATH//'%YRCONFIG'//TRIM(CLIND))
  ENDDO
ENDIF

END SUBROUTINE

END SUBMODULE
