SUBMODULE (TYPE_GEOMETRY) TYPE_GEOMETRY_GEOMETRY_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE COPY_GEOMETRY (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (GEOMETRY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LYRELBC_GEO

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

CALL SELF%YRVERT_GEOM%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRSTA%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRLAP%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRCSGLEG%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRDIM%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRDIMV%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRMP%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRGEM%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YROROG_B%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSPGEOM%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVABIO%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YREDIM%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YREGEO%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YREMP%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRELAP%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YREGSL%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LYRELBC_GEO = ASSOCIATED (SELF%YRELBC_GEO)
IF (LYRELBC_GEO) THEN
  !$ACC ENTER DATA CREATE (SELF%YRELBC_GEO)
  !$ACC UPDATE DEVICE (SELF%YRELBC_GEO)
  CALL SELF%YRELBC_GEO%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (SELF%YRELBC_GEO)
ENDIF

END SUBROUTINE

END SUBMODULE
