SUBMODULE (TYPE_MODEL) TYPE_MODEL_MODEL_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE SAVE_MODEL (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LYRCST
WRITE (KLUN) SELF%LINEAR_MODEL
CALL SELF%YRML_GCONF%SAVE (KLUN)
CALL SELF%YRML_AOC%SAVE (KLUN)
CALL SELF%YRML_DYN%SAVE (KLUN)
CALL SELF%YRML_PHY_G%SAVE (KLUN)
CALL SELF%YRML_PHY_EC%SAVE (KLUN)
CALL SELF%YRML_PHY_SLIN%SAVE (KLUN)
CALL SELF%YRML_PHY_AER%SAVE (KLUN)
CALL SELF%YRML_PHY_RAD%SAVE (KLUN)
CALL SELF%YRML_PHY_STOCH%SAVE (KLUN)
CALL SELF%YRML_PHY_MF%SAVE (KLUN)
CALL SELF%YRML_CHEM%SAVE (KLUN)
CALL SELF%YRML_DIAG%SAVE (KLUN)
CALL SELF%YREWCOU%SAVE (KLUN)
LYRCST = ASSOCIATED (SELF%YRCST)
WRITE (KLUN) LYRCST
IF (LYRCST) THEN
  CALL SELF%YRCST%SAVE (KLUN)
ENDIF
CALL SELF%YRML_LBC%SAVE (KLUN)
WRITE (KLUN) SELF%MOBJECT_ID
WRITE (KLUN) SELF%COBJECT_ID
END SUBROUTINE

END SUBMODULE
