SUBMODULE (TYPE_MODEL) TYPE_MODEL_MODEL_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_MODEL (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (MODEL), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LYRCST
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LINEAR_MODEL), CDPATH//'%LINEAR_MODEL'

CLIND = ''
CALL SELF%YRML_GCONF%ACDC_CRC64 (KLUN, CDPATH//'%YRML_GCONF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_AOC%ACDC_CRC64 (KLUN, CDPATH//'%YRML_AOC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_DYN%ACDC_CRC64 (KLUN, CDPATH//'%YRML_DYN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_PHY_G%ACDC_CRC64 (KLUN, CDPATH//'%YRML_PHY_G'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_PHY_EC%ACDC_CRC64 (KLUN, CDPATH//'%YRML_PHY_EC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_PHY_SLIN%ACDC_CRC64 (KLUN, CDPATH//'%YRML_PHY_SLIN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_PHY_AER%ACDC_CRC64 (KLUN, CDPATH//'%YRML_PHY_AER'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_PHY_RAD%ACDC_CRC64 (KLUN, CDPATH//'%YRML_PHY_RAD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_PHY_STOCH%ACDC_CRC64 (KLUN, CDPATH//'%YRML_PHY_STOCH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_PHY_MF%ACDC_CRC64 (KLUN, CDPATH//'%YRML_PHY_MF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_CHEM%ACDC_CRC64 (KLUN, CDPATH//'%YRML_CHEM'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRML_DIAG%ACDC_CRC64 (KLUN, CDPATH//'%YRML_DIAG'//TRIM(CLIND))

CLIND = ''
CALL SELF%YREWCOU%ACDC_CRC64 (KLUN, CDPATH//'%YREWCOU'//TRIM(CLIND))

LYRCST = ASSOCIATED (SELF%YRCST)
IF (LYRCST) THEN
  CLIND = ''
  CALL SELF%YRCST%ACDC_CRC64 (KLUN, CDPATH//'%YRCST'//TRIM(CLIND))
ENDIF

CLIND = ''
CALL SELF%YRML_LBC%ACDC_CRC64 (KLUN, CDPATH//'%YRML_LBC'//TRIM(CLIND))

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MOBJECT_ID), CDPATH//'%MOBJECT_ID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%COBJECT_ID), CDPATH//'%COBJECT_ID'

END SUBROUTINE

END SUBMODULE
