!> geometry derived type for the IFS model
!> separated from geometry_mod to break dependency issues with sugeometry

MODULE TYPE_GEOMETRY

!$ACDC methods  --skip-components GEOMETRY%YRCSGEOMAD,GEOMETRY%YRGSGEOMAD,GEOMETRY%YROROG,GEOMETRY%YRCSGEOMAD_NB,GEOMETRY%YRGSGEOMAD_NB,GEOMETRY%YRCSGEOM_NB,GEOMETRY%YRCSGEOM,GEOMETRY%YRCSGEOM_B,GEOMETRY%YRGSGEOM_NB,GEOMETRY%YRGSGEOM,GEOMETRY%YRGSGEOM_B


USE YOMVERT    , ONLY : TVAB, TVETA, TVFE, TVERTICAL_GEOM
USE YOMSTA     , ONLY : TSTA
USE YOMLAP     , ONLY : TLAP
USE YOMLEG     , ONLY : TCSGLEG
USE YOMDIM     , ONLY : TDIM
USE YOMDIMV    , ONLY : TDIMV
USE YOMMP      , ONLY : TMP
USE YOMGEM     , ONLY : TGEM
USE YOMCSGEOM  , ONLY : TCSGEOM, TCSGEOM_BLOCKED
USE YOMGSGEOM  , ONLY : TGSGEOM, TGSGEOM_BLOCKED
USE YOMOROG    , ONLY : TOROG,   TOROG_BLOCKED
USE TYPE_SPGEOM, ONLY : TSPGEOM
#ifdef WITH_ATLAS
USE YOMATLAS   , ONLY : TATLAS
#endif
! LAM specific objects
USE YEMDIM     , ONLY : TEDIM
USE YEMGEO     , ONLY : TEGEO
USE YEMMP      , ONLY : TEMMP
USE YEMLAP     , ONLY : TLEP
USE YEMGSL     , ONLY : TEGSL
!
USE YEMLBC_GEO , ONLY : TELBC_GEO
!
USE YOMCVER , ONLY : TCVER


IMPLICIT NONE 

PRIVATE

TYPE, PUBLIC :: GEOMETRY
  LOGICAL          :: LNHX_GEOM
  TYPE(TVERTICAL_GEOM) :: YRVERT_GEOM

  TYPE(TSTA)    :: YRSTA
  TYPE(TLAP)    :: YRLAP
  TYPE(TCSGLEG) :: YRCSGLEG

  TYPE(TDIM)    :: YRDIM
  TYPE(TDIMV)   :: YRDIMV
  TYPE(TMP)     :: YRMP
  TYPE(TGEM)    :: YRGEM


  TYPE(TCSGEOM)          :: YRCSGEOM_NB
  TYPE(TCSGEOM), POINTER :: YRCSGEOM(:) => NULL()
  TYPE(TCSGEOM_BLOCKED)  :: YRCSGEOM_B

  TYPE(TGSGEOM)          :: YRGSGEOM_NB
  TYPE(TGSGEOM), POINTER :: YRGSGEOM(:) => NULL() 
  TYPE(TGSGEOM_BLOCKED)  :: YRGSGEOM_B

  LOGICAL                    :: AD_GEOM = .FALSE.
  TYPE(TCSGEOM)              :: YRCSGEOMAD_NB
  TYPE(TCSGEOM), POINTER     :: YRCSGEOMAD(:) => NULL()
  TYPE(TGSGEOM)              :: YRGSGEOMAD_NB
  TYPE(TGSGEOM), POINTER     :: YRGSGEOMAD(:) => NULL()


  TYPE(TOROG), ALLOCATABLE :: YROROG(:)
  TYPE(TOROG_BLOCKED)      :: YROROG_B

  TYPE(TSPGEOM) :: YSPGEOM

#ifdef WITH_ATLAS
  TYPE(TATLAS),  POINTER :: YRATLAS => NULL()
#endif

  TYPE(TVAB)    :: YVABIO ! I/O full vertical hybrid coordinates 0->NIOLEVG (NIOLEVG >=NFLEVG)

  ! LAM specific objects
  TYPE(TEDIM) :: YREDIM
  TYPE(TEGEO) :: YREGEO
  TYPE(TEMMP) :: YREMP
  TYPE(TLEP)  :: YRELAP
  TYPE(TEGSL) :: YREGSL
!
  TYPE(TELBC_GEO), POINTER :: YRELBC_GEO => NULL()
!

CONTAINS

FINAL :: GEOMETRY_FINAL

PROCEDURE :: ACDC_COPY => ACDC_COPY_GEOMETRY
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_GEOMETRY
PROCEDURE :: ACDC_HOST => ACDC_HOST_GEOMETRY
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_GEOMETRY
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_GEOMETRY
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_GEOMETRY
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_GEOMETRY
END TYPE GEOMETRY

INTERFACE

MODULE SUBROUTINE ACDC_COPY_GEOMETRY (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (GEOMETRY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_GEOMETRY (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (GEOMETRY), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_GEOMETRY (SELF)

IMPLICIT NONE
CLASS (GEOMETRY), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_GEOMETRY (SELF, KLUN)

IMPLICIT NONE
CLASS (GEOMETRY), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_GEOMETRY (SELF, KLUN)

IMPLICIT NONE
CLASS (GEOMETRY), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_GEOMETRY (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (GEOMETRY),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_GEOMETRY (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (GEOMETRY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

CONTAINS

SUBROUTINE GEOMETRY_FINAL(THIS)
  TYPE(GEOMETRY) :: THIS
  ! If we don't add this, we may get a internal compiler error
END SUBROUTINE GEOMETRY_FINAL

END MODULE TYPE_GEOMETRY
