SUBMODULE (TYPE_SPGEOM) TYPE_SPGEOM_TSPGEOM_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TSPGEOM (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TSPGEOM), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LGMR, LSCGMAP
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GMR), CDPATH//'%GMR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SCGMAP), CDPATH//'%SCGMAP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ESCGMAP), CDPATH//'%ESCGMAP'

END SUBROUTINE

END SUBMODULE
