SUBMODULE (TYPE_ECV) TYPE_ECV_TECVGRIB_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_TECVGRIB (SELF)

IMPLICIT NONE
CLASS (TECVGRIB), TARGET :: SELF
LOGICAL :: LMECVGRB_1D, LMECVGRB_2D, LMECVGRB_3D, LMECVGRB_ALL

END SUBROUTINE

END SUBMODULE
