SUBMODULE (YEMDYN) YEMDYN_TEDYN_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TEDYN (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEDYN),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LRDIDIVE, LRDIGFLE, LRDIPDE, LRDISPE, LRDITE, LRDIVDE, LRDIVORE, LRDSDIVE, LRDSVDE, LRDSVORE
LOGICAL :: LREFILD, LREFILV
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LRDIVORE = ALLOCATED (SELF%RDIVORE)
IF (LRDIVORE) THEN
  ISIZE = KIND (SELF%RDIVORE) * SIZE (SELF%RDIVORE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDIVORE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRDIDIVE = ALLOCATED (SELF%RDIDIVE)
IF (LRDIDIVE) THEN
  ISIZE = KIND (SELF%RDIDIVE) * SIZE (SELF%RDIDIVE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDIDIVE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRDITE = ALLOCATED (SELF%RDITE)
IF (LRDITE) THEN
  ISIZE = KIND (SELF%RDITE) * SIZE (SELF%RDITE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDITE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRDIGFLE = ALLOCATED (SELF%RDIGFLE)
IF (LRDIGFLE) THEN
  ISIZE = KIND (SELF%RDIGFLE) * SIZE (SELF%RDIGFLE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDIGFLE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRDIPDE = ALLOCATED (SELF%RDIPDE)
IF (LRDIPDE) THEN
  ISIZE = KIND (SELF%RDIPDE) * SIZE (SELF%RDIPDE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDIPDE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRDIVDE = ALLOCATED (SELF%RDIVDE)
IF (LRDIVDE) THEN
  ISIZE = KIND (SELF%RDIVDE) * SIZE (SELF%RDIVDE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDIVDE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRDISPE = ALLOCATED (SELF%RDISPE)
IF (LRDISPE) THEN
  ISIZE = KIND (SELF%RDISPE) * SIZE (SELF%RDISPE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDISPE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRDSVORE = ALLOCATED (SELF%RDSVORE)
IF (LRDSVORE) THEN
  ISIZE = KIND (SELF%RDSVORE) * SIZE (SELF%RDSVORE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDSVORE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRDSDIVE = ALLOCATED (SELF%RDSDIVE)
IF (LRDSDIVE) THEN
  ISIZE = KIND (SELF%RDSDIVE) * SIZE (SELF%RDSDIVE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDSDIVE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRDSVDE = ALLOCATED (SELF%RDSVDE)
IF (LRDSVDE) THEN
  ISIZE = KIND (SELF%RDSVDE) * SIZE (SELF%RDSVDE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RDSVDE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LREFILV = ALLOCATED (SELF%REFILV)
IF (LREFILV) THEN
  ISIZE = KIND (SELF%REFILV) * SIZE (SELF%REFILV)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%REFILV'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LREFILD = ALLOCATED (SELF%REFILD)
IF (LREFILD) THEN
  ISIZE = KIND (SELF%REFILD) * SIZE (SELF%REFILD)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%REFILD'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%LESIDG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LESIDG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RTHRESIDG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTHRESIDG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XMALD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XMALD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TCDIS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TCDIS'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
