SUBMODULE (YEMGEO) YEMGEO_TEGEO_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TEGEO (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEGEO),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%ERPK)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ERPK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELON1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELON1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELAT1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELAT1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELON2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELON2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELAT2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELAT2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELON0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELON0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELAT0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELAT0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELONC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELONC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELATC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELATC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EDELX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EDELX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EDELY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EDELY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EXWN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EXWN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EYWN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EYWN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCORI_ACAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCORI_ACAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLAT_ACAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLAT_ACAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLON_ACAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLON_ACAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMAP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMAP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMRT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMRT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LREDEL_IN_METRES)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LREDEL_IN_METRES'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
