SUBMODULE (YEMLBC_MODEL) YEMLBC_MODEL_TGMVSCPL_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TGMVSCPL (SELF, KLUN)

IMPLICIT NONE
CLASS (TGMVSCPL), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%MSP
READ (KLUN) SELF%MSPL
READ (KLUN) SELF%MSPM
READ (KLUN) SELF%NDIM
READ (KLUN) SELF%NDIMT
END SUBROUTINE

END SUBMODULE
