SUBMODULE (YEMLAP) YEMLAP_TLEP_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TLEP (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TLEP),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LMVALUE, LNCPL2M, LNCPL2N, LNCPL4M, LNCPL4N, LNCPLM, LNCPLN, LNESM0, LNESM0G, LNESPZERO
LOGICAL :: LNPME, LNPNE, LRLEPDIM, LRLEPDIN, LRLEPINM, LRLEPINN
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LNCPL2M = ALLOCATED (SELF%NCPL2M)
IF (LNCPL2M) THEN
  ISIZE = KIND (SELF%NCPL2M) * SIZE (SELF%NCPL2M)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NCPL2M'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNCPL4M = ALLOCATED (SELF%NCPL4M)
IF (LNCPL4M) THEN
  ISIZE = KIND (SELF%NCPL4M) * SIZE (SELF%NCPL4M)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NCPL4M'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNCPLM = ALLOCATED (SELF%NCPLM)
IF (LNCPLM) THEN
  ISIZE = KIND (SELF%NCPLM) * SIZE (SELF%NCPLM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NCPLM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNCPL2N = ALLOCATED (SELF%NCPL2N)
IF (LNCPL2N) THEN
  ISIZE = KIND (SELF%NCPL2N) * SIZE (SELF%NCPL2N)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NCPL2N'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNCPL4N = ALLOCATED (SELF%NCPL4N)
IF (LNCPL4N) THEN
  ISIZE = KIND (SELF%NCPL4N) * SIZE (SELF%NCPL4N)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NCPL4N'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNCPLN = ALLOCATED (SELF%NCPLN)
IF (LNCPLN) THEN
  ISIZE = KIND (SELF%NCPLN) * SIZE (SELF%NCPLN)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NCPLN'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLEPDIN = ALLOCATED (SELF%RLEPDIN)
IF (LRLEPDIN) THEN
  ISIZE = KIND (SELF%RLEPDIN) * SIZE (SELF%RLEPDIN)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLEPDIN'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLEPINN = ALLOCATED (SELF%RLEPINN)
IF (LRLEPINN) THEN
  ISIZE = KIND (SELF%RLEPINN) * SIZE (SELF%RLEPINN)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLEPINN'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLEPDIM = ALLOCATED (SELF%RLEPDIM)
IF (LRLEPDIM) THEN
  ISIZE = KIND (SELF%RLEPDIM) * SIZE (SELF%RLEPDIM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLEPDIM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLEPINM = ALLOCATED (SELF%RLEPINM)
IF (LRLEPINM) THEN
  ISIZE = KIND (SELF%RLEPINM) * SIZE (SELF%RLEPINM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLEPINM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNESM0 = ALLOCATED (SELF%NESM0)
IF (LNESM0) THEN
  ISIZE = KIND (SELF%NESM0) * SIZE (SELF%NESM0)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NESM0'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNESPZERO = ALLOCATED (SELF%NESPZERO)
IF (LNESPZERO) THEN
  ISIZE = KIND (SELF%NESPZERO) * SIZE (SELF%NESPZERO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NESPZERO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNESM0G = ALLOCATED (SELF%NESM0G)
IF (LNESM0G) THEN
  ISIZE = KIND (SELF%NESM0G) * SIZE (SELF%NESM0G)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NESM0G'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPME = ALLOCATED (SELF%NPME)
IF (LNPME) THEN
  ISIZE = KIND (SELF%NPME) * SIZE (SELF%NPME)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPME'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPNE = ALLOCATED (SELF%NPNE)
IF (LNPNE) THEN
  ISIZE = KIND (SELF%NPNE) * SIZE (SELF%NPNE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPNE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMVALUE = ALLOCATED (SELF%MVALUE)
IF (LMVALUE) THEN
  ISIZE = KIND (SELF%MVALUE) * SIZE (SELF%MVALUE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MVALUE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END SUBMODULE
