SUBMODULE (YEMMP) YEMMP_TEMMP_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_TEMMP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEMMP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMYENS, LNEALLNS, LNEPROCN, LNEPTRNS, LNUEMPP
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LNEPROCN = ASSOCIATED (SELF%NEPROCN)
IF (LNEPROCN) THEN
  !$ACC ENTER DATA CREATE (SELF%NEPROCN)
  !$ACC UPDATE DEVICE (SELF%NEPROCN)
  !$ACC ENTER DATA ATTACH (SELF%NEPROCN)
ENDIF

LMYENS = ASSOCIATED (SELF%MYENS)
IF (LMYENS) THEN
  !$ACC ENTER DATA CREATE (SELF%MYENS)
  !$ACC UPDATE DEVICE (SELF%MYENS)
  !$ACC ENTER DATA ATTACH (SELF%MYENS)
ENDIF

LNUEMPP = ASSOCIATED (SELF%NUEMPP)
IF (LNUEMPP) THEN
  !$ACC ENTER DATA CREATE (SELF%NUEMPP)
  !$ACC UPDATE DEVICE (SELF%NUEMPP)
  !$ACC ENTER DATA ATTACH (SELF%NUEMPP)
ENDIF

LNEALLNS = ASSOCIATED (SELF%NEALLNS)
IF (LNEALLNS) THEN
  !$ACC ENTER DATA CREATE (SELF%NEALLNS)
  !$ACC UPDATE DEVICE (SELF%NEALLNS)
  !$ACC ENTER DATA ATTACH (SELF%NEALLNS)
ENDIF

LNEPTRNS = ASSOCIATED (SELF%NEPTRNS)
IF (LNEPTRNS) THEN
  !$ACC ENTER DATA CREATE (SELF%NEPTRNS)
  !$ACC UPDATE DEVICE (SELF%NEPTRNS)
  !$ACC ENTER DATA ATTACH (SELF%NEPTRNS)
ENDIF

END SUBROUTINE

END SUBMODULE
