SUBMODULE (YEMMP) YEMMP_TEMMP_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TEMMP (SELF, KLUN)

IMPLICIT NONE
CLASS (TEMMP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LMYENS, LNEALLNS, LNEPROCN, LNEPTRNS, LNUEMPP
LNEPROCN = ASSOCIATED (SELF%NEPROCN)
WRITE (KLUN) LNEPROCN
IF (LNEPROCN) THEN
  WRITE (KLUN) LBOUND (SELF%NEPROCN)
  WRITE (KLUN) UBOUND (SELF%NEPROCN)
  WRITE (KLUN) SELF%NEPROCN
ENDIF
WRITE (KLUN) SELF%NUEMP
LMYENS = ASSOCIATED (SELF%MYENS)
WRITE (KLUN) LMYENS
IF (LMYENS) THEN
  WRITE (KLUN) LBOUND (SELF%MYENS)
  WRITE (KLUN) UBOUND (SELF%MYENS)
  WRITE (KLUN) SELF%MYENS
ENDIF
LNUEMPP = ASSOCIATED (SELF%NUEMPP)
WRITE (KLUN) LNUEMPP
IF (LNUEMPP) THEN
  WRITE (KLUN) LBOUND (SELF%NUEMPP)
  WRITE (KLUN) UBOUND (SELF%NUEMPP)
  WRITE (KLUN) SELF%NUEMPP
ENDIF
LNEALLNS = ASSOCIATED (SELF%NEALLNS)
WRITE (KLUN) LNEALLNS
IF (LNEALLNS) THEN
  WRITE (KLUN) LBOUND (SELF%NEALLNS)
  WRITE (KLUN) UBOUND (SELF%NEALLNS)
  WRITE (KLUN) SELF%NEALLNS
ENDIF
LNEPTRNS = ASSOCIATED (SELF%NEPTRNS)
WRITE (KLUN) LNEPTRNS
IF (LNEPTRNS) THEN
  WRITE (KLUN) LBOUND (SELF%NEPTRNS)
  WRITE (KLUN) UBOUND (SELF%NEPTRNS)
  WRITE (KLUN) SELF%NEPTRNS
ENDIF
END SUBROUTINE

END SUBMODULE
