MODULE YEMMP

!$ACDC methods 


USE PARKIND1  ,ONLY : JPIM

IMPLICIT NONE

SAVE

!  ---------------------------------------------------------------------
!  C. Fischer : 99-06-11

!* store extra setup to perform distributed work along the efficient
!* wavenumber kstar in aladin 3d-var 

!  NEPROCN: number of the processor which possesses global kstar
!  NUEMP  : number of kstars treated in this processor
!  MYENS  : array containing those kstars (in 0:nsmax) treated in this proc
!  NUEMPP : array containing the number of kstars treated proc by proc
!  NEALLNS: array containing in a row the values of kstars proc by proc
!  NEPTRNS: pointer into neallns


TYPE :: TEMMP
  INTEGER(KIND=JPIM), POINTER :: NEPROCN(:) => NULL()
  INTEGER(KIND=JPIM) :: NUEMP
  INTEGER(KIND=JPIM), POINTER :: MYENS(:) => NULL()
  INTEGER(KIND=JPIM), POINTER :: NUEMPP(:) => NULL()
  INTEGER(KIND=JPIM), POINTER :: NEALLNS(:) => NULL()
  INTEGER(KIND=JPIM), POINTER :: NEPTRNS(:) => NULL()
CONTAINS
PROCEDURE :: ACDC_COPY => ACDC_COPY_TEMMP
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TEMMP
PROCEDURE :: ACDC_HOST => ACDC_HOST_TEMMP
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TEMMP
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TEMMP
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TEMMP
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TEMMP
END TYPE TEMMP

!  ---------------------------------------------------------------------
INTERFACE

MODULE SUBROUTINE ACDC_COPY_TEMMP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEMMP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TEMMP (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TEMMP), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TEMMP (SELF)

IMPLICIT NONE
CLASS (TEMMP), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TEMMP (SELF, KLUN)

IMPLICIT NONE
CLASS (TEMMP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TEMMP (SELF, KLUN)

IMPLICIT NONE
CLASS (TEMMP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TEMMP (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEMMP),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TEMMP (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEMMP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YEMMP
