SUBMODULE (YOE_SPECTRAL_PLANCK) YOE_SPECTRAL_PLANCK_TSPECTRALPLANCK_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_TSPECTRALPLANCK (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TSPECTRALPLANCK), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LPLANCK_LUT = ALLOCATED (SELF%PLANCK_LUT)
IF (LPLANCK_LUT) THEN
  !$ACC ENTER DATA CREATE (SELF%PLANCK_LUT)
  !$ACC UPDATE DEVICE (SELF%PLANCK_LUT)
  !$ACC ENTER DATA ATTACH (SELF%PLANCK_LUT)
ENDIF

LWAVLEN_BOUND = ALLOCATED (SELF%WAVLEN_BOUND)
IF (LWAVLEN_BOUND) THEN
  !$ACC ENTER DATA CREATE (SELF%WAVLEN_BOUND)
  !$ACC UPDATE DEVICE (SELF%WAVLEN_BOUND)
  !$ACC ENTER DATA ATTACH (SELF%WAVLEN_BOUND)
ENDIF

LINTERVAL_MAP = ALLOCATED (SELF%INTERVAL_MAP)
IF (LINTERVAL_MAP) THEN
  !$ACC ENTER DATA CREATE (SELF%INTERVAL_MAP)
  !$ACC UPDATE DEVICE (SELF%INTERVAL_MAP)
  !$ACC ENTER DATA ATTACH (SELF%INTERVAL_MAP)
ENDIF

END SUBROUTINE

END SUBMODULE
