SUBMODULE (YOEAERD) YOEAERD_TEAERD_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TEAERD (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TEAERD), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LCVDAED, LCVDAEL, LCVDAES, LCVDAEU
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CVDAES), CDPATH//'%CVDAES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CVDAEL), CDPATH//'%CVDAEL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CVDAEU), CDPATH//'%CVDAEU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CVDAED), CDPATH//'%CVDAED'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAESC), CDPATH//'%RAESC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAESS), CDPATH//'%RAESS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAELC), CDPATH//'%RAELC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAELS), CDPATH//'%RAELS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAEUC), CDPATH//'%RAEUC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAEUS), CDPATH//'%RAEUS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAEDC), CDPATH//'%RAEDC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAEDS), CDPATH//'%RAEDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCAEOPS), CDPATH//'%RCAEOPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCAEOPL), CDPATH//'%RCAEOPL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCAEOPU), CDPATH//'%RCAEOPU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCAEOPD), CDPATH//'%RCAEOPD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCTRBGA), CDPATH//'%RCTRBGA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCVOBGA), CDPATH//'%RCVOBGA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCSTBGA), CDPATH//'%RCSTBGA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCTRPT), CDPATH//'%RCTRPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCAEADK), CDPATH//'%RCAEADK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCAEADM), CDPATH//'%RCAEADM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCAEROS), CDPATH//'%RCAEROS'

END SUBROUTINE

END SUBMODULE
