MODULE YOEDBUG

!$ACDC methods 


USE PARKIND1  ,ONLY : JPIM

IMPLICIT NONE

SAVE

!     -------------------------------------------------
!*    ** *YOEDBUG* - CONTROL OPTIONS FOR DEBUGGING HELP
!     -------------------------------------------------

TYPE :: TEDBUG
INTEGER(KIND=JPIM) :: KSTPDBG(10), NSTPDBG
CONTAINS
PROCEDURE :: ACDC_COPY => ACDC_COPY_TEDBUG
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TEDBUG
PROCEDURE :: ACDC_HOST => ACDC_HOST_TEDBUG
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TEDBUG
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TEDBUG
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TEDBUG
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TEDBUG
END TYPE TEDBUG

!!TYPE(TEDBUG), POINTER :: YREDBUG => NULL()

!     ------------------------------------------------------------------
INTERFACE

MODULE SUBROUTINE ACDC_COPY_TEDBUG (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEDBUG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TEDBUG (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TEDBUG), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TEDBUG (SELF)

IMPLICIT NONE
CLASS (TEDBUG), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TEDBUG (SELF, KLUN)

IMPLICIT NONE
CLASS (TEDBUG), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TEDBUG (SELF, KLUN)

IMPLICIT NONE
CLASS (TEDBUG), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TEDBUG (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEDBUG),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TEDBUG (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEDBUG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YOEDBUG

