SUBMODULE (YOEGWD) YOEGWD_TEGWD_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TEGWD (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEGWD),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NKTOPG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKTOPG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NGWDLIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGWDLIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NGWDTOP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGWDTOP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDIFF_STRATO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDIFF_STRATO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GFRCRIT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GFRCRIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GRCRIT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GRCRIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GKDRAG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GKDRAG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GKWAKE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GKWAKE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GSSEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GSSEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GTSEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GTSEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GVSEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GVSEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GTENLIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GTENLIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GRFPLM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GRFPLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LRDIFF_STRATO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRDIFF_STRATO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LDIAG_STRATO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDIAG_STRATO'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
