SUBMODULE (YOEGWWMS) YOEGWWMS_TEGWWMS_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TEGWWMS (SELF, KLUN)

IMPLICIT NONE
CLASS (TEGWWMS), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LOZPR
WRITE (KLUN) SELF%LGACALC
WRITE (KLUN) SELF%LGSATL
WRITE (KLUN) SELF%LGINDL
WRITE (KLUN) SELF%NLAUNCHL
WRITE (KLUN) SELF%NLAUNCHLEV
WRITE (KLUN) SELF%NLAUNCH
WRITE (KLUN) SELF%NSLOPE
WRITE (KLUN) SELF%NGAUSS
WRITE (KLUN) SELF%GFLUXLAUNL
WRITE (KLUN) SELF%GFLUXLAUN
WRITE (KLUN) SELF%GMSTAR_L
WRITE (KLUN) SELF%GCSTAR
WRITE (KLUN) SELF%GPTWO
WRITE (KLUN) SELF%GTPHYGWWMS
WRITE (KLUN) SELF%GGAUSSA
WRITE (KLUN) SELF%GGAUSSB
WRITE (KLUN) SELF%GCOEFF
END SUBROUTINE

END SUBMODULE
