SUBMODULE (YOESW) YOESW_TESWRT_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TESWRT (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TESWRT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LRSUN, LRSUN2
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%APAD), CDPATH//'%APAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BPAD), CDPATH//'%BPAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRAY), CDPATH//'%RRAY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSUN), CDPATH//'%RSUN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSUN2), CDPATH//'%RSUN2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPDH1), CDPATH//'%RPDH1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPDU1), CDPATH//'%RPDU1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPNH), CDPATH//'%RPNH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPNU), CDPATH//'%RPNU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSWCE), CDPATH//'%RSWCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSWCP), CDPATH//'%RSWCP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTDH2O), CDPATH//'%RTDH2O'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTDUMG), CDPATH//'%RTDUMG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTH2O), CDPATH//'%RTH2O'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTUMG), CDPATH//'%RTUMG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%D), CDPATH//'%D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REXPO3), CDPATH//'%REXPO3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NEXPO3), CDPATH//'%NEXPO3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RYFWCA), CDPATH//'%RYFWCA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RYFWCB), CDPATH//'%RYFWCB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RYFWCC), CDPATH//'%RYFWCC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RYFWCD), CDPATH//'%RYFWCD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RYFWCE), CDPATH//'%RYFWCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RYFWCF), CDPATH//'%RYFWCF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUA), CDPATH//'%REBCUA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUB), CDPATH//'%REBCUB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUC), CDPATH//'%REBCUC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUD), CDPATH//'%REBCUD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUE), CDPATH//'%REBCUE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUF), CDPATH//'%REBCUF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUG), CDPATH//'%REBCUG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUH), CDPATH//'%REBCUH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUI), CDPATH//'%REBCUI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REBCUJ), CDPATH//'%REBCUJ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RASWCA), CDPATH//'%RASWCA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RASWCB), CDPATH//'%RASWCB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RASWCC), CDPATH//'%RASWCC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RASWCD), CDPATH//'%RASWCD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RASWCE), CDPATH//'%RASWCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RASWCF), CDPATH//'%RASWCF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKPNWCA), CDPATH//'%RKPNWCA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKPNWCB), CDPATH//'%RKPNWCB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKPNWCC), CDPATH//'%RKPNWCC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKPNWCD), CDPATH//'%RKPNWCD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKPNWCE), CDPATH//'%RKPNWCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKPNWCF), CDPATH//'%RKPNWCF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKPNWCG), CDPATH//'%RKPNWCG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKPNWCH), CDPATH//'%RKPNWCH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUETA), CDPATH//'%RFUETA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUETB), CDPATH//'%RFUETB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUETC), CDPATH//'%RFUETC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFULIO), CDPATH//'%RFULIO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHSAVI), CDPATH//'%RHSAVI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLILIA), CDPATH//'%RLILIA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLILIB), CDPATH//'%RLILIB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKPNLWCA), CDPATH//'%RKPNLWCA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLAA0), CDPATH//'%RFLAA0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLAA1), CDPATH//'%RFLAA1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLBB0), CDPATH//'%RFLBB0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLBB1), CDPATH//'%RFLBB1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLBB2), CDPATH//'%RFLBB2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLBB3), CDPATH//'%RFLBB3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLCC0), CDPATH//'%RFLCC0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLCC1), CDPATH//'%RFLCC1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLCC2), CDPATH//'%RFLCC2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLCC3), CDPATH//'%RFLCC3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUAA0), CDPATH//'%RFUAA0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUAA1), CDPATH//'%RFUAA1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUBB0), CDPATH//'%RFUBB0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUBB1), CDPATH//'%RFUBB1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUBB2), CDPATH//'%RFUBB2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUBB3), CDPATH//'%RFUBB3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUCC0), CDPATH//'%RFUCC0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUCC1), CDPATH//'%RFUCC1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUCC2), CDPATH//'%RFUCC2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFUCC3), CDPATH//'%RFUCC3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLDD0), CDPATH//'%RFLDD0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLDD1), CDPATH//'%RFLDD1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLDD2), CDPATH//'%RFLDD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFLDD3), CDPATH//'%RFLDD3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REFFIA), CDPATH//'%REFFIA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTAUA), CDPATH//'%RTAUA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPIZA), CDPATH//'%RPIZA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCGA), CDPATH//'%RCGA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAER), CDPATH//'%RAER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NMPSRTM), CDPATH//'%NMPSRTM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NTYPS), CDPATH//'%NTYPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RADJUST), CDPATH//'%RADJUST'

END SUBROUTINE

END SUBMODULE
