SUBMODULE (YOESW) YOESW_TESWRT_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_TESWRT (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TESWRT), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRSUN, LRSUN2
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LRSUN = ALLOCATED (SELF%RSUN)
IF (LRSUN) THEN
  !$ACC ENTER DATA CREATE (SELF%RSUN)
  !$ACC UPDATE DEVICE (SELF%RSUN)
  !$ACC ENTER DATA ATTACH (SELF%RSUN)
ENDIF

LRSUN2 = ALLOCATED (SELF%RSUN2)
IF (LRSUN2) THEN
  !$ACC ENTER DATA CREATE (SELF%RSUN2)
  !$ACC UPDATE DEVICE (SELF%RSUN2)
  !$ACC ENTER DATA ATTACH (SELF%RSUN2)
ENDIF

END SUBROUTINE

END SUBMODULE
