SUBMODULE (YOMCSGEOM) YOMCSGEOM_TCSGEOM_BLOCKED_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_TCSGEOM_BLOCKED (SELF)

IMPLICIT NONE
CLASS (TCSGEOM_BLOCKED), TARGET :: SELF
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON

END SUBROUTINE

END SUBMODULE
