SUBMODULE (YOMCAPE) YOMCAPE_TCAPE_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TCAPE (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TCAPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%NCAPEITER
READ (KLUN) SELF%NETAPES
READ (KLUN) SELF%NCAPEPSD
READ (KLUN) ZTMP0
SELF%GCAPERET = ZTMP0
READ (KLUN) ZTMP0
SELF%GCAPEPSD = ZTMP0
READ (KLUN) ZTMP0
SELF%GMISCINV = ZTMP0
READ (KLUN) ZTMP0
SELF%GCAPEMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GCINMAX = ZTMP0
READ (KLUN) SELF%LADAE
READ (KLUN) SELF%LMCAPEA
END SUBROUTINE

END SUBMODULE
