SUBMODULE (YOMCOMPO) YOMCOMPO_TCOMPO_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TCOMPO (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TCOMPO),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
INTEGER :: J1
LOGICAL :: LYEMIS2DAUX_DESC, LYEMIS2D_DESC, LYEMIS3D_DESC
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%LCHEM_DIA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCHEM_DIA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCHEM_DIA_PERIOD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCHEM_DIA_PERIOD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCHEM_DDFLX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCHEM_DDFLX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCOMPO_DDFLX_DIR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOMPO_DDFLX_DIR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCHEM_TROPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCHEM_TROPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LAEREQSAM4CLIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAEREQSAM4CLIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LAEROSFC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAEROSFC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCOMPO_DCDD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOMPO_DCDD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LAERNITRATE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAERNITRATE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LAERRESUSPENSION)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAERRESUSPENSION'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LAERSOA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAERSOA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LAERSOA_COUPLED)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAERSOA_COUPLED'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%KGHG_CHEMTEND_CH4)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%KGHG_CHEMTEND_CH4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LAERNUCL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAERNUCL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%AERO_SCHEME) * LEN (SELF%AERO_SCHEME)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%AERO_SCHEME'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NEMIS2D_DESC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NEMIS2D_DESC'
ENDIF
KSIZE = KSIZE + ISIZE
LYEMIS2D_DESC = ALLOCATED (SELF%YEMIS2D_DESC)
IF (LYEMIS2D_DESC) THEN
  JSIZE = 0
  DO J1 = LBOUND (SELF%YEMIS2D_DESC, 1), UBOUND (SELF%YEMIS2D_DESC, 1)
    ISIZE = SELF%YEMIS2D_DESC (J1)%ACDC_SIZE (CLPATH//'%YEMIS2D_DESC', .FALSE.)
    JSIZE = JSIZE + ISIZE
    KSIZE = KSIZE + ISIZE
  ENDDO
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
    WRITE (*, *) TRIM (CLPATH)//'%YEMIS2D_DESC'
  ENDIF
ENDIF
ISIZE = KIND (SELF%NEMIS3D_DESC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NEMIS3D_DESC'
ENDIF
KSIZE = KSIZE + ISIZE
LYEMIS3D_DESC = ALLOCATED (SELF%YEMIS3D_DESC)
IF (LYEMIS3D_DESC) THEN
  JSIZE = 0
  DO J1 = LBOUND (SELF%YEMIS3D_DESC, 1), UBOUND (SELF%YEMIS3D_DESC, 1)
    ISIZE = SELF%YEMIS3D_DESC (J1)%ACDC_SIZE (CLPATH//'%YEMIS3D_DESC', .FALSE.)
    JSIZE = JSIZE + ISIZE
    KSIZE = KSIZE + ISIZE
  ENDDO
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
    WRITE (*, *) TRIM (CLPATH)//'%YEMIS3D_DESC'
  ENDIF
ENDIF
LYEMIS2DAUX_DESC = ALLOCATED (SELF%YEMIS2DAUX_DESC)
IF (LYEMIS2DAUX_DESC) THEN
  JSIZE = 0
  DO J1 = LBOUND (SELF%YEMIS2DAUX_DESC, 1), UBOUND (SELF%YEMIS2DAUX_DESC, 1)
    ISIZE = SELF%YEMIS2DAUX_DESC (J1)%ACDC_SIZE (CLPATH//'%YEMIS2DAUX_DESC', .FALSE.)
    JSIZE = JSIZE + ISIZE
    KSIZE = KSIZE + ISIZE
  ENDDO
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
    WRITE (*, *) TRIM (CLPATH)//'%YEMIS2DAUX_DESC'
  ENDIF
ENDIF
END FUNCTION

END SUBMODULE
