SUBMODULE (YOMCLI) YOMCLI_TCLI_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TCLI (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TCLI),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%LIEEE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LIEEE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LGLOBE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGLOBE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LZ0THER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LZ0THER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NPINT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPINT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDATX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDATX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDATY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDATY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NAEROF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NAEROF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NGLOBX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGLOBX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NGLOBY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGLOBY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NTPMER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTPMER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NTPGLA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTPGLA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NTPDES)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTPDES'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NTPLAC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTPLAC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSLICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSLICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELONSW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELONSW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELATSW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELATSW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELONNE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELONNE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELATNE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELATNE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EDLON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EDLON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EDLAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EDLAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SMASK)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SMASK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SMANQ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SMANQ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SVEG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SVEG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SFCZ0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SFCZ0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSTR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSTR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSWR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSWR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%STHER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%STHER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SALBN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SALBN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SALBX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SALBX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SALBM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SALBM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SALBG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SALBG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SALBB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SALBB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SALBD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SALBD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SEMIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SEMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SEMIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SEMIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SEMIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SEMIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SEMIG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SEMIG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SEMIB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SEMIB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SEMID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SEMID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SDEPN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SDEPN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SDEPX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SDEPX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SDEPD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SDEPD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SARGN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SARGN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SARGX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SARGX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SARGD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SARGD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SSABN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SSABN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SSABX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SSABX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SSABD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SSABD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SRSMN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SRSMN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SRSMX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SRSMX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SRSMD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SRSMD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SZZ0N)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SZZ0N'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SZZ0M)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SZZ0M'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SZZ0B)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SZZ0B'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SZZ0U)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SZZ0U'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%SZZ0D)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%SZZ0D'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
