MODULE YOMCUMFS

!$ACDC methods 

USE PARKIND1, ONLY : JPRB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE

!       ----------------------------------------------------------------
!**    ** *YOMCUMFS* CONTAINS VARIABLES FOR SIMPLIFIED CONVECTION SCHEME 
!       ----------------------------------------------------------------

TYPE :: TCUMFS
LOGICAL :: LECUMFS
LOGICAL :: LREGCV
LOGICAL :: LMFCFL2_SHSTEP
!----------------------------------------------------------------------------
CONTAINS
  PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
PROCEDURE :: ACDC_COPY => ACDC_COPY_TCUMFS
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TCUMFS
PROCEDURE :: ACDC_HOST => ACDC_HOST_TCUMFS
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TCUMFS
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TCUMFS
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TCUMFS
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TCUMFS
END TYPE TCUMFS
!============================================================================

!!TYPE(TCUMFS), POINTER :: YRCUMFS => NULL()

!*    *YOMCUMFS* CONTAINS VARIABLES FOR SIMPLIFIED CONVECTION SCHEME 

!     P. LOPEZ      E.C.M.W.F.    09/01/2002

!     NAME            TYPE     DESCRIPTION
!     ----            ----     -----------

!***  LECUMFS         LOGICAL  SWITCH ON SIMPLIFIED CONVECTIVE MASS-FLUX SCHEME IN TRAJECTORY
!***  LREGCV          LOGICAL  SWITCH ON REGULARIZATIONS OF SIMPLIFIED CONVECTION SCHEME 
!***                           IN TANGENT-LINEAR AND ADJOINT CALCULATIONS
!***  LMFCFL2_SHSTEP  LOGICAL  SWITCH ON REDUCTION OF MASS FLUX CFL CRITERION FOR SHORT TIME STEPS 

!     ------------------------------------------------------------------
INTERFACE

MODULE SUBROUTINE ACDC_COPY_TCUMFS (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TCUMFS), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TCUMFS (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TCUMFS), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TCUMFS (SELF)

IMPLICIT NONE
CLASS (TCUMFS), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TCUMFS (SELF, KLUN)

IMPLICIT NONE
CLASS (TCUMFS), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TCUMFS (SELF, KLUN)

IMPLICIT NONE
CLASS (TCUMFS), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TCUMFS (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TCUMFS),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TCUMFS (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TCUMFS), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

CONTAINS

SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)

  IMPLICIT NONE
  CLASS(TCUMFS), INTENT(IN) :: SELF
  INTEGER      , INTENT(IN) :: KDEPTH
  INTEGER      , INTENT(IN) :: KOUTNO
  
  INTEGER :: IDEPTHLOC
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK('YOMCUMFS:PRINT_CONFIGURATION',0,ZHOOK_HANDLE)
  IDEPTHLOC = KDEPTH+2

  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'LECUMFS = ', SELF%LECUMFS
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'LREGCV = ', SELF%LREGCV
  WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'LMFCFL2_SHSTEP = ', SELF%LMFCFL2_SHSTEP
  IF (LHOOK) CALL DR_HOOK('YOMCUMFS:PRINT_CONFIGURATION',1,ZHOOK_HANDLE)
  
END SUBROUTINE PRINT_CONFIGURATION
END MODULE YOMCUMFS
