SUBMODULE (YOMCOMPO) YOMCOMPO_TCOMPO_EMIS_AUX_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TCOMPO_EMIS_AUX (SELF, KLUN)

IMPLICIT NONE
CLASS (TCOMPO_EMIS_AUX), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%PARAMID
WRITE (KLUN) SELF%TEMPORALITY
WRITE (KLUN) SELF%CNAME
END SUBROUTINE

END SUBMODULE
