SUBMODULE (YOMDGRADIENT) YOMDGRADIENT_TGRADIENT_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TGRADIENT (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64
IMPLICIT NONE
CLASS (TGRADIENT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YPTR%ACDC_CRC64 (KLUN, CDPATH//'%YPTR'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
