SUBMODULE (YOMDVISI) YOMDVISI_TDVISI_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TDVISI (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TDVISI),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%HVISI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%HVISI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_CM1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_CM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_CM2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_CM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_CM3)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_CM3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_CM4)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_CM4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_RM1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_RM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_RM2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_RM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_IM1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_IM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_IM2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_IM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_SM1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_SM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_SM2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_SM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_GM1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_GM1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COEF_GM2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COEF_GM2'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
