SUBMODULE (YOMDIMV) YOMDIMV_TDIMV_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TDIMV (SELF, KLUN)

IMPLICIT NONE
CLASS (TDIMV), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NFLEVG
READ (KLUN) SELF%NFLEVL
READ (KLUN) SELF%NFLEVLMX
READ (KLUN) SELF%NFLSUR
READ (KLUN) SELF%NFLSUL
READ (KLUN) SELF%NFLSA
READ (KLUN) SELF%NFLEN
READ (KLUN) SELF%NIOLEVG
END SUBROUTINE

END SUBMODULE
