SUBMODULE (YOMDPRECIPS) YOMDPRECIPS_TDPRECIPS_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TDPRECIPS (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TDPRECIPS), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%HDPRECIPS = ZTMP0
READ (KLUN) ZTMP0
SELF%HDCLWC = ZTMP0
READ (KLUN) ZTMP0
SELF%RDHAIL1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDHAIL2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDSEUIL1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDSEUIL2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDSEUIL3 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDSEUIL4 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDSEUIL5 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDCLWC = ZTMP0
READ (KLUN) ZTMP0
SELF%RPRECSEUIL = ZTMP0
READ (KLUN) ZTMP0
SELF%RHTOP = ZTMP0
READ (KLUN) ZTMP0
SELF%RTPW = ZTMP0
READ (KLUN) ZTMP0
SELF%RAWARM = ZTMP0
READ (KLUN) ZTMP0
SELF%RAWARM2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RACOLD = ZTMP0
READ (KLUN) ZTMP0
SELF%RACOLD2 = ZTMP0
READ (KLUN) SELF%NDTPREC
READ (KLUN) SELF%NDTPREC2
END SUBROUTINE

END SUBMODULE
