SUBMODULE (YOMDWET) YOMDWET_TDWET_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TDWET (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TDWET), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%WBETA = ZTMP0
READ (KLUN) ZTMP0
SELF%WRHOA = ZTMP0
READ (KLUN) ZTMP0
SELF%WRHOB = ZTMP0
READ (KLUN) ZTMP0
SELF%WDIAMWIRE = ZTMP0
READ (KLUN) ZTMP0
SELF%HWET = ZTMP0
READ (KLUN) ZTMP0
SELF%WURA = ZTMP0
READ (KLUN) ZTMP0
SELF%WURB = ZTMP0
READ (KLUN) ZTMP0
SELF%WFALLSN = ZTMP0
READ (KLUN) ZTMP0
SELF%WTTA = ZTMP0
READ (KLUN) ZTMP0
SELF%WTWB = ZTMP0
READ (KLUN) ZTMP0
SELF%WTWA = ZTMP0
READ (KLUN) ZTMP0
SELF%WTWDRYB = ZTMP0
READ (KLUN) ZTMP0
SELF%WUUDRY = ZTMP0
READ (KLUN) ZTMP0
SELF%WFALLICE = ZTMP0
READ (KLUN) ZTMP0
SELF%WTWAICE = ZTMP0
READ (KLUN) ZTMP0
SELF%WTWBICE = ZTMP0
READ (KLUN) ZTMP0
SELF%WBETAICE = ZTMP0
END SUBROUTINE

END SUBMODULE
