SUBMODULE (YOMGSGEOM) YOMGSGEOM_TGSGEOM_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_TGSGEOM (SELF)

IMPLICIT NONE
CLASS (TGSGEOM), TARGET :: SELF
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAMDEG, LGELAMINF, LGELAMSUP, LGELAT, LGEMU, LGESLO, LGEXCO
LOGICAL :: LGEYCO, LGEZCO, LGM, LGMAPPA, LGNORDL, LGNORDLCL, LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL
LOGICAL :: LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC

END SUBROUTINE

END SUBMODULE
