SUBMODULE (YOMGPDDH) YOMGPDDH_TGPDDH_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_TGPDDH (SELF)

IMPLICIT NONE
CLASS (TGPDDH), TARGET :: SELF
LOGICAL :: LGFLTNDHD_DDH, LGFLTNDSL_DDH, LGMVTNDHD_DDH, LGMVTNDSI_DDH, LGMVTNDSL_DDH

END SUBROUTINE

END SUBMODULE
