SUBMODULE (YOMGEM) YOMGEM_TGEM_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_TGEM (SELF)

IMPLICIT NONE
CLASS (TGEM), TARGET :: SELF
LOGICAL :: LNDGLU, LNGPTOTL, LNLOEN, LNLOENG, LNMEN, LNMENG, LNSTAGP, LNTSTAGP

END SUBROUTINE

END SUBMODULE
