SUBMODULE (YOMMCC) YOMMCC_TMCC_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TMCC (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TMCC), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: J1
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) SELF%N923
READ (KLUN) SELF%NCLIMTOT
READ (KLUN) SELF%NCLIMR
READ (KLUN) SELF%NCLIGC
READ (KLUN) SELF%NCLIGC_COMPO
READ (KLUN) SELF%NYSDMP_COMPO
READ (KLUN) SELF%NCLIMR_COMPO
READ (KLUN) SELF%NCLIAER
READ (KLUN) SELF%NDIFC
READ (KLUN) SELF%NJDCR
READ (KLUN) SELF%NJDCR1
READ (KLUN) SELF%NDIFC_COMPO
READ (KLUN) SELF%NJDCR_COMPO
READ (KLUN) SELF%NJDCR1_COMPO
READ (KLUN) SELF%NP1
READ (KLUN) SELF%NP2
READ (KLUN) SELF%NPCO2_1
READ (KLUN) SELF%NPCO2_2
READ (KLUN) SELF%NPAER_1
READ (KLUN) SELF%NPAER_2
READ (KLUN) SELF%NPCOMPO_1
READ (KLUN) SELF%NPCOMPO_2
READ (KLUN) SELF%NUNITC
READ (KLUN) SELF%NUNITC1
READ (KLUN) SELF%NUNITCM
READ (KLUN) SELF%NOACOMM
READ (KLUN) SELF%NSSTICEOP
READ (KLUN) LCLIMRCO2
IF (LCLIMRCO2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%CLIMRCO2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%CLIMRCO2,1):UBOUND(SELF%CLIMRCO2,1), LBOUND(SELF%CLIMRCO2,2):UBOUND(SELF%CLIMRCO2,2), LBOUND(SELF%CLIMRCO2,3):UBOUND(SELF%CLIMRCO2,3)))
  READ (KLUN) ZTMP3
  SELF%CLIMRCO2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LCLIMRAER
IF (LCLIMRAER) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%CLIMRAER (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%CLIMRAER,1):UBOUND(SELF%CLIMRAER,1), LBOUND(SELF%CLIMRAER,2):UBOUND(SELF%CLIMRAER,2), LBOUND(SELF%CLIMRAER,3):UBOUND(SELF%CLIMRAER,3)))
  READ (KLUN) ZTMP3
  SELF%CLIMRAER = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LCLIMRCOMPO
IF (LCLIMRCOMPO) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%CLIMRCOMPO (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%CLIMRCOMPO,1):UBOUND(SELF%CLIMRCOMPO,1), LBOUND(SELF%CLIMRCOMPO,2):UBOUND(SELF%CLIMRCOMPO,2), LBOUND(SELF%CLIMRCOMPO,3):UBOUND(SELF%CLIMRCOMPO,3)))
  READ (KLUN) ZTMP3
  SELF%CLIMRCOMPO = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LZLAKE
IF (LZLAKE) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%ZLAKE (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%ZLAKE,1):UBOUND(SELF%ZLAKE,1), LBOUND(SELF%ZLAKE,2):UBOUND(SELF%ZLAKE,2), LBOUND(SELF%ZLAKE,3):UBOUND(SELF%ZLAKE,3)))
  READ (KLUN) ZTMP3
  SELF%ZLAKE = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LOCEANBC
IF (LOCEANBC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%OCEANBC (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%OCEANBC,1):UBOUND(SELF%OCEANBC,1), LBOUND(SELF%OCEANBC,2):UBOUND(SELF%OCEANBC,2)))
  READ (KLUN) ZTMP2
  SELF%OCEANBC = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LCLIMR
IF (LCLIMR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%CLIMR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%CLIMR
ENDIF
READ (KLUN) SELF%LFIRSTUPD
READ (KLUN) SELF%LCURR
READ (KLUN) SELF%LGELATO
READ (KLUN) SELF%LMCC01_MSE
READ (KLUN) SELF%LMCC01
READ (KLUN) SELF%LMCC02
READ (KLUN) SELF%LMCC03
READ (KLUN) SELF%LMCC04
READ (KLUN) SELF%LMCC05
READ (KLUN) SELF%LMCC06
READ (KLUN) SELF%LMCCEC
READ (KLUN) SELF%LMCCIEC
READ (KLUN) SELF%LMCCIEC_COMPO
READ (KLUN) SELF%LMCCICEIC
READ (KLUN) SELF%LMCCDYNSEAICE
READ (KLUN) SELF%LNEMOCOUP
READ (KLUN) SELF%LNEMOFLUXNC
READ (KLUN) SELF%LNEMOOUTGRB
READ (KLUN) SELF%LCOUPINFOUT
READ (KLUN) SELF%LNEMO1WAY
READ (KLUN) SELF%LNEMOIFSLOG
READ (KLUN) SELF%LNEMOSSTFREEZ
READ (KLUN) SELF%LNEMOGRIBFLDS
READ (KLUN) SELF%LNEMOGRIBMASK
READ (KLUN) SELF%L2DECV2NEMO
READ (KLUN) SELF%LMULTIYR
READ (KLUN) SELF%LMCC_COMPO
READ (KLUN) SELF%NFRCPL
READ (KLUN) SELF%LNEMOLIMGET
READ (KLUN) SELF%LNEMOLIMPUT
READ (KLUN) SELF%LNEMOLIMALB
READ (KLUN) SELF%LNEMOLIMTEMP
READ (KLUN) SELF%LNEMOLIMTLVL
READ (KLUN) SELF%LNEMOLIMTHK
READ (KLUN) SELF%LNEMOSICOUP
READ (KLUN) SELF%LNEMOATMFLDS
READ (KLUN) SELF%LNEMOOCEICEMIX
READ (KLUN) SELF%LNEMOQNSICEFILT
READ (KLUN) SELF%LNEMOACCUMFLUX
READ (KLUN) SELF%LNEMOGRIB3D
READ (KLUN) SELF%NNEMO3DLEVS
READ (KLUN) LRNEMOLVLS
IF (LRNEMOLVLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RNEMOLVLS (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RNEMOLVLS,1):UBOUND(SELF%RNEMOLVLS,1)))
  READ (KLUN) ZTMP1
  SELF%RNEMOLVLS = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRNEMOMASK
IF (LRNEMOMASK) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RNEMOMASK (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%RNEMOMASK
ENDIF
READ (KLUN) SELF%LNEMOPARTCOUP
READ (KLUN) SELF%LNEMOPARTMASK
READ (KLUN) SELF%LNEMOPARTMASKFILE
READ (KLUN) ZTMP0
SELF%RNPARTRAMPSTART = ZTMP0
READ (KLUN) ZTMP0
SELF%RNPARTRAMPLEN = ZTMP0
READ (KLUN) ZTMP0
SELF%RNPARTLAT = ZTMP0
READ (KLUN) ZTMP0
SELF%RNPARTLATSPREAD = ZTMP0
READ (KLUN) LPARTSST0
IF (LPARTSST0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%PARTSST0 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%PARTSST0,1):UBOUND(SELF%PARTSST0,1)))
  READ (KLUN) ZTMP1
  SELF%PARTSST0 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LPARTMASK
IF (LPARTMASK) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%PARTMASK (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%PARTMASK,1):UBOUND(SELF%PARTMASK,1)))
  READ (KLUN) ZTMP1
  SELF%PARTMASK = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) SELF%CDNPARTMASKFILE
READ (KLUN) LCPLNG_FLD
IF (LCPLNG_FLD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%CPLNG_FLD (IL1(1):IU1(1)))
  DO J1 = LBOUND (SELF%CPLNG_FLD, 1), UBOUND (SELF%CPLNG_FLD, 1)
    CALL SELF%CPLNG_FLD (J1)%ACDC_LOAD (KLUN)
  ENDDO
ENDIF
READ (KLUN) SELF%CPLNG_ACTIVE
READ (KLUN) SELF%CPLNG_NUM_FIELDS
READ (KLUN) SELF%IP_A_SST
READ (KLUN) SELF%IP_A_ICE_FRAC
READ (KLUN) SELF%IP_A_CURR_U
READ (KLUN) SELF%IP_A_CURR_V
READ (KLUN) SELF%IP_A_TAUX_OCE
READ (KLUN) SELF%IP_A_TAUY_OCE
READ (KLUN) SELF%IP_A_TAUX_ICE
READ (KLUN) SELF%IP_A_TAUY_ICE
READ (KLUN) SELF%IP_A_QS_MIX
READ (KLUN) SELF%IP_A_QNS_MIX
READ (KLUN) SELF%IP_A_QS_OCE
READ (KLUN) SELF%IP_A_QNS_OCE
READ (KLUN) SELF%IP_A_QS_ICE
READ (KLUN) SELF%IP_A_QNS_ICE
READ (KLUN) SELF%IP_A_PRECIP_LIQUID
READ (KLUN) SELF%IP_A_PRECIP_SOLID
READ (KLUN) SELF%IP_A_EVAP_TOTAL
READ (KLUN) SELF%IP_A_EVAP_ICE
READ (KLUN) SELF%IP_A_DQNS_DT
READ (KLUN) SELF%IP_A_RUNOFF
READ (KLUN) SELF%IP_A_TOTAL_CC
READ (KLUN) SELF%IP_A_LOW_CC
READ (KLUN) SELF%IP_A_ICE_TEMP
READ (KLUN) SELF%IP_A_ICE_ALBEDO
READ (KLUN) SELF%IP_A_ICE_THICKNESS
READ (KLUN) SELF%IP_A_SNOW_THICKNESS
READ (KLUN) SELF%IP_A_ICE_TEMP_LVLS
READ (KLUN) SELF%IP_A_TAUX
READ (KLUN) SELF%IP_A_TAUY
READ (KLUN) SELF%IP_A_QS
READ (KLUN) SELF%IP_A_QNS
READ (KLUN) SELF%IP_A_WATER
READ (KLUN) SELF%IP_A_SST_ATM
READ (KLUN) SELF%IP_A_TSK_ATM
READ (KLUN) SELF%IP_A_IST_ATM
READ (KLUN) SELF%IP_A_2DECV_SKT
READ (KLUN) SELF%LCOUPSIM
END SUBROUTINE

END SUBMODULE
