SUBMODULE (YOMNORGWD) YOMNORGWD_TNORGWD_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TNORGWD (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TNORGWD), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_SCHEME), CDPATH//'%NORGWD_SCHEME'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_PRMAX), CDPATH//'%NORGWD_PRMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_DZ), CDPATH//'%NORGWD_DZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_PTROPO), CDPATH//'%NORGWD_PTROPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_NTROPO), CDPATH//'%NORGWD_NTROPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_RUWMAX), CDPATH//'%NORGWD_RUWMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_SAT), CDPATH//'%NORGWD_SAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_RDISS), CDPATH//'%NORGWD_RDISS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_DELTAT), CDPATH//'%NORGWD_DELTAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_KMIN), CDPATH//'%NORGWD_KMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_KMAX), CDPATH//'%NORGWD_KMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_CMIN), CDPATH//'%NORGWD_CMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_CMAX), CDPATH//'%NORGWD_CMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_PLAUNCH), CDPATH//'%NORGWD_PLAUNCH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_NLAUNCH), CDPATH//'%NORGWD_NLAUNCH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_PNOVERDIF), CDPATH//'%NORGWD_PNOVERDIF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_NNOVERDIF), CDPATH//'%NORGWD_NNOVERDIF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_DZFRON), CDPATH//'%NORGWD_DZFRON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_GFRON), CDPATH//'%NORGWD_GFRON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NORGWD_GB), CDPATH//'%NORGWD_GB'

END SUBROUTINE

END SUBMODULE
