MODULE YOMOROG

!$ACDC methods 


USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------

!*    Orography: structure TOROG

! OROG       : grid-point surface orography "Phi_s".
! OROGL      : zonal component of "grad Phi_s".
! OROGM      : meridian component of "grad Phi_s".
! OROGLL,OROGMM,OROGLM: second-order reduced derivatives of surface orography.

TYPE TOROG
  REAL(KIND=JPRB), ALLOCATABLE :: OROG(:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGL(:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGM(:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGLL(:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGMM(:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGLM(:)
CONTAINS
PROCEDURE :: ACDC_COPY => ACDC_COPY_TOROG
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TOROG
PROCEDURE :: ACDC_HOST => ACDC_HOST_TOROG
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TOROG
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TOROG
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TOROG
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TOROG
END TYPE TOROG

TYPE TOROG_BLOCKED
  REAL(KIND=JPRB), ALLOCATABLE :: OROG(:,:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGL(:,:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGM(:,:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGLL(:,:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGMM(:,:)
  REAL(KIND=JPRB), ALLOCATABLE :: OROGLM(:,:)
CONTAINS
PROCEDURE :: ACDC_COPY => ACDC_COPY_TOROG_BLOCKED
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TOROG_BLOCKED
PROCEDURE :: ACDC_HOST => ACDC_HOST_TOROG_BLOCKED
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TOROG_BLOCKED
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TOROG_BLOCKED
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TOROG_BLOCKED
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TOROG_BLOCKED
END TYPE TOROG_BLOCKED

! ------------------------------------------------------------------

INTERFACE

MODULE SUBROUTINE ACDC_COPY_TOROG (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TOROG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TOROG (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TOROG), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TOROG (SELF)

IMPLICIT NONE
CLASS (TOROG), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TOROG (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TOROG), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TOROG (SELF, KLUN)

IMPLICIT NONE
CLASS (TOROG), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TOROG (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TOROG),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TOROG (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TOROG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_COPY_TOROG_BLOCKED (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TOROG_BLOCKED), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TOROG_BLOCKED (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TOROG_BLOCKED), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TOROG_BLOCKED (SELF)

IMPLICIT NONE
CLASS (TOROG_BLOCKED), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TOROG_BLOCKED (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TOROG_BLOCKED), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TOROG_BLOCKED (SELF, KLUN)

IMPLICIT NONE
CLASS (TOROG_BLOCKED), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TOROG_BLOCKED (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TOROG_BLOCKED),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TOROG_BLOCKED (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TOROG_BLOCKED), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YOMOROG
