SUBMODULE (YOMPHY2) YOMPHY2_TPHY2_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TPHY2 (SELF, KLUN)

IMPLICIT NONE
CLASS (TPHY2), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NTSHM
WRITE (KLUN) SELF%NTSML
WRITE (KLUN) SELF%TSPHY
WRITE (KLUN) SELF%XMUCVPP
WRITE (KLUN) SELF%XMULAF
WRITE (KLUN) SELF%XDAMP
WRITE (KLUN) SELF%HCLP
WRITE (KLUN) SELF%HTCLS
WRITE (KLUN) SELF%HVCLS
WRITE (KLUN) SELF%HTSHM
WRITE (KLUN) SELF%HTSML
WRITE (KLUN) SELF%HWMOHIGH
WRITE (KLUN) SELF%HWMOLOW
WRITE (KLUN) SELF%GZ0RAF
WRITE (KLUN) SELF%FACRAF
WRITE (KLUN) SELF%FACRAFCV
WRITE (KLUN) SELF%FACRAFDCAPE
WRITE (KLUN) SELF%GCAPERAF
WRITE (KLUN) SELF%HTKERAF
WRITE (KLUN) SELF%LRAFTUR
WRITE (KLUN) SELF%LMULAF
WRITE (KLUN) SELF%LWMOCLOUD
WRITE (KLUN) SELF%LRAFTKE
END SUBROUTINE

END SUBMODULE
