SUBMODULE (YOMPADDH) YOMPADDH_TPADDH_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TPADDH (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (TPADDH), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LNGLALIST, LNGPUMASK
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGLALIST), CDPATH//'%NGLALIST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGPUMASK), CDPATH//'%NGPUMASK'

END SUBROUTINE

END SUBMODULE
