SUBMODULE (YOMPHY1) YOMPHY1_TPHY1_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TPHY1 (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TPHY1), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GF3), CDPATH//'%GF3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GF4), CDPATH//'%GF4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TREF4), CDPATH//'%TREF4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCTVEG), CDPATH//'%RCTVEG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RGL), CDPATH//'%RGL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SODELX), CDPATH//'%SODELX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCZ0H), CDPATH//'%GCZ0H'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALBGLA), CDPATH//'%ALBGLA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALBMAX), CDPATH//'%ALBMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALBMER), CDPATH//'%ALBMER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALBMED), CDPATH//'%ALBMED'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALBMIN), CDPATH//'%ALBMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALCRIN), CDPATH//'%ALCRIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALRCN1), CDPATH//'%ALRCN1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALRCN2), CDPATH//'%ALRCN2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EA), CDPATH//'%EA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EC2REF), CDPATH//'%EC2REF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EMCRIN), CDPATH//'%EMCRIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EMMGLA), CDPATH//'%EMMGLA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EMMMER), CDPATH//'%EMMMER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EWFC), CDPATH//'%EWFC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EWWILT), CDPATH//'%EWWILT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GA), CDPATH//'%GA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC1), CDPATH//'%GC1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC1S1), CDPATH//'%GC1S1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC1S2), CDPATH//'%GC1S2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC1S3), CDPATH//'%GC1S3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC1S4), CDPATH//'%GC1S4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC1Y1), CDPATH//'%GC1Y1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GTSVAP), CDPATH//'%GTSVAP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GVEGMX), CDPATH//'%GVEGMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GLAIMX), CDPATH//'%GLAIMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GNEIMX), CDPATH//'%GNEIMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GWPIMX), CDPATH//'%GWPIMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCGEL), CDPATH//'%GCGEL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC2), CDPATH//'%GC2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC2REF), CDPATH//'%GC2REF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC3), CDPATH//'%GC3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC31), CDPATH//'%GC31'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GC32), CDPATH//'%GC32'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCONV), CDPATH//'%GCONV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GF1), CDPATH//'%GF1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GWFC), CDPATH//'%GWFC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GWLEX), CDPATH//'%GWLEX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GWLMX), CDPATH//'%GWLMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GWWILT), CDPATH//'%GWWILT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G1B), CDPATH//'%G1B'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G1CGSAT), CDPATH//'%G1CGSAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G1C1SAT), CDPATH//'%G1C1SAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G1P), CDPATH//'%G1P'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G1WSAT), CDPATH//'%G1WSAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G2B), CDPATH//'%G2B'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G2CGSAT), CDPATH//'%G2CGSAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G2C1SAT), CDPATH//'%G2C1SAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G2P), CDPATH//'%G2P'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G2WSAT), CDPATH//'%G2WSAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%G3CGSAT), CDPATH//'%G3CGSAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GSNC1), CDPATH//'%GSNC1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GSNC2), CDPATH//'%GSNC2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%HSOL), CDPATH//'%HSOL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%HSOLIWR), CDPATH//'%HSOLIWR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%HSOLIT0), CDPATH//'%HSOLIT0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%OMTPRO), CDPATH//'%OMTPRO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%OMWPRO), CDPATH//'%OMWPRO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RC1MAX), CDPATH//'%RC1MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCTGLA), CDPATH//'%RCTGLA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCGMAX), CDPATH//'%RCGMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RD1), CDPATH//'%RD1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RD2GLA), CDPATH//'%RD2GLA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RD2MER), CDPATH//'%RD2MER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHOMAX), CDPATH//'%RHOMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHOMIN), CDPATH//'%RHOMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSMAX), CDPATH//'%RSMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTINER), CDPATH//'%RTINER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RZ0GLA), CDPATH//'%RZ0GLA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RZ0MER), CDPATH//'%RZ0MER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RZHZ0G), CDPATH//'%RZHZ0G'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RZHZ0M), CDPATH//'%RZHZ0M'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RZ0_TO_HEIGHT), CDPATH//'%RZ0_TO_HEIGHT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TMERGL), CDPATH//'%TMERGL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TOEXP), CDPATH//'%TOEXP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TOLIN), CDPATH//'%TOLIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%WCRIN), CDPATH//'%WCRIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%WCRINC), CDPATH//'%WCRINC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%WCRING), CDPATH//'%WCRING'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%WNEW), CDPATH//'%WNEW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%WPMX), CDPATH//'%WPMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%WSMX), CDPATH//'%WSMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XCRINR), CDPATH//'%XCRINR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XCRINV), CDPATH//'%XCRINV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LALBMERCLIM), CDPATH//'%LALBMERCLIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LIMC), CDPATH//'%LIMC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LIMW), CDPATH//'%LIMW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LC1VAP), CDPATH//'%LC1VAP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCLS_HS), CDPATH//'%LCLS_HS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCLS_TOUCANS), CDPATH//'%LCLS_TOUCANS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NTVGLA), CDPATH//'%NTVGLA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NTVMER), CDPATH//'%NTVMER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCGELS), CDPATH//'%GCGELS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GVEGMXS), CDPATH//'%GVEGMXS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GLAIMXS), CDPATH//'%GLAIMXS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GNEIMXS), CDPATH//'%GNEIMXS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALB1), CDPATH//'%ALB1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ALB2), CDPATH//'%ALB2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLAIMX), CDPATH//'%RLAIMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLAI), CDPATH//'%RLAI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ACLS_HS), CDPATH//'%ACLS_HS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCHSP), CDPATH//'%NCHSP'

END SUBROUTINE

END SUBMODULE
