SUBMODULE (YOMRADF) YOMRADF_TRADF_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TRADF (SELF, KLUN)

IMPLICIT NONE
CLASS (TRADF), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LDERIVATIVELW, LEDRO, LEMTC, LEMTD, LEMTU, LRMOON, LSRCDIR, LSRFDIR, LSRLWD, LSRLWDC
LOGICAL :: LSRLWDCS, LSRSWD, LSRSWDC, LSRSWDCS, LSRSWDUV, LSRSWDV, LSRSWPAR, LSRSWPARC, LSRSWTINC, LSRSWUVB
LOGICAL :: LTAUAER, LTRSC, LTRSW
LEMTD = ALLOCATED (SELF%EMTD)
WRITE (KLUN) LEMTD
IF (LEMTD) THEN
  WRITE (KLUN) LBOUND (SELF%EMTD)
  WRITE (KLUN) UBOUND (SELF%EMTD)
  WRITE (KLUN) SELF%EMTD
ENDIF
LTRSW = ALLOCATED (SELF%TRSW)
WRITE (KLUN) LTRSW
IF (LTRSW) THEN
  WRITE (KLUN) LBOUND (SELF%TRSW)
  WRITE (KLUN) UBOUND (SELF%TRSW)
  WRITE (KLUN) SELF%TRSW
ENDIF
LEMTC = ALLOCATED (SELF%EMTC)
WRITE (KLUN) LEMTC
IF (LEMTC) THEN
  WRITE (KLUN) LBOUND (SELF%EMTC)
  WRITE (KLUN) UBOUND (SELF%EMTC)
  WRITE (KLUN) SELF%EMTC
ENDIF
LTRSC = ALLOCATED (SELF%TRSC)
WRITE (KLUN) LTRSC
IF (LTRSC) THEN
  WRITE (KLUN) LBOUND (SELF%TRSC)
  WRITE (KLUN) UBOUND (SELF%TRSC)
  WRITE (KLUN) SELF%TRSC
ENDIF
LEMTU = ALLOCATED (SELF%EMTU)
WRITE (KLUN) LEMTU
IF (LEMTU) THEN
  WRITE (KLUN) LBOUND (SELF%EMTU)
  WRITE (KLUN) UBOUND (SELF%EMTU)
  WRITE (KLUN) SELF%EMTU
ENDIF
LTAUAER = ALLOCATED (SELF%TAUAER)
WRITE (KLUN) LTAUAER
IF (LTAUAER) THEN
  WRITE (KLUN) LBOUND (SELF%TAUAER)
  WRITE (KLUN) UBOUND (SELF%TAUAER)
  WRITE (KLUN) SELF%TAUAER
ENDIF
LSRSWD = ALLOCATED (SELF%SRSWD)
WRITE (KLUN) LSRSWD
IF (LSRSWD) THEN
  WRITE (KLUN) LBOUND (SELF%SRSWD)
  WRITE (KLUN) UBOUND (SELF%SRSWD)
  WRITE (KLUN) SELF%SRSWD
ENDIF
LSRLWDC = ALLOCATED (SELF%SRLWDC)
WRITE (KLUN) LSRLWDC
IF (LSRLWDC) THEN
  WRITE (KLUN) LBOUND (SELF%SRLWDC)
  WRITE (KLUN) UBOUND (SELF%SRLWDC)
  WRITE (KLUN) SELF%SRLWDC
ENDIF
LSRLWD = ALLOCATED (SELF%SRLWD)
WRITE (KLUN) LSRLWD
IF (LSRLWD) THEN
  WRITE (KLUN) LBOUND (SELF%SRLWD)
  WRITE (KLUN) UBOUND (SELF%SRLWD)
  WRITE (KLUN) SELF%SRLWD
ENDIF
LSRSWDC = ALLOCATED (SELF%SRSWDC)
WRITE (KLUN) LSRSWDC
IF (LSRSWDC) THEN
  WRITE (KLUN) LBOUND (SELF%SRSWDC)
  WRITE (KLUN) UBOUND (SELF%SRSWDC)
  WRITE (KLUN) SELF%SRSWDC
ENDIF
LSRSWDCS = ALLOCATED (SELF%SRSWDCS)
WRITE (KLUN) LSRSWDCS
IF (LSRSWDCS) THEN
  WRITE (KLUN) LBOUND (SELF%SRSWDCS)
  WRITE (KLUN) UBOUND (SELF%SRSWDCS)
  WRITE (KLUN) SELF%SRSWDCS
ENDIF
LSRLWDCS = ALLOCATED (SELF%SRLWDCS)
WRITE (KLUN) LSRLWDCS
IF (LSRLWDCS) THEN
  WRITE (KLUN) LBOUND (SELF%SRLWDCS)
  WRITE (KLUN) UBOUND (SELF%SRLWDCS)
  WRITE (KLUN) SELF%SRLWDCS
ENDIF
LSRSWDV = ALLOCATED (SELF%SRSWDV)
WRITE (KLUN) LSRSWDV
IF (LSRSWDV) THEN
  WRITE (KLUN) LBOUND (SELF%SRSWDV)
  WRITE (KLUN) UBOUND (SELF%SRSWDV)
  WRITE (KLUN) SELF%SRSWDV
ENDIF
LSRSWDUV = ALLOCATED (SELF%SRSWDUV)
WRITE (KLUN) LSRSWDUV
IF (LSRSWDUV) THEN
  WRITE (KLUN) LBOUND (SELF%SRSWDUV)
  WRITE (KLUN) UBOUND (SELF%SRSWDUV)
  WRITE (KLUN) SELF%SRSWDUV
ENDIF
LEDRO = ALLOCATED (SELF%EDRO)
WRITE (KLUN) LEDRO
IF (LEDRO) THEN
  WRITE (KLUN) LBOUND (SELF%EDRO)
  WRITE (KLUN) UBOUND (SELF%EDRO)
  WRITE (KLUN) SELF%EDRO
ENDIF
LSRSWPAR = ALLOCATED (SELF%SRSWPAR)
WRITE (KLUN) LSRSWPAR
IF (LSRSWPAR) THEN
  WRITE (KLUN) LBOUND (SELF%SRSWPAR)
  WRITE (KLUN) UBOUND (SELF%SRSWPAR)
  WRITE (KLUN) SELF%SRSWPAR
ENDIF
LSRSWUVB = ALLOCATED (SELF%SRSWUVB)
WRITE (KLUN) LSRSWUVB
IF (LSRSWUVB) THEN
  WRITE (KLUN) LBOUND (SELF%SRSWUVB)
  WRITE (KLUN) UBOUND (SELF%SRSWUVB)
  WRITE (KLUN) SELF%SRSWUVB
ENDIF
LSRSWPARC = ALLOCATED (SELF%SRSWPARC)
WRITE (KLUN) LSRSWPARC
IF (LSRSWPARC) THEN
  WRITE (KLUN) LBOUND (SELF%SRSWPARC)
  WRITE (KLUN) UBOUND (SELF%SRSWPARC)
  WRITE (KLUN) SELF%SRSWPARC
ENDIF
LSRSWTINC = ALLOCATED (SELF%SRSWTINC)
WRITE (KLUN) LSRSWTINC
IF (LSRSWTINC) THEN
  WRITE (KLUN) LBOUND (SELF%SRSWTINC)
  WRITE (KLUN) UBOUND (SELF%SRSWTINC)
  WRITE (KLUN) SELF%SRSWTINC
ENDIF
LSRFDIR = ALLOCATED (SELF%SRFDIR)
WRITE (KLUN) LSRFDIR
IF (LSRFDIR) THEN
  WRITE (KLUN) LBOUND (SELF%SRFDIR)
  WRITE (KLUN) UBOUND (SELF%SRFDIR)
  WRITE (KLUN) SELF%SRFDIR
ENDIF
LSRCDIR = ALLOCATED (SELF%SRCDIR)
WRITE (KLUN) LSRCDIR
IF (LSRCDIR) THEN
  WRITE (KLUN) LBOUND (SELF%SRCDIR)
  WRITE (KLUN) UBOUND (SELF%SRCDIR)
  WRITE (KLUN) SELF%SRCDIR
ENDIF
LRMOON = ALLOCATED (SELF%RMOON)
WRITE (KLUN) LRMOON
IF (LRMOON) THEN
  WRITE (KLUN) LBOUND (SELF%RMOON)
  WRITE (KLUN) UBOUND (SELF%RMOON)
  WRITE (KLUN) SELF%RMOON
ENDIF
LDERIVATIVELW = ASSOCIATED (SELF%DERIVATIVELW)
WRITE (KLUN) LDERIVATIVELW
IF (LDERIVATIVELW) THEN
  WRITE (KLUN) LBOUND (SELF%DERIVATIVELW)
  WRITE (KLUN) UBOUND (SELF%DERIVATIVELW)
  WRITE (KLUN) SELF%DERIVATIVELW
ENDIF
END SUBROUTINE

END SUBMODULE
