SUBMODULE (YOMRIP) YOMRIP_TRIP_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TRIP (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TRIP),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NSTART)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSTART'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSTOP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSTOP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CSTOP) * LEN (SELF%CSTOP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CSTOP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSTADD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSTADD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSTASS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSTASS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NFOST)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFOST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSTATI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSTATI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RTIMTR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTIMTR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RHGMT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RHGMT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%REQTIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REQTIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSOVR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSOVR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDEASO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDEASO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDECLI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDECLI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RWSOVR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RWSOVR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RIP0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RIP0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCODEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCODEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIDEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIDEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCOVSR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCOVSR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIVSR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIVSR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCODECN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCODECN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIDECN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIDECN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCOVSRN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCOVSRN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIVSRN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIVSRN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCODECF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCODECF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIDECF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIDECF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCOVSRF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCOVSRF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIVSRF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIVSRF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TSTEP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TSTEP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TDT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TDT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDTSA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDTSA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDTSA2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDTSA2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDTS62)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDTS62'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDTS22)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDTS22'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RTDT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTDT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDECLU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDECLU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RTMOLT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTMOLT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RJUSMP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RJUSMP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLUNDI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLUNDI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RIP0LU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RIP0LU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCODECLU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCODECLU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIDECLU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIDECLU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCOVSRLU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCOVSRLU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSIVSRLU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSIVSRLU'
ENDIF
KSIZE = KSIZE + ISIZE
JSIZE = 0
ISIZE = SELF%YREOZOC%ACDC_SIZE (CLPATH//'%YREOZOC', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREOZOC'
ENDIF
JSIZE = 0
ISIZE = SELF%YRECMIP%ACDC_SIZE (CLPATH//'%YRECMIP', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRECMIP'
ENDIF
JSIZE = 0
ISIZE = SELF%YRERADGHG%ACDC_SIZE (CLPATH//'%YRERADGHG', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRERADGHG'
ENDIF
JSIZE = 0
ISIZE = SELF%YREAERC_TEGEN%ACDC_SIZE (CLPATH//'%YREAERC_TEGEN', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREAERC_TEGEN'
ENDIF
JSIZE = 0
ISIZE = SELF%YREAERC_MACC%ACDC_SIZE (CLPATH//'%YREAERC_MACC', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREAERC_MACC'
ENDIF
JSIZE = 0
ISIZE = SELF%RAERSO4%ACDC_SIZE (CLPATH//'%RAERSO4', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAERSO4'
ENDIF
ISIZE = KIND (SELF%JPORDT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%JPORDT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GCOEFS_ASCENSION_DROITE) * SIZE (SELF%GCOEFS_ASCENSION_DROITE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GCOEFS_ASCENSION_DROITE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GCOEFS_DECLINAISON) * SIZE (SELF%GCOEFS_DECLINAISON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GCOEFS_DECLINAISON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GCOEFS_DISTANCE) * SIZE (SELF%GCOEFS_DISTANCE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GCOEFS_DISTANCE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GTDEBUT) * SIZE (SELF%GTDEBUT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GTDEBUT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%GTFIN) * SIZE (SELF%GTFIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GTFIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NINTT_MOON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NINTT_MOON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NINTT_SUN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NINTT_SUN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CGSOLEC_SUN) * LEN (SELF%CGSOLEC_SUN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CGSOLEC_SUN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CGSOLEC_MOON) * LEN (SELF%CGSOLEC_MOON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CGSOLEC_MOON'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
