SUBMODULE (YOMSIMPHL) YOMSIMPHL_TSIMPHL_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TSIMPHL (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TSIMPHL), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%LSIMPH
READ (KLUN) SELF%LTRAJPS
READ (KLUN) SELF%LTRAJPST
READ (KLUN) SELF%LSMOOTHD
READ (KLUN) SELF%LSMOOTHA
READ (KLUN) SELF%LSMOOTHB
READ (KLUN) SELF%LCVRASP
READ (KLUN) SELF%LGWDSP
READ (KLUN) SELF%LRAYSP
READ (KLUN) SELF%LSTRASP
READ (KLUN) SELF%LVDIFSP
READ (KLUN) SELF%LVDIFSPNL
READ (KLUN) SELF%LRRMESSP
READ (KLUN) SELF%LCLOUDS
READ (KLUN) SELF%LGWDSPNL
READ (KLUN) SELF%LSTRASPN
READ (KLUN) SELF%LPROCLDTL
READ (KLUN) SELF%LMELTTL
READ (KLUN) SELF%LMELTNL
READ (KLUN) SELF%LMICROTL
READ (KLUN) SELF%LTRAJRAIN
READ (KLUN) SELF%LTRAJCOND
READ (KLUN) SELF%LNEBCVPPKF
READ (KLUN) SELF%LCOLLECTL
READ (KLUN) SELF%LEVAPTL
READ (KLUN) SELF%LSMOOTHEVP
READ (KLUN) SELF%LIGELREPRO
READ (KLUN) SELF%LCVRASBM
READ (KLUN) SELF%LCONSENTH
READ (KLUN) SELF%LAPPROXCONV
READ (KLUN) ZTMP0
SELF%RHCRIT1S = ZTMP0
READ (KLUN) ZTMP0
SELF%RHCRIT2S = ZTMP0
READ (KLUN) ZTMP0
SELF%TADJ = ZTMP0
READ (KLUN) ZTMP0
SELF%RMINEVP = ZTMP0
READ (KLUN) ZTMP0
SELF%DELTAH = ZTMP0
READ (KLUN) ZTMP0
SELF%RMODULQCPROG = ZTMP0
END SUBROUTINE

END SUBMODULE
