SUBMODULE (YOMSTA) YOMSTA_TSTA_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TSTA (SELF, KLUN)

IMPLICIT NONE
CLASS (TSTA), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LSTDEN, LSTPHI, LSTPRE, LSTPREH, LSTTEM, LSTZ, LSVETAF, LSVETAH
LSTPREH = ALLOCATED (SELF%STPREH)
WRITE (KLUN) LSTPREH
IF (LSTPREH) THEN
  WRITE (KLUN) LBOUND (SELF%STPREH)
  WRITE (KLUN) UBOUND (SELF%STPREH)
  WRITE (KLUN) SELF%STPREH
ENDIF
LSTPRE = ALLOCATED (SELF%STPRE)
WRITE (KLUN) LSTPRE
IF (LSTPRE) THEN
  WRITE (KLUN) LBOUND (SELF%STPRE)
  WRITE (KLUN) UBOUND (SELF%STPRE)
  WRITE (KLUN) SELF%STPRE
ENDIF
LSTPHI = ALLOCATED (SELF%STPHI)
WRITE (KLUN) LSTPHI
IF (LSTPHI) THEN
  WRITE (KLUN) LBOUND (SELF%STPHI)
  WRITE (KLUN) UBOUND (SELF%STPHI)
  WRITE (KLUN) SELF%STPHI
ENDIF
LSTTEM = ALLOCATED (SELF%STTEM)
WRITE (KLUN) LSTTEM
IF (LSTTEM) THEN
  WRITE (KLUN) LBOUND (SELF%STTEM)
  WRITE (KLUN) UBOUND (SELF%STTEM)
  WRITE (KLUN) SELF%STTEM
ENDIF
LSTDEN = ALLOCATED (SELF%STDEN)
WRITE (KLUN) LSTDEN
IF (LSTDEN) THEN
  WRITE (KLUN) LBOUND (SELF%STDEN)
  WRITE (KLUN) UBOUND (SELF%STDEN)
  WRITE (KLUN) SELF%STDEN
ENDIF
LSTZ = ALLOCATED (SELF%STZ)
WRITE (KLUN) LSTZ
IF (LSTZ) THEN
  WRITE (KLUN) LBOUND (SELF%STZ)
  WRITE (KLUN) UBOUND (SELF%STZ)
  WRITE (KLUN) SELF%STZ
ENDIF
LSVETAH = ALLOCATED (SELF%SVETAH)
WRITE (KLUN) LSVETAH
IF (LSVETAH) THEN
  WRITE (KLUN) LBOUND (SELF%SVETAH)
  WRITE (KLUN) UBOUND (SELF%SVETAH)
  WRITE (KLUN) SELF%SVETAH
ENDIF
LSVETAF = ALLOCATED (SELF%SVETAF)
WRITE (KLUN) LSVETAF
IF (LSVETAF) THEN
  WRITE (KLUN) LBOUND (SELF%SVETAF)
  WRITE (KLUN) UBOUND (SELF%SVETAF)
  WRITE (KLUN) SELF%SVETAF
ENDIF
END SUBROUTINE

END SUBMODULE
