SUBMODULE (YOMSRFTLAD) YOMSRFTLAD_TSRFTLAD_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TSRFTLAD (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TSRFTLAD), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LGPTSKIN0, LGPTSKIN9
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GPTSKIN0), CDPATH//'%GPTSKIN0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GPTSKIN9), CDPATH//'%GPTSKIN9'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGSKIN), CDPATH//'%NGSKIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LREGSF), CDPATH//'%LREGSF'

END SUBROUTINE

END SUBMODULE
