SUBMODULE (YOMSPHYHIST) YOMSPHYHIST_SPHYS_HIST_TYPE_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_SPHYS_HIST_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (SPHYS_HIST_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5
LYA5 = ASSOCIATED (SELF%YA5)
WRITE (KLUN) LYA5
IF (LYA5) THEN
  WRITE (KLUN) LBOUND (SELF%YA5)
  WRITE (KLUN) UBOUND (SELF%YA5)
  WRITE (KLUN) SELF%YA5
ENDIF
LYL5 = ASSOCIATED (SELF%YL5)
WRITE (KLUN) LYL5
IF (LYL5) THEN
  WRITE (KLUN) LBOUND (SELF%YL5)
  WRITE (KLUN) UBOUND (SELF%YL5)
  WRITE (KLUN) SELF%YL5
ENDIF
LYI5 = ASSOCIATED (SELF%YI5)
WRITE (KLUN) LYI5
IF (LYI5) THEN
  WRITE (KLUN) LBOUND (SELF%YI5)
  WRITE (KLUN) UBOUND (SELF%YI5)
  WRITE (KLUN) SELF%YI5
ENDIF
LRADLWM = ASSOCIATED (SELF%RADLWM)
WRITE (KLUN) LRADLWM
IF (LRADLWM) THEN
  WRITE (KLUN) LBOUND (SELF%RADLWM)
  WRITE (KLUN) UBOUND (SELF%RADLWM)
  WRITE (KLUN) SELF%RADLWM
ENDIF
LRADLWM5 = ASSOCIATED (SELF%RADLWM5)
WRITE (KLUN) LRADLWM5
IF (LRADLWM5) THEN
  WRITE (KLUN) LBOUND (SELF%RADLWM5)
  WRITE (KLUN) UBOUND (SELF%RADLWM5)
  WRITE (KLUN) SELF%RADLWM5
ENDIF
LTGWDWMSU = ASSOCIATED (SELF%TGWDWMSU)
WRITE (KLUN) LTGWDWMSU
IF (LTGWDWMSU) THEN
  WRITE (KLUN) LBOUND (SELF%TGWDWMSU)
  WRITE (KLUN) UBOUND (SELF%TGWDWMSU)
  WRITE (KLUN) SELF%TGWDWMSU
ENDIF
LTGWDWMSU5 = ASSOCIATED (SELF%TGWDWMSU5)
WRITE (KLUN) LTGWDWMSU5
IF (LTGWDWMSU5) THEN
  WRITE (KLUN) LBOUND (SELF%TGWDWMSU5)
  WRITE (KLUN) UBOUND (SELF%TGWDWMSU5)
  WRITE (KLUN) SELF%TGWDWMSU5
ENDIF
LTGWDWMSV = ASSOCIATED (SELF%TGWDWMSV)
WRITE (KLUN) LTGWDWMSV
IF (LTGWDWMSV) THEN
  WRITE (KLUN) LBOUND (SELF%TGWDWMSV)
  WRITE (KLUN) UBOUND (SELF%TGWDWMSV)
  WRITE (KLUN) SELF%TGWDWMSV
ENDIF
LTGWDWMSV5 = ASSOCIATED (SELF%TGWDWMSV5)
WRITE (KLUN) LTGWDWMSV5
IF (LTGWDWMSV5) THEN
  WRITE (KLUN) LBOUND (SELF%TGWDWMSV5)
  WRITE (KLUN) UBOUND (SELF%TGWDWMSV5)
  WRITE (KLUN) SELF%TGWDWMSV5
ENDIF
END SUBROUTINE

END SUBMODULE
