SUBMODULE (YOMSLPHY) YOMSLPHY_TSLPHY_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TSLPHY (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TSLPHY),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LRSLWX, LSAVTEND, LSAVTEND5
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LRSLWX = ALLOCATED (SELF%RSLWX)
IF (LRSLWX) THEN
  ISIZE = KIND (SELF%RSLWX) * SIZE (SELF%RSLWX)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSLWX'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%NVTEND)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NVTEND'
ENDIF
KSIZE = KSIZE + ISIZE
LSAVTEND = ALLOCATED (SELF%SAVTEND)
IF (LSAVTEND) THEN
  ISIZE = KIND (SELF%SAVTEND) * SIZE (SELF%SAVTEND)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%SAVTEND'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LSAVTEND5 = ALLOCATED (SELF%SAVTEND5)
IF (LSAVTEND5) THEN
  ISIZE = KIND (SELF%SAVTEND5) * SIZE (SELF%SAVTEND5)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%SAVTEND5'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%MU_SAVTEND)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MU_SAVTEND'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MV_SAVTEND)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MV_SAVTEND'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MT_SAVTEND)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MT_SAVTEND'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
