SUBMODULE (YOMTRC) YOMTRC_TTRC_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_TTRC (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TTRC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGDEOSI, LGDEOTI, LGDEOTI2, LGEOLT, LGEOXT, LGFLUXC, LGMIXP, LGMU0, LGMU0_MAX, LGMU0_MIN
LOGICAL :: LGRPROX, LGRSURF, LGUEOSI, LGUEOTI, LGUEOTI2
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LGRSURF = ALLOCATED (SELF%GRSURF)
IF (LGRSURF) THEN
  !$ACC ENTER DATA CREATE (SELF%GRSURF)
  !$ACC UPDATE DEVICE (SELF%GRSURF)
  !$ACC ENTER DATA ATTACH (SELF%GRSURF)
ENDIF

LGDEOTI = ALLOCATED (SELF%GDEOTI)
IF (LGDEOTI) THEN
  !$ACC ENTER DATA CREATE (SELF%GDEOTI)
  !$ACC UPDATE DEVICE (SELF%GDEOTI)
  !$ACC ENTER DATA ATTACH (SELF%GDEOTI)
ENDIF

LGDEOTI2 = ALLOCATED (SELF%GDEOTI2)
IF (LGDEOTI2) THEN
  !$ACC ENTER DATA CREATE (SELF%GDEOTI2)
  !$ACC UPDATE DEVICE (SELF%GDEOTI2)
  !$ACC ENTER DATA ATTACH (SELF%GDEOTI2)
ENDIF

LGUEOTI = ALLOCATED (SELF%GUEOTI)
IF (LGUEOTI) THEN
  !$ACC ENTER DATA CREATE (SELF%GUEOTI)
  !$ACC UPDATE DEVICE (SELF%GUEOTI)
  !$ACC ENTER DATA ATTACH (SELF%GUEOTI)
ENDIF

LGUEOTI2 = ALLOCATED (SELF%GUEOTI2)
IF (LGUEOTI2) THEN
  !$ACC ENTER DATA CREATE (SELF%GUEOTI2)
  !$ACC UPDATE DEVICE (SELF%GUEOTI2)
  !$ACC ENTER DATA ATTACH (SELF%GUEOTI2)
ENDIF

LGEOLT = ALLOCATED (SELF%GEOLT)
IF (LGEOLT) THEN
  !$ACC ENTER DATA CREATE (SELF%GEOLT)
  !$ACC UPDATE DEVICE (SELF%GEOLT)
  !$ACC ENTER DATA ATTACH (SELF%GEOLT)
ENDIF

LGEOXT = ALLOCATED (SELF%GEOXT)
IF (LGEOXT) THEN
  !$ACC ENTER DATA CREATE (SELF%GEOXT)
  !$ACC UPDATE DEVICE (SELF%GEOXT)
  !$ACC ENTER DATA ATTACH (SELF%GEOXT)
ENDIF

LGRPROX = ALLOCATED (SELF%GRPROX)
IF (LGRPROX) THEN
  !$ACC ENTER DATA CREATE (SELF%GRPROX)
  !$ACC UPDATE DEVICE (SELF%GRPROX)
  !$ACC ENTER DATA ATTACH (SELF%GRPROX)
ENDIF

LGMIXP = ALLOCATED (SELF%GMIXP)
IF (LGMIXP) THEN
  !$ACC ENTER DATA CREATE (SELF%GMIXP)
  !$ACC UPDATE DEVICE (SELF%GMIXP)
  !$ACC ENTER DATA ATTACH (SELF%GMIXP)
ENDIF

LGFLUXC = ALLOCATED (SELF%GFLUXC)
IF (LGFLUXC) THEN
  !$ACC ENTER DATA CREATE (SELF%GFLUXC)
  !$ACC UPDATE DEVICE (SELF%GFLUXC)
  !$ACC ENTER DATA ATTACH (SELF%GFLUXC)
ENDIF

LGDEOSI = ALLOCATED (SELF%GDEOSI)
IF (LGDEOSI) THEN
  !$ACC ENTER DATA CREATE (SELF%GDEOSI)
  !$ACC UPDATE DEVICE (SELF%GDEOSI)
  !$ACC ENTER DATA ATTACH (SELF%GDEOSI)
ENDIF

LGUEOSI = ALLOCATED (SELF%GUEOSI)
IF (LGUEOSI) THEN
  !$ACC ENTER DATA CREATE (SELF%GUEOSI)
  !$ACC UPDATE DEVICE (SELF%GUEOSI)
  !$ACC ENTER DATA ATTACH (SELF%GUEOSI)
ENDIF

LGMU0 = ALLOCATED (SELF%GMU0)
IF (LGMU0) THEN
  !$ACC ENTER DATA CREATE (SELF%GMU0)
  !$ACC UPDATE DEVICE (SELF%GMU0)
  !$ACC ENTER DATA ATTACH (SELF%GMU0)
ENDIF

LGMU0_MIN = ALLOCATED (SELF%GMU0_MIN)
IF (LGMU0_MIN) THEN
  !$ACC ENTER DATA CREATE (SELF%GMU0_MIN)
  !$ACC UPDATE DEVICE (SELF%GMU0_MIN)
  !$ACC ENTER DATA ATTACH (SELF%GMU0_MIN)
ENDIF

LGMU0_MAX = ALLOCATED (SELF%GMU0_MAX)
IF (LGMU0_MAX) THEN
  !$ACC ENTER DATA CREATE (SELF%GMU0_MAX)
  !$ACC UPDATE DEVICE (SELF%GMU0_MAX)
  !$ACC ENTER DATA ATTACH (SELF%GMU0_MAX)
ENDIF

END SUBROUTINE

END SUBMODULE
