SUBMODULE (YOMTOPH) YOMTOPH_TTOPH_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TTOPH (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TTOPH), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRMESOQ, LRMESOT, LRMESOU, LRQREL, LRTREL, LRUREL, LRVREL
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
READ (KLUN) LRMESOU
IF (LRMESOU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RMESOU (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RMESOU,1):UBOUND(SELF%RMESOU,1)))
  READ (KLUN) ZTMP1
  SELF%RMESOU = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRMESOT
IF (LRMESOT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RMESOT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RMESOT,1):UBOUND(SELF%RMESOT,1)))
  READ (KLUN) ZTMP1
  SELF%RMESOT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRMESOQ
IF (LRMESOQ) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RMESOQ (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RMESOQ,1):UBOUND(SELF%RMESOQ,1)))
  READ (KLUN) ZTMP1
  SELF%RMESOQ = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRUREL
IF (LRUREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RUREL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RUREL,1):UBOUND(SELF%RUREL,1)))
  READ (KLUN) ZTMP1
  SELF%RUREL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRVREL
IF (LRVREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RVREL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RVREL,1):UBOUND(SELF%RVREL,1)))
  READ (KLUN) ZTMP1
  SELF%RVREL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRTREL
IF (LRTREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RTREL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RTREL,1):UBOUND(SELF%RTREL,1)))
  READ (KLUN) ZTMP1
  SELF%RTREL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRQREL
IF (LRQREL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RQREL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RQREL,1):UBOUND(SELF%RQREL,1)))
  READ (KLUN) ZTMP1
  SELF%RQREL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
SELF%RFMESOQ = ZTMP0
READ (KLUN) SELF%NTQSAT
READ (KLUN) SELF%NTDIFU
READ (KLUN) SELF%NTCOEF
READ (KLUN) SELF%NTDRAG
READ (KLUN) SELF%NTCVIM
READ (KLUN) SELF%NT850
READ (KLUN) SELF%NT950
READ (KLUN) SELF%NTPLUI
READ (KLUN) SELF%NTRADI
READ (KLUN) SELF%NTNEBU
READ (KLUN) SELF%NTOZON
READ (KLUN) SELF%NTDRME
READ (KLUN) SELF%NTCOET
READ (KLUN) SELF%NTAJUC
READ (KLUN) SELF%NTRELAXT
READ (KLUN) SELF%NTRELAXQ
READ (KLUN) SELF%NTRELAXU
READ (KLUN) SELF%CHEM_HPSC_NTOP
READ (KLUN) SELF%CHEM_HPSC_NBOT
READ (KLUN) SELF%CHEM_HOXF_NBOT
READ (KLUN) SELF%CHEM_ELEM_NTOP
READ (KLUN) SELF%CHEM_RELA_NIV
READ (KLUN) SELF%CHEM_NO_NIV
READ (KLUN) ZTMP0
SELF%ETQSAT = ZTMP0
READ (KLUN) ZTMP0
SELF%ETDIFU = ZTMP0
READ (KLUN) ZTMP0
SELF%ETCOEF = ZTMP0
READ (KLUN) ZTMP0
SELF%ETDRAG = ZTMP0
READ (KLUN) ZTMP0
SELF%ETCVIM = ZTMP0
READ (KLUN) ZTMP0
SELF%ET850 = ZTMP0
READ (KLUN) ZTMP0
SELF%ET950 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETPLUI = ZTMP0
READ (KLUN) ZTMP0
SELF%ETRADI = ZTMP0
READ (KLUN) ZTMP0
SELF%ETNEBU = ZTMP0
READ (KLUN) ZTMP0
SELF%ETOZON = ZTMP0
READ (KLUN) ZTMP0
SELF%ETDRME = ZTMP0
READ (KLUN) ZTMP0
SELF%ETCOET = ZTMP0
READ (KLUN) ZTMP0
SELF%ETAJUC = ZTMP0
READ (KLUN) ZTMP0
SELF%ETRELAXT = ZTMP0
READ (KLUN) ZTMP0
SELF%ETRELAXQ = ZTMP0
READ (KLUN) ZTMP0
SELF%ETRELAXU = ZTMP0
READ (KLUN) ZTMP0
SELF%XDRMUK = ZTMP0
READ (KLUN) ZTMP0
SELF%XDRMUX = ZTMP0
READ (KLUN) ZTMP0
SELF%XDRMUP = ZTMP0
READ (KLUN) ZTMP0
SELF%XDRMTK = ZTMP0
READ (KLUN) ZTMP0
SELF%XDRMTX = ZTMP0
READ (KLUN) ZTMP0
SELF%XDRMTP = ZTMP0
READ (KLUN) ZTMP0
SELF%XDRMQK = ZTMP0
READ (KLUN) ZTMP0
SELF%XDRMQP = ZTMP0
READ (KLUN) ZTMP0
SELF%XDRMQX = ZTMP0
READ (KLUN) ZTMP0
SELF%RCLX = ZTMP0
READ (KLUN) ZTMP0
SELF%TPSCLIM = ZTMP0
READ (KLUN) ZTMP0
SELF%ETELEM = ZTMP0
READ (KLUN) ZTMP0
SELF%ETRELA = ZTMP0
READ (KLUN) ZTMP0
SELF%ETPSCT = ZTMP0
READ (KLUN) ZTMP0
SELF%ETPSCB = ZTMP0
READ (KLUN) ZTMP0
SELF%ETHOXF = ZTMP0
READ (KLUN) ZTMP0
SELF%ETCHEMNO = ZTMP0
END SUBROUTINE

END SUBMODULE
