SUBMODULE (YOMTNH) YOMTNH_TTNH_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TTNH (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TTNH), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LTRAJNH
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) SELF%NLENNH95B
READ (KLUN) LTRAJNH
IF (LTRAJNH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%TRAJNH (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%TRAJNH,1):UBOUND(SELF%TRAJNH,1), LBOUND(SELF%TRAJNH,2):UBOUND(SELF%TRAJNH,2)))
  READ (KLUN) ZTMP2
  SELF%TRAJNH = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
END SUBROUTINE

END SUBMODULE
