SUBMODULE (YOMTNH) YOMTNH_TTNH_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TTNH (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TTNH), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LTRAJNH
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLENNH95B), CDPATH//'%NLENNH95B'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TRAJNH), CDPATH//'%TRAJNH'

END SUBROUTINE

END SUBMODULE
