SUBMODULE (YOMTDDH) YOMTDDH_TTDDH_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TTDDH (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TTDDH), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL3(3), IU3(3)
LOGICAL :: LCFLDNAMES2D, LCFLDNAMES3D, LCFLDTYPES2D, LCFLDTYPES3D, LHDCS0, LHDCS1, LHDCVB0, LHDCVB1, LPDDHFSVI
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) LHDCVB0
IF (LHDCVB0) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%HDCVB0 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%HDCVB0,1):UBOUND(SELF%HDCVB0,1), LBOUND(SELF%HDCVB0,2):UBOUND(SELF%HDCVB0,2), LBOUND(SELF%HDCVB0,3):UBOUND(SELF%HDCVB0,3)))
  READ (KLUN) ZTMP3
  SELF%HDCVB0 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LHDCVB1
IF (LHDCVB1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%HDCVB1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%HDCVB1,1):UBOUND(SELF%HDCVB1,1), LBOUND(SELF%HDCVB1,2):UBOUND(SELF%HDCVB1,2), LBOUND(SELF%HDCVB1,3):UBOUND(SELF%HDCVB1,3)))
  READ (KLUN) ZTMP3
  SELF%HDCVB1 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LHDCS0
IF (LHDCS0) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%HDCS0 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%HDCS0,1):UBOUND(SELF%HDCS0,1), LBOUND(SELF%HDCS0,2):UBOUND(SELF%HDCS0,2), LBOUND(SELF%HDCS0,3):UBOUND(SELF%HDCS0,3)))
  READ (KLUN) ZTMP3
  SELF%HDCS0 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LHDCS1
IF (LHDCS1) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%HDCS1 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%HDCS1,1):UBOUND(SELF%HDCS1,1), LBOUND(SELF%HDCS1,2):UBOUND(SELF%HDCS1,2), LBOUND(SELF%HDCS1,3):UBOUND(SELF%HDCS1,3)))
  READ (KLUN) ZTMP3
  SELF%HDCS1 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LPDDHFSVI
IF (LPDDHFSVI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%PDDHFSVI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%PDDHFSVI,1):UBOUND(SELF%PDDHFSVI,1)))
  READ (KLUN) ZTMP1
  SELF%PDDHFSVI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LCFLDNAMES3D
IF (LCFLDNAMES3D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%CFLDNAMES3D (IL1(1):IU1(1)))
  READ (KLUN) SELF%CFLDNAMES3D
ENDIF
READ (KLUN) LCFLDTYPES3D
IF (LCFLDTYPES3D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%CFLDTYPES3D (IL1(1):IU1(1)))
  READ (KLUN) SELF%CFLDTYPES3D
ENDIF
READ (KLUN) LCFLDNAMES2D
IF (LCFLDNAMES2D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%CFLDNAMES2D (IL1(1):IU1(1)))
  READ (KLUN) SELF%CFLDNAMES2D
ENDIF
READ (KLUN) LCFLDTYPES2D
IF (LCFLDTYPES2D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%CFLDTYPES2D (IL1(1):IU1(1)))
  READ (KLUN) SELF%CFLDTYPES2D
ENDIF
END SUBROUTINE

END SUBMODULE
