SUBMODULE (YOMVERT) YOMVERT_TVFE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TVFE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TVFE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LRDDERBF01, LRDDERI, LRDERB, LRDERBF00, LRDERBF01, LRDERBF10, LRDERBF11, LRDERBH00, LRDERBH01, LRDERGW
LOGICAL :: LRDERI, LRINTBF00, LRINTBF11, LRINTC, LRINTE, LRINTG, LRINTGW, LVFE_KNOT
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VFE_KNOT), CDPATH//'%VFE_KNOT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RINTE), CDPATH//'%RINTE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RINTBF00), CDPATH//'%RINTBF00'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RINTBF11), CDPATH//'%RINTBF11'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDERI), CDPATH//'%RDERI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDERB), CDPATH//'%RDERB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDERBF00), CDPATH//'%RDERBF00'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDERBF01), CDPATH//'%RDERBF01'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDERBF10), CDPATH//'%RDERBF10'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDERBF11), CDPATH//'%RDERBF11'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDERBH00), CDPATH//'%RDERBH00'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDERBH01), CDPATH//'%RDERBH01'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDDERI), CDPATH//'%RDDERI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDDERBF01), CDPATH//'%RDDERBF01'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RINTGW), CDPATH//'%RINTGW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDERGW), CDPATH//'%RDERGW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RINTG), CDPATH//'%RINTG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RINTC), CDPATH//'%RINTC'

END SUBROUTINE

END SUBMODULE
