SUBMODULE (YOMVERT) YOMVERT_TVAB_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TVAB (SELF, KLUN)

IMPLICIT NONE
CLASS (TVAB), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LVAF, LVAH, LVALH, LVBF, LVBH, LVC, LVDELA, LVDELB
LVALH = ALLOCATED (SELF%VALH)
WRITE (KLUN) LVALH
IF (LVALH) THEN
  WRITE (KLUN) LBOUND (SELF%VALH)
  WRITE (KLUN) UBOUND (SELF%VALH)
  WRITE (KLUN) SELF%VALH
ENDIF
LVBH = ALLOCATED (SELF%VBH)
WRITE (KLUN) LVBH
IF (LVBH) THEN
  WRITE (KLUN) LBOUND (SELF%VBH)
  WRITE (KLUN) UBOUND (SELF%VBH)
  WRITE (KLUN) SELF%VBH
ENDIF
LVAH = ALLOCATED (SELF%VAH)
WRITE (KLUN) LVAH
IF (LVAH) THEN
  WRITE (KLUN) LBOUND (SELF%VAH)
  WRITE (KLUN) UBOUND (SELF%VAH)
  WRITE (KLUN) SELF%VAH
ENDIF
LVC = ALLOCATED (SELF%VC)
WRITE (KLUN) LVC
IF (LVC) THEN
  WRITE (KLUN) LBOUND (SELF%VC)
  WRITE (KLUN) UBOUND (SELF%VC)
  WRITE (KLUN) SELF%VC
ENDIF
LVAF = ALLOCATED (SELF%VAF)
WRITE (KLUN) LVAF
IF (LVAF) THEN
  WRITE (KLUN) LBOUND (SELF%VAF)
  WRITE (KLUN) UBOUND (SELF%VAF)
  WRITE (KLUN) SELF%VAF
ENDIF
LVBF = ALLOCATED (SELF%VBF)
WRITE (KLUN) LVBF
IF (LVBF) THEN
  WRITE (KLUN) LBOUND (SELF%VBF)
  WRITE (KLUN) UBOUND (SELF%VBF)
  WRITE (KLUN) SELF%VBF
ENDIF
LVDELA = ALLOCATED (SELF%VDELA)
WRITE (KLUN) LVDELA
IF (LVDELA) THEN
  WRITE (KLUN) LBOUND (SELF%VDELA)
  WRITE (KLUN) UBOUND (SELF%VDELA)
  WRITE (KLUN) SELF%VDELA
ENDIF
LVDELB = ALLOCATED (SELF%VDELB)
WRITE (KLUN) LVDELB
IF (LVDELB) THEN
  WRITE (KLUN) LBOUND (SELF%VDELB)
  WRITE (KLUN) UBOUND (SELF%VDELB)
  WRITE (KLUN) SELF%VDELB
ENDIF
END SUBROUTINE

END SUBMODULE
