SUBMODULE (YOMVDOZ) YOMVDOZ_TVDOZ_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TVDOZ (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TVDOZ),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%VDHJS) * SIZE (SELF%VDHJS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDHJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDHJH) * SIZE (SELF%VDHJH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDHJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDHNS) * SIZE (SELF%VDHNS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDHNS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDHNH) * SIZE (SELF%VDHNH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDHNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDPJS) * SIZE (SELF%VDPJS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDPJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDPJH) * SIZE (SELF%VDPJH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDPJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDPNS) * SIZE (SELF%VDPNS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDPNS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDPNH) * SIZE (SELF%VDPNH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDPNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDEJS) * SIZE (SELF%VDEJS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDEJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDEJH) * SIZE (SELF%VDEJH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDEJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDENS) * SIZE (SELF%VDENS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDENS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDENH) * SIZE (SELF%VDENH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDENH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDAJS) * SIZE (SELF%VDAJS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDAJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDAJH) * SIZE (SELF%VDAJH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDAJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDANS) * SIZE (SELF%VDANS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDANS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDANH) * SIZE (SELF%VDANH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDANH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDNJS) * SIZE (SELF%VDNJS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDNJS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDNJH) * SIZE (SELF%VDNJH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDNJH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDNNS) * SIZE (SELF%VDNNS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDNNS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VDNNH) * SIZE (SELF%VDNNH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VDNNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VOZNJ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VOZNJ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%VOZHS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VOZHS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LRDIFOZ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRDIFOZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LRDEPOZ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRDEPOZ'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
