SUBMODULE (YOMVERT) YOMVERT_TVERTICAL_GEOM_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_TVERTICAL_GEOM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TVERTICAL_GEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL SELF%YRVAB%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRVETA%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRVFE%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRCVER%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
