SUBMODULE (YOPHNC) YOPHNC_TPHNC_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TPHNC (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TPHNC), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LETRAJP), CDPATH//'%LETRAJP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LETRAJPT), CDPATH//'%LETRAJPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADI2), CDPATH//'%LERADI2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADS2), CDPATH//'%LERADS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADSW2), CDPATH//'%LERADSW2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADN2), CDPATH//'%LERADN2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADFL2), CDPATH//'%LERADFL2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADLW2), CDPATH//'%LERADLW2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LH2OCO2), CDPATH//'%LH2OCO2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LWLOPT), CDPATH//'%LWLOPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LWSOPT), CDPATH//'%LWSOPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEDCLD2), CDPATH//'%LEDCLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEPCLD2), CDPATH//'%LEPCLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LENCLD2), CDPATH//'%LENCLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEVAPLS2), CDPATH//'%LEVAPLS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEVDIF2), CDPATH//'%LEVDIF2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEGWDG2), CDPATH//'%LEGWDG2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LECUMF2), CDPATH//'%LECUMF2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LECOND2), CDPATH//'%LECOND2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEGWWMS2), CDPATH//'%LEGWWMS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEQNGT2), CDPATH//'%LEQNGT2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LESURF2), CDPATH//'%LESURF2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEKPERT), CDPATH//'%LEKPERT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEKPERTS), CDPATH//'%LEKPERTS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LTRACLNPH), CDPATH//'%LTRACLNPH'

END SUBROUTINE

END SUBMODULE
