MODULE UTIL_TELBC_GEO_MOD

USE YEMLBC_GEO, ONLY : TELBC_GEO

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TELBC_GEO
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TELBC_GEO
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TELBC_GEO
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TELBC_GEO
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TELBC_GEO
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TELBC_GEO
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TELBC_GEO
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TELBC_GEO (SELF, KLUN)

IMPLICIT NONE
TYPE (TELBC_GEO), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LMPTRCPLBLK, LNIND_LEN, LNIND_LIST
LNIND_LIST = ALLOCATED (SELF%NIND_LIST)
WRITE (KLUN) LNIND_LIST
IF (LNIND_LIST) THEN
  WRITE (KLUN) LBOUND (SELF%NIND_LIST)
  WRITE (KLUN) UBOUND (SELF%NIND_LIST)
  WRITE (KLUN) SELF%NIND_LIST
ENDIF
LNIND_LEN = ALLOCATED (SELF%NIND_LEN)
WRITE (KLUN) LNIND_LEN
IF (LNIND_LEN) THEN
  WRITE (KLUN) LBOUND (SELF%NIND_LEN)
  WRITE (KLUN) UBOUND (SELF%NIND_LEN)
  WRITE (KLUN) SELF%NIND_LEN
ENDIF
WRITE (KLUN) SELF%NCPLBLKS
LMPTRCPLBLK = ALLOCATED (SELF%MPTRCPLBLK)
WRITE (KLUN) LMPTRCPLBLK
IF (LMPTRCPLBLK) THEN
  WRITE (KLUN) LBOUND (SELF%MPTRCPLBLK)
  WRITE (KLUN) UBOUND (SELF%MPTRCPLBLK)
  WRITE (KLUN) SELF%MPTRCPLBLK
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TELBC_GEO (SELF, KLUN)

IMPLICIT NONE
TYPE (TELBC_GEO), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LMPTRCPLBLK, LNIND_LEN, LNIND_LIST
READ (KLUN) LNIND_LIST
IF (LNIND_LIST) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NIND_LIST (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NIND_LIST
ENDIF
READ (KLUN) LNIND_LEN
IF (LNIND_LEN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NIND_LEN (IL1(1):IU1(1)))
  READ (KLUN) SELF%NIND_LEN
ENDIF
READ (KLUN) SELF%NCPLBLKS
READ (KLUN) LMPTRCPLBLK
IF (LMPTRCPLBLK) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%MPTRCPLBLK (IL1(1):IU1(1)))
  READ (KLUN) SELF%MPTRCPLBLK
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_COPY_TELBC_GEO (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TELBC_GEO), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMPTRCPLBLK, LNIND_LEN, LNIND_LIST
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LNIND_LIST = ALLOCATED (SELF%NIND_LIST)
IF (LNIND_LIST) THEN
  !$ACC ENTER DATA CREATE (SELF%NIND_LIST)
  !$ACC UPDATE DEVICE (SELF%NIND_LIST)
  !$ACC ENTER DATA ATTACH (SELF%NIND_LIST)
ENDIF

LNIND_LEN = ALLOCATED (SELF%NIND_LEN)
IF (LNIND_LEN) THEN
  !$ACC ENTER DATA CREATE (SELF%NIND_LEN)
  !$ACC UPDATE DEVICE (SELF%NIND_LEN)
  !$ACC ENTER DATA ATTACH (SELF%NIND_LEN)
ENDIF

LMPTRCPLBLK = ALLOCATED (SELF%MPTRCPLBLK)
IF (LMPTRCPLBLK) THEN
  !$ACC ENTER DATA CREATE (SELF%MPTRCPLBLK)
  !$ACC UPDATE DEVICE (SELF%MPTRCPLBLK)
  !$ACC ENTER DATA ATTACH (SELF%MPTRCPLBLK)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TELBC_GEO (SELF)

IMPLICIT NONE
TYPE (TELBC_GEO), TARGET :: SELF
LOGICAL :: LMPTRCPLBLK, LNIND_LEN, LNIND_LIST

END SUBROUTINE



SUBROUTINE ACDC_CRC64_TELBC_GEO (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TELBC_GEO), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LMPTRCPLBLK, LNIND_LEN, LNIND_LIST
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIND_LIST), CDPATH//'%NIND_LIST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NIND_LEN), CDPATH//'%NIND_LEN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCPLBLKS), CDPATH//'%NCPLBLKS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MPTRCPLBLK), CDPATH//'%MPTRCPLBLK'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TELBC_GEO (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TELBC_GEO), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMPTRCPLBLK, LNIND_LEN, LNIND_LIST
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LNIND_LIST = ALLOCATED (SELF%NIND_LIST)
IF (LNIND_LIST) THEN
  !$ACC EXIT DATA DETACH (SELF%NIND_LIST)
  !$ACC EXIT DATA DELETE (SELF%NIND_LIST)
ENDIF

LNIND_LEN = ALLOCATED (SELF%NIND_LEN)
IF (LNIND_LEN) THEN
  !$ACC EXIT DATA DETACH (SELF%NIND_LEN)
  !$ACC EXIT DATA DELETE (SELF%NIND_LEN)
ENDIF

LMPTRCPLBLK = ALLOCATED (SELF%MPTRCPLBLK)
IF (LMPTRCPLBLK) THEN
  !$ACC EXIT DATA DETACH (SELF%MPTRCPLBLK)
  !$ACC EXIT DATA DELETE (SELF%MPTRCPLBLK)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TELBC_GEO (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TELBC_GEO),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LMPTRCPLBLK, LNIND_LEN, LNIND_LIST
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LNIND_LIST = ALLOCATED (SELF%NIND_LIST)
IF (LNIND_LIST) THEN
  ISIZE = KIND (SELF%NIND_LIST) * SIZE (SELF%NIND_LIST)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NIND_LIST'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNIND_LEN = ALLOCATED (SELF%NIND_LEN)
IF (LNIND_LEN) THEN
  ISIZE = KIND (SELF%NIND_LEN) * SIZE (SELF%NIND_LEN)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NIND_LEN'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%NCPLBLKS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCPLBLKS'
ENDIF
KSIZE = KSIZE + ISIZE
LMPTRCPLBLK = ALLOCATED (SELF%MPTRCPLBLK)
IF (LMPTRCPLBLK) THEN
  ISIZE = KIND (SELF%MPTRCPLBLK) * SIZE (SELF%MPTRCPLBLK)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MPTRCPLBLK'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
