MODULE UTIL_TEGEO_MOD

USE YEMGEO, ONLY : TEGEO

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TEGEO
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TEGEO
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TEGEO
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TEGEO
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TEGEO
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TEGEO
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TEGEO
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TEGEO (SELF, KLUN)

IMPLICIT NONE
TYPE (TEGEO), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%ERPK
WRITE (KLUN) SELF%ELON1
WRITE (KLUN) SELF%ELAT1
WRITE (KLUN) SELF%ELON2
WRITE (KLUN) SELF%ELAT2
WRITE (KLUN) SELF%ELON0
WRITE (KLUN) SELF%ELAT0
WRITE (KLUN) SELF%ELONC
WRITE (KLUN) SELF%ELATC
WRITE (KLUN) SELF%EDELX
WRITE (KLUN) SELF%EDELY
WRITE (KLUN) SELF%ELX
WRITE (KLUN) SELF%ELY
WRITE (KLUN) SELF%EXWN
WRITE (KLUN) SELF%EYWN
WRITE (KLUN) SELF%RCORI_ACAD
WRITE (KLUN) SELF%RLAT_ACAD
WRITE (KLUN) SELF%RLON_ACAD
WRITE (KLUN) SELF%LMAP
WRITE (KLUN) SELF%LMRT
WRITE (KLUN) SELF%LREDEL_IN_METRES
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TEGEO (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TEGEO), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
SELF%ERPK = ZTMP0
READ (KLUN) ZTMP0
SELF%ELON1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELAT1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELON2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELAT2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELON0 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELAT0 = ZTMP0
READ (KLUN) ZTMP0
SELF%ELONC = ZTMP0
READ (KLUN) ZTMP0
SELF%ELATC = ZTMP0
READ (KLUN) ZTMP0
SELF%EDELX = ZTMP0
READ (KLUN) ZTMP0
SELF%EDELY = ZTMP0
READ (KLUN) ZTMP0
SELF%ELX = ZTMP0
READ (KLUN) ZTMP0
SELF%ELY = ZTMP0
READ (KLUN) ZTMP0
SELF%EXWN = ZTMP0
READ (KLUN) ZTMP0
SELF%EYWN = ZTMP0
READ (KLUN) ZTMP0
SELF%RCORI_ACAD = ZTMP0
READ (KLUN) ZTMP0
SELF%RLAT_ACAD = ZTMP0
READ (KLUN) ZTMP0
SELF%RLON_ACAD = ZTMP0
READ (KLUN) SELF%LMAP
READ (KLUN) SELF%LMRT
READ (KLUN) SELF%LREDEL_IN_METRES
END SUBROUTINE

SUBROUTINE ACDC_COPY_TEGEO (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEGEO), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TEGEO (SELF)

IMPLICIT NONE
TYPE (TEGEO), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TEGEO (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TEGEO), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ERPK), CDPATH//'%ERPK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELON1), CDPATH//'%ELON1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELAT1), CDPATH//'%ELAT1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELON2), CDPATH//'%ELON2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELAT2), CDPATH//'%ELAT2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELON0), CDPATH//'%ELON0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELAT0), CDPATH//'%ELAT0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELONC), CDPATH//'%ELONC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELATC), CDPATH//'%ELATC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EDELX), CDPATH//'%EDELX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EDELY), CDPATH//'%EDELY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELX), CDPATH//'%ELX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ELY), CDPATH//'%ELY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EXWN), CDPATH//'%EXWN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EYWN), CDPATH//'%EYWN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCORI_ACAD), CDPATH//'%RCORI_ACAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLAT_ACAD), CDPATH//'%RLAT_ACAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLON_ACAD), CDPATH//'%RLON_ACAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMAP), CDPATH//'%LMAP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMRT), CDPATH//'%LMRT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LREDEL_IN_METRES), CDPATH//'%LREDEL_IN_METRES'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TEGEO (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEGEO), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TEGEO (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TEGEO),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%ERPK)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ERPK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELON1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELON1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELAT1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELAT1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELON2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELON2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELAT2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELAT2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELON0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELON0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELAT0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELAT0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELONC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELONC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELATC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELATC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EDELX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EDELX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EDELY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EDELY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%ELY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ELY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EXWN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EXWN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%EYWN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%EYWN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RCORI_ACAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCORI_ACAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLAT_ACAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLAT_ACAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RLON_ACAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RLON_ACAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMAP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMAP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMRT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMRT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LREDEL_IN_METRES)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LREDEL_IN_METRES'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
