MODULE UTIL_TEAERSNK_MOD

USE YOEAERSNK, ONLY : TEAERSNK

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TEAERSNK
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TEAERSNK
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TEAERSNK
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TEAERSNK
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TEAERSNK
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TEAERSNK
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TEAERSNK
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TEAERSNK (SELF, KLUN)

IMPLICIT NONE
TYPE (TEAERSNK), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NDRYDEPVEL_DYN
WRITE (KLUN) SELF%NDRYDEP
WRITE (KLUN) SELF%R_R
WRITE (KLUN) SELF%R_S
WRITE (KLUN) SELF%RAERTS
WRITE (KLUN) SELF%RFRAER
WRITE (KLUN) SELF%RRHTAB
WRITE (KLUN) SELF%RRHTAB15
WRITE (KLUN) SELF%RSSGROWTH_RHTAB
WRITE (KLUN) SELF%RSSDENS_RHTAB
WRITE (KLUN) SELF%RSSGROWTH_RHTAB15
WRITE (KLUN) SELF%RSSDENS_RHTAB15
WRITE (KLUN) SELF%RMMD_DD
WRITE (KLUN) SELF%RRHO_DD
WRITE (KLUN) SELF%RMMD_NI
WRITE (KLUN) SELF%RRHO_NI
WRITE (KLUN) SELF%RMMD_SS
WRITE (KLUN) SELF%RRHO_SS
WRITE (KLUN) SELF%RHO_WAT
WRITE (KLUN) SELF%RHO_ICE
WRITE (KLUN) SELF%RHAMAKER
WRITE (KLUN) SELF%RSO2CV1
WRITE (KLUN) SELF%RSO2CV2
WRITE (KLUN) SELF%RSUCV1
WRITE (KLUN) SELF%RSUCV2
WRITE (KLUN) SELF%RVSO2CV1
WRITE (KLUN) SELF%RVSO2CV2
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TEAERSNK (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TEAERSNK), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
READ (KLUN) SELF%NDRYDEPVEL_DYN
READ (KLUN) SELF%NDRYDEP
READ (KLUN) ZTMP0
SELF%R_R = ZTMP0
READ (KLUN) ZTMP0
SELF%R_S = ZTMP0
ALLOCATE (ZTMP1(LBOUND(SELF%RAERTS,1):UBOUND(SELF%RAERTS,1)))
READ (KLUN) ZTMP1
SELF%RAERTS = ZTMP1
DEALLOCATE (ZTMP1)
READ (KLUN) ZTMP0
SELF%RFRAER = ZTMP0
ALLOCATE (ZTMP1(LBOUND(SELF%RRHTAB,1):UBOUND(SELF%RRHTAB,1)))
READ (KLUN) ZTMP1
SELF%RRHTAB = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RRHTAB15,1):UBOUND(SELF%RRHTAB15,1)))
READ (KLUN) ZTMP1
SELF%RRHTAB15 = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RSSGROWTH_RHTAB,1):UBOUND(SELF%RSSGROWTH_RHTAB,1)))
READ (KLUN) ZTMP1
SELF%RSSGROWTH_RHTAB = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RSSDENS_RHTAB,1):UBOUND(SELF%RSSDENS_RHTAB,1)))
READ (KLUN) ZTMP1
SELF%RSSDENS_RHTAB = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RSSGROWTH_RHTAB15,1):UBOUND(SELF%RSSGROWTH_RHTAB15,1)))
READ (KLUN) ZTMP1
SELF%RSSGROWTH_RHTAB15 = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RSSDENS_RHTAB15,1):UBOUND(SELF%RSSDENS_RHTAB15,1)))
READ (KLUN) ZTMP1
SELF%RSSDENS_RHTAB15 = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RMMD_DD,1):UBOUND(SELF%RMMD_DD,1)))
READ (KLUN) ZTMP1
SELF%RMMD_DD = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RRHO_DD,1):UBOUND(SELF%RRHO_DD,1)))
READ (KLUN) ZTMP1
SELF%RRHO_DD = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RMMD_NI,1):UBOUND(SELF%RMMD_NI,1)))
READ (KLUN) ZTMP1
SELF%RMMD_NI = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RRHO_NI,1):UBOUND(SELF%RRHO_NI,1)))
READ (KLUN) ZTMP1
SELF%RRHO_NI = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RMMD_SS,1):UBOUND(SELF%RMMD_SS,1)))
READ (KLUN) ZTMP1
SELF%RMMD_SS = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RRHO_SS,1):UBOUND(SELF%RRHO_SS,1)))
READ (KLUN) ZTMP1
SELF%RRHO_SS = ZTMP1
DEALLOCATE (ZTMP1)
READ (KLUN) ZTMP0
SELF%RHO_WAT = ZTMP0
READ (KLUN) ZTMP0
SELF%RHO_ICE = ZTMP0
READ (KLUN) ZTMP0
SELF%RHAMAKER = ZTMP0
READ (KLUN) ZTMP0
SELF%RSO2CV1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RSO2CV2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RSUCV1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RSUCV2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RVSO2CV1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RVSO2CV2 = ZTMP0
END SUBROUTINE

SUBROUTINE ACDC_COPY_TEAERSNK (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEAERSNK), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TEAERSNK (SELF)

IMPLICIT NONE
TYPE (TEAERSNK), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TEAERSNK (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TEAERSNK), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDRYDEPVEL_DYN), CDPATH//'%NDRYDEPVEL_DYN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDRYDEP), CDPATH//'%NDRYDEP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R_R), CDPATH//'%R_R'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R_S), CDPATH//'%R_S'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAERTS), CDPATH//'%RAERTS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFRAER), CDPATH//'%RFRAER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHTAB), CDPATH//'%RRHTAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHTAB15), CDPATH//'%RRHTAB15'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSSGROWTH_RHTAB), CDPATH//'%RSSGROWTH_RHTAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSSDENS_RHTAB), CDPATH//'%RSSDENS_RHTAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSSGROWTH_RHTAB15), CDPATH//'%RSSGROWTH_RHTAB15'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSSDENS_RHTAB15), CDPATH//'%RSSDENS_RHTAB15'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMMD_DD), CDPATH//'%RMMD_DD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHO_DD), CDPATH//'%RRHO_DD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMMD_NI), CDPATH//'%RMMD_NI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHO_NI), CDPATH//'%RRHO_NI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMMD_SS), CDPATH//'%RMMD_SS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHO_SS), CDPATH//'%RRHO_SS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHO_WAT), CDPATH//'%RHO_WAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHO_ICE), CDPATH//'%RHO_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHAMAKER), CDPATH//'%RHAMAKER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSO2CV1), CDPATH//'%RSO2CV1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSO2CV2), CDPATH//'%RSO2CV2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSUCV1), CDPATH//'%RSUCV1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSUCV2), CDPATH//'%RSUCV2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RVSO2CV1), CDPATH//'%RVSO2CV1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RVSO2CV2), CDPATH//'%RVSO2CV2'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TEAERSNK (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEAERSNK), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TEAERSNK (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TEAERSNK),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NDRYDEPVEL_DYN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDRYDEPVEL_DYN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDRYDEP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDRYDEP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%R_R)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%R_R'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%R_S)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%R_S'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RAERTS) * SIZE (SELF%RAERTS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAERTS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RFRAER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RFRAER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRHTAB) * SIZE (SELF%RRHTAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRHTAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRHTAB15) * SIZE (SELF%RRHTAB15)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRHTAB15'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSSGROWTH_RHTAB) * SIZE (SELF%RSSGROWTH_RHTAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSSGROWTH_RHTAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSSDENS_RHTAB) * SIZE (SELF%RSSDENS_RHTAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSSDENS_RHTAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSSGROWTH_RHTAB15) * SIZE (SELF%RSSGROWTH_RHTAB15)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSSGROWTH_RHTAB15'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSSDENS_RHTAB15) * SIZE (SELF%RSSDENS_RHTAB15)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSSDENS_RHTAB15'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RMMD_DD) * SIZE (SELF%RMMD_DD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RMMD_DD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRHO_DD) * SIZE (SELF%RRHO_DD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRHO_DD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RMMD_NI) * SIZE (SELF%RMMD_NI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RMMD_NI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRHO_NI) * SIZE (SELF%RRHO_NI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRHO_NI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RMMD_SS) * SIZE (SELF%RMMD_SS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RMMD_SS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RRHO_SS) * SIZE (SELF%RRHO_SS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RRHO_SS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RHO_WAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RHO_WAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RHO_ICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RHO_ICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RHAMAKER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RHAMAKER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSO2CV1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSO2CV1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSO2CV2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSO2CV2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSUCV1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSUCV1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RSUCV2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSUCV2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RVSO2CV1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RVSO2CV1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RVSO2CV2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RVSO2CV2'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
