MODULE UTIL_TSDDH_MOD

USE YOMSDDH, ONLY : TSDDH

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TSDDH
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TSDDH
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TSDDH
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TSDDH
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TSDDH
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TSDDH
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TSDDH
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TSDDH (SELF, KLUN)

IMPLICIT NONE
TYPE (TSDDH), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NHDQLNVA
WRITE (KLUN) SELF%NHDQLNTD
WRITE (KLUN) SELF%NHDQLNFD
WRITE (KLUN) SELF%NHDQLNFP
WRITE (KLUN) SELF%NHDQLNTP
WRITE (KLUN) SELF%NHDPASVA
WRITE (KLUN) SELF%NHDPASTD
WRITE (KLUN) SELF%NHDPASFD
WRITE (KLUN) SELF%NHDPASFP
WRITE (KLUN) SELF%NHDPASTP
WRITE (KLUN) SELF%LHDQLN
WRITE (KLUN) SELF%LHDPAS
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TSDDH (SELF, KLUN)

IMPLICIT NONE
TYPE (TSDDH), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NHDQLNVA
READ (KLUN) SELF%NHDQLNTD
READ (KLUN) SELF%NHDQLNFD
READ (KLUN) SELF%NHDQLNFP
READ (KLUN) SELF%NHDQLNTP
READ (KLUN) SELF%NHDPASVA
READ (KLUN) SELF%NHDPASTD
READ (KLUN) SELF%NHDPASFD
READ (KLUN) SELF%NHDPASFP
READ (KLUN) SELF%NHDPASTP
READ (KLUN) SELF%LHDQLN
READ (KLUN) SELF%LHDPAS
END SUBROUTINE

SUBROUTINE ACDC_COPY_TSDDH (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSDDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TSDDH (SELF)

IMPLICIT NONE
TYPE (TSDDH), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TSDDH (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TSDDH), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDQLNVA), CDPATH//'%NHDQLNVA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDQLNTD), CDPATH//'%NHDQLNTD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDQLNFD), CDPATH//'%NHDQLNFD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDQLNFP), CDPATH//'%NHDQLNFP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDQLNTP), CDPATH//'%NHDQLNTP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDPASVA), CDPATH//'%NHDPASVA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDPASTD), CDPATH//'%NHDPASTD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDPASFD), CDPATH//'%NHDPASFD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDPASFP), CDPATH//'%NHDPASFP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NHDPASTP), CDPATH//'%NHDPASTP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDQLN), CDPATH//'%LHDQLN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDPAS), CDPATH//'%LHDPAS'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TSDDH (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSDDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TSDDH (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TSDDH),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NHDQLNVA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDQLNVA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NHDQLNTD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDQLNTD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NHDQLNFD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDQLNFD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NHDQLNFP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDQLNFP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NHDQLNTP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDQLNTP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NHDPASVA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDPASVA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NHDPASTD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDPASTD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NHDPASFD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDPASFD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NHDPASFP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDPASFP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NHDPASTP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NHDPASTP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDQLN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDQLN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDPAS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDPAS'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
