MODULE UTIL_TSPECTRALPLANCK_MOD

USE YOE_SPECTRAL_PLANCK, ONLY : TSPECTRALPLANCK

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TSPECTRALPLANCK
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TSPECTRALPLANCK
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TSPECTRALPLANCK
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TSPECTRALPLANCK
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TSPECTRALPLANCK
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TSPECTRALPLANCK
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TSPECTRALPLANCK
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TSPECTRALPLANCK (SELF, KLUN)

IMPLICIT NONE
TYPE (TSPECTRALPLANCK), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND
WRITE (KLUN) SELF%NINTERVALS
WRITE (KLUN) SELF%NTEMPS
WRITE (KLUN) SELF%TEMP1
WRITE (KLUN) SELF%DTEMP
LPLANCK_LUT = ALLOCATED (SELF%PLANCK_LUT)
WRITE (KLUN) LPLANCK_LUT
IF (LPLANCK_LUT) THEN
  WRITE (KLUN) LBOUND (SELF%PLANCK_LUT)
  WRITE (KLUN) UBOUND (SELF%PLANCK_LUT)
  WRITE (KLUN) SELF%PLANCK_LUT
ENDIF
LWAVLEN_BOUND = ALLOCATED (SELF%WAVLEN_BOUND)
WRITE (KLUN) LWAVLEN_BOUND
IF (LWAVLEN_BOUND) THEN
  WRITE (KLUN) LBOUND (SELF%WAVLEN_BOUND)
  WRITE (KLUN) UBOUND (SELF%WAVLEN_BOUND)
  WRITE (KLUN) SELF%WAVLEN_BOUND
ENDIF
LINTERVAL_MAP = ALLOCATED (SELF%INTERVAL_MAP)
WRITE (KLUN) LINTERVAL_MAP
IF (LINTERVAL_MAP) THEN
  WRITE (KLUN) LBOUND (SELF%INTERVAL_MAP)
  WRITE (KLUN) UBOUND (SELF%INTERVAL_MAP)
  WRITE (KLUN) SELF%INTERVAL_MAP
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TSPECTRALPLANCK (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TSPECTRALPLANCK), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) SELF%NINTERVALS
READ (KLUN) SELF%NTEMPS
READ (KLUN) ZTMP0
SELF%TEMP1 = ZTMP0
READ (KLUN) ZTMP0
SELF%DTEMP = ZTMP0
READ (KLUN) LPLANCK_LUT
IF (LPLANCK_LUT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%PLANCK_LUT (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%PLANCK_LUT,1):UBOUND(SELF%PLANCK_LUT,1), LBOUND(SELF%PLANCK_LUT,2):UBOUND(SELF%PLANCK_LUT,2)))
  READ (KLUN) ZTMP2
  SELF%PLANCK_LUT = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LWAVLEN_BOUND
IF (LWAVLEN_BOUND) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%WAVLEN_BOUND (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%WAVLEN_BOUND,1):UBOUND(SELF%WAVLEN_BOUND,1)))
  READ (KLUN) ZTMP1
  SELF%WAVLEN_BOUND = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LINTERVAL_MAP
IF (LINTERVAL_MAP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%INTERVAL_MAP (IL1(1):IU1(1)))
  READ (KLUN) SELF%INTERVAL_MAP
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_COPY_TSPECTRALPLANCK (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSPECTRALPLANCK), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LPLANCK_LUT = ALLOCATED (SELF%PLANCK_LUT)
IF (LPLANCK_LUT) THEN
  !$ACC ENTER DATA CREATE (SELF%PLANCK_LUT)
  !$ACC UPDATE DEVICE (SELF%PLANCK_LUT)
  !$ACC ENTER DATA ATTACH (SELF%PLANCK_LUT)
ENDIF

LWAVLEN_BOUND = ALLOCATED (SELF%WAVLEN_BOUND)
IF (LWAVLEN_BOUND) THEN
  !$ACC ENTER DATA CREATE (SELF%WAVLEN_BOUND)
  !$ACC UPDATE DEVICE (SELF%WAVLEN_BOUND)
  !$ACC ENTER DATA ATTACH (SELF%WAVLEN_BOUND)
ENDIF

LINTERVAL_MAP = ALLOCATED (SELF%INTERVAL_MAP)
IF (LINTERVAL_MAP) THEN
  !$ACC ENTER DATA CREATE (SELF%INTERVAL_MAP)
  !$ACC UPDATE DEVICE (SELF%INTERVAL_MAP)
  !$ACC ENTER DATA ATTACH (SELF%INTERVAL_MAP)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TSPECTRALPLANCK (SELF)

IMPLICIT NONE
TYPE (TSPECTRALPLANCK), TARGET :: SELF
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND

END SUBROUTINE



SUBROUTINE ACDC_CRC64_TSPECTRALPLANCK (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TSPECTRALPLANCK), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NINTERVALS), CDPATH//'%NINTERVALS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NTEMPS), CDPATH//'%NTEMPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TEMP1), CDPATH//'%TEMP1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%DTEMP), CDPATH//'%DTEMP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PLANCK_LUT), CDPATH//'%PLANCK_LUT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%WAVLEN_BOUND), CDPATH//'%WAVLEN_BOUND'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%INTERVAL_MAP), CDPATH//'%INTERVAL_MAP'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TSPECTRALPLANCK (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSPECTRALPLANCK), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LPLANCK_LUT = ALLOCATED (SELF%PLANCK_LUT)
IF (LPLANCK_LUT) THEN
  !$ACC EXIT DATA DETACH (SELF%PLANCK_LUT)
  !$ACC EXIT DATA DELETE (SELF%PLANCK_LUT)
ENDIF

LWAVLEN_BOUND = ALLOCATED (SELF%WAVLEN_BOUND)
IF (LWAVLEN_BOUND) THEN
  !$ACC EXIT DATA DETACH (SELF%WAVLEN_BOUND)
  !$ACC EXIT DATA DELETE (SELF%WAVLEN_BOUND)
ENDIF

LINTERVAL_MAP = ALLOCATED (SELF%INTERVAL_MAP)
IF (LINTERVAL_MAP) THEN
  !$ACC EXIT DATA DETACH (SELF%INTERVAL_MAP)
  !$ACC EXIT DATA DELETE (SELF%INTERVAL_MAP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TSPECTRALPLANCK (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TSPECTRALPLANCK),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LINTERVAL_MAP, LPLANCK_LUT, LWAVLEN_BOUND
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NINTERVALS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NINTERVALS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NTEMPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTEMPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TEMP1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TEMP1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%DTEMP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%DTEMP'
ENDIF
KSIZE = KSIZE + ISIZE
LPLANCK_LUT = ALLOCATED (SELF%PLANCK_LUT)
IF (LPLANCK_LUT) THEN
  ISIZE = KIND (SELF%PLANCK_LUT) * SIZE (SELF%PLANCK_LUT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%PLANCK_LUT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LWAVLEN_BOUND = ALLOCATED (SELF%WAVLEN_BOUND)
IF (LWAVLEN_BOUND) THEN
  ISIZE = KIND (SELF%WAVLEN_BOUND) * SIZE (SELF%WAVLEN_BOUND)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%WAVLEN_BOUND'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LINTERVAL_MAP = ALLOCATED (SELF%INTERVAL_MAP)
IF (LINTERVAL_MAP) THEN
  ISIZE = KIND (SELF%INTERVAL_MAP) * SIZE (SELF%INTERVAL_MAP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%INTERVAL_MAP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
