MODULE UTIL_TEMCICA_MOD

USE YOE_MCICA, ONLY : TEMCICA

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TEMCICA
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TEMCICA
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TEMCICA
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TEMCICA
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TEMCICA
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TEMCICA
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TEMCICA
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TEMCICA (SELF, KLUN)

IMPLICIT NONE
TYPE (TEMCICA), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%XCW
WRITE (KLUN) SELF%XCW_D
WRITE (KLUN) SELF%NMCI1
WRITE (KLUN) SELF%NMCI2
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TEMCICA (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TEMCICA), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
ALLOCATE (ZTMP2(LBOUND(SELF%XCW,1):UBOUND(SELF%XCW,1), LBOUND(SELF%XCW,2):UBOUND(SELF%XCW,2)))
READ (KLUN) ZTMP2
SELF%XCW = ZTMP2
DEALLOCATE (ZTMP2)
READ (KLUN) SELF%XCW_D
READ (KLUN) SELF%NMCI1
READ (KLUN) SELF%NMCI2
END SUBROUTINE

SUBROUTINE ACDC_COPY_TEMCICA (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEMCICA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TEMCICA (SELF)

IMPLICIT NONE
TYPE (TEMCICA), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TEMCICA (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TEMCICA), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XCW), CDPATH//'%XCW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XCW_D), CDPATH//'%XCW_D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NMCI1), CDPATH//'%NMCI1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NMCI2), CDPATH//'%NMCI2'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TEMCICA (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEMCICA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TEMCICA (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TEMCICA),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%XCW) * SIZE (SELF%XCW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XCW_D) * SIZE (SELF%XCW_D)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCW_D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NMCI1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NMCI1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NMCI2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NMCI2'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
