MODULE UTIL_TLDDH_MOD

USE YOMLDDH, ONLY : TLDDH

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TLDDH
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TLDDH
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TLDDH
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TLDDH
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TLDDH
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TLDDH
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TLDDH
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TLDDH (SELF, KLUN)

IMPLICIT NONE
TYPE (TLDDH), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LSDDH
WRITE (KLUN) SELF%LHDGLB
WRITE (KLUN) SELF%LHDZON
WRITE (KLUN) SELF%LHDDOP
WRITE (KLUN) SELF%LHDLFA
WRITE (KLUN) SELF%LHDHKS
WRITE (KLUN) SELF%LHDMCI
WRITE (KLUN) SELF%LHDENT
WRITE (KLUN) SELF%LHDPRG
WRITE (KLUN) SELF%LHDPRZ
WRITE (KLUN) SELF%LHDPRD
WRITE (KLUN) SELF%LHDPR
WRITE (KLUN) SELF%LHDEFG
WRITE (KLUN) SELF%LHDEFZ
WRITE (KLUN) SELF%LHDEFD
WRITE (KLUN) SELF%LHDLIST
WRITE (KLUN) SELF%LHDOUFG
WRITE (KLUN) SELF%LHDOUFZ
WRITE (KLUN) SELF%LHDOUFD
WRITE (KLUN) SELF%LHDOUP
WRITE (KLUN) SELF%LHDFIL
WRITE (KLUN) SELF%LONLYVAR
WRITE (KLUN) SELF%LHDORIGP
WRITE (KLUN) SELF%LHDCDPI
WRITE (KLUN) SELF%LFLEXDIA
WRITE (KLUN) SELF%LRDDHDYN
WRITE (KLUN) SELF%LRSLDDH
WRITE (KLUN) SELF%LRSIDDH
WRITE (KLUN) SELF%LRHDDDH
WRITE (KLUN) SELF%LDDH_OMP
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TLDDH (SELF, KLUN)

IMPLICIT NONE
TYPE (TLDDH), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%LSDDH
READ (KLUN) SELF%LHDGLB
READ (KLUN) SELF%LHDZON
READ (KLUN) SELF%LHDDOP
READ (KLUN) SELF%LHDLFA
READ (KLUN) SELF%LHDHKS
READ (KLUN) SELF%LHDMCI
READ (KLUN) SELF%LHDENT
READ (KLUN) SELF%LHDPRG
READ (KLUN) SELF%LHDPRZ
READ (KLUN) SELF%LHDPRD
READ (KLUN) SELF%LHDPR
READ (KLUN) SELF%LHDEFG
READ (KLUN) SELF%LHDEFZ
READ (KLUN) SELF%LHDEFD
READ (KLUN) SELF%LHDLIST
READ (KLUN) SELF%LHDOUFG
READ (KLUN) SELF%LHDOUFZ
READ (KLUN) SELF%LHDOUFD
READ (KLUN) SELF%LHDOUP
READ (KLUN) SELF%LHDFIL
READ (KLUN) SELF%LONLYVAR
READ (KLUN) SELF%LHDORIGP
READ (KLUN) SELF%LHDCDPI
READ (KLUN) SELF%LFLEXDIA
READ (KLUN) SELF%LRDDHDYN
READ (KLUN) SELF%LRSLDDH
READ (KLUN) SELF%LRSIDDH
READ (KLUN) SELF%LRHDDDH
READ (KLUN) SELF%LDDH_OMP
END SUBROUTINE

SUBROUTINE ACDC_COPY_TLDDH (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLDDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TLDDH (SELF)

IMPLICIT NONE
TYPE (TLDDH), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TLDDH (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TLDDH), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LSDDH), CDPATH//'%LSDDH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDGLB), CDPATH//'%LHDGLB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDZON), CDPATH//'%LHDZON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDDOP), CDPATH//'%LHDDOP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDLFA), CDPATH//'%LHDLFA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDHKS), CDPATH//'%LHDHKS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDMCI), CDPATH//'%LHDMCI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDENT), CDPATH//'%LHDENT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDPRG), CDPATH//'%LHDPRG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDPRZ), CDPATH//'%LHDPRZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDPRD), CDPATH//'%LHDPRD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDPR), CDPATH//'%LHDPR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDEFG), CDPATH//'%LHDEFG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDEFZ), CDPATH//'%LHDEFZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDEFD), CDPATH//'%LHDEFD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDLIST), CDPATH//'%LHDLIST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDOUFG), CDPATH//'%LHDOUFG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDOUFZ), CDPATH//'%LHDOUFZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDOUFD), CDPATH//'%LHDOUFD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDOUP), CDPATH//'%LHDOUP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDFIL), CDPATH//'%LHDFIL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LONLYVAR), CDPATH//'%LONLYVAR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDORIGP), CDPATH//'%LHDORIGP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LHDCDPI), CDPATH//'%LHDCDPI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LFLEXDIA), CDPATH//'%LFLEXDIA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LRDDHDYN), CDPATH//'%LRDDHDYN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LRSLDDH), CDPATH//'%LRSLDDH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LRSIDDH), CDPATH//'%LRSIDDH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LRHDDDH), CDPATH//'%LRHDDDH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LDDH_OMP), CDPATH//'%LDDH_OMP'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TLDDH (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TLDDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TLDDH (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TLDDH),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%LSDDH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSDDH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDGLB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDGLB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDZON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDZON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDDOP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDDOP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDLFA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDLFA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDHKS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDHKS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDMCI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDMCI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDENT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDENT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDPRG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDPRG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDPRZ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDPRZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDPRD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDPRD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDPR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDPR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDEFG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDEFG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDEFZ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDEFZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDEFD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDEFD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDLIST)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDLIST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDOUFG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDOUFG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDOUFZ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDOUFZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDOUFD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDOUFD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDOUP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDOUP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDFIL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDFIL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LONLYVAR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LONLYVAR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDORIGP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDORIGP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LHDCDPI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHDCDPI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LFLEXDIA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LFLEXDIA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LRDDHDYN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRDDHDYN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LRSLDDH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRSLDDH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LRSIDDH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRSIDDH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LRHDDDH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRHDDDH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LDDH_OMP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDDH_OMP'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
