MODULE UTIL_TMCC_MOD

USE YOMMCC, ONLY : TMCC

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TMCC
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TMCC
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TMCC
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TMCC
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TMCC
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TMCC
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TMCC
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TMCC (SELF, KLUN)
USE UTIL_CPLNG_FLD_TYPE_MOD
IMPLICIT NONE
TYPE (TMCC), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: J1
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
WRITE (KLUN) SELF%N923
WRITE (KLUN) SELF%NCLIMTOT
WRITE (KLUN) SELF%NCLIMR
WRITE (KLUN) SELF%NCLIGC
WRITE (KLUN) SELF%NCLIGC_COMPO
WRITE (KLUN) SELF%NYSDMP_COMPO
WRITE (KLUN) SELF%NCLIMR_COMPO
WRITE (KLUN) SELF%NCLIAER
WRITE (KLUN) SELF%NDIFC
WRITE (KLUN) SELF%NJDCR
WRITE (KLUN) SELF%NJDCR1
WRITE (KLUN) SELF%NDIFC_COMPO
WRITE (KLUN) SELF%NJDCR_COMPO
WRITE (KLUN) SELF%NJDCR1_COMPO
WRITE (KLUN) SELF%NP1
WRITE (KLUN) SELF%NP2
WRITE (KLUN) SELF%NPCO2_1
WRITE (KLUN) SELF%NPCO2_2
WRITE (KLUN) SELF%NPAER_1
WRITE (KLUN) SELF%NPAER_2
WRITE (KLUN) SELF%NPCOMPO_1
WRITE (KLUN) SELF%NPCOMPO_2
WRITE (KLUN) SELF%NUNITC
WRITE (KLUN) SELF%NUNITC1
WRITE (KLUN) SELF%NUNITCM
WRITE (KLUN) SELF%NOACOMM
WRITE (KLUN) SELF%NSSTICEOP
LCLIMRCO2 = ALLOCATED (SELF%CLIMRCO2)
WRITE (KLUN) LCLIMRCO2
IF (LCLIMRCO2) THEN
  WRITE (KLUN) LBOUND (SELF%CLIMRCO2)
  WRITE (KLUN) UBOUND (SELF%CLIMRCO2)
  WRITE (KLUN) SELF%CLIMRCO2
ENDIF
LCLIMRAER = ALLOCATED (SELF%CLIMRAER)
WRITE (KLUN) LCLIMRAER
IF (LCLIMRAER) THEN
  WRITE (KLUN) LBOUND (SELF%CLIMRAER)
  WRITE (KLUN) UBOUND (SELF%CLIMRAER)
  WRITE (KLUN) SELF%CLIMRAER
ENDIF
LCLIMRCOMPO = ALLOCATED (SELF%CLIMRCOMPO)
WRITE (KLUN) LCLIMRCOMPO
IF (LCLIMRCOMPO) THEN
  WRITE (KLUN) LBOUND (SELF%CLIMRCOMPO)
  WRITE (KLUN) UBOUND (SELF%CLIMRCOMPO)
  WRITE (KLUN) SELF%CLIMRCOMPO
ENDIF
LZLAKE = ALLOCATED (SELF%ZLAKE)
WRITE (KLUN) LZLAKE
IF (LZLAKE) THEN
  WRITE (KLUN) LBOUND (SELF%ZLAKE)
  WRITE (KLUN) UBOUND (SELF%ZLAKE)
  WRITE (KLUN) SELF%ZLAKE
ENDIF
LOCEANBC = ALLOCATED (SELF%OCEANBC)
WRITE (KLUN) LOCEANBC
IF (LOCEANBC) THEN
  WRITE (KLUN) LBOUND (SELF%OCEANBC)
  WRITE (KLUN) UBOUND (SELF%OCEANBC)
  WRITE (KLUN) SELF%OCEANBC
ENDIF
LCLIMR = ALLOCATED (SELF%CLIMR)
WRITE (KLUN) LCLIMR
IF (LCLIMR) THEN
  WRITE (KLUN) LBOUND (SELF%CLIMR)
  WRITE (KLUN) UBOUND (SELF%CLIMR)
  WRITE (KLUN) SELF%CLIMR
ENDIF
WRITE (KLUN) SELF%LFIRSTUPD
WRITE (KLUN) SELF%LCURR
WRITE (KLUN) SELF%LGELATO
WRITE (KLUN) SELF%LMCC01_MSE
WRITE (KLUN) SELF%LMCC01
WRITE (KLUN) SELF%LMCC02
WRITE (KLUN) SELF%LMCC03
WRITE (KLUN) SELF%LMCC04
WRITE (KLUN) SELF%LMCC05
WRITE (KLUN) SELF%LMCC06
WRITE (KLUN) SELF%LMCCEC
WRITE (KLUN) SELF%LMCCIEC
WRITE (KLUN) SELF%LMCCIEC_COMPO
WRITE (KLUN) SELF%LMCCICEIC
WRITE (KLUN) SELF%LMCCDYNSEAICE
WRITE (KLUN) SELF%LNEMOCOUP
WRITE (KLUN) SELF%LNEMOFLUXNC
WRITE (KLUN) SELF%LNEMOOUTGRB
WRITE (KLUN) SELF%LCOUPINFOUT
WRITE (KLUN) SELF%LNEMO1WAY
WRITE (KLUN) SELF%LNEMOIFSLOG
WRITE (KLUN) SELF%LNEMOSSTFREEZ
WRITE (KLUN) SELF%LNEMOGRIBFLDS
WRITE (KLUN) SELF%LNEMOGRIBMASK
WRITE (KLUN) SELF%L2DECV2NEMO
WRITE (KLUN) SELF%LMULTIYR
WRITE (KLUN) SELF%LMCC_COMPO
WRITE (KLUN) SELF%NFRCPL
WRITE (KLUN) SELF%LNEMOLIMGET
WRITE (KLUN) SELF%LNEMOLIMPUT
WRITE (KLUN) SELF%LNEMOLIMALB
WRITE (KLUN) SELF%LNEMOLIMTEMP
WRITE (KLUN) SELF%LNEMOLIMTLVL
WRITE (KLUN) SELF%LNEMOLIMTHK
WRITE (KLUN) SELF%LNEMOSICOUP
WRITE (KLUN) SELF%LNEMOATMFLDS
WRITE (KLUN) SELF%LNEMOOCEICEMIX
WRITE (KLUN) SELF%LNEMOQNSICEFILT
WRITE (KLUN) SELF%LNEMOACCUMFLUX
WRITE (KLUN) SELF%LNEMOGRIB3D
WRITE (KLUN) SELF%NNEMO3DLEVS
LRNEMOLVLS = ALLOCATED (SELF%RNEMOLVLS)
WRITE (KLUN) LRNEMOLVLS
IF (LRNEMOLVLS) THEN
  WRITE (KLUN) LBOUND (SELF%RNEMOLVLS)
  WRITE (KLUN) UBOUND (SELF%RNEMOLVLS)
  WRITE (KLUN) SELF%RNEMOLVLS
ENDIF
LRNEMOMASK = ALLOCATED (SELF%RNEMOMASK)
WRITE (KLUN) LRNEMOMASK
IF (LRNEMOMASK) THEN
  WRITE (KLUN) LBOUND (SELF%RNEMOMASK)
  WRITE (KLUN) UBOUND (SELF%RNEMOMASK)
  WRITE (KLUN) SELF%RNEMOMASK
ENDIF
WRITE (KLUN) SELF%LNEMOPARTCOUP
WRITE (KLUN) SELF%LNEMOPARTMASK
WRITE (KLUN) SELF%LNEMOPARTMASKFILE
WRITE (KLUN) SELF%RNPARTRAMPSTART
WRITE (KLUN) SELF%RNPARTRAMPLEN
WRITE (KLUN) SELF%RNPARTLAT
WRITE (KLUN) SELF%RNPARTLATSPREAD
LPARTSST0 = ALLOCATED (SELF%PARTSST0)
WRITE (KLUN) LPARTSST0
IF (LPARTSST0) THEN
  WRITE (KLUN) LBOUND (SELF%PARTSST0)
  WRITE (KLUN) UBOUND (SELF%PARTSST0)
  WRITE (KLUN) SELF%PARTSST0
ENDIF
LPARTMASK = ALLOCATED (SELF%PARTMASK)
WRITE (KLUN) LPARTMASK
IF (LPARTMASK) THEN
  WRITE (KLUN) LBOUND (SELF%PARTMASK)
  WRITE (KLUN) UBOUND (SELF%PARTMASK)
  WRITE (KLUN) SELF%PARTMASK
ENDIF
WRITE (KLUN) SELF%CDNPARTMASKFILE
LCPLNG_FLD = ALLOCATED (SELF%CPLNG_FLD)
WRITE (KLUN) LCPLNG_FLD
IF (LCPLNG_FLD) THEN
  WRITE (KLUN) LBOUND (SELF%CPLNG_FLD)
  WRITE (KLUN) UBOUND (SELF%CPLNG_FLD)
  DO J1 = LBOUND (SELF%CPLNG_FLD, 1), UBOUND (SELF%CPLNG_FLD, 1)
    CALL ACDC_SAVE_CPLNG_FLD_TYPE (SELF%CPLNG_FLD (J1), KLUN)
  ENDDO
ENDIF
WRITE (KLUN) SELF%CPLNG_ACTIVE
WRITE (KLUN) SELF%CPLNG_NUM_FIELDS
WRITE (KLUN) SELF%IP_A_SST
WRITE (KLUN) SELF%IP_A_ICE_FRAC
WRITE (KLUN) SELF%IP_A_CURR_U
WRITE (KLUN) SELF%IP_A_CURR_V
WRITE (KLUN) SELF%IP_A_TAUX_OCE
WRITE (KLUN) SELF%IP_A_TAUY_OCE
WRITE (KLUN) SELF%IP_A_TAUX_ICE
WRITE (KLUN) SELF%IP_A_TAUY_ICE
WRITE (KLUN) SELF%IP_A_QS_MIX
WRITE (KLUN) SELF%IP_A_QNS_MIX
WRITE (KLUN) SELF%IP_A_QS_OCE
WRITE (KLUN) SELF%IP_A_QNS_OCE
WRITE (KLUN) SELF%IP_A_QS_ICE
WRITE (KLUN) SELF%IP_A_QNS_ICE
WRITE (KLUN) SELF%IP_A_PRECIP_LIQUID
WRITE (KLUN) SELF%IP_A_PRECIP_SOLID
WRITE (KLUN) SELF%IP_A_EVAP_TOTAL
WRITE (KLUN) SELF%IP_A_EVAP_ICE
WRITE (KLUN) SELF%IP_A_DQNS_DT
WRITE (KLUN) SELF%IP_A_RUNOFF
WRITE (KLUN) SELF%IP_A_TOTAL_CC
WRITE (KLUN) SELF%IP_A_LOW_CC
WRITE (KLUN) SELF%IP_A_ICE_TEMP
WRITE (KLUN) SELF%IP_A_ICE_ALBEDO
WRITE (KLUN) SELF%IP_A_ICE_THICKNESS
WRITE (KLUN) SELF%IP_A_SNOW_THICKNESS
WRITE (KLUN) SELF%IP_A_ICE_TEMP_LVLS
WRITE (KLUN) SELF%IP_A_TAUX
WRITE (KLUN) SELF%IP_A_TAUY
WRITE (KLUN) SELF%IP_A_QS
WRITE (KLUN) SELF%IP_A_QNS
WRITE (KLUN) SELF%IP_A_WATER
WRITE (KLUN) SELF%IP_A_SST_ATM
WRITE (KLUN) SELF%IP_A_TSK_ATM
WRITE (KLUN) SELF%IP_A_IST_ATM
WRITE (KLUN) SELF%IP_A_2DECV_SKT
WRITE (KLUN) SELF%LCOUPSIM
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TMCC (SELF, KLUN)
USE UTIL_CPLNG_FLD_TYPE_MOD
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TMCC), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: J1
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) SELF%N923
READ (KLUN) SELF%NCLIMTOT
READ (KLUN) SELF%NCLIMR
READ (KLUN) SELF%NCLIGC
READ (KLUN) SELF%NCLIGC_COMPO
READ (KLUN) SELF%NYSDMP_COMPO
READ (KLUN) SELF%NCLIMR_COMPO
READ (KLUN) SELF%NCLIAER
READ (KLUN) SELF%NDIFC
READ (KLUN) SELF%NJDCR
READ (KLUN) SELF%NJDCR1
READ (KLUN) SELF%NDIFC_COMPO
READ (KLUN) SELF%NJDCR_COMPO
READ (KLUN) SELF%NJDCR1_COMPO
READ (KLUN) SELF%NP1
READ (KLUN) SELF%NP2
READ (KLUN) SELF%NPCO2_1
READ (KLUN) SELF%NPCO2_2
READ (KLUN) SELF%NPAER_1
READ (KLUN) SELF%NPAER_2
READ (KLUN) SELF%NPCOMPO_1
READ (KLUN) SELF%NPCOMPO_2
READ (KLUN) SELF%NUNITC
READ (KLUN) SELF%NUNITC1
READ (KLUN) SELF%NUNITCM
READ (KLUN) SELF%NOACOMM
READ (KLUN) SELF%NSSTICEOP
READ (KLUN) LCLIMRCO2
IF (LCLIMRCO2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%CLIMRCO2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%CLIMRCO2,1):UBOUND(SELF%CLIMRCO2,1), LBOUND(SELF%CLIMRCO2,2):UBOUND(SELF%CLIMRCO2,2), LBOUND(SELF%CLIMRCO2,3):UBOUND(SELF%CLIMRCO2,3)))
  READ (KLUN) ZTMP3
  SELF%CLIMRCO2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LCLIMRAER
IF (LCLIMRAER) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%CLIMRAER (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%CLIMRAER,1):UBOUND(SELF%CLIMRAER,1), LBOUND(SELF%CLIMRAER,2):UBOUND(SELF%CLIMRAER,2), LBOUND(SELF%CLIMRAER,3):UBOUND(SELF%CLIMRAER,3)))
  READ (KLUN) ZTMP3
  SELF%CLIMRAER = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LCLIMRCOMPO
IF (LCLIMRCOMPO) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%CLIMRCOMPO (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%CLIMRCOMPO,1):UBOUND(SELF%CLIMRCOMPO,1), LBOUND(SELF%CLIMRCOMPO,2):UBOUND(SELF%CLIMRCOMPO,2), LBOUND(SELF%CLIMRCOMPO,3):UBOUND(SELF%CLIMRCOMPO,3)))
  READ (KLUN) ZTMP3
  SELF%CLIMRCOMPO = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LZLAKE
IF (LZLAKE) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%ZLAKE (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%ZLAKE,1):UBOUND(SELF%ZLAKE,1), LBOUND(SELF%ZLAKE,2):UBOUND(SELF%ZLAKE,2), LBOUND(SELF%ZLAKE,3):UBOUND(SELF%ZLAKE,3)))
  READ (KLUN) ZTMP3
  SELF%ZLAKE = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LOCEANBC
IF (LOCEANBC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%OCEANBC (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%OCEANBC,1):UBOUND(SELF%OCEANBC,1), LBOUND(SELF%OCEANBC,2):UBOUND(SELF%OCEANBC,2)))
  READ (KLUN) ZTMP2
  SELF%OCEANBC = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LCLIMR
IF (LCLIMR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%CLIMR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%CLIMR
ENDIF
READ (KLUN) SELF%LFIRSTUPD
READ (KLUN) SELF%LCURR
READ (KLUN) SELF%LGELATO
READ (KLUN) SELF%LMCC01_MSE
READ (KLUN) SELF%LMCC01
READ (KLUN) SELF%LMCC02
READ (KLUN) SELF%LMCC03
READ (KLUN) SELF%LMCC04
READ (KLUN) SELF%LMCC05
READ (KLUN) SELF%LMCC06
READ (KLUN) SELF%LMCCEC
READ (KLUN) SELF%LMCCIEC
READ (KLUN) SELF%LMCCIEC_COMPO
READ (KLUN) SELF%LMCCICEIC
READ (KLUN) SELF%LMCCDYNSEAICE
READ (KLUN) SELF%LNEMOCOUP
READ (KLUN) SELF%LNEMOFLUXNC
READ (KLUN) SELF%LNEMOOUTGRB
READ (KLUN) SELF%LCOUPINFOUT
READ (KLUN) SELF%LNEMO1WAY
READ (KLUN) SELF%LNEMOIFSLOG
READ (KLUN) SELF%LNEMOSSTFREEZ
READ (KLUN) SELF%LNEMOGRIBFLDS
READ (KLUN) SELF%LNEMOGRIBMASK
READ (KLUN) SELF%L2DECV2NEMO
READ (KLUN) SELF%LMULTIYR
READ (KLUN) SELF%LMCC_COMPO
READ (KLUN) SELF%NFRCPL
READ (KLUN) SELF%LNEMOLIMGET
READ (KLUN) SELF%LNEMOLIMPUT
READ (KLUN) SELF%LNEMOLIMALB
READ (KLUN) SELF%LNEMOLIMTEMP
READ (KLUN) SELF%LNEMOLIMTLVL
READ (KLUN) SELF%LNEMOLIMTHK
READ (KLUN) SELF%LNEMOSICOUP
READ (KLUN) SELF%LNEMOATMFLDS
READ (KLUN) SELF%LNEMOOCEICEMIX
READ (KLUN) SELF%LNEMOQNSICEFILT
READ (KLUN) SELF%LNEMOACCUMFLUX
READ (KLUN) SELF%LNEMOGRIB3D
READ (KLUN) SELF%NNEMO3DLEVS
READ (KLUN) LRNEMOLVLS
IF (LRNEMOLVLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RNEMOLVLS (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RNEMOLVLS,1):UBOUND(SELF%RNEMOLVLS,1)))
  READ (KLUN) ZTMP1
  SELF%RNEMOLVLS = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRNEMOMASK
IF (LRNEMOMASK) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RNEMOMASK (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%RNEMOMASK
ENDIF
READ (KLUN) SELF%LNEMOPARTCOUP
READ (KLUN) SELF%LNEMOPARTMASK
READ (KLUN) SELF%LNEMOPARTMASKFILE
READ (KLUN) ZTMP0
SELF%RNPARTRAMPSTART = ZTMP0
READ (KLUN) ZTMP0
SELF%RNPARTRAMPLEN = ZTMP0
READ (KLUN) ZTMP0
SELF%RNPARTLAT = ZTMP0
READ (KLUN) ZTMP0
SELF%RNPARTLATSPREAD = ZTMP0
READ (KLUN) LPARTSST0
IF (LPARTSST0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%PARTSST0 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%PARTSST0,1):UBOUND(SELF%PARTSST0,1)))
  READ (KLUN) ZTMP1
  SELF%PARTSST0 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LPARTMASK
IF (LPARTMASK) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%PARTMASK (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%PARTMASK,1):UBOUND(SELF%PARTMASK,1)))
  READ (KLUN) ZTMP1
  SELF%PARTMASK = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) SELF%CDNPARTMASKFILE
READ (KLUN) LCPLNG_FLD
IF (LCPLNG_FLD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%CPLNG_FLD (IL1(1):IU1(1)))
  DO J1 = LBOUND (SELF%CPLNG_FLD, 1), UBOUND (SELF%CPLNG_FLD, 1)
    CALL ACDC_LOAD_CPLNG_FLD_TYPE (SELF%CPLNG_FLD (J1), KLUN)
  ENDDO
ENDIF
READ (KLUN) SELF%CPLNG_ACTIVE
READ (KLUN) SELF%CPLNG_NUM_FIELDS
READ (KLUN) SELF%IP_A_SST
READ (KLUN) SELF%IP_A_ICE_FRAC
READ (KLUN) SELF%IP_A_CURR_U
READ (KLUN) SELF%IP_A_CURR_V
READ (KLUN) SELF%IP_A_TAUX_OCE
READ (KLUN) SELF%IP_A_TAUY_OCE
READ (KLUN) SELF%IP_A_TAUX_ICE
READ (KLUN) SELF%IP_A_TAUY_ICE
READ (KLUN) SELF%IP_A_QS_MIX
READ (KLUN) SELF%IP_A_QNS_MIX
READ (KLUN) SELF%IP_A_QS_OCE
READ (KLUN) SELF%IP_A_QNS_OCE
READ (KLUN) SELF%IP_A_QS_ICE
READ (KLUN) SELF%IP_A_QNS_ICE
READ (KLUN) SELF%IP_A_PRECIP_LIQUID
READ (KLUN) SELF%IP_A_PRECIP_SOLID
READ (KLUN) SELF%IP_A_EVAP_TOTAL
READ (KLUN) SELF%IP_A_EVAP_ICE
READ (KLUN) SELF%IP_A_DQNS_DT
READ (KLUN) SELF%IP_A_RUNOFF
READ (KLUN) SELF%IP_A_TOTAL_CC
READ (KLUN) SELF%IP_A_LOW_CC
READ (KLUN) SELF%IP_A_ICE_TEMP
READ (KLUN) SELF%IP_A_ICE_ALBEDO
READ (KLUN) SELF%IP_A_ICE_THICKNESS
READ (KLUN) SELF%IP_A_SNOW_THICKNESS
READ (KLUN) SELF%IP_A_ICE_TEMP_LVLS
READ (KLUN) SELF%IP_A_TAUX
READ (KLUN) SELF%IP_A_TAUY
READ (KLUN) SELF%IP_A_QS
READ (KLUN) SELF%IP_A_QNS
READ (KLUN) SELF%IP_A_WATER
READ (KLUN) SELF%IP_A_SST_ATM
READ (KLUN) SELF%IP_A_TSK_ATM
READ (KLUN) SELF%IP_A_IST_ATM
READ (KLUN) SELF%IP_A_2DECV_SKT
READ (KLUN) SELF%LCOUPSIM
END SUBROUTINE

SUBROUTINE ACDC_COPY_TMCC (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_CPLNG_FLD_TYPE_MOD
IMPLICIT NONE
TYPE (TMCC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LCLIMRCO2 = ALLOCATED (SELF%CLIMRCO2)
IF (LCLIMRCO2) THEN
  !$ACC ENTER DATA CREATE (SELF%CLIMRCO2)
  !$ACC UPDATE DEVICE (SELF%CLIMRCO2)
  !$ACC ENTER DATA ATTACH (SELF%CLIMRCO2)
ENDIF

LCLIMRAER = ALLOCATED (SELF%CLIMRAER)
IF (LCLIMRAER) THEN
  !$ACC ENTER DATA CREATE (SELF%CLIMRAER)
  !$ACC UPDATE DEVICE (SELF%CLIMRAER)
  !$ACC ENTER DATA ATTACH (SELF%CLIMRAER)
ENDIF

LCLIMRCOMPO = ALLOCATED (SELF%CLIMRCOMPO)
IF (LCLIMRCOMPO) THEN
  !$ACC ENTER DATA CREATE (SELF%CLIMRCOMPO)
  !$ACC UPDATE DEVICE (SELF%CLIMRCOMPO)
  !$ACC ENTER DATA ATTACH (SELF%CLIMRCOMPO)
ENDIF

LZLAKE = ALLOCATED (SELF%ZLAKE)
IF (LZLAKE) THEN
  !$ACC ENTER DATA CREATE (SELF%ZLAKE)
  !$ACC UPDATE DEVICE (SELF%ZLAKE)
  !$ACC ENTER DATA ATTACH (SELF%ZLAKE)
ENDIF

LOCEANBC = ALLOCATED (SELF%OCEANBC)
IF (LOCEANBC) THEN
  !$ACC ENTER DATA CREATE (SELF%OCEANBC)
  !$ACC UPDATE DEVICE (SELF%OCEANBC)
  !$ACC ENTER DATA ATTACH (SELF%OCEANBC)
ENDIF

LCLIMR = ALLOCATED (SELF%CLIMR)
IF (LCLIMR) THEN
  !$ACC ENTER DATA CREATE (SELF%CLIMR)
  !$ACC UPDATE DEVICE (SELF%CLIMR)
  !$ACC ENTER DATA ATTACH (SELF%CLIMR)
ENDIF

LRNEMOLVLS = ALLOCATED (SELF%RNEMOLVLS)
IF (LRNEMOLVLS) THEN
  !$ACC ENTER DATA CREATE (SELF%RNEMOLVLS)
  !$ACC UPDATE DEVICE (SELF%RNEMOLVLS)
  !$ACC ENTER DATA ATTACH (SELF%RNEMOLVLS)
ENDIF

LRNEMOMASK = ALLOCATED (SELF%RNEMOMASK)
IF (LRNEMOMASK) THEN
  !$ACC ENTER DATA CREATE (SELF%RNEMOMASK)
  !$ACC UPDATE DEVICE (SELF%RNEMOMASK)
  !$ACC ENTER DATA ATTACH (SELF%RNEMOMASK)
ENDIF

LPARTSST0 = ALLOCATED (SELF%PARTSST0)
IF (LPARTSST0) THEN
  !$ACC ENTER DATA CREATE (SELF%PARTSST0)
  !$ACC UPDATE DEVICE (SELF%PARTSST0)
  !$ACC ENTER DATA ATTACH (SELF%PARTSST0)
ENDIF

LPARTMASK = ALLOCATED (SELF%PARTMASK)
IF (LPARTMASK) THEN
  !$ACC ENTER DATA CREATE (SELF%PARTMASK)
  !$ACC UPDATE DEVICE (SELF%PARTMASK)
  !$ACC ENTER DATA ATTACH (SELF%PARTMASK)
ENDIF

LCPLNG_FLD = ALLOCATED (SELF%CPLNG_FLD)
IF (LCPLNG_FLD) THEN
  !$ACC ENTER DATA CREATE (SELF%CPLNG_FLD)
  !$ACC UPDATE DEVICE (SELF%CPLNG_FLD)
  DO J1 = LBOUND (SELF%CPLNG_FLD, 1), UBOUND (SELF%CPLNG_FLD, 1)
    CALL ACDC_COPY_CPLNG_FLD_TYPE (SELF%CPLNG_FLD (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%CPLNG_FLD)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TMCC (SELF)
USE UTIL_CPLNG_FLD_TYPE_MOD
IMPLICIT NONE
TYPE (TMCC), TARGET :: SELF
INTEGER :: J1
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE

LCPLNG_FLD = ALLOCATED (SELF%CPLNG_FLD)
IF (LCPLNG_FLD) THEN
  DO J1 = LBOUND (SELF%CPLNG_FLD, 1), UBOUND (SELF%CPLNG_FLD, 1)
    CALL ACDC_HOST_CPLNG_FLD_TYPE (SELF%CPLNG_FLD (J1))
  ENDDO
ENDIF

END SUBROUTINE



SUBROUTINE ACDC_CRC64_TMCC (SELF, KLUN, CDPATH)
USE UTIL_CPLNG_FLD_TYPE_MOD
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TMCC), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
INTEGER :: J1
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%N923), CDPATH//'%N923'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIMTOT), CDPATH//'%NCLIMTOT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIMR), CDPATH//'%NCLIMR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIGC), CDPATH//'%NCLIGC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIGC_COMPO), CDPATH//'%NCLIGC_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NYSDMP_COMPO), CDPATH//'%NYSDMP_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIMR_COMPO), CDPATH//'%NCLIMR_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIAER), CDPATH//'%NCLIAER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDIFC), CDPATH//'%NDIFC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJDCR), CDPATH//'%NJDCR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJDCR1), CDPATH//'%NJDCR1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDIFC_COMPO), CDPATH//'%NDIFC_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJDCR_COMPO), CDPATH//'%NJDCR_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJDCR1_COMPO), CDPATH//'%NJDCR1_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NP1), CDPATH//'%NP1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NP2), CDPATH//'%NP2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPCO2_1), CDPATH//'%NPCO2_1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPCO2_2), CDPATH//'%NPCO2_2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPAER_1), CDPATH//'%NPAER_1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPAER_2), CDPATH//'%NPAER_2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPCOMPO_1), CDPATH//'%NPCOMPO_1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPCOMPO_2), CDPATH//'%NPCOMPO_2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUNITC), CDPATH//'%NUNITC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUNITC1), CDPATH//'%NUNITC1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUNITCM), CDPATH//'%NUNITCM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NOACOMM), CDPATH//'%NOACOMM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSSTICEOP), CDPATH//'%NSSTICEOP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CLIMRCO2), CDPATH//'%CLIMRCO2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CLIMRAER), CDPATH//'%CLIMRAER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CLIMRCOMPO), CDPATH//'%CLIMRCOMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ZLAKE), CDPATH//'%ZLAKE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%OCEANBC), CDPATH//'%OCEANBC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CLIMR), CDPATH//'%CLIMR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LFIRSTUPD), CDPATH//'%LFIRSTUPD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCURR), CDPATH//'%LCURR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LGELATO), CDPATH//'%LGELATO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC01_MSE), CDPATH//'%LMCC01_MSE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC01), CDPATH//'%LMCC01'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC02), CDPATH//'%LMCC02'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC03), CDPATH//'%LMCC03'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC04), CDPATH//'%LMCC04'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC05), CDPATH//'%LMCC05'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC06), CDPATH//'%LMCC06'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCEC), CDPATH//'%LMCCEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCIEC), CDPATH//'%LMCCIEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCIEC_COMPO), CDPATH//'%LMCCIEC_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCICEIC), CDPATH//'%LMCCICEIC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCDYNSEAICE), CDPATH//'%LMCCDYNSEAICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOCOUP), CDPATH//'%LNEMOCOUP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOFLUXNC), CDPATH//'%LNEMOFLUXNC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOOUTGRB), CDPATH//'%LNEMOOUTGRB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCOUPINFOUT), CDPATH//'%LCOUPINFOUT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMO1WAY), CDPATH//'%LNEMO1WAY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOIFSLOG), CDPATH//'%LNEMOIFSLOG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOSSTFREEZ), CDPATH//'%LNEMOSSTFREEZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOGRIBFLDS), CDPATH//'%LNEMOGRIBFLDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOGRIBMASK), CDPATH//'%LNEMOGRIBMASK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%L2DECV2NEMO), CDPATH//'%L2DECV2NEMO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMULTIYR), CDPATH//'%LMULTIYR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC_COMPO), CDPATH//'%LMCC_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFRCPL), CDPATH//'%NFRCPL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMGET), CDPATH//'%LNEMOLIMGET'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMPUT), CDPATH//'%LNEMOLIMPUT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMALB), CDPATH//'%LNEMOLIMALB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMTEMP), CDPATH//'%LNEMOLIMTEMP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMTLVL), CDPATH//'%LNEMOLIMTLVL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMTHK), CDPATH//'%LNEMOLIMTHK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOSICOUP), CDPATH//'%LNEMOSICOUP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOATMFLDS), CDPATH//'%LNEMOATMFLDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOOCEICEMIX), CDPATH//'%LNEMOOCEICEMIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOQNSICEFILT), CDPATH//'%LNEMOQNSICEFILT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOACCUMFLUX), CDPATH//'%LNEMOACCUMFLUX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOGRIB3D), CDPATH//'%LNEMOGRIB3D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NNEMO3DLEVS), CDPATH//'%NNEMO3DLEVS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNEMOLVLS), CDPATH//'%RNEMOLVLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNEMOMASK), CDPATH//'%RNEMOMASK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOPARTCOUP), CDPATH//'%LNEMOPARTCOUP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOPARTMASK), CDPATH//'%LNEMOPARTMASK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOPARTMASKFILE), CDPATH//'%LNEMOPARTMASKFILE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNPARTRAMPSTART), CDPATH//'%RNPARTRAMPSTART'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNPARTRAMPLEN), CDPATH//'%RNPARTRAMPLEN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNPARTLAT), CDPATH//'%RNPARTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNPARTLATSPREAD), CDPATH//'%RNPARTLATSPREAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PARTSST0), CDPATH//'%PARTSST0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PARTMASK), CDPATH//'%PARTMASK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CDNPARTMASKFILE), CDPATH//'%CDNPARTMASKFILE'

LCPLNG_FLD = ALLOCATED (SELF%CPLNG_FLD)
IF (LCPLNG_FLD) THEN
  DO J1 = LBOUND (SELF%CPLNG_FLD, 1), UBOUND (SELF%CPLNG_FLD, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL ACDC_CRC64_CPLNG_FLD_TYPE (SELF%CPLNG_FLD (J1), KLUN, CDPATH//'%CPLNG_FLD'//TRIM(CLIND))
  ENDDO
ENDIF

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CPLNG_ACTIVE), CDPATH//'%CPLNG_ACTIVE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CPLNG_NUM_FIELDS), CDPATH//'%CPLNG_NUM_FIELDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_SST), CDPATH//'%IP_A_SST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_FRAC), CDPATH//'%IP_A_ICE_FRAC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_CURR_U), CDPATH//'%IP_A_CURR_U'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_CURR_V), CDPATH//'%IP_A_CURR_V'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUX_OCE), CDPATH//'%IP_A_TAUX_OCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUY_OCE), CDPATH//'%IP_A_TAUY_OCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUX_ICE), CDPATH//'%IP_A_TAUX_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUY_ICE), CDPATH//'%IP_A_TAUY_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QS_MIX), CDPATH//'%IP_A_QS_MIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QNS_MIX), CDPATH//'%IP_A_QNS_MIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QS_OCE), CDPATH//'%IP_A_QS_OCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QNS_OCE), CDPATH//'%IP_A_QNS_OCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QS_ICE), CDPATH//'%IP_A_QS_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QNS_ICE), CDPATH//'%IP_A_QNS_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_PRECIP_LIQUID), CDPATH//'%IP_A_PRECIP_LIQUID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_PRECIP_SOLID), CDPATH//'%IP_A_PRECIP_SOLID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_EVAP_TOTAL), CDPATH//'%IP_A_EVAP_TOTAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_EVAP_ICE), CDPATH//'%IP_A_EVAP_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_DQNS_DT), CDPATH//'%IP_A_DQNS_DT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_RUNOFF), CDPATH//'%IP_A_RUNOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TOTAL_CC), CDPATH//'%IP_A_TOTAL_CC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_LOW_CC), CDPATH//'%IP_A_LOW_CC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_TEMP), CDPATH//'%IP_A_ICE_TEMP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_ALBEDO), CDPATH//'%IP_A_ICE_ALBEDO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_THICKNESS), CDPATH//'%IP_A_ICE_THICKNESS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_SNOW_THICKNESS), CDPATH//'%IP_A_SNOW_THICKNESS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_TEMP_LVLS), CDPATH//'%IP_A_ICE_TEMP_LVLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUX), CDPATH//'%IP_A_TAUX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUY), CDPATH//'%IP_A_TAUY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QS), CDPATH//'%IP_A_QS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QNS), CDPATH//'%IP_A_QNS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_WATER), CDPATH//'%IP_A_WATER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_SST_ATM), CDPATH//'%IP_A_SST_ATM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TSK_ATM), CDPATH//'%IP_A_TSK_ATM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_IST_ATM), CDPATH//'%IP_A_IST_ATM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_2DECV_SKT), CDPATH//'%IP_A_2DECV_SKT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCOUPSIM), CDPATH//'%LCOUPSIM'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TMCC (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_CPLNG_FLD_TYPE_MOD
IMPLICIT NONE
TYPE (TMCC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LCLIMRCO2 = ALLOCATED (SELF%CLIMRCO2)
IF (LCLIMRCO2) THEN
  !$ACC EXIT DATA DETACH (SELF%CLIMRCO2)
  !$ACC EXIT DATA DELETE (SELF%CLIMRCO2)
ENDIF

LCLIMRAER = ALLOCATED (SELF%CLIMRAER)
IF (LCLIMRAER) THEN
  !$ACC EXIT DATA DETACH (SELF%CLIMRAER)
  !$ACC EXIT DATA DELETE (SELF%CLIMRAER)
ENDIF

LCLIMRCOMPO = ALLOCATED (SELF%CLIMRCOMPO)
IF (LCLIMRCOMPO) THEN
  !$ACC EXIT DATA DETACH (SELF%CLIMRCOMPO)
  !$ACC EXIT DATA DELETE (SELF%CLIMRCOMPO)
ENDIF

LZLAKE = ALLOCATED (SELF%ZLAKE)
IF (LZLAKE) THEN
  !$ACC EXIT DATA DETACH (SELF%ZLAKE)
  !$ACC EXIT DATA DELETE (SELF%ZLAKE)
ENDIF

LOCEANBC = ALLOCATED (SELF%OCEANBC)
IF (LOCEANBC) THEN
  !$ACC EXIT DATA DETACH (SELF%OCEANBC)
  !$ACC EXIT DATA DELETE (SELF%OCEANBC)
ENDIF

LCLIMR = ALLOCATED (SELF%CLIMR)
IF (LCLIMR) THEN
  !$ACC EXIT DATA DETACH (SELF%CLIMR)
  !$ACC EXIT DATA DELETE (SELF%CLIMR)
ENDIF

LRNEMOLVLS = ALLOCATED (SELF%RNEMOLVLS)
IF (LRNEMOLVLS) THEN
  !$ACC EXIT DATA DETACH (SELF%RNEMOLVLS)
  !$ACC EXIT DATA DELETE (SELF%RNEMOLVLS)
ENDIF

LRNEMOMASK = ALLOCATED (SELF%RNEMOMASK)
IF (LRNEMOMASK) THEN
  !$ACC EXIT DATA DETACH (SELF%RNEMOMASK)
  !$ACC EXIT DATA DELETE (SELF%RNEMOMASK)
ENDIF

LPARTSST0 = ALLOCATED (SELF%PARTSST0)
IF (LPARTSST0) THEN
  !$ACC EXIT DATA DETACH (SELF%PARTSST0)
  !$ACC EXIT DATA DELETE (SELF%PARTSST0)
ENDIF

LPARTMASK = ALLOCATED (SELF%PARTMASK)
IF (LPARTMASK) THEN
  !$ACC EXIT DATA DETACH (SELF%PARTMASK)
  !$ACC EXIT DATA DELETE (SELF%PARTMASK)
ENDIF

LCPLNG_FLD = ALLOCATED (SELF%CPLNG_FLD)
IF (LCPLNG_FLD) THEN
  !$ACC EXIT DATA DETACH (SELF%CPLNG_FLD)
  DO J1 = LBOUND (SELF%CPLNG_FLD, 1), UBOUND (SELF%CPLNG_FLD, 1)
    CALL ACDC_WIPE_CPLNG_FLD_TYPE (SELF%CPLNG_FLD (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DELETE (SELF%CPLNG_FLD)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TMCC (SELF, CDPATH, LDPRINT) RESULT (KSIZE)
USE UTIL_CPLNG_FLD_TYPE_MOD
IMPLICIT NONE
TYPE (TMCC),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
INTEGER :: J1
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%N923)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%N923'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NCLIMTOT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCLIMTOT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NCLIMR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCLIMR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NCLIGC) * SIZE (SELF%NCLIGC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCLIGC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NCLIGC_COMPO) * SIZE (SELF%NCLIGC_COMPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCLIGC_COMPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NYSDMP_COMPO) * SIZE (SELF%NYSDMP_COMPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NYSDMP_COMPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NCLIMR_COMPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCLIMR_COMPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NCLIAER) * SIZE (SELF%NCLIAER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCLIAER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDIFC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDIFC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NJDCR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NJDCR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NJDCR1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NJDCR1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDIFC_COMPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDIFC_COMPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NJDCR_COMPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NJDCR_COMPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NJDCR1_COMPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NJDCR1_COMPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NP1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NP1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NP2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NP2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NPCO2_1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPCO2_1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NPCO2_2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPCO2_2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NPAER_1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPAER_1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NPAER_2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPAER_2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NPCOMPO_1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPCOMPO_1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NPCOMPO_2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPCOMPO_2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NUNITC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NUNITC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NUNITC1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NUNITC1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NUNITCM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NUNITCM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NOACOMM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NOACOMM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSSTICEOP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSSTICEOP'
ENDIF
KSIZE = KSIZE + ISIZE
LCLIMRCO2 = ALLOCATED (SELF%CLIMRCO2)
IF (LCLIMRCO2) THEN
  ISIZE = KIND (SELF%CLIMRCO2) * SIZE (SELF%CLIMRCO2)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CLIMRCO2'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCLIMRAER = ALLOCATED (SELF%CLIMRAER)
IF (LCLIMRAER) THEN
  ISIZE = KIND (SELF%CLIMRAER) * SIZE (SELF%CLIMRAER)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CLIMRAER'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCLIMRCOMPO = ALLOCATED (SELF%CLIMRCOMPO)
IF (LCLIMRCOMPO) THEN
  ISIZE = KIND (SELF%CLIMRCOMPO) * SIZE (SELF%CLIMRCOMPO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CLIMRCOMPO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LZLAKE = ALLOCATED (SELF%ZLAKE)
IF (LZLAKE) THEN
  ISIZE = KIND (SELF%ZLAKE) * SIZE (SELF%ZLAKE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%ZLAKE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LOCEANBC = ALLOCATED (SELF%OCEANBC)
IF (LOCEANBC) THEN
  ISIZE = KIND (SELF%OCEANBC) * SIZE (SELF%OCEANBC)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%OCEANBC'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCLIMR = ALLOCATED (SELF%CLIMR)
IF (LCLIMR) THEN
  ISIZE = KIND (SELF%CLIMR) * SIZE (SELF%CLIMR)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CLIMR'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%LFIRSTUPD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LFIRSTUPD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCURR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCURR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LGELATO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGELATO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCC01_MSE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCC01_MSE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCC01)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCC01'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCC02)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCC02'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCC03)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCC03'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCC04)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCC04'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCC05)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCC05'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCC06)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCC06'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCCEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCCEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCCIEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCCIEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCCIEC_COMPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCCIEC_COMPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCCICEIC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCCICEIC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCCDYNSEAICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCCDYNSEAICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOCOUP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOCOUP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOFLUXNC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOFLUXNC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOOUTGRB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOOUTGRB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCOUPINFOUT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOUPINFOUT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMO1WAY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMO1WAY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOIFSLOG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOIFSLOG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOSSTFREEZ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOSSTFREEZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOGRIBFLDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOGRIBFLDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOGRIBMASK)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOGRIBMASK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%L2DECV2NEMO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%L2DECV2NEMO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMULTIYR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMULTIYR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LMCC_COMPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMCC_COMPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NFRCPL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFRCPL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOLIMGET)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOLIMGET'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOLIMPUT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOLIMPUT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOLIMALB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOLIMALB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOLIMTEMP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOLIMTEMP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOLIMTLVL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOLIMTLVL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOLIMTHK)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOLIMTHK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOSICOUP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOSICOUP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOATMFLDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOATMFLDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOOCEICEMIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOOCEICEMIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOQNSICEFILT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOQNSICEFILT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOACCUMFLUX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOACCUMFLUX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOGRIB3D)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOGRIB3D'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NNEMO3DLEVS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NNEMO3DLEVS'
ENDIF
KSIZE = KSIZE + ISIZE
LRNEMOLVLS = ALLOCATED (SELF%RNEMOLVLS)
IF (LRNEMOLVLS) THEN
  ISIZE = KIND (SELF%RNEMOLVLS) * SIZE (SELF%RNEMOLVLS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RNEMOLVLS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRNEMOMASK = ALLOCATED (SELF%RNEMOMASK)
IF (LRNEMOMASK) THEN
  ISIZE = KIND (SELF%RNEMOMASK) * SIZE (SELF%RNEMOMASK)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RNEMOMASK'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%LNEMOPARTCOUP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOPARTCOUP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOPARTMASK)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOPARTMASK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LNEMOPARTMASKFILE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEMOPARTMASKFILE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RNPARTRAMPSTART)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RNPARTRAMPSTART'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RNPARTRAMPLEN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RNPARTRAMPLEN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RNPARTLAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RNPARTLAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RNPARTLATSPREAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RNPARTLATSPREAD'
ENDIF
KSIZE = KSIZE + ISIZE
LPARTSST0 = ALLOCATED (SELF%PARTSST0)
IF (LPARTSST0) THEN
  ISIZE = KIND (SELF%PARTSST0) * SIZE (SELF%PARTSST0)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%PARTSST0'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LPARTMASK = ALLOCATED (SELF%PARTMASK)
IF (LPARTMASK) THEN
  ISIZE = KIND (SELF%PARTMASK) * SIZE (SELF%PARTMASK)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%PARTMASK'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%CDNPARTMASKFILE) * LEN (SELF%CDNPARTMASKFILE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CDNPARTMASKFILE'
ENDIF
KSIZE = KSIZE + ISIZE
LCPLNG_FLD = ALLOCATED (SELF%CPLNG_FLD)
IF (LCPLNG_FLD) THEN
  JSIZE = 0
  DO J1 = LBOUND (SELF%CPLNG_FLD, 1), UBOUND (SELF%CPLNG_FLD, 1)
    ISIZE = ACDC_SIZE_CPLNG_FLD_TYPE (SELF%CPLNG_FLD (J1), CLPATH//'%CPLNG_FLD', .FALSE.)
    JSIZE = JSIZE + ISIZE
    KSIZE = KSIZE + ISIZE
  ENDDO
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
    WRITE (*, *) TRIM (CLPATH)//'%CPLNG_FLD'
  ENDIF
ENDIF
ISIZE = KIND (SELF%CPLNG_ACTIVE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CPLNG_ACTIVE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%CPLNG_NUM_FIELDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CPLNG_NUM_FIELDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_SST)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_SST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_ICE_FRAC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_ICE_FRAC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_CURR_U)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_CURR_U'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_CURR_V)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_CURR_V'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_TAUX_OCE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_TAUX_OCE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_TAUY_OCE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_TAUY_OCE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_TAUX_ICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_TAUX_ICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_TAUY_ICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_TAUY_ICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_QS_MIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_QS_MIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_QNS_MIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_QNS_MIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_QS_OCE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_QS_OCE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_QNS_OCE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_QNS_OCE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_QS_ICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_QS_ICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_QNS_ICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_QNS_ICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_PRECIP_LIQUID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_PRECIP_LIQUID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_PRECIP_SOLID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_PRECIP_SOLID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_EVAP_TOTAL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_EVAP_TOTAL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_EVAP_ICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_EVAP_ICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_DQNS_DT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_DQNS_DT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_RUNOFF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_RUNOFF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_TOTAL_CC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_TOTAL_CC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_LOW_CC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_LOW_CC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_ICE_TEMP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_ICE_TEMP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_ICE_ALBEDO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_ICE_ALBEDO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_ICE_THICKNESS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_ICE_THICKNESS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_SNOW_THICKNESS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_SNOW_THICKNESS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_ICE_TEMP_LVLS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_ICE_TEMP_LVLS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_TAUX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_TAUX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_TAUY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_TAUY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_QS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_QS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_QNS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_QNS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_WATER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_WATER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_SST_ATM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_SST_ATM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_TSK_ATM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_TSK_ATM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_IST_ATM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_IST_ATM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%IP_A_2DECV_SKT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IP_A_2DECV_SKT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LCOUPSIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOUPSIM'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
