MODULE UTIL_TCSGEOM_MOD

USE YOMCSGEOM, ONLY : TCSGEOM

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TCSGEOM
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TCSGEOM
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TCSGEOM
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TCSGEOM
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TCSGEOM
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TCSGEOM
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TCSGEOM
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TCSGEOM (SELF, KLUN)

IMPLICIT NONE
TYPE (TCSGEOM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
LRCOLON = ASSOCIATED (SELF%RCOLON)
WRITE (KLUN) LRCOLON
IF (LRCOLON) THEN
  WRITE (KLUN) LBOUND (SELF%RCOLON)
  WRITE (KLUN) UBOUND (SELF%RCOLON)
  WRITE (KLUN) SELF%RCOLON
ENDIF
LRSILON = ASSOCIATED (SELF%RSILON)
WRITE (KLUN) LRSILON
IF (LRSILON) THEN
  WRITE (KLUN) LBOUND (SELF%RSILON)
  WRITE (KLUN) UBOUND (SELF%RSILON)
  WRITE (KLUN) SELF%RSILON
ENDIF
LRINDX = ASSOCIATED (SELF%RINDX)
WRITE (KLUN) LRINDX
IF (LRINDX) THEN
  WRITE (KLUN) LBOUND (SELF%RINDX)
  WRITE (KLUN) UBOUND (SELF%RINDX)
  WRITE (KLUN) SELF%RINDX
ENDIF
LRINDY = ASSOCIATED (SELF%RINDY)
WRITE (KLUN) LRINDY
IF (LRINDY) THEN
  WRITE (KLUN) LBOUND (SELF%RINDY)
  WRITE (KLUN) UBOUND (SELF%RINDY)
  WRITE (KLUN) SELF%RINDY
ENDIF
LRATATH = ASSOCIATED (SELF%RATATH)
WRITE (KLUN) LRATATH
IF (LRATATH) THEN
  WRITE (KLUN) LBOUND (SELF%RATATH)
  WRITE (KLUN) UBOUND (SELF%RATATH)
  WRITE (KLUN) SELF%RATATH
ENDIF
LRATATX = ASSOCIATED (SELF%RATATX)
WRITE (KLUN) LRATATX
IF (LRATATX) THEN
  WRITE (KLUN) LBOUND (SELF%RATATX)
  WRITE (KLUN) UBOUND (SELF%RATATX)
  WRITE (KLUN) SELF%RATATX
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TCSGEOM (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TCSGEOM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
READ (KLUN) LRCOLON
IF (LRCOLON) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RCOLON (IL1(1):IU1(1)))
  READ (KLUN) SELF%RCOLON
ELSE
  NULLIFY (SELF%RCOLON)
ENDIF
READ (KLUN) LRSILON
IF (LRSILON) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RSILON (IL1(1):IU1(1)))
  READ (KLUN) SELF%RSILON
ELSE
  NULLIFY (SELF%RSILON)
ENDIF
READ (KLUN) LRINDX
IF (LRINDX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RINDX (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RINDX,1):UBOUND(SELF%RINDX,1)))
  READ (KLUN) ZTMP1
  SELF%RINDX = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (SELF%RINDX)
ENDIF
READ (KLUN) LRINDY
IF (LRINDY) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RINDY (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RINDY,1):UBOUND(SELF%RINDY,1)))
  READ (KLUN) ZTMP1
  SELF%RINDY = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (SELF%RINDY)
ENDIF
READ (KLUN) LRATATH
IF (LRATATH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RATATH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RATATH,1):UBOUND(SELF%RATATH,1)))
  READ (KLUN) ZTMP1
  SELF%RATATH = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (SELF%RATATH)
ENDIF
READ (KLUN) LRATATX
IF (LRATATX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RATATX (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RATATX,1):UBOUND(SELF%RATATX,1)))
  READ (KLUN) ZTMP1
  SELF%RATATX = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (SELF%RATATX)
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_COPY_TCSGEOM (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCSGEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LRCOLON = ASSOCIATED (SELF%RCOLON)
IF (LRCOLON) THEN
  !$ACC ENTER DATA CREATE (SELF%RCOLON)
  !$ACC UPDATE DEVICE (SELF%RCOLON)
  !$ACC ENTER DATA ATTACH (SELF%RCOLON)
ENDIF

LRSILON = ASSOCIATED (SELF%RSILON)
IF (LRSILON) THEN
  !$ACC ENTER DATA CREATE (SELF%RSILON)
  !$ACC UPDATE DEVICE (SELF%RSILON)
  !$ACC ENTER DATA ATTACH (SELF%RSILON)
ENDIF

LRINDX = ASSOCIATED (SELF%RINDX)
IF (LRINDX) THEN
  !$ACC ENTER DATA CREATE (SELF%RINDX)
  !$ACC UPDATE DEVICE (SELF%RINDX)
  !$ACC ENTER DATA ATTACH (SELF%RINDX)
ENDIF

LRINDY = ASSOCIATED (SELF%RINDY)
IF (LRINDY) THEN
  !$ACC ENTER DATA CREATE (SELF%RINDY)
  !$ACC UPDATE DEVICE (SELF%RINDY)
  !$ACC ENTER DATA ATTACH (SELF%RINDY)
ENDIF

LRATATH = ASSOCIATED (SELF%RATATH)
IF (LRATATH) THEN
  !$ACC ENTER DATA CREATE (SELF%RATATH)
  !$ACC UPDATE DEVICE (SELF%RATATH)
  !$ACC ENTER DATA ATTACH (SELF%RATATH)
ENDIF

LRATATX = ASSOCIATED (SELF%RATATX)
IF (LRATATX) THEN
  !$ACC ENTER DATA CREATE (SELF%RATATX)
  !$ACC UPDATE DEVICE (SELF%RATATX)
  !$ACC ENTER DATA ATTACH (SELF%RATATX)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TCSGEOM (SELF)

IMPLICIT NONE
TYPE (TCSGEOM), TARGET :: SELF
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON

END SUBROUTINE



SUBROUTINE ACDC_CRC64_TCSGEOM (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TCSGEOM), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCOLON), CDPATH//'%RCOLON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSILON), CDPATH//'%RSILON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RINDX), CDPATH//'%RINDX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RINDY), CDPATH//'%RINDY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RATATH), CDPATH//'%RATATH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RATATX), CDPATH//'%RATATX'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TCSGEOM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCSGEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LRCOLON = ASSOCIATED (SELF%RCOLON)
IF (LRCOLON) THEN
  !$ACC EXIT DATA DETACH (SELF%RCOLON)
  !$ACC EXIT DATA DELETE (SELF%RCOLON)
ENDIF

LRSILON = ASSOCIATED (SELF%RSILON)
IF (LRSILON) THEN
  !$ACC EXIT DATA DETACH (SELF%RSILON)
  !$ACC EXIT DATA DELETE (SELF%RSILON)
ENDIF

LRINDX = ASSOCIATED (SELF%RINDX)
IF (LRINDX) THEN
  !$ACC EXIT DATA DETACH (SELF%RINDX)
  !$ACC EXIT DATA DELETE (SELF%RINDX)
ENDIF

LRINDY = ASSOCIATED (SELF%RINDY)
IF (LRINDY) THEN
  !$ACC EXIT DATA DETACH (SELF%RINDY)
  !$ACC EXIT DATA DELETE (SELF%RINDY)
ENDIF

LRATATH = ASSOCIATED (SELF%RATATH)
IF (LRATATH) THEN
  !$ACC EXIT DATA DETACH (SELF%RATATH)
  !$ACC EXIT DATA DELETE (SELF%RATATH)
ENDIF

LRATATX = ASSOCIATED (SELF%RATATX)
IF (LRATATX) THEN
  !$ACC EXIT DATA DETACH (SELF%RATATX)
  !$ACC EXIT DATA DELETE (SELF%RATATX)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TCSGEOM (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TCSGEOM),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LRCOLON = ASSOCIATED (SELF%RCOLON)
IF (LRCOLON) THEN
  ISIZE = KIND (SELF%RCOLON) * SIZE (SELF%RCOLON)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RCOLON'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSILON = ASSOCIATED (SELF%RSILON)
IF (LRSILON) THEN
  ISIZE = KIND (SELF%RSILON) * SIZE (SELF%RSILON)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSILON'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRINDX = ASSOCIATED (SELF%RINDX)
IF (LRINDX) THEN
  ISIZE = KIND (SELF%RINDX) * SIZE (SELF%RINDX)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RINDX'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRINDY = ASSOCIATED (SELF%RINDY)
IF (LRINDY) THEN
  ISIZE = KIND (SELF%RINDY) * SIZE (SELF%RINDY)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RINDY'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRATATH = ASSOCIATED (SELF%RATATH)
IF (LRATATH) THEN
  ISIZE = KIND (SELF%RATATH) * SIZE (SELF%RATATH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RATATH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRATATX = ASSOCIATED (SELF%RATATX)
IF (LRATATX) THEN
  ISIZE = KIND (SELF%RATATX) * SIZE (SELF%RATATX)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RATATX'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
