MODULE UTIL_RADIATION_GRID_STRUCT_MOD

USE YOMPRAD, ONLY : RADIATION_GRID_STRUCT

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_RADIATION_GRID_STRUCT
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_RADIATION_GRID_STRUCT
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_RADIATION_GRID_STRUCT (SELF, KLUN)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
WRITE (KLUN) SELF%NRESOL_ID
WRITE (KLUN) SELF%NGPTOT
WRITE (KLUN) SELF%NGPTOTG
WRITE (KLUN) SELF%NGPTOTMX
WRITE (KLUN) SELF%NSPEC2
WRITE (KLUN) SELF%NSMAX
WRITE (KLUN) SELF%NPTRFLOFF
WRITE (KLUN) SELF%NUMP
WRITE (KLUN) SELF%NDLON
WRITE (KLUN) SELF%NDGSAL
WRITE (KLUN) SELF%NDGENL
WRITE (KLUN) SELF%NDGSAH
WRITE (KLUN) SELF%NDGENH
WRITE (KLUN) SELF%NDGLG
WRITE (KLUN) SELF%NDGSAG
WRITE (KLUN) SELF%NDGENG
WRITE (KLUN) SELF%NDLSUR
WRITE (KLUN) SELF%NFRSTLOFF
WRITE (KLUN) SELF%NDSUR1
WRITE (KLUN) SELF%NDGSUR
WRITE (KLUN) SELF%MYFRSTACTLAT
WRITE (KLUN) SELF%MYLSTACTLAT
LNRGRI = ALLOCATED (SELF%NRGRI)
WRITE (KLUN) LNRGRI
IF (LNRGRI) THEN
  WRITE (KLUN) LBOUND (SELF%NRGRI)
  WRITE (KLUN) UBOUND (SELF%NRGRI)
  WRITE (KLUN) SELF%NRGRI
ENDIF
LNLOENG = ALLOCATED (SELF%NLOENG)
WRITE (KLUN) LNLOENG
IF (LNLOENG) THEN
  WRITE (KLUN) LBOUND (SELF%NLOENG)
  WRITE (KLUN) UBOUND (SELF%NLOENG)
  WRITE (KLUN) SELF%NLOENG
ENDIF
LNPTRFRSTLAT = ALLOCATED (SELF%NPTRFRSTLAT)
WRITE (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  WRITE (KLUN) LBOUND (SELF%NPTRFRSTLAT)
  WRITE (KLUN) UBOUND (SELF%NPTRFRSTLAT)
  WRITE (KLUN) SELF%NPTRFRSTLAT
ENDIF
LNFRSTLAT = ALLOCATED (SELF%NFRSTLAT)
WRITE (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  WRITE (KLUN) LBOUND (SELF%NFRSTLAT)
  WRITE (KLUN) UBOUND (SELF%NFRSTLAT)
  WRITE (KLUN) SELF%NFRSTLAT
ENDIF
LNLSTLAT = ALLOCATED (SELF%NLSTLAT)
WRITE (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  WRITE (KLUN) LBOUND (SELF%NLSTLAT)
  WRITE (KLUN) UBOUND (SELF%NLSTLAT)
  WRITE (KLUN) SELF%NLSTLAT
ENDIF
LMYMS = ALLOCATED (SELF%MYMS)
WRITE (KLUN) LMYMS
IF (LMYMS) THEN
  WRITE (KLUN) LBOUND (SELF%MYMS)
  WRITE (KLUN) UBOUND (SELF%MYMS)
  WRITE (KLUN) SELF%MYMS
ENDIF
LNASM0 = ALLOCATED (SELF%NASM0)
WRITE (KLUN) LNASM0
IF (LNASM0) THEN
  WRITE (KLUN) LBOUND (SELF%NASM0)
  WRITE (KLUN) UBOUND (SELF%NASM0)
  WRITE (KLUN) SELF%NASM0
ENDIF
LNSTA = ALLOCATED (SELF%NSTA)
WRITE (KLUN) LNSTA
IF (LNSTA) THEN
  WRITE (KLUN) LBOUND (SELF%NSTA)
  WRITE (KLUN) UBOUND (SELF%NSTA)
  WRITE (KLUN) SELF%NSTA
ENDIF
LNONL = ALLOCATED (SELF%NONL)
WRITE (KLUN) LNONL
IF (LNONL) THEN
  WRITE (KLUN) LBOUND (SELF%NONL)
  WRITE (KLUN) UBOUND (SELF%NONL)
  WRITE (KLUN) SELF%NONL
ENDIF
LGELAM = ALLOCATED (SELF%GELAM)
WRITE (KLUN) LGELAM
IF (LGELAM) THEN
  WRITE (KLUN) LBOUND (SELF%GELAM)
  WRITE (KLUN) UBOUND (SELF%GELAM)
  WRITE (KLUN) SELF%GELAM
ENDIF
LGELAT = ALLOCATED (SELF%GELAT)
WRITE (KLUN) LGELAT
IF (LGELAT) THEN
  WRITE (KLUN) LBOUND (SELF%GELAT)
  WRITE (KLUN) UBOUND (SELF%GELAT)
  WRITE (KLUN) SELF%GELAT
ENDIF
LGECLO = ALLOCATED (SELF%GECLO)
WRITE (KLUN) LGECLO
IF (LGECLO) THEN
  WRITE (KLUN) LBOUND (SELF%GECLO)
  WRITE (KLUN) UBOUND (SELF%GECLO)
  WRITE (KLUN) SELF%GECLO
ENDIF
LGESLO = ALLOCATED (SELF%GESLO)
WRITE (KLUN) LGESLO
IF (LGESLO) THEN
  WRITE (KLUN) LBOUND (SELF%GESLO)
  WRITE (KLUN) UBOUND (SELF%GESLO)
  WRITE (KLUN) SELF%GESLO
ENDIF
LRMU = ALLOCATED (SELF%RMU)
WRITE (KLUN) LRMU
IF (LRMU) THEN
  WRITE (KLUN) LBOUND (SELF%RMU)
  WRITE (KLUN) UBOUND (SELF%RMU)
  WRITE (KLUN) SELF%RMU
ENDIF
LRSQM2 = ALLOCATED (SELF%RSQM2)
WRITE (KLUN) LRSQM2
IF (LRSQM2) THEN
  WRITE (KLUN) LBOUND (SELF%RSQM2)
  WRITE (KLUN) UBOUND (SELF%RSQM2)
  WRITE (KLUN) SELF%RSQM2
ENDIF
LRLATIG = ALLOCATED (SELF%RLATIG)
WRITE (KLUN) LRLATIG
IF (LRLATIG) THEN
  WRITE (KLUN) LBOUND (SELF%RLATIG)
  WRITE (KLUN) UBOUND (SELF%RLATIG)
  WRITE (KLUN) SELF%RLATIG
ENDIF
LRLATI = ALLOCATED (SELF%RLATI)
WRITE (KLUN) LRLATI
IF (LRLATI) THEN
  WRITE (KLUN) LBOUND (SELF%RLATI)
  WRITE (KLUN) UBOUND (SELF%RLATI)
  WRITE (KLUN) SELF%RLATI
ENDIF
LGEMU = ALLOCATED (SELF%GEMU)
WRITE (KLUN) LGEMU
IF (LGEMU) THEN
  WRITE (KLUN) LBOUND (SELF%GEMU)
  WRITE (KLUN) UBOUND (SELF%GEMU)
  WRITE (KLUN) SELF%GEMU
ENDIF
LRIPI = ALLOCATED (SELF%RIPI)
WRITE (KLUN) LRIPI
IF (LRIPI) THEN
  WRITE (KLUN) LBOUND (SELF%RIPI)
  WRITE (KLUN) UBOUND (SELF%RIPI)
  WRITE (KLUN) SELF%RIPI
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_LOAD_RADIATION_GRID_STRUCT (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
READ (KLUN) SELF%NRESOL_ID
READ (KLUN) SELF%NGPTOT
READ (KLUN) SELF%NGPTOTG
READ (KLUN) SELF%NGPTOTMX
READ (KLUN) SELF%NSPEC2
READ (KLUN) SELF%NSMAX
READ (KLUN) SELF%NPTRFLOFF
READ (KLUN) SELF%NUMP
READ (KLUN) SELF%NDLON
READ (KLUN) SELF%NDGSAL
READ (KLUN) SELF%NDGENL
READ (KLUN) SELF%NDGSAH
READ (KLUN) SELF%NDGENH
READ (KLUN) SELF%NDGLG
READ (KLUN) SELF%NDGSAG
READ (KLUN) SELF%NDGENG
READ (KLUN) SELF%NDLSUR
READ (KLUN) SELF%NFRSTLOFF
READ (KLUN) SELF%NDSUR1
READ (KLUN) SELF%NDGSUR
READ (KLUN) SELF%MYFRSTACTLAT
READ (KLUN) SELF%MYLSTACTLAT
READ (KLUN) LNRGRI
IF (LNRGRI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NRGRI (IL1(1):IU1(1)))
  READ (KLUN) SELF%NRGRI
ENDIF
READ (KLUN) LNLOENG
IF (LNLOENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NLOENG (IL1(1):IU1(1)))
  READ (KLUN) SELF%NLOENG
ENDIF
READ (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NPTRFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%NPTRFRSTLAT
ENDIF
READ (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%NFRSTLAT
ENDIF
READ (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) SELF%NLSTLAT
ENDIF
READ (KLUN) LMYMS
IF (LMYMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%MYMS (IL1(1):IU1(1)))
  READ (KLUN) SELF%MYMS
ENDIF
READ (KLUN) LNASM0
IF (LNASM0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NASM0 (IL1(1):IU1(1)))
  READ (KLUN) SELF%NASM0
ENDIF
READ (KLUN) LNSTA
IF (LNSTA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NSTA (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NSTA
ENDIF
READ (KLUN) LNONL
IF (LNONL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%NONL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%NONL
ENDIF
READ (KLUN) LGELAM
IF (LGELAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%GELAM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%GELAM,1):UBOUND(SELF%GELAM,1)))
  READ (KLUN) ZTMP1
  SELF%GELAM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LGELAT
IF (LGELAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%GELAT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%GELAT,1):UBOUND(SELF%GELAT,1)))
  READ (KLUN) ZTMP1
  SELF%GELAT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LGECLO
IF (LGECLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%GECLO (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%GECLO,1):UBOUND(SELF%GECLO,1)))
  READ (KLUN) ZTMP1
  SELF%GECLO = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LGESLO
IF (LGESLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%GESLO (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%GESLO,1):UBOUND(SELF%GESLO,1)))
  READ (KLUN) ZTMP1
  SELF%GESLO = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRMU
IF (LRMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RMU (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RMU,1):UBOUND(SELF%RMU,1)))
  READ (KLUN) ZTMP1
  SELF%RMU = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRSQM2
IF (LRSQM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RSQM2 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RSQM2,1):UBOUND(SELF%RSQM2,1)))
  READ (KLUN) ZTMP1
  SELF%RSQM2 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLATIG
IF (LRLATIG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLATIG (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLATIG,1):UBOUND(SELF%RLATIG,1)))
  READ (KLUN) ZTMP1
  SELF%RLATIG = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLATI
IF (LRLATI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RLATI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RLATI,1):UBOUND(SELF%RLATI,1)))
  READ (KLUN) ZTMP1
  SELF%RLATI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LGEMU
IF (LGEMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%GEMU (IL1(1):IU1(1)))
  READ (KLUN) SELF%GEMU
ENDIF
READ (KLUN) LRIPI
IF (LRIPI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RIPI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%RIPI
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_COPY_RADIATION_GRID_STRUCT (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LNRGRI = ALLOCATED (SELF%NRGRI)
IF (LNRGRI) THEN
  !$ACC ENTER DATA CREATE (SELF%NRGRI)
  !$ACC UPDATE DEVICE (SELF%NRGRI)
  !$ACC ENTER DATA ATTACH (SELF%NRGRI)
ENDIF

LNLOENG = ALLOCATED (SELF%NLOENG)
IF (LNLOENG) THEN
  !$ACC ENTER DATA CREATE (SELF%NLOENG)
  !$ACC UPDATE DEVICE (SELF%NLOENG)
  !$ACC ENTER DATA ATTACH (SELF%NLOENG)
ENDIF

LNPTRFRSTLAT = ALLOCATED (SELF%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRFRSTLAT)
  !$ACC UPDATE DEVICE (SELF%NPTRFRSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NPTRFRSTLAT)
ENDIF

LNFRSTLAT = ALLOCATED (SELF%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NFRSTLAT)
  !$ACC UPDATE DEVICE (SELF%NFRSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (SELF%NLSTLAT)
IF (LNLSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NLSTLAT)
  !$ACC UPDATE DEVICE (SELF%NLSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NLSTLAT)
ENDIF

LMYMS = ALLOCATED (SELF%MYMS)
IF (LMYMS) THEN
  !$ACC ENTER DATA CREATE (SELF%MYMS)
  !$ACC UPDATE DEVICE (SELF%MYMS)
  !$ACC ENTER DATA ATTACH (SELF%MYMS)
ENDIF

LNASM0 = ALLOCATED (SELF%NASM0)
IF (LNASM0) THEN
  !$ACC ENTER DATA CREATE (SELF%NASM0)
  !$ACC UPDATE DEVICE (SELF%NASM0)
  !$ACC ENTER DATA ATTACH (SELF%NASM0)
ENDIF

LNSTA = ALLOCATED (SELF%NSTA)
IF (LNSTA) THEN
  !$ACC ENTER DATA CREATE (SELF%NSTA)
  !$ACC UPDATE DEVICE (SELF%NSTA)
  !$ACC ENTER DATA ATTACH (SELF%NSTA)
ENDIF

LNONL = ALLOCATED (SELF%NONL)
IF (LNONL) THEN
  !$ACC ENTER DATA CREATE (SELF%NONL)
  !$ACC UPDATE DEVICE (SELF%NONL)
  !$ACC ENTER DATA ATTACH (SELF%NONL)
ENDIF

LGELAM = ALLOCATED (SELF%GELAM)
IF (LGELAM) THEN
  !$ACC ENTER DATA CREATE (SELF%GELAM)
  !$ACC UPDATE DEVICE (SELF%GELAM)
  !$ACC ENTER DATA ATTACH (SELF%GELAM)
ENDIF

LGELAT = ALLOCATED (SELF%GELAT)
IF (LGELAT) THEN
  !$ACC ENTER DATA CREATE (SELF%GELAT)
  !$ACC UPDATE DEVICE (SELF%GELAT)
  !$ACC ENTER DATA ATTACH (SELF%GELAT)
ENDIF

LGECLO = ALLOCATED (SELF%GECLO)
IF (LGECLO) THEN
  !$ACC ENTER DATA CREATE (SELF%GECLO)
  !$ACC UPDATE DEVICE (SELF%GECLO)
  !$ACC ENTER DATA ATTACH (SELF%GECLO)
ENDIF

LGESLO = ALLOCATED (SELF%GESLO)
IF (LGESLO) THEN
  !$ACC ENTER DATA CREATE (SELF%GESLO)
  !$ACC UPDATE DEVICE (SELF%GESLO)
  !$ACC ENTER DATA ATTACH (SELF%GESLO)
ENDIF

LRMU = ALLOCATED (SELF%RMU)
IF (LRMU) THEN
  !$ACC ENTER DATA CREATE (SELF%RMU)
  !$ACC UPDATE DEVICE (SELF%RMU)
  !$ACC ENTER DATA ATTACH (SELF%RMU)
ENDIF

LRSQM2 = ALLOCATED (SELF%RSQM2)
IF (LRSQM2) THEN
  !$ACC ENTER DATA CREATE (SELF%RSQM2)
  !$ACC UPDATE DEVICE (SELF%RSQM2)
  !$ACC ENTER DATA ATTACH (SELF%RSQM2)
ENDIF

LRLATIG = ALLOCATED (SELF%RLATIG)
IF (LRLATIG) THEN
  !$ACC ENTER DATA CREATE (SELF%RLATIG)
  !$ACC UPDATE DEVICE (SELF%RLATIG)
  !$ACC ENTER DATA ATTACH (SELF%RLATIG)
ENDIF

LRLATI = ALLOCATED (SELF%RLATI)
IF (LRLATI) THEN
  !$ACC ENTER DATA CREATE (SELF%RLATI)
  !$ACC UPDATE DEVICE (SELF%RLATI)
  !$ACC ENTER DATA ATTACH (SELF%RLATI)
ENDIF

LGEMU = ALLOCATED (SELF%GEMU)
IF (LGEMU) THEN
  !$ACC ENTER DATA CREATE (SELF%GEMU)
  !$ACC UPDATE DEVICE (SELF%GEMU)
  !$ACC ENTER DATA ATTACH (SELF%GEMU)
ENDIF

LRIPI = ALLOCATED (SELF%RIPI)
IF (LRIPI) THEN
  !$ACC ENTER DATA CREATE (SELF%RIPI)
  !$ACC UPDATE DEVICE (SELF%RIPI)
  !$ACC ENTER DATA ATTACH (SELF%RIPI)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_RADIATION_GRID_STRUCT (SELF)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), TARGET :: SELF
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2

END SUBROUTINE



SUBROUTINE ACDC_CRC64_RADIATION_GRID_STRUCT (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NRESOL_ID), CDPATH//'%NRESOL_ID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGPTOT), CDPATH//'%NGPTOT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGPTOTG), CDPATH//'%NGPTOTG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGPTOTMX), CDPATH//'%NGPTOTMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPEC2), CDPATH//'%NSPEC2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSMAX), CDPATH//'%NSMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRFLOFF), CDPATH//'%NPTRFLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUMP), CDPATH//'%NUMP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDLON), CDPATH//'%NDLON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGSAL), CDPATH//'%NDGSAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGENL), CDPATH//'%NDGENL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGSAH), CDPATH//'%NDGSAH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGENH), CDPATH//'%NDGENH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGLG), CDPATH//'%NDGLG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGSAG), CDPATH//'%NDGSAG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGENG), CDPATH//'%NDGENG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDLSUR), CDPATH//'%NDLSUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFRSTLOFF), CDPATH//'%NFRSTLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDSUR1), CDPATH//'%NDSUR1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGSUR), CDPATH//'%NDGSUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYFRSTACTLAT), CDPATH//'%MYFRSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYLSTACTLAT), CDPATH//'%MYLSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NRGRI), CDPATH//'%NRGRI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLOENG), CDPATH//'%NLOENG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRFRSTLAT), CDPATH//'%NPTRFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFRSTLAT), CDPATH//'%NFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLSTLAT), CDPATH//'%NLSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYMS), CDPATH//'%MYMS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NASM0), CDPATH//'%NASM0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSTA), CDPATH//'%NSTA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NONL), CDPATH//'%NONL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GELAM), CDPATH//'%GELAM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GELAT), CDPATH//'%GELAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GECLO), CDPATH//'%GECLO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GESLO), CDPATH//'%GESLO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMU), CDPATH//'%RMU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSQM2), CDPATH//'%RSQM2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLATIG), CDPATH//'%RLATIG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLATI), CDPATH//'%RLATI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GEMU), CDPATH//'%GEMU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RIPI), CDPATH//'%RIPI'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_RADIATION_GRID_STRUCT (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LNRGRI = ALLOCATED (SELF%NRGRI)
IF (LNRGRI) THEN
  !$ACC EXIT DATA DETACH (SELF%NRGRI)
  !$ACC EXIT DATA DELETE (SELF%NRGRI)
ENDIF

LNLOENG = ALLOCATED (SELF%NLOENG)
IF (LNLOENG) THEN
  !$ACC EXIT DATA DETACH (SELF%NLOENG)
  !$ACC EXIT DATA DELETE (SELF%NLOENG)
ENDIF

LNPTRFRSTLAT = ALLOCATED (SELF%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%NPTRFRSTLAT)
  !$ACC EXIT DATA DELETE (SELF%NPTRFRSTLAT)
ENDIF

LNFRSTLAT = ALLOCATED (SELF%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%NFRSTLAT)
  !$ACC EXIT DATA DELETE (SELF%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (SELF%NLSTLAT)
IF (LNLSTLAT) THEN
  !$ACC EXIT DATA DETACH (SELF%NLSTLAT)
  !$ACC EXIT DATA DELETE (SELF%NLSTLAT)
ENDIF

LMYMS = ALLOCATED (SELF%MYMS)
IF (LMYMS) THEN
  !$ACC EXIT DATA DETACH (SELF%MYMS)
  !$ACC EXIT DATA DELETE (SELF%MYMS)
ENDIF

LNASM0 = ALLOCATED (SELF%NASM0)
IF (LNASM0) THEN
  !$ACC EXIT DATA DETACH (SELF%NASM0)
  !$ACC EXIT DATA DELETE (SELF%NASM0)
ENDIF

LNSTA = ALLOCATED (SELF%NSTA)
IF (LNSTA) THEN
  !$ACC EXIT DATA DETACH (SELF%NSTA)
  !$ACC EXIT DATA DELETE (SELF%NSTA)
ENDIF

LNONL = ALLOCATED (SELF%NONL)
IF (LNONL) THEN
  !$ACC EXIT DATA DETACH (SELF%NONL)
  !$ACC EXIT DATA DELETE (SELF%NONL)
ENDIF

LGELAM = ALLOCATED (SELF%GELAM)
IF (LGELAM) THEN
  !$ACC EXIT DATA DETACH (SELF%GELAM)
  !$ACC EXIT DATA DELETE (SELF%GELAM)
ENDIF

LGELAT = ALLOCATED (SELF%GELAT)
IF (LGELAT) THEN
  !$ACC EXIT DATA DETACH (SELF%GELAT)
  !$ACC EXIT DATA DELETE (SELF%GELAT)
ENDIF

LGECLO = ALLOCATED (SELF%GECLO)
IF (LGECLO) THEN
  !$ACC EXIT DATA DETACH (SELF%GECLO)
  !$ACC EXIT DATA DELETE (SELF%GECLO)
ENDIF

LGESLO = ALLOCATED (SELF%GESLO)
IF (LGESLO) THEN
  !$ACC EXIT DATA DETACH (SELF%GESLO)
  !$ACC EXIT DATA DELETE (SELF%GESLO)
ENDIF

LRMU = ALLOCATED (SELF%RMU)
IF (LRMU) THEN
  !$ACC EXIT DATA DETACH (SELF%RMU)
  !$ACC EXIT DATA DELETE (SELF%RMU)
ENDIF

LRSQM2 = ALLOCATED (SELF%RSQM2)
IF (LRSQM2) THEN
  !$ACC EXIT DATA DETACH (SELF%RSQM2)
  !$ACC EXIT DATA DELETE (SELF%RSQM2)
ENDIF

LRLATIG = ALLOCATED (SELF%RLATIG)
IF (LRLATIG) THEN
  !$ACC EXIT DATA DETACH (SELF%RLATIG)
  !$ACC EXIT DATA DELETE (SELF%RLATIG)
ENDIF

LRLATI = ALLOCATED (SELF%RLATI)
IF (LRLATI) THEN
  !$ACC EXIT DATA DETACH (SELF%RLATI)
  !$ACC EXIT DATA DELETE (SELF%RLATI)
ENDIF

LGEMU = ALLOCATED (SELF%GEMU)
IF (LGEMU) THEN
  !$ACC EXIT DATA DETACH (SELF%GEMU)
  !$ACC EXIT DATA DELETE (SELF%GEMU)
ENDIF

LRIPI = ALLOCATED (SELF%RIPI)
IF (LRIPI) THEN
  !$ACC EXIT DATA DETACH (SELF%RIPI)
  !$ACC EXIT DATA DELETE (SELF%RIPI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_RADIATION_GRID_STRUCT (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NRESOL_ID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NRESOL_ID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NGPTOT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGPTOT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NGPTOTG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGPTOTG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NGPTOTMX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGPTOTMX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSPEC2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NPTRFLOFF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPTRFLOFF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NUMP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NUMP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDLON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDLON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDGSAL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDGENL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDGSAH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDGENH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDGLG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGLG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDGSAG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDGENG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDLSUR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDLSUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NFRSTLOFF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFRSTLOFF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDSUR1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDSUR1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDGSUR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MYFRSTACTLAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MYFRSTACTLAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MYLSTACTLAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MYLSTACTLAT'
ENDIF
KSIZE = KSIZE + ISIZE
LNRGRI = ALLOCATED (SELF%NRGRI)
IF (LNRGRI) THEN
  ISIZE = KIND (SELF%NRGRI) * SIZE (SELF%NRGRI)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NRGRI'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNLOENG = ALLOCATED (SELF%NLOENG)
IF (LNLOENG) THEN
  ISIZE = KIND (SELF%NLOENG) * SIZE (SELF%NLOENG)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NLOENG'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRFRSTLAT = ALLOCATED (SELF%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  ISIZE = KIND (SELF%NPTRFRSTLAT) * SIZE (SELF%NPTRFRSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRFRSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNFRSTLAT = ALLOCATED (SELF%NFRSTLAT)
IF (LNFRSTLAT) THEN
  ISIZE = KIND (SELF%NFRSTLAT) * SIZE (SELF%NFRSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NFRSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNLSTLAT = ALLOCATED (SELF%NLSTLAT)
IF (LNLSTLAT) THEN
  ISIZE = KIND (SELF%NLSTLAT) * SIZE (SELF%NLSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NLSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMYMS = ALLOCATED (SELF%MYMS)
IF (LMYMS) THEN
  ISIZE = KIND (SELF%MYMS) * SIZE (SELF%MYMS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MYMS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNASM0 = ALLOCATED (SELF%NASM0)
IF (LNASM0) THEN
  ISIZE = KIND (SELF%NASM0) * SIZE (SELF%NASM0)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NASM0'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNSTA = ALLOCATED (SELF%NSTA)
IF (LNSTA) THEN
  ISIZE = KIND (SELF%NSTA) * SIZE (SELF%NSTA)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NSTA'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNONL = ALLOCATED (SELF%NONL)
IF (LNONL) THEN
  ISIZE = KIND (SELF%NONL) * SIZE (SELF%NONL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NONL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGELAM = ALLOCATED (SELF%GELAM)
IF (LGELAM) THEN
  ISIZE = KIND (SELF%GELAM) * SIZE (SELF%GELAM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GELAM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGELAT = ALLOCATED (SELF%GELAT)
IF (LGELAT) THEN
  ISIZE = KIND (SELF%GELAT) * SIZE (SELF%GELAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GELAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGECLO = ALLOCATED (SELF%GECLO)
IF (LGECLO) THEN
  ISIZE = KIND (SELF%GECLO) * SIZE (SELF%GECLO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GECLO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGESLO = ALLOCATED (SELF%GESLO)
IF (LGESLO) THEN
  ISIZE = KIND (SELF%GESLO) * SIZE (SELF%GESLO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GESLO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRMU = ALLOCATED (SELF%RMU)
IF (LRMU) THEN
  ISIZE = KIND (SELF%RMU) * SIZE (SELF%RMU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RMU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSQM2 = ALLOCATED (SELF%RSQM2)
IF (LRSQM2) THEN
  ISIZE = KIND (SELF%RSQM2) * SIZE (SELF%RSQM2)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSQM2'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLATIG = ALLOCATED (SELF%RLATIG)
IF (LRLATIG) THEN
  ISIZE = KIND (SELF%RLATIG) * SIZE (SELF%RLATIG)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLATIG'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLATI = ALLOCATED (SELF%RLATI)
IF (LRLATI) THEN
  ISIZE = KIND (SELF%RLATI) * SIZE (SELF%RLATI)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLATI'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGEMU = ALLOCATED (SELF%GEMU)
IF (LGEMU) THEN
  ISIZE = KIND (SELF%GEMU) * SIZE (SELF%GEMU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GEMU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRIPI = ALLOCATED (SELF%RIPI)
IF (LRIPI) THEN
  ISIZE = KIND (SELF%RIPI) * SIZE (SELF%RIPI)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RIPI'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
