MODULE UTIL_SPHYS_HIST_TYPE_MOD

USE YOMSPHYHIST, ONLY : SPHYS_HIST_TYPE

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_SPHYS_HIST_TYPE
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_SPHYS_HIST_TYPE
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_SPHYS_HIST_TYPE
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_SPHYS_HIST_TYPE
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_SPHYS_HIST_TYPE
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_SPHYS_HIST_TYPE
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_SPHYS_HIST_TYPE
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_SPHYS_HIST_TYPE (SELF, KLUN)

IMPLICIT NONE
TYPE (SPHYS_HIST_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5
LYA5 = ASSOCIATED (SELF%YA5)
WRITE (KLUN) LYA5
IF (LYA5) THEN
  WRITE (KLUN) LBOUND (SELF%YA5)
  WRITE (KLUN) UBOUND (SELF%YA5)
  WRITE (KLUN) SELF%YA5
ENDIF
LYL5 = ASSOCIATED (SELF%YL5)
WRITE (KLUN) LYL5
IF (LYL5) THEN
  WRITE (KLUN) LBOUND (SELF%YL5)
  WRITE (KLUN) UBOUND (SELF%YL5)
  WRITE (KLUN) SELF%YL5
ENDIF
LYI5 = ASSOCIATED (SELF%YI5)
WRITE (KLUN) LYI5
IF (LYI5) THEN
  WRITE (KLUN) LBOUND (SELF%YI5)
  WRITE (KLUN) UBOUND (SELF%YI5)
  WRITE (KLUN) SELF%YI5
ENDIF
LRADLWM = ASSOCIATED (SELF%RADLWM)
WRITE (KLUN) LRADLWM
IF (LRADLWM) THEN
  WRITE (KLUN) LBOUND (SELF%RADLWM)
  WRITE (KLUN) UBOUND (SELF%RADLWM)
  WRITE (KLUN) SELF%RADLWM
ENDIF
LRADLWM5 = ASSOCIATED (SELF%RADLWM5)
WRITE (KLUN) LRADLWM5
IF (LRADLWM5) THEN
  WRITE (KLUN) LBOUND (SELF%RADLWM5)
  WRITE (KLUN) UBOUND (SELF%RADLWM5)
  WRITE (KLUN) SELF%RADLWM5
ENDIF
LTGWDWMSU = ASSOCIATED (SELF%TGWDWMSU)
WRITE (KLUN) LTGWDWMSU
IF (LTGWDWMSU) THEN
  WRITE (KLUN) LBOUND (SELF%TGWDWMSU)
  WRITE (KLUN) UBOUND (SELF%TGWDWMSU)
  WRITE (KLUN) SELF%TGWDWMSU
ENDIF
LTGWDWMSU5 = ASSOCIATED (SELF%TGWDWMSU5)
WRITE (KLUN) LTGWDWMSU5
IF (LTGWDWMSU5) THEN
  WRITE (KLUN) LBOUND (SELF%TGWDWMSU5)
  WRITE (KLUN) UBOUND (SELF%TGWDWMSU5)
  WRITE (KLUN) SELF%TGWDWMSU5
ENDIF
LTGWDWMSV = ASSOCIATED (SELF%TGWDWMSV)
WRITE (KLUN) LTGWDWMSV
IF (LTGWDWMSV) THEN
  WRITE (KLUN) LBOUND (SELF%TGWDWMSV)
  WRITE (KLUN) UBOUND (SELF%TGWDWMSV)
  WRITE (KLUN) SELF%TGWDWMSV
ENDIF
LTGWDWMSV5 = ASSOCIATED (SELF%TGWDWMSV5)
WRITE (KLUN) LTGWDWMSV5
IF (LTGWDWMSV5) THEN
  WRITE (KLUN) LBOUND (SELF%TGWDWMSV5)
  WRITE (KLUN) UBOUND (SELF%TGWDWMSV5)
  WRITE (KLUN) SELF%TGWDWMSV5
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_LOAD_SPHYS_HIST_TYPE (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (SPHYS_HIST_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) LYA5
IF (LYA5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%YA5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%YA5,1):UBOUND(SELF%YA5,1), LBOUND(SELF%YA5,2):UBOUND(SELF%YA5,2)))
  READ (KLUN) ZTMP2
  SELF%YA5 = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%YA5)
ENDIF
READ (KLUN) LYL5
IF (LYL5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%YL5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%YL5,1):UBOUND(SELF%YL5,1), LBOUND(SELF%YL5,2):UBOUND(SELF%YL5,2)))
  READ (KLUN) ZTMP2
  SELF%YL5 = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%YL5)
ENDIF
READ (KLUN) LYI5
IF (LYI5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%YI5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%YI5,1):UBOUND(SELF%YI5,1), LBOUND(SELF%YI5,2):UBOUND(SELF%YI5,2)))
  READ (KLUN) ZTMP2
  SELF%YI5 = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%YI5)
ENDIF
READ (KLUN) LRADLWM
IF (LRADLWM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RADLWM (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RADLWM,1):UBOUND(SELF%RADLWM,1), LBOUND(SELF%RADLWM,2):UBOUND(SELF%RADLWM,2)))
  READ (KLUN) ZTMP2
  SELF%RADLWM = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%RADLWM)
ENDIF
READ (KLUN) LRADLWM5
IF (LRADLWM5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RADLWM5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RADLWM5,1):UBOUND(SELF%RADLWM5,1), LBOUND(SELF%RADLWM5,2):UBOUND(SELF%RADLWM5,2)))
  READ (KLUN) ZTMP2
  SELF%RADLWM5 = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%RADLWM5)
ENDIF
READ (KLUN) LTGWDWMSU
IF (LTGWDWMSU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%TGWDWMSU (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%TGWDWMSU,1):UBOUND(SELF%TGWDWMSU,1), LBOUND(SELF%TGWDWMSU,2):UBOUND(SELF%TGWDWMSU,2)))
  READ (KLUN) ZTMP2
  SELF%TGWDWMSU = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%TGWDWMSU)
ENDIF
READ (KLUN) LTGWDWMSU5
IF (LTGWDWMSU5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%TGWDWMSU5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%TGWDWMSU5,1):UBOUND(SELF%TGWDWMSU5,1), LBOUND(SELF%TGWDWMSU5,2):UBOUND(SELF%TGWDWMSU5,2)))
  READ (KLUN) ZTMP2
  SELF%TGWDWMSU5 = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%TGWDWMSU5)
ENDIF
READ (KLUN) LTGWDWMSV
IF (LTGWDWMSV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%TGWDWMSV (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%TGWDWMSV,1):UBOUND(SELF%TGWDWMSV,1), LBOUND(SELF%TGWDWMSV,2):UBOUND(SELF%TGWDWMSV,2)))
  READ (KLUN) ZTMP2
  SELF%TGWDWMSV = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%TGWDWMSV)
ENDIF
READ (KLUN) LTGWDWMSV5
IF (LTGWDWMSV5) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%TGWDWMSV5 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%TGWDWMSV5,1):UBOUND(SELF%TGWDWMSV5,1), LBOUND(SELF%TGWDWMSV5,2):UBOUND(SELF%TGWDWMSV5,2)))
  READ (KLUN) ZTMP2
  SELF%TGWDWMSV5 = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (SELF%TGWDWMSV5)
ENDIF
END SUBROUTINE

SUBROUTINE ACDC_COPY_SPHYS_HIST_TYPE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (SPHYS_HIST_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LYA5 = ASSOCIATED (SELF%YA5)
IF (LYA5) THEN
  !$ACC ENTER DATA CREATE (SELF%YA5)
  !$ACC UPDATE DEVICE (SELF%YA5)
  !$ACC ENTER DATA ATTACH (SELF%YA5)
ENDIF

LYL5 = ASSOCIATED (SELF%YL5)
IF (LYL5) THEN
  !$ACC ENTER DATA CREATE (SELF%YL5)
  !$ACC UPDATE DEVICE (SELF%YL5)
  !$ACC ENTER DATA ATTACH (SELF%YL5)
ENDIF

LYI5 = ASSOCIATED (SELF%YI5)
IF (LYI5) THEN
  !$ACC ENTER DATA CREATE (SELF%YI5)
  !$ACC UPDATE DEVICE (SELF%YI5)
  !$ACC ENTER DATA ATTACH (SELF%YI5)
ENDIF

LRADLWM = ASSOCIATED (SELF%RADLWM)
IF (LRADLWM) THEN
  !$ACC ENTER DATA CREATE (SELF%RADLWM)
  !$ACC UPDATE DEVICE (SELF%RADLWM)
  !$ACC ENTER DATA ATTACH (SELF%RADLWM)
ENDIF

LRADLWM5 = ASSOCIATED (SELF%RADLWM5)
IF (LRADLWM5) THEN
  !$ACC ENTER DATA CREATE (SELF%RADLWM5)
  !$ACC UPDATE DEVICE (SELF%RADLWM5)
  !$ACC ENTER DATA ATTACH (SELF%RADLWM5)
ENDIF

LTGWDWMSU = ASSOCIATED (SELF%TGWDWMSU)
IF (LTGWDWMSU) THEN
  !$ACC ENTER DATA CREATE (SELF%TGWDWMSU)
  !$ACC UPDATE DEVICE (SELF%TGWDWMSU)
  !$ACC ENTER DATA ATTACH (SELF%TGWDWMSU)
ENDIF

LTGWDWMSU5 = ASSOCIATED (SELF%TGWDWMSU5)
IF (LTGWDWMSU5) THEN
  !$ACC ENTER DATA CREATE (SELF%TGWDWMSU5)
  !$ACC UPDATE DEVICE (SELF%TGWDWMSU5)
  !$ACC ENTER DATA ATTACH (SELF%TGWDWMSU5)
ENDIF

LTGWDWMSV = ASSOCIATED (SELF%TGWDWMSV)
IF (LTGWDWMSV) THEN
  !$ACC ENTER DATA CREATE (SELF%TGWDWMSV)
  !$ACC UPDATE DEVICE (SELF%TGWDWMSV)
  !$ACC ENTER DATA ATTACH (SELF%TGWDWMSV)
ENDIF

LTGWDWMSV5 = ASSOCIATED (SELF%TGWDWMSV5)
IF (LTGWDWMSV5) THEN
  !$ACC ENTER DATA CREATE (SELF%TGWDWMSV5)
  !$ACC UPDATE DEVICE (SELF%TGWDWMSV5)
  !$ACC ENTER DATA ATTACH (SELF%TGWDWMSV5)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_SPHYS_HIST_TYPE (SELF)

IMPLICIT NONE
TYPE (SPHYS_HIST_TYPE), TARGET :: SELF
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5

END SUBROUTINE



SUBROUTINE ACDC_CRC64_SPHYS_HIST_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (SPHYS_HIST_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%YA5), CDPATH//'%YA5'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%YL5), CDPATH//'%YL5'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%YI5), CDPATH//'%YI5'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RADLWM), CDPATH//'%RADLWM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RADLWM5), CDPATH//'%RADLWM5'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TGWDWMSU), CDPATH//'%TGWDWMSU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TGWDWMSU5), CDPATH//'%TGWDWMSU5'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TGWDWMSV), CDPATH//'%TGWDWMSV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TGWDWMSV5), CDPATH//'%TGWDWMSV5'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_SPHYS_HIST_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (SPHYS_HIST_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LYA5 = ASSOCIATED (SELF%YA5)
IF (LYA5) THEN
  !$ACC EXIT DATA DETACH (SELF%YA5)
  !$ACC EXIT DATA DELETE (SELF%YA5)
ENDIF

LYL5 = ASSOCIATED (SELF%YL5)
IF (LYL5) THEN
  !$ACC EXIT DATA DETACH (SELF%YL5)
  !$ACC EXIT DATA DELETE (SELF%YL5)
ENDIF

LYI5 = ASSOCIATED (SELF%YI5)
IF (LYI5) THEN
  !$ACC EXIT DATA DETACH (SELF%YI5)
  !$ACC EXIT DATA DELETE (SELF%YI5)
ENDIF

LRADLWM = ASSOCIATED (SELF%RADLWM)
IF (LRADLWM) THEN
  !$ACC EXIT DATA DETACH (SELF%RADLWM)
  !$ACC EXIT DATA DELETE (SELF%RADLWM)
ENDIF

LRADLWM5 = ASSOCIATED (SELF%RADLWM5)
IF (LRADLWM5) THEN
  !$ACC EXIT DATA DETACH (SELF%RADLWM5)
  !$ACC EXIT DATA DELETE (SELF%RADLWM5)
ENDIF

LTGWDWMSU = ASSOCIATED (SELF%TGWDWMSU)
IF (LTGWDWMSU) THEN
  !$ACC EXIT DATA DETACH (SELF%TGWDWMSU)
  !$ACC EXIT DATA DELETE (SELF%TGWDWMSU)
ENDIF

LTGWDWMSU5 = ASSOCIATED (SELF%TGWDWMSU5)
IF (LTGWDWMSU5) THEN
  !$ACC EXIT DATA DETACH (SELF%TGWDWMSU5)
  !$ACC EXIT DATA DELETE (SELF%TGWDWMSU5)
ENDIF

LTGWDWMSV = ASSOCIATED (SELF%TGWDWMSV)
IF (LTGWDWMSV) THEN
  !$ACC EXIT DATA DETACH (SELF%TGWDWMSV)
  !$ACC EXIT DATA DELETE (SELF%TGWDWMSV)
ENDIF

LTGWDWMSV5 = ASSOCIATED (SELF%TGWDWMSV5)
IF (LTGWDWMSV5) THEN
  !$ACC EXIT DATA DETACH (SELF%TGWDWMSV5)
  !$ACC EXIT DATA DELETE (SELF%TGWDWMSV5)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_SPHYS_HIST_TYPE (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (SPHYS_HIST_TYPE),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LYA5 = ASSOCIATED (SELF%YA5)
IF (LYA5) THEN
  ISIZE = KIND (SELF%YA5) * SIZE (SELF%YA5)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%YA5'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LYL5 = ASSOCIATED (SELF%YL5)
IF (LYL5) THEN
  ISIZE = KIND (SELF%YL5) * SIZE (SELF%YL5)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%YL5'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LYI5 = ASSOCIATED (SELF%YI5)
IF (LYI5) THEN
  ISIZE = KIND (SELF%YI5) * SIZE (SELF%YI5)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%YI5'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRADLWM = ASSOCIATED (SELF%RADLWM)
IF (LRADLWM) THEN
  ISIZE = KIND (SELF%RADLWM) * SIZE (SELF%RADLWM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RADLWM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRADLWM5 = ASSOCIATED (SELF%RADLWM5)
IF (LRADLWM5) THEN
  ISIZE = KIND (SELF%RADLWM5) * SIZE (SELF%RADLWM5)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RADLWM5'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LTGWDWMSU = ASSOCIATED (SELF%TGWDWMSU)
IF (LTGWDWMSU) THEN
  ISIZE = KIND (SELF%TGWDWMSU) * SIZE (SELF%TGWDWMSU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%TGWDWMSU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LTGWDWMSU5 = ASSOCIATED (SELF%TGWDWMSU5)
IF (LTGWDWMSU5) THEN
  ISIZE = KIND (SELF%TGWDWMSU5) * SIZE (SELF%TGWDWMSU5)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%TGWDWMSU5'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LTGWDWMSV = ASSOCIATED (SELF%TGWDWMSV)
IF (LTGWDWMSV) THEN
  ISIZE = KIND (SELF%TGWDWMSV) * SIZE (SELF%TGWDWMSV)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%TGWDWMSV'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LTGWDWMSV5 = ASSOCIATED (SELF%TGWDWMSV5)
IF (LTGWDWMSV5) THEN
  ISIZE = KIND (SELF%TGWDWMSV5) * SIZE (SELF%TGWDWMSV5)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%TGWDWMSV5'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
