MODULE UTIL_TPHNC_MOD

USE YOPHNC, ONLY : TPHNC

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TPHNC
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TPHNC
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TPHNC
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_TPHNC
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_TPHNC
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TPHNC
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_TPHNC
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_TPHNC (SELF, KLUN)

IMPLICIT NONE
TYPE (TPHNC), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LETRAJP
WRITE (KLUN) SELF%LETRAJPT
WRITE (KLUN) SELF%LERADI2
WRITE (KLUN) SELF%LERADS2
WRITE (KLUN) SELF%LERADSW2
WRITE (KLUN) SELF%LERADN2
WRITE (KLUN) SELF%LERADFL2
WRITE (KLUN) SELF%LERADLW2
WRITE (KLUN) SELF%LH2OCO2
WRITE (KLUN) SELF%LWLOPT
WRITE (KLUN) SELF%LWSOPT
WRITE (KLUN) SELF%LEDCLD2
WRITE (KLUN) SELF%LEPCLD2
WRITE (KLUN) SELF%LENCLD2
WRITE (KLUN) SELF%LEVAPLS2
WRITE (KLUN) SELF%LEVDIF2
WRITE (KLUN) SELF%LEGWDG2
WRITE (KLUN) SELF%LECUMF2
WRITE (KLUN) SELF%LECOND2
WRITE (KLUN) SELF%LEGWWMS2
WRITE (KLUN) SELF%LEQNGT2
WRITE (KLUN) SELF%LESURF2
WRITE (KLUN) SELF%LEKPERT
WRITE (KLUN) SELF%LEKPERTS
WRITE (KLUN) SELF%LTRACLNPH
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TPHNC (SELF, KLUN)

IMPLICIT NONE
TYPE (TPHNC), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%LETRAJP
READ (KLUN) SELF%LETRAJPT
READ (KLUN) SELF%LERADI2
READ (KLUN) SELF%LERADS2
READ (KLUN) SELF%LERADSW2
READ (KLUN) SELF%LERADN2
READ (KLUN) SELF%LERADFL2
READ (KLUN) SELF%LERADLW2
READ (KLUN) SELF%LH2OCO2
READ (KLUN) SELF%LWLOPT
READ (KLUN) SELF%LWSOPT
READ (KLUN) SELF%LEDCLD2
READ (KLUN) SELF%LEPCLD2
READ (KLUN) SELF%LENCLD2
READ (KLUN) SELF%LEVAPLS2
READ (KLUN) SELF%LEVDIF2
READ (KLUN) SELF%LEGWDG2
READ (KLUN) SELF%LECUMF2
READ (KLUN) SELF%LECOND2
READ (KLUN) SELF%LEGWWMS2
READ (KLUN) SELF%LEQNGT2
READ (KLUN) SELF%LESURF2
READ (KLUN) SELF%LEKPERT
READ (KLUN) SELF%LEKPERTS
READ (KLUN) SELF%LTRACLNPH
END SUBROUTINE

SUBROUTINE ACDC_COPY_TPHNC (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPHNC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_TPHNC (SELF)

IMPLICIT NONE
TYPE (TPHNC), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_TPHNC (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (TPHNC), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LETRAJP), CDPATH//'%LETRAJP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LETRAJPT), CDPATH//'%LETRAJPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADI2), CDPATH//'%LERADI2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADS2), CDPATH//'%LERADS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADSW2), CDPATH//'%LERADSW2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADN2), CDPATH//'%LERADN2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADFL2), CDPATH//'%LERADFL2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LERADLW2), CDPATH//'%LERADLW2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LH2OCO2), CDPATH//'%LH2OCO2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LWLOPT), CDPATH//'%LWLOPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LWSOPT), CDPATH//'%LWSOPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEDCLD2), CDPATH//'%LEDCLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEPCLD2), CDPATH//'%LEPCLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LENCLD2), CDPATH//'%LENCLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEVAPLS2), CDPATH//'%LEVAPLS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEVDIF2), CDPATH//'%LEVDIF2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEGWDG2), CDPATH//'%LEGWDG2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LECUMF2), CDPATH//'%LECUMF2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LECOND2), CDPATH//'%LECOND2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEGWWMS2), CDPATH//'%LEGWWMS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEQNGT2), CDPATH//'%LEQNGT2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LESURF2), CDPATH//'%LESURF2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEKPERT), CDPATH//'%LEKPERT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LEKPERTS), CDPATH//'%LEKPERTS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LTRACLNPH), CDPATH//'%LTRACLNPH'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_TPHNC (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPHNC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_TPHNC (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TPHNC),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%LETRAJP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LETRAJP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LETRAJPT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LETRAJPT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LERADI2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADI2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LERADS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LERADSW2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADSW2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LERADN2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADN2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LERADFL2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADFL2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LERADLW2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADLW2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LH2OCO2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LH2OCO2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LWLOPT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LWLOPT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LWSOPT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LWSOPT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LEDCLD2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEDCLD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LEPCLD2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEPCLD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LENCLD2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LENCLD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LEVAPLS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEVAPLS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LEVDIF2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEVDIF2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LEGWDG2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEGWDG2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LECUMF2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECUMF2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LECOND2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECOND2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LEGWWMS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEGWWMS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LEQNGT2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEQNGT2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LESURF2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LESURF2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LEKPERT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEKPERT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LEKPERTS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEKPERTS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LTRACLNPH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LTRACLNPH'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
