SUBMODULE (MODD_CLOUDPAR_N) MODD_CLOUDPAR_N_CLOUDPAR_T_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_CLOUDPAR_T (SELF, KLUN)

IMPLICIT NONE
CLASS (CLOUDPAR_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NSPLITR
READ (KLUN) SELF%NSPLITG
END SUBROUTINE

END SUBMODULE
