SUBMODULE (MODD_RAIN_ICE_DESCR_N) MODD_RAIN_ICE_DESCR_N_RAIN_ICE_DESCR_T_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_RAIN_ICE_DESCR_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (RAIN_ICE_DESCR_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LXRTMIN
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LXRTMIN = ALLOCATED (SELF%XRTMIN)
IF (LXRTMIN) THEN
  !$ACC EXIT DATA DETACH (SELF%XRTMIN)
  !$ACC EXIT DATA DELETE (SELF%XRTMIN)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
