SUBMODULE (MODD_PARAM_LIMA) MODD_PARAM_LIMA_PARAM_LIMA_T_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_PARAM_LIMA_T (SELF, KLUN)

IMPLICIT NONE
CLASS (PARAM_LIMA_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LNIMM, LNINDICE_CCN_IMM, LXABSCISS, LXBETAHEN_MULTI, LXCONC_CCN_TOT, LXCTMIN, LXFRAC, LXFRAC_REF, LXKHEN_MULTI, LXLIMIT_FACTOR
LOGICAL :: LXLOGSIG_CCN, LXMDIAM_IFN, LXMUHEN_MULTI, LXRHO_CCN, LXRHO_IFN, LXRTMIN, LXR_MEAN_CCN, LXSIGMA_IFN, LXWEIGHT
READ (KLUN) SELF%LLIMA_DIAG
READ (KLUN) SELF%LPTSPLIT
READ (KLUN) SELF%LFEEDBACKT
READ (KLUN) SELF%NMAXITER
READ (KLUN) SELF%XMRSTEP
READ (KLUN) SELF%XTSTEP_TS
READ (KLUN) SELF%LNUCL
READ (KLUN) SELF%LSEDI
READ (KLUN) SELF%LHHONI
READ (KLUN) SELF%LMEYERS
READ (KLUN) SELF%LCIBU
READ (KLUN) SELF%LRDSF
READ (KLUN) SELF%NMOM_I
READ (KLUN) SELF%NMOM_S
READ (KLUN) SELF%NMOM_G
READ (KLUN) SELF%NMOM_H
READ (KLUN) SELF%NMOD_IFN
READ (KLUN) SELF%XIFN_CONC
READ (KLUN) SELF%LIFN_HOM
READ (KLUN) SELF%CIFN_SPECIES
READ (KLUN) SELF%CINT_MIXING
READ (KLUN) SELF%NMOD_IMM
READ (KLUN) SELF%NIND_SPECIE
READ (KLUN) LNIMM
IF (LNIMM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NIMM (IL1(1):IU1(1)))
  READ (KLUN) SELF%NIMM
ENDIF
READ (KLUN) LNINDICE_CCN_IMM
IF (LNINDICE_CCN_IMM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NINDICE_CCN_IMM (IL1(1):IU1(1)))
  READ (KLUN) SELF%NINDICE_CCN_IMM
ENDIF
READ (KLUN) SELF%NSPECIE
READ (KLUN) LXMDIAM_IFN
IF (LXMDIAM_IFN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XMDIAM_IFN (IL1(1):IU1(1)))
  READ (KLUN) SELF%XMDIAM_IFN
ENDIF
READ (KLUN) LXSIGMA_IFN
IF (LXSIGMA_IFN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XSIGMA_IFN (IL1(1):IU1(1)))
  READ (KLUN) SELF%XSIGMA_IFN
ENDIF
READ (KLUN) LXRHO_IFN
IF (LXRHO_IFN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XRHO_IFN (IL1(1):IU1(1)))
  READ (KLUN) SELF%XRHO_IFN
ENDIF
READ (KLUN) LXFRAC
IF (LXFRAC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XFRAC (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XFRAC
ENDIF
READ (KLUN) LXFRAC_REF
IF (LXFRAC_REF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XFRAC_REF (IL1(1):IU1(1)))
  READ (KLUN) SELF%XFRAC_REF
ENDIF
READ (KLUN) SELF%LSNOW_T
READ (KLUN) SELF%LMURAKAMI
READ (KLUN) SELF%CPRISTINE_ICE_LIMA
READ (KLUN) SELF%CHEVRIMED_ICE_LIMA
READ (KLUN) SELF%XALPHAI
READ (KLUN) SELF%XNUI
READ (KLUN) SELF%XALPHAS
READ (KLUN) SELF%XNUS
READ (KLUN) SELF%XALPHAG
READ (KLUN) SELF%XNUG
READ (KLUN) SELF%NPHILLIPS
READ (KLUN) SELF%XT0
READ (KLUN) SELF%XDT0
READ (KLUN) SELF%XDSI0
READ (KLUN) SELF%XSW0
READ (KLUN) SELF%XRHO_CFDC
READ (KLUN) SELF%XH
READ (KLUN) SELF%XAREA1
READ (KLUN) SELF%XGAMMA
READ (KLUN) SELF%XTX1
READ (KLUN) SELF%XTX2
READ (KLUN) LXABSCISS
IF (LXABSCISS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XABSCISS (IL1(1):IU1(1)))
  READ (KLUN) SELF%XABSCISS
ENDIF
READ (KLUN) LXWEIGHT
IF (LXWEIGHT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XWEIGHT (IL1(1):IU1(1)))
  READ (KLUN) SELF%XWEIGHT
ENDIF
READ (KLUN) SELF%NDIAM
READ (KLUN) SELF%XFACTNUC_DEP
READ (KLUN) SELF%XFACTNUC_CON
READ (KLUN) SELF%XNDEBRIS_CIBU
READ (KLUN) SELF%LACTI
READ (KLUN) SELF%LSEDC
READ (KLUN) SELF%LACTIT
READ (KLUN) SELF%LDEPOC
READ (KLUN) SELF%LACTTKE
READ (KLUN) SELF%LADJ
READ (KLUN) SELF%LSPRO
READ (KLUN) SELF%LKHKO
READ (KLUN) SELF%LKESSLERAC
READ (KLUN) SELF%NMOM_C
READ (KLUN) SELF%NMOM_R
READ (KLUN) SELF%NMOD_CCN
READ (KLUN) SELF%XCCN_CONC
READ (KLUN) SELF%LCCN_HOM
READ (KLUN) SELF%CCCN_MODES
READ (KLUN) LXR_MEAN_CCN
IF (LXR_MEAN_CCN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XR_MEAN_CCN (IL1(1):IU1(1)))
  READ (KLUN) SELF%XR_MEAN_CCN
ENDIF
READ (KLUN) LXLOGSIG_CCN
IF (LXLOGSIG_CCN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XLOGSIG_CCN (IL1(1):IU1(1)))
  READ (KLUN) SELF%XLOGSIG_CCN
ENDIF
READ (KLUN) LXRHO_CCN
IF (LXRHO_CCN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XRHO_CCN (IL1(1):IU1(1)))
  READ (KLUN) SELF%XRHO_CCN
ENDIF
READ (KLUN) LXKHEN_MULTI
IF (LXKHEN_MULTI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XKHEN_MULTI (IL1(1):IU1(1)))
  READ (KLUN) SELF%XKHEN_MULTI
ENDIF
READ (KLUN) LXMUHEN_MULTI
IF (LXMUHEN_MULTI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XMUHEN_MULTI (IL1(1):IU1(1)))
  READ (KLUN) SELF%XMUHEN_MULTI
ENDIF
READ (KLUN) LXBETAHEN_MULTI
IF (LXBETAHEN_MULTI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XBETAHEN_MULTI (IL1(1):IU1(1)))
  READ (KLUN) SELF%XBETAHEN_MULTI
ENDIF
READ (KLUN) LXCONC_CCN_TOT
IF (LXCONC_CCN_TOT) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%XCONC_CCN_TOT (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) SELF%XCONC_CCN_TOT
ENDIF
READ (KLUN) LXLIMIT_FACTOR
IF (LXLIMIT_FACTOR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XLIMIT_FACTOR (IL1(1):IU1(1)))
  READ (KLUN) SELF%XLIMIT_FACTOR
ENDIF
READ (KLUN) SELF%XALPHAR
READ (KLUN) SELF%XNUR
READ (KLUN) SELF%XALPHAC
READ (KLUN) SELF%XNUC
READ (KLUN) SELF%HPARAM_CCN
READ (KLUN) SELF%HINI_CCN
READ (KLUN) SELF%HTYPE_CCN
READ (KLUN) SELF%XFSOLUB_CCN
READ (KLUN) SELF%XACTEMP_CCN
READ (KLUN) SELF%XAERDIFF
READ (KLUN) SELF%XAERHEIGHT
READ (KLUN) SELF%XVDEPOC
READ (KLUN) SELF%LSCAV
READ (KLUN) SELF%LAERO_MASS
READ (KLUN) SELF%NDIAMR
READ (KLUN) SELF%NDIAMP
READ (KLUN) SELF%XT0SCAV
READ (KLUN) SELF%XTREF
READ (KLUN) SELF%XNDO
READ (KLUN) SELF%XMUA0
READ (KLUN) SELF%XT_SUTH_A
READ (KLUN) SELF%XMFPA0
READ (KLUN) SELF%XVISCW
READ (KLUN) SELF%XRHO00
READ (KLUN) SELF%XCEXVT
READ (KLUN) LXRTMIN
IF (LXRTMIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XRTMIN (IL1(1):IU1(1)))
  READ (KLUN) SELF%XRTMIN
ENDIF
READ (KLUN) LXCTMIN
IF (LXCTMIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%XCTMIN (IL1(1):IU1(1)))
  READ (KLUN) SELF%XCTMIN
ENDIF
READ (KLUN) SELF%NSPLITSED
READ (KLUN) SELF%XLB
READ (KLUN) SELF%XLBEX
READ (KLUN) SELF%XD
READ (KLUN) SELF%XFSEDR
READ (KLUN) SELF%XFSEDC
END SUBROUTINE

END SUBMODULE
