SUBMODULE (MODD_CLOUDPAR_N) MODD_CLOUDPAR_N_CLOUDPAR_T_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_CLOUDPAR_T (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (CLOUDPAR_T), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPLITR), CDPATH//'%NSPLITR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPLITG), CDPATH//'%NSPLITG'

END SUBROUTINE

END SUBMODULE
