SUBMODULE (MODD_PARAM_LIMA) MODD_PARAM_LIMA_PARAM_LIMA_T_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_PARAM_LIMA_T (SELF)

IMPLICIT NONE
CLASS (PARAM_LIMA_T), TARGET :: SELF
LOGICAL :: LNIMM, LNINDICE_CCN_IMM, LXABSCISS, LXBETAHEN_MULTI, LXCONC_CCN_TOT, LXCTMIN, LXFRAC, LXFRAC_REF, LXKHEN_MULTI, LXLIMIT_FACTOR
LOGICAL :: LXLOGSIG_CCN, LXMDIAM_IFN, LXMUHEN_MULTI, LXRHO_CCN, LXRHO_IFN, LXRTMIN, LXR_MEAN_CCN, LXSIGMA_IFN, LXWEIGHT

END SUBROUTINE

END SUBMODULE
