MODULE UTIL_CPG_BNDS_TYPE_MOD

USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_CPG_BNDS_TYPE
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_CPG_BNDS_TYPE
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_CPG_BNDS_TYPE
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_CPG_BNDS_TYPE
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_CPG_BNDS_TYPE
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_CPG_BNDS_TYPE
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_CPG_BNDS_TYPE (SELF, KLUN)

IMPLICIT NONE
TYPE (CPG_BNDS_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%KIDIA
WRITE (KLUN) SELF%KFDIA
WRITE (KLUN) SELF%KFDIE
WRITE (KLUN) SELF%KIDIE
WRITE (KLUN) SELF%KBL
WRITE (KLUN) SELF%KSTGLO
WRITE (KLUN) SELF%KLON
WRITE (KLUN) SELF%KGPTOT
WRITE (KLUN) SELF%KGPCOMP
END SUBROUTINE

SUBROUTINE ACDC_LOAD_CPG_BNDS_TYPE (SELF, KLUN)

IMPLICIT NONE
TYPE (CPG_BNDS_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%KIDIA
READ (KLUN) SELF%KFDIA
READ (KLUN) SELF%KFDIE
READ (KLUN) SELF%KIDIE
READ (KLUN) SELF%KBL
READ (KLUN) SELF%KSTGLO
READ (KLUN) SELF%KLON
READ (KLUN) SELF%KGPTOT
READ (KLUN) SELF%KGPCOMP
END SUBROUTINE

SUBROUTINE ACDC_COPY_CPG_BNDS_TYPE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CPG_BNDS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_CPG_BNDS_TYPE (SELF)

IMPLICIT NONE
TYPE (CPG_BNDS_TYPE), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_CPG_BNDS_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (CPG_BNDS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%KIDIA), CDPATH//'%KIDIA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%KFDIA), CDPATH//'%KFDIA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%KFDIE), CDPATH//'%KFDIE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%KIDIE), CDPATH//'%KIDIE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%KBL), CDPATH//'%KBL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%KSTGLO), CDPATH//'%KSTGLO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%KLON), CDPATH//'%KLON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%KGPTOT), CDPATH//'%KGPTOT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%KGPCOMP), CDPATH//'%KGPCOMP'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_CPG_BNDS_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CPG_BNDS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
