MODULE UTIL_SURFACE_VIEW_GROUP_VDIAGO2_MOD

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_VDIAGO2



INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_SURFACE_VIEW_GROUP_VDIAGO2
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_SURFACE_VIEW_GROUP_VDIAGO2
END INTERFACE

     

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_SURFACE_VIEW_GROUP_VDIAGO2
END INTERFACE



CONTAINS





SUBROUTINE ACDC_COPY_SURFACE_VIEW_GROUP_VDIAGO2 (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_VDIAGO2_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VDIAGO2), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP, LF_OCDEP, LF_USTRC, LF_VSTRC, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LVARIABLE_GROUP = ASSOCIATED (SELF%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC ENTER DATA CREATE (SELF%VARIABLE_GROUP)
  !$ACC UPDATE DEVICE (SELF%VARIABLE_GROUP)
  CALL ACDC_COPY_SURFACE_VARIABLE_GROUP_VDIAGO2 (SELF%VARIABLE_GROUP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (SELF%VARIABLE_GROUP)
ENDIF

LF_OCDEP = ASSOCIATED (SELF%F_OCDEP)
IF (LF_OCDEP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_OCDEP)
  !$ACC ENTER DATA ATTACH (SELF%F_OCDEP)
ENDIF

LF_USTRC = ASSOCIATED (SELF%F_USTRC)
IF (LF_USTRC .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_USTRC)
  !$ACC ENTER DATA ATTACH (SELF%F_USTRC)
ENDIF

LF_VSTRC = ASSOCIATED (SELF%F_VSTRC)
IF (LF_VSTRC .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (SELF%F_VSTRC)
  !$ACC ENTER DATA ATTACH (SELF%F_VSTRC)
ENDIF

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_GROUP)
  !$ACC ENTER DATA ATTACH (SELF%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_SURFACE_VIEW_GROUP_VDIAGO2 (SELF)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_VDIAGO2_MOD

IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VDIAGO2), TARGET :: SELF
LOGICAL :: LF_GROUP, LF_OCDEP, LF_USTRC, LF_VSTRC, LVARIABLE_GROUP
LVARIABLE_GROUP = ASSOCIATED (SELF%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  CALL ACDC_HOST_SURFACE_VARIABLE_GROUP_VDIAGO2 (SELF%VARIABLE_GROUP)
ENDIF

LF_OCDEP = ASSOCIATED (SELF%F_OCDEP)
IF (LF_OCDEP) THEN
  CALL HOST_FIELD_2RB (SELF%F_OCDEP)
ENDIF

LF_USTRC = ASSOCIATED (SELF%F_USTRC)
IF (LF_USTRC) THEN
  CALL HOST_FIELD_2RB (SELF%F_USTRC)
ENDIF

LF_VSTRC = ASSOCIATED (SELF%F_VSTRC)
IF (LF_VSTRC) THEN
  CALL HOST_FIELD_2RB (SELF%F_VSTRC)
ENDIF

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (SELF%F_GROUP)
ENDIF

END SUBROUTINE

     



SUBROUTINE ACDC_WIPE_SURFACE_VIEW_GROUP_VDIAGO2 (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_VDIAGO2_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VDIAGO2), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP, LF_OCDEP, LF_USTRC, LF_VSTRC, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVARIABLE_GROUP = ASSOCIATED (SELF%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC EXIT DATA DETACH (SELF%VARIABLE_GROUP)
  CALL ACDC_WIPE_SURFACE_VARIABLE_GROUP_VDIAGO2 (SELF%VARIABLE_GROUP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (SELF%VARIABLE_GROUP)
ENDIF

LF_OCDEP = ASSOCIATED (SELF%F_OCDEP)
IF (LF_OCDEP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_OCDEP)
ENDIF

LF_USTRC = ASSOCIATED (SELF%F_USTRC)
IF (LF_USTRC .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_USTRC)
ENDIF

LF_VSTRC = ASSOCIATED (SELF%F_VSTRC)
IF (LF_VSTRC .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_VSTRC)
ENDIF

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
