INTERFACE
SUBROUTINE APL_ARPEGE_SURFACE_UPDATE_LMSE_F (YDCPG_OPTS, PDTPHY, YDMF_PHYS, YDMF_PHYS_SURF&
&, YDMODEL, YDCPG_BNDS, PFLU_FEVI, PFLU_VEG, PDSA_C2, PDSA_C1)
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE TYPE_MODEL,ONLY:MODEL
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
REAL (KIND=JPRB), INTENT (IN)::PDTPHY
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (IN)::PFLU_FEVI (YDCPG_OPTS%KLON, YDCPG_OPTS%KTSSG+1)
REAL (KIND=JPRB), INTENT (IN)::PFLU_VEG (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PDSA_C2 (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PDSA_C1 (YDCPG_OPTS%KLON)
ENDSUBROUTINE
END INTERFACE
