INTERFACE
SUBROUTINE APL_ARPEGE_INIT_OUTLINE_001 (YDVARS, YDCPG_MISC, YDCPG_OPTS&
&, YDMF_PHYS_SURF, YDMF_PHYS_BASE_STATE, YDMODEL, YDCPG_BNDS, PQO3)
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (OUT)::PQO3 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
ENDSUBROUTINE
END INTERFACE
