SUBROUTINE APL_ARPEGE_FRSOPT (YDMF_PHYS_BASE_STATE, YDCPG_OPTS&
&, YDMF_PHYS, YDMODEL, YDCPG_BNDS, PFLU_EMIS, PRDG_MU0)
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_EMIS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PRDG_MU0 (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_FRSOPT', 0, ZHOOK_HANDLE)

DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA

  IF (.NOT.YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) THEN
    YDMF_PHYS%OUT%FRTHDS (JLON)=YDMF_PHYS%OUT%FRTH (JLON, YDCPG_OPTS%KFLEVG, 1)/PFLU_EMIS&
    & (JLON)+YDMODEL%YRCST%RSIGMA*YDMF_PHYS_BASE_STATE%YGSP_RR%T (JLON)**4
  ENDIF


  IF (PRDG_MU0 (JLON)<=0.0_JPRB) THEN
    YDMF_PHYS%OUT%FRSOPT (JLON)=0.0_JPRB
  ELSE
    YDMF_PHYS%OUT%FRSOPT (JLON)=YDMODEL%YRML_PHY_MF%YRPHY3%RII0*PRDG_MU0 (JLON)
  ENDIF

ENDDO

IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_FRSOPT', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
