INTERFACE
SUBROUTINE LAITRE_GMV_OPENACC (YDML_DYN, KASLB1, KPROMA, KST, KEND, KFLEV,&
& KFLDN, KFLDX, KWK, LDLIN, LDCOMAD, LDSLHD, LDVWENO, PWENOALPHA, LDMOM, LDQM&
&, LDQMH, KNOWENO, KL0, PLSCAW, PRSCAW, PXSL, POUT, LDADD, YDSTACK)
!$ACC ROUTINE (LAITRE_GMV_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB
USE MODEL_DYNAMICS_MOD,ONLY:MODEL_DYNAMICS_TYPE
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN)::YDML_DYN
INTEGER (KIND=JPIM), INTENT (IN)::KASLB1
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
INTEGER (KIND=JPIM), INTENT (IN)::KFLDN
INTEGER (KIND=JPIM), INTENT (IN)::KFLDX
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KWK
LOGICAL, INTENT (IN)::LDLIN
LOGICAL, INTENT (IN)::LDCOMAD
LOGICAL, INTENT (IN)::LDSLHD
LOGICAL, INTENT (IN)::LDVWENO
REAL (KIND=JPRB), INTENT (IN)::PWENOALPHA
LOGICAL, INTENT (IN)::LDMOM
LOGICAL, INTENT (IN)::LDQM
LOGICAL, INTENT (IN)::LDQMH
LOGICAL, OPTIONAL, INTENT (IN)::LDADD
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
INTEGER (KIND=JPIM), INTENT (IN)::KNOWENO (KPROMA, KFLEV)
INTEGER (KIND=JPIM), INTENT (IN)::KL0 (KPROMA, KFLEV, 0:3)
REAL (KIND=JPRB), INTENT (IN)::PLSCAW (KPROMA, KFLEV, YDML_DYN%YYTLSCAW%NDIM)
REAL (KIND=JPRB), INTENT (IN)::PRSCAW (KPROMA, KFLEV, YDML_DYN%YYTRSCAW%NDIM)
REAL (KIND=JPRB), INTENT (IN)::PXSL (KASLB1, KFLDN:KFLDX)
REAL (KIND=JPRB), INTENT (OUT)::POUT (KPROMA, KFLEV)
END SUBROUTINE LAITRE_GMV_OPENACC


END INTERFACE
