INTERFACE
SUBROUTINE LAITRE_GFL_OPENACC (YDGEOMETRY, YGFL, YDML_DYN, KASLB1, KPROMA&
&, KST, KEND, KFLEV, KFLDN, KFLDX, KHVI, KWK, CDINT, PWENOALPHA, LDMOM&
&, KNOWENO, KL0, PLSCAW, PRSCAW, PXSL, POUT, PXSPSL, YDSTACK)
!$ACC ROUTINE (LAITRE_GFL_OPENACC) SEQ
USE YOM_YGFL,ONLY:TYPE_GFLD
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE MODEL_DYNAMICS_MOD,ONLY:MODEL_DYNAMICS_TYPE
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (TYPE_GFLD), INTENT (IN)::YGFL
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN)::YDML_DYN
INTEGER (KIND=JPIM), INTENT (IN)::KASLB1
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
INTEGER (KIND=JPIM), INTENT (IN)::KFLDN
INTEGER (KIND=JPIM), INTENT (IN)::KFLDX
INTEGER (KIND=JPIM), INTENT (IN)::KHVI
INTEGER (KIND=JPIM), INTENT (IN)::KWK
CHARACTER (LEN=12), INTENT (IN)::CDINT
REAL (KIND=JPRB), INTENT (IN)::PWENOALPHA
LOGICAL, INTENT (IN)::LDMOM
INTEGER (KIND=JPIM), INTENT (IN)::KNOWENO (KPROMA, KFLEV)
INTEGER (KIND=JPIM), INTENT (IN)::KL0 (KPROMA, KFLEV, 0:3)
REAL (KIND=JPRB), INTENT (IN)::PLSCAW (KPROMA, KFLEV, YDML_DYN%YYTLSCAW%NDIM)
REAL (KIND=JPRB), INTENT (IN)::PRSCAW (KPROMA, KFLEV, YDML_DYN%YYTRSCAW%NDIM)
REAL (KIND=JPRB), INTENT (IN)::PXSL (KASLB1, KFLDN:KFLDX)
REAL (KIND=JPRB), INTENT (OUT)::POUT (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN), OPTIONAL::PXSPSL (KASLB1, KFLDN:KFLDX)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
END SUBROUTINE LAITRE_GFL_OPENACC


END INTERFACE
