SUBROUTINE LATTEX_EXPL_2TL_PARALLEL (YDGEOMETRY, YDCPG_BNDS&
&, YDCPG_OPTS, YDML_DYN, YDCPG_SL1, YDVARS, LDCT, LDCTC)

USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MODEL_DYNAMICS_MOD,ONLY:MODEL_DYNAMICS_TYPE
USE CPG_SL1_TYPE_MOD,ONLY:CPG_SL1B_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE PARKIND1
USE FXTRAN_ACDC_ARRAY_COPY_MOD
USE FXTRAN_ACDC_GPUMEM_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE


TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN)::YDML_DYN
TYPE (CPG_SL1B_TYPE), INTENT (INOUT)::YDCPG_SL1
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
LOGICAL, INTENT (IN)::LDCT
LOGICAL, INTENT (IN)::LDCTC
LOGICAL::LLTDIABLIN
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JGFL
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
INTEGER(KIND=JPIM) :: JBLK
TYPE(CPG_BNDS_TYPE) :: YLCPG_BNDS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_FIELD_API
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_PARALLEL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_COMPUTE
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLOFFSET
REAL (KIND=JPRB), POINTER :: Z_YDCPG_SL1_CVGQ_P(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDCPG_SL1_CVGQ_P_F(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDCPG_SL1_GFL_P(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDCPG_SL1_GFL_P_F(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDCPG_SL1_Q_P(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDCPG_SL1_Q_P_F(:,:,:)
REAL(KIND=JPRB), POINTER :: Z_YDVARS_GFL_PTR_T0(:,:,:)
REAL(KIND=JPRB), POINTER :: Z_YDVARS_GFL_PTR_T9(:,:,:)
#include "abor1.intfb.h"
IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL', 0, ZHOOK_HANDLE)

CALL FXTRAN_ACDC_GPUMEMSTAT (__FILE__, __LINE__, "BEGIN")


IF (LHOOK) CALL DR_HOOK ('CREATE_TEMPORARIES',0,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('CREATE_TEMPORARIES',1,ZHOOK_HANDLE_FIELD_API)

IF (LDCT.AND.(.NOT.LDCTC)) THEN

  DO JGFL=1, SIZE (YDCPG_SL1%GFL)

    IF (YDVARS%GFL_PTR (JGFL)%YCOMP%LADV) THEN

      IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0&
        &).AND.(.NOT.YDVARS%GFL_PTR (JGFL)%YCOMP%LTDIABLIN)) THEN
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0',0,ZHOOK_HANDLE_PARALLEL)

        IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','LATTEX_EXPL_2TL_PARALLEL:0')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDONLY (YDCPG_SL1%GFL (JGFL)%F_P_F)
          Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT9)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
          !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF) FIRSTPRIVATE (YLCPG_BNDS)

          DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
            CALL YLCPG_BNDS%UPDATE (JBLK)

            

            DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

              DO JROF=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)+Z_YDCPG_SL1_GFL_P_F&
                &  (JROF, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T9  (JROF, JLEV, JBLK)
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:0')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P_F)
            Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT9)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDCPG_SL1_GFL_P_F => NULL ()
          Z_YDVARS_GFL_PTR_T9 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:0')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDONLY (YDCPG_SL1%GFL (JGFL)%F_P_F)
          Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT9)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF, YLCPG_BNDS)

          DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

            

            

            DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
              YLCPG_BNDS%KIDIA = JROF
              YLCPG_BNDS%KFDIA = JROF

              

              DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
                
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)+Z_YDCPG_SL1_GFL_P_F&
                &  (JROF, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T9  (JROF, JLEV, JBLK)
              
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:0')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P_F)
            Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT9)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDCPG_SL1_GFL_P_F => NULL ()
          Z_YDVARS_GFL_PTR_T9 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:0')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_DEVICE_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDCPG_SL1_GFL_P_F => GET_DEVICE_DATA_RDONLY (YDCPG_SL1%GFL (JGFL)%F_P_F)
          Z_YDVARS_GFL_PTR_T9 => GET_DEVICE_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT9)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          
            !$ACC PARALLEL LOOP GANG &
            !$ACC&PRESENT (YDCPG_OPTS, YDGEOMETRY, YFXTRAN_ACDC_STACK, Z_YDCPG_SL1_GFL_P, &
            !$ACC&         Z_YDCPG_SL1_GFL_P_F, Z_YDVARS_GFL_PTR_T9) &
            !$ACC&PRIVATE (JBLK) &
            !$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON) 
            
            DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
            
            
            
            !$ACC LOOP VECTOR &
            !$ACC&PRIVATE (JLEV, JROF, YLCPG_BNDS) 

            

            DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
              YLCPG_BNDS%KIDIA = JROF
              YLCPG_BNDS%KFDIA = JROF

              

              DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
                
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)+Z_YDCPG_SL1_GFL_P_F&
                &  (JROF, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T9  (JROF, JLEV, JBLK)
              
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:0')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P_F)
            Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT9)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDCPG_SL1_GFL_P_F => NULL ()
          Z_YDVARS_GFL_PTR_T9 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSE
            CALL ABOR1 ('LATTEX_EXPL_2TL_PARALLEL: NOT METHOD WAS FOUND')
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:0',1,ZHOOK_HANDLE_PARALLEL)
      ELSE
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1',0,ZHOOK_HANDLE_PARALLEL)

        IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','LATTEX_EXPL_2TL_PARALLEL:1')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT9)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
          !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF) FIRSTPRIVATE (YLCPG_BNDS)

          DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
            CALL YLCPG_BNDS%UPDATE (JBLK)

            

            DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

              DO JROF=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF&
                &, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T9  (JROF, JLEV, JBLK)
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:1')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT9)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDVARS_GFL_PTR_T9 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:1')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT9)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF, YLCPG_BNDS)

          DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

            

            

            DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
              YLCPG_BNDS%KIDIA = JROF
              YLCPG_BNDS%KFDIA = JROF

              

              DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
                
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF&
                &, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T9  (JROF, JLEV, JBLK)
              
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:1')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT9)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDVARS_GFL_PTR_T9 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:1')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_DEVICE_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDVARS_GFL_PTR_T9 => GET_DEVICE_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT9)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          
            !$ACC PARALLEL LOOP GANG &
            !$ACC&PRESENT (YDCPG_OPTS, YDGEOMETRY, YFXTRAN_ACDC_STACK, Z_YDCPG_SL1_GFL_P, &
            !$ACC&         Z_YDVARS_GFL_PTR_T9) &
            !$ACC&PRIVATE (JBLK) &
            !$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON) 
            
            DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
            
            
            
            !$ACC LOOP VECTOR &
            !$ACC&PRIVATE (JLEV, JROF, YLCPG_BNDS) 

            

            DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
              YLCPG_BNDS%KIDIA = JROF
              YLCPG_BNDS%KFDIA = JROF

              

              DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
                
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF&
                &, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T9  (JROF, JLEV, JBLK)
              
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:1')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDVARS_GFL_PTR_T9 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT9)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDVARS_GFL_PTR_T9 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSE
            CALL ABOR1 ('LATTEX_EXPL_2TL_PARALLEL: NOT METHOD WAS FOUND')
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:1',1,ZHOOK_HANDLE_PARALLEL)
      ENDIF

    ENDIF

  ENDDO

ELSEIF (.NOT.LDCT) THEN

  DO JGFL=1, SIZE (YDCPG_SL1%GFL)

    IF (YDVARS%GFL_PTR (JGFL)%YCOMP%LADV) THEN

      IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0&
        &).AND.(.NOT.YDVARS%GFL_PTR (JGFL)%YCOMP%LTDIABLIN)) THEN
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2',0,ZHOOK_HANDLE_PARALLEL)

        IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','LATTEX_EXPL_2TL_PARALLEL:2')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDONLY (YDCPG_SL1%GFL (JGFL)%F_P_F)
          Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT0)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
          !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF) FIRSTPRIVATE (YLCPG_BNDS)

          DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
            CALL YLCPG_BNDS%UPDATE (JBLK)

            

            DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

              DO JROF=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)+Z_YDCPG_SL1_GFL_P_F&
                &  (JROF, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T0  (JROF, JLEV, JBLK)
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:2')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P_F)
            Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT0)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDCPG_SL1_GFL_P_F => NULL ()
          Z_YDVARS_GFL_PTR_T0 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:2')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDONLY (YDCPG_SL1%GFL (JGFL)%F_P_F)
          Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT0)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF, YLCPG_BNDS)

          DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

            

            

            DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
              YLCPG_BNDS%KIDIA = JROF
              YLCPG_BNDS%KFDIA = JROF

              

              DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
                
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)+Z_YDCPG_SL1_GFL_P_F&
                &  (JROF, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T0  (JROF, JLEV, JBLK)
              
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:2')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P_F)
            Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT0)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDCPG_SL1_GFL_P_F => NULL ()
          Z_YDVARS_GFL_PTR_T0 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:2')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_DEVICE_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDCPG_SL1_GFL_P_F => GET_DEVICE_DATA_RDONLY (YDCPG_SL1%GFL (JGFL)%F_P_F)
          Z_YDVARS_GFL_PTR_T0 => GET_DEVICE_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT0)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          
            !$ACC PARALLEL LOOP GANG &
            !$ACC&PRESENT (YDCPG_OPTS, YDGEOMETRY, YFXTRAN_ACDC_STACK, Z_YDCPG_SL1_GFL_P, &
            !$ACC&         Z_YDCPG_SL1_GFL_P_F, Z_YDVARS_GFL_PTR_T0) &
            !$ACC&PRIVATE (JBLK) &
            !$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON) 
            
            DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
            
            
            
            !$ACC LOOP VECTOR &
            !$ACC&PRIVATE (JLEV, JROF, YLCPG_BNDS) 

            

            DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
              YLCPG_BNDS%KIDIA = JROF
              YLCPG_BNDS%KFDIA = JROF

              

              DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
                
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)+Z_YDCPG_SL1_GFL_P_F&
                &  (JROF, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T0  (JROF, JLEV, JBLK)
              
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:2')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDCPG_SL1_GFL_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P_F)
            Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT0)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDCPG_SL1_GFL_P_F => NULL ()
          Z_YDVARS_GFL_PTR_T0 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSE
            CALL ABOR1 ('LATTEX_EXPL_2TL_PARALLEL: NOT METHOD WAS FOUND')
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:2',1,ZHOOK_HANDLE_PARALLEL)
      ELSE
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3',0,ZHOOK_HANDLE_PARALLEL)

        IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','LATTEX_EXPL_2TL_PARALLEL:3')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT0)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
          !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF) FIRSTPRIVATE (YLCPG_BNDS)

          DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
            CALL YLCPG_BNDS%UPDATE (JBLK)

            

            DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

              DO JROF=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF&
                &, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T0  (JROF, JLEV, JBLK)
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:3')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT0)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDVARS_GFL_PTR_T0 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:3')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT0)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF, YLCPG_BNDS)

          DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

            

            

            DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
              YLCPG_BNDS%KIDIA = JROF
              YLCPG_BNDS%KFDIA = JROF

              

              DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
                
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF&
                &, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T0  (JROF, JLEV, JBLK)
              
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:3')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT0)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDVARS_GFL_PTR_T0 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:3')) THEN
          
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => GET_DEVICE_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
          Z_YDVARS_GFL_PTR_T0 => GET_DEVICE_DATA_RDONLY (YDVARS%GFL_PTR (JGFL)%FT0)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
          
          
            !$ACC PARALLEL LOOP GANG &
            !$ACC&PRESENT (YDCPG_OPTS, YDGEOMETRY, YFXTRAN_ACDC_STACK, Z_YDCPG_SL1_GFL_P, &
            !$ACC&         Z_YDVARS_GFL_PTR_T0) &
            !$ACC&PRIVATE (JBLK) &
            !$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON) 
            
            DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
            
            
            
            !$ACC LOOP VECTOR &
            !$ACC&PRIVATE (JLEV, JROF, YLCPG_BNDS) 

            

            DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
              YLCPG_BNDS%KIDIA = JROF
              YLCPG_BNDS%KFDIA = JROF

              

              DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
                
                Z_YDCPG_SL1_GFL_P  (JROF, JLEV, JBLK)=Z_YDCPG_SL1_GFL_P  (JROF&
                &, JLEV, JBLK)+Z_YDVARS_GFL_PTR_T0  (JROF, JLEV, JBLK)
              
              ENDDO

            ENDDO

          ENDDO

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

          IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:3')) THEN
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
            Z_YDCPG_SL1_GFL_P => GET_HOST_DATA_RDWR (YDCPG_SL1%GFL (JGFL)%F_P)
            Z_YDVARS_GFL_PTR_T0 => GET_HOST_DATA_RDWR (YDVARS%GFL_PTR (JGFL)%FT0)
            IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
            
            
          ENDIF

          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
          Z_YDCPG_SL1_GFL_P => NULL ()
          Z_YDVARS_GFL_PTR_T0 => NULL ()
          IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ELSE
            CALL ABOR1 ('LATTEX_EXPL_2TL_PARALLEL: NOT METHOD WAS FOUND')
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:3',1,ZHOOK_HANDLE_PARALLEL)
      ENDIF

    ENDIF

  ENDDO

ENDIF


IF (YDVARS%CVGQ%YCOMP%LGP.AND.(.NOT.LDCTC)) THEN
  LLTDIABLIN=YDVARS%CVGQ%YCOMP%LTDIABLIN

  IF ((YDML_DYN%YRDYN%NSPLTHOI/=0).OR.LLTDIABLIN) THEN
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4',0,ZHOOK_HANDLE_PARALLEL)

    IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','LATTEX_EXPL_2TL_PARALLEL:4')) THEN
      
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P_F)
      Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDONLY (YDCPG_SL1%Q%F_P_F)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
      
      CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
      !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF) FIRSTPRIVATE (YLCPG_BNDS)

      DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
        CALL YLCPG_BNDS%UPDATE (JBLK)

        

        DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

          DO JROF=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA
            Z_YDCPG_SL1_CVGQ_P_F (JROF, JLEV, JBLK)=Z_YDCPG_SL1_Q_P_F (JROF, JLEV, JBLK)
          ENDDO

        ENDDO

      ENDDO

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

      IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:4')) THEN
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
        Z_YDCPG_SL1_CVGQ_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P_F)
        Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%Q%F_P_F)
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P_F => NULL ()
      Z_YDCPG_SL1_Q_P_F => NULL ()
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:4')) THEN
      
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P_F)
      Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDONLY (YDCPG_SL1%Q%F_P_F)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
      
      !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF, YLCPG_BNDS)

      DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

        

        

        DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
          YLCPG_BNDS%KIDIA = JROF
          YLCPG_BNDS%KFDIA = JROF

          

          DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
            
            Z_YDCPG_SL1_CVGQ_P_F (JROF, JLEV, JBLK)=Z_YDCPG_SL1_Q_P_F (JROF, JLEV, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

      IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:4')) THEN
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
        Z_YDCPG_SL1_CVGQ_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P_F)
        Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%Q%F_P_F)
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P_F => NULL ()
      Z_YDCPG_SL1_Q_P_F => NULL ()
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:4')) THEN
      
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P_F => GET_DEVICE_DATA_RDWR (YDCPG_SL1%CVGQ%F_P_F)
      Z_YDCPG_SL1_Q_P_F => GET_DEVICE_DATA_RDONLY (YDCPG_SL1%Q%F_P_F)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
      
      
        !$ACC PARALLEL LOOP GANG &
        !$ACC&PRESENT (YDCPG_OPTS, YDGEOMETRY, YFXTRAN_ACDC_STACK, Z_YDCPG_SL1_CVGQ_P_F, &
        !$ACC&         Z_YDCPG_SL1_Q_P_F) &
        !$ACC&PRIVATE (JBLK) &
        !$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON) 
        
        DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
        
        
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JLEV, JROF, YLCPG_BNDS) 

        

        DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
          YLCPG_BNDS%KIDIA = JROF
          YLCPG_BNDS%KFDIA = JROF

          

          DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
            
            Z_YDCPG_SL1_CVGQ_P_F (JROF, JLEV, JBLK)=Z_YDCPG_SL1_Q_P_F (JROF, JLEV, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

      IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:4')) THEN
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
        Z_YDCPG_SL1_CVGQ_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P_F)
        Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%Q%F_P_F)
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P_F => NULL ()
      Z_YDCPG_SL1_Q_P_F => NULL ()
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ELSE
        CALL ABOR1 ('LATTEX_EXPL_2TL_PARALLEL: NOT METHOD WAS FOUND')
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:4',1,ZHOOK_HANDLE_PARALLEL)
  ENDIF

  IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5',0,ZHOOK_HANDLE_PARALLEL)

  IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','LATTEX_EXPL_2TL_PARALLEL:5')) THEN
    
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
    Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
    Z_YDCPG_SL1_Q_P => GET_HOST_DATA_RDONLY (YDCPG_SL1%Q%F_P)
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
    
    CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
    !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF) FIRSTPRIVATE (YLCPG_BNDS)

    DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
      CALL YLCPG_BNDS%UPDATE (JBLK)

      

      DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

        DO JROF=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA
          Z_YDCPG_SL1_CVGQ_P (JROF, JLEV, JBLK)=Z_YDCPG_SL1_Q_P (JROF, JLEV, JBLK)
        ENDDO

      ENDDO

    ENDDO

    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

    IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:5')) THEN
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
      Z_YDCPG_SL1_Q_P => GET_HOST_DATA_RDWR (YDCPG_SL1%Q%F_P)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
    Z_YDCPG_SL1_CVGQ_P => NULL ()
    Z_YDCPG_SL1_Q_P => NULL ()
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:5')) THEN
    
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
    Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
    Z_YDCPG_SL1_Q_P => GET_HOST_DATA_RDONLY (YDCPG_SL1%Q%F_P)
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
    
    !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF, YLCPG_BNDS)

    DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

      

      

      DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JROF
        YLCPG_BNDS%KFDIA = JROF

        

        DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
          
          Z_YDCPG_SL1_CVGQ_P (JROF, JLEV, JBLK)=Z_YDCPG_SL1_Q_P (JROF, JLEV, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

    IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:5')) THEN
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
      Z_YDCPG_SL1_Q_P => GET_HOST_DATA_RDWR (YDCPG_SL1%Q%F_P)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
    Z_YDCPG_SL1_CVGQ_P => NULL ()
    Z_YDCPG_SL1_Q_P => NULL ()
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:5')) THEN
    
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
    Z_YDCPG_SL1_CVGQ_P => GET_DEVICE_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
    Z_YDCPG_SL1_Q_P => GET_DEVICE_DATA_RDONLY (YDCPG_SL1%Q%F_P)
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
    
    
      !$ACC PARALLEL LOOP GANG &
      !$ACC&PRESENT (YDCPG_OPTS, YDGEOMETRY, YFXTRAN_ACDC_STACK, Z_YDCPG_SL1_CVGQ_P, &
      !$ACC&         Z_YDCPG_SL1_Q_P) &
      !$ACC&PRIVATE (JBLK) &
      !$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON) 
      
      DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
      
      
      
      !$ACC LOOP VECTOR &
      !$ACC&PRIVATE (JLEV, JROF, YLCPG_BNDS) 

      

      DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JROF
        YLCPG_BNDS%KFDIA = JROF

        

        DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
          
          Z_YDCPG_SL1_CVGQ_P (JROF, JLEV, JBLK)=Z_YDCPG_SL1_Q_P (JROF, JLEV, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

    IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:5')) THEN
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
      Z_YDCPG_SL1_Q_P => GET_HOST_DATA_RDWR (YDCPG_SL1%Q%F_P)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
    Z_YDCPG_SL1_CVGQ_P => NULL ()
    Z_YDCPG_SL1_Q_P => NULL ()
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ELSE
      CALL ABOR1 ('LATTEX_EXPL_2TL_PARALLEL: NOT METHOD WAS FOUND')
  ENDIF

  IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:5',1,ZHOOK_HANDLE_PARALLEL)
  LLTDIABLIN=YDVARS%CVGQ%YCOMP%LTDIABLIN.AND.YDVARS%Q%YCOMP%LTDIABLIN

  IF ((YDML_DYN%YRDYN%NSPLTHOI==0).AND.LLTDIABLIN) THEN
    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6',0,ZHOOK_HANDLE_PARALLEL)

    IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','LATTEX_EXPL_2TL_PARALLEL:6')) THEN
      
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
      Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDONLY (YDCPG_SL1%Q%F_P_F)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
      
      CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
      !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF) FIRSTPRIVATE (YLCPG_BNDS)

      DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
        CALL YLCPG_BNDS%UPDATE (JBLK)

        

        DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

          DO JROF=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA
            Z_YDCPG_SL1_CVGQ_P (JROF, JLEV, JBLK)=Z_YDCPG_SL1_CVGQ_P (JROF&
            &, JLEV, JBLK)+Z_YDCPG_SL1_Q_P_F (JROF, JLEV, JBLK)
          ENDDO

        ENDDO

      ENDDO

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

      IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:6')) THEN
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
        Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
        Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%Q%F_P_F)
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P => NULL ()
      Z_YDCPG_SL1_Q_P_F => NULL ()
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:6')) THEN
      
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
      Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDONLY (YDCPG_SL1%Q%F_P_F)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
      
      !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JROF, YLCPG_BNDS)

      DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

        

        

        DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
          YLCPG_BNDS%KIDIA = JROF
          YLCPG_BNDS%KFDIA = JROF

          

          DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
            
            Z_YDCPG_SL1_CVGQ_P (JROF, JLEV, JBLK)=Z_YDCPG_SL1_CVGQ_P (JROF&
            &, JLEV, JBLK)+Z_YDCPG_SL1_Q_P_F (JROF, JLEV, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

      IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:6')) THEN
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
        Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
        Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%Q%F_P_F)
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P => NULL ()
      Z_YDCPG_SL1_Q_P_F => NULL ()
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN','LATTEX_EXPL_2TL_PARALLEL:6')) THEN
      
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P => GET_DEVICE_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
      Z_YDCPG_SL1_Q_P_F => GET_DEVICE_DATA_RDONLY (YDCPG_SL1%Q%F_P_F)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
      
      
        !$ACC PARALLEL LOOP GANG &
        !$ACC&PRESENT (YDCPG_OPTS, YDGEOMETRY, YFXTRAN_ACDC_STACK, Z_YDCPG_SL1_CVGQ_P, &
        !$ACC&         Z_YDCPG_SL1_Q_P_F) &
        !$ACC&PRIVATE (JBLK) &
        !$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON) 
        
        DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
        
        
        
        !$ACC LOOP VECTOR &
        !$ACC&PRIVATE (JLEV, JROF, YLCPG_BNDS) 

        

        DO JROF = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
          YLCPG_BNDS%KIDIA = JROF
          YLCPG_BNDS%KFDIA = JROF

          

          DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
            
            Z_YDCPG_SL1_CVGQ_P (JROF, JLEV, JBLK)=Z_YDCPG_SL1_CVGQ_P (JROF&
            &, JLEV, JBLK)+Z_YDCPG_SL1_Q_P_F (JROF, JLEV, JBLK)
          
          ENDDO

        ENDDO

      ENDDO

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

      IF (FXTRAN_ACDC_LSYNCHOST ('LATTEX_EXPL_2TL_PARALLEL:6')) THEN
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
        Z_YDCPG_SL1_CVGQ_P => GET_HOST_DATA_RDWR (YDCPG_SL1%CVGQ%F_P)
        Z_YDCPG_SL1_Q_P_F => GET_HOST_DATA_RDWR (YDCPG_SL1%Q%F_P_F)
        IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
      Z_YDCPG_SL1_CVGQ_P => NULL ()
      Z_YDCPG_SL1_Q_P_F => NULL ()
      IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ELSE
        CALL ABOR1 ('LATTEX_EXPL_2TL_PARALLEL: NOT METHOD WAS FOUND')
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL:6',1,ZHOOK_HANDLE_PARALLEL)
  ENDIF

ENDIF


CALL FXTRAN_ACDC_GPUMEMSTAT (__FILE__, __LINE__, "END")

IF (LHOOK) CALL DR_HOOK ('DELETE_TEMPORARIES',0,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('DELETE_TEMPORARIES',1,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_2TL_PARALLEL', 1, ZHOOK_HANDLE)
END SUBROUTINE LATTEX_EXPL_2TL_PARALLEL
