MODULE UTIL_TYPE_SFL_CANRI_MOD

USE SURFACE_FIELDS_MIX, ONLY : TYPE_SFL_CANRI

INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_SFL_CANRI
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_SFL_CANRI
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TYPE_SFL_CANRI
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TYPE_SFL_CANRI
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TYPE_SFL_CANRI
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TYPE_SFL_CANRI
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TYPE_SFL_CANRI (SELF, KLUN)
USE UTIL_TYPE_SURF_MTL_2D_MOD
IMPLICIT NONE
TYPE (TYPE_SFL_CANRI), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: J1
LOGICAL :: LYCI
LYCI = ASSOCIATED (SELF%YCI)
WRITE (KLUN) LYCI
IF (LYCI) THEN
  WRITE (KLUN) LBOUND (SELF%YCI)
  WRITE (KLUN) UBOUND (SELF%YCI)
  DO J1 = LBOUND (SELF%YCI, 1), UBOUND (SELF%YCI, 1)
    CALL SAVE_TYPE_SURF_MTL_2D (SELF%YCI (J1), KLUN)
  ENDDO
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TYPE_SFL_CANRI (SELF, KLUN)
USE UTIL_TYPE_SURF_MTL_2D_MOD

IMPLICIT NONE
TYPE (TYPE_SFL_CANRI), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYCI
READ (KLUN) LYCI
IF (LYCI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%YCI (IL1(1):IU1(1)))
  DO J1 = LBOUND (SELF%YCI, 1), UBOUND (SELF%YCI, 1)
    CALL LOAD_TYPE_SURF_MTL_2D (SELF%YCI (J1), KLUN)
  ENDDO
ELSE
  NULLIFY (SELF%YCI)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TYPE_SFL_CANRI (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TYPE_SURF_MTL_2D_MOD
IMPLICIT NONE
TYPE (TYPE_SFL_CANRI), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LYCI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LYCI = ASSOCIATED (SELF%YCI)
IF (LYCI) THEN
  !$ACC ENTER DATA CREATE (SELF%YCI)
  !$ACC UPDATE DEVICE (SELF%YCI)
  DO J1 = LBOUND (SELF%YCI, 1), UBOUND (SELF%YCI, 1)
    CALL COPY_TYPE_SURF_MTL_2D (SELF%YCI (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%YCI)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TYPE_SFL_CANRI (SELF)
USE UTIL_TYPE_SURF_MTL_2D_MOD

IMPLICIT NONE
TYPE (TYPE_SFL_CANRI), TARGET :: SELF
INTEGER :: J1
LOGICAL :: LYCI
LYCI = ASSOCIATED (SELF%YCI)
IF (LYCI) THEN
  DO J1 = LBOUND (SELF%YCI, 1), UBOUND (SELF%YCI, 1)
    CALL HOST_TYPE_SURF_MTL_2D (SELF%YCI (J1))
  ENDDO
ENDIF

END SUBROUTINE

     

SUBROUTINE CRC64_TYPE_SFL_CANRI (SELF, KLUN, CDPATH)
USE UTIL_TYPE_SURF_MTL_2D_MOD
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TYPE_SFL_CANRI), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
INTEGER :: J1
LOGICAL :: LYCI
LYCI = ASSOCIATED (SELF%YCI)
IF (LYCI) THEN
  DO J1 = LBOUND (SELF%YCI, 1), UBOUND (SELF%YCI, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL CRC64_TYPE_SURF_MTL_2D (SELF%YCI (J1), KLUN, CDPATH//'%YCI'//TRIM(CLIND))
  ENDDO
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TYPE_SFL_CANRI (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TYPE_SURF_MTL_2D_MOD
IMPLICIT NONE
TYPE (TYPE_SFL_CANRI), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LYCI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LYCI = ASSOCIATED (SELF%YCI)
IF (LYCI) THEN
  !$ACC EXIT DATA DETACH (SELF%YCI)
  DO J1 = LBOUND (SELF%YCI, 1), UBOUND (SELF%YCI, 1)
    CALL WIPE_TYPE_SURF_MTL_2D (SELF%YCI (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (SELF%YCI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
