MODULE UTIL_TNORGWD_MOD

USE YOMNORGWD, ONLY : TNORGWD

INTERFACE SAVE
MODULE PROCEDURE SAVE_TNORGWD
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TNORGWD
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TNORGWD
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TNORGWD
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TNORGWD
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TNORGWD
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TNORGWD
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TNORGWD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TNORGWD), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NORGWD_SCHEME
WRITE (KLUN) YD%NORGWD_PRMAX
WRITE (KLUN) YD%NORGWD_DZ
WRITE (KLUN) YD%NORGWD_PTROPO
WRITE (KLUN) YD%NORGWD_NTROPO
WRITE (KLUN) YD%NORGWD_RUWMAX
WRITE (KLUN) YD%NORGWD_SAT
WRITE (KLUN) YD%NORGWD_RDISS
WRITE (KLUN) YD%NORGWD_DELTAT
WRITE (KLUN) YD%NORGWD_KMIN
WRITE (KLUN) YD%NORGWD_KMAX
WRITE (KLUN) YD%NORGWD_CMIN
WRITE (KLUN) YD%NORGWD_CMAX
WRITE (KLUN) YD%NORGWD_PLAUNCH
WRITE (KLUN) YD%NORGWD_NLAUNCH
WRITE (KLUN) YD%NORGWD_PNOVERDIF
WRITE (KLUN) YD%NORGWD_NNOVERDIF
WRITE (KLUN) YD%NORGWD_DZFRON
WRITE (KLUN) YD%NORGWD_GFRON
WRITE (KLUN) YD%NORGWD_GB
END SUBROUTINE

SUBROUTINE LOAD_TNORGWD (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TNORGWD), INTENT (OUT), TARGET :: YD
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) YD%NORGWD_SCHEME
READ (KLUN) ZTMP0
YD%NORGWD_PRMAX = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_DZ = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_PTROPO = ZTMP0
READ (KLUN) YD%NORGWD_NTROPO
READ (KLUN) ZTMP0
YD%NORGWD_RUWMAX = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_SAT = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_RDISS = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_DELTAT = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_KMIN = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_KMAX = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_CMIN = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_CMAX = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_PLAUNCH = ZTMP0
READ (KLUN) YD%NORGWD_NLAUNCH
READ (KLUN) ZTMP0
YD%NORGWD_PNOVERDIF = ZTMP0
READ (KLUN) YD%NORGWD_NNOVERDIF
READ (KLUN) ZTMP0
YD%NORGWD_DZFRON = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_GFRON = ZTMP0
READ (KLUN) ZTMP0
YD%NORGWD_GB = ZTMP0
END SUBROUTINE


SUBROUTINE COPY_TNORGWD (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TNORGWD), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF




















END SUBROUTINE

SUBROUTINE HOST_TNORGWD (YD)

IMPLICIT NONE
TYPE (TNORGWD), TARGET :: YD





















END SUBROUTINE

     

SUBROUTINE CRC64_TNORGWD (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TNORGWD), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_SCHEME), CDPATH//'%NORGWD_SCHEME'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_PRMAX), CDPATH//'%NORGWD_PRMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_DZ), CDPATH//'%NORGWD_DZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_PTROPO), CDPATH//'%NORGWD_PTROPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_NTROPO), CDPATH//'%NORGWD_NTROPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_RUWMAX), CDPATH//'%NORGWD_RUWMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_SAT), CDPATH//'%NORGWD_SAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_RDISS), CDPATH//'%NORGWD_RDISS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_DELTAT), CDPATH//'%NORGWD_DELTAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_KMIN), CDPATH//'%NORGWD_KMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_KMAX), CDPATH//'%NORGWD_KMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_CMIN), CDPATH//'%NORGWD_CMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_CMAX), CDPATH//'%NORGWD_CMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_PLAUNCH), CDPATH//'%NORGWD_PLAUNCH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_NLAUNCH), CDPATH//'%NORGWD_NLAUNCH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_PNOVERDIF), CDPATH//'%NORGWD_PNOVERDIF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_NNOVERDIF), CDPATH//'%NORGWD_NNOVERDIF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_DZFRON), CDPATH//'%NORGWD_DZFRON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_GFRON), CDPATH//'%NORGWD_GFRON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NORGWD_GB), CDPATH//'%NORGWD_GB'

END SUBROUTINE

SUBROUTINE WIPE_TNORGWD (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TNORGWD), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF




















LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TNORGWD (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TNORGWD),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%NORGWD_SCHEME) * LEN (YD%NORGWD_SCHEME)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_SCHEME'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_PRMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_PRMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_DZ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_DZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_PTROPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_PTROPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_NTROPO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_NTROPO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_RUWMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_RUWMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_SAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_SAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_RDISS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_RDISS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_DELTAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_DELTAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_KMIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_KMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_KMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_KMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_CMIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_CMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_CMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_CMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_PLAUNCH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_PLAUNCH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_NLAUNCH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_NLAUNCH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_PNOVERDIF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_PNOVERDIF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_NNOVERDIF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_NNOVERDIF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_DZFRON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_DZFRON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_GFRON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_GFRON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NORGWD_GB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORGWD_GB'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
