MODULE UTIL_CPG_RCP_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_RCP_TYPE



INTERFACE COPY
MODULE PROCEDURE COPY_CPG_RCP_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_CPG_RCP_TYPE
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_RCP_TYPE
END INTERFACE



CONTAINS





SUBROUTINE COPY_CPG_RCP_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (CPG_RCP_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_CP, LF_DATA, LF_KAP, LF_R, LZDATA, LZVIEW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LZVIEW = ASSOCIATED (SELF%ZVIEW)
IF (LZVIEW) THEN
  !$ACC ENTER DATA CREATE (SELF%ZVIEW)
  !$ACC UPDATE DEVICE (SELF%ZVIEW)
  !$ACC ENTER DATA ATTACH (SELF%ZVIEW)
ENDIF

LZDATA = ASSOCIATED (SELF%ZDATA)
IF (LZDATA) THEN
  !$ACC ENTER DATA CREATE (SELF%ZDATA)
  !$ACC UPDATE DEVICE (SELF%ZDATA)
  !$ACC ENTER DATA ATTACH (SELF%ZDATA)
ENDIF

LF_DATA = ASSOCIATED (SELF%F_DATA)
IF (LF_DATA .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_4RB (SELF%F_DATA)
  !$ACC ENTER DATA ATTACH (SELF%F_DATA)
ENDIF

LF_CP = ASSOCIATED (SELF%F_CP)
IF (LF_CP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_CP)
  !$ACC ENTER DATA ATTACH (SELF%F_CP)
ENDIF

LF_R = ASSOCIATED (SELF%F_R)
IF (LF_R .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_R)
  !$ACC ENTER DATA ATTACH (SELF%F_R)
ENDIF

LF_KAP = ASSOCIATED (SELF%F_KAP)
IF (LF_KAP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_KAP)
  !$ACC ENTER DATA ATTACH (SELF%F_KAP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_CPG_RCP_TYPE (SELF)
USE FIELD_UTIL_MODULE

IMPLICIT NONE
TYPE (CPG_RCP_TYPE), TARGET :: SELF
LOGICAL :: LF_CP, LF_DATA, LF_KAP, LF_R, LZDATA, LZVIEW

LF_DATA = ASSOCIATED (SELF%F_DATA)
IF (LF_DATA) THEN
  CALL HOST_FIELD_4RB (SELF%F_DATA)
ENDIF

LF_CP = ASSOCIATED (SELF%F_CP)
IF (LF_CP) THEN
  CALL HOST_FIELD_3RB (SELF%F_CP)
ENDIF

LF_R = ASSOCIATED (SELF%F_R)
IF (LF_R) THEN
  CALL HOST_FIELD_3RB (SELF%F_R)
ENDIF

LF_KAP = ASSOCIATED (SELF%F_KAP)
IF (LF_KAP) THEN
  CALL HOST_FIELD_3RB (SELF%F_KAP)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_CPG_RCP_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (CPG_RCP_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_CP, LF_DATA, LF_KAP, LF_R, LZDATA, LZVIEW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LZVIEW = ASSOCIATED (SELF%ZVIEW)
IF (LZVIEW) THEN
  !$ACC EXIT DATA DETACH (SELF%ZVIEW)
  !$ACC EXIT DATA DETACH (SELF%ZVIEW)
ENDIF

LZDATA = ASSOCIATED (SELF%ZDATA)
IF (LZDATA) THEN
  !$ACC EXIT DATA DETACH (SELF%ZDATA)
  !$ACC EXIT DATA DETACH (SELF%ZDATA)
ENDIF

LF_DATA = ASSOCIATED (SELF%F_DATA)
IF (LF_DATA .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (SELF%F_DATA)
ENDIF

LF_CP = ASSOCIATED (SELF%F_CP)
IF (LF_CP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_CP)
ENDIF

LF_R = ASSOCIATED (SELF%F_R)
IF (LF_R .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_R)
ENDIF

LF_KAP = ASSOCIATED (SELF%F_KAP)
IF (LF_KAP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_KAP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
