MODULE UTIL_SURFACE_VIEW_GROUP_RESVR_MOD

USE SURFACE_VIEWS_PROGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_RESVR



INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VIEW_GROUP_RESVR
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_SURFACE_VIEW_GROUP_RESVR
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VIEW_GROUP_RESVR
END INTERFACE



CONTAINS





SUBROUTINE COPY_SURFACE_VIEW_GROUP_RESVR (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_RESVR_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_RESVR), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_FC_T0, LF_FC_T1, LF_FC_T9, LF_FP1_T0, LF_FP1_T1, LF_FP1_T9, LF_GROUP, LF_IC_T0, LF_IC_T1, LF_IC_T9
LOGICAL :: LF_T_T0, LF_T_T1, LF_T_T9, LF_W_T0, LF_W_T1, LF_W_T9, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC ENTER DATA CREATE (YD%VARIABLE_GROUP)
  !$ACC UPDATE DEVICE (YD%VARIABLE_GROUP)
  CALL COPY_SURFACE_VARIABLE_GROUP_RESVR (YD%VARIABLE_GROUP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%VARIABLE_GROUP)
ENDIF

LF_T_T0 = ASSOCIATED (YD%F_T_T0)
IF (LF_T_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_T_T0)
  !$ACC ENTER DATA ATTACH (YD%F_T_T0)
ENDIF

LF_T_T1 = ASSOCIATED (YD%F_T_T1)
IF (LF_T_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_T_T1)
  !$ACC ENTER DATA ATTACH (YD%F_T_T1)
ENDIF

LF_T_T9 = ASSOCIATED (YD%F_T_T9)
IF (LF_T_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_T_T9)
  !$ACC ENTER DATA ATTACH (YD%F_T_T9)
ENDIF

LF_W_T0 = ASSOCIATED (YD%F_W_T0)
IF (LF_W_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_W_T0)
  !$ACC ENTER DATA ATTACH (YD%F_W_T0)
ENDIF

LF_W_T1 = ASSOCIATED (YD%F_W_T1)
IF (LF_W_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_W_T1)
  !$ACC ENTER DATA ATTACH (YD%F_W_T1)
ENDIF

LF_W_T9 = ASSOCIATED (YD%F_W_T9)
IF (LF_W_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_W_T9)
  !$ACC ENTER DATA ATTACH (YD%F_W_T9)
ENDIF

LF_FC_T0 = ASSOCIATED (YD%F_FC_T0)
IF (LF_FC_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_FC_T0)
  !$ACC ENTER DATA ATTACH (YD%F_FC_T0)
ENDIF

LF_FC_T1 = ASSOCIATED (YD%F_FC_T1)
IF (LF_FC_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_FC_T1)
  !$ACC ENTER DATA ATTACH (YD%F_FC_T1)
ENDIF

LF_FC_T9 = ASSOCIATED (YD%F_FC_T9)
IF (LF_FC_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_FC_T9)
  !$ACC ENTER DATA ATTACH (YD%F_FC_T9)
ENDIF

LF_IC_T0 = ASSOCIATED (YD%F_IC_T0)
IF (LF_IC_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_IC_T0)
  !$ACC ENTER DATA ATTACH (YD%F_IC_T0)
ENDIF

LF_IC_T1 = ASSOCIATED (YD%F_IC_T1)
IF (LF_IC_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_IC_T1)
  !$ACC ENTER DATA ATTACH (YD%F_IC_T1)
ENDIF

LF_IC_T9 = ASSOCIATED (YD%F_IC_T9)
IF (LF_IC_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_IC_T9)
  !$ACC ENTER DATA ATTACH (YD%F_IC_T9)
ENDIF

LF_FP1_T0 = ASSOCIATED (YD%F_FP1_T0)
IF (LF_FP1_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_FP1_T0)
  !$ACC ENTER DATA ATTACH (YD%F_FP1_T0)
ENDIF

LF_FP1_T1 = ASSOCIATED (YD%F_FP1_T1)
IF (LF_FP1_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_FP1_T1)
  !$ACC ENTER DATA ATTACH (YD%F_FP1_T1)
ENDIF

LF_FP1_T9 = ASSOCIATED (YD%F_FP1_T9)
IF (LF_FP1_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_FP1_T9)
  !$ACC ENTER DATA ATTACH (YD%F_FP1_T9)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_GROUP)
  !$ACC ENTER DATA ATTACH (YD%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_SURFACE_VIEW_GROUP_RESVR (YD)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_RESVR_MOD

IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_RESVR), TARGET :: YD
LOGICAL :: LF_FC_T0, LF_FC_T1, LF_FC_T9, LF_FP1_T0, LF_FP1_T1, LF_FP1_T9, LF_GROUP, LF_IC_T0, LF_IC_T1, LF_IC_T9
LOGICAL :: LF_T_T0, LF_T_T1, LF_T_T9, LF_W_T0, LF_W_T1, LF_W_T9, LVARIABLE_GROUP
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  CALL HOST_SURFACE_VARIABLE_GROUP_RESVR (YD%VARIABLE_GROUP)
ENDIF

LF_T_T0 = ASSOCIATED (YD%F_T_T0)
IF (LF_T_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_T_T0)
ENDIF

LF_T_T1 = ASSOCIATED (YD%F_T_T1)
IF (LF_T_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_T_T1)
ENDIF

LF_T_T9 = ASSOCIATED (YD%F_T_T9)
IF (LF_T_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_T_T9)
ENDIF

LF_W_T0 = ASSOCIATED (YD%F_W_T0)
IF (LF_W_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_W_T0)
ENDIF

LF_W_T1 = ASSOCIATED (YD%F_W_T1)
IF (LF_W_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_W_T1)
ENDIF

LF_W_T9 = ASSOCIATED (YD%F_W_T9)
IF (LF_W_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_W_T9)
ENDIF

LF_FC_T0 = ASSOCIATED (YD%F_FC_T0)
IF (LF_FC_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_FC_T0)
ENDIF

LF_FC_T1 = ASSOCIATED (YD%F_FC_T1)
IF (LF_FC_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_FC_T1)
ENDIF

LF_FC_T9 = ASSOCIATED (YD%F_FC_T9)
IF (LF_FC_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_FC_T9)
ENDIF

LF_IC_T0 = ASSOCIATED (YD%F_IC_T0)
IF (LF_IC_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_IC_T0)
ENDIF

LF_IC_T1 = ASSOCIATED (YD%F_IC_T1)
IF (LF_IC_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_IC_T1)
ENDIF

LF_IC_T9 = ASSOCIATED (YD%F_IC_T9)
IF (LF_IC_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_IC_T9)
ENDIF

LF_FP1_T0 = ASSOCIATED (YD%F_FP1_T0)
IF (LF_FP1_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_FP1_T0)
ENDIF

LF_FP1_T1 = ASSOCIATED (YD%F_FP1_T1)
IF (LF_FP1_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_FP1_T1)
ENDIF

LF_FP1_T9 = ASSOCIATED (YD%F_FP1_T9)
IF (LF_FP1_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_FP1_T9)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (YD%F_GROUP)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_SURFACE_VIEW_GROUP_RESVR (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_RESVR_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_RESVR), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_FC_T0, LF_FC_T1, LF_FC_T9, LF_FP1_T0, LF_FP1_T1, LF_FP1_T9, LF_GROUP, LF_IC_T0, LF_IC_T1, LF_IC_T9
LOGICAL :: LF_T_T0, LF_T_T1, LF_T_T9, LF_W_T0, LF_W_T1, LF_W_T9, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
  CALL WIPE_SURFACE_VARIABLE_GROUP_RESVR (YD%VARIABLE_GROUP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
ENDIF

LF_T_T0 = ASSOCIATED (YD%F_T_T0)
IF (LF_T_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_T_T0)
ENDIF

LF_T_T1 = ASSOCIATED (YD%F_T_T1)
IF (LF_T_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_T_T1)
ENDIF

LF_T_T9 = ASSOCIATED (YD%F_T_T9)
IF (LF_T_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_T_T9)
ENDIF

LF_W_T0 = ASSOCIATED (YD%F_W_T0)
IF (LF_W_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_W_T0)
ENDIF

LF_W_T1 = ASSOCIATED (YD%F_W_T1)
IF (LF_W_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_W_T1)
ENDIF

LF_W_T9 = ASSOCIATED (YD%F_W_T9)
IF (LF_W_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_W_T9)
ENDIF

LF_FC_T0 = ASSOCIATED (YD%F_FC_T0)
IF (LF_FC_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_FC_T0)
ENDIF

LF_FC_T1 = ASSOCIATED (YD%F_FC_T1)
IF (LF_FC_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_FC_T1)
ENDIF

LF_FC_T9 = ASSOCIATED (YD%F_FC_T9)
IF (LF_FC_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_FC_T9)
ENDIF

LF_IC_T0 = ASSOCIATED (YD%F_IC_T0)
IF (LF_IC_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_IC_T0)
ENDIF

LF_IC_T1 = ASSOCIATED (YD%F_IC_T1)
IF (LF_IC_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_IC_T1)
ENDIF

LF_IC_T9 = ASSOCIATED (YD%F_IC_T9)
IF (LF_IC_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_IC_T9)
ENDIF

LF_FP1_T0 = ASSOCIATED (YD%F_FP1_T0)
IF (LF_FP1_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_FP1_T0)
ENDIF

LF_FP1_T1 = ASSOCIATED (YD%F_FP1_T1)
IF (LF_FP1_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_FP1_T1)
ENDIF

LF_FP1_T9 = ASSOCIATED (YD%F_FP1_T9)
IF (LF_FP1_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_FP1_T9)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
