MODULE UTIL_TYPE_SFL_VCLIH_MOD

USE SURFACE_FIELDS_MIX, ONLY : TYPE_SFL_VCLIH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_SFL_VCLIH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_SFL_VCLIH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TYPE_SFL_VCLIH
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TYPE_SFL_VCLIH
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TYPE_SFL_VCLIH
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TYPE_SFL_VCLIH
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TYPE_SFL_VCLIH (KLUN, YD)
USE UTIL_TYPE_SURF_MTL_2D_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_SFL_VCLIH), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYBCCH, LYEVA, LYPBLH, LYPCL, LYPCN, LYPSL, LYPSN, LYQSH, LYSCCH, LYSPSH
LOGICAL :: LYTCCH, LYVH
LYTCCH = ASSOCIATED (YD%YTCCH)
WRITE (KLUN) LYTCCH
IF (LYTCCH) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YTCCH)
ENDIF
LYSCCH = ASSOCIATED (YD%YSCCH)
WRITE (KLUN) LYSCCH
IF (LYSCCH) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YSCCH)
ENDIF
LYBCCH = ASSOCIATED (YD%YBCCH)
WRITE (KLUN) LYBCCH
IF (LYBCCH) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YBCCH)
ENDIF
LYPBLH = ASSOCIATED (YD%YPBLH)
WRITE (KLUN) LYPBLH
IF (LYPBLH) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YPBLH)
ENDIF
LYSPSH = ASSOCIATED (YD%YSPSH)
WRITE (KLUN) LYSPSH
IF (LYSPSH) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YSPSH)
ENDIF
LYQSH = ASSOCIATED (YD%YQSH)
WRITE (KLUN) LYQSH
IF (LYQSH) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YQSH)
ENDIF
LYVH = ASSOCIATED (YD%YVH)
WRITE (KLUN) LYVH
IF (LYVH) THEN
  WRITE (KLUN) LBOUND (YD%YVH)
  WRITE (KLUN) UBOUND (YD%YVH)
  DO J1 = LBOUND (YD%YVH, 1), UBOUND (YD%YVH, 1)
    CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YVH (J1))
  ENDDO
ENDIF
LYPCL = ASSOCIATED (YD%YPCL)
WRITE (KLUN) LYPCL
IF (LYPCL) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YPCL)
ENDIF
LYPSL = ASSOCIATED (YD%YPSL)
WRITE (KLUN) LYPSL
IF (LYPSL) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YPSL)
ENDIF
LYPCN = ASSOCIATED (YD%YPCN)
WRITE (KLUN) LYPCN
IF (LYPCN) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YPCN)
ENDIF
LYPSN = ASSOCIATED (YD%YPSN)
WRITE (KLUN) LYPSN
IF (LYPSN) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YPSN)
ENDIF
LYEVA = ASSOCIATED (YD%YEVA)
WRITE (KLUN) LYEVA
IF (LYEVA) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YEVA)
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TYPE_SFL_VCLIH (KLUN, YD)
USE UTIL_TYPE_SURF_MTL_2D_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_SFL_VCLIH), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYBCCH, LYEVA, LYPBLH, LYPCL, LYPCN, LYPSL, LYPSN, LYQSH, LYSCCH, LYSPSH
LOGICAL :: LYTCCH, LYVH
READ (KLUN) LYTCCH
IF (LYTCCH) THEN
  ALLOCATE (YD%YTCCH)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YTCCH)
ELSE
  NULLIFY (YD%YTCCH)
ENDIF
READ (KLUN) LYSCCH
IF (LYSCCH) THEN
  ALLOCATE (YD%YSCCH)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YSCCH)
ELSE
  NULLIFY (YD%YSCCH)
ENDIF
READ (KLUN) LYBCCH
IF (LYBCCH) THEN
  ALLOCATE (YD%YBCCH)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YBCCH)
ELSE
  NULLIFY (YD%YBCCH)
ENDIF
READ (KLUN) LYPBLH
IF (LYPBLH) THEN
  ALLOCATE (YD%YPBLH)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YPBLH)
ELSE
  NULLIFY (YD%YPBLH)
ENDIF
READ (KLUN) LYSPSH
IF (LYSPSH) THEN
  ALLOCATE (YD%YSPSH)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YSPSH)
ELSE
  NULLIFY (YD%YSPSH)
ENDIF
READ (KLUN) LYQSH
IF (LYQSH) THEN
  ALLOCATE (YD%YQSH)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YQSH)
ELSE
  NULLIFY (YD%YQSH)
ENDIF
READ (KLUN) LYVH
IF (LYVH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YVH (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YVH, 1), UBOUND (YD%YVH, 1)
    CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YVH (J1))
  ENDDO
ELSE
  NULLIFY (YD%YVH)
ENDIF
READ (KLUN) LYPCL
IF (LYPCL) THEN
  ALLOCATE (YD%YPCL)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YPCL)
ELSE
  NULLIFY (YD%YPCL)
ENDIF
READ (KLUN) LYPSL
IF (LYPSL) THEN
  ALLOCATE (YD%YPSL)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YPSL)
ELSE
  NULLIFY (YD%YPSL)
ENDIF
READ (KLUN) LYPCN
IF (LYPCN) THEN
  ALLOCATE (YD%YPCN)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YPCN)
ELSE
  NULLIFY (YD%YPCN)
ENDIF
READ (KLUN) LYPSN
IF (LYPSN) THEN
  ALLOCATE (YD%YPSN)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YPSN)
ELSE
  NULLIFY (YD%YPSN)
ENDIF
READ (KLUN) LYEVA
IF (LYEVA) THEN
  ALLOCATE (YD%YEVA)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YEVA)
ELSE
  NULLIFY (YD%YEVA)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TYPE_SFL_VCLIH (YD, LDCREATED, LDFIELDAPI)
USE UTIL_TYPE_SURF_MTL_2D_MOD
IMPLICIT NONE
TYPE (TYPE_SFL_VCLIH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LYBCCH, LYEVA, LYPBLH, LYPCL, LYPCN, LYPSL, LYPSN, LYQSH, LYSCCH, LYSPSH
LOGICAL :: LYTCCH, LYVH

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LYTCCH = ASSOCIATED (YD%YTCCH)
IF (LYTCCH) THEN
  !$ACC ENTER DATA CREATE (YD%YTCCH)
  !$ACC UPDATE DEVICE (YD%YTCCH)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YTCCH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YTCCH)
ENDIF

LYSCCH = ASSOCIATED (YD%YSCCH)
IF (LYSCCH) THEN
  !$ACC ENTER DATA CREATE (YD%YSCCH)
  !$ACC UPDATE DEVICE (YD%YSCCH)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YSCCH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YSCCH)
ENDIF

LYBCCH = ASSOCIATED (YD%YBCCH)
IF (LYBCCH) THEN
  !$ACC ENTER DATA CREATE (YD%YBCCH)
  !$ACC UPDATE DEVICE (YD%YBCCH)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YBCCH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YBCCH)
ENDIF

LYPBLH = ASSOCIATED (YD%YPBLH)
IF (LYPBLH) THEN
  !$ACC ENTER DATA CREATE (YD%YPBLH)
  !$ACC UPDATE DEVICE (YD%YPBLH)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YPBLH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YPBLH)
ENDIF

LYSPSH = ASSOCIATED (YD%YSPSH)
IF (LYSPSH) THEN
  !$ACC ENTER DATA CREATE (YD%YSPSH)
  !$ACC UPDATE DEVICE (YD%YSPSH)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YSPSH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YSPSH)
ENDIF

LYQSH = ASSOCIATED (YD%YQSH)
IF (LYQSH) THEN
  !$ACC ENTER DATA CREATE (YD%YQSH)
  !$ACC UPDATE DEVICE (YD%YQSH)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YQSH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YQSH)
ENDIF

LYVH = ASSOCIATED (YD%YVH)
IF (LYVH) THEN
  !$ACC ENTER DATA CREATE (YD%YVH)
  !$ACC UPDATE DEVICE (YD%YVH)
  DO J1 = LBOUND (YD%YVH, 1), UBOUND (YD%YVH, 1)
    CALL COPY_TYPE_SURF_MTL_2D (YD%YVH (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%YVH)
ENDIF

LYPCL = ASSOCIATED (YD%YPCL)
IF (LYPCL) THEN
  !$ACC ENTER DATA CREATE (YD%YPCL)
  !$ACC UPDATE DEVICE (YD%YPCL)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YPCL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YPCL)
ENDIF

LYPSL = ASSOCIATED (YD%YPSL)
IF (LYPSL) THEN
  !$ACC ENTER DATA CREATE (YD%YPSL)
  !$ACC UPDATE DEVICE (YD%YPSL)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YPSL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YPSL)
ENDIF

LYPCN = ASSOCIATED (YD%YPCN)
IF (LYPCN) THEN
  !$ACC ENTER DATA CREATE (YD%YPCN)
  !$ACC UPDATE DEVICE (YD%YPCN)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YPCN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YPCN)
ENDIF

LYPSN = ASSOCIATED (YD%YPSN)
IF (LYPSN) THEN
  !$ACC ENTER DATA CREATE (YD%YPSN)
  !$ACC UPDATE DEVICE (YD%YPSN)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YPSN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YPSN)
ENDIF

LYEVA = ASSOCIATED (YD%YEVA)
IF (LYEVA) THEN
  !$ACC ENTER DATA CREATE (YD%YEVA)
  !$ACC UPDATE DEVICE (YD%YEVA)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YEVA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YEVA)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TYPE_SFL_VCLIH (YD)
USE UTIL_TYPE_SURF_MTL_2D_MOD

IMPLICIT NONE
TYPE (TYPE_SFL_VCLIH), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYBCCH, LYEVA, LYPBLH, LYPCL, LYPCN, LYPSL, LYPSN, LYQSH, LYSCCH, LYSPSH
LOGICAL :: LYTCCH, LYVH
LYTCCH = ASSOCIATED (YD%YTCCH)
IF (LYTCCH) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YTCCH)
ENDIF

LYSCCH = ASSOCIATED (YD%YSCCH)
IF (LYSCCH) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YSCCH)
ENDIF

LYBCCH = ASSOCIATED (YD%YBCCH)
IF (LYBCCH) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YBCCH)
ENDIF

LYPBLH = ASSOCIATED (YD%YPBLH)
IF (LYPBLH) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YPBLH)
ENDIF

LYSPSH = ASSOCIATED (YD%YSPSH)
IF (LYSPSH) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YSPSH)
ENDIF

LYQSH = ASSOCIATED (YD%YQSH)
IF (LYQSH) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YQSH)
ENDIF

LYVH = ASSOCIATED (YD%YVH)
IF (LYVH) THEN
  DO J1 = LBOUND (YD%YVH, 1), UBOUND (YD%YVH, 1)
    CALL HOST_TYPE_SURF_MTL_2D (YD%YVH (J1))
  ENDDO
ENDIF

LYPCL = ASSOCIATED (YD%YPCL)
IF (LYPCL) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YPCL)
ENDIF

LYPSL = ASSOCIATED (YD%YPSL)
IF (LYPSL) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YPSL)
ENDIF

LYPCN = ASSOCIATED (YD%YPCN)
IF (LYPCN) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YPCN)
ENDIF

LYPSN = ASSOCIATED (YD%YPSN)
IF (LYPSN) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YPSN)
ENDIF

LYEVA = ASSOCIATED (YD%YEVA)
IF (LYEVA) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YEVA)
ENDIF

END SUBROUTINE

     

SUBROUTINE CRC64_TYPE_SFL_VCLIH (YD, KLUN, CDPATH)
USE UTIL_TYPE_SURF_MTL_2D_MOD
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TYPE_SFL_VCLIH), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
INTEGER :: J1
LOGICAL :: LYBCCH, LYEVA, LYPBLH, LYPCL, LYPCN, LYPSL, LYPSN, LYQSH, LYSCCH, LYSPSH
LOGICAL :: LYTCCH, LYVH
LYTCCH = ASSOCIATED (YD%YTCCH)
IF (LYTCCH) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YTCCH, KLUN, CDPATH//'%YTCCH'//TRIM(CLIND))
ENDIF

LYSCCH = ASSOCIATED (YD%YSCCH)
IF (LYSCCH) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YSCCH, KLUN, CDPATH//'%YSCCH'//TRIM(CLIND))
ENDIF

LYBCCH = ASSOCIATED (YD%YBCCH)
IF (LYBCCH) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YBCCH, KLUN, CDPATH//'%YBCCH'//TRIM(CLIND))
ENDIF

LYPBLH = ASSOCIATED (YD%YPBLH)
IF (LYPBLH) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YPBLH, KLUN, CDPATH//'%YPBLH'//TRIM(CLIND))
ENDIF

LYSPSH = ASSOCIATED (YD%YSPSH)
IF (LYSPSH) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YSPSH, KLUN, CDPATH//'%YSPSH'//TRIM(CLIND))
ENDIF

LYQSH = ASSOCIATED (YD%YQSH)
IF (LYQSH) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YQSH, KLUN, CDPATH//'%YQSH'//TRIM(CLIND))
ENDIF

LYVH = ASSOCIATED (YD%YVH)
IF (LYVH) THEN
  DO J1 = LBOUND (YD%YVH, 1), UBOUND (YD%YVH, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL CRC64_TYPE_SURF_MTL_2D (YD%YVH (J1), KLUN, CDPATH//'%YVH'//TRIM(CLIND))
  ENDDO
ENDIF

LYPCL = ASSOCIATED (YD%YPCL)
IF (LYPCL) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YPCL, KLUN, CDPATH//'%YPCL'//TRIM(CLIND))
ENDIF

LYPSL = ASSOCIATED (YD%YPSL)
IF (LYPSL) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YPSL, KLUN, CDPATH//'%YPSL'//TRIM(CLIND))
ENDIF

LYPCN = ASSOCIATED (YD%YPCN)
IF (LYPCN) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YPCN, KLUN, CDPATH//'%YPCN'//TRIM(CLIND))
ENDIF

LYPSN = ASSOCIATED (YD%YPSN)
IF (LYPSN) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YPSN, KLUN, CDPATH//'%YPSN'//TRIM(CLIND))
ENDIF

LYEVA = ASSOCIATED (YD%YEVA)
IF (LYEVA) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YEVA, KLUN, CDPATH//'%YEVA'//TRIM(CLIND))
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TYPE_SFL_VCLIH (YD, LDDELETED, LDFIELDAPI)
USE UTIL_TYPE_SURF_MTL_2D_MOD
IMPLICIT NONE
TYPE (TYPE_SFL_VCLIH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LYBCCH, LYEVA, LYPBLH, LYPCL, LYPCN, LYPSL, LYPSN, LYQSH, LYSCCH, LYSPSH
LOGICAL :: LYTCCH, LYVH

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LYTCCH = ASSOCIATED (YD%YTCCH)
IF (LYTCCH) THEN
  !$ACC EXIT DATA DETACH (YD%YTCCH)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YTCCH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YTCCH)
ENDIF

LYSCCH = ASSOCIATED (YD%YSCCH)
IF (LYSCCH) THEN
  !$ACC EXIT DATA DETACH (YD%YSCCH)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YSCCH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YSCCH)
ENDIF

LYBCCH = ASSOCIATED (YD%YBCCH)
IF (LYBCCH) THEN
  !$ACC EXIT DATA DETACH (YD%YBCCH)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YBCCH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YBCCH)
ENDIF

LYPBLH = ASSOCIATED (YD%YPBLH)
IF (LYPBLH) THEN
  !$ACC EXIT DATA DETACH (YD%YPBLH)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YPBLH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YPBLH)
ENDIF

LYSPSH = ASSOCIATED (YD%YSPSH)
IF (LYSPSH) THEN
  !$ACC EXIT DATA DETACH (YD%YSPSH)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YSPSH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YSPSH)
ENDIF

LYQSH = ASSOCIATED (YD%YQSH)
IF (LYQSH) THEN
  !$ACC EXIT DATA DETACH (YD%YQSH)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YQSH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YQSH)
ENDIF

LYVH = ASSOCIATED (YD%YVH)
IF (LYVH) THEN
  !$ACC EXIT DATA DETACH (YD%YVH)
  DO J1 = LBOUND (YD%YVH, 1), UBOUND (YD%YVH, 1)
    CALL WIPE_TYPE_SURF_MTL_2D (YD%YVH (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%YVH)
ENDIF

LYPCL = ASSOCIATED (YD%YPCL)
IF (LYPCL) THEN
  !$ACC EXIT DATA DETACH (YD%YPCL)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YPCL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YPCL)
ENDIF

LYPSL = ASSOCIATED (YD%YPSL)
IF (LYPSL) THEN
  !$ACC EXIT DATA DETACH (YD%YPSL)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YPSL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YPSL)
ENDIF

LYPCN = ASSOCIATED (YD%YPCN)
IF (LYPCN) THEN
  !$ACC EXIT DATA DETACH (YD%YPCN)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YPCN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YPCN)
ENDIF

LYPSN = ASSOCIATED (YD%YPSN)
IF (LYPSN) THEN
  !$ACC EXIT DATA DETACH (YD%YPSN)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YPSN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YPSN)
ENDIF

LYEVA = ASSOCIATED (YD%YEVA)
IF (LYEVA) THEN
  !$ACC EXIT DATA DETACH (YD%YEVA)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YEVA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YEVA)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
