MODULE UTIL_TPHNC_MOD

USE YOPHNC, ONLY : TPHNC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHNC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHNC
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPHNC
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TPHNC
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TPHNC
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TPHNC
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TPHNC
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TPHNC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHNC), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%LETRAJP
WRITE (KLUN) YD%LETRAJPT
WRITE (KLUN) YD%LERADI2
WRITE (KLUN) YD%LERADS2
WRITE (KLUN) YD%LERADSW2
WRITE (KLUN) YD%LERADN2
WRITE (KLUN) YD%LERADFL2
WRITE (KLUN) YD%LERADLW2
WRITE (KLUN) YD%LH2OCO2
WRITE (KLUN) YD%LWLOPT
WRITE (KLUN) YD%LWSOPT
WRITE (KLUN) YD%LEDCLD2
WRITE (KLUN) YD%LEPCLD2
WRITE (KLUN) YD%LENCLD2
WRITE (KLUN) YD%LEVAPLS2
WRITE (KLUN) YD%LEVDIF2
WRITE (KLUN) YD%LEGWDG2
WRITE (KLUN) YD%LECUMF2
WRITE (KLUN) YD%LECOND2
WRITE (KLUN) YD%LEGWWMS2
WRITE (KLUN) YD%LEQNGT2
WRITE (KLUN) YD%LESURF2
WRITE (KLUN) YD%LEKPERT
WRITE (KLUN) YD%LEKPERTS
WRITE (KLUN) YD%LTRACLNPH
END SUBROUTINE

SUBROUTINE LOAD_TPHNC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHNC), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%LETRAJP
READ (KLUN) YD%LETRAJPT
READ (KLUN) YD%LERADI2
READ (KLUN) YD%LERADS2
READ (KLUN) YD%LERADSW2
READ (KLUN) YD%LERADN2
READ (KLUN) YD%LERADFL2
READ (KLUN) YD%LERADLW2
READ (KLUN) YD%LH2OCO2
READ (KLUN) YD%LWLOPT
READ (KLUN) YD%LWSOPT
READ (KLUN) YD%LEDCLD2
READ (KLUN) YD%LEPCLD2
READ (KLUN) YD%LENCLD2
READ (KLUN) YD%LEVAPLS2
READ (KLUN) YD%LEVDIF2
READ (KLUN) YD%LEGWDG2
READ (KLUN) YD%LECUMF2
READ (KLUN) YD%LECOND2
READ (KLUN) YD%LEGWWMS2
READ (KLUN) YD%LEQNGT2
READ (KLUN) YD%LESURF2
READ (KLUN) YD%LEKPERT
READ (KLUN) YD%LEKPERTS
READ (KLUN) YD%LTRACLNPH
END SUBROUTINE


SUBROUTINE COPY_TPHNC (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPHNC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF

























END SUBROUTINE

SUBROUTINE HOST_TPHNC (YD)

IMPLICIT NONE
TYPE (TPHNC), TARGET :: YD


























END SUBROUTINE

     

SUBROUTINE CRC64_TPHNC (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TPHNC), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LETRAJP), CDPATH//'%LETRAJP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LETRAJPT), CDPATH//'%LETRAJPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LERADI2), CDPATH//'%LERADI2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LERADS2), CDPATH//'%LERADS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LERADSW2), CDPATH//'%LERADSW2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LERADN2), CDPATH//'%LERADN2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LERADFL2), CDPATH//'%LERADFL2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LERADLW2), CDPATH//'%LERADLW2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LH2OCO2), CDPATH//'%LH2OCO2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LWLOPT), CDPATH//'%LWLOPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LWSOPT), CDPATH//'%LWSOPT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEDCLD2), CDPATH//'%LEDCLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEPCLD2), CDPATH//'%LEPCLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LENCLD2), CDPATH//'%LENCLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEVAPLS2), CDPATH//'%LEVAPLS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEVDIF2), CDPATH//'%LEVDIF2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEGWDG2), CDPATH//'%LEGWDG2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECUMF2), CDPATH//'%LECUMF2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECOND2), CDPATH//'%LECOND2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEGWWMS2), CDPATH//'%LEGWWMS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEQNGT2), CDPATH//'%LEQNGT2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LESURF2), CDPATH//'%LESURF2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEKPERT), CDPATH//'%LEKPERT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEKPERTS), CDPATH//'%LEKPERTS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LTRACLNPH), CDPATH//'%LTRACLNPH'

END SUBROUTINE

SUBROUTINE WIPE_TPHNC (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPHNC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

























LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TPHNC (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TPHNC),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%LETRAJP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LETRAJP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LETRAJPT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LETRAJPT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LERADI2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADI2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LERADS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LERADSW2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADSW2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LERADN2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADN2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LERADFL2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADFL2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LERADLW2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LERADLW2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LH2OCO2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LH2OCO2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LWLOPT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LWLOPT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LWSOPT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LWSOPT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEDCLD2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEDCLD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEPCLD2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEPCLD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LENCLD2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LENCLD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEVAPLS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEVAPLS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEVDIF2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEVDIF2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEGWDG2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEGWDG2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECUMF2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECUMF2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECOND2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECOND2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEGWWMS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEGWWMS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEQNGT2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEQNGT2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LESURF2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LESURF2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEKPERT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEKPERT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEKPERTS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEKPERTS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LTRACLNPH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LTRACLNPH'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
