MODULE UTIL_TEAERC_TEGEN_MOD

USE YOEAERC, ONLY : TEAERC_TEGEN

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEAERC_TEGEN
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEAERC_TEGEN
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEAERC_TEGEN
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TEAERC_TEGEN
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TEAERC_TEGEN
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEAERC_TEGEN
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TEAERC_TEGEN
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TEAERC_TEGEN (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERC_TEGEN), INTENT (IN), TARGET :: YD
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV
WRITE (KLUN) YD%REPAER
LRAERBC = ASSOCIATED (YD%RAERBC)
WRITE (KLUN) LRAERBC
IF (LRAERBC) THEN
  WRITE (KLUN) LBOUND (YD%RAERBC)
  WRITE (KLUN) UBOUND (YD%RAERBC)
  WRITE (KLUN) YD%RAERBC
ENDIF
LRAEROR = ASSOCIATED (YD%RAEROR)
WRITE (KLUN) LRAEROR
IF (LRAEROR) THEN
  WRITE (KLUN) LBOUND (YD%RAEROR)
  WRITE (KLUN) UBOUND (YD%RAEROR)
  WRITE (KLUN) YD%RAEROR
ENDIF
LRAERSD = ASSOCIATED (YD%RAERSD)
WRITE (KLUN) LRAERSD
IF (LRAERSD) THEN
  WRITE (KLUN) LBOUND (YD%RAERSD)
  WRITE (KLUN) UBOUND (YD%RAERSD)
  WRITE (KLUN) YD%RAERSD
ENDIF
LRAERSS = ASSOCIATED (YD%RAERSS)
WRITE (KLUN) LRAERSS
IF (LRAERSS) THEN
  WRITE (KLUN) LBOUND (YD%RAERSS)
  WRITE (KLUN) UBOUND (YD%RAERSS)
  WRITE (KLUN) YD%RAERSS
ENDIF
LRAERSU = ASSOCIATED (YD%RAERSU)
WRITE (KLUN) LRAERSU
IF (LRAERSU) THEN
  WRITE (KLUN) LBOUND (YD%RAERSU)
  WRITE (KLUN) UBOUND (YD%RAERSU)
  WRITE (KLUN) YD%RAERSU
ENDIF
LRAERV = ASSOCIATED (YD%RAERV)
WRITE (KLUN) LRAERV
IF (LRAERV) THEN
  WRITE (KLUN) LBOUND (YD%RAERV)
  WRITE (KLUN) UBOUND (YD%RAERV)
  WRITE (KLUN) YD%RAERV
ENDIF
LRLATV = ASSOCIATED (YD%RLATV)
WRITE (KLUN) LRLATV
IF (LRLATV) THEN
  WRITE (KLUN) LBOUND (YD%RLATV)
  WRITE (KLUN) UBOUND (YD%RLATV)
  WRITE (KLUN) YD%RLATV
ENDIF
WRITE (KLUN) YD%RTAEBC
WRITE (KLUN) YD%RTAEOR
WRITE (KLUN) YD%RTAESD
WRITE (KLUN) YD%RTAESS
WRITE (KLUN) YD%RTAESU
WRITE (KLUN) YD%RTAEVO
WRITE (KLUN) YD%ISYEAR
WRITE (KLUN) YD%IEYEAR
WRITE (KLUN) YD%IS_INITIALISED
END SUBROUTINE

SUBROUTINE LOAD_TEAERC_TEGEN (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEAERC_TEGEN), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL3(3), IU3(3)
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) ZTMP0
YD%REPAER = ZTMP0
READ (KLUN) LRAERBC
IF (LRAERBC) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERBC (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERBC,1):UBOUND(YD%RAERBC,1), LBOUND(YD%RAERBC,2):UBOUND(YD%RAERBC,2), LBOUND(YD%RAERBC,3):UBOUND(YD%RAERBC,3)))
  READ (KLUN) ZTMP3
  YD%RAERBC = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERBC)
ENDIF
READ (KLUN) LRAEROR
IF (LRAEROR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAEROR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAEROR,1):UBOUND(YD%RAEROR,1), LBOUND(YD%RAEROR,2):UBOUND(YD%RAEROR,2), LBOUND(YD%RAEROR,3):UBOUND(YD%RAEROR,3)))
  READ (KLUN) ZTMP3
  YD%RAEROR = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAEROR)
ENDIF
READ (KLUN) LRAERSD
IF (LRAERSD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERSD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERSD,1):UBOUND(YD%RAERSD,1), LBOUND(YD%RAERSD,2):UBOUND(YD%RAERSD,2), LBOUND(YD%RAERSD,3):UBOUND(YD%RAERSD,3)))
  READ (KLUN) ZTMP3
  YD%RAERSD = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERSD)
ENDIF
READ (KLUN) LRAERSS
IF (LRAERSS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERSS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERSS,1):UBOUND(YD%RAERSS,1), LBOUND(YD%RAERSS,2):UBOUND(YD%RAERSS,2), LBOUND(YD%RAERSS,3):UBOUND(YD%RAERSS,3)))
  READ (KLUN) ZTMP3
  YD%RAERSS = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERSS)
ENDIF
READ (KLUN) LRAERSU
IF (LRAERSU) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERSU (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERSU,1):UBOUND(YD%RAERSU,1), LBOUND(YD%RAERSU,2):UBOUND(YD%RAERSU,2), LBOUND(YD%RAERSU,3):UBOUND(YD%RAERSU,3)))
  READ (KLUN) ZTMP3
  YD%RAERSU = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERSU)
ENDIF
READ (KLUN) LRAERV
IF (LRAERV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RAERV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RAERV,1):UBOUND(YD%RAERV,1), LBOUND(YD%RAERV,2):UBOUND(YD%RAERV,2), LBOUND(YD%RAERV,3):UBOUND(YD%RAERV,3)))
  READ (KLUN) ZTMP3
  YD%RAERV = ZTMP3
  DEALLOCATE (ZTMP3)
ELSE
  NULLIFY (YD%RAERV)
ENDIF
READ (KLUN) LRLATV
IF (LRLATV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATV (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RLATV,1):UBOUND(YD%RLATV,1)))
  READ (KLUN) ZTMP1
  YD%RLATV = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (YD%RLATV)
ENDIF
ALLOCATE (ZTMP2(LBOUND(YD%RTAEBC,1):UBOUND(YD%RTAEBC,1), LBOUND(YD%RTAEBC,2):UBOUND(YD%RTAEBC,2)))
READ (KLUN) ZTMP2
YD%RTAEBC = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(YD%RTAEOR,1):UBOUND(YD%RTAEOR,1), LBOUND(YD%RTAEOR,2):UBOUND(YD%RTAEOR,2)))
READ (KLUN) ZTMP2
YD%RTAEOR = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(YD%RTAESD,1):UBOUND(YD%RTAESD,1), LBOUND(YD%RTAESD,2):UBOUND(YD%RTAESD,2)))
READ (KLUN) ZTMP2
YD%RTAESD = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(YD%RTAESS,1):UBOUND(YD%RTAESS,1), LBOUND(YD%RTAESS,2):UBOUND(YD%RTAESS,2)))
READ (KLUN) ZTMP2
YD%RTAESS = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP2(LBOUND(YD%RTAESU,1):UBOUND(YD%RTAESU,1), LBOUND(YD%RTAESU,2):UBOUND(YD%RTAESU,2)))
READ (KLUN) ZTMP2
YD%RTAESU = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP1(LBOUND(YD%RTAEVO,1):UBOUND(YD%RTAEVO,1)))
READ (KLUN) ZTMP1
YD%RTAEVO = ZTMP1
DEALLOCATE (ZTMP1)
READ (KLUN) YD%ISYEAR
READ (KLUN) YD%IEYEAR
READ (KLUN) YD%IS_INITIALISED
END SUBROUTINE


SUBROUTINE COPY_TEAERC_TEGEN (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEAERC_TEGEN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF

LRAERBC = ASSOCIATED (YD%RAERBC)
IF (LRAERBC) THEN
  !$ACC ENTER DATA CREATE (YD%RAERBC)
  !$ACC UPDATE DEVICE (YD%RAERBC)
  !$ACC ENTER DATA ATTACH (YD%RAERBC)
ENDIF

LRAEROR = ASSOCIATED (YD%RAEROR)
IF (LRAEROR) THEN
  !$ACC ENTER DATA CREATE (YD%RAEROR)
  !$ACC UPDATE DEVICE (YD%RAEROR)
  !$ACC ENTER DATA ATTACH (YD%RAEROR)
ENDIF

LRAERSD = ASSOCIATED (YD%RAERSD)
IF (LRAERSD) THEN
  !$ACC ENTER DATA CREATE (YD%RAERSD)
  !$ACC UPDATE DEVICE (YD%RAERSD)
  !$ACC ENTER DATA ATTACH (YD%RAERSD)
ENDIF

LRAERSS = ASSOCIATED (YD%RAERSS)
IF (LRAERSS) THEN
  !$ACC ENTER DATA CREATE (YD%RAERSS)
  !$ACC UPDATE DEVICE (YD%RAERSS)
  !$ACC ENTER DATA ATTACH (YD%RAERSS)
ENDIF

LRAERSU = ASSOCIATED (YD%RAERSU)
IF (LRAERSU) THEN
  !$ACC ENTER DATA CREATE (YD%RAERSU)
  !$ACC UPDATE DEVICE (YD%RAERSU)
  !$ACC ENTER DATA ATTACH (YD%RAERSU)
ENDIF

LRAERV = ASSOCIATED (YD%RAERV)
IF (LRAERV) THEN
  !$ACC ENTER DATA CREATE (YD%RAERV)
  !$ACC UPDATE DEVICE (YD%RAERV)
  !$ACC ENTER DATA ATTACH (YD%RAERV)
ENDIF

LRLATV = ASSOCIATED (YD%RLATV)
IF (LRLATV) THEN
  !$ACC ENTER DATA CREATE (YD%RLATV)
  !$ACC UPDATE DEVICE (YD%RLATV)
  !$ACC ENTER DATA ATTACH (YD%RLATV)
ENDIF










END SUBROUTINE

SUBROUTINE HOST_TEAERC_TEGEN (YD)

IMPLICIT NONE
TYPE (TEAERC_TEGEN), TARGET :: YD
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV

















END SUBROUTINE

     

SUBROUTINE CRC64_TEAERC_TEGEN (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TEAERC_TEGEN), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%REPAER), CDPATH//'%REPAER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RAERBC), CDPATH//'%RAERBC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RAEROR), CDPATH//'%RAEROR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RAERSD), CDPATH//'%RAERSD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RAERSS), CDPATH//'%RAERSS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RAERSU), CDPATH//'%RAERSU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RAERV), CDPATH//'%RAERV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RLATV), CDPATH//'%RLATV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RTAEBC), CDPATH//'%RTAEBC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RTAEOR), CDPATH//'%RTAEOR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RTAESD), CDPATH//'%RTAESD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RTAESS), CDPATH//'%RTAESS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RTAESU), CDPATH//'%RTAESU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RTAEVO), CDPATH//'%RTAEVO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%ISYEAR), CDPATH//'%ISYEAR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%IEYEAR), CDPATH//'%IEYEAR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%IS_INITIALISED), CDPATH//'%IS_INITIALISED'

END SUBROUTINE

SUBROUTINE WIPE_TEAERC_TEGEN (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEAERC_TEGEN), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LRAERBC = ASSOCIATED (YD%RAERBC)
IF (LRAERBC) THEN
  !$ACC EXIT DATA DETACH (YD%RAERBC)
  !$ACC EXIT DATA DETACH (YD%RAERBC)
ENDIF

LRAEROR = ASSOCIATED (YD%RAEROR)
IF (LRAEROR) THEN
  !$ACC EXIT DATA DETACH (YD%RAEROR)
  !$ACC EXIT DATA DETACH (YD%RAEROR)
ENDIF

LRAERSD = ASSOCIATED (YD%RAERSD)
IF (LRAERSD) THEN
  !$ACC EXIT DATA DETACH (YD%RAERSD)
  !$ACC EXIT DATA DETACH (YD%RAERSD)
ENDIF

LRAERSS = ASSOCIATED (YD%RAERSS)
IF (LRAERSS) THEN
  !$ACC EXIT DATA DETACH (YD%RAERSS)
  !$ACC EXIT DATA DETACH (YD%RAERSS)
ENDIF

LRAERSU = ASSOCIATED (YD%RAERSU)
IF (LRAERSU) THEN
  !$ACC EXIT DATA DETACH (YD%RAERSU)
  !$ACC EXIT DATA DETACH (YD%RAERSU)
ENDIF

LRAERV = ASSOCIATED (YD%RAERV)
IF (LRAERV) THEN
  !$ACC EXIT DATA DETACH (YD%RAERV)
  !$ACC EXIT DATA DETACH (YD%RAERV)
ENDIF

LRLATV = ASSOCIATED (YD%RLATV)
IF (LRLATV) THEN
  !$ACC EXIT DATA DETACH (YD%RLATV)
  !$ACC EXIT DATA DETACH (YD%RLATV)
ENDIF










LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TEAERC_TEGEN (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TEAERC_TEGEN),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LRAERBC, LRAEROR, LRAERSD, LRAERSS, LRAERSU, LRAERV, LRLATV

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%REPAER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%REPAER'
ENDIF
KSIZE = KSIZE + ISIZE
LRAERBC = ASSOCIATED (YD%RAERBC)
IF (LRAERBC) THEN
  ISIZE = KIND (YD%RAERBC) * SIZE (YD%RAERBC)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RAERBC'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRAEROR = ASSOCIATED (YD%RAEROR)
IF (LRAEROR) THEN
  ISIZE = KIND (YD%RAEROR) * SIZE (YD%RAEROR)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RAEROR'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRAERSD = ASSOCIATED (YD%RAERSD)
IF (LRAERSD) THEN
  ISIZE = KIND (YD%RAERSD) * SIZE (YD%RAERSD)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RAERSD'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRAERSS = ASSOCIATED (YD%RAERSS)
IF (LRAERSS) THEN
  ISIZE = KIND (YD%RAERSS) * SIZE (YD%RAERSS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RAERSS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRAERSU = ASSOCIATED (YD%RAERSU)
IF (LRAERSU) THEN
  ISIZE = KIND (YD%RAERSU) * SIZE (YD%RAERSU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RAERSU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRAERV = ASSOCIATED (YD%RAERV)
IF (LRAERV) THEN
  ISIZE = KIND (YD%RAERV) * SIZE (YD%RAERV)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RAERV'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLATV = ASSOCIATED (YD%RLATV)
IF (LRLATV) THEN
  ISIZE = KIND (YD%RLATV) * SIZE (YD%RLATV)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLATV'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%RTAEBC) * SIZE (YD%RTAEBC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTAEBC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTAEOR) * SIZE (YD%RTAEOR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTAEOR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTAESD) * SIZE (YD%RTAESD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTAESD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTAESS) * SIZE (YD%RTAESS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTAESS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTAESU) * SIZE (YD%RTAESU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTAESU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTAEVO) * SIZE (YD%RTAEVO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTAEVO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ISYEAR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ISYEAR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%IEYEAR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IEYEAR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%IS_INITIALISED)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%IS_INITIALISED'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
