MODULE UTIL_SURFACE_VIEW_GROUP_VDIAGO3_MOD

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_VDIAGO3



INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VIEW_GROUP_VDIAGO3
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_SURFACE_VIEW_GROUP_VDIAGO3
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VIEW_GROUP_VDIAGO3
END INTERFACE



CONTAINS





SUBROUTINE COPY_SURFACE_VIEW_GROUP_VDIAGO3 (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_VDIAGO3_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VDIAGO3), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_ADVS, LF_ADVT, LF_DIFM, LF_DIFS, LF_DIFT, LF_DO, LF_GROUP, LF_HO, LF_HO_INV, LF_OTKE
LOGICAL :: LF_SWDK, LF_TRI0, LF_TRI1, LF_UOC, LF_VOC, LF_ZO, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC ENTER DATA CREATE (YD%VARIABLE_GROUP)
  !$ACC UPDATE DEVICE (YD%VARIABLE_GROUP)
  CALL COPY_SURFACE_VARIABLE_GROUP_VDIAGO3 (YD%VARIABLE_GROUP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%VARIABLE_GROUP)
ENDIF

LF_DIFM = ASSOCIATED (YD%F_DIFM)
IF (LF_DIFM .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DIFM)
  !$ACC ENTER DATA ATTACH (YD%F_DIFM)
ENDIF

LF_DIFT = ASSOCIATED (YD%F_DIFT)
IF (LF_DIFT .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DIFT)
  !$ACC ENTER DATA ATTACH (YD%F_DIFT)
ENDIF

LF_DIFS = ASSOCIATED (YD%F_DIFS)
IF (LF_DIFS .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DIFS)
  !$ACC ENTER DATA ATTACH (YD%F_DIFS)
ENDIF

LF_ADVT = ASSOCIATED (YD%F_ADVT)
IF (LF_ADVT .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_ADVT)
  !$ACC ENTER DATA ATTACH (YD%F_ADVT)
ENDIF

LF_ADVS = ASSOCIATED (YD%F_ADVS)
IF (LF_ADVS .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_ADVS)
  !$ACC ENTER DATA ATTACH (YD%F_ADVS)
ENDIF

LF_TRI0 = ASSOCIATED (YD%F_TRI0)
IF (LF_TRI0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_TRI0)
  !$ACC ENTER DATA ATTACH (YD%F_TRI0)
ENDIF

LF_TRI1 = ASSOCIATED (YD%F_TRI1)
IF (LF_TRI1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_TRI1)
  !$ACC ENTER DATA ATTACH (YD%F_TRI1)
ENDIF

LF_SWDK = ASSOCIATED (YD%F_SWDK)
IF (LF_SWDK .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_SWDK)
  !$ACC ENTER DATA ATTACH (YD%F_SWDK)
ENDIF

LF_ZO = ASSOCIATED (YD%F_ZO)
IF (LF_ZO .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_ZO)
  !$ACC ENTER DATA ATTACH (YD%F_ZO)
ENDIF

LF_HO = ASSOCIATED (YD%F_HO)
IF (LF_HO .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_HO)
  !$ACC ENTER DATA ATTACH (YD%F_HO)
ENDIF

LF_DO = ASSOCIATED (YD%F_DO)
IF (LF_DO .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DO)
  !$ACC ENTER DATA ATTACH (YD%F_DO)
ENDIF

LF_HO_INV = ASSOCIATED (YD%F_HO_INV)
IF (LF_HO_INV .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_HO_INV)
  !$ACC ENTER DATA ATTACH (YD%F_HO_INV)
ENDIF

LF_UOC = ASSOCIATED (YD%F_UOC)
IF (LF_UOC .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_UOC)
  !$ACC ENTER DATA ATTACH (YD%F_UOC)
ENDIF

LF_VOC = ASSOCIATED (YD%F_VOC)
IF (LF_VOC .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_VOC)
  !$ACC ENTER DATA ATTACH (YD%F_VOC)
ENDIF

LF_OTKE = ASSOCIATED (YD%F_OTKE)
IF (LF_OTKE .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_OTKE)
  !$ACC ENTER DATA ATTACH (YD%F_OTKE)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_4RB (YD%F_GROUP)
  !$ACC ENTER DATA ATTACH (YD%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_SURFACE_VIEW_GROUP_VDIAGO3 (YD)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_VDIAGO3_MOD

IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VDIAGO3), TARGET :: YD
LOGICAL :: LF_ADVS, LF_ADVT, LF_DIFM, LF_DIFS, LF_DIFT, LF_DO, LF_GROUP, LF_HO, LF_HO_INV, LF_OTKE
LOGICAL :: LF_SWDK, LF_TRI0, LF_TRI1, LF_UOC, LF_VOC, LF_ZO, LVARIABLE_GROUP
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  CALL HOST_SURFACE_VARIABLE_GROUP_VDIAGO3 (YD%VARIABLE_GROUP)
ENDIF

LF_DIFM = ASSOCIATED (YD%F_DIFM)
IF (LF_DIFM) THEN
  CALL HOST_FIELD_3RB (YD%F_DIFM)
ENDIF

LF_DIFT = ASSOCIATED (YD%F_DIFT)
IF (LF_DIFT) THEN
  CALL HOST_FIELD_3RB (YD%F_DIFT)
ENDIF

LF_DIFS = ASSOCIATED (YD%F_DIFS)
IF (LF_DIFS) THEN
  CALL HOST_FIELD_3RB (YD%F_DIFS)
ENDIF

LF_ADVT = ASSOCIATED (YD%F_ADVT)
IF (LF_ADVT) THEN
  CALL HOST_FIELD_3RB (YD%F_ADVT)
ENDIF

LF_ADVS = ASSOCIATED (YD%F_ADVS)
IF (LF_ADVS) THEN
  CALL HOST_FIELD_3RB (YD%F_ADVS)
ENDIF

LF_TRI0 = ASSOCIATED (YD%F_TRI0)
IF (LF_TRI0) THEN
  CALL HOST_FIELD_3RB (YD%F_TRI0)
ENDIF

LF_TRI1 = ASSOCIATED (YD%F_TRI1)
IF (LF_TRI1) THEN
  CALL HOST_FIELD_3RB (YD%F_TRI1)
ENDIF

LF_SWDK = ASSOCIATED (YD%F_SWDK)
IF (LF_SWDK) THEN
  CALL HOST_FIELD_3RB (YD%F_SWDK)
ENDIF

LF_ZO = ASSOCIATED (YD%F_ZO)
IF (LF_ZO) THEN
  CALL HOST_FIELD_3RB (YD%F_ZO)
ENDIF

LF_HO = ASSOCIATED (YD%F_HO)
IF (LF_HO) THEN
  CALL HOST_FIELD_3RB (YD%F_HO)
ENDIF

LF_DO = ASSOCIATED (YD%F_DO)
IF (LF_DO) THEN
  CALL HOST_FIELD_3RB (YD%F_DO)
ENDIF

LF_HO_INV = ASSOCIATED (YD%F_HO_INV)
IF (LF_HO_INV) THEN
  CALL HOST_FIELD_3RB (YD%F_HO_INV)
ENDIF

LF_UOC = ASSOCIATED (YD%F_UOC)
IF (LF_UOC) THEN
  CALL HOST_FIELD_3RB (YD%F_UOC)
ENDIF

LF_VOC = ASSOCIATED (YD%F_VOC)
IF (LF_VOC) THEN
  CALL HOST_FIELD_3RB (YD%F_VOC)
ENDIF

LF_OTKE = ASSOCIATED (YD%F_OTKE)
IF (LF_OTKE) THEN
  CALL HOST_FIELD_3RB (YD%F_OTKE)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_4RB (YD%F_GROUP)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_SURFACE_VIEW_GROUP_VDIAGO3 (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_VDIAGO3_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_VDIAGO3), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_ADVS, LF_ADVT, LF_DIFM, LF_DIFS, LF_DIFT, LF_DO, LF_GROUP, LF_HO, LF_HO_INV, LF_OTKE
LOGICAL :: LF_SWDK, LF_TRI0, LF_TRI1, LF_UOC, LF_VOC, LF_ZO, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
  CALL WIPE_SURFACE_VARIABLE_GROUP_VDIAGO3 (YD%VARIABLE_GROUP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
ENDIF

LF_DIFM = ASSOCIATED (YD%F_DIFM)
IF (LF_DIFM .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DIFM)
ENDIF

LF_DIFT = ASSOCIATED (YD%F_DIFT)
IF (LF_DIFT .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DIFT)
ENDIF

LF_DIFS = ASSOCIATED (YD%F_DIFS)
IF (LF_DIFS .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DIFS)
ENDIF

LF_ADVT = ASSOCIATED (YD%F_ADVT)
IF (LF_ADVT .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_ADVT)
ENDIF

LF_ADVS = ASSOCIATED (YD%F_ADVS)
IF (LF_ADVS .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_ADVS)
ENDIF

LF_TRI0 = ASSOCIATED (YD%F_TRI0)
IF (LF_TRI0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_TRI0)
ENDIF

LF_TRI1 = ASSOCIATED (YD%F_TRI1)
IF (LF_TRI1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_TRI1)
ENDIF

LF_SWDK = ASSOCIATED (YD%F_SWDK)
IF (LF_SWDK .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_SWDK)
ENDIF

LF_ZO = ASSOCIATED (YD%F_ZO)
IF (LF_ZO .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_ZO)
ENDIF

LF_HO = ASSOCIATED (YD%F_HO)
IF (LF_HO .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_HO)
ENDIF

LF_DO = ASSOCIATED (YD%F_DO)
IF (LF_DO .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DO)
ENDIF

LF_HO_INV = ASSOCIATED (YD%F_HO_INV)
IF (LF_HO_INV .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_HO_INV)
ENDIF

LF_UOC = ASSOCIATED (YD%F_UOC)
IF (LF_UOC .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_UOC)
ENDIF

LF_VOC = ASSOCIATED (YD%F_VOC)
IF (LF_VOC .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_VOC)
ENDIF

LF_OTKE = ASSOCIATED (YD%F_OTKE)
IF (LF_OTKE .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_OTKE)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (YD%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
