MODULE UTIL_TYPE_SFL_RESVR_MOD

USE SURFACE_FIELDS_MIX, ONLY : TYPE_SFL_RESVR

INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_SFL_RESVR
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_SFL_RESVR
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TYPE_SFL_RESVR
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TYPE_SFL_RESVR
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TYPE_SFL_RESVR
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TYPE_SFL_RESVR
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TYPE_SFL_RESVR (KLUN, YD)
USE UTIL_TYPE_SURF_MTL_2D_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_SFL_RESVR), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYFC, LYFP1, LYIC, LYRR, LYT, LYW
LYT = ASSOCIATED (YD%YT)
WRITE (KLUN) LYT
IF (LYT) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YT)
ENDIF
LYW = ASSOCIATED (YD%YW)
WRITE (KLUN) LYW
IF (LYW) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YW)
ENDIF
LYFC = ASSOCIATED (YD%YFC)
WRITE (KLUN) LYFC
IF (LYFC) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YFC)
ENDIF
LYIC = ASSOCIATED (YD%YIC)
WRITE (KLUN) LYIC
IF (LYIC) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YIC)
ENDIF
LYFP1 = ASSOCIATED (YD%YFP1)
WRITE (KLUN) LYFP1
IF (LYFP1) THEN
  CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YFP1)
ENDIF
LYRR = ASSOCIATED (YD%YRR)
WRITE (KLUN) LYRR
IF (LYRR) THEN
  WRITE (KLUN) LBOUND (YD%YRR)
  WRITE (KLUN) UBOUND (YD%YRR)
  DO J1 = LBOUND (YD%YRR, 1), UBOUND (YD%YRR, 1)
    CALL SAVE_TYPE_SURF_MTL_2D (KLUN, YD%YRR (J1))
  ENDDO
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TYPE_SFL_RESVR (KLUN, YD)
USE UTIL_TYPE_SURF_MTL_2D_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TYPE_SFL_RESVR), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYFC, LYFP1, LYIC, LYRR, LYT, LYW
READ (KLUN) LYT
IF (LYT) THEN
  ALLOCATE (YD%YT)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YT)
ELSE
  NULLIFY (YD%YT)
ENDIF
READ (KLUN) LYW
IF (LYW) THEN
  ALLOCATE (YD%YW)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YW)
ELSE
  NULLIFY (YD%YW)
ENDIF
READ (KLUN) LYFC
IF (LYFC) THEN
  ALLOCATE (YD%YFC)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YFC)
ELSE
  NULLIFY (YD%YFC)
ENDIF
READ (KLUN) LYIC
IF (LYIC) THEN
  ALLOCATE (YD%YIC)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YIC)
ELSE
  NULLIFY (YD%YIC)
ENDIF
READ (KLUN) LYFP1
IF (LYFP1) THEN
  ALLOCATE (YD%YFP1)
  CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YFP1)
ELSE
  NULLIFY (YD%YFP1)
ENDIF
READ (KLUN) LYRR
IF (LYRR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRR (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRR, 1), UBOUND (YD%YRR, 1)
    CALL LOAD_TYPE_SURF_MTL_2D (KLUN, YD%YRR (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRR)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TYPE_SFL_RESVR (YD, LDCREATED, LDFIELDAPI)
USE UTIL_TYPE_SURF_MTL_2D_MOD
IMPLICIT NONE
TYPE (TYPE_SFL_RESVR), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LYFC, LYFP1, LYIC, LYRR, LYT, LYW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LYT = ASSOCIATED (YD%YT)
IF (LYT) THEN
  !$ACC ENTER DATA CREATE (YD%YT)
  !$ACC UPDATE DEVICE (YD%YT)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YT)
ENDIF

LYW = ASSOCIATED (YD%YW)
IF (LYW) THEN
  !$ACC ENTER DATA CREATE (YD%YW)
  !$ACC UPDATE DEVICE (YD%YW)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YW, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YW)
ENDIF

LYFC = ASSOCIATED (YD%YFC)
IF (LYFC) THEN
  !$ACC ENTER DATA CREATE (YD%YFC)
  !$ACC UPDATE DEVICE (YD%YFC)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YFC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YFC)
ENDIF

LYIC = ASSOCIATED (YD%YIC)
IF (LYIC) THEN
  !$ACC ENTER DATA CREATE (YD%YIC)
  !$ACC UPDATE DEVICE (YD%YIC)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YIC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YIC)
ENDIF

LYFP1 = ASSOCIATED (YD%YFP1)
IF (LYFP1) THEN
  !$ACC ENTER DATA CREATE (YD%YFP1)
  !$ACC UPDATE DEVICE (YD%YFP1)
  CALL COPY_TYPE_SURF_MTL_2D (YD%YFP1, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%YFP1)
ENDIF

LYRR = ASSOCIATED (YD%YRR)
IF (LYRR) THEN
  !$ACC ENTER DATA CREATE (YD%YRR)
  !$ACC UPDATE DEVICE (YD%YRR)
  DO J1 = LBOUND (YD%YRR, 1), UBOUND (YD%YRR, 1)
    CALL COPY_TYPE_SURF_MTL_2D (YD%YRR (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%YRR)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TYPE_SFL_RESVR (YD)
USE UTIL_TYPE_SURF_MTL_2D_MOD

IMPLICIT NONE
TYPE (TYPE_SFL_RESVR), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYFC, LYFP1, LYIC, LYRR, LYT, LYW
LYT = ASSOCIATED (YD%YT)
IF (LYT) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YT)
ENDIF

LYW = ASSOCIATED (YD%YW)
IF (LYW) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YW)
ENDIF

LYFC = ASSOCIATED (YD%YFC)
IF (LYFC) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YFC)
ENDIF

LYIC = ASSOCIATED (YD%YIC)
IF (LYIC) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YIC)
ENDIF

LYFP1 = ASSOCIATED (YD%YFP1)
IF (LYFP1) THEN
  CALL HOST_TYPE_SURF_MTL_2D (YD%YFP1)
ENDIF

LYRR = ASSOCIATED (YD%YRR)
IF (LYRR) THEN
  DO J1 = LBOUND (YD%YRR, 1), UBOUND (YD%YRR, 1)
    CALL HOST_TYPE_SURF_MTL_2D (YD%YRR (J1))
  ENDDO
ENDIF

END SUBROUTINE

     

SUBROUTINE CRC64_TYPE_SFL_RESVR (YD, KLUN, CDPATH)
USE UTIL_TYPE_SURF_MTL_2D_MOD
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TYPE_SFL_RESVR), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
INTEGER :: J1
LOGICAL :: LYFC, LYFP1, LYIC, LYRR, LYT, LYW
LYT = ASSOCIATED (YD%YT)
IF (LYT) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YT, KLUN, CDPATH//'%YT'//TRIM(CLIND))
ENDIF

LYW = ASSOCIATED (YD%YW)
IF (LYW) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YW, KLUN, CDPATH//'%YW'//TRIM(CLIND))
ENDIF

LYFC = ASSOCIATED (YD%YFC)
IF (LYFC) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YFC, KLUN, CDPATH//'%YFC'//TRIM(CLIND))
ENDIF

LYIC = ASSOCIATED (YD%YIC)
IF (LYIC) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YIC, KLUN, CDPATH//'%YIC'//TRIM(CLIND))
ENDIF

LYFP1 = ASSOCIATED (YD%YFP1)
IF (LYFP1) THEN
  CLIND = ''
  CALL CRC64_TYPE_SURF_MTL_2D (YD%YFP1, KLUN, CDPATH//'%YFP1'//TRIM(CLIND))
ENDIF

LYRR = ASSOCIATED (YD%YRR)
IF (LYRR) THEN
  DO J1 = LBOUND (YD%YRR, 1), UBOUND (YD%YRR, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL CRC64_TYPE_SURF_MTL_2D (YD%YRR (J1), KLUN, CDPATH//'%YRR'//TRIM(CLIND))
  ENDDO
ENDIF

END SUBROUTINE

SUBROUTINE WIPE_TYPE_SFL_RESVR (YD, LDDELETED, LDFIELDAPI)
USE UTIL_TYPE_SURF_MTL_2D_MOD
IMPLICIT NONE
TYPE (TYPE_SFL_RESVR), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LYFC, LYFP1, LYIC, LYRR, LYT, LYW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LYT = ASSOCIATED (YD%YT)
IF (LYT) THEN
  !$ACC EXIT DATA DETACH (YD%YT)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YT, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YT)
ENDIF

LYW = ASSOCIATED (YD%YW)
IF (LYW) THEN
  !$ACC EXIT DATA DETACH (YD%YW)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YW, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YW)
ENDIF

LYFC = ASSOCIATED (YD%YFC)
IF (LYFC) THEN
  !$ACC EXIT DATA DETACH (YD%YFC)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YFC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YFC)
ENDIF

LYIC = ASSOCIATED (YD%YIC)
IF (LYIC) THEN
  !$ACC EXIT DATA DETACH (YD%YIC)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YIC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YIC)
ENDIF

LYFP1 = ASSOCIATED (YD%YFP1)
IF (LYFP1) THEN
  !$ACC EXIT DATA DETACH (YD%YFP1)
  CALL WIPE_TYPE_SURF_MTL_2D (YD%YFP1, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%YFP1)
ENDIF

LYRR = ASSOCIATED (YD%YRR)
IF (LYRR) THEN
  !$ACC EXIT DATA DETACH (YD%YRR)
  DO J1 = LBOUND (YD%YRR, 1), UBOUND (YD%YRR, 1)
    CALL WIPE_TYPE_SURF_MTL_2D (YD%YRR (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%YRR)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
