MODULE UTIL_CPLNG_FLD_TYPE_MOD

USE CPLNG_TYPES_MOD, ONLY : CPLNG_FLD_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPLNG_FLD_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPLNG_FLD_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_CPLNG_FLD_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_CPLNG_FLD_TYPE
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_CPLNG_FLD_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPLNG_FLD_TYPE
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_CPLNG_FLD_TYPE
END INTERFACE


CONTAINS

SUBROUTINE SAVE_CPLNG_FLD_TYPE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LD, LID
LID = ALLOCATED (YD%ID)
WRITE (KLUN) LID
IF (LID) THEN
  WRITE (KLUN) LBOUND (YD%ID)
  WRITE (KLUN) UBOUND (YD%ID)
  WRITE (KLUN) YD%ID
ENDIF
WRITE (KLUN) YD%NAME
WRITE (KLUN) YD%TYPE
WRITE (KLUN) YD%INOUT
WRITE (KLUN) YD%STAGE
WRITE (KLUN) YD%NUM_LVL
WRITE (KLUN) YD%NUM_CAT
LD = ALLOCATED (YD%D)
WRITE (KLUN) LD
IF (LD) THEN
  WRITE (KLUN) LBOUND (YD%D)
  WRITE (KLUN) UBOUND (YD%D)
  WRITE (KLUN) YD%D
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_CPLNG_FLD_TYPE (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPLNG_FLD_TYPE), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LD, LID
READ (KLUN) LID
IF (LID) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%ID (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%ID
ENDIF
READ (KLUN) YD%NAME
READ (KLUN) YD%TYPE
READ (KLUN) YD%INOUT
READ (KLUN) YD%STAGE
READ (KLUN) YD%NUM_LVL
READ (KLUN) YD%NUM_CAT
READ (KLUN) LD
IF (LD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  READ (KLUN) YD%D
ENDIF
END SUBROUTINE


SUBROUTINE COPY_CPLNG_FLD_TYPE (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LD, LID

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LID = ALLOCATED (YD%ID)
IF (LID) THEN
  !$ACC ENTER DATA CREATE (YD%ID)
  !$ACC UPDATE DEVICE (YD%ID)
  !$ACC ENTER DATA ATTACH (YD%ID)
ENDIF







LD = ALLOCATED (YD%D)
IF (LD) THEN
  !$ACC ENTER DATA CREATE (YD%D)
  !$ACC UPDATE DEVICE (YD%D)
  !$ACC ENTER DATA ATTACH (YD%D)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_CPLNG_FLD_TYPE (YD)

IMPLICIT NONE
TYPE (CPLNG_FLD_TYPE), TARGET :: YD
LOGICAL :: LD, LID








END SUBROUTINE

     

SUBROUTINE CRC64_CPLNG_FLD_TYPE (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (CPLNG_FLD_TYPE), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LD, LID
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%ID), CDPATH//'%ID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NAME), CDPATH//'%NAME'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%TYPE), CDPATH//'%TYPE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%INOUT), CDPATH//'%INOUT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%STAGE), CDPATH//'%STAGE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NUM_LVL), CDPATH//'%NUM_LVL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NUM_CAT), CDPATH//'%NUM_CAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%D), CDPATH//'%D'

END SUBROUTINE

SUBROUTINE WIPE_CPLNG_FLD_TYPE (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LD, LID

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LID = ALLOCATED (YD%ID)
IF (LID) THEN
  !$ACC EXIT DATA DETACH (YD%ID)
  !$ACC EXIT DATA DETACH (YD%ID)
ENDIF







LD = ALLOCATED (YD%D)
IF (LD) THEN
  !$ACC EXIT DATA DETACH (YD%D)
  !$ACC EXIT DATA DETACH (YD%D)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_CPLNG_FLD_TYPE (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (CPLNG_FLD_TYPE),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LD, LID

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LID = ALLOCATED (YD%ID)
IF (LID) THEN
  ISIZE = KIND (YD%ID) * SIZE (YD%ID)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%ID'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%NAME) * LEN (YD%NAME)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NAME'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TYPE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TYPE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%INOUT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%INOUT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%STAGE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%STAGE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NUM_LVL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NUM_LVL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NUM_CAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NUM_CAT'
ENDIF
KSIZE = KSIZE + ISIZE
LD = ALLOCATED (YD%D)
IF (LD) THEN
  ISIZE = KIND (YD%D) * SIZE (YD%D)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%D'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
