MODULE UTIL_TDIM_MOD

USE YOMDIM, ONLY : TDIM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDIM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDIM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDIM
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TDIM
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TDIM
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDIM
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TDIM
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TDIM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDIM), INTENT (IN), TARGET :: YD
LOGICAL :: LNDLUNL, LNDLUXL
WRITE (KLUN) YD%NDGLG
WRITE (KLUN) YD%NDGLL
WRITE (KLUN) YD%NDGNH
WRITE (KLUN) YD%NDGSUR
WRITE (KLUN) YD%NDGSAG
WRITE (KLUN) YD%NDGSAL
WRITE (KLUN) YD%NDGSAH
WRITE (KLUN) YD%NDGSAFPH
WRITE (KLUN) YD%NDGENG
WRITE (KLUN) YD%NDGENL
WRITE (KLUN) YD%NDGENH
WRITE (KLUN) YD%NDGENFPH
WRITE (KLUN) YD%NDGUNG
WRITE (KLUN) YD%NDGUXG
WRITE (KLUN) YD%NDGUNL
WRITE (KLUN) YD%NDGUXL
WRITE (KLUN) YD%NDLON
WRITE (KLUN) YD%NDSUR1
WRITE (KLUN) YD%NSTENCILWIDE
WRITE (KLUN) YD%NDLSUR
WRITE (KLUN) YD%NDLSM
WRITE (KLUN) YD%NDLUNG
WRITE (KLUN) YD%NDLUXG
LNDLUNL = ALLOCATED (YD%NDLUNL)
WRITE (KLUN) LNDLUNL
IF (LNDLUNL) THEN
  WRITE (KLUN) LBOUND (YD%NDLUNL)
  WRITE (KLUN) UBOUND (YD%NDLUNL)
  WRITE (KLUN) YD%NDLUNL
ENDIF
LNDLUXL = ALLOCATED (YD%NDLUXL)
WRITE (KLUN) LNDLUXL
IF (LNDLUXL) THEN
  WRITE (KLUN) LBOUND (YD%NDLUXL)
  WRITE (KLUN) UBOUND (YD%NDLUXL)
  WRITE (KLUN) YD%NDLUXL
ENDIF
WRITE (KLUN) YD%NPROMA
WRITE (KLUN) YD%NPROMM
WRITE (KLUN) YD%NPROMM9
WRITE (KLUN) YD%NPROMNH
WRITE (KLUN) YD%NGPBLKS
WRITE (KLUN) YD%LOPTPROMA
WRITE (KLUN) YD%NRESOL
WRITE (KLUN) YD%NSMAX
WRITE (KLUN) YD%NMSMAX
WRITE (KLUN) YD%NVARMAX
WRITE (KLUN) YD%NSEFRE
WRITE (KLUN) YD%NSPECG
WRITE (KLUN) YD%NSPEC2G
WRITE (KLUN) YD%NSPEC
WRITE (KLUN) YD%NSPEC2
WRITE (KLUN) YD%NSPEC2MX
WRITE (KLUN) YD%NCMAX
WRITE (KLUN) YD%NUMP
WRITE (KLUN) YD%NUMCP
END SUBROUTINE

SUBROUTINE LOAD_TDIM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDIM), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LNDLUNL, LNDLUXL
READ (KLUN) YD%NDGLG
READ (KLUN) YD%NDGLL
READ (KLUN) YD%NDGNH
READ (KLUN) YD%NDGSUR
READ (KLUN) YD%NDGSAG
READ (KLUN) YD%NDGSAL
READ (KLUN) YD%NDGSAH
READ (KLUN) YD%NDGSAFPH
READ (KLUN) YD%NDGENG
READ (KLUN) YD%NDGENL
READ (KLUN) YD%NDGENH
READ (KLUN) YD%NDGENFPH
READ (KLUN) YD%NDGUNG
READ (KLUN) YD%NDGUXG
READ (KLUN) YD%NDGUNL
READ (KLUN) YD%NDGUXL
READ (KLUN) YD%NDLON
READ (KLUN) YD%NDSUR1
READ (KLUN) YD%NSTENCILWIDE
READ (KLUN) YD%NDLSUR
READ (KLUN) YD%NDLSM
READ (KLUN) YD%NDLUNG
READ (KLUN) YD%NDLUXG
READ (KLUN) LNDLUNL
IF (LNDLUNL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NDLUNL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NDLUNL
ENDIF
READ (KLUN) LNDLUXL
IF (LNDLUXL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NDLUXL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NDLUXL
ENDIF
READ (KLUN) YD%NPROMA
READ (KLUN) YD%NPROMM
READ (KLUN) YD%NPROMM9
READ (KLUN) YD%NPROMNH
READ (KLUN) YD%NGPBLKS
READ (KLUN) YD%LOPTPROMA
READ (KLUN) YD%NRESOL
READ (KLUN) YD%NSMAX
READ (KLUN) YD%NMSMAX
READ (KLUN) YD%NVARMAX
READ (KLUN) YD%NSEFRE
READ (KLUN) YD%NSPECG
READ (KLUN) YD%NSPEC2G
READ (KLUN) YD%NSPEC
READ (KLUN) YD%NSPEC2
READ (KLUN) YD%NSPEC2MX
READ (KLUN) YD%NCMAX
READ (KLUN) YD%NUMP
READ (KLUN) YD%NUMCP
END SUBROUTINE


SUBROUTINE COPY_TDIM (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDIM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNDLUNL, LNDLUXL

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF























LNDLUNL = ALLOCATED (YD%NDLUNL)
IF (LNDLUNL) THEN
  !$ACC ENTER DATA CREATE (YD%NDLUNL)
  !$ACC UPDATE DEVICE (YD%NDLUNL)
  !$ACC ENTER DATA ATTACH (YD%NDLUNL)
ENDIF

LNDLUXL = ALLOCATED (YD%NDLUXL)
IF (LNDLUXL) THEN
  !$ACC ENTER DATA CREATE (YD%NDLUXL)
  !$ACC UPDATE DEVICE (YD%NDLUXL)
  !$ACC ENTER DATA ATTACH (YD%NDLUXL)
ENDIF




















END SUBROUTINE

SUBROUTINE HOST_TDIM (YD)

IMPLICIT NONE
TYPE (TDIM), TARGET :: YD
LOGICAL :: LNDLUNL, LNDLUXL












































END SUBROUTINE

     

SUBROUTINE CRC64_TDIM (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TDIM), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LNDLUNL, LNDLUXL
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGLG), CDPATH//'%NDGLG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGLL), CDPATH//'%NDGLL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGNH), CDPATH//'%NDGNH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGSUR), CDPATH//'%NDGSUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGSAG), CDPATH//'%NDGSAG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGSAL), CDPATH//'%NDGSAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGSAH), CDPATH//'%NDGSAH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGSAFPH), CDPATH//'%NDGSAFPH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGENG), CDPATH//'%NDGENG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGENL), CDPATH//'%NDGENL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGENH), CDPATH//'%NDGENH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGENFPH), CDPATH//'%NDGENFPH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGUNG), CDPATH//'%NDGUNG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGUXG), CDPATH//'%NDGUXG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGUNL), CDPATH//'%NDGUNL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGUXL), CDPATH//'%NDGUXL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDLON), CDPATH//'%NDLON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDSUR1), CDPATH//'%NDSUR1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSTENCILWIDE), CDPATH//'%NSTENCILWIDE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDLSUR), CDPATH//'%NDLSUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDLSM), CDPATH//'%NDLSM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDLUNG), CDPATH//'%NDLUNG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDLUXG), CDPATH//'%NDLUXG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDLUNL), CDPATH//'%NDLUNL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDLUXL), CDPATH//'%NDLUXL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPROMA), CDPATH//'%NPROMA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPROMM), CDPATH//'%NPROMM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPROMM9), CDPATH//'%NPROMM9'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPROMNH), CDPATH//'%NPROMNH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGPBLKS), CDPATH//'%NGPBLKS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LOPTPROMA), CDPATH//'%LOPTPROMA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NRESOL), CDPATH//'%NRESOL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSMAX), CDPATH//'%NSMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NMSMAX), CDPATH//'%NMSMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NVARMAX), CDPATH//'%NVARMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSEFRE), CDPATH//'%NSEFRE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPECG), CDPATH//'%NSPECG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC2G), CDPATH//'%NSPEC2G'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC), CDPATH//'%NSPEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC2), CDPATH//'%NSPEC2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC2MX), CDPATH//'%NSPEC2MX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NCMAX), CDPATH//'%NCMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NUMP), CDPATH//'%NUMP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NUMCP), CDPATH//'%NUMCP'

END SUBROUTINE

SUBROUTINE WIPE_TDIM (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDIM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LNDLUNL, LNDLUXL

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF























LNDLUNL = ALLOCATED (YD%NDLUNL)
IF (LNDLUNL) THEN
  !$ACC EXIT DATA DETACH (YD%NDLUNL)
  !$ACC EXIT DATA DETACH (YD%NDLUNL)
ENDIF

LNDLUXL = ALLOCATED (YD%NDLUXL)
IF (LNDLUXL) THEN
  !$ACC EXIT DATA DETACH (YD%NDLUXL)
  !$ACC EXIT DATA DETACH (YD%NDLUXL)
ENDIF




















LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TDIM (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TDIM),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LNDLUNL, LNDLUXL

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%NDGLG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGLG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGLL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGLL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGNH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGSUR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGSAG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGSAL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGSAH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGSAFPH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAFPH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGENG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGENL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGENH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGENFPH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENFPH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGUNG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGUNG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGUXG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGUXG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGUNL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGUNL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGUXL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGUXL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDLON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDLON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDSUR1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDSUR1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSTENCILWIDE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSTENCILWIDE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDLSUR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDLSUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDLSM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDLSM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDLUNG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDLUNG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDLUXG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDLUXG'
ENDIF
KSIZE = KSIZE + ISIZE
LNDLUNL = ALLOCATED (YD%NDLUNL)
IF (LNDLUNL) THEN
  ISIZE = KIND (YD%NDLUNL) * SIZE (YD%NDLUNL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NDLUNL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNDLUXL = ALLOCATED (YD%NDLUXL)
IF (LNDLUXL) THEN
  ISIZE = KIND (YD%NDLUXL) * SIZE (YD%NDLUXL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NDLUXL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%NPROMA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPROMA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPROMM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPROMM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPROMM9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPROMM9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPROMNH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPROMNH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NGPBLKS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGPBLKS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LOPTPROMA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LOPTPROMA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NRESOL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NRESOL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NMSMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NMSMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NVARMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NVARMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSEFRE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSEFRE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPECG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPECG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC2G)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2G'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC2MX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2MX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NUMP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NUMP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NUMCP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NUMCP'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
