MODULE UTIL_TYPE_SURF_MTL_MOD

USE SURFACE_FIELDS_MIX, ONLY : TYPE_SURF_MTL

INTERFACE SAVE
MODULE PROCEDURE SAVE_TYPE_SURF_MTL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TYPE_SURF_MTL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TYPE_SURF_MTL
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TYPE_SURF_MTL
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TYPE_SURF_MTL
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TYPE_SURF_MTL
END INTERFACE



CONTAINS

SUBROUTINE SAVE_TYPE_SURF_MTL (SELF, KLUN)

IMPLICIT NONE
TYPE (TYPE_SURF_MTL), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%MP
WRITE (KLUN) SELF%MP0
WRITE (KLUN) SELF%MP9
WRITE (KLUN) SELF%MP1
WRITE (KLUN) SELF%ITRAJ
WRITE (KLUN) SELF%IBUGFINDER
WRITE (KLUN) SELF%LSET
END SUBROUTINE

SUBROUTINE LOAD_TYPE_SURF_MTL (SELF, KLUN)

IMPLICIT NONE
TYPE (TYPE_SURF_MTL), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%MP
READ (KLUN) SELF%MP0
READ (KLUN) SELF%MP9
READ (KLUN) SELF%MP1
READ (KLUN) SELF%ITRAJ
READ (KLUN) SELF%IBUGFINDER
READ (KLUN) SELF%LSET
END SUBROUTINE


SUBROUTINE COPY_TYPE_SURF_MTL (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TYPE_SURF_MTL), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TYPE_SURF_MTL (SELF)

IMPLICIT NONE
TYPE (TYPE_SURF_MTL), TARGET :: SELF


END SUBROUTINE

     

SUBROUTINE CRC64_TYPE_SURF_MTL (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TYPE_SURF_MTL), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MP), CDPATH//'%MP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MP0), CDPATH//'%MP0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MP9), CDPATH//'%MP9'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MP1), CDPATH//'%MP1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ITRAJ), CDPATH//'%ITRAJ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IBUGFINDER), CDPATH//'%IBUGFINDER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LSET), CDPATH//'%LSET'

END SUBROUTINE

SUBROUTINE WIPE_TYPE_SURF_MTL (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TYPE_SURF_MTL), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
