MODULE UTIL_SURFACE_VARIABLE_GROUP_WAVES_MOD

USE SURFACE_VARIABLES_MOD, ONLY : SURFACE_VARIABLE_GROUP_WAVES



INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VARIABLE_GROUP_WAVES
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_SURFACE_VARIABLE_GROUP_WAVES
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VARIABLE_GROUP_WAVES
END INTERFACE



CONTAINS





SUBROUTINE COPY_SURFACE_VARIABLE_GROUP_WAVES (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_2RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_WAVES), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
CALL COPY_VARIABLE_2RB (YD%VCHAR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_VARIABLE_2RB (YD%VCHARHQ, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_VARIABLE_2RB (YD%VUSTOKES, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_VARIABLE_2RB (YD%VVSTOKES, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_VARIABLE_2RB (YD%VTAUOCX, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_VARIABLE_2RB (YD%VTAUOCY, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_VARIABLE_2RB (YD%VPHIOC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_VARIABLE_2RB (YD%VWSEMEAN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_VARIABLE_2RB (YD%VWSFMEAN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_GROUP)
  !$ACC ENTER DATA ATTACH (YD%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_SURFACE_VARIABLE_GROUP_WAVES (YD)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_2RB_MOD

IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_WAVES), TARGET :: YD
LOGICAL :: LF_GROUP
CALL HOST_VARIABLE_2RB (YD%VCHAR)

CALL HOST_VARIABLE_2RB (YD%VCHARHQ)

CALL HOST_VARIABLE_2RB (YD%VUSTOKES)

CALL HOST_VARIABLE_2RB (YD%VVSTOKES)

CALL HOST_VARIABLE_2RB (YD%VTAUOCX)

CALL HOST_VARIABLE_2RB (YD%VTAUOCY)

CALL HOST_VARIABLE_2RB (YD%VPHIOC)

CALL HOST_VARIABLE_2RB (YD%VWSEMEAN)

CALL HOST_VARIABLE_2RB (YD%VWSFMEAN)

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (YD%F_GROUP)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_SURFACE_VARIABLE_GROUP_WAVES (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_2RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_WAVES), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL WIPE_VARIABLE_2RB (YD%VCHAR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_VARIABLE_2RB (YD%VCHARHQ, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_VARIABLE_2RB (YD%VUSTOKES, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_VARIABLE_2RB (YD%VVSTOKES, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_VARIABLE_2RB (YD%VTAUOCX, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_VARIABLE_2RB (YD%VTAUOCY, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_VARIABLE_2RB (YD%VPHIOC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_VARIABLE_2RB (YD%VWSEMEAN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_VARIABLE_2RB (YD%VWSFMEAN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
