MODULE UTIL_TCDDH_MOD

USE YOMCDDH, ONLY : TCDDH

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCDDH
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCDDH
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCDDH
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TCDDH
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TCDDH
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCDDH
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TCDDH
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TCDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCDDH), INTENT (IN), TARGET :: YD
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS
LCADHTLS = ALLOCATED (YD%CADHTLS)
WRITE (KLUN) LCADHTLS
IF (LCADHTLS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTLS)
  WRITE (KLUN) UBOUND (YD%CADHTLS)
  WRITE (KLUN) YD%CADHTLS
ENDIF
LCADHTSS = ALLOCATED (YD%CADHTSS)
WRITE (KLUN) LCADHTSS
IF (LCADHTSS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTSS)
  WRITE (KLUN) UBOUND (YD%CADHTSS)
  WRITE (KLUN) YD%CADHTSS
ENDIF
LCADHTTS = ALLOCATED (YD%CADHTTS)
WRITE (KLUN) LCADHTTS
IF (LCADHTTS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTTS)
  WRITE (KLUN) UBOUND (YD%CADHTTS)
  WRITE (KLUN) YD%CADHTTS
ENDIF
LCADHTIS = ALLOCATED (YD%CADHTIS)
WRITE (KLUN) LCADHTIS
IF (LCADHTIS) THEN
  WRITE (KLUN) LBOUND (YD%CADHTIS)
  WRITE (KLUN) UBOUND (YD%CADHTIS)
  WRITE (KLUN) YD%CADHTIS
ENDIF
LCADHSSS = ALLOCATED (YD%CADHSSS)
WRITE (KLUN) LCADHSSS
IF (LCADHSSS) THEN
  WRITE (KLUN) LBOUND (YD%CADHSSS)
  WRITE (KLUN) UBOUND (YD%CADHSSS)
  WRITE (KLUN) YD%CADHSSS
ENDIF
LCADHIIS = ALLOCATED (YD%CADHIIS)
WRITE (KLUN) LCADHIIS
IF (LCADHIIS) THEN
  WRITE (KLUN) LBOUND (YD%CADHIIS)
  WRITE (KLUN) UBOUND (YD%CADHIIS)
  WRITE (KLUN) YD%CADHIIS
ENDIF
LCADHWLS = ALLOCATED (YD%CADHWLS)
WRITE (KLUN) LCADHWLS
IF (LCADHWLS) THEN
  WRITE (KLUN) LBOUND (YD%CADHWLS)
  WRITE (KLUN) UBOUND (YD%CADHWLS)
  WRITE (KLUN) YD%CADHWLS
ENDIF
LCADHFSS = ALLOCATED (YD%CADHFSS)
WRITE (KLUN) LCADHFSS
IF (LCADHFSS) THEN
  WRITE (KLUN) LBOUND (YD%CADHFSS)
  WRITE (KLUN) UBOUND (YD%CADHFSS)
  WRITE (KLUN) YD%CADHFSS
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TCDDH (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCDDH), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS
READ (KLUN) LCADHTLS
IF (LCADHTLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTLS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTLS
ENDIF
READ (KLUN) LCADHTSS
IF (LCADHTSS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTSS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTSS
ENDIF
READ (KLUN) LCADHTTS
IF (LCADHTTS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTTS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTTS
ENDIF
READ (KLUN) LCADHTIS
IF (LCADHTIS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHTIS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHTIS
ENDIF
READ (KLUN) LCADHSSS
IF (LCADHSSS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHSSS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHSSS
ENDIF
READ (KLUN) LCADHIIS
IF (LCADHIIS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHIIS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHIIS
ENDIF
READ (KLUN) LCADHWLS
IF (LCADHWLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHWLS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHWLS
ENDIF
READ (KLUN) LCADHFSS
IF (LCADHFSS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%CADHFSS (IL1(1):IU1(1)))
  READ (KLUN) YD%CADHFSS
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TCDDH (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCDDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LCADHTLS = ALLOCATED (YD%CADHTLS)
IF (LCADHTLS) THEN
  !$ACC ENTER DATA CREATE (YD%CADHTLS)
  !$ACC UPDATE DEVICE (YD%CADHTLS)
  !$ACC ENTER DATA ATTACH (YD%CADHTLS)
ENDIF

LCADHTSS = ALLOCATED (YD%CADHTSS)
IF (LCADHTSS) THEN
  !$ACC ENTER DATA CREATE (YD%CADHTSS)
  !$ACC UPDATE DEVICE (YD%CADHTSS)
  !$ACC ENTER DATA ATTACH (YD%CADHTSS)
ENDIF

LCADHTTS = ALLOCATED (YD%CADHTTS)
IF (LCADHTTS) THEN
  !$ACC ENTER DATA CREATE (YD%CADHTTS)
  !$ACC UPDATE DEVICE (YD%CADHTTS)
  !$ACC ENTER DATA ATTACH (YD%CADHTTS)
ENDIF

LCADHTIS = ALLOCATED (YD%CADHTIS)
IF (LCADHTIS) THEN
  !$ACC ENTER DATA CREATE (YD%CADHTIS)
  !$ACC UPDATE DEVICE (YD%CADHTIS)
  !$ACC ENTER DATA ATTACH (YD%CADHTIS)
ENDIF

LCADHSSS = ALLOCATED (YD%CADHSSS)
IF (LCADHSSS) THEN
  !$ACC ENTER DATA CREATE (YD%CADHSSS)
  !$ACC UPDATE DEVICE (YD%CADHSSS)
  !$ACC ENTER DATA ATTACH (YD%CADHSSS)
ENDIF

LCADHIIS = ALLOCATED (YD%CADHIIS)
IF (LCADHIIS) THEN
  !$ACC ENTER DATA CREATE (YD%CADHIIS)
  !$ACC UPDATE DEVICE (YD%CADHIIS)
  !$ACC ENTER DATA ATTACH (YD%CADHIIS)
ENDIF

LCADHWLS = ALLOCATED (YD%CADHWLS)
IF (LCADHWLS) THEN
  !$ACC ENTER DATA CREATE (YD%CADHWLS)
  !$ACC UPDATE DEVICE (YD%CADHWLS)
  !$ACC ENTER DATA ATTACH (YD%CADHWLS)
ENDIF

LCADHFSS = ALLOCATED (YD%CADHFSS)
IF (LCADHFSS) THEN
  !$ACC ENTER DATA CREATE (YD%CADHFSS)
  !$ACC UPDATE DEVICE (YD%CADHFSS)
  !$ACC ENTER DATA ATTACH (YD%CADHFSS)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TCDDH (YD)

IMPLICIT NONE
TYPE (TCDDH), TARGET :: YD
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS








END SUBROUTINE

     

SUBROUTINE CRC64_TCDDH (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TCDDH), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CADHTLS), CDPATH//'%CADHTLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CADHTSS), CDPATH//'%CADHTSS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CADHTTS), CDPATH//'%CADHTTS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CADHTIS), CDPATH//'%CADHTIS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CADHSSS), CDPATH//'%CADHSSS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CADHIIS), CDPATH//'%CADHIIS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CADHWLS), CDPATH//'%CADHWLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CADHFSS), CDPATH//'%CADHFSS'

END SUBROUTINE

SUBROUTINE WIPE_TCDDH (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCDDH), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LCADHTLS = ALLOCATED (YD%CADHTLS)
IF (LCADHTLS) THEN
  !$ACC EXIT DATA DETACH (YD%CADHTLS)
  !$ACC EXIT DATA DETACH (YD%CADHTLS)
ENDIF

LCADHTSS = ALLOCATED (YD%CADHTSS)
IF (LCADHTSS) THEN
  !$ACC EXIT DATA DETACH (YD%CADHTSS)
  !$ACC EXIT DATA DETACH (YD%CADHTSS)
ENDIF

LCADHTTS = ALLOCATED (YD%CADHTTS)
IF (LCADHTTS) THEN
  !$ACC EXIT DATA DETACH (YD%CADHTTS)
  !$ACC EXIT DATA DETACH (YD%CADHTTS)
ENDIF

LCADHTIS = ALLOCATED (YD%CADHTIS)
IF (LCADHTIS) THEN
  !$ACC EXIT DATA DETACH (YD%CADHTIS)
  !$ACC EXIT DATA DETACH (YD%CADHTIS)
ENDIF

LCADHSSS = ALLOCATED (YD%CADHSSS)
IF (LCADHSSS) THEN
  !$ACC EXIT DATA DETACH (YD%CADHSSS)
  !$ACC EXIT DATA DETACH (YD%CADHSSS)
ENDIF

LCADHIIS = ALLOCATED (YD%CADHIIS)
IF (LCADHIIS) THEN
  !$ACC EXIT DATA DETACH (YD%CADHIIS)
  !$ACC EXIT DATA DETACH (YD%CADHIIS)
ENDIF

LCADHWLS = ALLOCATED (YD%CADHWLS)
IF (LCADHWLS) THEN
  !$ACC EXIT DATA DETACH (YD%CADHWLS)
  !$ACC EXIT DATA DETACH (YD%CADHWLS)
ENDIF

LCADHFSS = ALLOCATED (YD%CADHFSS)
IF (LCADHFSS) THEN
  !$ACC EXIT DATA DETACH (YD%CADHFSS)
  !$ACC EXIT DATA DETACH (YD%CADHFSS)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TCDDH (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TCDDH),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LCADHFSS, LCADHIIS, LCADHSSS, LCADHTIS, LCADHTLS, LCADHTSS, LCADHTTS, LCADHWLS

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LCADHTLS = ALLOCATED (YD%CADHTLS)
IF (LCADHTLS) THEN
  ISIZE = KIND (YD%CADHTLS) * SIZE (YD%CADHTLS) * LEN (YD%CADHTLS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CADHTLS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCADHTSS = ALLOCATED (YD%CADHTSS)
IF (LCADHTSS) THEN
  ISIZE = KIND (YD%CADHTSS) * SIZE (YD%CADHTSS) * LEN (YD%CADHTSS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CADHTSS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCADHTTS = ALLOCATED (YD%CADHTTS)
IF (LCADHTTS) THEN
  ISIZE = KIND (YD%CADHTTS) * SIZE (YD%CADHTTS) * LEN (YD%CADHTTS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CADHTTS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCADHTIS = ALLOCATED (YD%CADHTIS)
IF (LCADHTIS) THEN
  ISIZE = KIND (YD%CADHTIS) * SIZE (YD%CADHTIS) * LEN (YD%CADHTIS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CADHTIS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCADHSSS = ALLOCATED (YD%CADHSSS)
IF (LCADHSSS) THEN
  ISIZE = KIND (YD%CADHSSS) * SIZE (YD%CADHSSS) * LEN (YD%CADHSSS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CADHSSS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCADHIIS = ALLOCATED (YD%CADHIIS)
IF (LCADHIIS) THEN
  ISIZE = KIND (YD%CADHIIS) * SIZE (YD%CADHIIS) * LEN (YD%CADHIIS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CADHIIS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCADHWLS = ALLOCATED (YD%CADHWLS)
IF (LCADHWLS) THEN
  ISIZE = KIND (YD%CADHWLS) * SIZE (YD%CADHWLS) * LEN (YD%CADHWLS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CADHWLS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LCADHFSS = ALLOCATED (YD%CADHFSS)
IF (LCADHFSS) THEN
  ISIZE = KIND (YD%CADHFSS) * SIZE (YD%CADHFSS) * LEN (YD%CADHFSS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%CADHFSS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
