MODULE UTIL_CPG_TNDSL_DDH_TYPE_MOD

USE CPG_DDH_TND_TYPE_MOD, ONLY : CPG_TNDSL_DDH_TYPE



INTERFACE COPY
MODULE PROCEDURE COPY_CPG_TNDSL_DDH_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_CPG_TNDSL_DDH_TYPE
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_TNDSL_DDH_TYPE
END INTERFACE



CONTAINS





SUBROUTINE COPY_CPG_TNDSL_DDH_TYPE (YD, LDCREATED, LDFIELDAPI)
USE UTIL_CPG_TNDSL_DDH_3D_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_TNDSL_DDH_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LAERAOT, LAERLISI, LAERO, LAEROCLIM, LAEROUT, LCHEM, LEDRP, LEMIS3D, LERA40, LEXT
LOGICAL :: LEZDIAG, LFORC, LGFL, LGHG, LLIMA, LNOGW, LSLDIA, LUVP, LZDATA_GFL, LZDATA_GMV
LOGICAL :: LZVIEW_GFL, LZVIEW_GMV

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LZDATA_GMV = ASSOCIATED (YD%ZDATA_GMV)
IF (LZDATA_GMV) THEN
  !$ACC ENTER DATA CREATE (YD%ZDATA_GMV)
  !$ACC UPDATE DEVICE (YD%ZDATA_GMV)
  !$ACC ENTER DATA ATTACH (YD%ZDATA_GMV)
ENDIF

LZVIEW_GMV = ASSOCIATED (YD%ZVIEW_GMV)
IF (LZVIEW_GMV) THEN
  !$ACC ENTER DATA CREATE (YD%ZVIEW_GMV)
  !$ACC UPDATE DEVICE (YD%ZVIEW_GMV)
  !$ACC ENTER DATA ATTACH (YD%ZVIEW_GMV)
ENDIF

LZDATA_GFL = ASSOCIATED (YD%ZDATA_GFL)
IF (LZDATA_GFL) THEN
  !$ACC ENTER DATA CREATE (YD%ZDATA_GFL)
  !$ACC UPDATE DEVICE (YD%ZDATA_GFL)
  !$ACC ENTER DATA ATTACH (YD%ZDATA_GFL)
ENDIF

LZVIEW_GFL = ASSOCIATED (YD%ZVIEW_GFL)
IF (LZVIEW_GFL) THEN
  !$ACC ENTER DATA CREATE (YD%ZVIEW_GFL)
  !$ACC UPDATE DEVICE (YD%ZVIEW_GFL)
  !$ACC ENTER DATA ATTACH (YD%ZVIEW_GFL)
ENDIF

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%U, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%V, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%T, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%PD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%VD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%NHX, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%Q, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%I, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%L, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%IMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%LMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%LCONV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%ICONV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%RCONV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%SCONV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%IRAD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%LRAD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%S, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%R, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%G, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%H, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%TKE, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%TTE, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%EFB1, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%EFB2, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%EFB3, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%A, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%AMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%O3, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%SRC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%MXL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%SHTUR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%FQTUR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%FSTUR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%CPF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%SPF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%CVGQ, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%QVA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LGHG = ALLOCATED (YD%GHG)
IF (LGHG) THEN
  !$ACC ENTER DATA CREATE (YD%GHG)
  !$ACC UPDATE DEVICE (YD%GHG)
  DO J1 = LBOUND (YD%GHG, 1), UBOUND (YD%GHG, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%GHG (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%GHG)
ENDIF

LCHEM = ALLOCATED (YD%CHEM)
IF (LCHEM) THEN
  !$ACC ENTER DATA CREATE (YD%CHEM)
  !$ACC UPDATE DEVICE (YD%CHEM)
  DO J1 = LBOUND (YD%CHEM, 1), UBOUND (YD%CHEM, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%CHEM (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%CHEM)
ENDIF

LAERO = ALLOCATED (YD%AERO)
IF (LAERO) THEN
  !$ACC ENTER DATA CREATE (YD%AERO)
  !$ACC UPDATE DEVICE (YD%AERO)
  DO J1 = LBOUND (YD%AERO, 1), UBOUND (YD%AERO, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%AERO (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%AERO)
ENDIF

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%LRCH4, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LFORC = ALLOCATED (YD%FORC)
IF (LFORC) THEN
  !$ACC ENTER DATA CREATE (YD%FORC)
  !$ACC UPDATE DEVICE (YD%FORC)
  DO J1 = LBOUND (YD%FORC, 1), UBOUND (YD%FORC, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%FORC (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%FORC)
ENDIF

LEZDIAG = ALLOCATED (YD%EZDIAG)
IF (LEZDIAG) THEN
  !$ACC ENTER DATA CREATE (YD%EZDIAG)
  !$ACC UPDATE DEVICE (YD%EZDIAG)
  DO J1 = LBOUND (YD%EZDIAG, 1), UBOUND (YD%EZDIAG, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%EZDIAG (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%EZDIAG)
ENDIF

LERA40 = ALLOCATED (YD%ERA40)
IF (LERA40) THEN
  !$ACC ENTER DATA CREATE (YD%ERA40)
  !$ACC UPDATE DEVICE (YD%ERA40)
  DO J1 = LBOUND (YD%ERA40, 1), UBOUND (YD%ERA40, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%ERA40 (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%ERA40)
ENDIF

LNOGW = ALLOCATED (YD%NOGW)
IF (LNOGW) THEN
  !$ACC ENTER DATA CREATE (YD%NOGW)
  !$ACC UPDATE DEVICE (YD%NOGW)
  DO J1 = LBOUND (YD%NOGW, 1), UBOUND (YD%NOGW, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%NOGW (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%NOGW)
ENDIF

LEMIS3D = ALLOCATED (YD%EMIS3D)
IF (LEMIS3D) THEN
  !$ACC ENTER DATA CREATE (YD%EMIS3D)
  !$ACC UPDATE DEVICE (YD%EMIS3D)
  DO J1 = LBOUND (YD%EMIS3D, 1), UBOUND (YD%EMIS3D, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%EMIS3D (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%EMIS3D)
ENDIF

LEDRP = ALLOCATED (YD%EDRP)
IF (LEDRP) THEN
  !$ACC ENTER DATA CREATE (YD%EDRP)
  !$ACC UPDATE DEVICE (YD%EDRP)
  DO J1 = LBOUND (YD%EDRP, 1), UBOUND (YD%EDRP, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%EDRP (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%EDRP)
ENDIF

LSLDIA = ALLOCATED (YD%SLDIA)
IF (LSLDIA) THEN
  !$ACC ENTER DATA CREATE (YD%SLDIA)
  !$ACC UPDATE DEVICE (YD%SLDIA)
  DO J1 = LBOUND (YD%SLDIA, 1), UBOUND (YD%SLDIA, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%SLDIA (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%SLDIA)
ENDIF

LAERAOT = ALLOCATED (YD%AERAOT)
IF (LAERAOT) THEN
  !$ACC ENTER DATA CREATE (YD%AERAOT)
  !$ACC UPDATE DEVICE (YD%AERAOT)
  DO J1 = LBOUND (YD%AERAOT, 1), UBOUND (YD%AERAOT, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%AERAOT (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%AERAOT)
ENDIF

LAERLISI = ALLOCATED (YD%AERLISI)
IF (LAERLISI) THEN
  !$ACC ENTER DATA CREATE (YD%AERLISI)
  !$ACC UPDATE DEVICE (YD%AERLISI)
  DO J1 = LBOUND (YD%AERLISI, 1), UBOUND (YD%AERLISI, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%AERLISI (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%AERLISI)
ENDIF

LAEROUT = ALLOCATED (YD%AEROUT)
IF (LAEROUT) THEN
  !$ACC ENTER DATA CREATE (YD%AEROUT)
  !$ACC UPDATE DEVICE (YD%AEROUT)
  DO J1 = LBOUND (YD%AEROUT, 1), UBOUND (YD%AEROUT, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%AEROUT (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%AEROUT)
ENDIF

LAEROCLIM = ALLOCATED (YD%AEROCLIM)
IF (LAEROCLIM) THEN
  !$ACC ENTER DATA CREATE (YD%AEROCLIM)
  !$ACC UPDATE DEVICE (YD%AEROCLIM)
  DO J1 = LBOUND (YD%AEROCLIM, 1), UBOUND (YD%AEROCLIM, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%AEROCLIM (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%AEROCLIM)
ENDIF

LUVP = ALLOCATED (YD%UVP)
IF (LUVP) THEN
  !$ACC ENTER DATA CREATE (YD%UVP)
  !$ACC UPDATE DEVICE (YD%UVP)
  DO J1 = LBOUND (YD%UVP, 1), UBOUND (YD%UVP, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%UVP (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%UVP)
ENDIF

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%PHYCTY, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%RSPEC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%SDSAT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%CVV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%RKTH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%RKTQV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%RKTQC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%UOM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%UAL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%DOM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%DAL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%UEN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%UNEBH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLIMA = ALLOCATED (YD%LIMA)
IF (LLIMA) THEN
  !$ACC ENTER DATA CREATE (YD%LIMA)
  !$ACC UPDATE DEVICE (YD%LIMA)
  DO J1 = LBOUND (YD%LIMA, 1), UBOUND (YD%LIMA, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%LIMA (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%LIMA)
ENDIF

CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%FSD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LEXT = ALLOCATED (YD%EXT)
IF (LEXT) THEN
  !$ACC ENTER DATA CREATE (YD%EXT)
  !$ACC UPDATE DEVICE (YD%EXT)
  DO J1 = LBOUND (YD%EXT, 1), UBOUND (YD%EXT, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%EXT (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%EXT)
ENDIF

LGFL = ALLOCATED (YD%GFL)
IF (LGFL) THEN
  !$ACC ENTER DATA CREATE (YD%GFL)
  !$ACC UPDATE DEVICE (YD%GFL)
  DO J1 = LBOUND (YD%GFL, 1), UBOUND (YD%GFL, 1)
    CALL COPY_CPG_TNDSL_DDH_3D_TYPE (YD%GFL (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%GFL)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_CPG_TNDSL_DDH_TYPE (YD)
USE UTIL_CPG_TNDSL_DDH_3D_TYPE_MOD

IMPLICIT NONE
TYPE (CPG_TNDSL_DDH_TYPE), TARGET :: YD
INTEGER :: J1
LOGICAL :: LAERAOT, LAERLISI, LAERO, LAEROCLIM, LAEROUT, LCHEM, LEDRP, LEMIS3D, LERA40, LEXT
LOGICAL :: LEZDIAG, LFORC, LGFL, LGHG, LLIMA, LNOGW, LSLDIA, LUVP, LZDATA_GFL, LZDATA_GMV
LOGICAL :: LZVIEW_GFL, LZVIEW_GMV




CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%U)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%V)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%T)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%PD)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%VD)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%NHX)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%Q)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%I)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%L)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%IMF)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%LMF)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%LCONV)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%ICONV)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%RCONV)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%SCONV)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%IRAD)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%LRAD)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%S)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%R)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%G)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%H)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%TKE)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%TTE)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%EFB1)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%EFB2)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%EFB3)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%A)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%AMF)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%O3)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%SRC)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%MXL)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%SHTUR)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%FQTUR)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%FSTUR)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%CPF)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%SPF)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%CVGQ)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%QVA)

LGHG = ALLOCATED (YD%GHG)
IF (LGHG) THEN
  DO J1 = LBOUND (YD%GHG, 1), UBOUND (YD%GHG, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%GHG (J1))
  ENDDO
ENDIF

LCHEM = ALLOCATED (YD%CHEM)
IF (LCHEM) THEN
  DO J1 = LBOUND (YD%CHEM, 1), UBOUND (YD%CHEM, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%CHEM (J1))
  ENDDO
ENDIF

LAERO = ALLOCATED (YD%AERO)
IF (LAERO) THEN
  DO J1 = LBOUND (YD%AERO, 1), UBOUND (YD%AERO, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%AERO (J1))
  ENDDO
ENDIF

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%LRCH4)

LFORC = ALLOCATED (YD%FORC)
IF (LFORC) THEN
  DO J1 = LBOUND (YD%FORC, 1), UBOUND (YD%FORC, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%FORC (J1))
  ENDDO
ENDIF

LEZDIAG = ALLOCATED (YD%EZDIAG)
IF (LEZDIAG) THEN
  DO J1 = LBOUND (YD%EZDIAG, 1), UBOUND (YD%EZDIAG, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%EZDIAG (J1))
  ENDDO
ENDIF

LERA40 = ALLOCATED (YD%ERA40)
IF (LERA40) THEN
  DO J1 = LBOUND (YD%ERA40, 1), UBOUND (YD%ERA40, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%ERA40 (J1))
  ENDDO
ENDIF

LNOGW = ALLOCATED (YD%NOGW)
IF (LNOGW) THEN
  DO J1 = LBOUND (YD%NOGW, 1), UBOUND (YD%NOGW, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%NOGW (J1))
  ENDDO
ENDIF

LEMIS3D = ALLOCATED (YD%EMIS3D)
IF (LEMIS3D) THEN
  DO J1 = LBOUND (YD%EMIS3D, 1), UBOUND (YD%EMIS3D, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%EMIS3D (J1))
  ENDDO
ENDIF

LEDRP = ALLOCATED (YD%EDRP)
IF (LEDRP) THEN
  DO J1 = LBOUND (YD%EDRP, 1), UBOUND (YD%EDRP, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%EDRP (J1))
  ENDDO
ENDIF

LSLDIA = ALLOCATED (YD%SLDIA)
IF (LSLDIA) THEN
  DO J1 = LBOUND (YD%SLDIA, 1), UBOUND (YD%SLDIA, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%SLDIA (J1))
  ENDDO
ENDIF

LAERAOT = ALLOCATED (YD%AERAOT)
IF (LAERAOT) THEN
  DO J1 = LBOUND (YD%AERAOT, 1), UBOUND (YD%AERAOT, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%AERAOT (J1))
  ENDDO
ENDIF

LAERLISI = ALLOCATED (YD%AERLISI)
IF (LAERLISI) THEN
  DO J1 = LBOUND (YD%AERLISI, 1), UBOUND (YD%AERLISI, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%AERLISI (J1))
  ENDDO
ENDIF

LAEROUT = ALLOCATED (YD%AEROUT)
IF (LAEROUT) THEN
  DO J1 = LBOUND (YD%AEROUT, 1), UBOUND (YD%AEROUT, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%AEROUT (J1))
  ENDDO
ENDIF

LAEROCLIM = ALLOCATED (YD%AEROCLIM)
IF (LAEROCLIM) THEN
  DO J1 = LBOUND (YD%AEROCLIM, 1), UBOUND (YD%AEROCLIM, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%AEROCLIM (J1))
  ENDDO
ENDIF

LUVP = ALLOCATED (YD%UVP)
IF (LUVP) THEN
  DO J1 = LBOUND (YD%UVP, 1), UBOUND (YD%UVP, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%UVP (J1))
  ENDDO
ENDIF

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%PHYCTY)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%RSPEC)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%SDSAT)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%CVV)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%RKTH)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%RKTQV)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%RKTQC)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%UOM)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%UAL)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%DOM)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%DAL)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%UEN)

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%UNEBH)

LLIMA = ALLOCATED (YD%LIMA)
IF (LLIMA) THEN
  DO J1 = LBOUND (YD%LIMA, 1), UBOUND (YD%LIMA, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%LIMA (J1))
  ENDDO
ENDIF

CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%FSD)

LEXT = ALLOCATED (YD%EXT)
IF (LEXT) THEN
  DO J1 = LBOUND (YD%EXT, 1), UBOUND (YD%EXT, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%EXT (J1))
  ENDDO
ENDIF

LGFL = ALLOCATED (YD%GFL)
IF (LGFL) THEN
  DO J1 = LBOUND (YD%GFL, 1), UBOUND (YD%GFL, 1)
    CALL HOST_CPG_TNDSL_DDH_3D_TYPE (YD%GFL (J1))
  ENDDO
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_CPG_TNDSL_DDH_TYPE (YD, LDDELETED, LDFIELDAPI)
USE UTIL_CPG_TNDSL_DDH_3D_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_TNDSL_DDH_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LAERAOT, LAERLISI, LAERO, LAEROCLIM, LAEROUT, LCHEM, LEDRP, LEMIS3D, LERA40, LEXT
LOGICAL :: LEZDIAG, LFORC, LGFL, LGHG, LLIMA, LNOGW, LSLDIA, LUVP, LZDATA_GFL, LZDATA_GMV
LOGICAL :: LZVIEW_GFL, LZVIEW_GMV

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LZDATA_GMV = ASSOCIATED (YD%ZDATA_GMV)
IF (LZDATA_GMV) THEN
  !$ACC EXIT DATA DETACH (YD%ZDATA_GMV)
  !$ACC EXIT DATA DETACH (YD%ZDATA_GMV)
ENDIF

LZVIEW_GMV = ASSOCIATED (YD%ZVIEW_GMV)
IF (LZVIEW_GMV) THEN
  !$ACC EXIT DATA DETACH (YD%ZVIEW_GMV)
  !$ACC EXIT DATA DETACH (YD%ZVIEW_GMV)
ENDIF

LZDATA_GFL = ASSOCIATED (YD%ZDATA_GFL)
IF (LZDATA_GFL) THEN
  !$ACC EXIT DATA DETACH (YD%ZDATA_GFL)
  !$ACC EXIT DATA DETACH (YD%ZDATA_GFL)
ENDIF

LZVIEW_GFL = ASSOCIATED (YD%ZVIEW_GFL)
IF (LZVIEW_GFL) THEN
  !$ACC EXIT DATA DETACH (YD%ZVIEW_GFL)
  !$ACC EXIT DATA DETACH (YD%ZVIEW_GFL)
ENDIF

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%U, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%V, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%T, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%PD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%VD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%NHX, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%Q, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%I, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%L, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%IMF, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%LMF, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%LCONV, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%ICONV, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%RCONV, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%SCONV, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%IRAD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%LRAD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%S, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%R, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%G, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%H, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%TKE, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%TTE, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%EFB1, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%EFB2, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%EFB3, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%A, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%AMF, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%O3, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%SRC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%MXL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%SHTUR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%FQTUR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%FSTUR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%CPF, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%SPF, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%CVGQ, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%QVA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LGHG = ALLOCATED (YD%GHG)
IF (LGHG) THEN
  !$ACC EXIT DATA DETACH (YD%GHG)
  DO J1 = LBOUND (YD%GHG, 1), UBOUND (YD%GHG, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%GHG (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%GHG)
ENDIF

LCHEM = ALLOCATED (YD%CHEM)
IF (LCHEM) THEN
  !$ACC EXIT DATA DETACH (YD%CHEM)
  DO J1 = LBOUND (YD%CHEM, 1), UBOUND (YD%CHEM, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%CHEM (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%CHEM)
ENDIF

LAERO = ALLOCATED (YD%AERO)
IF (LAERO) THEN
  !$ACC EXIT DATA DETACH (YD%AERO)
  DO J1 = LBOUND (YD%AERO, 1), UBOUND (YD%AERO, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%AERO (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%AERO)
ENDIF

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%LRCH4, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LFORC = ALLOCATED (YD%FORC)
IF (LFORC) THEN
  !$ACC EXIT DATA DETACH (YD%FORC)
  DO J1 = LBOUND (YD%FORC, 1), UBOUND (YD%FORC, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%FORC (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%FORC)
ENDIF

LEZDIAG = ALLOCATED (YD%EZDIAG)
IF (LEZDIAG) THEN
  !$ACC EXIT DATA DETACH (YD%EZDIAG)
  DO J1 = LBOUND (YD%EZDIAG, 1), UBOUND (YD%EZDIAG, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%EZDIAG (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%EZDIAG)
ENDIF

LERA40 = ALLOCATED (YD%ERA40)
IF (LERA40) THEN
  !$ACC EXIT DATA DETACH (YD%ERA40)
  DO J1 = LBOUND (YD%ERA40, 1), UBOUND (YD%ERA40, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%ERA40 (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%ERA40)
ENDIF

LNOGW = ALLOCATED (YD%NOGW)
IF (LNOGW) THEN
  !$ACC EXIT DATA DETACH (YD%NOGW)
  DO J1 = LBOUND (YD%NOGW, 1), UBOUND (YD%NOGW, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%NOGW (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%NOGW)
ENDIF

LEMIS3D = ALLOCATED (YD%EMIS3D)
IF (LEMIS3D) THEN
  !$ACC EXIT DATA DETACH (YD%EMIS3D)
  DO J1 = LBOUND (YD%EMIS3D, 1), UBOUND (YD%EMIS3D, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%EMIS3D (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%EMIS3D)
ENDIF

LEDRP = ALLOCATED (YD%EDRP)
IF (LEDRP) THEN
  !$ACC EXIT DATA DETACH (YD%EDRP)
  DO J1 = LBOUND (YD%EDRP, 1), UBOUND (YD%EDRP, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%EDRP (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%EDRP)
ENDIF

LSLDIA = ALLOCATED (YD%SLDIA)
IF (LSLDIA) THEN
  !$ACC EXIT DATA DETACH (YD%SLDIA)
  DO J1 = LBOUND (YD%SLDIA, 1), UBOUND (YD%SLDIA, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%SLDIA (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%SLDIA)
ENDIF

LAERAOT = ALLOCATED (YD%AERAOT)
IF (LAERAOT) THEN
  !$ACC EXIT DATA DETACH (YD%AERAOT)
  DO J1 = LBOUND (YD%AERAOT, 1), UBOUND (YD%AERAOT, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%AERAOT (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%AERAOT)
ENDIF

LAERLISI = ALLOCATED (YD%AERLISI)
IF (LAERLISI) THEN
  !$ACC EXIT DATA DETACH (YD%AERLISI)
  DO J1 = LBOUND (YD%AERLISI, 1), UBOUND (YD%AERLISI, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%AERLISI (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%AERLISI)
ENDIF

LAEROUT = ALLOCATED (YD%AEROUT)
IF (LAEROUT) THEN
  !$ACC EXIT DATA DETACH (YD%AEROUT)
  DO J1 = LBOUND (YD%AEROUT, 1), UBOUND (YD%AEROUT, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%AEROUT (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%AEROUT)
ENDIF

LAEROCLIM = ALLOCATED (YD%AEROCLIM)
IF (LAEROCLIM) THEN
  !$ACC EXIT DATA DETACH (YD%AEROCLIM)
  DO J1 = LBOUND (YD%AEROCLIM, 1), UBOUND (YD%AEROCLIM, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%AEROCLIM (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%AEROCLIM)
ENDIF

LUVP = ALLOCATED (YD%UVP)
IF (LUVP) THEN
  !$ACC EXIT DATA DETACH (YD%UVP)
  DO J1 = LBOUND (YD%UVP, 1), UBOUND (YD%UVP, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%UVP (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%UVP)
ENDIF

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%PHYCTY, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%RSPEC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%SDSAT, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%CVV, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%RKTH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%RKTQV, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%RKTQC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%UOM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%UAL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%DOM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%DAL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%UEN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%UNEBH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLIMA = ALLOCATED (YD%LIMA)
IF (LLIMA) THEN
  !$ACC EXIT DATA DETACH (YD%LIMA)
  DO J1 = LBOUND (YD%LIMA, 1), UBOUND (YD%LIMA, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%LIMA (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%LIMA)
ENDIF

CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%FSD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LEXT = ALLOCATED (YD%EXT)
IF (LEXT) THEN
  !$ACC EXIT DATA DETACH (YD%EXT)
  DO J1 = LBOUND (YD%EXT, 1), UBOUND (YD%EXT, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%EXT (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%EXT)
ENDIF

LGFL = ALLOCATED (YD%GFL)
IF (LGFL) THEN
  !$ACC EXIT DATA DETACH (YD%GFL)
  DO J1 = LBOUND (YD%GFL, 1), UBOUND (YD%GFL, 1)
    CALL WIPE_CPG_TNDSL_DDH_3D_TYPE (YD%GFL (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%GFL)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
