MODULE UTIL_TMP_MOD

USE YOMMP, ONLY : TMP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TMP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TMP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TMP
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TMP
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TMP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TMP
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TMP
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TMP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMP), INTENT (IN), TARGET :: YD
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP
LNUMPP = ALLOCATED (YD%NUMPP)
WRITE (KLUN) LNUMPP
IF (LNUMPP) THEN
  WRITE (KLUN) LBOUND (YD%NUMPP)
  WRITE (KLUN) UBOUND (YD%NUMPP)
  WRITE (KLUN) YD%NUMPP
ENDIF
LNPROCM = ALLOCATED (YD%NPROCM)
WRITE (KLUN) LNPROCM
IF (LNPROCM) THEN
  WRITE (KLUN) LBOUND (YD%NPROCM)
  WRITE (KLUN) UBOUND (YD%NPROCM)
  WRITE (KLUN) YD%NPROCM
ENDIF
LNPTRMS = ALLOCATED (YD%NPTRMS)
WRITE (KLUN) LNPTRMS
IF (LNPTRMS) THEN
  WRITE (KLUN) LBOUND (YD%NPTRMS)
  WRITE (KLUN) UBOUND (YD%NPTRMS)
  WRITE (KLUN) YD%NPTRMS
ENDIF
LNALLMS = ALLOCATED (YD%NALLMS)
WRITE (KLUN) LNALLMS
IF (LNALLMS) THEN
  WRITE (KLUN) LBOUND (YD%NALLMS)
  WRITE (KLUN) UBOUND (YD%NALLMS)
  WRITE (KLUN) YD%NALLMS
ENDIF
LNPTRLS = ALLOCATED (YD%NPTRLS)
WRITE (KLUN) LNPTRLS
IF (LNPTRLS) THEN
  WRITE (KLUN) LBOUND (YD%NPTRLS)
  WRITE (KLUN) UBOUND (YD%NPTRLS)
  WRITE (KLUN) YD%NPTRLS
ENDIF
LNPTRSV = ALLOCATED (YD%NPTRSV)
WRITE (KLUN) LNPTRSV
IF (LNPTRSV) THEN
  WRITE (KLUN) LBOUND (YD%NPTRSV)
  WRITE (KLUN) UBOUND (YD%NPTRSV)
  WRITE (KLUN) YD%NPTRSV
ENDIF
LNPTRSVF = ALLOCATED (YD%NPTRSVF)
WRITE (KLUN) LNPTRSVF
IF (LNPTRSVF) THEN
  WRITE (KLUN) LBOUND (YD%NPTRSVF)
  WRITE (KLUN) UBOUND (YD%NPTRSVF)
  WRITE (KLUN) YD%NPTRSVF
ENDIF
LNPTRMF = ALLOCATED (YD%NPTRMF)
WRITE (KLUN) LNPTRMF
IF (LNPTRMF) THEN
  WRITE (KLUN) LBOUND (YD%NPTRMF)
  WRITE (KLUN) UBOUND (YD%NPTRMF)
  WRITE (KLUN) YD%NPTRMF
ENDIF
LNSPSTAF = ALLOCATED (YD%NSPSTAF)
WRITE (KLUN) LNSPSTAF
IF (LNSPSTAF) THEN
  WRITE (KLUN) LBOUND (YD%NSPSTAF)
  WRITE (KLUN) UBOUND (YD%NSPSTAF)
  WRITE (KLUN) YD%NSPSTAF
ENDIF
LNUMLL = ALLOCATED (YD%NUMLL)
WRITE (KLUN) LNUMLL
IF (LNUMLL) THEN
  WRITE (KLUN) LBOUND (YD%NUMLL)
  WRITE (KLUN) UBOUND (YD%NUMLL)
  WRITE (KLUN) YD%NUMLL
ENDIF
LNPTRLL = ALLOCATED (YD%NPTRLL)
WRITE (KLUN) LNPTRLL
IF (LNPTRLL) THEN
  WRITE (KLUN) LBOUND (YD%NPTRLL)
  WRITE (KLUN) UBOUND (YD%NPTRLL)
  WRITE (KLUN) YD%NPTRLL
ENDIF
LMYLEVS = ALLOCATED (YD%MYLEVS)
WRITE (KLUN) LMYLEVS
IF (LMYLEVS) THEN
  WRITE (KLUN) LBOUND (YD%MYLEVS)
  WRITE (KLUN) UBOUND (YD%MYLEVS)
  WRITE (KLUN) YD%MYLEVS
ENDIF
LNPSURF = ALLOCATED (YD%NPSURF)
WRITE (KLUN) LNPSURF
IF (LNPSURF) THEN
  WRITE (KLUN) LBOUND (YD%NPSURF)
  WRITE (KLUN) UBOUND (YD%NPSURF)
  WRITE (KLUN) YD%NPSURF
ENDIF
LNSTA = ALLOCATED (YD%NSTA)
WRITE (KLUN) LNSTA
IF (LNSTA) THEN
  WRITE (KLUN) LBOUND (YD%NSTA)
  WRITE (KLUN) UBOUND (YD%NSTA)
  WRITE (KLUN) YD%NSTA
ENDIF
LNONL = ALLOCATED (YD%NONL)
WRITE (KLUN) LNONL
IF (LNONL) THEN
  WRITE (KLUN) LBOUND (YD%NONL)
  WRITE (KLUN) UBOUND (YD%NONL)
  WRITE (KLUN) YD%NONL
ENDIF
LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
WRITE (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) YD%NPTRFRSTLAT
ENDIF
LNPTRLSTLAT = ALLOCATED (YD%NPTRLSTLAT)
WRITE (KLUN) LNPTRLSTLAT
IF (LNPTRLSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NPTRLSTLAT)
  WRITE (KLUN) UBOUND (YD%NPTRLSTLAT)
  WRITE (KLUN) YD%NPTRLSTLAT
ENDIF
LNPTRLAT = ALLOCATED (YD%NPTRLAT)
WRITE (KLUN) LNPTRLAT
IF (LNPTRLAT) THEN
  WRITE (KLUN) LBOUND (YD%NPTRLAT)
  WRITE (KLUN) UBOUND (YD%NPTRLAT)
  WRITE (KLUN) YD%NPTRLAT
ENDIF
LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
WRITE (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NFRSTLAT)
  WRITE (KLUN) YD%NFRSTLAT
ENDIF
LNLSTLAT = ALLOCATED (YD%NLSTLAT)
WRITE (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NLSTLAT)
  WRITE (KLUN) UBOUND (YD%NLSTLAT)
  WRITE (KLUN) YD%NLSTLAT
ENDIF
LNBSETLEV = ALLOCATED (YD%NBSETLEV)
WRITE (KLUN) LNBSETLEV
IF (LNBSETLEV) THEN
  WRITE (KLUN) LBOUND (YD%NBSETLEV)
  WRITE (KLUN) UBOUND (YD%NBSETLEV)
  WRITE (KLUN) YD%NBSETLEV
ENDIF
LNGLOBALINDEX = ALLOCATED (YD%NGLOBALINDEX)
WRITE (KLUN) LNGLOBALINDEX
IF (LNGLOBALINDEX) THEN
  WRITE (KLUN) LBOUND (YD%NGLOBALINDEX)
  WRITE (KLUN) UBOUND (YD%NGLOBALINDEX)
  WRITE (KLUN) YD%NGLOBALINDEX
ENDIF
LNGLOBALAT = ALLOCATED (YD%NGLOBALAT)
WRITE (KLUN) LNGLOBALAT
IF (LNGLOBALAT) THEN
  WRITE (KLUN) LBOUND (YD%NGLOBALAT)
  WRITE (KLUN) UBOUND (YD%NGLOBALAT)
  WRITE (KLUN) YD%NGLOBALAT
ENDIF
LNGLOBALPROC = ALLOCATED (YD%NGLOBALPROC)
WRITE (KLUN) LNGLOBALPROC
IF (LNGLOBALPROC) THEN
  WRITE (KLUN) LBOUND (YD%NGLOBALPROC)
  WRITE (KLUN) UBOUND (YD%NGLOBALPROC)
  WRITE (KLUN) YD%NGLOBALPROC
ENDIF
LNLOCALINDEX = ALLOCATED (YD%NLOCALINDEX)
WRITE (KLUN) LNLOCALINDEX
IF (LNLOCALINDEX) THEN
  WRITE (KLUN) LBOUND (YD%NLOCALINDEX)
  WRITE (KLUN) UBOUND (YD%NLOCALINDEX)
  WRITE (KLUN) YD%NLOCALINDEX
ENDIF
LNLATGPP = ALLOCATED (YD%NLATGPP)
WRITE (KLUN) LNLATGPP
IF (LNLATGPP) THEN
  WRITE (KLUN) LBOUND (YD%NLATGPP)
  WRITE (KLUN) UBOUND (YD%NLATGPP)
  WRITE (KLUN) YD%NLATGPP
ENDIF
LNLONGPP = ALLOCATED (YD%NLONGPP)
WRITE (KLUN) LNLONGPP
IF (LNLONGPP) THEN
  WRITE (KLUN) LBOUND (YD%NLONGPP)
  WRITE (KLUN) UBOUND (YD%NLONGPP)
  WRITE (KLUN) YD%NLONGPP
ENDIF
LLSPLITLAT = ALLOCATED (YD%LSPLITLAT)
WRITE (KLUN) LLSPLITLAT
IF (LLSPLITLAT) THEN
  WRITE (KLUN) LBOUND (YD%LSPLITLAT)
  WRITE (KLUN) UBOUND (YD%LSPLITLAT)
  WRITE (KLUN) YD%LSPLITLAT
ENDIF
LMYLATS = ALLOCATED (YD%MYLATS)
WRITE (KLUN) LMYLATS
IF (LMYLATS) THEN
  WRITE (KLUN) LBOUND (YD%MYLATS)
  WRITE (KLUN) UBOUND (YD%MYLATS)
  WRITE (KLUN) YD%MYLATS
ENDIF
WRITE (KLUN) YD%NPSP
WRITE (KLUN) YD%NSPEC2V
WRITE (KLUN) YD%NSPEC2VF
WRITE (KLUN) YD%NSPEC2VDDH
WRITE (KLUN) YD%NSPEC2V_NH
WRITE (KLUN) YD%NSPEC2V_NHX
WRITE (KLUN) YD%NBSETSP
WRITE (KLUN) YD%NFRSTLOFF
WRITE (KLUN) YD%MYFRSTACTLAT
WRITE (KLUN) YD%MYLSTACTLAT
WRITE (KLUN) YD%NPTRFLOFF
LNPOSSP = ALLOCATED (YD%NPOSSP)
WRITE (KLUN) LNPOSSP
IF (LNPOSSP) THEN
  WRITE (KLUN) LBOUND (YD%NPOSSP)
  WRITE (KLUN) UBOUND (YD%NPOSSP)
  WRITE (KLUN) YD%NPOSSP
ENDIF
LNDIM0G = ALLOCATED (YD%NDIM0G)
WRITE (KLUN) LNDIM0G
IF (LNDIM0G) THEN
  WRITE (KLUN) LBOUND (YD%NDIM0G)
  WRITE (KLUN) UBOUND (YD%NDIM0G)
  WRITE (KLUN) YD%NDIM0G
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TMP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TMP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP
READ (KLUN) LNUMPP
IF (LNUMPP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NUMPP (IL1(1):IU1(1)))
  READ (KLUN) YD%NUMPP
ENDIF
READ (KLUN) LNPROCM
IF (LNPROCM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPROCM (IL1(1):IU1(1)))
  READ (KLUN) YD%NPROCM
ENDIF
READ (KLUN) LNPTRMS
IF (LNPTRMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRMS (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRMS
ENDIF
READ (KLUN) LNALLMS
IF (LNALLMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NALLMS (IL1(1):IU1(1)))
  READ (KLUN) YD%NALLMS
ENDIF
READ (KLUN) LNPTRLS
IF (LNPTRLS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLS (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLS
ENDIF
READ (KLUN) LNPTRSV
IF (LNPTRSV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRSV (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRSV
ENDIF
READ (KLUN) LNPTRSVF
IF (LNPTRSVF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRSVF (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRSVF
ENDIF
READ (KLUN) LNPTRMF
IF (LNPTRMF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRMF (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRMF
ENDIF
READ (KLUN) LNSPSTAF
IF (LNSPSTAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NSPSTAF (IL1(1):IU1(1)))
  READ (KLUN) YD%NSPSTAF
ENDIF
READ (KLUN) LNUMLL
IF (LNUMLL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NUMLL (IL1(1):IU1(1)))
  READ (KLUN) YD%NUMLL
ENDIF
READ (KLUN) LNPTRLL
IF (LNPTRLL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLL (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLL
ENDIF
READ (KLUN) LMYLEVS
IF (LMYLEVS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYLEVS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYLEVS
ENDIF
READ (KLUN) LNPSURF
IF (LNPSURF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPSURF (IL1(1):IU1(1)))
  READ (KLUN) YD%NPSURF
ENDIF
READ (KLUN) LNSTA
IF (LNSTA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSTA (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSTA
ENDIF
READ (KLUN) LNONL
IF (LNONL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NONL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NONL
ENDIF
READ (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRFRSTLAT
ENDIF
READ (KLUN) LNPTRLSTLAT
IF (LNPTRLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLSTLAT
ENDIF
READ (KLUN) LNPTRLAT
IF (LNPTRLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRLAT
ENDIF
READ (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NFRSTLAT
ENDIF
READ (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NLSTLAT
ENDIF
READ (KLUN) LNBSETLEV
IF (LNBSETLEV) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NBSETLEV (IL1(1):IU1(1)))
  READ (KLUN) YD%NBSETLEV
ENDIF
READ (KLUN) LNGLOBALINDEX
IF (LNGLOBALINDEX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGLOBALINDEX (IL1(1):IU1(1)))
  READ (KLUN) YD%NGLOBALINDEX
ENDIF
READ (KLUN) LNGLOBALAT
IF (LNGLOBALAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGLOBALAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NGLOBALAT
ENDIF
READ (KLUN) LNGLOBALPROC
IF (LNGLOBALPROC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NGLOBALPROC (IL1(1):IU1(1)))
  READ (KLUN) YD%NGLOBALPROC
ENDIF
READ (KLUN) LNLOCALINDEX
IF (LNLOCALINDEX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOCALINDEX (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOCALINDEX
ENDIF
READ (KLUN) LNLATGPP
IF (LNLATGPP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NLATGPP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NLATGPP
ENDIF
READ (KLUN) LNLONGPP
IF (LNLONGPP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NLONGPP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NLONGPP
ENDIF
READ (KLUN) LLSPLITLAT
IF (LLSPLITLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LSPLITLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%LSPLITLAT
ENDIF
READ (KLUN) LMYLATS
IF (LMYLATS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYLATS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYLATS
ENDIF
READ (KLUN) YD%NPSP
READ (KLUN) YD%NSPEC2V
READ (KLUN) YD%NSPEC2VF
READ (KLUN) YD%NSPEC2VDDH
READ (KLUN) YD%NSPEC2V_NH
READ (KLUN) YD%NSPEC2V_NHX
READ (KLUN) YD%NBSETSP
READ (KLUN) YD%NFRSTLOFF
READ (KLUN) YD%MYFRSTACTLAT
READ (KLUN) YD%MYLSTACTLAT
READ (KLUN) YD%NPTRFLOFF
READ (KLUN) LNPOSSP
IF (LNPOSSP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPOSSP (IL1(1):IU1(1)))
  READ (KLUN) YD%NPOSSP
ENDIF
READ (KLUN) LNDIM0G
IF (LNDIM0G) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NDIM0G (IL1(1):IU1(1)))
  READ (KLUN) YD%NDIM0G
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TMP (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TMP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LNUMPP = ALLOCATED (YD%NUMPP)
IF (LNUMPP) THEN
  !$ACC ENTER DATA CREATE (YD%NUMPP)
  !$ACC UPDATE DEVICE (YD%NUMPP)
  !$ACC ENTER DATA ATTACH (YD%NUMPP)
ENDIF

LNPROCM = ALLOCATED (YD%NPROCM)
IF (LNPROCM) THEN
  !$ACC ENTER DATA CREATE (YD%NPROCM)
  !$ACC UPDATE DEVICE (YD%NPROCM)
  !$ACC ENTER DATA ATTACH (YD%NPROCM)
ENDIF

LNPTRMS = ALLOCATED (YD%NPTRMS)
IF (LNPTRMS) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRMS)
  !$ACC UPDATE DEVICE (YD%NPTRMS)
  !$ACC ENTER DATA ATTACH (YD%NPTRMS)
ENDIF

LNALLMS = ALLOCATED (YD%NALLMS)
IF (LNALLMS) THEN
  !$ACC ENTER DATA CREATE (YD%NALLMS)
  !$ACC UPDATE DEVICE (YD%NALLMS)
  !$ACC ENTER DATA ATTACH (YD%NALLMS)
ENDIF

LNPTRLS = ALLOCATED (YD%NPTRLS)
IF (LNPTRLS) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRLS)
  !$ACC UPDATE DEVICE (YD%NPTRLS)
  !$ACC ENTER DATA ATTACH (YD%NPTRLS)
ENDIF

LNPTRSV = ALLOCATED (YD%NPTRSV)
IF (LNPTRSV) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRSV)
  !$ACC UPDATE DEVICE (YD%NPTRSV)
  !$ACC ENTER DATA ATTACH (YD%NPTRSV)
ENDIF

LNPTRSVF = ALLOCATED (YD%NPTRSVF)
IF (LNPTRSVF) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRSVF)
  !$ACC UPDATE DEVICE (YD%NPTRSVF)
  !$ACC ENTER DATA ATTACH (YD%NPTRSVF)
ENDIF

LNPTRMF = ALLOCATED (YD%NPTRMF)
IF (LNPTRMF) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRMF)
  !$ACC UPDATE DEVICE (YD%NPTRMF)
  !$ACC ENTER DATA ATTACH (YD%NPTRMF)
ENDIF

LNSPSTAF = ALLOCATED (YD%NSPSTAF)
IF (LNSPSTAF) THEN
  !$ACC ENTER DATA CREATE (YD%NSPSTAF)
  !$ACC UPDATE DEVICE (YD%NSPSTAF)
  !$ACC ENTER DATA ATTACH (YD%NSPSTAF)
ENDIF

LNUMLL = ALLOCATED (YD%NUMLL)
IF (LNUMLL) THEN
  !$ACC ENTER DATA CREATE (YD%NUMLL)
  !$ACC UPDATE DEVICE (YD%NUMLL)
  !$ACC ENTER DATA ATTACH (YD%NUMLL)
ENDIF

LNPTRLL = ALLOCATED (YD%NPTRLL)
IF (LNPTRLL) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRLL)
  !$ACC UPDATE DEVICE (YD%NPTRLL)
  !$ACC ENTER DATA ATTACH (YD%NPTRLL)
ENDIF

LMYLEVS = ALLOCATED (YD%MYLEVS)
IF (LMYLEVS) THEN
  !$ACC ENTER DATA CREATE (YD%MYLEVS)
  !$ACC UPDATE DEVICE (YD%MYLEVS)
  !$ACC ENTER DATA ATTACH (YD%MYLEVS)
ENDIF

LNPSURF = ALLOCATED (YD%NPSURF)
IF (LNPSURF) THEN
  !$ACC ENTER DATA CREATE (YD%NPSURF)
  !$ACC UPDATE DEVICE (YD%NPSURF)
  !$ACC ENTER DATA ATTACH (YD%NPSURF)
ENDIF

LNSTA = ALLOCATED (YD%NSTA)
IF (LNSTA) THEN
  !$ACC ENTER DATA CREATE (YD%NSTA)
  !$ACC UPDATE DEVICE (YD%NSTA)
  !$ACC ENTER DATA ATTACH (YD%NSTA)
ENDIF

LNONL = ALLOCATED (YD%NONL)
IF (LNONL) THEN
  !$ACC ENTER DATA CREATE (YD%NONL)
  !$ACC UPDATE DEVICE (YD%NONL)
  !$ACC ENTER DATA ATTACH (YD%NONL)
ENDIF

LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRFRSTLAT)
  !$ACC UPDATE DEVICE (YD%NPTRFRSTLAT)
  !$ACC ENTER DATA ATTACH (YD%NPTRFRSTLAT)
ENDIF

LNPTRLSTLAT = ALLOCATED (YD%NPTRLSTLAT)
IF (LNPTRLSTLAT) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRLSTLAT)
  !$ACC UPDATE DEVICE (YD%NPTRLSTLAT)
  !$ACC ENTER DATA ATTACH (YD%NPTRLSTLAT)
ENDIF

LNPTRLAT = ALLOCATED (YD%NPTRLAT)
IF (LNPTRLAT) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRLAT)
  !$ACC UPDATE DEVICE (YD%NPTRLAT)
  !$ACC ENTER DATA ATTACH (YD%NPTRLAT)
ENDIF

LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (YD%NFRSTLAT)
  !$ACC UPDATE DEVICE (YD%NFRSTLAT)
  !$ACC ENTER DATA ATTACH (YD%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (YD%NLSTLAT)
IF (LNLSTLAT) THEN
  !$ACC ENTER DATA CREATE (YD%NLSTLAT)
  !$ACC UPDATE DEVICE (YD%NLSTLAT)
  !$ACC ENTER DATA ATTACH (YD%NLSTLAT)
ENDIF

LNBSETLEV = ALLOCATED (YD%NBSETLEV)
IF (LNBSETLEV) THEN
  !$ACC ENTER DATA CREATE (YD%NBSETLEV)
  !$ACC UPDATE DEVICE (YD%NBSETLEV)
  !$ACC ENTER DATA ATTACH (YD%NBSETLEV)
ENDIF

LNGLOBALINDEX = ALLOCATED (YD%NGLOBALINDEX)
IF (LNGLOBALINDEX) THEN
  !$ACC ENTER DATA CREATE (YD%NGLOBALINDEX)
  !$ACC UPDATE DEVICE (YD%NGLOBALINDEX)
  !$ACC ENTER DATA ATTACH (YD%NGLOBALINDEX)
ENDIF

LNGLOBALAT = ALLOCATED (YD%NGLOBALAT)
IF (LNGLOBALAT) THEN
  !$ACC ENTER DATA CREATE (YD%NGLOBALAT)
  !$ACC UPDATE DEVICE (YD%NGLOBALAT)
  !$ACC ENTER DATA ATTACH (YD%NGLOBALAT)
ENDIF

LNGLOBALPROC = ALLOCATED (YD%NGLOBALPROC)
IF (LNGLOBALPROC) THEN
  !$ACC ENTER DATA CREATE (YD%NGLOBALPROC)
  !$ACC UPDATE DEVICE (YD%NGLOBALPROC)
  !$ACC ENTER DATA ATTACH (YD%NGLOBALPROC)
ENDIF

LNLOCALINDEX = ALLOCATED (YD%NLOCALINDEX)
IF (LNLOCALINDEX) THEN
  !$ACC ENTER DATA CREATE (YD%NLOCALINDEX)
  !$ACC UPDATE DEVICE (YD%NLOCALINDEX)
  !$ACC ENTER DATA ATTACH (YD%NLOCALINDEX)
ENDIF

LNLATGPP = ALLOCATED (YD%NLATGPP)
IF (LNLATGPP) THEN
  !$ACC ENTER DATA CREATE (YD%NLATGPP)
  !$ACC UPDATE DEVICE (YD%NLATGPP)
  !$ACC ENTER DATA ATTACH (YD%NLATGPP)
ENDIF

LNLONGPP = ALLOCATED (YD%NLONGPP)
IF (LNLONGPP) THEN
  !$ACC ENTER DATA CREATE (YD%NLONGPP)
  !$ACC UPDATE DEVICE (YD%NLONGPP)
  !$ACC ENTER DATA ATTACH (YD%NLONGPP)
ENDIF

LLSPLITLAT = ALLOCATED (YD%LSPLITLAT)
IF (LLSPLITLAT) THEN
  !$ACC ENTER DATA CREATE (YD%LSPLITLAT)
  !$ACC UPDATE DEVICE (YD%LSPLITLAT)
  !$ACC ENTER DATA ATTACH (YD%LSPLITLAT)
ENDIF

LMYLATS = ALLOCATED (YD%MYLATS)
IF (LMYLATS) THEN
  !$ACC ENTER DATA CREATE (YD%MYLATS)
  !$ACC UPDATE DEVICE (YD%MYLATS)
  !$ACC ENTER DATA ATTACH (YD%MYLATS)
ENDIF












LNPOSSP = ALLOCATED (YD%NPOSSP)
IF (LNPOSSP) THEN
  !$ACC ENTER DATA CREATE (YD%NPOSSP)
  !$ACC UPDATE DEVICE (YD%NPOSSP)
  !$ACC ENTER DATA ATTACH (YD%NPOSSP)
ENDIF

LNDIM0G = ALLOCATED (YD%NDIM0G)
IF (LNDIM0G) THEN
  !$ACC ENTER DATA CREATE (YD%NDIM0G)
  !$ACC UPDATE DEVICE (YD%NDIM0G)
  !$ACC ENTER DATA ATTACH (YD%NDIM0G)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TMP (YD)

IMPLICIT NONE
TYPE (TMP), TARGET :: YD
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP










































END SUBROUTINE

     

SUBROUTINE CRC64_TMP (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TMP), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NUMPP), CDPATH//'%NUMPP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPROCM), CDPATH//'%NPROCM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRMS), CDPATH//'%NPTRMS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NALLMS), CDPATH//'%NALLMS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRLS), CDPATH//'%NPTRLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRSV), CDPATH//'%NPTRSV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRSVF), CDPATH//'%NPTRSVF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRMF), CDPATH//'%NPTRMF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPSTAF), CDPATH//'%NSPSTAF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NUMLL), CDPATH//'%NUMLL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRLL), CDPATH//'%NPTRLL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MYLEVS), CDPATH//'%MYLEVS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPSURF), CDPATH//'%NPSURF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSTA), CDPATH//'%NSTA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NONL), CDPATH//'%NONL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRFRSTLAT), CDPATH//'%NPTRFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRLSTLAT), CDPATH//'%NPTRLSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRLAT), CDPATH//'%NPTRLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NFRSTLAT), CDPATH//'%NFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NLSTLAT), CDPATH//'%NLSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NBSETLEV), CDPATH//'%NBSETLEV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGLOBALINDEX), CDPATH//'%NGLOBALINDEX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGLOBALAT), CDPATH//'%NGLOBALAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGLOBALPROC), CDPATH//'%NGLOBALPROC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NLOCALINDEX), CDPATH//'%NLOCALINDEX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NLATGPP), CDPATH//'%NLATGPP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NLONGPP), CDPATH//'%NLONGPP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSPLITLAT), CDPATH//'%LSPLITLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MYLATS), CDPATH//'%MYLATS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPSP), CDPATH//'%NPSP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC2V), CDPATH//'%NSPEC2V'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC2VF), CDPATH//'%NSPEC2VF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC2VDDH), CDPATH//'%NSPEC2VDDH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC2V_NH), CDPATH//'%NSPEC2V_NH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC2V_NHX), CDPATH//'%NSPEC2V_NHX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NBSETSP), CDPATH//'%NBSETSP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NFRSTLOFF), CDPATH//'%NFRSTLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MYFRSTACTLAT), CDPATH//'%MYFRSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MYLSTACTLAT), CDPATH//'%MYLSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRFLOFF), CDPATH//'%NPTRFLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPOSSP), CDPATH//'%NPOSSP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDIM0G), CDPATH//'%NDIM0G'

END SUBROUTINE

SUBROUTINE WIPE_TMP (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TMP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LNUMPP = ALLOCATED (YD%NUMPP)
IF (LNUMPP) THEN
  !$ACC EXIT DATA DETACH (YD%NUMPP)
  !$ACC EXIT DATA DETACH (YD%NUMPP)
ENDIF

LNPROCM = ALLOCATED (YD%NPROCM)
IF (LNPROCM) THEN
  !$ACC EXIT DATA DETACH (YD%NPROCM)
  !$ACC EXIT DATA DETACH (YD%NPROCM)
ENDIF

LNPTRMS = ALLOCATED (YD%NPTRMS)
IF (LNPTRMS) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRMS)
  !$ACC EXIT DATA DETACH (YD%NPTRMS)
ENDIF

LNALLMS = ALLOCATED (YD%NALLMS)
IF (LNALLMS) THEN
  !$ACC EXIT DATA DETACH (YD%NALLMS)
  !$ACC EXIT DATA DETACH (YD%NALLMS)
ENDIF

LNPTRLS = ALLOCATED (YD%NPTRLS)
IF (LNPTRLS) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRLS)
  !$ACC EXIT DATA DETACH (YD%NPTRLS)
ENDIF

LNPTRSV = ALLOCATED (YD%NPTRSV)
IF (LNPTRSV) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRSV)
  !$ACC EXIT DATA DETACH (YD%NPTRSV)
ENDIF

LNPTRSVF = ALLOCATED (YD%NPTRSVF)
IF (LNPTRSVF) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRSVF)
  !$ACC EXIT DATA DETACH (YD%NPTRSVF)
ENDIF

LNPTRMF = ALLOCATED (YD%NPTRMF)
IF (LNPTRMF) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRMF)
  !$ACC EXIT DATA DETACH (YD%NPTRMF)
ENDIF

LNSPSTAF = ALLOCATED (YD%NSPSTAF)
IF (LNSPSTAF) THEN
  !$ACC EXIT DATA DETACH (YD%NSPSTAF)
  !$ACC EXIT DATA DETACH (YD%NSPSTAF)
ENDIF

LNUMLL = ALLOCATED (YD%NUMLL)
IF (LNUMLL) THEN
  !$ACC EXIT DATA DETACH (YD%NUMLL)
  !$ACC EXIT DATA DETACH (YD%NUMLL)
ENDIF

LNPTRLL = ALLOCATED (YD%NPTRLL)
IF (LNPTRLL) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRLL)
  !$ACC EXIT DATA DETACH (YD%NPTRLL)
ENDIF

LMYLEVS = ALLOCATED (YD%MYLEVS)
IF (LMYLEVS) THEN
  !$ACC EXIT DATA DETACH (YD%MYLEVS)
  !$ACC EXIT DATA DETACH (YD%MYLEVS)
ENDIF

LNPSURF = ALLOCATED (YD%NPSURF)
IF (LNPSURF) THEN
  !$ACC EXIT DATA DETACH (YD%NPSURF)
  !$ACC EXIT DATA DETACH (YD%NPSURF)
ENDIF

LNSTA = ALLOCATED (YD%NSTA)
IF (LNSTA) THEN
  !$ACC EXIT DATA DETACH (YD%NSTA)
  !$ACC EXIT DATA DETACH (YD%NSTA)
ENDIF

LNONL = ALLOCATED (YD%NONL)
IF (LNONL) THEN
  !$ACC EXIT DATA DETACH (YD%NONL)
  !$ACC EXIT DATA DETACH (YD%NONL)
ENDIF

LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRFRSTLAT)
  !$ACC EXIT DATA DETACH (YD%NPTRFRSTLAT)
ENDIF

LNPTRLSTLAT = ALLOCATED (YD%NPTRLSTLAT)
IF (LNPTRLSTLAT) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRLSTLAT)
  !$ACC EXIT DATA DETACH (YD%NPTRLSTLAT)
ENDIF

LNPTRLAT = ALLOCATED (YD%NPTRLAT)
IF (LNPTRLAT) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRLAT)
  !$ACC EXIT DATA DETACH (YD%NPTRLAT)
ENDIF

LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$ACC EXIT DATA DETACH (YD%NFRSTLAT)
  !$ACC EXIT DATA DETACH (YD%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (YD%NLSTLAT)
IF (LNLSTLAT) THEN
  !$ACC EXIT DATA DETACH (YD%NLSTLAT)
  !$ACC EXIT DATA DETACH (YD%NLSTLAT)
ENDIF

LNBSETLEV = ALLOCATED (YD%NBSETLEV)
IF (LNBSETLEV) THEN
  !$ACC EXIT DATA DETACH (YD%NBSETLEV)
  !$ACC EXIT DATA DETACH (YD%NBSETLEV)
ENDIF

LNGLOBALINDEX = ALLOCATED (YD%NGLOBALINDEX)
IF (LNGLOBALINDEX) THEN
  !$ACC EXIT DATA DETACH (YD%NGLOBALINDEX)
  !$ACC EXIT DATA DETACH (YD%NGLOBALINDEX)
ENDIF

LNGLOBALAT = ALLOCATED (YD%NGLOBALAT)
IF (LNGLOBALAT) THEN
  !$ACC EXIT DATA DETACH (YD%NGLOBALAT)
  !$ACC EXIT DATA DETACH (YD%NGLOBALAT)
ENDIF

LNGLOBALPROC = ALLOCATED (YD%NGLOBALPROC)
IF (LNGLOBALPROC) THEN
  !$ACC EXIT DATA DETACH (YD%NGLOBALPROC)
  !$ACC EXIT DATA DETACH (YD%NGLOBALPROC)
ENDIF

LNLOCALINDEX = ALLOCATED (YD%NLOCALINDEX)
IF (LNLOCALINDEX) THEN
  !$ACC EXIT DATA DETACH (YD%NLOCALINDEX)
  !$ACC EXIT DATA DETACH (YD%NLOCALINDEX)
ENDIF

LNLATGPP = ALLOCATED (YD%NLATGPP)
IF (LNLATGPP) THEN
  !$ACC EXIT DATA DETACH (YD%NLATGPP)
  !$ACC EXIT DATA DETACH (YD%NLATGPP)
ENDIF

LNLONGPP = ALLOCATED (YD%NLONGPP)
IF (LNLONGPP) THEN
  !$ACC EXIT DATA DETACH (YD%NLONGPP)
  !$ACC EXIT DATA DETACH (YD%NLONGPP)
ENDIF

LLSPLITLAT = ALLOCATED (YD%LSPLITLAT)
IF (LLSPLITLAT) THEN
  !$ACC EXIT DATA DETACH (YD%LSPLITLAT)
  !$ACC EXIT DATA DETACH (YD%LSPLITLAT)
ENDIF

LMYLATS = ALLOCATED (YD%MYLATS)
IF (LMYLATS) THEN
  !$ACC EXIT DATA DETACH (YD%MYLATS)
  !$ACC EXIT DATA DETACH (YD%MYLATS)
ENDIF












LNPOSSP = ALLOCATED (YD%NPOSSP)
IF (LNPOSSP) THEN
  !$ACC EXIT DATA DETACH (YD%NPOSSP)
  !$ACC EXIT DATA DETACH (YD%NPOSSP)
ENDIF

LNDIM0G = ALLOCATED (YD%NDIM0G)
IF (LNDIM0G) THEN
  !$ACC EXIT DATA DETACH (YD%NDIM0G)
  !$ACC EXIT DATA DETACH (YD%NDIM0G)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TMP (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TMP),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LNUMPP = ALLOCATED (YD%NUMPP)
IF (LNUMPP) THEN
  ISIZE = KIND (YD%NUMPP) * SIZE (YD%NUMPP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NUMPP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPROCM = ALLOCATED (YD%NPROCM)
IF (LNPROCM) THEN
  ISIZE = KIND (YD%NPROCM) * SIZE (YD%NPROCM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPROCM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRMS = ALLOCATED (YD%NPTRMS)
IF (LNPTRMS) THEN
  ISIZE = KIND (YD%NPTRMS) * SIZE (YD%NPTRMS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRMS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNALLMS = ALLOCATED (YD%NALLMS)
IF (LNALLMS) THEN
  ISIZE = KIND (YD%NALLMS) * SIZE (YD%NALLMS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NALLMS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRLS = ALLOCATED (YD%NPTRLS)
IF (LNPTRLS) THEN
  ISIZE = KIND (YD%NPTRLS) * SIZE (YD%NPTRLS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRLS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRSV = ALLOCATED (YD%NPTRSV)
IF (LNPTRSV) THEN
  ISIZE = KIND (YD%NPTRSV) * SIZE (YD%NPTRSV)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRSV'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRSVF = ALLOCATED (YD%NPTRSVF)
IF (LNPTRSVF) THEN
  ISIZE = KIND (YD%NPTRSVF) * SIZE (YD%NPTRSVF)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRSVF'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRMF = ALLOCATED (YD%NPTRMF)
IF (LNPTRMF) THEN
  ISIZE = KIND (YD%NPTRMF) * SIZE (YD%NPTRMF)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRMF'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNSPSTAF = ALLOCATED (YD%NSPSTAF)
IF (LNSPSTAF) THEN
  ISIZE = KIND (YD%NSPSTAF) * SIZE (YD%NSPSTAF)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NSPSTAF'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNUMLL = ALLOCATED (YD%NUMLL)
IF (LNUMLL) THEN
  ISIZE = KIND (YD%NUMLL) * SIZE (YD%NUMLL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NUMLL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRLL = ALLOCATED (YD%NPTRLL)
IF (LNPTRLL) THEN
  ISIZE = KIND (YD%NPTRLL) * SIZE (YD%NPTRLL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRLL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMYLEVS = ALLOCATED (YD%MYLEVS)
IF (LMYLEVS) THEN
  ISIZE = KIND (YD%MYLEVS) * SIZE (YD%MYLEVS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MYLEVS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPSURF = ALLOCATED (YD%NPSURF)
IF (LNPSURF) THEN
  ISIZE = KIND (YD%NPSURF) * SIZE (YD%NPSURF)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPSURF'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNSTA = ALLOCATED (YD%NSTA)
IF (LNSTA) THEN
  ISIZE = KIND (YD%NSTA) * SIZE (YD%NSTA)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NSTA'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNONL = ALLOCATED (YD%NONL)
IF (LNONL) THEN
  ISIZE = KIND (YD%NONL) * SIZE (YD%NONL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NONL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  ISIZE = KIND (YD%NPTRFRSTLAT) * SIZE (YD%NPTRFRSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRFRSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRLSTLAT = ALLOCATED (YD%NPTRLSTLAT)
IF (LNPTRLSTLAT) THEN
  ISIZE = KIND (YD%NPTRLSTLAT) * SIZE (YD%NPTRLSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRLSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRLAT = ALLOCATED (YD%NPTRLAT)
IF (LNPTRLAT) THEN
  ISIZE = KIND (YD%NPTRLAT) * SIZE (YD%NPTRLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
IF (LNFRSTLAT) THEN
  ISIZE = KIND (YD%NFRSTLAT) * SIZE (YD%NFRSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NFRSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNLSTLAT = ALLOCATED (YD%NLSTLAT)
IF (LNLSTLAT) THEN
  ISIZE = KIND (YD%NLSTLAT) * SIZE (YD%NLSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NLSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNBSETLEV = ALLOCATED (YD%NBSETLEV)
IF (LNBSETLEV) THEN
  ISIZE = KIND (YD%NBSETLEV) * SIZE (YD%NBSETLEV)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NBSETLEV'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNGLOBALINDEX = ALLOCATED (YD%NGLOBALINDEX)
IF (LNGLOBALINDEX) THEN
  ISIZE = KIND (YD%NGLOBALINDEX) * SIZE (YD%NGLOBALINDEX)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NGLOBALINDEX'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNGLOBALAT = ALLOCATED (YD%NGLOBALAT)
IF (LNGLOBALAT) THEN
  ISIZE = KIND (YD%NGLOBALAT) * SIZE (YD%NGLOBALAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NGLOBALAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNGLOBALPROC = ALLOCATED (YD%NGLOBALPROC)
IF (LNGLOBALPROC) THEN
  ISIZE = KIND (YD%NGLOBALPROC) * SIZE (YD%NGLOBALPROC)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NGLOBALPROC'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNLOCALINDEX = ALLOCATED (YD%NLOCALINDEX)
IF (LNLOCALINDEX) THEN
  ISIZE = KIND (YD%NLOCALINDEX) * SIZE (YD%NLOCALINDEX)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NLOCALINDEX'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNLATGPP = ALLOCATED (YD%NLATGPP)
IF (LNLATGPP) THEN
  ISIZE = KIND (YD%NLATGPP) * SIZE (YD%NLATGPP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NLATGPP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNLONGPP = ALLOCATED (YD%NLONGPP)
IF (LNLONGPP) THEN
  ISIZE = KIND (YD%NLONGPP) * SIZE (YD%NLONGPP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NLONGPP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LLSPLITLAT = ALLOCATED (YD%LSPLITLAT)
IF (LLSPLITLAT) THEN
  ISIZE = KIND (YD%LSPLITLAT) * SIZE (YD%LSPLITLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%LSPLITLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMYLATS = ALLOCATED (YD%MYLATS)
IF (LMYLATS) THEN
  ISIZE = KIND (YD%MYLATS) * SIZE (YD%MYLATS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MYLATS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%NPSP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPSP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC2V)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2V'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC2VF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2VF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC2VDDH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2VDDH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC2V_NH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2V_NH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC2V_NHX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2V_NHX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NBSETSP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NBSETSP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NFRSTLOFF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFRSTLOFF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MYFRSTACTLAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MYFRSTACTLAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MYLSTACTLAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MYLSTACTLAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPTRFLOFF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPTRFLOFF'
ENDIF
KSIZE = KSIZE + ISIZE
LNPOSSP = ALLOCATED (YD%NPOSSP)
IF (LNPOSSP) THEN
  ISIZE = KIND (YD%NPOSSP) * SIZE (YD%NPOSSP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPOSSP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNDIM0G = ALLOCATED (YD%NDIM0G)
IF (LNDIM0G) THEN
  ISIZE = KIND (YD%NDIM0G) * SIZE (YD%NDIM0G)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NDIM0G'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
