MODULE UTIL_TGMVCPL_MOD

USE YEMLBC_MODEL, ONLY : TGMVCPL

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGMVCPL
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGMVCPL
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TGMVCPL
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TGMVCPL
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TGMVCPL
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TGMVCPL
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TGMVCPL
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TGMVCPL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGMVCPL), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%MU
WRITE (KLUN) YD%MV
WRITE (KLUN) YD%MT
WRITE (KLUN) YD%MSPD
WRITE (KLUN) YD%MSVD
WRITE (KLUN) YD%MNHX
WRITE (KLUN) YD%MDIV
WRITE (KLUN) YD%MTL
WRITE (KLUN) YD%MTM
WRITE (KLUN) YD%MSPDL
WRITE (KLUN) YD%MSPDM
WRITE (KLUN) YD%NDIM
WRITE (KLUN) YD%NDIMT
END SUBROUTINE

SUBROUTINE LOAD_TGMVCPL (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGMVCPL), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%MU
READ (KLUN) YD%MV
READ (KLUN) YD%MT
READ (KLUN) YD%MSPD
READ (KLUN) YD%MSVD
READ (KLUN) YD%MNHX
READ (KLUN) YD%MDIV
READ (KLUN) YD%MTL
READ (KLUN) YD%MTM
READ (KLUN) YD%MSPDL
READ (KLUN) YD%MSPDM
READ (KLUN) YD%NDIM
READ (KLUN) YD%NDIMT
END SUBROUTINE


SUBROUTINE COPY_TGMVCPL (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGMVCPL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF













END SUBROUTINE

SUBROUTINE HOST_TGMVCPL (YD)

IMPLICIT NONE
TYPE (TGMVCPL), TARGET :: YD














END SUBROUTINE

     

SUBROUTINE CRC64_TGMVCPL (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TGMVCPL), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MU), CDPATH//'%MU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MV), CDPATH//'%MV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MT), CDPATH//'%MT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MSPD), CDPATH//'%MSPD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MSVD), CDPATH//'%MSVD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MNHX), CDPATH//'%MNHX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MDIV), CDPATH//'%MDIV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MTL), CDPATH//'%MTL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MTM), CDPATH//'%MTM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MSPDL), CDPATH//'%MSPDL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MSPDM), CDPATH//'%MSPDM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDIM), CDPATH//'%NDIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDIMT), CDPATH//'%NDIMT'

END SUBROUTINE

SUBROUTINE WIPE_TGMVCPL (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGMVCPL), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF













LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TGMVCPL (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TGMVCPL),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%MU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MSPD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSPD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MSVD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSVD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MNHX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MNHX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MDIV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MDIV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MTL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MTL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MTM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MTM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MSPDL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSPDL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MSPDM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSPDM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDIMT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDIMT'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
