MODULE UTIL_MODEL_PHYSICS_RADIATION_TYPE_MOD

USE MODEL_PHYSICS_RADIATION_MOD, ONLY : MODEL_PHYSICS_RADIATION_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_MODEL_PHYSICS_RADIATION_TYPE
END INTERFACE


CONTAINS

SUBROUTINE SAVE_MODEL_PHYSICS_RADIATION_TYPE (KLUN, YD)
USE UTIL_RADIATION_GRID_STRUCT_MOD
USE UTIL_SL_STRUCT_MOD
USE UTIL_TEAERATM_MOD
USE UTIL_TEAERD_MOD
USE UTIL_TELWRAD_MOD
USE UTIL_TEMCICA_MOD
USE UTIL_TENEUR_MOD
USE UTIL_TEOVLP_MOD
USE UTIL_TERAD_MOD
USE UTIL_TERDI_MOD
USE UTIL_TERIP_MOD
USE UTIL_TESWRT_MOD
USE UTIL_TEUVRAD_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TRADIATION_MOD
USE UTIL_TRCOEF_MOD
USE UTIL_TTRC_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_RADIATION_TYPE), INTENT (IN), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM
CALL SAVE_TERAD (KLUN, YD%YRERAD)
CALL SAVE_TESWRT (KLUN, YD%YRESWRT)
CALL SAVE_TEOVLP (KLUN, YD%YREOVLP)
CALL SAVE_TENEUR (KLUN, YD%YRENEUR)
CALL SAVE_TELWRAD (KLUN, YD%YRELWRAD)
CALL SAVE_TEAERD (KLUN, YD%YREAERD)
CALL SAVE_TEAERATM (KLUN, YD%YREAERATM)
CALL SAVE_TEUVRAD (KLUN, YD%YREUVRAD)
CALL SAVE_TERDI (KLUN, YD%YRERDI)
CALL SAVE_TEMCICA (KLUN, YD%YREMCICA)
CALL SAVE_TRCOEF (KLUN, YD%YRRCOEF)
CALL SAVE_TTRC (KLUN, YD%YRTRC)
CALL SAVE_RADIATION_GRID_STRUCT (KLUN, YD%RADGRID)
LYRAD_GSGEOM = ASSOCIATED (YD%YRAD_GSGEOM)
WRITE (KLUN) LYRAD_GSGEOM
IF (LYRAD_GSGEOM) THEN
  WRITE (KLUN) LBOUND (YD%YRAD_GSGEOM)
  WRITE (KLUN) UBOUND (YD%YRAD_GSGEOM)
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    CALL SAVE_TGSGEOM (KLUN, YD%YRAD_GSGEOM (J1))
  ENDDO
ENDIF
CALL SAVE_TERIP (KLUN, YD%YRERIP)
CALL SAVE_TRADIATION (KLUN, YD%YRADIATION)
CALL SAVE_SL_STRUCT (KLUN, YD%YRRI)
CALL SAVE_SL_STRUCT (KLUN, YD%YRRO)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_PHYSICS_RADIATION_TYPE (KLUN, YD)
USE UTIL_RADIATION_GRID_STRUCT_MOD
USE UTIL_SL_STRUCT_MOD
USE UTIL_TEAERATM_MOD
USE UTIL_TEAERD_MOD
USE UTIL_TELWRAD_MOD
USE UTIL_TEMCICA_MOD
USE UTIL_TENEUR_MOD
USE UTIL_TEOVLP_MOD
USE UTIL_TERAD_MOD
USE UTIL_TERDI_MOD
USE UTIL_TERIP_MOD
USE UTIL_TESWRT_MOD
USE UTIL_TEUVRAD_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TRADIATION_MOD
USE UTIL_TRCOEF_MOD
USE UTIL_TTRC_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_RADIATION_TYPE), INTENT (OUT), TARGET :: YD
INTEGER :: J1
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LYRAD_GSGEOM
CALL LOAD_TERAD (KLUN, YD%YRERAD)
CALL LOAD_TESWRT (KLUN, YD%YRESWRT)
CALL LOAD_TEOVLP (KLUN, YD%YREOVLP)
CALL LOAD_TENEUR (KLUN, YD%YRENEUR)
CALL LOAD_TELWRAD (KLUN, YD%YRELWRAD)
CALL LOAD_TEAERD (KLUN, YD%YREAERD)
CALL LOAD_TEAERATM (KLUN, YD%YREAERATM)
CALL LOAD_TEUVRAD (KLUN, YD%YREUVRAD)
CALL LOAD_TERDI (KLUN, YD%YRERDI)
CALL LOAD_TEMCICA (KLUN, YD%YREMCICA)
CALL LOAD_TRCOEF (KLUN, YD%YRRCOEF)
CALL LOAD_TTRC (KLUN, YD%YRTRC)
CALL LOAD_RADIATION_GRID_STRUCT (KLUN, YD%RADGRID)
READ (KLUN) LYRAD_GSGEOM
IF (LYRAD_GSGEOM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%YRAD_GSGEOM (IL1(1):IU1(1)))
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    CALL LOAD_TGSGEOM (KLUN, YD%YRAD_GSGEOM (J1))
  ENDDO
ELSE
  NULLIFY (YD%YRAD_GSGEOM)
ENDIF
CALL LOAD_TERIP (KLUN, YD%YRERIP)
CALL LOAD_TRADIATION (KLUN, YD%YRADIATION)
CALL LOAD_SL_STRUCT (KLUN, YD%YRRI)
CALL LOAD_SL_STRUCT (KLUN, YD%YRRO)
END SUBROUTINE


SUBROUTINE COPY_MODEL_PHYSICS_RADIATION_TYPE (YD, LDCREATED, LDFIELDAPI)
USE UTIL_RADIATION_GRID_STRUCT_MOD
USE UTIL_SL_STRUCT_MOD
USE UTIL_TEAERATM_MOD
USE UTIL_TEAERD_MOD
USE UTIL_TELWRAD_MOD
USE UTIL_TEMCICA_MOD
USE UTIL_TENEUR_MOD
USE UTIL_TEOVLP_MOD
USE UTIL_TERAD_MOD
USE UTIL_TERDI_MOD
USE UTIL_TERIP_MOD
USE UTIL_TESWRT_MOD
USE UTIL_TEUVRAD_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TRADIATION_MOD
USE UTIL_TRCOEF_MOD
USE UTIL_TTRC_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_RADIATION_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
CALL COPY_TERAD (YD%YRERAD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TESWRT (YD%YRESWRT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEOVLP (YD%YREOVLP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TENEUR (YD%YRENEUR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TELWRAD (YD%YRELWRAD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEAERD (YD%YREAERD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEAERATM (YD%YREAERATM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEUVRAD (YD%YREUVRAD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TERDI (YD%YRERDI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEMCICA (YD%YREMCICA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TRCOEF (YD%YRRCOEF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TTRC (YD%YRTRC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_RADIATION_GRID_STRUCT (YD%RADGRID, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LYRAD_GSGEOM = ASSOCIATED (YD%YRAD_GSGEOM)
IF (LYRAD_GSGEOM) THEN
  !$ACC ENTER DATA CREATE (YD%YRAD_GSGEOM)
  !$ACC UPDATE DEVICE (YD%YRAD_GSGEOM)
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    CALL COPY_TGSGEOM (YD%YRAD_GSGEOM (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (YD%YRAD_GSGEOM)
ENDIF

CALL COPY_TERIP (YD%YRERIP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TRADIATION (YD%YRADIATION, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_SL_STRUCT (YD%YRRI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_SL_STRUCT (YD%YRRO, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

SUBROUTINE HOST_MODEL_PHYSICS_RADIATION_TYPE (YD)
USE UTIL_RADIATION_GRID_STRUCT_MOD
USE UTIL_SL_STRUCT_MOD
USE UTIL_TEAERATM_MOD
USE UTIL_TEAERD_MOD
USE UTIL_TELWRAD_MOD
USE UTIL_TEMCICA_MOD
USE UTIL_TENEUR_MOD
USE UTIL_TEOVLP_MOD
USE UTIL_TERAD_MOD
USE UTIL_TERDI_MOD
USE UTIL_TERIP_MOD
USE UTIL_TESWRT_MOD
USE UTIL_TEUVRAD_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TRADIATION_MOD
USE UTIL_TRCOEF_MOD
USE UTIL_TTRC_MOD

IMPLICIT NONE
TYPE (MODEL_PHYSICS_RADIATION_TYPE), TARGET :: YD
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM
CALL HOST_TERAD (YD%YRERAD)

CALL HOST_TESWRT (YD%YRESWRT)

CALL HOST_TEOVLP (YD%YREOVLP)

CALL HOST_TENEUR (YD%YRENEUR)

CALL HOST_TELWRAD (YD%YRELWRAD)

CALL HOST_TEAERD (YD%YREAERD)

CALL HOST_TEAERATM (YD%YREAERATM)

CALL HOST_TEUVRAD (YD%YREUVRAD)

CALL HOST_TERDI (YD%YRERDI)

CALL HOST_TEMCICA (YD%YREMCICA)

CALL HOST_TRCOEF (YD%YRRCOEF)

CALL HOST_TTRC (YD%YRTRC)

CALL HOST_RADIATION_GRID_STRUCT (YD%RADGRID)

LYRAD_GSGEOM = ASSOCIATED (YD%YRAD_GSGEOM)
IF (LYRAD_GSGEOM) THEN
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    CALL HOST_TGSGEOM (YD%YRAD_GSGEOM (J1))
  ENDDO
ENDIF

CALL HOST_TERIP (YD%YRERIP)

CALL HOST_TRADIATION (YD%YRADIATION)

CALL HOST_SL_STRUCT (YD%YRRI)

CALL HOST_SL_STRUCT (YD%YRRO)

END SUBROUTINE

     

SUBROUTINE CRC64_MODEL_PHYSICS_RADIATION_TYPE (YD, KLUN, CDPATH)
USE UTIL_RADIATION_GRID_STRUCT_MOD
USE UTIL_SL_STRUCT_MOD
USE UTIL_TEAERATM_MOD
USE UTIL_TEAERD_MOD
USE UTIL_TELWRAD_MOD
USE UTIL_TEMCICA_MOD
USE UTIL_TENEUR_MOD
USE UTIL_TEOVLP_MOD
USE UTIL_TERAD_MOD
USE UTIL_TERDI_MOD
USE UTIL_TERIP_MOD
USE UTIL_TESWRT_MOD
USE UTIL_TEUVRAD_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TRADIATION_MOD
USE UTIL_TRCOEF_MOD
USE UTIL_TTRC_MOD
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (MODEL_PHYSICS_RADIATION_TYPE), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM
CLIND = ''
CALL CRC64_TERAD (YD%YRERAD, KLUN, CDPATH//'%YRERAD'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TESWRT (YD%YRESWRT, KLUN, CDPATH//'%YRESWRT'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TEOVLP (YD%YREOVLP, KLUN, CDPATH//'%YREOVLP'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TENEUR (YD%YRENEUR, KLUN, CDPATH//'%YRENEUR'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TELWRAD (YD%YRELWRAD, KLUN, CDPATH//'%YRELWRAD'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TEAERD (YD%YREAERD, KLUN, CDPATH//'%YREAERD'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TEAERATM (YD%YREAERATM, KLUN, CDPATH//'%YREAERATM'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TEUVRAD (YD%YREUVRAD, KLUN, CDPATH//'%YREUVRAD'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TERDI (YD%YRERDI, KLUN, CDPATH//'%YRERDI'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TEMCICA (YD%YREMCICA, KLUN, CDPATH//'%YREMCICA'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TRCOEF (YD%YRRCOEF, KLUN, CDPATH//'%YRRCOEF'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TTRC (YD%YRTRC, KLUN, CDPATH//'%YRTRC'//TRIM(CLIND))

CLIND = ''
CALL CRC64_RADIATION_GRID_STRUCT (YD%RADGRID, KLUN, CDPATH//'%RADGRID'//TRIM(CLIND))

LYRAD_GSGEOM = ASSOCIATED (YD%YRAD_GSGEOM)
IF (LYRAD_GSGEOM) THEN
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL CRC64_TGSGEOM (YD%YRAD_GSGEOM (J1), KLUN, CDPATH//'%YRAD_GSGEOM'//TRIM(CLIND))
  ENDDO
ENDIF

CLIND = ''
CALL CRC64_TERIP (YD%YRERIP, KLUN, CDPATH//'%YRERIP'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TRADIATION (YD%YRADIATION, KLUN, CDPATH//'%YRADIATION'//TRIM(CLIND))

CLIND = ''
CALL CRC64_SL_STRUCT (YD%YRRI, KLUN, CDPATH//'%YRRI'//TRIM(CLIND))

CLIND = ''
CALL CRC64_SL_STRUCT (YD%YRRO, KLUN, CDPATH//'%YRRO'//TRIM(CLIND))

END SUBROUTINE

SUBROUTINE WIPE_MODEL_PHYSICS_RADIATION_TYPE (YD, LDDELETED, LDFIELDAPI)
USE UTIL_RADIATION_GRID_STRUCT_MOD
USE UTIL_SL_STRUCT_MOD
USE UTIL_TEAERATM_MOD
USE UTIL_TEAERD_MOD
USE UTIL_TELWRAD_MOD
USE UTIL_TEMCICA_MOD
USE UTIL_TENEUR_MOD
USE UTIL_TEOVLP_MOD
USE UTIL_TERAD_MOD
USE UTIL_TERDI_MOD
USE UTIL_TERIP_MOD
USE UTIL_TESWRT_MOD
USE UTIL_TEUVRAD_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TRADIATION_MOD
USE UTIL_TRCOEF_MOD
USE UTIL_TTRC_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_RADIATION_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL WIPE_TERAD (YD%YRERAD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TESWRT (YD%YRESWRT, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEOVLP (YD%YREOVLP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TENEUR (YD%YRENEUR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TELWRAD (YD%YRELWRAD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEAERD (YD%YREAERD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEAERATM (YD%YREAERATM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEUVRAD (YD%YREUVRAD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TERDI (YD%YRERDI, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEMCICA (YD%YREMCICA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TRCOEF (YD%YRRCOEF, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TTRC (YD%YRTRC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_RADIATION_GRID_STRUCT (YD%RADGRID, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LYRAD_GSGEOM = ASSOCIATED (YD%YRAD_GSGEOM)
IF (LYRAD_GSGEOM) THEN
  !$ACC EXIT DATA DETACH (YD%YRAD_GSGEOM)
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    CALL WIPE_TGSGEOM (YD%YRAD_GSGEOM (J1), LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DETACH (YD%YRAD_GSGEOM)
ENDIF

CALL WIPE_TERIP (YD%YRERIP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TRADIATION (YD%YRADIATION, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_SL_STRUCT (YD%YRRI, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_SL_STRUCT (YD%YRRO, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_MODEL_PHYSICS_RADIATION_TYPE (YD, CDPATH, LDPRINT) RESULT (KSIZE)
USE UTIL_RADIATION_GRID_STRUCT_MOD
USE UTIL_SL_STRUCT_MOD
USE UTIL_TEAERATM_MOD
USE UTIL_TEAERD_MOD
USE UTIL_TELWRAD_MOD
USE UTIL_TEMCICA_MOD
USE UTIL_TENEUR_MOD
USE UTIL_TEOVLP_MOD
USE UTIL_TERAD_MOD
USE UTIL_TERDI_MOD
USE UTIL_TERIP_MOD
USE UTIL_TESWRT_MOD
USE UTIL_TEUVRAD_MOD
USE UTIL_TGSGEOM_MOD
USE UTIL_TRADIATION_MOD
USE UTIL_TRCOEF_MOD
USE UTIL_TTRC_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_RADIATION_TYPE),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
JSIZE = 0
ISIZE = SIZE_TERAD (YD%YRERAD, CLPATH//'%YRERAD', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRERAD'
ENDIF
JSIZE = 0
ISIZE = SIZE_TESWRT (YD%YRESWRT, CLPATH//'%YRESWRT', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRESWRT'
ENDIF
JSIZE = 0
ISIZE = SIZE_TEOVLP (YD%YREOVLP, CLPATH//'%YREOVLP', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREOVLP'
ENDIF
JSIZE = 0
ISIZE = SIZE_TENEUR (YD%YRENEUR, CLPATH//'%YRENEUR', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRENEUR'
ENDIF
JSIZE = 0
ISIZE = SIZE_TELWRAD (YD%YRELWRAD, CLPATH//'%YRELWRAD', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRELWRAD'
ENDIF
JSIZE = 0
ISIZE = SIZE_TEAERD (YD%YREAERD, CLPATH//'%YREAERD', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREAERD'
ENDIF
JSIZE = 0
ISIZE = SIZE_TEAERATM (YD%YREAERATM, CLPATH//'%YREAERATM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREAERATM'
ENDIF
JSIZE = 0
ISIZE = SIZE_TEUVRAD (YD%YREUVRAD, CLPATH//'%YREUVRAD', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREUVRAD'
ENDIF
JSIZE = 0
ISIZE = SIZE_TERDI (YD%YRERDI, CLPATH//'%YRERDI', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRERDI'
ENDIF
JSIZE = 0
ISIZE = SIZE_TEMCICA (YD%YREMCICA, CLPATH//'%YREMCICA', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREMCICA'
ENDIF
JSIZE = 0
ISIZE = SIZE_TRCOEF (YD%YRRCOEF, CLPATH//'%YRRCOEF', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRRCOEF'
ENDIF
JSIZE = 0
ISIZE = SIZE_TTRC (YD%YRTRC, CLPATH//'%YRTRC', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRTRC'
ENDIF
JSIZE = 0
ISIZE = SIZE_RADIATION_GRID_STRUCT (YD%RADGRID, CLPATH//'%RADGRID', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RADGRID'
ENDIF
LYRAD_GSGEOM = ASSOCIATED (YD%YRAD_GSGEOM)
IF (LYRAD_GSGEOM) THEN
  JSIZE = 0
  DO J1 = LBOUND (YD%YRAD_GSGEOM, 1), UBOUND (YD%YRAD_GSGEOM, 1)
    ISIZE = SIZE_TGSGEOM (YD%YRAD_GSGEOM (J1), CLPATH//'%YRAD_GSGEOM', .FALSE.)
    JSIZE = JSIZE + ISIZE
    KSIZE = KSIZE + ISIZE
  ENDDO
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
    WRITE (*, *) TRIM (CLPATH)//'%YRAD_GSGEOM'
  ENDIF
ENDIF
JSIZE = 0
ISIZE = SIZE_TERIP (YD%YRERIP, CLPATH//'%YRERIP', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRERIP'
ENDIF
JSIZE = 0
ISIZE = SIZE_TRADIATION (YD%YRADIATION, CLPATH//'%YRADIATION', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRADIATION'
ENDIF
JSIZE = 0
ISIZE = SIZE_SL_STRUCT (YD%YRRI, CLPATH//'%YRRI', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRRI'
ENDIF
JSIZE = 0
ISIZE = SIZE_SL_STRUCT (YD%YRRO, CLPATH//'%YRRO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRRO'
ENDIF
END FUNCTION

END MODULE
