MODULE UTIL_TVSLETA_MOD

USE YOMVSLETA, ONLY : TVSLETA

INTERFACE SAVE
MODULE PROCEDURE SAVE_TVSLETA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TVSLETA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TVSLETA
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TVSLETA
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TVSLETA
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TVSLETA
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TVSLETA
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TVSLETA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSLETA), INTENT (IN), TARGET :: YD
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
LOGICAL :: LVSLVF, LVSLVFH
LVCUICO = ALLOCATED (YD%VCUICO)
WRITE (KLUN) LVCUICO
IF (LVCUICO) THEN
  WRITE (KLUN) LBOUND (YD%VCUICO)
  WRITE (KLUN) UBOUND (YD%VCUICO)
  WRITE (KLUN) YD%VCUICO
ENDIF
LVCUICOH = ALLOCATED (YD%VCUICOH)
WRITE (KLUN) LVCUICOH
IF (LVCUICOH) THEN
  WRITE (KLUN) LBOUND (YD%VCUICOH)
  WRITE (KLUN) UBOUND (YD%VCUICOH)
  WRITE (KLUN) YD%VCUICOH
ENDIF
LVSLD = ALLOCATED (YD%VSLD)
WRITE (KLUN) LVSLD
IF (LVSLD) THEN
  WRITE (KLUN) LBOUND (YD%VSLD)
  WRITE (KLUN) UBOUND (YD%VSLD)
  WRITE (KLUN) YD%VSLD
ENDIF
LVSLDH = ALLOCATED (YD%VSLDH)
WRITE (KLUN) LVSLDH
IF (LVSLDH) THEN
  WRITE (KLUN) LBOUND (YD%VSLDH)
  WRITE (KLUN) UBOUND (YD%VSLDH)
  WRITE (KLUN) YD%VSLDH
ENDIF
LVSLDW = ALLOCATED (YD%VSLDW)
WRITE (KLUN) LVSLDW
IF (LVSLDW) THEN
  WRITE (KLUN) LBOUND (YD%VSLDW)
  WRITE (KLUN) UBOUND (YD%VSLDW)
  WRITE (KLUN) YD%VSLDW
ENDIF
LVSLDWH = ALLOCATED (YD%VSLDWH)
WRITE (KLUN) LVSLDWH
IF (LVSLDWH) THEN
  WRITE (KLUN) LBOUND (YD%VSLDWH)
  WRITE (KLUN) UBOUND (YD%VSLDWH)
  WRITE (KLUN) YD%VSLDWH
ENDIF
LVSLVF = ALLOCATED (YD%VSLVF)
WRITE (KLUN) LVSLVF
IF (LVSLVF) THEN
  WRITE (KLUN) LBOUND (YD%VSLVF)
  WRITE (KLUN) UBOUND (YD%VSLVF)
  WRITE (KLUN) YD%VSLVF
ENDIF
LVSLVFH = ALLOCATED (YD%VSLVFH)
WRITE (KLUN) LVSLVFH
IF (LVSLVFH) THEN
  WRITE (KLUN) LBOUND (YD%VSLVFH)
  WRITE (KLUN) UBOUND (YD%VSLVFH)
  WRITE (KLUN) YD%VSLVFH
ENDIF
LGAMMA_WENO = ALLOCATED (YD%GAMMA_WENO)
WRITE (KLUN) LGAMMA_WENO
IF (LGAMMA_WENO) THEN
  WRITE (KLUN) LBOUND (YD%GAMMA_WENO)
  WRITE (KLUN) UBOUND (YD%GAMMA_WENO)
  WRITE (KLUN) YD%GAMMA_WENO
ENDIF
LVRDETAR = ALLOCATED (YD%VRDETAR)
WRITE (KLUN) LVRDETAR
IF (LVRDETAR) THEN
  WRITE (KLUN) LBOUND (YD%VRDETAR)
  WRITE (KLUN) UBOUND (YD%VRDETAR)
  WRITE (KLUN) YD%VRDETAR
ENDIF
WRITE (KLUN) YD%NRLEVX
WRITE (KLUN) YD%VRLEVX
LNVAUTF = ALLOCATED (YD%NVAUTF)
WRITE (KLUN) LNVAUTF
IF (LNVAUTF) THEN
  WRITE (KLUN) LBOUND (YD%NVAUTF)
  WRITE (KLUN) UBOUND (YD%NVAUTF)
  WRITE (KLUN) YD%NVAUTF
ENDIF
LNVAUTH = ALLOCATED (YD%NVAUTH)
WRITE (KLUN) LNVAUTH
IF (LNVAUTH) THEN
  WRITE (KLUN) LBOUND (YD%NVAUTH)
  WRITE (KLUN) UBOUND (YD%NVAUTH)
  WRITE (KLUN) YD%NVAUTH
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TVSLETA (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TVSLETA), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
LOGICAL :: LVSLVF, LVSLVFH
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) LVCUICO
IF (LVCUICO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VCUICO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%VCUICO,1):UBOUND(YD%VCUICO,1), LBOUND(YD%VCUICO,2):UBOUND(YD%VCUICO,2)))
  READ (KLUN) ZTMP2
  YD%VCUICO = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LVCUICOH
IF (LVCUICOH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VCUICOH (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%VCUICOH,1):UBOUND(YD%VCUICOH,1), LBOUND(YD%VCUICOH,2):UBOUND(YD%VCUICOH,2)))
  READ (KLUN) ZTMP2
  YD%VCUICOH = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LVSLD
IF (LVSLD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VSLD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%VSLD,1):UBOUND(YD%VSLD,1), LBOUND(YD%VSLD,2):UBOUND(YD%VSLD,2)))
  READ (KLUN) ZTMP2
  YD%VSLD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LVSLDH
IF (LVSLDH) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%VSLDH (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%VSLDH,1):UBOUND(YD%VSLDH,1), LBOUND(YD%VSLDH,2):UBOUND(YD%VSLDH,2)))
  READ (KLUN) ZTMP2
  YD%VSLDH = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LVSLDW
IF (LVSLDW) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLDW (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%VSLDW,1):UBOUND(YD%VSLDW,1), LBOUND(YD%VSLDW,2):UBOUND(YD%VSLDW,2), LBOUND(YD%VSLDW,3):UBOUND(YD%VSLDW,3)))
  READ (KLUN) ZTMP3
  YD%VSLDW = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LVSLDWH
IF (LVSLDWH) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLDWH (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%VSLDWH,1):UBOUND(YD%VSLDWH,1), LBOUND(YD%VSLDWH,2):UBOUND(YD%VSLDWH,2), LBOUND(YD%VSLDWH,3):UBOUND(YD%VSLDWH,3)))
  READ (KLUN) ZTMP3
  YD%VSLDWH = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LVSLVF
IF (LVSLVF) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLVF (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%VSLVF,1):UBOUND(YD%VSLVF,1), LBOUND(YD%VSLVF,2):UBOUND(YD%VSLVF,2), LBOUND(YD%VSLVF,3):UBOUND(YD%VSLVF,3)))
  READ (KLUN) ZTMP3
  YD%VSLVF = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LVSLVFH
IF (LVSLVFH) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%VSLVFH (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%VSLVFH,1):UBOUND(YD%VSLVFH,1), LBOUND(YD%VSLVFH,2):UBOUND(YD%VSLVFH,2), LBOUND(YD%VSLVFH,3):UBOUND(YD%VSLVFH,3)))
  READ (KLUN) ZTMP3
  YD%VSLVFH = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LGAMMA_WENO
IF (LGAMMA_WENO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GAMMA_WENO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GAMMA_WENO,1):UBOUND(YD%GAMMA_WENO,1), LBOUND(YD%GAMMA_WENO,2):UBOUND(YD%GAMMA_WENO,2)))
  READ (KLUN) ZTMP2
  YD%GAMMA_WENO = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LVRDETAR
IF (LVRDETAR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%VRDETAR (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%VRDETAR,1):UBOUND(YD%VRDETAR,1)))
  READ (KLUN) ZTMP1
  YD%VRDETAR = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) YD%NRLEVX
READ (KLUN) ZTMP0
YD%VRLEVX = ZTMP0
READ (KLUN) LNVAUTF
IF (LNVAUTF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NVAUTF (IL1(1):IU1(1)))
  READ (KLUN) YD%NVAUTF
ENDIF
READ (KLUN) LNVAUTH
IF (LNVAUTH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NVAUTH (IL1(1):IU1(1)))
  READ (KLUN) YD%NVAUTH
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TVSLETA (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TVSLETA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
LOGICAL :: LVSLVF, LVSLVFH

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LVCUICO = ALLOCATED (YD%VCUICO)
IF (LVCUICO) THEN
  !$ACC ENTER DATA CREATE (YD%VCUICO)
  !$ACC UPDATE DEVICE (YD%VCUICO)
  !$ACC ENTER DATA ATTACH (YD%VCUICO)
ENDIF

LVCUICOH = ALLOCATED (YD%VCUICOH)
IF (LVCUICOH) THEN
  !$ACC ENTER DATA CREATE (YD%VCUICOH)
  !$ACC UPDATE DEVICE (YD%VCUICOH)
  !$ACC ENTER DATA ATTACH (YD%VCUICOH)
ENDIF

LVSLD = ALLOCATED (YD%VSLD)
IF (LVSLD) THEN
  !$ACC ENTER DATA CREATE (YD%VSLD)
  !$ACC UPDATE DEVICE (YD%VSLD)
  !$ACC ENTER DATA ATTACH (YD%VSLD)
ENDIF

LVSLDH = ALLOCATED (YD%VSLDH)
IF (LVSLDH) THEN
  !$ACC ENTER DATA CREATE (YD%VSLDH)
  !$ACC UPDATE DEVICE (YD%VSLDH)
  !$ACC ENTER DATA ATTACH (YD%VSLDH)
ENDIF

LVSLDW = ALLOCATED (YD%VSLDW)
IF (LVSLDW) THEN
  !$ACC ENTER DATA CREATE (YD%VSLDW)
  !$ACC UPDATE DEVICE (YD%VSLDW)
  !$ACC ENTER DATA ATTACH (YD%VSLDW)
ENDIF

LVSLDWH = ALLOCATED (YD%VSLDWH)
IF (LVSLDWH) THEN
  !$ACC ENTER DATA CREATE (YD%VSLDWH)
  !$ACC UPDATE DEVICE (YD%VSLDWH)
  !$ACC ENTER DATA ATTACH (YD%VSLDWH)
ENDIF

LVSLVF = ALLOCATED (YD%VSLVF)
IF (LVSLVF) THEN
  !$ACC ENTER DATA CREATE (YD%VSLVF)
  !$ACC UPDATE DEVICE (YD%VSLVF)
  !$ACC ENTER DATA ATTACH (YD%VSLVF)
ENDIF

LVSLVFH = ALLOCATED (YD%VSLVFH)
IF (LVSLVFH) THEN
  !$ACC ENTER DATA CREATE (YD%VSLVFH)
  !$ACC UPDATE DEVICE (YD%VSLVFH)
  !$ACC ENTER DATA ATTACH (YD%VSLVFH)
ENDIF

LGAMMA_WENO = ALLOCATED (YD%GAMMA_WENO)
IF (LGAMMA_WENO) THEN
  !$ACC ENTER DATA CREATE (YD%GAMMA_WENO)
  !$ACC UPDATE DEVICE (YD%GAMMA_WENO)
  !$ACC ENTER DATA ATTACH (YD%GAMMA_WENO)
ENDIF

LVRDETAR = ALLOCATED (YD%VRDETAR)
IF (LVRDETAR) THEN
  !$ACC ENTER DATA CREATE (YD%VRDETAR)
  !$ACC UPDATE DEVICE (YD%VRDETAR)
  !$ACC ENTER DATA ATTACH (YD%VRDETAR)
ENDIF



LNVAUTF = ALLOCATED (YD%NVAUTF)
IF (LNVAUTF) THEN
  !$ACC ENTER DATA CREATE (YD%NVAUTF)
  !$ACC UPDATE DEVICE (YD%NVAUTF)
  !$ACC ENTER DATA ATTACH (YD%NVAUTF)
ENDIF

LNVAUTH = ALLOCATED (YD%NVAUTH)
IF (LNVAUTH) THEN
  !$ACC ENTER DATA CREATE (YD%NVAUTH)
  !$ACC UPDATE DEVICE (YD%NVAUTH)
  !$ACC ENTER DATA ATTACH (YD%NVAUTH)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TVSLETA (YD)

IMPLICIT NONE
TYPE (TVSLETA), TARGET :: YD
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
LOGICAL :: LVSLVF, LVSLVFH














END SUBROUTINE

     

SUBROUTINE CRC64_TVSLETA (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TVSLETA), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
LOGICAL :: LVSLVF, LVSLVFH
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VCUICO), CDPATH//'%VCUICO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VCUICOH), CDPATH//'%VCUICOH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VSLD), CDPATH//'%VSLD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VSLDH), CDPATH//'%VSLDH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VSLDW), CDPATH//'%VSLDW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VSLDWH), CDPATH//'%VSLDWH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VSLVF), CDPATH//'%VSLVF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VSLVFH), CDPATH//'%VSLVFH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GAMMA_WENO), CDPATH//'%GAMMA_WENO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VRDETAR), CDPATH//'%VRDETAR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NRLEVX), CDPATH//'%NRLEVX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%VRLEVX), CDPATH//'%VRLEVX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NVAUTF), CDPATH//'%NVAUTF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NVAUTH), CDPATH//'%NVAUTH'

END SUBROUTINE

SUBROUTINE WIPE_TVSLETA (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TVSLETA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
LOGICAL :: LVSLVF, LVSLVFH

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVCUICO = ALLOCATED (YD%VCUICO)
IF (LVCUICO) THEN
  !$ACC EXIT DATA DETACH (YD%VCUICO)
  !$ACC EXIT DATA DETACH (YD%VCUICO)
ENDIF

LVCUICOH = ALLOCATED (YD%VCUICOH)
IF (LVCUICOH) THEN
  !$ACC EXIT DATA DETACH (YD%VCUICOH)
  !$ACC EXIT DATA DETACH (YD%VCUICOH)
ENDIF

LVSLD = ALLOCATED (YD%VSLD)
IF (LVSLD) THEN
  !$ACC EXIT DATA DETACH (YD%VSLD)
  !$ACC EXIT DATA DETACH (YD%VSLD)
ENDIF

LVSLDH = ALLOCATED (YD%VSLDH)
IF (LVSLDH) THEN
  !$ACC EXIT DATA DETACH (YD%VSLDH)
  !$ACC EXIT DATA DETACH (YD%VSLDH)
ENDIF

LVSLDW = ALLOCATED (YD%VSLDW)
IF (LVSLDW) THEN
  !$ACC EXIT DATA DETACH (YD%VSLDW)
  !$ACC EXIT DATA DETACH (YD%VSLDW)
ENDIF

LVSLDWH = ALLOCATED (YD%VSLDWH)
IF (LVSLDWH) THEN
  !$ACC EXIT DATA DETACH (YD%VSLDWH)
  !$ACC EXIT DATA DETACH (YD%VSLDWH)
ENDIF

LVSLVF = ALLOCATED (YD%VSLVF)
IF (LVSLVF) THEN
  !$ACC EXIT DATA DETACH (YD%VSLVF)
  !$ACC EXIT DATA DETACH (YD%VSLVF)
ENDIF

LVSLVFH = ALLOCATED (YD%VSLVFH)
IF (LVSLVFH) THEN
  !$ACC EXIT DATA DETACH (YD%VSLVFH)
  !$ACC EXIT DATA DETACH (YD%VSLVFH)
ENDIF

LGAMMA_WENO = ALLOCATED (YD%GAMMA_WENO)
IF (LGAMMA_WENO) THEN
  !$ACC EXIT DATA DETACH (YD%GAMMA_WENO)
  !$ACC EXIT DATA DETACH (YD%GAMMA_WENO)
ENDIF

LVRDETAR = ALLOCATED (YD%VRDETAR)
IF (LVRDETAR) THEN
  !$ACC EXIT DATA DETACH (YD%VRDETAR)
  !$ACC EXIT DATA DETACH (YD%VRDETAR)
ENDIF



LNVAUTF = ALLOCATED (YD%NVAUTF)
IF (LNVAUTF) THEN
  !$ACC EXIT DATA DETACH (YD%NVAUTF)
  !$ACC EXIT DATA DETACH (YD%NVAUTF)
ENDIF

LNVAUTH = ALLOCATED (YD%NVAUTH)
IF (LNVAUTH) THEN
  !$ACC EXIT DATA DETACH (YD%NVAUTH)
  !$ACC EXIT DATA DETACH (YD%NVAUTH)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TVSLETA (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TVSLETA),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LGAMMA_WENO, LNVAUTF, LNVAUTH, LVCUICO, LVCUICOH, LVRDETAR, LVSLD, LVSLDH, LVSLDW, LVSLDWH
LOGICAL :: LVSLVF, LVSLVFH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LVCUICO = ALLOCATED (YD%VCUICO)
IF (LVCUICO) THEN
  ISIZE = KIND (YD%VCUICO) * SIZE (YD%VCUICO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%VCUICO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LVCUICOH = ALLOCATED (YD%VCUICOH)
IF (LVCUICOH) THEN
  ISIZE = KIND (YD%VCUICOH) * SIZE (YD%VCUICOH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%VCUICOH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LVSLD = ALLOCATED (YD%VSLD)
IF (LVSLD) THEN
  ISIZE = KIND (YD%VSLD) * SIZE (YD%VSLD)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%VSLD'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LVSLDH = ALLOCATED (YD%VSLDH)
IF (LVSLDH) THEN
  ISIZE = KIND (YD%VSLDH) * SIZE (YD%VSLDH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%VSLDH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LVSLDW = ALLOCATED (YD%VSLDW)
IF (LVSLDW) THEN
  ISIZE = KIND (YD%VSLDW) * SIZE (YD%VSLDW)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%VSLDW'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LVSLDWH = ALLOCATED (YD%VSLDWH)
IF (LVSLDWH) THEN
  ISIZE = KIND (YD%VSLDWH) * SIZE (YD%VSLDWH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%VSLDWH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LVSLVF = ALLOCATED (YD%VSLVF)
IF (LVSLVF) THEN
  ISIZE = KIND (YD%VSLVF) * SIZE (YD%VSLVF)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%VSLVF'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LVSLVFH = ALLOCATED (YD%VSLVFH)
IF (LVSLVFH) THEN
  ISIZE = KIND (YD%VSLVFH) * SIZE (YD%VSLVFH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%VSLVFH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGAMMA_WENO = ALLOCATED (YD%GAMMA_WENO)
IF (LGAMMA_WENO) THEN
  ISIZE = KIND (YD%GAMMA_WENO) * SIZE (YD%GAMMA_WENO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GAMMA_WENO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LVRDETAR = ALLOCATED (YD%VRDETAR)
IF (LVRDETAR) THEN
  ISIZE = KIND (YD%VRDETAR) * SIZE (YD%VRDETAR)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%VRDETAR'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%NRLEVX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NRLEVX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%VRLEVX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%VRLEVX'
ENDIF
KSIZE = KSIZE + ISIZE
LNVAUTF = ALLOCATED (YD%NVAUTF)
IF (LNVAUTF) THEN
  ISIZE = KIND (YD%NVAUTF) * SIZE (YD%NVAUTF)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NVAUTF'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNVAUTH = ALLOCATED (YD%NVAUTH)
IF (LNVAUTH) THEN
  ISIZE = KIND (YD%NVAUTH) * SIZE (YD%NVAUTH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NVAUTH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
