MODULE UTIL_TCOMPO_EMIS_AUX_MOD

USE YOMCOMPO, ONLY : TCOMPO_EMIS_AUX

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TCOMPO_EMIS_AUX
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCOMPO_EMIS_AUX
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TCOMPO_EMIS_AUX
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TCOMPO_EMIS_AUX (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCOMPO_EMIS_AUX), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%PARAMID
WRITE (KLUN) YD%TEMPORALITY
WRITE (KLUN) YD%CNAME
END SUBROUTINE

SUBROUTINE LOAD_TCOMPO_EMIS_AUX (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCOMPO_EMIS_AUX), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%PARAMID
READ (KLUN) YD%TEMPORALITY
READ (KLUN) YD%CNAME
END SUBROUTINE


SUBROUTINE COPY_TCOMPO_EMIS_AUX (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF



END SUBROUTINE

SUBROUTINE HOST_TCOMPO_EMIS_AUX (YD)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), TARGET :: YD




END SUBROUTINE

     

SUBROUTINE CRC64_TCOMPO_EMIS_AUX (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%PARAMID), CDPATH//'%PARAMID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%TEMPORALITY), CDPATH//'%TEMPORALITY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CNAME), CDPATH//'%CNAME'

END SUBROUTINE

SUBROUTINE WIPE_TCOMPO_EMIS_AUX (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF



LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TCOMPO_EMIS_AUX (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TCOMPO_EMIS_AUX),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%PARAMID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%PARAMID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%TEMPORALITY) * LEN (YD%TEMPORALITY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TEMPORALITY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CNAME) * LEN (YD%CNAME)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CNAME'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
