MODULE UTIL_ECV_CONTAINER_MOD

USE TYPE_ECV, ONLY : ECV_CONTAINER

INTERFACE SAVE
MODULE PROCEDURE SAVE_ECV_CONTAINER
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_ECV_CONTAINER
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_ECV_CONTAINER
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_ECV_CONTAINER
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_ECV_CONTAINER
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_ECV_CONTAINER
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_ECV_CONTAINER
END INTERFACE


CONTAINS

SUBROUTINE SAVE_ECV_CONTAINER (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (ECV_CONTAINER), INTENT (IN), TARGET :: YD
LOGICAL :: LRECV1D, LRGPECV2D, LRGPECV3D, LRLSM, LRSPECV2D, LRSPECV3D
LRECV1D = ALLOCATED (YD%RECV1D)
WRITE (KLUN) LRECV1D
IF (LRECV1D) THEN
  WRITE (KLUN) LBOUND (YD%RECV1D)
  WRITE (KLUN) UBOUND (YD%RECV1D)
  WRITE (KLUN) YD%RECV1D
ENDIF
LRSPECV2D = ALLOCATED (YD%RSPECV2D)
WRITE (KLUN) LRSPECV2D
IF (LRSPECV2D) THEN
  WRITE (KLUN) LBOUND (YD%RSPECV2D)
  WRITE (KLUN) UBOUND (YD%RSPECV2D)
  WRITE (KLUN) YD%RSPECV2D
ENDIF
LRGPECV2D = ALLOCATED (YD%RGPECV2D)
WRITE (KLUN) LRGPECV2D
IF (LRGPECV2D) THEN
  WRITE (KLUN) LBOUND (YD%RGPECV2D)
  WRITE (KLUN) UBOUND (YD%RGPECV2D)
  WRITE (KLUN) YD%RGPECV2D
ENDIF
LRSPECV3D = ALLOCATED (YD%RSPECV3D)
WRITE (KLUN) LRSPECV3D
IF (LRSPECV3D) THEN
  WRITE (KLUN) LBOUND (YD%RSPECV3D)
  WRITE (KLUN) UBOUND (YD%RSPECV3D)
  WRITE (KLUN) YD%RSPECV3D
ENDIF
LRGPECV3D = ALLOCATED (YD%RGPECV3D)
WRITE (KLUN) LRGPECV3D
IF (LRGPECV3D) THEN
  WRITE (KLUN) LBOUND (YD%RGPECV3D)
  WRITE (KLUN) UBOUND (YD%RGPECV3D)
  WRITE (KLUN) YD%RGPECV3D
ENDIF
LRLSM = ALLOCATED (YD%RLSM)
WRITE (KLUN) LRLSM
IF (LRLSM) THEN
  WRITE (KLUN) LBOUND (YD%RLSM)
  WRITE (KLUN) UBOUND (YD%RLSM)
  WRITE (KLUN) YD%RLSM
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_ECV_CONTAINER (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (ECV_CONTAINER), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LRECV1D, LRGPECV2D, LRGPECV3D, LRLSM, LRSPECV2D, LRSPECV3D
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP4 (:,:,:,:)
READ (KLUN) LRECV1D
IF (LRECV1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RECV1D (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RECV1D,1):UBOUND(YD%RECV1D,1)))
  READ (KLUN) ZTMP1
  YD%RECV1D = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRSPECV2D
IF (LRSPECV2D) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RSPECV2D (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RSPECV2D,1):UBOUND(YD%RSPECV2D,1), LBOUND(YD%RSPECV2D,2):UBOUND(YD%RSPECV2D,2)))
  READ (KLUN) ZTMP2
  YD%RSPECV2D = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRGPECV2D
IF (LRGPECV2D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RGPECV2D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RGPECV2D,1):UBOUND(YD%RGPECV2D,1), LBOUND(YD%RGPECV2D,2):UBOUND(YD%RGPECV2D,2), LBOUND(YD%RGPECV2D,3):UBOUND(YD%RGPECV2D,3)))
  READ (KLUN) ZTMP3
  YD%RGPECV2D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRSPECV3D
IF (LRSPECV3D) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RSPECV3D (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RSPECV3D,1):UBOUND(YD%RSPECV3D,1), LBOUND(YD%RSPECV3D,2):UBOUND(YD%RSPECV3D,2), LBOUND(YD%RSPECV3D,3):UBOUND(YD%RSPECV3D,3)))
  READ (KLUN) ZTMP3
  YD%RSPECV3D = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRGPECV3D
IF (LRGPECV3D) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (YD%RGPECV3D (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(YD%RGPECV3D,1):UBOUND(YD%RGPECV3D,1), LBOUND(YD%RGPECV3D,2):UBOUND(YD%RGPECV3D,2), LBOUND(YD%RGPECV3D,3):UBOUND(YD%RGPECV3D,3), LBOUND(YD%RGPECV3D,4):UBOUND(YD%RGPECV3D,4)))
  READ (KLUN) ZTMP4
  YD%RGPECV3D = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LRLSM
IF (LRLSM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RLSM (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RLSM,1):UBOUND(YD%RLSM,1), LBOUND(YD%RLSM,2):UBOUND(YD%RLSM,2)))
  READ (KLUN) ZTMP2
  YD%RLSM = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_ECV_CONTAINER (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (ECV_CONTAINER), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRECV1D, LRGPECV2D, LRGPECV3D, LRLSM, LRSPECV2D, LRSPECV3D

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LRECV1D = ALLOCATED (YD%RECV1D)
IF (LRECV1D) THEN
  !$ACC ENTER DATA CREATE (YD%RECV1D)
  !$ACC UPDATE DEVICE (YD%RECV1D)
  !$ACC ENTER DATA ATTACH (YD%RECV1D)
ENDIF

LRSPECV2D = ALLOCATED (YD%RSPECV2D)
IF (LRSPECV2D) THEN
  !$ACC ENTER DATA CREATE (YD%RSPECV2D)
  !$ACC UPDATE DEVICE (YD%RSPECV2D)
  !$ACC ENTER DATA ATTACH (YD%RSPECV2D)
ENDIF

LRGPECV2D = ALLOCATED (YD%RGPECV2D)
IF (LRGPECV2D) THEN
  !$ACC ENTER DATA CREATE (YD%RGPECV2D)
  !$ACC UPDATE DEVICE (YD%RGPECV2D)
  !$ACC ENTER DATA ATTACH (YD%RGPECV2D)
ENDIF

LRSPECV3D = ALLOCATED (YD%RSPECV3D)
IF (LRSPECV3D) THEN
  !$ACC ENTER DATA CREATE (YD%RSPECV3D)
  !$ACC UPDATE DEVICE (YD%RSPECV3D)
  !$ACC ENTER DATA ATTACH (YD%RSPECV3D)
ENDIF

LRGPECV3D = ALLOCATED (YD%RGPECV3D)
IF (LRGPECV3D) THEN
  !$ACC ENTER DATA CREATE (YD%RGPECV3D)
  !$ACC UPDATE DEVICE (YD%RGPECV3D)
  !$ACC ENTER DATA ATTACH (YD%RGPECV3D)
ENDIF

LRLSM = ALLOCATED (YD%RLSM)
IF (LRLSM) THEN
  !$ACC ENTER DATA CREATE (YD%RLSM)
  !$ACC UPDATE DEVICE (YD%RLSM)
  !$ACC ENTER DATA ATTACH (YD%RLSM)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_ECV_CONTAINER (YD)

IMPLICIT NONE
TYPE (ECV_CONTAINER), TARGET :: YD
LOGICAL :: LRECV1D, LRGPECV2D, LRGPECV3D, LRLSM, LRSPECV2D, LRSPECV3D






END SUBROUTINE

     

SUBROUTINE CRC64_ECV_CONTAINER (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (ECV_CONTAINER), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LRECV1D, LRGPECV2D, LRGPECV3D, LRLSM, LRSPECV2D, LRSPECV3D
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RECV1D), CDPATH//'%RECV1D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RSPECV2D), CDPATH//'%RSPECV2D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RGPECV2D), CDPATH//'%RGPECV2D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RSPECV3D), CDPATH//'%RSPECV3D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RGPECV3D), CDPATH//'%RGPECV3D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RLSM), CDPATH//'%RLSM'

END SUBROUTINE

SUBROUTINE WIPE_ECV_CONTAINER (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (ECV_CONTAINER), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRECV1D, LRGPECV2D, LRGPECV3D, LRLSM, LRSPECV2D, LRSPECV3D

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LRECV1D = ALLOCATED (YD%RECV1D)
IF (LRECV1D) THEN
  !$ACC EXIT DATA DETACH (YD%RECV1D)
  !$ACC EXIT DATA DETACH (YD%RECV1D)
ENDIF

LRSPECV2D = ALLOCATED (YD%RSPECV2D)
IF (LRSPECV2D) THEN
  !$ACC EXIT DATA DETACH (YD%RSPECV2D)
  !$ACC EXIT DATA DETACH (YD%RSPECV2D)
ENDIF

LRGPECV2D = ALLOCATED (YD%RGPECV2D)
IF (LRGPECV2D) THEN
  !$ACC EXIT DATA DETACH (YD%RGPECV2D)
  !$ACC EXIT DATA DETACH (YD%RGPECV2D)
ENDIF

LRSPECV3D = ALLOCATED (YD%RSPECV3D)
IF (LRSPECV3D) THEN
  !$ACC EXIT DATA DETACH (YD%RSPECV3D)
  !$ACC EXIT DATA DETACH (YD%RSPECV3D)
ENDIF

LRGPECV3D = ALLOCATED (YD%RGPECV3D)
IF (LRGPECV3D) THEN
  !$ACC EXIT DATA DETACH (YD%RGPECV3D)
  !$ACC EXIT DATA DETACH (YD%RGPECV3D)
ENDIF

LRLSM = ALLOCATED (YD%RLSM)
IF (LRLSM) THEN
  !$ACC EXIT DATA DETACH (YD%RLSM)
  !$ACC EXIT DATA DETACH (YD%RLSM)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_ECV_CONTAINER (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (ECV_CONTAINER),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LRECV1D, LRGPECV2D, LRGPECV3D, LRLSM, LRSPECV2D, LRSPECV3D

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LRECV1D = ALLOCATED (YD%RECV1D)
IF (LRECV1D) THEN
  ISIZE = KIND (YD%RECV1D) * SIZE (YD%RECV1D)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RECV1D'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSPECV2D = ALLOCATED (YD%RSPECV2D)
IF (LRSPECV2D) THEN
  ISIZE = KIND (YD%RSPECV2D) * SIZE (YD%RSPECV2D)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSPECV2D'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRGPECV2D = ALLOCATED (YD%RGPECV2D)
IF (LRGPECV2D) THEN
  ISIZE = KIND (YD%RGPECV2D) * SIZE (YD%RGPECV2D)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RGPECV2D'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSPECV3D = ALLOCATED (YD%RSPECV3D)
IF (LRSPECV3D) THEN
  ISIZE = KIND (YD%RSPECV3D) * SIZE (YD%RSPECV3D)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSPECV3D'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRGPECV3D = ALLOCATED (YD%RGPECV3D)
IF (LRGPECV3D) THEN
  ISIZE = KIND (YD%RGPECV3D) * SIZE (YD%RGPECV3D)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RGPECV3D'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLSM = ALLOCATED (YD%RLSM)
IF (LRLSM) THEN
  ISIZE = KIND (YD%RLSM) * SIZE (YD%RLSM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLSM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
