MODULE UTIL_CPG_XYBDER_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_XYBDER_TYPE



INTERFACE COPY
MODULE PROCEDURE COPY_CPG_XYBDER_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_CPG_XYBDER_TYPE
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_XYBDER_TYPE
END INTERFACE



CONTAINS





SUBROUTINE COPY_CPG_XYBDER_TYPE (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (CPG_XYBDER_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_ALPHL, LF_ALPHM, LF_ALPHPLL, LF_ALPHPLM, LF_COEFA, LF_COEFAPL, LF_COEFD, LF_DATA, LF_LNPRL, LF_LNPRM
LOGICAL :: LZDATA, LZVIEW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF

LZVIEW = ASSOCIATED (YD%ZVIEW)
IF (LZVIEW) THEN
  !$ACC ENTER DATA CREATE (YD%ZVIEW)
  !$ACC UPDATE DEVICE (YD%ZVIEW)
  !$ACC ENTER DATA ATTACH (YD%ZVIEW)
ENDIF

LZDATA = ASSOCIATED (YD%ZDATA)
IF (LZDATA) THEN
  !$ACC ENTER DATA CREATE (YD%ZDATA)
  !$ACC UPDATE DEVICE (YD%ZDATA)
  !$ACC ENTER DATA ATTACH (YD%ZDATA)
ENDIF

LF_DATA = ASSOCIATED (YD%F_DATA)
IF (LF_DATA .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_4RB (YD%F_DATA)
  !$ACC ENTER DATA ATTACH (YD%F_DATA)
ENDIF


LF_LNPRL = ASSOCIATED (YD%F_LNPRL)
IF (LF_LNPRL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_LNPRL)
  !$ACC ENTER DATA ATTACH (YD%F_LNPRL)
ENDIF


LF_LNPRM = ASSOCIATED (YD%F_LNPRM)
IF (LF_LNPRM .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_LNPRM)
  !$ACC ENTER DATA ATTACH (YD%F_LNPRM)
ENDIF


LF_ALPHL = ASSOCIATED (YD%F_ALPHL)
IF (LF_ALPHL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_ALPHL)
  !$ACC ENTER DATA ATTACH (YD%F_ALPHL)
ENDIF


LF_ALPHM = ASSOCIATED (YD%F_ALPHM)
IF (LF_ALPHM .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_ALPHM)
  !$ACC ENTER DATA ATTACH (YD%F_ALPHM)
ENDIF


LF_ALPHPLL = ASSOCIATED (YD%F_ALPHPLL)
IF (LF_ALPHPLL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_ALPHPLL)
  !$ACC ENTER DATA ATTACH (YD%F_ALPHPLL)
ENDIF


LF_ALPHPLM = ASSOCIATED (YD%F_ALPHPLM)
IF (LF_ALPHPLM .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_ALPHPLM)
  !$ACC ENTER DATA ATTACH (YD%F_ALPHPLM)
ENDIF


LF_COEFD = ASSOCIATED (YD%F_COEFD)
IF (LF_COEFD .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_COEFD)
  !$ACC ENTER DATA ATTACH (YD%F_COEFD)
ENDIF


LF_COEFA = ASSOCIATED (YD%F_COEFA)
IF (LF_COEFA .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_COEFA)
  !$ACC ENTER DATA ATTACH (YD%F_COEFA)
ENDIF


LF_COEFAPL = ASSOCIATED (YD%F_COEFAPL)
IF (LF_COEFAPL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_COEFAPL)
  !$ACC ENTER DATA ATTACH (YD%F_COEFAPL)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_CPG_XYBDER_TYPE (YD)
USE FIELD_UTIL_MODULE

IMPLICIT NONE
TYPE (CPG_XYBDER_TYPE), TARGET :: YD
LOGICAL :: LF_ALPHL, LF_ALPHM, LF_ALPHPLL, LF_ALPHPLM, LF_COEFA, LF_COEFAPL, LF_COEFD, LF_DATA, LF_LNPRL, LF_LNPRM
LOGICAL :: LZDATA, LZVIEW



LF_DATA = ASSOCIATED (YD%F_DATA)
IF (LF_DATA) THEN
  CALL HOST_FIELD_4RB (YD%F_DATA)
ENDIF


LF_LNPRL = ASSOCIATED (YD%F_LNPRL)
IF (LF_LNPRL) THEN
  CALL HOST_FIELD_3RB (YD%F_LNPRL)
ENDIF


LF_LNPRM = ASSOCIATED (YD%F_LNPRM)
IF (LF_LNPRM) THEN
  CALL HOST_FIELD_3RB (YD%F_LNPRM)
ENDIF


LF_ALPHL = ASSOCIATED (YD%F_ALPHL)
IF (LF_ALPHL) THEN
  CALL HOST_FIELD_3RB (YD%F_ALPHL)
ENDIF


LF_ALPHM = ASSOCIATED (YD%F_ALPHM)
IF (LF_ALPHM) THEN
  CALL HOST_FIELD_3RB (YD%F_ALPHM)
ENDIF


LF_ALPHPLL = ASSOCIATED (YD%F_ALPHPLL)
IF (LF_ALPHPLL) THEN
  CALL HOST_FIELD_3RB (YD%F_ALPHPLL)
ENDIF


LF_ALPHPLM = ASSOCIATED (YD%F_ALPHPLM)
IF (LF_ALPHPLM) THEN
  CALL HOST_FIELD_3RB (YD%F_ALPHPLM)
ENDIF


LF_COEFD = ASSOCIATED (YD%F_COEFD)
IF (LF_COEFD) THEN
  CALL HOST_FIELD_3RB (YD%F_COEFD)
ENDIF


LF_COEFA = ASSOCIATED (YD%F_COEFA)
IF (LF_COEFA) THEN
  CALL HOST_FIELD_3RB (YD%F_COEFA)
ENDIF


LF_COEFAPL = ASSOCIATED (YD%F_COEFAPL)
IF (LF_COEFAPL) THEN
  CALL HOST_FIELD_3RB (YD%F_COEFAPL)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_CPG_XYBDER_TYPE (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (CPG_XYBDER_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_ALPHL, LF_ALPHM, LF_ALPHPLL, LF_ALPHPLM, LF_COEFA, LF_COEFAPL, LF_COEFD, LF_DATA, LF_LNPRL, LF_LNPRM
LOGICAL :: LZDATA, LZVIEW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LZVIEW = ASSOCIATED (YD%ZVIEW)
IF (LZVIEW) THEN
  !$ACC EXIT DATA DETACH (YD%ZVIEW)
  !$ACC EXIT DATA DETACH (YD%ZVIEW)
ENDIF

LZDATA = ASSOCIATED (YD%ZDATA)
IF (LZDATA) THEN
  !$ACC EXIT DATA DETACH (YD%ZDATA)
  !$ACC EXIT DATA DETACH (YD%ZDATA)
ENDIF

LF_DATA = ASSOCIATED (YD%F_DATA)
IF (LF_DATA .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (YD%F_DATA)
ENDIF


LF_LNPRL = ASSOCIATED (YD%F_LNPRL)
IF (LF_LNPRL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_LNPRL)
ENDIF


LF_LNPRM = ASSOCIATED (YD%F_LNPRM)
IF (LF_LNPRM .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_LNPRM)
ENDIF


LF_ALPHL = ASSOCIATED (YD%F_ALPHL)
IF (LF_ALPHL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_ALPHL)
ENDIF


LF_ALPHM = ASSOCIATED (YD%F_ALPHM)
IF (LF_ALPHM .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_ALPHM)
ENDIF


LF_ALPHPLL = ASSOCIATED (YD%F_ALPHPLL)
IF (LF_ALPHPLL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_ALPHPLL)
ENDIF


LF_ALPHPLM = ASSOCIATED (YD%F_ALPHPLM)
IF (LF_ALPHPLM .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_ALPHPLM)
ENDIF


LF_COEFD = ASSOCIATED (YD%F_COEFD)
IF (LF_COEFD .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_COEFD)
ENDIF


LF_COEFA = ASSOCIATED (YD%F_COEFA)
IF (LF_COEFA .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_COEFA)
ENDIF


LF_COEFAPL = ASSOCIATED (YD%F_COEFAPL)
IF (LF_COEFAPL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_COEFAPL)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
