MODULE UTIL_CPG_SURF_CLP_OPTS_TYPE_MOD

USE CPG_OPTS_TYPE_MOD, ONLY : CPG_SURF_CLP_OPTS_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_SURF_CLP_OPTS_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_SURF_CLP_OPTS_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_CPG_SURF_CLP_OPTS_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_CPG_SURF_CLP_OPTS_TYPE
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_CPG_SURF_CLP_OPTS_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_SURF_CLP_OPTS_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_CPG_SURF_CLP_OPTS_TYPE (KLUN, YD)
USE UTIL_CPG_SURF_CL_HUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NVCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_TCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_UCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_VCLSP_OPTS_TYPE_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_SURF_CLP_OPTS_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE_CPG_SURF_CL_TCLSP_OPTS_TYPE (KLUN, YD%YTCLS)
CALL SAVE_CPG_SURF_CL_HUCLSP_OPTS_TYPE (KLUN, YD%YHUCLS)
CALL SAVE_CPG_SURF_CL_UCLSP_OPTS_TYPE (KLUN, YD%YUCLS)
CALL SAVE_CPG_SURF_CL_VCLSP_OPTS_TYPE (KLUN, YD%YVCLS)
CALL SAVE_CPG_SURF_CL_NUCLSP_OPTS_TYPE (KLUN, YD%YNUCLS)
CALL SAVE_CPG_SURF_CL_NVCLSP_OPTS_TYPE (KLUN, YD%YNVCLS)
END SUBROUTINE

SUBROUTINE LOAD_CPG_SURF_CLP_OPTS_TYPE (KLUN, YD)
USE UTIL_CPG_SURF_CL_HUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NVCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_TCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_UCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_VCLSP_OPTS_TYPE_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (CPG_SURF_CLP_OPTS_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD_CPG_SURF_CL_TCLSP_OPTS_TYPE (KLUN, YD%YTCLS)
CALL LOAD_CPG_SURF_CL_HUCLSP_OPTS_TYPE (KLUN, YD%YHUCLS)
CALL LOAD_CPG_SURF_CL_UCLSP_OPTS_TYPE (KLUN, YD%YUCLS)
CALL LOAD_CPG_SURF_CL_VCLSP_OPTS_TYPE (KLUN, YD%YVCLS)
CALL LOAD_CPG_SURF_CL_NUCLSP_OPTS_TYPE (KLUN, YD%YNUCLS)
CALL LOAD_CPG_SURF_CL_NVCLSP_OPTS_TYPE (KLUN, YD%YNVCLS)
END SUBROUTINE


SUBROUTINE COPY_CPG_SURF_CLP_OPTS_TYPE (YD, LDCREATED, LDFIELDAPI)
USE UTIL_CPG_SURF_CL_HUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NVCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_TCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_UCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_VCLSP_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_CLP_OPTS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
CALL COPY_CPG_SURF_CL_TCLSP_OPTS_TYPE (YD%YTCLS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_CL_HUCLSP_OPTS_TYPE (YD%YHUCLS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_CL_UCLSP_OPTS_TYPE (YD%YUCLS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_CL_VCLSP_OPTS_TYPE (YD%YVCLS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_CL_NUCLSP_OPTS_TYPE (YD%YNUCLS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_CL_NVCLSP_OPTS_TYPE (YD%YNVCLS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

SUBROUTINE HOST_CPG_SURF_CLP_OPTS_TYPE (YD)
USE UTIL_CPG_SURF_CL_HUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NVCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_TCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_UCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_VCLSP_OPTS_TYPE_MOD

IMPLICIT NONE
TYPE (CPG_SURF_CLP_OPTS_TYPE), TARGET :: YD

CALL HOST_CPG_SURF_CL_TCLSP_OPTS_TYPE (YD%YTCLS)

CALL HOST_CPG_SURF_CL_HUCLSP_OPTS_TYPE (YD%YHUCLS)

CALL HOST_CPG_SURF_CL_UCLSP_OPTS_TYPE (YD%YUCLS)

CALL HOST_CPG_SURF_CL_VCLSP_OPTS_TYPE (YD%YVCLS)

CALL HOST_CPG_SURF_CL_NUCLSP_OPTS_TYPE (YD%YNUCLS)

CALL HOST_CPG_SURF_CL_NVCLSP_OPTS_TYPE (YD%YNVCLS)

END SUBROUTINE

     

SUBROUTINE CRC64_CPG_SURF_CLP_OPTS_TYPE (YD, KLUN, CDPATH)
USE UTIL_CPG_SURF_CL_HUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NVCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_TCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_UCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_VCLSP_OPTS_TYPE_MOD
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (CPG_SURF_CLP_OPTS_TYPE), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

CLIND = ''
CALL CRC64_CPG_SURF_CL_TCLSP_OPTS_TYPE (YD%YTCLS, KLUN, CDPATH//'%YTCLS'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_CL_HUCLSP_OPTS_TYPE (YD%YHUCLS, KLUN, CDPATH//'%YHUCLS'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_CL_UCLSP_OPTS_TYPE (YD%YUCLS, KLUN, CDPATH//'%YUCLS'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_CL_VCLSP_OPTS_TYPE (YD%YVCLS, KLUN, CDPATH//'%YVCLS'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_CL_NUCLSP_OPTS_TYPE (YD%YNUCLS, KLUN, CDPATH//'%YNUCLS'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_CL_NVCLSP_OPTS_TYPE (YD%YNVCLS, KLUN, CDPATH//'%YNVCLS'//TRIM(CLIND))

END SUBROUTINE

SUBROUTINE WIPE_CPG_SURF_CLP_OPTS_TYPE (YD, LDDELETED, LDFIELDAPI)
USE UTIL_CPG_SURF_CL_HUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NUCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_NVCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_TCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_UCLSP_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_CL_VCLSP_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_CLP_OPTS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL WIPE_CPG_SURF_CL_TCLSP_OPTS_TYPE (YD%YTCLS, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_CL_HUCLSP_OPTS_TYPE (YD%YHUCLS, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_CL_UCLSP_OPTS_TYPE (YD%YUCLS, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_CL_VCLSP_OPTS_TYPE (YD%YVCLS, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_CL_NUCLSP_OPTS_TYPE (YD%YNUCLS, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_CL_NVCLSP_OPTS_TYPE (YD%YNVCLS, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
