MODULE UTIL_TPHY_MOD

USE YOMPHY, ONLY : TPHY

INTERFACE SAVE
MODULE PROCEDURE SAVE_TPHY
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHY
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TPHY
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TPHY
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TPHY
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TPHY
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TPHY
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TPHY (KLUN, YD)
USE UTIL_TCAPE_MOD
USE UTIL_TDPRECIPS_MOD
USE UTIL_TDVISI_MOD
USE UTIL_TDWET_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NBITER
WRITE (KLUN) YD%NITERFL
WRITE (KLUN) YD%NDPSFI
WRITE (KLUN) YD%LMPHYS
WRITE (KLUN) YD%LREASUR
WRITE (KLUN) YD%LCAPE
WRITE (KLUN) YD%LCVGQD
WRITE (KLUN) YD%LCVGQM
WRITE (KLUN) YD%LCVGQP
WRITE (KLUN) YD%LCONDWT
WRITE (KLUN) YD%LCVDD
WRITE (KLUN) YD%LCVPGY
WRITE (KLUN) YD%LCVPP
WRITE (KLUN) YD%LDIFCEXP
WRITE (KLUN) YD%LDIFCONS
WRITE (KLUN) YD%LDIFQL
WRITE (KLUN) YD%LDISTUR
WRITE (KLUN) YD%LNEIGE
WRITE (KLUN) YD%LRNUMX
WRITE (KLUN) YD%LRNUEXP
WRITE (KLUN) YD%LRTRUEBBC
WRITE (KLUN) YD%LRTRUEDIR
WRITE (KLUN) YD%LACPANMX
WRITE (KLUN) YD%LCLSATUR
WRITE (KLUN) YD%LVOIGT
WRITE (KLUN) YD%LGLACIERS
WRITE (KLUN) YD%LVFULL
WRITE (KLUN) YD%LSLC
WRITE (KLUN) YD%LRAYLU
WRITE (KLUN) YD%LREWS
WRITE (KLUN) YD%LRPROX
WRITE (KLUN) YD%LRMIX
WRITE (KLUN) YD%LRSTAB
WRITE (KLUN) YD%LRSTAER
WRITE (KLUN) YD%LRTPP
WRITE (KLUN) YD%LRTDL
WRITE (KLUN) YD%LRAYPL
WRITE (KLUN) YD%LRRGUST
WRITE (KLUN) YD%LO3ABC
WRITE (KLUN) YD%LO3FL
WRITE (KLUN) YD%LECSHAL
WRITE (KLUN) YD%LECDEEP
WRITE (KLUN) YD%LNEBNXR
WRITE (KLUN) YD%LNEB_FP
WRITE (KLUN) YD%LQXRTGH
WRITE (KLUN) YD%LHUCN
WRITE (KLUN) YD%LFPCOR
WRITE (KLUN) YD%LNOIAS
WRITE (KLUN) YD%LGLT
WRITE (KLUN) YD%LNEWD
WRITE (KLUN) YD%LPROCLD
WRITE (KLUN) YD%LEVAPP
WRITE (KLUN) YD%LCOLLEC
WRITE (KLUN) YD%LADJCLD
WRITE (KLUN) YD%LSEDSTA
WRITE (KLUN) YD%LSEDLAG
WRITE (KLUN) YD%LSEDCL
WRITE (KLUN) YD%LFSVAR
WRITE (KLUN) YD%LFSFIX
WRITE (KLUN) YD%LA0MPS
WRITE (KLUN) YD%LARPMPS
WRITE (KLUN) YD%L3MT
WRITE (KLUN) YD%LGPCMT
WRITE (KLUN) YD%LENTCH
WRITE (KLUN) YD%LCDDEVPRO
WRITE (KLUN) YD%LAEROSEA
WRITE (KLUN) YD%LAEROLAN
WRITE (KLUN) YD%LAEROSOO
WRITE (KLUN) YD%LAERODES
WRITE (KLUN) YD%LAEROVOL
WRITE (KLUN) YD%LAEROSUL
WRITE (KLUN) YD%LAEROMMR
WRITE (KLUN) YD%LAERONRT
WRITE (KLUN) YD%LRELAXT
WRITE (KLUN) YD%LRELAXW
WRITE (KLUN) YD%LSSD
WRITE (KLUN) YD%LPBLE
WRITE (KLUN) YD%LBLVAR
WRITE (KLUN) YD%LZ0HSREL
WRITE (KLUN) YD%LZ0SNOWH
WRITE (KLUN) YD%LMLH
WRITE (KLUN) YD%LNODIFQC
WRITE (KLUN) YD%LNCVPGY
WRITE (KLUN) YD%LSQRML
WRITE (KLUN) YD%LAB12
WRITE (KLUN) YD%LFVGICE3
WRITE (KLUN) YD%LEVAPLOP
WRITE (KLUN) YD%LCP06
WRITE (KLUN) YD%LCVSHCU
WRITE (KLUN) YD%LCVGQ
WRITE (KLUN) YD%LPEC
WRITE (KLUN) YD%LUDEVOL
WRITE (KLUN) YD%LCDDCSD
WRITE (KLUN) YD%NCLOMIX
WRITE (KLUN) YD%NFSIG
WRITE (KLUN) YD%LHLRADUPD
WRITE (KLUN) YD%NDPRECPERIOD
WRITE (KLUN) YD%NDPRECPERIOD2
WRITE (KLUN) YD%LDPRECIPS
WRITE (KLUN) YD%LDPRECIPS2
CALL SAVE_TDPRECIPS (KLUN, YD%YRDPRECIPS)
CALL SAVE_TDVISI (KLUN, YD%YRDVISI)
CALL SAVE_TDWET (KLUN, YD%YRDWET)
WRITE (KLUN) YD%CGMIXLEN
WRITE (KLUN) YD%CGTURS
WRITE (KLUN) YD%CGTRG
WRITE (KLUN) YD%LPRGML
WRITE (KLUN) YD%LCVRA
WRITE (KLUN) YD%LCVTDK
WRITE (KLUN) YD%LDAYD
WRITE (KLUN) YD%LCVPRO
WRITE (KLUN) YD%LGRAPRO
WRITE (KLUN) YD%LCDDPRO
WRITE (KLUN) YD%LCVCSD
WRITE (KLUN) YD%LUSL
WRITE (KLUN) YD%LNSDO
WRITE (KLUN) YD%LECT
WRITE (KLUN) YD%LEFB
WRITE (KLUN) YD%LFLUSO
WRITE (KLUN) YD%LECTQ1
WRITE (KLUN) YD%LECTREP
WRITE (KLUN) YD%LPTKE
WRITE (KLUN) YD%LCOEFKTKE
WRITE (KLUN) YD%LCOEFKSURF
WRITE (KLUN) YD%LCOEFK_MSC
WRITE (KLUN) YD%LCOEFK_F1
WRITE (KLUN) YD%LCOEFK_TOMS
WRITE (KLUN) YD%LCOEFK_THS1
WRITE (KLUN) YD%LCOEFK_RIS
WRITE (KLUN) YD%LCOEFK_PL
WRITE (KLUN) YD%LCOEFK_ML
WRITE (KLUN) YD%LCOEFK_PTTE
WRITE (KLUN) YD%LCOEFK_FLX
WRITE (KLUN) YD%LCOEFK_SCQ
WRITE (KLUN) YD%LAFGD_A
WRITE (KLUN) YD%LGWD
WRITE (KLUN) YD%LGWDC
WRITE (KLUN) YD%LNORGWD
WRITE (KLUN) YD%LHMTO
WRITE (KLUN) YD%LNEBCO
WRITE (KLUN) YD%LNEBN
WRITE (KLUN) YD%LNEBR
WRITE (KLUN) YD%LPTOPC
WRITE (KLUN) YD%LOZONE
WRITE (KLUN) YD%LRAY
WRITE (KLUN) YD%LRAYFM
WRITE (KLUN) YD%LRMU0M
WRITE (KLUN) YD%LRAYFM15
WRITE (KLUN) YD%LRRMES
WRITE (KLUN) YD%LSFHYD
WRITE (KLUN) YD%LSNV
WRITE (KLUN) YD%LSOLV
WRITE (KLUN) YD%LFGEL
WRITE (KLUN) YD%LSTRA
WRITE (KLUN) YD%LSTRAS
WRITE (KLUN) YD%LSTRAPRO
WRITE (KLUN) YD%LNEWSTAT
WRITE (KLUN) YD%LTHERMO
WRITE (KLUN) YD%LVDIF
WRITE (KLUN) YD%LCVLIS
WRITE (KLUN) YD%LCVCAS
WRITE (KLUN) YD%LSCMF
WRITE (KLUN) YD%LVGSN
WRITE (KLUN) YD%LPHCDPI
WRITE (KLUN) YD%LNEBGR
WRITE (KLUN) YD%LNEBGY
WRITE (KLUN) YD%LCVRAV3
WRITE (KLUN) YD%LCVPPKF
WRITE (KLUN) YD%LCVTURB
WRITE (KLUN) YD%LNEBRIC
WRITE (KLUN) YD%LEDKF
WRITE (KLUN) YD%LEDMFI
WRITE (KLUN) YD%LEDMFS
WRITE (KLUN) YD%LECTFL
WRITE (KLUN) YD%LECTFL0
WRITE (KLUN) YD%LECTPRODCVP
WRITE (KLUN) YD%NPHYREP
WRITE (KLUN) YD%LCAMOD
WRITE (KLUN) YD%LCOMOD
WRITE (KLUN) YD%LPHSPSH
WRITE (KLUN) YD%LSMNIMBT
WRITE (KLUN) YD%LSMTPS
WRITE (KLUN) YD%LSMGCDEV
WRITE (KLUN) YD%LXRCDEV
WRITE (KLUN) YD%LRKCDEV
WRITE (KLUN) YD%LSMITH_CDEV
WRITE (KLUN) YD%LRCVOTT
WRITE (KLUN) YD%LNEBCV
WRITE (KLUN) YD%LNEBINS
WRITE (KLUN) YD%NDIFFNEB
WRITE (KLUN) YD%NIMELIT
WRITE (KLUN) YD%NRAY
WRITE (KLUN) YD%NSORAYFR
WRITE (KLUN) YD%NTHRAYFR
WRITE (KLUN) YD%NRAUTOEV
WRITE (KLUN) YD%NSMTBOT
WRITE (KLUN) YD%NSMDNEB
WRITE (KLUN) YD%NPRAC
WRITE (KLUN) YD%NPRRI
WRITE (KLUN) YD%NPHY
WRITE (KLUN) YD%NCALLRAD
WRITE (KLUN) YD%NLEND
WRITE (KLUN) YD%NTEND_DIAG_POS
WRITE (KLUN) YD%NTEND_DIAG_FREQ_RESET
WRITE (KLUN) YD%LNEBECT
WRITE (KLUN) YD%LCVGQKF
WRITE (KLUN) YD%LACDIFUS
WRITE (KLUN) YD%L2MICRO
WRITE (KLUN) YD%NSOLE
WRITE (KLUN) YD%LAJUCV
WRITE (KLUN) YD%LSMOOTHMELT
WRITE (KLUN) YD%LGCHECKMV
WRITE (KLUN) YD%LGCHECKNAN
WRITE (KLUN) YD%LEDR
WRITE (KLUN) YD%LWINDFARM
WRITE (KLUN) YD%LVOLKER
WRITE (KLUN) YD%NWINDFARMMODORO
WRITE (KLUN) YD%LAPL_ARPEGE
CALL SAVE_TCAPE (KLUN, YD%YRCAPE)
END SUBROUTINE

SUBROUTINE LOAD_TPHY (KLUN, YD)
USE UTIL_TCAPE_MOD
USE UTIL_TDPRECIPS_MOD
USE UTIL_TDVISI_MOD
USE UTIL_TDWET_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%NBITER
READ (KLUN) YD%NITERFL
READ (KLUN) YD%NDPSFI
READ (KLUN) YD%LMPHYS
READ (KLUN) YD%LREASUR
READ (KLUN) YD%LCAPE
READ (KLUN) YD%LCVGQD
READ (KLUN) YD%LCVGQM
READ (KLUN) YD%LCVGQP
READ (KLUN) YD%LCONDWT
READ (KLUN) YD%LCVDD
READ (KLUN) YD%LCVPGY
READ (KLUN) YD%LCVPP
READ (KLUN) YD%LDIFCEXP
READ (KLUN) YD%LDIFCONS
READ (KLUN) YD%LDIFQL
READ (KLUN) YD%LDISTUR
READ (KLUN) YD%LNEIGE
READ (KLUN) YD%LRNUMX
READ (KLUN) YD%LRNUEXP
READ (KLUN) YD%LRTRUEBBC
READ (KLUN) YD%LRTRUEDIR
READ (KLUN) YD%LACPANMX
READ (KLUN) YD%LCLSATUR
READ (KLUN) YD%LVOIGT
READ (KLUN) YD%LGLACIERS
READ (KLUN) YD%LVFULL
READ (KLUN) YD%LSLC
READ (KLUN) YD%LRAYLU
READ (KLUN) YD%LREWS
READ (KLUN) YD%LRPROX
READ (KLUN) YD%LRMIX
READ (KLUN) YD%LRSTAB
READ (KLUN) YD%LRSTAER
READ (KLUN) YD%LRTPP
READ (KLUN) YD%LRTDL
READ (KLUN) YD%LRAYPL
READ (KLUN) YD%LRRGUST
READ (KLUN) YD%LO3ABC
READ (KLUN) YD%LO3FL
READ (KLUN) YD%LECSHAL
READ (KLUN) YD%LECDEEP
READ (KLUN) YD%LNEBNXR
READ (KLUN) YD%LNEB_FP
READ (KLUN) YD%LQXRTGH
READ (KLUN) YD%LHUCN
READ (KLUN) YD%LFPCOR
READ (KLUN) YD%LNOIAS
READ (KLUN) YD%LGLT
READ (KLUN) YD%LNEWD
READ (KLUN) YD%LPROCLD
READ (KLUN) YD%LEVAPP
READ (KLUN) YD%LCOLLEC
READ (KLUN) YD%LADJCLD
READ (KLUN) YD%LSEDSTA
READ (KLUN) YD%LSEDLAG
READ (KLUN) YD%LSEDCL
READ (KLUN) YD%LFSVAR
READ (KLUN) YD%LFSFIX
READ (KLUN) YD%LA0MPS
READ (KLUN) YD%LARPMPS
READ (KLUN) YD%L3MT
READ (KLUN) YD%LGPCMT
READ (KLUN) YD%LENTCH
READ (KLUN) YD%LCDDEVPRO
READ (KLUN) YD%LAEROSEA
READ (KLUN) YD%LAEROLAN
READ (KLUN) YD%LAEROSOO
READ (KLUN) YD%LAERODES
READ (KLUN) YD%LAEROVOL
READ (KLUN) YD%LAEROSUL
READ (KLUN) YD%LAEROMMR
READ (KLUN) YD%LAERONRT
READ (KLUN) YD%LRELAXT
READ (KLUN) YD%LRELAXW
READ (KLUN) YD%LSSD
READ (KLUN) YD%LPBLE
READ (KLUN) YD%LBLVAR
READ (KLUN) YD%LZ0HSREL
READ (KLUN) YD%LZ0SNOWH
READ (KLUN) YD%LMLH
READ (KLUN) YD%LNODIFQC
READ (KLUN) YD%LNCVPGY
READ (KLUN) YD%LSQRML
READ (KLUN) YD%LAB12
READ (KLUN) YD%LFVGICE3
READ (KLUN) YD%LEVAPLOP
READ (KLUN) YD%LCP06
READ (KLUN) YD%LCVSHCU
READ (KLUN) YD%LCVGQ
READ (KLUN) YD%LPEC
READ (KLUN) YD%LUDEVOL
READ (KLUN) YD%LCDDCSD
READ (KLUN) YD%NCLOMIX
READ (KLUN) YD%NFSIG
READ (KLUN) YD%LHLRADUPD
READ (KLUN) YD%NDPRECPERIOD
READ (KLUN) YD%NDPRECPERIOD2
READ (KLUN) YD%LDPRECIPS
READ (KLUN) YD%LDPRECIPS2
CALL LOAD_TDPRECIPS (KLUN, YD%YRDPRECIPS)
CALL LOAD_TDVISI (KLUN, YD%YRDVISI)
CALL LOAD_TDWET (KLUN, YD%YRDWET)
READ (KLUN) YD%CGMIXLEN
READ (KLUN) YD%CGTURS
READ (KLUN) YD%CGTRG
READ (KLUN) YD%LPRGML
READ (KLUN) YD%LCVRA
READ (KLUN) YD%LCVTDK
READ (KLUN) YD%LDAYD
READ (KLUN) YD%LCVPRO
READ (KLUN) YD%LGRAPRO
READ (KLUN) YD%LCDDPRO
READ (KLUN) YD%LCVCSD
READ (KLUN) YD%LUSL
READ (KLUN) YD%LNSDO
READ (KLUN) YD%LECT
READ (KLUN) YD%LEFB
READ (KLUN) YD%LFLUSO
READ (KLUN) YD%LECTQ1
READ (KLUN) YD%LECTREP
READ (KLUN) YD%LPTKE
READ (KLUN) YD%LCOEFKTKE
READ (KLUN) YD%LCOEFKSURF
READ (KLUN) YD%LCOEFK_MSC
READ (KLUN) YD%LCOEFK_F1
READ (KLUN) YD%LCOEFK_TOMS
READ (KLUN) YD%LCOEFK_THS1
READ (KLUN) YD%LCOEFK_RIS
READ (KLUN) YD%LCOEFK_PL
READ (KLUN) YD%LCOEFK_ML
READ (KLUN) YD%LCOEFK_PTTE
READ (KLUN) YD%LCOEFK_FLX
READ (KLUN) YD%LCOEFK_SCQ
READ (KLUN) YD%LAFGD_A
READ (KLUN) YD%LGWD
READ (KLUN) YD%LGWDC
READ (KLUN) YD%LNORGWD
READ (KLUN) YD%LHMTO
READ (KLUN) YD%LNEBCO
READ (KLUN) YD%LNEBN
READ (KLUN) YD%LNEBR
READ (KLUN) YD%LPTOPC
READ (KLUN) YD%LOZONE
READ (KLUN) YD%LRAY
READ (KLUN) YD%LRAYFM
READ (KLUN) YD%LRMU0M
READ (KLUN) YD%LRAYFM15
READ (KLUN) YD%LRRMES
READ (KLUN) YD%LSFHYD
READ (KLUN) YD%LSNV
READ (KLUN) YD%LSOLV
READ (KLUN) YD%LFGEL
READ (KLUN) YD%LSTRA
READ (KLUN) YD%LSTRAS
READ (KLUN) YD%LSTRAPRO
READ (KLUN) YD%LNEWSTAT
READ (KLUN) YD%LTHERMO
READ (KLUN) YD%LVDIF
READ (KLUN) YD%LCVLIS
READ (KLUN) YD%LCVCAS
READ (KLUN) YD%LSCMF
READ (KLUN) YD%LVGSN
READ (KLUN) YD%LPHCDPI
READ (KLUN) YD%LNEBGR
READ (KLUN) YD%LNEBGY
READ (KLUN) YD%LCVRAV3
READ (KLUN) YD%LCVPPKF
READ (KLUN) YD%LCVTURB
READ (KLUN) YD%LNEBRIC
READ (KLUN) YD%LEDKF
READ (KLUN) YD%LEDMFI
READ (KLUN) YD%LEDMFS
READ (KLUN) YD%LECTFL
READ (KLUN) YD%LECTFL0
READ (KLUN) YD%LECTPRODCVP
READ (KLUN) YD%NPHYREP
READ (KLUN) YD%LCAMOD
READ (KLUN) YD%LCOMOD
READ (KLUN) YD%LPHSPSH
READ (KLUN) YD%LSMNIMBT
READ (KLUN) YD%LSMTPS
READ (KLUN) YD%LSMGCDEV
READ (KLUN) YD%LXRCDEV
READ (KLUN) YD%LRKCDEV
READ (KLUN) YD%LSMITH_CDEV
READ (KLUN) YD%LRCVOTT
READ (KLUN) YD%LNEBCV
READ (KLUN) YD%LNEBINS
READ (KLUN) YD%NDIFFNEB
READ (KLUN) YD%NIMELIT
READ (KLUN) YD%NRAY
READ (KLUN) YD%NSORAYFR
READ (KLUN) YD%NTHRAYFR
READ (KLUN) YD%NRAUTOEV
READ (KLUN) YD%NSMTBOT
READ (KLUN) YD%NSMDNEB
READ (KLUN) YD%NPRAC
READ (KLUN) YD%NPRRI
READ (KLUN) YD%NPHY
READ (KLUN) YD%NCALLRAD
READ (KLUN) YD%NLEND
READ (KLUN) YD%NTEND_DIAG_POS
READ (KLUN) YD%NTEND_DIAG_FREQ_RESET
READ (KLUN) YD%LNEBECT
READ (KLUN) YD%LCVGQKF
READ (KLUN) YD%LACDIFUS
READ (KLUN) YD%L2MICRO
READ (KLUN) YD%NSOLE
READ (KLUN) YD%LAJUCV
READ (KLUN) YD%LSMOOTHMELT
READ (KLUN) YD%LGCHECKMV
READ (KLUN) YD%LGCHECKNAN
READ (KLUN) YD%LEDR
READ (KLUN) YD%LWINDFARM
READ (KLUN) YD%LVOLKER
READ (KLUN) YD%NWINDFARMMODORO
READ (KLUN) YD%LAPL_ARPEGE
CALL LOAD_TCAPE (KLUN, YD%YRCAPE)
END SUBROUTINE


SUBROUTINE COPY_TPHY (YD, LDCREATED, LDFIELDAPI)
USE UTIL_TCAPE_MOD
USE UTIL_TDPRECIPS_MOD
USE UTIL_TDVISI_MOD
USE UTIL_TDWET_MOD
IMPLICIT NONE
TYPE (TPHY), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF




































































































CALL COPY_TDPRECIPS (YD%YRDPRECIPS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TDVISI (YD%YRDVISI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TDWET (YD%YRDWET, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)




















































































































CALL COPY_TCAPE (YD%YRCAPE, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

SUBROUTINE HOST_TPHY (YD)
USE UTIL_TCAPE_MOD
USE UTIL_TDPRECIPS_MOD
USE UTIL_TDVISI_MOD
USE UTIL_TDWET_MOD

IMPLICIT NONE
TYPE (TPHY), TARGET :: YD





































































































CALL HOST_TDPRECIPS (YD%YRDPRECIPS)

CALL HOST_TDVISI (YD%YRDVISI)

CALL HOST_TDWET (YD%YRDWET)




















































































































CALL HOST_TCAPE (YD%YRCAPE)

END SUBROUTINE

     

SUBROUTINE CRC64_TPHY (YD, KLUN, CDPATH)
USE UTIL_TCAPE_MOD
USE UTIL_TDPRECIPS_MOD
USE UTIL_TDVISI_MOD
USE UTIL_TDWET_MOD
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TPHY), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NBITER), CDPATH//'%NBITER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NITERFL), CDPATH//'%NITERFL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDPSFI), CDPATH//'%NDPSFI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LMPHYS), CDPATH//'%LMPHYS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LREASUR), CDPATH//'%LREASUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCAPE), CDPATH//'%LCAPE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVGQD), CDPATH//'%LCVGQD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVGQM), CDPATH//'%LCVGQM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVGQP), CDPATH//'%LCVGQP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCONDWT), CDPATH//'%LCONDWT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVDD), CDPATH//'%LCVDD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVPGY), CDPATH//'%LCVPGY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVPP), CDPATH//'%LCVPP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LDIFCEXP), CDPATH//'%LDIFCEXP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LDIFCONS), CDPATH//'%LDIFCONS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LDIFQL), CDPATH//'%LDIFQL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LDISTUR), CDPATH//'%LDISTUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEIGE), CDPATH//'%LNEIGE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRNUMX), CDPATH//'%LRNUMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRNUEXP), CDPATH//'%LRNUEXP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRTRUEBBC), CDPATH//'%LRTRUEBBC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRTRUEDIR), CDPATH//'%LRTRUEDIR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LACPANMX), CDPATH//'%LACPANMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCLSATUR), CDPATH//'%LCLSATUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LVOIGT), CDPATH//'%LVOIGT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LGLACIERS), CDPATH//'%LGLACIERS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LVFULL), CDPATH//'%LVFULL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSLC), CDPATH//'%LSLC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRAYLU), CDPATH//'%LRAYLU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LREWS), CDPATH//'%LREWS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRPROX), CDPATH//'%LRPROX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRMIX), CDPATH//'%LRMIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRSTAB), CDPATH//'%LRSTAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRSTAER), CDPATH//'%LRSTAER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRTPP), CDPATH//'%LRTPP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRTDL), CDPATH//'%LRTDL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRAYPL), CDPATH//'%LRAYPL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRRGUST), CDPATH//'%LRRGUST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LO3ABC), CDPATH//'%LO3ABC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LO3FL), CDPATH//'%LO3FL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECSHAL), CDPATH//'%LECSHAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECDEEP), CDPATH//'%LECDEEP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBNXR), CDPATH//'%LNEBNXR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEB_FP), CDPATH//'%LNEB_FP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LQXRTGH), CDPATH//'%LQXRTGH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LHUCN), CDPATH//'%LHUCN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LFPCOR), CDPATH//'%LFPCOR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNOIAS), CDPATH//'%LNOIAS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LGLT), CDPATH//'%LGLT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEWD), CDPATH//'%LNEWD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LPROCLD), CDPATH//'%LPROCLD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEVAPP), CDPATH//'%LEVAPP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOLLEC), CDPATH//'%LCOLLEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LADJCLD), CDPATH//'%LADJCLD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSEDSTA), CDPATH//'%LSEDSTA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSEDLAG), CDPATH//'%LSEDLAG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSEDCL), CDPATH//'%LSEDCL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LFSVAR), CDPATH//'%LFSVAR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LFSFIX), CDPATH//'%LFSFIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LA0MPS), CDPATH//'%LA0MPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LARPMPS), CDPATH//'%LARPMPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%L3MT), CDPATH//'%L3MT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LGPCMT), CDPATH//'%LGPCMT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LENTCH), CDPATH//'%LENTCH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCDDEVPRO), CDPATH//'%LCDDEVPRO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAEROSEA), CDPATH//'%LAEROSEA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAEROLAN), CDPATH//'%LAEROLAN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAEROSOO), CDPATH//'%LAEROSOO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAERODES), CDPATH//'%LAERODES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAEROVOL), CDPATH//'%LAEROVOL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAEROSUL), CDPATH//'%LAEROSUL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAEROMMR), CDPATH//'%LAEROMMR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAERONRT), CDPATH//'%LAERONRT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRELAXT), CDPATH//'%LRELAXT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRELAXW), CDPATH//'%LRELAXW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSSD), CDPATH//'%LSSD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LPBLE), CDPATH//'%LPBLE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LBLVAR), CDPATH//'%LBLVAR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LZ0HSREL), CDPATH//'%LZ0HSREL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LZ0SNOWH), CDPATH//'%LZ0SNOWH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LMLH), CDPATH//'%LMLH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNODIFQC), CDPATH//'%LNODIFQC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNCVPGY), CDPATH//'%LNCVPGY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSQRML), CDPATH//'%LSQRML'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAB12), CDPATH//'%LAB12'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LFVGICE3), CDPATH//'%LFVGICE3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEVAPLOP), CDPATH//'%LEVAPLOP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCP06), CDPATH//'%LCP06'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVSHCU), CDPATH//'%LCVSHCU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVGQ), CDPATH//'%LCVGQ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LPEC), CDPATH//'%LPEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LUDEVOL), CDPATH//'%LUDEVOL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCDDCSD), CDPATH//'%LCDDCSD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NCLOMIX), CDPATH//'%NCLOMIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NFSIG), CDPATH//'%NFSIG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LHLRADUPD), CDPATH//'%LHLRADUPD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDPRECPERIOD), CDPATH//'%NDPRECPERIOD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDPRECPERIOD2), CDPATH//'%NDPRECPERIOD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LDPRECIPS), CDPATH//'%LDPRECIPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LDPRECIPS2), CDPATH//'%LDPRECIPS2'

CLIND = ''
CALL CRC64_TDPRECIPS (YD%YRDPRECIPS, KLUN, CDPATH//'%YRDPRECIPS'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TDVISI (YD%YRDVISI, KLUN, CDPATH//'%YRDVISI'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TDWET (YD%YRDWET, KLUN, CDPATH//'%YRDWET'//TRIM(CLIND))

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CGMIXLEN), CDPATH//'%CGMIXLEN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CGTURS), CDPATH//'%CGTURS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CGTRG), CDPATH//'%CGTRG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LPRGML), CDPATH//'%LPRGML'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVRA), CDPATH//'%LCVRA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVTDK), CDPATH//'%LCVTDK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LDAYD), CDPATH//'%LDAYD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVPRO), CDPATH//'%LCVPRO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LGRAPRO), CDPATH//'%LGRAPRO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCDDPRO), CDPATH//'%LCDDPRO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVCSD), CDPATH//'%LCVCSD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LUSL), CDPATH//'%LUSL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNSDO), CDPATH//'%LNSDO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECT), CDPATH//'%LECT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEFB), CDPATH//'%LEFB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LFLUSO), CDPATH//'%LFLUSO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECTQ1), CDPATH//'%LECTQ1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECTREP), CDPATH//'%LECTREP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LPTKE), CDPATH//'%LPTKE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFKTKE), CDPATH//'%LCOEFKTKE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFKSURF), CDPATH//'%LCOEFKSURF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_MSC), CDPATH//'%LCOEFK_MSC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_F1), CDPATH//'%LCOEFK_F1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_TOMS), CDPATH//'%LCOEFK_TOMS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_THS1), CDPATH//'%LCOEFK_THS1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_RIS), CDPATH//'%LCOEFK_RIS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_PL), CDPATH//'%LCOEFK_PL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_ML), CDPATH//'%LCOEFK_ML'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_PTTE), CDPATH//'%LCOEFK_PTTE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_FLX), CDPATH//'%LCOEFK_FLX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOEFK_SCQ), CDPATH//'%LCOEFK_SCQ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAFGD_A), CDPATH//'%LAFGD_A'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LGWD), CDPATH//'%LGWD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LGWDC), CDPATH//'%LGWDC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNORGWD), CDPATH//'%LNORGWD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LHMTO), CDPATH//'%LHMTO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBCO), CDPATH//'%LNEBCO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBN), CDPATH//'%LNEBN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBR), CDPATH//'%LNEBR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LPTOPC), CDPATH//'%LPTOPC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LOZONE), CDPATH//'%LOZONE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRAY), CDPATH//'%LRAY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRAYFM), CDPATH//'%LRAYFM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRMU0M), CDPATH//'%LRMU0M'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRAYFM15), CDPATH//'%LRAYFM15'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRRMES), CDPATH//'%LRRMES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSFHYD), CDPATH//'%LSFHYD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSNV), CDPATH//'%LSNV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSOLV), CDPATH//'%LSOLV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LFGEL), CDPATH//'%LFGEL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSTRA), CDPATH//'%LSTRA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSTRAS), CDPATH//'%LSTRAS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSTRAPRO), CDPATH//'%LSTRAPRO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEWSTAT), CDPATH//'%LNEWSTAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LTHERMO), CDPATH//'%LTHERMO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LVDIF), CDPATH//'%LVDIF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVLIS), CDPATH//'%LCVLIS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVCAS), CDPATH//'%LCVCAS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSCMF), CDPATH//'%LSCMF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LVGSN), CDPATH//'%LVGSN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LPHCDPI), CDPATH//'%LPHCDPI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBGR), CDPATH//'%LNEBGR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBGY), CDPATH//'%LNEBGY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVRAV3), CDPATH//'%LCVRAV3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVPPKF), CDPATH//'%LCVPPKF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVTURB), CDPATH//'%LCVTURB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBRIC), CDPATH//'%LNEBRIC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEDKF), CDPATH//'%LEDKF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEDMFI), CDPATH//'%LEDMFI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEDMFS), CDPATH//'%LEDMFS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECTFL), CDPATH//'%LECTFL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECTFL0), CDPATH//'%LECTFL0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LECTPRODCVP), CDPATH//'%LECTPRODCVP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPHYREP), CDPATH//'%NPHYREP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCAMOD), CDPATH//'%LCAMOD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCOMOD), CDPATH//'%LCOMOD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LPHSPSH), CDPATH//'%LPHSPSH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSMNIMBT), CDPATH//'%LSMNIMBT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSMTPS), CDPATH//'%LSMTPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSMGCDEV), CDPATH//'%LSMGCDEV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LXRCDEV), CDPATH//'%LXRCDEV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRKCDEV), CDPATH//'%LRKCDEV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSMITH_CDEV), CDPATH//'%LSMITH_CDEV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRCVOTT), CDPATH//'%LRCVOTT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBCV), CDPATH//'%LNEBCV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBINS), CDPATH//'%LNEBINS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDIFFNEB), CDPATH//'%NDIFFNEB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NIMELIT), CDPATH//'%NIMELIT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NRAY), CDPATH//'%NRAY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSORAYFR), CDPATH//'%NSORAYFR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NTHRAYFR), CDPATH//'%NTHRAYFR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NRAUTOEV), CDPATH//'%NRAUTOEV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSMTBOT), CDPATH//'%NSMTBOT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSMDNEB), CDPATH//'%NSMDNEB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPRAC), CDPATH//'%NPRAC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPRRI), CDPATH//'%NPRRI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPHY), CDPATH//'%NPHY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NCALLRAD), CDPATH//'%NCALLRAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NLEND), CDPATH//'%NLEND'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NTEND_DIAG_POS), CDPATH//'%NTEND_DIAG_POS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NTEND_DIAG_FREQ_RESET), CDPATH//'%NTEND_DIAG_FREQ_RESET'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LNEBECT), CDPATH//'%LNEBECT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LCVGQKF), CDPATH//'%LCVGQKF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LACDIFUS), CDPATH//'%LACDIFUS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%L2MICRO), CDPATH//'%L2MICRO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSOLE), CDPATH//'%NSOLE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAJUCV), CDPATH//'%LAJUCV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LSMOOTHMELT), CDPATH//'%LSMOOTHMELT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LGCHECKMV), CDPATH//'%LGCHECKMV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LGCHECKNAN), CDPATH//'%LGCHECKNAN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LEDR), CDPATH//'%LEDR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LWINDFARM), CDPATH//'%LWINDFARM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LVOLKER), CDPATH//'%LVOLKER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NWINDFARMMODORO), CDPATH//'%NWINDFARMMODORO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LAPL_ARPEGE), CDPATH//'%LAPL_ARPEGE'

CLIND = ''
CALL CRC64_TCAPE (YD%YRCAPE, KLUN, CDPATH//'%YRCAPE'//TRIM(CLIND))

END SUBROUTINE

SUBROUTINE WIPE_TPHY (YD, LDDELETED, LDFIELDAPI)
USE UTIL_TCAPE_MOD
USE UTIL_TDPRECIPS_MOD
USE UTIL_TDVISI_MOD
USE UTIL_TDWET_MOD
IMPLICIT NONE
TYPE (TPHY), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF




































































































CALL WIPE_TDPRECIPS (YD%YRDPRECIPS, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TDVISI (YD%YRDVISI, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TDWET (YD%YRDWET, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)




















































































































CALL WIPE_TCAPE (YD%YRCAPE, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TPHY (YD, CDPATH, LDPRINT) RESULT (KSIZE)
USE UTIL_TCAPE_MOD
USE UTIL_TDPRECIPS_MOD
USE UTIL_TDVISI_MOD
USE UTIL_TDWET_MOD
IMPLICIT NONE
TYPE (TPHY),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%NBITER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NBITER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NITERFL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NITERFL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDPSFI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDPSFI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LMPHYS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMPHYS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LREASUR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LREASUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCAPE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCAPE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVGQD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVGQD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVGQM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVGQM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVGQP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVGQP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCONDWT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCONDWT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVDD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVDD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVPGY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVPGY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVPP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVPP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDIFCEXP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDIFCEXP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDIFCONS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDIFCONS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDIFQL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDIFQL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDISTUR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDISTUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEIGE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEIGE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRNUMX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRNUMX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRNUEXP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRNUEXP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRTRUEBBC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRTRUEBBC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRTRUEDIR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRTRUEDIR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LACPANMX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LACPANMX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCLSATUR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCLSATUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LVOIGT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LVOIGT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGLACIERS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGLACIERS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LVFULL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LVFULL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSLC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSLC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRAYLU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRAYLU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LREWS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LREWS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRPROX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRPROX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRMIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRMIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRSTAB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRSTAB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRSTAER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRSTAER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRTPP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRTPP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRTDL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRTDL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRAYPL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRAYPL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRRGUST)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRRGUST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LO3ABC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LO3ABC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LO3FL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LO3FL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECSHAL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECSHAL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECDEEP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECDEEP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBNXR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBNXR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEB_FP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEB_FP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LQXRTGH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LQXRTGH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LHUCN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHUCN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LFPCOR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LFPCOR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNOIAS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNOIAS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGLT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGLT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEWD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEWD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LPROCLD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPROCLD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEVAPP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEVAPP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOLLEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOLLEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LADJCLD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LADJCLD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSEDSTA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSEDSTA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSEDLAG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSEDLAG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSEDCL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSEDCL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LFSVAR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LFSVAR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LFSFIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LFSFIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LA0MPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LA0MPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LARPMPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LARPMPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%L3MT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%L3MT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGPCMT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGPCMT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LENTCH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LENTCH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCDDEVPRO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCDDEVPRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAEROSEA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAEROSEA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAEROLAN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAEROLAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAEROSOO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAEROSOO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAERODES)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAERODES'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAEROVOL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAEROVOL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAEROSUL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAEROSUL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAEROMMR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAEROMMR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAERONRT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAERONRT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRELAXT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRELAXT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRELAXW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRELAXW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSSD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSSD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LPBLE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPBLE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LBLVAR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LBLVAR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LZ0HSREL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LZ0HSREL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LZ0SNOWH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LZ0SNOWH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LMLH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LMLH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNODIFQC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNODIFQC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNCVPGY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNCVPGY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSQRML)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSQRML'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAB12)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAB12'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LFVGICE3)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LFVGICE3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEVAPLOP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEVAPLOP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCP06)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCP06'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVSHCU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVSHCU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVGQ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVGQ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LPEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LUDEVOL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LUDEVOL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCDDCSD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCDDCSD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCLOMIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCLOMIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NFSIG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFSIG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LHLRADUPD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHLRADUPD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDPRECPERIOD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDPRECPERIOD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDPRECPERIOD2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDPRECPERIOD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDPRECIPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDPRECIPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDPRECIPS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDPRECIPS2'
ENDIF
KSIZE = KSIZE + ISIZE
JSIZE = 0
ISIZE = SIZE_TDPRECIPS (YD%YRDPRECIPS, CLPATH//'%YRDPRECIPS', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDPRECIPS'
ENDIF
JSIZE = 0
ISIZE = SIZE_TDVISI (YD%YRDVISI, CLPATH//'%YRDVISI', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDVISI'
ENDIF
JSIZE = 0
ISIZE = SIZE_TDWET (YD%YRDWET, CLPATH//'%YRDWET', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDWET'
ENDIF
ISIZE = KIND (YD%CGMIXLEN) * LEN (YD%CGMIXLEN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CGMIXLEN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CGTURS) * LEN (YD%CGTURS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CGTURS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CGTRG) * LEN (YD%CGTRG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CGTRG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LPRGML)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPRGML'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVRA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVRA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVTDK)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVTDK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDAYD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDAYD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVPRO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVPRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGRAPRO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGRAPRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCDDPRO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCDDPRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVCSD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVCSD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LUSL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LUSL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNSDO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNSDO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEFB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEFB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LFLUSO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LFLUSO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECTQ1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECTQ1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECTREP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECTREP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LPTKE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPTKE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFKTKE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFKTKE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFKSURF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFKSURF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_MSC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_MSC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_F1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_F1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_TOMS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_TOMS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_THS1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_THS1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_RIS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_RIS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_PL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_PL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_ML)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_ML'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_PTTE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_PTTE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_FLX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_FLX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOEFK_SCQ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOEFK_SCQ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAFGD_A)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAFGD_A'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGWD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGWD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGWDC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGWDC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNORGWD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNORGWD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LHMTO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LHMTO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBCO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBCO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LPTOPC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPTOPC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LOZONE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LOZONE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRAY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRAY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRAYFM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRAYFM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRMU0M)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRMU0M'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRAYFM15)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRAYFM15'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRRMES)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRRMES'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSFHYD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSFHYD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSNV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSNV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSOLV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSOLV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LFGEL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LFGEL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSTRA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSTRA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSTRAS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSTRAS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSTRAPRO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSTRAPRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEWSTAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEWSTAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LTHERMO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LTHERMO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LVDIF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LVDIF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVLIS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVLIS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVCAS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVCAS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSCMF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSCMF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LVGSN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LVGSN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LPHCDPI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPHCDPI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBGR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBGR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBGY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBGY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVRAV3)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVRAV3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVPPKF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVPPKF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVTURB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVTURB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBRIC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBRIC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEDKF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEDKF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEDMFI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEDMFI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEDMFS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEDMFS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECTFL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECTFL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECTFL0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECTFL0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LECTPRODCVP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LECTPRODCVP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPHYREP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPHYREP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCAMOD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCAMOD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCOMOD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCOMOD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LPHSPSH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LPHSPSH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSMNIMBT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSMNIMBT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSMTPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSMTPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSMGCDEV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSMGCDEV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LXRCDEV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LXRCDEV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRKCDEV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRKCDEV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSMITH_CDEV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSMITH_CDEV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRCVOTT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRCVOTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBCV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBCV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBINS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBINS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDIFFNEB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDIFFNEB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NIMELIT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NIMELIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NRAY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NRAY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSORAYFR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSORAYFR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTHRAYFR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTHRAYFR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NRAUTOEV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NRAUTOEV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSMTBOT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSMTBOT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSMDNEB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSMDNEB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPRAC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPRAC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPRRI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPRRI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPHY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPHY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NCALLRAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NCALLRAD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NLEND)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NLEND'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTEND_DIAG_POS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTEND_DIAG_POS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTEND_DIAG_FREQ_RESET)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTEND_DIAG_FREQ_RESET'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LNEBECT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LNEBECT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LCVGQKF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LCVGQKF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LACDIFUS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LACDIFUS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%L2MICRO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%L2MICRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSOLE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSOLE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAJUCV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAJUCV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LSMOOTHMELT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSMOOTHMELT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGCHECKMV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGCHECKMV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LGCHECKNAN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LGCHECKNAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LEDR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LEDR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LWINDFARM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LWINDFARM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LVOLKER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LVOLKER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NWINDFARMMODORO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NWINDFARMMODORO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LAPL_ARPEGE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LAPL_ARPEGE'
ENDIF
KSIZE = KSIZE + ISIZE
JSIZE = 0
ISIZE = SIZE_TCAPE (YD%YRCAPE, CLPATH//'%YRCAPE', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRCAPE'
ENDIF
END FUNCTION

END MODULE
