MODULE UTIL_RADIATION_GRID_STRUCT_MOD

USE YOMPRAD, ONLY : RADIATION_GRID_STRUCT

INTERFACE SAVE
MODULE PROCEDURE SAVE_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_RADIATION_GRID_STRUCT
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_RADIATION_GRID_STRUCT
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_RADIATION_GRID_STRUCT
END INTERFACE


CONTAINS

SUBROUTINE SAVE_RADIATION_GRID_STRUCT (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: YD
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
WRITE (KLUN) YD%NRESOL_ID
WRITE (KLUN) YD%NGPTOT
WRITE (KLUN) YD%NGPTOTG
WRITE (KLUN) YD%NGPTOTMX
WRITE (KLUN) YD%NSPEC2
WRITE (KLUN) YD%NSMAX
WRITE (KLUN) YD%NPTRFLOFF
WRITE (KLUN) YD%NUMP
WRITE (KLUN) YD%NDLON
WRITE (KLUN) YD%NDGSAL
WRITE (KLUN) YD%NDGENL
WRITE (KLUN) YD%NDGSAH
WRITE (KLUN) YD%NDGENH
WRITE (KLUN) YD%NDGLG
WRITE (KLUN) YD%NDGSAG
WRITE (KLUN) YD%NDGENG
WRITE (KLUN) YD%NDLSUR
WRITE (KLUN) YD%NFRSTLOFF
WRITE (KLUN) YD%NDSUR1
WRITE (KLUN) YD%NDGSUR
WRITE (KLUN) YD%MYFRSTACTLAT
WRITE (KLUN) YD%MYLSTACTLAT
LNRGRI = ALLOCATED (YD%NRGRI)
WRITE (KLUN) LNRGRI
IF (LNRGRI) THEN
  WRITE (KLUN) LBOUND (YD%NRGRI)
  WRITE (KLUN) UBOUND (YD%NRGRI)
  WRITE (KLUN) YD%NRGRI
ENDIF
LNLOENG = ALLOCATED (YD%NLOENG)
WRITE (KLUN) LNLOENG
IF (LNLOENG) THEN
  WRITE (KLUN) LBOUND (YD%NLOENG)
  WRITE (KLUN) UBOUND (YD%NLOENG)
  WRITE (KLUN) YD%NLOENG
ENDIF
LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
WRITE (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NPTRFRSTLAT)
  WRITE (KLUN) YD%NPTRFRSTLAT
ENDIF
LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
WRITE (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NFRSTLAT)
  WRITE (KLUN) UBOUND (YD%NFRSTLAT)
  WRITE (KLUN) YD%NFRSTLAT
ENDIF
LNLSTLAT = ALLOCATED (YD%NLSTLAT)
WRITE (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  WRITE (KLUN) LBOUND (YD%NLSTLAT)
  WRITE (KLUN) UBOUND (YD%NLSTLAT)
  WRITE (KLUN) YD%NLSTLAT
ENDIF
LMYMS = ALLOCATED (YD%MYMS)
WRITE (KLUN) LMYMS
IF (LMYMS) THEN
  WRITE (KLUN) LBOUND (YD%MYMS)
  WRITE (KLUN) UBOUND (YD%MYMS)
  WRITE (KLUN) YD%MYMS
ENDIF
LNASM0 = ALLOCATED (YD%NASM0)
WRITE (KLUN) LNASM0
IF (LNASM0) THEN
  WRITE (KLUN) LBOUND (YD%NASM0)
  WRITE (KLUN) UBOUND (YD%NASM0)
  WRITE (KLUN) YD%NASM0
ENDIF
LNSTA = ALLOCATED (YD%NSTA)
WRITE (KLUN) LNSTA
IF (LNSTA) THEN
  WRITE (KLUN) LBOUND (YD%NSTA)
  WRITE (KLUN) UBOUND (YD%NSTA)
  WRITE (KLUN) YD%NSTA
ENDIF
LNONL = ALLOCATED (YD%NONL)
WRITE (KLUN) LNONL
IF (LNONL) THEN
  WRITE (KLUN) LBOUND (YD%NONL)
  WRITE (KLUN) UBOUND (YD%NONL)
  WRITE (KLUN) YD%NONL
ENDIF
LGELAM = ALLOCATED (YD%GELAM)
WRITE (KLUN) LGELAM
IF (LGELAM) THEN
  WRITE (KLUN) LBOUND (YD%GELAM)
  WRITE (KLUN) UBOUND (YD%GELAM)
  WRITE (KLUN) YD%GELAM
ENDIF
LGELAT = ALLOCATED (YD%GELAT)
WRITE (KLUN) LGELAT
IF (LGELAT) THEN
  WRITE (KLUN) LBOUND (YD%GELAT)
  WRITE (KLUN) UBOUND (YD%GELAT)
  WRITE (KLUN) YD%GELAT
ENDIF
LGECLO = ALLOCATED (YD%GECLO)
WRITE (KLUN) LGECLO
IF (LGECLO) THEN
  WRITE (KLUN) LBOUND (YD%GECLO)
  WRITE (KLUN) UBOUND (YD%GECLO)
  WRITE (KLUN) YD%GECLO
ENDIF
LGESLO = ALLOCATED (YD%GESLO)
WRITE (KLUN) LGESLO
IF (LGESLO) THEN
  WRITE (KLUN) LBOUND (YD%GESLO)
  WRITE (KLUN) UBOUND (YD%GESLO)
  WRITE (KLUN) YD%GESLO
ENDIF
LRMU = ALLOCATED (YD%RMU)
WRITE (KLUN) LRMU
IF (LRMU) THEN
  WRITE (KLUN) LBOUND (YD%RMU)
  WRITE (KLUN) UBOUND (YD%RMU)
  WRITE (KLUN) YD%RMU
ENDIF
LRSQM2 = ALLOCATED (YD%RSQM2)
WRITE (KLUN) LRSQM2
IF (LRSQM2) THEN
  WRITE (KLUN) LBOUND (YD%RSQM2)
  WRITE (KLUN) UBOUND (YD%RSQM2)
  WRITE (KLUN) YD%RSQM2
ENDIF
LRLATIG = ALLOCATED (YD%RLATIG)
WRITE (KLUN) LRLATIG
IF (LRLATIG) THEN
  WRITE (KLUN) LBOUND (YD%RLATIG)
  WRITE (KLUN) UBOUND (YD%RLATIG)
  WRITE (KLUN) YD%RLATIG
ENDIF
LRLATI = ALLOCATED (YD%RLATI)
WRITE (KLUN) LRLATI
IF (LRLATI) THEN
  WRITE (KLUN) LBOUND (YD%RLATI)
  WRITE (KLUN) UBOUND (YD%RLATI)
  WRITE (KLUN) YD%RLATI
ENDIF
LGEMU = ALLOCATED (YD%GEMU)
WRITE (KLUN) LGEMU
IF (LGEMU) THEN
  WRITE (KLUN) LBOUND (YD%GEMU)
  WRITE (KLUN) UBOUND (YD%GEMU)
  WRITE (KLUN) YD%GEMU
ENDIF
LRIPI = ALLOCATED (YD%RIPI)
WRITE (KLUN) LRIPI
IF (LRIPI) THEN
  WRITE (KLUN) LBOUND (YD%RIPI)
  WRITE (KLUN) UBOUND (YD%RIPI)
  WRITE (KLUN) YD%RIPI
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_RADIATION_GRID_STRUCT (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (RADIATION_GRID_STRUCT), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
READ (KLUN) YD%NRESOL_ID
READ (KLUN) YD%NGPTOT
READ (KLUN) YD%NGPTOTG
READ (KLUN) YD%NGPTOTMX
READ (KLUN) YD%NSPEC2
READ (KLUN) YD%NSMAX
READ (KLUN) YD%NPTRFLOFF
READ (KLUN) YD%NUMP
READ (KLUN) YD%NDLON
READ (KLUN) YD%NDGSAL
READ (KLUN) YD%NDGENL
READ (KLUN) YD%NDGSAH
READ (KLUN) YD%NDGENH
READ (KLUN) YD%NDGLG
READ (KLUN) YD%NDGSAG
READ (KLUN) YD%NDGENG
READ (KLUN) YD%NDLSUR
READ (KLUN) YD%NFRSTLOFF
READ (KLUN) YD%NDSUR1
READ (KLUN) YD%NDGSUR
READ (KLUN) YD%MYFRSTACTLAT
READ (KLUN) YD%MYLSTACTLAT
READ (KLUN) LNRGRI
IF (LNRGRI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NRGRI (IL1(1):IU1(1)))
  READ (KLUN) YD%NRGRI
ENDIF
READ (KLUN) LNLOENG
IF (LNLOENG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLOENG (IL1(1):IU1(1)))
  READ (KLUN) YD%NLOENG
ENDIF
READ (KLUN) LNPTRFRSTLAT
IF (LNPTRFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NPTRFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NPTRFRSTLAT
ENDIF
READ (KLUN) LNFRSTLAT
IF (LNFRSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NFRSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NFRSTLAT
ENDIF
READ (KLUN) LNLSTLAT
IF (LNLSTLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NLSTLAT (IL1(1):IU1(1)))
  READ (KLUN) YD%NLSTLAT
ENDIF
READ (KLUN) LMYMS
IF (LMYMS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%MYMS (IL1(1):IU1(1)))
  READ (KLUN) YD%MYMS
ENDIF
READ (KLUN) LNASM0
IF (LNASM0) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NASM0 (IL1(1):IU1(1)))
  READ (KLUN) YD%NASM0
ENDIF
READ (KLUN) LNSTA
IF (LNSTA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NSTA (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NSTA
ENDIF
READ (KLUN) LNONL
IF (LNONL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NONL (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NONL
ENDIF
READ (KLUN) LGELAM
IF (LGELAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%GELAM,1):UBOUND(YD%GELAM,1)))
  READ (KLUN) ZTMP1
  YD%GELAM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LGELAT
IF (LGELAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GELAT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%GELAT,1):UBOUND(YD%GELAT,1)))
  READ (KLUN) ZTMP1
  YD%GELAT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LGECLO
IF (LGECLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GECLO (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%GECLO,1):UBOUND(YD%GECLO,1)))
  READ (KLUN) ZTMP1
  YD%GECLO = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LGESLO
IF (LGESLO) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GESLO (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%GESLO,1):UBOUND(YD%GESLO,1)))
  READ (KLUN) ZTMP1
  YD%GESLO = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRMU
IF (LRMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RMU (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RMU,1):UBOUND(YD%RMU,1)))
  READ (KLUN) ZTMP1
  YD%RMU = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRSQM2
IF (LRSQM2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSQM2 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RSQM2,1):UBOUND(YD%RSQM2,1)))
  READ (KLUN) ZTMP1
  YD%RSQM2 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLATIG
IF (LRLATIG) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATIG (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RLATIG,1):UBOUND(YD%RLATIG,1)))
  READ (KLUN) ZTMP1
  YD%RLATIG = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLATI
IF (LRLATI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLATI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RLATI,1):UBOUND(YD%RLATI,1)))
  READ (KLUN) ZTMP1
  YD%RLATI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LGEMU
IF (LGEMU) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%GEMU (IL1(1):IU1(1)))
  READ (KLUN) YD%GEMU
ENDIF
READ (KLUN) LRIPI
IF (LRIPI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RIPI (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%RIPI
ENDIF
END SUBROUTINE


SUBROUTINE COPY_RADIATION_GRID_STRUCT (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF






















LNRGRI = ALLOCATED (YD%NRGRI)
IF (LNRGRI) THEN
  !$ACC ENTER DATA CREATE (YD%NRGRI)
  !$ACC UPDATE DEVICE (YD%NRGRI)
  !$ACC ENTER DATA ATTACH (YD%NRGRI)
ENDIF

LNLOENG = ALLOCATED (YD%NLOENG)
IF (LNLOENG) THEN
  !$ACC ENTER DATA CREATE (YD%NLOENG)
  !$ACC UPDATE DEVICE (YD%NLOENG)
  !$ACC ENTER DATA ATTACH (YD%NLOENG)
ENDIF

LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (YD%NPTRFRSTLAT)
  !$ACC UPDATE DEVICE (YD%NPTRFRSTLAT)
  !$ACC ENTER DATA ATTACH (YD%NPTRFRSTLAT)
ENDIF

LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (YD%NFRSTLAT)
  !$ACC UPDATE DEVICE (YD%NFRSTLAT)
  !$ACC ENTER DATA ATTACH (YD%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (YD%NLSTLAT)
IF (LNLSTLAT) THEN
  !$ACC ENTER DATA CREATE (YD%NLSTLAT)
  !$ACC UPDATE DEVICE (YD%NLSTLAT)
  !$ACC ENTER DATA ATTACH (YD%NLSTLAT)
ENDIF

LMYMS = ALLOCATED (YD%MYMS)
IF (LMYMS) THEN
  !$ACC ENTER DATA CREATE (YD%MYMS)
  !$ACC UPDATE DEVICE (YD%MYMS)
  !$ACC ENTER DATA ATTACH (YD%MYMS)
ENDIF

LNASM0 = ALLOCATED (YD%NASM0)
IF (LNASM0) THEN
  !$ACC ENTER DATA CREATE (YD%NASM0)
  !$ACC UPDATE DEVICE (YD%NASM0)
  !$ACC ENTER DATA ATTACH (YD%NASM0)
ENDIF

LNSTA = ALLOCATED (YD%NSTA)
IF (LNSTA) THEN
  !$ACC ENTER DATA CREATE (YD%NSTA)
  !$ACC UPDATE DEVICE (YD%NSTA)
  !$ACC ENTER DATA ATTACH (YD%NSTA)
ENDIF

LNONL = ALLOCATED (YD%NONL)
IF (LNONL) THEN
  !$ACC ENTER DATA CREATE (YD%NONL)
  !$ACC UPDATE DEVICE (YD%NONL)
  !$ACC ENTER DATA ATTACH (YD%NONL)
ENDIF

LGELAM = ALLOCATED (YD%GELAM)
IF (LGELAM) THEN
  !$ACC ENTER DATA CREATE (YD%GELAM)
  !$ACC UPDATE DEVICE (YD%GELAM)
  !$ACC ENTER DATA ATTACH (YD%GELAM)
ENDIF

LGELAT = ALLOCATED (YD%GELAT)
IF (LGELAT) THEN
  !$ACC ENTER DATA CREATE (YD%GELAT)
  !$ACC UPDATE DEVICE (YD%GELAT)
  !$ACC ENTER DATA ATTACH (YD%GELAT)
ENDIF

LGECLO = ALLOCATED (YD%GECLO)
IF (LGECLO) THEN
  !$ACC ENTER DATA CREATE (YD%GECLO)
  !$ACC UPDATE DEVICE (YD%GECLO)
  !$ACC ENTER DATA ATTACH (YD%GECLO)
ENDIF

LGESLO = ALLOCATED (YD%GESLO)
IF (LGESLO) THEN
  !$ACC ENTER DATA CREATE (YD%GESLO)
  !$ACC UPDATE DEVICE (YD%GESLO)
  !$ACC ENTER DATA ATTACH (YD%GESLO)
ENDIF

LRMU = ALLOCATED (YD%RMU)
IF (LRMU) THEN
  !$ACC ENTER DATA CREATE (YD%RMU)
  !$ACC UPDATE DEVICE (YD%RMU)
  !$ACC ENTER DATA ATTACH (YD%RMU)
ENDIF

LRSQM2 = ALLOCATED (YD%RSQM2)
IF (LRSQM2) THEN
  !$ACC ENTER DATA CREATE (YD%RSQM2)
  !$ACC UPDATE DEVICE (YD%RSQM2)
  !$ACC ENTER DATA ATTACH (YD%RSQM2)
ENDIF

LRLATIG = ALLOCATED (YD%RLATIG)
IF (LRLATIG) THEN
  !$ACC ENTER DATA CREATE (YD%RLATIG)
  !$ACC UPDATE DEVICE (YD%RLATIG)
  !$ACC ENTER DATA ATTACH (YD%RLATIG)
ENDIF

LRLATI = ALLOCATED (YD%RLATI)
IF (LRLATI) THEN
  !$ACC ENTER DATA CREATE (YD%RLATI)
  !$ACC UPDATE DEVICE (YD%RLATI)
  !$ACC ENTER DATA ATTACH (YD%RLATI)
ENDIF

LGEMU = ALLOCATED (YD%GEMU)
IF (LGEMU) THEN
  !$ACC ENTER DATA CREATE (YD%GEMU)
  !$ACC UPDATE DEVICE (YD%GEMU)
  !$ACC ENTER DATA ATTACH (YD%GEMU)
ENDIF

LRIPI = ALLOCATED (YD%RIPI)
IF (LRIPI) THEN
  !$ACC ENTER DATA CREATE (YD%RIPI)
  !$ACC UPDATE DEVICE (YD%RIPI)
  !$ACC ENTER DATA ATTACH (YD%RIPI)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_RADIATION_GRID_STRUCT (YD)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), TARGET :: YD
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2









































END SUBROUTINE

     

SUBROUTINE CRC64_RADIATION_GRID_STRUCT (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NRESOL_ID), CDPATH//'%NRESOL_ID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGPTOT), CDPATH//'%NGPTOT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGPTOTG), CDPATH//'%NGPTOTG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGPTOTMX), CDPATH//'%NGPTOTMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSPEC2), CDPATH//'%NSPEC2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSMAX), CDPATH//'%NSMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRFLOFF), CDPATH//'%NPTRFLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NUMP), CDPATH//'%NUMP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDLON), CDPATH//'%NDLON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGSAL), CDPATH//'%NDGSAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGENL), CDPATH//'%NDGENL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGSAH), CDPATH//'%NDGSAH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGENH), CDPATH//'%NDGENH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGLG), CDPATH//'%NDGLG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGSAG), CDPATH//'%NDGSAG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGENG), CDPATH//'%NDGENG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDLSUR), CDPATH//'%NDLSUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NFRSTLOFF), CDPATH//'%NFRSTLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDSUR1), CDPATH//'%NDSUR1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDGSUR), CDPATH//'%NDGSUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MYFRSTACTLAT), CDPATH//'%MYFRSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MYLSTACTLAT), CDPATH//'%MYLSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NRGRI), CDPATH//'%NRGRI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NLOENG), CDPATH//'%NLOENG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPTRFRSTLAT), CDPATH//'%NPTRFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NFRSTLAT), CDPATH//'%NFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NLSTLAT), CDPATH//'%NLSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MYMS), CDPATH//'%MYMS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NASM0), CDPATH//'%NASM0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSTA), CDPATH//'%NSTA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NONL), CDPATH//'%NONL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GELAM), CDPATH//'%GELAM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GELAT), CDPATH//'%GELAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GECLO), CDPATH//'%GECLO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GESLO), CDPATH//'%GESLO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RMU), CDPATH//'%RMU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RSQM2), CDPATH//'%RSQM2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RLATIG), CDPATH//'%RLATIG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RLATI), CDPATH//'%RLATI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GEMU), CDPATH//'%GEMU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RIPI), CDPATH//'%RIPI'

END SUBROUTINE

SUBROUTINE WIPE_RADIATION_GRID_STRUCT (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF






















LNRGRI = ALLOCATED (YD%NRGRI)
IF (LNRGRI) THEN
  !$ACC EXIT DATA DETACH (YD%NRGRI)
  !$ACC EXIT DATA DETACH (YD%NRGRI)
ENDIF

LNLOENG = ALLOCATED (YD%NLOENG)
IF (LNLOENG) THEN
  !$ACC EXIT DATA DETACH (YD%NLOENG)
  !$ACC EXIT DATA DETACH (YD%NLOENG)
ENDIF

LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$ACC EXIT DATA DETACH (YD%NPTRFRSTLAT)
  !$ACC EXIT DATA DETACH (YD%NPTRFRSTLAT)
ENDIF

LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$ACC EXIT DATA DETACH (YD%NFRSTLAT)
  !$ACC EXIT DATA DETACH (YD%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (YD%NLSTLAT)
IF (LNLSTLAT) THEN
  !$ACC EXIT DATA DETACH (YD%NLSTLAT)
  !$ACC EXIT DATA DETACH (YD%NLSTLAT)
ENDIF

LMYMS = ALLOCATED (YD%MYMS)
IF (LMYMS) THEN
  !$ACC EXIT DATA DETACH (YD%MYMS)
  !$ACC EXIT DATA DETACH (YD%MYMS)
ENDIF

LNASM0 = ALLOCATED (YD%NASM0)
IF (LNASM0) THEN
  !$ACC EXIT DATA DETACH (YD%NASM0)
  !$ACC EXIT DATA DETACH (YD%NASM0)
ENDIF

LNSTA = ALLOCATED (YD%NSTA)
IF (LNSTA) THEN
  !$ACC EXIT DATA DETACH (YD%NSTA)
  !$ACC EXIT DATA DETACH (YD%NSTA)
ENDIF

LNONL = ALLOCATED (YD%NONL)
IF (LNONL) THEN
  !$ACC EXIT DATA DETACH (YD%NONL)
  !$ACC EXIT DATA DETACH (YD%NONL)
ENDIF

LGELAM = ALLOCATED (YD%GELAM)
IF (LGELAM) THEN
  !$ACC EXIT DATA DETACH (YD%GELAM)
  !$ACC EXIT DATA DETACH (YD%GELAM)
ENDIF

LGELAT = ALLOCATED (YD%GELAT)
IF (LGELAT) THEN
  !$ACC EXIT DATA DETACH (YD%GELAT)
  !$ACC EXIT DATA DETACH (YD%GELAT)
ENDIF

LGECLO = ALLOCATED (YD%GECLO)
IF (LGECLO) THEN
  !$ACC EXIT DATA DETACH (YD%GECLO)
  !$ACC EXIT DATA DETACH (YD%GECLO)
ENDIF

LGESLO = ALLOCATED (YD%GESLO)
IF (LGESLO) THEN
  !$ACC EXIT DATA DETACH (YD%GESLO)
  !$ACC EXIT DATA DETACH (YD%GESLO)
ENDIF

LRMU = ALLOCATED (YD%RMU)
IF (LRMU) THEN
  !$ACC EXIT DATA DETACH (YD%RMU)
  !$ACC EXIT DATA DETACH (YD%RMU)
ENDIF

LRSQM2 = ALLOCATED (YD%RSQM2)
IF (LRSQM2) THEN
  !$ACC EXIT DATA DETACH (YD%RSQM2)
  !$ACC EXIT DATA DETACH (YD%RSQM2)
ENDIF

LRLATIG = ALLOCATED (YD%RLATIG)
IF (LRLATIG) THEN
  !$ACC EXIT DATA DETACH (YD%RLATIG)
  !$ACC EXIT DATA DETACH (YD%RLATIG)
ENDIF

LRLATI = ALLOCATED (YD%RLATI)
IF (LRLATI) THEN
  !$ACC EXIT DATA DETACH (YD%RLATI)
  !$ACC EXIT DATA DETACH (YD%RLATI)
ENDIF

LGEMU = ALLOCATED (YD%GEMU)
IF (LGEMU) THEN
  !$ACC EXIT DATA DETACH (YD%GEMU)
  !$ACC EXIT DATA DETACH (YD%GEMU)
ENDIF

LRIPI = ALLOCATED (YD%RIPI)
IF (LRIPI) THEN
  !$ACC EXIT DATA DETACH (YD%RIPI)
  !$ACC EXIT DATA DETACH (YD%RIPI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_RADIATION_GRID_STRUCT (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (RADIATION_GRID_STRUCT),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%NRESOL_ID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NRESOL_ID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NGPTOT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGPTOT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NGPTOTG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGPTOTG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NGPTOTMX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGPTOTMX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSPEC2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPEC2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPTRFLOFF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPTRFLOFF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NUMP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NUMP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDLON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDLON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGSAL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGENL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGSAH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGENH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGLG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGLG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGSAG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSAG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGENG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGENG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDLSUR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDLSUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NFRSTLOFF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFRSTLOFF'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDSUR1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDSUR1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDGSUR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDGSUR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MYFRSTACTLAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MYFRSTACTLAT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%MYLSTACTLAT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MYLSTACTLAT'
ENDIF
KSIZE = KSIZE + ISIZE
LNRGRI = ALLOCATED (YD%NRGRI)
IF (LNRGRI) THEN
  ISIZE = KIND (YD%NRGRI) * SIZE (YD%NRGRI)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NRGRI'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNLOENG = ALLOCATED (YD%NLOENG)
IF (LNLOENG) THEN
  ISIZE = KIND (YD%NLOENG) * SIZE (YD%NLOENG)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NLOENG'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNPTRFRSTLAT = ALLOCATED (YD%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  ISIZE = KIND (YD%NPTRFRSTLAT) * SIZE (YD%NPTRFRSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NPTRFRSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNFRSTLAT = ALLOCATED (YD%NFRSTLAT)
IF (LNFRSTLAT) THEN
  ISIZE = KIND (YD%NFRSTLAT) * SIZE (YD%NFRSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NFRSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNLSTLAT = ALLOCATED (YD%NLSTLAT)
IF (LNLSTLAT) THEN
  ISIZE = KIND (YD%NLSTLAT) * SIZE (YD%NLSTLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NLSTLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMYMS = ALLOCATED (YD%MYMS)
IF (LMYMS) THEN
  ISIZE = KIND (YD%MYMS) * SIZE (YD%MYMS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MYMS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNASM0 = ALLOCATED (YD%NASM0)
IF (LNASM0) THEN
  ISIZE = KIND (YD%NASM0) * SIZE (YD%NASM0)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NASM0'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNSTA = ALLOCATED (YD%NSTA)
IF (LNSTA) THEN
  ISIZE = KIND (YD%NSTA) * SIZE (YD%NSTA)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NSTA'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNONL = ALLOCATED (YD%NONL)
IF (LNONL) THEN
  ISIZE = KIND (YD%NONL) * SIZE (YD%NONL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NONL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGELAM = ALLOCATED (YD%GELAM)
IF (LGELAM) THEN
  ISIZE = KIND (YD%GELAM) * SIZE (YD%GELAM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GELAM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGELAT = ALLOCATED (YD%GELAT)
IF (LGELAT) THEN
  ISIZE = KIND (YD%GELAT) * SIZE (YD%GELAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GELAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGECLO = ALLOCATED (YD%GECLO)
IF (LGECLO) THEN
  ISIZE = KIND (YD%GECLO) * SIZE (YD%GECLO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GECLO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGESLO = ALLOCATED (YD%GESLO)
IF (LGESLO) THEN
  ISIZE = KIND (YD%GESLO) * SIZE (YD%GESLO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GESLO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRMU = ALLOCATED (YD%RMU)
IF (LRMU) THEN
  ISIZE = KIND (YD%RMU) * SIZE (YD%RMU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RMU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSQM2 = ALLOCATED (YD%RSQM2)
IF (LRSQM2) THEN
  ISIZE = KIND (YD%RSQM2) * SIZE (YD%RSQM2)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSQM2'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLATIG = ALLOCATED (YD%RLATIG)
IF (LRLATIG) THEN
  ISIZE = KIND (YD%RLATIG) * SIZE (YD%RLATIG)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLATIG'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLATI = ALLOCATED (YD%RLATI)
IF (LRLATI) THEN
  ISIZE = KIND (YD%RLATI) * SIZE (YD%RLATI)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLATI'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGEMU = ALLOCATED (YD%GEMU)
IF (LGEMU) THEN
  ISIZE = KIND (YD%GEMU) * SIZE (YD%GEMU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GEMU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRIPI = ALLOCATED (YD%RIPI)
IF (LRIPI) THEN
  ISIZE = KIND (YD%RIPI) * SIZE (YD%RIPI)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RIPI'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
