MODULE UTIL_TEGWD_MOD

USE YOEGWD, ONLY : TEGWD

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEGWD
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEGWD
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEGWD
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TEGWD
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TEGWD
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEGWD
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TEGWD
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TEGWD (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGWD), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%NKTOPG
WRITE (KLUN) YD%NGWDLIM
WRITE (KLUN) YD%NGWDTOP
WRITE (KLUN) YD%NDIFF_STRATO
WRITE (KLUN) YD%GFRCRIT
WRITE (KLUN) YD%GRCRIT
WRITE (KLUN) YD%GKDRAG
WRITE (KLUN) YD%GKWAKE
WRITE (KLUN) YD%GSSEC
WRITE (KLUN) YD%GTSEC
WRITE (KLUN) YD%GVSEC
WRITE (KLUN) YD%GTENLIM
WRITE (KLUN) YD%GRFPLM
WRITE (KLUN) YD%LRDIFF_STRATO
WRITE (KLUN) YD%LDIAG_STRATO
END SUBROUTINE

SUBROUTINE LOAD_TEGWD (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEGWD), INTENT (OUT), TARGET :: YD
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) YD%NKTOPG
READ (KLUN) YD%NGWDLIM
READ (KLUN) YD%NGWDTOP
READ (KLUN) YD%NDIFF_STRATO
READ (KLUN) ZTMP0
YD%GFRCRIT = ZTMP0
READ (KLUN) ZTMP0
YD%GRCRIT = ZTMP0
READ (KLUN) ZTMP0
YD%GKDRAG = ZTMP0
READ (KLUN) ZTMP0
YD%GKWAKE = ZTMP0
READ (KLUN) ZTMP0
YD%GSSEC = ZTMP0
READ (KLUN) ZTMP0
YD%GTSEC = ZTMP0
READ (KLUN) ZTMP0
YD%GVSEC = ZTMP0
READ (KLUN) ZTMP0
YD%GTENLIM = ZTMP0
READ (KLUN) ZTMP0
YD%GRFPLM = ZTMP0
READ (KLUN) YD%LRDIFF_STRATO
READ (KLUN) YD%LDIAG_STRATO
END SUBROUTINE


SUBROUTINE COPY_TEGWD (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEGWD), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF















END SUBROUTINE

SUBROUTINE HOST_TEGWD (YD)

IMPLICIT NONE
TYPE (TEGWD), TARGET :: YD
















END SUBROUTINE

     

SUBROUTINE CRC64_TEGWD (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TEGWD), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NKTOPG), CDPATH//'%NKTOPG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGWDLIM), CDPATH//'%NGWDLIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGWDTOP), CDPATH//'%NGWDTOP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDIFF_STRATO), CDPATH//'%NDIFF_STRATO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GFRCRIT), CDPATH//'%GFRCRIT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GRCRIT), CDPATH//'%GRCRIT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GKDRAG), CDPATH//'%GKDRAG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GKWAKE), CDPATH//'%GKWAKE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GSSEC), CDPATH//'%GSSEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GTSEC), CDPATH//'%GTSEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GVSEC), CDPATH//'%GVSEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GTENLIM), CDPATH//'%GTENLIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GRFPLM), CDPATH//'%GRFPLM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LRDIFF_STRATO), CDPATH//'%LRDIFF_STRATO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LDIAG_STRATO), CDPATH//'%LDIAG_STRATO'

END SUBROUTINE

SUBROUTINE WIPE_TEGWD (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEGWD), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF















LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TEGWD (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TEGWD),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%NKTOPG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NKTOPG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NGWDLIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGWDLIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NGWDTOP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGWDTOP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDIFF_STRATO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDIFF_STRATO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GFRCRIT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GFRCRIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GRCRIT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GRCRIT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GKDRAG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GKDRAG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GKWAKE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GKWAKE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GSSEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GSSEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTSEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GTSEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GVSEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GVSEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GTENLIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GTENLIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%GRFPLM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%GRFPLM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LRDIFF_STRATO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LRDIFF_STRATO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LDIAG_STRATO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LDIAG_STRATO'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
