MODULE UTIL_MF_PHYS_TYPE_MOD

USE MF_PHYS_TYPE_MOD, ONLY : MF_PHYS_TYPE



INTERFACE COPY
MODULE PROCEDURE COPY_MF_PHYS_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_MF_PHYS_TYPE
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_MF_PHYS_TYPE
END INTERFACE



CONTAINS





SUBROUTINE COPY_MF_PHYS_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_MF_PHYS_FOR_TYPE_MOD
USE UTIL_MF_PHYS_OPT_TYPE_MOD
USE UTIL_MF_PHYS_OUT_TYPE_MOD
IMPLICIT NONE
TYPE (MF_PHYS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
CALL COPY_MF_PHYS_OUT_TYPE (SELF%OUT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_MF_PHYS_OPT_TYPE (SELF%OPT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_MF_PHYS_FOR_TYPE (SELF%FOR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

SUBROUTINE HOST_MF_PHYS_TYPE (SELF)
USE UTIL_MF_PHYS_FOR_TYPE_MOD
USE UTIL_MF_PHYS_OPT_TYPE_MOD
USE UTIL_MF_PHYS_OUT_TYPE_MOD

IMPLICIT NONE
TYPE (MF_PHYS_TYPE), TARGET :: SELF

CALL HOST_MF_PHYS_OUT_TYPE (SELF%OUT)

CALL HOST_MF_PHYS_OPT_TYPE (SELF%OPT)

CALL HOST_MF_PHYS_FOR_TYPE (SELF%FOR)

END SUBROUTINE

     



SUBROUTINE WIPE_MF_PHYS_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_MF_PHYS_FOR_TYPE_MOD
USE UTIL_MF_PHYS_OPT_TYPE_MOD
USE UTIL_MF_PHYS_OUT_TYPE_MOD
IMPLICIT NONE
TYPE (MF_PHYS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL WIPE_MF_PHYS_OUT_TYPE (SELF%OUT, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_MF_PHYS_OPT_TYPE (SELF%OPT, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_MF_PHYS_FOR_TYPE (SELF%FOR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
