MODULE UTIL_TDWET_MOD

USE YOMDWET, ONLY : TDWET

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDWET
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDWET
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDWET
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TDWET
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TDWET
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDWET
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TDWET
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TDWET (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDWET), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%WBETA
WRITE (KLUN) YD%WRHOA
WRITE (KLUN) YD%WRHOB
WRITE (KLUN) YD%WDIAMWIRE
WRITE (KLUN) YD%HWET
WRITE (KLUN) YD%WURA
WRITE (KLUN) YD%WURB
WRITE (KLUN) YD%WFALLSN
WRITE (KLUN) YD%WTTA
WRITE (KLUN) YD%WTWB
WRITE (KLUN) YD%WTWA
WRITE (KLUN) YD%WTWDRYB
WRITE (KLUN) YD%WUUDRY
WRITE (KLUN) YD%WFALLICE
WRITE (KLUN) YD%WTWAICE
WRITE (KLUN) YD%WTWBICE
WRITE (KLUN) YD%WBETAICE
END SUBROUTINE

SUBROUTINE LOAD_TDWET (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDWET), INTENT (OUT), TARGET :: YD
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
YD%WBETA = ZTMP0
READ (KLUN) ZTMP0
YD%WRHOA = ZTMP0
READ (KLUN) ZTMP0
YD%WRHOB = ZTMP0
READ (KLUN) ZTMP0
YD%WDIAMWIRE = ZTMP0
READ (KLUN) ZTMP0
YD%HWET = ZTMP0
READ (KLUN) ZTMP0
YD%WURA = ZTMP0
READ (KLUN) ZTMP0
YD%WURB = ZTMP0
READ (KLUN) ZTMP0
YD%WFALLSN = ZTMP0
READ (KLUN) ZTMP0
YD%WTTA = ZTMP0
READ (KLUN) ZTMP0
YD%WTWB = ZTMP0
READ (KLUN) ZTMP0
YD%WTWA = ZTMP0
READ (KLUN) ZTMP0
YD%WTWDRYB = ZTMP0
READ (KLUN) ZTMP0
YD%WUUDRY = ZTMP0
READ (KLUN) ZTMP0
YD%WFALLICE = ZTMP0
READ (KLUN) ZTMP0
YD%WTWAICE = ZTMP0
READ (KLUN) ZTMP0
YD%WTWBICE = ZTMP0
READ (KLUN) ZTMP0
YD%WBETAICE = ZTMP0
END SUBROUTINE


SUBROUTINE COPY_TDWET (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDWET), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF

















END SUBROUTINE

SUBROUTINE HOST_TDWET (YD)

IMPLICIT NONE
TYPE (TDWET), TARGET :: YD


















END SUBROUTINE

     

SUBROUTINE CRC64_TDWET (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TDWET), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WBETA), CDPATH//'%WBETA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WRHOA), CDPATH//'%WRHOA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WRHOB), CDPATH//'%WRHOB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WDIAMWIRE), CDPATH//'%WDIAMWIRE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%HWET), CDPATH//'%HWET'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WURA), CDPATH//'%WURA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WURB), CDPATH//'%WURB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WFALLSN), CDPATH//'%WFALLSN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WTTA), CDPATH//'%WTTA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WTWB), CDPATH//'%WTWB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WTWA), CDPATH//'%WTWA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WTWDRYB), CDPATH//'%WTWDRYB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WUUDRY), CDPATH//'%WUUDRY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WFALLICE), CDPATH//'%WFALLICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WTWAICE), CDPATH//'%WTWAICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WTWBICE), CDPATH//'%WTWBICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%WBETAICE), CDPATH//'%WBETAICE'

END SUBROUTINE

SUBROUTINE WIPE_TDWET (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDWET), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

















LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TDWET (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TDWET),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%WBETA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WBETA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WRHOA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WRHOA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WRHOB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WRHOB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WDIAMWIRE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WDIAMWIRE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HWET)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%HWET'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WURA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WURA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WURB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WURB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WFALLSN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WFALLSN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WTTA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WTTA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WTWB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WTWB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WTWA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WTWA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WTWDRYB)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WTWDRYB'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WUUDRY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WUUDRY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WFALLICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WFALLICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WTWAICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WTWAICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WTWBICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WTWBICE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%WBETAICE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%WBETAICE'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
