MODULE UTIL_CPG_PHY_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_PHY_TYPE



INTERFACE COPY
MODULE PROCEDURE COPY_CPG_PHY_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_CPG_PHY_TYPE
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_PHY_TYPE
END INTERFACE



CONTAINS





SUBROUTINE COPY_CPG_PHY_TYPE (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_CPG_XYB_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_PHY_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_PRE, LF_PREF, LF_PREHYD, LF_PREHYDF, LF_W, LF_WL, LF_WM

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LF_PRE = ASSOCIATED (YD%F_PRE)
IF (LF_PRE .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_PRE)
  !$ACC ENTER DATA ATTACH (YD%F_PRE)
ENDIF

LF_PREF = ASSOCIATED (YD%F_PREF)
IF (LF_PREF .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_PREF)
  !$ACC ENTER DATA ATTACH (YD%F_PREF)
ENDIF

LF_PREHYD = ASSOCIATED (YD%F_PREHYD)
IF (LF_PREHYD .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_PREHYD)
  !$ACC ENTER DATA ATTACH (YD%F_PREHYD)
ENDIF

LF_PREHYDF = ASSOCIATED (YD%F_PREHYDF)
IF (LF_PREHYDF .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_PREHYDF)
  !$ACC ENTER DATA ATTACH (YD%F_PREHYDF)
ENDIF

LF_WL = ASSOCIATED (YD%F_WL)
IF (LF_WL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_WL)
  !$ACC ENTER DATA ATTACH (YD%F_WL)
ENDIF

LF_WM = ASSOCIATED (YD%F_WM)
IF (LF_WM .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_WM)
  !$ACC ENTER DATA ATTACH (YD%F_WM)
ENDIF

LF_W = ASSOCIATED (YD%F_W)
IF (LF_W .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_W)
  !$ACC ENTER DATA ATTACH (YD%F_W)
ENDIF

CALL COPY_CPG_XYB_TYPE (YD%XYB, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

SUBROUTINE HOST_CPG_PHY_TYPE (YD)
USE FIELD_UTIL_MODULE
USE UTIL_CPG_XYB_TYPE_MOD

IMPLICIT NONE
TYPE (CPG_PHY_TYPE), TARGET :: YD
LOGICAL :: LF_PRE, LF_PREF, LF_PREHYD, LF_PREHYDF, LF_W, LF_WL, LF_WM
LF_PRE = ASSOCIATED (YD%F_PRE)
IF (LF_PRE) THEN
  CALL HOST_FIELD_3RB (YD%F_PRE)
ENDIF

LF_PREF = ASSOCIATED (YD%F_PREF)
IF (LF_PREF) THEN
  CALL HOST_FIELD_3RB (YD%F_PREF)
ENDIF

LF_PREHYD = ASSOCIATED (YD%F_PREHYD)
IF (LF_PREHYD) THEN
  CALL HOST_FIELD_3RB (YD%F_PREHYD)
ENDIF

LF_PREHYDF = ASSOCIATED (YD%F_PREHYDF)
IF (LF_PREHYDF) THEN
  CALL HOST_FIELD_3RB (YD%F_PREHYDF)
ENDIF

LF_WL = ASSOCIATED (YD%F_WL)
IF (LF_WL) THEN
  CALL HOST_FIELD_3RB (YD%F_WL)
ENDIF

LF_WM = ASSOCIATED (YD%F_WM)
IF (LF_WM) THEN
  CALL HOST_FIELD_3RB (YD%F_WM)
ENDIF

LF_W = ASSOCIATED (YD%F_W)
IF (LF_W) THEN
  CALL HOST_FIELD_3RB (YD%F_W)
ENDIF

CALL HOST_CPG_XYB_TYPE (YD%XYB)

END SUBROUTINE

     



SUBROUTINE WIPE_CPG_PHY_TYPE (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_CPG_XYB_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_PHY_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_PRE, LF_PREF, LF_PREHYD, LF_PREHYDF, LF_W, LF_WL, LF_WM

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_PRE = ASSOCIATED (YD%F_PRE)
IF (LF_PRE .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_PRE)
ENDIF

LF_PREF = ASSOCIATED (YD%F_PREF)
IF (LF_PREF .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_PREF)
ENDIF

LF_PREHYD = ASSOCIATED (YD%F_PREHYD)
IF (LF_PREHYD .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_PREHYD)
ENDIF

LF_PREHYDF = ASSOCIATED (YD%F_PREHYDF)
IF (LF_PREHYDF .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_PREHYDF)
ENDIF

LF_WL = ASSOCIATED (YD%F_WL)
IF (LF_WL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_WL)
ENDIF

LF_WM = ASSOCIATED (YD%F_WM)
IF (LF_WM .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_WM)
ENDIF

LF_W = ASSOCIATED (YD%F_W)
IF (LF_W .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_W)
ENDIF

CALL WIPE_CPG_XYB_TYPE (YD%XYB, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
