MODULE UTIL_SURFACE_VIEW_GROUP_EXTRP_MOD

USE SURFACE_VIEWS_PROGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_EXTRP



INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VIEW_GROUP_EXTRP
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_SURFACE_VIEW_GROUP_EXTRP
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VIEW_GROUP_EXTRP
END INTERFACE



CONTAINS





SUBROUTINE COPY_SURFACE_VIEW_GROUP_EXTRP (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_EXTRP_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_EXTRP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC ENTER DATA CREATE (YD%VARIABLE_GROUP)
  !$ACC UPDATE DEVICE (YD%VARIABLE_GROUP)
  CALL COPY_SURFACE_VARIABLE_GROUP_EXTRP (YD%VARIABLE_GROUP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%VARIABLE_GROUP)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_4RB (YD%F_GROUP)
  !$ACC ENTER DATA ATTACH (YD%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_SURFACE_VIEW_GROUP_EXTRP (YD)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_EXTRP_MOD

IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_EXTRP), TARGET :: YD
LOGICAL :: LF_GROUP, LVARIABLE_GROUP
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  CALL HOST_SURFACE_VARIABLE_GROUP_EXTRP (YD%VARIABLE_GROUP)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_4RB (YD%F_GROUP)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_SURFACE_VIEW_GROUP_EXTRP (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_EXTRP_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_EXTRP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
  CALL WIPE_SURFACE_VARIABLE_GROUP_EXTRP (YD%VARIABLE_GROUP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (YD%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
