MODULE UTIL_TCSGEOM_MOD

USE YOMCSGEOM, ONLY : TCSGEOM

INTERFACE SAVE
MODULE PROCEDURE SAVE_TCSGEOM
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCSGEOM
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TCSGEOM
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TCSGEOM
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TCSGEOM
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TCSGEOM
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TCSGEOM
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TCSGEOM (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCSGEOM), INTENT (IN), TARGET :: YD
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
LRCOLON = ASSOCIATED (YD%RCOLON)
WRITE (KLUN) LRCOLON
IF (LRCOLON) THEN
  WRITE (KLUN) LBOUND (YD%RCOLON)
  WRITE (KLUN) UBOUND (YD%RCOLON)
  WRITE (KLUN) YD%RCOLON
ENDIF
LRSILON = ASSOCIATED (YD%RSILON)
WRITE (KLUN) LRSILON
IF (LRSILON) THEN
  WRITE (KLUN) LBOUND (YD%RSILON)
  WRITE (KLUN) UBOUND (YD%RSILON)
  WRITE (KLUN) YD%RSILON
ENDIF
LRINDX = ASSOCIATED (YD%RINDX)
WRITE (KLUN) LRINDX
IF (LRINDX) THEN
  WRITE (KLUN) LBOUND (YD%RINDX)
  WRITE (KLUN) UBOUND (YD%RINDX)
  WRITE (KLUN) YD%RINDX
ENDIF
LRINDY = ASSOCIATED (YD%RINDY)
WRITE (KLUN) LRINDY
IF (LRINDY) THEN
  WRITE (KLUN) LBOUND (YD%RINDY)
  WRITE (KLUN) UBOUND (YD%RINDY)
  WRITE (KLUN) YD%RINDY
ENDIF
LRATATH = ASSOCIATED (YD%RATATH)
WRITE (KLUN) LRATATH
IF (LRATATH) THEN
  WRITE (KLUN) LBOUND (YD%RATATH)
  WRITE (KLUN) UBOUND (YD%RATATH)
  WRITE (KLUN) YD%RATATH
ENDIF
LRATATX = ASSOCIATED (YD%RATATX)
WRITE (KLUN) LRATATX
IF (LRATATX) THEN
  WRITE (KLUN) LBOUND (YD%RATATX)
  WRITE (KLUN) UBOUND (YD%RATATX)
  WRITE (KLUN) YD%RATATX
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TCSGEOM (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCSGEOM), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
READ (KLUN) LRCOLON
IF (LRCOLON) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RCOLON (IL1(1):IU1(1)))
  READ (KLUN) YD%RCOLON
ELSE
  NULLIFY (YD%RCOLON)
ENDIF
READ (KLUN) LRSILON
IF (LRSILON) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSILON (IL1(1):IU1(1)))
  READ (KLUN) YD%RSILON
ELSE
  NULLIFY (YD%RSILON)
ENDIF
READ (KLUN) LRINDX
IF (LRINDX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RINDX (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RINDX,1):UBOUND(YD%RINDX,1)))
  READ (KLUN) ZTMP1
  YD%RINDX = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (YD%RINDX)
ENDIF
READ (KLUN) LRINDY
IF (LRINDY) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RINDY (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RINDY,1):UBOUND(YD%RINDY,1)))
  READ (KLUN) ZTMP1
  YD%RINDY = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (YD%RINDY)
ENDIF
READ (KLUN) LRATATH
IF (LRATATH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RATATH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RATATH,1):UBOUND(YD%RATATH,1)))
  READ (KLUN) ZTMP1
  YD%RATATH = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (YD%RATATH)
ENDIF
READ (KLUN) LRATATX
IF (LRATATX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RATATX (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RATATX,1):UBOUND(YD%RATATX,1)))
  READ (KLUN) ZTMP1
  YD%RATATX = ZTMP1
  DEALLOCATE (ZTMP1)
ELSE
  NULLIFY (YD%RATATX)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TCSGEOM (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCSGEOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LRCOLON = ASSOCIATED (YD%RCOLON)
IF (LRCOLON) THEN
  !$ACC ENTER DATA CREATE (YD%RCOLON)
  !$ACC UPDATE DEVICE (YD%RCOLON)
  !$ACC ENTER DATA ATTACH (YD%RCOLON)
ENDIF

LRSILON = ASSOCIATED (YD%RSILON)
IF (LRSILON) THEN
  !$ACC ENTER DATA CREATE (YD%RSILON)
  !$ACC UPDATE DEVICE (YD%RSILON)
  !$ACC ENTER DATA ATTACH (YD%RSILON)
ENDIF

LRINDX = ASSOCIATED (YD%RINDX)
IF (LRINDX) THEN
  !$ACC ENTER DATA CREATE (YD%RINDX)
  !$ACC UPDATE DEVICE (YD%RINDX)
  !$ACC ENTER DATA ATTACH (YD%RINDX)
ENDIF

LRINDY = ASSOCIATED (YD%RINDY)
IF (LRINDY) THEN
  !$ACC ENTER DATA CREATE (YD%RINDY)
  !$ACC UPDATE DEVICE (YD%RINDY)
  !$ACC ENTER DATA ATTACH (YD%RINDY)
ENDIF

LRATATH = ASSOCIATED (YD%RATATH)
IF (LRATATH) THEN
  !$ACC ENTER DATA CREATE (YD%RATATH)
  !$ACC UPDATE DEVICE (YD%RATATH)
  !$ACC ENTER DATA ATTACH (YD%RATATH)
ENDIF

LRATATX = ASSOCIATED (YD%RATATX)
IF (LRATATX) THEN
  !$ACC ENTER DATA CREATE (YD%RATATX)
  !$ACC UPDATE DEVICE (YD%RATATX)
  !$ACC ENTER DATA ATTACH (YD%RATATX)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TCSGEOM (YD)

IMPLICIT NONE
TYPE (TCSGEOM), TARGET :: YD
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON






END SUBROUTINE

     

SUBROUTINE CRC64_TCSGEOM (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TCSGEOM), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RCOLON), CDPATH//'%RCOLON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RSILON), CDPATH//'%RSILON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RINDX), CDPATH//'%RINDX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RINDY), CDPATH//'%RINDY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RATATH), CDPATH//'%RATATH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RATATX), CDPATH//'%RATATX'

END SUBROUTINE

SUBROUTINE WIPE_TCSGEOM (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TCSGEOM), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LRCOLON = ASSOCIATED (YD%RCOLON)
IF (LRCOLON) THEN
  !$ACC EXIT DATA DETACH (YD%RCOLON)
  !$ACC EXIT DATA DETACH (YD%RCOLON)
ENDIF

LRSILON = ASSOCIATED (YD%RSILON)
IF (LRSILON) THEN
  !$ACC EXIT DATA DETACH (YD%RSILON)
  !$ACC EXIT DATA DETACH (YD%RSILON)
ENDIF

LRINDX = ASSOCIATED (YD%RINDX)
IF (LRINDX) THEN
  !$ACC EXIT DATA DETACH (YD%RINDX)
  !$ACC EXIT DATA DETACH (YD%RINDX)
ENDIF

LRINDY = ASSOCIATED (YD%RINDY)
IF (LRINDY) THEN
  !$ACC EXIT DATA DETACH (YD%RINDY)
  !$ACC EXIT DATA DETACH (YD%RINDY)
ENDIF

LRATATH = ASSOCIATED (YD%RATATH)
IF (LRATATH) THEN
  !$ACC EXIT DATA DETACH (YD%RATATH)
  !$ACC EXIT DATA DETACH (YD%RATATH)
ENDIF

LRATATX = ASSOCIATED (YD%RATATX)
IF (LRATATX) THEN
  !$ACC EXIT DATA DETACH (YD%RATATX)
  !$ACC EXIT DATA DETACH (YD%RATATX)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TCSGEOM (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TCSGEOM),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LRCOLON = ASSOCIATED (YD%RCOLON)
IF (LRCOLON) THEN
  ISIZE = KIND (YD%RCOLON) * SIZE (YD%RCOLON)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RCOLON'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSILON = ASSOCIATED (YD%RSILON)
IF (LRSILON) THEN
  ISIZE = KIND (YD%RSILON) * SIZE (YD%RSILON)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSILON'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRINDX = ASSOCIATED (YD%RINDX)
IF (LRINDX) THEN
  ISIZE = KIND (YD%RINDX) * SIZE (YD%RINDX)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RINDX'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRINDY = ASSOCIATED (YD%RINDY)
IF (LRINDY) THEN
  ISIZE = KIND (YD%RINDY) * SIZE (YD%RINDY)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RINDY'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRATATH = ASSOCIATED (YD%RATATH)
IF (LRATATH) THEN
  ISIZE = KIND (YD%RATATH) * SIZE (YD%RATATH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RATATH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRATATX = ASSOCIATED (YD%RATATX)
IF (LRATATX) THEN
  ISIZE = KIND (YD%RATATX) * SIZE (YD%RATATX)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RATATX'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
