MODULE UTIL_TSLREP_MOD

USE YOMSLREP, ONLY : TSLREP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TSLREP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TSLREP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TSLREP
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TSLREP
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TSLREP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TSLREP
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TSLREP
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TSLREP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSLREP), INTENT (IN), TARGET :: YD
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN
WRITE (KLUN) YD%NGPTOTAD
LNADMAP = ALLOCATED (YD%NADMAP)
WRITE (KLUN) LNADMAP
IF (LNADMAP) THEN
  WRITE (KLUN) LBOUND (YD%NADMAP)
  WRITE (KLUN) UBOUND (YD%NADMAP)
  WRITE (KLUN) YD%NADMAP
ENDIF
LNADCORE = ALLOCATED (YD%NADCORE)
WRITE (KLUN) LNADCORE
IF (LNADCORE) THEN
  WRITE (KLUN) LBOUND (YD%NADCORE)
  WRITE (KLUN) UBOUND (YD%NADCORE)
  WRITE (KLUN) YD%NADCORE
ENDIF
LLADCORE = ALLOCATED (YD%LADCORE)
WRITE (KLUN) LLADCORE
IF (LLADCORE) THEN
  WRITE (KLUN) LBOUND (YD%LADCORE)
  WRITE (KLUN) UBOUND (YD%LADCORE)
  WRITE (KLUN) YD%LADCORE
ENDIF
LRSASIGN = ALLOCATED (YD%RSASIGN)
WRITE (KLUN) LRSASIGN
IF (LRSASIGN) THEN
  WRITE (KLUN) LBOUND (YD%RSASIGN)
  WRITE (KLUN) UBOUND (YD%RSASIGN)
  WRITE (KLUN) YD%RSASIGN
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TSLREP (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TSLREP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) YD%NGPTOTAD
READ (KLUN) LNADMAP
IF (LNADMAP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NADMAP (IL1(1):IU1(1)))
  READ (KLUN) YD%NADMAP
ENDIF
READ (KLUN) LNADCORE
IF (LNADCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%NADCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%NADCORE
ENDIF
READ (KLUN) LLADCORE
IF (LLADCORE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%LADCORE (IL1(1):IU1(1)))
  READ (KLUN) YD%LADCORE
ENDIF
READ (KLUN) LRSASIGN
IF (LRSASIGN) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RSASIGN (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RSASIGN,1):UBOUND(YD%RSASIGN,1), LBOUND(YD%RSASIGN,2):UBOUND(YD%RSASIGN,2)))
  READ (KLUN) ZTMP2
  YD%RSASIGN = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TSLREP (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSLREP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF

LNADMAP = ALLOCATED (YD%NADMAP)
IF (LNADMAP) THEN
  !$ACC ENTER DATA CREATE (YD%NADMAP)
  !$ACC UPDATE DEVICE (YD%NADMAP)
  !$ACC ENTER DATA ATTACH (YD%NADMAP)
ENDIF

LNADCORE = ALLOCATED (YD%NADCORE)
IF (LNADCORE) THEN
  !$ACC ENTER DATA CREATE (YD%NADCORE)
  !$ACC UPDATE DEVICE (YD%NADCORE)
  !$ACC ENTER DATA ATTACH (YD%NADCORE)
ENDIF

LLADCORE = ALLOCATED (YD%LADCORE)
IF (LLADCORE) THEN
  !$ACC ENTER DATA CREATE (YD%LADCORE)
  !$ACC UPDATE DEVICE (YD%LADCORE)
  !$ACC ENTER DATA ATTACH (YD%LADCORE)
ENDIF

LRSASIGN = ALLOCATED (YD%RSASIGN)
IF (LRSASIGN) THEN
  !$ACC ENTER DATA CREATE (YD%RSASIGN)
  !$ACC UPDATE DEVICE (YD%RSASIGN)
  !$ACC ENTER DATA ATTACH (YD%RSASIGN)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TSLREP (YD)

IMPLICIT NONE
TYPE (TSLREP), TARGET :: YD
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN





END SUBROUTINE

     

SUBROUTINE CRC64_TSLREP (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TSLREP), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGPTOTAD), CDPATH//'%NGPTOTAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NADMAP), CDPATH//'%NADMAP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NADCORE), CDPATH//'%NADCORE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LADCORE), CDPATH//'%LADCORE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RSASIGN), CDPATH//'%RSASIGN'

END SUBROUTINE

SUBROUTINE WIPE_TSLREP (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TSLREP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LNADMAP = ALLOCATED (YD%NADMAP)
IF (LNADMAP) THEN
  !$ACC EXIT DATA DETACH (YD%NADMAP)
  !$ACC EXIT DATA DETACH (YD%NADMAP)
ENDIF

LNADCORE = ALLOCATED (YD%NADCORE)
IF (LNADCORE) THEN
  !$ACC EXIT DATA DETACH (YD%NADCORE)
  !$ACC EXIT DATA DETACH (YD%NADCORE)
ENDIF

LLADCORE = ALLOCATED (YD%LADCORE)
IF (LLADCORE) THEN
  !$ACC EXIT DATA DETACH (YD%LADCORE)
  !$ACC EXIT DATA DETACH (YD%LADCORE)
ENDIF

LRSASIGN = ALLOCATED (YD%RSASIGN)
IF (LRSASIGN) THEN
  !$ACC EXIT DATA DETACH (YD%RSASIGN)
  !$ACC EXIT DATA DETACH (YD%RSASIGN)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TSLREP (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TSLREP),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LLADCORE, LNADCORE, LNADMAP, LRSASIGN

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%NGPTOTAD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGPTOTAD'
ENDIF
KSIZE = KSIZE + ISIZE
LNADMAP = ALLOCATED (YD%NADMAP)
IF (LNADMAP) THEN
  ISIZE = KIND (YD%NADMAP) * SIZE (YD%NADMAP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NADMAP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNADCORE = ALLOCATED (YD%NADCORE)
IF (LNADCORE) THEN
  ISIZE = KIND (YD%NADCORE) * SIZE (YD%NADCORE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NADCORE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LLADCORE = ALLOCATED (YD%LADCORE)
IF (LLADCORE) THEN
  ISIZE = KIND (YD%LADCORE) * SIZE (YD%LADCORE)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%LADCORE'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSASIGN = ALLOCATED (YD%RSASIGN)
IF (LRSASIGN) THEN
  ISIZE = KIND (YD%RSASIGN) * SIZE (YD%RSASIGN)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSASIGN'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
