MODULE UTIL_MODEL_GENERAL_CONF_TYPE_MOD

USE MODEL_GENERAL_CONF_MOD, ONLY : MODEL_GENERAL_CONF_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_MODEL_GENERAL_CONF_TYPE
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_GENERAL_CONF_TYPE
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_MODEL_GENERAL_CONF_TYPE
END INTERFACE


CONTAINS

SUBROUTINE SAVE_MODEL_GENERAL_CONF_TYPE (KLUN, YD)
USE UTIL_GEOMETRY_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TECVDIM_MOD
USE UTIL_TMODERR_MOD
USE UTIL_TRIP_MOD
USE UTIL_TSPPT_CONFIG_MOD
USE UTIL_TSPP_CONFIG_MOD
USE UTIL_TYPE_GFLD_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL :: LGEOM
LGEOM = ASSOCIATED (YD%GEOM)
WRITE (KLUN) LGEOM
IF (LGEOM) THEN
  CALL SAVE_GEOMETRY (KLUN, YD%GEOM)
ENDIF
CALL SAVE_TDIMF (KLUN, YD%YRDIMF)
CALL SAVE_TYPE_GFLD (KLUN, YD%YGFL)
CALL SAVE_TRIP (KLUN, YD%YRRIP)
CALL SAVE_TECVDIM (KLUN, YD%YRDIMECV)
CALL SAVE_TMODERR (KLUN, YD%YRMODERR)
CALL SAVE_TSPPT_CONFIG (KLUN, YD%YRSPPT_CONFIG)
CALL SAVE_TSPP_CONFIG (KLUN, YD%YRSPP_CONFIG)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_GENERAL_CONF_TYPE (KLUN, YD)
USE UTIL_GEOMETRY_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TECVDIM_MOD
USE UTIL_TMODERR_MOD
USE UTIL_TRIP_MOD
USE UTIL_TSPPT_CONFIG_MOD
USE UTIL_TSPP_CONFIG_MOD
USE UTIL_TYPE_GFLD_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (OUT), TARGET :: YD
LOGICAL :: LGEOM
READ (KLUN) LGEOM
IF (LGEOM) THEN
  ALLOCATE (YD%GEOM)
  CALL LOAD_GEOMETRY (KLUN, YD%GEOM)
ELSE
  NULLIFY (YD%GEOM)
ENDIF
CALL LOAD_TDIMF (KLUN, YD%YRDIMF)
CALL LOAD_TYPE_GFLD (KLUN, YD%YGFL)
CALL LOAD_TRIP (KLUN, YD%YRRIP)
CALL LOAD_TECVDIM (KLUN, YD%YRDIMECV)
CALL LOAD_TMODERR (KLUN, YD%YRMODERR)
CALL LOAD_TSPPT_CONFIG (KLUN, YD%YRSPPT_CONFIG)
CALL LOAD_TSPP_CONFIG (KLUN, YD%YRSPP_CONFIG)
END SUBROUTINE


SUBROUTINE COPY_MODEL_GENERAL_CONF_TYPE (YD, LDCREATED, LDFIELDAPI)
USE UTIL_GEOMETRY_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TECVDIM_MOD
USE UTIL_TMODERR_MOD
USE UTIL_TRIP_MOD
USE UTIL_TSPPT_CONFIG_MOD
USE UTIL_TSPP_CONFIG_MOD
USE UTIL_TYPE_GFLD_MOD
IMPLICIT NONE
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGEOM

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LGEOM = ASSOCIATED (YD%GEOM)
IF (LGEOM) THEN
  !$ACC ENTER DATA CREATE (YD%GEOM)
  !$ACC UPDATE DEVICE (YD%GEOM)
  CALL COPY_GEOMETRY (YD%GEOM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%GEOM)
ENDIF

CALL COPY_TDIMF (YD%YRDIMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TYPE_GFLD (YD%YGFL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TRIP (YD%YRRIP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TECVDIM (YD%YRDIMECV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TMODERR (YD%YRMODERR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TSPPT_CONFIG (YD%YRSPPT_CONFIG, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TSPP_CONFIG (YD%YRSPP_CONFIG, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

SUBROUTINE HOST_MODEL_GENERAL_CONF_TYPE (YD)
USE UTIL_GEOMETRY_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TECVDIM_MOD
USE UTIL_TMODERR_MOD
USE UTIL_TRIP_MOD
USE UTIL_TSPPT_CONFIG_MOD
USE UTIL_TSPP_CONFIG_MOD
USE UTIL_TYPE_GFLD_MOD

IMPLICIT NONE
TYPE (MODEL_GENERAL_CONF_TYPE), TARGET :: YD
LOGICAL :: LGEOM
LGEOM = ASSOCIATED (YD%GEOM)
IF (LGEOM) THEN
  CALL HOST_GEOMETRY (YD%GEOM)
ENDIF

CALL HOST_TDIMF (YD%YRDIMF)

CALL HOST_TYPE_GFLD (YD%YGFL)

CALL HOST_TRIP (YD%YRRIP)

CALL HOST_TECVDIM (YD%YRDIMECV)

CALL HOST_TMODERR (YD%YRMODERR)

CALL HOST_TSPPT_CONFIG (YD%YRSPPT_CONFIG)

CALL HOST_TSPP_CONFIG (YD%YRSPP_CONFIG)

END SUBROUTINE

     

SUBROUTINE CRC64_MODEL_GENERAL_CONF_TYPE (YD, KLUN, CDPATH)
USE UTIL_GEOMETRY_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TECVDIM_MOD
USE UTIL_TMODERR_MOD
USE UTIL_TRIP_MOD
USE UTIL_TSPPT_CONFIG_MOD
USE UTIL_TSPP_CONFIG_MOD
USE UTIL_TYPE_GFLD_MOD
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (MODEL_GENERAL_CONF_TYPE), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LGEOM
LGEOM = ASSOCIATED (YD%GEOM)
IF (LGEOM) THEN
  CLIND = ''
  CALL CRC64_GEOMETRY (YD%GEOM, KLUN, CDPATH//'%GEOM'//TRIM(CLIND))
ENDIF

CLIND = ''
CALL CRC64_TDIMF (YD%YRDIMF, KLUN, CDPATH//'%YRDIMF'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TYPE_GFLD (YD%YGFL, KLUN, CDPATH//'%YGFL'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TRIP (YD%YRRIP, KLUN, CDPATH//'%YRRIP'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TECVDIM (YD%YRDIMECV, KLUN, CDPATH//'%YRDIMECV'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TMODERR (YD%YRMODERR, KLUN, CDPATH//'%YRMODERR'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TSPPT_CONFIG (YD%YRSPPT_CONFIG, KLUN, CDPATH//'%YRSPPT_CONFIG'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TSPP_CONFIG (YD%YRSPP_CONFIG, KLUN, CDPATH//'%YRSPP_CONFIG'//TRIM(CLIND))

END SUBROUTINE

SUBROUTINE WIPE_MODEL_GENERAL_CONF_TYPE (YD, LDDELETED, LDFIELDAPI)
USE UTIL_GEOMETRY_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TECVDIM_MOD
USE UTIL_TMODERR_MOD
USE UTIL_TRIP_MOD
USE UTIL_TSPPT_CONFIG_MOD
USE UTIL_TSPP_CONFIG_MOD
USE UTIL_TYPE_GFLD_MOD
IMPLICIT NONE
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGEOM

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LGEOM = ASSOCIATED (YD%GEOM)
IF (LGEOM) THEN
  !$ACC EXIT DATA DETACH (YD%GEOM)
  CALL WIPE_GEOMETRY (YD%GEOM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%GEOM)
ENDIF

CALL WIPE_TDIMF (YD%YRDIMF, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TYPE_GFLD (YD%YGFL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TRIP (YD%YRRIP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TECVDIM (YD%YRDIMECV, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TMODERR (YD%YRMODERR, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TSPPT_CONFIG (YD%YRSPPT_CONFIG, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TSPP_CONFIG (YD%YRSPP_CONFIG, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_MODEL_GENERAL_CONF_TYPE (YD, CDPATH, LDPRINT) RESULT (KSIZE)
USE UTIL_GEOMETRY_MOD
USE UTIL_TDIMF_MOD
USE UTIL_TECVDIM_MOD
USE UTIL_TMODERR_MOD
USE UTIL_TRIP_MOD
USE UTIL_TSPPT_CONFIG_MOD
USE UTIL_TSPP_CONFIG_MOD
USE UTIL_TYPE_GFLD_MOD
IMPLICIT NONE
TYPE (MODEL_GENERAL_CONF_TYPE),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LGEOM

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LGEOM = ASSOCIATED (YD%GEOM)
IF (LGEOM) THEN
  JSIZE = 0
  ISIZE = SIZE_GEOMETRY (YD%GEOM, CLPATH//'%GEOM', .FALSE.)
  JSIZE = JSIZE + ISIZE
  KSIZE = KSIZE + ISIZE
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
    WRITE (*, *) TRIM (CLPATH)//'%GEOM'
  ENDIF
ENDIF
JSIZE = 0
ISIZE = SIZE_TDIMF (YD%YRDIMF, CLPATH//'%YRDIMF', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDIMF'
ENDIF
JSIZE = 0
ISIZE = SIZE_TYPE_GFLD (YD%YGFL, CLPATH//'%YGFL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YGFL'
ENDIF
JSIZE = 0
ISIZE = SIZE_TRIP (YD%YRRIP, CLPATH//'%YRRIP', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRRIP'
ENDIF
JSIZE = 0
ISIZE = SIZE_TECVDIM (YD%YRDIMECV, CLPATH//'%YRDIMECV', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDIMECV'
ENDIF
JSIZE = 0
ISIZE = SIZE_TMODERR (YD%YRMODERR, CLPATH//'%YRMODERR', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRMODERR'
ENDIF
JSIZE = 0
ISIZE = SIZE_TSPPT_CONFIG (YD%YRSPPT_CONFIG, CLPATH//'%YRSPPT_CONFIG', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSPPT_CONFIG'
ENDIF
JSIZE = 0
ISIZE = SIZE_TSPP_CONFIG (YD%YRSPP_CONFIG, CLPATH//'%YRSPP_CONFIG', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSPP_CONFIG'
ENDIF
END FUNCTION

END MODULE
