MODULE UTIL_TGSGEOM_BLOCKED_MOD

USE YOMGSGEOM, ONLY : TGSGEOM_BLOCKED

INTERFACE SAVE
MODULE PROCEDURE SAVE_TGSGEOM_BLOCKED
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TGSGEOM_BLOCKED
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TGSGEOM_BLOCKED
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TGSGEOM_BLOCKED
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TGSGEOM_BLOCKED
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TGSGEOM_BLOCKED
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TGSGEOM_BLOCKED
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TGSGEOM_BLOCKED (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGSGEOM_BLOCKED), INTENT (IN), TARGET :: YD
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAMDEG, LGELAMINF, LGELAMSUP, LGELAT, LGEMU, LGESLO, LGEXCO
LOGICAL :: LGEYCO, LGEZCO, LGM, LGMAPPA, LGNORDL, LGNORDLCL, LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL
LOGICAL :: LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC
LRCORI = ASSOCIATED (YD%RCORI)
WRITE (KLUN) LRCORI
IF (LRCORI) THEN
  WRITE (KLUN) LBOUND (YD%RCORI)
  WRITE (KLUN) UBOUND (YD%RCORI)
  WRITE (KLUN) YD%RCORI
ENDIF
LRCORIC = ASSOCIATED (YD%RCORIC)
WRITE (KLUN) LRCORIC
IF (LRCORIC) THEN
  WRITE (KLUN) LBOUND (YD%RCORIC)
  WRITE (KLUN) UBOUND (YD%RCORIC)
  WRITE (KLUN) YD%RCORIC
ENDIF
LGEMU = ASSOCIATED (YD%GEMU)
WRITE (KLUN) LGEMU
IF (LGEMU) THEN
  WRITE (KLUN) LBOUND (YD%GEMU)
  WRITE (KLUN) UBOUND (YD%GEMU)
  WRITE (KLUN) YD%GEMU
ENDIF
LGSQM2 = ASSOCIATED (YD%GSQM2)
WRITE (KLUN) LGSQM2
IF (LGSQM2) THEN
  WRITE (KLUN) LBOUND (YD%GSQM2)
  WRITE (KLUN) UBOUND (YD%GSQM2)
  WRITE (KLUN) YD%GSQM2
ENDIF
LGELAM = ASSOCIATED (YD%GELAM)
WRITE (KLUN) LGELAM
IF (LGELAM) THEN
  WRITE (KLUN) LBOUND (YD%GELAM)
  WRITE (KLUN) UBOUND (YD%GELAM)
  WRITE (KLUN) YD%GELAM
ENDIF
LGELAT = ASSOCIATED (YD%GELAT)
WRITE (KLUN) LGELAT
IF (LGELAT) THEN
  WRITE (KLUN) LBOUND (YD%GELAT)
  WRITE (KLUN) UBOUND (YD%GELAT)
  WRITE (KLUN) YD%GELAT
ENDIF
LGECLO = ASSOCIATED (YD%GECLO)
WRITE (KLUN) LGECLO
IF (LGECLO) THEN
  WRITE (KLUN) LBOUND (YD%GECLO)
  WRITE (KLUN) UBOUND (YD%GECLO)
  WRITE (KLUN) YD%GECLO
ENDIF
LGESLO = ASSOCIATED (YD%GESLO)
WRITE (KLUN) LGESLO
IF (LGESLO) THEN
  WRITE (KLUN) LBOUND (YD%GESLO)
  WRITE (KLUN) UBOUND (YD%GESLO)
  WRITE (KLUN) YD%GESLO
ENDIF
LGELAMDEG = ASSOCIATED (YD%GELAMDEG)
WRITE (KLUN) LGELAMDEG
IF (LGELAMDEG) THEN
  WRITE (KLUN) LBOUND (YD%GELAMDEG)
  WRITE (KLUN) UBOUND (YD%GELAMDEG)
  WRITE (KLUN) YD%GELAMDEG
ENDIF
LGELAMINF = ASSOCIATED (YD%GELAMINF)
WRITE (KLUN) LGELAMINF
IF (LGELAMINF) THEN
  WRITE (KLUN) LBOUND (YD%GELAMINF)
  WRITE (KLUN) UBOUND (YD%GELAMINF)
  WRITE (KLUN) YD%GELAMINF
ENDIF
LGELAMSUP = ASSOCIATED (YD%GELAMSUP)
WRITE (KLUN) LGELAMSUP
IF (LGELAMSUP) THEN
  WRITE (KLUN) LBOUND (YD%GELAMSUP)
  WRITE (KLUN) UBOUND (YD%GELAMSUP)
  WRITE (KLUN) YD%GELAMSUP
ENDIF
LGEXCO = ASSOCIATED (YD%GEXCO)
WRITE (KLUN) LGEXCO
IF (LGEXCO) THEN
  WRITE (KLUN) LBOUND (YD%GEXCO)
  WRITE (KLUN) UBOUND (YD%GEXCO)
  WRITE (KLUN) YD%GEXCO
ENDIF
LGEYCO = ASSOCIATED (YD%GEYCO)
WRITE (KLUN) LGEYCO
IF (LGEYCO) THEN
  WRITE (KLUN) LBOUND (YD%GEYCO)
  WRITE (KLUN) UBOUND (YD%GEYCO)
  WRITE (KLUN) YD%GEYCO
ENDIF
LGEZCO = ASSOCIATED (YD%GEZCO)
WRITE (KLUN) LGEZCO
IF (LGEZCO) THEN
  WRITE (KLUN) LBOUND (YD%GEZCO)
  WRITE (KLUN) UBOUND (YD%GEZCO)
  WRITE (KLUN) YD%GEZCO
ENDIF
LGM = ASSOCIATED (YD%GM)
WRITE (KLUN) LGM
IF (LGM) THEN
  WRITE (KLUN) LBOUND (YD%GM)
  WRITE (KLUN) UBOUND (YD%GM)
  WRITE (KLUN) YD%GM
ENDIF
LGMAPPA = ASSOCIATED (YD%GMAPPA)
WRITE (KLUN) LGMAPPA
IF (LGMAPPA) THEN
  WRITE (KLUN) LBOUND (YD%GMAPPA)
  WRITE (KLUN) UBOUND (YD%GMAPPA)
  WRITE (KLUN) YD%GMAPPA
ENDIF
LGOMVRL = ASSOCIATED (YD%GOMVRL)
WRITE (KLUN) LGOMVRL
IF (LGOMVRL) THEN
  WRITE (KLUN) LBOUND (YD%GOMVRL)
  WRITE (KLUN) UBOUND (YD%GOMVRL)
  WRITE (KLUN) YD%GOMVRL
ENDIF
LGOMVRM = ASSOCIATED (YD%GOMVRM)
WRITE (KLUN) LGOMVRM
IF (LGOMVRM) THEN
  WRITE (KLUN) LBOUND (YD%GOMVRM)
  WRITE (KLUN) UBOUND (YD%GOMVRM)
  WRITE (KLUN) YD%GOMVRM
ENDIF
LGNORDL = ASSOCIATED (YD%GNORDL)
WRITE (KLUN) LGNORDL
IF (LGNORDL) THEN
  WRITE (KLUN) LBOUND (YD%GNORDL)
  WRITE (KLUN) UBOUND (YD%GNORDL)
  WRITE (KLUN) YD%GNORDL
ENDIF
LGNORDM = ASSOCIATED (YD%GNORDM)
WRITE (KLUN) LGNORDM
IF (LGNORDM) THEN
  WRITE (KLUN) LBOUND (YD%GNORDM)
  WRITE (KLUN) UBOUND (YD%GNORDM)
  WRITE (KLUN) YD%GNORDM
ENDIF
LGNORDLCL = ASSOCIATED (YD%GNORDLCL)
WRITE (KLUN) LGNORDLCL
IF (LGNORDLCL) THEN
  WRITE (KLUN) LBOUND (YD%GNORDLCL)
  WRITE (KLUN) UBOUND (YD%GNORDLCL)
  WRITE (KLUN) YD%GNORDLCL
ENDIF
LGNORDMCL = ASSOCIATED (YD%GNORDMCL)
WRITE (KLUN) LGNORDMCL
IF (LGNORDMCL) THEN
  WRITE (KLUN) LBOUND (YD%GNORDMCL)
  WRITE (KLUN) UBOUND (YD%GNORDMCL)
  WRITE (KLUN) YD%GNORDMCL
ENDIF
LGNORDMCM = ASSOCIATED (YD%GNORDMCM)
WRITE (KLUN) LGNORDMCM
IF (LGNORDMCM) THEN
  WRITE (KLUN) LBOUND (YD%GNORDMCM)
  WRITE (KLUN) UBOUND (YD%GNORDMCM)
  WRITE (KLUN) YD%GNORDMCM
ENDIF
LGAW = ASSOCIATED (YD%GAW)
WRITE (KLUN) LGAW
IF (LGAW) THEN
  WRITE (KLUN) LBOUND (YD%GAW)
  WRITE (KLUN) UBOUND (YD%GAW)
  WRITE (KLUN) YD%GAW
ENDIF
LNGPLAT = ASSOCIATED (YD%NGPLAT)
WRITE (KLUN) LNGPLAT
IF (LNGPLAT) THEN
  WRITE (KLUN) LBOUND (YD%NGPLAT)
  WRITE (KLUN) UBOUND (YD%NGPLAT)
  WRITE (KLUN) YD%NGPLAT
ENDIF
LNUNIQUEGP = ASSOCIATED (YD%NUNIQUEGP)
WRITE (KLUN) LNUNIQUEGP
IF (LNUNIQUEGP) THEN
  WRITE (KLUN) LBOUND (YD%NUNIQUEGP)
  WRITE (KLUN) UBOUND (YD%NUNIQUEGP)
  WRITE (KLUN) YD%NUNIQUEGP
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TGSGEOM_BLOCKED (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TGSGEOM_BLOCKED), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAMDEG, LGELAMINF, LGELAMSUP, LGELAT, LGEMU, LGESLO, LGEXCO
LOGICAL :: LGEYCO, LGEZCO, LGM, LGMAPPA, LGNORDL, LGNORDLCL, LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL
LOGICAL :: LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) LRCORI
IF (LRCORI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RCORI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RCORI,1):UBOUND(YD%RCORI,1), LBOUND(YD%RCORI,2):UBOUND(YD%RCORI,2)))
  READ (KLUN) ZTMP2
  YD%RCORI = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%RCORI)
ENDIF
READ (KLUN) LRCORIC
IF (LRCORIC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%RCORIC (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%RCORIC,1):UBOUND(YD%RCORIC,1), LBOUND(YD%RCORIC,2):UBOUND(YD%RCORIC,2)))
  READ (KLUN) ZTMP2
  YD%RCORIC = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%RCORIC)
ENDIF
READ (KLUN) LGEMU
IF (LGEMU) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GEMU (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GEMU,1):UBOUND(YD%GEMU,1), LBOUND(YD%GEMU,2):UBOUND(YD%GEMU,2)))
  READ (KLUN) ZTMP2
  YD%GEMU = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GEMU)
ENDIF
READ (KLUN) LGSQM2
IF (LGSQM2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GSQM2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GSQM2,1):UBOUND(YD%GSQM2,1), LBOUND(YD%GSQM2,2):UBOUND(YD%GSQM2,2)))
  READ (KLUN) ZTMP2
  YD%GSQM2 = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GSQM2)
ENDIF
READ (KLUN) LGELAM
IF (LGELAM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GELAM (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GELAM,1):UBOUND(YD%GELAM,1), LBOUND(YD%GELAM,2):UBOUND(YD%GELAM,2)))
  READ (KLUN) ZTMP2
  YD%GELAM = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GELAM)
ENDIF
READ (KLUN) LGELAT
IF (LGELAT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GELAT (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GELAT,1):UBOUND(YD%GELAT,1), LBOUND(YD%GELAT,2):UBOUND(YD%GELAT,2)))
  READ (KLUN) ZTMP2
  YD%GELAT = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GELAT)
ENDIF
READ (KLUN) LGECLO
IF (LGECLO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GECLO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GECLO,1):UBOUND(YD%GECLO,1), LBOUND(YD%GECLO,2):UBOUND(YD%GECLO,2)))
  READ (KLUN) ZTMP2
  YD%GECLO = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GECLO)
ENDIF
READ (KLUN) LGESLO
IF (LGESLO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GESLO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GESLO,1):UBOUND(YD%GESLO,1), LBOUND(YD%GESLO,2):UBOUND(YD%GESLO,2)))
  READ (KLUN) ZTMP2
  YD%GESLO = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GESLO)
ENDIF
READ (KLUN) LGELAMDEG
IF (LGELAMDEG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GELAMDEG (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GELAMDEG,1):UBOUND(YD%GELAMDEG,1), LBOUND(YD%GELAMDEG,2):UBOUND(YD%GELAMDEG,2)))
  READ (KLUN) ZTMP2
  YD%GELAMDEG = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GELAMDEG)
ENDIF
READ (KLUN) LGELAMINF
IF (LGELAMINF) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GELAMINF (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GELAMINF,1):UBOUND(YD%GELAMINF,1), LBOUND(YD%GELAMINF,2):UBOUND(YD%GELAMINF,2)))
  READ (KLUN) ZTMP2
  YD%GELAMINF = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GELAMINF)
ENDIF
READ (KLUN) LGELAMSUP
IF (LGELAMSUP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GELAMSUP (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GELAMSUP,1):UBOUND(YD%GELAMSUP,1), LBOUND(YD%GELAMSUP,2):UBOUND(YD%GELAMSUP,2)))
  READ (KLUN) ZTMP2
  YD%GELAMSUP = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GELAMSUP)
ENDIF
READ (KLUN) LGEXCO
IF (LGEXCO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GEXCO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GEXCO,1):UBOUND(YD%GEXCO,1), LBOUND(YD%GEXCO,2):UBOUND(YD%GEXCO,2)))
  READ (KLUN) ZTMP2
  YD%GEXCO = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GEXCO)
ENDIF
READ (KLUN) LGEYCO
IF (LGEYCO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GEYCO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GEYCO,1):UBOUND(YD%GEYCO,1), LBOUND(YD%GEYCO,2):UBOUND(YD%GEYCO,2)))
  READ (KLUN) ZTMP2
  YD%GEYCO = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GEYCO)
ENDIF
READ (KLUN) LGEZCO
IF (LGEZCO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GEZCO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GEZCO,1):UBOUND(YD%GEZCO,1), LBOUND(YD%GEZCO,2):UBOUND(YD%GEZCO,2)))
  READ (KLUN) ZTMP2
  YD%GEZCO = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GEZCO)
ENDIF
READ (KLUN) LGM
IF (LGM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GM (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GM,1):UBOUND(YD%GM,1), LBOUND(YD%GM,2):UBOUND(YD%GM,2)))
  READ (KLUN) ZTMP2
  YD%GM = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GM)
ENDIF
READ (KLUN) LGMAPPA
IF (LGMAPPA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GMAPPA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GMAPPA,1):UBOUND(YD%GMAPPA,1), LBOUND(YD%GMAPPA,2):UBOUND(YD%GMAPPA,2)))
  READ (KLUN) ZTMP2
  YD%GMAPPA = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GMAPPA)
ENDIF
READ (KLUN) LGOMVRL
IF (LGOMVRL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GOMVRL (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GOMVRL,1):UBOUND(YD%GOMVRL,1), LBOUND(YD%GOMVRL,2):UBOUND(YD%GOMVRL,2)))
  READ (KLUN) ZTMP2
  YD%GOMVRL = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GOMVRL)
ENDIF
READ (KLUN) LGOMVRM
IF (LGOMVRM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GOMVRM (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GOMVRM,1):UBOUND(YD%GOMVRM,1), LBOUND(YD%GOMVRM,2):UBOUND(YD%GOMVRM,2)))
  READ (KLUN) ZTMP2
  YD%GOMVRM = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GOMVRM)
ENDIF
READ (KLUN) LGNORDL
IF (LGNORDL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GNORDL (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GNORDL,1):UBOUND(YD%GNORDL,1), LBOUND(YD%GNORDL,2):UBOUND(YD%GNORDL,2)))
  READ (KLUN) ZTMP2
  YD%GNORDL = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GNORDL)
ENDIF
READ (KLUN) LGNORDM
IF (LGNORDM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GNORDM (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GNORDM,1):UBOUND(YD%GNORDM,1), LBOUND(YD%GNORDM,2):UBOUND(YD%GNORDM,2)))
  READ (KLUN) ZTMP2
  YD%GNORDM = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GNORDM)
ENDIF
READ (KLUN) LGNORDLCL
IF (LGNORDLCL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GNORDLCL (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GNORDLCL,1):UBOUND(YD%GNORDLCL,1), LBOUND(YD%GNORDLCL,2):UBOUND(YD%GNORDLCL,2)))
  READ (KLUN) ZTMP2
  YD%GNORDLCL = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GNORDLCL)
ENDIF
READ (KLUN) LGNORDMCL
IF (LGNORDMCL) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GNORDMCL (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GNORDMCL,1):UBOUND(YD%GNORDMCL,1), LBOUND(YD%GNORDMCL,2):UBOUND(YD%GNORDMCL,2)))
  READ (KLUN) ZTMP2
  YD%GNORDMCL = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GNORDMCL)
ENDIF
READ (KLUN) LGNORDMCM
IF (LGNORDMCM) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GNORDMCM (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GNORDMCM,1):UBOUND(YD%GNORDMCM,1), LBOUND(YD%GNORDMCM,2):UBOUND(YD%GNORDMCM,2)))
  READ (KLUN) ZTMP2
  YD%GNORDMCM = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GNORDMCM)
ENDIF
READ (KLUN) LGAW
IF (LGAW) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%GAW (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%GAW,1):UBOUND(YD%GAW,1), LBOUND(YD%GAW,2):UBOUND(YD%GAW,2)))
  READ (KLUN) ZTMP2
  YD%GAW = ZTMP2
  DEALLOCATE (ZTMP2)
ELSE
  NULLIFY (YD%GAW)
ENDIF
READ (KLUN) LNGPLAT
IF (LNGPLAT) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NGPLAT (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NGPLAT
ELSE
  NULLIFY (YD%NGPLAT)
ENDIF
READ (KLUN) LNUNIQUEGP
IF (LNUNIQUEGP) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%NUNIQUEGP (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%NUNIQUEGP
ELSE
  NULLIFY (YD%NUNIQUEGP)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TGSGEOM_BLOCKED (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGSGEOM_BLOCKED), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAMDEG, LGELAMINF, LGELAMSUP, LGELAT, LGEMU, LGESLO, LGEXCO
LOGICAL :: LGEYCO, LGEZCO, LGM, LGMAPPA, LGNORDL, LGNORDLCL, LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL
LOGICAL :: LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LRCORI = ASSOCIATED (YD%RCORI)
IF (LRCORI) THEN
  !$ACC ENTER DATA CREATE (YD%RCORI)
  !$ACC UPDATE DEVICE (YD%RCORI)
  !$ACC ENTER DATA ATTACH (YD%RCORI)
ENDIF

LRCORIC = ASSOCIATED (YD%RCORIC)
IF (LRCORIC) THEN
  !$ACC ENTER DATA CREATE (YD%RCORIC)
  !$ACC UPDATE DEVICE (YD%RCORIC)
  !$ACC ENTER DATA ATTACH (YD%RCORIC)
ENDIF

LGEMU = ASSOCIATED (YD%GEMU)
IF (LGEMU) THEN
  !$ACC ENTER DATA CREATE (YD%GEMU)
  !$ACC UPDATE DEVICE (YD%GEMU)
  !$ACC ENTER DATA ATTACH (YD%GEMU)
ENDIF

LGSQM2 = ASSOCIATED (YD%GSQM2)
IF (LGSQM2) THEN
  !$ACC ENTER DATA CREATE (YD%GSQM2)
  !$ACC UPDATE DEVICE (YD%GSQM2)
  !$ACC ENTER DATA ATTACH (YD%GSQM2)
ENDIF

LGELAM = ASSOCIATED (YD%GELAM)
IF (LGELAM) THEN
  !$ACC ENTER DATA CREATE (YD%GELAM)
  !$ACC UPDATE DEVICE (YD%GELAM)
  !$ACC ENTER DATA ATTACH (YD%GELAM)
ENDIF

LGELAT = ASSOCIATED (YD%GELAT)
IF (LGELAT) THEN
  !$ACC ENTER DATA CREATE (YD%GELAT)
  !$ACC UPDATE DEVICE (YD%GELAT)
  !$ACC ENTER DATA ATTACH (YD%GELAT)
ENDIF

LGECLO = ASSOCIATED (YD%GECLO)
IF (LGECLO) THEN
  !$ACC ENTER DATA CREATE (YD%GECLO)
  !$ACC UPDATE DEVICE (YD%GECLO)
  !$ACC ENTER DATA ATTACH (YD%GECLO)
ENDIF

LGESLO = ASSOCIATED (YD%GESLO)
IF (LGESLO) THEN
  !$ACC ENTER DATA CREATE (YD%GESLO)
  !$ACC UPDATE DEVICE (YD%GESLO)
  !$ACC ENTER DATA ATTACH (YD%GESLO)
ENDIF

LGELAMDEG = ASSOCIATED (YD%GELAMDEG)
IF (LGELAMDEG) THEN
  !$ACC ENTER DATA CREATE (YD%GELAMDEG)
  !$ACC UPDATE DEVICE (YD%GELAMDEG)
  !$ACC ENTER DATA ATTACH (YD%GELAMDEG)
ENDIF

LGELAMINF = ASSOCIATED (YD%GELAMINF)
IF (LGELAMINF) THEN
  !$ACC ENTER DATA CREATE (YD%GELAMINF)
  !$ACC UPDATE DEVICE (YD%GELAMINF)
  !$ACC ENTER DATA ATTACH (YD%GELAMINF)
ENDIF

LGELAMSUP = ASSOCIATED (YD%GELAMSUP)
IF (LGELAMSUP) THEN
  !$ACC ENTER DATA CREATE (YD%GELAMSUP)
  !$ACC UPDATE DEVICE (YD%GELAMSUP)
  !$ACC ENTER DATA ATTACH (YD%GELAMSUP)
ENDIF

LGEXCO = ASSOCIATED (YD%GEXCO)
IF (LGEXCO) THEN
  !$ACC ENTER DATA CREATE (YD%GEXCO)
  !$ACC UPDATE DEVICE (YD%GEXCO)
  !$ACC ENTER DATA ATTACH (YD%GEXCO)
ENDIF

LGEYCO = ASSOCIATED (YD%GEYCO)
IF (LGEYCO) THEN
  !$ACC ENTER DATA CREATE (YD%GEYCO)
  !$ACC UPDATE DEVICE (YD%GEYCO)
  !$ACC ENTER DATA ATTACH (YD%GEYCO)
ENDIF

LGEZCO = ASSOCIATED (YD%GEZCO)
IF (LGEZCO) THEN
  !$ACC ENTER DATA CREATE (YD%GEZCO)
  !$ACC UPDATE DEVICE (YD%GEZCO)
  !$ACC ENTER DATA ATTACH (YD%GEZCO)
ENDIF

LGM = ASSOCIATED (YD%GM)
IF (LGM) THEN
  !$ACC ENTER DATA CREATE (YD%GM)
  !$ACC UPDATE DEVICE (YD%GM)
  !$ACC ENTER DATA ATTACH (YD%GM)
ENDIF

LGMAPPA = ASSOCIATED (YD%GMAPPA)
IF (LGMAPPA) THEN
  !$ACC ENTER DATA CREATE (YD%GMAPPA)
  !$ACC UPDATE DEVICE (YD%GMAPPA)
  !$ACC ENTER DATA ATTACH (YD%GMAPPA)
ENDIF

LGOMVRL = ASSOCIATED (YD%GOMVRL)
IF (LGOMVRL) THEN
  !$ACC ENTER DATA CREATE (YD%GOMVRL)
  !$ACC UPDATE DEVICE (YD%GOMVRL)
  !$ACC ENTER DATA ATTACH (YD%GOMVRL)
ENDIF

LGOMVRM = ASSOCIATED (YD%GOMVRM)
IF (LGOMVRM) THEN
  !$ACC ENTER DATA CREATE (YD%GOMVRM)
  !$ACC UPDATE DEVICE (YD%GOMVRM)
  !$ACC ENTER DATA ATTACH (YD%GOMVRM)
ENDIF

LGNORDL = ASSOCIATED (YD%GNORDL)
IF (LGNORDL) THEN
  !$ACC ENTER DATA CREATE (YD%GNORDL)
  !$ACC UPDATE DEVICE (YD%GNORDL)
  !$ACC ENTER DATA ATTACH (YD%GNORDL)
ENDIF

LGNORDM = ASSOCIATED (YD%GNORDM)
IF (LGNORDM) THEN
  !$ACC ENTER DATA CREATE (YD%GNORDM)
  !$ACC UPDATE DEVICE (YD%GNORDM)
  !$ACC ENTER DATA ATTACH (YD%GNORDM)
ENDIF

LGNORDLCL = ASSOCIATED (YD%GNORDLCL)
IF (LGNORDLCL) THEN
  !$ACC ENTER DATA CREATE (YD%GNORDLCL)
  !$ACC UPDATE DEVICE (YD%GNORDLCL)
  !$ACC ENTER DATA ATTACH (YD%GNORDLCL)
ENDIF

LGNORDMCL = ASSOCIATED (YD%GNORDMCL)
IF (LGNORDMCL) THEN
  !$ACC ENTER DATA CREATE (YD%GNORDMCL)
  !$ACC UPDATE DEVICE (YD%GNORDMCL)
  !$ACC ENTER DATA ATTACH (YD%GNORDMCL)
ENDIF

LGNORDMCM = ASSOCIATED (YD%GNORDMCM)
IF (LGNORDMCM) THEN
  !$ACC ENTER DATA CREATE (YD%GNORDMCM)
  !$ACC UPDATE DEVICE (YD%GNORDMCM)
  !$ACC ENTER DATA ATTACH (YD%GNORDMCM)
ENDIF

LGAW = ASSOCIATED (YD%GAW)
IF (LGAW) THEN
  !$ACC ENTER DATA CREATE (YD%GAW)
  !$ACC UPDATE DEVICE (YD%GAW)
  !$ACC ENTER DATA ATTACH (YD%GAW)
ENDIF

LNGPLAT = ASSOCIATED (YD%NGPLAT)
IF (LNGPLAT) THEN
  !$ACC ENTER DATA CREATE (YD%NGPLAT)
  !$ACC UPDATE DEVICE (YD%NGPLAT)
  !$ACC ENTER DATA ATTACH (YD%NGPLAT)
ENDIF

LNUNIQUEGP = ASSOCIATED (YD%NUNIQUEGP)
IF (LNUNIQUEGP) THEN
  !$ACC ENTER DATA CREATE (YD%NUNIQUEGP)
  !$ACC UPDATE DEVICE (YD%NUNIQUEGP)
  !$ACC ENTER DATA ATTACH (YD%NUNIQUEGP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TGSGEOM_BLOCKED (YD)

IMPLICIT NONE
TYPE (TGSGEOM_BLOCKED), TARGET :: YD
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAMDEG, LGELAMINF, LGELAMSUP, LGELAT, LGEMU, LGESLO, LGEXCO
LOGICAL :: LGEYCO, LGEZCO, LGM, LGMAPPA, LGNORDL, LGNORDLCL, LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL
LOGICAL :: LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC


























END SUBROUTINE

     

SUBROUTINE CRC64_TGSGEOM_BLOCKED (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TGSGEOM_BLOCKED), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAMDEG, LGELAMINF, LGELAMSUP, LGELAT, LGEMU, LGESLO, LGEXCO
LOGICAL :: LGEYCO, LGEZCO, LGM, LGMAPPA, LGNORDL, LGNORDLCL, LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL
LOGICAL :: LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RCORI), CDPATH//'%RCORI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RCORIC), CDPATH//'%RCORIC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GEMU), CDPATH//'%GEMU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GSQM2), CDPATH//'%GSQM2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GELAM), CDPATH//'%GELAM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GELAT), CDPATH//'%GELAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GECLO), CDPATH//'%GECLO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GESLO), CDPATH//'%GESLO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GELAMDEG), CDPATH//'%GELAMDEG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GELAMINF), CDPATH//'%GELAMINF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GELAMSUP), CDPATH//'%GELAMSUP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GEXCO), CDPATH//'%GEXCO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GEYCO), CDPATH//'%GEYCO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GEZCO), CDPATH//'%GEZCO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GM), CDPATH//'%GM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GMAPPA), CDPATH//'%GMAPPA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GOMVRL), CDPATH//'%GOMVRL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GOMVRM), CDPATH//'%GOMVRM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GNORDL), CDPATH//'%GNORDL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GNORDM), CDPATH//'%GNORDM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GNORDLCL), CDPATH//'%GNORDLCL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GNORDMCL), CDPATH//'%GNORDMCL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GNORDMCM), CDPATH//'%GNORDMCM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%GAW), CDPATH//'%GAW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGPLAT), CDPATH//'%NGPLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NUNIQUEGP), CDPATH//'%NUNIQUEGP'

END SUBROUTINE

SUBROUTINE WIPE_TGSGEOM_BLOCKED (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TGSGEOM_BLOCKED), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAMDEG, LGELAMINF, LGELAMSUP, LGELAT, LGEMU, LGESLO, LGEXCO
LOGICAL :: LGEYCO, LGEZCO, LGM, LGMAPPA, LGNORDL, LGNORDLCL, LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL
LOGICAL :: LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LRCORI = ASSOCIATED (YD%RCORI)
IF (LRCORI) THEN
  !$ACC EXIT DATA DETACH (YD%RCORI)
  !$ACC EXIT DATA DETACH (YD%RCORI)
ENDIF

LRCORIC = ASSOCIATED (YD%RCORIC)
IF (LRCORIC) THEN
  !$ACC EXIT DATA DETACH (YD%RCORIC)
  !$ACC EXIT DATA DETACH (YD%RCORIC)
ENDIF

LGEMU = ASSOCIATED (YD%GEMU)
IF (LGEMU) THEN
  !$ACC EXIT DATA DETACH (YD%GEMU)
  !$ACC EXIT DATA DETACH (YD%GEMU)
ENDIF

LGSQM2 = ASSOCIATED (YD%GSQM2)
IF (LGSQM2) THEN
  !$ACC EXIT DATA DETACH (YD%GSQM2)
  !$ACC EXIT DATA DETACH (YD%GSQM2)
ENDIF

LGELAM = ASSOCIATED (YD%GELAM)
IF (LGELAM) THEN
  !$ACC EXIT DATA DETACH (YD%GELAM)
  !$ACC EXIT DATA DETACH (YD%GELAM)
ENDIF

LGELAT = ASSOCIATED (YD%GELAT)
IF (LGELAT) THEN
  !$ACC EXIT DATA DETACH (YD%GELAT)
  !$ACC EXIT DATA DETACH (YD%GELAT)
ENDIF

LGECLO = ASSOCIATED (YD%GECLO)
IF (LGECLO) THEN
  !$ACC EXIT DATA DETACH (YD%GECLO)
  !$ACC EXIT DATA DETACH (YD%GECLO)
ENDIF

LGESLO = ASSOCIATED (YD%GESLO)
IF (LGESLO) THEN
  !$ACC EXIT DATA DETACH (YD%GESLO)
  !$ACC EXIT DATA DETACH (YD%GESLO)
ENDIF

LGELAMDEG = ASSOCIATED (YD%GELAMDEG)
IF (LGELAMDEG) THEN
  !$ACC EXIT DATA DETACH (YD%GELAMDEG)
  !$ACC EXIT DATA DETACH (YD%GELAMDEG)
ENDIF

LGELAMINF = ASSOCIATED (YD%GELAMINF)
IF (LGELAMINF) THEN
  !$ACC EXIT DATA DETACH (YD%GELAMINF)
  !$ACC EXIT DATA DETACH (YD%GELAMINF)
ENDIF

LGELAMSUP = ASSOCIATED (YD%GELAMSUP)
IF (LGELAMSUP) THEN
  !$ACC EXIT DATA DETACH (YD%GELAMSUP)
  !$ACC EXIT DATA DETACH (YD%GELAMSUP)
ENDIF

LGEXCO = ASSOCIATED (YD%GEXCO)
IF (LGEXCO) THEN
  !$ACC EXIT DATA DETACH (YD%GEXCO)
  !$ACC EXIT DATA DETACH (YD%GEXCO)
ENDIF

LGEYCO = ASSOCIATED (YD%GEYCO)
IF (LGEYCO) THEN
  !$ACC EXIT DATA DETACH (YD%GEYCO)
  !$ACC EXIT DATA DETACH (YD%GEYCO)
ENDIF

LGEZCO = ASSOCIATED (YD%GEZCO)
IF (LGEZCO) THEN
  !$ACC EXIT DATA DETACH (YD%GEZCO)
  !$ACC EXIT DATA DETACH (YD%GEZCO)
ENDIF

LGM = ASSOCIATED (YD%GM)
IF (LGM) THEN
  !$ACC EXIT DATA DETACH (YD%GM)
  !$ACC EXIT DATA DETACH (YD%GM)
ENDIF

LGMAPPA = ASSOCIATED (YD%GMAPPA)
IF (LGMAPPA) THEN
  !$ACC EXIT DATA DETACH (YD%GMAPPA)
  !$ACC EXIT DATA DETACH (YD%GMAPPA)
ENDIF

LGOMVRL = ASSOCIATED (YD%GOMVRL)
IF (LGOMVRL) THEN
  !$ACC EXIT DATA DETACH (YD%GOMVRL)
  !$ACC EXIT DATA DETACH (YD%GOMVRL)
ENDIF

LGOMVRM = ASSOCIATED (YD%GOMVRM)
IF (LGOMVRM) THEN
  !$ACC EXIT DATA DETACH (YD%GOMVRM)
  !$ACC EXIT DATA DETACH (YD%GOMVRM)
ENDIF

LGNORDL = ASSOCIATED (YD%GNORDL)
IF (LGNORDL) THEN
  !$ACC EXIT DATA DETACH (YD%GNORDL)
  !$ACC EXIT DATA DETACH (YD%GNORDL)
ENDIF

LGNORDM = ASSOCIATED (YD%GNORDM)
IF (LGNORDM) THEN
  !$ACC EXIT DATA DETACH (YD%GNORDM)
  !$ACC EXIT DATA DETACH (YD%GNORDM)
ENDIF

LGNORDLCL = ASSOCIATED (YD%GNORDLCL)
IF (LGNORDLCL) THEN
  !$ACC EXIT DATA DETACH (YD%GNORDLCL)
  !$ACC EXIT DATA DETACH (YD%GNORDLCL)
ENDIF

LGNORDMCL = ASSOCIATED (YD%GNORDMCL)
IF (LGNORDMCL) THEN
  !$ACC EXIT DATA DETACH (YD%GNORDMCL)
  !$ACC EXIT DATA DETACH (YD%GNORDMCL)
ENDIF

LGNORDMCM = ASSOCIATED (YD%GNORDMCM)
IF (LGNORDMCM) THEN
  !$ACC EXIT DATA DETACH (YD%GNORDMCM)
  !$ACC EXIT DATA DETACH (YD%GNORDMCM)
ENDIF

LGAW = ASSOCIATED (YD%GAW)
IF (LGAW) THEN
  !$ACC EXIT DATA DETACH (YD%GAW)
  !$ACC EXIT DATA DETACH (YD%GAW)
ENDIF

LNGPLAT = ASSOCIATED (YD%NGPLAT)
IF (LNGPLAT) THEN
  !$ACC EXIT DATA DETACH (YD%NGPLAT)
  !$ACC EXIT DATA DETACH (YD%NGPLAT)
ENDIF

LNUNIQUEGP = ASSOCIATED (YD%NUNIQUEGP)
IF (LNUNIQUEGP) THEN
  !$ACC EXIT DATA DETACH (YD%NUNIQUEGP)
  !$ACC EXIT DATA DETACH (YD%NUNIQUEGP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TGSGEOM_BLOCKED (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TGSGEOM_BLOCKED),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LGAW, LGECLO, LGELAM, LGELAMDEG, LGELAMINF, LGELAMSUP, LGELAT, LGEMU, LGESLO, LGEXCO
LOGICAL :: LGEYCO, LGEZCO, LGM, LGMAPPA, LGNORDL, LGNORDLCL, LGNORDM, LGNORDMCL, LGNORDMCM, LGOMVRL
LOGICAL :: LGOMVRM, LGSQM2, LNGPLAT, LNUNIQUEGP, LRCORI, LRCORIC

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LRCORI = ASSOCIATED (YD%RCORI)
IF (LRCORI) THEN
  ISIZE = KIND (YD%RCORI) * SIZE (YD%RCORI)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RCORI'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRCORIC = ASSOCIATED (YD%RCORIC)
IF (LRCORIC) THEN
  ISIZE = KIND (YD%RCORIC) * SIZE (YD%RCORIC)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RCORIC'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGEMU = ASSOCIATED (YD%GEMU)
IF (LGEMU) THEN
  ISIZE = KIND (YD%GEMU) * SIZE (YD%GEMU)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GEMU'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGSQM2 = ASSOCIATED (YD%GSQM2)
IF (LGSQM2) THEN
  ISIZE = KIND (YD%GSQM2) * SIZE (YD%GSQM2)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GSQM2'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGELAM = ASSOCIATED (YD%GELAM)
IF (LGELAM) THEN
  ISIZE = KIND (YD%GELAM) * SIZE (YD%GELAM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GELAM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGELAT = ASSOCIATED (YD%GELAT)
IF (LGELAT) THEN
  ISIZE = KIND (YD%GELAT) * SIZE (YD%GELAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GELAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGECLO = ASSOCIATED (YD%GECLO)
IF (LGECLO) THEN
  ISIZE = KIND (YD%GECLO) * SIZE (YD%GECLO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GECLO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGESLO = ASSOCIATED (YD%GESLO)
IF (LGESLO) THEN
  ISIZE = KIND (YD%GESLO) * SIZE (YD%GESLO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GESLO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGELAMDEG = ASSOCIATED (YD%GELAMDEG)
IF (LGELAMDEG) THEN
  ISIZE = KIND (YD%GELAMDEG) * SIZE (YD%GELAMDEG)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GELAMDEG'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGELAMINF = ASSOCIATED (YD%GELAMINF)
IF (LGELAMINF) THEN
  ISIZE = KIND (YD%GELAMINF) * SIZE (YD%GELAMINF)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GELAMINF'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGELAMSUP = ASSOCIATED (YD%GELAMSUP)
IF (LGELAMSUP) THEN
  ISIZE = KIND (YD%GELAMSUP) * SIZE (YD%GELAMSUP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GELAMSUP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGEXCO = ASSOCIATED (YD%GEXCO)
IF (LGEXCO) THEN
  ISIZE = KIND (YD%GEXCO) * SIZE (YD%GEXCO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GEXCO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGEYCO = ASSOCIATED (YD%GEYCO)
IF (LGEYCO) THEN
  ISIZE = KIND (YD%GEYCO) * SIZE (YD%GEYCO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GEYCO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGEZCO = ASSOCIATED (YD%GEZCO)
IF (LGEZCO) THEN
  ISIZE = KIND (YD%GEZCO) * SIZE (YD%GEZCO)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GEZCO'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGM = ASSOCIATED (YD%GM)
IF (LGM) THEN
  ISIZE = KIND (YD%GM) * SIZE (YD%GM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGMAPPA = ASSOCIATED (YD%GMAPPA)
IF (LGMAPPA) THEN
  ISIZE = KIND (YD%GMAPPA) * SIZE (YD%GMAPPA)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GMAPPA'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGOMVRL = ASSOCIATED (YD%GOMVRL)
IF (LGOMVRL) THEN
  ISIZE = KIND (YD%GOMVRL) * SIZE (YD%GOMVRL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GOMVRL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGOMVRM = ASSOCIATED (YD%GOMVRM)
IF (LGOMVRM) THEN
  ISIZE = KIND (YD%GOMVRM) * SIZE (YD%GOMVRM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GOMVRM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGNORDL = ASSOCIATED (YD%GNORDL)
IF (LGNORDL) THEN
  ISIZE = KIND (YD%GNORDL) * SIZE (YD%GNORDL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GNORDL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGNORDM = ASSOCIATED (YD%GNORDM)
IF (LGNORDM) THEN
  ISIZE = KIND (YD%GNORDM) * SIZE (YD%GNORDM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GNORDM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGNORDLCL = ASSOCIATED (YD%GNORDLCL)
IF (LGNORDLCL) THEN
  ISIZE = KIND (YD%GNORDLCL) * SIZE (YD%GNORDLCL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GNORDLCL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGNORDMCL = ASSOCIATED (YD%GNORDMCL)
IF (LGNORDMCL) THEN
  ISIZE = KIND (YD%GNORDMCL) * SIZE (YD%GNORDMCL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GNORDMCL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGNORDMCM = ASSOCIATED (YD%GNORDMCM)
IF (LGNORDMCM) THEN
  ISIZE = KIND (YD%GNORDMCM) * SIZE (YD%GNORDMCM)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GNORDMCM'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGAW = ASSOCIATED (YD%GAW)
IF (LGAW) THEN
  ISIZE = KIND (YD%GAW) * SIZE (YD%GAW)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GAW'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNGPLAT = ASSOCIATED (YD%NGPLAT)
IF (LNGPLAT) THEN
  ISIZE = KIND (YD%NGPLAT) * SIZE (YD%NGPLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NGPLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNUNIQUEGP = ASSOCIATED (YD%NUNIQUEGP)
IF (LNUNIQUEGP) THEN
  ISIZE = KIND (YD%NUNIQUEGP) * SIZE (YD%NUNIQUEGP)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NUNIQUEGP'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
