MODULE UTIL_SURFACE_VIEW_GROUP_LAKEB_MOD

USE SURFACE_VIEWS_PROGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_LAKEB



INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VIEW_GROUP_LAKEB
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_SURFACE_VIEW_GROUP_LAKEB
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VIEW_GROUP_LAKEB
END INTERFACE



CONTAINS





SUBROUTINE COPY_SURFACE_VIEW_GROUP_LAKEB (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_LAKEB_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_LAKEB), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP, LF_LBLT_T0, LF_LBLT_T1, LF_LBLT_T9, LF_LICD_T0, LF_LICD_T1, LF_LICD_T9, LF_LICT_T0, LF_LICT_T1, LF_LICT_T9
LOGICAL :: LF_LMLD_T0, LF_LMLD_T1, LF_LMLD_T9, LF_LMLT_T0, LF_LMLT_T1, LF_LMLT_T9, LF_LSHF_T0, LF_LSHF_T1, LF_LSHF_T9, LF_LTLT_T0
LOGICAL :: LF_LTLT_T1, LF_LTLT_T9, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC ENTER DATA CREATE (YD%VARIABLE_GROUP)
  !$ACC UPDATE DEVICE (YD%VARIABLE_GROUP)
  CALL COPY_SURFACE_VARIABLE_GROUP_LAKEB (YD%VARIABLE_GROUP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%VARIABLE_GROUP)
ENDIF

LF_LICT_T0 = ASSOCIATED (YD%F_LICT_T0)
IF (LF_LICT_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LICT_T0)
  !$ACC ENTER DATA ATTACH (YD%F_LICT_T0)
ENDIF

LF_LICT_T1 = ASSOCIATED (YD%F_LICT_T1)
IF (LF_LICT_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LICT_T1)
  !$ACC ENTER DATA ATTACH (YD%F_LICT_T1)
ENDIF

LF_LICT_T9 = ASSOCIATED (YD%F_LICT_T9)
IF (LF_LICT_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LICT_T9)
  !$ACC ENTER DATA ATTACH (YD%F_LICT_T9)
ENDIF

LF_LMLT_T0 = ASSOCIATED (YD%F_LMLT_T0)
IF (LF_LMLT_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LMLT_T0)
  !$ACC ENTER DATA ATTACH (YD%F_LMLT_T0)
ENDIF

LF_LMLT_T1 = ASSOCIATED (YD%F_LMLT_T1)
IF (LF_LMLT_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LMLT_T1)
  !$ACC ENTER DATA ATTACH (YD%F_LMLT_T1)
ENDIF

LF_LMLT_T9 = ASSOCIATED (YD%F_LMLT_T9)
IF (LF_LMLT_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LMLT_T9)
  !$ACC ENTER DATA ATTACH (YD%F_LMLT_T9)
ENDIF

LF_LTLT_T0 = ASSOCIATED (YD%F_LTLT_T0)
IF (LF_LTLT_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LTLT_T0)
  !$ACC ENTER DATA ATTACH (YD%F_LTLT_T0)
ENDIF

LF_LTLT_T1 = ASSOCIATED (YD%F_LTLT_T1)
IF (LF_LTLT_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LTLT_T1)
  !$ACC ENTER DATA ATTACH (YD%F_LTLT_T1)
ENDIF

LF_LTLT_T9 = ASSOCIATED (YD%F_LTLT_T9)
IF (LF_LTLT_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LTLT_T9)
  !$ACC ENTER DATA ATTACH (YD%F_LTLT_T9)
ENDIF

LF_LBLT_T0 = ASSOCIATED (YD%F_LBLT_T0)
IF (LF_LBLT_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LBLT_T0)
  !$ACC ENTER DATA ATTACH (YD%F_LBLT_T0)
ENDIF

LF_LBLT_T1 = ASSOCIATED (YD%F_LBLT_T1)
IF (LF_LBLT_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LBLT_T1)
  !$ACC ENTER DATA ATTACH (YD%F_LBLT_T1)
ENDIF

LF_LBLT_T9 = ASSOCIATED (YD%F_LBLT_T9)
IF (LF_LBLT_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LBLT_T9)
  !$ACC ENTER DATA ATTACH (YD%F_LBLT_T9)
ENDIF

LF_LSHF_T0 = ASSOCIATED (YD%F_LSHF_T0)
IF (LF_LSHF_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LSHF_T0)
  !$ACC ENTER DATA ATTACH (YD%F_LSHF_T0)
ENDIF

LF_LSHF_T1 = ASSOCIATED (YD%F_LSHF_T1)
IF (LF_LSHF_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LSHF_T1)
  !$ACC ENTER DATA ATTACH (YD%F_LSHF_T1)
ENDIF

LF_LSHF_T9 = ASSOCIATED (YD%F_LSHF_T9)
IF (LF_LSHF_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LSHF_T9)
  !$ACC ENTER DATA ATTACH (YD%F_LSHF_T9)
ENDIF

LF_LICD_T0 = ASSOCIATED (YD%F_LICD_T0)
IF (LF_LICD_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LICD_T0)
  !$ACC ENTER DATA ATTACH (YD%F_LICD_T0)
ENDIF

LF_LICD_T1 = ASSOCIATED (YD%F_LICD_T1)
IF (LF_LICD_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LICD_T1)
  !$ACC ENTER DATA ATTACH (YD%F_LICD_T1)
ENDIF

LF_LICD_T9 = ASSOCIATED (YD%F_LICD_T9)
IF (LF_LICD_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LICD_T9)
  !$ACC ENTER DATA ATTACH (YD%F_LICD_T9)
ENDIF

LF_LMLD_T0 = ASSOCIATED (YD%F_LMLD_T0)
IF (LF_LMLD_T0 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LMLD_T0)
  !$ACC ENTER DATA ATTACH (YD%F_LMLD_T0)
ENDIF

LF_LMLD_T1 = ASSOCIATED (YD%F_LMLD_T1)
IF (LF_LMLD_T1 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LMLD_T1)
  !$ACC ENTER DATA ATTACH (YD%F_LMLD_T1)
ENDIF

LF_LMLD_T9 = ASSOCIATED (YD%F_LMLD_T9)
IF (LF_LMLD_T9 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_LMLD_T9)
  !$ACC ENTER DATA ATTACH (YD%F_LMLD_T9)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_GROUP)
  !$ACC ENTER DATA ATTACH (YD%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_SURFACE_VIEW_GROUP_LAKEB (YD)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_LAKEB_MOD

IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_LAKEB), TARGET :: YD
LOGICAL :: LF_GROUP, LF_LBLT_T0, LF_LBLT_T1, LF_LBLT_T9, LF_LICD_T0, LF_LICD_T1, LF_LICD_T9, LF_LICT_T0, LF_LICT_T1, LF_LICT_T9
LOGICAL :: LF_LMLD_T0, LF_LMLD_T1, LF_LMLD_T9, LF_LMLT_T0, LF_LMLT_T1, LF_LMLT_T9, LF_LSHF_T0, LF_LSHF_T1, LF_LSHF_T9, LF_LTLT_T0
LOGICAL :: LF_LTLT_T1, LF_LTLT_T9, LVARIABLE_GROUP
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  CALL HOST_SURFACE_VARIABLE_GROUP_LAKEB (YD%VARIABLE_GROUP)
ENDIF

LF_LICT_T0 = ASSOCIATED (YD%F_LICT_T0)
IF (LF_LICT_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_LICT_T0)
ENDIF

LF_LICT_T1 = ASSOCIATED (YD%F_LICT_T1)
IF (LF_LICT_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_LICT_T1)
ENDIF

LF_LICT_T9 = ASSOCIATED (YD%F_LICT_T9)
IF (LF_LICT_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_LICT_T9)
ENDIF

LF_LMLT_T0 = ASSOCIATED (YD%F_LMLT_T0)
IF (LF_LMLT_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_LMLT_T0)
ENDIF

LF_LMLT_T1 = ASSOCIATED (YD%F_LMLT_T1)
IF (LF_LMLT_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_LMLT_T1)
ENDIF

LF_LMLT_T9 = ASSOCIATED (YD%F_LMLT_T9)
IF (LF_LMLT_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_LMLT_T9)
ENDIF

LF_LTLT_T0 = ASSOCIATED (YD%F_LTLT_T0)
IF (LF_LTLT_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_LTLT_T0)
ENDIF

LF_LTLT_T1 = ASSOCIATED (YD%F_LTLT_T1)
IF (LF_LTLT_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_LTLT_T1)
ENDIF

LF_LTLT_T9 = ASSOCIATED (YD%F_LTLT_T9)
IF (LF_LTLT_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_LTLT_T9)
ENDIF

LF_LBLT_T0 = ASSOCIATED (YD%F_LBLT_T0)
IF (LF_LBLT_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_LBLT_T0)
ENDIF

LF_LBLT_T1 = ASSOCIATED (YD%F_LBLT_T1)
IF (LF_LBLT_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_LBLT_T1)
ENDIF

LF_LBLT_T9 = ASSOCIATED (YD%F_LBLT_T9)
IF (LF_LBLT_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_LBLT_T9)
ENDIF

LF_LSHF_T0 = ASSOCIATED (YD%F_LSHF_T0)
IF (LF_LSHF_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_LSHF_T0)
ENDIF

LF_LSHF_T1 = ASSOCIATED (YD%F_LSHF_T1)
IF (LF_LSHF_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_LSHF_T1)
ENDIF

LF_LSHF_T9 = ASSOCIATED (YD%F_LSHF_T9)
IF (LF_LSHF_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_LSHF_T9)
ENDIF

LF_LICD_T0 = ASSOCIATED (YD%F_LICD_T0)
IF (LF_LICD_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_LICD_T0)
ENDIF

LF_LICD_T1 = ASSOCIATED (YD%F_LICD_T1)
IF (LF_LICD_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_LICD_T1)
ENDIF

LF_LICD_T9 = ASSOCIATED (YD%F_LICD_T9)
IF (LF_LICD_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_LICD_T9)
ENDIF

LF_LMLD_T0 = ASSOCIATED (YD%F_LMLD_T0)
IF (LF_LMLD_T0) THEN
  CALL HOST_FIELD_2RB (YD%F_LMLD_T0)
ENDIF

LF_LMLD_T1 = ASSOCIATED (YD%F_LMLD_T1)
IF (LF_LMLD_T1) THEN
  CALL HOST_FIELD_2RB (YD%F_LMLD_T1)
ENDIF

LF_LMLD_T9 = ASSOCIATED (YD%F_LMLD_T9)
IF (LF_LMLD_T9) THEN
  CALL HOST_FIELD_2RB (YD%F_LMLD_T9)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (YD%F_GROUP)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_SURFACE_VIEW_GROUP_LAKEB (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_LAKEB_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_LAKEB), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP, LF_LBLT_T0, LF_LBLT_T1, LF_LBLT_T9, LF_LICD_T0, LF_LICD_T1, LF_LICD_T9, LF_LICT_T0, LF_LICT_T1, LF_LICT_T9
LOGICAL :: LF_LMLD_T0, LF_LMLD_T1, LF_LMLD_T9, LF_LMLT_T0, LF_LMLT_T1, LF_LMLT_T9, LF_LSHF_T0, LF_LSHF_T1, LF_LSHF_T9, LF_LTLT_T0
LOGICAL :: LF_LTLT_T1, LF_LTLT_T9, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
  CALL WIPE_SURFACE_VARIABLE_GROUP_LAKEB (YD%VARIABLE_GROUP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
ENDIF

LF_LICT_T0 = ASSOCIATED (YD%F_LICT_T0)
IF (LF_LICT_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LICT_T0)
ENDIF

LF_LICT_T1 = ASSOCIATED (YD%F_LICT_T1)
IF (LF_LICT_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LICT_T1)
ENDIF

LF_LICT_T9 = ASSOCIATED (YD%F_LICT_T9)
IF (LF_LICT_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LICT_T9)
ENDIF

LF_LMLT_T0 = ASSOCIATED (YD%F_LMLT_T0)
IF (LF_LMLT_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LMLT_T0)
ENDIF

LF_LMLT_T1 = ASSOCIATED (YD%F_LMLT_T1)
IF (LF_LMLT_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LMLT_T1)
ENDIF

LF_LMLT_T9 = ASSOCIATED (YD%F_LMLT_T9)
IF (LF_LMLT_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LMLT_T9)
ENDIF

LF_LTLT_T0 = ASSOCIATED (YD%F_LTLT_T0)
IF (LF_LTLT_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LTLT_T0)
ENDIF

LF_LTLT_T1 = ASSOCIATED (YD%F_LTLT_T1)
IF (LF_LTLT_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LTLT_T1)
ENDIF

LF_LTLT_T9 = ASSOCIATED (YD%F_LTLT_T9)
IF (LF_LTLT_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LTLT_T9)
ENDIF

LF_LBLT_T0 = ASSOCIATED (YD%F_LBLT_T0)
IF (LF_LBLT_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LBLT_T0)
ENDIF

LF_LBLT_T1 = ASSOCIATED (YD%F_LBLT_T1)
IF (LF_LBLT_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LBLT_T1)
ENDIF

LF_LBLT_T9 = ASSOCIATED (YD%F_LBLT_T9)
IF (LF_LBLT_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LBLT_T9)
ENDIF

LF_LSHF_T0 = ASSOCIATED (YD%F_LSHF_T0)
IF (LF_LSHF_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LSHF_T0)
ENDIF

LF_LSHF_T1 = ASSOCIATED (YD%F_LSHF_T1)
IF (LF_LSHF_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LSHF_T1)
ENDIF

LF_LSHF_T9 = ASSOCIATED (YD%F_LSHF_T9)
IF (LF_LSHF_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LSHF_T9)
ENDIF

LF_LICD_T0 = ASSOCIATED (YD%F_LICD_T0)
IF (LF_LICD_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LICD_T0)
ENDIF

LF_LICD_T1 = ASSOCIATED (YD%F_LICD_T1)
IF (LF_LICD_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LICD_T1)
ENDIF

LF_LICD_T9 = ASSOCIATED (YD%F_LICD_T9)
IF (LF_LICD_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LICD_T9)
ENDIF

LF_LMLD_T0 = ASSOCIATED (YD%F_LMLD_T0)
IF (LF_LMLD_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LMLD_T0)
ENDIF

LF_LMLD_T1 = ASSOCIATED (YD%F_LMLD_T1)
IF (LF_LMLD_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LMLD_T1)
ENDIF

LF_LMLD_T9 = ASSOCIATED (YD%F_LMLD_T9)
IF (LF_LMLD_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_LMLD_T9)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
