MODULE UTIL_SURFACE_VIEW_GROUP_WAVES_MOD

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE, ONLY : SURFACE_VIEW_GROUP_WAVES



INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VIEW_GROUP_WAVES
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_SURFACE_VIEW_GROUP_WAVES
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VIEW_GROUP_WAVES
END INTERFACE



CONTAINS





SUBROUTINE COPY_SURFACE_VIEW_GROUP_WAVES (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_WAVES_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_WAVES), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_CHAR, LF_CHARHQ, LF_GROUP, LF_PHIOC, LF_TAUOCX, LF_TAUOCY, LF_USTOKES, LF_VSTOKES, LF_WSEMEAN, LF_WSFMEAN
LOGICAL :: LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC ENTER DATA CREATE (YD%VARIABLE_GROUP)
  !$ACC UPDATE DEVICE (YD%VARIABLE_GROUP)
  CALL COPY_SURFACE_VARIABLE_GROUP_WAVES (YD%VARIABLE_GROUP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC ENTER DATA ATTACH (YD%VARIABLE_GROUP)
ENDIF

LF_CHAR = ASSOCIATED (YD%F_CHAR)
IF (LF_CHAR .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_CHAR)
  !$ACC ENTER DATA ATTACH (YD%F_CHAR)
ENDIF

LF_CHARHQ = ASSOCIATED (YD%F_CHARHQ)
IF (LF_CHARHQ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_CHARHQ)
  !$ACC ENTER DATA ATTACH (YD%F_CHARHQ)
ENDIF

LF_USTOKES = ASSOCIATED (YD%F_USTOKES)
IF (LF_USTOKES .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_USTOKES)
  !$ACC ENTER DATA ATTACH (YD%F_USTOKES)
ENDIF

LF_VSTOKES = ASSOCIATED (YD%F_VSTOKES)
IF (LF_VSTOKES .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_VSTOKES)
  !$ACC ENTER DATA ATTACH (YD%F_VSTOKES)
ENDIF

LF_TAUOCX = ASSOCIATED (YD%F_TAUOCX)
IF (LF_TAUOCX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_TAUOCX)
  !$ACC ENTER DATA ATTACH (YD%F_TAUOCX)
ENDIF

LF_TAUOCY = ASSOCIATED (YD%F_TAUOCY)
IF (LF_TAUOCY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_TAUOCY)
  !$ACC ENTER DATA ATTACH (YD%F_TAUOCY)
ENDIF

LF_PHIOC = ASSOCIATED (YD%F_PHIOC)
IF (LF_PHIOC .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_PHIOC)
  !$ACC ENTER DATA ATTACH (YD%F_PHIOC)
ENDIF

LF_WSEMEAN = ASSOCIATED (YD%F_WSEMEAN)
IF (LF_WSEMEAN .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_WSEMEAN)
  !$ACC ENTER DATA ATTACH (YD%F_WSEMEAN)
ENDIF

LF_WSFMEAN = ASSOCIATED (YD%F_WSFMEAN)
IF (LF_WSFMEAN .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_2RB (YD%F_WSFMEAN)
  !$ACC ENTER DATA ATTACH (YD%F_WSFMEAN)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_GROUP)
  !$ACC ENTER DATA ATTACH (YD%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_SURFACE_VIEW_GROUP_WAVES (YD)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_WAVES_MOD

IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_WAVES), TARGET :: YD
LOGICAL :: LF_CHAR, LF_CHARHQ, LF_GROUP, LF_PHIOC, LF_TAUOCX, LF_TAUOCY, LF_USTOKES, LF_VSTOKES, LF_WSEMEAN, LF_WSFMEAN
LOGICAL :: LVARIABLE_GROUP
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  CALL HOST_SURFACE_VARIABLE_GROUP_WAVES (YD%VARIABLE_GROUP)
ENDIF

LF_CHAR = ASSOCIATED (YD%F_CHAR)
IF (LF_CHAR) THEN
  CALL HOST_FIELD_2RB (YD%F_CHAR)
ENDIF

LF_CHARHQ = ASSOCIATED (YD%F_CHARHQ)
IF (LF_CHARHQ) THEN
  CALL HOST_FIELD_2RB (YD%F_CHARHQ)
ENDIF

LF_USTOKES = ASSOCIATED (YD%F_USTOKES)
IF (LF_USTOKES) THEN
  CALL HOST_FIELD_2RB (YD%F_USTOKES)
ENDIF

LF_VSTOKES = ASSOCIATED (YD%F_VSTOKES)
IF (LF_VSTOKES) THEN
  CALL HOST_FIELD_2RB (YD%F_VSTOKES)
ENDIF

LF_TAUOCX = ASSOCIATED (YD%F_TAUOCX)
IF (LF_TAUOCX) THEN
  CALL HOST_FIELD_2RB (YD%F_TAUOCX)
ENDIF

LF_TAUOCY = ASSOCIATED (YD%F_TAUOCY)
IF (LF_TAUOCY) THEN
  CALL HOST_FIELD_2RB (YD%F_TAUOCY)
ENDIF

LF_PHIOC = ASSOCIATED (YD%F_PHIOC)
IF (LF_PHIOC) THEN
  CALL HOST_FIELD_2RB (YD%F_PHIOC)
ENDIF

LF_WSEMEAN = ASSOCIATED (YD%F_WSEMEAN)
IF (LF_WSEMEAN) THEN
  CALL HOST_FIELD_2RB (YD%F_WSEMEAN)
ENDIF

LF_WSFMEAN = ASSOCIATED (YD%F_WSFMEAN)
IF (LF_WSFMEAN) THEN
  CALL HOST_FIELD_2RB (YD%F_WSFMEAN)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (YD%F_GROUP)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_SURFACE_VIEW_GROUP_WAVES (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_SURFACE_VARIABLE_GROUP_WAVES_MOD
IMPLICIT NONE
TYPE (SURFACE_VIEW_GROUP_WAVES), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_CHAR, LF_CHARHQ, LF_GROUP, LF_PHIOC, LF_TAUOCX, LF_TAUOCY, LF_USTOKES, LF_VSTOKES, LF_WSEMEAN, LF_WSFMEAN
LOGICAL :: LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVARIABLE_GROUP = ASSOCIATED (YD%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
  CALL WIPE_SURFACE_VARIABLE_GROUP_WAVES (YD%VARIABLE_GROUP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (YD%VARIABLE_GROUP)
ENDIF

LF_CHAR = ASSOCIATED (YD%F_CHAR)
IF (LF_CHAR .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_CHAR)
ENDIF

LF_CHARHQ = ASSOCIATED (YD%F_CHARHQ)
IF (LF_CHARHQ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_CHARHQ)
ENDIF

LF_USTOKES = ASSOCIATED (YD%F_USTOKES)
IF (LF_USTOKES .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_USTOKES)
ENDIF

LF_VSTOKES = ASSOCIATED (YD%F_VSTOKES)
IF (LF_VSTOKES .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_VSTOKES)
ENDIF

LF_TAUOCX = ASSOCIATED (YD%F_TAUOCX)
IF (LF_TAUOCX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_TAUOCX)
ENDIF

LF_TAUOCY = ASSOCIATED (YD%F_TAUOCY)
IF (LF_TAUOCY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_TAUOCY)
ENDIF

LF_PHIOC = ASSOCIATED (YD%F_PHIOC)
IF (LF_PHIOC .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_PHIOC)
ENDIF

LF_WSEMEAN = ASSOCIATED (YD%F_WSEMEAN)
IF (LF_WSEMEAN .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_WSEMEAN)
ENDIF

LF_WSFMEAN = ASSOCIATED (YD%F_WSFMEAN)
IF (LF_WSFMEAN .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (YD%F_WSFMEAN)
ENDIF

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
