MODULE UTIL_CPG_CTY_TYPE_MOD

USE CPG_TYPE_MOD, ONLY : CPG_CTY_TYPE



INTERFACE COPY
MODULE PROCEDURE COPY_CPG_CTY_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_CPG_CTY_TYPE
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_CTY_TYPE
END INTERFACE



CONTAINS





SUBROUTINE COPY_CPG_CTY_TYPE (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (CPG_CTY_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_DATA, LF_DIVDP, LF_EVEL, LF_PSDIV, LF_PSDVBC, LF_VVEL, LZDATA, LZVIEW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF

LZVIEW = ASSOCIATED (YD%ZVIEW)
IF (LZVIEW) THEN
  !$ACC ENTER DATA CREATE (YD%ZVIEW)
  !$ACC UPDATE DEVICE (YD%ZVIEW)
  !$ACC ENTER DATA ATTACH (YD%ZVIEW)
ENDIF

LZDATA = ASSOCIATED (YD%ZDATA)
IF (LZDATA) THEN
  !$ACC ENTER DATA CREATE (YD%ZDATA)
  !$ACC UPDATE DEVICE (YD%ZDATA)
  !$ACC ENTER DATA ATTACH (YD%ZDATA)
ENDIF

LF_DATA = ASSOCIATED (YD%F_DATA)
IF (LF_DATA .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_4RB (YD%F_DATA)
  !$ACC ENTER DATA ATTACH (YD%F_DATA)
ENDIF


LF_EVEL = ASSOCIATED (YD%F_EVEL)
IF (LF_EVEL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_EVEL)
  !$ACC ENTER DATA ATTACH (YD%F_EVEL)
ENDIF


LF_VVEL = ASSOCIATED (YD%F_VVEL)
IF (LF_VVEL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_VVEL)
  !$ACC ENTER DATA ATTACH (YD%F_VVEL)
ENDIF


LF_PSDIV = ASSOCIATED (YD%F_PSDIV)
IF (LF_PSDIV .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_PSDIV)
  !$ACC ENTER DATA ATTACH (YD%F_PSDIV)
ENDIF


LF_PSDVBC = ASSOCIATED (YD%F_PSDVBC)
IF (LF_PSDVBC .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_PSDVBC)
  !$ACC ENTER DATA ATTACH (YD%F_PSDVBC)
ENDIF


LF_DIVDP = ASSOCIATED (YD%F_DIVDP)
IF (LF_DIVDP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DIVDP)
  !$ACC ENTER DATA ATTACH (YD%F_DIVDP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_CPG_CTY_TYPE (YD)
USE FIELD_UTIL_MODULE

IMPLICIT NONE
TYPE (CPG_CTY_TYPE), TARGET :: YD
LOGICAL :: LF_DATA, LF_DIVDP, LF_EVEL, LF_PSDIV, LF_PSDVBC, LF_VVEL, LZDATA, LZVIEW



LF_DATA = ASSOCIATED (YD%F_DATA)
IF (LF_DATA) THEN
  CALL HOST_FIELD_4RB (YD%F_DATA)
ENDIF


LF_EVEL = ASSOCIATED (YD%F_EVEL)
IF (LF_EVEL) THEN
  CALL HOST_FIELD_3RB (YD%F_EVEL)
ENDIF


LF_VVEL = ASSOCIATED (YD%F_VVEL)
IF (LF_VVEL) THEN
  CALL HOST_FIELD_3RB (YD%F_VVEL)
ENDIF


LF_PSDIV = ASSOCIATED (YD%F_PSDIV)
IF (LF_PSDIV) THEN
  CALL HOST_FIELD_3RB (YD%F_PSDIV)
ENDIF


LF_PSDVBC = ASSOCIATED (YD%F_PSDVBC)
IF (LF_PSDVBC) THEN
  CALL HOST_FIELD_3RB (YD%F_PSDVBC)
ENDIF


LF_DIVDP = ASSOCIATED (YD%F_DIVDP)
IF (LF_DIVDP) THEN
  CALL HOST_FIELD_3RB (YD%F_DIVDP)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_CPG_CTY_TYPE (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (CPG_CTY_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_DATA, LF_DIVDP, LF_EVEL, LF_PSDIV, LF_PSDVBC, LF_VVEL, LZDATA, LZVIEW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LZVIEW = ASSOCIATED (YD%ZVIEW)
IF (LZVIEW) THEN
  !$ACC EXIT DATA DETACH (YD%ZVIEW)
  !$ACC EXIT DATA DETACH (YD%ZVIEW)
ENDIF

LZDATA = ASSOCIATED (YD%ZDATA)
IF (LZDATA) THEN
  !$ACC EXIT DATA DETACH (YD%ZDATA)
  !$ACC EXIT DATA DETACH (YD%ZDATA)
ENDIF

LF_DATA = ASSOCIATED (YD%F_DATA)
IF (LF_DATA .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (YD%F_DATA)
ENDIF


LF_EVEL = ASSOCIATED (YD%F_EVEL)
IF (LF_EVEL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_EVEL)
ENDIF


LF_VVEL = ASSOCIATED (YD%F_VVEL)
IF (LF_VVEL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_VVEL)
ENDIF


LF_PSDIV = ASSOCIATED (YD%F_PSDIV)
IF (LF_PSDIV .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_PSDIV)
ENDIF


LF_PSDVBC = ASSOCIATED (YD%F_PSDVBC)
IF (LF_PSDVBC .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_PSDVBC)
ENDIF


LF_DIVDP = ASSOCIATED (YD%F_DIVDP)
IF (LF_DIVDP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DIVDP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
