MODULE UTIL_GRADIENT_TYPE_MOD

USE YOMDGRADIENT_TYPE_MOD, ONLY : GRADIENT_TYPE



INTERFACE COPY
MODULE PROCEDURE COPY_GRADIENT_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_GRADIENT_TYPE
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_GRADIENT_TYPE
END INTERFACE



CONTAINS





SUBROUTINE COPY_GRADIENT_TYPE (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (GRADIENT_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_DATA, LF_DQGDX, LF_DQGDY, LF_DQIDX, LF_DQIDY, LF_DQLDX, LF_DQLDY, LF_DQRDX, LF_DQRDY, LF_DQSDX
LOGICAL :: LF_DQSDY, LF_DQVDX, LF_DQVDY, LF_DRIDXZ, LF_DRIDYZ, LF_DRLDXZ, LF_DRLDYZ, LF_DRVDXZ, LF_DRVDYZ, LF_DTDX
LOGICAL :: LF_DTDY, LF_DTHETADXZ, LF_DTHETADYZ, LF_DU2DX2, LF_DU2DY2, LF_DUDX, LF_DUDXZ, LF_DUDY, LF_DUDYZ, LF_DV2DX2
LOGICAL :: LF_DV2DY2, LF_DVDX, LF_DVDXZ, LF_DVDY, LF_DVDYZ, LF_DWDXZ, LF_DWDYZ, LZDATA, LZVIEW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF

LZVIEW = ASSOCIATED (YD%ZVIEW)
IF (LZVIEW) THEN
  !$ACC ENTER DATA CREATE (YD%ZVIEW)
  !$ACC UPDATE DEVICE (YD%ZVIEW)
  !$ACC ENTER DATA ATTACH (YD%ZVIEW)
ENDIF

LZDATA = ASSOCIATED (YD%ZDATA)
IF (LZDATA) THEN
  !$ACC ENTER DATA CREATE (YD%ZDATA)
  !$ACC UPDATE DEVICE (YD%ZDATA)
  !$ACC ENTER DATA ATTACH (YD%ZDATA)
ENDIF

LF_DATA = ASSOCIATED (YD%F_DATA)
IF (LF_DATA .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_4RB (YD%F_DATA)
  !$ACC ENTER DATA ATTACH (YD%F_DATA)
ENDIF


LF_DUDX = ASSOCIATED (YD%F_DUDX)
IF (LF_DUDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DUDX)
  !$ACC ENTER DATA ATTACH (YD%F_DUDX)
ENDIF


LF_DUDY = ASSOCIATED (YD%F_DUDY)
IF (LF_DUDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DUDY)
  !$ACC ENTER DATA ATTACH (YD%F_DUDY)
ENDIF


LF_DVDX = ASSOCIATED (YD%F_DVDX)
IF (LF_DVDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DVDX)
  !$ACC ENTER DATA ATTACH (YD%F_DVDX)
ENDIF


LF_DVDY = ASSOCIATED (YD%F_DVDY)
IF (LF_DVDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DVDY)
  !$ACC ENTER DATA ATTACH (YD%F_DVDY)
ENDIF


LF_DTDX = ASSOCIATED (YD%F_DTDX)
IF (LF_DTDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DTDX)
  !$ACC ENTER DATA ATTACH (YD%F_DTDX)
ENDIF


LF_DTDY = ASSOCIATED (YD%F_DTDY)
IF (LF_DTDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DTDY)
  !$ACC ENTER DATA ATTACH (YD%F_DTDY)
ENDIF


LF_DQVDX = ASSOCIATED (YD%F_DQVDX)
IF (LF_DQVDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQVDX)
  !$ACC ENTER DATA ATTACH (YD%F_DQVDX)
ENDIF


LF_DQVDY = ASSOCIATED (YD%F_DQVDY)
IF (LF_DQVDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQVDY)
  !$ACC ENTER DATA ATTACH (YD%F_DQVDY)
ENDIF


LF_DQLDX = ASSOCIATED (YD%F_DQLDX)
IF (LF_DQLDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQLDX)
  !$ACC ENTER DATA ATTACH (YD%F_DQLDX)
ENDIF


LF_DQLDY = ASSOCIATED (YD%F_DQLDY)
IF (LF_DQLDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQLDY)
  !$ACC ENTER DATA ATTACH (YD%F_DQLDY)
ENDIF


LF_DQIDX = ASSOCIATED (YD%F_DQIDX)
IF (LF_DQIDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQIDX)
  !$ACC ENTER DATA ATTACH (YD%F_DQIDX)
ENDIF


LF_DQIDY = ASSOCIATED (YD%F_DQIDY)
IF (LF_DQIDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQIDY)
  !$ACC ENTER DATA ATTACH (YD%F_DQIDY)
ENDIF


LF_DQRDX = ASSOCIATED (YD%F_DQRDX)
IF (LF_DQRDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQRDX)
  !$ACC ENTER DATA ATTACH (YD%F_DQRDX)
ENDIF


LF_DQRDY = ASSOCIATED (YD%F_DQRDY)
IF (LF_DQRDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQRDY)
  !$ACC ENTER DATA ATTACH (YD%F_DQRDY)
ENDIF


LF_DQSDX = ASSOCIATED (YD%F_DQSDX)
IF (LF_DQSDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQSDX)
  !$ACC ENTER DATA ATTACH (YD%F_DQSDX)
ENDIF


LF_DQSDY = ASSOCIATED (YD%F_DQSDY)
IF (LF_DQSDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQSDY)
  !$ACC ENTER DATA ATTACH (YD%F_DQSDY)
ENDIF


LF_DQGDX = ASSOCIATED (YD%F_DQGDX)
IF (LF_DQGDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQGDX)
  !$ACC ENTER DATA ATTACH (YD%F_DQGDX)
ENDIF


LF_DQGDY = ASSOCIATED (YD%F_DQGDY)
IF (LF_DQGDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DQGDY)
  !$ACC ENTER DATA ATTACH (YD%F_DQGDY)
ENDIF


LF_DU2DX2 = ASSOCIATED (YD%F_DU2DX2)
IF (LF_DU2DX2 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DU2DX2)
  !$ACC ENTER DATA ATTACH (YD%F_DU2DX2)
ENDIF


LF_DU2DY2 = ASSOCIATED (YD%F_DU2DY2)
IF (LF_DU2DY2 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DU2DY2)
  !$ACC ENTER DATA ATTACH (YD%F_DU2DY2)
ENDIF


LF_DV2DX2 = ASSOCIATED (YD%F_DV2DX2)
IF (LF_DV2DX2 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DV2DX2)
  !$ACC ENTER DATA ATTACH (YD%F_DV2DX2)
ENDIF


LF_DV2DY2 = ASSOCIATED (YD%F_DV2DY2)
IF (LF_DV2DY2 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DV2DY2)
  !$ACC ENTER DATA ATTACH (YD%F_DV2DY2)
ENDIF


LF_DUDXZ = ASSOCIATED (YD%F_DUDXZ)
IF (LF_DUDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DUDXZ)
  !$ACC ENTER DATA ATTACH (YD%F_DUDXZ)
ENDIF


LF_DUDYZ = ASSOCIATED (YD%F_DUDYZ)
IF (LF_DUDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DUDYZ)
  !$ACC ENTER DATA ATTACH (YD%F_DUDYZ)
ENDIF


LF_DVDXZ = ASSOCIATED (YD%F_DVDXZ)
IF (LF_DVDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DVDXZ)
  !$ACC ENTER DATA ATTACH (YD%F_DVDXZ)
ENDIF


LF_DVDYZ = ASSOCIATED (YD%F_DVDYZ)
IF (LF_DVDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DVDYZ)
  !$ACC ENTER DATA ATTACH (YD%F_DVDYZ)
ENDIF


LF_DWDXZ = ASSOCIATED (YD%F_DWDXZ)
IF (LF_DWDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DWDXZ)
  !$ACC ENTER DATA ATTACH (YD%F_DWDXZ)
ENDIF


LF_DWDYZ = ASSOCIATED (YD%F_DWDYZ)
IF (LF_DWDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DWDYZ)
  !$ACC ENTER DATA ATTACH (YD%F_DWDYZ)
ENDIF


LF_DRVDXZ = ASSOCIATED (YD%F_DRVDXZ)
IF (LF_DRVDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DRVDXZ)
  !$ACC ENTER DATA ATTACH (YD%F_DRVDXZ)
ENDIF


LF_DRVDYZ = ASSOCIATED (YD%F_DRVDYZ)
IF (LF_DRVDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DRVDYZ)
  !$ACC ENTER DATA ATTACH (YD%F_DRVDYZ)
ENDIF


LF_DRLDXZ = ASSOCIATED (YD%F_DRLDXZ)
IF (LF_DRLDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DRLDXZ)
  !$ACC ENTER DATA ATTACH (YD%F_DRLDXZ)
ENDIF


LF_DRLDYZ = ASSOCIATED (YD%F_DRLDYZ)
IF (LF_DRLDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DRLDYZ)
  !$ACC ENTER DATA ATTACH (YD%F_DRLDYZ)
ENDIF


LF_DRIDXZ = ASSOCIATED (YD%F_DRIDXZ)
IF (LF_DRIDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DRIDXZ)
  !$ACC ENTER DATA ATTACH (YD%F_DRIDXZ)
ENDIF


LF_DRIDYZ = ASSOCIATED (YD%F_DRIDYZ)
IF (LF_DRIDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DRIDYZ)
  !$ACC ENTER DATA ATTACH (YD%F_DRIDYZ)
ENDIF


LF_DTHETADXZ = ASSOCIATED (YD%F_DTHETADXZ)
IF (LF_DTHETADXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DTHETADXZ)
  !$ACC ENTER DATA ATTACH (YD%F_DTHETADXZ)
ENDIF


LF_DTHETADYZ = ASSOCIATED (YD%F_DTHETADYZ)
IF (LF_DTHETADYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (YD%F_DTHETADYZ)
  !$ACC ENTER DATA ATTACH (YD%F_DTHETADYZ)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_GRADIENT_TYPE (YD)
USE FIELD_UTIL_MODULE

IMPLICIT NONE
TYPE (GRADIENT_TYPE), TARGET :: YD
LOGICAL :: LF_DATA, LF_DQGDX, LF_DQGDY, LF_DQIDX, LF_DQIDY, LF_DQLDX, LF_DQLDY, LF_DQRDX, LF_DQRDY, LF_DQSDX
LOGICAL :: LF_DQSDY, LF_DQVDX, LF_DQVDY, LF_DRIDXZ, LF_DRIDYZ, LF_DRLDXZ, LF_DRLDYZ, LF_DRVDXZ, LF_DRVDYZ, LF_DTDX
LOGICAL :: LF_DTDY, LF_DTHETADXZ, LF_DTHETADYZ, LF_DU2DX2, LF_DU2DY2, LF_DUDX, LF_DUDXZ, LF_DUDY, LF_DUDYZ, LF_DV2DX2
LOGICAL :: LF_DV2DY2, LF_DVDX, LF_DVDXZ, LF_DVDY, LF_DVDYZ, LF_DWDXZ, LF_DWDYZ, LZDATA, LZVIEW



LF_DATA = ASSOCIATED (YD%F_DATA)
IF (LF_DATA) THEN
  CALL HOST_FIELD_4RB (YD%F_DATA)
ENDIF


LF_DUDX = ASSOCIATED (YD%F_DUDX)
IF (LF_DUDX) THEN
  CALL HOST_FIELD_3RB (YD%F_DUDX)
ENDIF


LF_DUDY = ASSOCIATED (YD%F_DUDY)
IF (LF_DUDY) THEN
  CALL HOST_FIELD_3RB (YD%F_DUDY)
ENDIF


LF_DVDX = ASSOCIATED (YD%F_DVDX)
IF (LF_DVDX) THEN
  CALL HOST_FIELD_3RB (YD%F_DVDX)
ENDIF


LF_DVDY = ASSOCIATED (YD%F_DVDY)
IF (LF_DVDY) THEN
  CALL HOST_FIELD_3RB (YD%F_DVDY)
ENDIF


LF_DTDX = ASSOCIATED (YD%F_DTDX)
IF (LF_DTDX) THEN
  CALL HOST_FIELD_3RB (YD%F_DTDX)
ENDIF


LF_DTDY = ASSOCIATED (YD%F_DTDY)
IF (LF_DTDY) THEN
  CALL HOST_FIELD_3RB (YD%F_DTDY)
ENDIF


LF_DQVDX = ASSOCIATED (YD%F_DQVDX)
IF (LF_DQVDX) THEN
  CALL HOST_FIELD_3RB (YD%F_DQVDX)
ENDIF


LF_DQVDY = ASSOCIATED (YD%F_DQVDY)
IF (LF_DQVDY) THEN
  CALL HOST_FIELD_3RB (YD%F_DQVDY)
ENDIF


LF_DQLDX = ASSOCIATED (YD%F_DQLDX)
IF (LF_DQLDX) THEN
  CALL HOST_FIELD_3RB (YD%F_DQLDX)
ENDIF


LF_DQLDY = ASSOCIATED (YD%F_DQLDY)
IF (LF_DQLDY) THEN
  CALL HOST_FIELD_3RB (YD%F_DQLDY)
ENDIF


LF_DQIDX = ASSOCIATED (YD%F_DQIDX)
IF (LF_DQIDX) THEN
  CALL HOST_FIELD_3RB (YD%F_DQIDX)
ENDIF


LF_DQIDY = ASSOCIATED (YD%F_DQIDY)
IF (LF_DQIDY) THEN
  CALL HOST_FIELD_3RB (YD%F_DQIDY)
ENDIF


LF_DQRDX = ASSOCIATED (YD%F_DQRDX)
IF (LF_DQRDX) THEN
  CALL HOST_FIELD_3RB (YD%F_DQRDX)
ENDIF


LF_DQRDY = ASSOCIATED (YD%F_DQRDY)
IF (LF_DQRDY) THEN
  CALL HOST_FIELD_3RB (YD%F_DQRDY)
ENDIF


LF_DQSDX = ASSOCIATED (YD%F_DQSDX)
IF (LF_DQSDX) THEN
  CALL HOST_FIELD_3RB (YD%F_DQSDX)
ENDIF


LF_DQSDY = ASSOCIATED (YD%F_DQSDY)
IF (LF_DQSDY) THEN
  CALL HOST_FIELD_3RB (YD%F_DQSDY)
ENDIF


LF_DQGDX = ASSOCIATED (YD%F_DQGDX)
IF (LF_DQGDX) THEN
  CALL HOST_FIELD_3RB (YD%F_DQGDX)
ENDIF


LF_DQGDY = ASSOCIATED (YD%F_DQGDY)
IF (LF_DQGDY) THEN
  CALL HOST_FIELD_3RB (YD%F_DQGDY)
ENDIF


LF_DU2DX2 = ASSOCIATED (YD%F_DU2DX2)
IF (LF_DU2DX2) THEN
  CALL HOST_FIELD_3RB (YD%F_DU2DX2)
ENDIF


LF_DU2DY2 = ASSOCIATED (YD%F_DU2DY2)
IF (LF_DU2DY2) THEN
  CALL HOST_FIELD_3RB (YD%F_DU2DY2)
ENDIF


LF_DV2DX2 = ASSOCIATED (YD%F_DV2DX2)
IF (LF_DV2DX2) THEN
  CALL HOST_FIELD_3RB (YD%F_DV2DX2)
ENDIF


LF_DV2DY2 = ASSOCIATED (YD%F_DV2DY2)
IF (LF_DV2DY2) THEN
  CALL HOST_FIELD_3RB (YD%F_DV2DY2)
ENDIF


LF_DUDXZ = ASSOCIATED (YD%F_DUDXZ)
IF (LF_DUDXZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DUDXZ)
ENDIF


LF_DUDYZ = ASSOCIATED (YD%F_DUDYZ)
IF (LF_DUDYZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DUDYZ)
ENDIF


LF_DVDXZ = ASSOCIATED (YD%F_DVDXZ)
IF (LF_DVDXZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DVDXZ)
ENDIF


LF_DVDYZ = ASSOCIATED (YD%F_DVDYZ)
IF (LF_DVDYZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DVDYZ)
ENDIF


LF_DWDXZ = ASSOCIATED (YD%F_DWDXZ)
IF (LF_DWDXZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DWDXZ)
ENDIF


LF_DWDYZ = ASSOCIATED (YD%F_DWDYZ)
IF (LF_DWDYZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DWDYZ)
ENDIF


LF_DRVDXZ = ASSOCIATED (YD%F_DRVDXZ)
IF (LF_DRVDXZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DRVDXZ)
ENDIF


LF_DRVDYZ = ASSOCIATED (YD%F_DRVDYZ)
IF (LF_DRVDYZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DRVDYZ)
ENDIF


LF_DRLDXZ = ASSOCIATED (YD%F_DRLDXZ)
IF (LF_DRLDXZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DRLDXZ)
ENDIF


LF_DRLDYZ = ASSOCIATED (YD%F_DRLDYZ)
IF (LF_DRLDYZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DRLDYZ)
ENDIF


LF_DRIDXZ = ASSOCIATED (YD%F_DRIDXZ)
IF (LF_DRIDXZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DRIDXZ)
ENDIF


LF_DRIDYZ = ASSOCIATED (YD%F_DRIDYZ)
IF (LF_DRIDYZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DRIDYZ)
ENDIF


LF_DTHETADXZ = ASSOCIATED (YD%F_DTHETADXZ)
IF (LF_DTHETADXZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DTHETADXZ)
ENDIF


LF_DTHETADYZ = ASSOCIATED (YD%F_DTHETADYZ)
IF (LF_DTHETADYZ) THEN
  CALL HOST_FIELD_3RB (YD%F_DTHETADYZ)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_GRADIENT_TYPE (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (GRADIENT_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_DATA, LF_DQGDX, LF_DQGDY, LF_DQIDX, LF_DQIDY, LF_DQLDX, LF_DQLDY, LF_DQRDX, LF_DQRDY, LF_DQSDX
LOGICAL :: LF_DQSDY, LF_DQVDX, LF_DQVDY, LF_DRIDXZ, LF_DRIDYZ, LF_DRLDXZ, LF_DRLDYZ, LF_DRVDXZ, LF_DRVDYZ, LF_DTDX
LOGICAL :: LF_DTDY, LF_DTHETADXZ, LF_DTHETADYZ, LF_DU2DX2, LF_DU2DY2, LF_DUDX, LF_DUDXZ, LF_DUDY, LF_DUDYZ, LF_DV2DX2
LOGICAL :: LF_DV2DY2, LF_DVDX, LF_DVDXZ, LF_DVDY, LF_DVDYZ, LF_DWDXZ, LF_DWDYZ, LZDATA, LZVIEW

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LZVIEW = ASSOCIATED (YD%ZVIEW)
IF (LZVIEW) THEN
  !$ACC EXIT DATA DETACH (YD%ZVIEW)
  !$ACC EXIT DATA DETACH (YD%ZVIEW)
ENDIF

LZDATA = ASSOCIATED (YD%ZDATA)
IF (LZDATA) THEN
  !$ACC EXIT DATA DETACH (YD%ZDATA)
  !$ACC EXIT DATA DETACH (YD%ZDATA)
ENDIF

LF_DATA = ASSOCIATED (YD%F_DATA)
IF (LF_DATA .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (YD%F_DATA)
ENDIF


LF_DUDX = ASSOCIATED (YD%F_DUDX)
IF (LF_DUDX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DUDX)
ENDIF


LF_DUDY = ASSOCIATED (YD%F_DUDY)
IF (LF_DUDY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DUDY)
ENDIF


LF_DVDX = ASSOCIATED (YD%F_DVDX)
IF (LF_DVDX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DVDX)
ENDIF


LF_DVDY = ASSOCIATED (YD%F_DVDY)
IF (LF_DVDY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DVDY)
ENDIF


LF_DTDX = ASSOCIATED (YD%F_DTDX)
IF (LF_DTDX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DTDX)
ENDIF


LF_DTDY = ASSOCIATED (YD%F_DTDY)
IF (LF_DTDY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DTDY)
ENDIF


LF_DQVDX = ASSOCIATED (YD%F_DQVDX)
IF (LF_DQVDX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQVDX)
ENDIF


LF_DQVDY = ASSOCIATED (YD%F_DQVDY)
IF (LF_DQVDY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQVDY)
ENDIF


LF_DQLDX = ASSOCIATED (YD%F_DQLDX)
IF (LF_DQLDX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQLDX)
ENDIF


LF_DQLDY = ASSOCIATED (YD%F_DQLDY)
IF (LF_DQLDY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQLDY)
ENDIF


LF_DQIDX = ASSOCIATED (YD%F_DQIDX)
IF (LF_DQIDX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQIDX)
ENDIF


LF_DQIDY = ASSOCIATED (YD%F_DQIDY)
IF (LF_DQIDY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQIDY)
ENDIF


LF_DQRDX = ASSOCIATED (YD%F_DQRDX)
IF (LF_DQRDX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQRDX)
ENDIF


LF_DQRDY = ASSOCIATED (YD%F_DQRDY)
IF (LF_DQRDY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQRDY)
ENDIF


LF_DQSDX = ASSOCIATED (YD%F_DQSDX)
IF (LF_DQSDX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQSDX)
ENDIF


LF_DQSDY = ASSOCIATED (YD%F_DQSDY)
IF (LF_DQSDY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQSDY)
ENDIF


LF_DQGDX = ASSOCIATED (YD%F_DQGDX)
IF (LF_DQGDX .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQGDX)
ENDIF


LF_DQGDY = ASSOCIATED (YD%F_DQGDY)
IF (LF_DQGDY .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DQGDY)
ENDIF


LF_DU2DX2 = ASSOCIATED (YD%F_DU2DX2)
IF (LF_DU2DX2 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DU2DX2)
ENDIF


LF_DU2DY2 = ASSOCIATED (YD%F_DU2DY2)
IF (LF_DU2DY2 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DU2DY2)
ENDIF


LF_DV2DX2 = ASSOCIATED (YD%F_DV2DX2)
IF (LF_DV2DX2 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DV2DX2)
ENDIF


LF_DV2DY2 = ASSOCIATED (YD%F_DV2DY2)
IF (LF_DV2DY2 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DV2DY2)
ENDIF


LF_DUDXZ = ASSOCIATED (YD%F_DUDXZ)
IF (LF_DUDXZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DUDXZ)
ENDIF


LF_DUDYZ = ASSOCIATED (YD%F_DUDYZ)
IF (LF_DUDYZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DUDYZ)
ENDIF


LF_DVDXZ = ASSOCIATED (YD%F_DVDXZ)
IF (LF_DVDXZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DVDXZ)
ENDIF


LF_DVDYZ = ASSOCIATED (YD%F_DVDYZ)
IF (LF_DVDYZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DVDYZ)
ENDIF


LF_DWDXZ = ASSOCIATED (YD%F_DWDXZ)
IF (LF_DWDXZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DWDXZ)
ENDIF


LF_DWDYZ = ASSOCIATED (YD%F_DWDYZ)
IF (LF_DWDYZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DWDYZ)
ENDIF


LF_DRVDXZ = ASSOCIATED (YD%F_DRVDXZ)
IF (LF_DRVDXZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DRVDXZ)
ENDIF


LF_DRVDYZ = ASSOCIATED (YD%F_DRVDYZ)
IF (LF_DRVDYZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DRVDYZ)
ENDIF


LF_DRLDXZ = ASSOCIATED (YD%F_DRLDXZ)
IF (LF_DRLDXZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DRLDXZ)
ENDIF


LF_DRLDYZ = ASSOCIATED (YD%F_DRLDYZ)
IF (LF_DRLDYZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DRLDYZ)
ENDIF


LF_DRIDXZ = ASSOCIATED (YD%F_DRIDXZ)
IF (LF_DRIDXZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DRIDXZ)
ENDIF


LF_DRIDYZ = ASSOCIATED (YD%F_DRIDYZ)
IF (LF_DRIDYZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DRIDYZ)
ENDIF


LF_DTHETADXZ = ASSOCIATED (YD%F_DTHETADXZ)
IF (LF_DTHETADXZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DTHETADXZ)
ENDIF


LF_DTHETADYZ = ASSOCIATED (YD%F_DTHETADYZ)
IF (LF_DTHETADYZ .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (YD%F_DTHETADYZ)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
