MODULE UTIL_TEOZOC_MOD

USE YOEOZOC, ONLY : TEOZOC

INTERFACE SAVE
MODULE PROCEDURE SAVE_TEOZOC
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TEOZOC
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TEOZOC
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TEOZOC
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TEOZOC
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TEOZOC
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TEOZOC
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TEOZOC (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEOZOC), INTENT (IN), TARGET :: YD
LOGICAL :: LZOZCL, LZOZCLAQUA
LZOZCL = ALLOCATED (YD%ZOZCL)
WRITE (KLUN) LZOZCL
IF (LZOZCL) THEN
  WRITE (KLUN) LBOUND (YD%ZOZCL)
  WRITE (KLUN) UBOUND (YD%ZOZCL)
  WRITE (KLUN) YD%ZOZCL
ENDIF
LZOZCLAQUA = ALLOCATED (YD%ZOZCLAQUA)
WRITE (KLUN) LZOZCLAQUA
IF (LZOZCLAQUA) THEN
  WRITE (KLUN) LBOUND (YD%ZOZCLAQUA)
  WRITE (KLUN) UBOUND (YD%ZOZCLAQUA)
  WRITE (KLUN) YD%ZOZCLAQUA
ENDIF
WRITE (KLUN) YD%COZQC
WRITE (KLUN) YD%COZQS
WRITE (KLUN) YD%COZHC
WRITE (KLUN) YD%COZHS
WRITE (KLUN) YD%RSINC
WRITE (KLUN) YD%ROZT
WRITE (KLUN) YD%RPROC
END SUBROUTINE

SUBROUTINE LOAD_TEOZOC (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TEOZOC), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2), IL3(3), IU3(3)
LOGICAL :: LZOZCL, LZOZCLAQUA
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) LZOZCL
IF (LZOZCL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%ZOZCL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%ZOZCL,1):UBOUND(YD%ZOZCL,1), LBOUND(YD%ZOZCL,2):UBOUND(YD%ZOZCL,2), LBOUND(YD%ZOZCL,3):UBOUND(YD%ZOZCL,3)))
  READ (KLUN) ZTMP3
  YD%ZOZCL = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LZOZCLAQUA
IF (LZOZCLAQUA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%ZOZCLAQUA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%ZOZCLAQUA,1):UBOUND(YD%ZOZCLAQUA,1), LBOUND(YD%ZOZCLAQUA,2):UBOUND(YD%ZOZCLAQUA,2)))
  READ (KLUN) ZTMP2
  YD%ZOZCLAQUA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
ALLOCATE (ZTMP1(LBOUND(YD%COZQC,1):UBOUND(YD%COZQC,1)))
READ (KLUN) ZTMP1
YD%COZQC = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%COZQS,1):UBOUND(YD%COZQS,1)))
READ (KLUN) ZTMP1
YD%COZQS = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%COZHC,1):UBOUND(YD%COZHC,1)))
READ (KLUN) ZTMP1
YD%COZHC = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%COZHS,1):UBOUND(YD%COZHS,1)))
READ (KLUN) ZTMP1
YD%COZHS = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(YD%RSINC,1):UBOUND(YD%RSINC,1)))
READ (KLUN) ZTMP1
YD%RSINC = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP2(LBOUND(YD%ROZT,1):UBOUND(YD%ROZT,1), LBOUND(YD%ROZT,2):UBOUND(YD%ROZT,2)))
READ (KLUN) ZTMP2
YD%ROZT = ZTMP2
DEALLOCATE (ZTMP2)
ALLOCATE (ZTMP1(LBOUND(YD%RPROC,1):UBOUND(YD%RPROC,1)))
READ (KLUN) ZTMP1
YD%RPROC = ZTMP1
DEALLOCATE (ZTMP1)
END SUBROUTINE


SUBROUTINE COPY_TEOZOC (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEOZOC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LZOZCL, LZOZCLAQUA

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LZOZCL = ALLOCATED (YD%ZOZCL)
IF (LZOZCL) THEN
  !$ACC ENTER DATA CREATE (YD%ZOZCL)
  !$ACC UPDATE DEVICE (YD%ZOZCL)
  !$ACC ENTER DATA ATTACH (YD%ZOZCL)
ENDIF

LZOZCLAQUA = ALLOCATED (YD%ZOZCLAQUA)
IF (LZOZCLAQUA) THEN
  !$ACC ENTER DATA CREATE (YD%ZOZCLAQUA)
  !$ACC UPDATE DEVICE (YD%ZOZCLAQUA)
  !$ACC ENTER DATA ATTACH (YD%ZOZCLAQUA)
ENDIF








END SUBROUTINE

SUBROUTINE HOST_TEOZOC (YD)

IMPLICIT NONE
TYPE (TEOZOC), TARGET :: YD
LOGICAL :: LZOZCL, LZOZCLAQUA









END SUBROUTINE

     

SUBROUTINE CRC64_TEOZOC (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TEOZOC), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LZOZCL, LZOZCLAQUA
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%ZOZCL), CDPATH//'%ZOZCL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%ZOZCLAQUA), CDPATH//'%ZOZCLAQUA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%COZQC), CDPATH//'%COZQC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%COZQS), CDPATH//'%COZQS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%COZHC), CDPATH//'%COZHC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%COZHS), CDPATH//'%COZHS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RSINC), CDPATH//'%RSINC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%ROZT), CDPATH//'%ROZT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RPROC), CDPATH//'%RPROC'

END SUBROUTINE

SUBROUTINE WIPE_TEOZOC (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TEOZOC), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LZOZCL, LZOZCLAQUA

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LZOZCL = ALLOCATED (YD%ZOZCL)
IF (LZOZCL) THEN
  !$ACC EXIT DATA DETACH (YD%ZOZCL)
  !$ACC EXIT DATA DETACH (YD%ZOZCL)
ENDIF

LZOZCLAQUA = ALLOCATED (YD%ZOZCLAQUA)
IF (LZOZCLAQUA) THEN
  !$ACC EXIT DATA DETACH (YD%ZOZCLAQUA)
  !$ACC EXIT DATA DETACH (YD%ZOZCLAQUA)
ENDIF








LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TEOZOC (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TEOZOC),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LZOZCL, LZOZCLAQUA

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LZOZCL = ALLOCATED (YD%ZOZCL)
IF (LZOZCL) THEN
  ISIZE = KIND (YD%ZOZCL) * SIZE (YD%ZOZCL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%ZOZCL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LZOZCLAQUA = ALLOCATED (YD%ZOZCLAQUA)
IF (LZOZCLAQUA) THEN
  ISIZE = KIND (YD%ZOZCLAQUA) * SIZE (YD%ZOZCLAQUA)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%ZOZCLAQUA'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%COZQC) * SIZE (YD%COZQC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COZQC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COZQS) * SIZE (YD%COZQS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COZQS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COZHC) * SIZE (YD%COZHC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COZHC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%COZHS) * SIZE (YD%COZHS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COZHS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RSINC) * SIZE (YD%RSINC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSINC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%ROZT) * SIZE (YD%ROZT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%ROZT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPROC) * SIZE (YD%RPROC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPROC'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
