MODULE UTIL_TRADGHG_MOD

USE YOERADGHG, ONLY : TRADGHG

INTERFACE SAVE
MODULE PROCEDURE SAVE_TRADGHG
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TRADGHG
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TRADGHG
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TRADGHG
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TRADGHG
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TRADGHG
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TRADGHG
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TRADGHG (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRADGHG), INTENT (IN), TARGET :: YD
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT
LSINLAT = ALLOCATED (YD%SINLAT)
WRITE (KLUN) LSINLAT
IF (LSINLAT) THEN
  WRITE (KLUN) LBOUND (YD%SINLAT)
  WRITE (KLUN) UBOUND (YD%SINLAT)
  WRITE (KLUN) YD%SINLAT
ENDIF
LPRESSURE_HL = ALLOCATED (YD%PRESSURE_HL)
WRITE (KLUN) LPRESSURE_HL
IF (LPRESSURE_HL) THEN
  WRITE (KLUN) LBOUND (YD%PRESSURE_HL)
  WRITE (KLUN) UBOUND (YD%PRESSURE_HL)
  WRITE (KLUN) YD%PRESSURE_HL
ENDIF
LMASS_CH4 = ALLOCATED (YD%MASS_CH4)
WRITE (KLUN) LMASS_CH4
IF (LMASS_CH4) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CH4)
  WRITE (KLUN) UBOUND (YD%MASS_CH4)
  WRITE (KLUN) YD%MASS_CH4
ENDIF
LMASS_CO2 = ALLOCATED (YD%MASS_CO2)
WRITE (KLUN) LMASS_CO2
IF (LMASS_CO2) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CO2)
  WRITE (KLUN) UBOUND (YD%MASS_CO2)
  WRITE (KLUN) YD%MASS_CO2
ENDIF
LMASS_N2O = ALLOCATED (YD%MASS_N2O)
WRITE (KLUN) LMASS_N2O
IF (LMASS_N2O) THEN
  WRITE (KLUN) LBOUND (YD%MASS_N2O)
  WRITE (KLUN) UBOUND (YD%MASS_N2O)
  WRITE (KLUN) YD%MASS_N2O
ENDIF
LMASS_NO2 = ALLOCATED (YD%MASS_NO2)
WRITE (KLUN) LMASS_NO2
IF (LMASS_NO2) THEN
  WRITE (KLUN) LBOUND (YD%MASS_NO2)
  WRITE (KLUN) UBOUND (YD%MASS_NO2)
  WRITE (KLUN) YD%MASS_NO2
ENDIF
LMASS_CFC11 = ALLOCATED (YD%MASS_CFC11)
WRITE (KLUN) LMASS_CFC11
IF (LMASS_CFC11) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CFC11)
  WRITE (KLUN) UBOUND (YD%MASS_CFC11)
  WRITE (KLUN) YD%MASS_CFC11
ENDIF
LMASS_CFC12 = ALLOCATED (YD%MASS_CFC12)
WRITE (KLUN) LMASS_CFC12
IF (LMASS_CFC12) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CFC12)
  WRITE (KLUN) UBOUND (YD%MASS_CFC12)
  WRITE (KLUN) YD%MASS_CFC12
ENDIF
LMASS_CCL4 = ALLOCATED (YD%MASS_CCL4)
WRITE (KLUN) LMASS_CCL4
IF (LMASS_CCL4) THEN
  WRITE (KLUN) LBOUND (YD%MASS_CCL4)
  WRITE (KLUN) UBOUND (YD%MASS_CCL4)
  WRITE (KLUN) YD%MASS_CCL4
ENDIF
LMASS_HCFC22 = ALLOCATED (YD%MASS_HCFC22)
WRITE (KLUN) LMASS_HCFC22
IF (LMASS_HCFC22) THEN
  WRITE (KLUN) LBOUND (YD%MASS_HCFC22)
  WRITE (KLUN) UBOUND (YD%MASS_HCFC22)
  WRITE (KLUN) YD%MASS_HCFC22
ENDIF
LMASS_O3 = ALLOCATED (YD%MASS_O3)
WRITE (KLUN) LMASS_O3
IF (LMASS_O3) THEN
  WRITE (KLUN) LBOUND (YD%MASS_O3)
  WRITE (KLUN) UBOUND (YD%MASS_O3)
  WRITE (KLUN) YD%MASS_O3
ENDIF
WRITE (KLUN) YD%NLATITUDE
WRITE (KLUN) YD%NPRESSURE
END SUBROUTINE

SUBROUTINE LOAD_TRADGHG (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TRADGHG), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2)
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP2 (:,:)
READ (KLUN) LSINLAT
IF (LSINLAT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%SINLAT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%SINLAT,1):UBOUND(YD%SINLAT,1)))
  READ (KLUN) ZTMP1
  YD%SINLAT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LPRESSURE_HL
IF (LPRESSURE_HL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%PRESSURE_HL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%PRESSURE_HL,1):UBOUND(YD%PRESSURE_HL,1)))
  READ (KLUN) ZTMP1
  YD%PRESSURE_HL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LMASS_CH4
IF (LMASS_CH4) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CH4 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CH4,1):UBOUND(YD%MASS_CH4,1), LBOUND(YD%MASS_CH4,2):UBOUND(YD%MASS_CH4,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CH4 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_CO2
IF (LMASS_CO2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CO2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CO2,1):UBOUND(YD%MASS_CO2,1), LBOUND(YD%MASS_CO2,2):UBOUND(YD%MASS_CO2,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CO2 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_N2O
IF (LMASS_N2O) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_N2O (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_N2O,1):UBOUND(YD%MASS_N2O,1), LBOUND(YD%MASS_N2O,2):UBOUND(YD%MASS_N2O,2)))
  READ (KLUN) ZTMP2
  YD%MASS_N2O = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_NO2
IF (LMASS_NO2) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_NO2 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_NO2,1):UBOUND(YD%MASS_NO2,1), LBOUND(YD%MASS_NO2,2):UBOUND(YD%MASS_NO2,2)))
  READ (KLUN) ZTMP2
  YD%MASS_NO2 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_CFC11
IF (LMASS_CFC11) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CFC11 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CFC11,1):UBOUND(YD%MASS_CFC11,1), LBOUND(YD%MASS_CFC11,2):UBOUND(YD%MASS_CFC11,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CFC11 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_CFC12
IF (LMASS_CFC12) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CFC12 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CFC12,1):UBOUND(YD%MASS_CFC12,1), LBOUND(YD%MASS_CFC12,2):UBOUND(YD%MASS_CFC12,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CFC12 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_CCL4
IF (LMASS_CCL4) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_CCL4 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_CCL4,1):UBOUND(YD%MASS_CCL4,1), LBOUND(YD%MASS_CCL4,2):UBOUND(YD%MASS_CCL4,2)))
  READ (KLUN) ZTMP2
  YD%MASS_CCL4 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_HCFC22
IF (LMASS_HCFC22) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_HCFC22 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_HCFC22,1):UBOUND(YD%MASS_HCFC22,1), LBOUND(YD%MASS_HCFC22,2):UBOUND(YD%MASS_HCFC22,2)))
  READ (KLUN) ZTMP2
  YD%MASS_HCFC22 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LMASS_O3
IF (LMASS_O3) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%MASS_O3 (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(YD%MASS_O3,1):UBOUND(YD%MASS_O3,1), LBOUND(YD%MASS_O3,2):UBOUND(YD%MASS_O3,2)))
  READ (KLUN) ZTMP2
  YD%MASS_O3 = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) YD%NLATITUDE
READ (KLUN) YD%NPRESSURE
END SUBROUTINE


SUBROUTINE COPY_TRADGHG (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TRADGHG), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
LSINLAT = ALLOCATED (YD%SINLAT)
IF (LSINLAT) THEN
  !$ACC ENTER DATA CREATE (YD%SINLAT)
  !$ACC UPDATE DEVICE (YD%SINLAT)
  !$ACC ENTER DATA ATTACH (YD%SINLAT)
ENDIF

LPRESSURE_HL = ALLOCATED (YD%PRESSURE_HL)
IF (LPRESSURE_HL) THEN
  !$ACC ENTER DATA CREATE (YD%PRESSURE_HL)
  !$ACC UPDATE DEVICE (YD%PRESSURE_HL)
  !$ACC ENTER DATA ATTACH (YD%PRESSURE_HL)
ENDIF

LMASS_CH4 = ALLOCATED (YD%MASS_CH4)
IF (LMASS_CH4) THEN
  !$ACC ENTER DATA CREATE (YD%MASS_CH4)
  !$ACC UPDATE DEVICE (YD%MASS_CH4)
  !$ACC ENTER DATA ATTACH (YD%MASS_CH4)
ENDIF

LMASS_CO2 = ALLOCATED (YD%MASS_CO2)
IF (LMASS_CO2) THEN
  !$ACC ENTER DATA CREATE (YD%MASS_CO2)
  !$ACC UPDATE DEVICE (YD%MASS_CO2)
  !$ACC ENTER DATA ATTACH (YD%MASS_CO2)
ENDIF

LMASS_N2O = ALLOCATED (YD%MASS_N2O)
IF (LMASS_N2O) THEN
  !$ACC ENTER DATA CREATE (YD%MASS_N2O)
  !$ACC UPDATE DEVICE (YD%MASS_N2O)
  !$ACC ENTER DATA ATTACH (YD%MASS_N2O)
ENDIF

LMASS_NO2 = ALLOCATED (YD%MASS_NO2)
IF (LMASS_NO2) THEN
  !$ACC ENTER DATA CREATE (YD%MASS_NO2)
  !$ACC UPDATE DEVICE (YD%MASS_NO2)
  !$ACC ENTER DATA ATTACH (YD%MASS_NO2)
ENDIF

LMASS_CFC11 = ALLOCATED (YD%MASS_CFC11)
IF (LMASS_CFC11) THEN
  !$ACC ENTER DATA CREATE (YD%MASS_CFC11)
  !$ACC UPDATE DEVICE (YD%MASS_CFC11)
  !$ACC ENTER DATA ATTACH (YD%MASS_CFC11)
ENDIF

LMASS_CFC12 = ALLOCATED (YD%MASS_CFC12)
IF (LMASS_CFC12) THEN
  !$ACC ENTER DATA CREATE (YD%MASS_CFC12)
  !$ACC UPDATE DEVICE (YD%MASS_CFC12)
  !$ACC ENTER DATA ATTACH (YD%MASS_CFC12)
ENDIF

LMASS_CCL4 = ALLOCATED (YD%MASS_CCL4)
IF (LMASS_CCL4) THEN
  !$ACC ENTER DATA CREATE (YD%MASS_CCL4)
  !$ACC UPDATE DEVICE (YD%MASS_CCL4)
  !$ACC ENTER DATA ATTACH (YD%MASS_CCL4)
ENDIF

LMASS_HCFC22 = ALLOCATED (YD%MASS_HCFC22)
IF (LMASS_HCFC22) THEN
  !$ACC ENTER DATA CREATE (YD%MASS_HCFC22)
  !$ACC UPDATE DEVICE (YD%MASS_HCFC22)
  !$ACC ENTER DATA ATTACH (YD%MASS_HCFC22)
ENDIF

LMASS_O3 = ALLOCATED (YD%MASS_O3)
IF (LMASS_O3) THEN
  !$ACC ENTER DATA CREATE (YD%MASS_O3)
  !$ACC UPDATE DEVICE (YD%MASS_O3)
  !$ACC ENTER DATA ATTACH (YD%MASS_O3)
ENDIF



END SUBROUTINE

SUBROUTINE HOST_TRADGHG (YD)

IMPLICIT NONE
TYPE (TRADGHG), TARGET :: YD
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT













END SUBROUTINE

     

SUBROUTINE CRC64_TRADGHG (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TRADGHG), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%SINLAT), CDPATH//'%SINLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%PRESSURE_HL), CDPATH//'%PRESSURE_HL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MASS_CH4), CDPATH//'%MASS_CH4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MASS_CO2), CDPATH//'%MASS_CO2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MASS_N2O), CDPATH//'%MASS_N2O'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MASS_NO2), CDPATH//'%MASS_NO2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MASS_CFC11), CDPATH//'%MASS_CFC11'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MASS_CFC12), CDPATH//'%MASS_CFC12'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MASS_CCL4), CDPATH//'%MASS_CCL4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MASS_HCFC22), CDPATH//'%MASS_HCFC22'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%MASS_O3), CDPATH//'%MASS_O3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NLATITUDE), CDPATH//'%NLATITUDE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NPRESSURE), CDPATH//'%NPRESSURE'

END SUBROUTINE

SUBROUTINE WIPE_TRADGHG (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TRADGHG), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LSINLAT = ALLOCATED (YD%SINLAT)
IF (LSINLAT) THEN
  !$ACC EXIT DATA DETACH (YD%SINLAT)
  !$ACC EXIT DATA DETACH (YD%SINLAT)
ENDIF

LPRESSURE_HL = ALLOCATED (YD%PRESSURE_HL)
IF (LPRESSURE_HL) THEN
  !$ACC EXIT DATA DETACH (YD%PRESSURE_HL)
  !$ACC EXIT DATA DETACH (YD%PRESSURE_HL)
ENDIF

LMASS_CH4 = ALLOCATED (YD%MASS_CH4)
IF (LMASS_CH4) THEN
  !$ACC EXIT DATA DETACH (YD%MASS_CH4)
  !$ACC EXIT DATA DETACH (YD%MASS_CH4)
ENDIF

LMASS_CO2 = ALLOCATED (YD%MASS_CO2)
IF (LMASS_CO2) THEN
  !$ACC EXIT DATA DETACH (YD%MASS_CO2)
  !$ACC EXIT DATA DETACH (YD%MASS_CO2)
ENDIF

LMASS_N2O = ALLOCATED (YD%MASS_N2O)
IF (LMASS_N2O) THEN
  !$ACC EXIT DATA DETACH (YD%MASS_N2O)
  !$ACC EXIT DATA DETACH (YD%MASS_N2O)
ENDIF

LMASS_NO2 = ALLOCATED (YD%MASS_NO2)
IF (LMASS_NO2) THEN
  !$ACC EXIT DATA DETACH (YD%MASS_NO2)
  !$ACC EXIT DATA DETACH (YD%MASS_NO2)
ENDIF

LMASS_CFC11 = ALLOCATED (YD%MASS_CFC11)
IF (LMASS_CFC11) THEN
  !$ACC EXIT DATA DETACH (YD%MASS_CFC11)
  !$ACC EXIT DATA DETACH (YD%MASS_CFC11)
ENDIF

LMASS_CFC12 = ALLOCATED (YD%MASS_CFC12)
IF (LMASS_CFC12) THEN
  !$ACC EXIT DATA DETACH (YD%MASS_CFC12)
  !$ACC EXIT DATA DETACH (YD%MASS_CFC12)
ENDIF

LMASS_CCL4 = ALLOCATED (YD%MASS_CCL4)
IF (LMASS_CCL4) THEN
  !$ACC EXIT DATA DETACH (YD%MASS_CCL4)
  !$ACC EXIT DATA DETACH (YD%MASS_CCL4)
ENDIF

LMASS_HCFC22 = ALLOCATED (YD%MASS_HCFC22)
IF (LMASS_HCFC22) THEN
  !$ACC EXIT DATA DETACH (YD%MASS_HCFC22)
  !$ACC EXIT DATA DETACH (YD%MASS_HCFC22)
ENDIF

LMASS_O3 = ALLOCATED (YD%MASS_O3)
IF (LMASS_O3) THEN
  !$ACC EXIT DATA DETACH (YD%MASS_O3)
  !$ACC EXIT DATA DETACH (YD%MASS_O3)
ENDIF



LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TRADGHG (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TRADGHG),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LSINLAT = ALLOCATED (YD%SINLAT)
IF (LSINLAT) THEN
  ISIZE = KIND (YD%SINLAT) * SIZE (YD%SINLAT)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%SINLAT'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LPRESSURE_HL = ALLOCATED (YD%PRESSURE_HL)
IF (LPRESSURE_HL) THEN
  ISIZE = KIND (YD%PRESSURE_HL) * SIZE (YD%PRESSURE_HL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%PRESSURE_HL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMASS_CH4 = ALLOCATED (YD%MASS_CH4)
IF (LMASS_CH4) THEN
  ISIZE = KIND (YD%MASS_CH4) * SIZE (YD%MASS_CH4)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MASS_CH4'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMASS_CO2 = ALLOCATED (YD%MASS_CO2)
IF (LMASS_CO2) THEN
  ISIZE = KIND (YD%MASS_CO2) * SIZE (YD%MASS_CO2)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MASS_CO2'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMASS_N2O = ALLOCATED (YD%MASS_N2O)
IF (LMASS_N2O) THEN
  ISIZE = KIND (YD%MASS_N2O) * SIZE (YD%MASS_N2O)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MASS_N2O'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMASS_NO2 = ALLOCATED (YD%MASS_NO2)
IF (LMASS_NO2) THEN
  ISIZE = KIND (YD%MASS_NO2) * SIZE (YD%MASS_NO2)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MASS_NO2'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMASS_CFC11 = ALLOCATED (YD%MASS_CFC11)
IF (LMASS_CFC11) THEN
  ISIZE = KIND (YD%MASS_CFC11) * SIZE (YD%MASS_CFC11)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MASS_CFC11'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMASS_CFC12 = ALLOCATED (YD%MASS_CFC12)
IF (LMASS_CFC12) THEN
  ISIZE = KIND (YD%MASS_CFC12) * SIZE (YD%MASS_CFC12)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MASS_CFC12'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMASS_CCL4 = ALLOCATED (YD%MASS_CCL4)
IF (LMASS_CCL4) THEN
  ISIZE = KIND (YD%MASS_CCL4) * SIZE (YD%MASS_CCL4)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MASS_CCL4'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMASS_HCFC22 = ALLOCATED (YD%MASS_HCFC22)
IF (LMASS_HCFC22) THEN
  ISIZE = KIND (YD%MASS_HCFC22) * SIZE (YD%MASS_HCFC22)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MASS_HCFC22'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LMASS_O3 = ALLOCATED (YD%MASS_O3)
IF (LMASS_O3) THEN
  ISIZE = KIND (YD%MASS_O3) * SIZE (YD%MASS_O3)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MASS_O3'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%NLATITUDE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NLATITUDE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NPRESSURE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPRESSURE'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
