MODULE UTIL_TDPRECIPS_MOD

USE YOMDPRECIPS, ONLY : TDPRECIPS

INTERFACE SAVE
MODULE PROCEDURE SAVE_TDPRECIPS
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDPRECIPS
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TDPRECIPS
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TDPRECIPS
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TDPRECIPS
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TDPRECIPS
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TDPRECIPS
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TDPRECIPS (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDPRECIPS), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%HDPRECIPS
WRITE (KLUN) YD%HDCLWC
WRITE (KLUN) YD%RDHAIL1
WRITE (KLUN) YD%RDHAIL2
WRITE (KLUN) YD%RDSEUIL1
WRITE (KLUN) YD%RDSEUIL2
WRITE (KLUN) YD%RDSEUIL3
WRITE (KLUN) YD%RDSEUIL4
WRITE (KLUN) YD%RDSEUIL5
WRITE (KLUN) YD%RDCLWC
WRITE (KLUN) YD%RPRECSEUIL
WRITE (KLUN) YD%RHTOP
WRITE (KLUN) YD%RTPW
WRITE (KLUN) YD%RAWARM
WRITE (KLUN) YD%RAWARM2
WRITE (KLUN) YD%RACOLD
WRITE (KLUN) YD%RACOLD2
WRITE (KLUN) YD%NDTPREC
WRITE (KLUN) YD%NDTPREC2
END SUBROUTINE

SUBROUTINE LOAD_TDPRECIPS (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDPRECIPS), INTENT (OUT), TARGET :: YD
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) ZTMP0
YD%HDPRECIPS = ZTMP0
READ (KLUN) ZTMP0
YD%HDCLWC = ZTMP0
READ (KLUN) ZTMP0
YD%RDHAIL1 = ZTMP0
READ (KLUN) ZTMP0
YD%RDHAIL2 = ZTMP0
READ (KLUN) ZTMP0
YD%RDSEUIL1 = ZTMP0
READ (KLUN) ZTMP0
YD%RDSEUIL2 = ZTMP0
READ (KLUN) ZTMP0
YD%RDSEUIL3 = ZTMP0
READ (KLUN) ZTMP0
YD%RDSEUIL4 = ZTMP0
READ (KLUN) ZTMP0
YD%RDSEUIL5 = ZTMP0
READ (KLUN) ZTMP0
YD%RDCLWC = ZTMP0
READ (KLUN) ZTMP0
YD%RPRECSEUIL = ZTMP0
READ (KLUN) ZTMP0
YD%RHTOP = ZTMP0
READ (KLUN) ZTMP0
YD%RTPW = ZTMP0
READ (KLUN) ZTMP0
YD%RAWARM = ZTMP0
READ (KLUN) ZTMP0
YD%RAWARM2 = ZTMP0
READ (KLUN) ZTMP0
YD%RACOLD = ZTMP0
READ (KLUN) ZTMP0
YD%RACOLD2 = ZTMP0
READ (KLUN) YD%NDTPREC
READ (KLUN) YD%NDTPREC2
END SUBROUTINE


SUBROUTINE COPY_TDPRECIPS (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDPRECIPS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF



















END SUBROUTINE

SUBROUTINE HOST_TDPRECIPS (YD)

IMPLICIT NONE
TYPE (TDPRECIPS), TARGET :: YD




















END SUBROUTINE

     

SUBROUTINE CRC64_TDPRECIPS (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TDPRECIPS), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%HDPRECIPS), CDPATH//'%HDPRECIPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%HDCLWC), CDPATH//'%HDCLWC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RDHAIL1), CDPATH//'%RDHAIL1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RDHAIL2), CDPATH//'%RDHAIL2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RDSEUIL1), CDPATH//'%RDSEUIL1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RDSEUIL2), CDPATH//'%RDSEUIL2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RDSEUIL3), CDPATH//'%RDSEUIL3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RDSEUIL4), CDPATH//'%RDSEUIL4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RDSEUIL5), CDPATH//'%RDSEUIL5'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RDCLWC), CDPATH//'%RDCLWC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RPRECSEUIL), CDPATH//'%RPRECSEUIL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RHTOP), CDPATH//'%RHTOP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RTPW), CDPATH//'%RTPW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RAWARM), CDPATH//'%RAWARM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RAWARM2), CDPATH//'%RAWARM2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RACOLD), CDPATH//'%RACOLD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%RACOLD2), CDPATH//'%RACOLD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDTPREC), CDPATH//'%NDTPREC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDTPREC2), CDPATH//'%NDTPREC2'

END SUBROUTINE

SUBROUTINE WIPE_TDPRECIPS (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TDPRECIPS), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF



















LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TDPRECIPS (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TDPRECIPS),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%HDPRECIPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%HDPRECIPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%HDCLWC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%HDCLWC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDHAIL1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDHAIL1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDHAIL2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDHAIL2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDSEUIL1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDSEUIL2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL3)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDSEUIL3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL4)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDSEUIL4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDSEUIL5)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDSEUIL5'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RDCLWC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDCLWC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RPRECSEUIL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RPRECSEUIL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RHTOP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RHTOP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RTPW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RTPW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RAWARM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAWARM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RAWARM2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RAWARM2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RACOLD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RACOLD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%RACOLD2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RACOLD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDTPREC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDTPREC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDTPREC2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDTPREC2'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
