MODULE UTIL_SURFACE_VARIABLE_GROUP_VPRECIP_MOD

USE SURFACE_VARIABLES_MOD, ONLY : SURFACE_VARIABLE_GROUP_VPRECIP



INTERFACE COPY
MODULE PROCEDURE COPY_SURFACE_VARIABLE_GROUP_VPRECIP
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_SURFACE_VARIABLE_GROUP_VPRECIP
END INTERFACE

     

INTERFACE WIPE
MODULE PROCEDURE WIPE_SURFACE_VARIABLE_GROUP_VPRECIP
END INTERFACE



CONTAINS





SUBROUTINE COPY_SURFACE_VARIABLE_GROUP_VPRECIP (YD, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_3RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_VPRECIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
CALL COPY_VARIABLE_3RB (YD%VPRECIP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_4RB (YD%F_GROUP)
  !$ACC ENTER DATA ATTACH (YD%F_GROUP)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_SURFACE_VARIABLE_GROUP_VPRECIP (YD)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_3RB_MOD

IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_VPRECIP), TARGET :: YD
LOGICAL :: LF_GROUP
CALL HOST_VARIABLE_3RB (YD%VPRECIP)

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_4RB (YD%F_GROUP)
ENDIF

END SUBROUTINE

     



SUBROUTINE WIPE_SURFACE_VARIABLE_GROUP_VPRECIP (YD, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
USE UTIL_VARIABLE_3RB_MOD
IMPLICIT NONE
TYPE (SURFACE_VARIABLE_GROUP_VPRECIP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL WIPE_VARIABLE_3RB (YD%VPRECIP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LF_GROUP = ASSOCIATED (YD%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (YD%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE



END MODULE
