MODULE UTIL_MODEL_DYNAMICS_TYPE_MOD

USE MODEL_DYNAMICS_MOD, ONLY : MODEL_DYNAMICS_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_MODEL_DYNAMICS_TYPE
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_MODEL_DYNAMICS_TYPE
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_MODEL_DYNAMICS_TYPE
END INTERFACE


CONTAINS

SUBROUTINE SAVE_MODEL_DYNAMICS_TYPE (KLUN, YD)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLINT_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD

CALL SAVE_TDYNA (KLUN, YD%YRDYNA)
CALL SAVE_TDYN (KLUN, YD%YRDYN)
CALL SAVE_TEDYN (KLUN, YD%YREDYN)
CALL SAVE_TSPNG (KLUN, YD%YRSPNG)
CALL SAVE_TPTRGPPC (KLUN, YD%YRPTRGPPC)
CALL SAVE_TLSCAW (KLUN, YD%YYTLSCAW)
CALL SAVE_TLSCAW (KLUN, YD%YYTLSCAWH)
CALL SAVE_TRSCAW (KLUN, YD%YYTRSCAW)
CALL SAVE_TRSCAW (KLUN, YD%YYTRSCAWH)
CALL SAVE_TSCO (KLUN, YD%YYTSCO)
CALL SAVE_TCCO (KLUN, YD%YYTCCO)
CALL SAVE_TSLREP (KLUN, YD%YRSLREP)
CALL SAVE_TSLINT (KLUN, YD%YRSLINT)
CALL SAVE_TPTRSLB1 (KLUN, YD%YRPTRSLB1)
CALL SAVE_TPTRSLB2 (KLUN, YD%YRPTRSLB2)
CALL SAVE_TPTRSLB15 (KLUN, YD%YRPTRSLB15)
CALL SAVE_TTNH (KLUN, YD%YRTNH)
CALL SAVE_SL_STRUCT (KLUN, YD%YRSL)
CALL SAVE_SL_STRUCT (KLUN, YD%YRAD)
END SUBROUTINE

SUBROUTINE LOAD_MODEL_DYNAMICS_TYPE (KLUN, YD)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLINT_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_DYNAMICS_TYPE), INTENT (OUT), TARGET :: YD

CALL LOAD_TDYNA (KLUN, YD%YRDYNA)
CALL LOAD_TDYN (KLUN, YD%YRDYN)
CALL LOAD_TEDYN (KLUN, YD%YREDYN)
CALL LOAD_TSPNG (KLUN, YD%YRSPNG)
CALL LOAD_TPTRGPPC (KLUN, YD%YRPTRGPPC)
CALL LOAD_TLSCAW (KLUN, YD%YYTLSCAW)
CALL LOAD_TLSCAW (KLUN, YD%YYTLSCAWH)
CALL LOAD_TRSCAW (KLUN, YD%YYTRSCAW)
CALL LOAD_TRSCAW (KLUN, YD%YYTRSCAWH)
CALL LOAD_TSCO (KLUN, YD%YYTSCO)
CALL LOAD_TCCO (KLUN, YD%YYTCCO)
CALL LOAD_TSLREP (KLUN, YD%YRSLREP)
CALL LOAD_TSLINT (KLUN, YD%YRSLINT)
CALL LOAD_TPTRSLB1 (KLUN, YD%YRPTRSLB1)
CALL LOAD_TPTRSLB2 (KLUN, YD%YRPTRSLB2)
CALL LOAD_TPTRSLB15 (KLUN, YD%YRPTRSLB15)
CALL LOAD_TTNH (KLUN, YD%YRTNH)
CALL LOAD_SL_STRUCT (KLUN, YD%YRSL)
CALL LOAD_SL_STRUCT (KLUN, YD%YRAD)
END SUBROUTINE


SUBROUTINE COPY_MODEL_DYNAMICS_TYPE (YD, LDCREATED, LDFIELDAPI)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLINT_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD
IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF
CALL COPY_TDYNA (YD%YRDYNA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TDYN (YD%YRDYN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TEDYN (YD%YREDYN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TSPNG (YD%YRSPNG, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TPTRGPPC (YD%YRPTRGPPC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TLSCAW (YD%YYTLSCAW, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TLSCAW (YD%YYTLSCAWH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TRSCAW (YD%YYTRSCAW, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TRSCAW (YD%YYTRSCAWH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TSCO (YD%YYTSCO, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TCCO (YD%YYTCCO, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TSLREP (YD%YRSLREP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TSLINT (YD%YRSLINT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TPTRSLB1 (YD%YRPTRSLB1, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TPTRSLB2 (YD%YRPTRSLB2, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TPTRSLB15 (YD%YRPTRSLB15, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_TTNH (YD%YRTNH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_SL_STRUCT (YD%YRSL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_SL_STRUCT (YD%YRAD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

SUBROUTINE HOST_MODEL_DYNAMICS_TYPE (YD)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLINT_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD

IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), TARGET :: YD

CALL HOST_TDYNA (YD%YRDYNA)

CALL HOST_TDYN (YD%YRDYN)

CALL HOST_TEDYN (YD%YREDYN)

CALL HOST_TSPNG (YD%YRSPNG)

CALL HOST_TPTRGPPC (YD%YRPTRGPPC)

CALL HOST_TLSCAW (YD%YYTLSCAW)

CALL HOST_TLSCAW (YD%YYTLSCAWH)

CALL HOST_TRSCAW (YD%YYTRSCAW)

CALL HOST_TRSCAW (YD%YYTRSCAWH)

CALL HOST_TSCO (YD%YYTSCO)

CALL HOST_TCCO (YD%YYTCCO)

CALL HOST_TSLREP (YD%YRSLREP)

CALL HOST_TSLINT (YD%YRSLINT)

CALL HOST_TPTRSLB1 (YD%YRPTRSLB1)

CALL HOST_TPTRSLB2 (YD%YRPTRSLB2)

CALL HOST_TPTRSLB15 (YD%YRPTRSLB15)

CALL HOST_TTNH (YD%YRTNH)

CALL HOST_SL_STRUCT (YD%YRSL)

CALL HOST_SL_STRUCT (YD%YRAD)

END SUBROUTINE

     

SUBROUTINE CRC64_MODEL_DYNAMICS_TYPE (YD, KLUN, CDPATH)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLINT_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

CLIND = ''
CALL CRC64_TDYNA (YD%YRDYNA, KLUN, CDPATH//'%YRDYNA'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TDYN (YD%YRDYN, KLUN, CDPATH//'%YRDYN'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TEDYN (YD%YREDYN, KLUN, CDPATH//'%YREDYN'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TSPNG (YD%YRSPNG, KLUN, CDPATH//'%YRSPNG'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TPTRGPPC (YD%YRPTRGPPC, KLUN, CDPATH//'%YRPTRGPPC'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TLSCAW (YD%YYTLSCAW, KLUN, CDPATH//'%YYTLSCAW'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TLSCAW (YD%YYTLSCAWH, KLUN, CDPATH//'%YYTLSCAWH'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TRSCAW (YD%YYTRSCAW, KLUN, CDPATH//'%YYTRSCAW'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TRSCAW (YD%YYTRSCAWH, KLUN, CDPATH//'%YYTRSCAWH'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TSCO (YD%YYTSCO, KLUN, CDPATH//'%YYTSCO'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TCCO (YD%YYTCCO, KLUN, CDPATH//'%YYTCCO'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TSLREP (YD%YRSLREP, KLUN, CDPATH//'%YRSLREP'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TSLINT (YD%YRSLINT, KLUN, CDPATH//'%YRSLINT'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TPTRSLB1 (YD%YRPTRSLB1, KLUN, CDPATH//'%YRPTRSLB1'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TPTRSLB2 (YD%YRPTRSLB2, KLUN, CDPATH//'%YRPTRSLB2'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TPTRSLB15 (YD%YRPTRSLB15, KLUN, CDPATH//'%YRPTRSLB15'//TRIM(CLIND))

CLIND = ''
CALL CRC64_TTNH (YD%YRTNH, KLUN, CDPATH//'%YRTNH'//TRIM(CLIND))

CLIND = ''
CALL CRC64_SL_STRUCT (YD%YRSL, KLUN, CDPATH//'%YRSL'//TRIM(CLIND))

CLIND = ''
CALL CRC64_SL_STRUCT (YD%YRAD, KLUN, CDPATH//'%YRAD'//TRIM(CLIND))

END SUBROUTINE

SUBROUTINE WIPE_MODEL_DYNAMICS_TYPE (YD, LDDELETED, LDFIELDAPI)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLINT_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD
IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL WIPE_TDYNA (YD%YRDYNA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TDYN (YD%YRDYN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TEDYN (YD%YREDYN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TSPNG (YD%YRSPNG, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TPTRGPPC (YD%YRPTRGPPC, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TLSCAW (YD%YYTLSCAW, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TLSCAW (YD%YYTLSCAWH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TRSCAW (YD%YYTRSCAW, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TRSCAW (YD%YYTRSCAWH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TSCO (YD%YYTSCO, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TCCO (YD%YYTCCO, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TSLREP (YD%YRSLREP, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TSLINT (YD%YRSLINT, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TPTRSLB1 (YD%YRPTRSLB1, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TPTRSLB2 (YD%YRPTRSLB2, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TPTRSLB15 (YD%YRPTRSLB15, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_TTNH (YD%YRTNH, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_SL_STRUCT (YD%YRSL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_SL_STRUCT (YD%YRAD, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_MODEL_DYNAMICS_TYPE (YD, CDPATH, LDPRINT) RESULT (KSIZE)
USE UTIL_SL_STRUCT_MOD
USE UTIL_TCCO_MOD
USE UTIL_TDYNA_MOD
USE UTIL_TDYN_MOD
USE UTIL_TEDYN_MOD
USE UTIL_TLSCAW_MOD
USE UTIL_TPTRGPPC_MOD
USE UTIL_TPTRSLB15_MOD
USE UTIL_TPTRSLB1_MOD
USE UTIL_TPTRSLB2_MOD
USE UTIL_TRSCAW_MOD
USE UTIL_TSCO_MOD
USE UTIL_TSLINT_MOD
USE UTIL_TSLREP_MOD
USE UTIL_TSPNG_MOD
USE UTIL_TTNH_MOD
IMPLICIT NONE
TYPE (MODEL_DYNAMICS_TYPE),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
JSIZE = 0
ISIZE = SIZE_TDYNA (YD%YRDYNA, CLPATH//'%YRDYNA', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDYNA'
ENDIF
JSIZE = 0
ISIZE = SIZE_TDYN (YD%YRDYN, CLPATH//'%YRDYN', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRDYN'
ENDIF
JSIZE = 0
ISIZE = SIZE_TEDYN (YD%YREDYN, CLPATH//'%YREDYN', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREDYN'
ENDIF
JSIZE = 0
ISIZE = SIZE_TSPNG (YD%YRSPNG, CLPATH//'%YRSPNG', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSPNG'
ENDIF
JSIZE = 0
ISIZE = SIZE_TPTRGPPC (YD%YRPTRGPPC, CLPATH//'%YRPTRGPPC', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRPTRGPPC'
ENDIF
JSIZE = 0
ISIZE = SIZE_TLSCAW (YD%YYTLSCAW, CLPATH//'%YYTLSCAW', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTLSCAW'
ENDIF
JSIZE = 0
ISIZE = SIZE_TLSCAW (YD%YYTLSCAWH, CLPATH//'%YYTLSCAWH', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTLSCAWH'
ENDIF
JSIZE = 0
ISIZE = SIZE_TRSCAW (YD%YYTRSCAW, CLPATH//'%YYTRSCAW', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTRSCAW'
ENDIF
JSIZE = 0
ISIZE = SIZE_TRSCAW (YD%YYTRSCAWH, CLPATH//'%YYTRSCAWH', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTRSCAWH'
ENDIF
JSIZE = 0
ISIZE = SIZE_TSCO (YD%YYTSCO, CLPATH//'%YYTSCO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTSCO'
ENDIF
JSIZE = 0
ISIZE = SIZE_TCCO (YD%YYTCCO, CLPATH//'%YYTCCO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YYTCCO'
ENDIF
JSIZE = 0
ISIZE = SIZE_TSLREP (YD%YRSLREP, CLPATH//'%YRSLREP', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSLREP'
ENDIF
JSIZE = 0
ISIZE = SIZE_TSLINT (YD%YRSLINT, CLPATH//'%YRSLINT', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSLINT'
ENDIF
JSIZE = 0
ISIZE = SIZE_TPTRSLB1 (YD%YRPTRSLB1, CLPATH//'%YRPTRSLB1', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRPTRSLB1'
ENDIF
JSIZE = 0
ISIZE = SIZE_TPTRSLB2 (YD%YRPTRSLB2, CLPATH//'%YRPTRSLB2', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRPTRSLB2'
ENDIF
JSIZE = 0
ISIZE = SIZE_TPTRSLB15 (YD%YRPTRSLB15, CLPATH//'%YRPTRSLB15', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRPTRSLB15'
ENDIF
JSIZE = 0
ISIZE = SIZE_TTNH (YD%YRTNH, CLPATH//'%YRTNH', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRTNH'
ENDIF
JSIZE = 0
ISIZE = SIZE_SL_STRUCT (YD%YRSL, CLPATH//'%YRSL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRSL'
ENDIF
JSIZE = 0
ISIZE = SIZE_SL_STRUCT (YD%YRAD, CLPATH//'%YRAD', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRAD'
ENDIF
END FUNCTION

END MODULE
