SUBMODULE (CPG_TYPE_MOD) CPG_TYPE_MOD_CPG_MISC_TYPE_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_CPG_MISC_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (CPG_MISC_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_CLCT, LF_DHSF, LF_FTCNS, LF_KOZO, LF_LSM, LF_NEB, LF_QGRAUPEL, LF_QICE, LF_QLI, LF_QRAIN
LOGICAL :: LF_QS, LF_QSNOW, LF_QSOL, LF_RH, LF_TSOL
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_NEB = ASSOCIATED (SELF%F_NEB)
IF (LF_NEB .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_NEB)
ENDIF

LF_QLI = ASSOCIATED (SELF%F_QLI)
IF (LF_QLI .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_QLI)
ENDIF

LF_QICE = ASSOCIATED (SELF%F_QICE)
IF (LF_QICE .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_QICE)
ENDIF

LF_QRAIN = ASSOCIATED (SELF%F_QRAIN)
IF (LF_QRAIN .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_QRAIN)
ENDIF

LF_QSNOW = ASSOCIATED (SELF%F_QSNOW)
IF (LF_QSNOW .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_QSNOW)
ENDIF

LF_QGRAUPEL = ASSOCIATED (SELF%F_QGRAUPEL)
IF (LF_QGRAUPEL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_QGRAUPEL)
ENDIF

LF_RH = ASSOCIATED (SELF%F_RH)
IF (LF_RH .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_RH)
ENDIF

LF_QS = ASSOCIATED (SELF%F_QS)
IF (LF_QS .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_QS)
ENDIF

LF_QSOL = ASSOCIATED (SELF%F_QSOL)
IF (LF_QSOL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_QSOL)
ENDIF

LF_DHSF = ASSOCIATED (SELF%F_DHSF)
IF (LF_DHSF .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_DHSF)
ENDIF

LF_CLCT = ASSOCIATED (SELF%F_CLCT)
IF (LF_CLCT .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_CLCT)
ENDIF

LF_LSM = ASSOCIATED (SELF%F_LSM)
IF (LF_LSM .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_LSM)
ENDIF

LF_TSOL = ASSOCIATED (SELF%F_TSOL)
IF (LF_TSOL .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_TSOL)
ENDIF

LF_FTCNS = ASSOCIATED (SELF%F_FTCNS)
IF (LF_FTCNS .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (SELF%F_FTCNS)
ENDIF

LF_KOZO = ASSOCIATED (SELF%F_KOZO)
IF (LF_KOZO .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (SELF%F_KOZO)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
