SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_OPTS_SURF_TYPE_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_CPG_OPTS_SURF_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (CPG_OPTS_SURF_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL SELF%YSP_SB%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSP_SG%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSP_SL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSP_RR%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSP_CL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSP_OM%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSP_EP%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSP_X2%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSP_CI%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_VF%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_VH%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_VK%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_VP%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_VV%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_VA%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_VN%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_V2%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_V3%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_VD%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_SM%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_WS%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_WW%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_PF%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_XA%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_DI%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_XP%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_XP2%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_X2%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_SFO%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_SFL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSD_VC%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
