SUBMODULE (CPG_SL1_TYPE_MOD) CPG_SL1_TYPE_MOD_CPG_SL1F_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_CPG_SL1F_TYPE (SELF)

IMPLICIT NONE
CLASS (CPG_SL1F_TYPE), TARGET :: SELF
INTEGER :: J1
LOGICAL :: LAERAOT, LAERLISI, LAERO, LAEROCLIM, LAEROUT, LCHEM, LEDRP, LEMIS3D, LERA40, LEXT
LOGICAL :: LEZDIAG, LFORC, LGFL, LGHG, LLIMA, LNOGW, LSLDIA, LUVP, LY2FSL, LY2FSLA
LOGICAL :: LY2FSLB, LY3FSL, LY3FSLA, LY3FSLB

CALL SELF%U9%ACDC_HOST ()

CALL SELF%V9%ACDC_HOST ()

CALL SELF%T9%ACDC_HOST ()

CALL SELF%PD9%ACDC_HOST ()

CALL SELF%VD9%ACDC_HOST ()

CALL SELF%NHX9%ACDC_HOST ()

CALL SELF%UR0%ACDC_HOST ()

CALL SELF%VR0%ACDC_HOST ()

CALL SELF%ZR0%ACDC_HOST ()

CALL SELF%WR0%ACDC_HOST ()

CALL SELF%UR00%ACDC_HOST ()

CALL SELF%VR00%ACDC_HOST ()

CALL SELF%ZR00%ACDC_HOST ()

CALL SELF%WR00%ACDC_HOST ()

CALL SELF%WRA%ACDC_HOST ()

CALL SELF%UR9%ACDC_HOST ()

CALL SELF%VR9%ACDC_HOST ()

CALL SELF%DBBC9%ACDC_HOST ()

CALL SELF%DPHI9%ACDC_HOST ()

CALL SELF%GWS9%ACDC_HOST ()

CALL SELF%U0%ACDC_HOST ()

CALL SELF%V0%ACDC_HOST ()

CALL SELF%T0%ACDC_HOST ()

CALL SELF%PD0%ACDC_HOST ()

CALL SELF%VD0%ACDC_HOST ()

CALL SELF%C9%ACDC_HOST ()

CALL SELF%SP9%ACDC_HOST ()

CALL SELF%SP0%ACDC_HOST ()

CALL SELF%C0%ACDC_HOST ()

CALL SELF%UP9%ACDC_HOST ()

CALL SELF%VP9%ACDC_HOST ()

CALL SELF%TP9%ACDC_HOST ()

CALL SELF%U9_SI%ACDC_HOST ()

CALL SELF%V9_SI%ACDC_HOST ()

CALL SELF%T9_SI%ACDC_HOST ()

CALL SELF%PD9_SI%ACDC_HOST ()

CALL SELF%VD9_SI%ACDC_HOST ()

CALL SELF%C9_SI%ACDC_HOST ()

CALL SELF%UF9%ACDC_HOST ()

CALL SELF%VF9%ACDC_HOST ()

CALL SELF%TF9%ACDC_HOST ()

CALL SELF%VDF9%ACDC_HOST ()

CALL SELF%U9_NL%ACDC_HOST ()

CALL SELF%V9_NL%ACDC_HOST ()

CALL SELF%T9_NL%ACDC_HOST ()

CALL SELF%PD9_NL%ACDC_HOST ()

CALL SELF%VD9_NL%ACDC_HOST ()

CALL SELF%C9_NL%ACDC_HOST ()

CALL SELF%ZR9%ACDC_HOST ()

CALL SELF%Z9%ACDC_HOST ()

CALL SELF%Z0%ACDC_HOST ()

CALL SELF%ZP9%ACDC_HOST ()

CALL SELF%Q%ACDC_HOST ()

CALL SELF%I%ACDC_HOST ()

CALL SELF%L%ACDC_HOST ()

CALL SELF%IMF%ACDC_HOST ()

CALL SELF%LMF%ACDC_HOST ()

CALL SELF%LCONV%ACDC_HOST ()

CALL SELF%ICONV%ACDC_HOST ()

CALL SELF%RCONV%ACDC_HOST ()

CALL SELF%SCONV%ACDC_HOST ()

CALL SELF%IRAD%ACDC_HOST ()

CALL SELF%LRAD%ACDC_HOST ()

CALL SELF%S%ACDC_HOST ()

CALL SELF%R%ACDC_HOST ()

CALL SELF%G%ACDC_HOST ()

CALL SELF%H%ACDC_HOST ()

CALL SELF%TKE%ACDC_HOST ()

CALL SELF%TTE%ACDC_HOST ()

CALL SELF%EFB1%ACDC_HOST ()

CALL SELF%EFB2%ACDC_HOST ()

CALL SELF%EFB3%ACDC_HOST ()

CALL SELF%A%ACDC_HOST ()

CALL SELF%AMF%ACDC_HOST ()

CALL SELF%O3%ACDC_HOST ()

CALL SELF%SRC%ACDC_HOST ()

CALL SELF%MXL%ACDC_HOST ()

CALL SELF%SHTUR%ACDC_HOST ()

CALL SELF%FQTUR%ACDC_HOST ()

CALL SELF%FSTUR%ACDC_HOST ()

CALL SELF%CPF%ACDC_HOST ()

CALL SELF%SPF%ACDC_HOST ()

CALL SELF%CVGQ%ACDC_HOST ()

CALL SELF%QVA%ACDC_HOST ()

LGHG = ALLOCATED (SELF%GHG)
IF (LGHG) THEN
  DO J1 = LBOUND (SELF%GHG, 1), UBOUND (SELF%GHG, 1)
    CALL SELF%GHG (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LCHEM = ALLOCATED (SELF%CHEM)
IF (LCHEM) THEN
  DO J1 = LBOUND (SELF%CHEM, 1), UBOUND (SELF%CHEM, 1)
    CALL SELF%CHEM (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LAERO = ALLOCATED (SELF%AERO)
IF (LAERO) THEN
  DO J1 = LBOUND (SELF%AERO, 1), UBOUND (SELF%AERO, 1)
    CALL SELF%AERO (J1)%ACDC_HOST ()
  ENDDO
ENDIF

CALL SELF%LRCH4%ACDC_HOST ()

LFORC = ALLOCATED (SELF%FORC)
IF (LFORC) THEN
  DO J1 = LBOUND (SELF%FORC, 1), UBOUND (SELF%FORC, 1)
    CALL SELF%FORC (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LEZDIAG = ALLOCATED (SELF%EZDIAG)
IF (LEZDIAG) THEN
  DO J1 = LBOUND (SELF%EZDIAG, 1), UBOUND (SELF%EZDIAG, 1)
    CALL SELF%EZDIAG (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LERA40 = ALLOCATED (SELF%ERA40)
IF (LERA40) THEN
  DO J1 = LBOUND (SELF%ERA40, 1), UBOUND (SELF%ERA40, 1)
    CALL SELF%ERA40 (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LNOGW = ALLOCATED (SELF%NOGW)
IF (LNOGW) THEN
  DO J1 = LBOUND (SELF%NOGW, 1), UBOUND (SELF%NOGW, 1)
    CALL SELF%NOGW (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LEMIS3D = ALLOCATED (SELF%EMIS3D)
IF (LEMIS3D) THEN
  DO J1 = LBOUND (SELF%EMIS3D, 1), UBOUND (SELF%EMIS3D, 1)
    CALL SELF%EMIS3D (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LEDRP = ALLOCATED (SELF%EDRP)
IF (LEDRP) THEN
  DO J1 = LBOUND (SELF%EDRP, 1), UBOUND (SELF%EDRP, 1)
    CALL SELF%EDRP (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LSLDIA = ALLOCATED (SELF%SLDIA)
IF (LSLDIA) THEN
  DO J1 = LBOUND (SELF%SLDIA, 1), UBOUND (SELF%SLDIA, 1)
    CALL SELF%SLDIA (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LAERAOT = ALLOCATED (SELF%AERAOT)
IF (LAERAOT) THEN
  DO J1 = LBOUND (SELF%AERAOT, 1), UBOUND (SELF%AERAOT, 1)
    CALL SELF%AERAOT (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LAERLISI = ALLOCATED (SELF%AERLISI)
IF (LAERLISI) THEN
  DO J1 = LBOUND (SELF%AERLISI, 1), UBOUND (SELF%AERLISI, 1)
    CALL SELF%AERLISI (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LAEROUT = ALLOCATED (SELF%AEROUT)
IF (LAEROUT) THEN
  DO J1 = LBOUND (SELF%AEROUT, 1), UBOUND (SELF%AEROUT, 1)
    CALL SELF%AEROUT (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LAEROCLIM = ALLOCATED (SELF%AEROCLIM)
IF (LAEROCLIM) THEN
  DO J1 = LBOUND (SELF%AEROCLIM, 1), UBOUND (SELF%AEROCLIM, 1)
    CALL SELF%AEROCLIM (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LUVP = ALLOCATED (SELF%UVP)
IF (LUVP) THEN
  DO J1 = LBOUND (SELF%UVP, 1), UBOUND (SELF%UVP, 1)
    CALL SELF%UVP (J1)%ACDC_HOST ()
  ENDDO
ENDIF

CALL SELF%PHYCTY%ACDC_HOST ()

CALL SELF%RSPEC%ACDC_HOST ()

CALL SELF%SDSAT%ACDC_HOST ()

CALL SELF%CVV%ACDC_HOST ()

CALL SELF%RKTH%ACDC_HOST ()

CALL SELF%RKTQV%ACDC_HOST ()

CALL SELF%RKTQC%ACDC_HOST ()

CALL SELF%UOM%ACDC_HOST ()

CALL SELF%UAL%ACDC_HOST ()

CALL SELF%DOM%ACDC_HOST ()

CALL SELF%DAL%ACDC_HOST ()

CALL SELF%UEN%ACDC_HOST ()

CALL SELF%UNEBH%ACDC_HOST ()

LLIMA = ALLOCATED (SELF%LIMA)
IF (LLIMA) THEN
  DO J1 = LBOUND (SELF%LIMA, 1), UBOUND (SELF%LIMA, 1)
    CALL SELF%LIMA (J1)%ACDC_HOST ()
  ENDDO
ENDIF

CALL SELF%FSD%ACDC_HOST ()

LEXT = ALLOCATED (SELF%EXT)
IF (LEXT) THEN
  DO J1 = LBOUND (SELF%EXT, 1), UBOUND (SELF%EXT, 1)
    CALL SELF%EXT (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LGFL = ALLOCATED (SELF%GFL)
IF (LGFL) THEN
  DO J1 = LBOUND (SELF%GFL, 1), UBOUND (SELF%GFL, 1)
    CALL SELF%GFL (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LY2FSL = ALLOCATED (SELF%Y2FSL)
IF (LY2FSL) THEN
  DO J1 = LBOUND (SELF%Y2FSL, 1), UBOUND (SELF%Y2FSL, 1)
    CALL SELF%Y2FSL (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LY3FSL = ALLOCATED (SELF%Y3FSL)
IF (LY3FSL) THEN
  DO J1 = LBOUND (SELF%Y3FSL, 1), UBOUND (SELF%Y3FSL, 1)
    CALL SELF%Y3FSL (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LY2FSLA = ALLOCATED (SELF%Y2FSLA)
IF (LY2FSLA) THEN
  DO J1 = LBOUND (SELF%Y2FSLA, 1), UBOUND (SELF%Y2FSLA, 1)
    CALL SELF%Y2FSLA (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LY3FSLA = ALLOCATED (SELF%Y3FSLA)
IF (LY3FSLA) THEN
  DO J1 = LBOUND (SELF%Y3FSLA, 1), UBOUND (SELF%Y3FSLA, 1)
    CALL SELF%Y3FSLA (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LY2FSLB = ALLOCATED (SELF%Y2FSLB)
IF (LY2FSLB) THEN
  DO J1 = LBOUND (SELF%Y2FSLB, 1), UBOUND (SELF%Y2FSLB, 1)
    CALL SELF%Y2FSLB (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LY3FSLB = ALLOCATED (SELF%Y3FSLB)
IF (LY3FSLB) THEN
  DO J1 = LBOUND (SELF%Y3FSLB, 1), UBOUND (SELF%Y3FSLB, 1)
    CALL SELF%Y3FSLB (J1)%ACDC_HOST ()
  ENDDO
ENDIF

END SUBROUTINE

END SUBMODULE
