SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_VVD_OPTS_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_CPG_SURF_VVD_OPTS_TYPE (SELF)

IMPLICIT NONE
CLASS (CPG_SURF_VVD_OPTS_TYPE), TARGET :: SELF

CALL SELF%YARG%ACDC_HOST ()

CALL SELF%YSAB%ACDC_HOST ()

CALL SELF%YD2%ACDC_HOST ()

CALL SELF%YIVEG%ACDC_HOST ()

CALL SELF%YRSMIN%ACDC_HOST ()

CALL SELF%YLAI%ACDC_HOST ()

CALL SELF%YHV%ACDC_HOST ()

CALL SELF%YZ0H%ACDC_HOST ()

CALL SELF%YALS%ACDC_HOST ()

CALL SELF%YALV%ACDC_HOST ()

END SUBROUTINE

END SUBMODULE
