SUBMODULE (CPG_TYPE_MOD) CPG_TYPE_MOD_CPG_RCP_TYPE_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_CPG_RCP_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (CPG_RCP_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_CP, LF_KAP, LF_R
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LF_CP = ASSOCIATED (SELF%F_CP)
IF (LF_CP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_CP)
  !$ACC ENTER DATA ATTACH (SELF%F_CP)
ENDIF

LF_R = ASSOCIATED (SELF%F_R)
IF (LF_R .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_R)
  !$ACC ENTER DATA ATTACH (SELF%F_R)
ENDIF

LF_KAP = ASSOCIATED (SELF%F_KAP)
IF (LF_KAP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_KAP)
  !$ACC ENTER DATA ATTACH (SELF%F_KAP)
ENDIF

END SUBROUTINE

END SUBMODULE
