MODULE CPG_GFL_TYPE_MOD

!$ACDC methods --methods-list=host --skip-components cpg --field-api --field-api-class cpg


USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_REGISTRY_MOD
USE PARKIND1, ONLY : JPRB, JPIM, JPIB

IMPLICIT NONE

TYPE CPG_GFL_3D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:, :) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P => NULL ()
CONTAINS
PROCEDURE :: ACDC_HOST => ACDC_HOST_CPG_GFL_3D_TYPE
END TYPE CPG_GFL_3D_TYPE


TYPE CPG_GFL_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()

  TYPE (CPG_GFL_3D_TYPE) :: Q
  TYPE (CPG_GFL_3D_TYPE) :: I
  TYPE (CPG_GFL_3D_TYPE) :: L
  TYPE (CPG_GFL_3D_TYPE) :: IMF
  TYPE (CPG_GFL_3D_TYPE) :: LMF
  TYPE (CPG_GFL_3D_TYPE) :: LCONV
  TYPE (CPG_GFL_3D_TYPE) :: ICONV
  TYPE (CPG_GFL_3D_TYPE) :: RCONV
  TYPE (CPG_GFL_3D_TYPE) :: SCONV
  TYPE (CPG_GFL_3D_TYPE) :: IRAD
  TYPE (CPG_GFL_3D_TYPE) :: LRAD
  TYPE (CPG_GFL_3D_TYPE) :: S
  TYPE (CPG_GFL_3D_TYPE) :: R
  TYPE (CPG_GFL_3D_TYPE) :: G
  TYPE (CPG_GFL_3D_TYPE) :: H
  TYPE (CPG_GFL_3D_TYPE) :: TKE
  TYPE (CPG_GFL_3D_TYPE) :: TTE
  TYPE (CPG_GFL_3D_TYPE) :: EFB1
  TYPE (CPG_GFL_3D_TYPE) :: EFB2
  TYPE (CPG_GFL_3D_TYPE) :: EFB3
  TYPE (CPG_GFL_3D_TYPE) :: A
  TYPE (CPG_GFL_3D_TYPE) :: AMF
  TYPE (CPG_GFL_3D_TYPE) :: O3
  TYPE (CPG_GFL_3D_TYPE) :: SRC
  TYPE (CPG_GFL_3D_TYPE) :: MXL
  TYPE (CPG_GFL_3D_TYPE) :: SHTUR
  TYPE (CPG_GFL_3D_TYPE) :: FQTUR
  TYPE (CPG_GFL_3D_TYPE) :: FSTUR
  TYPE (CPG_GFL_3D_TYPE) :: CPF
  TYPE (CPG_GFL_3D_TYPE) :: SPF
  TYPE (CPG_GFL_3D_TYPE) :: CVGQ
  TYPE (CPG_GFL_3D_TYPE) :: QVA
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: GHG (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: CHEM (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: AERO (:)
  TYPE (CPG_GFL_3D_TYPE) :: LRCH4
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: FORC (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: EZDIAG (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: ERA40 (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: NOGW (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: EMIS3D (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: EDRP (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: SLDIA (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: AERAOT (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: AERLISI (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: AEROUT (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: AEROCLIM (:)
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: UVP (:)
  TYPE (CPG_GFL_3D_TYPE) :: PHYCTY
  TYPE (CPG_GFL_3D_TYPE) :: RSPEC
  TYPE (CPG_GFL_3D_TYPE) :: SDSAT
  TYPE (CPG_GFL_3D_TYPE) :: CVV
  TYPE (CPG_GFL_3D_TYPE) :: RKTH
  TYPE (CPG_GFL_3D_TYPE) :: RKTQV
  TYPE (CPG_GFL_3D_TYPE) :: RKTQC
  TYPE (CPG_GFL_3D_TYPE) :: UOM
  TYPE (CPG_GFL_3D_TYPE) :: UAL
  TYPE (CPG_GFL_3D_TYPE) :: DOM
  TYPE (CPG_GFL_3D_TYPE) :: DAL
  TYPE (CPG_GFL_3D_TYPE) :: UEN
  TYPE (CPG_GFL_3D_TYPE) :: UNEBH
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: LIMA (:)
  TYPE (CPG_GFL_3D_TYPE) :: FSD
  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: EXT (:)

  TYPE (CPG_GFL_3D_TYPE), ALLOCATABLE :: GFL (:)
CONTAINS
  PROCEDURE :: INIT_ => CPG_GFL_TYPE_INIT_
  PROCEDURE :: INIT => CPG_GFL_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_GFL_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_GFL_TYPE_FINAL
PROCEDURE :: ACDC_HOST => ACDC_HOST_CPG_GFL_TYPE
END TYPE CPG_GFL_TYPE

TYPE, EXTENDS (CPG_GFL_TYPE) :: CPG_GFLSL_TYPE
CONTAINS
  PROCEDURE :: INIT => CPG_GFLSL_TYPE_INIT
PROCEDURE :: ACDC_HOST => ACDC_HOST_CPG_GFLSL_TYPE
END TYPE CPG_GFLSL_TYPE

REAL (KIND=JPRB), TARGET, SAVE:: ZDUM2(1,1), ZDUM3(1,1,1)

INTERFACE

MODULE SUBROUTINE ACDC_HOST_CPG_GFL_3D_TYPE (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (CPG_GFL_3D_TYPE), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_CPG_GFL_TYPE (SELF)

IMPLICIT NONE
CLASS (CPG_GFL_TYPE), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_CPG_GFLSL_TYPE (SELF)

IMPLICIT NONE
CLASS (CPG_GFLSL_TYPE), TARGET :: SELF
END SUBROUTINE


END INTERFACE

CONTAINS

SUBROUTINE CPG_GFL_TYPE_INIT (SELF, REGISTRY, NLEV, &
                             & YGFL, PERSISTENT, PGFL, &
                             & KBLKMIN, KBLKMAX)

USE OML_MOD, ONLY: OML_MAX_THREADS
USE YOM_YGFL, ONLY: TYPE_GFLD

CLASS (CPG_GFL_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TYPE_GFLD),                   INTENT (IN)    :: YGFL
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PGFL (:, :, :, :)
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

CALL SELF%INIT_ (REGISTRY, NLEV, YGFL, PERSISTENT, PGFL=PGFL, LDSL=.FALSE., KBLKMIN=KBLKMIN, KBLKMAX=KBLKMAX)

END SUBROUTINE

SUBROUTINE CPG_GFLSL_TYPE_INIT (SELF, REGISTRY, NLEV, &
                              & YGFL, PERSISTENT, PGFL, &
                              & KBLKMIN, KBLKMAX)

USE OML_MOD, ONLY: OML_MAX_THREADS
USE YOM_YGFL, ONLY: TYPE_GFLD

CLASS (CPG_GFLSL_TYPE)                        :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TYPE_GFLD),                   INTENT (IN)    :: YGFL
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PGFL (:, :, :, :)
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

CALL SELF%INIT_ (REGISTRY, NLEV, YGFL, PERSISTENT, PGFL=PGFL, LDSL=.TRUE., KBLKMIN=KBLKMIN, KBLKMAX=KBLKMAX)

END SUBROUTINE

SUBROUTINE CPG_GFL_TYPE_INIT_ (SELF, REGISTRY, NLEV, &
                             & YGFL, PERSISTENT, PGFL, LDSL, &
                             & KBLKMIN, KBLKMAX)

USE OML_MOD, ONLY: OML_MAX_THREADS
USE YOM_YGFL, ONLY: TYPE_GFLD

USE FIELD_DEFAULTS_MODULE

CLASS (CPG_GFL_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TYPE_GFLD),                   INTENT (IN)    :: YGFL
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PGFL (:, :, :, :)
LOGICAL,                            INTENT (IN)    :: LDSL
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

LOGICAL :: LLPERSISTENT
INTEGER (KIND=JPIM) :: ICOUNT, ISIZE, JFLD, IP
LOGICAL :: LLSL
INTEGER (KIND=JPIM) :: IBLKMIN, IBLKMAX
LOGICAL :: LLINITIALIZED
LOGICAL :: LLSYNC_ON_FINAL

LLSL = LDSL

IF (LLSL) THEN
  ISIZE = YGFL%NDIMSLP
ELSE
  ISIZE = YGFL%NUMFLDS
ENDIF

LLPERSISTENT = .FALSE.
IF (PRESENT (PERSISTENT)) LLPERSISTENT = PERSISTENT

IBLKMIN = 1
IF (PRESENT (KBLKMIN)) IBLKMIN = KBLKMIN
IBLKMAX = REGISTRY%GEOM%YRDIM%NGPBLKS
IF (PRESENT (KBLKMAX)) IBLKMAX = KBLKMAX

LLINITIALIZED = .FALSE.

IF (PRESENT (PGFL)) THEN
  SELF%ZDATA => PGFL
  SELF%LOWNED = .FALSE.
  LLPERSISTENT = .TRUE.
  LLINITIALIZED = .TRUE.
ELSEIF (LLPERSISTENT) THEN
  ALLOCATE (SELF%ZDATA (REGISTRY%GEOM%YRDIM%NPROMA, NLEV, ISIZE, IBLKMIN:IBLKMAX))
  IF (USE_INIT_DEBUG_VALUE) THEN
    SELF%ZDATA = INIT_DEBUG_VALUE_JPRB
    LLINITIALIZED = .TRUE.
  ENDIF
  SELF%LOWNED = .TRUE.
ELSE
  ALLOCATE (SELF%ZDATA (REGISTRY%GEOM%YRDIM%NPROMA, NLEV, ISIZE, OML_MAX_THREADS ()))
  IF (USE_INIT_DEBUG_VALUE) THEN
    SELF%ZDATA = INIT_DEBUG_VALUE_JPRB
    LLINITIALIZED = .TRUE.
  ENDIF
  SELF%LOWNED = .TRUE.
ENDIF

CALL FIELD_NEW (SELF%F_DATA, DATA=SELF%ZDATA, PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, 1, IBLKMIN])

ICOUNT = 0

LLSYNC_ON_FINAL = .NOT. SELF%LOWNED


IP = MERGE (YGFL%YQ%MPSLP, YGFL%YQ%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YQ%MP > 0) THEN  
  CALL FIELD_NEW (SELF%Q%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YI%MPSLP, YGFL%YI%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YI%MP > 0) THEN  
  CALL FIELD_NEW (SELF%I%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YL%MPSLP, YGFL%YL%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YL%MP > 0) THEN  
  CALL FIELD_NEW (SELF%L%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YIMF%MPSLP, YGFL%YIMF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YIMF%MP > 0) THEN  
  CALL FIELD_NEW (SELF%IMF%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YLMF%MPSLP, YGFL%YLMF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YLMF%MP > 0) THEN  
  CALL FIELD_NEW (SELF%LMF%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YLCONV%MPSLP, YGFL%YLCONV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YLCONV%MP > 0) THEN  
  CALL FIELD_NEW (SELF%LCONV%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YICONV%MPSLP, YGFL%YICONV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YICONV%MP > 0) THEN  
  CALL FIELD_NEW (SELF%ICONV%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YRCONV%MPSLP, YGFL%YRCONV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YRCONV%MP > 0) THEN  
  CALL FIELD_NEW (SELF%RCONV%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YSCONV%MPSLP, YGFL%YSCONV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YSCONV%MP > 0) THEN  
  CALL FIELD_NEW (SELF%SCONV%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YIRAD%MPSLP, YGFL%YIRAD%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YIRAD%MP > 0) THEN  
  CALL FIELD_NEW (SELF%IRAD%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YLRAD%MPSLP, YGFL%YLRAD%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YLRAD%MP > 0) THEN  
  CALL FIELD_NEW (SELF%LRAD%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YS%MPSLP, YGFL%YS%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YS%MP > 0) THEN  
  CALL FIELD_NEW (SELF%S%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YR%MPSLP, YGFL%YR%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YR%MP > 0) THEN  
  CALL FIELD_NEW (SELF%R%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YG%MPSLP, YGFL%YG%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YG%MP > 0) THEN  
  CALL FIELD_NEW (SELF%G%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YH%MPSLP, YGFL%YH%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YH%MP > 0) THEN  
  CALL FIELD_NEW (SELF%H%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YTKE%MPSLP, YGFL%YTKE%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YTKE%MP > 0) THEN  
  CALL FIELD_NEW (SELF%TKE%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YTTE%MPSLP, YGFL%YTTE%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YTTE%MP > 0) THEN  
  CALL FIELD_NEW (SELF%TTE%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YEFB1%MPSLP, YGFL%YEFB1%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YEFB1%MP > 0) THEN  
  CALL FIELD_NEW (SELF%EFB1%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YEFB2%MPSLP, YGFL%YEFB2%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YEFB2%MP > 0) THEN  
  CALL FIELD_NEW (SELF%EFB2%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YEFB3%MPSLP, YGFL%YEFB3%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YEFB3%MP > 0) THEN  
  CALL FIELD_NEW (SELF%EFB3%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YA%MPSLP, YGFL%YA%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YA%MP > 0) THEN  
  CALL FIELD_NEW (SELF%A%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YAMF%MPSLP, YGFL%YAMF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YAMF%MP > 0) THEN  
  CALL FIELD_NEW (SELF%AMF%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YO3%MPSLP, YGFL%YO3%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YO3%MP > 0) THEN  
  CALL FIELD_NEW (SELF%O3%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YSRC%MPSLP, YGFL%YSRC%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YSRC%MP > 0) THEN  
  CALL FIELD_NEW (SELF%SRC%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YMXL%MPSLP, YGFL%YMXL%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YMXL%MP > 0) THEN  
  CALL FIELD_NEW (SELF%MXL%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YSHTUR%MPSLP, YGFL%YSHTUR%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YSHTUR%MP > 0) THEN  
  CALL FIELD_NEW (SELF%SHTUR%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YFQTUR%MPSLP, YGFL%YFQTUR%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YFQTUR%MP > 0) THEN  
  CALL FIELD_NEW (SELF%FQTUR%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YFSTUR%MPSLP, YGFL%YFSTUR%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YFSTUR%MP > 0) THEN  
  CALL FIELD_NEW (SELF%FSTUR%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YCPF%MPSLP, YGFL%YCPF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YCPF%MP > 0) THEN  
  CALL FIELD_NEW (SELF%CPF%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YSPF%MPSLP, YGFL%YSPF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YSPF%MP > 0) THEN  
  CALL FIELD_NEW (SELF%SPF%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YCVGQ%MPSLP, YGFL%YCVGQ%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YCVGQ%MP > 0) THEN  
  CALL FIELD_NEW (SELF%CVGQ%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YQVA%MPSLP, YGFL%YQVA%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YQVA%MP > 0) THEN  
  CALL FIELD_NEW (SELF%QVA%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IF (ASSOCIATED (YGFL%YGHG)) THEN
  IF (SIZE (YGFL%YGHG) > 0) THEN
    ALLOCATE (SELF%GHG(SIZE (YGFL%YGHG)))
    DO JFLD = 1, SIZE (YGFL%YGHG)
      IP = MERGE (YGFL%YGHG (JFLD)%MPSLP, YGFL%YGHG (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YGHG (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%GHG(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YCHEM)) THEN
  IF (SIZE (YGFL%YCHEM) > 0) THEN
    ALLOCATE (SELF%CHEM(SIZE (YGFL%YCHEM)))
    DO JFLD = 1, SIZE (YGFL%YCHEM)
      IP = MERGE (YGFL%YCHEM (JFLD)%MPSLP, YGFL%YCHEM (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YCHEM (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%CHEM(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YAERO)) THEN
  IF (SIZE (YGFL%YAERO) > 0) THEN
    ALLOCATE (SELF%AERO(SIZE (YGFL%YAERO)))
    DO JFLD = 1, SIZE (YGFL%YAERO)
      IP = MERGE (YGFL%YAERO (JFLD)%MPSLP, YGFL%YAERO (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YAERO (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%AERO(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IP = MERGE (YGFL%YLRCH4%MPSLP, YGFL%YLRCH4%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YLRCH4%MP > 0) THEN  
  CALL FIELD_NEW (SELF%LRCH4%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IF (ASSOCIATED (YGFL%YFORC)) THEN
  IF (SIZE (YGFL%YFORC) > 0) THEN
    ALLOCATE (SELF%FORC(SIZE (YGFL%YFORC)))
    DO JFLD = 1, SIZE (YGFL%YFORC)
      IP = MERGE (YGFL%YFORC (JFLD)%MPSLP, YGFL%YFORC (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YFORC (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%FORC(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YEZDIAG)) THEN
  IF (SIZE (YGFL%YEZDIAG) > 0) THEN
    ALLOCATE (SELF%EZDIAG(SIZE (YGFL%YEZDIAG)))
    DO JFLD = 1, SIZE (YGFL%YEZDIAG)
      IP = MERGE (YGFL%YEZDIAG (JFLD)%MPSLP, YGFL%YEZDIAG (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YEZDIAG (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%EZDIAG(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YERA40)) THEN
  IF (SIZE (YGFL%YERA40) > 0) THEN
    ALLOCATE (SELF%ERA40(SIZE (YGFL%YERA40)))
    DO JFLD = 1, SIZE (YGFL%YERA40)
      IP = MERGE (YGFL%YERA40 (JFLD)%MPSLP, YGFL%YERA40 (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YERA40 (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%ERA40(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YNOGW)) THEN
  IF (SIZE (YGFL%YNOGW) > 0) THEN
    ALLOCATE (SELF%NOGW(SIZE (YGFL%YNOGW)))
    DO JFLD = 1, SIZE (YGFL%YNOGW)
      IP = MERGE (YGFL%YNOGW (JFLD)%MPSLP, YGFL%YNOGW (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YNOGW (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%NOGW(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YEMIS3D)) THEN
  IF (SIZE (YGFL%YEMIS3D) > 0) THEN
    ALLOCATE (SELF%EMIS3D(SIZE (YGFL%YEMIS3D)))
    DO JFLD = 1, SIZE (YGFL%YEMIS3D)
      IP = MERGE (YGFL%YEMIS3D (JFLD)%MPSLP, YGFL%YEMIS3D (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YEMIS3D (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%EMIS3D(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YEDRP)) THEN
  IF (SIZE (YGFL%YEDRP) > 0) THEN
    ALLOCATE (SELF%EDRP(SIZE (YGFL%YEDRP)))
    DO JFLD = 1, SIZE (YGFL%YEDRP)
      IP = MERGE (YGFL%YEDRP (JFLD)%MPSLP, YGFL%YEDRP (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YEDRP (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%EDRP(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YSLDIA)) THEN
  IF (SIZE (YGFL%YSLDIA) > 0) THEN
    ALLOCATE (SELF%SLDIA(SIZE (YGFL%YSLDIA)))
    DO JFLD = 1, SIZE (YGFL%YSLDIA)
      IP = MERGE (YGFL%YSLDIA (JFLD)%MPSLP, YGFL%YSLDIA (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YSLDIA (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%SLDIA(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YAERAOT)) THEN
  IF (SIZE (YGFL%YAERAOT) > 0) THEN
    ALLOCATE (SELF%AERAOT(SIZE (YGFL%YAERAOT)))
    DO JFLD = 1, SIZE (YGFL%YAERAOT)
      IP = MERGE (YGFL%YAERAOT (JFLD)%MPSLP, YGFL%YAERAOT (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YAERAOT (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%AERAOT(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YAERLISI)) THEN
  IF (SIZE (YGFL%YAERLISI) > 0) THEN
    ALLOCATE (SELF%AERLISI(SIZE (YGFL%YAERLISI)))
    DO JFLD = 1, SIZE (YGFL%YAERLISI)
      IP = MERGE (YGFL%YAERLISI (JFLD)%MPSLP, YGFL%YAERLISI (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YAERLISI (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%AERLISI(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YAEROUT)) THEN
  IF (SIZE (YGFL%YAEROUT) > 0) THEN
    ALLOCATE (SELF%AEROUT(SIZE (YGFL%YAEROUT)))
    DO JFLD = 1, SIZE (YGFL%YAEROUT)
      IP = MERGE (YGFL%YAEROUT (JFLD)%MPSLP, YGFL%YAEROUT (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YAEROUT (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%AEROUT(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YAEROCLIM)) THEN
  IF (SIZE (YGFL%YAEROCLIM) > 0) THEN
    ALLOCATE (SELF%AEROCLIM(SIZE (YGFL%YAEROCLIM)))
    DO JFLD = 1, SIZE (YGFL%YAEROCLIM)
      IP = MERGE (YGFL%YAEROCLIM (JFLD)%MPSLP, YGFL%YAEROCLIM (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YAEROCLIM (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%AEROCLIM(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IF (ASSOCIATED (YGFL%YUVP)) THEN
  IF (SIZE (YGFL%YUVP) > 0) THEN
    ALLOCATE (SELF%UVP(SIZE (YGFL%YUVP)))
    DO JFLD = 1, SIZE (YGFL%YUVP)
      IP = MERGE (YGFL%YUVP (JFLD)%MPSLP, YGFL%YUVP (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YUVP (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%UVP(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IP = MERGE (YGFL%YPHYCTY%MPSLP, YGFL%YPHYCTY%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YPHYCTY%MP > 0) THEN  
  CALL FIELD_NEW (SELF%PHYCTY%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YRSPEC%MPSLP, YGFL%YRSPEC%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YRSPEC%MP > 0) THEN  
  CALL FIELD_NEW (SELF%RSPEC%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YSDSAT%MPSLP, YGFL%YSDSAT%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YSDSAT%MP > 0) THEN  
  CALL FIELD_NEW (SELF%SDSAT%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YCVV%MPSLP, YGFL%YCVV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YCVV%MP > 0) THEN  
  CALL FIELD_NEW (SELF%CVV%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YRKTH%MPSLP, YGFL%YRKTH%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YRKTH%MP > 0) THEN  
  CALL FIELD_NEW (SELF%RKTH%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YRKTQV%MPSLP, YGFL%YRKTQV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YRKTQV%MP > 0) THEN  
  CALL FIELD_NEW (SELF%RKTQV%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YRKTQC%MPSLP, YGFL%YRKTQC%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YRKTQC%MP > 0) THEN  
  CALL FIELD_NEW (SELF%RKTQC%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YUOM%MPSLP, YGFL%YUOM%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YUOM%MP > 0) THEN  
  CALL FIELD_NEW (SELF%UOM%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YUAL%MPSLP, YGFL%YUAL%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YUAL%MP > 0) THEN  
  CALL FIELD_NEW (SELF%UAL%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YDOM%MPSLP, YGFL%YDOM%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YDOM%MP > 0) THEN  
  CALL FIELD_NEW (SELF%DOM%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YDAL%MPSLP, YGFL%YDAL%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YDAL%MP > 0) THEN  
  CALL FIELD_NEW (SELF%DAL%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YUEN%MPSLP, YGFL%YUEN%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YUEN%MP > 0) THEN  
  CALL FIELD_NEW (SELF%UEN%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IP = MERGE (YGFL%YUNEBH%MPSLP, YGFL%YUNEBH%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YUNEBH%MP > 0) THEN  
  CALL FIELD_NEW (SELF%UNEBH%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IF (ASSOCIATED (YGFL%YLIMA)) THEN
  IF (SIZE (YGFL%YLIMA) > 0) THEN
    ALLOCATE (SELF%LIMA(SIZE (YGFL%YLIMA)))
    DO JFLD = 1, SIZE (YGFL%YLIMA)
      IP = MERGE (YGFL%YLIMA (JFLD)%MPSLP, YGFL%YLIMA (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YLIMA (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%LIMA(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


IP = MERGE (YGFL%YFSD%MPSLP, YGFL%YFSD%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (YGFL%YFSD%MP > 0) THEN  
  CALL FIELD_NEW (SELF%FSD%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
ENDIF


IF (ASSOCIATED (YGFL%YEXT)) THEN
  IF (SIZE (YGFL%YEXT) > 0) THEN
    ALLOCATE (SELF%EXT(SIZE (YGFL%YEXT)))
    DO JFLD = 1, SIZE (YGFL%YEXT)
      IP = MERGE (YGFL%YEXT (JFLD)%MPSLP, YGFL%YEXT (JFLD)%MP, LLSL)
      ICOUNT = ICOUNT + 1
      IF (YGFL%YEXT (JFLD)%MP > 0) THEN
        CALL FIELD_NEW (SELF%EXT(JFLD)%F_P, DATA=SELF%ZDATA (:, :, IP, :), PERSISTENT=LLPERSISTENT, LBOUNDS=[1, 1, IBLKMIN], &
                      & INITIALIZED=LLINITIALIZED, SYNC_ON_FINAL=LLSYNC_ON_FINAL)
      ENDIF
    ENDDO
  ENDIF
ENDIF


ALLOCATE (SELF%GFL (ICOUNT))

ICOUNT = 0


IP = MERGE (YGFL%YQ%MPSLP, YGFL%YQ%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%Q%F_P
ENDIF


IP = MERGE (YGFL%YI%MPSLP, YGFL%YI%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%I%F_P
ENDIF


IP = MERGE (YGFL%YL%MPSLP, YGFL%YL%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%L%F_P
ENDIF


IP = MERGE (YGFL%YIMF%MPSLP, YGFL%YIMF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%IMF%F_P
ENDIF


IP = MERGE (YGFL%YLMF%MPSLP, YGFL%YLMF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%LMF%F_P
ENDIF


IP = MERGE (YGFL%YLCONV%MPSLP, YGFL%YLCONV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%LCONV%F_P
ENDIF


IP = MERGE (YGFL%YICONV%MPSLP, YGFL%YICONV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%ICONV%F_P
ENDIF


IP = MERGE (YGFL%YRCONV%MPSLP, YGFL%YRCONV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%RCONV%F_P
ENDIF


IP = MERGE (YGFL%YSCONV%MPSLP, YGFL%YSCONV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%SCONV%F_P
ENDIF


IP = MERGE (YGFL%YIRAD%MPSLP, YGFL%YIRAD%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%IRAD%F_P
ENDIF


IP = MERGE (YGFL%YLRAD%MPSLP, YGFL%YLRAD%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%LRAD%F_P
ENDIF


IP = MERGE (YGFL%YS%MPSLP, YGFL%YS%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%S%F_P
ENDIF


IP = MERGE (YGFL%YR%MPSLP, YGFL%YR%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%R%F_P
ENDIF


IP = MERGE (YGFL%YG%MPSLP, YGFL%YG%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%G%F_P
ENDIF


IP = MERGE (YGFL%YH%MPSLP, YGFL%YH%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%H%F_P
ENDIF


IP = MERGE (YGFL%YTKE%MPSLP, YGFL%YTKE%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%TKE%F_P
ENDIF


IP = MERGE (YGFL%YTTE%MPSLP, YGFL%YTTE%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%TTE%F_P
ENDIF


IP = MERGE (YGFL%YEFB1%MPSLP, YGFL%YEFB1%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%EFB1%F_P
ENDIF


IP = MERGE (YGFL%YEFB2%MPSLP, YGFL%YEFB2%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%EFB2%F_P
ENDIF


IP = MERGE (YGFL%YEFB3%MPSLP, YGFL%YEFB3%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%EFB3%F_P
ENDIF


IP = MERGE (YGFL%YA%MPSLP, YGFL%YA%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%A%F_P
ENDIF


IP = MERGE (YGFL%YAMF%MPSLP, YGFL%YAMF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%AMF%F_P
ENDIF


IP = MERGE (YGFL%YO3%MPSLP, YGFL%YO3%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%O3%F_P
ENDIF


IP = MERGE (YGFL%YSRC%MPSLP, YGFL%YSRC%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%SRC%F_P
ENDIF


IP = MERGE (YGFL%YMXL%MPSLP, YGFL%YMXL%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%MXL%F_P
ENDIF


IP = MERGE (YGFL%YSHTUR%MPSLP, YGFL%YSHTUR%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%SHTUR%F_P
ENDIF


IP = MERGE (YGFL%YFQTUR%MPSLP, YGFL%YFQTUR%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%FQTUR%F_P
ENDIF


IP = MERGE (YGFL%YFSTUR%MPSLP, YGFL%YFSTUR%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%FSTUR%F_P
ENDIF


IP = MERGE (YGFL%YCPF%MPSLP, YGFL%YCPF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%CPF%F_P
ENDIF


IP = MERGE (YGFL%YSPF%MPSLP, YGFL%YSPF%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%SPF%F_P
ENDIF


IP = MERGE (YGFL%YCVGQ%MPSLP, YGFL%YCVGQ%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%CVGQ%F_P
ENDIF


IP = MERGE (YGFL%YQVA%MPSLP, YGFL%YQVA%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%QVA%F_P
ENDIF


IF (ASSOCIATED (YGFL%YGHG)) THEN
  DO JFLD = 1, SIZE (YGFL%YGHG)
    IP = MERGE (YGFL%YGHG (JFLD)%MPSLP, YGFL%YGHG (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%GHG(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YCHEM)) THEN
  DO JFLD = 1, SIZE (YGFL%YCHEM)
    IP = MERGE (YGFL%YCHEM (JFLD)%MPSLP, YGFL%YCHEM (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%CHEM(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YAERO)) THEN
  DO JFLD = 1, SIZE (YGFL%YAERO)
    IP = MERGE (YGFL%YAERO (JFLD)%MPSLP, YGFL%YAERO (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%AERO(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IP = MERGE (YGFL%YLRCH4%MPSLP, YGFL%YLRCH4%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%LRCH4%F_P
ENDIF


IF (ASSOCIATED (YGFL%YFORC)) THEN
  DO JFLD = 1, SIZE (YGFL%YFORC)
    IP = MERGE (YGFL%YFORC (JFLD)%MPSLP, YGFL%YFORC (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%FORC(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YEZDIAG)) THEN
  DO JFLD = 1, SIZE (YGFL%YEZDIAG)
    IP = MERGE (YGFL%YEZDIAG (JFLD)%MPSLP, YGFL%YEZDIAG (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%EZDIAG(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YERA40)) THEN
  DO JFLD = 1, SIZE (YGFL%YERA40)
    IP = MERGE (YGFL%YERA40 (JFLD)%MPSLP, YGFL%YERA40 (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%ERA40(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YNOGW)) THEN
  DO JFLD = 1, SIZE (YGFL%YNOGW)
    IP = MERGE (YGFL%YNOGW (JFLD)%MPSLP, YGFL%YNOGW (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%NOGW(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YEMIS3D)) THEN
  DO JFLD = 1, SIZE (YGFL%YEMIS3D)
    IP = MERGE (YGFL%YEMIS3D (JFLD)%MPSLP, YGFL%YEMIS3D (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%EMIS3D(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YEDRP)) THEN
  DO JFLD = 1, SIZE (YGFL%YEDRP)
    IP = MERGE (YGFL%YEDRP (JFLD)%MPSLP, YGFL%YEDRP (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%EDRP(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YSLDIA)) THEN
  DO JFLD = 1, SIZE (YGFL%YSLDIA)
    IP = MERGE (YGFL%YSLDIA (JFLD)%MPSLP, YGFL%YSLDIA (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%SLDIA(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YAERAOT)) THEN
  DO JFLD = 1, SIZE (YGFL%YAERAOT)
    IP = MERGE (YGFL%YAERAOT (JFLD)%MPSLP, YGFL%YAERAOT (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%AERAOT(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YAERLISI)) THEN
  DO JFLD = 1, SIZE (YGFL%YAERLISI)
    IP = MERGE (YGFL%YAERLISI (JFLD)%MPSLP, YGFL%YAERLISI (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%AERLISI(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YAEROUT)) THEN
  DO JFLD = 1, SIZE (YGFL%YAEROUT)
    IP = MERGE (YGFL%YAEROUT (JFLD)%MPSLP, YGFL%YAEROUT (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%AEROUT(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YAEROCLIM)) THEN
  DO JFLD = 1, SIZE (YGFL%YAEROCLIM)
    IP = MERGE (YGFL%YAEROCLIM (JFLD)%MPSLP, YGFL%YAEROCLIM (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%AEROCLIM(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IF (ASSOCIATED (YGFL%YUVP)) THEN
  DO JFLD = 1, SIZE (YGFL%YUVP)
    IP = MERGE (YGFL%YUVP (JFLD)%MPSLP, YGFL%YUVP (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%UVP(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IP = MERGE (YGFL%YPHYCTY%MPSLP, YGFL%YPHYCTY%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%PHYCTY%F_P
ENDIF


IP = MERGE (YGFL%YRSPEC%MPSLP, YGFL%YRSPEC%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%RSPEC%F_P
ENDIF


IP = MERGE (YGFL%YSDSAT%MPSLP, YGFL%YSDSAT%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%SDSAT%F_P
ENDIF


IP = MERGE (YGFL%YCVV%MPSLP, YGFL%YCVV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%CVV%F_P
ENDIF


IP = MERGE (YGFL%YRKTH%MPSLP, YGFL%YRKTH%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%RKTH%F_P
ENDIF


IP = MERGE (YGFL%YRKTQV%MPSLP, YGFL%YRKTQV%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%RKTQV%F_P
ENDIF


IP = MERGE (YGFL%YRKTQC%MPSLP, YGFL%YRKTQC%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%RKTQC%F_P
ENDIF


IP = MERGE (YGFL%YUOM%MPSLP, YGFL%YUOM%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%UOM%F_P
ENDIF


IP = MERGE (YGFL%YUAL%MPSLP, YGFL%YUAL%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%UAL%F_P
ENDIF


IP = MERGE (YGFL%YDOM%MPSLP, YGFL%YDOM%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%DOM%F_P
ENDIF


IP = MERGE (YGFL%YDAL%MPSLP, YGFL%YDAL%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%DAL%F_P
ENDIF


IP = MERGE (YGFL%YUEN%MPSLP, YGFL%YUEN%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%UEN%F_P
ENDIF


IP = MERGE (YGFL%YUNEBH%MPSLP, YGFL%YUNEBH%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%UNEBH%F_P
ENDIF


IF (ASSOCIATED (YGFL%YLIMA)) THEN
  DO JFLD = 1, SIZE (YGFL%YLIMA)
    IP = MERGE (YGFL%YLIMA (JFLD)%MPSLP, YGFL%YLIMA (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%LIMA(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


IP = MERGE (YGFL%YFSD%MPSLP, YGFL%YFSD%MP, LLSL)
ICOUNT = ICOUNT + 1
IF (IP > 0) THEN  
  SELF%GFL(ICOUNT)%F_P => SELF%FSD%F_P
ENDIF


IF (ASSOCIATED (YGFL%YEXT)) THEN
  DO JFLD = 1, SIZE (YGFL%YEXT)
    IP = MERGE (YGFL%YEXT (JFLD)%MPSLP, YGFL%YEXT (JFLD)%MP, LLSL)
    ICOUNT = ICOUNT + 1
    IF (IP > 0) THEN
      SELF%GFL(ICOUNT)%F_P => SELF%EXT(JFLD)%F_P 
    ENDIF
  ENDDO
ENDIF


END SUBROUTINE 

SUBROUTINE CPG_GFL_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_GFL_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX
INTEGER(KIND=JPIM) :: JFLD

IF (ASSOCIATED (SELF%F_DATA)) THEN

  SELF%ZVIEW => SELF%F_DATA%GET_VIEW (BLOCK_INDEX)


  IF (ASSOCIATED (SELF%Q%F_P)) THEN
    IF ((.NOT. SELF%Q%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%Q%P))) THEN
      SELF%Q%P => SELF%Q%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%Q%P)) THEN
    SELF%Q%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%I%F_P)) THEN
    IF ((.NOT. SELF%I%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%I%P))) THEN
      SELF%I%P => SELF%I%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%I%P)) THEN
    SELF%I%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%L%F_P)) THEN
    IF ((.NOT. SELF%L%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%L%P))) THEN
      SELF%L%P => SELF%L%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%L%P)) THEN
    SELF%L%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%IMF%F_P)) THEN
    IF ((.NOT. SELF%IMF%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%IMF%P))) THEN
      SELF%IMF%P => SELF%IMF%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%IMF%P)) THEN
    SELF%IMF%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%LMF%F_P)) THEN
    IF ((.NOT. SELF%LMF%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%LMF%P))) THEN
      SELF%LMF%P => SELF%LMF%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%LMF%P)) THEN
    SELF%LMF%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%LCONV%F_P)) THEN
    IF ((.NOT. SELF%LCONV%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%LCONV%P))) THEN
      SELF%LCONV%P => SELF%LCONV%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%LCONV%P)) THEN
    SELF%LCONV%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%ICONV%F_P)) THEN
    IF ((.NOT. SELF%ICONV%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%ICONV%P))) THEN
      SELF%ICONV%P => SELF%ICONV%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%ICONV%P)) THEN
    SELF%ICONV%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%RCONV%F_P)) THEN
    IF ((.NOT. SELF%RCONV%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%RCONV%P))) THEN
      SELF%RCONV%P => SELF%RCONV%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%RCONV%P)) THEN
    SELF%RCONV%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%SCONV%F_P)) THEN
    IF ((.NOT. SELF%SCONV%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%SCONV%P))) THEN
      SELF%SCONV%P => SELF%SCONV%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%SCONV%P)) THEN
    SELF%SCONV%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%IRAD%F_P)) THEN
    IF ((.NOT. SELF%IRAD%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%IRAD%P))) THEN
      SELF%IRAD%P => SELF%IRAD%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%IRAD%P)) THEN
    SELF%IRAD%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%LRAD%F_P)) THEN
    IF ((.NOT. SELF%LRAD%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%LRAD%P))) THEN
      SELF%LRAD%P => SELF%LRAD%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%LRAD%P)) THEN
    SELF%LRAD%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%S%F_P)) THEN
    IF ((.NOT. SELF%S%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%S%P))) THEN
      SELF%S%P => SELF%S%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%S%P)) THEN
    SELF%S%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%R%F_P)) THEN
    IF ((.NOT. SELF%R%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%R%P))) THEN
      SELF%R%P => SELF%R%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%R%P)) THEN
    SELF%R%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%G%F_P)) THEN
    IF ((.NOT. SELF%G%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%G%P))) THEN
      SELF%G%P => SELF%G%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%G%P)) THEN
    SELF%G%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%H%F_P)) THEN
    IF ((.NOT. SELF%H%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%H%P))) THEN
      SELF%H%P => SELF%H%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%H%P)) THEN
    SELF%H%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%TKE%F_P)) THEN
    IF ((.NOT. SELF%TKE%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%TKE%P))) THEN
      SELF%TKE%P => SELF%TKE%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%TKE%P)) THEN
    SELF%TKE%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%TTE%F_P)) THEN
    IF ((.NOT. SELF%TTE%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%TTE%P))) THEN
      SELF%TTE%P => SELF%TTE%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%TTE%P)) THEN
    SELF%TTE%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%EFB1%F_P)) THEN
    IF ((.NOT. SELF%EFB1%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%EFB1%P))) THEN
      SELF%EFB1%P => SELF%EFB1%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%EFB1%P)) THEN
    SELF%EFB1%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%EFB2%F_P)) THEN
    IF ((.NOT. SELF%EFB2%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%EFB2%P))) THEN
      SELF%EFB2%P => SELF%EFB2%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%EFB2%P)) THEN
    SELF%EFB2%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%EFB3%F_P)) THEN
    IF ((.NOT. SELF%EFB3%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%EFB3%P))) THEN
      SELF%EFB3%P => SELF%EFB3%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%EFB3%P)) THEN
    SELF%EFB3%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%A%F_P)) THEN
    IF ((.NOT. SELF%A%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%A%P))) THEN
      SELF%A%P => SELF%A%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%A%P)) THEN
    SELF%A%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%AMF%F_P)) THEN
    IF ((.NOT. SELF%AMF%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%AMF%P))) THEN
      SELF%AMF%P => SELF%AMF%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%AMF%P)) THEN
    SELF%AMF%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%O3%F_P)) THEN
    IF ((.NOT. SELF%O3%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%O3%P))) THEN
      SELF%O3%P => SELF%O3%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%O3%P)) THEN
    SELF%O3%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%SRC%F_P)) THEN
    IF ((.NOT. SELF%SRC%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%SRC%P))) THEN
      SELF%SRC%P => SELF%SRC%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%SRC%P)) THEN
    SELF%SRC%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%MXL%F_P)) THEN
    IF ((.NOT. SELF%MXL%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%MXL%P))) THEN
      SELF%MXL%P => SELF%MXL%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%MXL%P)) THEN
    SELF%MXL%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%SHTUR%F_P)) THEN
    IF ((.NOT. SELF%SHTUR%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%SHTUR%P))) THEN
      SELF%SHTUR%P => SELF%SHTUR%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%SHTUR%P)) THEN
    SELF%SHTUR%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%FQTUR%F_P)) THEN
    IF ((.NOT. SELF%FQTUR%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%FQTUR%P))) THEN
      SELF%FQTUR%P => SELF%FQTUR%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%FQTUR%P)) THEN
    SELF%FQTUR%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%FSTUR%F_P)) THEN
    IF ((.NOT. SELF%FSTUR%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%FSTUR%P))) THEN
      SELF%FSTUR%P => SELF%FSTUR%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%FSTUR%P)) THEN
    SELF%FSTUR%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%CPF%F_P)) THEN
    IF ((.NOT. SELF%CPF%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%CPF%P))) THEN
      SELF%CPF%P => SELF%CPF%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%CPF%P)) THEN
    SELF%CPF%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%SPF%F_P)) THEN
    IF ((.NOT. SELF%SPF%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%SPF%P))) THEN
      SELF%SPF%P => SELF%SPF%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%SPF%P)) THEN
    SELF%SPF%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%CVGQ%F_P)) THEN
    IF ((.NOT. SELF%CVGQ%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%CVGQ%P))) THEN
      SELF%CVGQ%P => SELF%CVGQ%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%CVGQ%P)) THEN
    SELF%CVGQ%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%QVA%F_P)) THEN
    IF ((.NOT. SELF%QVA%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%QVA%P))) THEN
      SELF%QVA%P => SELF%QVA%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%QVA%P)) THEN
    SELF%QVA%P => ZDUM2
  ENDIF


  IF (ALLOCATED (SELF%GHG)) THEN
    DO JFLD = 1, SIZE (SELF%GHG)
      IF (ASSOCIATED (SELF%GHG(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%GHG(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%GHG(JFLD)%P))) THEN
          SELF%GHG(JFLD)%P => SELF%GHG(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%GHG(JFLD)%P)) THEN
        SELF%GHG(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%CHEM)) THEN
    DO JFLD = 1, SIZE (SELF%CHEM)
      IF (ASSOCIATED (SELF%CHEM(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%CHEM(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%CHEM(JFLD)%P))) THEN
          SELF%CHEM(JFLD)%P => SELF%CHEM(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%CHEM(JFLD)%P)) THEN
        SELF%CHEM(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AERO)) THEN
    DO JFLD = 1, SIZE (SELF%AERO)
      IF (ASSOCIATED (SELF%AERO(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%AERO(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%AERO(JFLD)%P))) THEN
          SELF%AERO(JFLD)%P => SELF%AERO(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%AERO(JFLD)%P)) THEN
        SELF%AERO(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ASSOCIATED (SELF%LRCH4%F_P)) THEN
    IF ((.NOT. SELF%LRCH4%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%LRCH4%P))) THEN
      SELF%LRCH4%P => SELF%LRCH4%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%LRCH4%P)) THEN
    SELF%LRCH4%P => ZDUM2
  ENDIF


  IF (ALLOCATED (SELF%FORC)) THEN
    DO JFLD = 1, SIZE (SELF%FORC)
      IF (ASSOCIATED (SELF%FORC(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%FORC(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%FORC(JFLD)%P))) THEN
          SELF%FORC(JFLD)%P => SELF%FORC(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%FORC(JFLD)%P)) THEN
        SELF%FORC(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%EZDIAG)) THEN
    DO JFLD = 1, SIZE (SELF%EZDIAG)
      IF (ASSOCIATED (SELF%EZDIAG(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%EZDIAG(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%EZDIAG(JFLD)%P))) THEN
          SELF%EZDIAG(JFLD)%P => SELF%EZDIAG(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%EZDIAG(JFLD)%P)) THEN
        SELF%EZDIAG(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%ERA40)) THEN
    DO JFLD = 1, SIZE (SELF%ERA40)
      IF (ASSOCIATED (SELF%ERA40(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%ERA40(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%ERA40(JFLD)%P))) THEN
          SELF%ERA40(JFLD)%P => SELF%ERA40(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%ERA40(JFLD)%P)) THEN
        SELF%ERA40(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%NOGW)) THEN
    DO JFLD = 1, SIZE (SELF%NOGW)
      IF (ASSOCIATED (SELF%NOGW(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%NOGW(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%NOGW(JFLD)%P))) THEN
          SELF%NOGW(JFLD)%P => SELF%NOGW(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%NOGW(JFLD)%P)) THEN
        SELF%NOGW(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%EMIS3D)) THEN
    DO JFLD = 1, SIZE (SELF%EMIS3D)
      IF (ASSOCIATED (SELF%EMIS3D(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%EMIS3D(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%EMIS3D(JFLD)%P))) THEN
          SELF%EMIS3D(JFLD)%P => SELF%EMIS3D(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%EMIS3D(JFLD)%P)) THEN
        SELF%EMIS3D(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%EDRP)) THEN
    DO JFLD = 1, SIZE (SELF%EDRP)
      IF (ASSOCIATED (SELF%EDRP(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%EDRP(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%EDRP(JFLD)%P))) THEN
          SELF%EDRP(JFLD)%P => SELF%EDRP(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%EDRP(JFLD)%P)) THEN
        SELF%EDRP(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%SLDIA)) THEN
    DO JFLD = 1, SIZE (SELF%SLDIA)
      IF (ASSOCIATED (SELF%SLDIA(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%SLDIA(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%SLDIA(JFLD)%P))) THEN
          SELF%SLDIA(JFLD)%P => SELF%SLDIA(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%SLDIA(JFLD)%P)) THEN
        SELF%SLDIA(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AERAOT)) THEN
    DO JFLD = 1, SIZE (SELF%AERAOT)
      IF (ASSOCIATED (SELF%AERAOT(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%AERAOT(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%AERAOT(JFLD)%P))) THEN
          SELF%AERAOT(JFLD)%P => SELF%AERAOT(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%AERAOT(JFLD)%P)) THEN
        SELF%AERAOT(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AERLISI)) THEN
    DO JFLD = 1, SIZE (SELF%AERLISI)
      IF (ASSOCIATED (SELF%AERLISI(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%AERLISI(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%AERLISI(JFLD)%P))) THEN
          SELF%AERLISI(JFLD)%P => SELF%AERLISI(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%AERLISI(JFLD)%P)) THEN
        SELF%AERLISI(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AEROUT)) THEN
    DO JFLD = 1, SIZE (SELF%AEROUT)
      IF (ASSOCIATED (SELF%AEROUT(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%AEROUT(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%AEROUT(JFLD)%P))) THEN
          SELF%AEROUT(JFLD)%P => SELF%AEROUT(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%AEROUT(JFLD)%P)) THEN
        SELF%AEROUT(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AEROCLIM)) THEN
    DO JFLD = 1, SIZE (SELF%AEROCLIM)
      IF (ASSOCIATED (SELF%AEROCLIM(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%AEROCLIM(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%AEROCLIM(JFLD)%P))) THEN
          SELF%AEROCLIM(JFLD)%P => SELF%AEROCLIM(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%AEROCLIM(JFLD)%P)) THEN
        SELF%AEROCLIM(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%UVP)) THEN
    DO JFLD = 1, SIZE (SELF%UVP)
      IF (ASSOCIATED (SELF%UVP(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%UVP(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%UVP(JFLD)%P))) THEN
          SELF%UVP(JFLD)%P => SELF%UVP(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%UVP(JFLD)%P)) THEN
        SELF%UVP(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ASSOCIATED (SELF%PHYCTY%F_P)) THEN
    IF ((.NOT. SELF%PHYCTY%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%PHYCTY%P))) THEN
      SELF%PHYCTY%P => SELF%PHYCTY%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%PHYCTY%P)) THEN
    SELF%PHYCTY%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%RSPEC%F_P)) THEN
    IF ((.NOT. SELF%RSPEC%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%RSPEC%P))) THEN
      SELF%RSPEC%P => SELF%RSPEC%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%RSPEC%P)) THEN
    SELF%RSPEC%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%SDSAT%F_P)) THEN
    IF ((.NOT. SELF%SDSAT%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%SDSAT%P))) THEN
      SELF%SDSAT%P => SELF%SDSAT%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%SDSAT%P)) THEN
    SELF%SDSAT%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%CVV%F_P)) THEN
    IF ((.NOT. SELF%CVV%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%CVV%P))) THEN
      SELF%CVV%P => SELF%CVV%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%CVV%P)) THEN
    SELF%CVV%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%RKTH%F_P)) THEN
    IF ((.NOT. SELF%RKTH%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%RKTH%P))) THEN
      SELF%RKTH%P => SELF%RKTH%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%RKTH%P)) THEN
    SELF%RKTH%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%RKTQV%F_P)) THEN
    IF ((.NOT. SELF%RKTQV%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%RKTQV%P))) THEN
      SELF%RKTQV%P => SELF%RKTQV%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%RKTQV%P)) THEN
    SELF%RKTQV%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%RKTQC%F_P)) THEN
    IF ((.NOT. SELF%RKTQC%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%RKTQC%P))) THEN
      SELF%RKTQC%P => SELF%RKTQC%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%RKTQC%P)) THEN
    SELF%RKTQC%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%UOM%F_P)) THEN
    IF ((.NOT. SELF%UOM%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%UOM%P))) THEN
      SELF%UOM%P => SELF%UOM%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%UOM%P)) THEN
    SELF%UOM%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%UAL%F_P)) THEN
    IF ((.NOT. SELF%UAL%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%UAL%P))) THEN
      SELF%UAL%P => SELF%UAL%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%UAL%P)) THEN
    SELF%UAL%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%DOM%F_P)) THEN
    IF ((.NOT. SELF%DOM%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%DOM%P))) THEN
      SELF%DOM%P => SELF%DOM%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%DOM%P)) THEN
    SELF%DOM%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%DAL%F_P)) THEN
    IF ((.NOT. SELF%DAL%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%DAL%P))) THEN
      SELF%DAL%P => SELF%DAL%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%DAL%P)) THEN
    SELF%DAL%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%UEN%F_P)) THEN
    IF ((.NOT. SELF%UEN%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%UEN%P))) THEN
      SELF%UEN%P => SELF%UEN%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%UEN%P)) THEN
    SELF%UEN%P => ZDUM2
  ENDIF


  IF (ASSOCIATED (SELF%UNEBH%F_P)) THEN
    IF ((.NOT. SELF%UNEBH%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%UNEBH%P))) THEN
      SELF%UNEBH%P => SELF%UNEBH%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%UNEBH%P)) THEN
    SELF%UNEBH%P => ZDUM2
  ENDIF


  IF (ALLOCATED (SELF%LIMA)) THEN
    DO JFLD = 1, SIZE (SELF%LIMA)
      IF (ASSOCIATED (SELF%LIMA(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%LIMA(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%LIMA(JFLD)%P))) THEN
          SELF%LIMA(JFLD)%P => SELF%LIMA(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%LIMA(JFLD)%P)) THEN
        SELF%LIMA(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  IF (ASSOCIATED (SELF%FSD%F_P)) THEN
    IF ((.NOT. SELF%FSD%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%FSD%P))) THEN
      SELF%FSD%P => SELF%FSD%F_P%GET_VIEW (BLOCK_INDEX)
    ENDIF
  ELSEIF (.NOT. ASSOCIATED (SELF%FSD%P)) THEN
    SELF%FSD%P => ZDUM2
  ENDIF


  IF (ALLOCATED (SELF%EXT)) THEN
    DO JFLD = 1, SIZE (SELF%EXT)
      IF (ASSOCIATED (SELF%EXT(JFLD)%F_P)) THEN
        IF ((.NOT. SELF%EXT(JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%EXT(JFLD)%P))) THEN
          SELF%EXT(JFLD)%P => SELF%EXT(JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
        ENDIF
      ELSEIF (.NOT. ASSOCIATED (SELF%EXT(JFLD)%P)) THEN
        SELF%EXT(JFLD)%P => ZDUM2
      ENDIF
    ENDDO
  ENDIF


  DO JFLD = 1, SIZE (SELF%GFL)
    IF (ASSOCIATED (SELF%GFL (JFLD)%F_P)) THEN
      IF ((.NOT. SELF%GFL (JFLD)%F_P%THREAD_BUFFER) .OR. (.NOT. ASSOCIATED (SELF%GFL (JFLD)%P))) THEN
        SELF%GFL (JFLD)%P  => SELF%GFL (JFLD)%F_P%GET_VIEW (BLOCK_INDEX)
      ENDIF
    ELSEIF (.NOT. ASSOCIATED (SELF%GFL (JFLD)%F_P)) THEN
      SELF%GFL (JFLD)%P  => ZDUM2
    ENDIF
  ENDDO

ELSE

  SELF%ZVIEW => ZDUM3


  IF (.NOT. ASSOCIATED (SELF%Q%P)) SELF%Q%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%I%P)) SELF%I%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%L%P)) SELF%L%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%IMF%P)) SELF%IMF%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%LMF%P)) SELF%LMF%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%LCONV%P)) SELF%LCONV%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%ICONV%P)) SELF%ICONV%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%RCONV%P)) SELF%RCONV%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%SCONV%P)) SELF%SCONV%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%IRAD%P)) SELF%IRAD%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%LRAD%P)) SELF%LRAD%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%S%P)) SELF%S%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%R%P)) SELF%R%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%G%P)) SELF%G%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%H%P)) SELF%H%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%TKE%P)) SELF%TKE%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%TTE%P)) SELF%TTE%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%EFB1%P)) SELF%EFB1%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%EFB2%P)) SELF%EFB2%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%EFB3%P)) SELF%EFB3%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%A%P)) SELF%A%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%AMF%P)) SELF%AMF%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%O3%P)) SELF%O3%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%SRC%P)) SELF%SRC%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%MXL%P)) SELF%MXL%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%SHTUR%P)) SELF%SHTUR%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%FQTUR%P)) SELF%FQTUR%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%FSTUR%P)) SELF%FSTUR%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%CPF%P)) SELF%CPF%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%SPF%P)) SELF%SPF%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%CVGQ%P)) SELF%CVGQ%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%QVA%P)) SELF%QVA%P  => ZDUM2


  IF (ALLOCATED (SELF%GHG)) THEN
    DO JFLD = 1, SIZE (SELF%GHG)
      IF (.NOT. ASSOCIATED (SELF%GHG(JFLD)%P)) SELF%GHG(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%CHEM)) THEN
    DO JFLD = 1, SIZE (SELF%CHEM)
      IF (.NOT. ASSOCIATED (SELF%CHEM(JFLD)%P)) SELF%CHEM(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AERO)) THEN
    DO JFLD = 1, SIZE (SELF%AERO)
      IF (.NOT. ASSOCIATED (SELF%AERO(JFLD)%P)) SELF%AERO(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (.NOT. ASSOCIATED (SELF%LRCH4%P)) SELF%LRCH4%P  => ZDUM2


  IF (ALLOCATED (SELF%FORC)) THEN
    DO JFLD = 1, SIZE (SELF%FORC)
      IF (.NOT. ASSOCIATED (SELF%FORC(JFLD)%P)) SELF%FORC(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%EZDIAG)) THEN
    DO JFLD = 1, SIZE (SELF%EZDIAG)
      IF (.NOT. ASSOCIATED (SELF%EZDIAG(JFLD)%P)) SELF%EZDIAG(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%ERA40)) THEN
    DO JFLD = 1, SIZE (SELF%ERA40)
      IF (.NOT. ASSOCIATED (SELF%ERA40(JFLD)%P)) SELF%ERA40(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%NOGW)) THEN
    DO JFLD = 1, SIZE (SELF%NOGW)
      IF (.NOT. ASSOCIATED (SELF%NOGW(JFLD)%P)) SELF%NOGW(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%EMIS3D)) THEN
    DO JFLD = 1, SIZE (SELF%EMIS3D)
      IF (.NOT. ASSOCIATED (SELF%EMIS3D(JFLD)%P)) SELF%EMIS3D(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%EDRP)) THEN
    DO JFLD = 1, SIZE (SELF%EDRP)
      IF (.NOT. ASSOCIATED (SELF%EDRP(JFLD)%P)) SELF%EDRP(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%SLDIA)) THEN
    DO JFLD = 1, SIZE (SELF%SLDIA)
      IF (.NOT. ASSOCIATED (SELF%SLDIA(JFLD)%P)) SELF%SLDIA(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AERAOT)) THEN
    DO JFLD = 1, SIZE (SELF%AERAOT)
      IF (.NOT. ASSOCIATED (SELF%AERAOT(JFLD)%P)) SELF%AERAOT(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AERLISI)) THEN
    DO JFLD = 1, SIZE (SELF%AERLISI)
      IF (.NOT. ASSOCIATED (SELF%AERLISI(JFLD)%P)) SELF%AERLISI(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AEROUT)) THEN
    DO JFLD = 1, SIZE (SELF%AEROUT)
      IF (.NOT. ASSOCIATED (SELF%AEROUT(JFLD)%P)) SELF%AEROUT(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%AEROCLIM)) THEN
    DO JFLD = 1, SIZE (SELF%AEROCLIM)
      IF (.NOT. ASSOCIATED (SELF%AEROCLIM(JFLD)%P)) SELF%AEROCLIM(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (ALLOCATED (SELF%UVP)) THEN
    DO JFLD = 1, SIZE (SELF%UVP)
      IF (.NOT. ASSOCIATED (SELF%UVP(JFLD)%P)) SELF%UVP(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (.NOT. ASSOCIATED (SELF%PHYCTY%P)) SELF%PHYCTY%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%RSPEC%P)) SELF%RSPEC%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%SDSAT%P)) SELF%SDSAT%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%CVV%P)) SELF%CVV%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%RKTH%P)) SELF%RKTH%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%RKTQV%P)) SELF%RKTQV%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%RKTQC%P)) SELF%RKTQC%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%UOM%P)) SELF%UOM%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%UAL%P)) SELF%UAL%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%DOM%P)) SELF%DOM%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%DAL%P)) SELF%DAL%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%UEN%P)) SELF%UEN%P  => ZDUM2


  IF (.NOT. ASSOCIATED (SELF%UNEBH%P)) SELF%UNEBH%P  => ZDUM2


  IF (ALLOCATED (SELF%LIMA)) THEN
    DO JFLD = 1, SIZE (SELF%LIMA)
      IF (.NOT. ASSOCIATED (SELF%LIMA(JFLD)%P)) SELF%LIMA(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


  IF (.NOT. ASSOCIATED (SELF%FSD%P)) SELF%FSD%P  => ZDUM2


  IF (ALLOCATED (SELF%EXT)) THEN
    DO JFLD = 1, SIZE (SELF%EXT)
      IF (.NOT. ASSOCIATED (SELF%EXT(JFLD)%P)) SELF%EXT(JFLD)%P  => ZDUM2
    ENDDO
  ENDIF


ENDIF

END SUBROUTINE CPG_GFL_TYPE_UPDATE_VIEW

SUBROUTINE CPG_GFL_TYPE_FINAL (SELF)
CLASS (CPG_GFL_TYPE)          :: SELF

INTEGER (KIND=JPIM) :: JFLD

IF (ALLOCATED (SELF%GFL)) DEALLOCATE (SELF%GFL)


IF (ALLOCATED (SELF%EXT)) THEN
  DO JFLD = 1, SIZE (SELF%EXT)
    IF (ASSOCIATED (SELF%EXT(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%EXT(JFLD)%F_P) 
    ENDIF
    SELF%EXT(JFLD)%F_P => NULL ()
    SELF%EXT(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%EXT)
ENDIF


IF (ASSOCIATED (SELF%FSD%F_P)) THEN
  CALL FIELD_DELETE (SELF%FSD%F_P) 
ENDIF
SELF%FSD%F_P => NULL ()
SELF%FSD%P => NULL ()


IF (ALLOCATED (SELF%LIMA)) THEN
  DO JFLD = 1, SIZE (SELF%LIMA)
    IF (ASSOCIATED (SELF%LIMA(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%LIMA(JFLD)%F_P) 
    ENDIF
    SELF%LIMA(JFLD)%F_P => NULL ()
    SELF%LIMA(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%LIMA)
ENDIF


IF (ASSOCIATED (SELF%UNEBH%F_P)) THEN
  CALL FIELD_DELETE (SELF%UNEBH%F_P) 
ENDIF
SELF%UNEBH%F_P => NULL ()
SELF%UNEBH%P => NULL ()


IF (ASSOCIATED (SELF%UEN%F_P)) THEN
  CALL FIELD_DELETE (SELF%UEN%F_P) 
ENDIF
SELF%UEN%F_P => NULL ()
SELF%UEN%P => NULL ()


IF (ASSOCIATED (SELF%DAL%F_P)) THEN
  CALL FIELD_DELETE (SELF%DAL%F_P) 
ENDIF
SELF%DAL%F_P => NULL ()
SELF%DAL%P => NULL ()


IF (ASSOCIATED (SELF%DOM%F_P)) THEN
  CALL FIELD_DELETE (SELF%DOM%F_P) 
ENDIF
SELF%DOM%F_P => NULL ()
SELF%DOM%P => NULL ()


IF (ASSOCIATED (SELF%UAL%F_P)) THEN
  CALL FIELD_DELETE (SELF%UAL%F_P) 
ENDIF
SELF%UAL%F_P => NULL ()
SELF%UAL%P => NULL ()


IF (ASSOCIATED (SELF%UOM%F_P)) THEN
  CALL FIELD_DELETE (SELF%UOM%F_P) 
ENDIF
SELF%UOM%F_P => NULL ()
SELF%UOM%P => NULL ()


IF (ASSOCIATED (SELF%RKTQC%F_P)) THEN
  CALL FIELD_DELETE (SELF%RKTQC%F_P) 
ENDIF
SELF%RKTQC%F_P => NULL ()
SELF%RKTQC%P => NULL ()


IF (ASSOCIATED (SELF%RKTQV%F_P)) THEN
  CALL FIELD_DELETE (SELF%RKTQV%F_P) 
ENDIF
SELF%RKTQV%F_P => NULL ()
SELF%RKTQV%P => NULL ()


IF (ASSOCIATED (SELF%RKTH%F_P)) THEN
  CALL FIELD_DELETE (SELF%RKTH%F_P) 
ENDIF
SELF%RKTH%F_P => NULL ()
SELF%RKTH%P => NULL ()


IF (ASSOCIATED (SELF%CVV%F_P)) THEN
  CALL FIELD_DELETE (SELF%CVV%F_P) 
ENDIF
SELF%CVV%F_P => NULL ()
SELF%CVV%P => NULL ()


IF (ASSOCIATED (SELF%SDSAT%F_P)) THEN
  CALL FIELD_DELETE (SELF%SDSAT%F_P) 
ENDIF
SELF%SDSAT%F_P => NULL ()
SELF%SDSAT%P => NULL ()


IF (ASSOCIATED (SELF%RSPEC%F_P)) THEN
  CALL FIELD_DELETE (SELF%RSPEC%F_P) 
ENDIF
SELF%RSPEC%F_P => NULL ()
SELF%RSPEC%P => NULL ()


IF (ASSOCIATED (SELF%PHYCTY%F_P)) THEN
  CALL FIELD_DELETE (SELF%PHYCTY%F_P) 
ENDIF
SELF%PHYCTY%F_P => NULL ()
SELF%PHYCTY%P => NULL ()


IF (ALLOCATED (SELF%UVP)) THEN
  DO JFLD = 1, SIZE (SELF%UVP)
    IF (ASSOCIATED (SELF%UVP(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%UVP(JFLD)%F_P) 
    ENDIF
    SELF%UVP(JFLD)%F_P => NULL ()
    SELF%UVP(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%UVP)
ENDIF


IF (ALLOCATED (SELF%AEROCLIM)) THEN
  DO JFLD = 1, SIZE (SELF%AEROCLIM)
    IF (ASSOCIATED (SELF%AEROCLIM(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%AEROCLIM(JFLD)%F_P) 
    ENDIF
    SELF%AEROCLIM(JFLD)%F_P => NULL ()
    SELF%AEROCLIM(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%AEROCLIM)
ENDIF


IF (ALLOCATED (SELF%AEROUT)) THEN
  DO JFLD = 1, SIZE (SELF%AEROUT)
    IF (ASSOCIATED (SELF%AEROUT(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%AEROUT(JFLD)%F_P) 
    ENDIF
    SELF%AEROUT(JFLD)%F_P => NULL ()
    SELF%AEROUT(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%AEROUT)
ENDIF


IF (ALLOCATED (SELF%AERLISI)) THEN
  DO JFLD = 1, SIZE (SELF%AERLISI)
    IF (ASSOCIATED (SELF%AERLISI(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%AERLISI(JFLD)%F_P) 
    ENDIF
    SELF%AERLISI(JFLD)%F_P => NULL ()
    SELF%AERLISI(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%AERLISI)
ENDIF


IF (ALLOCATED (SELF%AERAOT)) THEN
  DO JFLD = 1, SIZE (SELF%AERAOT)
    IF (ASSOCIATED (SELF%AERAOT(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%AERAOT(JFLD)%F_P) 
    ENDIF
    SELF%AERAOT(JFLD)%F_P => NULL ()
    SELF%AERAOT(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%AERAOT)
ENDIF


IF (ALLOCATED (SELF%SLDIA)) THEN
  DO JFLD = 1, SIZE (SELF%SLDIA)
    IF (ASSOCIATED (SELF%SLDIA(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%SLDIA(JFLD)%F_P) 
    ENDIF
    SELF%SLDIA(JFLD)%F_P => NULL ()
    SELF%SLDIA(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%SLDIA)
ENDIF


IF (ALLOCATED (SELF%EDRP)) THEN
  DO JFLD = 1, SIZE (SELF%EDRP)
    IF (ASSOCIATED (SELF%EDRP(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%EDRP(JFLD)%F_P) 
    ENDIF
    SELF%EDRP(JFLD)%F_P => NULL ()
    SELF%EDRP(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%EDRP)
ENDIF


IF (ALLOCATED (SELF%EMIS3D)) THEN
  DO JFLD = 1, SIZE (SELF%EMIS3D)
    IF (ASSOCIATED (SELF%EMIS3D(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%EMIS3D(JFLD)%F_P) 
    ENDIF
    SELF%EMIS3D(JFLD)%F_P => NULL ()
    SELF%EMIS3D(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%EMIS3D)
ENDIF


IF (ALLOCATED (SELF%NOGW)) THEN
  DO JFLD = 1, SIZE (SELF%NOGW)
    IF (ASSOCIATED (SELF%NOGW(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%NOGW(JFLD)%F_P) 
    ENDIF
    SELF%NOGW(JFLD)%F_P => NULL ()
    SELF%NOGW(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%NOGW)
ENDIF


IF (ALLOCATED (SELF%ERA40)) THEN
  DO JFLD = 1, SIZE (SELF%ERA40)
    IF (ASSOCIATED (SELF%ERA40(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%ERA40(JFLD)%F_P) 
    ENDIF
    SELF%ERA40(JFLD)%F_P => NULL ()
    SELF%ERA40(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%ERA40)
ENDIF


IF (ALLOCATED (SELF%EZDIAG)) THEN
  DO JFLD = 1, SIZE (SELF%EZDIAG)
    IF (ASSOCIATED (SELF%EZDIAG(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%EZDIAG(JFLD)%F_P) 
    ENDIF
    SELF%EZDIAG(JFLD)%F_P => NULL ()
    SELF%EZDIAG(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%EZDIAG)
ENDIF


IF (ALLOCATED (SELF%FORC)) THEN
  DO JFLD = 1, SIZE (SELF%FORC)
    IF (ASSOCIATED (SELF%FORC(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%FORC(JFLD)%F_P) 
    ENDIF
    SELF%FORC(JFLD)%F_P => NULL ()
    SELF%FORC(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%FORC)
ENDIF


IF (ASSOCIATED (SELF%LRCH4%F_P)) THEN
  CALL FIELD_DELETE (SELF%LRCH4%F_P) 
ENDIF
SELF%LRCH4%F_P => NULL ()
SELF%LRCH4%P => NULL ()


IF (ALLOCATED (SELF%AERO)) THEN
  DO JFLD = 1, SIZE (SELF%AERO)
    IF (ASSOCIATED (SELF%AERO(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%AERO(JFLD)%F_P) 
    ENDIF
    SELF%AERO(JFLD)%F_P => NULL ()
    SELF%AERO(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%AERO)
ENDIF


IF (ALLOCATED (SELF%CHEM)) THEN
  DO JFLD = 1, SIZE (SELF%CHEM)
    IF (ASSOCIATED (SELF%CHEM(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%CHEM(JFLD)%F_P) 
    ENDIF
    SELF%CHEM(JFLD)%F_P => NULL ()
    SELF%CHEM(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%CHEM)
ENDIF


IF (ALLOCATED (SELF%GHG)) THEN
  DO JFLD = 1, SIZE (SELF%GHG)
    IF (ASSOCIATED (SELF%GHG(JFLD)%F_P)) THEN
      CALL FIELD_DELETE (SELF%GHG(JFLD)%F_P) 
    ENDIF
    SELF%GHG(JFLD)%F_P => NULL ()
    SELF%GHG(JFLD)%P => NULL ()
  ENDDO 
  DEALLOCATE (SELF%GHG)
ENDIF


IF (ASSOCIATED (SELF%QVA%F_P)) THEN
  CALL FIELD_DELETE (SELF%QVA%F_P) 
ENDIF
SELF%QVA%F_P => NULL ()
SELF%QVA%P => NULL ()


IF (ASSOCIATED (SELF%CVGQ%F_P)) THEN
  CALL FIELD_DELETE (SELF%CVGQ%F_P) 
ENDIF
SELF%CVGQ%F_P => NULL ()
SELF%CVGQ%P => NULL ()


IF (ASSOCIATED (SELF%SPF%F_P)) THEN
  CALL FIELD_DELETE (SELF%SPF%F_P) 
ENDIF
SELF%SPF%F_P => NULL ()
SELF%SPF%P => NULL ()


IF (ASSOCIATED (SELF%CPF%F_P)) THEN
  CALL FIELD_DELETE (SELF%CPF%F_P) 
ENDIF
SELF%CPF%F_P => NULL ()
SELF%CPF%P => NULL ()


IF (ASSOCIATED (SELF%FSTUR%F_P)) THEN
  CALL FIELD_DELETE (SELF%FSTUR%F_P) 
ENDIF
SELF%FSTUR%F_P => NULL ()
SELF%FSTUR%P => NULL ()


IF (ASSOCIATED (SELF%FQTUR%F_P)) THEN
  CALL FIELD_DELETE (SELF%FQTUR%F_P) 
ENDIF
SELF%FQTUR%F_P => NULL ()
SELF%FQTUR%P => NULL ()


IF (ASSOCIATED (SELF%SHTUR%F_P)) THEN
  CALL FIELD_DELETE (SELF%SHTUR%F_P) 
ENDIF
SELF%SHTUR%F_P => NULL ()
SELF%SHTUR%P => NULL ()


IF (ASSOCIATED (SELF%MXL%F_P)) THEN
  CALL FIELD_DELETE (SELF%MXL%F_P) 
ENDIF
SELF%MXL%F_P => NULL ()
SELF%MXL%P => NULL ()


IF (ASSOCIATED (SELF%SRC%F_P)) THEN
  CALL FIELD_DELETE (SELF%SRC%F_P) 
ENDIF
SELF%SRC%F_P => NULL ()
SELF%SRC%P => NULL ()


IF (ASSOCIATED (SELF%O3%F_P)) THEN
  CALL FIELD_DELETE (SELF%O3%F_P) 
ENDIF
SELF%O3%F_P => NULL ()
SELF%O3%P => NULL ()


IF (ASSOCIATED (SELF%AMF%F_P)) THEN
  CALL FIELD_DELETE (SELF%AMF%F_P) 
ENDIF
SELF%AMF%F_P => NULL ()
SELF%AMF%P => NULL ()


IF (ASSOCIATED (SELF%A%F_P)) THEN
  CALL FIELD_DELETE (SELF%A%F_P) 
ENDIF
SELF%A%F_P => NULL ()
SELF%A%P => NULL ()


IF (ASSOCIATED (SELF%EFB3%F_P)) THEN
  CALL FIELD_DELETE (SELF%EFB3%F_P) 
ENDIF
SELF%EFB3%F_P => NULL ()
SELF%EFB3%P => NULL ()


IF (ASSOCIATED (SELF%EFB2%F_P)) THEN
  CALL FIELD_DELETE (SELF%EFB2%F_P) 
ENDIF
SELF%EFB2%F_P => NULL ()
SELF%EFB2%P => NULL ()


IF (ASSOCIATED (SELF%EFB1%F_P)) THEN
  CALL FIELD_DELETE (SELF%EFB1%F_P) 
ENDIF
SELF%EFB1%F_P => NULL ()
SELF%EFB1%P => NULL ()


IF (ASSOCIATED (SELF%TTE%F_P)) THEN
  CALL FIELD_DELETE (SELF%TTE%F_P) 
ENDIF
SELF%TTE%F_P => NULL ()
SELF%TTE%P => NULL ()


IF (ASSOCIATED (SELF%TKE%F_P)) THEN
  CALL FIELD_DELETE (SELF%TKE%F_P) 
ENDIF
SELF%TKE%F_P => NULL ()
SELF%TKE%P => NULL ()


IF (ASSOCIATED (SELF%H%F_P)) THEN
  CALL FIELD_DELETE (SELF%H%F_P) 
ENDIF
SELF%H%F_P => NULL ()
SELF%H%P => NULL ()


IF (ASSOCIATED (SELF%G%F_P)) THEN
  CALL FIELD_DELETE (SELF%G%F_P) 
ENDIF
SELF%G%F_P => NULL ()
SELF%G%P => NULL ()


IF (ASSOCIATED (SELF%R%F_P)) THEN
  CALL FIELD_DELETE (SELF%R%F_P) 
ENDIF
SELF%R%F_P => NULL ()
SELF%R%P => NULL ()


IF (ASSOCIATED (SELF%S%F_P)) THEN
  CALL FIELD_DELETE (SELF%S%F_P) 
ENDIF
SELF%S%F_P => NULL ()
SELF%S%P => NULL ()


IF (ASSOCIATED (SELF%LRAD%F_P)) THEN
  CALL FIELD_DELETE (SELF%LRAD%F_P) 
ENDIF
SELF%LRAD%F_P => NULL ()
SELF%LRAD%P => NULL ()


IF (ASSOCIATED (SELF%IRAD%F_P)) THEN
  CALL FIELD_DELETE (SELF%IRAD%F_P) 
ENDIF
SELF%IRAD%F_P => NULL ()
SELF%IRAD%P => NULL ()


IF (ASSOCIATED (SELF%SCONV%F_P)) THEN
  CALL FIELD_DELETE (SELF%SCONV%F_P) 
ENDIF
SELF%SCONV%F_P => NULL ()
SELF%SCONV%P => NULL ()


IF (ASSOCIATED (SELF%RCONV%F_P)) THEN
  CALL FIELD_DELETE (SELF%RCONV%F_P) 
ENDIF
SELF%RCONV%F_P => NULL ()
SELF%RCONV%P => NULL ()


IF (ASSOCIATED (SELF%ICONV%F_P)) THEN
  CALL FIELD_DELETE (SELF%ICONV%F_P) 
ENDIF
SELF%ICONV%F_P => NULL ()
SELF%ICONV%P => NULL ()


IF (ASSOCIATED (SELF%LCONV%F_P)) THEN
  CALL FIELD_DELETE (SELF%LCONV%F_P) 
ENDIF
SELF%LCONV%F_P => NULL ()
SELF%LCONV%P => NULL ()


IF (ASSOCIATED (SELF%LMF%F_P)) THEN
  CALL FIELD_DELETE (SELF%LMF%F_P) 
ENDIF
SELF%LMF%F_P => NULL ()
SELF%LMF%P => NULL ()


IF (ASSOCIATED (SELF%IMF%F_P)) THEN
  CALL FIELD_DELETE (SELF%IMF%F_P) 
ENDIF
SELF%IMF%F_P => NULL ()
SELF%IMF%P => NULL ()


IF (ASSOCIATED (SELF%L%F_P)) THEN
  CALL FIELD_DELETE (SELF%L%F_P) 
ENDIF
SELF%L%F_P => NULL ()
SELF%L%P => NULL ()


IF (ASSOCIATED (SELF%I%F_P)) THEN
  CALL FIELD_DELETE (SELF%I%F_P) 
ENDIF
SELF%I%F_P => NULL ()
SELF%I%P => NULL ()


IF (ASSOCIATED (SELF%Q%F_P)) THEN
  CALL FIELD_DELETE (SELF%Q%F_P) 
ENDIF
SELF%Q%F_P => NULL ()
SELF%Q%P => NULL ()


IF (ASSOCIATED (SELF%F_DATA)) CALL FIELD_DELETE (SELF%F_DATA)
SELF%F_DATA => NULL ()

IF (SELF%LOWNED) THEN
  IF (ASSOCIATED (SELF%ZDATA)) DEALLOCATE (SELF%ZDATA)
ENDIF

SELF%ZDATA => NULL ()
SELF%ZVIEW => NULL ()

END SUBROUTINE CPG_GFL_TYPE_FINAL

END MODULE CPG_GFL_TYPE_MOD

