SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_SMD_OPTS_TYPE_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_CPG_SURF_SMD_OPTS_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (CPG_SURF_SMD_OPTS_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SELF%YCLBT%ACDC_LOAD (KLUN)
CALL SELF%YCSBT%ACDC_LOAD (KLUN)
END SUBROUTINE

END SUBMODULE
