SUBMODULE (CPG_TYPE_MOD) CPG_TYPE_MOD_CPG_DDH_TYPE_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_CPG_DDH_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (CPG_DDH_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_AUX2D, LF_AUX3D, LF_AUXSM, LF_DDHI, LF_DHCV
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_AUX3D = ASSOCIATED (SELF%F_AUX3D)
IF (LF_AUX3D .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (SELF%F_AUX3D)
ENDIF

LF_AUX2D = ASSOCIATED (SELF%F_AUX2D)
IF (LF_AUX2D .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_AUX2D)
ENDIF

LF_DHCV = ASSOCIATED (SELF%F_DHCV)
IF (LF_DHCV .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (SELF%F_DHCV)
ENDIF

LF_AUXSM = ASSOCIATED (SELF%F_AUXSM)
IF (LF_AUXSM .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_5RB (SELF%F_AUXSM)
ENDIF

LF_DDHI = ASSOCIATED (SELF%F_DDHI)
IF (LF_DDHI .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2IM (SELF%F_DDHI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
