SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_VFD_OPTS_TYPE_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_CPG_SURF_VFD_OPTS_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (CPG_SURF_VFD_OPTS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL SELF%YZ0F%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YALBF%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YEMISF%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YGETRL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLSM%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVEG%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVRLAN%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVRLDI%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSIG%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YALBSF%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLAN%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSST%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSSS%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLZ0H%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCVL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCO2TYP%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCVH%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCUR%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTVL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTVH%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLAIL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLAIH%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YFWET%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSOTY%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCLK%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YDL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCI%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YUCUR%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVCUR%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YZ0RLF%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCGPP%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCREC%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSDFOR%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YALUVP%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YALUVD%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YALNIP%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YALNID%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YFP1%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSO2DD%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YDMSO%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YURBF%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YFCA1%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YFCA2%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YAERDEP%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YAERLTS%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YAERSCC%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YDSF%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YNUDM%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
