SUBMODULE (CPG_TYPE_MOD) CPG_TYPE_MOD_CPG_CTY_TYPE_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_CPG_CTY_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (CPG_CTY_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_DIVDP, LF_EVEL, LF_PSDIV, LF_PSDVBC, LF_VVEL
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LF_EVEL = ASSOCIATED (SELF%F_EVEL)
IF (LF_EVEL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_EVEL)
  !$ACC ENTER DATA ATTACH (SELF%F_EVEL)
ENDIF

LF_VVEL = ASSOCIATED (SELF%F_VVEL)
IF (LF_VVEL .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_VVEL)
  !$ACC ENTER DATA ATTACH (SELF%F_VVEL)
ENDIF

LF_PSDIV = ASSOCIATED (SELF%F_PSDIV)
IF (LF_PSDIV .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_PSDIV)
  !$ACC ENTER DATA ATTACH (SELF%F_PSDIV)
ENDIF

LF_PSDVBC = ASSOCIATED (SELF%F_PSDVBC)
IF (LF_PSDVBC .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_PSDVBC)
  !$ACC ENTER DATA ATTACH (SELF%F_PSDVBC)
ENDIF

LF_DIVDP = ASSOCIATED (SELF%F_DIVDP)
IF (LF_DIVDP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DIVDP)
  !$ACC ENTER DATA ATTACH (SELF%F_DIVDP)
ENDIF

END SUBROUTINE

END SUBMODULE
