SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_V2D_OPTS_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_CPG_SURF_V2D_OPTS_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (CPG_SURF_V2D_OPTS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YOCDEP%ACDC_CRC64 (KLUN, CDPATH//'%YOCDEP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YUSTRC%ACDC_CRC64 (KLUN, CDPATH//'%YUSTRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVSTRC%ACDC_CRC64 (KLUN, CDPATH//'%YVSTRC'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
