SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_VDD_OPTS_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_CPG_SURF_VDD_OPTS_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (CPG_SURF_VDD_OPTS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YLSP%ACDC_CRC64 (KLUN, CDPATH//'%YLSP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCP%ACDC_CRC64 (KLUN, CDPATH//'%YCP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSF%ACDC_CRC64 (KLUN, CDPATH//'%YSF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YFZRA%ACDC_CRC64 (KLUN, CDPATH//'%YFZRA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YBLD%ACDC_CRC64 (KLUN, CDPATH//'%YBLD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSHF%ACDC_CRC64 (KLUN, CDPATH//'%YSSHF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSLHF%ACDC_CRC64 (KLUN, CDPATH//'%YSLHF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YNEE%ACDC_CRC64 (KLUN, CDPATH//'%YNEE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YGPP%ACDC_CRC64 (KLUN, CDPATH//'%YGPP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YREC%ACDC_CRC64 (KLUN, CDPATH//'%YREC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMSL%ACDC_CRC64 (KLUN, CDPATH//'%YMSL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSP%ACDC_CRC64 (KLUN, CDPATH//'%YSP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCC%ACDC_CRC64 (KLUN, CDPATH//'%YTCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10U%ACDC_CRC64 (KLUN, CDPATH//'%Y10U'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10V%ACDC_CRC64 (KLUN, CDPATH//'%Y10V'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y2T%ACDC_CRC64 (KLUN, CDPATH//'%Y2T'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y2D%ACDC_CRC64 (KLUN, CDPATH//'%Y2D'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y2SH%ACDC_CRC64 (KLUN, CDPATH//'%Y2SH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSR%ACDC_CRC64 (KLUN, CDPATH//'%YSSR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTR%ACDC_CRC64 (KLUN, CDPATH//'%YSTR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTSR%ACDC_CRC64 (KLUN, CDPATH//'%YTSR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTTR%ACDC_CRC64 (KLUN, CDPATH//'%YTTR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YEWSS%ACDC_CRC64 (KLUN, CDPATH//'%YEWSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YNSSS%ACDC_CRC64 (KLUN, CDPATH//'%YNSSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YE%ACDC_CRC64 (KLUN, CDPATH//'%YE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YPEV%ACDC_CRC64 (KLUN, CDPATH//'%YPEV'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCCC%ACDC_CRC64 (KLUN, CDPATH//'%YCCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLCC%ACDC_CRC64 (KLUN, CDPATH//'%YLCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMCC%ACDC_CRC64 (KLUN, CDPATH//'%YMCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YHCC%ACDC_CRC64 (KLUN, CDPATH//'%YHCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLGWS%ACDC_CRC64 (KLUN, CDPATH//'%YLGWS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMGWS%ACDC_CRC64 (KLUN, CDPATH//'%YMGWS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YGWD%ACDC_CRC64 (KLUN, CDPATH//'%YGWD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMX2T%ACDC_CRC64 (KLUN, CDPATH//'%YMX2T'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMN2T%ACDC_CRC64 (KLUN, CDPATH//'%YMN2T'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRO%ACDC_CRC64 (KLUN, CDPATH//'%YRO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSRO%ACDC_CRC64 (KLUN, CDPATH//'%YSRO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSRO%ACDC_CRC64 (KLUN, CDPATH//'%YSSRO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YALB%ACDC_CRC64 (KLUN, CDPATH//'%YALB'//TRIM(CLIND))

CLIND = ''
CALL SELF%YIEWSS%ACDC_CRC64 (KLUN, CDPATH//'%YIEWSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YINSSS%ACDC_CRC64 (KLUN, CDPATH//'%YINSSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YISSHF%ACDC_CRC64 (KLUN, CDPATH//'%YISSHF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YIE%ACDC_CRC64 (KLUN, CDPATH//'%YIE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YINEE%ACDC_CRC64 (KLUN, CDPATH//'%YINEE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YIGPP%ACDC_CRC64 (KLUN, CDPATH//'%YIGPP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YIREC%ACDC_CRC64 (KLUN, CDPATH//'%YIREC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YICH4%ACDC_CRC64 (KLUN, CDPATH//'%YICH4'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCSF%ACDC_CRC64 (KLUN, CDPATH//'%YCSF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLSSF%ACDC_CRC64 (KLUN, CDPATH//'%YLSSF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMXTPR%ACDC_CRC64 (KLUN, CDPATH//'%YMXTPR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMNTPR%ACDC_CRC64 (KLUN, CDPATH//'%YMNTPR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTPR%ACDC_CRC64 (KLUN, CDPATH//'%YTPR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLSRR%ACDC_CRC64 (KLUN, CDPATH//'%YLSRR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCRR%ACDC_CRC64 (KLUN, CDPATH//'%YCRR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLSSFR%ACDC_CRC64 (KLUN, CDPATH//'%YLSSFR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCSFR%ACDC_CRC64 (KLUN, CDPATH//'%YCSFR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YPTYPE%ACDC_CRC64 (KLUN, CDPATH//'%YPTYPE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YILSPF%ACDC_CRC64 (KLUN, CDPATH//'%YILSPF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZ0F%ACDC_CRC64 (KLUN, CDPATH//'%YZ0F'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLZ0H%ACDC_CRC64 (KLUN, CDPATH//'%YLZ0H'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVIWVE%ACDC_CRC64 (KLUN, CDPATH//'%YVIWVE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVIWVN%ACDC_CRC64 (KLUN, CDPATH//'%YVIWVN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCW%ACDC_CRC64 (KLUN, CDPATH//'%YTCW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCWV%ACDC_CRC64 (KLUN, CDPATH//'%YTCWV'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCLW%ACDC_CRC64 (KLUN, CDPATH//'%YTCLW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCIW%ACDC_CRC64 (KLUN, CDPATH//'%YTCIW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCRW%ACDC_CRC64 (KLUN, CDPATH//'%YTCRW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCSW%ACDC_CRC64 (KLUN, CDPATH//'%YTCSW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCSLW%ACDC_CRC64 (KLUN, CDPATH//'%YTCSLW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSRD%ACDC_CRC64 (KLUN, CDPATH//'%YSSRD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTRD%ACDC_CRC64 (KLUN, CDPATH//'%YSTRD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSRDC%ACDC_CRC64 (KLUN, CDPATH//'%YSSRDC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTRDC%ACDC_CRC64 (KLUN, CDPATH//'%YSTRDC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YBLH%ACDC_CRC64 (KLUN, CDPATH//'%YBLH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSUND%ACDC_CRC64 (KLUN, CDPATH//'%YSUND'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSPAR%ACDC_CRC64 (KLUN, CDPATH//'%YSPAR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSUVB%ACDC_CRC64 (KLUN, CDPATH//'%YSUVB'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSFDIR%ACDC_CRC64 (KLUN, CDPATH//'%YSFDIR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSCDIR%ACDC_CRC64 (KLUN, CDPATH//'%YSCDIR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSDSRP%ACDC_CRC64 (KLUN, CDPATH//'%YSDSRP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCAPE%ACDC_CRC64 (KLUN, CDPATH//'%YCAPE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMUCAPE%ACDC_CRC64 (KLUN, CDPATH//'%YMUCAPE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMLCAPE50%ACDC_CRC64 (KLUN, CDPATH//'%YMLCAPE50'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMLCAPE100%ACDC_CRC64 (KLUN, CDPATH//'%YMLCAPE100'//TRIM(CLIND))

CLIND = ''
CALL SELF%YPDEPL%ACDC_CRC64 (KLUN, CDPATH//'%YPDEPL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCAPES%ACDC_CRC64 (KLUN, CDPATH//'%YCAPES'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTROPOTP%ACDC_CRC64 (KLUN, CDPATH//'%YTROPOTP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTSRC%ACDC_CRC64 (KLUN, CDPATH//'%YTSRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTTRC%ACDC_CRC64 (KLUN, CDPATH//'%YTTRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSRC%ACDC_CRC64 (KLUN, CDPATH//'%YSSRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTRC%ACDC_CRC64 (KLUN, CDPATH//'%YSTRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YES%ACDC_CRC64 (KLUN, CDPATH//'%YES'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSMLT%ACDC_CRC64 (KLUN, CDPATH//'%YSMLT'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10FG%ACDC_CRC64 (KLUN, CDPATH//'%Y10FG'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10FGCV%ACDC_CRC64 (KLUN, CDPATH//'%Y10FGCV'//TRIM(CLIND))

CLIND = ''
CALL SELF%YI10FG%ACDC_CRC64 (KLUN, CDPATH//'%YI10FG'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLSPF%ACDC_CRC64 (KLUN, CDPATH//'%YLSPF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCO3%ACDC_CRC64 (KLUN, CDPATH//'%YTCO3'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVIMD%ACDC_CRC64 (KLUN, CDPATH//'%YVIMD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSPARC%ACDC_CRC64 (KLUN, CDPATH//'%YSPARC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTINC%ACDC_CRC64 (KLUN, CDPATH//'%YSTINC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCBASE%ACDC_CRC64 (KLUN, CDPATH//'%YCBASE'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y0DEGL%ACDC_CRC64 (KLUN, CDPATH//'%Y0DEGL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YM10DEGL%ACDC_CRC64 (KLUN, CDPATH//'%YM10DEGL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVISIH%ACDC_CRC64 (KLUN, CDPATH//'%YVISIH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCIN%ACDC_CRC64 (KLUN, CDPATH//'%YCIN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMLCIN50%ACDC_CRC64 (KLUN, CDPATH//'%YMLCIN50'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMLCIN100%ACDC_CRC64 (KLUN, CDPATH//'%YMLCIN100'//TRIM(CLIND))

CLIND = ''
CALL SELF%YKINDEX%ACDC_CRC64 (KLUN, CDPATH//'%YKINDEX'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTTINDEX%ACDC_CRC64 (KLUN, CDPATH//'%YTTINDEX'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCBASEA%ACDC_CRC64 (KLUN, CDPATH//'%YCBASEA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCTOPC%ACDC_CRC64 (KLUN, CDPATH//'%YCTOPC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZTWETB0%ACDC_CRC64 (KLUN, CDPATH//'%YZTWETB0'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZTWETB1%ACDC_CRC64 (KLUN, CDPATH//'%YZTWETB1'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y100U%ACDC_CRC64 (KLUN, CDPATH//'%Y100U'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y100V%ACDC_CRC64 (KLUN, CDPATH//'%Y100V'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y200U%ACDC_CRC64 (KLUN, CDPATH//'%Y200U'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y200V%ACDC_CRC64 (KLUN, CDPATH//'%Y200V'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZUST%ACDC_CRC64 (KLUN, CDPATH//'%YZUST'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10NU%ACDC_CRC64 (KLUN, CDPATH//'%Y10NU'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10NV%ACDC_CRC64 (KLUN, CDPATH//'%Y10NV'//TRIM(CLIND))

CLIND = ''
CALL SELF%YDNDZN%ACDC_CRC64 (KLUN, CDPATH//'%YDNDZN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YDNDZA%ACDC_CRC64 (KLUN, CDPATH//'%YDNDZA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YDCTB%ACDC_CRC64 (KLUN, CDPATH//'%YDCTB'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTPLB%ACDC_CRC64 (KLUN, CDPATH//'%YTPLB'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTPLT%ACDC_CRC64 (KLUN, CDPATH//'%YTPLT'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODSS%ACDC_CRC64 (KLUN, CDPATH//'%YODSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODDU%ACDC_CRC64 (KLUN, CDPATH//'%YODDU'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODOM%ACDC_CRC64 (KLUN, CDPATH//'%YODOM'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODBC%ACDC_CRC64 (KLUN, CDPATH//'%YODBC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODSU%ACDC_CRC64 (KLUN, CDPATH//'%YODSU'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODNI%ACDC_CRC64 (KLUN, CDPATH//'%YODNI'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODAM%ACDC_CRC64 (KLUN, CDPATH//'%YODAM'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODSOA%ACDC_CRC64 (KLUN, CDPATH//'%YODSOA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODVFA%ACDC_CRC64 (KLUN, CDPATH//'%YODVFA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODVSU%ACDC_CRC64 (KLUN, CDPATH//'%YODVSU'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODTOACC%ACDC_CRC64 (KLUN, CDPATH//'%YODTOACC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YAEPM1%ACDC_CRC64 (KLUN, CDPATH//'%YAEPM1'//TRIM(CLIND))

CLIND = ''
CALL SELF%YAEPM25%ACDC_CRC64 (KLUN, CDPATH//'%YAEPM25'//TRIM(CLIND))

CLIND = ''
CALL SELF%YAEPM10%ACDC_CRC64 (KLUN, CDPATH//'%YAEPM10'//TRIM(CLIND))

CLIND = ''
CALL SELF%YUVBED%ACDC_CRC64 (KLUN, CDPATH//'%YUVBED'//TRIM(CLIND))

CLIND = ''
CALL SELF%YUVBEDCS%ACDC_CRC64 (KLUN, CDPATH//'%YUVBEDCS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLITOTI%ACDC_CRC64 (KLUN, CDPATH//'%YLITOTI'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLICGI%ACDC_CRC64 (KLUN, CDPATH//'%YLICGI'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
