SUBMODULE (CPG_TYPE_MOD) CPG_TYPE_MOD_CPG_XYB_TYPE_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_CPG_XYB_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (CPG_XYB_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_ALPH, LF_DELP, LF_LNPR, LF_RDELP, LF_RPP, LF_RPRE, LF_RTGR
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LF_DELP = ASSOCIATED (SELF%F_DELP)
IF (LF_DELP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DELP)
  !$ACC ENTER DATA ATTACH (SELF%F_DELP)
ENDIF

LF_RDELP = ASSOCIATED (SELF%F_RDELP)
IF (LF_RDELP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_RDELP)
  !$ACC ENTER DATA ATTACH (SELF%F_RDELP)
ENDIF

LF_LNPR = ASSOCIATED (SELF%F_LNPR)
IF (LF_LNPR .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_LNPR)
  !$ACC ENTER DATA ATTACH (SELF%F_LNPR)
ENDIF

LF_ALPH = ASSOCIATED (SELF%F_ALPH)
IF (LF_ALPH .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_ALPH)
  !$ACC ENTER DATA ATTACH (SELF%F_ALPH)
ENDIF

LF_RTGR = ASSOCIATED (SELF%F_RTGR)
IF (LF_RTGR .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_RTGR)
  !$ACC ENTER DATA ATTACH (SELF%F_RTGR)
ENDIF

LF_RPRE = ASSOCIATED (SELF%F_RPRE)
IF (LF_RPRE .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_RPRE)
  !$ACC ENTER DATA ATTACH (SELF%F_RPRE)
ENDIF

LF_RPP = ASSOCIATED (SELF%F_RPP)
IF (LF_RPP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_RPP)
  !$ACC ENTER DATA ATTACH (SELF%F_RPP)
ENDIF

END SUBROUTINE

END SUBMODULE
