SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_VD_ODOMD_OPTS_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_CPG_SURF_VD_ODOMD_OPTS_TYPE (SELF)

IMPLICIT NONE
CLASS (CPG_SURF_VD_ODOMD_OPTS_TYPE), TARGET :: SELF


END SUBROUTINE

END SUBMODULE
