SUBMODULE (MF_PHYS_BASE_STATE_TYPE_MOD) MF_PHYS_BASE_STATE_TYPE_MOD_MF_PHYS_BASE_STATE_TYPE_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_MF_PHYS_BASE_STATE_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (MF_PHYS_BASE_STATE_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_AMF, LF_CVV, LF_DIV, LF_EFB1, LF_EFB2, LF_EFB3, LF_G, LF_H, LF_I, LF_IMF
LOGICAL :: LF_L, LF_LMF, LF_O3, LF_Q, LF_R, LF_S, LF_SRC, LF_T, LF_TKE, LF_U
LOGICAL :: LF_V, LF_VOR, LP1AERO, LP1CHEM, LP1EXT, LP1LIMA, LP1NOGW, LP2NOGW
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL SELF%YCPG_DYN%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCPG_PHY%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LP1EXT = ASSOCIATED (SELF%P1EXT)
IF (LP1EXT) THEN
  !$ACC EXIT DATA DETACH (SELF%P1EXT)
  !$ACC EXIT DATA DELETE (SELF%P1EXT)
ENDIF

LP1CHEM = ASSOCIATED (SELF%P1CHEM)
IF (LP1CHEM) THEN
  !$ACC EXIT DATA DETACH (SELF%P1CHEM)
  !$ACC EXIT DATA DELETE (SELF%P1CHEM)
ENDIF

LP1NOGW = ASSOCIATED (SELF%P1NOGW)
IF (LP1NOGW) THEN
  !$ACC EXIT DATA DETACH (SELF%P1NOGW)
  !$ACC EXIT DATA DELETE (SELF%P1NOGW)
ENDIF

LP2NOGW = ASSOCIATED (SELF%P2NOGW)
IF (LP2NOGW) THEN
  !$ACC EXIT DATA DETACH (SELF%P2NOGW)
  !$ACC EXIT DATA DELETE (SELF%P2NOGW)
ENDIF

LP1LIMA = ASSOCIATED (SELF%P1LIMA)
IF (LP1LIMA) THEN
  !$ACC EXIT DATA DETACH (SELF%P1LIMA)
  !$ACC EXIT DATA DELETE (SELF%P1LIMA)
ENDIF

LP1AERO = ASSOCIATED (SELF%P1AERO)
IF (LP1AERO) THEN
  !$ACC EXIT DATA DETACH (SELF%P1AERO)
  !$ACC EXIT DATA DELETE (SELF%P1AERO)
ENDIF

LF_CVV = ASSOCIATED (SELF%F_CVV)
IF (LF_CVV .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_CVV)
ENDIF

LF_DIV = ASSOCIATED (SELF%F_DIV)
IF (LF_DIV .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_DIV)
ENDIF

LF_EFB1 = ASSOCIATED (SELF%F_EFB1)
IF (LF_EFB1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_EFB1)
ENDIF

LF_EFB2 = ASSOCIATED (SELF%F_EFB2)
IF (LF_EFB2 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_EFB2)
ENDIF

LF_EFB3 = ASSOCIATED (SELF%F_EFB3)
IF (LF_EFB3 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_EFB3)
ENDIF

LF_G = ASSOCIATED (SELF%F_G)
IF (LF_G .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_G)
ENDIF

LF_H = ASSOCIATED (SELF%F_H)
IF (LF_H .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_H)
ENDIF

LF_I = ASSOCIATED (SELF%F_I)
IF (LF_I .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_I)
ENDIF

LF_L = ASSOCIATED (SELF%F_L)
IF (LF_L .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_L)
ENDIF

LF_IMF = ASSOCIATED (SELF%F_IMF)
IF (LF_IMF .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_IMF)
ENDIF

LF_LMF = ASSOCIATED (SELF%F_LMF)
IF (LF_LMF .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_LMF)
ENDIF

LF_AMF = ASSOCIATED (SELF%F_AMF)
IF (LF_AMF .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_AMF)
ENDIF

LF_O3 = ASSOCIATED (SELF%F_O3)
IF (LF_O3 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_O3)
ENDIF

LF_Q = ASSOCIATED (SELF%F_Q)
IF (LF_Q .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_Q)
ENDIF

LF_R = ASSOCIATED (SELF%F_R)
IF (LF_R .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_R)
ENDIF

LF_S = ASSOCIATED (SELF%F_S)
IF (LF_S .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_S)
ENDIF

LF_SRC = ASSOCIATED (SELF%F_SRC)
IF (LF_SRC .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_SRC)
ENDIF

LF_T = ASSOCIATED (SELF%F_T)
IF (LF_T .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_T)
ENDIF

LF_TKE = ASSOCIATED (SELF%F_TKE)
IF (LF_TKE .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_TKE)
ENDIF

LF_U = ASSOCIATED (SELF%F_U)
IF (LF_U .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_U)
ENDIF

LF_V = ASSOCIATED (SELF%F_V)
IF (LF_V .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_V)
ENDIF

LF_VOR = ASSOCIATED (SELF%F_VOR)
IF (LF_VOR .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_VOR)
ENDIF

CALL SELF%YGSP_SG%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YGSP_RR%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YGSP_SB%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
