SUBMODULE (SURFACE_VIEWS_DIAGNOSTIC_MODULE) SURFACE_VIEWS_DIAGNOSTIC_MODULE_SURFACE_VIEW_GROUP_SATSIM_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_SURFACE_VIEW_GROUP_SATSIM (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_SATSIM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_CLBT, LF_CSBT
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LF_CLBT = ASSOCIATED (SELF%F_CLBT)
IF (LF_CLBT .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_CLBT)
  !$ACC ENTER DATA ATTACH (SELF%F_CLBT)
ENDIF

LF_CSBT = ASSOCIATED (SELF%F_CSBT)
IF (LF_CSBT .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_CSBT)
  !$ACC ENTER DATA ATTACH (SELF%F_CSBT)
ENDIF

END SUBROUTINE

END SUBMODULE
