SUBMODULE (SURFACE_VIEWS_DIAGNOSTIC_MODULE) SURFACE_VIEWS_DIAGNOSTIC_MODULE_SURFACE_VIEW_GROUP_VCLIN_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_SURFACE_VIEW_GROUP_VCLIN (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_VCLIN), TARGET :: SELF
LOGICAL :: LF_ACCPR, LF_ACCPR5, LF_ACPR, LF_BAS, LF_TOP
LF_TOP = ASSOCIATED (SELF%F_TOP)
IF (LF_TOP) THEN
  CALL HOST_FIELD_2RB (SELF%F_TOP)
ENDIF

LF_BAS = ASSOCIATED (SELF%F_BAS)
IF (LF_BAS) THEN
  CALL HOST_FIELD_2RB (SELF%F_BAS)
ENDIF

LF_ACPR = ASSOCIATED (SELF%F_ACPR)
IF (LF_ACPR) THEN
  CALL HOST_FIELD_2RB (SELF%F_ACPR)
ENDIF

LF_ACCPR = ASSOCIATED (SELF%F_ACCPR)
IF (LF_ACCPR) THEN
  CALL HOST_FIELD_2RB (SELF%F_ACCPR)
ENDIF

LF_ACCPR5 = ASSOCIATED (SELF%F_ACCPR5)
IF (LF_ACCPR5) THEN
  CALL HOST_FIELD_2RB (SELF%F_ACCPR5)
ENDIF

END SUBROUTINE

END SUBMODULE
