SUBMODULE (SURFACE_VIEWS_PROGNOSTIC_MODULE) SURFACE_VIEWS_PROGNOSTIC_MODULE_SURFACE_VIEW_GROUP_EXTRP_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_SURFACE_VIEW_GROUP_EXTRP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_EXTRP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
