SUBMODULE (SURFACE_VIEWS_PROGNOSTIC_MODULE) SURFACE_VIEWS_PROGNOSTIC_MODULE_SURFACE_VIEW_GROUP_OML_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_SURFACE_VIEW_GROUP_OML (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_OML), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_SO_T0, LF_SO_T1, LF_SO_T9, LF_TO_T0, LF_TO_T1, LF_TO_T9, LF_UO_T0, LF_UO_T1, LF_UO_T9, LF_VO_T0
LOGICAL :: LF_VO_T1, LF_VO_T9
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_TO_T0 = ASSOCIATED (SELF%F_TO_T0)
IF (LF_TO_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_TO_T0)
ENDIF

LF_TO_T1 = ASSOCIATED (SELF%F_TO_T1)
IF (LF_TO_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_TO_T1)
ENDIF

LF_TO_T9 = ASSOCIATED (SELF%F_TO_T9)
IF (LF_TO_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_TO_T9)
ENDIF

LF_SO_T0 = ASSOCIATED (SELF%F_SO_T0)
IF (LF_SO_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_SO_T0)
ENDIF

LF_SO_T1 = ASSOCIATED (SELF%F_SO_T1)
IF (LF_SO_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_SO_T1)
ENDIF

LF_SO_T9 = ASSOCIATED (SELF%F_SO_T9)
IF (LF_SO_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_SO_T9)
ENDIF

LF_UO_T0 = ASSOCIATED (SELF%F_UO_T0)
IF (LF_UO_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_UO_T0)
ENDIF

LF_UO_T1 = ASSOCIATED (SELF%F_UO_T1)
IF (LF_UO_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_UO_T1)
ENDIF

LF_UO_T9 = ASSOCIATED (SELF%F_UO_T9)
IF (LF_UO_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_UO_T9)
ENDIF

LF_VO_T0 = ASSOCIATED (SELF%F_VO_T0)
IF (LF_VO_T0 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_VO_T0)
ENDIF

LF_VO_T1 = ASSOCIATED (SELF%F_VO_T1)
IF (LF_VO_T1 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_VO_T1)
ENDIF

LF_VO_T9 = ASSOCIATED (SELF%F_VO_T9)
IF (LF_VO_T9 .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_VO_T9)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
