SUBMODULE (SURFACE_VIEWS_DIAGNOSTIC_MODULE) SURFACE_VIEWS_DIAGNOSTIC_MODULE_SURFACE_VIEW_GROUP_VCLIK_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_SURFACE_VIEW_GROUP_VCLIK (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_VCLIK), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_UDGRO
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_UDGRO = ASSOCIATED (SELF%F_UDGRO)
IF (LF_UDGRO .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_UDGRO)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
