SUBMODULE (SURFACE_VIEWS_PROGNOSTIC_MODULE) SURFACE_VIEWS_PROGNOSTIC_MODULE_SURFACE_VIEW_GROUP_XTRP2_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_SURFACE_VIEW_GROUP_XTRP2 (SELF)

IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_XTRP2), TARGET :: SELF

END SUBROUTINE

END SUBMODULE
