SUBMODULE (SURFACE_VIEWS_DIAGNOSTIC_MODULE) SURFACE_VIEWS_DIAGNOSTIC_MODULE_SURFACE_VIEW_GROUP_WAM_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_SURFACE_VIEW_GROUP_WAM (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_WAM), TARGET :: SELF
LOGICAL :: LF_CIF, LF_CLK, LF_RHO, LF_U10N, LF_UCURW, LF_V10N, LF_VCURW, LF_ZIL
LF_U10N = ASSOCIATED (SELF%F_U10N)
IF (LF_U10N) THEN
  CALL HOST_FIELD_2RB (SELF%F_U10N)
ENDIF

LF_V10N = ASSOCIATED (SELF%F_V10N)
IF (LF_V10N) THEN
  CALL HOST_FIELD_2RB (SELF%F_V10N)
ENDIF

LF_RHO = ASSOCIATED (SELF%F_RHO)
IF (LF_RHO) THEN
  CALL HOST_FIELD_2RB (SELF%F_RHO)
ENDIF

LF_ZIL = ASSOCIATED (SELF%F_ZIL)
IF (LF_ZIL) THEN
  CALL HOST_FIELD_2RB (SELF%F_ZIL)
ENDIF

LF_CIF = ASSOCIATED (SELF%F_CIF)
IF (LF_CIF) THEN
  CALL HOST_FIELD_2RB (SELF%F_CIF)
ENDIF

LF_CLK = ASSOCIATED (SELF%F_CLK)
IF (LF_CLK) THEN
  CALL HOST_FIELD_2RB (SELF%F_CLK)
ENDIF

LF_UCURW = ASSOCIATED (SELF%F_UCURW)
IF (LF_UCURW) THEN
  CALL HOST_FIELD_2RB (SELF%F_UCURW)
ENDIF

LF_VCURW = ASSOCIATED (SELF%F_VCURW)
IF (LF_VCURW) THEN
  CALL HOST_FIELD_2RB (SELF%F_VCURW)
ENDIF

END SUBROUTINE

END SUBMODULE
