SUBMODULE (SURFACE_VIEWS_PROGNOSTIC_MODULE) SURFACE_VIEWS_PROGNOSTIC_MODULE_SURFACE_VIEW_GROUP_OML_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_SURFACE_VIEW_GROUP_OML (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_OML), TARGET :: SELF
LOGICAL :: LF_SO_T0, LF_SO_T1, LF_SO_T9, LF_TO_T0, LF_TO_T1, LF_TO_T9, LF_UO_T0, LF_UO_T1, LF_UO_T9, LF_VO_T0
LOGICAL :: LF_VO_T1, LF_VO_T9
LF_TO_T0 = ASSOCIATED (SELF%F_TO_T0)
IF (LF_TO_T0) THEN
  CALL HOST_FIELD_3RB (SELF%F_TO_T0)
ENDIF

LF_TO_T1 = ASSOCIATED (SELF%F_TO_T1)
IF (LF_TO_T1) THEN
  CALL HOST_FIELD_3RB (SELF%F_TO_T1)
ENDIF

LF_TO_T9 = ASSOCIATED (SELF%F_TO_T9)
IF (LF_TO_T9) THEN
  CALL HOST_FIELD_3RB (SELF%F_TO_T9)
ENDIF

LF_SO_T0 = ASSOCIATED (SELF%F_SO_T0)
IF (LF_SO_T0) THEN
  CALL HOST_FIELD_3RB (SELF%F_SO_T0)
ENDIF

LF_SO_T1 = ASSOCIATED (SELF%F_SO_T1)
IF (LF_SO_T1) THEN
  CALL HOST_FIELD_3RB (SELF%F_SO_T1)
ENDIF

LF_SO_T9 = ASSOCIATED (SELF%F_SO_T9)
IF (LF_SO_T9) THEN
  CALL HOST_FIELD_3RB (SELF%F_SO_T9)
ENDIF

LF_UO_T0 = ASSOCIATED (SELF%F_UO_T0)
IF (LF_UO_T0) THEN
  CALL HOST_FIELD_3RB (SELF%F_UO_T0)
ENDIF

LF_UO_T1 = ASSOCIATED (SELF%F_UO_T1)
IF (LF_UO_T1) THEN
  CALL HOST_FIELD_3RB (SELF%F_UO_T1)
ENDIF

LF_UO_T9 = ASSOCIATED (SELF%F_UO_T9)
IF (LF_UO_T9) THEN
  CALL HOST_FIELD_3RB (SELF%F_UO_T9)
ENDIF

LF_VO_T0 = ASSOCIATED (SELF%F_VO_T0)
IF (LF_VO_T0) THEN
  CALL HOST_FIELD_3RB (SELF%F_VO_T0)
ENDIF

LF_VO_T1 = ASSOCIATED (SELF%F_VO_T1)
IF (LF_VO_T1) THEN
  CALL HOST_FIELD_3RB (SELF%F_VO_T1)
ENDIF

LF_VO_T9 = ASSOCIATED (SELF%F_VO_T9)
IF (LF_VO_T9) THEN
  CALL HOST_FIELD_3RB (SELF%F_VO_T9)
ENDIF

END SUBROUTINE

END SUBMODULE
