SUBMODULE (SURFACE_VIEWS_DIAGNOSTIC_MODULE) SURFACE_VIEWS_DIAGNOSTIC_MODULE_SURFACE_VIEW_GROUP_VDIAGO3_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_SURFACE_VIEW_GROUP_VDIAGO3 (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_VDIAGO3), TARGET :: SELF
LOGICAL :: LF_ADVS, LF_ADVT, LF_DIFM, LF_DIFS, LF_DIFT, LF_DO, LF_HO, LF_HO_INV, LF_OTKE, LF_SWDK
LOGICAL :: LF_TRI0, LF_TRI1, LF_UOC, LF_VOC, LF_ZO
LF_DIFM = ASSOCIATED (SELF%F_DIFM)
IF (LF_DIFM) THEN
  CALL HOST_FIELD_3RB (SELF%F_DIFM)
ENDIF

LF_DIFT = ASSOCIATED (SELF%F_DIFT)
IF (LF_DIFT) THEN
  CALL HOST_FIELD_3RB (SELF%F_DIFT)
ENDIF

LF_DIFS = ASSOCIATED (SELF%F_DIFS)
IF (LF_DIFS) THEN
  CALL HOST_FIELD_3RB (SELF%F_DIFS)
ENDIF

LF_ADVT = ASSOCIATED (SELF%F_ADVT)
IF (LF_ADVT) THEN
  CALL HOST_FIELD_3RB (SELF%F_ADVT)
ENDIF

LF_ADVS = ASSOCIATED (SELF%F_ADVS)
IF (LF_ADVS) THEN
  CALL HOST_FIELD_3RB (SELF%F_ADVS)
ENDIF

LF_TRI0 = ASSOCIATED (SELF%F_TRI0)
IF (LF_TRI0) THEN
  CALL HOST_FIELD_3RB (SELF%F_TRI0)
ENDIF

LF_TRI1 = ASSOCIATED (SELF%F_TRI1)
IF (LF_TRI1) THEN
  CALL HOST_FIELD_3RB (SELF%F_TRI1)
ENDIF

LF_SWDK = ASSOCIATED (SELF%F_SWDK)
IF (LF_SWDK) THEN
  CALL HOST_FIELD_3RB (SELF%F_SWDK)
ENDIF

LF_ZO = ASSOCIATED (SELF%F_ZO)
IF (LF_ZO) THEN
  CALL HOST_FIELD_3RB (SELF%F_ZO)
ENDIF

LF_HO = ASSOCIATED (SELF%F_HO)
IF (LF_HO) THEN
  CALL HOST_FIELD_3RB (SELF%F_HO)
ENDIF

LF_DO = ASSOCIATED (SELF%F_DO)
IF (LF_DO) THEN
  CALL HOST_FIELD_3RB (SELF%F_DO)
ENDIF

LF_HO_INV = ASSOCIATED (SELF%F_HO_INV)
IF (LF_HO_INV) THEN
  CALL HOST_FIELD_3RB (SELF%F_HO_INV)
ENDIF

LF_UOC = ASSOCIATED (SELF%F_UOC)
IF (LF_UOC) THEN
  CALL HOST_FIELD_3RB (SELF%F_UOC)
ENDIF

LF_VOC = ASSOCIATED (SELF%F_VOC)
IF (LF_VOC) THEN
  CALL HOST_FIELD_3RB (SELF%F_VOC)
ENDIF

LF_OTKE = ASSOCIATED (SELF%F_OTKE)
IF (LF_OTKE) THEN
  CALL HOST_FIELD_3RB (SELF%F_OTKE)
ENDIF

END SUBROUTINE

END SUBMODULE
