SUBMODULE (SURFACE_VIEWS_DIAGNOSTIC_MODULE) SURFACE_VIEWS_DIAGNOSTIC_MODULE_SURFACE_VIEW_GROUP_VEXTR2_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_SURFACE_VIEW_GROUP_VEXTR2 (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_VEXTR2), TARGET :: SELF
LOGICAL :: LF_GROUP, LVARIABLE_GROUP
LVARIABLE_GROUP = ASSOCIATED (SELF%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  CALL SELF%VARIABLE_GROUP%ACDC_HOST ()
ENDIF

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (SELF%F_GROUP)
ENDIF

END SUBROUTINE

END SUBMODULE
