SUBMODULE (VARIABLE_MODULE) VARIABLE_MODULE_VARIABLE_3RD_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_VARIABLE_3RD (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (VARIABLE_3RD), TARGET :: SELF
CLASS (VARIABLE_BASE), POINTER :: YLSUPER
LOGICAL :: LFDL, LFDL9, LFDM, LFDM9, LFPC_PH, LFPH9, LFT0, LFT1, LFT9
YLSUPER => SELF
CALL YLSUPER%ACDC_HOST ()
LFT0 = ASSOCIATED (SELF%FT0)
IF (LFT0) THEN
  CALL HOST_FIELD_3RD (SELF%FT0)
ENDIF

LFT1 = ASSOCIATED (SELF%FT1)
IF (LFT1) THEN
  CALL HOST_FIELD_3RD (SELF%FT1)
ENDIF

LFT9 = ASSOCIATED (SELF%FT9)
IF (LFT9) THEN
  CALL HOST_FIELD_3RD (SELF%FT9)
ENDIF

LFPH9 = ASSOCIATED (SELF%FPH9)
IF (LFPH9) THEN
  CALL HOST_FIELD_3RD (SELF%FPH9)
ENDIF

LFDL = ASSOCIATED (SELF%FDL)
IF (LFDL) THEN
  CALL HOST_FIELD_3RD (SELF%FDL)
ENDIF

LFDM = ASSOCIATED (SELF%FDM)
IF (LFDM) THEN
  CALL HOST_FIELD_3RD (SELF%FDM)
ENDIF

LFDL9 = ASSOCIATED (SELF%FDL9)
IF (LFDL9) THEN
  CALL HOST_FIELD_3RD (SELF%FDL9)
ENDIF

LFDM9 = ASSOCIATED (SELF%FDM9)
IF (LFDM9) THEN
  CALL HOST_FIELD_3RD (SELF%FDM9)
ENDIF

LFPC_PH = ASSOCIATED (SELF%FPC_PH)
IF (LFPC_PH) THEN
  CALL HOST_FIELD_3RD (SELF%FPC_PH)
ENDIF

END SUBROUTINE

END SUBMODULE
