SUBMODULE (YOMDGRADIENT_TYPE_MOD) YOMDGRADIENT_TYPE_MOD_GRADIENT_TYPE_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_GRADIENT_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (GRADIENT_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_DQGDX, LF_DQGDY, LF_DQIDX, LF_DQIDY, LF_DQLDX, LF_DQLDY, LF_DQRDX, LF_DQRDY, LF_DQSDX, LF_DQSDY
LOGICAL :: LF_DQVDX, LF_DQVDY, LF_DRIDXZ, LF_DRIDYZ, LF_DRLDXZ, LF_DRLDYZ, LF_DRVDXZ, LF_DRVDYZ, LF_DTDX, LF_DTDY
LOGICAL :: LF_DTHETADXZ, LF_DTHETADYZ, LF_DU2DX2, LF_DU2DY2, LF_DUDX, LF_DUDXZ, LF_DUDY, LF_DUDYZ, LF_DV2DX2, LF_DV2DY2
LOGICAL :: LF_DVDX, LF_DVDXZ, LF_DVDY, LF_DVDYZ, LF_DWDXZ, LF_DWDYZ
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LF_DUDX = ASSOCIATED (SELF%F_DUDX)
IF (LF_DUDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DUDX)
  !$ACC ENTER DATA ATTACH (SELF%F_DUDX)
ENDIF

LF_DUDY = ASSOCIATED (SELF%F_DUDY)
IF (LF_DUDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DUDY)
  !$ACC ENTER DATA ATTACH (SELF%F_DUDY)
ENDIF

LF_DVDX = ASSOCIATED (SELF%F_DVDX)
IF (LF_DVDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DVDX)
  !$ACC ENTER DATA ATTACH (SELF%F_DVDX)
ENDIF

LF_DVDY = ASSOCIATED (SELF%F_DVDY)
IF (LF_DVDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DVDY)
  !$ACC ENTER DATA ATTACH (SELF%F_DVDY)
ENDIF

LF_DTDX = ASSOCIATED (SELF%F_DTDX)
IF (LF_DTDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DTDX)
  !$ACC ENTER DATA ATTACH (SELF%F_DTDX)
ENDIF

LF_DTDY = ASSOCIATED (SELF%F_DTDY)
IF (LF_DTDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DTDY)
  !$ACC ENTER DATA ATTACH (SELF%F_DTDY)
ENDIF

LF_DQVDX = ASSOCIATED (SELF%F_DQVDX)
IF (LF_DQVDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQVDX)
  !$ACC ENTER DATA ATTACH (SELF%F_DQVDX)
ENDIF

LF_DQVDY = ASSOCIATED (SELF%F_DQVDY)
IF (LF_DQVDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQVDY)
  !$ACC ENTER DATA ATTACH (SELF%F_DQVDY)
ENDIF

LF_DQLDX = ASSOCIATED (SELF%F_DQLDX)
IF (LF_DQLDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQLDX)
  !$ACC ENTER DATA ATTACH (SELF%F_DQLDX)
ENDIF

LF_DQLDY = ASSOCIATED (SELF%F_DQLDY)
IF (LF_DQLDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQLDY)
  !$ACC ENTER DATA ATTACH (SELF%F_DQLDY)
ENDIF

LF_DQIDX = ASSOCIATED (SELF%F_DQIDX)
IF (LF_DQIDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQIDX)
  !$ACC ENTER DATA ATTACH (SELF%F_DQIDX)
ENDIF

LF_DQIDY = ASSOCIATED (SELF%F_DQIDY)
IF (LF_DQIDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQIDY)
  !$ACC ENTER DATA ATTACH (SELF%F_DQIDY)
ENDIF

LF_DQRDX = ASSOCIATED (SELF%F_DQRDX)
IF (LF_DQRDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQRDX)
  !$ACC ENTER DATA ATTACH (SELF%F_DQRDX)
ENDIF

LF_DQRDY = ASSOCIATED (SELF%F_DQRDY)
IF (LF_DQRDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQRDY)
  !$ACC ENTER DATA ATTACH (SELF%F_DQRDY)
ENDIF

LF_DQSDX = ASSOCIATED (SELF%F_DQSDX)
IF (LF_DQSDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQSDX)
  !$ACC ENTER DATA ATTACH (SELF%F_DQSDX)
ENDIF

LF_DQSDY = ASSOCIATED (SELF%F_DQSDY)
IF (LF_DQSDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQSDY)
  !$ACC ENTER DATA ATTACH (SELF%F_DQSDY)
ENDIF

LF_DQGDX = ASSOCIATED (SELF%F_DQGDX)
IF (LF_DQGDX .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQGDX)
  !$ACC ENTER DATA ATTACH (SELF%F_DQGDX)
ENDIF

LF_DQGDY = ASSOCIATED (SELF%F_DQGDY)
IF (LF_DQGDY .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DQGDY)
  !$ACC ENTER DATA ATTACH (SELF%F_DQGDY)
ENDIF

LF_DU2DX2 = ASSOCIATED (SELF%F_DU2DX2)
IF (LF_DU2DX2 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DU2DX2)
  !$ACC ENTER DATA ATTACH (SELF%F_DU2DX2)
ENDIF

LF_DU2DY2 = ASSOCIATED (SELF%F_DU2DY2)
IF (LF_DU2DY2 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DU2DY2)
  !$ACC ENTER DATA ATTACH (SELF%F_DU2DY2)
ENDIF

LF_DV2DX2 = ASSOCIATED (SELF%F_DV2DX2)
IF (LF_DV2DX2 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DV2DX2)
  !$ACC ENTER DATA ATTACH (SELF%F_DV2DX2)
ENDIF

LF_DV2DY2 = ASSOCIATED (SELF%F_DV2DY2)
IF (LF_DV2DY2 .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DV2DY2)
  !$ACC ENTER DATA ATTACH (SELF%F_DV2DY2)
ENDIF

LF_DUDXZ = ASSOCIATED (SELF%F_DUDXZ)
IF (LF_DUDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DUDXZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DUDXZ)
ENDIF

LF_DUDYZ = ASSOCIATED (SELF%F_DUDYZ)
IF (LF_DUDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DUDYZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DUDYZ)
ENDIF

LF_DVDXZ = ASSOCIATED (SELF%F_DVDXZ)
IF (LF_DVDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DVDXZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DVDXZ)
ENDIF

LF_DVDYZ = ASSOCIATED (SELF%F_DVDYZ)
IF (LF_DVDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DVDYZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DVDYZ)
ENDIF

LF_DWDXZ = ASSOCIATED (SELF%F_DWDXZ)
IF (LF_DWDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DWDXZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DWDXZ)
ENDIF

LF_DWDYZ = ASSOCIATED (SELF%F_DWDYZ)
IF (LF_DWDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DWDYZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DWDYZ)
ENDIF

LF_DRVDXZ = ASSOCIATED (SELF%F_DRVDXZ)
IF (LF_DRVDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DRVDXZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DRVDXZ)
ENDIF

LF_DRVDYZ = ASSOCIATED (SELF%F_DRVDYZ)
IF (LF_DRVDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DRVDYZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DRVDYZ)
ENDIF

LF_DRLDXZ = ASSOCIATED (SELF%F_DRLDXZ)
IF (LF_DRLDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DRLDXZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DRLDXZ)
ENDIF

LF_DRLDYZ = ASSOCIATED (SELF%F_DRLDYZ)
IF (LF_DRLDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DRLDYZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DRLDYZ)
ENDIF

LF_DRIDXZ = ASSOCIATED (SELF%F_DRIDXZ)
IF (LF_DRIDXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DRIDXZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DRIDXZ)
ENDIF

LF_DRIDYZ = ASSOCIATED (SELF%F_DRIDYZ)
IF (LF_DRIDYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DRIDYZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DRIDYZ)
ENDIF

LF_DTHETADXZ = ASSOCIATED (SELF%F_DTHETADXZ)
IF (LF_DTHETADXZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DTHETADXZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DTHETADXZ)
ENDIF

LF_DTHETADYZ = ASSOCIATED (SELF%F_DTHETADYZ)
IF (LF_DTHETADYZ .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_DTHETADYZ)
  !$ACC ENTER DATA ATTACH (SELF%F_DTHETADYZ)
ENDIF

END SUBROUTINE

END SUBMODULE
