SUBMODULE (YOMXFU_TYPE) YOMXFU_TYPE_TXFU_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_TXFU (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (TXFU), TARGET :: SELF
CLASS (TXFU_KEYS), POINTER :: YLSUPER
INTEGER :: J1
LOGICAL :: LF_CAPE, LF_CLPH, LF_CLPHMF, LF_CLWC, LF_CLWC2, LF_CTOP, LF_DICQ, LF_DICS, LF_DITQ, LF_DITS
LOGICAL :: LF_FCHSP, LF_FEVL, LF_FEVV, LF_FLWSP, LF_FONTE, LF_FTR, LF_HUN, LF_HUX, LF_MOCON, LF_MRT
LOGICAL :: LF_NBBAS, LF_NBCON, LF_NBHAU, LF_NBMOY, LF_NEB, LF_NEBT, LF_NUCLS, LF_NVCLS, LF_PLCG, LF_PLCH
LOGICAL :: LF_PLCL, LF_PLCN, LF_PLSG, LF_PLSH, LF_PLSL, LF_PLSN, LF_PTYPE, LF_PTYPE2, LF_PTYPESEV, LF_PTYPESEV2
LOGICAL :: LF_QCLS, LF_QICE, LF_QLI, LF_RHCLS, LF_RMNWINDCALC, LF_RMWINDCALC, LF_RSO, LF_RTH, LF_RUISL, LF_RUISP
LOGICAL :: LF_RUISS, LF_SIC, LF_SNWDE, LF_TCLS, LF_THW, LF_TN, LF_TPWCLS, LF_TRCU, LF_TRCV, LF_TRDU
LOGICAL :: LF_TRDV, LF_TRTU, LF_TRTV, LF_TX, LF_UCLS, LF_UGST, LF_UGST2, LF_VCLS, LF_VEIN, LF_VGST
LOGICAL :: LF_VGST2, LF_VISICLD, LF_VISICLD2, LF_VISIHYD, LF_VISIHYD2, LF_VMAXTH, LF_XDIAGH, LTYPE_XFU
YLSUPER => SELF
CALL YLSUPER%ACDC_HOST ()
LTYPE_XFU = ALLOCATED (SELF%TYPE_XFU)
IF (LTYPE_XFU) THEN
  DO J1 = LBOUND (SELF%TYPE_XFU, 1), UBOUND (SELF%TYPE_XFU, 1)
    CALL SELF%TYPE_XFU (J1)%ACDC_HOST ()
  ENDDO
ENDIF

LF_RMWINDCALC = ASSOCIATED (SELF%F_RMWINDCALC)
IF (LF_RMWINDCALC) THEN
  CALL HOST_FIELD_2RB (SELF%F_RMWINDCALC)
ENDIF

LF_RMNWINDCALC = ASSOCIATED (SELF%F_RMNWINDCALC)
IF (LF_RMNWINDCALC) THEN
  CALL HOST_FIELD_2RB (SELF%F_RMNWINDCALC)
ENDIF

CALL SELF%YXFUPT%ACDC_HOST ()

LF_CAPE = ASSOCIATED (SELF%F_CAPE)
IF (LF_CAPE) THEN
  CALL HOST_FIELD_2RB (SELF%F_CAPE)
ENDIF

CALL SELF%YCAPE%ACDC_HOST ()

LF_CLPH = ASSOCIATED (SELF%F_CLPH)
IF (LF_CLPH) THEN
  CALL HOST_FIELD_2RB (SELF%F_CLPH)
ENDIF

CALL SELF%YCLPH%ACDC_HOST ()

LF_CLPHMF = ASSOCIATED (SELF%F_CLPHMF)
IF (LF_CLPHMF) THEN
  CALL HOST_FIELD_2RB (SELF%F_CLPHMF)
ENDIF

CALL SELF%YCLPHMF%ACDC_HOST ()

LF_VMAXTH = ASSOCIATED (SELF%F_VMAXTH)
IF (LF_VMAXTH) THEN
  CALL HOST_FIELD_2RB (SELF%F_VMAXTH)
ENDIF

CALL SELF%YVMAXTH%ACDC_HOST ()

LF_CLWC2 = ASSOCIATED (SELF%F_CLWC2)
IF (LF_CLWC2) THEN
  CALL HOST_FIELD_2RB (SELF%F_CLWC2)
ENDIF

CALL SELF%YCLWC2%ACDC_HOST ()

LF_CLWC = ASSOCIATED (SELF%F_CLWC)
IF (LF_CLWC) THEN
  CALL HOST_FIELD_2RB (SELF%F_CLWC)
ENDIF

CALL SELF%YCLWC%ACDC_HOST ()

LF_CTOP = ASSOCIATED (SELF%F_CTOP)
IF (LF_CTOP) THEN
  CALL HOST_FIELD_2RB (SELF%F_CTOP)
ENDIF

CALL SELF%YCTOP%ACDC_HOST ()

LF_DICQ = ASSOCIATED (SELF%F_DICQ)
IF (LF_DICQ) THEN
  CALL HOST_FIELD_3RB (SELF%F_DICQ)
ENDIF

CALL SELF%YDICQ%ACDC_HOST ()

LF_DICS = ASSOCIATED (SELF%F_DICS)
IF (LF_DICS) THEN
  CALL HOST_FIELD_3RB (SELF%F_DICS)
ENDIF

CALL SELF%YDICS%ACDC_HOST ()

LF_DITQ = ASSOCIATED (SELF%F_DITQ)
IF (LF_DITQ) THEN
  CALL HOST_FIELD_3RB (SELF%F_DITQ)
ENDIF

CALL SELF%YDITQ%ACDC_HOST ()

LF_DITS = ASSOCIATED (SELF%F_DITS)
IF (LF_DITS) THEN
  CALL HOST_FIELD_3RB (SELF%F_DITS)
ENDIF

CALL SELF%YDITS%ACDC_HOST ()

LF_FCHSP = ASSOCIATED (SELF%F_FCHSP)
IF (LF_FCHSP) THEN
  CALL HOST_FIELD_2RB (SELF%F_FCHSP)
ENDIF

CALL SELF%YFCHSP%ACDC_HOST ()

LF_FEVL = ASSOCIATED (SELF%F_FEVL)
IF (LF_FEVL) THEN
  CALL HOST_FIELD_2RB (SELF%F_FEVL)
ENDIF

CALL SELF%YFEVL%ACDC_HOST ()

LF_FEVV = ASSOCIATED (SELF%F_FEVV)
IF (LF_FEVV) THEN
  CALL HOST_FIELD_2RB (SELF%F_FEVV)
ENDIF

CALL SELF%YFEVV%ACDC_HOST ()

LF_FLWSP = ASSOCIATED (SELF%F_FLWSP)
IF (LF_FLWSP) THEN
  CALL HOST_FIELD_2RB (SELF%F_FLWSP)
ENDIF

CALL SELF%YFLWSP%ACDC_HOST ()

LF_FONTE = ASSOCIATED (SELF%F_FONTE)
IF (LF_FONTE) THEN
  CALL HOST_FIELD_2RB (SELF%F_FONTE)
ENDIF

CALL SELF%YFONTE%ACDC_HOST ()

LF_FTR = ASSOCIATED (SELF%F_FTR)
IF (LF_FTR) THEN
  CALL HOST_FIELD_2RB (SELF%F_FTR)
ENDIF

CALL SELF%YFTR%ACDC_HOST ()

LF_HUN = ASSOCIATED (SELF%F_HUN)
IF (LF_HUN) THEN
  CALL HOST_FIELD_2RB (SELF%F_HUN)
ENDIF

CALL SELF%YHUN%ACDC_HOST ()

LF_HUX = ASSOCIATED (SELF%F_HUX)
IF (LF_HUX) THEN
  CALL HOST_FIELD_2RB (SELF%F_HUX)
ENDIF

CALL SELF%YHUX%ACDC_HOST ()

LF_MOCON = ASSOCIATED (SELF%F_MOCON)
IF (LF_MOCON) THEN
  CALL HOST_FIELD_2RB (SELF%F_MOCON)
ENDIF

CALL SELF%YMOCON%ACDC_HOST ()

LF_MRT = ASSOCIATED (SELF%F_MRT)
IF (LF_MRT) THEN
  CALL HOST_FIELD_2RB (SELF%F_MRT)
ENDIF

CALL SELF%YMRT%ACDC_HOST ()

LF_NBBAS = ASSOCIATED (SELF%F_NBBAS)
IF (LF_NBBAS) THEN
  CALL HOST_FIELD_2RB (SELF%F_NBBAS)
ENDIF

CALL SELF%YNBBAS%ACDC_HOST ()

LF_NBCON = ASSOCIATED (SELF%F_NBCON)
IF (LF_NBCON) THEN
  CALL HOST_FIELD_2RB (SELF%F_NBCON)
ENDIF

CALL SELF%YNBCON%ACDC_HOST ()

LF_NBHAU = ASSOCIATED (SELF%F_NBHAU)
IF (LF_NBHAU) THEN
  CALL HOST_FIELD_2RB (SELF%F_NBHAU)
ENDIF

CALL SELF%YNBHAU%ACDC_HOST ()

LF_NBMOY = ASSOCIATED (SELF%F_NBMOY)
IF (LF_NBMOY) THEN
  CALL HOST_FIELD_2RB (SELF%F_NBMOY)
ENDIF

CALL SELF%YNBMOY%ACDC_HOST ()

LF_NEB = ASSOCIATED (SELF%F_NEB)
IF (LF_NEB) THEN
  CALL HOST_FIELD_3RB (SELF%F_NEB)
ENDIF

CALL SELF%YNEB%ACDC_HOST ()

LF_NEBT = ASSOCIATED (SELF%F_NEBT)
IF (LF_NEBT) THEN
  CALL HOST_FIELD_2RB (SELF%F_NEBT)
ENDIF

CALL SELF%YNEBT%ACDC_HOST ()

LF_NUCLS = ASSOCIATED (SELF%F_NUCLS)
IF (LF_NUCLS) THEN
  CALL HOST_FIELD_2RB (SELF%F_NUCLS)
ENDIF

CALL SELF%YNUCLS%ACDC_HOST ()

LF_NVCLS = ASSOCIATED (SELF%F_NVCLS)
IF (LF_NVCLS) THEN
  CALL HOST_FIELD_2RB (SELF%F_NVCLS)
ENDIF

CALL SELF%YNVCLS%ACDC_HOST ()

LF_PLCG = ASSOCIATED (SELF%F_PLCG)
IF (LF_PLCG) THEN
  CALL HOST_FIELD_3RB (SELF%F_PLCG)
ENDIF

CALL SELF%YPLCG%ACDC_HOST ()

LF_PLCH = ASSOCIATED (SELF%F_PLCH)
IF (LF_PLCH) THEN
  CALL HOST_FIELD_3RB (SELF%F_PLCH)
ENDIF

CALL SELF%YPLCH%ACDC_HOST ()

LF_PLCL = ASSOCIATED (SELF%F_PLCL)
IF (LF_PLCL) THEN
  CALL HOST_FIELD_3RB (SELF%F_PLCL)
ENDIF

CALL SELF%YPLCL%ACDC_HOST ()

LF_PLCN = ASSOCIATED (SELF%F_PLCN)
IF (LF_PLCN) THEN
  CALL HOST_FIELD_3RB (SELF%F_PLCN)
ENDIF

CALL SELF%YPLCN%ACDC_HOST ()

LF_PLSG = ASSOCIATED (SELF%F_PLSG)
IF (LF_PLSG) THEN
  CALL HOST_FIELD_3RB (SELF%F_PLSG)
ENDIF

CALL SELF%YPLSG%ACDC_HOST ()

LF_PLSH = ASSOCIATED (SELF%F_PLSH)
IF (LF_PLSH) THEN
  CALL HOST_FIELD_3RB (SELF%F_PLSH)
ENDIF

CALL SELF%YPLSH%ACDC_HOST ()

LF_PLSL = ASSOCIATED (SELF%F_PLSL)
IF (LF_PLSL) THEN
  CALL HOST_FIELD_3RB (SELF%F_PLSL)
ENDIF

CALL SELF%YPLSL%ACDC_HOST ()

LF_PLSN = ASSOCIATED (SELF%F_PLSN)
IF (LF_PLSN) THEN
  CALL HOST_FIELD_3RB (SELF%F_PLSN)
ENDIF

CALL SELF%YPLSN%ACDC_HOST ()

LF_PTYPE2 = ASSOCIATED (SELF%F_PTYPE2)
IF (LF_PTYPE2) THEN
  CALL HOST_FIELD_2RB (SELF%F_PTYPE2)
ENDIF

CALL SELF%YPTYPE2%ACDC_HOST ()

LF_PTYPE = ASSOCIATED (SELF%F_PTYPE)
IF (LF_PTYPE) THEN
  CALL HOST_FIELD_2RB (SELF%F_PTYPE)
ENDIF

CALL SELF%YPTYPE%ACDC_HOST ()

LF_PTYPESEV2 = ASSOCIATED (SELF%F_PTYPESEV2)
IF (LF_PTYPESEV2) THEN
  CALL HOST_FIELD_2RB (SELF%F_PTYPESEV2)
ENDIF

CALL SELF%YPTYPESEV2%ACDC_HOST ()

LF_PTYPESEV = ASSOCIATED (SELF%F_PTYPESEV)
IF (LF_PTYPESEV) THEN
  CALL HOST_FIELD_2RB (SELF%F_PTYPESEV)
ENDIF

CALL SELF%YPTYPESEV%ACDC_HOST ()

LF_QCLS = ASSOCIATED (SELF%F_QCLS)
IF (LF_QCLS) THEN
  CALL HOST_FIELD_2RB (SELF%F_QCLS)
ENDIF

CALL SELF%YQCLS%ACDC_HOST ()

LF_QICE = ASSOCIATED (SELF%F_QICE)
IF (LF_QICE) THEN
  CALL HOST_FIELD_3RB (SELF%F_QICE)
ENDIF

CALL SELF%YQICE%ACDC_HOST ()

LF_QLI = ASSOCIATED (SELF%F_QLI)
IF (LF_QLI) THEN
  CALL HOST_FIELD_3RB (SELF%F_QLI)
ENDIF

CALL SELF%YQLI%ACDC_HOST ()

LF_RHCLS = ASSOCIATED (SELF%F_RHCLS)
IF (LF_RHCLS) THEN
  CALL HOST_FIELD_2RB (SELF%F_RHCLS)
ENDIF

CALL SELF%YRHCLS%ACDC_HOST ()

LF_RSO = ASSOCIATED (SELF%F_RSO)
IF (LF_RSO) THEN
  CALL HOST_FIELD_3RB (SELF%F_RSO)
ENDIF

CALL SELF%YRSO%ACDC_HOST ()

LF_RTH = ASSOCIATED (SELF%F_RTH)
IF (LF_RTH) THEN
  CALL HOST_FIELD_3RB (SELF%F_RTH)
ENDIF

CALL SELF%YRTH%ACDC_HOST ()

LF_RUISL = ASSOCIATED (SELF%F_RUISL)
IF (LF_RUISL) THEN
  CALL HOST_FIELD_2RB (SELF%F_RUISL)
ENDIF

CALL SELF%YRUISL%ACDC_HOST ()

LF_RUISP = ASSOCIATED (SELF%F_RUISP)
IF (LF_RUISP) THEN
  CALL HOST_FIELD_2RB (SELF%F_RUISP)
ENDIF

CALL SELF%YRUISP%ACDC_HOST ()

LF_RUISS = ASSOCIATED (SELF%F_RUISS)
IF (LF_RUISS) THEN
  CALL HOST_FIELD_2RB (SELF%F_RUISS)
ENDIF

CALL SELF%YRUISS%ACDC_HOST ()

LF_SIC = ASSOCIATED (SELF%F_SIC)
IF (LF_SIC) THEN
  CALL HOST_FIELD_2RB (SELF%F_SIC)
ENDIF

CALL SELF%YSIC%ACDC_HOST ()

LF_TCLS = ASSOCIATED (SELF%F_TCLS)
IF (LF_TCLS) THEN
  CALL HOST_FIELD_2RB (SELF%F_TCLS)
ENDIF

CALL SELF%YTCLS%ACDC_HOST ()

LF_THW = ASSOCIATED (SELF%F_THW)
IF (LF_THW) THEN
  CALL HOST_FIELD_2RB (SELF%F_THW)
ENDIF

CALL SELF%YTHW%ACDC_HOST ()

LF_TN = ASSOCIATED (SELF%F_TN)
IF (LF_TN) THEN
  CALL HOST_FIELD_2RB (SELF%F_TN)
ENDIF

CALL SELF%YTN%ACDC_HOST ()

LF_TPWCLS = ASSOCIATED (SELF%F_TPWCLS)
IF (LF_TPWCLS) THEN
  CALL HOST_FIELD_2RB (SELF%F_TPWCLS)
ENDIF

CALL SELF%YTPWCLS%ACDC_HOST ()

LF_TRCU = ASSOCIATED (SELF%F_TRCU)
IF (LF_TRCU) THEN
  CALL HOST_FIELD_3RB (SELF%F_TRCU)
ENDIF

CALL SELF%YTRCU%ACDC_HOST ()

LF_TRCV = ASSOCIATED (SELF%F_TRCV)
IF (LF_TRCV) THEN
  CALL HOST_FIELD_3RB (SELF%F_TRCV)
ENDIF

CALL SELF%YTRCV%ACDC_HOST ()

LF_TRDU = ASSOCIATED (SELF%F_TRDU)
IF (LF_TRDU) THEN
  CALL HOST_FIELD_3RB (SELF%F_TRDU)
ENDIF

CALL SELF%YTRDU%ACDC_HOST ()

LF_TRDV = ASSOCIATED (SELF%F_TRDV)
IF (LF_TRDV) THEN
  CALL HOST_FIELD_3RB (SELF%F_TRDV)
ENDIF

CALL SELF%YTRDV%ACDC_HOST ()

LF_TRTU = ASSOCIATED (SELF%F_TRTU)
IF (LF_TRTU) THEN
  CALL HOST_FIELD_3RB (SELF%F_TRTU)
ENDIF

CALL SELF%YTRTU%ACDC_HOST ()

LF_TRTV = ASSOCIATED (SELF%F_TRTV)
IF (LF_TRTV) THEN
  CALL HOST_FIELD_3RB (SELF%F_TRTV)
ENDIF

CALL SELF%YTRTV%ACDC_HOST ()

LF_TX = ASSOCIATED (SELF%F_TX)
IF (LF_TX) THEN
  CALL HOST_FIELD_2RB (SELF%F_TX)
ENDIF

CALL SELF%YTX%ACDC_HOST ()

LF_UCLS = ASSOCIATED (SELF%F_UCLS)
IF (LF_UCLS) THEN
  CALL HOST_FIELD_2RB (SELF%F_UCLS)
ENDIF

CALL SELF%YUCLS%ACDC_HOST ()

LF_UGST2 = ASSOCIATED (SELF%F_UGST2)
IF (LF_UGST2) THEN
  CALL HOST_FIELD_2RB (SELF%F_UGST2)
ENDIF

CALL SELF%YUGST2%ACDC_HOST ()

LF_UGST = ASSOCIATED (SELF%F_UGST)
IF (LF_UGST) THEN
  CALL HOST_FIELD_2RB (SELF%F_UGST)
ENDIF

CALL SELF%YUGST%ACDC_HOST ()

LF_VCLS = ASSOCIATED (SELF%F_VCLS)
IF (LF_VCLS) THEN
  CALL HOST_FIELD_2RB (SELF%F_VCLS)
ENDIF

CALL SELF%YVCLS%ACDC_HOST ()

LF_VEIN = ASSOCIATED (SELF%F_VEIN)
IF (LF_VEIN) THEN
  CALL HOST_FIELD_2RB (SELF%F_VEIN)
ENDIF

CALL SELF%YVEIN%ACDC_HOST ()

LF_VGST2 = ASSOCIATED (SELF%F_VGST2)
IF (LF_VGST2) THEN
  CALL HOST_FIELD_2RB (SELF%F_VGST2)
ENDIF

CALL SELF%YVGST2%ACDC_HOST ()

LF_VGST = ASSOCIATED (SELF%F_VGST)
IF (LF_VGST) THEN
  CALL HOST_FIELD_2RB (SELF%F_VGST)
ENDIF

CALL SELF%YVGST%ACDC_HOST ()

LF_VISICLD2 = ASSOCIATED (SELF%F_VISICLD2)
IF (LF_VISICLD2) THEN
  CALL HOST_FIELD_2RB (SELF%F_VISICLD2)
ENDIF

CALL SELF%YVISICLD2%ACDC_HOST ()

LF_VISICLD = ASSOCIATED (SELF%F_VISICLD)
IF (LF_VISICLD) THEN
  CALL HOST_FIELD_2RB (SELF%F_VISICLD)
ENDIF

CALL SELF%YVISICLD%ACDC_HOST ()

LF_VISIHYD2 = ASSOCIATED (SELF%F_VISIHYD2)
IF (LF_VISIHYD2) THEN
  CALL HOST_FIELD_2RB (SELF%F_VISIHYD2)
ENDIF

CALL SELF%YVISIHYD2%ACDC_HOST ()

LF_VISIHYD = ASSOCIATED (SELF%F_VISIHYD)
IF (LF_VISIHYD) THEN
  CALL HOST_FIELD_2RB (SELF%F_VISIHYD)
ENDIF

CALL SELF%YVISIHYD%ACDC_HOST ()

LF_XDIAGH = ASSOCIATED (SELF%F_XDIAGH)
IF (LF_XDIAGH) THEN
  CALL HOST_FIELD_2RB (SELF%F_XDIAGH)
ENDIF

CALL SELF%YXDIAGH%ACDC_HOST ()

LF_SNWDE = ASSOCIATED (SELF%F_SNWDE)
IF (LF_SNWDE) THEN
  CALL HOST_FIELD_2RB (SELF%F_SNWDE)
ENDIF

CALL SELF%YSNWDE%ACDC_HOST ()

END SUBROUTINE

END SUBMODULE
