INTERFACE
SUBROUTINE RECMWF_OUTLINE_001 (YDCPG_OPTS, YDMODEL, YDCPG_BNDS, PRSWINHF)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (INOUT)::PRSWINHF (YDCPG_OPTS%KLON)
ENDSUBROUTINE
END INTERFACE
