MODULE UTIL_CLOUDPAR_T_MOD

USE MODD_CLOUDPAR_n, ONLY : CLOUDPAR_T

INTERFACE SAVE
MODULE PROCEDURE SAVE_CLOUDPAR_T
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CLOUDPAR_T
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_CLOUDPAR_T
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_CLOUDPAR_T
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_CLOUDPAR_T
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_CLOUDPAR_T
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_CLOUDPAR_T
END INTERFACE


CONTAINS

SUBROUTINE SAVE_CLOUDPAR_T (SELF, KLUN)

IMPLICIT NONE
TYPE (CLOUDPAR_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NSPLITR
WRITE (KLUN) SELF%NSPLITG
END SUBROUTINE

SUBROUTINE LOAD_CLOUDPAR_T (SELF, KLUN)

IMPLICIT NONE
TYPE (CLOUDPAR_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NSPLITR
READ (KLUN) SELF%NSPLITG
END SUBROUTINE


SUBROUTINE COPY_CLOUDPAR_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CLOUDPAR_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_CLOUDPAR_T (SELF)

IMPLICIT NONE
TYPE (CLOUDPAR_T), TARGET :: SELF


END SUBROUTINE

     

SUBROUTINE CRC64_CLOUDPAR_T (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (CLOUDPAR_T), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPLITR), CDPATH//'%NSPLITR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPLITG), CDPATH//'%NSPLITG'

END SUBROUTINE

SUBROUTINE WIPE_CLOUDPAR_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CLOUDPAR_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION SIZE_CLOUDPAR_T (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (CLOUDPAR_T),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NSPLITR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPLITR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSPLITG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSPLITG'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
