SUBROUTINE LAIDLI_OPENACC (KSLB1, KPROMA, KST, KEND, KFLEV&
&, KFLDN, KFLDX, PDLAT, PDLO, KL0, PXSL, PXF, YDSTACK)
!$ACC ROUTINE (LAIDLI_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


INTEGER (KIND=JPIM), INTENT (IN)::KSLB1
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
INTEGER (KIND=JPIM), INTENT (IN)::KFLDN
INTEGER (KIND=JPIM), INTENT (IN)::KFLDX
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
REAL (KIND=JPRB), INTENT (IN)::PDLAT (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDLO (KPROMA, KFLEV, 1:2)
INTEGER (KIND=JPIM), INTENT (IN)::KL0 (KPROMA, KFLEV, 1:2)
REAL (KIND=JPRB), INTENT (IN)::PXSL (KSLB1*(KFLDX-KFLDN+1))
REAL (KIND=JPRB), INTENT (OUT)::PXF (KPROMA, KFLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRB)::Z2
REAL (KIND=JPRB)::Z1

#include "interp.func.h"

JROF = KST



DO JLEV=1, KFLEV
  
  Z1=PXSL (KL0 (JROF, JLEV, 1)+1)
  Z1=FDWEIGHT (PDLO (JROF, JLEV, 1), Z1, PXSL (KL0 (JROF, JLEV, 1)+2))
  Z2=PXSL (KL0 (JROF, JLEV, 2)+1)
  Z2=FDWEIGHT (PDLO (JROF, JLEV, 2), Z2, PXSL (KL0 (JROF, JLEV, 2)+2))
  PXF (JROF, JLEV)=FDWEIGHT (PDLAT (JROF, JLEV), Z1, Z2)
  
ENDDO


END SUBROUTINE LAIDLI_OPENACC
