INTERFACE
SUBROUTINE CPCFU_OUTLINE_005 (LDRESET, YDCFU, YDCPG_BNDS, YDCPG_DYN0&
&, YDCPG_MISC, YDCPG_OPTS, YDCST, YDRIP, YDVARS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_DYN_TYPE, CPG_MISC_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMCFU,ONLY:TCFU
USE YOMCST,ONLY:TCST
USE YOMRIP,ONLY:TRIP
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

LOGICAL, INTENT (INOUT)::LDRESET
TYPE (TCFU), INTENT (INOUT)::YDCFU
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_DYN_TYPE), INTENT (IN)::YDCPG_DYN0
TYPE (CPG_MISC_TYPE), INTENT (IN)::YDCPG_MISC
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TRIP), INTENT (IN)::YDRIP
TYPE (FIELD_VARIABLES), INTENT (IN)::YDVARS
ENDSUBROUTINE
END INTERFACE
