SUBROUTINE CPXFU_OUTLINE_004 (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_OUT&
&, YDPRECIPS, YDXFU, PDPRECIPS, PDPRECIPS2)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_OUT_TYPE
USE YOMDPRECIPS,ONLY:TDPRECIPS
USE YOMXFU,ONLY:TXFU
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_OUT_TYPE), INTENT (IN)::YDMF_PHYS_OUT
TYPE (TDPRECIPS), INTENT (IN)::YDPRECIPS
TYPE (TXFU), INTENT (INOUT)::YDXFU
REAL (KIND=JPRB), INTENT (IN)::PDPRECIPS (YDCPG_OPTS%KLON, YDPRECIPS%NDTPREC)
REAL (KIND=JPRB), INTENT (IN)::PDPRECIPS2 (YDCPG_OPTS%KLON, YDPRECIPS%NDTPREC2)
#include "dprecips_xfu.intfb.h"
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('CPXFU_OUTLINE_004', 0, ZHOOK_HANDLE)

IF (YDXFU%YTHW%LACTIVE) THEN
  YDXFU%THW (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%FCS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, 1)
ENDIF


IF (YDXFU%YPTYPE%LACTIVE) THEN
  CALL DPRECIPS_XFU (YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDPRECIPS&
  &%NDTPREC, 0_JPIM, PDPRECIPS, YDXFU%PTYPE, YDXFU%LRESET_PRECIP)
ENDIF


IF (YDXFU%YPTYPESEV%LACTIVE) THEN
  CALL DPRECIPS_XFU (YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDPRECIPS&
  &%NDTPREC, 2_JPIM, PDPRECIPS, YDXFU%PTYPESEV, YDXFU%LRESET_PRECIP)
ENDIF


IF (YDXFU%YPTYPE2%LACTIVE) THEN
  CALL DPRECIPS_XFU (YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDPRECIPS&
  &%NDTPREC2, 0_JPIM, PDPRECIPS2, YDXFU%PTYPE2, YDXFU%LRESET_PRECIP)
ENDIF


IF (YDXFU%YPTYPESEV2%LACTIVE) THEN
  CALL DPRECIPS_XFU (YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDPRECIPS&
  &%NDTPREC2, 2_JPIM, PDPRECIPS2, YDXFU%PTYPESEV2, YDXFU%LRESET_PRECIP)
ENDIF

IF (LHOOK) CALL DR_HOOK ('CPXFU_OUTLINE_004', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
