INTERFACE
SUBROUTINE CPXFU_OUTLINE_004 (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_OUT&
&, YDPRECIPS, YDXFU, PDPRECIPS, PDPRECIPS2)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_OUT_TYPE
USE YOMDPRECIPS,ONLY:TDPRECIPS
USE YOMXFU,ONLY:TXFU
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_OUT_TYPE), INTENT (IN)::YDMF_PHYS_OUT
TYPE (TDPRECIPS), INTENT (IN)::YDPRECIPS
TYPE (TXFU), INTENT (INOUT)::YDXFU
REAL (KIND=JPRB), INTENT (IN)::PDPRECIPS (YDCPG_OPTS%KLON, YDPRECIPS%NDTPREC)
REAL (KIND=JPRB), INTENT (IN)::PDPRECIPS2 (YDCPG_OPTS%KLON, YDPRECIPS%NDTPREC2)
ENDSUBROUTINE
END INTERFACE
