SUBMODULE (MODD_RAIN_ICE_DESCR_N) MODD_RAIN_ICE_DESCR_N_RAIN_ICE_DESCR_T_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_RAIN_ICE_DESCR_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (RAIN_ICE_DESCR_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LXRTMIN
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LXRTMIN = ALLOCATED (SELF%XRTMIN)
IF (LXRTMIN) THEN
  !$ACC ENTER DATA CREATE (SELF%XRTMIN)
  !$ACC UPDATE DEVICE (SELF%XRTMIN)
  !$ACC ENTER DATA ATTACH (SELF%XRTMIN)
ENDIF

END SUBROUTINE

END SUBMODULE
