SUBMODULE (MODD_PARAM_LIMA_COLD) MODD_PARAM_LIMA_COLD_PARAM_LIMA_COLD_T_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_PARAM_LIMA_COLD_T (SELF, KLUN)

IMPLICIT NONE
CLASS (PARAM_LIMA_COLD_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LXKER_N_SSCS
READ (KLUN) SELF%XLBEXI
READ (KLUN) SELF%XLBI
READ (KLUN) SELF%XLBEXS
READ (KLUN) SELF%XLBS
READ (KLUN) SELF%XNS
READ (KLUN) SELF%XAI
READ (KLUN) SELF%XBI
READ (KLUN) SELF%XC_I
READ (KLUN) SELF%XDI
READ (KLUN) SELF%XF0I
READ (KLUN) SELF%XF2I
READ (KLUN) SELF%XC1I
READ (KLUN) SELF%XF0IS
READ (KLUN) SELF%XF1IS
READ (KLUN) SELF%XAS
READ (KLUN) SELF%XBS
READ (KLUN) SELF%XCS
READ (KLUN) SELF%XDS
READ (KLUN) SELF%XCCS
READ (KLUN) SELF%XCXS
READ (KLUN) SELF%XF0S
READ (KLUN) SELF%XF1S
READ (KLUN) SELF%XC1S
READ (KLUN) SELF%XLBDAS_MIN
READ (KLUN) SELF%XLBDAS_MAX
READ (KLUN) SELF%XFVELOS
READ (KLUN) SELF%XTRANS_MP_GAMMAS
READ (KLUN) SELF%XFSEDRI
READ (KLUN) SELF%XFSEDCI
READ (KLUN) SELF%XFSEDRS
READ (KLUN) SELF%XFSEDCS
READ (KLUN) SELF%XFSEDS
READ (KLUN) SELF%XEXSEDS
READ (KLUN) SELF%XNUC_DEP
READ (KLUN) SELF%XEXSI_DEP
READ (KLUN) SELF%XEX_DEP
READ (KLUN) SELF%XNUC_CON
READ (KLUN) SELF%XEXTT_CON
READ (KLUN) SELF%XEX_CON
READ (KLUN) SELF%XMNU0
READ (KLUN) SELF%XRHOI_HONH
READ (KLUN) SELF%XCEXP_DIFVAP_HONH
READ (KLUN) SELF%XCOEF_DIFVAP_HONH
READ (KLUN) SELF%XRCOEF_HONH
READ (KLUN) SELF%XCRITSAT1_HONH
READ (KLUN) SELF%XCRITSAT2_HONH
READ (KLUN) SELF%XTMIN_HONH
READ (KLUN) SELF%XTMAX_HONH
READ (KLUN) SELF%XDLNJODT1_HONH
READ (KLUN) SELF%XDLNJODT2_HONH
READ (KLUN) SELF%XC1_HONH
READ (KLUN) SELF%XC2_HONH
READ (KLUN) SELF%XC3_HONH
READ (KLUN) SELF%XC_HONC
READ (KLUN) SELF%XR_HONC
READ (KLUN) SELF%XTEXP1_HONC
READ (KLUN) SELF%XTEXP2_HONC
READ (KLUN) SELF%XTEXP3_HONC
READ (KLUN) SELF%XTEXP4_HONC
READ (KLUN) SELF%XTEXP5_HONC
READ (KLUN) SELF%XCSCNVI_MAX
READ (KLUN) SELF%XLBDASCNVI_MAX
READ (KLUN) SELF%XRHORSMIN
READ (KLUN) SELF%XDSCNVI_LIM
READ (KLUN) SELF%XLBDASCNVI_LIM
READ (KLUN) SELF%XC0DEPSI
READ (KLUN) SELF%XC1DEPSI
READ (KLUN) SELF%XR0DEPSI
READ (KLUN) SELF%XR1DEPSI
READ (KLUN) SELF%XSCFAC
READ (KLUN) SELF%X0DEPI
READ (KLUN) SELF%X2DEPI
READ (KLUN) SELF%X0DEPS
READ (KLUN) SELF%X1DEPS
READ (KLUN) SELF%XEX0DEPS
READ (KLUN) SELF%XEX1DEPS
READ (KLUN) SELF%XDICNVS_LIM
READ (KLUN) SELF%XLBDAICNVS_LIM
READ (KLUN) SELF%XC0DEPIS
READ (KLUN) SELF%XC1DEPIS
READ (KLUN) SELF%XR0DEPIS
READ (KLUN) SELF%XR1DEPIS
READ (KLUN) SELF%XCOLEXIS
READ (KLUN) SELF%XAGGS_CLARGE1
READ (KLUN) SELF%XAGGS_CLARGE2
READ (KLUN) SELF%XAGGS_RLARGE1
READ (KLUN) SELF%XAGGS_RLARGE2
READ (KLUN) SELF%XFIAGGS
READ (KLUN) SELF%XEXIAGGS
READ (KLUN) SELF%XACCS1
READ (KLUN) SELF%XSPONBUDS1
READ (KLUN) SELF%XSPONBUDS2
READ (KLUN) SELF%XSPONBUDS3
READ (KLUN) SELF%XSPONCOEFS2
READ (KLUN) SELF%XKER_ZRNIC_A1
READ (KLUN) SELF%XKER_ZRNIC_A2
READ (KLUN) SELF%XSELFI
READ (KLUN) SELF%XCOLEXII
READ (KLUN) LXKER_N_SSCS
IF (LXKER_N_SSCS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%XKER_N_SSCS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) SELF%XKER_N_SSCS
ENDIF
READ (KLUN) SELF%XCOLSS
READ (KLUN) SELF%XCOLEXSS
READ (KLUN) SELF%XFNSSCS
READ (KLUN) SELF%XLBNSSCS1
READ (KLUN) SELF%XLBNSSCS2
READ (KLUN) SELF%XSCINTP1S
READ (KLUN) SELF%XSCINTP2S
READ (KLUN) SELF%NSCLBDAS
READ (KLUN) SELF%XAUTO3
READ (KLUN) SELF%XAUTO4
READ (KLUN) SELF%XLAUTS
READ (KLUN) SELF%XLAUTS_THRESHOLD
READ (KLUN) SELF%XITAUTS
READ (KLUN) SELF%XITAUTS_THRESHOLD
READ (KLUN) SELF%XTEXAUTI
READ (KLUN) SELF%XCONCI_MAX
READ (KLUN) SELF%XFREFFI
READ (KLUN) SELF%XALPHA1
READ (KLUN) SELF%XALPHA2
READ (KLUN) SELF%XBETA1
READ (KLUN) SELF%XBETA2
READ (KLUN) SELF%XNU10
READ (KLUN) SELF%XNU20
END SUBROUTINE

END SUBMODULE
