SUBMODULE (MODD_PARAM_ICE_N) MODD_PARAM_ICE_N_PARAM_ICE_T_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_PARAM_ICE_T (SELF)

IMPLICIT NONE
CLASS (PARAM_ICE_T), TARGET :: SELF


END SUBROUTINE

END SUBMODULE
