
SUBROUTINE SIGAM_GP_OPENACC (YDCST, YDGEOMETRY, YDDYN&
&, KLON, KLEV, KIDIA, KFDIA, PD, PT, PSP, YDSTACK)
!$ACC ROUTINE (SIGAM_GP_OPENACC) SEQ
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOMDYN,ONLY:TDYN
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (TDYN), INTENT (IN)::YDDYN
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (OUT)::PD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PSP (KLON)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
fxtran_acdc_temp (REAL (KIND=JPRB), ZSPHI, (KLON, 0:KLEV+1))
fxtran_acdc_temp (REAL (KIND=JPRB), ZOUT, (KLON, KLEV))
REAL (KIND=JPRB)::ZSPHIX 
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
CHARACTER (LEN=4)::CLOPER

#include "verdisint_openacc.intfb.h"

YLSTACK = YDSTACK



IF (KIND (ZSPHI) == 8) THEN
    fxtran_acdc_alloc8 (ZSPHI)
ELSEIF (KIND (ZSPHI) == 4) THEN
    fxtran_acdc_alloc4 (ZSPHI)
ELSE
    STOP 1
ENDIF


IF (KIND (ZOUT) == 8) THEN
    fxtran_acdc_alloc8 (ZOUT)
ELSEIF (KIND (ZOUT) == 4) THEN
    fxtran_acdc_alloc4 (ZOUT)
ELSE
    STOP 1
ENDIF


JLON = KIDIA







IF (YDGEOMETRY%YRVERT_GEOM%YRCVER%LVERTFE) THEN
  CLOPER='IBOT'

  IF (YDGEOMETRY%YRVERT_GEOM%YRCVER%LVFE_COMPATIBLE)  THEN
    CLOPER='INTG'
  ENDIF


  DO JLEV=1, KLEV
    
    ZSPHI (JLON, JLEV)=-YDCST%RD*PT (JLON, JLEV)*YDDYN%SILNPR&
    &(JLEV)*YDGEOMETRY%YRVERT_GEOM%YRVETA%VFE_RDETAH (JLEV)
  
  ENDDO

  ZSPHI (JLON, 0)=0.0_JPRB
  ZSPHI (JLON, KLEV+1)=0.0_JPRB
  CALL VERDISINT_OPENACC (YDGEOMETRY%YRVERT_GEOM%YRVFE, YDGEOMETRY%YRVERT_GEOM%YRCVER, CLOPER,'11&
  &', KLON, KIDIA, KFDIA, KLEV, ZSPHI, ZOUT, KCHUNK=YDGEOMETRY%YRDIM%NPROMA, YDSTACK=YLSTACK)

  DO JLEV=1, KLEV
    
    PD (JLON, JLEV)=ZOUT (JLON, JLEV)+PSP (JLON)*YDDYN%SIRPRG
  
  ENDDO

ELSE
  ZSPHIX =0.0_JPRB

  DO JLEV=KLEV, 1,-1
    
    PD (JLON, JLEV)=ZSPHIX +YDDYN%SIALPH(JLEV)*YDCST%RD*PT (JLON, JLEV)+PSP (JLON)*YDDYN%SIRPRG
    ZSPHIX =ZSPHIX +YDCST%RD*PT (JLON, JLEV)*YDDYN%SILNPR(JLEV)
  
  ENDDO

ENDIF




END SUBROUTINE SIGAM_GP_OPENACC
