MODULE UTIL_MF_PHYS_NEXT_STATE_3D_TYPE_MOD

USE MF_PHYS_NEXT_STATE_TYPE_MOD, ONLY : MF_PHYS_NEXT_STATE_3D_TYPE



INTERFACE COPY
MODULE PROCEDURE COPY_MF_PHYS_NEXT_STATE_3D_TYPE
END INTERFACE


     

INTERFACE WIPE
MODULE PROCEDURE WIPE_MF_PHYS_NEXT_STATE_3D_TYPE
END INTERFACE



CONTAINS





SUBROUTINE COPY_MF_PHYS_NEXT_STATE_3D_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_P

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LF_P = ASSOCIATED (SELF%F_P)
IF (LF_P .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_P)
  !$ACC ENTER DATA ATTACH (SELF%F_P)
ENDIF

END SUBROUTINE



     



SUBROUTINE WIPE_MF_PHYS_NEXT_STATE_3D_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_P

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_P = ASSOCIATED (SELF%F_P)
IF (LF_P .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_P)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
