SUBROUTINE GPRCP_EXPL (YDCST, YDCPG_BNDS, YDCPG_OPTS, PCP, PR, PKAP, YDVARS, KGFLTYP)
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK
USE YOMCST,ONLY:TCST
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN)::KGFLTYP
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (OUT)::PCP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (OUT)::PR (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), OPTIONAL, INTENT (OUT)::PKAP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
#include "abor1.intfb.h"
#include "gprcp_expl_outline_005.intfb.h"
#include "gprcp_expl_outline_004.intfb.h"
#include "gprcp_expl_outline_003.intfb.h"
#include "gprcp_expl_outline_002.intfb.h"
#include "gprcp_expl_outline_001.intfb.h"
#include "gprcp_expl_outline_000.intfb.h"
REAL (KIND=JPRB), POINTER::ZR (:,:)
REAL (KIND=JPRB), POINTER::ZCP (:,:)
LOGICAL::LLCP
REAL (KIND=JPRB), TARGET::ZR0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), TARGET::ZCP0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
INTEGER (KIND=JPIM)::IFLD
INTEGER (KIND=JPIM)::JFLD


INTEGER (KIND=JPIM)::IGFLTYP
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ("GPRCP_EXPL", 0, ZHOOK_HANDLE)



IF (PRESENT (PR)) THEN
  ZR=>PR
ELSEIF (PRESENT (PKAP)) THEN
  ZR=>ZR0
ELSE
  CALL ABOR1 ('GPRCP_EXPL: EXPECTED PR OR PKAP')
ENDIF

LLCP=.TRUE.

IF (PRESENT (PCP)) THEN
  ZCP=>PCP
ELSEIF (PRESENT (PKAP)) THEN
  ZCP=>ZCP0
ELSE
  ZCP=>NULL ()
  LLCP=.FALSE.
ENDIF

IGFLTYP=0

IF (PRESENT (KGFLTYP))  THEN
  IGFLTYP=KGFLTYP
ENDIF

IFLD=SIZE (YDVARS%GFL_PTR)
CALL GPRCP_EXPL_OUTLINE_000 (LLCP, ZCP, ZR)

SELECTCASE (IGFLTYP)
CASE (0)

  DO JFLD=1, IFLD

    IF (YDVARS%GFL_PTR (JFLD)%YCOMP%LTHERMACT) THEN
      CALL GPRCP_EXPL_OUTLINE_001 (LLCP, JFLD, YDCPG_BNDS, YDCPG_OPTS, YDCST, YDVARS, ZCP, ZR)
    ENDIF

  ENDDO

CASE (1)

  DO JFLD=1, IFLD

    IF (YDVARS%GFL_PTR (JFLD)%YCOMP%LTHERMACT) THEN
      CALL GPRCP_EXPL_OUTLINE_002 (LLCP, JFLD, YDCPG_BNDS, YDCPG_OPTS, YDCST, YDVARS, ZCP, ZR)
    ENDIF

  ENDDO

CASE (9)

  DO JFLD=1, IFLD

    IF (YDVARS%GFL_PTR (JFLD)%YCOMP%LTHERMACT) THEN
      CALL GPRCP_EXPL_OUTLINE_003 (LLCP, JFLD, YDCPG_BNDS, YDCPG_OPTS, YDCST, YDVARS, ZCP, ZR)
    ENDIF

  ENDDO

CASE DEFAULT
  CALL ABOR1 ('UNEXPECTED IGFLTYP')
ENDSELECT

CALL GPRCP_EXPL_OUTLINE_004 (LLCP, YDCPG_BNDS, YDCPG_OPTS, YDCST, ZCP, ZR)

IF (PRESENT (PKAP)) THEN
  CALL GPRCP_EXPL_OUTLINE_005 (YDCPG_BNDS, YDCPG_OPTS, ZCP, ZR, PKAP)
ENDIF


IF (LHOOK) CALL DR_HOOK ("GPRCP_EXPL", 1, ZHOOK_HANDLE)
ENDSUBROUTINE GPRCP_EXPL
