SUBROUTINE SCAN2M_TS (YDGEOMETRY, YDVARS, YDCPG_OPTS, YDCPG_BNDS)
USE PARKIND1,ONLY:JPIM
USE YOMHOOK,ONLY:DR_HOOK, JPHOOK, LHOOK
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY

IMPLICIT NONE


TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS


INTEGER (KIND=JPIM)::JFLD
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
#include "scan2m_ts_outline_000.intfb.h"
IF (LHOOK) CALL DR_HOOK ('SCAN2M_TS', 0, ZHOOK_HANDLE)





DO JFLD=1, SIZE (YDVARS%GFL_PTR)

  IF (YDVARS%GFL_PTR (JFLD)%YCOMP%LGP.AND.YDVARS%GFL_PTR (JFLD)%YCOMP%LT1) THEN

    IF (YDVARS%GFL_PTR (JFLD)%YCOMP%NCOUPLING==0) THEN
      CALL SCAN2M_TS_OUTLINE_000 (JFLD, YDCPG_BNDS, YDGEOMETRY, YDVARS)
    ENDIF

  ENDIF

ENDDO



IF (LHOOK) CALL DR_HOOK ('SCAN2M_TS', 1, ZHOOK_HANDLE)
ENDSUBROUTINE SCAN2M_TS
