
SUBROUTINE CUADJTQ_OPENACC (YDTHF, YDCST, YDEPHLI, KIDIA, KFDIA, KLON&
&, KLEV, KK, PSP, PT, PQ, LDFLAG, KCALL, LDOFLAG, YDSTACK)
!$ACC ROUTINE (CUADJTQ_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOEPHLI,ONLY:TEPHLI
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KK
REAL (KIND=JPRB), INTENT (IN)::PSP (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQ (KLON, KLEV)
LOGICAL, INTENT (IN)::LDFLAG (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCALL
LOGICAL, INTENT (IN), OPTIONAL::LDOFLAG (KLON)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
INTEGER (KIND=JPIM)::JL
REAL (KIND=JPRB)::ZQP
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZQSAT
REAL (KIND=JPRB)::ZQMAX
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZFOEEWL
REAL (KIND=JPRB)::ZFOEEWI
REAL (KIND=JPRB)::ZCOR
REAL (KIND=JPRB)::ZCOND1
REAL (KIND=JPRB)::ZCOND
REAL (KIND=JPRB)::Z2S
REAL (KIND=JPRB)::Z1S
REAL (KIND=JPRB)::ZF
REAL (KIND=JPRB)::ZI
REAL (KIND=JPRB)::ZL
LOGICAL::LLFLAG 

#include "fcttre.func.h"
#include "cuadjtq.func.h"


JL = KIDIA



ZQMAX=0.5_JPRB

IF (.NOT.YDEPHLI%LPHYLIN) THEN

  IF (KCALL==1.OR.KCALL==6) THEN
    LLFLAG =LDFLAG (JL)

    IF (KCALL==6) THEN

      IF (PRESENT (LDOFLAG)) THEN
        LLFLAG =LLFLAG .AND..NOT.LDOFLAG (JL)
      ELSE
        CALL FXTRAN_ACDC_ABORT ("CUADJTQ: LDOFLAG has to be present when KCALL==6")
      ENDIF

    ENDIF


    

    IF (LLFLAG ) THEN
      ZQP=1.0_JPRB/PSP (JL)
      ZL=1.0_JPRB/(PT (JL, KK)-YDTHF%R4LES)
      ZI=1.0_JPRB/(PT (JL, KK)-YDTHF%R4IES)
      ZQSAT=YDTHF%R2ES*(FOEALFCU (PT (JL, KK))*EXP (YDTHF%R3LES*(PT (JL, KK)-YDCST%RTT)*ZL&
      &)+(1.0_JPRB-FOEALFCU (PT (JL, KK)))*EXP (YDTHF%R3IES*(PT (JL, KK)-YDCST%RTT)*ZI))
      ZQSAT=ZQSAT*ZQP
      ZQSAT=MIN (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
      ZF=FOEALFCU (PT (JL, KK))*YDTHF%R5ALVCP*ZL**2+(1.0_JPRB-FOEALFCU (PT (JL, KK)))*YDTHF%R5ALSCP*ZI**2
      ZCOND=(PQ (JL, KK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)
      ZCOND=MAX (ZCOND, 0.0_JPRB)
      PT (JL, KK)=PT (JL, KK)+FOELDCPMCU (PT (JL, KK))*ZCOND
      PQ (JL, KK)=PQ (JL, KK)-ZCOND
      ZL=1.0_JPRB/(PT (JL, KK)-YDTHF%R4LES)
      ZI=1.0_JPRB/(PT (JL, KK)-YDTHF%R4IES)
      ZQSAT=YDTHF%R2ES*(FOEALFCU (PT (JL, KK))*EXP (YDTHF%R3LES*(PT (JL, KK)-YDCST%RTT)*ZL&
      &)+(1.0_JPRB-FOEALFCU (PT (JL, KK)))*EXP (YDTHF%R3IES*(PT (JL, KK)-YDCST%RTT)*ZI))
      ZQSAT=ZQSAT*ZQP
      ZQSAT=FMINJ (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
      ZF=FOEALFCU (PT (JL, KK))*YDTHF%R5ALVCP*ZL**2+(1.0_JPRB-FOEALFCU (PT (JL, KK)))*YDTHF%R5ALSCP*ZI**2
      ZCOND1=(PQ (JL, KK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)

      IF (ZCOND==0.0_JPRB)  THEN
        ZCOND1=0.0_JPRB
      ENDIF

      PT (JL, KK)=PT (JL, KK)+FOELDCPMCU (PT (JL, KK))*ZCOND1
      PQ (JL, KK)=PQ (JL, KK)-ZCOND1
    ENDIF


    

    IF (KCALL==6) THEN

      

      IF (LDFLAG (JL).AND.LDOFLAG (JL)) THEN
        ZQP=1.0_JPRB/PSP (JL)
        ZL=1.0_JPRB/(PT (JL, KK)-YDTHF%R4LES)
        ZQSAT=YDTHF%R2ES*EXP (YDTHF%R3LES*(PT (JL, KK)-YDCST%RTT)*ZL)
        ZQSAT=ZQSAT*ZQP
        ZQSAT=MIN (0.5_JPRB, ZQSAT)
        ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
        ZF=YDTHF%R5ALVCP*ZL**2
        ZCOND=(PQ (JL, KK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)
        ZCOND=MAX (ZCOND, 0.0_JPRB)
        PT (JL, KK)=PT (JL, KK)+YDTHF%RALVDCP*ZCOND
        PQ (JL, KK)=PQ (JL, KK)-ZCOND
        ZL=1.0_JPRB/(PT (JL, KK)-YDTHF%R4LES)
        ZQSAT=YDTHF%R2ES*EXP (YDTHF%R3LES*(PT (JL, KK)-YDCST%RTT)*ZL)
        ZQSAT=ZQSAT*ZQP
        ZQSAT=FMINJ (0.5_JPRB, ZQSAT)
        ZCOR=1.0_JPRB-YDCST%RETV*ZQSAT
        ZF=YDTHF%R5ALVCP*ZL**2
        ZCOND1=(PQ (JL, KK)*ZCOR**2-ZQSAT*ZCOR)/(ZCOR**2+ZQSAT*ZF)

        IF (ZCOND==0.0_JPRB)  THEN
          ZCOND1=0.0_JPRB
        ENDIF

        PT (JL, KK)=PT (JL, KK)+YDTHF%RALVDCP*ZCOND1
        PQ (JL, KK)=PQ (JL, KK)-ZCOND1
      ENDIF

    
    ENDIF

  ENDIF


  IF (KCALL==2) THEN

    

    IF (LDFLAG (JL)) THEN
      ZQP=1.0_JPRB/PSP (JL)
      ZQSAT=FOEEWMCU (PT (JL, KK))*ZQP
      ZQSAT=MIN (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      ZCOND=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (PT (JL, KK)))
      ZCOND=MIN (ZCOND, 0.0_JPRB)
      PT (JL, KK)=PT (JL, KK)+FOELDCPMCU (PT (JL, KK))*ZCOND
      PQ (JL, KK)=PQ (JL, KK)-ZCOND
      ZQSAT=FOEEWMCU (PT (JL, KK))*ZQP
      ZQSAT=MIN (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (PT (JL, KK)))

      IF (ZCOND==0.0_JPRB)  THEN
        ZCOND1=MIN (ZCOND1, 0.0_JPRB)
      ENDIF

      PT (JL, KK)=PT (JL, KK)+FOELDCPMCU (PT (JL, KK))*ZCOND1
      PQ (JL, KK)=PQ (JL, KK)-ZCOND1
    ENDIF

  
  ENDIF


  IF (KCALL==0) THEN
    
    ZQP=1.0_JPRB/PSP (JL)
    ZQSAT=FOEEWM (PT (JL, KK))*ZQP
    ZQSAT=MIN (0.5_JPRB, ZQSAT)
    ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
    ZQSAT=ZQSAT*ZCOR
    ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEM (PT (JL, KK)))
    PT (JL, KK)=PT (JL, KK)+FOELDCPM (PT (JL, KK))*ZCOND1
    PQ (JL, KK)=PQ (JL, KK)-ZCOND1
    ZQSAT=FOEEWM (PT (JL, KK))*ZQP
    ZQSAT=MIN (0.5_JPRB, ZQSAT)
    ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
    ZQSAT=ZQSAT*ZCOR
    ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEM (PT (JL, KK)))
    PT (JL, KK)=PT (JL, KK)+FOELDCPM (PT (JL, KK))*ZCOND1
    PQ (JL, KK)=PQ (JL, KK)-ZCOND1
  
  ENDIF


  IF (KCALL==4) THEN

    

    IF (LDFLAG (JL)) THEN
      ZQP=1.0_JPRB/PSP (JL)
      ZQSAT=FOEEWM (PT (JL, KK))*ZQP
      ZQSAT=MIN (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      ZCOND=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEM (PT (JL, KK)))
      PT (JL, KK)=PT (JL, KK)+FOELDCPM (PT (JL, KK))*ZCOND
      PQ (JL, KK)=PQ (JL, KK)-ZCOND
      ZQSAT=FOEEWM (PT (JL, KK))*ZQP
      ZQSAT=MIN (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEM (PT (JL, KK)))
      PT (JL, KK)=PT (JL, KK)+FOELDCPM (PT (JL, KK))*ZCOND1
      PQ (JL, KK)=PQ (JL, KK)-ZCOND1
    ENDIF

  
  ENDIF


  IF (KCALL==5) THEN
    
    ZQP=1.0_JPRB/PSP (JL)
    ZQSAT=FOEEWM (PT (JL, KK))*ZQP
    ZQSAT=MIN (0.5_JPRB, ZQSAT)
    ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
    ZQSAT=ZQSAT*ZCOR
    ZCOND=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEM (PT (JL, KK)))
    PT (JL, KK)=PT (JL, KK)+FOELDCPM (PT (JL, KK))*ZCOND
    PQ (JL, KK)=PQ (JL, KK)-ZCOND
    ZQSAT=FOEEWM (PT (JL, KK))*ZQP
    ZQSAT=MIN (0.5_JPRB, ZQSAT)
    ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
    ZQSAT=ZQSAT*ZCOR
    ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEM (PT (JL, KK)))
    PT (JL, KK)=PT (JL, KK)+FOELDCPM (PT (JL, KK))*ZCOND1
    PQ (JL, KK)=PQ (JL, KK)-ZCOND1
  
  ENDIF


  IF (KCALL==3) THEN
    
    ZQP=1.0_JPRB/PSP (JL)
    ZQSAT=FOEEWMCU (PT (JL, KK))*ZQP
    ZQSAT=MIN (0.5_JPRB, ZQSAT)
    ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
    ZQSAT=ZQSAT*ZCOR
    ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (PT (JL, KK)))
    PT (JL, KK)=PT (JL, KK)+FOELDCPMCU (PT (JL, KK))*ZCOND1
    PQ (JL, KK)=PQ (JL, KK)-ZCOND1
    ZQSAT=FOEEWMCU (PT (JL, KK))*ZQP
    ZQSAT=MIN (0.5_JPRB, ZQSAT)
    ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
    ZQSAT=ZQSAT*ZCOR
    ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (PT (JL, KK)))
    PT (JL, KK)=PT (JL, KK)+FOELDCPMCU (PT (JL, KK))*ZCOND1
    PQ (JL, KK)=PQ (JL, KK)-ZCOND1
  
  ENDIF

ELSE

  IF (KCALL==1) THEN

    

    IF (LDFLAG (JL)) THEN
      ZQP=1.0_JPRB/PSP (JL)
      ZTARG=PT (JL, KK)
      ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
      ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
      ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
      ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
      Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
      ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
      &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
      ZCOND=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
      ZCOND=MAX (ZCOND, 0.0_JPRB)

      IF (ZCOND/=0.0_JPRB) THEN
        PT (JL, KK)=PT (JL, KK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND
        PQ (JL, KK)=PQ (JL, KK)-ZCOND
        ZTARG=PT (JL, KK)
        ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
        ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
        ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
        ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
        Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
        ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
        ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
        ZQSAT=ZQSAT*ZCOR
        Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
        &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
        ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
        PT (JL, KK)=PT (JL, KK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND1
        PQ (JL, KK)=PQ (JL, KK)-ZCOND1
      ENDIF

    ENDIF

  
  ENDIF


  IF (KCALL==2) THEN

    

    IF (LDFLAG (JL)) THEN
      ZQP=1.0_JPRB/PSP (JL)
      ZTARG=PT (JL, KK)
      ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
      ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
      ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
      ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
      Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
      ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
      &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
      ZCOND=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
      ZCOND=MIN (ZCOND, 0.0_JPRB)

      IF (ZCOND/=0.0_JPRB) THEN
        PT (JL, KK)=PT (JL, KK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND
        PQ (JL, KK)=PQ (JL, KK)-ZCOND
        ZTARG=PT (JL, KK)
        ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
        ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
        ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
        ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
        Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
        ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
        ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
        ZQSAT=ZQSAT*ZCOR
        Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
        &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
        ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
        PT (JL, KK)=PT (JL, KK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND1
        PQ (JL, KK)=PQ (JL, KK)-ZCOND1
      ENDIF

    ENDIF

  
  ENDIF


  IF (KCALL==0) THEN
    
    ZQP=1.0_JPRB/PSP (JL)
    ZTARG=PT (JL, KK)
    ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
    ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
    ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
    ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
    Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
    ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
    ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
    ZQSAT=ZQSAT*ZCOR
    Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
    &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
    ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
    PT (JL, KK)=PT (JL, KK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND1
    PQ (JL, KK)=PQ (JL, KK)-ZCOND1
    ZTARG=PT (JL, KK)
    ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
    ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
    ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
    ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
    Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
    ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
    ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
    ZQSAT=ZQSAT*ZCOR
    Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
    &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
    ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
    PT (JL, KK)=PT (JL, KK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND1
    PQ (JL, KK)=PQ (JL, KK)-ZCOND1
  
  ENDIF


  IF (KCALL==4) THEN

    

    IF (LDFLAG (JL)) THEN
      ZQP=1.0_JPRB/PSP (JL)
      ZTARG=PT (JL, KK)
      ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
      ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
      ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
      ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
      Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
      ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
      &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
      ZCOND=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
      PT (JL, KK)=PT (JL, KK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND
      PQ (JL, KK)=PQ (JL, KK)-ZCOND
      ZTARG=PT (JL, KK)
      ZOEALFA=0.5_JPRB*(TANH (YDEPHLI%RLPAL1*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB)
      ZFOEEWL=YDTHF%R2ES*EXP (YDTHF%R3LES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4LES))
      ZFOEEWI=YDTHF%R2ES*EXP (YDTHF%R3IES*(ZTARG-YDCST%RTT)/(ZTARG-YDTHF%R4IES))
      ZQSAT=ZQP*(ZOEALFA*ZFOEEWL+(1.0_JPRB-ZOEALFA)*ZFOEEWI)
      Z1S=TANH (YDEPHLI%RLPAL2*(ZQSAT-ZQMAX))
      ZQSAT=0.5_JPRB*((1.0_JPRB-Z1S)*ZQSAT+(1.0_JPRB+Z1S)*ZQMAX)
      ZQSAT=MIN (ZQMAX, ZQSAT)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      Z2S=ZOEALFA*YDTHF%R5ALVCP*(1.0_JPRB/(ZTARG-YDTHF%R4LES)**2)+(1.0_JPRB&
      &-ZOEALFA)*YDTHF%R5ALSCP*(1.0_JPRB/(ZTARG-YDTHF%R4IES)**2)
      ZCOND1=(PQ (JL, KK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*Z2S)
      PT (JL, KK)=PT (JL, KK)+(ZOEALFA*YDTHF%RALVDCP+(1.0_JPRB-ZOEALFA)*YDTHF%RALSDCP)*ZCOND1
      PQ (JL, KK)=PQ (JL, KK)-ZCOND1
    ENDIF

  
  ENDIF

ENDIF


END SUBROUTINE CUADJTQ_OPENACC
