SUBROUTINE CUDTDQN_OPENACC (YDTHF, YDCST, YDEPHLI, YDPHNC, YDECUMF, YDEPHY, KIDIA, KFDIA, KLON, KLEV&
&, KTOPM2, KTYPE, KCTOP, KCBOT, KDTOP, LDTDKMF, LDCUM, LDDRAF, LSCVFLAG, PTSPHY, PAPH, PAP, PGEOH&
&, PGEO, PTEN, PTENH, PQEN, PQENH, PQSEN, PLGLAC, PLUDE, PLUDELI, PSNDE, PMFU, PMFD, PMFUS, PMFDS&
&, PMFUQ, PMFDQ, PMFUL, PDMFUP, PDPMEL, PMFLXR, PMFLXS, PTENT, PTENQ, PENTH, YDSTACK)
!$ACC ROUTINE (CUDTDQN_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE YOEPHY,ONLY:TEPHY
USE YOEPHLI,ONLY:TEPHLI
USE YOPHNC,ONLY:TPHNC
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
TYPE (TEPHY), INTENT (IN)::YDEPHY
TYPE (TPHNC), INTENT (IN)::YDPHNC
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTOPM2
INTEGER (KIND=JPIM), INTENT (IN)::KTYPE (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KDTOP (KLON)
LOGICAL, INTENT (INOUT)::LDCUM (KLON)
LOGICAL, INTENT (IN)::LDDRAF (KLON)
LOGICAL, INTENT (IN)::LDTDKMF
LOGICAL, INTENT (IN)::LSCVFLAG (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PLGLAC (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLUDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLUDELI (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (INOUT)::PSNDE (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (IN)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFDS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFDQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDMFUP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDPMEL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFLXR (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PMFLXS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (INOUT)::PTENT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PENTH (KLON, KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
LOGICAL::LLTEST
INTEGER (KIND=JPIM)::JL
INTEGER (KIND=JPIM)::IM
INTEGER (KIND=JPIM)::IK
INTEGER (KIND=JPIM)::JK
REAL (KIND=JPRB)::ZQ
REAL (KIND=JPRB)::ZS
REAL (KIND=JPRB)::ZGH
REAL (KIND=JPRB)::ZGS
REAL (KIND=JPRB)::ZGQ
REAL (KIND=JPRB)::ZZP
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZORCPD
REAL (KIND=JPRB)::ZIMP
REAL (KIND=JPRB)::ZTSPHY
REAL (KIND=JPRB)::ZINT2 
REAL (KIND=JPRB)::ZINT 
fxtran_acdc_temp (REAL (KIND=JPRB), ZALV2, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZALV, (KLON, KLEV))
REAL (KIND=JPRB)::ZADVW 
fxtran_acdc_temp (REAL (KIND=JPRB), ZMFDQ, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZMFDS, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZMFUQ, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZMFUS, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZDP, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZDQDT, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZDTDT, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZR2, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZR1, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZB, (KLON, KLEV))
fxtran_acdc_temp (LOGICAL, LLCUMBAS, (KLON, KLEV))

#include "cubidiag.intfb.h"
#include "fcttre.func.h"

YLSTACK = YDSTACK



IF (KIND (ZALV2) == 8) THEN
    fxtran_acdc_alloc8 (ZALV2)
ELSEIF (KIND (ZALV2) == 4) THEN
    fxtran_acdc_alloc4 (ZALV2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZALV) == 8) THEN
    fxtran_acdc_alloc8 (ZALV)
ELSEIF (KIND (ZALV) == 4) THEN
    fxtran_acdc_alloc4 (ZALV)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFDQ) == 8) THEN
    fxtran_acdc_alloc8 (ZMFDQ)
ELSEIF (KIND (ZMFDQ) == 4) THEN
    fxtran_acdc_alloc4 (ZMFDQ)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFDS) == 8) THEN
    fxtran_acdc_alloc8 (ZMFDS)
ELSEIF (KIND (ZMFDS) == 4) THEN
    fxtran_acdc_alloc4 (ZMFDS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUQ) == 8) THEN
    fxtran_acdc_alloc8 (ZMFUQ)
ELSEIF (KIND (ZMFUQ) == 4) THEN
    fxtran_acdc_alloc4 (ZMFUQ)
ELSE
    STOP 1
ENDIF


IF (KIND (ZMFUS) == 8) THEN
    fxtran_acdc_alloc8 (ZMFUS)
ELSEIF (KIND (ZMFUS) == 4) THEN
    fxtran_acdc_alloc4 (ZMFUS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDP) == 8) THEN
    fxtran_acdc_alloc8 (ZDP)
ELSEIF (KIND (ZDP) == 4) THEN
    fxtran_acdc_alloc4 (ZDP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDQDT) == 8) THEN
    fxtran_acdc_alloc8 (ZDQDT)
ELSEIF (KIND (ZDQDT) == 4) THEN
    fxtran_acdc_alloc4 (ZDQDT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDTDT) == 8) THEN
    fxtran_acdc_alloc8 (ZDTDT)
ELSEIF (KIND (ZDTDT) == 4) THEN
    fxtran_acdc_alloc4 (ZDTDT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZR2) == 8) THEN
    fxtran_acdc_alloc8 (ZR2)
ELSEIF (KIND (ZR2) == 4) THEN
    fxtran_acdc_alloc4 (ZR2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZR1) == 8) THEN
    fxtran_acdc_alloc8 (ZR1)
ELSEIF (KIND (ZR1) == 4) THEN
    fxtran_acdc_alloc4 (ZR1)
ELSE
    STOP 1
ENDIF


IF (KIND (ZB) == 8) THEN
    fxtran_acdc_alloc8 (ZB)
ELSEIF (KIND (ZB) == 4) THEN
    fxtran_acdc_alloc4 (ZB)
ELSE
    STOP 1
ENDIF


IF (KIND (LLCUMBAS) == 8) THEN
    fxtran_acdc_alloc8 (LLCUMBAS)
ELSEIF (KIND (LLCUMBAS) == 4) THEN
    fxtran_acdc_alloc4 (LLCUMBAS)
ELSE
    STOP 1
ENDIF


JL = KIDIA



ZIMP=1.0_JPRB-YDECUMF%RMFSOLTQ
ZTSPHY=1.0_JPRB/PTSPHY
ZORCPD=1.0_JPRB/YDCST%RCPD

ZADVW =0.0_JPRB

IF (KTYPE (JL)==1)  THEN
  ZADVW =YDECUMF%RMFADVW
ENDIF



DO JK=1, KLEV
  
  PENTH (JL, JK)=0.0_JPRB
  
ENDDO



IF (KTYPE (JL)/=1.AND.YDEPHLI%LPHYLIN)  THEN
  LDCUM (JL)=.FALSE.
ENDIF


LLTEST=(.NOT.YDEPHY%LEPCLD.AND..NOT.YDPHNC%LENCLD2.AND..NOT.YDPHNC%LEPCLD2&
&).OR.(YDEPHLI%LPHYLIN.AND..NOT.YDPHNC%LENCLD2.AND..NOT.YDPHNC%LEPCLD2)

IF (LLTEST) THEN

  DO JK=1, KLEV
    
    PLUDE (JL, JK)=0.0_JPRB
    PLUDELI (JL, JK, 1)=0.0_JPRB
    PLUDELI (JL, JK, 2)=0.0_JPRB
  
  ENDDO

ENDIF


DO JK=1, KLEV

  

  IF (LDCUM (JL)) THEN
    ZDP (JL, JK)=YDCST%RG/(PAPH (JL, JK+1)-PAPH (JL, JK))
    ZMFUS (JL, JK)=PMFUS (JL, JK)
    ZMFDS (JL, JK)=PMFDS (JL, JK)
    ZMFUQ (JL, JK)=PMFUQ (JL, JK)
    ZMFDQ (JL, JK)=PMFDQ (JL, JK)
  ENDIF

  
ENDDO


IF (YDECUMF%RMFSOLTQ>0.0_JPRB) THEN

  DO JK=KTOPM2, KLEV
    IK=JK-1

    

    IF (LDCUM (JL).AND.JK>=KCTOP (JL)-1) THEN
      ZGQ=(PQENH (JL, JK)-PQEN (JL, IK))/PQSEN (JL, JK)
      ZGH=YDCST%RCPD*PTEN (JL, JK)+PGEO (JL, JK)
      ZGS=(YDCST%RCPD*(PTENH (JL, JK)-PTEN (JL, IK))+PGEOH (JL, JK)-PGEO (JL, IK))/ZGH
      ZS=YDCST%RCPD*(ZIMP*PTEN (JL, IK)+ZGS*PTEN (JL, JK))+PGEO (JL, IK)+ZGS*PGEO (JL, JK)
      ZQ=ZIMP*PQEN (JL, IK)+ZGQ*PQSEN (JL, JK)
      ZMFUS (JL, JK)=PMFUS (JL, JK)-PMFU (JL, JK)*ZS
      ZMFUQ (JL, JK)=PMFUQ (JL, JK)-PMFU (JL, JK)*ZQ

      IF (LDDRAF (JL).AND.JK>=KDTOP (JL)) THEN
        ZMFDS (JL, JK)=PMFDS (JL, JK)-PMFD (JL, JK)*ZS
        ZMFDQ (JL, JK)=PMFDQ (JL, JK)-PMFD (JL, JK)*ZQ
      ENDIF

    ENDIF

  
  ENDDO

ENDIF

ZINT=0._JPRB

DO JK=KTOPM2, KLEV
  
  ZALV (JL, JK)=FOELHMCU (PTEN (JL, JK))
  ZALV2 (JL, JK)=ZALV (JL, JK)
  
ENDDO


IF (YDECUMF%LMFENTHCONS) THEN

  DO JK=KTOPM2, KLEV-1

    

    IF (LSCVFLAG (JL))  THEN
      ZALV (JL, JK)=YDCST%RLVTT
    ENDIF

    ZINT =ZINT +YDCST%RLMLT*(PLGLAC (JL, JK)-PDPMEL (JL, JK))-ZALV (JL, JK&
    &)*(PMFUL (JL, JK+1)-PMFUL (JL, JK))+ZALV2 (JL, JK)*PDMFUP (JL, JK)
  
  ENDDO

  JK=KLEV

  

  IF (LSCVFLAG (JL))  THEN
    ZALV (JL, JK)=YDCST%RLVTT
  ENDIF

  ZINT =ZINT +YDCST%RLMLT*(PLGLAC (JL, JK)-PDPMEL (JL, JK))+ZALV&
  & (JL, JK)*PMFUL (JL, JK)+ZALV2 (JL, JK)*PDMFUP (JL, JK)
  ZINT2 =ZINT -YDCST%RLVTT*PMFLXR (JL, KLEV+1)-YDCST%RLSTT*PMFLXS (JL, KLEV+1)

  IF (ABS (ZINT )>0.1_JPRB) THEN
    ZINT =ZINT2 /(ZINT +1.E-3_JPRB)
  ELSE
    ZINT =0.0_JPRB
  ENDIF


  IF (ABS (ZINT )>2.0_JPRB)  THEN
    ZINT =0.0_JPRB
  ENDIF

  
ENDIF


DO JK=KTOPM2, KLEV

  IF (JK<KLEV) THEN

    

    IF (LDCUM (JL)) THEN

      IF (YDEPHLI%LPHYLIN) THEN
        ZTARG=PTEN (JL, JK)
        ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
        ZALV (JL, JK)=ZOEALFA*YDCST%RLVTT+(1.0_JPRB-ZOEALFA)*YDCST%RLSTT
        ZALV2 (JL, JK)=ZALV (JL, JK)
      ENDIF


      IF (LDTDKMF) THEN
        ZDTDT (JL, JK)=ZDP (JL, JK)*ZORCPD*(ZMFUS (JL, JK+1)-ZMFUS (JL, JK)+ZMFDS (JL, JK&
        &+1)-ZMFDS (JL, JK)+YDCST%RLMLT*PLGLAC (JL, JK)-YDCST%RLMLT*PDPMEL (JL, JK)-ZALV&
        & (JL, JK)*(PMFUL (JL, JK+1)-PMFUL (JL, JK)-PLUDE (JL, JK)-PDMFUP (JL, JK)))
        ZDQDT (JL, JK)=ZDP (JL, JK)*(ZMFUQ (JL, JK+1)-ZMFUQ (JL, JK)+ZMFDQ (JL, JK+1)-ZMFDQ&
        & (JL, JK)+PMFUL (JL, JK+1)-PMFUL (JL, JK)-PLUDE (JL, JK)-PDMFUP (JL, JK))
      ELSE
        ZDTDT (JL, JK)=ZDP (JL, JK)*ZORCPD*(ZMFUS (JL, JK+1)-ZMFUS (JL, JK)+ZMFDS (JL, JK+1)-ZMFDS&
        & (JL, JK)+(YDCST%RLMLT*(PLGLAC (JL, JK)-PDPMEL (JL, JK))-ZALV (JL, JK)*(PMFUL (JL, JK+1)&
        &-PMFUL (JL, JK))+ZALV2 (JL, JK)*PDMFUP (JL, JK))*(1.0_JPRB-ZINT )+YDCST%RLVTT*(PLUDELI (JL&
        &, JK, 1)+PSNDE (JL, JK, 1))+YDCST%RLSTT*(PLUDELI (JL, JK, 2)+PSNDE (JL, JK, 2)))
        ZDQDT (JL, JK)=ZDP (JL, JK)*(ZMFUQ (JL, JK+1)-ZMFUQ (JL, JK)+ZMFDQ (JL, JK+1)-ZMFDQ (JL, JK)+PMFUL&
        & (JL, JK+1)-PMFUL (JL, JK)-PLUDE (JL, JK)-PDMFUP (JL, JK)-PSNDE (JL, JK, 1)-PSNDE (JL, JK, 2))
      ENDIF

    ENDIF

  
  ELSE

    

    IF (LDCUM (JL)) THEN

      IF (YDEPHLI%LPHYLIN) THEN
        ZTARG=PTEN (JL, JK)
        ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
        ZALV (JL, JK)=ZOEALFA*YDCST%RLVTT+(1.0_JPRB-ZOEALFA)*YDCST%RLSTT
        ZALV2 (JL, JK)=ZALV (JL, JK)
      ENDIF

      ZDTDT (JL, JK)=-ZDP (JL, JK)*ZORCPD*(ZMFUS (JL, JK)+ZMFDS (JL, JK)+(YDCST%RLMLT*(PDPMEL (JL, JK)-PLGLAC&
      & (JL, JK))-ZALV (JL, JK)*PMFUL (JL, JK)-ZALV2 (JL, JK)*PDMFUP (JL, JK))*(1.0_JPRB-ZINT ))
      ZDQDT (JL, JK)=-ZDP (JL, JK)*(ZMFUQ (JL, JK)+ZMFDQ (JL, JK)+(PMFUL (JL, JK)+PDMFUP (JL, JK)))
    ENDIF

  
  ENDIF

ENDDO


IF (YDECUMF%RMFSOLTQ==0.0_JPRB) THEN

  DO JK=KTOPM2, KLEV

    

    IF (LDCUM (JL)) THEN
      PTENT (JL, JK)=PTENT (JL, JK)+ZDTDT (JL, JK)
      PTENQ (JL, JK)=PTENQ (JL, JK)+ZDQDT (JL, JK)
      PENTH (JL, JK)=ZDTDT (JL, JK)*YDCST%RCPD
    ENDIF

  
  ENDDO

ELSE
  LLCUMBAS (JL,:)=.FALSE.
  ZB (JL,:)=1.0_JPRB
  ZMFUS (JL,:)=0.0_JPRB

  DO JK=KTOPM2, KLEV
    IK=JK+1
    IM=JK-1
    
    LLCUMBAS (JL, JK)=LDCUM (JL).AND.JK>=KCTOP (JL)-1

    IF (LLCUMBAS (JL, JK)) THEN
      ZZP=YDECUMF%RMFSOLTQ*ZDP (JL, JK)*PTSPHY
      ZMFUS (JL, JK)=-ZZP*(PMFU (JL, JK)+PMFD (JL, JK))

      IF (JK<KLEV) THEN
        ZB (JL, JK)=1.0_JPRB+ZZP*(PMFU (JL, IK)+PMFD (JL, IK))
      ELSE
        ZB (JL, JK)=1.0_JPRB
      ENDIF


      IF (LDTDKMF) THEN
        ZDTDT (JL, JK)=ZDTDT (JL, JK)*PTSPHY+PTEN (JL, JK)
        ZDQDT (JL, JK)=ZDQDT (JL, JK)*PTSPHY+PQEN (JL, JK)
      ELSE
        ZZP=YDCST%RG*(PMFU (JL, JK)+YDECUMF%RMFADVWDD*PMFD (JL&
        &, JK))/(PAP (JL, JK)-PAP (JL, IM))*PTSPHY*ZADVW 
        ZS=ZZP*(PTEN (JL, IM)-PTEN (JL, JK)+ZORCPD*(PGEO (JL, IM)-PGEO (JL, JK)))
        ZQ=ZZP*(PQEN (JL, IM)-PQEN (JL, JK))
        ZDTDT (JL, JK)=(ZDTDT (JL, JK)+PTENT (JL, JK)*YDECUMF%RMFSOLRHS)*PTSPHY+PTEN (JL, JK)-ZS
        ZDQDT (JL, JK)=(ZDQDT (JL, JK)+PTENQ (JL, JK)*YDECUMF%RMFSOLRHS)*PTSPHY+PQEN (JL, JK)-ZQ
      ENDIF

    ENDIF

  
  ENDDO

  CALL CUBIDIAG_OPENACC (KIDIA, KFDIA, KLON, KLEV, KCTOP&
  &, LLCUMBAS, ZMFUS, ZB, ZDTDT, ZR1, YDSTACK=YLSTACK)
  CALL CUBIDIAG_OPENACC (KIDIA, KFDIA, KLON, KLEV, KCTOP&
  &, LLCUMBAS, ZMFUS, ZB, ZDQDT, ZR2, YDSTACK=YLSTACK)

  DO JK=KTOPM2, KLEV

    

    IF (LLCUMBAS (JL, JK)) THEN

      IF (LDTDKMF) THEN
        PTENT (JL, JK)=PTENT (JL, JK)+(ZR1 (JL, JK)-PTEN (JL, JK))*ZTSPHY
        PTENQ (JL, JK)=PTENQ (JL, JK)+(ZR2 (JL, JK)-PQEN (JL, JK))*ZTSPHY
      ELSE
        PTENT (JL, JK)=PTENT (JL, JK)*(1.0_JPRB-YDECUMF%RMFSOLRHS)+(ZR1 (JL, JK)-PTEN (JL, JK))*ZTSPHY
        PTENQ (JL, JK)=PTENQ (JL, JK)*(1.0_JPRB-YDECUMF%RMFSOLRHS)+(ZR2 (JL, JK)-PQEN (JL, JK))*ZTSPHY
      ENDIF

      PENTH (JL, JK)=(ZR1 (JL, JK)-PTEN (JL, JK))*ZTSPHY
    ENDIF

  
  ENDDO

ENDIF



END SUBROUTINE CUDTDQN_OPENACC
