
MODULE MODE_COMPUTE_MF_CLOUD_STAT_OPENACC


IMPLICIT NONE


CONTAINS
SUBROUTINE COMPUTE_MF_CLOUD_STAT_OPENACC (D, CST, TURBN, PARAMMF, KRR, KRRL, KRRI, OSTATNW, PFRAC_ICE&
&, PTHLM, PRTM, PPABSM, PRM, PDZZ, PTHM, PEXNM, PEMF, PTHL_UP, PRT_UP, PSIGMF, YDSTACK)
!$ACC ROUTINE (COMPUTE_MF_CLOUD_STAT_OPENACC) SEQ
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_CST,ONLY:CST_T
USE MODD_PARAM_MFSHALL_N,ONLY:PARAM_MFSHALL_T
USE MODD_TURB_N,ONLY:TURB_T
USE MODI_SHUMAN_MF,ONLY:MZF_MF, MZM_MF, GZ_M_W_MF
USE MODI_SHUMAN_MF_OPENACC, ONLY : MZM_MF_OPENACC
USE MODI_SHUMAN_MF_OPENACC, ONLY : MZF_MF_OPENACC
USE MODI_SHUMAN_MF_OPENACC, ONLY : GZ_M_W_MF_OPENACC
USE MODE_COMPUTE_FUNCTION_THERMO_MF,ONLY:COMPUTE_FUNCTION_THERMO_MF
USE MODE_COMPUTE_FUNCTION_THERMO_MF_OPENACC,ONLY:COMPUTE_FUNCTION_THERMO_MF_OPENACC

#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (TURB_T), INTENT (IN)::TURBN
TYPE (PARAM_MFSHALL_T), INTENT (IN)::PARAMMF
LOGICAL, INTENT (IN)::OSTATNW
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KRRL
INTEGER, INTENT (IN)::KRRI
REAL, INTENT (IN)::PFRAC_ICE(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRTM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHLM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PPABSM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRM(D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PDZZ(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PEXNM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PEMF(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRT_UP(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHL_UP(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PSIGMF(D%NIJT, D%NKT)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
fxtran_acdc_temp (REAL, ZFLXZ3, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZFLXZ2, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZFLXZ, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZT, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZATHETA, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZAMOIST, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZWK2, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZWK, (D%NIJT, D%NKT))
INTEGER::JK
INTEGER::JI
INTEGER::IIJE
INTEGER::IIJB
INTEGER::IKT


YLSTACK = YDSTACK



IF (KIND (ZFLXZ3) == 8) THEN
    fxtran_acdc_alloc8 (ZFLXZ3)
ELSEIF (KIND (ZFLXZ3) == 4) THEN
    fxtran_acdc_alloc4 (ZFLXZ3)
ELSE
    STOP 1
ENDIF


IF (KIND (ZFLXZ2) == 8) THEN
    fxtran_acdc_alloc8 (ZFLXZ2)
ELSEIF (KIND (ZFLXZ2) == 4) THEN
    fxtran_acdc_alloc4 (ZFLXZ2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZFLXZ) == 8) THEN
    fxtran_acdc_alloc8 (ZFLXZ)
ELSEIF (KIND (ZFLXZ) == 4) THEN
    fxtran_acdc_alloc4 (ZFLXZ)
ELSE
    STOP 1
ENDIF


IF (KIND (ZT) == 8) THEN
    fxtran_acdc_alloc8 (ZT)
ELSEIF (KIND (ZT) == 4) THEN
    fxtran_acdc_alloc4 (ZT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZATHETA) == 8) THEN
    fxtran_acdc_alloc8 (ZATHETA)
ELSEIF (KIND (ZATHETA) == 4) THEN
    fxtran_acdc_alloc4 (ZATHETA)
ELSE
    STOP 1
ENDIF


IF (KIND (ZAMOIST) == 8) THEN
    fxtran_acdc_alloc8 (ZAMOIST)
ELSEIF (KIND (ZAMOIST) == 4) THEN
    fxtran_acdc_alloc4 (ZAMOIST)
ELSE
    STOP 1
ENDIF


IF (KIND (ZWK2) == 8) THEN
    fxtran_acdc_alloc8 (ZWK2)
ELSEIF (KIND (ZWK2) == 4) THEN
    fxtran_acdc_alloc4 (ZWK2)
ELSE
    STOP 1
ENDIF


IF (KIND (ZWK) == 8) THEN
    fxtran_acdc_alloc8 (ZWK)
ELSEIF (KIND (ZWK) == 4) THEN
    fxtran_acdc_alloc4 (ZWK)
ELSE
    STOP 1
ENDIF


JI = D%NIB


IIJE=D%NIJE
IIJB=D%NIJB
IKT=D%NKT
CALL COMPUTE_FUNCTION_THERMO_MF_OPENACC (D, CST, KRR, KRRL, KRRI, OSTATNW, PTHM&
&, PRM, PEXNM, PFRAC_ICE, PPABSM, ZT, ZAMOIST, ZATHETA, YDSTACK=YLSTACK)

IF (KRRL>0) THEN
  CALL MZM_MF_OPENACC (D, PTHLM (:,:), ZFLXZ (:,:), YDSTACK=YLSTACK)
  CALL GZ_M_W_MF_OPENACC (D, PTHLM (:,:), PDZZ (:,:), ZWK (:,:), YDSTACK=YLSTACK)

  IF (OSTATNW) THEN

    DO JK=1, IKT
      
      ZFLXZ (JI, JK)=-2*TURBN%XCTV*PARAMMF%XTAUSIGMF*PEMF (JI&
      &, JK)*(PTHL_UP (JI, JK)-ZFLXZ (JI, JK))*ZWK (JI, JK)
    
    ENDDO

  ELSE

    DO JK=1, IKT
      
      ZFLXZ (JI, JK)=-2*PARAMMF%XTAUSIGMF*PEMF (JI, JK)*(PTHL_UP (JI, JK)-ZFLXZ (JI, JK))*ZWK (JI, JK)
    
    ENDDO

  ENDIF


  DO JK=1, IKT
    
    ZFLXZ (JI, JK)=MAX (0., ZFLXZ (JI, JK))
  
  ENDDO

  CALL MZF_MF_OPENACC (D, ZFLXZ (:,:), PSIGMF (:,:), YDSTACK=YLSTACK)

  DO JK=1, IKT
    
    PSIGMF (JI, JK)=PSIGMF (JI, JK)*ZATHETA (JI, JK)**2
  
  ENDDO

  CALL MZM_MF_OPENACC (D, PRTM (:,:), ZFLXZ2 (:,:), YDSTACK=YLSTACK)
  CALL GZ_M_W_MF_OPENACC (D, PRTM (:,:), PDZZ (:,:), ZWK2 (:,:), YDSTACK=YLSTACK)

  IF (OSTATNW) THEN

    DO JK=1, IKT
      
      ZFLXZ2 (JI, JK)=-2*TURBN%XCTV*PARAMMF%XTAUSIGMF*PEMF (JI&
      &, JK)*(PRT_UP (JI, JK)-ZFLXZ2 (JI, JK))*ZWK2 (JI, JK)
    
    ENDDO

  ELSE

    DO JK=1, IKT
      
      ZFLXZ2 (JI, JK)=-2*PARAMMF%XTAUSIGMF*PEMF (JI, JK)*(PRT_UP (JI, JK)-ZFLXZ2 (JI, JK))*ZWK2 (JI, JK)
    
    ENDDO

  ENDIF


  DO JK=1, IKT
    
    ZFLXZ2 (JI, JK)=MAX (0., ZFLXZ2 (JI, JK))
  
  ENDDO

  CALL MZF_MF_OPENACC (D, ZFLXZ2 (:,:), ZWK2 (:,:), YDSTACK=YLSTACK)

  DO JK=1, IKT
    
    PSIGMF (JI, JK)=PSIGMF (JI, JK)+ZAMOIST (JI, JK)**2*ZWK2 (JI, JK)
  
  ENDDO


  IF (OSTATNW) THEN

    DO JK=1, IKT
      
      ZFLXZ3 (JI, JK)=-TURBN%XCTV*PARAMMF%XTAUSIGMF*(PEMF (JI, JK)*(PRT_UP (JI, JK)-ZFLXZ2 (JI&
      &, JK))*ZWK (JI, JK)+PEMF (JI, JK)*(PTHL_UP (JI, JK)-ZFLXZ (JI, JK))*ZWK2 (JI, JK))
    
    ENDDO

    CALL MZF_MF_OPENACC (D, ZFLXZ3, ZFLXZ, YDSTACK=YLSTACK)

    DO JK=1, IKT
      
      PSIGMF (JI, JK)=PSIGMF (JI, JK)-MIN (0., 2.*ZAMOIST (JI, JK)*ZATHETA (JI, JK)*ZFLXZ (JI, JK))
    
    ENDDO

  ENDIF


  DO JK=1, IKT
    
    PSIGMF (JI, JK)=SQRT (MAX (PSIGMF (JI, JK), 0.))
  
  ENDDO

ELSE
  PSIGMF (JI,:)=0.
ENDIF


END SUBROUTINE COMPUTE_MF_CLOUD_STAT_OPENACC

ENDMODULE MODE_COMPUTE_MF_CLOUD_STAT_OPENACC
