
MODULE MODE_COMPUTE_UPDRAFT_RAHA_OPENACC


IMPLICIT NONE


CONTAINS
SUBROUTINE COMPUTE_UPDRAFT_RAHA_OPENACC (D, CST, NEBN, PARAMMF, KSV, OENTR_DETR, ONOMIXLG, KSV_LGBEG&
&, KSV_LGEND, PZZ, PDZZ, PSFTH, PSFRV, PPABSM, PRHODREF, PUM, PVM, PTKEM, PEXNM, PTHM, PRVM, PTHLM, PRTM&
&, PSVM, PTHL_UP, PRT_UP, PRV_UP, PRC_UP, PRI_UP, PTHV_UP, PW_UP, PU_UP, PV_UP, PSV_UP, PFRAC_UP, PFRAC_ICE_UP&
&, PRSAT_UP, PEMF, PDETR, PENTR, PBUO_INTEG, KKLCL, KKETL, KKCTL, PDEPTH, YDSTACK)
!$ACC ROUTINE (COMPUTE_UPDRAFT_RAHA_OPENACC) SEQ
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_CST,ONLY:CST_T
USE MODD_NEB_N,ONLY:NEB_T
USE MODD_PARAM_MFSHALL_N,ONLY:PARAM_MFSHALL_T
USE MODI_SHUMAN_MF_OPENACC,ONLY:MZM_MF_OPENACC

#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
TYPE (NEB_T), INTENT (IN)::NEBN
TYPE (PARAM_MFSHALL_T), INTENT (IN)::PARAMMF
INTEGER, INTENT (IN)::KSV
LOGICAL, INTENT (IN)::OENTR_DETR
LOGICAL, INTENT (IN)::ONOMIXLG
INTEGER, INTENT (IN)::KSV_LGBEG
INTEGER, INTENT (IN)::KSV_LGEND
REAL, INTENT (IN)::PZZ(D%NIJT, D%NKT)
REAL, INTENT (IN)::PDZZ(D%NIJT, D%NKT)
REAL, INTENT (IN)::PSFRV(D%NIJT)
REAL, INTENT (IN)::PSFTH(D%NIJT)
REAL, INTENT (IN)::PPABSM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRHODREF(D%NIJT, D%NKT)
REAL, INTENT (IN)::PUM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PVM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTKEM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PEXNM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRVM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PRTM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PTHLM(D%NIJT, D%NKT)
REAL, INTENT (IN)::PSVM(D%NIJT, D%NKT, KSV)
REAL, INTENT (OUT)::PRT_UP(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PTHL_UP(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PV_UP(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PU_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRC_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRV_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PTHV_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRI_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PFRAC_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PW_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PFRAC_ICE_UP(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PRSAT_UP(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PSV_UP(D%NIJT, D%NKT, KSV)
REAL, INTENT (INOUT)::PENTR(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PDETR(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PEMF(D%NIJT, D%NKT)
REAL, INTENT (INOUT)::PBUO_INTEG(D%NIJT, D%NKT)
INTEGER, INTENT (INOUT)::KKCTL(D%NIJT)
INTEGER, INTENT (INOUT)::KKETL(D%NIJT)
INTEGER, INTENT (INOUT)::KKLCL(D%NIJT)
REAL, INTENT (OUT)::PDEPTH(D%NIJT)
TYPE(STACK), INTENT (IN) :: YDSTACK
TYPE(STACK) :: YLSTACK
REAL::ZRVM_F(D%NIJT, D%NKT)
REAL::ZTHM_F(D%NIJT, D%NKT)
REAL::ZTKEM_F(D%NIJT, D%NKT)
REAL::ZTHLM_F(D%NIJT, D%NKT)
REAL::ZRTM_F(D%NIJT, D%NKT)
REAL::ZRHO_F(D%NIJT, D%NKT)
REAL::ZVM_F(D%NIJT, D%NKT)
REAL::ZUM_F(D%NIJT, D%NKT)
REAL::ZTHVM(D%NIJT, D%NKT)
REAL::ZTHVM_F(D%NIJT, D%NKT)
REAL::ZPRES_F(D%NIJT, D%NKT)
REAL::ZG_O_THVREF(D%NIJT, D%NKT)
REAL::ZW_UP2(D%NIJT, D%NKT)
REAL::ZTH_UP(D%NIJT, D%NKT)
REAL::ZT_UP(D%NIJT)
REAL::ZLVOCPEXN(D%NIJT)
REAL::ZCP(D%NIJT)
REAL::ZBUO(D%NIJT, D%NKT)
REAL::ZTHSM(D%NIJT, D%NKT)
REAL::ZTHS_UP(D%NIJT, D%NKT)
REAL::ZCOEF(D%NIJT, D%NKT)
REAL::ZRDORV
REAL::ZRVORD
REAL::ZMIX3(D%NIJT)
REAL::ZMIX2(D%NIJT)
REAL::ZMIX1(D%NIJT)
INTEGER::JIJ
INTEGER::JK
INTEGER::IIJE
INTEGER::IIJB
INTEGER::IKL
INTEGER::IKE
INTEGER::IKB
INTEGER::IKT
LOGICAL::GTESTETL(D%NIJT)
LOGICAL::GTESTLCL(D%NIJT)
LOGICAL::GTEST(D%NIJT)
LOGICAL::GWORK1(D%NIJT)
LOGICAL::GWORK2(D%NIJT, D%NKT)
REAL::ZRSATI(D%NIJT)
REAL::ZRSATW(D%NIJT)
REAL::ZRV_UP(D%NIJT)
REAL::ZRI_UP(D%NIJT)
REAL::ZRC_UP(D%NIJT)
REAL::ZALIM_STAR_TOT(D%NIJT)
REAL::ZPHI(D%NIJT)
REAL::ZZZ(D%NIJT, D%NKT)
REAL::ZZDZ(D%NIJT, D%NKT)
REAL::ZALIM_STAR(D%NIJT, D%NKT)
REAL::ZDTHETASDZ(D%NIJT, D%NKT)
INTEGER::IALIM(D%NIJT)
REAL::ZWUP_MEAN(D%NIJT)
REAL::ZDZ(D%NIJT)
REAL::ZTEST(D%NIJT)
REAL::ZBUCOE(D%NIJT)
REAL::ZWCOE(D%NIJT)
REAL::ZCOE(D%NIJT)
REAL::ZDETR_RT(D%NIJT)
REAL::ZDETR_BUO(D%NIJT)
REAL::ZW_MAX(D%NIJT)
REAL::ZZTOP(D%NIJT)
REAL::ZQT_UP(D%NIJT)
REAL::ZQTM(D%NIJT)
REAL::ZDEPTH_MAX2
REAL::ZDEPTH_MAX1
REAL::ZEPS
REAL::ZRMAX
REAL::ZTMAX
REAL::ZBUF(D%NIJT, 16)

INTEGER (KIND=JPIM) :: JLON

YLSTACK = YDSTACK



JLON = KIDIA


IIJE=D%NIJE
IIJB=D%NIJB
IKT=D%NKT
IKB=D%NKB
IKE=D%NKE
IKL=D%NKL
ZTMAX=2.0
ZRMAX=1.E-3
ZEPS=1.E-15
ZRDORV=CST%XRD/CST%XRV
ZRVORD=(CST%XRV/CST%XRD)
ZDEPTH_MAX1=4500.
ZDEPTH_MAX2=5000.
KKLCL (:)=IKE
KKETL (:)=IKE
KKCTL (:)=IKE
PEMF (:,:)=0.
PDETR (:,:)=0.
PENTR (:,:)=0.
PRV_UP (:,:)=0.
PRC_UP (:,:)=0.
PW_UP (:,:)=0.
ZTH_UP (:,:)=0.
PFRAC_UP (:,:)=0.
PTHV_UP (:,:)=0.
PBUO_INTEG (:,:)=0.
ZBUO (:,:)=0.
PRI_UP (:,:)=0.
PFRAC_ICE_UP (:,:)=0.

DO JK=1, IKT

  DO JIJ=IIJB, IIJE
    PRSAT_UP (JIJ, JK)=PRVM (JIJ, JK)
  ENDDO

ENDDO

CALL MZM_MF_OPENACC (D, PTHLM (:,:), ZTHLM_F (:,:), YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, PRTM (:,:), ZRTM_F (:,:), YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, PUM (:,:), ZUM_F (:,:), YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, PVM (:,:), ZVM_F (:,:), YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, PTKEM (:,:), ZTKEM_F (:,:), YDSTACK=YLSTACK)

DO JK=1, IKT

  DO JIJ=IIJB, IIJE
    PTHL_UP (JIJ, JK)=ZTHLM_F (JIJ, JK)
    PRT_UP (JIJ, JK)=ZRTM_F (JIJ, JK)
    PU_UP (JIJ, JK)=ZUM_F (JIJ, JK)
    PV_UP (JIJ, JK)=ZVM_F (JIJ, JK)
  ENDDO

ENDDO

PSV_UP (:,:,:)=0.

DO JIJ=IIJB, IIJE
  PTHL_UP (JIJ, IKB)=ZTHLM_F (JIJ, IKB)+MAX (0., MIN (ZTMAX,(PSFTH&
  & (JIJ)/SQRT (ZTKEM_F (JIJ, IKB)))*PARAMMF%XALP_PERT))
  PRT_UP (JIJ, IKB)=ZRTM_F (JIJ, IKB)+MAX (0., MIN (ZRMAX,(PSFRV&
  & (JIJ)/SQRT (ZTKEM_F (JIJ, IKB)))*PARAMMF%XALP_PERT))
  ZQT_UP (JIJ)=PRT_UP (JIJ, IKB)/(1.+PRT_UP (JIJ, IKB))
  ZTHS_UP (JIJ, IKB)=PTHL_UP (JIJ, IKB)*(1.+PARAMMF%XLAMBDA_MF*ZQT_UP (JIJ))
ENDDO

CALL MZM_MF_OPENACC (D, PTHM (:,:), ZTHM_F (:,:), YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, PPABSM (:,:), ZPRES_F (:,:), YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, PRHODREF (:,:), ZRHO_F (:,:), YDSTACK=YLSTACK)
CALL MZM_MF_OPENACC (D, PRVM (:,:), ZRVM_F (:,:), YDSTACK=YLSTACK)

DO JK=1, IKT

  DO JIJ=IIJB, IIJE
    ZTHVM_F (JIJ, JK)=ZTHM_F (JIJ, JK)*((1.+ZRVORD*ZRVM_F (JIJ, JK))/(1.+ZRTM_F (JIJ, JK)))
    ZTHVM (JIJ, JK)=PTHM (JIJ, JK)*((1.+ZRVORD*PRVM (JIJ, JK))/(1.+PRTM (JIJ, JK)))
    PTHV_UP (JIJ, JK)=ZTHVM_F (JIJ, JK)
    PRV_UP (JIJ, JK)=ZRVM_F (JIJ, JK)
  ENDDO

ENDDO

ZW_UP2 (:,:)=ZEPS

DO JIJ=IIJB, IIJE
  ZW_UP2 (JIJ, IKB)=MAX (0.0001,(1./6.)*ZTKEM_F (JIJ, IKB))
  GTEST (JIJ)=(ZW_UP2 (JIJ, IKB)>ZEPS)
ENDDO


DO JIJ=IIJB, IIJE
  PRC_UP (JIJ, IKB)=0.
  PRI_UP (JIJ, IKB)=0.
ENDDO

CALL TH_R_FROM_THL_RT_OPENACC (CST, NEBN, D%NIJT, NEBN%CFRAC_ICE_SHALLOW_MF, PFRAC_ICE_UP&
& (:, IKB), ZPRES_F (:, IKB), PTHL_UP (:, IKB), PRT_UP (:, IKB), ZTH_UP (:, IKB&
&), PRV_UP (:, IKB), PRC_UP (:, IKB), PRI_UP (:, IKB), ZRSATW (:), ZRSATI (:), OOCEAN&
&=.FALSE., PBUF=ZBUF, KB=D%NIJB, KE=D%NIJE, YDSTACK=YLSTACK)

DO JIJ=IIJB, IIJE
  PTHV_UP (JIJ, IKB)=ZTH_UP (JIJ, IKB)*((1+ZRVORD*PRV_UP (JIJ, IKB))/(1+PRT_UP (JIJ, IKB)))
  PRSAT_UP (JIJ, IKB)=ZRSATW (JIJ)*(1-PFRAC_ICE_UP (JIJ, IKB))+ZRSATI (JIJ)*PFRAC_ICE_UP (JIJ, IKB)
ENDDO


DO JK=1, IKT

  DO JIJ=IIJB, IIJE
    ZG_O_THVREF (JIJ, JK)=CST%XG/ZTHVM_F (JIJ, JK)
  ENDDO

ENDDO

ZALIM_STAR (:,:)=0.
ZALIM_STAR_TOT (:)=0.
IALIM (:)=IKB

DO JK=IKB, IKE-IKL, IKL

  DO JIJ=IIJB, IIJE
    ZZDZ (JIJ, JK)=MAX (ZEPS, PZZ (JIJ, JK+IKL)-PZZ (JIJ, JK))
    ZZZ (JIJ, JK)=MAX (0., 0.5*(PZZ (JIJ, JK+IKL)+PZZ (JIJ, JK)))
    ZDTHETASDZ (JIJ, JK)=(ZTHVM_F (JIJ, JK)-ZTHVM_F (JIJ, JK+IKL))

    IF ((ZTHVM_F (JIJ, JK+IKL)<ZTHVM_F (JIJ, JK)).AND.(ZTHVM_F (JIJ, IKB)>=ZTHVM_F (JIJ, JK))) THEN
      ZALIM_STAR (JIJ, JK)=SQRT (ZZZ (JIJ, JK))*ZDTHETASDZ (JIJ, JK)/ZZDZ (JIJ, JK)
      ZALIM_STAR_TOT (JIJ)=ZALIM_STAR_TOT (JIJ)+ZALIM_STAR (JIJ, JK)*ZZDZ (JIJ, JK)
      IALIM (JIJ)=JK
    ENDIF

  ENDDO

ENDDO


DO JK=IKB, IKE-IKL, IKL

  DO JIJ=IIJB, IIJE

    IF (ZALIM_STAR_TOT (JIJ)>ZEPS) THEN
      ZALIM_STAR (JIJ, JK)=ZALIM_STAR (JIJ, JK)/ZALIM_STAR_TOT (JIJ)
    ENDIF

  ENDDO

ENDDO

ZALIM_STAR_TOT (:)=0.
GTESTLCL (:)=.FALSE.
GTESTETL (:)=.FALSE.
ZW_MAX (:)=0.
ZZTOP (:)=0.
ZPHI (:)=0.

DO JK=IKB, IKE-IKL, IKL

  DO JIJ=IIJB, IIJE

    IF ((PRC_UP (JIJ, JK)+PRI_UP (JIJ, JK)>0.).AND.(.NOT.(GTESTLCL (JIJ)))) THEN
      KKLCL (JIJ)=JK
      GTESTLCL (JIJ)=.TRUE.
    ENDIF

    ZRC_UP (JIJ)=PRC_UP (JIJ, JK)
    ZRI_UP (JIJ)=PRI_UP (JIJ, JK)
    ZRV_UP (JIJ)=PRV_UP (JIJ, JK)
    ZBUO (JIJ, JK)=ZG_O_THVREF (JIJ, JK)*(PTHV_UP (JIJ, JK)-ZTHVM_F (JIJ, JK))
    PBUO_INTEG (JIJ, JK)=ZBUO (JIJ, JK)*(PZZ (JIJ, JK+IKL)-PZZ (JIJ, JK))
    ZDZ (JIJ)=MAX (ZEPS, PZZ (JIJ, JK+IKL)-PZZ (JIJ, JK))
    ZTEST (JIJ)=PARAMMF%XA1*ZBUO (JIJ, JK)-PARAMMF%XB*ZW_UP2 (JIJ, JK)
    ZCOE (JIJ)=ZDZ (JIJ)

    IF (ZTEST (JIJ)>0.) THEN
      ZCOE (JIJ)=ZDZ (JIJ)/(1.+PARAMMF%XBETA1)
    ENDIF

    ZWCOE (JIJ)=(1.-PARAMMF%XB*ZCOE (JIJ))/(1.+PARAMMF%XB*ZCOE (JIJ))
    ZBUCOE (JIJ)=2.*ZCOE (JIJ)/(1.+PARAMMF%XB*ZCOE (JIJ))
    ZW_UP2 (JIJ, JK+IKL)=MAX (ZEPS, ZW_UP2 (JIJ, JK)*ZWCOE&
    & (JIJ)+PARAMMF%XA1*ZBUO (JIJ, JK)*ZBUCOE (JIJ))
    ZW_MAX (JIJ)=MAX (ZW_MAX (JIJ), SQRT (ZW_UP2 (JIJ, JK+IKL)))
    ZWUP_MEAN (JIJ)=MAX (ZEPS, 0.5*(ZW_UP2 (JIJ, JK+IKL)+ZW_UP2 (JIJ, JK)))
    PENTR (JIJ, JK)=MAX (0.,(PARAMMF%XBETA1/(1.+PARAMMF%XBETA1))&
    &*(PARAMMF%XA1*ZBUO (JIJ, JK)/ZWUP_MEAN (JIJ)-PARAMMF%XB))
    ZDETR_BUO (JIJ)=MAX (0.,-(PARAMMF%XBETA1/(1.+PARAMMF%XBETA1&
    &))*PARAMMF%XA1*ZBUO (JIJ, JK)/ZWUP_MEAN (JIJ))
    ZDETR_RT (JIJ)=PARAMMF%XC*SQRT (MAX (0.,(PRT_UP (JIJ, JK)-ZRTM_F&
    & (JIJ, JK)))/MAX (ZEPS, ZRTM_F (JIJ, JK))/ZWUP_MEAN (JIJ))
    PDETR (JIJ, JK)=ZDETR_RT (JIJ)+ZDETR_BUO (JIJ)

    IF (GTEST (JIJ)) THEN
      ZZTOP (JIJ)=MAX (ZZTOP (JIJ), PZZ (JIJ, JK+IKL))
      ZMIX2 (JIJ)=(PZZ (JIJ, JK+IKL)-PZZ (JIJ, JK))*PENTR (JIJ, JK)
      ZMIX3 (JIJ)=(PZZ (JIJ, JK+IKL)-PZZ (JIJ, JK))*PDETR (JIJ, JK)
      ZQTM (JIJ)=PRTM (JIJ, JK)/(1.+PRTM (JIJ, JK))
      ZTHSM (JIJ, JK)=PTHLM (JIJ, JK)*(1.+PARAMMF%XLAMBDA_MF*ZQTM (JIJ))
      ZTHS_UP (JIJ, JK+IKL)=(ZTHS_UP (JIJ, JK)*(1.-0.5*ZMIX2 (JIJ&
      &))+ZTHSM (JIJ, JK)*ZMIX2 (JIJ))/(1.+0.5*ZMIX2 (JIJ))
      PRT_UP (JIJ, JK+IKL)=(PRT_UP (JIJ, JK)*(1.-0.5*ZMIX2 (JIJ&
      &))+PRTM (JIJ, JK)*ZMIX2 (JIJ))/(1.+0.5*ZMIX2 (JIJ))
      ZQT_UP (JIJ)=PRT_UP (JIJ, JK+IKL)/(1.+PRT_UP (JIJ, JK+IKL))
      PTHL_UP (JIJ, JK+IKL)=ZTHS_UP (JIJ, JK+IKL)/(1.+PARAMMF%XLAMBDA_MF*ZQT_UP (JIJ))
    ENDIF


    IF (PARAMMF%LMIXUV) THEN

      IF (JK/=IKB) THEN

        IF (GTEST (JIJ)) THEN
          PU_UP (JIJ, JK+IKL)=(PU_UP (JIJ, JK)*(1-0.5*ZMIX2 (JIJ))+PUM (JIJ, JK)*ZMIX2 (JIJ)+0.5*PARAMMF&
          &%XPRES_UV*(PZZ (JIJ, JK+IKL)-PZZ (JIJ, JK))*((PUM (JIJ, JK+IKL)-PUM (JIJ, JK))/PDZZ (JIJ&
          &, JK+IKL)+(PUM (JIJ, JK)-PUM (JIJ, JK-IKL))/PDZZ (JIJ, JK)))/(1+0.5*ZMIX2 (JIJ))
          PV_UP (JIJ, JK+IKL)=(PV_UP (JIJ, JK)*(1-0.5*ZMIX2 (JIJ))+PVM (JIJ, JK)*ZMIX2 (JIJ)+0.5*PARAMMF&
          &%XPRES_UV*(PZZ (JIJ, JK+IKL)-PZZ (JIJ, JK))*((PVM (JIJ, JK+IKL)-PVM (JIJ, JK))/PDZZ (JIJ&
          &, JK+IKL)+(PVM (JIJ, JK)-PVM (JIJ, JK-IKL))/PDZZ (JIJ, JK)))/(1+0.5*ZMIX2 (JIJ))
        ENDIF

      ELSE

        IF (GTEST (JIJ)) THEN
          PU_UP (JIJ, JK+IKL)=(PU_UP (JIJ, JK)*(1-0.5*ZMIX2 (JIJ))+PUM (JIJ, JK)*ZMIX2&
          & (JIJ)+0.5*PARAMMF%XPRES_UV*(PZZ (JIJ, JK+IKL)-PZZ (JIJ, JK))*((PUM (JIJ&
          &, JK+IKL)-PUM (JIJ, JK))/PDZZ (JIJ, JK+IKL)))/(1+0.5*ZMIX2 (JIJ))
          PV_UP (JIJ, JK+IKL)=(PV_UP (JIJ, JK)*(1-0.5*ZMIX2 (JIJ))+PVM (JIJ, JK)*ZMIX2&
          & (JIJ)+0.5*PARAMMF%XPRES_UV*(PZZ (JIJ, JK+IKL)-PZZ (JIJ, JK))*((PVM (JIJ&
          &, JK+IKL)-PVM (JIJ, JK))/PDZZ (JIJ, JK+IKL)))/(1+0.5*ZMIX2 (JIJ))
        ENDIF

      ENDIF

    ENDIF

    ZRC_UP (JIJ)=PRC_UP (JIJ, JK)
    ZRI_UP (JIJ)=PRI_UP (JIJ, JK)
    ZRV_UP (JIJ)=PRV_UP (JIJ, JK)
  ENDDO

  CALL TH_R_FROM_THL_RT_OPENACC (CST, NEBN, D%NIJT, NEBN%CFRAC_ICE_SHALLOW_MF, PFRAC_ICE_UP&
  & (:, JK+IKL), ZPRES_F (:, JK+IKL), PTHL_UP (:, JK+IKL), PRT_UP (:, JK+IKL), ZTH_UP&
  & (:, JK+IKL), ZRV_UP (:), ZRC_UP (:), ZRI_UP (:), ZRSATW (:), ZRSATI (:), OOCEAN&
  &=.FALSE., PBUF=ZBUF, KB=D%NIJB, KE=D%NIJE, YDSTACK=YLSTACK)

  DO JIJ=IIJB, IIJE

    IF (GTEST (JIJ)) THEN
      ZT_UP (JIJ)=ZTH_UP (JIJ, JK+IKL)*PEXNM (JIJ, JK+IKL)
      ZCP (JIJ)=CST%XCPD+CST%XCL*ZRC_UP (JIJ)
      ZLVOCPEXN (JIJ)=(CST%XLVTT+(CST%XCPV-CST%XCL)*(ZT_UP (JIJ)-CST%XTT))/ZCP (JIJ)/PEXNM (JIJ, JK+IKL)
      PRC_UP (JIJ, JK+IKL)=MIN (0.5E-3, ZRC_UP (JIJ))
      PTHL_UP (JIJ, JK+IKL)=PTHL_UP (JIJ, JK+IKL)+ZLVOCPEXN (JIJ)*(ZRC_UP (JIJ)-PRC_UP (JIJ, JK+IKL))
      PRV_UP (JIJ, JK+IKL)=ZRV_UP (JIJ)
      PRI_UP (JIJ, JK+IKL)=ZRI_UP (JIJ)
      PRT_UP (JIJ, JK+IKL)=PRC_UP (JIJ, JK+IKL)+PRV_UP (JIJ, JK+IKL)
      PRSAT_UP (JIJ, JK+IKL)=ZRSATW (JIJ)*(1-PFRAC_ICE_UP (JIJ&
      &, JK+IKL))+ZRSATI (JIJ)*PFRAC_ICE_UP (JIJ, JK+IKL)
    ENDIF


    IF (GTEST (JIJ)) THEN
      PTHV_UP (JIJ, JK+IKL)=ZTH_UP (JIJ, JK+IKL)*(1.+0.608*PRV_UP (JIJ, JK+IKL)-PRC_UP (JIJ, JK+IKL))
    ENDIF

    GTESTETL (JIJ)=.FALSE.

    IF (GTEST (JIJ).AND.(PBUO_INTEG (JIJ, JK)<=0.)) THEN
      KKETL (JIJ)=JK+IKL
      GTESTETL (JIJ)=.TRUE.
    ENDIF


    IF (GTEST (JIJ).AND.((ZW_UP2 (JIJ, JK+IKL)<=ZEPS))) THEN
      ZW_UP2 (JIJ, JK+IKL)=ZEPS
      GTEST (JIJ)=.FALSE.
      PTHL_UP (JIJ, JK+IKL)=ZTHLM_F (JIJ, JK+IKL)
      PRT_UP (JIJ, JK+IKL)=ZRTM_F (JIJ, JK+IKL)
      PRC_UP (JIJ, JK+IKL)=0.
      PRI_UP (JIJ, JK+IKL)=0.
      PRV_UP (JIJ, JK+IKL)=0.
      PTHV_UP (JIJ, JK+IKL)=ZTHVM_F (JIJ, JK+IKL)
      PFRAC_UP (JIJ, JK+IKL)=0.
      KKCTL (JIJ)=JK+IKL
    ENDIF

  ENDDO

ENDDO


DO JIJ=IIJB, IIJE
  ZZTOP (JIJ)=MAX (ZZTOP (JIJ), ZEPS)
ENDDO


DO JK=IKB+IKL, IKE-IKL, IKL

  DO JIJ=IIJB, IIJE

    IF (JK<=IALIM (JIJ)) THEN
      ZALIM_STAR_TOT (JIJ)=ZALIM_STAR_TOT (JIJ)+ZALIM_STAR (JIJ, JK)**2*ZZDZ (JIJ, JK)/PRHODREF (JIJ, JK)
    ENDIF

  ENDDO

ENDDO


DO JIJ=IIJB, IIJE

  IF (ZALIM_STAR_TOT (JIJ)*ZZTOP (JIJ)>ZEPS) THEN
    ZPHI (JIJ)=ZW_MAX (JIJ)/(PARAMMF%XR*ZZTOP (JIJ)*ZALIM_STAR_TOT (JIJ))
  ENDIF

  GTEST (JIJ)=.TRUE.
  PEMF (JIJ, IKB+IKL)=ZPHI (JIJ)*ZZDZ (JIJ, IKB)*ZALIM_STAR (JIJ, IKB)
  PFRAC_UP (JIJ, IKB+IKL)=PEMF (JIJ, IKB+IKL)/(SQRT (ZW_UP2 (JIJ, IKB+IKL))*ZRHO_F (JIJ, IKB+IKL))
  PFRAC_UP (JIJ, IKB+IKL)=MIN (PARAMMF%XFRAC_UP_MAX, PFRAC_UP (JIJ, IKB+IKL))
  PEMF (JIJ, IKB+IKL)=ZRHO_F (JIJ, IKB+IKL)*PFRAC_UP (JIJ, IKB+IKL)*SQRT (ZW_UP2 (JIJ, IKB+IKL))
ENDDO


DO JK=IKB+IKL, IKE-IKL, IKL

  DO JIJ=IIJB, IIJE
    GTEST (JIJ)=(ZW_UP2 (JIJ, JK)>ZEPS)

    IF (GTEST (JIJ)) THEN

      IF (JK<IALIM (JIJ)) THEN
        PEMF (JIJ, JK+IKL)=MAX (0., PEMF (JIJ, JK)+ZPHI (JIJ)&
        &*ZZDZ (JIJ, JK)*(PENTR (JIJ, JK)-PDETR (JIJ, JK)))
      ELSE
        ZMIX1 (JIJ)=ZZDZ (JIJ, JK)*(PENTR (JIJ, JK)-PDETR (JIJ, JK))
        PEMF (JIJ, JK+IKL)=PEMF (JIJ, JK)*EXP (ZMIX1 (JIJ))
      ENDIF

      PFRAC_UP (JIJ, JK+IKL)=PEMF (JIJ, JK+IKL)/(SQRT (ZW_UP2 (JIJ, JK+IKL))*ZRHO_F (JIJ, JK+IKL))
      PFRAC_UP (JIJ, JK+IKL)=MIN (PARAMMF%XFRAC_UP_MAX, PFRAC_UP (JIJ, JK+IKL))
      PEMF (JIJ, JK+IKL)=ZRHO_F (JIJ, JK+IKL)*PFRAC_UP (JIJ, JK+IKL)*SQRT (ZW_UP2 (JIJ, JK+IKL))
    ENDIF

  ENDDO

ENDDO


DO JK=1, IKT

  DO JIJ=IIJB, IIJE
    PW_UP (JIJ, JK)=SQRT (ZW_UP2 (JIJ, JK))
  ENDDO

ENDDO


DO JIJ=IIJB, IIJE
  PEMF (JIJ, IKB)=0.
ENDDO


DO JIJ=IIJB, IIJE
  PDEPTH (JIJ)=MAX (0., PZZ (JIJ, KKCTL (JIJ))-PZZ (JIJ, KKLCL (JIJ)))
ENDDO


DO JIJ=IIJB, IIJE
  GWORK1 (JIJ)=(GTESTLCL (JIJ).AND.(PDEPTH (JIJ)>ZDEPTH_MAX1))
ENDDO


DO JK=1, D%NKT

  DO JIJ=IIJB, IIJE
    GWORK2 (JIJ, JK)=GWORK1 (JIJ)
    ZCOEF (JIJ, JK)=(1.-(PDEPTH (JIJ)-ZDEPTH_MAX1)/(ZDEPTH_MAX2-ZDEPTH_MAX1))
    ZCOEF (JIJ, JK)=MIN (MAX (ZCOEF (JIJ, JK), 0.), 1.)
  ENDDO

ENDDO


DO JK=1, IKT

  DO JIJ=IIJB, IIJE

    IF (GWORK2 (JIJ, JK)) THEN
      PEMF (JIJ, JK)=PEMF (JIJ, JK)*ZCOEF (JIJ, JK)
      PFRAC_UP (JIJ, JK)=PFRAC_UP (JIJ, JK)*ZCOEF (JIJ, JK)
    ENDIF

  ENDDO

ENDDO




INCLUDE"th_r_from_thl_rt.func.h"
INCLUDE"compute_frac_ice.func.h"
ENDSUBROUTINE COMPUTE_UPDRAFT_RAHA_OPENACC

ENDMODULE MODE_COMPUTE_UPDRAFT_RAHA_OPENACC
