MODULE UTIL_CPG_SURF_VAD_OPTS_TYPE_MOD

USE CPG_OPTS_TYPE_MOD, ONLY : CPG_SURF_VAD_OPTS_TYPE

INTERFACE SAVE
MODULE PROCEDURE SAVE_CPG_SURF_VAD_OPTS_TYPE
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_CPG_SURF_VAD_OPTS_TYPE
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_CPG_SURF_VAD_OPTS_TYPE
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_CPG_SURF_VAD_OPTS_TYPE
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_CPG_SURF_VAD_OPTS_TYPE
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_CPG_SURF_VAD_OPTS_TYPE
END INTERFACE



CONTAINS

SUBROUTINE SAVE_CPG_SURF_VAD_OPTS_TYPE (SELF, KLUN)
USE UTIL_CPG_SURF_VA_DESD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_LAND_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SEAD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SOOD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SULD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_VOLD_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_VAD_OPTS_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SAVE_CPG_SURF_VA_SEAD_OPTS_TYPE (SELF%YSEA, KLUN)
CALL SAVE_CPG_SURF_VA_LAND_OPTS_TYPE (SELF%YLAN, KLUN)
CALL SAVE_CPG_SURF_VA_SOOD_OPTS_TYPE (SELF%YSOO, KLUN)
CALL SAVE_CPG_SURF_VA_DESD_OPTS_TYPE (SELF%YDES, KLUN)
CALL SAVE_CPG_SURF_VA_SULD_OPTS_TYPE (SELF%YSUL, KLUN)
CALL SAVE_CPG_SURF_VA_VOLD_OPTS_TYPE (SELF%YVOL, KLUN)
END SUBROUTINE

SUBROUTINE LOAD_CPG_SURF_VAD_OPTS_TYPE (SELF, KLUN)
USE UTIL_CPG_SURF_VA_DESD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_LAND_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SEAD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SOOD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SULD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_VOLD_OPTS_TYPE_MOD

IMPLICIT NONE
TYPE (CPG_SURF_VAD_OPTS_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL LOAD_CPG_SURF_VA_SEAD_OPTS_TYPE (SELF%YSEA, KLUN)
CALL LOAD_CPG_SURF_VA_LAND_OPTS_TYPE (SELF%YLAN, KLUN)
CALL LOAD_CPG_SURF_VA_SOOD_OPTS_TYPE (SELF%YSOO, KLUN)
CALL LOAD_CPG_SURF_VA_DESD_OPTS_TYPE (SELF%YDES, KLUN)
CALL LOAD_CPG_SURF_VA_SULD_OPTS_TYPE (SELF%YSUL, KLUN)
CALL LOAD_CPG_SURF_VA_VOLD_OPTS_TYPE (SELF%YVOL, KLUN)
END SUBROUTINE


SUBROUTINE COPY_CPG_SURF_VAD_OPTS_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_CPG_SURF_VA_DESD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_LAND_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SEAD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SOOD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SULD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_VOLD_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_VAD_OPTS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
CALL COPY_CPG_SURF_VA_SEAD_OPTS_TYPE (SELF%YSEA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_VA_LAND_OPTS_TYPE (SELF%YLAN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_VA_SOOD_OPTS_TYPE (SELF%YSOO, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_VA_DESD_OPTS_TYPE (SELF%YDES, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_VA_SULD_OPTS_TYPE (SELF%YSUL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL COPY_CPG_SURF_VA_VOLD_OPTS_TYPE (SELF%YVOL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

SUBROUTINE HOST_CPG_SURF_VAD_OPTS_TYPE (SELF)
USE UTIL_CPG_SURF_VA_DESD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_LAND_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SEAD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SOOD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SULD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_VOLD_OPTS_TYPE_MOD

IMPLICIT NONE
TYPE (CPG_SURF_VAD_OPTS_TYPE), TARGET :: SELF

CALL HOST_CPG_SURF_VA_SEAD_OPTS_TYPE (SELF%YSEA)

CALL HOST_CPG_SURF_VA_LAND_OPTS_TYPE (SELF%YLAN)

CALL HOST_CPG_SURF_VA_SOOD_OPTS_TYPE (SELF%YSOO)

CALL HOST_CPG_SURF_VA_DESD_OPTS_TYPE (SELF%YDES)

CALL HOST_CPG_SURF_VA_SULD_OPTS_TYPE (SELF%YSUL)

CALL HOST_CPG_SURF_VA_VOLD_OPTS_TYPE (SELF%YVOL)

END SUBROUTINE

     

SUBROUTINE CRC64_CPG_SURF_VAD_OPTS_TYPE (SELF, KLUN, CDPATH)
USE UTIL_CPG_SURF_VA_DESD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_LAND_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SEAD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SOOD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SULD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_VOLD_OPTS_TYPE_MOD
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (CPG_SURF_VAD_OPTS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL CRC64_CPG_SURF_VA_SEAD_OPTS_TYPE (SELF%YSEA, KLUN, CDPATH//'%YSEA'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_VA_LAND_OPTS_TYPE (SELF%YLAN, KLUN, CDPATH//'%YLAN'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_VA_SOOD_OPTS_TYPE (SELF%YSOO, KLUN, CDPATH//'%YSOO'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_VA_DESD_OPTS_TYPE (SELF%YDES, KLUN, CDPATH//'%YDES'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_VA_SULD_OPTS_TYPE (SELF%YSUL, KLUN, CDPATH//'%YSUL'//TRIM(CLIND))

CLIND = ''
CALL CRC64_CPG_SURF_VA_VOLD_OPTS_TYPE (SELF%YVOL, KLUN, CDPATH//'%YVOL'//TRIM(CLIND))

END SUBROUTINE

SUBROUTINE WIPE_CPG_SURF_VAD_OPTS_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_CPG_SURF_VA_DESD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_LAND_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SEAD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SOOD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_SULD_OPTS_TYPE_MOD
USE UTIL_CPG_SURF_VA_VOLD_OPTS_TYPE_MOD
IMPLICIT NONE
TYPE (CPG_SURF_VAD_OPTS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL WIPE_CPG_SURF_VA_SEAD_OPTS_TYPE (SELF%YSEA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_VA_LAND_OPTS_TYPE (SELF%YLAN, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_VA_SOOD_OPTS_TYPE (SELF%YSOO, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_VA_DESD_OPTS_TYPE (SELF%YDES, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_VA_SULD_OPTS_TYPE (SELF%YSUL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL WIPE_CPG_SURF_VA_VOLD_OPTS_TYPE (SELF%YVOL, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
