INTERFACE
SUBROUTINE APL_ARPEGE_ATMOSPHERE_UPDATE_PARALLEL (YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE&
&, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF&
&, YDVARS, YDMODEL, YDDDH, YD_PDIFEXT, YD_PDSA_CPS, YD_PMSC_FRMQ, YD_PPFL_FEFB1, YD_PPFL_FEFB2&
&, YD_PPFL_FEFB3, YD_PPFL_FTKE, YD_PPFL_FTKEI, YD_PFCHQ)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_NEXT_STATE_TYPE_MOD,ONLY:MF_PHYS_NEXT_STATE_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE, CPG_DYN_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE TYPE_MODEL,ONLY:MODEL
USE DDH_MIX,ONLY:TYP_DDH
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE PARKIND1
USE FXTRAN_ACDC_ARRAY_COPY_MOD
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MF_PHYS_NEXT_STATE_TYPE), INTENT (INOUT)::YDMF_PHYS_NEXT_STATE
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (CPG_DYN_TYPE), INTENT (IN)::YDCPG_DYN0
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (TYP_DDH), INTENT (INOUT)::YDDDH
CLASS (FIELD_4RB), POINTER :: YD_PDIFEXT
CLASS (FIELD_2RB), POINTER :: YD_PDSA_CPS
CLASS (FIELD_3RB), POINTER :: YD_PMSC_FRMQ
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FEFB1
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FEFB2
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FEFB3
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FTKE
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FTKEI
CLASS (FIELD_3RB), POINTER :: YD_PFCHQ
END SUBROUTINE APL_ARPEGE_ATMOSPHERE_UPDATE_PARALLEL


END INTERFACE
