INTERFACE
SUBROUTINE APL_ARPEGE_INIT_SURFEX_PARALLEL (YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS&
&, YDCPG_OPTS, YDCPG_MISC, YDCPG_GPAR, YDMF_PHYS, YDVARS, YDMODEL, YD_PALBD, YD_PALBP&
&, YD_PFLU_EMIS, YD_PSGROUPEL, YD_PSRAIN, YD_PSSNOW, YD_PTSN)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE, CPG_GPAR_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE PARKIND1
USE FXTRAN_ACDC_ARRAY_COPY_MOD
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (CPG_GPAR_TYPE), INTENT (INOUT)::YDCPG_GPAR
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (MODEL), INTENT (IN)::YDMODEL
CLASS (FIELD_3RB), POINTER :: YD_PALBD
CLASS (FIELD_3RB), POINTER :: YD_PALBP
CLASS (FIELD_2RB), POINTER :: YD_PFLU_EMIS
CLASS (FIELD_2RB), POINTER :: YD_PSGROUPEL
CLASS (FIELD_2RB), POINTER :: YD_PSRAIN
CLASS (FIELD_2RB), POINTER :: YD_PSSNOW
CLASS (FIELD_2RB), POINTER :: YD_PTSN
END SUBROUTINE APL_ARPEGE_INIT_SURFEX_PARALLEL


END INTERFACE
