SUBROUTINE CUENTR_OPENACC (YDCST, YDECUMF, YDSPP_CONFIG, KIDIA, KFDIA, KLON, KLEV, KK, KCBOT&
&, KTYPE, LDCUM, LDWORK, PQSEN, PAPH, PGEOH, PMFU, PGP2DSPP, PDMFEN, PDMFDE, YDSTACK)
!$ACC ROUTINE (CUENTR_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOECUMF,ONLY:TECUMF
USE SPP_MOD,ONLY:TSPP_CONFIG
USE SPP_GEN_MOD,ONLY:SPP_PERT
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TSPP_CONFIG), INTENT (IN)::YDSPP_CONFIG
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KK
INTEGER (KIND=JPIM), INTENT (IN)::KCBOT 
INTEGER (KIND=JPIM), INTENT (IN)::KTYPE 
LOGICAL, INTENT (IN)::LDCUM 
LOGICAL, INTENT (IN)::LDWORK
REAL (KIND=JPRB), INTENT (IN)::PQSEN 
REAL (KIND=JPRB), INTENT (IN)::PAPH 
REAL (KIND=JPRB), INTENT (IN)::PGEOH 
REAL (KIND=JPRB), INTENT (IN)::PMFU 
REAL (KIND=JPRB), INTENT (IN)::PGP2DSPP 
REAL (KIND=JPRB), INTENT (OUT)::PDMFEN 
REAL (KIND=JPRB), INTENT (OUT)::PDMFDE 
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK

fxtran_acdc_temp (INTEGER(KIND=JPIM), KCBOT_PTR, (KLON))
fxtran_acdc_temp (INTEGER(KIND=JPIM), KTYPE_PTR, (KLON))
fxtran_acdc_temp (LOGICAL, LDCUM_PTR, (KLON))
fxtran_acdc_temp (REAL(KIND=JPRB), PQSEN_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PAPH_PTR, (KLON, KLEV+1))
fxtran_acdc_temp (REAL(KIND=JPRB), PGEOH_PTR, (KLON, KLEV+1))
fxtran_acdc_temp (REAL(KIND=JPRB), PMFU_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PGP2DSPP_PTR, (KLON, YDSPP_CONFIG%SM%NRFTOTAL))
fxtran_acdc_temp (REAL(KIND=JPRB), PDMFEN_PTR, (KLON))
fxtran_acdc_temp (REAL(KIND=JPRB), PDMFDE_PTR, (KLON))

LOGICAL::LLO1
INTEGER (KIND=JPIM)::JL
LOGICAL::LLPERT_DETRPEN
INTEGER (KIND=JPIM)::IPDETRPEN
INTEGER (KIND=JPIM)::IPN
TYPE (SPP_PERT)::PN1
REAL (KIND=JPRB)::ZXDETRPEN
REAL (KIND=JPRB)::ZRG
REAL (KIND=JPRB)::ZMF
REAL (KIND=JPRB)::ZENTR 
REAL (KIND=JPRB)::ZDZ


fxtran_acdc_assoc (KCBOT_PTR, KCBOT)

fxtran_acdc_assoc (KTYPE_PTR, KTYPE)

fxtran_acdc_assoc (LDCUM_PTR, LDCUM)

fxtran_acdc_assoc (PQSEN_PTR, PQSEN)

fxtran_acdc_assoc (PAPH_PTR, PAPH)

fxtran_acdc_assoc (PGEOH_PTR, PGEOH)

fxtran_acdc_assoc (PMFU_PTR, PMFU)

fxtran_acdc_assoc (PGP2DSPP_PTR, PGP2DSPP)

fxtran_acdc_assoc (PDMFEN_PTR, PDMFEN)

fxtran_acdc_assoc (PDMFDE_PTR, PDMFDE)

JL = KIDIA





IF (LDWORK) THEN
  ZRG=1.0_JPRB/YDCST%RG
  
  LLPERT_DETRPEN=.FALSE.
  
  
  PDMFEN_PTR (JL)=0.0_JPRB
  PDMFDE_PTR (JL)=0.0_JPRB
  ZENTR =0.0

  

  

  IF (LDCUM_PTR (JL)) THEN
    ZDZ=(PGEOH_PTR (JL, KK)-PGEOH_PTR (JL, KK+1))*ZRG
    ZMF=PMFU_PTR (JL, KK+1)*ZDZ
    LLO1=KK<KCBOT_PTR (JL)

    IF (LLO1) THEN
      
      ZXDETRPEN=YDECUMF%DETRPEN
      
      PDMFEN_PTR (JL)=ZENTR *ZMF
      PDMFDE_PTR (JL)=ZXDETRPEN*ZMF
    ENDIF

  ENDIF

  
ENDIF



ENDSUBROUTINE CUENTR_OPENACC
