MODULE UTIL_CST_T_MOD

USE MODD_CST, ONLY : CST_T

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_CST_T
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_CST_T
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_CST_T
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_CST_T
END INTERFACE


INTERFACE ACDC_CRC64
MODULE PROCEDURE ACDC_CRC64_CST_T
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_CST_T
END INTERFACE

INTERFACE ACDC_SIZE
MODULE PROCEDURE ACDC_SIZE_CST_T
END INTERFACE

CONTAINS

SUBROUTINE ACDC_SAVE_CST_T (SELF, KLUN)

IMPLICIT NONE
TYPE (CST_T), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%XPI
WRITE (KLUN) SELF%XKARMAN
WRITE (KLUN) SELF%XLIGHTSPEED
WRITE (KLUN) SELF%XPLANCK
WRITE (KLUN) SELF%XBOLTZ
WRITE (KLUN) SELF%XAVOGADRO
WRITE (KLUN) SELF%XDAY
WRITE (KLUN) SELF%XSIYEA
WRITE (KLUN) SELF%XSIDAY
WRITE (KLUN) SELF%NDAYSEC
WRITE (KLUN) SELF%XOMEGA
WRITE (KLUN) SELF%XRADIUS
WRITE (KLUN) SELF%XG
WRITE (KLUN) SELF%XP00
WRITE (KLUN) SELF%XP00OCEAN
WRITE (KLUN) SELF%XRH00OCEAN
WRITE (KLUN) SELF%XTH00
WRITE (KLUN) SELF%XTH00OCEAN
WRITE (KLUN) SELF%XSA00OCEAN
WRITE (KLUN) SELF%XSTEFAN
WRITE (KLUN) SELF%XI0
WRITE (KLUN) SELF%XMD
WRITE (KLUN) SELF%XMV
WRITE (KLUN) SELF%XRD
WRITE (KLUN) SELF%XRV
WRITE (KLUN) SELF%XEPSILO
WRITE (KLUN) SELF%XCPD
WRITE (KLUN) SELF%XCPV
WRITE (KLUN) SELF%XRHOLW
WRITE (KLUN) SELF%XCL
WRITE (KLUN) SELF%XCI
WRITE (KLUN) SELF%XTT
WRITE (KLUN) SELF%XLVTT
WRITE (KLUN) SELF%XLSTT
WRITE (KLUN) SELF%XLMTT
WRITE (KLUN) SELF%XESTT
WRITE (KLUN) SELF%XALPW
WRITE (KLUN) SELF%XBETAW
WRITE (KLUN) SELF%XGAMW
WRITE (KLUN) SELF%XALPI
WRITE (KLUN) SELF%XBETAI
WRITE (KLUN) SELF%XGAMI
WRITE (KLUN) SELF%XCONDI
WRITE (KLUN) SELF%XALPHAOC
WRITE (KLUN) SELF%XBETAOC
WRITE (KLUN) SELF%XROC
WRITE (KLUN) SELF%XD1
WRITE (KLUN) SELF%XD2
WRITE (KLUN) SELF%XRHOLI
WRITE (KLUN) SELF%RDSRV
WRITE (KLUN) SELF%RDSCPD
WRITE (KLUN) SELF%RINVXP00
WRITE (KLUN) SELF%XMNH_TINY
WRITE (KLUN) SELF%XMNH_TINY_12
WRITE (KLUN) SELF%XMNH_EPSILON
WRITE (KLUN) SELF%XMNH_HUGE
WRITE (KLUN) SELF%XMNH_HUGE_12_LOG
WRITE (KLUN) SELF%XEPS_DT
WRITE (KLUN) SELF%XRES_FLAT_CART
WRITE (KLUN) SELF%XRES_OTHER
WRITE (KLUN) SELF%XRES_PREP
END SUBROUTINE

SUBROUTINE ACDC_LOAD_CST_T (SELF, KLUN)

IMPLICIT NONE
TYPE (CST_T), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%XPI
READ (KLUN) SELF%XKARMAN
READ (KLUN) SELF%XLIGHTSPEED
READ (KLUN) SELF%XPLANCK
READ (KLUN) SELF%XBOLTZ
READ (KLUN) SELF%XAVOGADRO
READ (KLUN) SELF%XDAY
READ (KLUN) SELF%XSIYEA
READ (KLUN) SELF%XSIDAY
READ (KLUN) SELF%NDAYSEC
READ (KLUN) SELF%XOMEGA
READ (KLUN) SELF%XRADIUS
READ (KLUN) SELF%XG
READ (KLUN) SELF%XP00
READ (KLUN) SELF%XP00OCEAN
READ (KLUN) SELF%XRH00OCEAN
READ (KLUN) SELF%XTH00
READ (KLUN) SELF%XTH00OCEAN
READ (KLUN) SELF%XSA00OCEAN
READ (KLUN) SELF%XSTEFAN
READ (KLUN) SELF%XI0
READ (KLUN) SELF%XMD
READ (KLUN) SELF%XMV
READ (KLUN) SELF%XRD
READ (KLUN) SELF%XRV
READ (KLUN) SELF%XEPSILO
READ (KLUN) SELF%XCPD
READ (KLUN) SELF%XCPV
READ (KLUN) SELF%XRHOLW
READ (KLUN) SELF%XCL
READ (KLUN) SELF%XCI
READ (KLUN) SELF%XTT
READ (KLUN) SELF%XLVTT
READ (KLUN) SELF%XLSTT
READ (KLUN) SELF%XLMTT
READ (KLUN) SELF%XESTT
READ (KLUN) SELF%XALPW
READ (KLUN) SELF%XBETAW
READ (KLUN) SELF%XGAMW
READ (KLUN) SELF%XALPI
READ (KLUN) SELF%XBETAI
READ (KLUN) SELF%XGAMI
READ (KLUN) SELF%XCONDI
READ (KLUN) SELF%XALPHAOC
READ (KLUN) SELF%XBETAOC
READ (KLUN) SELF%XROC
READ (KLUN) SELF%XD1
READ (KLUN) SELF%XD2
READ (KLUN) SELF%XRHOLI
READ (KLUN) SELF%RDSRV
READ (KLUN) SELF%RDSCPD
READ (KLUN) SELF%RINVXP00
READ (KLUN) SELF%XMNH_TINY
READ (KLUN) SELF%XMNH_TINY_12
READ (KLUN) SELF%XMNH_EPSILON
READ (KLUN) SELF%XMNH_HUGE
READ (KLUN) SELF%XMNH_HUGE_12_LOG
READ (KLUN) SELF%XEPS_DT
READ (KLUN) SELF%XRES_FLAT_CART
READ (KLUN) SELF%XRES_OTHER
READ (KLUN) SELF%XRES_PREP
END SUBROUTINE

SUBROUTINE ACDC_COPY_CST_T (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CST_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_CST_T (SELF)

IMPLICIT NONE
TYPE (CST_T), TARGET :: SELF


END SUBROUTINE



SUBROUTINE ACDC_CRC64_CST_T (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
TYPE (CST_T), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XPI), CDPATH//'%XPI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XKARMAN), CDPATH//'%XKARMAN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XLIGHTSPEED), CDPATH//'%XLIGHTSPEED'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XPLANCK), CDPATH//'%XPLANCK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XBOLTZ), CDPATH//'%XBOLTZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XAVOGADRO), CDPATH//'%XAVOGADRO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XDAY), CDPATH//'%XDAY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XSIYEA), CDPATH//'%XSIYEA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XSIDAY), CDPATH//'%XSIDAY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDAYSEC), CDPATH//'%NDAYSEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XOMEGA), CDPATH//'%XOMEGA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRADIUS), CDPATH//'%XRADIUS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XG), CDPATH//'%XG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XP00), CDPATH//'%XP00'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XP00OCEAN), CDPATH//'%XP00OCEAN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRH00OCEAN), CDPATH//'%XRH00OCEAN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XTH00), CDPATH//'%XTH00'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XTH00OCEAN), CDPATH//'%XTH00OCEAN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XSA00OCEAN), CDPATH//'%XSA00OCEAN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XSTEFAN), CDPATH//'%XSTEFAN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XI0), CDPATH//'%XI0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XMD), CDPATH//'%XMD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XMV), CDPATH//'%XMV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRD), CDPATH//'%XRD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRV), CDPATH//'%XRV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XEPSILO), CDPATH//'%XEPSILO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XCPD), CDPATH//'%XCPD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XCPV), CDPATH//'%XCPV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRHOLW), CDPATH//'%XRHOLW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XCL), CDPATH//'%XCL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XCI), CDPATH//'%XCI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XTT), CDPATH//'%XTT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XLVTT), CDPATH//'%XLVTT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XLSTT), CDPATH//'%XLSTT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XLMTT), CDPATH//'%XLMTT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XESTT), CDPATH//'%XESTT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XALPW), CDPATH//'%XALPW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XBETAW), CDPATH//'%XBETAW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XGAMW), CDPATH//'%XGAMW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XALPI), CDPATH//'%XALPI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XBETAI), CDPATH//'%XBETAI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XGAMI), CDPATH//'%XGAMI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XCONDI), CDPATH//'%XCONDI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XALPHAOC), CDPATH//'%XALPHAOC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XBETAOC), CDPATH//'%XBETAOC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XROC), CDPATH//'%XROC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XD1), CDPATH//'%XD1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XD2), CDPATH//'%XD2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRHOLI), CDPATH//'%XRHOLI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDSRV), CDPATH//'%RDSRV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RDSCPD), CDPATH//'%RDSCPD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RINVXP00), CDPATH//'%RINVXP00'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XMNH_TINY), CDPATH//'%XMNH_TINY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XMNH_TINY_12), CDPATH//'%XMNH_TINY_12'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XMNH_EPSILON), CDPATH//'%XMNH_EPSILON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XMNH_HUGE), CDPATH//'%XMNH_HUGE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XMNH_HUGE_12_LOG), CDPATH//'%XMNH_HUGE_12_LOG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XEPS_DT), CDPATH//'%XEPS_DT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRES_FLAT_CART), CDPATH//'%XRES_FLAT_CART'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRES_OTHER), CDPATH//'%XRES_OTHER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%XRES_PREP), CDPATH//'%XRES_PREP'

END SUBROUTINE

SUBROUTINE ACDC_WIPE_CST_T (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (CST_T), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

FUNCTION ACDC_SIZE_CST_T (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (CST_T),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%XPI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XPI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XKARMAN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XKARMAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XLIGHTSPEED)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLIGHTSPEED'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XPLANCK)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XPLANCK'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XBOLTZ)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBOLTZ'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XAVOGADRO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAVOGADRO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XDAY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XDAY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XSIYEA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSIYEA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XSIDAY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSIDAY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NDAYSEC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDAYSEC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XOMEGA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XOMEGA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRADIUS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRADIUS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XP00)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XP00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XP00OCEAN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XP00OCEAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRH00OCEAN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRH00OCEAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XTH00)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTH00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XTH00OCEAN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTH00OCEAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XSA00OCEAN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSA00OCEAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XSTEFAN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSTEFAN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XI0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XI0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XMD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XMD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XMV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XMV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XEPSILO)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEPSILO'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XCPD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCPD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XCPV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCPV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRHOLW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRHOLW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XCL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XCI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XTT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XLVTT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLVTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XLSTT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLSTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XLMTT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLMTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XESTT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XESTT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XALPW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XALPW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XBETAW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBETAW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XGAMW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XGAMW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XALPI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XALPI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XBETAI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBETAI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XGAMI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XGAMI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XCONDI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCONDI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XALPHAOC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XALPHAOC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XBETAOC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBETAOC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XROC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XROC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XD1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XD1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XD2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XD2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRHOLI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRHOLI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDSRV)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDSRV'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RDSCPD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RDSCPD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%RINVXP00)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%RINVXP00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XMNH_TINY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XMNH_TINY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XMNH_TINY_12)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XMNH_TINY_12'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XMNH_EPSILON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XMNH_EPSILON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XMNH_HUGE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XMNH_HUGE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XMNH_HUGE_12_LOG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XMNH_HUGE_12_LOG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XEPS_DT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEPS_DT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRES_FLAT_CART)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRES_FLAT_CART'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRES_OTHER)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRES_OTHER'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%XRES_PREP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRES_PREP'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
