MODULE LOAD_MODEL_PHYSICS_MF_TYPE_MOD

USE MODEL_PHYSICS_MF_MOD, ONLY : MODEL_PHYSICS_MF_TYPE

INTERFACE LOAD
MODULE PROCEDURE LOAD_MODEL_PHYSICS_MF_TYPE
END INTERFACE

CONTAINS

SUBROUTINE LOAD_MODEL_PHYSICS_MF_TYPE (KLUN, YD)
USE LOAD_TARPHY_MOD
USE LOAD_TCVMNH_MOD
USE LOAD_TLOUIS_MOD
USE LOAD_TMSE_MOD
USE LOAD_TNORGWD_MOD
USE LOAD_TPARAR_MOD
USE LOAD_TPHY_MOD
USE LOAD_TPHY0_MOD
USE LOAD_TPHY1_MOD
USE LOAD_TPHY2_MOD
USE LOAD_TPHY3_MOD
USE LOAD_TPHYDS_MOD
USE LOAD_TSIMPHL_MOD
USE LOAD_TTOPH_MOD
USE LOAD_TVDOZ_MOD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (OUT) :: YD

CALL LOAD (KLUN, YD%YRPHY)
CALL LOAD (KLUN, YD%YRPHY0)
CALL LOAD (KLUN, YD%YRPHY1)
CALL LOAD (KLUN, YD%YRPHY2)
CALL LOAD (KLUN, YD%YRPHY3)
CALL LOAD (KLUN, YD%YRPHYDS)
CALL LOAD (KLUN, YD%YRCVMNH)
CALL LOAD (KLUN, YD%YRTOPH)
CALL LOAD (KLUN, YD%YRVDOZ)
CALL LOAD (KLUN, YD%YRSIMPHL)
CALL LOAD (KLUN, YD%YRARPHY)
CALL LOAD (KLUN, YD%YRPARAR)
CALL LOAD (KLUN, YD%YRMSE)
CALL LOAD (KLUN, YD%YRLOUIS)
CALL LOAD (KLUN, YD%YRNORGWD)
END SUBROUTINE


END MODULE
