MODULE YOEGWD

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

!     -----------------------------------------------------------------
!*    ** *YOEGWD* - PARAMETERS FOR GRAVITY WAVE DRAG CALCULATIONS
!     -----------------------------------------------------------------

TYPE :: TEGWD
INTEGER(KIND=JPIM) :: NKTOPG
INTEGER(KIND=JPIM) :: NGWDLIM
INTEGER(KIND=JPIM) :: NGWDTOP
INTEGER(KIND=JPIM) :: NDIFF_STRATO
REAL(KIND=JPRB) :: GFRCRIT
REAL(KIND=JPRB) :: GRCRIT
REAL(KIND=JPRB) :: GKDRAG
REAL(KIND=JPRB) :: GKWAKE
REAL(KIND=JPRB) :: GSSEC
REAL(KIND=JPRB) :: GTSEC
REAL(KIND=JPRB) :: GVSEC
REAL(KIND=JPRB) :: GTENLIM
REAL(KIND=JPRB) :: GRFPLM
LOGICAL         :: LRDIFF_STRATO
LOGICAL         :: LDIAG_STRATO
!---------------------------------------------------------------------
CONTAINS
  PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
END TYPE TEGWD
!=====================================================================

!!TYPE(TEGWD), POINTER :: YREGWD => NULL()

!        * E.C.M.W.F. PHYSICS PACKAGE *

!     M. J. MILLER          E.C.M.W.F.      89/12/14

!  NAME     TYPE     PURPOSE
!  ----  :  ----   : ---------------------------------------------------

! GFRCRIT: CRITICAL FROUDE NUMBER
! GRCRIT : CRITICAL RICHARDSON NUMBER FOR ONSET OF WAVE TURBULENCE.
! GKDRAG : DRAG CONSTANT (PROPORTIONAL TO WAVENUMBER)
! GKWAKE : DRAG COEFFICIENT FOR LOWLEVEL WAKE DRAG
! NKTOPG : NUMBER OF TOPMOST LAYER USED TO DEFINE LOW-LEVEL FLOW
! NGWDLIM: VERTICAL LEVEL ABOVE WHICH THE WIND TENDENCIES WILL BE LIMITED 
!          TO GTENLIM
! GTENLIM: LIMITER FOR WIND TENDENCIES IN THE STRATOSPHERE AND MESOSPHERE
! GRFPLM : PRESUURE LIMIT FOR RAYLEIGH FRICTION
! NGWDTOP: INDEX FOR GRFPLM
! LRDIFF_STRATO: IF TRUE REDUCED VERTICAL DIFFUSION IN STRATOSPHERE
! NDIFF_STRATO: TYPE OF REDUCED VERTICAL DIFFUSION IN STRATOSPHERE
! LDIAG_STRATO:  IF TRUE STORE GRAVITY-WAVE MOMENTUM FLUXES


!*    SECURITY PARAMETERS.
!     --------------------

! GSSEC  : TO SECURE STABILITY.
! GTSEC  : TO SECURE THE STRESS CALCULATION.
! GVSEC  : TO SECURE THE PROJECTION CALCULATION.
!     -----------------------------------------------------------------
 
!---------------------------------------------------------------------

CONTAINS 
  
SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
IMPLICIT NONE
CLASS(TEGWD), INTENT(IN) :: SELF
INTEGER     , INTENT(IN) :: KDEPTH
INTEGER     , INTENT(IN) :: KOUTNO

INTEGER :: IDEPTHLOC

IDEPTHLOC = KDEPTH+2

WRITE(KOUTNO,*) REPEAT(' ',KDEPTH)    // 'model%yrml_phy_ec%yregwd : '
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'NKTOPG = ', SELF%NKTOPG
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'NGWDLIM = ', SELF%NGWDLIM
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'NGWDTOP = ', SELF%NGWDTOP
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'NDIFF_STRATO = ', SELF%NDIFF_STRATO
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'GFRCRIT = ', SELF%GFRCRIT
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'GRCRIT = ', SELF%GRCRIT
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'GKDRAG = ', SELF%GKDRAG
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'GKWAKE = ', SELF%GKWAKE
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'GSSEC = ', SELF%GSSEC
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'GTSEC = ', SELF%GTSEC
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'GVSEC = ', SELF%GVSEC
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'GTENLIM = ', SELF%GTENLIM
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'GRFPLM = ', SELF%GRFPLM
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'LRDIFF_STRATO = ', SELF%LRDIFF_STRATO
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'LDIAG_STRATO = ', SELF%LDIAG_STRATO

END SUBROUTINE PRINT_CONFIGURATION

END MODULE YOEGWD
