
SUBROUTINE ACVISIH_OPENACC (YDCST, YDVISI, KIDIA, KFDIA, KLON, KTDIA, KLEV, PAPHI, PAPHIF&
&, PAPRSF, PT, PR, PQL, PQI, PQR, PQS, PQG, PVISICLD, PVISIHYD, PMXCLWC, YDSTACK)
!$ACC ROUTINE (ACVISIH_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOMDVISI,ONLY:TDVISI
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (TDVISI), INTENT (IN)::YDVISI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPHI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPHIF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PR (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQI (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQR (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQG (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PVISICLD (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PVISIHYD (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PMXCLWC (KLON)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
REAL (KIND=JPRB)::ZGCONTENT 
REAL (KIND=JPRB)::ZSCONTENT 
REAL (KIND=JPRB)::ZRCONTENT 
REAL (KIND=JPRB)::ZICONTENT 
REAL (KIND=JPRB)::ZLCONTENT 
fxtran_acdc_temp (REAL (KIND=JPRB), ZRHOAIR, (KLON, KLEV))
REAL (KIND=JPRB)::ZC2 
REAL (KIND=JPRB)::ZC1 
INTEGER (KIND=JPIM)::ILEVB
INTEGER (KIND=JPIM)::ILEVH
INTEGER (KIND=JPIM)::ILEV 
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPRB)::ZCONTRAST
REAL (KIND=JPRB)::ZBETARAYL
REAL (KIND=JPRB)::ZDELTA
REAL (KIND=JPRB)::ZSCALE
REAL (KIND=JPRB)::ZEPSQ
REAL (KIND=JPRB)::ZEPS
REAL (KIND=JPRB)::ZZVISI


YLSTACK = YDSTACK



IF (KIND (ZRHOAIR) == 8) THEN
    fxtran_acdc_alloc8 (ZRHOAIR)
ELSEIF (KIND (ZRHOAIR) == 4) THEN
    fxtran_acdc_alloc4 (ZRHOAIR)
ELSE
    STOP 1
ENDIF


JLON = KIDIA



ZCONTRAST=-LOG (0.05_JPRB)
ZBETARAYL=0.013_JPRB
ZEPS=EPSILON (1._JPRB)*100._JPRB
ZEPSQ=1.E-6_JPRB
ZSCALE=1.E+3_JPRB
ILEV =1

DO JLEV=KLEV, 1,-1
  
  ZZVISI=PAPHIF (JLON, JLEV)-PAPHI (JLON, KLEV)-YDVISI%HVISI*YDCST%RG
  ILEVH=MAX (0._JPRB, SIGN (1._JPRB, ZZVISI))*JLEV
  ILEV =MAX (ILEVH, ILEV )
  ZRHOAIR (JLON, JLEV)=PAPRSF (JLON, JLEV)/(PR (JLON, JLEV)*PT (JLON, JLEV))
  
ENDDO


ILEVH=ILEV 
ILEVB=MIN (ILEV +1, KLEV)
ZDELTA=(PAPHIF (JLON, ILEVH)-YDVISI%HVISI*YDCST%RG-PAPHI (JLON, KLEV&
&))/MAX (ZEPS,(PAPHIF (JLON, ILEVH)-PAPHIF (JLON, ILEVB)))

IF (ILEVH==ILEVB)  THEN
  ZDELTA=1._JPRB
ENDIF

ZLCONTENT =MAX (ZEPSQ, ZSCALE*(PQL (JLON, ILEVB)*ZRHOAIR (JLON, ILEVB&
&)*ZDELTA+PQL (JLON, ILEVH)*ZRHOAIR (JLON, ILEVH)*(1-ZDELTA)))
ZICONTENT =MAX (ZEPSQ, ZSCALE*(PQI (JLON, ILEVB)*ZRHOAIR (JLON, ILEVB&
&)*ZDELTA+PQI (JLON, ILEVH)*ZRHOAIR (JLON, ILEVH)*(1-ZDELTA)))
ZRCONTENT =MAX (ZEPSQ, ZSCALE*(PQR (JLON, ILEVB)*ZRHOAIR (JLON, ILEVB&
&)*ZDELTA+PQR (JLON, ILEVH)*ZRHOAIR (JLON, ILEVH)*(1-ZDELTA)))
ZSCONTENT =MAX (ZEPSQ, ZSCALE*(PQS (JLON, ILEVB)*ZRHOAIR (JLON, ILEVB&
&)*ZDELTA+PQS (JLON, ILEVH)*ZRHOAIR (JLON, ILEVH)*(1-ZDELTA)))
ZGCONTENT =MAX (ZEPSQ, ZSCALE*(PQG (JLON, ILEVB)*ZRHOAIR (JLON, ILEVB&
&)*ZDELTA+PQG (JLON, ILEVH)*ZRHOAIR (JLON, ILEVH)*(1-ZDELTA)))
PMXCLWC (JLON)=PQL (JLON, ILEVB)*ZRHOAIR (JLON, ILEVB)*ZDELTA&
&+PQL (JLON, ILEVH)*ZRHOAIR (JLON, ILEVH)*(1-ZDELTA)


ZC1 =ZSCALE*EXP (YDVISI%COEF_CM2*((LOG (ZLCONTENT ))**2))
ZC2 =EXP (YDVISI%COEF_CM3*((LOG (ZLCONTENT ))**3))
PVISICLD (JLON)=ZCONTRAST/(YDVISI%COEF_CM1*ZC1 *ZC2 *((ZLCONTENT *&
&*YDVISI%COEF_CM4))+YDVISI%COEF_IM1*ZICONTENT **YDVISI%COEF_IM2)
PVISICLD (JLON)=ZSCALE*MIN (PVISICLD (JLON), 20.0_JPRB)
PVISIHYD (JLON)=ZCONTRAST/(ZBETARAYL+YDVISI%COEF_RM1*ZRCONTENT **YDVISI%COEF_RM2+YDVISI&
&%COEF_SM1*ZSCONTENT **YDVISI%COEF_SM2+YDVISI%COEF_GM1*ZGCONTENT **YDVISI%COEF_GM2)
PVISIHYD (JLON)=ZSCALE*MIN (PVISIHYD (JLON), 20.0_JPRB)



END SUBROUTINE ACVISIH_OPENACC
