SUBROUTINE APL_ARPEGE_HYDRO_BUDGET_PARALLEL (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_GPAR&
&, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, YD_PC3, YD_PCN, YD_PDSA_C1, YD_PDSA_C2, YD_PFLU_FEVI, YD_PFLU_NEIJ&
&, YD_PFLU_VEG, YD_PFPLSL, YD_PFPLSN, YD_PWFC, YD_PWLMX, YD_PWPMX, YD_PWSEQ, YD_PWSMX)
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_GPAR_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE SURFACE_FIELDS_MIX,ONLY:TSURF
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE PARKIND1
USE FXTRAN_ACDC_ARRAY_COPY_MOD
USE FXTRAN_ACDC_GPUMEM_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE


TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_GPAR_TYPE), INTENT (INOUT)::YDCPG_GPAR
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
CLASS (FIELD_2RB), POINTER :: YD_PC3
REAL (KIND=JPRB), POINTER::PC3 (:,:)
CLASS (FIELD_2RB), POINTER :: YD_PCN
REAL (KIND=JPRB), POINTER::PCN (:,:)
CLASS (FIELD_2RB), POINTER :: YD_PDSA_C1
REAL (KIND=JPRB), POINTER::PDSA_C1 (:,:)
CLASS (FIELD_2RB), POINTER :: YD_PDSA_C2
REAL (KIND=JPRB), POINTER::PDSA_C2 (:,:)
CLASS (FIELD_3RB), POINTER :: YD_PFLU_FEVI
REAL (KIND=JPRB), POINTER::PFLU_FEVI (:,:,:)
CLASS (FIELD_2RB), POINTER :: YD_PFLU_NEIJ
REAL (KIND=JPRB), POINTER::PFLU_NEIJ (:,:)
CLASS (FIELD_2RB), POINTER :: YD_PFLU_VEG
REAL (KIND=JPRB), POINTER::PFLU_VEG (:,:)
CLASS (FIELD_3RB), POINTER :: YD_PFPLSL
REAL (KIND=JPRB), POINTER::PFPLSL (:,:,:)
CLASS (FIELD_3RB), POINTER :: YD_PFPLSN
REAL (KIND=JPRB), POINTER::PFPLSN (:,:,:)
CLASS (FIELD_2RB), POINTER :: YD_PWFC
REAL (KIND=JPRB), POINTER::PWFC (:,:)
CLASS (FIELD_2RB), POINTER :: YD_PWLMX
REAL (KIND=JPRB), POINTER::PWLMX (:,:)
CLASS (FIELD_2RB), POINTER :: YD_PWPMX
REAL (KIND=JPRB), POINTER::PWPMX (:,:)
CLASS (FIELD_2RB), POINTER :: YD_PWSEQ
REAL (KIND=JPRB), POINTER::PWSEQ (:,:)
CLASS (FIELD_2RB), POINTER :: YD_PWSMX
REAL (KIND=JPRB), POINTER::PWSMX (:,:)
#include "acdrov.intfb.h"
#include "abor1.intfb.h"
#include "acdrov_openacc.intfb.h"
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
INTEGER(KIND=JPIM) :: JBLK
TYPE(CPG_BNDS_TYPE) :: YLCPG_BNDS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_FIELD_API
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_PARALLEL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_COMPUTE
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLOFFSET
REAL (KIND=JPRB), POINTER :: Z_YDCPG_GPAR_RAIN(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDCPG_GPAR_SNOW(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_CT(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FCHSP(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FCLL(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FCLN(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FCS(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FEVL(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FEVN(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FEVV(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FGEL(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FGELS(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FLWSP(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FONTE(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FPLCL(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FPLCN(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FRSO(:,:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FRTH(:,:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FTR(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_RUISL(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_RUISP(:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_RUISS(:,:)
REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VF_PLSM(:,:)
REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VV_PD2(:,:)
REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VV_PLAI(:,:)
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL', 0, ZHOOK_HANDLE)

CALL FXTRAN_ACDC_GPUMEMSTAT (FXTRAN_FILE, FXTRAN_LINE, "BEGIN")


IF (LHOOK) CALL DR_HOOK ('CREATE_TEMPORARIES',0,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('CREATE_TEMPORARIES',1,ZHOOK_HANDLE_FIELD_API)



IF (YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) THEN
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE',0,ZHOOK_HANDLE_PARALLEL)

  IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE')) THEN
    
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
    CALL SGET_HOST_DATA_RDONLY (PFPLSL, YD_PFPLSL)
    CALL SGET_HOST_DATA_RDONLY (PFPLSN, YD_PFPLSN)
    CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_RAIN, YDCPG_GPAR%F_RAIN)
    CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_SNOW, YDCPG_GPAR%F_SNOW)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
    CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
    !$OMP PARALLEL DO PRIVATE (JBLK, JLON) FIRSTPRIVATE (YLCPG_BNDS)

    DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
      CALL YLCPG_BNDS%UPDATE (JBLK)

      

      DO JLON=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA
        Z_YDCPG_GPAR_RAIN (JLON, JBLK)=PFPLSL (JLON, YDCPG_OPTS%KFLEVG,&
        & JBLK)+Z_YDMF_PHYS_OUT_FPLCL (JLON, YDCPG_OPTS%KFLEVG, JBLK)
        Z_YDCPG_GPAR_SNOW (JLON, JBLK)=PFPLSN (JLON, YDCPG_OPTS%KFLEVG,&
        & JBLK)+Z_YDMF_PHYS_OUT_FPLCN (JLON, YDCPG_OPTS%KFLEVG, JBLK)
      ENDDO

    ENDDO

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

    IF (FXTRAN_ACDC_LSYNCHOST ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE')) THEN
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
      CALL SGET_HOST_DATA_RDWR (PFPLSL, YD_PFPLSL)
      CALL SGET_HOST_DATA_RDWR (PFPLSN, YD_PFPLSN)
      CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_RAIN, YDCPG_GPAR%F_RAIN)
      CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_SNOW, YDCPG_GPAR%F_SNOW)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
    PFPLSL => NULL ()
    PFPLSN => NULL ()
    Z_YDCPG_GPAR_RAIN => NULL ()
    Z_YDCPG_GPAR_SNOW => NULL ()
    Z_YDMF_PHYS_OUT_FPLCL => NULL ()
    Z_YDMF_PHYS_OUT_FPLCN => NULL ()
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN&
    &','APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE')) THEN
    
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
    CALL SGET_HOST_DATA_RDONLY (PFPLSL, YD_PFPLSL)
    CALL SGET_HOST_DATA_RDONLY (PFPLSN, YD_PFPLSN)
    CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_RAIN, YDCPG_GPAR%F_RAIN)
    CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_SNOW, YDCPG_GPAR%F_SNOW)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
    !$OMP PARALLEL DO PRIVATE (JBLK, JLON, YLCPG_BNDS)

    DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

      

      

      DO JLON = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JLON
        YLCPG_BNDS%KFDIA = JLON
        
        
        Z_YDCPG_GPAR_RAIN (JLON, JBLK)=PFPLSL (JLON, YDCPG_OPTS%KFLEVG,&
        & JBLK)+Z_YDMF_PHYS_OUT_FPLCL (JLON, YDCPG_OPTS%KFLEVG, JBLK)
        Z_YDCPG_GPAR_SNOW (JLON, JBLK)=PFPLSN (JLON, YDCPG_OPTS%KFLEVG,&
        & JBLK)+Z_YDMF_PHYS_OUT_FPLCN (JLON, YDCPG_OPTS%KFLEVG, JBLK)
      
      ENDDO

    ENDDO

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

    IF (FXTRAN_ACDC_LSYNCHOST ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE')) THEN
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
      CALL SGET_HOST_DATA_RDWR (PFPLSL, YD_PFPLSL)
      CALL SGET_HOST_DATA_RDWR (PFPLSN, YD_PFPLSN)
      CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_RAIN, YDCPG_GPAR%F_RAIN)
      CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_SNOW, YDCPG_GPAR%F_SNOW)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
    PFPLSL => NULL ()
    PFPLSN => NULL ()
    Z_YDCPG_GPAR_RAIN => NULL ()
    Z_YDCPG_GPAR_SNOW => NULL ()
    Z_YDMF_PHYS_OUT_FPLCL => NULL ()
    Z_YDMF_PHYS_OUT_FPLCN => NULL ()
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN&
    &','APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE')) THEN
    
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
    CALL SGET_HOST_DATA_RDONLY (PFPLSL, YD_PFPLSL)
    CALL SGET_HOST_DATA_RDONLY (PFPLSN, YD_PFPLSN)
    CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_RAIN, YDCPG_GPAR%F_RAIN)
    CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_SNOW, YDCPG_GPAR%F_SNOW)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
    
    !$ACC PARALLEL LOOP GANG  & 
    !$ACC & PRESENT (PFPLSL, PFPLSN, YDCPG_OPTS, YFXTRAN_ACDC_STACK, Z_YDCPG_GPAR_RAIN,  & 
    !$ACC &          Z_YDCPG_GPAR_SNOW, Z_YDMF_PHYS_OUT_FPLCL, Z_YDMF_PHYS_OUT_FPLCN)  & 
    !$ACC & PRIVATE (JBLK)  & 
    !$ACC & VECTOR_LENGTH (YDCPG_OPTS%KLON)       

    DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
      
      
      
      !$ACC LOOP VECTOR  & 
      !$ACC & PRIVATE (JLON, YLCPG_BNDS)       

      DO JLON = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JLON
        YLCPG_BNDS%KFDIA = JLON
        
        
        Z_YDCPG_GPAR_RAIN (JLON, JBLK)=PFPLSL (JLON, YDCPG_OPTS%KFLEVG,&
        & JBLK)+Z_YDMF_PHYS_OUT_FPLCL (JLON, YDCPG_OPTS%KFLEVG, JBLK)
        Z_YDCPG_GPAR_SNOW (JLON, JBLK)=PFPLSN (JLON, YDCPG_OPTS%KFLEVG,&
        & JBLK)+Z_YDMF_PHYS_OUT_FPLCN (JLON, YDCPG_OPTS%KFLEVG, JBLK)
      
      ENDDO

    ENDDO

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

    IF (FXTRAN_ACDC_LSYNCHOST ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE')) THEN
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
      CALL SGET_HOST_DATA_RDWR (PFPLSL, YD_PFPLSL)
      CALL SGET_HOST_DATA_RDWR (PFPLSN, YD_PFPLSN)
      CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_RAIN, YDCPG_GPAR%F_RAIN)
      CALL SGET_HOST_DATA_RDWR (Z_YDCPG_GPAR_SNOW, YDCPG_GPAR%F_SNOW)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
    PFPLSL => NULL ()
    PFPLSN => NULL ()
    Z_YDCPG_GPAR_RAIN => NULL ()
    Z_YDCPG_GPAR_SNOW => NULL ()
    Z_YDMF_PHYS_OUT_FPLCL => NULL ()
    Z_YDMF_PHYS_OUT_FPLCN => NULL ()
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ELSE
      CALL ABOR1 ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL: NOT METHOD WAS FOUND')
  ENDIF

  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:LMSE',1,ZHOOK_HANDLE_PARALLEL)
ELSEIF (YDMODEL%YRML_PHY_MF%YRPHY%LSOLV) THEN
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV',0,ZHOOK_HANDLE_PARALLEL)

  IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV')) THEN
    
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
    &:ACDROV:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
    CALL SGET_HOST_DATA_RDONLY (PC3, YD_PC3)
    CALL SGET_HOST_DATA_RDONLY (PCN, YD_PCN)
    CALL SGET_HOST_DATA_RDONLY (PDSA_C1, YD_PDSA_C1)
    CALL SGET_HOST_DATA_RDONLY (PDSA_C2, YD_PDSA_C2)
    CALL SGET_HOST_DATA_RDONLY (PFLU_FEVI, YD_PFLU_FEVI)
    CALL SGET_HOST_DATA_RDONLY (PFLU_NEIJ, YD_PFLU_NEIJ)
    CALL SGET_HOST_DATA_RDONLY (PFLU_VEG, YD_PFLU_VEG)
    CALL SGET_HOST_DATA_RDONLY (PFPLSL, YD_PFPLSL)
    CALL SGET_HOST_DATA_RDONLY (PFPLSN, YD_PFPLSN)
    CALL SGET_HOST_DATA_RDONLY (PWFC, YD_PWFC)
    CALL SGET_HOST_DATA_RDONLY (PWLMX, YD_PWLMX)
    CALL SGET_HOST_DATA_RDONLY (PWPMX, YD_PWPMX)
    CALL SGET_HOST_DATA_RDONLY (PWSEQ, YD_PWSEQ)
    CALL SGET_HOST_DATA_RDONLY (PWSMX, YD_PWSMX)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_FC)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_IC)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T, YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W, YDMF_PHYS_BASE_STATE%YGSP_RR%F_W)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q, YDMF_PHYS_BASE_STATE%YGSP_SB%F_Q)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T, YDMF_PHYS_BASE_STATE%YGSP_SB%F_T)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL, YDMF_PHYS_BASE_STATE%YGSP_SB%F_TL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F, YDMF_PHYS_BASE_STATE%YGSP_SG%F_F)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_CT, YDMF_PHYS%OUT%F_CT)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCHSP, YDMF_PHYS%OUT%F_FCHSP)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCLL, YDMF_PHYS%OUT%F_FCLL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCLN, YDMF_PHYS%OUT%F_FCLN)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCS, YDMF_PHYS%OUT%F_FCS)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FEVL, YDMF_PHYS%OUT%F_FEVL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FEVN, YDMF_PHYS%OUT%F_FEVN)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FEVV, YDMF_PHYS%OUT%F_FEVV)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGEL, YDMF_PHYS%OUT%F_FGEL)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGELS, YDMF_PHYS%OUT%F_FGELS)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FLWSP, YDMF_PHYS%OUT%F_FLWSP)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FONTE, YDMF_PHYS%OUT%F_FONTE)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FRSO, YDMF_PHYS%OUT%F_FRSO)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FRTH, YDMF_PHYS%OUT%F_FRTH)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FTR, YDMF_PHYS%OUT%F_FTR)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISL, YDMF_PHYS%OUT%F_RUISL)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISP, YDMF_PHYS%OUT%F_RUISP)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISS, YDMF_PHYS%OUT%F_RUISS)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_SURF_GSD_VF_PLSM, YDMF_PHYS_SURF%GSD_VF%F_LSM)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_SURF_GSD_VV_PD2, YDMF_PHYS_SURF%GSD_VV%F_D2)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_SURF_GSD_VV_PLAI, YDMF_PHYS_SURF%GSD_VV%F_LAI)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
    &:ACDROV:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
    CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
    !$OMP PARALLEL DO PRIVATE (JBLK) FIRSTPRIVATE (YLCPG_BNDS)

    DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
      CALL YLCPG_BNDS%UPDATE (JBLK)
      
      CALL ACDROV (YDMODEL%YRCST, YDMODEL%YRML_PHY_MF, YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA, YDCPG_OPTS%KLON&
      &, YDCPG_OPTS%KFLEVG, YDCPG_OPTS%YRSURF_DIMS%YSP_SBD%NLEVS, Z_YDMF_PHYS_OUT_FPLCL(:,:, JBLK), Z_YDMF_PHYS_OUT_FPLCN&
      &(:,:, JBLK), PFPLSL(:,:, JBLK), PFPLSN(:,:, JBLK), Z_YDMF_PHYS_OUT_FRSO(:,:,:, JBLK), Z_YDMF_PHYS_OUT_FRTH&
      &(:,:,:, JBLK), PDSA_C1(:, JBLK), PDSA_C2(:, JBLK), PC3(:, JBLK), PCN(:, JBLK), Z_YDMF_PHYS_OUT_CT&
      &(:, JBLK), Z_YDMF_PHYS_SURF_GSD_VV_PD2(:, JBLK), Z_YDMF_PHYS_OUT_FEVV(:, JBLK), Z_YDMF_PHYS_OUT_FTR&
      &(:, JBLK), Z_YDMF_PHYS_SURF_GSD_VV_PLAI(:, JBLK), PFLU_NEIJ(:, JBLK), PFLU_VEG(:, JBLK), PWFC(:, JBLK&
      &), PWPMX(:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC(:, JBLK), PWLMX(:, JBLK), PWSEQ(:, JBLK), PWSMX&
      &(:, JBLK), Z_YDMF_PHYS_OUT_FCHSP (:, 1, JBLK), Z_YDMF_PHYS_OUT_FCLL (:, 1, JBLK), Z_YDMF_PHYS_OUT_FCLN&
      & (:, 1, JBLK), Z_YDMF_PHYS_OUT_FCS (:, 1, JBLK), PFLU_FEVI (:, 1, JBLK), Z_YDMF_PHYS_OUT_FEVL (:,&
      & 1, JBLK), Z_YDMF_PHYS_OUT_FEVN (:, 1, JBLK), Z_YDMF_PHYS_SURF_GSD_VF_PLSM(:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F&
      & (:, 1, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T(:,:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:, JBLK&
      &), Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q (:, 1, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL (:, 1, JBLK),&
      & Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W(:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC(:, JBLK), Z_YDMF_PHYS_OUT_FGEL&
      &(:, JBLK), Z_YDMF_PHYS_OUT_FGELS(:, JBLK), Z_YDMF_PHYS_OUT_FLWSP(:, JBLK), Z_YDMF_PHYS_OUT_FONTE(&
      &:, JBLK), Z_YDMF_PHYS_OUT_RUISP(:, JBLK), Z_YDMF_PHYS_OUT_RUISL(:, JBLK), Z_YDMF_PHYS_OUT_RUISS(:&
      &, JBLK))
    ENDDO

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

    IF (FXTRAN_ACDC_LSYNCHOST ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV')) THEN
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
      &:ACDROV:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
      CALL SGET_HOST_DATA_RDWR (PC3, YD_PC3)
      CALL SGET_HOST_DATA_RDWR (PCN, YD_PCN)
      CALL SGET_HOST_DATA_RDWR (PDSA_C1, YD_PDSA_C1)
      CALL SGET_HOST_DATA_RDWR (PDSA_C2, YD_PDSA_C2)
      CALL SGET_HOST_DATA_RDWR (PFLU_FEVI, YD_PFLU_FEVI)
      CALL SGET_HOST_DATA_RDWR (PFLU_NEIJ, YD_PFLU_NEIJ)
      CALL SGET_HOST_DATA_RDWR (PFLU_VEG, YD_PFLU_VEG)
      CALL SGET_HOST_DATA_RDWR (PFPLSL, YD_PFPLSL)
      CALL SGET_HOST_DATA_RDWR (PFPLSN, YD_PFPLSN)
      CALL SGET_HOST_DATA_RDWR (PWFC, YD_PWFC)
      CALL SGET_HOST_DATA_RDWR (PWLMX, YD_PWLMX)
      CALL SGET_HOST_DATA_RDWR (PWPMX, YD_PWPMX)
      CALL SGET_HOST_DATA_RDWR (PWSEQ, YD_PWSEQ)
      CALL SGET_HOST_DATA_RDWR (PWSMX, YD_PWSMX)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_FC)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_IC)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T, YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W, YDMF_PHYS_BASE_STATE%YGSP_RR%F_W)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q, YDMF_PHYS_BASE_STATE%YGSP_SB%F_Q)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T, YDMF_PHYS_BASE_STATE%YGSP_SB%F_T)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL, YDMF_PHYS_BASE_STATE%YGSP_SB%F_TL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F, YDMF_PHYS_BASE_STATE%YGSP_SG%F_F)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_CT, YDMF_PHYS%OUT%F_CT)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCHSP, YDMF_PHYS%OUT%F_FCHSP)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCLL, YDMF_PHYS%OUT%F_FCLL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCLN, YDMF_PHYS%OUT%F_FCLN)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCS, YDMF_PHYS%OUT%F_FCS)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FEVL, YDMF_PHYS%OUT%F_FEVL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FEVN, YDMF_PHYS%OUT%F_FEVN)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FEVV, YDMF_PHYS%OUT%F_FEVV)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGEL, YDMF_PHYS%OUT%F_FGEL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGELS, YDMF_PHYS%OUT%F_FGELS)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FLWSP, YDMF_PHYS%OUT%F_FLWSP)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FONTE, YDMF_PHYS%OUT%F_FONTE)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FRSO, YDMF_PHYS%OUT%F_FRSO)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FRTH, YDMF_PHYS%OUT%F_FRTH)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FTR, YDMF_PHYS%OUT%F_FTR)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISL, YDMF_PHYS%OUT%F_RUISL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISP, YDMF_PHYS%OUT%F_RUISP)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISS, YDMF_PHYS%OUT%F_RUISS)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_SURF_GSD_VF_PLSM, YDMF_PHYS_SURF%GSD_VF%F_LSM)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_SURF_GSD_VV_PD2, YDMF_PHYS_SURF%GSD_VV%F_D2)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_SURF_GSD_VV_PLAI, YDMF_PHYS_SURF%GSD_VV%F_LAI)
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
      &:ACDROV:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
    PC3 => NULL ()
    PCN => NULL ()
    PDSA_C1 => NULL ()
    PDSA_C2 => NULL ()
    PFLU_FEVI => NULL ()
    PFLU_NEIJ => NULL ()
    PFLU_VEG => NULL ()
    PFPLSL => NULL ()
    PFPLSN => NULL ()
    PWFC => NULL ()
    PWLMX => NULL ()
    PWPMX => NULL ()
    PWSEQ => NULL ()
    PWSMX => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F => NULL ()
    Z_YDMF_PHYS_OUT_CT => NULL ()
    Z_YDMF_PHYS_OUT_FCHSP => NULL ()
    Z_YDMF_PHYS_OUT_FCLL => NULL ()
    Z_YDMF_PHYS_OUT_FCLN => NULL ()
    Z_YDMF_PHYS_OUT_FCS => NULL ()
    Z_YDMF_PHYS_OUT_FEVL => NULL ()
    Z_YDMF_PHYS_OUT_FEVN => NULL ()
    Z_YDMF_PHYS_OUT_FEVV => NULL ()
    Z_YDMF_PHYS_OUT_FGEL => NULL ()
    Z_YDMF_PHYS_OUT_FGELS => NULL ()
    Z_YDMF_PHYS_OUT_FLWSP => NULL ()
    Z_YDMF_PHYS_OUT_FONTE => NULL ()
    Z_YDMF_PHYS_OUT_FPLCL => NULL ()
    Z_YDMF_PHYS_OUT_FPLCN => NULL ()
    Z_YDMF_PHYS_OUT_FRSO => NULL ()
    Z_YDMF_PHYS_OUT_FRTH => NULL ()
    Z_YDMF_PHYS_OUT_FTR => NULL ()
    Z_YDMF_PHYS_OUT_RUISL => NULL ()
    Z_YDMF_PHYS_OUT_RUISP => NULL ()
    Z_YDMF_PHYS_OUT_RUISS => NULL ()
    Z_YDMF_PHYS_SURF_GSD_VF_PLSM => NULL ()
    Z_YDMF_PHYS_SURF_GSD_VV_PD2 => NULL ()
    Z_YDMF_PHYS_SURF_GSD_VV_PLAI => NULL ()
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN&
    &','APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV')) THEN
    
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
    &:ACDROV:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
    CALL SGET_HOST_DATA_RDONLY (PC3, YD_PC3)
    CALL SGET_HOST_DATA_RDONLY (PCN, YD_PCN)
    CALL SGET_HOST_DATA_RDONLY (PDSA_C1, YD_PDSA_C1)
    CALL SGET_HOST_DATA_RDONLY (PDSA_C2, YD_PDSA_C2)
    CALL SGET_HOST_DATA_RDONLY (PFLU_FEVI, YD_PFLU_FEVI)
    CALL SGET_HOST_DATA_RDONLY (PFLU_NEIJ, YD_PFLU_NEIJ)
    CALL SGET_HOST_DATA_RDONLY (PFLU_VEG, YD_PFLU_VEG)
    CALL SGET_HOST_DATA_RDONLY (PFPLSL, YD_PFPLSL)
    CALL SGET_HOST_DATA_RDONLY (PFPLSN, YD_PFPLSN)
    CALL SGET_HOST_DATA_RDONLY (PWFC, YD_PWFC)
    CALL SGET_HOST_DATA_RDONLY (PWLMX, YD_PWLMX)
    CALL SGET_HOST_DATA_RDONLY (PWPMX, YD_PWPMX)
    CALL SGET_HOST_DATA_RDONLY (PWSEQ, YD_PWSEQ)
    CALL SGET_HOST_DATA_RDONLY (PWSMX, YD_PWSMX)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_FC)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_IC)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T, YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W, YDMF_PHYS_BASE_STATE%YGSP_RR%F_W)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q, YDMF_PHYS_BASE_STATE%YGSP_SB%F_Q)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T, YDMF_PHYS_BASE_STATE%YGSP_SB%F_T)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL, YDMF_PHYS_BASE_STATE%YGSP_SB%F_TL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F, YDMF_PHYS_BASE_STATE%YGSP_SG%F_F)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_CT, YDMF_PHYS%OUT%F_CT)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCHSP, YDMF_PHYS%OUT%F_FCHSP)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCLL, YDMF_PHYS%OUT%F_FCLL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCLN, YDMF_PHYS%OUT%F_FCLN)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCS, YDMF_PHYS%OUT%F_FCS)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FEVL, YDMF_PHYS%OUT%F_FEVL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FEVN, YDMF_PHYS%OUT%F_FEVN)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FEVV, YDMF_PHYS%OUT%F_FEVV)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGEL, YDMF_PHYS%OUT%F_FGEL)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGELS, YDMF_PHYS%OUT%F_FGELS)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FLWSP, YDMF_PHYS%OUT%F_FLWSP)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FONTE, YDMF_PHYS%OUT%F_FONTE)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FRSO, YDMF_PHYS%OUT%F_FRSO)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FRTH, YDMF_PHYS%OUT%F_FRTH)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FTR, YDMF_PHYS%OUT%F_FTR)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISL, YDMF_PHYS%OUT%F_RUISL)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISP, YDMF_PHYS%OUT%F_RUISP)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISS, YDMF_PHYS%OUT%F_RUISS)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_SURF_GSD_VF_PLSM, YDMF_PHYS_SURF%GSD_VF%F_LSM)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_SURF_GSD_VV_PD2, YDMF_PHYS_SURF%GSD_VV%F_D2)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_SURF_GSD_VV_PLAI, YDMF_PHYS_SURF%GSD_VV%F_LAI)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
    &:ACDROV:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
    !$OMP PARALLEL DO PRIVATE (JBLK, JLON, YLCPG_BNDS, YLSTACK)

    DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

      

      

      DO JLON = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JLON
        YLCPG_BNDS%KFDIA = JLON
        YLSTACK%L8 = fxtran_acdc_stack_l8 (YFXTRAN_ACDC_STACK, (JBLK-YDCPG_OPTS%JBLKMIN)+1, YDCPG_OPTS%KGPBLKS)
        YLSTACK%U8 = fxtran_acdc_stack_u8 (YFXTRAN_ACDC_STACK, (JBLK-YDCPG_OPTS%JBLKMIN)+1, YDCPG_OPTS%KGPBLKS)
        YLSTACK%L4 = fxtran_acdc_stack_l4 (YFXTRAN_ACDC_STACK, (JBLK-YDCPG_OPTS%JBLKMIN)+1, YDCPG_OPTS%KGPBLKS)
        YLSTACK%U4 = fxtran_acdc_stack_u4 (YFXTRAN_ACDC_STACK, (JBLK-YDCPG_OPTS%JBLKMIN)+1, YDCPG_OPTS%KGPBLKS)
        
        CALL ACDROV_OPENACC (YDMODEL%YRCST, YDMODEL%YRML_PHY_MF, YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA, YDCPG_OPTS&
        &%KLON, YDCPG_OPTS%KFLEVG, YDCPG_OPTS%YRSURF_DIMS%YSP_SBD%NLEVS, Z_YDMF_PHYS_OUT_FPLCL(:,:, JBLK), Z_YDMF_PHYS_OUT_FPLCN&
        &(:,:, JBLK), PFPLSL(:,:, JBLK), PFPLSN(:,:, JBLK), Z_YDMF_PHYS_OUT_FRSO(:,:,:, JBLK), Z_YDMF_PHYS_OUT_FRTH&
        &(:,:,:, JBLK), PDSA_C1(:, JBLK), PDSA_C2(:, JBLK), PC3(:, JBLK), PCN(:, JBLK), Z_YDMF_PHYS_OUT_CT(&
        &:, JBLK), Z_YDMF_PHYS_SURF_GSD_VV_PD2(:, JBLK), Z_YDMF_PHYS_OUT_FEVV(:, JBLK), Z_YDMF_PHYS_OUT_FTR&
        &(:, JBLK), Z_YDMF_PHYS_SURF_GSD_VV_PLAI(:, JBLK), PFLU_NEIJ(:, JBLK), PFLU_VEG(:, JBLK), PWFC(:, JBLK&
        &), PWPMX(:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC(:, JBLK), PWLMX(:, JBLK), PWSEQ(:, JBLK), PWSMX&
        &(:, JBLK), Z_YDMF_PHYS_OUT_FCHSP (:, 1, JBLK), Z_YDMF_PHYS_OUT_FCLL (:, 1, JBLK), Z_YDMF_PHYS_OUT_FCLN&
        & (:, 1, JBLK), Z_YDMF_PHYS_OUT_FCS (:, 1, JBLK), PFLU_FEVI (:, 1, JBLK), Z_YDMF_PHYS_OUT_FEVL (:, 1&
        &, JBLK), Z_YDMF_PHYS_OUT_FEVN (:, 1, JBLK), Z_YDMF_PHYS_SURF_GSD_VF_PLSM(:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F&
        & (:, 1, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T(:,:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:, JBLK&
        &), Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q (:, 1, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL (:, 1, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W&
        &(:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC(:, JBLK), Z_YDMF_PHYS_OUT_FGEL(:, JBLK), Z_YDMF_PHYS_OUT_FGELS&
        &(:, JBLK), Z_YDMF_PHYS_OUT_FLWSP(:, JBLK), Z_YDMF_PHYS_OUT_FONTE(:, JBLK), Z_YDMF_PHYS_OUT_RUISP(:&
        &, JBLK), Z_YDMF_PHYS_OUT_RUISL(:, JBLK), Z_YDMF_PHYS_OUT_RUISS(:, JBLK),YDSTACK=YLSTACK)
      ENDDO

    ENDDO

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

    IF (FXTRAN_ACDC_LSYNCHOST ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV')) THEN
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
      &:ACDROV:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
      CALL SGET_HOST_DATA_RDWR (PC3, YD_PC3)
      CALL SGET_HOST_DATA_RDWR (PCN, YD_PCN)
      CALL SGET_HOST_DATA_RDWR (PDSA_C1, YD_PDSA_C1)
      CALL SGET_HOST_DATA_RDWR (PDSA_C2, YD_PDSA_C2)
      CALL SGET_HOST_DATA_RDWR (PFLU_FEVI, YD_PFLU_FEVI)
      CALL SGET_HOST_DATA_RDWR (PFLU_NEIJ, YD_PFLU_NEIJ)
      CALL SGET_HOST_DATA_RDWR (PFLU_VEG, YD_PFLU_VEG)
      CALL SGET_HOST_DATA_RDWR (PFPLSL, YD_PFPLSL)
      CALL SGET_HOST_DATA_RDWR (PFPLSN, YD_PFPLSN)
      CALL SGET_HOST_DATA_RDWR (PWFC, YD_PWFC)
      CALL SGET_HOST_DATA_RDWR (PWLMX, YD_PWLMX)
      CALL SGET_HOST_DATA_RDWR (PWPMX, YD_PWPMX)
      CALL SGET_HOST_DATA_RDWR (PWSEQ, YD_PWSEQ)
      CALL SGET_HOST_DATA_RDWR (PWSMX, YD_PWSMX)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_FC)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_IC)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T, YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W, YDMF_PHYS_BASE_STATE%YGSP_RR%F_W)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q, YDMF_PHYS_BASE_STATE%YGSP_SB%F_Q)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T, YDMF_PHYS_BASE_STATE%YGSP_SB%F_T)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL, YDMF_PHYS_BASE_STATE%YGSP_SB%F_TL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F, YDMF_PHYS_BASE_STATE%YGSP_SG%F_F)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_CT, YDMF_PHYS%OUT%F_CT)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCHSP, YDMF_PHYS%OUT%F_FCHSP)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCLL, YDMF_PHYS%OUT%F_FCLL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCLN, YDMF_PHYS%OUT%F_FCLN)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCS, YDMF_PHYS%OUT%F_FCS)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FEVL, YDMF_PHYS%OUT%F_FEVL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FEVN, YDMF_PHYS%OUT%F_FEVN)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FEVV, YDMF_PHYS%OUT%F_FEVV)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGEL, YDMF_PHYS%OUT%F_FGEL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGELS, YDMF_PHYS%OUT%F_FGELS)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FLWSP, YDMF_PHYS%OUT%F_FLWSP)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FONTE, YDMF_PHYS%OUT%F_FONTE)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FRSO, YDMF_PHYS%OUT%F_FRSO)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FRTH, YDMF_PHYS%OUT%F_FRTH)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FTR, YDMF_PHYS%OUT%F_FTR)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISL, YDMF_PHYS%OUT%F_RUISL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISP, YDMF_PHYS%OUT%F_RUISP)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISS, YDMF_PHYS%OUT%F_RUISS)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_SURF_GSD_VF_PLSM, YDMF_PHYS_SURF%GSD_VF%F_LSM)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_SURF_GSD_VV_PD2, YDMF_PHYS_SURF%GSD_VV%F_D2)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_SURF_GSD_VV_PLAI, YDMF_PHYS_SURF%GSD_VV%F_LAI)
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
      &:ACDROV:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
    PC3 => NULL ()
    PCN => NULL ()
    PDSA_C1 => NULL ()
    PDSA_C2 => NULL ()
    PFLU_FEVI => NULL ()
    PFLU_NEIJ => NULL ()
    PFLU_VEG => NULL ()
    PFPLSL => NULL ()
    PFPLSN => NULL ()
    PWFC => NULL ()
    PWLMX => NULL ()
    PWPMX => NULL ()
    PWSEQ => NULL ()
    PWSMX => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F => NULL ()
    Z_YDMF_PHYS_OUT_CT => NULL ()
    Z_YDMF_PHYS_OUT_FCHSP => NULL ()
    Z_YDMF_PHYS_OUT_FCLL => NULL ()
    Z_YDMF_PHYS_OUT_FCLN => NULL ()
    Z_YDMF_PHYS_OUT_FCS => NULL ()
    Z_YDMF_PHYS_OUT_FEVL => NULL ()
    Z_YDMF_PHYS_OUT_FEVN => NULL ()
    Z_YDMF_PHYS_OUT_FEVV => NULL ()
    Z_YDMF_PHYS_OUT_FGEL => NULL ()
    Z_YDMF_PHYS_OUT_FGELS => NULL ()
    Z_YDMF_PHYS_OUT_FLWSP => NULL ()
    Z_YDMF_PHYS_OUT_FONTE => NULL ()
    Z_YDMF_PHYS_OUT_FPLCL => NULL ()
    Z_YDMF_PHYS_OUT_FPLCN => NULL ()
    Z_YDMF_PHYS_OUT_FRSO => NULL ()
    Z_YDMF_PHYS_OUT_FRTH => NULL ()
    Z_YDMF_PHYS_OUT_FTR => NULL ()
    Z_YDMF_PHYS_OUT_RUISL => NULL ()
    Z_YDMF_PHYS_OUT_RUISP => NULL ()
    Z_YDMF_PHYS_OUT_RUISS => NULL ()
    Z_YDMF_PHYS_SURF_GSD_VF_PLSM => NULL ()
    Z_YDMF_PHYS_SURF_GSD_VV_PD2 => NULL ()
    Z_YDMF_PHYS_SURF_GSD_VV_PLAI => NULL ()
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN&
    &','APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV')) THEN
    
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
    &:ACDROV:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
    CALL SGET_HOST_DATA_RDONLY (PC3, YD_PC3)
    CALL SGET_HOST_DATA_RDONLY (PCN, YD_PCN)
    CALL SGET_HOST_DATA_RDONLY (PDSA_C1, YD_PDSA_C1)
    CALL SGET_HOST_DATA_RDONLY (PDSA_C2, YD_PDSA_C2)
    CALL SGET_HOST_DATA_RDONLY (PFLU_FEVI, YD_PFLU_FEVI)
    CALL SGET_HOST_DATA_RDONLY (PFLU_NEIJ, YD_PFLU_NEIJ)
    CALL SGET_HOST_DATA_RDONLY (PFLU_VEG, YD_PFLU_VEG)
    CALL SGET_HOST_DATA_RDONLY (PFPLSL, YD_PFPLSL)
    CALL SGET_HOST_DATA_RDONLY (PFPLSN, YD_PFPLSN)
    CALL SGET_HOST_DATA_RDONLY (PWFC, YD_PWFC)
    CALL SGET_HOST_DATA_RDONLY (PWLMX, YD_PWLMX)
    CALL SGET_HOST_DATA_RDONLY (PWPMX, YD_PWPMX)
    CALL SGET_HOST_DATA_RDONLY (PWSEQ, YD_PWSEQ)
    CALL SGET_HOST_DATA_RDONLY (PWSMX, YD_PWSMX)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_FC)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_IC)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T, YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W, YDMF_PHYS_BASE_STATE%YGSP_RR%F_W)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q, YDMF_PHYS_BASE_STATE%YGSP_SB%F_Q)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T, YDMF_PHYS_BASE_STATE%YGSP_SB%F_T)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL, YDMF_PHYS_BASE_STATE%YGSP_SB%F_TL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F, YDMF_PHYS_BASE_STATE%YGSP_SG%F_F)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_CT, YDMF_PHYS%OUT%F_CT)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCHSP, YDMF_PHYS%OUT%F_FCHSP)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCLL, YDMF_PHYS%OUT%F_FCLL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCLN, YDMF_PHYS%OUT%F_FCLN)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FCS, YDMF_PHYS%OUT%F_FCS)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FEVL, YDMF_PHYS%OUT%F_FEVL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FEVN, YDMF_PHYS%OUT%F_FEVN)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FEVV, YDMF_PHYS%OUT%F_FEVV)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGEL, YDMF_PHYS%OUT%F_FGEL)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGELS, YDMF_PHYS%OUT%F_FGELS)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FLWSP, YDMF_PHYS%OUT%F_FLWSP)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FONTE, YDMF_PHYS%OUT%F_FONTE)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FRSO, YDMF_PHYS%OUT%F_FRSO)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FRTH, YDMF_PHYS%OUT%F_FRTH)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_OUT_FTR, YDMF_PHYS%OUT%F_FTR)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISL, YDMF_PHYS%OUT%F_RUISL)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISP, YDMF_PHYS%OUT%F_RUISP)
    CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISS, YDMF_PHYS%OUT%F_RUISS)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_SURF_GSD_VF_PLSM, YDMF_PHYS_SURF%GSD_VF%F_LSM)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_SURF_GSD_VV_PD2, YDMF_PHYS_SURF%GSD_VV%F_D2)
    CALL SGET_HOST_DATA_RDONLY (Z_YDMF_PHYS_SURF_GSD_VV_PLAI, YDMF_PHYS_SURF%GSD_VV%F_LAI)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
    &:ACDROV:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
    
    !$ACC PARALLEL LOOP GANG  & 
    !$ACC & PRESENT (PC3, PCN, PDSA_C1, PDSA_C2, PFLU_FEVI, PFLU_NEIJ, PFLU_VEG, PFPLSL,  & 
    !$ACC &          PFPLSN, PWFC, PWLMX, PWPMX, PWSEQ, PWSMX, YDCPG_OPTS, YDMODEL, YFXTRAN_ACDC_STACK,  & 
    !$ACC &          Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC, Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC,  & 
    !$ACC &          Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T, Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W,  & 
    !$ACC &          Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q, Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T,  & 
    !$ACC &          Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL, Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F,  & 
    !$ACC &          Z_YDMF_PHYS_OUT_CT, Z_YDMF_PHYS_OUT_FCHSP, Z_YDMF_PHYS_OUT_FCLL,  & 
    !$ACC &          Z_YDMF_PHYS_OUT_FCLN, Z_YDMF_PHYS_OUT_FCS, Z_YDMF_PHYS_OUT_FEVL,  & 
    !$ACC &          Z_YDMF_PHYS_OUT_FEVN, Z_YDMF_PHYS_OUT_FEVV, Z_YDMF_PHYS_OUT_FGEL,  & 
    !$ACC &          Z_YDMF_PHYS_OUT_FGELS, Z_YDMF_PHYS_OUT_FLWSP, Z_YDMF_PHYS_OUT_FONTE,  & 
    !$ACC &          Z_YDMF_PHYS_OUT_FPLCL, Z_YDMF_PHYS_OUT_FPLCN, Z_YDMF_PHYS_OUT_FRSO,  & 
    !$ACC &          Z_YDMF_PHYS_OUT_FRTH, Z_YDMF_PHYS_OUT_FTR, Z_YDMF_PHYS_OUT_RUISL,  & 
    !$ACC &          Z_YDMF_PHYS_OUT_RUISP, Z_YDMF_PHYS_OUT_RUISS, Z_YDMF_PHYS_SURF_GSD_VF_PLSM,  & 
    !$ACC &          Z_YDMF_PHYS_SURF_GSD_VV_PD2, Z_YDMF_PHYS_SURF_GSD_VV_PLAI)  & 
    !$ACC & PRIVATE (JBLK)  & 
    !$ACC & VECTOR_LENGTH (YDCPG_OPTS%KLON)       

    DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
      
      
      
      !$ACC LOOP VECTOR  & 
      !$ACC & PRIVATE (JLON, YLCPG_BNDS, YLSTACK)       

      DO JLON = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JLON
        YLCPG_BNDS%KFDIA = JLON
        YLSTACK%L8 = fxtran_acdc_stack_l8 (YFXTRAN_ACDC_STACK, (JBLK-YDCPG_OPTS%JBLKMIN)+1, YDCPG_OPTS%KGPBLKS)
        YLSTACK%U8 = fxtran_acdc_stack_u8 (YFXTRAN_ACDC_STACK, (JBLK-YDCPG_OPTS%JBLKMIN)+1, YDCPG_OPTS%KGPBLKS)
        YLSTACK%L4 = fxtran_acdc_stack_l4 (YFXTRAN_ACDC_STACK, (JBLK-YDCPG_OPTS%JBLKMIN)+1, YDCPG_OPTS%KGPBLKS)
        YLSTACK%U4 = fxtran_acdc_stack_u4 (YFXTRAN_ACDC_STACK, (JBLK-YDCPG_OPTS%JBLKMIN)+1, YDCPG_OPTS%KGPBLKS)
        
        CALL ACDROV_OPENACC (YDMODEL%YRCST, YDMODEL%YRML_PHY_MF, YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA, YDCPG_OPTS&
        &%KLON, YDCPG_OPTS%KFLEVG, YDCPG_OPTS%YRSURF_DIMS%YSP_SBD%NLEVS, Z_YDMF_PHYS_OUT_FPLCL(:,:, JBLK), Z_YDMF_PHYS_OUT_FPLCN&
        &(:,:, JBLK), PFPLSL(:,:, JBLK), PFPLSN(:,:, JBLK), Z_YDMF_PHYS_OUT_FRSO(:,:,:, JBLK), Z_YDMF_PHYS_OUT_FRTH&
        &(:,:,:, JBLK), PDSA_C1(:, JBLK), PDSA_C2(:, JBLK), PC3(:, JBLK), PCN(:, JBLK), Z_YDMF_PHYS_OUT_CT(&
        &:, JBLK), Z_YDMF_PHYS_SURF_GSD_VV_PD2(:, JBLK), Z_YDMF_PHYS_OUT_FEVV(:, JBLK), Z_YDMF_PHYS_OUT_FTR&
        &(:, JBLK), Z_YDMF_PHYS_SURF_GSD_VV_PLAI(:, JBLK), PFLU_NEIJ(:, JBLK), PFLU_VEG(:, JBLK), PWFC(:, JBLK&
        &), PWPMX(:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC(:, JBLK), PWLMX(:, JBLK), PWSEQ(:, JBLK), PWSMX&
        &(:, JBLK), Z_YDMF_PHYS_OUT_FCHSP (:, 1, JBLK), Z_YDMF_PHYS_OUT_FCLL (:, 1, JBLK), Z_YDMF_PHYS_OUT_FCLN&
        & (:, 1, JBLK), Z_YDMF_PHYS_OUT_FCS (:, 1, JBLK), PFLU_FEVI (:, 1, JBLK), Z_YDMF_PHYS_OUT_FEVL (:, 1&
        &, JBLK), Z_YDMF_PHYS_OUT_FEVN (:, 1, JBLK), Z_YDMF_PHYS_SURF_GSD_VF_PLSM(:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F&
        & (:, 1, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T(:,:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:, JBLK&
        &), Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q (:, 1, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL (:, 1, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W&
        &(:, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC(:, JBLK), Z_YDMF_PHYS_OUT_FGEL(:, JBLK), Z_YDMF_PHYS_OUT_FGELS&
        &(:, JBLK), Z_YDMF_PHYS_OUT_FLWSP(:, JBLK), Z_YDMF_PHYS_OUT_FONTE(:, JBLK), Z_YDMF_PHYS_OUT_RUISP(:&
        &, JBLK), Z_YDMF_PHYS_OUT_RUISL(:, JBLK), Z_YDMF_PHYS_OUT_RUISS(:, JBLK),YDSTACK=YLSTACK)
      ENDDO

    ENDDO

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

    IF (FXTRAN_ACDC_LSYNCHOST ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV')) THEN
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
      &:ACDROV:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
      CALL SGET_HOST_DATA_RDWR (PC3, YD_PC3)
      CALL SGET_HOST_DATA_RDWR (PCN, YD_PCN)
      CALL SGET_HOST_DATA_RDWR (PDSA_C1, YD_PDSA_C1)
      CALL SGET_HOST_DATA_RDWR (PDSA_C2, YD_PDSA_C2)
      CALL SGET_HOST_DATA_RDWR (PFLU_FEVI, YD_PFLU_FEVI)
      CALL SGET_HOST_DATA_RDWR (PFLU_NEIJ, YD_PFLU_NEIJ)
      CALL SGET_HOST_DATA_RDWR (PFLU_VEG, YD_PFLU_VEG)
      CALL SGET_HOST_DATA_RDWR (PFPLSL, YD_PFPLSL)
      CALL SGET_HOST_DATA_RDWR (PFPLSN, YD_PFPLSN)
      CALL SGET_HOST_DATA_RDWR (PWFC, YD_PWFC)
      CALL SGET_HOST_DATA_RDWR (PWLMX, YD_PWLMX)
      CALL SGET_HOST_DATA_RDWR (PWPMX, YD_PWPMX)
      CALL SGET_HOST_DATA_RDWR (PWSEQ, YD_PWSEQ)
      CALL SGET_HOST_DATA_RDWR (PWSMX, YD_PWSMX)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_FC)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC, YDMF_PHYS_BASE_STATE%YGSP_RR%F_IC)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T, YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W, YDMF_PHYS_BASE_STATE%YGSP_RR%F_W)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q, YDMF_PHYS_BASE_STATE%YGSP_SB%F_Q)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T, YDMF_PHYS_BASE_STATE%YGSP_SB%F_T)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL, YDMF_PHYS_BASE_STATE%YGSP_SB%F_TL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F, YDMF_PHYS_BASE_STATE%YGSP_SG%F_F)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_CT, YDMF_PHYS%OUT%F_CT)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCHSP, YDMF_PHYS%OUT%F_FCHSP)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCLL, YDMF_PHYS%OUT%F_FCLL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCLN, YDMF_PHYS%OUT%F_FCLN)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FCS, YDMF_PHYS%OUT%F_FCS)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FEVL, YDMF_PHYS%OUT%F_FEVL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FEVN, YDMF_PHYS%OUT%F_FEVN)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FEVV, YDMF_PHYS%OUT%F_FEVV)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGEL, YDMF_PHYS%OUT%F_FGEL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FGELS, YDMF_PHYS%OUT%F_FGELS)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FLWSP, YDMF_PHYS%OUT%F_FLWSP)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FONTE, YDMF_PHYS%OUT%F_FONTE)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCL, YDMF_PHYS%OUT%F_FPLCL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FPLCN, YDMF_PHYS%OUT%F_FPLCN)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FRSO, YDMF_PHYS%OUT%F_FRSO)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FRTH, YDMF_PHYS%OUT%F_FRTH)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_FTR, YDMF_PHYS%OUT%F_FTR)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISL, YDMF_PHYS%OUT%F_RUISL)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISP, YDMF_PHYS%OUT%F_RUISP)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_OUT_RUISS, YDMF_PHYS%OUT%F_RUISS)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_SURF_GSD_VF_PLSM, YDMF_PHYS_SURF%GSD_VF%F_LSM)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_SURF_GSD_VV_PD2, YDMF_PHYS_SURF%GSD_VV%F_D2)
      CALL SGET_HOST_DATA_RDWR (Z_YDMF_PHYS_SURF_GSD_VV_PLAI, YDMF_PHYS_SURF%GSD_VV%F_LAI)
      IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL&
      &:ACDROV:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
    PC3 => NULL ()
    PCN => NULL ()
    PDSA_C1 => NULL ()
    PDSA_C2 => NULL ()
    PFLU_FEVI => NULL ()
    PFLU_NEIJ => NULL ()
    PFLU_VEG => NULL ()
    PFPLSL => NULL ()
    PFPLSN => NULL ()
    PWFC => NULL ()
    PWLMX => NULL ()
    PWPMX => NULL ()
    PWSEQ => NULL ()
    PWSMX => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_FC => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_IC => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_RR_W => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SB_Q => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SB_T => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SB_TL => NULL ()
    Z_YDMF_PHYS_BASE_STATE_YGSP_SG_F => NULL ()
    Z_YDMF_PHYS_OUT_CT => NULL ()
    Z_YDMF_PHYS_OUT_FCHSP => NULL ()
    Z_YDMF_PHYS_OUT_FCLL => NULL ()
    Z_YDMF_PHYS_OUT_FCLN => NULL ()
    Z_YDMF_PHYS_OUT_FCS => NULL ()
    Z_YDMF_PHYS_OUT_FEVL => NULL ()
    Z_YDMF_PHYS_OUT_FEVN => NULL ()
    Z_YDMF_PHYS_OUT_FEVV => NULL ()
    Z_YDMF_PHYS_OUT_FGEL => NULL ()
    Z_YDMF_PHYS_OUT_FGELS => NULL ()
    Z_YDMF_PHYS_OUT_FLWSP => NULL ()
    Z_YDMF_PHYS_OUT_FONTE => NULL ()
    Z_YDMF_PHYS_OUT_FPLCL => NULL ()
    Z_YDMF_PHYS_OUT_FPLCN => NULL ()
    Z_YDMF_PHYS_OUT_FRSO => NULL ()
    Z_YDMF_PHYS_OUT_FRTH => NULL ()
    Z_YDMF_PHYS_OUT_FTR => NULL ()
    Z_YDMF_PHYS_OUT_RUISL => NULL ()
    Z_YDMF_PHYS_OUT_RUISP => NULL ()
    Z_YDMF_PHYS_OUT_RUISS => NULL ()
    Z_YDMF_PHYS_SURF_GSD_VF_PLSM => NULL ()
    Z_YDMF_PHYS_SURF_GSD_VV_PD2 => NULL ()
    Z_YDMF_PHYS_SURF_GSD_VV_PLAI => NULL ()
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ELSE
      CALL ABOR1 ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL: NOT METHOD WAS FOUND')
  ENDIF

  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL:ACDROV',1,ZHOOK_HANDLE_PARALLEL)
ENDIF




CALL FXTRAN_ACDC_GPUMEMSTAT (FXTRAN_FILE, FXTRAN_LINE, "END")

IF (LHOOK) CALL DR_HOOK ('DELETE_TEMPORARIES',0,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('DELETE_TEMPORARIES',1,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_HYDRO_BUDGET_PARALLEL', 1, ZHOOK_HANDLE)
END SUBROUTINE APL_ARPEGE_HYDRO_BUDGET_PARALLEL
