INTERFACE

SUBROUTINE TRIDIFV1_OPENACC (YDPHY, YDPHY0, KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, PA, PB, PC, PF, PDFDT, PIPOI, PY, PCFA, PCFB, YDSTACK)
!$ACC ROUTINE (TRIDIFV1_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMPHY,ONLY:TPHY
USE YOMPHY0,ONLY:TPHY0
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
TYPE (TPHY), INTENT (IN)::YDPHY
TYPE (TPHY0), INTENT (IN)::YDPHY0
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PA (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PB (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PC (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PY (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PF (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDFDT (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PIPOI (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFA (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCFB (KLON, KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
END SUBROUTINE TRIDIFV1_OPENACC


END INTERFACE
