SUBROUTINE ACVPPKF_PART3 (LDCONDWT, LDOCHTRANS, K_KCH1, YDCPG_BNDS, YDCPG_OPTS, YDCST, YDML_PHY_MF&
&, PEPS, PSMD, PVMD, PWMD, KCLBAS, KCLBASS, KCLTOP, KCLTOPS, K_KCLBAS, K_KCLTOP, KNLAB, KNND&
&, PAPRSF, PCP, PDIFCQ, PDIFCS, PFCCQL, PFCCQN, PNEBPP, PPRODTH, PQCPP, PR, PT, PDPSG, PDQIDT&
&, PDQLDT, PDQVDT, PDTDT, PDUDT, PDVDT, PLS, PLV, PQC, PRCTEN, PRITEN, PRVTEN, PSHAL_ZCH1TEN&
&, PTTEN, PUMF, PUMFMAX, PUQL, PUQV, PURCI, PURV, PUTEN, PVTEN, PZUMF)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE YOMCST,ONLY:TCST
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

LOGICAL, INTENT (INOUT)::LDCONDWT
LOGICAL, INTENT (INOUT)::LDOCHTRANS
INTEGER (KIND=JPIM), INTENT (IN)::K_KCH1
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
REAL (KIND=JPRB), INTENT (INOUT)::PEPS
REAL (KIND=JPRB), INTENT (INOUT)::PSMD
REAL (KIND=JPRB), INTENT (INOUT)::PVMD
REAL (KIND=JPRB), INTENT (INOUT)::PWMD
INTEGER (KIND=JPIM), INTENT (INOUT)::KCLBAS (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCLBASS (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCLTOP (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCLTOPS (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::K_KCLBAS (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::K_KCLTOP (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KNLAB (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
INTEGER (KIND=JPIM), INTENT (OUT)::KNND (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PCP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDIFCQ (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDIFCS (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFCCQL (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFCCQN (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PNEBPP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PPRODTH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PQCPP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PR (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDPSG (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDQIDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDQLDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDQVDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDTDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDUDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDVDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PLS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PLV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PQC (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRCTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRITEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRVTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSHAL_ZCH1TEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, K_KCH1)
REAL (KIND=JPRB), INTENT (INOUT)::PTTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUMFMAX (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PUQL (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUQV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PURCI (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PURV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PVTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PZUMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
INTEGER::JKP
INTEGER::JN
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPRB)::ZDQCDT
REAL (KIND=JPRB)::ZDTLDT
REAL (KIND=JPRB)::ZTDCP
REAL (KIND=JPRB)::ZBETA (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCH1TEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, K_KCH1)
REAL (KIND=JPRB)::ZRHO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG+1)
REAL (KIND=JPRB)::ZTHETA (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG+1)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('ACVPPKF_PART3', 0, ZHOOK_HANDLE)

DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
  KCLTOP (JLON)=MAX (KCLTOP (JLON), KCLTOPS (JLON))
  KCLBAS (JLON)=MAX (KCLBAS (JLON), KCLBASS (JLON))
ENDDO


DO JLEV=1, YDCPG_OPTS%KFLEVG
  JKP=YDCPG_OPTS%KFLEVG-JLEV+1

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    PDTDT (JLON, JLEV)=PTTEN (JLON, JKP)
    PDQVDT (JLON, JLEV)=PRVTEN (JLON, JKP)
    PDQLDT (JLON, JLEV)=PRCTEN (JLON, JKP)
    PDQIDT (JLON, JLEV)=PRITEN (JLON, JKP)
    PDUDT (JLON, JLEV)=PUTEN (JLON, JKP)
    PDVDT (JLON, JLEV)=PVTEN (JLON, JKP)
    PUMF (JLON, JLEV)=PZUMF (JLON, JKP)
    PUQV (JLON, JLEV)=PURV (JLON, JKP)/(1.0+PURV (JLON, JKP))
    PUQL (JLON, JLEV)=PURCI (JLON, JKP)/(1.0+PURCI (JLON, JKP))
  ENDDO

ENDDO


DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
  JLEV=KCLTOP (JLON)
  K_KCLTOP (JLON)=YDCPG_OPTS%KFLEVG-JLEV+1
  JLEV=KCLBAS (JLON)
  K_KCLBAS (JLON)=YDCPG_OPTS%KFLEVG-JLEV+1

  IF (KCLTOP (JLON)==1) THEN
    K_KCLTOP (JLON)=1
  ENDIF


  IF (KCLBAS (JLON)==1) THEN
    K_KCLBAS (JLON)=1
  ENDIF

ENDDO


IF (LDOCHTRANS) THEN

  DO JLEV=1, YDCPG_OPTS%KFLEVG
    JKP=YDCPG_OPTS%KFLEVG-JLEV+1

    DO JN=1, K_KCH1

      DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
        ZCH1TEN (JLON, JLEV, JN)=PSHAL_ZCH1TEN (JLON, JKP, JN)
      ENDDO

    ENDDO

  ENDDO

ENDIF

PPRODTH (:,:)=0.0_JPRB

IF (YDML_PHY_MF%YRPHY0%RPRTH>0._JPRB) THEN

  DO JLEV=1, YDCPG_OPTS%KFLEVG

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
      ZBETA (JLON, JLEV)=(YDCST%RATM/PAPRSF (JLON, JLEV))**(YDCST%RKAPPA)
      ZTHETA (JLON, JLEV)=PT (JLON, JLEV)*ZBETA (JLON, JLEV)
      ZRHO (JLON, JLEV)=PAPRSF (JLON, JLEV)/(PR (JLON, JLEV)*PT (JLON, JLEV))
    ENDDO

  ENDDO


  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    ZTHETA (JLON, 0)=ZTHETA (JLON, 1)
    ZRHO (JLON, 0)=ZRHO (JLON, 1)
    ZTHETA (JLON, YDCPG_OPTS%KFLEVG+1)=ZTHETA (JLON, YDCPG_OPTS%KFLEVG)
    ZRHO (JLON, YDCPG_OPTS%KFLEVG+1)=ZRHO (JLON, YDCPG_OPTS%KFLEVG)
  ENDDO


  DO JLEV=1, YDCPG_OPTS%KFLEVG

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
      ZTDCP=PVMD*PDQVDT (JLON, JLEV)+PWMD*PDQLDT (JLON, JLEV)+PSMD*PDQIDT (JLON, JLEV)
      ZDQCDT=PDQLDT (JLON, JLEV)+PDQIDT (JLON, JLEV)
      ZDTLDT=ZBETA (JLON, JLEV)*(PDTDT (JLON, JLEV)+PLV (JLON, JLEV)/PCP&
      & (JLON, JLEV)*(PQC (JLON, JLEV)*ZTDCP/PCP (JLON, JLEV)-ZDQCDT))
      PPRODTH (JLON, JLEV)=PPRODTH (JLON, JLEV-1)-PDPSG (JLON, JLEV)*ZDTLDT
    ENDDO

  ENDDO


  DO JLEV=0, YDCPG_OPTS%KFLEVG

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
      PPRODTH (JLON, JLEV)=PPRODTH (JLON, JLEV)*YDCST%RG*4._JPRB/(ZRHO (JLON, JLEV&
      &)+ZRHO (JLON, JLEV+1))/(ZTHETA (JLON, JLEV)+ZTHETA (JLON, JLEV+1))
    ENDDO

  ENDDO

ENDIF


DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA

  DO JLEV=1, YDCPG_OPTS%KFLEVG
    KNLAB (JLON, JLEV)=1-MAX (0, MIN (1,(K_KCLTOP (JLON)-JLEV)*(K_KCLBAS (JLON)-JLEV)))
  ENDDO

  KNND (JLON)=MIN (1, K_KCLTOP (JLON)-1)
ENDDO


IF (YDML_PHY_MF%YRPHY0%RKFBTAU>0._JPRB) THEN

  DO JLEV=1, YDCPG_OPTS%KFLEVG

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
      ZDQCDT=MAX (0.0_JPRB, PDQLDT (JLON, JLEV)+PDQIDT (JLON, JLEV))
      PQCPP (JLON, JLEV)=YDML_PHY_MF%YRPHY0%RKFBTAU*ZDQCDT*FLOAT (KNLAB (JLON, JLEV))
      PNEBPP (JLON, JLEV)=MAX (PEPS, MIN (YDML_PHY_MF%YRPHY0%RKFBNBX&
      &, PQCPP (JLON, JLEV)/YDML_PHY_MF%YRPHY0%RQLCR))
      PUMFMAX (JLON)=MAX (PUMFMAX (JLON), PUMF (JLON, JLEV))
    ENDDO

  ENDDO


  IF (.NOT.YDML_PHY_MF%YRCVMNH%LSMOOTH) THEN

    DO JLEV=1, YDCPG_OPTS%KFLEVG

      DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
        PQCPP (JLON, JLEV)=PQCPP (JLON, JLEV)*MIN (1.0_JPRB, PUMF (JLON, JLEV)/PUMFMAX (JLON))
        PNEBPP (JLON, JLEV)=MAX (PEPS, MIN (YDML_PHY_MF%YRPHY0%RKFBNBX&
        &, PQCPP (JLON, JLEV)/YDML_PHY_MF%YRPHY0%RQLCR))
      ENDDO

    ENDDO

  ENDIF

ENDIF


IF (.NOT.LDCONDWT) THEN

  DO JLEV=1, YDCPG_OPTS%KFLEVG

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
      PDQVDT (JLON, JLEV)=PDQVDT (JLON, JLEV)+PDQLDT (JLON, JLEV)+PDQIDT (JLON, JLEV)
      PDTDT (JLON, JLEV)=PDTDT (JLON, JLEV)-(PLV (JLON, JLEV)*PDQLDT (JLON&
      &, JLEV)+PLS (JLON, JLEV)*PDQIDT (JLON, JLEV))/PCP (JLON, JLEV)
      PDQLDT (JLON, JLEV)=0.0_JPRB
      PDQIDT (JLON, JLEV)=0.0_JPRB
    ENDDO

  ENDDO

ELSE

  DO JLEV=1, YDCPG_OPTS%KFLEVG

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
      PFCCQL (JLON, JLEV)=PFCCQL (JLON, JLEV-1)+PDPSG (JLON, JLEV)*PDQLDT (JLON, JLEV)
      PFCCQN (JLON, JLEV)=PFCCQN (JLON, JLEV-1)+PDPSG (JLON, JLEV)*PDQIDT (JLON, JLEV)
    ENDDO

  ENDDO

ENDIF


DO JLEV=1, YDCPG_OPTS%KFLEVG

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    PDIFCQ (JLON, JLEV)=PDIFCQ (JLON, JLEV-1)-PDPSG (JLON, JLEV)*PDQVDT (JLON, JLEV)
    ZTDCP=PVMD*PDQVDT (JLON, JLEV)+PWMD*PDQLDT (JLON, JLEV)+PSMD*PDQIDT (JLON, JLEV)
    PDIFCS (JLON, JLEV)=PDIFCS (JLON, JLEV-1)-PDPSG (JLON, JLEV)*(PDTDT (JLON, JLEV&
    &)*(PCP (JLON, JLEV)+YDML_PHY_MF%YRPHY2%TSPHY*ZTDCP)+PT (JLON, JLEV)*ZTDCP)
  ENDDO

ENDDO


DO JLEV=1, YDCPG_OPTS%KFLEVG

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    PDIFCQ (JLON, JLEV)=PDIFCQ (JLON, JLEV)-PFCCQL (JLON, JLEV)-PFCCQN (JLON, JLEV)
    PDIFCS (JLON, JLEV)=PDIFCS (JLON, JLEV)+YDCST%RLVZER*PFCCQL&
    & (JLON, JLEV)+YDCST%RLSZER*PFCCQN (JLON, JLEV)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('ACVPPKF_PART3', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
