SUBROUTINE APL_ARPEGE_INIT_SURFEX_OUTLINE_001 (YDCPG_BNDS, YDCPG_GPAR, YDCPG_OPTS&
&, YDMF_PHYS, YDMF_PHYS_BASE_STATE, YDMODEL, PALBD, PALBP, PFLU_EMIS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE, CPG_GPAR_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_GPAR_TYPE), INTENT (INOUT)::YDCPG_GPAR
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (OUT)::PALBD (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PALBP (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PFLU_EMIS (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JSG
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_INIT_SURFEX_OUTLINE_001', 0, ZHOOK_HANDLE)

DO JSG=1, YDMODEL%YRML_PHY_RAD%YRERAD%NSW

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    PALBP (JLON, JSG)=YDCPG_GPAR%ALBDIR (JLON, JSG)
    PALBD (JLON, JSG)=YDCPG_GPAR%ALBSCA (JLON, JSG)
  ENDDO

ENDDO


DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
  YDMF_PHYS%OUT%ALB (JLON)=0.0_JPRB
ENDDO


DO JSG=1, YDMODEL%YRML_PHY_RAD%YRERAD%NSW

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    YDMF_PHYS%OUT%ALB (JLON)=YDMF_PHYS%OUT%ALB (JLON)+0.5*(PALBP (JLON, JSG)+PALBD (JLON, JSG))
  ENDDO

ENDDO


DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
  YDMF_PHYS%OUT%ALB (JLON)=YDMF_PHYS%OUT%ALB (JLON)/REAL (YDMODEL%YRML_PHY_RAD%YRERAD%NSW, JPRB)
ENDDO


DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA

  IF (PFLU_EMIS (JLON)==0._JPRB) THEN
    PFLU_EMIS (JLON)=0.99_JPRB
    YDMF_PHYS_BASE_STATE%YGSP_RR%T (JLON)=288.0_JPRB
    YDMF_PHYS%OUT%ALB (JLON)=0.1_JPRB
  ENDIF

ENDDO

IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_INIT_SURFEX_OUTLINE_001', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
