SUBROUTINE APL_ARPEGE_ACHMT (LDCLS, LDHMT, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS, YDMF_PHYS_SURF, YDMF_PHYS_BASE_STATE&
&, YDMODEL, YDCPG_BNDS, PFLU_CDN, PNEIJG, PXDROV, PFLU_QSATS, PDQSTS, PFLU_CD, PDSA_RS, PCHROV&
&, PNEIJV, PPFL_FPLCH, PQV, PDPHIV, PFLU_NEIJ, PNBVNO, PFLU_VEG, PFLU_CH, PHQ, PDSA_CPS, PRTI,&
& PMRIPP, PHU, PPFL_FPLSH, PDPHIT, PXHROV, PWFC, PCDROV, PGWDCS, PPCLS)
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE, CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_PHY_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

LOGICAL, INTENT (INOUT)::LDCLS
LOGICAL, INTENT (INOUT)::LDHMT
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_CDN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PNEIJG (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PXDROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_QSATS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PDQSTS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_CD (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PDSA_RS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PCHROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PNEIJV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PPFL_FPLCH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PQV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDPHIV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_NEIJ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PNBVNO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_VEG (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_CH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PHQ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PDSA_CPS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PRTI (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PMRIPP (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PHU (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PPFL_FPLSH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDPHIT (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PXHROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PWFC (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PCDROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PGWDCS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PPCLS (YDCPG_OPTS%KLON)
#include "achmt.intfb.h"
REAL (KIND=JPRB)::ZSTAB (YDCPG_OPTS%KLON)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_ACHMT', 0, ZHOOK_HANDLE)
CALL ACHMT (YDCPG_OPTS%YRCLI, YDMODEL%YRML_PHY_MF%YRPHY, YDMODEL%YRML_PHY_MF%YRPHY0, YDMODEL%YRML_PHY_MF&
&%YRPHY1, YDMODEL%YRML_PHY_MF%YRPHY2, YDMODEL%YRCST, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON&
&, YDCPG_OPTS%KFLEVG, YDCPG_OPTS%YRSURF_DIMS%YSD_VVD%NUMFLDS>=8.AND.YDMODEL%YRML_PHY_MF%YRPHY%LSOLV, YDMF_PHYS_BASE_STATE&
&%YCPG_DYN%PHI, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, YDMF_PHYS_BASE_STATE&
&%YCPG_PHY%PREHYDF, YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP, PQV, YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%R, YDMF_PHYS_BASE_STATE&
&%T, YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, PPFL_FPLSH, PPFL_FPLCH, PDPHIT, PDPHIV, YDMF_PHYS_SURF&
&%GSD_VF%PZ0F, YDMF_PHYS_SURF%GSD_VV%PZ0H, YDMF_PHYS_SURF%GSD_VF%PZ0RLF, YDMF_PHYS_SURF%GSD_VV%PHV, YDMF_PHYS_SURF&
&%GSD_VF%PLSM, PNEIJG, PNEIJV, YDMF_PHYS_BASE_STATE%YGSP_SG%F (:, 1), YDMF_PHYS_BASE_STATE%YGSP_RR%T,&
& YDMF_PHYS_SURF%GSD_VF%PVEG, PWFC, YDMF_PHYS_BASE_STATE%YGSP_RR%W, YDMF_PHYS_BASE_STATE%YGSP_RR%IC, LDCLS&
&, LDHMT, PNBVNO, PMRIPP, PFLU_CD, PFLU_CDN, PCDROV, PFLU_CH, PCHROV, PDSA_CPS, PDQSTS, PGWDCS, YDMF_PHYS&
&%OUT%GZ0, YDMF_PHYS%OUT%GZ0H, PHQ, PHU, PFLU_NEIJ, YDMF_PHYS%OUT%QCLS, YDCPG_MISC%QS, PFLU_QSATS, YDMF_PHYS&
&%OUT%RHCLS, PDSA_RS, PRTI, ZSTAB, YDMF_PHYS%OUT%TCLS, YDMF_PHYS%OUT%UCLS, YDMF_PHYS%OUT%VCLS, YDMF_PHYS&
&%OUT%NUCLS, YDMF_PHYS%OUT%NVCLS, PPCLS, PFLU_VEG, PXDROV, PXHROV, YDMF_PHYS%OUT%UGST, YDMF_PHYS%OUT%VGST&
&)
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_ACHMT', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
