SUBROUTINE APL_ARPEGE_PPWETPOINT (YDMF_PHYS_BASE_STATE,&
& YDCPG_OPTS, YDMF_PHYS, YDMODEL, YDCPG_BNDS, PPCLS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (INOUT)::PPCLS (YDCPG_OPTS%KLON)
#include "ppwetpoint.intfb.h"
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_PPWETPOINT', 0, ZHOOK_HANDLE)
CALL PPWETPOINT (YDMODEL%YRCST, YDMODEL%YRML_PHY_MF%YRPHY, YDCPG_BNDS%KIDIA, YDCPG_BNDS&
&%KFDIA, YDCPG_OPTS%KLON, 1, PPCLS, YDMF_PHYS%OUT%TCLS, YDMF_PHYS_BASE_STATE%Q&
& (:, YDCPG_OPTS%KFLEVG), YDMF_PHYS_BASE_STATE%L (:, YDCPG_OPTS%KFLEVG), YDMF_PHYS_BASE_STATE&
&%I (:, YDCPG_OPTS%KFLEVG), YDMF_PHYS%OUT%TPWCLS)
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_PPWETPOINT', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
