SUBROUTINE APL_ARPEGE_SURFACE_LMSE_F (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE&
&, YDMF_PHYS_SURF, YDMODEL, PALPHA1, PCDROV, PCEROV, PCFAU, PCFBU, PCFBV, PCHROV, PCOEFA&
&, PCP, PDIFWQ, PDIFWS, PDQSTS, PDSA_CPS, PDSA_LHS, PFLU_CD, PFLU_CDN, PFLU_EMIS, PFLU_FEVI&
&, PFLU_NEIJ, PFLU_QSATS, PFLU_VEG, PHQ, PHTR, PHU, PLVT, PNEBCH, PNEBDIFF, PNEBS, PQI&
&, PQICE, PQL, PQV, PSC_FCLL, PSC_FCLN, PSC_FEVI, PSC_FEVN, PXDROV, PXHROV, PXQRO, PXTRO&
&, PXURO, PCFAS, PCFBQ, PCFBS, PDSE, PFMDU, PFMDV)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE, CPG_GPAR_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (OUT)::PALPHA1 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PCDROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PCEROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PCFAU (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PCFBU (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PCFBV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PCHROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PCOEFA (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PCP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PDIFWQ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PDIFWS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PDQSTS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PDSA_CPS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PDSA_LHS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PFLU_CD (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PFLU_CDN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_EMIS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PFLU_FEVI (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KTSSG+1)
REAL (KIND=JPRB), INTENT (IN)::PFLU_NEIJ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PFLU_QSATS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PFLU_VEG (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PHQ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PHTR (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PHU (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PLVT (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PNEBCH (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PNEBDIFF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PNEBS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PQI (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PQICE (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PQL (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PQV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSC_FCLL (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSC_FCLN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSC_FEVI (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSC_FEVN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PXDROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PXHROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PXQRO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PXTRO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PXURO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PCFAS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PCFBQ (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PCFBS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDSE (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFMDU (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PFMDV (YDCPG_OPTS%KLON)
#include "arp_ground_param.intfb.h"
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPRB)::ZCFBQ_G (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCFBS_G (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCFBU_G (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCFBV_G (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_SURFACE_LMSE_F', 0, ZHOOK_HANDLE)

IF (YDMODEL%YRML_PHY_MF%YRPHY%NDIFFNEB==5) THEN
  PNEBDIFF (:,:)=PNEBS (:,:)
ELSEIF (YDMODEL%YRML_PHY_MF%YRPHY%NDIFFNEB==2) THEN

  DO JLEV=1, YDCPG_OPTS%KFLEVG

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
      PNEBDIFF (JLON, JLEV)=YDCPG_MISC%NEB (JLON, JLEV)
    ENDDO

  ENDDO

ELSEIF (YDMODEL%YRML_PHY_MF%YRPHY%NDIFFNEB==3) THEN
  PNEBDIFF (:,:)=PNEBS (:,:)+(1.0_JPRB-PNEBS (:,:))*PNEBCH (:,:)
ENDIF


IF (YDMODEL%YRML_PHY_MF%YRPHY%LEDMFI) THEN
  ZCFBS_G (:,:)=PCFBS (:,:)
  ZCFBQ_G (:,:)=PCFBQ (:,:)
  ZCFBU_G (:,:)=PCFBU (:,:)
  ZCFBV_G (:,:)=PCFBV (:,:)
ENDIF

CALL ARP_GROUND_PARAM (YDMODEL%YRCST, YDMODEL%YRML_AOC%YRMCC, YDMODEL%YRML_PHY_MF, YDCPG_BNDS%KIDIA&
&, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KTDIA, YDCPG_OPTS%KFLEVG, YDCPG_OPTS%YRSURF_DIMS%YSP_SBD&
&%NLEVS, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI, PCP, YDMF_PHYS%OUT%FRSO, PQV, YDMF_PHYS_BASE_STATE%YCPG_PHY&
&%XYB%RDELP, YDMF_PHYS_BASE_STATE%T, YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, PXURO, PXQRO,&
& PXTRO, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, PQL, PQI, PNEBDIFF, PFLU_CD, PFLU_CDN, PCDROV, PCHROV&
&, PCEROV, PDSA_CPS, YDMF_PHYS%OUT%CT, PDQSTS, PFLU_EMIS, YDMF_PHYS_SURF%GSD_VH%PSPSH, PHQ, PHTR, PHU&
&, YDMF_PHYS_SURF%GSD_VV%PHV, YDMF_PHYS_SURF%GSD_VF%PLSM, YDMF_PHYS_SURF%GSD_VV%PIVEG, PFLU_NEIJ, YDCPG_MISC&
&%QS, PFLU_QSATS, YDMF_PHYS_BASE_STATE%YGSP_SB%T, YDMF_PHYS_BASE_STATE%YGSP_RR%T, PFLU_VEG, PXDROV&
&, PXHROV, YDMF_PHYS_BASE_STATE%YGSP_RR%W, YDMF_PHYS_BASE_STATE%YGSP_RR%IC, PDSE, PCFAS, PCFAU, PCFBS&
&, PCFBU, PCFBV, PCFBQ, PCOEFA, PALPHA1, PLVT, PQICE, PDIFWQ, PDIFWS, PFMDU, PFMDV, PSC_FEVI, PSC_FEVN&
&, PSC_FCLL, PSC_FCLN, YDMF_PHYS%OUT%FCHSP, YDMF_PHYS%OUT%FCLL (:, 1), YDMF_PHYS%OUT%FCLN (:, 1), YDMF_PHYS&
&%OUT%FCS (:, 1), PFLU_FEVI (:, 1), YDMF_PHYS%OUT%FEVL (:, 1), YDMF_PHYS%OUT%FEVN (:, 1), YDMF_PHYS&
&%OUT%FEVV, YDMF_PHYS%OUT%FTR, PDSA_LHS, YDMF_PHYS_SURF%GSD_VH%PQSH, YDMF_PHYS%OUT%FRTH, YDMF_PHYS_SURF&
&%GSD_VF%PZ0F, YDMF_PHYS_SURF%GSD_VV%PZ0H)

DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
  YDMF_PHYS%OUT%DIFTQ (JLON, YDCPG_OPTS%KFLEVG)=PDIFWQ (JLON)
  YDMF_PHYS%OUT%DIFTS (JLON, YDCPG_OPTS%KFLEVG)=PDIFWS (JLON)
ENDDO


IF (YDMODEL%YRML_PHY_MF%YRPHY%LEDMFI) THEN
  PCFBQ (:,:)=ZCFBQ_G (:,:)
  PCFBS (:,:)=ZCFBS_G (:,:)
  PCFBU (:, YDCPG_OPTS%KFLEVG)=ZCFBU_G (:, YDCPG_OPTS%KFLEVG)
  PCFBV (:, YDCPG_OPTS%KFLEVG)=ZCFBV_G (:, YDCPG_OPTS%KFLEVG)
ENDIF

IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_SURFACE_LMSE_F', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
