INTERFACE
SUBROUTINE APL_ARPEGE_INIT_OUTLINE_005 (YDCPG_BNDS, YDCPG_OPTS, YDMODEL, KMOC_CLPH, PAER, PAERINDS, PALBD&
&, PALBP, PCEMTR, PCTRSO, PSFSWDIF, PSFSWDIR, PSUDU, PTRSOD, PTRSODIF, PTRSODIR, PXDROV, PXHROV)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MODEL), INTENT (IN)::YDMODEL
INTEGER (KIND=JPIM), INTENT (OUT)::KMOC_CLPH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PAER (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 6)
REAL (KIND=JPRB), INTENT (OUT)::PAERINDS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PALBD (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PALBP (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PCEMTR (YDCPG_OPTS%KLON, 0:1)
REAL (KIND=JPRB), INTENT (OUT)::PCTRSO (YDCPG_OPTS%KLON, 0:1)
REAL (KIND=JPRB), INTENT (OUT)::PSFSWDIF (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PSFSWDIR (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PSUDU (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PTRSOD (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PTRSODIF (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PTRSODIR (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PXDROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PXHROV (YDCPG_OPTS%KLON)
ENDSUBROUTINE
END INTERFACE
