SUBROUTINE APL_ARPEGE_RADIATION_RADHEAT (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE&
&, YDMODEL, YDVARS, PALBD, PALBP, PCEMTR, PCTRSO, PFLU_EMIS, PQV, PRDG_MU0, PRDG_SOLO,&
& PSFSWDIF, PSFSWDIR, PSUDU, PTENT, PTRSOD, PTRSODIF, PTRSODIR, PFRSODS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
REAL (KIND=JPRB), INTENT (IN)::PALBD (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (IN)::PALBP (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PCEMTR (YDCPG_OPTS%KLON, 0:1)
REAL (KIND=JPRB), INTENT (OUT)::PCTRSO (YDCPG_OPTS%KLON, 0:1)
REAL (KIND=JPRB), INTENT (IN)::PFLU_EMIS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PQV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PRDG_MU0 (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PRDG_SOLO (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSFSWDIF (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PSFSWDIR (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (IN)::PSUDU (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PTENT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PTRSOD (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PTRSODIF (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (OUT)::PTRSODIR (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB), INTENT (INOUT)::PFRSODS (YDCPG_OPTS%KLON)
#include "radheat.intfb.h"
REAL (KIND=JPRB)::ZDSRP (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSDUR (YDCPG_OPTS%KLON)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_RADIATION_RADHEAT', 0, ZHOOK_HANDLE)
YDMF_PHYS%OUT%FRSOLU (:)=YDVARS%RADIATION%RMOON%T0 (:)
CALL RADHEAT (YDMODEL%YRCST, YDMODEL%YRML_PHY_EC%YRTHF, YDMODEL%YRML_PHY_RAD%YRERAD, YDMODEL%YRML_PHY_RAD&
&%YRERDI, YDMODEL%YRML_PHY_MF, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG&
&, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, PFLU_EMIS, YDVARS%RADIATION%EMTD%T0, PRDG_MU0, PRDG_SOLO, PQV&
&, PTENT, YDVARS%RADIATION%TRSW%T0, PTRSOD, YDMF_PHYS_BASE_STATE%YGSP_RR%T, YDMODEL%YRML_PHY_MF%YRPHY2&
&%TSPHY, PTRSODIR, PTRSODIF, PALBD, PALBP, YDMF_PHYS%OUT%FRSO, YDMF_PHYS%OUT%FRTH, YDMF_PHYS%OUT%FRSODS&
&, YDMF_PHYS%OUT%FRTHDS, PCEMTR, PCTRSO, YDMF_PHYS%OUT%FRSOC, YDMF_PHYS%OUT%FRTHC, PSUDU, ZSDUR, ZDSRP&
&, PSFSWDIR, PSFSWDIF, YDMF_PHYS%OUT%FRSOPS, PFRSODS, YDMF_PHYS%OUT%FRSOPT)
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_RADIATION_RADHEAT', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
