INTERFACE
SUBROUTINE ARP_SHALLOW_MF_FINISH (PTSPHY, YDCPG_BNDS, YDCPG_OPTS, YDCST, PVMD, KNLAB, PCP, PDIFTQ&
&, PDIFTS, PMF_UP, PQLI, PRODTH_CVPP, PSTRTU, PSTRTV, PT, PDPSG, PDRTDT_MF, PDTHLDT_MF, PDUDT_MF&
&, PDVDT_MF, PEMF, PEXNER, PFLXZTHVMF, PHRODREF, PQDM, PRC_UP, PRI_UP, PRT_UP, PTHETA)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMCST,ONLY:TCST
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

REAL (KIND=JPRB), INTENT (IN)::PTSPHY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (TCST), INTENT (IN)::YDCST
REAL (KIND=JPRB), INTENT (INOUT)::PVMD
INTEGER (KIND=JPIM), INTENT (OUT)::KNLAB (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PCP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDIFTQ (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDIFTS (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PMF_UP (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PQLI (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PRODTH_CVPP (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSTRTU (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSTRTV (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDPSG (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDRTDT_MF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDTHLDT_MF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDUDT_MF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDVDT_MF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PEMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PEXNER (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFLXZTHVMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PHRODREF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PQDM (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRC_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRI_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRT_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PTHETA (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
ENDSUBROUTINE
END INTERFACE
