SUBROUTINE ARP_SHALLOW_MF_SHALLOW_MF (YDCPG_OPTS, KKRI, KSV_LGEND, KSV_LGBEG, D, KKR, PTSPHY&
&, YDPHYEX, KKRL, PRM, PSFTH, PFLXZTHVMF, PNEB, PSFRV, PHRODREF, PDTHLDT_MF, PRC_UP, PRI_UP,&
& PFLXZTHMF, PV, PDVDT_MF, PU, PFLXZVMF, PSVM, PZZ, PFLXZUMF, PHRODJ, PTHETA, PTKE, PRV_UP, PEXNER&
&, PDUDT_MF, PDZZ, PRT_UP, PDRTDT_MF, PU_UP, PEMF, PW_UP, PFRAC_UP, PTHL_UP, PAPRSF)
USE MODD_PHYEX,ONLY:PHYEX_T
USE PARKIND1,ONLY:JPIM, JPRB
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODI_SHALLOW_MF,ONLY:SHALLOW_MF
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
INTEGER (KIND=JPIM), INTENT (INOUT)::KKRI
INTEGER (KIND=JPIM), INTENT (INOUT)::KSV_LGEND
INTEGER (KIND=JPIM), INTENT (INOUT)::KSV_LGBEG
TYPE (DIMPHYEX_T), INTENT (INOUT)::D
INTEGER (KIND=JPIM), INTENT (INOUT)::KKR
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
TYPE (PHYEX_T), INTENT (IN)::YDPHYEX
INTEGER (KIND=JPIM), INTENT (INOUT)::KKRL
REAL (KIND=JPRB), INTENT (INOUT)::PRM (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 5)
REAL (KIND=JPRB), INTENT (INOUT)::PSFTH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PFLXZTHVMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PNEB (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSFRV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PHRODREF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDTHLDT_MF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRC_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRI_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFLXZTHMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDVDT_MF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PU (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFLXZVMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSVM (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 1)
REAL (KIND=JPRB), INTENT (INOUT)::PZZ (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFLXZUMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PHRODJ (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PTHETA (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PTKE (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRV_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PEXNER (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDUDT_MF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDZZ (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRT_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDRTDT_MF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PU_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PEMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PW_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFRAC_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PTHL_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
INTEGER (KIND=JPIM)::IKLCL (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZV_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSVDT_MF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 1)
REAL (KIND=JPRB)::ZSIGMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
INTEGER (KIND=JPIM)::IKCTL (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZTHV_UP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
INTEGER (KIND=JPIM)::IKETL (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZDETR (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZENTR (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZFLXZRMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('ARP_SHALLOW_MF_SHALLOW_MF', 0, ZHOOK_HANDLE)
CALL SHALLOW_MF (D, YDPHYEX%CST, YDPHYEX%NEBN, YDPHYEX%PARAM_MFSHALLN, YDPHYEX%TURBN, YDPHYEX%CSTURB&
&, KRR=KKR, KRRL=KKRL, KRRI=KKRI, KSV=1, ONOMIXLG=YDPHYEX%MISC%ONOMIXLG, KSV_LGBEG=KSV_LGBEG, KSV_LGEND&
&=KSV_LGEND, PTSTEP=PTSPHY, PDZZ=PDZZ, PZZ=PZZ, PRHODJ=PHRODJ, PRHODREF=PHRODREF, PPABSM=PAPRSF&
&, PEXNM=PEXNER, PSFTH=PSFTH, PSFRV=PSFRV, PTHM=PTHETA, PRM=PRM, PUM=PU, PVM=PV, PTKEM=PTKE, PSVM&
&=PSVM, PDUDT_MF=PDUDT_MF, PDVDT_MF=PDVDT_MF, PDTHLDT_MF=PDTHLDT_MF, PDRTDT_MF=PDRTDT_MF, PDSVDT_MF&
&=ZSVDT_MF, PSIGMF=ZSIGMF, PRC_MF=PRC_UP, PRI_MF=PRI_UP, PCF_MF=PNEB, PFLXZTHVMF=PFLXZTHVMF, PFLXZTHMF&
&=PFLXZTHMF, PFLXZRMF=ZFLXZRMF, PFLXZUMF=PFLXZUMF, PFLXZVMF=PFLXZVMF, PTHL_UP=PTHL_UP, PRT_UP=PRT_UP&
&, PRV_UP=PRV_UP, PRC_UP=PRC_UP, PRI_UP=PRI_UP, PU_UP=PU_UP, PV_UP=ZV_UP, PTHV_UP=ZTHV_UP, PW_UP&
&=PW_UP, PFRAC_UP=PFRAC_UP, PEMF=PEMF, PDETR=ZDETR, PENTR=ZENTR, KKLCL=IKLCL, KKETL=IKETL, KKCTL&
&=IKCTL, PDX=0._JPRB, PDY=0._JPRB, KBUDGETS=0)
IF (LHOOK) CALL DR_HOOK ('ARP_SHALLOW_MF_SHALLOW_MF', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
