SUBROUTINE MF_PHYS_SAVE_PHSURF_PART1_PART1 (YDCPG_OPTS, YDMODEL, PDAL_T0, PDOM_T0, PGSD_VF_PZ0F&
&, PGSD_VH_PPBLH, PGSD_VH_PQSH, PGSD_VH_PSPSH, PGSD_VK_PUDGRO, PGSD_VV_PHV, PGSD_VV_PZ0H, PSAV_DDAL&
&, PSAV_DDOM, PSAV_ENTCH, PSAV_FHPS, PSAV_GZ0F, PSAV_GZ0HF, PSAV_HV, PSAV_PBLH, PSAV_QSH, PSAV_UDAL&
&, PSAV_UDGRO, PSAV_UDOM, PSAV_UNEBH, PUAL_T0, PUEN_T0, PUNEBH_T0, PUOM_T0)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (IN)::PDAL_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PDOM_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VF_PZ0F (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VH_PPBLH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VH_PQSH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VH_PSPSH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VK_PUDGRO (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VV_PHV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VV_PZ0H (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_DDAL (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_DDOM (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_ENTCH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_FHPS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_GZ0F (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_GZ0HF (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_HV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_PBLH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_QSH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_UDAL (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_UDGRO (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_UDOM (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_UNEBH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PUAL_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PUEN_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PUNEBH_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PUOM_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('MF_PHYS_SAVE_PHSURF_PART1_PART1', 0, ZHOOK_HANDLE)

IF (YDCPG_OPTS%YRSURF_OPTS%YSD_VV%YHV%LSET) THEN
  PSAV_HV (1:YDCPG_OPTS%KLON)=PGSD_VV_PHV (1:YDCPG_OPTS%KLON)
ENDIF


IF (YDCPG_OPTS%YRSURF_OPTS%YSD_VF%YZ0F%LSET) THEN
  PSAV_GZ0F (1:YDCPG_OPTS%KLON)=PGSD_VF_PZ0F (1:YDCPG_OPTS%KLON)
ENDIF


IF (YDCPG_OPTS%YRSURF_OPTS%YSD_VV%YZ0H%LSET) THEN
  PSAV_GZ0HF (1:YDCPG_OPTS%KLON)=PGSD_VV_PZ0H (1:YDCPG_OPTS%KLON)
ENDIF


IF (YDCPG_OPTS%YRSURF_OPTS%YSD_VH%YPBLH%LSET) THEN
  PSAV_PBLH (1:YDCPG_OPTS%KLON)=PGSD_VH_PPBLH (1:YDCPG_OPTS%KLON)
ENDIF


IF (YDCPG_OPTS%YRSURF_OPTS%YSD_VH%YSPSH%LSET) THEN
  PSAV_FHPS (1:YDCPG_OPTS%KLON)=PGSD_VH_PSPSH (1:YDCPG_OPTS%KLON)
ENDIF


IF (YDCPG_OPTS%YRSURF_OPTS%YSD_VH%YQSH%LSET) THEN
  PSAV_QSH (1:YDCPG_OPTS%KLON)=PGSD_VH_PQSH (1:YDCPG_OPTS%KLON)
ENDIF


IF (YDCPG_OPTS%YRSURF_OPTS%YSD_VK%YUDGRO%LSET) THEN
  PSAV_UDGRO (1:YDCPG_OPTS%KLON)=PGSD_VK_PUDGRO (1:YDCPG_OPTS%KLON)
ENDIF


IF (YDMODEL%YRML_PHY_MF%YRPHY%LCVPRO.OR.YDMODEL%YRML_PHY_MF%YRPHY%LGPCMT) THEN
  PSAV_UDAL (:,:)=PUAL_T0 (:,:)
  PSAV_UDOM (:,:)=PUOM_T0 (:,:)

  IF (YDMODEL%YRML_PHY_MF%YRPHY%LCDDPRO) THEN
    PSAV_DDAL (:,:)=PDAL_T0 (:,:)
    PSAV_DDOM (:,:)=PDOM_T0 (:,:)
  ENDIF

ENDIF


IF (YDMODEL%YRML_GCONF%YGFL%YUNEBH%LACTIVE) THEN
  PSAV_UNEBH (:,:)=PUNEBH_T0 (:,:)
ENDIF


IF (YDMODEL%YRML_GCONF%YGFL%YUEN%LACTIVE) THEN
  PSAV_ENTCH (:,:)=PUEN_T0 (:,:)
ENDIF

IF (LHOOK) CALL DR_HOOK ('MF_PHYS_SAVE_PHSURF_PART1_PART1', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
