
SUBROUTINE ACRSO_OPENACC (YDPHY0, KIDIA, KFDIA, KLON, KLEV, KTDIA&
&, KSGST, PGEMU, PMU0, PAPHIF, PDELP, PFRSO, YDSTACK)
!$ACC ROUTINE (ACRSO_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMPHY0,ONLY:TPHY0
#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE


TYPE (TPHY0), INTENT (IN)::YDPHY0
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
INTEGER (KIND=JPIM), INTENT (IN)::KSGST
REAL (KIND=JPRB), INTENT (IN)::PGEMU (KLON)
REAL (KIND=JPRB), INTENT (IN)::PMU0 (KLON)
REAL (KIND=JPRB), INTENT (IN)::PAPHIF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PFRSO (KLON, 0:KLEV, KSGST+1)
TYPE(STACK), INTENT (IN) :: YDSTACK
TYPE(STACK) :: YLSTACK
temp (REAL (KIND=JPRB), ZRSO, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTEND, (KLON, KLEV))
REAL (KIND=JPRB)::ZFRAC

INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON

YLSTACK = YDSTACK



IF (KIND (ZRSO) == 8) THEN
    alloc8 (ZRSO)
ELSEIF (KIND (ZRSO) == 4) THEN
    alloc4 (ZRSO)
ELSE
    STOP 1
ENDIF


IF (KIND (ZTEND) == 8) THEN
    alloc8 (ZTEND)
ELSEIF (KIND (ZTEND) == 4) THEN
    alloc4 (ZTEND)
ELSE
    STOP 1
ENDIF


JLON = KIDIA





DO JLEV=KTDIA, KLEV
  
  ZFRAC=MAX (0._JPRB, MIN (1._JPRB,(PAPHIF (JLON, JLEV)-115000._JPRB)/45000._JPRB))
  ZRSO (JLON, JLEV)=ZFRAC+(1._JPRB-ZFRAC)*(YDPHY0%GRSO+PMU0 (JLON)*(1._JPRB-YDPHY0%GRSO))
  
ENDDO


DO JLEV=KTDIA, KLEV
  
  ZTEND (JLON, JLEV)=-(PFRSO (JLON, JLEV, 1)-PFRSO (JLON, JLEV-1, 1))/PDELP (JLON, JLEV)
  ZTEND (JLON, JLEV)=ZRSO (JLON, JLEV)*ZTEND (JLON, JLEV)
  
ENDDO


DO JLEV=KLEV, KTDIA,-1
  
  PFRSO (JLON, JLEV-1, 1)=PFRSO (JLON, JLEV, 1)+ZTEND (JLON, JLEV)*PDELP (JLON, JLEV)
  
ENDDO



ENDSUBROUTINE ACRSO_OPENACC
