INTERFACE
SUBROUTINE SIMPLICO(KM,KSMAX,KFLEV,KFLSUR,PALPHA,PDENIM,&
& PFPLUS,PFMINUS,PSIVP,PRLAPDI,PBDT2,PY,PX)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KM
INTEGER(KIND=JPIM),INTENT(IN)    :: KSMAX
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLSUR
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALPHA(KM:KSMAX+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDENIM(KM:KSMAX+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLUS(KM:KSMAX+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFMINUS(KM:KSMAX+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSIVP(KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRLAPDI(0:KSMAX)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PBDT2
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PY(2,KM:KSMAX,KFLSUR)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PX(2,KM:KSMAX,KFLSUR)
END SUBROUTINE SIMPLICO







END INTERFACE
