SUBROUTINE CUININ_OPENACC (YDCST, YDTHF, YDEPHLI, YDECUMF, KIDIA, KFDIA, KLON&
&, KLEV, PTEN, PQEN, PQSEN, PUEN, PVEN, PGEO, PAPH, KLAB, PTENH, PQENH, PQSENH&
&, PGEOH, PTU, PQU, PTD, PQD, PUU, PVU, PUD, PVD, PLU, YDSTACK)
!$ACC ROUTINE (CUININ_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE YOEPHLI,ONLY:TEPHLI
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (IN)::PTEN 
REAL (KIND=JPRB), INTENT (IN)::PQEN 
REAL (KIND=JPRB), INTENT (IN)::PQSEN 
REAL (KIND=JPRB), INTENT (IN)::PUEN 
REAL (KIND=JPRB), INTENT (IN)::PVEN 
REAL (KIND=JPRB), INTENT (IN)::PGEO 
REAL (KIND=JPRB), INTENT (IN)::PAPH 
INTEGER (KIND=JPIM), INTENT (OUT)::KLAB 
REAL (KIND=JPRB), INTENT (INOUT)::PTENH 
REAL (KIND=JPRB), INTENT (OUT)::PQENH 
REAL (KIND=JPRB), INTENT (INOUT)::PQSENH 
REAL (KIND=JPRB), INTENT (IN)::PGEOH 
REAL (KIND=JPRB), INTENT (OUT)::PTU 
REAL (KIND=JPRB), INTENT (OUT)::PQU 
REAL (KIND=JPRB), INTENT (OUT)::PTD 
REAL (KIND=JPRB), INTENT (OUT)::PQD 
REAL (KIND=JPRB), INTENT (OUT)::PUU 
REAL (KIND=JPRB), INTENT (OUT)::PVU 
REAL (KIND=JPRB), INTENT (OUT)::PUD 
REAL (KIND=JPRB), INTENT (OUT)::PVD 
REAL (KIND=JPRB), INTENT (OUT)::PLU 
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK

fxtran_acdc_temp (REAL(KIND=JPRB), PTEN_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PQEN_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PQSEN_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PUEN_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PVEN_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PGEO_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PAPH_PTR, (KLON, KLEV+1))
fxtran_acdc_temp (INTEGER(KIND=JPIM), KLAB_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PTENH_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PQENH_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PQSENH_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PGEOH_PTR, (KLON, KLEV+1))
fxtran_acdc_temp (REAL(KIND=JPRB), PTU_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PQU_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PTD_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PQD_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PUU_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PVU_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PUD_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PVD_PTR, (KLON, KLEV))
fxtran_acdc_temp (REAL(KIND=JPRB), PLU_PTR, (KLON, KLEV))

REAL (KIND=JPRB)::ZPH 
LOGICAL::LLFLAG 
INTEGER (KIND=JPIM)::JL
INTEGER (KIND=JPIM)::JK
INTEGER (KIND=JPIM)::IK
REAL (KIND=JPRB)::ZORCPD

REAL (KIND=JPRB)::ZQP
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZQSAT
REAL (KIND=JPRB)::ZQMAX
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZFOEEWL
REAL (KIND=JPRB)::ZFOEEWI
REAL (KIND=JPRB)::ZCOR
REAL (KIND=JPRB)::ZCOND1
REAL (KIND=JPRB)::ZCOND
REAL (KIND=JPRB)::Z2S
REAL (KIND=JPRB)::Z1S
REAL (KIND=JPRB)::ZF
REAL (KIND=JPRB)::ZI
REAL (KIND=JPRB)::ZL
LOGICAL::LLFLAG_CUADJTQ 

#include "fcttre.func.h"
#include "cuadjtq.func.h"
REAL (KIND=JPRB)::ZALDCP 
REAL (KIND=JPRB)::Z5ALCP 
REAL (KIND=JPRB)::Z4ES 
REAL (KIND=JPRB)::Z3ES 
REAL (KIND=JPRB)::Z2S_CUADJTQS
REAL (KIND=JPRB)::ZFOEEW
REAL (KIND=JPRB)::ZQSAT_CUADJTQS
REAL (KIND=JPRB)::ZCOR_CUADJTQS
REAL (KIND=JPRB)::ZTARG_CUADJTQS
REAL (KIND=JPRB)::ZCOND1_CUADJTQS
REAL (KIND=JPRB)::ZCOND_CUADJTQS
REAL (KIND=JPRB)::ZQP_CUADJTQS
REAL (KIND=JPRB)::ZQMAX_CUADJTQS

fxtran_acdc_assoc (PTEN_PTR, PTEN)

fxtran_acdc_assoc (PQEN_PTR, PQEN)

fxtran_acdc_assoc (PQSEN_PTR, PQSEN)

fxtran_acdc_assoc (PUEN_PTR, PUEN)

fxtran_acdc_assoc (PVEN_PTR, PVEN)

fxtran_acdc_assoc (PGEO_PTR, PGEO)

fxtran_acdc_assoc (PAPH_PTR, PAPH)

fxtran_acdc_assoc (KLAB_PTR, KLAB)

fxtran_acdc_assoc (PTENH_PTR, PTENH)

fxtran_acdc_assoc (PQENH_PTR, PQENH)

fxtran_acdc_assoc (PQSENH_PTR, PQSENH)

fxtran_acdc_assoc (PGEOH_PTR, PGEOH)

fxtran_acdc_assoc (PTU_PTR, PTU)

fxtran_acdc_assoc (PQU_PTR, PQU)

fxtran_acdc_assoc (PTD_PTR, PTD)

fxtran_acdc_assoc (PQD_PTR, PQD)

fxtran_acdc_assoc (PUU_PTR, PUU)

fxtran_acdc_assoc (PVU_PTR, PVU)

fxtran_acdc_assoc (PUD_PTR, PUD)

fxtran_acdc_assoc (PVD_PTR, PVD)

fxtran_acdc_assoc (PLU_PTR, PLU)

JL = KIDIA



ZORCPD=1._JPRB/YDCST%RCPD

DO JK=2, KLEV
  
  PTENH_PTR (JL, JK)=(MAX (YDCST%RCPD*PTEN_PTR (JL, JK-1)+PGEO_PTR (JL, JK-1), YDCST&
  &%RCPD*PTEN_PTR (JL, JK)+PGEO_PTR (JL, JK))-PGEOH_PTR (JL, JK))*ZORCPD
  PQENH_PTR (JL, JK)=PQEN_PTR (JL, JK-1)
  PQSENH_PTR (JL, JK)=PQSEN_PTR (JL, JK-1)
  ZPH =PAPH_PTR (JL, JK)
  LLFLAG =.TRUE.

  

  IF (JK>=KLEV-1.OR.JK<YDECUMF%NJKT2)  THEN
    CYCLE
  ENDIF

  IK=JK

  IF (YDEPHLI%LPHYLIN) THEN
    
    
    ZQMAX_CUADJTQS=0.5_JPRB

    

    IF (PTENH_PTR (JL, IK)>YDCST%RTT) THEN
      Z3ES =YDTHF%R3LES
      Z4ES =YDTHF%R4LES
      Z5ALCP =YDTHF%R5ALVCP
      ZALDCP =YDTHF%RALVDCP
    ELSE
      Z3ES =YDTHF%R3IES
      Z4ES =YDTHF%R4IES
      Z5ALCP =YDTHF%R5ALSCP
      ZALDCP =YDTHF%RALSDCP
    ENDIF

    
    
    
    
    
    ZQP_CUADJTQS=1.0_JPRB/ZPH 
    ZTARG_CUADJTQS=PTENH_PTR (JL, IK)
    ZFOEEW=YDTHF%R2ES*EXP (Z3ES *(ZTARG_CUADJTQS-YDCST%RTT)/(ZTARG_CUADJTQS-Z4ES ))
    ZQSAT_CUADJTQS=ZQP_CUADJTQS*ZFOEEW

    IF (ZQSAT_CUADJTQS>ZQMAX_CUADJTQS) THEN
      ZQSAT_CUADJTQS=ZQMAX_CUADJTQS
    ENDIF

    ZCOR_CUADJTQS=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT_CUADJTQS)
    ZQSAT_CUADJTQS=ZQSAT_CUADJTQS*ZCOR_CUADJTQS
    Z2S_CUADJTQS=Z5ALCP /(ZTARG_CUADJTQS-Z4ES )**2
    ZCOND1_CUADJTQS=(PQSENH_PTR (JL, IK)-ZQSAT_CUADJTQS)/(1&
    &.0_JPRB+ZQSAT_CUADJTQS*ZCOR_CUADJTQS*Z2S_CUADJTQS)
    PTENH_PTR (JL, IK)=PTENH_PTR (JL, IK)+ZALDCP *ZCOND1_CUADJTQS
    PQSENH_PTR (JL, IK)=PQSENH_PTR (JL, IK)-ZCOND1_CUADJTQS
    ZTARG_CUADJTQS=PTENH_PTR (JL, IK)
    ZFOEEW=YDTHF%R2ES*EXP (Z3ES *(ZTARG_CUADJTQS-YDCST%RTT)/(ZTARG_CUADJTQS-Z4ES ))
    ZQSAT_CUADJTQS=ZQP_CUADJTQS*ZFOEEW

    IF (ZQSAT_CUADJTQS>ZQMAX_CUADJTQS) THEN
      ZQSAT_CUADJTQS=ZQMAX_CUADJTQS
    ENDIF

    ZCOR_CUADJTQS=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT_CUADJTQS)
    ZQSAT_CUADJTQS=ZQSAT_CUADJTQS*ZCOR_CUADJTQS
    Z2S_CUADJTQS=Z5ALCP /(ZTARG_CUADJTQS-Z4ES )**2
    ZCOND1_CUADJTQS=(PQSENH_PTR (JL, IK)-ZQSAT_CUADJTQS)/(1&
    &.0_JPRB+ZQSAT_CUADJTQS*ZCOR_CUADJTQS*Z2S_CUADJTQS)
    PTENH_PTR (JL, IK)=PTENH_PTR (JL, IK)+ZALDCP *ZCOND1_CUADJTQS
    PQSENH_PTR (JL, IK)=PQSENH_PTR (JL, IK)-ZCOND1_CUADJTQS
  
  
  
  
  
  
  ELSE
    
    
    ZQMAX=0.5_JPRB

    IF (.NOT.YDEPHLI%LPHYLIN) THEN
      
      
      
      
      
      
      
      ZQP=1.0_JPRB/ZPH 
      ZQSAT=FOEEWMCU (PTENH_PTR (JL, IK))*ZQP
      ZQSAT=MIN (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      ZCOND1=(PQSENH_PTR (JL, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (PTENH_PTR (JL, IK)))
      PTENH_PTR (JL, IK)=PTENH_PTR (JL, IK)+FOELDCPMCU (PTENH_PTR (JL, IK))*ZCOND1
      PQSENH_PTR (JL, IK)=PQSENH_PTR (JL, IK)-ZCOND1
      ZQSAT=FOEEWMCU (PTENH_PTR (JL, IK))*ZQP
      ZQSAT=MIN (0.5_JPRB, ZQSAT)
      ZCOR=1.0_JPRB/(1.0_JPRB-YDCST%RETV*ZQSAT)
      ZQSAT=ZQSAT*ZCOR
      ZCOND1=(PQSENH_PTR (JL, IK)-ZQSAT)/(1.0_JPRB+ZQSAT*ZCOR*FOEDEMCU (PTENH_PTR (JL, IK)))
      PTENH_PTR (JL, IK)=PTENH_PTR (JL, IK)+FOELDCPMCU (PTENH_PTR (JL, IK))*ZCOND1
      PQSENH_PTR (JL, IK)=PQSENH_PTR (JL, IK)-ZCOND1
    
    
    ELSE
    
    
    
    
    ENDIF

  
  
  
  ENDIF

  
  PQENH_PTR (JL, JK)=MIN (PQEN_PTR (JL, JK-1), PQSEN_PTR (JL&
  &, JK-1))+(PQSENH_PTR (JL, JK)-PQSEN_PTR (JL, JK-1))
  PQENH_PTR (JL, JK)=MAX (PQENH_PTR (JL, JK), 0.0_JPRB)
  
ENDDO


PTENH_PTR (JL, KLEV)=(YDCST%RCPD*PTEN_PTR (JL, KLEV)&
&+PGEO_PTR (JL, KLEV)-PGEOH_PTR (JL, KLEV))*ZORCPD
PQENH_PTR (JL, KLEV)=PQEN_PTR (JL, KLEV)
PTENH_PTR (JL, 1)=PTEN_PTR (JL, 1)
PQENH_PTR (JL, 1)=PQEN_PTR (JL, 1)


DO JK=1, KLEV
  IK=JK-1

  IF (JK==1)  THEN
    IK=1
  ENDIF

  
  PTU_PTR (JL, JK)=PTENH_PTR (JL, JK)
  PTD_PTR (JL, JK)=PTENH_PTR (JL, JK)
  PQU_PTR (JL, JK)=PQENH_PTR (JL, JK)
  PQD_PTR (JL, JK)=PQENH_PTR (JL, JK)
  PLU_PTR (JL, JK)=0.0_JPRB
  PUU_PTR (JL, JK)=PUEN_PTR (JL, IK)
  PUD_PTR (JL, JK)=PUEN_PTR (JL, IK)
  PVU_PTR (JL, JK)=PVEN_PTR (JL, IK)
  PVD_PTR (JL, JK)=PVEN_PTR (JL, IK)
  KLAB_PTR (JL, JK)=0
  
ENDDO



ENDSUBROUTINE CUININ_OPENACC
