MODULE UTIL_MF_PHYS_FOR_TYPE_MOD

USE MF_PHYS_TYPE_MOD, ONLY : MF_PHYS_FOR_TYPE



INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_MF_PHYS_FOR_TYPE
END INTERFACE

INTERFACE ACDC_HOST
MODULE PROCEDURE ACDC_HOST_MF_PHYS_FOR_TYPE
END INTERFACE



INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_MF_PHYS_FOR_TYPE
END INTERFACE



CONTAINS





SUBROUTINE ACDC_COPY_MF_PHYS_FOR_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (MF_PHYS_FOR_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_Q, LF_T, LF_U, LF_V
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF)
  !$OMP TARGET UPDATE TO (SELF)
ENDIF
LF_U = ASSOCIATED (SELF%F_U)
IF (LF_U .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_U)
  !$OMP TARGET ENTER DATA MAP (TO: SELF%F_U)
ENDIF

LF_V = ASSOCIATED (SELF%F_V)
IF (LF_V .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_V)
  !$OMP TARGET ENTER DATA MAP (TO: SELF%F_V)
ENDIF

LF_T = ASSOCIATED (SELF%F_T)
IF (LF_T .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_T)
  !$OMP TARGET ENTER DATA MAP (TO: SELF%F_T)
ENDIF

LF_Q = ASSOCIATED (SELF%F_Q)
IF (LF_Q .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_Q)
  !$OMP TARGET ENTER DATA MAP (TO: SELF%F_Q)
ENDIF

END SUBROUTINE

SUBROUTINE ACDC_HOST_MF_PHYS_FOR_TYPE (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (MF_PHYS_FOR_TYPE), TARGET :: SELF
LOGICAL :: LF_Q, LF_T, LF_U, LF_V
LF_U = ASSOCIATED (SELF%F_U)
IF (LF_U) THEN
  CALL HOST_FIELD_3RB (SELF%F_U)
ENDIF

LF_V = ASSOCIATED (SELF%F_V)
IF (LF_V) THEN
  CALL HOST_FIELD_3RB (SELF%F_V)
ENDIF

LF_T = ASSOCIATED (SELF%F_T)
IF (LF_T) THEN
  CALL HOST_FIELD_3RB (SELF%F_T)
ENDIF

LF_Q = ASSOCIATED (SELF%F_Q)
IF (LF_Q) THEN
  CALL HOST_FIELD_3RB (SELF%F_Q)
ENDIF

END SUBROUTINE





SUBROUTINE ACDC_WIPE_MF_PHYS_FOR_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
TYPE (MF_PHYS_FOR_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_Q, LF_T, LF_U, LF_V
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LF_U = ASSOCIATED (SELF%F_U)
IF (LF_U .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_U)
ENDIF

LF_V = ASSOCIATED (SELF%F_V)
IF (LF_V .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_V)
ENDIF

LF_T = ASSOCIATED (SELF%F_T)
IF (LF_T .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_T)
ENDIF

LF_Q = ASSOCIATED (SELF%F_Q)
IF (LF_Q .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_Q)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$OMP TARGET EXIT DATA MAP (DELETE: SELF)
ENDIF
END SUBROUTINE





END MODULE
