MODULE LOAD_TPHY1_MOD

USE YOMPHY1, ONLY : TPHY1
USE PARKIND1, ONLY : JPRB, JPRD

INTERFACE LOAD
MODULE PROCEDURE LOAD_TPHY1
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TPHY1 (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TPHY1), INTENT (OUT) :: YD
REAL(KIND=JPRD) :: ZTEMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTEMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTEMP2 (:, :)
ALLOCATE (ZTEMP1 (LBOUND (YD%GF3, 1):UBOUND (YD%GF3, 1)))
READ (KLUN) ZTEMP1
YD%GF3 = ZTEMP1
DEALLOCATE (ZTEMP1)
ALLOCATE (ZTEMP1 (LBOUND (YD%GF4, 1):UBOUND (YD%GF4, 1)))
READ (KLUN) ZTEMP1
YD%GF4 = ZTEMP1
DEALLOCATE (ZTEMP1)
ALLOCATE (ZTEMP1 (LBOUND (YD%TREF4, 1):UBOUND (YD%TREF4, 1)))
READ (KLUN) ZTEMP1
YD%TREF4 = ZTEMP1
DEALLOCATE (ZTEMP1)
ALLOCATE (ZTEMP1 (LBOUND (YD%RCTVEG, 1):UBOUND (YD%RCTVEG, 1)))
READ (KLUN) ZTEMP1
YD%RCTVEG = ZTEMP1
DEALLOCATE (ZTEMP1)
ALLOCATE (ZTEMP1 (LBOUND (YD%RGL, 1):UBOUND (YD%RGL, 1)))
READ (KLUN) ZTEMP1
YD%RGL = ZTEMP1
DEALLOCATE (ZTEMP1)
ALLOCATE (ZTEMP1 (LBOUND (YD%SODELX, 1):UBOUND (YD%SODELX, 1)))
READ (KLUN) ZTEMP1
YD%SODELX = ZTEMP1
DEALLOCATE (ZTEMP1)
ALLOCATE (ZTEMP2 (LBOUND (YD%GCZ0H, 1):UBOUND (YD%GCZ0H, 1), LBOUND (YD%GCZ0H, 2):UBOUND (YD%GCZ0H, 2)))
READ (KLUN) ZTEMP2
YD%GCZ0H = ZTEMP2
DEALLOCATE (ZTEMP2)
READ (KLUN) ZTEMP0
YD%ALBGLA = ZTEMP0
READ (KLUN) ZTEMP0
YD%ALBMAX = ZTEMP0
READ (KLUN) ZTEMP0
YD%ALBMER = ZTEMP0
READ (KLUN) ZTEMP0
YD%ALBMED = ZTEMP0
READ (KLUN) ZTEMP0
YD%ALBMIN = ZTEMP0
READ (KLUN) ZTEMP0
YD%ALCRIN = ZTEMP0
READ (KLUN) ZTEMP0
YD%ALRCN1 = ZTEMP0
READ (KLUN) ZTEMP0
YD%ALRCN2 = ZTEMP0
READ (KLUN) ZTEMP0
YD%EA = ZTEMP0
READ (KLUN) ZTEMP0
YD%EC2REF = ZTEMP0
READ (KLUN) ZTEMP0
YD%EMCRIN = ZTEMP0
READ (KLUN) ZTEMP0
YD%EMMGLA = ZTEMP0
READ (KLUN) ZTEMP0
YD%EMMMER = ZTEMP0
READ (KLUN) ZTEMP0
YD%EWFC = ZTEMP0
READ (KLUN) ZTEMP0
YD%EWWILT = ZTEMP0
READ (KLUN) ZTEMP0
YD%GA = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC1 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC1S1 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC1S2 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC1S3 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC1S4 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC1Y1 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GTSVAP = ZTEMP0
READ (KLUN) ZTEMP0
YD%GVEGMX = ZTEMP0
READ (KLUN) ZTEMP0
YD%GLAIMX = ZTEMP0
READ (KLUN) ZTEMP0
YD%GNEIMX = ZTEMP0
READ (KLUN) ZTEMP0
YD%GWPIMX = ZTEMP0
READ (KLUN) ZTEMP0
YD%GCGEL = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC2 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC2REF = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC3 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC31 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GC32 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GCONV = ZTEMP0
READ (KLUN) ZTEMP0
YD%GF1 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GWFC = ZTEMP0
READ (KLUN) ZTEMP0
YD%GWLEX = ZTEMP0
READ (KLUN) ZTEMP0
YD%GWLMX = ZTEMP0
READ (KLUN) ZTEMP0
YD%GWWILT = ZTEMP0
READ (KLUN) ZTEMP0
YD%G1B = ZTEMP0
READ (KLUN) ZTEMP0
YD%G1CGSAT = ZTEMP0
READ (KLUN) ZTEMP0
YD%G1C1SAT = ZTEMP0
READ (KLUN) ZTEMP0
YD%G1P = ZTEMP0
READ (KLUN) ZTEMP0
YD%G1WSAT = ZTEMP0
READ (KLUN) ZTEMP0
YD%G2B = ZTEMP0
READ (KLUN) ZTEMP0
YD%G2CGSAT = ZTEMP0
READ (KLUN) ZTEMP0
YD%G2C1SAT = ZTEMP0
READ (KLUN) ZTEMP0
YD%G2P = ZTEMP0
READ (KLUN) ZTEMP0
YD%G2WSAT = ZTEMP0
READ (KLUN) ZTEMP0
YD%G3CGSAT = ZTEMP0
READ (KLUN) ZTEMP0
YD%GSNC1 = ZTEMP0
READ (KLUN) ZTEMP0
YD%GSNC2 = ZTEMP0
READ (KLUN) ZTEMP0
YD%HSOL = ZTEMP0
READ (KLUN) ZTEMP0
YD%HSOLIWR = ZTEMP0
READ (KLUN) ZTEMP0
YD%HSOLIT0 = ZTEMP0
READ (KLUN) ZTEMP0
YD%OMTPRO = ZTEMP0
READ (KLUN) ZTEMP0
YD%OMWPRO = ZTEMP0
READ (KLUN) ZTEMP0
YD%RC1MAX = ZTEMP0
READ (KLUN) ZTEMP0
YD%RCTGLA = ZTEMP0
READ (KLUN) ZTEMP0
YD%RCGMAX = ZTEMP0
READ (KLUN) ZTEMP0
YD%RD1 = ZTEMP0
READ (KLUN) ZTEMP0
YD%RD2GLA = ZTEMP0
READ (KLUN) ZTEMP0
YD%RD2MER = ZTEMP0
READ (KLUN) ZTEMP0
YD%RHOMAX = ZTEMP0
READ (KLUN) ZTEMP0
YD%RHOMIN = ZTEMP0
READ (KLUN) ZTEMP0
YD%RSMAX = ZTEMP0
READ (KLUN) ZTEMP0
YD%RTINER = ZTEMP0
READ (KLUN) ZTEMP0
YD%RZ0GLA = ZTEMP0
READ (KLUN) ZTEMP0
YD%RZ0MER = ZTEMP0
READ (KLUN) ZTEMP0
YD%RZHZ0G = ZTEMP0
READ (KLUN) ZTEMP0
YD%RZHZ0M = ZTEMP0
READ (KLUN) ZTEMP0
YD%TMERGL = ZTEMP0
READ (KLUN) ZTEMP0
YD%TOEXP = ZTEMP0
READ (KLUN) ZTEMP0
YD%TOLIN = ZTEMP0
READ (KLUN) ZTEMP0
YD%WCRIN = ZTEMP0
READ (KLUN) ZTEMP0
YD%WCRINC = ZTEMP0
READ (KLUN) ZTEMP0
YD%WCRING = ZTEMP0
READ (KLUN) ZTEMP0
YD%WNEW = ZTEMP0
READ (KLUN) ZTEMP0
YD%WPMX = ZTEMP0
READ (KLUN) ZTEMP0
YD%WSMX = ZTEMP0
READ (KLUN) ZTEMP0
YD%XCRINR = ZTEMP0
READ (KLUN) ZTEMP0
YD%XCRINV = ZTEMP0
READ (KLUN) YD%LALBMERCLIM
READ (KLUN) YD%LIMC
READ (KLUN) YD%LIMW
READ (KLUN) YD%LC1VAP
READ (KLUN) YD%LCLS_HS
READ (KLUN) YD%NTVGLA
READ (KLUN) YD%NTVMER
READ (KLUN) ZTEMP0
YD%GCGELS = ZTEMP0
READ (KLUN) ZTEMP0
YD%GVEGMXS = ZTEMP0
READ (KLUN) ZTEMP0
YD%GLAIMXS = ZTEMP0
READ (KLUN) ZTEMP0
YD%GNEIMXS = ZTEMP0
READ (KLUN) ZTEMP0
YD%ALB1 = ZTEMP0
READ (KLUN) ZTEMP0
YD%ALB2 = ZTEMP0
READ (KLUN) ZTEMP0
YD%RLAIMX = ZTEMP0
READ (KLUN) ZTEMP0
YD%RLAI = ZTEMP0
READ (KLUN) ZTEMP0
YD%ACLS_HS = ZTEMP0
READ (KLUN) YD%NCHSP
END SUBROUTINE


END MODULE
