INTERFACE
SUBROUTINE CPG_GP_GPINISLB_PART1_EXPL (YDCPG_BNDS, YDCPG_DYN9&
&, YDCPG_MISC, YDCPG_OPTS, YDGEOMETRY, YDMODEL, YDVARS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_MISC_TYPE, CPG_TND_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_DYN_TYPE), INTENT (INOUT)::YDCPG_DYN9
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
ENDSUBROUTINE
END INTERFACE
