SUBROUTINE CPG_DIA_FLU_OUTLINE_001 (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_OUT&
&, PNUCLS, PNVCLS, PUCLS, PUGST, PVCLS, PVGST)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_OUT_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_OUT_TYPE), INTENT (IN)::YDMF_PHYS_OUT
REAL (KIND=JPRB), INTENT (INOUT)::PNUCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PNVCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PUCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PUGST (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PVCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PVGST (YDCPG_OPTS%KLON)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('CPG_DIA_FLU_OUTLINE_001', 0, ZHOOK_HANDLE)
PUCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%UCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
PVCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%VCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
PNUCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%NUCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
PNVCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%NVCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
PUGST (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%UGST (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
PVGST (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%VGST (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
IF (LHOOK) CALL DR_HOOK ('CPG_DIA_FLU_OUTLINE_001', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
