INTERFACE
SUBROUTINE CPG_GP_HYD_OUTLINE_000 (YDCPG_BNDS, YDCPG_DYN0, YDCPG_OPTS, YDGEOMETRY&
&, YDMODEL, P_RPREF_T0, P_XYBDER_ALPHL_T0, P_XYBDER_ALPHM_T0, P_XYBDER_ALPHPLL_T0&
&, P_XYBDER_ALPHPLM_T0, P_XYBDER_LNPRL_T0, P_XYBDER_LNPRM_T0)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_DYN_TYPE, CPG_TND_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_DYN_TYPE), INTENT (INOUT)::YDCPG_DYN0
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (INOUT)::P_RPREF_T0 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::P_XYBDER_ALPHL_T0 (YDGEOMETRY&
&%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::P_XYBDER_ALPHM_T0 (YDGEOMETRY&
&%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::P_XYBDER_ALPHPLL_T0 &
&(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::P_XYBDER_ALPHPLM_T0 &
&(YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::P_XYBDER_LNPRL_T0 (YDGEOMETRY&
&%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::P_XYBDER_LNPRM_T0 (YDGEOMETRY&
&%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
ENDSUBROUTINE
END INTERFACE
