SUBROUTINE CPG_GP_GP_SPV (YDCPG_BNDS, YDCPG_DYN0, YDCPG_DYN9, YDGEOMETRY, YDMODEL, YDVARS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_MISC_TYPE, CPG_TND_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_DYN_TYPE), INTENT (INOUT)::YDCPG_DYN0
TYPE (CPG_DYN_TYPE), INTENT (INOUT)::YDCPG_DYN9
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
#include "gp_spv.intfb.h"
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('CPG_GP_GP_SPV', 0, ZHOOK_HANDLE)
CALL GP_SPV (YDGEOMETRY, YDMODEL%YRML_DYN%YRDYN, YDMODEL%YRML_DYN%YRDYNA, YDMODEL%YRML_PHY_MF&
&%YRSIMPHL,.FALSE., YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDVARS%SP%T0, YDVARS%SP%DL, YDVARS&
&%SP%DM, YDVARS%SP%T9, YDVARS%SP%DL9, YDVARS%SP%DM9, YDCPG_DYN0%PRE, YDCPG_DYN0%PREL,&
& YDCPG_DYN0%PREM, YDCPG_DYN9%PRE, YDCPG_DYN9%PREL, YDCPG_DYN9%PREM)
IF (LHOOK) CALL DR_HOOK ('CPG_GP_GP_SPV', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
