INTERFACE
SUBROUTINE GPMPFC_EXPL_OUTLINE_000 (YDCPG_BNDS, YDCPG_OPTS, ZGM, PGM)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
REAL (KIND=JPRB), INTENT (INOUT), CONTIGUOUS, POINTER::ZGM (:)
REAL (KIND=JPRB), INTENT (IN), TARGET::PGM (YDCPG_OPTS%KLON)
ENDSUBROUTINE
END INTERFACE
