INTERFACE
SUBROUTINE LAPINEB_NVLAG2 (YDCPG_BNDS, YDGEOMETRY, YDVARS, PC9, PDP9, PVWEI)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
REAL (KIND=JPRB), INTENT (INOUT)::PC9 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDP9 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PVWEI (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
ENDSUBROUTINE
END INTERFACE
