INTERFACE
SUBROUTINE LAPINEB_NVLAG3 (YDCPG_BNDS, YDCPG_SL2, YDGEOMETRY,&
& YDMODEL, YDVARS, PC9, PC9_SI, PDP9, PSPT1, PSPTO, PVWEI)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE CPG_SL2_TYPE_MOD,ONLY:CPG_SL2_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_SL2_TYPE), INTENT (IN)::YDCPG_SL2
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
REAL (KIND=JPRB), INTENT (INOUT)::PC9 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PC9_SI (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDP9 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSPT1 (YDGEOMETRY%YRDIM%NPROMA, 0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB), INTENT (INOUT)::PSPTO (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::PVWEI (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
ENDSUBROUTINE
END INTERFACE
