INTERFACE
SUBROUTINE LATTEX_LRHS_CURV (YDCPG_BNDS, YDCPG_SL1, YDGEOMETRY, YDML_DYN, YDVARS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_SL1_TYPE_MOD,ONLY:CPG_SL1B_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE MODEL_DYNAMICS_MOD,ONLY:MODEL_DYNAMICS_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_SL1B_TYPE), INTENT (INOUT)::YDCPG_SL1
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN)::YDML_DYN
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
ENDSUBROUTINE
END INTERFACE
