INTERFACE
SUBROUTINE ACVPPKF_PART3 (LDCONDWT, LDOCHTRANS, K_KCH1, YDCPG_BNDS, YDCPG_OPTS, YDCST, YDML_PHY_MF&
&, PEPS, PSMD, PVMD, PWMD, KCLBAS, KCLBASS, KCLTOP, KCLTOPS, K_KCLBAS, K_KCLTOP, KNLAB, KNND&
&, PAPRSF, PCP, PDIFCQ, PDIFCS, PFCCQL, PFCCQN, PNEBPP, PPRODTH, PQCPP, PR, PT, PDPSG, PDQIDT&
&, PDQLDT, PDQVDT, PDTDT, PDUDT, PDVDT, PLS, PLV, PQC, PRCTEN, PRITEN, PRVTEN, PSHAL_ZCH1TEN&
&, PTTEN, PUMF, PUMFMAX, PUQL, PUQV, PURCI, PURV, PUTEN, PVTEN, PZUMF)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE YOMCST,ONLY:TCST
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

LOGICAL, INTENT (INOUT)::LDCONDWT
LOGICAL, INTENT (INOUT)::LDOCHTRANS
INTEGER (KIND=JPIM), INTENT (IN)::K_KCH1
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
REAL (KIND=JPRB), INTENT (INOUT)::PEPS
REAL (KIND=JPRB), INTENT (INOUT)::PSMD
REAL (KIND=JPRB), INTENT (INOUT)::PVMD
REAL (KIND=JPRB), INTENT (INOUT)::PWMD
INTEGER (KIND=JPIM), INTENT (INOUT)::KCLBAS (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCLBASS (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCLTOP (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCLTOPS (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::K_KCLBAS (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::K_KCLTOP (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KNLAB (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
INTEGER (KIND=JPIM), INTENT (OUT)::KNND (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PCP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDIFCQ (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDIFCS (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFCCQL (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PFCCQN (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PNEBPP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PPRODTH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PQCPP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PR (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDPSG (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDQIDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDQLDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDQVDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDTDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDUDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDVDT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PLS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PLV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PQC (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRCTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRITEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRVTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSHAL_ZCH1TEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, K_KCH1)
REAL (KIND=JPRB), INTENT (INOUT)::PTTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUMFMAX (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PUQL (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUQV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PURCI (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PURV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PVTEN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PZUMF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
ENDSUBROUTINE
END INTERFACE
