INTERFACE
SUBROUTINE APL_ARPEGE_ACCLPH (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS&
&, YDMF_PHYS_BASE_STATE, YDMODEL, KMOC_CLPH, PBLH, PCP, PQV)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE, CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_PHY_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MODEL), INTENT (IN)::YDMODEL
INTEGER (KIND=JPIM), INTENT (INOUT)::KMOC_CLPH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PBLH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PCP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PQV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
ENDSUBROUTINE
END INTERFACE
