SUBROUTINE APL_ARPEGE_SOIL_HYDRO_ACVEG (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE&
&, YDMF_PHYS_SURF, YDMODEL, PCHROV, PFLU_NEIJ, PFLU_QSAT, PFLU_QSATS, PFLU_VEG&
&, PGWDCS, PHQ, PHTR, PHU, PQV, PWFC, PWLMX, PWWILT)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (IN)::PCHROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PFLU_NEIJ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PFLU_QSAT (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PFLU_QSATS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PFLU_VEG (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGWDCS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PHQ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PHTR (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PHU (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PQV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PWFC (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PWLMX (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PWWILT (YDCPG_OPTS%KLON)
#include "acveg.intfb.h"
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_SOIL_HYDRO_ACVEG', 0, ZHOOK_HANDLE)
CALL ACVEG (YDMODEL%YRML_PHY_MF%YRPHY, YDMODEL%YRML_PHY_MF%YRPHY1, YDCPG_BNDS%KIDIA, YDCPG_BNDS&
&%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, YDMF_PHYS%OUT%FRSO, PQV, PFLU_QSAT, YDMF_PHYS_BASE_STATE&
&%T, YDMF_PHYS_SURF%GSD_VV%PD2, YDMF_PHYS_SURF%GSD_VF%PLSM, YDMF_PHYS_SURF%GSD_VV%PIVEG, YDMF_PHYS_SURF&
&%GSD_VV%PLAI, PFLU_NEIJ, PFLU_VEG, YDMF_PHYS_SURF%GSD_VV%PRSMIN, PCHROV, PGWDCS, PWFC, YDMF_PHYS_BASE_STATE&
&%YGSP_RR%FC, PWWILT, YDMF_PHYS_BASE_STATE%YGSP_SB%Q (:, 1), PFLU_QSATS, PHQ, PHTR, PHU, YDMF_PHYS_SURF&
&%GSD_VV%PHV, PWLMX)
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_SOIL_HYDRO_ACVEG', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
