INTERFACE
SUBROUTINE APL_ARPEGE_TURBULENCE_PART2 (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE&
&, YDMODEL, PECTCLS, PKCLS, PKUROV2, PPFL_FTKE, PPRODTH, PTKE1, PUSLE)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (INOUT)::PECTCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PKCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PKUROV2 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PPFL_FTKE (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PPRODTH (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PTKE1 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUSLE (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
ENDSUBROUTINE
END INTERFACE
