SUBROUTINE APL_ARPEGE_AEROSOLS_FOR_RADIATION_RADAER (LDAERO, YDCPG_BNDS, YDCPG_OPTS&
&, YDMF_PHYS_BASE_STATE, YDMF_PHYS_SURF, YDMODEL, PAER, PAERINDS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

LOGICAL, INTENT (INOUT)::LDAERO
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (OUT)::PAER (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 6)
REAL (KIND=JPRB), INTENT (OUT)::PAERINDS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
#include "radaer.intfb.h"
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPRB)::ZAEDES (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZAELAN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZAESEA (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZAESOO (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZAESUL (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZAEVOL (YDCPG_OPTS%KLON)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_AEROSOLS_FOR_RADIATION_RADAER', 0, ZHOOK_HANDLE)

IF (LDAERO) THEN

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    ZAESEA (JLON)=YDMF_PHYS_SURF%GSD_VA%PSEA (JLON)
    ZAELAN (JLON)=YDMF_PHYS_SURF%GSD_VA%PLAN (JLON)
    ZAESOO (JLON)=YDMF_PHYS_SURF%GSD_VA%PSOO (JLON)
    ZAEDES (JLON)=YDMF_PHYS_SURF%GSD_VA%PDES (JLON)
  ENDDO

ELSE

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    ZAESEA (JLON)=0.0_JPRB
    ZAELAN (JLON)=0.0_JPRB
    ZAESOO (JLON)=0.0_JPRB
    ZAEDES (JLON)=0.0_JPRB
  ENDDO

ENDIF


DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
  ZAESUL (JLON)=0.0_JPRB
ENDDO


DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
  ZAEVOL (JLON)=0.0_JPRB
ENDDO


IF ((YDMODEL%YRML_PHY_RAD%YRERAD%NAER/=0).AND.LDAERO) THEN
  CALL RADAER (YDMODEL%YRML_PHY_RAD%YREAERD, YDMODEL%YRML_PHY_RAD%YRERAD, YDMODEL%YRML_PHY_MF%YRPHY&
  &, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, YDMF_PHYS_BASE_STATE&
  &%YCPG_PHY%PREHYD, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, YDMF_PHYS_BASE_STATE%T, YDMF_PHYS_BASE_STATE&
  &%YGSP_RR%T, ZAESEA, ZAELAN, ZAESOO, ZAEDES, ZAESUL, ZAEVOL, PAER, PAERINDS)
ENDIF

IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_AEROSOLS_FOR_RADIATION_RADAER', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
