SUBROUTINE APL_ARPEGE (YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE, YDGEOMETRY, YDCPG_BNDS&
&, YDCPG_OPTS, YDCPG_MISC, YDCPG_GPAR, YDCPG_PHY0, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF&
&, YDCPG_SL2, YDVARS, YDCFU, YDMODEL, YDDDH, YDPHYSMWAVE)
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE, CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_PHY_TYPE
USE CPG_SL2_TYPE_MOD,ONLY:CPG_SL2_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_NEXT_STATE_TYPE_MOD,ONLY:MF_PHYS_NEXT_STATE_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE DDH_MIX,ONLY:TYP_DDH
USE YOE_PHYS_MWAVE,ONLY:TEPHYSMWAVE
USE YOMCFU,ONLY:TCFU

IMPLICIT NONE


TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MF_PHYS_NEXT_STATE_TYPE), INTENT (INOUT)::YDMF_PHYS_NEXT_STATE
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (CPG_GPAR_TYPE), INTENT (INOUT)::YDCPG_GPAR
TYPE (CPG_PHY_TYPE), INTENT (IN)::YDCPG_PHY0
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (CPG_DYN_TYPE), INTENT (IN)::YDCPG_DYN0
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (CPG_SL2_TYPE), INTENT (INOUT)::YDCPG_SL2
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (TCFU), INTENT (IN)::YDCFU
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (TYP_DDH), INTENT (INOUT)::YDDDH
TYPE (TEPHYSMWAVE), INTENT (INOUT)::YDPHYSMWAVE

#include "mf_phys_fpl_part1.intfb.h"
#include "apl_arpege_precips.intfb.h"
#include "apl_arpege_edr.intfb.h"
#include "apl_arpege_bayrad.intfb.h"
#include "apl_arpege_outline_024.intfb.h"
#include "apl_arpege_outline_023.intfb.h"
#include "apl_arpege_outline_022.intfb.h"
#include "apl_arpege_ppwetpoint.intfb.h"
#include "apl_arpege_zde2mr.intfb.h"
#include "apl_arpege_zbay_qrconv.intfb.h"
#include "apl_arpege_acvisih.intfb.h"
#include "apl_arpege_acevadcape.intfb.h"
#include "apl_arpege_acdrme.intfb.h"
#include "apl_arpege_qngcor.intfb.h"
#include "apl_arpege_turbulence_part2.intfb.h"
#include "apl_arpege_acdrag.intfb.h"
#include "apl_arpege_frsopt.intfb.h"
#include "apl_arpege_diftq.intfb.h"
#include "apl_arpege_acclph.intfb.h"
#include "apl_arpege_achmt.intfb.h"
#include "apl_arpege_achmtls.intfb.h"
#include "apl_arpege_zdphiv.intfb.h"
#include "apl_arpege_acsol.intfb.h"
#include "apl_arpege_actqsat.intfb.h"
#include "apl_arpege_checkmv.intfb.h"
#include "apl_arpege_plsm.intfb.h"
#include "apl_arpege_aplpar_init.intfb.h"
#include "apl_arpege_zrdg_lcvq.intfb.h"
#include "apl_arpege_cpphinp.intfb.h"
#include "mf_phys_save_phsurf_part1.intfb.h"


#include "apl_arpege_init.intfb.h"


#include "apl_arpege_init_surfex.intfb.h"














#include "mf_phys_fpl_part2.intfb.h"
#include "mf_phys_mocon.intfb.h"

#include "mf_phys_save_phsurf_part2.intfb.h"
#include "mf_phys_transfer.intfb.h"


#include "aplpar_flexdia.intfb.h"
#include "apl_arpege_oceanic_fluxes.intfb.h"
#include "apl_wind_gust.intfb.h"
#include "apl_arpege_shallow_convection_and_turbulence.intfb.h"
#include "apl_arpege_albedo_computation.intfb.h"
#include "apl_arpege_aerosols_for_radiation.intfb.h"
#include "apl_arpege_cloudiness.intfb.h"
#include "apl_arpege_radiation.intfb.h"
#include "apl_arpege_soil_hydro.intfb.h"
#include "apl_arpege_surface.intfb.h"
#include "apl_arpege_deep_convection.intfb.h"

#include "apl_arpege_precipitation.intfb.h"
#include "apl_arpege_hydro_budget.intfb.h"
#include "apl_arpege_surface_update.intfb.h"
#include "apl_arpege_atmosphere_update.intfb.h"
#include "apl_arpege_dprecips.intfb.h"
#include "apl_arpege_mwave.intfb.h"
REAL (KIND=JPRB)::ZDIFEXT (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG, YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)
INTEGER (KIND=JPIM)::INLAB_CVPP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZXUROV (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZXTROV (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZMRIPP (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZNBVNO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZKTROV (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZKUROV2 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZKUROV (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZKQLROV (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZKQROV (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZNEBS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQLIS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZNEBS0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQLIS0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZNEBC0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZNEBDIFF (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZNEBCH (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZUNEBH (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZFPCOR (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPOID (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQI (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQL (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQR (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZTENHA (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZTENQVA (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZFPLSL (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZFPLSN (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSEDIQL (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSEDIQI (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZDIFCVPPQ (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZDIFCVPPS (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZDIFCVPPU (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZDIFCVPPV (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZEDMFQ (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZEDMFS (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZEDMFU (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZEDMFV (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZMF_UP (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCONDCVPPL (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCONDCVPPI (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPRODTH_CVPP (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPRODTH (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)

REAL (KIND=JPRB)::ZXDROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZXHROV (YDCPG_OPTS%KLON)


REAL (KIND=JPRB)::ZCDROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZCHROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZDQSTS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZGWDCS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZHQ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZHU (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZHTR (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZRTI (YDCPG_OPTS%KLON)



REAL (KIND=JPRB)::ZWFC (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZWPMX (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZWLMX (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZWSEQ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZWSMX (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZWWILT (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZC3 (YDCPG_OPTS%KLON)

REAL (KIND=JPRB)::ZCN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZNEIJG (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZNEIJV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZPCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZBLH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZQO3 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZAER (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 6)
REAL (KIND=JPRB)::ZAERINDS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZDPHIT (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZDPHIV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZTRSOD (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZCTRSO (YDCPG_OPTS%KLON, 0:1)
REAL (KIND=JPRB)::ZCEMTR (YDCPG_OPTS%KLON, 0:1)
REAL (KIND=JPRB)::ZALBP (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB)::ZALBD (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB)::ZSFSWDIF (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB)::ZSFSWDIR (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB)::ZTRSODIF (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB)::ZTRSODIR (YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
REAL (KIND=JPRB)::ZSUDU (YDCPG_OPTS%KLON)


REAL (KIND=JPRB)::ZTENT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)

REAL (KIND=JPRB)::ZCOEFN (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQCO2 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZALBDIR (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZCLCT_RAD (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZQLI_CVPP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZNEB_CVPP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCFBTH (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSTATI
REAL (KIND=JPRB)::ZRHGMT
REAL (KIND=JPRB)::ZDTMSE
REAL (KIND=JPRB)::ZCFATH (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCFAU (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCFBU (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCFBV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSRAIN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSSNOW (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSGROUPEL (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZTSN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZCE (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZCEROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZCRTI (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZXURO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZXQRO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZXTRO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)


REAL (KIND=JPRB)::ZTKE1 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)

REAL (KIND=JPRB)::ZALPHA1 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZCOEFA (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZLVT (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQICE (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZDIFWQ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZDIFWS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSC_FEVI (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSC_FEVN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSC_FCLL (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSC_FCLN (YDCPG_OPTS%KLON)

REAL (KIND=JPRB)::ZAIPCMT (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZQLC (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQIC (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQLI_CVP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZQC_DET_PCMT (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZDCAPE (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZDECRD (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM)::IMOC_CLPH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZBAY_QRCONV (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZBAY_QSCONV (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZDSA_C1 (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZDSA_C2 (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZDSA_CPS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZDSA_LHS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZDSA_RS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZFLU_CDN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZFLU_CD (YDCPG_OPTS%KLON)

REAL (KIND=JPRB)::ZFLU_CH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZFLU_EMIS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZFLU_FEVI (YDCPG_OPTS%KLON, 1:YDMODEL%YRML_PHY_G%YRDPHY%NTSSG+1)
REAL (KIND=JPRB)::ZFLU_NEIJ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZFLU_QSATS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZFLU_QSAT (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZFLU_VEG (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZMSC_FRMQ (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZFCHQ (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZMSC_LH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZMSC_LSCPE (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZMSC_QW (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZMSC_TW (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPFL_FEFB1 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPFL_FEFB2 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPFL_FEFB3 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPFL_FPLCH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPFL_FPLSH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPFL_FTKEI (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPFL_FTKE (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZPRC_DPRECIPS2 (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC2)
REAL (KIND=JPRB)::ZPRC_DPRECIPS (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC)
REAL (KIND=JPRB)::ZRDG_CVGQ (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZRDG_CVGT (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZRDG_LCVQ (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZRDG_MU0LU (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZRDG_MU0M (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZRDG_MU0N (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZRDG_MU0 (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZRDG_SOLO (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSAV_DDAL (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSAV_DDOM (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSAV_ENTCH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSAV_FHPS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSAV_GZ0F (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSAV_GZ0HF (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSAV_HV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSAV_PBLH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSAV_QSH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSAV_UDAL (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSAV_UDGRO (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZSAV_UDOM (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZSAV_UNEBH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)


LOGICAL::LLREDPR
LOGICAL::LLHMT
LOGICAL::LLCLS
REAL (KIND=JPRB)::ZEPSNEB
REAL (KIND=JPRB)::ZEPS0
REAL (KIND=JPRB)::ZRVMD
REAL (KIND=JPRB)::ZUSLE (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB)::ZKCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB)::ZECTCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE', 0, ZHOOK_HANDLE)




LLREDPR=.FALSE.
ZRVMD=YDMODEL%YRCST%RV-YDMODEL%YRCST%RD

IF (YDCPG_OPTS%LCONFX) THEN
  ZDTMSE=0.01_JPRB
  ZSTATI=YDMODEL%YRML_GCONF%YRRIP%RSTATI+(ZDTMSE-YDMODEL%YRML_GCONF%YRRIP%TSTEP)*0.5_JPRB
ELSE
  ZDTMSE=YDMODEL%YRML_PHY_MF%YRPHY2%TSPHY
  ZSTATI=YDMODEL%YRML_GCONF%YRRIP%RSTATI
ENDIF

ZRHGMT=REAL (YDMODEL%YRML_GCONF%YRRIP%RHGMT, JPRB)
CALL APL_ARPEGE_CPPHINP (YDCPG_BNDS, YDCPG_DYN0, YDCPG_OPTS, YDCPG_PHY0, YDGEOMETRY, YDMODEL&
&, YDVARS, ZRDG_CVGQ, ZRDG_CVGT, ZRDG_MU0, ZRDG_MU0LU, ZRDG_MU0M, ZRDG_MU0N, ZRDG_SOLO)
CALL APL_ARPEGE_ZRDG_LCVQ (YDCPG_BNDS, YDCPG_OPTS, YDMODEL, ZFLU_QSATS, ZQCO2, ZRDG_CVGQ, ZRDG_LCVQ)
CALL MF_PHYS_FPL_PART1 (YDCPG_BNDS, YDCPG_OPTS, ZPFL_FPLCH&
&, ZPFL_FPLSH, YDVARS%CPF%T0, YDVARS%SPF%T0, YDMODEL)

IF (YDCPG_OPTS%LCONFX) THEN
  CALL MF_PHYS_SAVE_PHSURF_PART1 (YDCPG_BNDS, YDCPG_OPTS, ZSAV_DDAL, ZSAV_DDOM, ZSAV_ENTCH, ZSAV_FHPS, ZSAV_GZ0F&
  &, ZSAV_GZ0HF, ZSAV_HV, ZSAV_PBLH, ZSAV_QSH, ZSAV_UDAL, ZSAV_UDGRO, ZSAV_UDOM, ZSAV_UNEBH, YDMF_PHYS_SURF&
  &%GSD_VF%PZ0F, YDMF_PHYS_SURF%GSD_VH%PPBLH, YDMF_PHYS_SURF%GSD_VH%PQSH, YDMF_PHYS_SURF%GSD_VH%PSPSH, YDMF_PHYS_SURF&
  &%GSD_VK%PUDGRO, YDMF_PHYS_SURF%GSD_VV%PHV, YDMF_PHYS_SURF%GSD_VV%PZ0H, YDVARS%DAL%T0, YDVARS%DOM%T0,&
  & YDVARS%UAL%T0, YDVARS%UEN%T0, YDVARS%UNEBH%T0, YDVARS%UOM%T0, YDMODEL)
ENDIF

CALL APL_ARPEGE_APLPAR_INIT (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_SURF, YDMODEL, IMOC_CLPH,&
& ZDSA_C1, ZDSA_C2, ZDSA_CPS, ZDSA_LHS, ZDSA_RS, ZFCHQ, ZFLU_CD, ZFLU_CDN, ZFLU_CH, ZFLU_EMIS&
&, ZFLU_FEVI, ZFLU_NEIJ, ZFLU_QSAT, ZFLU_QSATS, ZFLU_VEG, ZMSC_FRMQ, ZMSC_LH, ZMSC_LSCPE&
&, ZMSC_QW, ZMSC_TW, ZPFL_FEFB1, ZPFL_FEFB2, ZPFL_FEFB3, ZPFL_FTKE, ZPFL_FTKEI)
CALL APL_ARPEGE_PLSM (YDCPG_BNDS, YDMF_PHYS_SURF)

IF (YDMODEL%YRML_PHY_MF%YRPHY%LGCHECKMV) THEN
  CALL APL_ARPEGE_CHECKMV (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_BASE_STATE&
  &, YDMF_PHYS_SURF, YDMODEL, YDVARS, ZRDG_MU0)
ENDIF

CALL APL_ARPEGE_INIT (YDMODEL%YRCST, YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS&
&, YDMF_PHYS_SURF, YDVARS, YDMODEL, IMOC_CLPH, INLAB_CVPP, ZAER, ZAERINDS, ZAIPCMT, ZALBD, ZALBP, ZALPHA1&
&, ZCEMTR, ZCFATH, ZCFAU, ZCFBTH, ZCFBU, ZCFBV, ZCOEFA, ZCONDCVPPI, ZCONDCVPPL, ZCTRSO, ZDECRD, ZDIFCVPPQ&
&, ZDIFCVPPS, ZDIFCVPPU, ZDIFCVPPV, ZDIFWQ, ZDIFWS, ZEDMFQ, ZEDMFS, ZEDMFU, ZEDMFV, ZEPS0, ZEPSNEB&
&, ZFPCOR, ZKQLROV, ZKQROV, ZKTROV, ZKUROV, ZLVT, ZMF_UP, ZMRIPP, ZNEBC0, ZNEBCH, ZNEBDIFF, ZNEBS,&
& ZNEBS0, ZNEB_CVPP, ZPFL_FPLCH, ZPFL_FPLSH, ZPOID, ZPRODTH_CVPP, ZQC_DET_PCMT, ZQI, ZQIC, ZQICE, ZQL&
&, ZQLC, ZQLIS, ZQLIS0, ZQLI_CVP, ZQLI_CVPP, ZQO3, ZQR, ZQS, ZQV, ZSC_FCLL, ZSC_FCLN, ZSC_FEVI, ZSC_FEVN&
&, ZSEDIQI, ZSEDIQL, ZSFSWDIF, ZSFSWDIR, ZSUDU, ZTENHA, ZTENQVA, ZTENT, ZTRSOD, ZTRSODIF, ZTRSODIR&
&, ZUNEBH, ZXDROV, ZXHROV, ZXQRO, ZXTRO, ZXTROV, ZXURO, ZXUROV)
CALL APL_ARPEGE_ACTQSAT (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS_BASE_STATE&
&, YDMODEL, ZFLU_QSAT, ZMSC_LH, ZMSC_LSCPE, ZMSC_QW, ZMSC_TW, ZQV)

IF (.NOT.YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) THEN
  CALL APL_ARPEGE_ACSOL (LLHMT, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE, YDMF_PHYS_SURF&
  &, YDMODEL, ZC3, ZCN, ZDSA_C1, ZDSA_C2, ZNEIJG, ZNEIJV, ZWFC, ZWPMX, ZWSEQ, ZWSMX, ZWWILT)
ENDIF

CALL APL_ARPEGE_INIT_SURFEX (YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDCPG_GPAR&
&, YDMF_PHYS, YDVARS, YDMODEL, ZALBD, ZALBP, ZFLU_EMIS, ZSGROUPEL, ZSRAIN, ZSSNOW, ZTSN)
CALL APL_ARPEGE_ZDPHIV (YDCPG_BNDS, YDCPG_OPTS, YDMODEL, ZDPHIT, ZDPHIV)
LLCLS=.TRUE.
LLHMT=.TRUE.

IF (YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) THEN
  CALL APL_ARPEGE_ACHMTLS (LLCLS, YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE, YDMODEL&
  &, ZRVMD, ZDPHIT, ZDSA_CPS, ZDSA_LHS, ZFLU_CD, ZFLU_CDN, ZGWDCS, ZMRIPP, ZNBVNO, ZPCLS, ZRTI)
ELSE
  CALL APL_ARPEGE_ACHMT (LLCLS, LLHMT, YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE&
  &, YDMF_PHYS_SURF, YDMODEL, ZCDROV, ZCHROV, ZDPHIT, ZDPHIV, ZDQSTS, ZDSA_CPS, ZDSA_RS, ZFLU_CD&
  &, ZFLU_CDN, ZFLU_CH, ZFLU_NEIJ, ZFLU_QSATS, ZFLU_VEG, ZGWDCS, ZHQ, ZHU, ZMRIPP, ZNBVNO, ZNEIJG&
  &, ZNEIJV, ZPCLS, ZPFL_FPLCH, ZPFL_FPLSH, ZQV, ZRTI, ZWFC, ZXDROV, ZXHROV)
ENDIF

CALL APL_ARPEGE_ACCLPH (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS&
&, YDMF_PHYS_BASE_STATE, YDMODEL, IMOC_CLPH, ZBLH, ZCP, ZQV)
CALL APL_ARPEGE_OCEANIC_FLUXES (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS&
&, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, LLHMT, ZCDROV, ZCEROV, ZCHROV, ZDPHIT&
&, ZDPHIV, ZDSA_RS, ZFLU_CD, ZFLU_CDN, ZFLU_CH, ZFLU_QSATS)
CALL APL_WIND_GUST (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS&
&, YDMF_PHYS, YDVARS, YDMODEL, IMOC_CLPH, ZBLH, ZDCAPE)
CALL APL_ARPEGE_SHALLOW_CONVECTION_AND_TURBULENCE (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC&
&, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, YDDDH, INLAB_CVPP, ZCDROV, ZCHROV, ZCOEFN, ZCONDCVPPI, ZCONDCVPPL&
&, ZDIFCVPPQ, ZDIFCVPPS, YDMODEL%YRML_PHY_MF%YRPHY0%REPS, ZFLU_CD, ZFLU_CH, ZKQLROV, ZKQROV, ZKTROV&
&, ZKUROV, ZKUROV2, ZMSC_LSCPE, ZNBVNO, ZNEBS, ZNEBS0, ZNEB_CVPP, ZPFL_FPLCH, ZPFL_FTKE, ZPFL_FTKEI&
&, ZPRODTH_CVPP, ZQI, ZQIC, ZQL, ZQLC, ZQLIS, ZQLIS0, ZQLI_CVPP, ZQV, ZQR, ZQS, ZTKE1, ZXTROV, ZXUROV&
&, ZUSLE, ZKCLS, ZECTCLS, ZPRODTH, ZEDMFQ, ZEDMFS, ZEDMFU, ZEDMFV, ZMF_UP)
CALL APL_ARPEGE_ALBEDO_COMPUTATION (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS&
&, YDMF_PHYS_SURF, YDMODEL, ZALBD, ZALBP, ZEPS0, ZFLU_EMIS, ZFLU_NEIJ, ZRDG_MU0, ZALBDIR)
CALL APL_ARPEGE_AEROSOLS_FOR_RADIATION (YDMF_PHYS_BASE_STATE, YDCPG_BNDS&
&, YDCPG_OPTS, YDMF_PHYS_SURF, YDMODEL, ZAER, ZAERINDS)
CALL APL_ARPEGE_CLOUDINESS (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC&
&, YDMF_PHYS, YDVARS, YDMODEL, LLREDPR, ZAIPCMT, ZBLH, ZDECRD, ZFLU_QSAT, ZMSC_QW&
&, ZNEBC0, ZNEBCH, ZNEBS, ZNEBS0, ZNEB_CVPP, ZPFL_FPLCH, ZQI, ZQL, ZQLIS, ZQLIS0&
&, ZQLI_CVP, ZQLI_CVPP, ZQV, ZUNEBH, ZCLCT_RAD, YDGEOMETRY%YRSTA)
CALL APL_ARPEGE_RADIATION (YDMF_PHYS_BASE_STATE, YDCFU, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC&
&, YDCPG_GPAR, YDMF_PHYS, YDMF_PHYS_SURF, YDVARS, YDMODEL, ZCLCT_RAD, ZALBDIR, ZDECRD, ZAER, ZAERINDS&
&, ZALBD, ZALBP, ZQCO2, ZCEMTR, ZCTRSO, ZFLU_EMIS, ZFLU_QSAT, ZQO3, ZQR, ZQS, ZQV, ZRDG_MU0, ZRDG_SOLO&
&, ZRDG_MU0LU, ZRDG_MU0M, ZSFSWDIF, ZSFSWDIR, ZSUDU, ZTENT, ZTRSOD, ZTRSODIF, ZTRSODIR)
CALL APL_ARPEGE_SOIL_HYDRO (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS&
&, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, ZCHROV, ZFLU_NEIJ, ZFLU_QSAT, ZFLU_QSATS&
&, ZFLU_VEG, ZGWDCS, ZHQ, ZHTR, ZHU, ZQV, ZWFC, ZWLMX, ZWWILT)
CALL APL_ARPEGE_SURFACE (YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC&
&, YDCPG_GPAR, YDMF_PHYS, YDMF_PHYS_SURF, YDVARS, YDMODEL, ZALBD, ZALBP, ZALPHA1, ZCDROV, ZCEROV&
&, ZCFATH, ZCFAU, ZCFBTH, ZCFBU, ZCFBV, ZCHROV, ZCOEFA, ZCOEFN, ZCP, ZDIFEXT, ZDIFWQ, ZDIFWS&
&, ZDQSTS, ZDSA_CPS, ZDSA_LHS, ZDTMSE, ZEDMFQ, ZEDMFS, ZEDMFU, ZEDMFV, ZFLU_CD, ZFLU_CDN, ZFLU_EMIS&
&, ZFLU_FEVI, ZFLU_NEIJ, ZFLU_QSATS, ZFLU_VEG, ZHQ, ZHTR, ZHU, ZKQLROV, ZKQROV, ZKTROV, ZKUROV&
&, ZLVT, ZMF_UP, ZNEBCH, ZNEBDIFF, ZNEBS, ZPOID, ZQI, ZQICE, ZQL, ZQV, ZRDG_MU0, ZRDG_MU0N, ZRHGMT&
&, ZSC_FCLL, ZSC_FCLN, ZSC_FEVI, ZSC_FEVN, ZSFSWDIF, ZSFSWDIR, ZSGROUPEL, ZSRAIN, ZSSNOW, ZSTATI&
&, ZTSN, ZXDROV, ZXHROV, ZXQRO, ZXTRO, ZXTROV, ZXURO, ZXUROV)
CALL APL_ARPEGE_DIFTQ (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMODEL, ZDIFCVPPQ&
&, ZDIFCVPPS, ZDIFCVPPU, ZDIFCVPPV, ZEDMFQ, ZEDMFS, ZEDMFU, ZEDMFV)
CALL APL_ARPEGE_FRSOPT (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS&
&, YDMF_PHYS_BASE_STATE, YDMODEL, ZFLU_EMIS, ZRDG_MU0)
CALL APL_ARPEGE_ACDRAG (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE&
&, YDMF_PHYS_SURF, YDMODEL, YDVARS, ZCHROV, ZDQSTS, ZFLU_EMIS, ZFLU_NEIJ&
&, ZGWDCS, ZMSC_QW, ZNBVNO, ZNEBS, ZQLIS, ZQV)

IF (YDMODEL%YRML_PHY_MF%YRPHY%LCVTDK) THEN
  CALL APL_ARPEGE_DEEP_CONVECTION (YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS&
  &, YDCPG_OPTS, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF, YDVARS, YDMODEL,&
  & ZFPCOR, ZQV, ZTENHA, ZTENQVA, ZTENT, ZRDG_CVGQ, ZRDG_CVGT)
ENDIF


IF (YDMODEL%YRML_PHY_MF%YRPHY%LECTPRODCVP) THEN
  CALL APL_ARPEGE_TURBULENCE_PART2 (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE&
  &, YDMODEL, ZECTCLS, ZKCLS, ZKUROV2, ZPFL_FTKE, ZPRODTH, ZTKE1, ZUSLE)
ENDIF

CALL APL_ARPEGE_PRECIPITATION (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_SURF&
&, YDVARS, YDMODEL, ZFLU_NEIJ, ZNEBS, ZNEB_CVPP, ZQC_DET_PCMT, ZQI, ZQL, ZQLIS, ZQLI_CVPP&
&, ZQR, ZQS, ZQV, ZSEDIQI, ZSEDIQL, ZTENHA, ZTENQVA, YDGEOMETRY%YRSTA)
CALL APL_ARPEGE_QNGCOR (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE, YDMODEL&
&, ZFPCOR, ZFPLSL, ZFPLSN, ZPFL_FPLCH, ZPFL_FPLSH, ZQI, ZQL, ZQV, ZSEDIQI, ZSEDIQL)
CALL APL_ARPEGE_HYDRO_BUDGET (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_GPAR&
&, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, ZC3, ZCN, ZDSA_C1, ZDSA_C2, ZFLU_FEVI, ZFLU_NEIJ&
&, ZFLU_VEG, ZFPLSL, ZFPLSN, ZWFC, ZWLMX, ZWPMX, ZWSEQ, ZWSMX)
CALL APL_ARPEGE_ACDRME (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDGEOMETRY&
&, YDMF_PHYS, YDMF_PHYS_BASE_STATE, YDMODEL, YDVARS, ZMSC_FRMQ, ZQV)

IF (YDMODEL%YRML_DIAG%YRLDDH%LFLEXDIA) THEN
  
  CALL APLPAR_FLEXDIA (YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS&
  &, YDMF_PHYS_SURF, YDMODEL, YDDDH, YDMF_PHYS_BASE_STATE)
  
ENDIF


IF (YDMODEL%YRML_PHY_MF%YRPHY2%LRAFTKE) THEN
  CALL APL_ARPEGE_ACEVADCAPE (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE&
  &, YDMODEL, YDVARS, IMOC_CLPH, ZBLH, ZDCAPE, ZTKE1)
ENDIF

CALL APL_ARPEGE_ACVISIH (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS&
&, YDMF_PHYS_BASE_STATE, YDMODEL, ZEPSNEB, ZQR, ZQS)
CALL APL_ARPEGE_ZBAY_QRCONV (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMODEL, ZBAY_QRCONV, ZBAY_QSCONV)
CALL APL_ARPEGE_ZDE2MR (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_BASE_STATE&
&, YDMODEL, ZBAY_QRCONV, ZBAY_QSCONV)
CALL APL_ARPEGE_PPWETPOINT (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_BASE_STATE, YDMODEL, ZPCLS)
CALL APL_ARPEGE_DPRECIPS (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS&
&, YDMF_PHYS, YDVARS, YDMODEL, ZPRC_DPRECIPS, ZPRC_DPRECIPS2)
CALL MF_PHYS_MOCON (YDCPG_BNDS, YDCPG_OPTS, ZRDG_LCVQ, IMOC_CLPH, YDMF_PHYS, YDMF_PHYS_BASE_STATE)

IF (YDCPG_OPTS%LCORWAT) THEN
  CALL APL_ARPEGE_OUTLINE_022 (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_SURF)
ENDIF


IF (YDMODEL%YRML_PHY_MF%YRPHY%NDPSFI==1) THEN
  CALL APL_ARPEGE_OUTLINE_023 (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS,&
  & YDCPG_PHY0, YDGEOMETRY, YDMF_PHYS_SURF, YDMODEL, ZFLU_QSATS)
ENDIF

CALL APL_ARPEGE_ATMOSPHERE_UPDATE (YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE, YDGEOMETRY, YDCPG_BNDS&
&, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF, YDVARS, YDMODEL, YDDDH, ZDIFEXT&
&, ZDSA_CPS, ZMSC_FRMQ, ZPFL_FEFB1, ZPFL_FEFB2, ZPFL_FEFB3, ZPFL_FTKE, ZPFL_FTKEI, ZFCHQ)
CALL MF_PHYS_FPL_PART2 (YDCPG_BNDS, YDCPG_OPTS, ZPFL_FPLCH&
&, ZPFL_FPLSH, YDVARS%CPF%T1, YDVARS%SPF%T1, YDMODEL)
CALL MF_PHYS_TRANSFER (YDCPG_BNDS, YDCPG_OPTS, YDVARS, YDMODEL&
&%YRML_PHY_MF%YRPHY, YDMODEL%YRML_GCONF%YGFL)
CALL APL_ARPEGE_SURFACE_UPDATE (YDCPG_BNDS, YDCPG_OPTS, YDCPG_GPAR, YDMF_PHYS, YDMF_PHYS_SURF&
&, YDMODEL, YDCPG_OPTS%LCONFX, YDCPG_OPTS%ZDTPHY, ZDSA_C1, ZDSA_C2, ZFLU_FEVI, ZFLU_VEG)

IF (YDMODEL%YRML_PHY_MF%YRPHY%LCVPGY) THEN
  CALL APL_ARPEGE_OUTLINE_024 (YDCPG_BNDS, YDCPG_OPTS, YDVARS)
ENDIF


IF (YDCPG_OPTS%LCONFX) THEN
  CALL MF_PHYS_SAVE_PHSURF_PART2 (YDCPG_BNDS, YDCPG_OPTS, ZSAV_DDAL, ZSAV_DDOM, ZSAV_ENTCH, ZSAV_FHPS, ZSAV_GZ0F&
  &, ZSAV_GZ0HF, ZSAV_HV, ZSAV_PBLH, ZSAV_QSH, ZSAV_UDAL, ZSAV_UDGRO, ZSAV_UDOM, ZSAV_UNEBH, YDMF_PHYS_SURF&
  &%GSD_VF%PZ0F, YDMF_PHYS_SURF%GSD_VH%PPBLH, YDMF_PHYS_SURF%GSD_VH%PQSH, YDMF_PHYS_SURF%GSD_VH%PSPSH, YDMF_PHYS_SURF&
  &%GSD_VK%PUDGRO, YDMF_PHYS_SURF%GSD_VV%PHV, YDMF_PHYS_SURF%GSD_VV%PZ0H, YDVARS%DAL%T0, YDVARS%DOM%T0,&
  & YDVARS%UAL%T0, YDVARS%UEN%T0, YDVARS%UNEBH%T0, YDVARS%UOM%T0, YDMODEL)
ENDIF

CALL APL_ARPEGE_BAYRAD (YDCPG_BNDS, YDCPG_OPTS, YDMODEL, YDVARS, ZBAY_QRCONV, ZBAY_QSCONV)

IF (YDMODEL%YRML_PHY_EC%YREPHY%LEMWAVE) THEN
  CALL APL_ARPEGE_MWAVE (YDCPG_MISC, YDMF_PHYS, YDCPG_BNDS, YDCPG_OPTS, YDPHYSMWAVE)
ENDIF

CALL APL_ARPEGE_EDR (YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL)
CALL APL_ARPEGE_PRECIPS (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_SURF&
&, YDMODEL, ZPRC_DPRECIPS, ZPRC_DPRECIPS2)




IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE', 1, ZHOOK_HANDLE)
ENDSUBROUTINE APL_ARPEGE
