SUBROUTINE APL_ARPEGE_ZDE2MR (YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_BASE_STATE&
&, YDMODEL, PBAY_QRCONV, PBAY_QSCONV)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (INOUT)::PBAY_QRCONV (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PBAY_QSCONV (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPRB)::ZDE2MR (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_ZDE2MR', 0, ZHOOK_HANDLE)

DO JLEV=1, YDCPG_OPTS%KFLEVG

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    ZDE2MR (JLON, JLEV)=YDMODEL%YRCST%RD*YDMF_PHYS_BASE_STATE%T (JLON&
    &, JLEV)/YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF (JLON, JLEV)
    PBAY_QRCONV (JLON, JLEV)=PBAY_QRCONV (JLON, JLEV)*ZDE2MR (JLON, JLEV)
    PBAY_QSCONV (JLON, JLEV)=PBAY_QSCONV (JLON, JLEV)*ZDE2MR (JLON, JLEV)
  ENDDO

ENDDO

IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_ZDE2MR', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
