INTERFACE
SUBROUTINE APL_ARPEGE_ACDRAG (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS&
&, YDMF_PHYS_BASE_STATE, YDMF_PHYS_SURF, YDMODEL, YDVARS, PCHROV, PDQSTS,&
& PFLU_EMIS, PFLU_NEIJ, PGWDCS, PMSC_QW, PNBVNO, PNEBS, PQLIS, PQV)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE, CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_PHY_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
REAL (KIND=JPRB), INTENT (INOUT)::PCHROV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PDQSTS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_EMIS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PFLU_NEIJ (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PGWDCS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PMSC_QW (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PNBVNO (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PNEBS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PQLIS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PQV (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
ENDSUBROUTINE
END INTERFACE
