INTERFACE
SUBROUTINE APL_ARPEGE_AEROSOLS_FOR_RADIATION_RADAER (LDAERO, YDCPG_BNDS, YDCPG_OPTS&
&, YDMF_PHYS_BASE_STATE, YDMF_PHYS_SURF, YDMODEL, PAER, PAERINDS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

LOGICAL, INTENT (INOUT)::LDAERO
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (OUT)::PAER (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 6)
REAL (KIND=JPRB), INTENT (OUT)::PAERINDS (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
ENDSUBROUTINE
END INTERFACE
