INTERFACE
SUBROUTINE MF_PHYS_SAVE_PHSURF_PART1_PART1 (YDCPG_OPTS, YDMODEL, PDAL_T0, PDOM_T0, PGSD_VF_PZ0F&
&, PGSD_VH_PPBLH, PGSD_VH_PQSH, PGSD_VH_PSPSH, PGSD_VK_PUDGRO, PGSD_VV_PHV, PGSD_VV_PZ0H, PSAV_DDAL&
&, PSAV_DDOM, PSAV_ENTCH, PSAV_FHPS, PSAV_GZ0F, PSAV_GZ0HF, PSAV_HV, PSAV_PBLH, PSAV_QSH, PSAV_UDAL&
&, PSAV_UDGRO, PSAV_UDOM, PSAV_UNEBH, PUAL_T0, PUEN_T0, PUNEBH_T0, PUOM_T0)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (IN)::PDAL_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PDOM_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VF_PZ0F (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VH_PPBLH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VH_PQSH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VH_PSPSH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VK_PUDGRO (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VV_PHV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PGSD_VV_PZ0H (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_DDAL (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_DDOM (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_ENTCH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_FHPS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_GZ0F (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_GZ0HF (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_HV (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_PBLH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_QSH (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_UDAL (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_UDGRO (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_UDOM (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSAV_UNEBH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PUAL_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PUEN_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PUNEBH_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PUOM_T0 (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
ENDSUBROUTINE
END INTERFACE
