INTERFACE
SUBROUTINE CPUTQY_APLPAR_EXPL_PARALLEL (YDCST, YDCPG_BNDS, YDCPG_OPTS, YDDYNA, YDMF_PHYS_NEXT_STATE&
&, YDMF_PHYS_BASE_STATE, YDVARS, YDPHY, PDT, YD_PTENDH, YD_PTENDU, YD_PTENDV, YD_PTENDU_ZDEC&
&, YD_PTENDV_ZDEC, YD_PTENDD, YD_PTENDEFB1, YD_PTENDEFB2, YD_PTENDEFB3, YD_PTENDG, YD_PTENDICONV&
&, YD_PTENDI, YD_PTENDLCONV, YD_PTENDL, YD_PTENDQ, YD_PTENDRCONV, YD_PTENDR, YD_PTENDSCONV&
&, YD_PTENDS, YD_PTENDTKE, YD_PFDIS)
USE YOMCST,ONLY:TCST
USE YOMPHY,ONLY:TPHY
USE YOMDYNA,ONLY:TDYNA
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_NEXT_STATE_TYPE_MOD,ONLY:MF_PHYS_NEXT_STATE_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE PARKIND1
USE FXTRAN_ACDC_ARRAY_COPY_MOD
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE
TYPE (TCST), INTENT (IN)::YDCST
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (TDYNA), INTENT (IN)::YDDYNA
TYPE (MF_PHYS_NEXT_STATE_TYPE), INTENT (INOUT)::YDMF_PHYS_NEXT_STATE
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (TPHY), INTENT (IN)::YDPHY
REAL (KIND=JPRB), INTENT (IN)::PDT
CLASS (FIELD_3RB), POINTER :: YD_PTENDH
CLASS (FIELD_3RB), POINTER :: YD_PTENDU
CLASS (FIELD_3RB), POINTER :: YD_PTENDV
CLASS (FIELD_3RB), POINTER :: YD_PTENDU_ZDEC
CLASS (FIELD_3RB), POINTER :: YD_PTENDV_ZDEC
CLASS (FIELD_3RB), POINTER :: YD_PTENDD
CLASS (FIELD_3RB), POINTER :: YD_PTENDEFB1
CLASS (FIELD_3RB), POINTER :: YD_PTENDEFB2
CLASS (FIELD_3RB), POINTER :: YD_PTENDEFB3
CLASS (FIELD_3RB), POINTER :: YD_PTENDG
CLASS (FIELD_3RB), POINTER :: YD_PTENDICONV
CLASS (FIELD_3RB), POINTER :: YD_PTENDI
CLASS (FIELD_3RB), POINTER :: YD_PTENDLCONV
CLASS (FIELD_3RB), POINTER :: YD_PTENDL
CLASS (FIELD_3RB), POINTER :: YD_PTENDQ
CLASS (FIELD_3RB), POINTER :: YD_PTENDRCONV
CLASS (FIELD_3RB), POINTER :: YD_PTENDR
CLASS (FIELD_3RB), POINTER :: YD_PTENDSCONV
CLASS (FIELD_3RB), POINTER :: YD_PTENDS
CLASS (FIELD_3RB), POINTER :: YD_PTENDTKE
CLASS (FIELD_3RB), POINTER :: YD_PFDIS
END SUBROUTINE CPUTQY_APLPAR_EXPL_PARALLEL


END INTERFACE
