INTERFACE
SUBROUTINE CTVTOT_EXPL_PARALLEL (YDCST, YDGEOMETRY, YDVARS, YDCPG_OPTS, YDCPG_BNDS)
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE YOMCST,ONLY:TCST
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
IMPLICIT NONE
TYPE (TCST), INTENT (IN)::YDCST
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
END SUBROUTINE CTVTOT_EXPL_PARALLEL


END INTERFACE
