SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_V3D_OPTS_TYPE_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE COPY_CPG_SURF_V3D_OPTS_TYPE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (CPG_SURF_V3D_OPTS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
CALL SELF%YDIFM%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YDIFT%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YDIFS%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YADVT%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YADVS%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTRI0%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTRI1%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSWDK%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YZO%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YHO%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YDO%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YHO_INV%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YUOC%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVOC%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YOTKE%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

END SUBMODULE
