SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_VDD_OPTS_TYPE_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE WIPE_CPG_SURF_VDD_OPTS_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (CPG_SURF_VDD_OPTS_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL SELF%YLSP%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCP%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSF%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YFZRA%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YBLD%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSSHF%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSLHF%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YNEE%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YGPP%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YREC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMSL%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSP%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTCC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y10U%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y10V%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y2T%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y2D%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y2SH%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSSR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSTR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTSR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTTR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YEWSS%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YNSSS%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YE%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YPEV%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCCC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLCC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMCC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YHCC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLGWS%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMGWS%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YGWD%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMX2T%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMN2T%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRO%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSRO%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSSRO%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YALB%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YIEWSS%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YINSSS%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YISSHF%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YIE%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YINEE%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YIGPP%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YIREC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YICH4%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCSF%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLSSF%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMXTPR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMNTPR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTPR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLSRR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCRR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLSSFR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCSFR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YPTYPE%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YILSPF%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YZ0F%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLZ0H%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVIWVE%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVIWVN%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTCW%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTCWV%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTCLW%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTCIW%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTCRW%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTCSW%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTCSLW%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSSRD%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSTRD%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSSRDC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSTRDC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YBLH%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSUND%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSPAR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSUVB%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSFDIR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSCDIR%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSDSRP%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCAPE%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMUCAPE%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMLCAPE50%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMLCAPE100%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YPDEPL%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCAPES%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTROPOTP%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTSRC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTTRC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSSRC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSTRC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YES%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSMLT%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y10FG%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y10FGCV%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YI10FG%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLSPF%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTCO3%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVIMD%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSPARC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSTINC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCBASE%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y0DEGL%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YM10DEGL%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YVISIH%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCIN%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMLCIN50%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YMLCIN100%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YKINDEX%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTTINDEX%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCBASEA%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YCTOPC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YZTWETB0%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YZTWETB1%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y100U%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y100V%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y200U%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y200V%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YZUST%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y10NU%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%Y10NV%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YDNDZN%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YDNDZA%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YDCTB%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTPLB%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YTPLT%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODSS%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODDU%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODOM%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODBC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODSU%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODNI%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODAM%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODSOA%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODVFA%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODVSU%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YODTOACC%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YAEPM1%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YAEPM25%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YAEPM10%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YUVBED%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YUVBEDCS%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLITOTI%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YLICGI%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
