SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_WSD_OPTS_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE HOST_CPG_SURF_WSD_OPTS_TYPE (SELF)

IMPLICIT NONE
CLASS (CPG_SURF_WSD_OPTS_TYPE), TARGET :: SELF

CALL SELF%YCHAR%HOST ()

CALL SELF%YCHARHQ%HOST ()

CALL SELF%YUSTOKES%HOST ()

CALL SELF%YVSTOKES%HOST ()

CALL SELF%YTAUOCX%HOST ()

CALL SELF%YTAUOCY%HOST ()

CALL SELF%YPHIOC%HOST ()

CALL SELF%YWSEMEAN%HOST ()

CALL SELF%YWSFMEAN%HOST ()

END SUBROUTINE

END SUBMODULE
