SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_WWD_OPTS_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE CRC64_CPG_SURF_WWD_OPTS_TYPE (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (CPG_SURF_WWD_OPTS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YU10N%CRC64 (KLUN, CDPATH//'%YU10N'//TRIM(CLIND))

CLIND = ''
CALL SELF%YV10N%CRC64 (KLUN, CDPATH//'%YV10N'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRHO%CRC64 (KLUN, CDPATH//'%YRHO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZIL%CRC64 (KLUN, CDPATH//'%YZIL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCIF%CRC64 (KLUN, CDPATH//'%YCIF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCLK%CRC64 (KLUN, CDPATH//'%YCLK'//TRIM(CLIND))

CLIND = ''
CALL SELF%YUCURW%CRC64 (KLUN, CDPATH//'%YUCURW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVCURW%CRC64 (KLUN, CDPATH//'%YVCURW'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
