SUBMODULE (CPG_GMV_TYPE_MOD) CPG_GMV_TYPE_MOD_CPG_GMV_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE HOST_CPG_GMV_TYPE (SELF)
USE FIELD_UTIL_MODULE

IMPLICIT NONE
CLASS (CPG_GMV_TYPE), TARGET :: SELF
INTEGER :: J1
LOGICAL :: LF_DATA, LGMV, LZDATA, LZVIEW

LF_DATA = ASSOCIATED (SELF%F_DATA)
IF (LF_DATA) THEN
  CALL HOST_FIELD_4RB (SELF%F_DATA)
ENDIF

CALL SELF%U%HOST ()

CALL SELF%V%HOST ()

CALL SELF%T%HOST ()

CALL SELF%SPD%HOST ()

CALL SELF%SVD%HOST ()

CALL SELF%NHX%HOST ()

LGMV = ALLOCATED (SELF%GMV)
IF (LGMV) THEN
  DO J1 = LBOUND (SELF%GMV, 1), UBOUND (SELF%GMV, 1)
    CALL SELF%GMV (J1)%HOST ()
  ENDDO
ENDIF

END SUBROUTINE

END SUBMODULE
