SUBMODULE (FIELD_VARIABLES_MOD) FIELD_VARIABLES_MOD_FIELD_VARIABLES_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE HOST_FIELD_VARIABLES (SELF)

IMPLICIT NONE
CLASS (FIELD_VARIABLES), TARGET :: SELF
INTEGER :: J1
LOGICAL :: LAERAOT, LAERLISI, LAERO, LAEROCLIM, LAEROUT, LCHEM, LEDRP, LEMIS3D, LERA40, LEXT
LOGICAL :: LEZDIAG, LFORC, LGFL_PTR, LGHG, LLIMA, LNOGW, LSLDIA, LUVP
CALL SELF%U%HOST ()

CALL SELF%V%HOST ()

CALL SELF%T%HOST ()

CALL SELF%DIV%HOST ()

CALL SELF%VOR%HOST ()

CALL SELF%SPD%HOST ()

CALL SELF%SVD%HOST ()

CALL SELF%CSPDNL%HOST ()

CALL SELF%CSPNL%HOST ()

CALL SELF%CSVDPT%HOST ()

CALL SELF%CTNL%HOST ()

CALL SELF%CTPT%HOST ()

CALL SELF%CUNL%HOST ()

CALL SELF%CUPT%HOST ()

CALL SELF%CVNL%HOST ()

CALL SELF%CVPT%HOST ()

CALL SELF%CVWVNL%HOST ()

CALL SELF%DPHI%HOST ()

CALL SELF%EDOT%HOST ()

CALL SELF%GW%HOST ()

CALL SELF%NHX%HOST ()

CALL SELF%NHY%HOST ()

CALL SELF%SGRTL%HOST ()

CALL SELF%SGRTM%HOST ()

CALL SELF%SPDNL%HOST ()

CALL SELF%SPDNL_SI%HOST ()

CALL SELF%SPNL%HOST ()

CALL SELF%SPNL_SI%HOST ()

CALL SELF%SVDNL_SI%HOST ()

CALL SELF%TNL%HOST ()

CALL SELF%TNL_SI%HOST ()

CALL SELF%UNL%HOST ()

CALL SELF%UNL_SI%HOST ()

CALL SELF%VNL%HOST ()

CALL SELF%VNL_SI%HOST ()

CALL SELF%VWVNL%HOST ()

CALL SELF%CURHS%HOST ()

CALL SELF%CVRHS%HOST ()

CALL SELF%CTRHS%HOST ()

CALL SELF%CSPDRHS%HOST ()

CALL SELF%CSVDRHS%HOST ()

CALL SELF%NHXNL%HOST ()

CALL SELF%CNHXNL%HOST ()

CALL SELF%PCF_U%HOST ()

CALL SELF%PCF_V%HOST ()

CALL SELF%PCF_T%HOST ()

CALL SELF%PCF_SPD%HOST ()

CALL SELF%PCF_SVD%HOST ()

CALL SELF%PCF_NHX%HOST ()

CALL SELF%PCF_SP%HOST ()

CALL SELF%PCF_CP%HOST ()

CALL SELF%PCF_UP%HOST ()

CALL SELF%PCF_VP%HOST ()

CALL SELF%PCF_TP%HOST ()

CALL SELF%SP%HOST ()

CALL SELF%SPNL2%HOST ()

CALL SELF%PREHYDS%HOST ()

CALL SELF%DBBC%HOST ()

CALL SELF%CSPPT%HOST ()

CALL SELF%CSPNL2%HOST ()

CALL SELF%CSPRHS%HOST ()

CALL SELF%GWS%HOST ()

CALL SELF%PCF_BBC%HOST ()

CALL SELF%PCF_DPHI%HOST ()

CALL SELF%PCF_GWS%HOST ()

CALL SELF%Q%HOST ()

CALL SELF%I%HOST ()

CALL SELF%L%HOST ()

CALL SELF%IMF%HOST ()

CALL SELF%LMF%HOST ()

CALL SELF%LCONV%HOST ()

CALL SELF%ICONV%HOST ()

CALL SELF%RCONV%HOST ()

CALL SELF%SCONV%HOST ()

CALL SELF%IRAD%HOST ()

CALL SELF%LRAD%HOST ()

CALL SELF%S%HOST ()

CALL SELF%R%HOST ()

CALL SELF%G%HOST ()

CALL SELF%H%HOST ()

CALL SELF%TKE%HOST ()

CALL SELF%TTE%HOST ()

CALL SELF%EFB1%HOST ()

CALL SELF%EFB2%HOST ()

CALL SELF%EFB3%HOST ()

CALL SELF%A%HOST ()

CALL SELF%AMF%HOST ()

CALL SELF%O3%HOST ()

CALL SELF%SRC%HOST ()

CALL SELF%MXL%HOST ()

CALL SELF%SHTUR%HOST ()

CALL SELF%FQTUR%HOST ()

CALL SELF%FSTUR%HOST ()

CALL SELF%CPF%HOST ()

CALL SELF%SPF%HOST ()

CALL SELF%CVGQ%HOST ()

CALL SELF%QVA%HOST ()

LGHG = ALLOCATED (SELF%GHG)
IF (LGHG) THEN
  DO J1 = LBOUND (SELF%GHG, 1), UBOUND (SELF%GHG, 1)
    CALL SELF%GHG (J1)%HOST ()
  ENDDO
ENDIF

LCHEM = ALLOCATED (SELF%CHEM)
IF (LCHEM) THEN
  DO J1 = LBOUND (SELF%CHEM, 1), UBOUND (SELF%CHEM, 1)
    CALL SELF%CHEM (J1)%HOST ()
  ENDDO
ENDIF

LAERO = ALLOCATED (SELF%AERO)
IF (LAERO) THEN
  DO J1 = LBOUND (SELF%AERO, 1), UBOUND (SELF%AERO, 1)
    CALL SELF%AERO (J1)%HOST ()
  ENDDO
ENDIF

CALL SELF%LRCH4%HOST ()

LFORC = ALLOCATED (SELF%FORC)
IF (LFORC) THEN
  DO J1 = LBOUND (SELF%FORC, 1), UBOUND (SELF%FORC, 1)
    CALL SELF%FORC (J1)%HOST ()
  ENDDO
ENDIF

LEZDIAG = ALLOCATED (SELF%EZDIAG)
IF (LEZDIAG) THEN
  DO J1 = LBOUND (SELF%EZDIAG, 1), UBOUND (SELF%EZDIAG, 1)
    CALL SELF%EZDIAG (J1)%HOST ()
  ENDDO
ENDIF

LERA40 = ALLOCATED (SELF%ERA40)
IF (LERA40) THEN
  DO J1 = LBOUND (SELF%ERA40, 1), UBOUND (SELF%ERA40, 1)
    CALL SELF%ERA40 (J1)%HOST ()
  ENDDO
ENDIF

LNOGW = ALLOCATED (SELF%NOGW)
IF (LNOGW) THEN
  DO J1 = LBOUND (SELF%NOGW, 1), UBOUND (SELF%NOGW, 1)
    CALL SELF%NOGW (J1)%HOST ()
  ENDDO
ENDIF

LEMIS3D = ALLOCATED (SELF%EMIS3D)
IF (LEMIS3D) THEN
  DO J1 = LBOUND (SELF%EMIS3D, 1), UBOUND (SELF%EMIS3D, 1)
    CALL SELF%EMIS3D (J1)%HOST ()
  ENDDO
ENDIF

LEDRP = ALLOCATED (SELF%EDRP)
IF (LEDRP) THEN
  DO J1 = LBOUND (SELF%EDRP, 1), UBOUND (SELF%EDRP, 1)
    CALL SELF%EDRP (J1)%HOST ()
  ENDDO
ENDIF

LSLDIA = ALLOCATED (SELF%SLDIA)
IF (LSLDIA) THEN
  DO J1 = LBOUND (SELF%SLDIA, 1), UBOUND (SELF%SLDIA, 1)
    CALL SELF%SLDIA (J1)%HOST ()
  ENDDO
ENDIF

LAERAOT = ALLOCATED (SELF%AERAOT)
IF (LAERAOT) THEN
  DO J1 = LBOUND (SELF%AERAOT, 1), UBOUND (SELF%AERAOT, 1)
    CALL SELF%AERAOT (J1)%HOST ()
  ENDDO
ENDIF

LAERLISI = ALLOCATED (SELF%AERLISI)
IF (LAERLISI) THEN
  DO J1 = LBOUND (SELF%AERLISI, 1), UBOUND (SELF%AERLISI, 1)
    CALL SELF%AERLISI (J1)%HOST ()
  ENDDO
ENDIF

LAEROUT = ALLOCATED (SELF%AEROUT)
IF (LAEROUT) THEN
  DO J1 = LBOUND (SELF%AEROUT, 1), UBOUND (SELF%AEROUT, 1)
    CALL SELF%AEROUT (J1)%HOST ()
  ENDDO
ENDIF

LAEROCLIM = ALLOCATED (SELF%AEROCLIM)
IF (LAEROCLIM) THEN
  DO J1 = LBOUND (SELF%AEROCLIM, 1), UBOUND (SELF%AEROCLIM, 1)
    CALL SELF%AEROCLIM (J1)%HOST ()
  ENDDO
ENDIF

LUVP = ALLOCATED (SELF%UVP)
IF (LUVP) THEN
  DO J1 = LBOUND (SELF%UVP, 1), UBOUND (SELF%UVP, 1)
    CALL SELF%UVP (J1)%HOST ()
  ENDDO
ENDIF

CALL SELF%PHYCTY%HOST ()

CALL SELF%RSPEC%HOST ()

CALL SELF%SDSAT%HOST ()

CALL SELF%CVV%HOST ()

CALL SELF%RKTH%HOST ()

CALL SELF%RKTQV%HOST ()

CALL SELF%RKTQC%HOST ()

CALL SELF%UOM%HOST ()

CALL SELF%UAL%HOST ()

CALL SELF%DOM%HOST ()

CALL SELF%DAL%HOST ()

CALL SELF%UEN%HOST ()

CALL SELF%UNEBH%HOST ()

LLIMA = ALLOCATED (SELF%LIMA)
IF (LLIMA) THEN
  DO J1 = LBOUND (SELF%LIMA, 1), UBOUND (SELF%LIMA, 1)
    CALL SELF%LIMA (J1)%HOST ()
  ENDDO
ENDIF

CALL SELF%FSD%HOST ()

LEXT = ALLOCATED (SELF%EXT)
IF (LEXT) THEN
  DO J1 = LBOUND (SELF%EXT, 1), UBOUND (SELF%EXT, 1)
    CALL SELF%EXT (J1)%HOST ()
  ENDDO
ENDIF

CALL SELF%GEOMETRY%HOST ()

CALL SELF%ECPHYS%HOST ()

CALL SELF%RADIATION%HOST ()

LGFL_PTR = ALLOCATED (SELF%GFL_PTR)
IF (LGFL_PTR) THEN
  DO J1 = LBOUND (SELF%GFL_PTR, 1), UBOUND (SELF%GFL_PTR, 1)
    CALL SELF%GFL_PTR (J1)%HOST ()
  ENDDO
ENDIF

END SUBROUTINE

END SUBMODULE
