SUBMODULE (FIELD_VARIABLES_MOD) FIELD_VARIABLES_MOD_GEOMETRY_VARIABLES_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION SIZE_GEOMETRY_VARIABLES (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (GEOMETRY_VARIABLES),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
JSIZE = 0
ISIZE = SELF%RCORI%SIZE (CLPATH//'%RCORI', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCORI'
ENDIF
JSIZE = 0
ISIZE = SELF%RCORIC%SIZE (CLPATH//'%RCORIC', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCORIC'
ENDIF
JSIZE = 0
ISIZE = SELF%GEMU%SIZE (CLPATH//'%GEMU', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GEMU'
ENDIF
JSIZE = 0
ISIZE = SELF%GSQM2%SIZE (CLPATH//'%GSQM2', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GSQM2'
ENDIF
JSIZE = 0
ISIZE = SELF%GELAM%SIZE (CLPATH//'%GELAM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GELAM'
ENDIF
JSIZE = 0
ISIZE = SELF%GELAT%SIZE (CLPATH//'%GELAT', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GELAT'
ENDIF
JSIZE = 0
ISIZE = SELF%GECLO%SIZE (CLPATH//'%GECLO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GECLO'
ENDIF
JSIZE = 0
ISIZE = SELF%GESLO%SIZE (CLPATH//'%GESLO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GESLO'
ENDIF
JSIZE = 0
ISIZE = SELF%GM%SIZE (CLPATH//'%GM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GM'
ENDIF
JSIZE = 0
ISIZE = SELF%GMAPPA%SIZE (CLPATH//'%GMAPPA', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GMAPPA'
ENDIF
JSIZE = 0
ISIZE = SELF%GOMVRL%SIZE (CLPATH//'%GOMVRL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GOMVRL'
ENDIF
JSIZE = 0
ISIZE = SELF%GOMVRM%SIZE (CLPATH//'%GOMVRM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GOMVRM'
ENDIF
JSIZE = 0
ISIZE = SELF%GNORDL%SIZE (CLPATH//'%GNORDL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GNORDL'
ENDIF
JSIZE = 0
ISIZE = SELF%GNORDM%SIZE (CLPATH//'%GNORDM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GNORDM'
ENDIF
JSIZE = 0
ISIZE = SELF%GNORDLCL%SIZE (CLPATH//'%GNORDLCL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GNORDLCL'
ENDIF
JSIZE = 0
ISIZE = SELF%GNORDMCL%SIZE (CLPATH//'%GNORDMCL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GNORDMCL'
ENDIF
JSIZE = 0
ISIZE = SELF%GNORDMCM%SIZE (CLPATH//'%GNORDMCM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GNORDMCM'
ENDIF
JSIZE = 0
ISIZE = SELF%GAW%SIZE (CLPATH//'%GAW', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GAW'
ENDIF
JSIZE = 0
ISIZE = SELF%OROG%SIZE (CLPATH//'%OROG', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%OROG'
ENDIF
JSIZE = 0
ISIZE = SELF%OROGL%SIZE (CLPATH//'%OROGL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%OROGL'
ENDIF
JSIZE = 0
ISIZE = SELF%OROGM%SIZE (CLPATH//'%OROGM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%OROGM'
ENDIF
JSIZE = 0
ISIZE = SELF%RINDX%SIZE (CLPATH//'%RINDX', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RINDX'
ENDIF
JSIZE = 0
ISIZE = SELF%RINDY%SIZE (CLPATH//'%RINDY', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RINDY'
ENDIF
JSIZE = 0
ISIZE = SELF%RATATH%SIZE (CLPATH//'%RATATH', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RATATH'
ENDIF
JSIZE = 0
ISIZE = SELF%RATATX%SIZE (CLPATH//'%RATATX', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RATATX'
ENDIF
JSIZE = 0
ISIZE = SELF%OROGLL%SIZE (CLPATH//'%OROGLL', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%OROGLL'
ENDIF
JSIZE = 0
ISIZE = SELF%OROGMM%SIZE (CLPATH//'%OROGMM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%OROGMM'
ENDIF
JSIZE = 0
ISIZE = SELF%OROGLM%SIZE (CLPATH//'%OROGLM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%OROGLM'
ENDIF
JSIZE = 0
ISIZE = SELF%GEXCO%SIZE (CLPATH//'%GEXCO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GEXCO'
ENDIF
JSIZE = 0
ISIZE = SELF%GEYCO%SIZE (CLPATH//'%GEYCO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GEYCO'
ENDIF
JSIZE = 0
ISIZE = SELF%GEZCO%SIZE (CLPATH//'%GEZCO', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%GEZCO'
ENDIF
JSIZE = 0
ISIZE = SELF%RCOLON%SIZE (CLPATH//'%RCOLON', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RCOLON'
ENDIF
JSIZE = 0
ISIZE = SELF%RSILON%SIZE (CLPATH//'%RSILON', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%RSILON'
ENDIF
END FUNCTION

END SUBMODULE
