SUBMODULE (SURFACE_VIEWS_DIAGNOSTIC_MODULE) SURFACE_VIEWS_DIAGNOSTIC_MODULE_SURFACE_VIEW_GROUP_VDIAGO2_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE WIPE_SURFACE_VIEW_GROUP_VDIAGO2 (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_VDIAGO2), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_GROUP, LF_OCDEP, LF_USTRC, LF_VSTRC, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVARIABLE_GROUP = ASSOCIATED (SELF%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC EXIT DATA DETACH (SELF%VARIABLE_GROUP)
  CALL SELF%VARIABLE_GROUP%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (SELF%VARIABLE_GROUP)
ENDIF

LF_OCDEP = ASSOCIATED (SELF%F_OCDEP)
IF (LF_OCDEP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_OCDEP)
ENDIF

LF_USTRC = ASSOCIATED (SELF%F_USTRC)
IF (LF_USTRC .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_USTRC)
ENDIF

LF_VSTRC = ASSOCIATED (SELF%F_VSTRC)
IF (LF_VSTRC .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_2RB (SELF%F_VSTRC)
ENDIF

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
