SUBMODULE (SURFACE_VARIABLES_MOD) SURFACE_VARIABLES_MOD_SURFACE_VARIABLE_GROUP_WAVES_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE HOST_SURFACE_VARIABLE_GROUP_WAVES (SELF)
USE FIELD_UTIL_MODULE

IMPLICIT NONE
CLASS (SURFACE_VARIABLE_GROUP_WAVES), TARGET :: SELF
LOGICAL :: LF_GROUP
CALL SELF%VCHAR%HOST ()

CALL SELF%VCHARHQ%HOST ()

CALL SELF%VUSTOKES%HOST ()

CALL SELF%VVSTOKES%HOST ()

CALL SELF%VTAUOCX%HOST ()

CALL SELF%VTAUOCY%HOST ()

CALL SELF%VPHIOC%HOST ()

CALL SELF%VWSEMEAN%HOST ()

CALL SELF%VWSFMEAN%HOST ()

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (SELF%F_GROUP)
ENDIF

END SUBROUTINE

END SUBMODULE
