INTERFACE
SUBROUTINE PPWETPOINT_OPENACC (YDCST, YDPHY, KIDIA, KFDIA, KLON&
&, KLEV, PAPRS, PT, PQV, PQL, PQI, PWETPOINT, YDSTACK)
!$ACC ROUTINE (PPWETPOINT_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMPHY,ONLY:TPHY
USE YOMCST,ONLY:TCST
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TPHY), INTENT (IN)::YDPHY
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQI (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PWETPOINT (KLON, KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
END SUBROUTINE PPWETPOINT_OPENACC


END INTERFACE
