SUBROUTINE CPG_GP_GPTF2_EXPL_2TL (YDCPG_BNDS, YDCPG_OPTS, YDGEOMETRY, YDVARS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
#include "gptf2_expl_2tl.intfb.h"
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('CPG_GP_GPTF2_EXPL_2TL', 0, ZHOOK_HANDLE)
CALL GPTF2_EXPL_2TL (YDGEOMETRY, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS&
&%LFSTEP, P0U=YDVARS%U%T0, P0V=YDVARS%V%T0, P9U=YDVARS%U%T9, P9V=YDVARS%V%T9)
IF (LHOOK) CALL DR_HOOK ('CPG_GP_GPTF2_EXPL_2TL', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
