INTERFACE
SUBROUTINE CPG_LSMTSOL (YDVARS, YDCPG_MISC, YDMF_PHYS_SURF, YDCPG_OPTS, YDGEOMETRY, YDCPG_BNDS)
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_DDH_TYPE, CPG_DYN_TYPE, CPG_GPAR_TYPE&
&, CPG_MISC_TYPE, CPG_PHY_TYPE, CPG_TND_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
ENDSUBROUTINE
END INTERFACE
