INTERFACE
SUBROUTINE CPG_GP_GPTF2_EXPL_2TL (YDCPG_BNDS, YDCPG_OPTS, YDGEOMETRY, YDVARS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
ENDSUBROUTINE
END INTERFACE
