SUBROUTINE CPUTQY_APLPAR_EXPL_PFDIS (YDCPG_BNDS, YDCPG_OPTS, YDPHY, PFDIS, PTENDTKE, PDEC, PRRGDELP)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMPHY,ONLY:TPHY
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (TPHY), INTENT (IN)::YDPHY
REAL (KIND=JPRB), INTENT (OUT)::PFDIS (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PTENDTKE (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PDEC (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PRRGDELP (YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('CPUTQY_APLPAR_EXPL_PFDIS', 0, ZHOOK_HANDLE)
PFDIS (:, 0)=0.0_JPRB

DO JLEV=1, YDCPG_OPTS%KFLEVG

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    PFDIS (JLON, JLEV)=PFDIS (JLON, JLEV-1)+PRRGDELP (JLON, JLEV)*PDEC (JLON, JLEV)
  ENDDO


  IF (YDPHY%LPTKE) THEN

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
      PFDIS (JLON, JLEV)=PFDIS (JLON, JLEV)+PRRGDELP (JLON, JLEV)*PTENDTKE (JLON, JLEV)
    ENDDO

  ENDIF

ENDDO

IF (LHOOK) CALL DR_HOOK ('CPUTQY_APLPAR_EXPL_PFDIS', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
