SUBROUTINE GPINISLB_PART2_EXPL_OUTLINE_000 (JGFL, YDCPG_BNDS, YDVARS)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

INTEGER (KIND=JPIM), INTENT (INOUT)::JGFL
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('GPINISLB_PART2_EXPL_OUTLINE_000', 0, ZHOOK_HANDLE)
YDVARS%GFL_PTR (JGFL)%T1 (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,:)=0._JPRB
IF (LHOOK) CALL DR_HOOK ('GPINISLB_PART2_EXPL_OUTLINE_000', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
