SUBROUTINE LACDYN_LASURE (YDCPG_BNDS, YDGEOMETRY, YDMODEL, YDVARS, PBT, PBDT, PREDIV)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPRB
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
REAL (KIND=JPRB), INTENT (INOUT)::PBT
REAL (KIND=JPRB), INTENT (INOUT)::PBDT (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::PREDIV (YDGEOMETRY%YRDIM%NPROMA)
#include "lasure.intfb.h"
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('LACDYN_LASURE', 0, ZHOOK_HANDLE)
CALL LASURE (YDGEOMETRY, YDMODEL%YRML_PHY_EC%YREPHY, YDMODEL%YRML_DYN%YRDYN, YDMODEL&
&%YRML_DYN%YREDYN, YDMODEL%YRML_PHY_MF%YRPHY, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA&
&, YDVARS%GEOMETRY%GMAPPA%T0, YDVARS%GEOMETRY%GM%T0, PBT, PBDT, PREDIV)
IF (LHOOK) CALL DR_HOOK ('LACDYN_LASURE', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
