INTERFACE
SUBROUTINE LACDYN_LASURE (YDVARS, PBT, YDMODEL, YDGEOMETRY, YDCPG_BNDS, PREDIV, PBDT)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE PARKIND1,ONLY:JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
REAL (KIND=JPRB), INTENT (INOUT)::PBT
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (INOUT)::PREDIV (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::PBDT (YDGEOMETRY%YRDIM%NPROMA)
ENDSUBROUTINE
END INTERFACE
