INTERFACE
SUBROUTINE LAPINEB_NVLAG3 (YDVARS, YDCPG_SL2, YDMODEL, YDGEOMETRY&
&, YDCPG_BNDS, PVWEI, PC9, PSPTO, PC9_SI, PSPT1, PDP9)
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_SL2_TYPE_MOD,ONLY:CPG_SL2_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (CPG_SL2_TYPE), INTENT (IN)::YDCPG_SL2
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (INOUT)::PVWEI (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PC9 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSPTO (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::PC9_SI (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSPT1 (YDGEOMETRY%YRDIM%NPROMA, 0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB), INTENT (INOUT)::PDP9 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
ENDSUBROUTINE
END INTERFACE
