INTERFACE
SUBROUTINE LAPINEB_CVGQ (YDVARS, JFLD, YDCPG_GFL9, YDGEOMETRY, YDCPG_BNDS)
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_GFL_TYPE_MOD,ONLY:CPG_GFL_TYPE, CPG_GFLSL_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
INTEGER (KIND=JPIM), INTENT (INOUT)::JFLD
TYPE (CPG_GFL_TYPE), INTENT (INOUT)::YDCPG_GFL9
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
ENDSUBROUTINE
END INTERFACE
