INTERFACE
SUBROUTINE LAPINEB_ROTUVGEO_2 (YDVARS, YDCPG_GMV9, YDA_PCCO, YDMODEL, YDGEOMETRY, YDCPG_BNDS)
USE FIELD_ARRAY_MODULE,ONLY:FIELD_3IM_ARRAY, FIELD_4IM_ARRAY, FIELD_3RB_ARRAY, FIELD_4RB_ARRAY
USE TYPE_MODEL,ONLY:MODEL
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_GMV_TYPE_MOD,ONLY:CPG_GMV_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (CPG_GMV_TYPE), INTENT (INOUT)::YDCPG_GMV9
TYPE (FIELD_4RB_ARRAY), INTENT (IN)::YDA_PCCO
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
ENDSUBROUTINE
END INTERFACE
