SUBROUTINE LAPINEB_ZERO_GMV9_SL (JFLD, YDCPG_GMV9_NL)
USE CPG_GMV_TYPE_MOD,ONLY:CPG_GMV_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

INTEGER (KIND=JPIM), INTENT (INOUT)::JFLD
TYPE (CPG_GMV_TYPE), INTENT (INOUT)::YDCPG_GMV9_NL
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('LAPINEB_ZERO_GMV9_SL', 0, ZHOOK_HANDLE)
YDCPG_GMV9_NL%GMV (JFLD)%P=0.0_JPRB
IF (LHOOK) CALL DR_HOOK ('LAPINEB_ZERO_GMV9_SL', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
