SUBROUTINE LARCINB_LAITRE_GFL (LDMOM, KWKGFL, JFLD, KASLB1, KHVI, YDCPG_BNDS, YDCPG_GFLF&
&, YDCPG_SL1, YDGEOMETRY, YDML_DYN, YDML_GCONF, YDVARS, KL0, KNOWENO, PLSCAW, PRSCAW)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE CPG_GFL_TYPE_MOD,ONLY:CPG_GFL_TYPE, CPG_GFLSL_TYPE
USE CPG_SL1_TYPE_MOD,ONLY:CPG_SL1F_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE MODEL_DYNAMICS_MOD,ONLY:MODEL_DYNAMICS_TYPE
USE MODEL_GENERAL_CONF_MOD,ONLY:MODEL_GENERAL_CONF_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

LOGICAL, INTENT (INOUT)::LDMOM
INTEGER (KIND=JPIM), INTENT (INOUT)::KWKGFL
INTEGER (KIND=JPIM), INTENT (INOUT)::JFLD
INTEGER (KIND=JPIM), INTENT (IN)::KASLB1
INTEGER (KIND=JPIM), INTENT (IN)::KHVI
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_GFL_TYPE), INTENT (INOUT)::YDCPG_GFLF
TYPE (CPG_SL1F_TYPE), INTENT (IN)::YDCPG_SL1
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN)::YDML_DYN
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN)::YDML_GCONF
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
INTEGER (KIND=JPIM), INTENT (IN)::KL0 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG, 0:3)
INTEGER (KIND=JPIM), INTENT (IN)::KNOWENO (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PLSCAW (YDGEOMETRY%YRDIM%NPROMA&
&, YDGEOMETRY%YRDIMV%NFLEVG, YDML_DYN%YYTLSCAW%NDIM)
REAL (KIND=JPRB), INTENT (IN)::PRSCAW (YDGEOMETRY%YRDIM%NPROMA&
&, YDGEOMETRY%YRDIMV%NFLEVG, YDML_DYN%YYTRSCAW%NDIM)
#include "laitre_gfl.intfb.h"
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('LARCINB_LAITRE_GFL', 0, ZHOOK_HANDLE)
CALL LAITRE_GFL (YDGEOMETRY, YDML_GCONF%YGFL, YDML_DYN, KASLB1, YDGEOMETRY%YRDIM%NPROMA, YDCPG_BNDS&
&%KIDIA, YDCPG_BNDS%KFDIA, YDGEOMETRY%YRDIMV%NFLEVG, YDGEOMETRY%YRDIMV%NFLSA, YDGEOMETRY%YRDIMV%NFLEN&
&, KHVI, KWKGFL, YDVARS%GFL_PTR (JFLD)%YCOMP%CSLINT, YDVARS%GFL_PTR (JFLD)%YCOMP%WENO_ALPHA, LDMOM&
&, KNOWENO, KL0, PLSCAW, PRSCAW, YDCPG_SL1%GFL (JFLD)%P, YDCPG_GFLF%GFL (JFLD)%P)
IF (LHOOK) CALL DR_HOOK ('LARCINB_LAITRE_GFL', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
