INTERFACE
SUBROUTINE LATTEX_LRHS_CURV (YDVARS, YDCPG_SL1, YDML_DYN, YDGEOMETRY, YDCPG_BNDS)
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_SL1_TYPE_MOD,ONLY:CPG_SL1B_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE MODEL_DYNAMICS_MOD,ONLY:MODEL_DYNAMICS_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (CPG_SL1B_TYPE), INTENT (INOUT)::YDCPG_SL1
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN)::YDML_DYN
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
ENDSUBROUTINE
END INTERFACE
