INTERFACE
SUBROUTINE LATTEX_EXPL_2TL_OUTLINE_004 (YDCPG_BNDS, YDCPG_SL1, YDGEOMETRY)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_SL1_TYPE_MOD,ONLY:CPG_SL1B_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_SL1B_TYPE), INTENT (INOUT)::YDCPG_SL1
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
ENDSUBROUTINE
END INTERFACE
