SUBROUTINE LATTEX_EXPL_VSPLTRANS_OUTLINE_001 (JGFL, YDCPG_BNDS, YDCPG_SL1, YDGEOMETRY, YDML_DYN)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_SL1_TYPE_MOD,ONLY:CPG_SL1B_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE MODEL_DYNAMICS_MOD,ONLY:MODEL_DYNAMICS_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

INTEGER (KIND=JPIM), INTENT (INOUT)::JGFL
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_SL1B_TYPE), INTENT (INOUT)::YDCPG_SL1
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN)::YDML_DYN
#include "vspltrans.intfb.h"
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JROF
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_VSPLTRANS_OUTLINE_001', 0, ZHOOK_HANDLE)

DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

  DO JROF=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    YDCPG_SL1%GFL (JGFL)%P_SP (JROF, JLEV)=YDCPG_SL1%GFL (JGFL)%P (JROF, JLEV)
  ENDDO

ENDDO

CALL VSPLTRANS (YDML_DYN%YRSLINT%YRVSPLIP, YDGEOMETRY%YRDIM%NPROMA, YDCPG_BNDS&
&%KIDIA, YDCPG_BNDS%KFDIA, YDGEOMETRY%YRDIMV%NFLEVG, YDGEOMETRY%YRDIMV&
&%NFLSA, YDGEOMETRY%YRDIMV%NFLEN, YDCPG_SL1%GFL (JGFL)%P_SP)
IF (LHOOK) CALL DR_HOOK ('LATTEX_EXPL_VSPLTRANS_OUTLINE_001', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
