SUBROUTINE LAVABO_EXPL_LAITVSPCQM_PART2_OUTLINE_000 (YDCPG_SL1, JGFL, JLEV1, YDCPG_BNDS, JLEV0)
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE CPG_SL1_TYPE_MOD,ONLY:CPG_SL1B_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_SL1B_TYPE), INTENT (INOUT)::YDCPG_SL1
INTEGER (KIND=JPIM), INTENT (INOUT)::JGFL
INTEGER (KIND=JPIM), INTENT (INOUT)::JLEV1
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
INTEGER (KIND=JPIM), INTENT (INOUT)::JLEV0
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('LAVABO_EXPL_LAITVSPCQM_PART2_OUTLINE_000', 0, ZHOOK_HANDLE)
YDCPG_SL1%GFL (JGFL)%P_F (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV0)=0.0_JPRB
YDCPG_SL1%GFL (JGFL)%P_F (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
IF (LHOOK) CALL DR_HOOK ('LAVABO_EXPL_LAITVSPCQM_PART2_OUTLINE_000', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
