SUBROUTINE LAVABO_OUTLINE_000 (LD2TLFF1, JLEV1, JLEV2, YDCPG_BNDS, YDCPG_SL1, YDMODEL)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE CPG_SL1_TYPE_MOD,ONLY:CPG_SL1B_TYPE
USE PARKIND1,ONLY:JPRB, JPIM
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

LOGICAL, INTENT (IN)::LD2TLFF1
INTEGER (KIND=JPIM), INTENT (INOUT)::JLEV1
INTEGER (KIND=JPIM), INTENT (INOUT)::JLEV2
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_SL1B_TYPE), INTENT (INOUT)::YDCPG_SL1
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('LAVABO_OUTLINE_000', 0, ZHOOK_HANDLE)
YDCPG_SL1%UR0%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
YDCPG_SL1%UR0%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
YDCPG_SL1%VR0%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
YDCPG_SL1%VR0%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB

IF (YDMODEL%YRML_DYN%YRDYN%LSLDP_CURV) THEN
  YDCPG_SL1%ZR0%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
  YDCPG_SL1%ZR0%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
ENDIF

YDCPG_SL1%WR0%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
YDCPG_SL1%WR0%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB

IF (YDMODEL%YRML_DYN%YRDYN%LSLDP_RK) THEN
  YDCPG_SL1%UR00%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
  YDCPG_SL1%UR00%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
  YDCPG_SL1%VR00%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
  YDCPG_SL1%VR00%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB

  IF (YDMODEL%YRML_DYN%YRDYN%LSLDP_CURV) THEN
    YDCPG_SL1%ZR00%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
    YDCPG_SL1%ZR00%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
  ENDIF

  YDCPG_SL1%WR00%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
  YDCPG_SL1%WR00%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
ENDIF


IF (LD2TLFF1) THEN
  YDCPG_SL1%UR9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
  YDCPG_SL1%UR9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
  YDCPG_SL1%VR9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
  YDCPG_SL1%VR9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB

  IF (YDMODEL%YRML_DYN%YRDYN%LRHS_CURV) THEN
    YDCPG_SL1%ZR9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
    YDCPG_SL1%ZR9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
  ENDIF

ENDIF

YDCPG_SL1%U9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
YDCPG_SL1%U9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
YDCPG_SL1%V9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
YDCPG_SL1%V9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB

IF (YDMODEL%YRML_DYN%YRDYN%LRHS_CURV) THEN
  YDCPG_SL1%Z9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
  YDCPG_SL1%Z9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
ENDIF

YDCPG_SL1%T9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV1)=0.0_JPRB
YDCPG_SL1%T9%P (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JLEV2)=0.0_JPRB
IF (LHOOK) CALL DR_HOOK ('LAVABO_OUTLINE_000', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
