SUBROUTINE LATRAJOUT (YDCST, LDRPRSLTRJ, KPROMA, KFLEVG, KST, KEND, &
                    & KSTEST, KSTESB, PWF, PRCOLON, PGEMU)

!$ACDC singlecolumn  --process-pointers


!**** *LATRAJOUT*  - Report out of atmosphere & underground trajectories

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 27-02-2024

USE PARKIND1, ONLY : JPIM, JPRB, JPRD
USE YOMCST  , ONLY : TCST
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN  , ONLY : NULERR
IMPLICIT NONE


TYPE(TCST)         ,INTENT(IN)  :: YDCST
LOGICAL            ,INTENT(IN)  :: LDRPRSLTRJ
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KFLEVG
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KST
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KEND
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KSTEST(KPROMA)
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KSTESB(KPROMA)
REAL(KIND=JPRB)    ,INTENT(IN)  :: PWF(KPROMA,KFLEVG)
REAL(KIND=JPRD)    ,INTENT(IN)  :: PRCOLON(KPROMA)
REAL(KIND=JPRB)    ,INTENT(IN)  :: PGEMU(KPROMA)

INTEGER (KIND=JPIM) :: JROF
INTEGER (KIND=JPIM) :: ICNT

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('LATRAJOUT',0,ZHOOK_HANDLE)

ICNT = SUM(KSTEST(KST:KEND))

IF (ICNT > 0) THEN
  WRITE(NULERR,'(A,I6,A)') ' SMILAG TRAJECTORY OUT OF ATM ',ICNT,' TIMES.'
  ! print statistics
  IF (LDRPRSLTRJ) THEN
    DO JROF=KST,KEND
      IF( KSTEST(JROF) /= 0 ) THEN
        WRITE(NULERR,*) ' POINT= ',JROF,' MAX ETADOT VERTICAL VEL.= ',MAXVAL(PWF(JROF,:))
        WRITE(NULERR,*) ' LON  = ',ACOS(PRCOLON(JROF))*180._JPRB/YDCST%RPI,' degrees'
        WRITE(NULERR,*) ' LAT  = ',ASIN(PGEMU(JROF))*180._JPRB/YDCST%RPI,' degrees'
      ENDIF
    ENDDO
  ENDIF
ENDIF

ICNT = SUM(KSTESB(KST:KEND))

IF (ICNT > 0) THEN
  WRITE(NULERR,'(A,I6,A)') ' SMILAG TRAJECTORY UNDERGROUND ',ICNT,' TIMES.'
  ! print statistics
  IF (LDRPRSLTRJ) THEN
    DO JROF=KST,KEND
      IF(KSTESB(JROF) /= 0 ) THEN
        WRITE(NULERR,*) ' POINT= ',JROF,' MAX ETADOT VERTICAL VEL.= ',MAXVAL(PWF(JROF,:))
        WRITE(NULERR,*) ' LON  = ',ACOS(PRCOLON(JROF))*180._JPRB/YDCST%RPI,' degrees'
        WRITE(NULERR,*) ' LAT  = ',ASIN(PGEMU(JROF))*180._JPRB/YDCST%RPI,' degrees'
      ENDIF
    ENDDO
  ENDIF
ENDIF

IF (LHOOK) CALL DR_HOOK('LATRAJOUT',1,ZHOOK_HANDLE)

END SUBROUTINE LATRAJOUT

