INTERFACE

SUBROUTINE GPTF1_YDVARS_PARALLEL (YDGEOMETRY, YDML_GCONF, YDDYN&
&, YDDYNA, YDVARS, LDTF1, YDCPG_BNDS, YDCPG_OPTS, LDLSTEP)
USE MODEL_GENERAL_CONF_MOD,ONLY:MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE YOMDYN,ONLY:TDYN
USE YOMDYNA,ONLY:TDYNA
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (TDYN), INTENT (IN)::YDDYN
TYPE (TDYNA), INTENT (IN)::YDDYNA
TYPE (MODEL_GENERAL_CONF_TYPE), INTENT (IN)::YDML_GCONF
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
LOGICAL, INTENT (IN)::LDTF1
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
LOGICAL, INTENT (IN)::LDLSTEP
END SUBROUTINE GPTF1_YDVARS_PARALLEL


END INTERFACE
