MODULE CPLNG_TYPES_MOD

!$ACDC methods 


   USE PARKIND1, ONLY: JPIM
   USE PARKIND_OCEAN, ONLY : JPRO

   IMPLICIT NONE

   PRIVATE

   PUBLIC CPLNG_FLD_TYPE

   TYPE CPLNG_FLD_TYPE
      INTEGER(KIND=JPIM),ALLOCATABLE :: ID(:,:)
      CHARACTER(LEN=128)             :: NAME
      INTEGER(KIND=JPIM)             :: TYPE
      INTEGER(KIND=JPIM)             :: INOUT
      INTEGER(KIND=JPIM)             :: STAGE
      INTEGER(KIND=JPIM)             :: NUM_LVL
      INTEGER(KIND=JPIM)             :: NUM_CAT
      REAL(KIND=JPRO),   ALLOCATABLE :: D(:,:,:)
   CONTAINS
PROCEDURE :: ACDC_COPY => ACDC_COPY_CPLNG_FLD_TYPE
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_CPLNG_FLD_TYPE
PROCEDURE :: ACDC_HOST => ACDC_HOST_CPLNG_FLD_TYPE
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_CPLNG_FLD_TYPE
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_CPLNG_FLD_TYPE
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_CPLNG_FLD_TYPE
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_CPLNG_FLD_TYPE
END TYPE CPLNG_FLD_TYPE

INTERFACE

MODULE SUBROUTINE ACDC_COPY_CPLNG_FLD_TYPE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_CPLNG_FLD_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_CPLNG_FLD_TYPE (SELF)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_CPLNG_FLD_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_CPLNG_FLD_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_CPLNG_FLD_TYPE (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_CPLNG_FLD_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE CPLNG_TYPES_MOD
