SUBMODULE (CPLNG_TYPES_MOD) CPLNG_TYPES_MOD_CPLNG_FLD_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_CPLNG_FLD_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LD, LID
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ID), CDPATH//'%ID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NAME), CDPATH//'%NAME'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TYPE), CDPATH//'%TYPE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%INOUT), CDPATH//'%INOUT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%STAGE), CDPATH//'%STAGE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUM_LVL), CDPATH//'%NUM_LVL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUM_CAT), CDPATH//'%NUM_CAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%D), CDPATH//'%D'

END SUBROUTINE

END SUBMODULE
