SUBMODULE (INTDYN_MOD) INTDYN_MOD_THWIND_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_THWIND (SELF, KLUN)

IMPLICIT NONE
CLASS (THWIND), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%M_UH
WRITE (KLUN) SELF%M_VH
WRITE (KLUN) SELF%M_WWI
WRITE (KLUN) SELF%NDIM
END SUBROUTINE

END SUBMODULE
