SUBMODULE (MODEL_PHYSICS_RADIATION_MOD) MODEL_PHYSICS_RADIATION_MOD_MODEL_PHYSICS_RADIATION_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_MODEL_PHYSICS_RADIATION_TYPE (SELF)

IMPLICIT NONE
CLASS (MODEL_PHYSICS_RADIATION_TYPE), TARGET :: SELF
INTEGER :: J1
LOGICAL :: LYRAD_GSGEOM
CALL SELF%YRERAD%ACDC_HOST ()

CALL SELF%YRESWRT%ACDC_HOST ()

CALL SELF%YREOVLP%ACDC_HOST ()

CALL SELF%YRENEUR%ACDC_HOST ()

CALL SELF%YRELWRAD%ACDC_HOST ()

CALL SELF%YREAERD%ACDC_HOST ()

CALL SELF%YREAERATM%ACDC_HOST ()

CALL SELF%YREUVRAD%ACDC_HOST ()

CALL SELF%YRERDI%ACDC_HOST ()

CALL SELF%YREMCICA%ACDC_HOST ()

CALL SELF%YRRCOEF%ACDC_HOST ()

CALL SELF%YRTRC%ACDC_HOST ()

CALL SELF%RADGRID%ACDC_HOST ()

LYRAD_GSGEOM = ASSOCIATED (SELF%YRAD_GSGEOM)
IF (LYRAD_GSGEOM) THEN
  DO J1 = LBOUND (SELF%YRAD_GSGEOM, 1), UBOUND (SELF%YRAD_GSGEOM, 1)
    CALL SELF%YRAD_GSGEOM (J1)%ACDC_HOST ()
  ENDDO
ENDIF

CALL SELF%YRERIP%ACDC_HOST ()

CALL SELF%YRADIATION%ACDC_HOST ()

CALL SELF%YRRI%ACDC_HOST ()

CALL SELF%YRRO%ACDC_HOST ()

END SUBROUTINE

END SUBMODULE
