SUBMODULE (MODEL_PHYSICS_STOCHAST_MOD) MODEL_PHYSICS_STOCHAST_MOD_MODEL_PHYSICS_STOCHAST_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_MODEL_PHYSICS_STOCHAST_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (MODEL_PHYSICS_STOCHAST_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YRPERTPAR%ACDC_CRC64 (KLUN, CDPATH//'%YRPERTPAR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRSTOPH%ACDC_CRC64 (KLUN, CDPATH//'%YRSTOPH'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
