SUBMODULE (MODEL_GENERAL_CONF_MOD) MODEL_GENERAL_CONF_MOD_MODEL_GENERAL_CONF_TYPE_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_MODEL_GENERAL_CONF_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_GENERAL_CONF_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LGEOM
LGEOM = ASSOCIATED (SELF%GEOM)
WRITE (KLUN) LGEOM
IF (LGEOM) THEN
  CALL SELF%GEOM%ACDC_SAVE (KLUN)
ENDIF
CALL SELF%YRDIMF%ACDC_SAVE (KLUN)
CALL SELF%YGFL%ACDC_SAVE (KLUN)
CALL SELF%YRRIP%ACDC_SAVE (KLUN)
CALL SELF%YRDIMECV%ACDC_SAVE (KLUN)
CALL SELF%YRMODERR%ACDC_SAVE (KLUN)
CALL SELF%YRSPPT_CONFIG%ACDC_SAVE (KLUN)
CALL SELF%YRSPP_CONFIG%ACDC_SAVE (KLUN)
END SUBROUTINE

END SUBMODULE
