MODULE PTRGPPC

!$ACDC methods 


USE PARKIND1  ,ONLY : JPIM

IMPLICIT NONE

SAVE

!*    Pointers for grid point array for PC schemes (obsolescent feature
!      which has not yet been moved into GMV, GMVS and GFL).
!     These pointers must later to be put in GMV+GMVS (new attributes
!      to create), and also GFL for MGPPCF_GFLP.
!     They are linked to the different PC schemes and they are no
!      longer purely NH pointers, so they have been renamed in Jan 2008.

!  NFGPPC       - number of (2D) fields in PC gridpoint buffer GPPCBUF

!  MGPPC        - whole GPPCBUF-pointer.
!  -- Pointers for LPC_FULL (hydrostatic or NH):
!  MGPPCF_U     - pointer for U.
!  MGPPCF_V     - pointer for V.
!  MGPPCF_T     - pointer for T.
!  MGPPCF_SPD   - pointer for pressure departure variable.
!  MGPPCF_SVD   - pointer for vertical divergence variable.
!  MGPPCF_SP    - pointer for log(prehyds).
!  -- Additional pointers for LPC_CHEAP (hydrostatic or NH):
!     (they are used to save interpolated quantities from the predictor
!     to the corrector step).
!  MGPPCF_CP    - pointer for continuity eqn (3D quantity).
!  MGPPCF_NHX   - pointer for NHX.
!  MGPPCF_UP    - pointer for split EC physics (U eqn).
!  MGPPCF_VP    - pointer for split EC physics (V eqn).
!  MGPPCF_TP    - pointer for split EC physics (T eqn).
!  MGPPCF_GFLP  - pointer for split EC physics (GFL eqn).
!  MGPPCF_BBC   - pointer for BBC quantity (LRDBBC=T).

!  The same names with a suffix "5": pointers for trajectory.

TYPE :: TPTRGPPC
INTEGER(KIND=JPIM) :: NFGPPC

INTEGER(KIND=JPIM) :: MGPPC

INTEGER(KIND=JPIM) :: MGPPCF_U
INTEGER(KIND=JPIM) :: MGPPCF_V
INTEGER(KIND=JPIM) :: MGPPCF_T
INTEGER(KIND=JPIM) :: MGPPCF_SPD
INTEGER(KIND=JPIM) :: MGPPCF_SVD
INTEGER(KIND=JPIM) :: MGPPCF_SP

INTEGER(KIND=JPIM) :: MGPPCF_CP
INTEGER(KIND=JPIM) :: MGPPCF_NHX
INTEGER(KIND=JPIM) :: MGPPCF_UP
INTEGER(KIND=JPIM) :: MGPPCF_VP
INTEGER(KIND=JPIM) :: MGPPCF_TP
INTEGER(KIND=JPIM) :: MGPPCF_GFLP
INTEGER(KIND=JPIM) :: MGPPCF_BBC
INTEGER(KIND=JPIM) :: MGPPCF_PHI
INTEGER(KIND=JPIM) :: MGPPCF_GWS

INTEGER(KIND=JPIM) :: MGPPC5

INTEGER(KIND=JPIM) :: MGPPCF_U5
INTEGER(KIND=JPIM) :: MGPPCF_V5
INTEGER(KIND=JPIM) :: MGPPCF_T5
INTEGER(KIND=JPIM) :: MGPPCF_SPD5
INTEGER(KIND=JPIM) :: MGPPCF_SVD5
INTEGER(KIND=JPIM) :: MGPPCF_SP5

CONTAINS
  
  PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
    
PROCEDURE :: ACDC_COPY => ACDC_COPY_TPTRGPPC
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TPTRGPPC
PROCEDURE :: ACDC_HOST => ACDC_HOST_TPTRGPPC
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TPTRGPPC
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TPTRGPPC
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TPTRGPPC
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TPTRGPPC
END TYPE TPTRGPPC

!!TYPE(TPTRGPPC), POINTER :: YRPTRGPPC => NULL()
  !---------------------------------------------------------------------

INTERFACE

MODULE SUBROUTINE ACDC_COPY_TPTRGPPC (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TPTRGPPC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TPTRGPPC (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TPTRGPPC), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TPTRGPPC (SELF)

IMPLICIT NONE
CLASS (TPTRGPPC), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TPTRGPPC (SELF, KLUN)

IMPLICIT NONE
CLASS (TPTRGPPC), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TPTRGPPC (SELF, KLUN)

IMPLICIT NONE
CLASS (TPTRGPPC), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TPTRGPPC (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TPTRGPPC),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TPTRGPPC (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TPTRGPPC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

CONTAINS 
  
SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
IMPLICIT NONE
CLASS(TPTRGPPC), INTENT(IN) :: SELF
INTEGER        , INTENT(IN) :: KDEPTH
INTEGER        , INTENT(IN) :: KOUTNO

INTEGER :: IDEPTHLOC

IDEPTHLOC = KDEPTH + 2

WRITE(KOUTNO,*) REPEAT(' ',KDEPTH) // 'model%yrml_dyn%yrptrgppc : '
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'NFGPPC = ', SELF%NFGPPC
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPC = ', SELF%MGPPC
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_U = ', SELF%MGPPCF_U
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_V = ', SELF%MGPPCF_V
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_T = ', SELF%MGPPCF_T
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_SPD = ', SELF%MGPPCF_SPD
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_SVD = ', SELF%MGPPCF_SVD
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_SP = ', SELF%MGPPCF_SP
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_CP = ', SELF%MGPPCF_CP
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_NHX = ', SELF%MGPPCF_NHX
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_UP = ', SELF%MGPPCF_UP
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_VP = ', SELF%MGPPCF_VP
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_TP = ', SELF%MGPPCF_TP
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_GFLP = ', SELF%MGPPCF_GFLP
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_BBC = ', SELF%MGPPCF_BBC
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPC5 = ', SELF%MGPPC5
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_U5 = ', SELF%MGPPCF_U5
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_V5 = ', SELF%MGPPCF_V5
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_T5 = ', SELF%MGPPCF_T5
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_SPD5 = ', SELF%MGPPCF_SPD5
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_SVD5 = ', SELF%MGPPCF_SVD5
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'MGPPCF_SP5 = ', SELF%MGPPCF_SP5


END SUBROUTINE PRINT_CONFIGURATION


END MODULE PTRGPPC
