SUBMODULE (PTRSLB1) PTRSLB1_TPTRSLB1_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TPTRSLB1 (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TPTRSLB1),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LRPARSL1
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NFLDSLB1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFLDSLB1'
ENDIF
KSIZE = KSIZE + ISIZE
LRPARSL1 = ALLOCATED (SELF%RPARSL1)
IF (LRPARSL1) THEN
  ISIZE = KIND (SELF%RPARSL1) * SIZE (SELF%RPARSL1)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RPARSL1'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%MSLBUF1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLBUF1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1U9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1U9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1V9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1V9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1Z9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1Z9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1T9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1T9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1GFL9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1GFL9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1GFLSP9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1GFLSP9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1PD9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1PD9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VD9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VD9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1NHX9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1NHX9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1UR0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1UR0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VR0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VR0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1ZR0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1ZR0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1WR0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1WR0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1UR00)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1UR00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VR00)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VR00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1ZR00)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1ZR00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1WR00)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1WR00'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1WRA)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1WRA'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1UR9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1UR9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VR9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VR9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1ZR9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1ZR9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1DBBC9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1DBBC9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1DPHI9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1DPHI9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1GWS9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1GWS9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1U0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1U0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1V0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1V0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1Z0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1Z0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1T0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1T0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1PD0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1PD0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VD0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VD0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1C9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1C9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1SP9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1SP9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1SP0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1SP0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1C0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1C0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1UP9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1UP9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VP9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VP9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1ZP9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1ZP9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1TP9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1TP9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1GFLP9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1GFLP9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1U9_SI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1U9_SI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1V9_SI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1V9_SI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1T9_SI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1T9_SI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1PD9_SI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1PD9_SI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VD9_SI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VD9_SI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1C9_SI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1C9_SI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1UF9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1UF9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VF9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VF9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1TF9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1TF9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1GFLF9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1GFLF9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VDF9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VDF9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1GFLSPF9)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1GFLSPF9'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1U9_NL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1U9_NL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1V9_NL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1V9_NL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1T9_NL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1T9_NL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1PD9_NL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1PD9_NL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1VD9_NL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1VD9_NL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%MSLB1C9_NL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MSLB1C9_NL'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
