SUBMODULE (TYPE_ECV) TYPE_ECV_TECV_CONFIG_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_TECV_CONFIG (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TECV_CONFIG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LYRCONFIG
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LYRCONFIG = ALLOCATED (SELF%YRCONFIG)
IF (LYRCONFIG) THEN
  !$ACC EXIT DATA DETACH (SELF%YRCONFIG)
  DO J1 = LBOUND (SELF%YRCONFIG, 1), UBOUND (SELF%YRCONFIG, 1)
    CALL SELF%YRCONFIG (J1)%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC EXIT DATA DELETE (SELF%YRCONFIG)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
