SUBMODULE (TYPE_ECV) TYPE_ECV_TECVDIM_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TECVDIM (SELF, KLUN)

IMPLICIT NONE
CLASS (TECVDIM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%LECV_1D
READ (KLUN) SELF%LECV_2D
READ (KLUN) SELF%LECV_3D
READ (KLUN) SELF%NECV_1D
READ (KLUN) SELF%NECVSP_2D
READ (KLUN) SELF%NECVGP_2D
READ (KLUN) SELF%NECV_2D
READ (KLUN) SELF%NECVSP_3D
READ (KLUN) SELF%NECVGP_3D
READ (KLUN) SELF%NECV_3D
READ (KLUN) SELF%NECV_ALL
END SUBROUTINE

END SUBMODULE
