SUBMODULE (YEMDIM) YEMDIM_TEDIM_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TEDIM (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEDIM),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LNISMAX, LNISNAX
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%NSECPLG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSECPLG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NBZONG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NBZONG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NBZONL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NBZONL'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NBZONU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NBZONU'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NNOEXTZG)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NNOEXTZG'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NNOEXTZL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NNOEXTZL'
ENDIF
KSIZE = KSIZE + ISIZE
LNISMAX = ASSOCIATED (SELF%NISMAX)
IF (LNISMAX) THEN
  ISIZE = KIND (SELF%NISMAX) * SIZE (SELF%NISMAX)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NISMAX'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LNISNAX = ASSOCIATED (SELF%NISNAX)
IF (LNISNAX) THEN
  ISIZE = KIND (SELF%NISNAX) * SIZE (SELF%NISNAX)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%NISNAX'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%LBIPINCI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LBIPINCI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NBIPINCIX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NBIPINCIX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NBIPINCIY)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NBIPINCIY'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NEDOM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NEDOM'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
