MODULE YEMDIM

!$ACDC methods 


USE PARKIND1, ONLY : JPIM

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------

!*    Dimensions of model working arrays (YEMDIM)

!   NSECPLG: dimension for the Laplace operator

!*    Width of coupling/relaxation belts

!   NBZONG : half-difference between the size of C+I and C zone in meridional direction
!   NBZONL : half-difference between the size of C+I and C zone in zonal direction
!   NBZONU : number of levels in coupling zone
!   NNOEXTZL : alternative extension zone (E') zonal dimension
!   NNOEXTZG : alternative extension zone (E') meridional dimension

!   NISNAX : zonal limit wavenumbers within the ellipse
!   NISMAX : meridional limit wavenumbers within the ellipse

!   LBIPINCI  : Boyd coupling business (...)
!   NBIPINCIX : Boyd coupling business (...)
!   NBIPINCIY : Boyd coupling business (...)

!*    Key to be moved out (in YOMOPH or so ?)

!   NEDOM  : key: options for file ALADIN :
!                        -1 --- Gridpoint file
!                         1 --- Spectral file (Aladin standard)


TYPE :: TEDIM
INTEGER(KIND=JPIM) :: NSECPLG
INTEGER(KIND=JPIM) :: NBZONG
INTEGER(KIND=JPIM) :: NBZONL
INTEGER(KIND=JPIM) :: NBZONU
INTEGER(KIND=JPIM) :: NNOEXTZG
INTEGER(KIND=JPIM) :: NNOEXTZL
INTEGER(KIND=JPIM), POINTER :: NISMAX(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: NISNAX(:) => NULL()
LOGICAL :: LBIPINCI
INTEGER(KIND=JPIM) :: NBIPINCIX
INTEGER(KIND=JPIM) :: NBIPINCIY
INTEGER(KIND=JPIM) :: NEDOM
CONTAINS
PROCEDURE :: ACDC_COPY => ACDC_COPY_TEDIM
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TEDIM
PROCEDURE :: ACDC_HOST => ACDC_HOST_TEDIM
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TEDIM
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TEDIM
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TEDIM
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TEDIM
END TYPE TEDIM


!     ------------------------------------------------------------------
INTERFACE

MODULE SUBROUTINE ACDC_COPY_TEDIM (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEDIM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TEDIM (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TEDIM), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TEDIM (SELF)

IMPLICIT NONE
CLASS (TEDIM), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TEDIM (SELF, KLUN)

IMPLICIT NONE
CLASS (TEDIM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TEDIM (SELF, KLUN)

IMPLICIT NONE
CLASS (TEDIM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TEDIM (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEDIM),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TEDIM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEDIM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YEMDIM
