MODULE YEMGSL

!$ACDC methods 


USE PARKIND1  ,ONLY : JPRB

IMPLICIT NONE

SAVE

TYPE :: TEGSL
!*    Defining specific geometry variables for semi-Lagrangian advection in the LAM model.
!     These variables are set-up in SUEGEM_NAML and should not be modified elsewhere.
!     They are used in the ELARCHE.. routines.

!     IMPORTANT REMARK ABOUT UNITS OF ANGLES (RLON0R, RELONC, RELATC):
!      - Printings done in SUEGEM_NAML are in radians.
!      - Final values are computed in SUEGEM_NAML.
!      - When leaving SUEGEM_NAML, values SHOULD be in radians.
!      - Other routines using these values assume that they are in radians.

!     RIPORE : COPY OF XIPORE, X-location of the pole (Stereo/Lambert)
!     RJPORE : COPY OF XJPORE, Y-location of the pole (Stereo/Lambert)
!     REGPK  : COPY OF XGGPK , effective projection parameter
!     RNOBILE: QUANTITY TO SCALE THE DISTANCE TO THE POLE
!              r**2 * RNOBILE = [(1-sin(phi))/(1+sin(phi))]**REGPK  
!     RHSUD  : COPY OF HSUD                                      
!     RMERCAT: QUANTITY TO SCALE THE DISTANCE IN MERCATOR PROJECTION
!              x * RMERCAT = lon - lon0
!              y * RMERCAT = - ln(cos(phi)/(1.+sin(phi)))
!     RLON0R : ROTATED PROJECTION REFERENCE LONGITUDE (COPY OF XLON0R)                                   
!     RELONC and RELATC: longitude and latitude of the apparent pole,
!              which defines the Mercator rotated tilted projection.
!              These variables are used only for the Mercator rotated tilted projection.

REAL(KIND=JPRB) :: RIPORE
REAL(KIND=JPRB) :: RJPORE
REAL(KIND=JPRB) :: REGPK
REAL(KIND=JPRB) :: RNOBILE
REAL(KIND=JPRB) :: RHSUD
REAL(KIND=JPRB) :: RMERCAT
REAL(KIND=JPRB) :: RLON0R
REAL(KIND=JPRB) :: RELONC    
REAL(KIND=JPRB) :: RELATC 

CONTAINS
PROCEDURE :: ACDC_COPY => ACDC_COPY_TEGSL
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TEGSL
PROCEDURE :: ACDC_HOST => ACDC_HOST_TEGSL
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TEGSL
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TEGSL
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TEGSL
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TEGSL
END TYPE TEGSL

INTERFACE

MODULE SUBROUTINE ACDC_COPY_TEGSL (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEGSL), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TEGSL (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TEGSL), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TEGSL (SELF)

IMPLICIT NONE
CLASS (TEGSL), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TEGSL (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TEGSL), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TEGSL (SELF, KLUN)

IMPLICIT NONE
CLASS (TEGSL), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TEGSL (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEGSL),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TEGSL (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEGSL), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YEMGSL
