SUBMODULE (YEMLBC_MODEL) YEMLBC_MODEL_TELBC_MODEL_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_TELBC_MODEL (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TELBC_MODEL), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LEALFAGT3GFL, LEALFAGT3GMV, LEALFAGT3GMVS, LEALFAU_GFL, LEALFAU_GMV, LEALFA_GFL, LEALFA_GMV, LEALFA_GMVS, LEALFA_TENC, LEWB
LOGICAL :: LEWBDFIBW, LEWBDFIFW, LGMGT3, LGMGT4, LLNUDSPGFL
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL SELF%YYTGMVSTENC%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YYTGMVCPL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YYTGMVSCPL%ACDC_WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LEALFA_GMV = ALLOCATED (SELF%EALFA_GMV)
IF (LEALFA_GMV) THEN
  !$ACC EXIT DATA DETACH (SELF%EALFA_GMV)
  !$ACC EXIT DATA DELETE (SELF%EALFA_GMV)
ENDIF

LEALFA_GMVS = ALLOCATED (SELF%EALFA_GMVS)
IF (LEALFA_GMVS) THEN
  !$ACC EXIT DATA DETACH (SELF%EALFA_GMVS)
  !$ACC EXIT DATA DELETE (SELF%EALFA_GMVS)
ENDIF

LEALFA_GFL = ALLOCATED (SELF%EALFA_GFL)
IF (LEALFA_GFL) THEN
  !$ACC EXIT DATA DETACH (SELF%EALFA_GFL)
  !$ACC EXIT DATA DELETE (SELF%EALFA_GFL)
ENDIF

LEALFA_TENC = ALLOCATED (SELF%EALFA_TENC)
IF (LEALFA_TENC) THEN
  !$ACC EXIT DATA DETACH (SELF%EALFA_TENC)
  !$ACC EXIT DATA DELETE (SELF%EALFA_TENC)
ENDIF

LEALFAGT3GMV = ALLOCATED (SELF%EALFAGT3GMV)
IF (LEALFAGT3GMV) THEN
  !$ACC EXIT DATA DETACH (SELF%EALFAGT3GMV)
  !$ACC EXIT DATA DELETE (SELF%EALFAGT3GMV)
ENDIF

LEALFAGT3GMVS = ALLOCATED (SELF%EALFAGT3GMVS)
IF (LEALFAGT3GMVS) THEN
  !$ACC EXIT DATA DETACH (SELF%EALFAGT3GMVS)
  !$ACC EXIT DATA DELETE (SELF%EALFAGT3GMVS)
ENDIF

LEALFAGT3GFL = ALLOCATED (SELF%EALFAGT3GFL)
IF (LEALFAGT3GFL) THEN
  !$ACC EXIT DATA DETACH (SELF%EALFAGT3GFL)
  !$ACC EXIT DATA DELETE (SELF%EALFAGT3GFL)
ENDIF

LEALFAU_GMV = ALLOCATED (SELF%EALFAU_GMV)
IF (LEALFAU_GMV) THEN
  !$ACC EXIT DATA DETACH (SELF%EALFAU_GMV)
  !$ACC EXIT DATA DELETE (SELF%EALFAU_GMV)
ENDIF

LEALFAU_GFL = ALLOCATED (SELF%EALFAU_GFL)
IF (LEALFAU_GFL) THEN
  !$ACC EXIT DATA DETACH (SELF%EALFAU_GFL)
  !$ACC EXIT DATA DELETE (SELF%EALFAU_GFL)
ENDIF

LGMGT3 = ALLOCATED (SELF%GMGT3)
IF (LGMGT3) THEN
  !$ACC EXIT DATA DETACH (SELF%GMGT3)
  !$ACC EXIT DATA DELETE (SELF%GMGT3)
ENDIF

LGMGT4 = ALLOCATED (SELF%GMGT4)
IF (LGMGT4) THEN
  !$ACC EXIT DATA DETACH (SELF%GMGT4)
  !$ACC EXIT DATA DELETE (SELF%GMGT4)
ENDIF

LEWB = ALLOCATED (SELF%EWB)
IF (LEWB) THEN
  !$ACC EXIT DATA DETACH (SELF%EWB)
  !$ACC EXIT DATA DELETE (SELF%EWB)
ENDIF

LEWBDFIFW = ALLOCATED (SELF%EWBDFIFW)
IF (LEWBDFIFW) THEN
  !$ACC EXIT DATA DETACH (SELF%EWBDFIFW)
  !$ACC EXIT DATA DELETE (SELF%EWBDFIFW)
ENDIF

LEWBDFIBW = ALLOCATED (SELF%EWBDFIBW)
IF (LEWBDFIBW) THEN
  !$ACC EXIT DATA DETACH (SELF%EWBDFIBW)
  !$ACC EXIT DATA DELETE (SELF%EWBDFIBW)
ENDIF

LLNUDSPGFL = ALLOCATED (SELF%LNUDSPGFL)
IF (LLNUDSPGFL) THEN
  !$ACC EXIT DATA DETACH (SELF%LNUDSPGFL)
  !$ACC EXIT DATA DELETE (SELF%LNUDSPGFL)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
