SUBMODULE (YEMLBC_MODEL) YEMLBC_MODEL_TGMVCPL_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TGMVCPL (SELF, KLUN)

IMPLICIT NONE
CLASS (TGMVCPL), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%MU
WRITE (KLUN) SELF%MV
WRITE (KLUN) SELF%MT
WRITE (KLUN) SELF%MSPD
WRITE (KLUN) SELF%MSVD
WRITE (KLUN) SELF%MNHX
WRITE (KLUN) SELF%MDIV
WRITE (KLUN) SELF%MTL
WRITE (KLUN) SELF%MTM
WRITE (KLUN) SELF%MSPDL
WRITE (KLUN) SELF%MSPDM
WRITE (KLUN) SELF%NDIM
WRITE (KLUN) SELF%NDIMT
END SUBROUTINE

END SUBMODULE
