SUBMODULE (YEMLBC_MODEL) YEMLBC_MODEL_TGMVSTENC_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TGMVSTENC (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TGMVSTENC), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MSP), CDPATH//'%MSP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MSPL), CDPATH//'%MSPL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MSPM), CDPATH//'%MSPM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDIM), CDPATH//'%NDIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDIMT), CDPATH//'%NDIMT'

END SUBROUTINE

END SUBMODULE
