SUBMODULE (YEMLAP) YEMLAP_TLEP_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_TLEP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TLEP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LMVALUE, LNCPL2M, LNCPL2N, LNCPL4M, LNCPL4N, LNCPLM, LNCPLN, LNESM0, LNESM0G, LNESPZERO
LOGICAL :: LNPME, LNPNE, LRLEPDIM, LRLEPDIN, LRLEPINM, LRLEPINN
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LNCPL2M = ALLOCATED (SELF%NCPL2M)
IF (LNCPL2M) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPL2M)
  !$ACC UPDATE DEVICE (SELF%NCPL2M)
  !$ACC ENTER DATA ATTACH (SELF%NCPL2M)
ENDIF

LNCPL4M = ALLOCATED (SELF%NCPL4M)
IF (LNCPL4M) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPL4M)
  !$ACC UPDATE DEVICE (SELF%NCPL4M)
  !$ACC ENTER DATA ATTACH (SELF%NCPL4M)
ENDIF

LNCPLM = ALLOCATED (SELF%NCPLM)
IF (LNCPLM) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPLM)
  !$ACC UPDATE DEVICE (SELF%NCPLM)
  !$ACC ENTER DATA ATTACH (SELF%NCPLM)
ENDIF

LNCPL2N = ALLOCATED (SELF%NCPL2N)
IF (LNCPL2N) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPL2N)
  !$ACC UPDATE DEVICE (SELF%NCPL2N)
  !$ACC ENTER DATA ATTACH (SELF%NCPL2N)
ENDIF

LNCPL4N = ALLOCATED (SELF%NCPL4N)
IF (LNCPL4N) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPL4N)
  !$ACC UPDATE DEVICE (SELF%NCPL4N)
  !$ACC ENTER DATA ATTACH (SELF%NCPL4N)
ENDIF

LNCPLN = ALLOCATED (SELF%NCPLN)
IF (LNCPLN) THEN
  !$ACC ENTER DATA CREATE (SELF%NCPLN)
  !$ACC UPDATE DEVICE (SELF%NCPLN)
  !$ACC ENTER DATA ATTACH (SELF%NCPLN)
ENDIF

LRLEPDIN = ALLOCATED (SELF%RLEPDIN)
IF (LRLEPDIN) THEN
  !$ACC ENTER DATA CREATE (SELF%RLEPDIN)
  !$ACC UPDATE DEVICE (SELF%RLEPDIN)
  !$ACC ENTER DATA ATTACH (SELF%RLEPDIN)
ENDIF

LRLEPINN = ALLOCATED (SELF%RLEPINN)
IF (LRLEPINN) THEN
  !$ACC ENTER DATA CREATE (SELF%RLEPINN)
  !$ACC UPDATE DEVICE (SELF%RLEPINN)
  !$ACC ENTER DATA ATTACH (SELF%RLEPINN)
ENDIF

LRLEPDIM = ALLOCATED (SELF%RLEPDIM)
IF (LRLEPDIM) THEN
  !$ACC ENTER DATA CREATE (SELF%RLEPDIM)
  !$ACC UPDATE DEVICE (SELF%RLEPDIM)
  !$ACC ENTER DATA ATTACH (SELF%RLEPDIM)
ENDIF

LRLEPINM = ALLOCATED (SELF%RLEPINM)
IF (LRLEPINM) THEN
  !$ACC ENTER DATA CREATE (SELF%RLEPINM)
  !$ACC UPDATE DEVICE (SELF%RLEPINM)
  !$ACC ENTER DATA ATTACH (SELF%RLEPINM)
ENDIF

LNESM0 = ALLOCATED (SELF%NESM0)
IF (LNESM0) THEN
  !$ACC ENTER DATA CREATE (SELF%NESM0)
  !$ACC UPDATE DEVICE (SELF%NESM0)
  !$ACC ENTER DATA ATTACH (SELF%NESM0)
ENDIF

LNESPZERO = ALLOCATED (SELF%NESPZERO)
IF (LNESPZERO) THEN
  !$ACC ENTER DATA CREATE (SELF%NESPZERO)
  !$ACC UPDATE DEVICE (SELF%NESPZERO)
  !$ACC ENTER DATA ATTACH (SELF%NESPZERO)
ENDIF

LNESM0G = ALLOCATED (SELF%NESM0G)
IF (LNESM0G) THEN
  !$ACC ENTER DATA CREATE (SELF%NESM0G)
  !$ACC UPDATE DEVICE (SELF%NESM0G)
  !$ACC ENTER DATA ATTACH (SELF%NESM0G)
ENDIF

LNPME = ALLOCATED (SELF%NPME)
IF (LNPME) THEN
  !$ACC ENTER DATA CREATE (SELF%NPME)
  !$ACC UPDATE DEVICE (SELF%NPME)
  !$ACC ENTER DATA ATTACH (SELF%NPME)
ENDIF

LNPNE = ALLOCATED (SELF%NPNE)
IF (LNPNE) THEN
  !$ACC ENTER DATA CREATE (SELF%NPNE)
  !$ACC UPDATE DEVICE (SELF%NPNE)
  !$ACC ENTER DATA ATTACH (SELF%NPNE)
ENDIF

LMVALUE = ALLOCATED (SELF%MVALUE)
IF (LMVALUE) THEN
  !$ACC ENTER DATA CREATE (SELF%MVALUE)
  !$ACC UPDATE DEVICE (SELF%MVALUE)
  !$ACC ENTER DATA ATTACH (SELF%MVALUE)
ENDIF

END SUBROUTINE

END SUBMODULE
