SUBMODULE (YEMMP) YEMMP_TEMMP_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TEMMP (SELF, KLUN)

IMPLICIT NONE
CLASS (TEMMP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LMYENS, LNEALLNS, LNEPROCN, LNEPTRNS, LNUEMPP
READ (KLUN) LNEPROCN
IF (LNEPROCN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NEPROCN (IL1(1):IU1(1)))
  READ (KLUN) SELF%NEPROCN
ELSE
  NULLIFY (SELF%NEPROCN)
ENDIF
READ (KLUN) SELF%NUEMP
READ (KLUN) LMYENS
IF (LMYENS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%MYENS (IL1(1):IU1(1)))
  READ (KLUN) SELF%MYENS
ELSE
  NULLIFY (SELF%MYENS)
ENDIF
READ (KLUN) LNUEMPP
IF (LNUEMPP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NUEMPP (IL1(1):IU1(1)))
  READ (KLUN) SELF%NUEMPP
ELSE
  NULLIFY (SELF%NUEMPP)
ENDIF
READ (KLUN) LNEALLNS
IF (LNEALLNS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NEALLNS (IL1(1):IU1(1)))
  READ (KLUN) SELF%NEALLNS
ELSE
  NULLIFY (SELF%NEALLNS)
ENDIF
READ (KLUN) LNEPTRNS
IF (LNEPTRNS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%NEPTRNS (IL1(1):IU1(1)))
  READ (KLUN) SELF%NEPTRNS
ELSE
  NULLIFY (SELF%NEPTRNS)
ENDIF
END SUBROUTINE

END SUBMODULE
