SUBMODULE (YOE_CUCONVCA) YOE_CUCONVCA_TECUCONVCA_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TECUCONVCA (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TECUCONVCA), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LNBEW, LNBLS, LNBNS, LNBSS, LNCELLCU, LNFERTCU, LNRNBLS, LNRNBSS, LRCAPECONVCA, LRCUCONVCA
LOGICAL :: LRLATDEP, LRLATLONNBLS, LRLATLONNBSS, LRLONDEP, LRNLCONVCA, LRWASALIVE, LRWGHTCU, LSLDDLAT, LSLDLAT, LSLDLONG
LOGICAL :: LSLLAT, LSLLONG
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLIVES), CDPATH//'%NLIVES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFERTYRS), CDPATH//'%NFERTYRS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPINUP), CDPATH//'%NSPINUP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCELLCU), CDPATH//'%NCELLCU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFERTCU), CDPATH//'%NFERTCU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NBLS), CDPATH//'%NBLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NBSS), CDPATH//'%NBSS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NRNBLS), CDPATH//'%NRNBLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NRNBSS), CDPATH//'%NRNBSS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NBEW), CDPATH//'%NBEW'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NBNS), CDPATH//'%NBNS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCUCONVCA), CDPATH//'%RCUCONVCA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNLCONVCA), CDPATH//'%RNLCONVCA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCAPECONVCA), CDPATH//'%RCAPECONVCA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RWASALIVE), CDPATH//'%RWASALIVE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RWGHTCU), CDPATH//'%RWGHTCU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLATLONNBLS), CDPATH//'%RLATLONNBLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLATLONNBSS), CDPATH//'%RLATLONNBSS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPROB_SURVIVE), CDPATH//'%RPROB_SURVIVE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPROB_BIRTH), CDPATH//'%RPROB_BIRTH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPROB_FUN_FERT_S), CDPATH//'%RPROB_FUN_FERT_S'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPROB_FUN_UW_DW_S), CDPATH//'%RPROB_FUN_UW_DW_S'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPROB_FUN_FERT_B), CDPATH//'%RPROB_FUN_FERT_B'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPROB_FUN_UW_DW_B), CDPATH//'%RPROB_FUN_UW_DW_B'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLONDEP), CDPATH//'%RLONDEP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLATDEP), CDPATH//'%RLATDEP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCA_SEEDPROB), CDPATH//'%RCA_SEEDPROB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RCADELX), CDPATH//'%RCADELX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCUCONV_CA), CDPATH//'%LCUCONV_CA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCA_ADVECT), CDPATH//'%LCA_ADVECT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCA_GLOBAL), CDPATH//'%LCA_GLOBAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCA_SMOOTH), CDPATH//'%LCA_SMOOTH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCA_TEST), CDPATH//'%LCA_TEST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCA_ADVTEST), CDPATH//'%LCA_ADVTEST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCA_RANTROP), CDPATH//'%LCA_RANTROP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCA_NBDEBUG), CDPATH//'%LCA_NBDEBUG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCA_EXTRACT), CDPATH//'%LCA_EXTRACT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CA_FORC), CDPATH//'%CA_FORC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CA_WIND), CDPATH//'%CA_WIND'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CA_PROB), CDPATH//'%CA_PROB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFRCASEED), CDPATH//'%NFRCASEED'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NTESTPROC), CDPATH//'%NTESTPROC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NTESTGP), CDPATH//'%NTESTGP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDXUNREAL), CDPATH//'%NDXUNREAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDYUNREAL), CDPATH//'%NDYUNREAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SLLONG), CDPATH//'%SLLONG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SLLAT), CDPATH//'%SLLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SLDLONG), CDPATH//'%SLDLONG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SLDLAT), CDPATH//'%SLDLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SLDDLAT), CDPATH//'%SLDDLAT'

END SUBROUTINE

END SUBMODULE
