MODULE YOEAERMAP

!$ACDC methods 


USE PARKIND1  ,ONLY : JPIM, JPRB

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------
!*    ** *YOEAERMAP* - GEOGRAPHICALLY DEPENDENT PARAMETERS
!     ------------------------------------------------------------------

TYPE :: TEAERMAP
INTEGER(KIND=JPIM) :: NDUSRCP(50)

REAL(KIND=JPRB)    :: RDDUAER(50)
REAL(KIND=JPRB)    :: RDUSRCP(10,2)
!---------------------------------------------------------------------
CONTAINS
  PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION 
PROCEDURE :: ACDC_COPY => ACDC_COPY_TEAERMAP
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TEAERMAP
PROCEDURE :: ACDC_HOST => ACDC_HOST_TEAERMAP
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TEAERMAP
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TEAERMAP
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TEAERMAP
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TEAERMAP
END TYPE TEAERMAP
!=====================================================================

!!TYPE(TEAERMAP), POINTER :: YREAERMAP => NULL()

!     ------------------------------------------------------------------
! NDUSRCP ! INTEGER ! INDEX FOR DUST SOURCE TYPE
! RDUSRCP : REAL    ! 1: DUST SOURCE-RELATED REFERENCE THRESHOLD SPEED
! RDUSRCP : REAL    ! 2: DUST SOURCE-RELATED REFERENCE PARTICLE RADIUS
! RDDUAER ! REAL    ! DUST EMISSION POTENTIAL SCALING FACTOR
!     ------------------------------------------------------------------

INTERFACE

MODULE SUBROUTINE ACDC_COPY_TEAERMAP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEAERMAP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TEAERMAP (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TEAERMAP), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TEAERMAP (SELF)

IMPLICIT NONE
CLASS (TEAERMAP), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TEAERMAP (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TEAERMAP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TEAERMAP (SELF, KLUN)

IMPLICIT NONE
CLASS (TEAERMAP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TEAERMAP (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEAERMAP),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TEAERMAP (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEAERMAP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

CONTAINS

SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
IMPLICIT NONE
CLASS(TEAERMAP), INTENT(IN) :: SELF
INTEGER     , INTENT(IN) :: KDEPTH
INTEGER     , INTENT(IN) :: KOUTNO

INTEGER :: IDEPTHLOC

IDEPTHLOC = KDEPTH+2

WRITE(KOUTNO,*) REPEAT(' ',KDEPTH   ) // 'model%yrml_phy_aer%yreaermap : '
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'NDUSRCP sum = ', SUM(SELF%NDUSRCP)
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RDDUAER sum = ', SUM(SELF%RDDUAER)
WRITE(KOUTNO,*) REPEAT(' ',IDEPTHLOC) // 'RDUSRCP sum = ', SUM(SELF%RDUSRCP)

END SUBROUTINE PRINT_CONFIGURATION

END MODULE YOEAERMAP



