SUBMODULE (YOEAERSNK) YOEAERSNK_TEAERSNK_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TEAERSNK (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TEAERSNK), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDRYDEPVEL_DYN), CDPATH//'%NDRYDEPVEL_DYN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDRYDEP), CDPATH//'%NDRYDEP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R_R), CDPATH//'%R_R'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R_S), CDPATH//'%R_S'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RAERTS), CDPATH//'%RAERTS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RFRAER), CDPATH//'%RFRAER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHTAB), CDPATH//'%RRHTAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHTAB15), CDPATH//'%RRHTAB15'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSSGROWTH_RHTAB), CDPATH//'%RSSGROWTH_RHTAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSSDENS_RHTAB), CDPATH//'%RSSDENS_RHTAB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSSGROWTH_RHTAB15), CDPATH//'%RSSGROWTH_RHTAB15'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSSDENS_RHTAB15), CDPATH//'%RSSDENS_RHTAB15'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMMD_DD), CDPATH//'%RMMD_DD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHO_DD), CDPATH//'%RRHO_DD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMMD_NI), CDPATH//'%RMMD_NI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHO_NI), CDPATH//'%RRHO_NI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMMD_SS), CDPATH//'%RMMD_SS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RRHO_SS), CDPATH//'%RRHO_SS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHO_WAT), CDPATH//'%RHO_WAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHO_ICE), CDPATH//'%RHO_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHAMAKER), CDPATH//'%RHAMAKER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSO2CV1), CDPATH//'%RSO2CV1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSO2CV2), CDPATH//'%RSO2CV2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSUCV1), CDPATH//'%RSUCV1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSUCV2), CDPATH//'%RSUCV2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RVSO2CV1), CDPATH//'%RVSO2CV1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RVSO2CV2), CDPATH//'%RVSO2CV2'

END SUBROUTINE

END SUBMODULE
