SUBMODULE (YOECUMF2) YOECUMF2_TECUMF2_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TECUMF2 (SELF, KLUN)

IMPLICIT NONE
CLASS (TECUMF2), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%ENTRORG2
WRITE (KLUN) SELF%DETRPEN2
WRITE (KLUN) SELF%ENTSHALP2
WRITE (KLUN) SELF%ENTSTPC12
WRITE (KLUN) SELF%ENTSTPC22
WRITE (KLUN) SELF%ENTSTPC32
WRITE (KLUN) SELF%ENTRDD2
WRITE (KLUN) SELF%RMFCMIN2
WRITE (KLUN) SELF%RMFDEPS2
WRITE (KLUN) SELF%RDEPTHS2
WRITE (KLUN) SELF%RPRCON2
WRITE (KLUN) SELF%RTAU2
WRITE (KLUN) SELF%RCPECONS2
WRITE (KLUN) SELF%RCUCOV2
WRITE (KLUN) SELF%RTAUMEL2
WRITE (KLUN) SELF%RUVPER2
WRITE (KLUN) SELF%RMFSOLCT2
WRITE (KLUN) SELF%RMFSOLTQ2
WRITE (KLUN) SELF%RMFSOLUV2
WRITE (KLUN) SELF%RMFSOLRHS2
WRITE (KLUN) SELF%RMFCFL2
WRITE (KLUN) SELF%RMFLIA2
WRITE (KLUN) SELF%RCAPDCYCL2
WRITE (KLUN) SELF%RTAU02
WRITE (KLUN) SELF%LMFMID2
WRITE (KLUN) SELF%LMFDD2
WRITE (KLUN) SELF%LMFDUDV2
WRITE (KLUN) SELF%LMFUVDIS2
WRITE (KLUN) SELF%LMFWETB2
WRITE (KLUN) SELF%LMFGLAC2
WRITE (KLUN) SELF%NJKT12
WRITE (KLUN) SELF%NJKT22
WRITE (KLUN) SELF%NJKT32
WRITE (KLUN) SELF%NJKT52
WRITE (KLUN) SELF%NJKT62
END SUBROUTINE

END SUBMODULE
