SUBMODULE (YOECMIP) YOECMIP_TECMIP_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_TECMIP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TECMIP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRLATCLI, LRLONCLI, LROZT1, LRPROC1, LRSINC1, LZOZCL
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LZOZCL = ALLOCATED (SELF%ZOZCL)
IF (LZOZCL) THEN
  !$ACC ENTER DATA CREATE (SELF%ZOZCL)
  !$ACC UPDATE DEVICE (SELF%ZOZCL)
  !$ACC ENTER DATA ATTACH (SELF%ZOZCL)
ENDIF

LRSINC1 = ALLOCATED (SELF%RSINC1)
IF (LRSINC1) THEN
  !$ACC ENTER DATA CREATE (SELF%RSINC1)
  !$ACC UPDATE DEVICE (SELF%RSINC1)
  !$ACC ENTER DATA ATTACH (SELF%RSINC1)
ENDIF

LRPROC1 = ALLOCATED (SELF%RPROC1)
IF (LRPROC1) THEN
  !$ACC ENTER DATA CREATE (SELF%RPROC1)
  !$ACC UPDATE DEVICE (SELF%RPROC1)
  !$ACC ENTER DATA ATTACH (SELF%RPROC1)
ENDIF

LRLATCLI = ALLOCATED (SELF%RLATCLI)
IF (LRLATCLI) THEN
  !$ACC ENTER DATA CREATE (SELF%RLATCLI)
  !$ACC UPDATE DEVICE (SELF%RLATCLI)
  !$ACC ENTER DATA ATTACH (SELF%RLATCLI)
ENDIF

LRLONCLI = ALLOCATED (SELF%RLONCLI)
IF (LRLONCLI) THEN
  !$ACC ENTER DATA CREATE (SELF%RLONCLI)
  !$ACC UPDATE DEVICE (SELF%RLONCLI)
  !$ACC ENTER DATA ATTACH (SELF%RLONCLI)
ENDIF

LROZT1 = ALLOCATED (SELF%ROZT1)
IF (LROZT1) THEN
  !$ACC ENTER DATA CREATE (SELF%ROZT1)
  !$ACC UPDATE DEVICE (SELF%ROZT1)
  !$ACC ENTER DATA ATTACH (SELF%ROZT1)
ENDIF

END SUBROUTINE

END SUBMODULE
