SUBMODULE (YOEOZOC) YOEOZOC_TEOZOC_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_TEOZOC (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEOZOC), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LZOZCL, LZOZCLAQUA
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LZOZCL = ALLOCATED (SELF%ZOZCL)
IF (LZOZCL) THEN
  !$ACC EXIT DATA DETACH (SELF%ZOZCL)
  !$ACC EXIT DATA DELETE (SELF%ZOZCL)
ENDIF

LZOZCLAQUA = ALLOCATED (SELF%ZOZCLAQUA)
IF (LZOZCLAQUA) THEN
  !$ACC EXIT DATA DETACH (SELF%ZOZCLAQUA)
  !$ACC EXIT DATA DELETE (SELF%ZOZCLAQUA)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
