SUBMODULE (YOEOZOC) YOEOZOC_TEOZOC_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TEOZOC (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TEOZOC), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LZOZCL, LZOZCLAQUA
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ZOZCL), CDPATH//'%ZOZCL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ZOZCLAQUA), CDPATH//'%ZOZCLAQUA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%COZQC), CDPATH//'%COZQC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%COZQS), CDPATH//'%COZQS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%COZHC), CDPATH//'%COZHC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%COZHS), CDPATH//'%COZHS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSINC), CDPATH//'%RSINC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ROZT), CDPATH//'%ROZT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RPROC), CDPATH//'%RPROC'

END SUBROUTINE

END SUBMODULE
