SUBMODULE (YOERDI) YOERDI_TERDI_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TERDI (SELF, KLUN)

IMPLICIT NONE
CLASS (TERDI), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%RRAE
WRITE (KLUN) SELF%RSUNDUR
WRITE (KLUN) SELF%RCARDI
WRITE (KLUN) SELF%RCH4
WRITE (KLUN) SELF%RN2O
WRITE (KLUN) SELF%RNO2
WRITE (KLUN) SELF%RO3
WRITE (KLUN) SELF%RCCL4
WRITE (KLUN) SELF%RCFC11
WRITE (KLUN) SELF%RCFC12
WRITE (KLUN) SELF%RCFC22
WRITE (KLUN) SELF%REPCLC
WRITE (KLUN) SELF%REPH2O
WRITE (KLUN) SELF%RCCO2
WRITE (KLUN) SELF%RCCH4
WRITE (KLUN) SELF%RCN2O
WRITE (KLUN) SELF%RCNO2
WRITE (KLUN) SELF%RCCFC11
WRITE (KLUN) SELF%RCCFC12
WRITE (KLUN) SELF%RCCFC22
WRITE (KLUN) SELF%RCCCL4
WRITE (KLUN) SELF%RSOLINC
END SUBROUTINE

END SUBMODULE
