SUBMODULE (YOERADGHG) YOERADGHG_TRADGHG_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_TRADGHG (SELF)

IMPLICIT NONE
CLASS (TRADGHG), TARGET :: SELF
LOGICAL :: LMASS_CCL4, LMASS_CFC11, LMASS_CFC12, LMASS_CH4, LMASS_CO2, LMASS_HCFC22, LMASS_N2O, LMASS_NO2, LMASS_O3, LPRESSURE_HL
LOGICAL :: LSINLAT

END SUBROUTINE

END SUBMODULE
