SUBMODULE (YOETHF) YOETHF_TTHF_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TTHF (SELF, KLUN)

IMPLICIT NONE
CLASS (TTHF), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%R2ES
WRITE (KLUN) SELF%R3LES
WRITE (KLUN) SELF%R3IES
WRITE (KLUN) SELF%R4LES
WRITE (KLUN) SELF%R4IES
WRITE (KLUN) SELF%R5LES
WRITE (KLUN) SELF%R5IES
WRITE (KLUN) SELF%RVTMP2
WRITE (KLUN) SELF%RHOH2O
WRITE (KLUN) SELF%R5ALVCP
WRITE (KLUN) SELF%R5ALSCP
WRITE (KLUN) SELF%RALVDCP
WRITE (KLUN) SELF%RALSDCP
WRITE (KLUN) SELF%RALFDCP
WRITE (KLUN) SELF%RTWAT
WRITE (KLUN) SELF%RTBER
WRITE (KLUN) SELF%RTBERCU
WRITE (KLUN) SELF%RTICE
WRITE (KLUN) SELF%RTICECU
WRITE (KLUN) SELF%RTWAT_RTICE_R
WRITE (KLUN) SELF%RTWAT_RTICECU_R
WRITE (KLUN) SELF%RKOOP1
WRITE (KLUN) SELF%RKOOP2
END SUBROUTINE

END SUBMODULE
