SUBMODULE (YOETHF) YOETHF_TTHF_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TTHF (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TTHF), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R2ES), CDPATH//'%R2ES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R3LES), CDPATH//'%R3LES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R3IES), CDPATH//'%R3IES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R4LES), CDPATH//'%R4LES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R4IES), CDPATH//'%R4IES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R5LES), CDPATH//'%R5LES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R5IES), CDPATH//'%R5IES'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RVTMP2), CDPATH//'%RVTMP2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RHOH2O), CDPATH//'%RHOH2O'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R5ALVCP), CDPATH//'%R5ALVCP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%R5ALSCP), CDPATH//'%R5ALSCP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RALVDCP), CDPATH//'%RALVDCP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RALSDCP), CDPATH//'%RALSDCP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RALFDCP), CDPATH//'%RALFDCP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTWAT), CDPATH//'%RTWAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTBER), CDPATH//'%RTBER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTBERCU), CDPATH//'%RTBERCU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTICE), CDPATH//'%RTICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTICECU), CDPATH//'%RTICECU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTWAT_RTICE_R), CDPATH//'%RTWAT_RTICE_R'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTWAT_RTICECU_R), CDPATH//'%RTWAT_RTICECU_R'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKOOP1), CDPATH//'%RKOOP1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RKOOP2), CDPATH//'%RKOOP2'

END SUBROUTINE

END SUBMODULE
