SUBMODULE (YOM_YGFL) YOM_YGFL_TYPE_GFL_NAML_LEGACY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LEGACY_TYPE_GFL_NAML (SELF, KADDRL, KADDRU, KDIR)

IMPLICIT NONE
CLASS (TYPE_GFL_NAML), TARGET :: SELF
INTEGER*8, INTENT (IN) :: KADDRL
INTEGER*8, INTENT (IN) :: KADDRU
INTEGER, INTENT (IN) :: KDIR


END SUBROUTINE

END SUBMODULE
