SUBMODULE (YOMCST) YOMCST_TCST_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TCST (SELF, KLUN)

IMPLICIT NONE
CLASS (TCST), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%RPI
WRITE (KLUN) SELF%RCLUM
WRITE (KLUN) SELF%RHPLA
WRITE (KLUN) SELF%RKBOL
WRITE (KLUN) SELF%RNAVO
WRITE (KLUN) SELF%RDAY
WRITE (KLUN) SELF%RDAYI
WRITE (KLUN) SELF%RHOUR
WRITE (KLUN) SELF%REA
WRITE (KLUN) SELF%REPSM
WRITE (KLUN) SELF%RSIYEA
WRITE (KLUN) SELF%RSIDAY
WRITE (KLUN) SELF%ROMEGA
WRITE (KLUN) SELF%RA
WRITE (KLUN) SELF%RG
WRITE (KLUN) SELF%R1SA
WRITE (KLUN) SELF%DEG2RAD
WRITE (KLUN) SELF%RSIGMA
WRITE (KLUN) SELF%RI0
WRITE (KLUN) SELF%R
WRITE (KLUN) SELF%RMD
WRITE (KLUN) SELF%RMV
WRITE (KLUN) SELF%RMO3
WRITE (KLUN) SELF%RD
WRITE (KLUN) SELF%RV
WRITE (KLUN) SELF%RCPD
WRITE (KLUN) SELF%RCPV
WRITE (KLUN) SELF%RCVD
WRITE (KLUN) SELF%RCVV
WRITE (KLUN) SELF%RKAPPA
WRITE (KLUN) SELF%RETV
WRITE (KLUN) SELF%RMCO2
WRITE (KLUN) SELF%RMCH4
WRITE (KLUN) SELF%RMN2O
WRITE (KLUN) SELF%RMCO
WRITE (KLUN) SELF%RMHCHO
WRITE (KLUN) SELF%RMNO2
WRITE (KLUN) SELF%RMSO2
WRITE (KLUN) SELF%RMSO4
WRITE (KLUN) SELF%RMCFC11
WRITE (KLUN) SELF%RMCFC12
WRITE (KLUN) SELF%RMHCFC22
WRITE (KLUN) SELF%RMCCL4
WRITE (KLUN) SELF%RCW
WRITE (KLUN) SELF%RCS
WRITE (KLUN) SELF%RATM
WRITE (KLUN) SELF%RTT
WRITE (KLUN) SELF%RLVTT
WRITE (KLUN) SELF%RLSTT
WRITE (KLUN) SELF%RLVZER
WRITE (KLUN) SELF%RLSZER
WRITE (KLUN) SELF%RLMLT
WRITE (KLUN) SELF%RDT
WRITE (KLUN) SELF%RESTT
WRITE (KLUN) SELF%RGAMW
WRITE (KLUN) SELF%RBETW
WRITE (KLUN) SELF%RALPW
WRITE (KLUN) SELF%RGAMS
WRITE (KLUN) SELF%RBETS
WRITE (KLUN) SELF%RALPS
WRITE (KLUN) SELF%RALPD
WRITE (KLUN) SELF%RBETD
WRITE (KLUN) SELF%RGAMD
WRITE (KLUN) SELF%RK1
WRITE (KLUN) SELF%RK2
WRITE (KLUN) SELF%RK3
WRITE (KLUN) SELF%RGNSSSAT
WRITE (KLUN) SELF%RGNSSEAR
WRITE (KLUN) SELF%RAWGS
WRITE (KLUN) SELF%REWGS
WRITE (KLUN) SELF%RFWGS
WRITE (KLUN) SELF%RGEQU
WRITE (KLUN) SELF%RGRAT
WRITE (KLUN) SELF%RKSSOM
END SUBROUTINE

END SUBMODULE
