MODULE YOMCSGEOM

!$ACDC methods 


USE PARKIND1, ONLY : JPIM, JPRB, JPRD

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------

!*    * Computational sphere horizontal geometry

!     RCOLON(NGPTOT) cosine of longitude on transformed sphere
!     RSILON(NGPTOT)   sine        "             "         "
!     RINDX (NGPTOT) Longitude index
!     RINDY (NGPTOT) Latitude index
!     RATATH(NGPTOT) RA*TAN(THETA) on real sphere
!     RATATX(NGPTOT) Curvature term for LAM (for u eq.)

TYPE TCSGEOM
  REAL(KIND=JPRD), POINTER :: RCOLON(:) => NULL()
  REAL(KIND=JPRD), POINTER :: RSILON(:) => NULL()
  REAL(KIND=JPRB), POINTER :: RINDX (:) => NULL()
  REAL(KIND=JPRB), POINTER :: RINDY (:) => NULL()
  REAL(KIND=JPRB), POINTER :: RATATH(:) => NULL()
  REAL(KIND=JPRB), POINTER :: RATATX(:) => NULL()
CONTAINS
PROCEDURE :: ACDC_COPY => ACDC_COPY_TCSGEOM
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TCSGEOM
PROCEDURE :: ACDC_HOST => ACDC_HOST_TCSGEOM
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TCSGEOM
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TCSGEOM
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TCSGEOM
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TCSGEOM
END TYPE TCSGEOM

TYPE TCSGEOM_BLOCKED
  REAL(KIND=JPRD), POINTER :: RCOLON(:,:) => NULL()
  REAL(KIND=JPRD), POINTER :: RSILON(:,:) => NULL()
  REAL(KIND=JPRB), POINTER :: RINDX (:,:) => NULL()
  REAL(KIND=JPRB), POINTER :: RINDY (:,:) => NULL()
  REAL(KIND=JPRB), POINTER :: RATATH(:,:) => NULL()
  REAL(KIND=JPRB), POINTER :: RATATX(:,:) => NULL()
CONTAINS
PROCEDURE :: ACDC_COPY => ACDC_COPY_TCSGEOM_BLOCKED
PROCEDURE :: ACDC_CRC64 => ACDC_CRC64_TCSGEOM_BLOCKED
PROCEDURE :: ACDC_HOST => ACDC_HOST_TCSGEOM_BLOCKED
PROCEDURE :: ACDC_LOAD => ACDC_LOAD_TCSGEOM_BLOCKED
PROCEDURE :: ACDC_SAVE => ACDC_SAVE_TCSGEOM_BLOCKED
PROCEDURE :: ACDC_SIZE => ACDC_SIZE_TCSGEOM_BLOCKED
PROCEDURE :: ACDC_WIPE => ACDC_WIPE_TCSGEOM_BLOCKED
END TYPE TCSGEOM_BLOCKED

! define blocked and non-blocked (_NB) structures
! note that the blocked structure YRCSGEOM will be initialised to point into 
! the non-blocked structure YRCSGEOM_NB
!!TYPE(TCSGEOM), POINTER :: YRCSGEOM(:) => NULL()
!!TYPE(TCSGEOM), POINTER :: YRCSGEOM_NB => NULL()

! ------------------------------------------------------------------
INTERFACE

MODULE SUBROUTINE ACDC_COPY_TCSGEOM (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TCSGEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TCSGEOM (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TCSGEOM), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TCSGEOM (SELF)

IMPLICIT NONE
CLASS (TCSGEOM), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TCSGEOM (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TCSGEOM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TCSGEOM (SELF, KLUN)

IMPLICIT NONE
CLASS (TCSGEOM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TCSGEOM (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TCSGEOM),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TCSGEOM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TCSGEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_COPY_TCSGEOM_BLOCKED (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TCSGEOM_BLOCKED), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE ACDC_CRC64_TCSGEOM_BLOCKED (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TCSGEOM_BLOCKED), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE ACDC_HOST_TCSGEOM_BLOCKED (SELF)

IMPLICIT NONE
CLASS (TCSGEOM_BLOCKED), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE ACDC_LOAD_TCSGEOM_BLOCKED (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
CLASS (TCSGEOM_BLOCKED), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE ACDC_SAVE_TCSGEOM_BLOCKED (SELF, KLUN)

IMPLICIT NONE
CLASS (TCSGEOM_BLOCKED), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION ACDC_SIZE_TCSGEOM_BLOCKED (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TCSGEOM_BLOCKED),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE ACDC_WIPE_TCSGEOM_BLOCKED (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TCSGEOM_BLOCKED), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

CONTAINS
! ------------------------------------------------------------------

SUBROUTINE DEALLO_TCSGEOM(YDCSGEOM)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

TYPE(TCSGEOM), POINTER, INTENT(INOUT) :: YDCSGEOM(:)
INTEGER(KIND=JPIM) :: J
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('YOMCSGEOM:DEALLO_TCSGEOM',0,ZHOOK_HANDLE)

IF (ASSOCIATED(YDCSGEOM)) THEN
  DO J = 1, SIZE(YDCSGEOM)
    NULLIFY(YDCSGEOM(J)%RCOLON)
    NULLIFY(YDCSGEOM(J)%RSILON)
    NULLIFY(YDCSGEOM(J)%RINDX )
    NULLIFY(YDCSGEOM(J)%RINDY )
    NULLIFY(YDCSGEOM(J)%RATATH)
    NULLIFY(YDCSGEOM(J)%RATATX)
  ENDDO
  DEALLOCATE(YDCSGEOM)
ENDIF

IF (LHOOK) CALL DR_HOOK('YOMCSGEOM:DEALLO_TCSGEOM',1,ZHOOK_HANDLE)

END SUBROUTINE DEALLO_TCSGEOM

!     ------------------------------------------------------------------

SUBROUTINE DEALLO_TCSGEOM_NB(YDCSGEOM)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK
USE DEALLOCATE_IF_ASSOCIATED_MOD, ONLY : DEALLOCATE_IF_ASSOCIATED

TYPE(TCSGEOM), INTENT(INOUT) :: YDCSGEOM
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('YOMCSGEOM:DEALLO_TCSGEOM_NB',0,ZHOOK_HANDLE)

CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RCOLON)
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RSILON)
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RINDX )
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RINDY )
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RATATH)
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RATATX)

IF (LHOOK) CALL DR_HOOK('YOMCSGEOM:DEALLO_TCSGEOM_NB',1,ZHOOK_HANDLE)

END SUBROUTINE DEALLO_TCSGEOM_NB

SUBROUTINE DEALLO_TCSGEOM_B(YDCSGEOM)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK
USE DEALLOCATE_IF_ASSOCIATED_MOD, ONLY : DEALLOCATE_IF_ASSOCIATED

TYPE(TCSGEOM_BLOCKED), INTENT(INOUT) :: YDCSGEOM
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('YOMCSGEOM:DEALLO_TCSGEOM_B',0,ZHOOK_HANDLE)

CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RCOLON)
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RSILON)
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RINDX )
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RINDY )
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RATATH)
CALL DEALLOCATE_IF_ASSOCIATED(YDCSGEOM%RATATX)

IF (LHOOK) CALL DR_HOOK('YOMCSGEOM:DEALLO_TCSGEOM_B',1,ZHOOK_HANDLE)

END SUBROUTINE DEALLO_TCSGEOM_B

!     ------------------------------------------------------------------

END MODULE YOMCSGEOM
