SUBMODULE (YOMCOM) YOMCOM_TCOM_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TCOM (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TCOM), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LGTTLIN, LOMLDTH, LSSTMSK, LSSTPRE, LTRAFLX
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NVCOM), CDPATH//'%NVCOM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%OMLDTH), CDPATH//'%OMLDTH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GTTLIN), CDPATH//'%GTTLIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SSTPRE), CDPATH//'%SSTPRE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SSTMSK), CDPATH//'%SSTMSK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LOMLDTH), CDPATH//'%LOMLDTH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TRAFLX), CDPATH//'%TRAFLX'

END SUBROUTINE

END SUBMODULE
