SUBMODULE (YOMCSGEOM) YOMCSGEOM_TCSGEOM_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_TCSGEOM (SELF, KLUN)

IMPLICIT NONE
CLASS (TCSGEOM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LRATATH, LRATATX, LRCOLON, LRINDX, LRINDY, LRSILON
LRCOLON = ASSOCIATED (SELF%RCOLON)
WRITE (KLUN) LRCOLON
IF (LRCOLON) THEN
  WRITE (KLUN) LBOUND (SELF%RCOLON)
  WRITE (KLUN) UBOUND (SELF%RCOLON)
  WRITE (KLUN) SELF%RCOLON
ENDIF
LRSILON = ASSOCIATED (SELF%RSILON)
WRITE (KLUN) LRSILON
IF (LRSILON) THEN
  WRITE (KLUN) LBOUND (SELF%RSILON)
  WRITE (KLUN) UBOUND (SELF%RSILON)
  WRITE (KLUN) SELF%RSILON
ENDIF
LRINDX = ASSOCIATED (SELF%RINDX)
WRITE (KLUN) LRINDX
IF (LRINDX) THEN
  WRITE (KLUN) LBOUND (SELF%RINDX)
  WRITE (KLUN) UBOUND (SELF%RINDX)
  WRITE (KLUN) SELF%RINDX
ENDIF
LRINDY = ASSOCIATED (SELF%RINDY)
WRITE (KLUN) LRINDY
IF (LRINDY) THEN
  WRITE (KLUN) LBOUND (SELF%RINDY)
  WRITE (KLUN) UBOUND (SELF%RINDY)
  WRITE (KLUN) SELF%RINDY
ENDIF
LRATATH = ASSOCIATED (SELF%RATATH)
WRITE (KLUN) LRATATH
IF (LRATATH) THEN
  WRITE (KLUN) LBOUND (SELF%RATATH)
  WRITE (KLUN) UBOUND (SELF%RATATH)
  WRITE (KLUN) SELF%RATATH
ENDIF
LRATATX = ASSOCIATED (SELF%RATATX)
WRITE (KLUN) LRATATX
IF (LRATATX) THEN
  WRITE (KLUN) LBOUND (SELF%RATATX)
  WRITE (KLUN) UBOUND (SELF%RATATX)
  WRITE (KLUN) SELF%RATATX
ENDIF
END SUBROUTINE

END SUBMODULE
