SUBMODULE (YOMCHEM) YOMCHEM_TCHEM_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_TCHEM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TCHEM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LTCO2DG, LTCOTOP
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LTCO2DG = ALLOCATED (SELF%TCO2DG)
IF (LTCO2DG) THEN
  !$ACC EXIT DATA DETACH (SELF%TCO2DG)
  !$ACC EXIT DATA DELETE (SELF%TCO2DG)
ENDIF

LTCOTOP = ALLOCATED (SELF%TCOTOP)
IF (LTCOTOP) THEN
  !$ACC EXIT DATA DETACH (SELF%TCOTOP)
  !$ACC EXIT DATA DELETE (SELF%TCOTOP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
