SUBMODULE (YOMDGRADIENT) YOMDGRADIENT_TGRADIENT_PTR_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_LOAD_TGRADIENT_PTR (SELF, KLUN)

IMPLICIT NONE
CLASS (TGRADIENT_PTR), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%M_DUDX
READ (KLUN) SELF%M_DUDY
READ (KLUN) SELF%M_DVDX
READ (KLUN) SELF%M_DVDY
READ (KLUN) SELF%M_DTDX
READ (KLUN) SELF%M_DTDY
READ (KLUN) SELF%M_DQVDX
READ (KLUN) SELF%M_DQVDY
READ (KLUN) SELF%M_DQLDX
READ (KLUN) SELF%M_DQLDY
READ (KLUN) SELF%M_DQIDX
READ (KLUN) SELF%M_DQIDY
READ (KLUN) SELF%M_DQRDX
READ (KLUN) SELF%M_DQRDY
READ (KLUN) SELF%M_DQSDX
READ (KLUN) SELF%M_DQSDY
READ (KLUN) SELF%M_DQGDX
READ (KLUN) SELF%M_DQGDY
READ (KLUN) SELF%M_DU2DX2
READ (KLUN) SELF%M_DU2DY2
READ (KLUN) SELF%M_DV2DX2
READ (KLUN) SELF%M_DV2DY2
READ (KLUN) SELF%M_DUDXZ
READ (KLUN) SELF%M_DUDYZ
READ (KLUN) SELF%M_DVDXZ
READ (KLUN) SELF%M_DVDYZ
READ (KLUN) SELF%M_DWDXZ
READ (KLUN) SELF%M_DWDYZ
READ (KLUN) SELF%M_DRVDXZ
READ (KLUN) SELF%M_DRVDYZ
READ (KLUN) SELF%M_DRLDXZ
READ (KLUN) SELF%M_DRLDYZ
READ (KLUN) SELF%M_DRIDXZ
READ (KLUN) SELF%M_DRIDYZ
READ (KLUN) SELF%M_DTHETADXZ
READ (KLUN) SELF%M_DTHETADYZ
READ (KLUN) SELF%NFLDCORE
READ (KLUN) SELF%NDIM
READ (KLUN) SELF%NDIMLEO
READ (KLUN) SELF%NDIMGOG
END SUBROUTINE

END SUBMODULE
