SUBMODULE (YOMGPDDH) YOMGPDDH_TGPDDH_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TGPDDH (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TGPDDH),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LGFLTNDHD_DDH, LGFLTNDSL_DDH, LGMVTNDHD_DDH, LGMVTNDSI_DDH, LGMVTNDSL_DDH
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LGMVTNDHD_DDH = ALLOCATED (SELF%GMVTNDHD_DDH)
IF (LGMVTNDHD_DDH) THEN
  ISIZE = KIND (SELF%GMVTNDHD_DDH) * SIZE (SELF%GMVTNDHD_DDH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GMVTNDHD_DDH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGFLTNDHD_DDH = ALLOCATED (SELF%GFLTNDHD_DDH)
IF (LGFLTNDHD_DDH) THEN
  ISIZE = KIND (SELF%GFLTNDHD_DDH) * SIZE (SELF%GFLTNDHD_DDH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GFLTNDHD_DDH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGMVTNDSI_DDH = ALLOCATED (SELF%GMVTNDSI_DDH)
IF (LGMVTNDSI_DDH) THEN
  ISIZE = KIND (SELF%GMVTNDSI_DDH) * SIZE (SELF%GMVTNDSI_DDH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GMVTNDSI_DDH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGMVTNDSL_DDH = ALLOCATED (SELF%GMVTNDSL_DDH)
IF (LGMVTNDSL_DDH) THEN
  ISIZE = KIND (SELF%GMVTNDSL_DDH) * SIZE (SELF%GMVTNDSL_DDH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GMVTNDSL_DDH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGFLTNDSL_DDH = ALLOCATED (SELF%GFLTNDSL_DDH)
IF (LGFLTNDSL_DDH) THEN
  ISIZE = KIND (SELF%GFLTNDSL_DDH) * SIZE (SELF%GFLTNDSL_DDH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GFLTNDSL_DDH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END SUBMODULE
