SUBMODULE (YOMHSLMER) YOMHSLMER_THSLMER_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_THSLMER (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (THSLMER), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LR3DTW, LRIPI, LRSLD, LRSLDW
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LRIPI = ALLOCATED (SELF%RIPI)
IF (LRIPI) THEN
  !$ACC EXIT DATA DETACH (SELF%RIPI)
  !$ACC EXIT DATA DELETE (SELF%RIPI)
ENDIF

LRSLD = ALLOCATED (SELF%RSLD)
IF (LRSLD) THEN
  !$ACC EXIT DATA DETACH (SELF%RSLD)
  !$ACC EXIT DATA DELETE (SELF%RSLD)
ENDIF

LRSLDW = ALLOCATED (SELF%RSLDW)
IF (LRSLDW) THEN
  !$ACC EXIT DATA DETACH (SELF%RSLDW)
  !$ACC EXIT DATA DELETE (SELF%RSLDW)
ENDIF

LR3DTW = ALLOCATED (SELF%R3DTW)
IF (LR3DTW) THEN
  !$ACC EXIT DATA DETACH (SELF%R3DTW)
  !$ACC EXIT DATA DELETE (SELF%R3DTW)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
