SUBMODULE (YOMLOUIS) YOMLOUIS_TLOUIS_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_TLOUIS (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TLOUIS), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
