SUBMODULE (YOMMCC) YOMMCC_TMCC_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TMCC (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TMCC), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
INTEGER :: J1
LOGICAL :: LCLIMR, LCLIMRAER, LCLIMRCO2, LCLIMRCOMPO, LCPLNG_FLD, LOCEANBC, LPARTMASK, LPARTSST0, LRNEMOLVLS, LRNEMOMASK
LOGICAL :: LZLAKE
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%N923), CDPATH//'%N923'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIMTOT), CDPATH//'%NCLIMTOT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIMR), CDPATH//'%NCLIMR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIGC), CDPATH//'%NCLIGC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIGC_COMPO), CDPATH//'%NCLIGC_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NYSDMP_COMPO), CDPATH//'%NYSDMP_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIMR_COMPO), CDPATH//'%NCLIMR_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NCLIAER), CDPATH//'%NCLIAER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDIFC), CDPATH//'%NDIFC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJDCR), CDPATH//'%NJDCR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJDCR1), CDPATH//'%NJDCR1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDIFC_COMPO), CDPATH//'%NDIFC_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJDCR_COMPO), CDPATH//'%NJDCR_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NJDCR1_COMPO), CDPATH//'%NJDCR1_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NP1), CDPATH//'%NP1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NP2), CDPATH//'%NP2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPCO2_1), CDPATH//'%NPCO2_1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPCO2_2), CDPATH//'%NPCO2_2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPAER_1), CDPATH//'%NPAER_1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPAER_2), CDPATH//'%NPAER_2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPCOMPO_1), CDPATH//'%NPCOMPO_1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPCOMPO_2), CDPATH//'%NPCOMPO_2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUNITC), CDPATH//'%NUNITC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUNITC1), CDPATH//'%NUNITC1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUNITCM), CDPATH//'%NUNITCM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NOACOMM), CDPATH//'%NOACOMM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSSTICEOP), CDPATH//'%NSSTICEOP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CLIMRCO2), CDPATH//'%CLIMRCO2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CLIMRAER), CDPATH//'%CLIMRAER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CLIMRCOMPO), CDPATH//'%CLIMRCOMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%ZLAKE), CDPATH//'%ZLAKE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%OCEANBC), CDPATH//'%OCEANBC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CLIMR), CDPATH//'%CLIMR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LFIRSTUPD), CDPATH//'%LFIRSTUPD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCURR), CDPATH//'%LCURR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LGELATO), CDPATH//'%LGELATO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC01_MSE), CDPATH//'%LMCC01_MSE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC01), CDPATH//'%LMCC01'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC02), CDPATH//'%LMCC02'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC03), CDPATH//'%LMCC03'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC04), CDPATH//'%LMCC04'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC05), CDPATH//'%LMCC05'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC06), CDPATH//'%LMCC06'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCEC), CDPATH//'%LMCCEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCIEC), CDPATH//'%LMCCIEC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCIEC_COMPO), CDPATH//'%LMCCIEC_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCICEIC), CDPATH//'%LMCCICEIC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCCDYNSEAICE), CDPATH//'%LMCCDYNSEAICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOCOUP), CDPATH//'%LNEMOCOUP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOFLUXNC), CDPATH//'%LNEMOFLUXNC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOOUTGRB), CDPATH//'%LNEMOOUTGRB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCOUPINFOUT), CDPATH//'%LCOUPINFOUT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMO1WAY), CDPATH//'%LNEMO1WAY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOIFSLOG), CDPATH//'%LNEMOIFSLOG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOSSTFREEZ), CDPATH//'%LNEMOSSTFREEZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOGRIBFLDS), CDPATH//'%LNEMOGRIBFLDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOGRIBMASK), CDPATH//'%LNEMOGRIBMASK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%L2DECV2NEMO), CDPATH//'%L2DECV2NEMO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMULTIYR), CDPATH//'%LMULTIYR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LMCC_COMPO), CDPATH//'%LMCC_COMPO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFRCPL), CDPATH//'%NFRCPL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMGET), CDPATH//'%LNEMOLIMGET'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMPUT), CDPATH//'%LNEMOLIMPUT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMALB), CDPATH//'%LNEMOLIMALB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMTEMP), CDPATH//'%LNEMOLIMTEMP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMTLVL), CDPATH//'%LNEMOLIMTLVL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOLIMTHK), CDPATH//'%LNEMOLIMTHK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOSICOUP), CDPATH//'%LNEMOSICOUP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOATMFLDS), CDPATH//'%LNEMOATMFLDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOOCEICEMIX), CDPATH//'%LNEMOOCEICEMIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOQNSICEFILT), CDPATH//'%LNEMOQNSICEFILT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOACCUMFLUX), CDPATH//'%LNEMOACCUMFLUX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOGRIB3D), CDPATH//'%LNEMOGRIB3D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NNEMO3DLEVS), CDPATH//'%NNEMO3DLEVS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNEMOLVLS), CDPATH//'%RNEMOLVLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNEMOMASK), CDPATH//'%RNEMOMASK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOPARTCOUP), CDPATH//'%LNEMOPARTCOUP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOPARTMASK), CDPATH//'%LNEMOPARTMASK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LNEMOPARTMASKFILE), CDPATH//'%LNEMOPARTMASKFILE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNPARTRAMPSTART), CDPATH//'%RNPARTRAMPSTART'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNPARTRAMPLEN), CDPATH//'%RNPARTRAMPLEN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNPARTLAT), CDPATH//'%RNPARTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RNPARTLATSPREAD), CDPATH//'%RNPARTLATSPREAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PARTSST0), CDPATH//'%PARTSST0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%PARTMASK), CDPATH//'%PARTMASK'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CDNPARTMASKFILE), CDPATH//'%CDNPARTMASKFILE'

LCPLNG_FLD = ALLOCATED (SELF%CPLNG_FLD)
IF (LCPLNG_FLD) THEN
  DO J1 = LBOUND (SELF%CPLNG_FLD, 1), UBOUND (SELF%CPLNG_FLD, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%CPLNG_FLD (J1)%ACDC_CRC64 (KLUN, CDPATH//'%CPLNG_FLD'//TRIM(CLIND))
  ENDDO
ENDIF

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CPLNG_ACTIVE), CDPATH//'%CPLNG_ACTIVE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%CPLNG_NUM_FIELDS), CDPATH//'%CPLNG_NUM_FIELDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_SST), CDPATH//'%IP_A_SST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_FRAC), CDPATH//'%IP_A_ICE_FRAC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_CURR_U), CDPATH//'%IP_A_CURR_U'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_CURR_V), CDPATH//'%IP_A_CURR_V'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUX_OCE), CDPATH//'%IP_A_TAUX_OCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUY_OCE), CDPATH//'%IP_A_TAUY_OCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUX_ICE), CDPATH//'%IP_A_TAUX_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUY_ICE), CDPATH//'%IP_A_TAUY_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QS_MIX), CDPATH//'%IP_A_QS_MIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QNS_MIX), CDPATH//'%IP_A_QNS_MIX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QS_OCE), CDPATH//'%IP_A_QS_OCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QNS_OCE), CDPATH//'%IP_A_QNS_OCE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QS_ICE), CDPATH//'%IP_A_QS_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QNS_ICE), CDPATH//'%IP_A_QNS_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_PRECIP_LIQUID), CDPATH//'%IP_A_PRECIP_LIQUID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_PRECIP_SOLID), CDPATH//'%IP_A_PRECIP_SOLID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_EVAP_TOTAL), CDPATH//'%IP_A_EVAP_TOTAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_EVAP_ICE), CDPATH//'%IP_A_EVAP_ICE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_DQNS_DT), CDPATH//'%IP_A_DQNS_DT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_RUNOFF), CDPATH//'%IP_A_RUNOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TOTAL_CC), CDPATH//'%IP_A_TOTAL_CC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_LOW_CC), CDPATH//'%IP_A_LOW_CC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_TEMP), CDPATH//'%IP_A_ICE_TEMP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_ALBEDO), CDPATH//'%IP_A_ICE_ALBEDO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_THICKNESS), CDPATH//'%IP_A_ICE_THICKNESS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_SNOW_THICKNESS), CDPATH//'%IP_A_SNOW_THICKNESS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_ICE_TEMP_LVLS), CDPATH//'%IP_A_ICE_TEMP_LVLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUX), CDPATH//'%IP_A_TAUX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TAUY), CDPATH//'%IP_A_TAUY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QS), CDPATH//'%IP_A_QS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_QNS), CDPATH//'%IP_A_QNS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_WATER), CDPATH//'%IP_A_WATER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_SST_ATM), CDPATH//'%IP_A_SST_ATM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_TSK_ATM), CDPATH//'%IP_A_TSK_ATM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_IST_ATM), CDPATH//'%IP_A_IST_ATM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%IP_A_2DECV_SKT), CDPATH//'%IP_A_2DECV_SKT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LCOUPSIM), CDPATH//'%LCOUPSIM'

END SUBROUTINE

END SUBMODULE
