SUBMODULE (YOMMP) YOMMP_TMP_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_TMP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TMP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LNUMPP = ALLOCATED (SELF%NUMPP)
IF (LNUMPP) THEN
  !$ACC ENTER DATA CREATE (SELF%NUMPP)
  !$ACC UPDATE DEVICE (SELF%NUMPP)
  !$ACC ENTER DATA ATTACH (SELF%NUMPP)
ENDIF

LNPROCM = ALLOCATED (SELF%NPROCM)
IF (LNPROCM) THEN
  !$ACC ENTER DATA CREATE (SELF%NPROCM)
  !$ACC UPDATE DEVICE (SELF%NPROCM)
  !$ACC ENTER DATA ATTACH (SELF%NPROCM)
ENDIF

LNPTRMS = ALLOCATED (SELF%NPTRMS)
IF (LNPTRMS) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRMS)
  !$ACC UPDATE DEVICE (SELF%NPTRMS)
  !$ACC ENTER DATA ATTACH (SELF%NPTRMS)
ENDIF

LNALLMS = ALLOCATED (SELF%NALLMS)
IF (LNALLMS) THEN
  !$ACC ENTER DATA CREATE (SELF%NALLMS)
  !$ACC UPDATE DEVICE (SELF%NALLMS)
  !$ACC ENTER DATA ATTACH (SELF%NALLMS)
ENDIF

LNPTRLS = ALLOCATED (SELF%NPTRLS)
IF (LNPTRLS) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRLS)
  !$ACC UPDATE DEVICE (SELF%NPTRLS)
  !$ACC ENTER DATA ATTACH (SELF%NPTRLS)
ENDIF

LNPTRSV = ALLOCATED (SELF%NPTRSV)
IF (LNPTRSV) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRSV)
  !$ACC UPDATE DEVICE (SELF%NPTRSV)
  !$ACC ENTER DATA ATTACH (SELF%NPTRSV)
ENDIF

LNPTRSVF = ALLOCATED (SELF%NPTRSVF)
IF (LNPTRSVF) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRSVF)
  !$ACC UPDATE DEVICE (SELF%NPTRSVF)
  !$ACC ENTER DATA ATTACH (SELF%NPTRSVF)
ENDIF

LNPTRMF = ALLOCATED (SELF%NPTRMF)
IF (LNPTRMF) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRMF)
  !$ACC UPDATE DEVICE (SELF%NPTRMF)
  !$ACC ENTER DATA ATTACH (SELF%NPTRMF)
ENDIF

LNSPSTAF = ALLOCATED (SELF%NSPSTAF)
IF (LNSPSTAF) THEN
  !$ACC ENTER DATA CREATE (SELF%NSPSTAF)
  !$ACC UPDATE DEVICE (SELF%NSPSTAF)
  !$ACC ENTER DATA ATTACH (SELF%NSPSTAF)
ENDIF

LNUMLL = ALLOCATED (SELF%NUMLL)
IF (LNUMLL) THEN
  !$ACC ENTER DATA CREATE (SELF%NUMLL)
  !$ACC UPDATE DEVICE (SELF%NUMLL)
  !$ACC ENTER DATA ATTACH (SELF%NUMLL)
ENDIF

LNPTRLL = ALLOCATED (SELF%NPTRLL)
IF (LNPTRLL) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRLL)
  !$ACC UPDATE DEVICE (SELF%NPTRLL)
  !$ACC ENTER DATA ATTACH (SELF%NPTRLL)
ENDIF

LMYLEVS = ALLOCATED (SELF%MYLEVS)
IF (LMYLEVS) THEN
  !$ACC ENTER DATA CREATE (SELF%MYLEVS)
  !$ACC UPDATE DEVICE (SELF%MYLEVS)
  !$ACC ENTER DATA ATTACH (SELF%MYLEVS)
ENDIF

LNPSURF = ALLOCATED (SELF%NPSURF)
IF (LNPSURF) THEN
  !$ACC ENTER DATA CREATE (SELF%NPSURF)
  !$ACC UPDATE DEVICE (SELF%NPSURF)
  !$ACC ENTER DATA ATTACH (SELF%NPSURF)
ENDIF

LNSTA = ALLOCATED (SELF%NSTA)
IF (LNSTA) THEN
  !$ACC ENTER DATA CREATE (SELF%NSTA)
  !$ACC UPDATE DEVICE (SELF%NSTA)
  !$ACC ENTER DATA ATTACH (SELF%NSTA)
ENDIF

LNONL = ALLOCATED (SELF%NONL)
IF (LNONL) THEN
  !$ACC ENTER DATA CREATE (SELF%NONL)
  !$ACC UPDATE DEVICE (SELF%NONL)
  !$ACC ENTER DATA ATTACH (SELF%NONL)
ENDIF

LNPTRFRSTLAT = ALLOCATED (SELF%NPTRFRSTLAT)
IF (LNPTRFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRFRSTLAT)
  !$ACC UPDATE DEVICE (SELF%NPTRFRSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NPTRFRSTLAT)
ENDIF

LNPTRLSTLAT = ALLOCATED (SELF%NPTRLSTLAT)
IF (LNPTRLSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRLSTLAT)
  !$ACC UPDATE DEVICE (SELF%NPTRLSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NPTRLSTLAT)
ENDIF

LNPTRLAT = ALLOCATED (SELF%NPTRLAT)
IF (LNPTRLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NPTRLAT)
  !$ACC UPDATE DEVICE (SELF%NPTRLAT)
  !$ACC ENTER DATA ATTACH (SELF%NPTRLAT)
ENDIF

LNFRSTLAT = ALLOCATED (SELF%NFRSTLAT)
IF (LNFRSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NFRSTLAT)
  !$ACC UPDATE DEVICE (SELF%NFRSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NFRSTLAT)
ENDIF

LNLSTLAT = ALLOCATED (SELF%NLSTLAT)
IF (LNLSTLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NLSTLAT)
  !$ACC UPDATE DEVICE (SELF%NLSTLAT)
  !$ACC ENTER DATA ATTACH (SELF%NLSTLAT)
ENDIF

LNBSETLEV = ALLOCATED (SELF%NBSETLEV)
IF (LNBSETLEV) THEN
  !$ACC ENTER DATA CREATE (SELF%NBSETLEV)
  !$ACC UPDATE DEVICE (SELF%NBSETLEV)
  !$ACC ENTER DATA ATTACH (SELF%NBSETLEV)
ENDIF

LNGLOBALINDEX = ALLOCATED (SELF%NGLOBALINDEX)
IF (LNGLOBALINDEX) THEN
  !$ACC ENTER DATA CREATE (SELF%NGLOBALINDEX)
  !$ACC UPDATE DEVICE (SELF%NGLOBALINDEX)
  !$ACC ENTER DATA ATTACH (SELF%NGLOBALINDEX)
ENDIF

LNGLOBALAT = ALLOCATED (SELF%NGLOBALAT)
IF (LNGLOBALAT) THEN
  !$ACC ENTER DATA CREATE (SELF%NGLOBALAT)
  !$ACC UPDATE DEVICE (SELF%NGLOBALAT)
  !$ACC ENTER DATA ATTACH (SELF%NGLOBALAT)
ENDIF

LNGLOBALPROC = ALLOCATED (SELF%NGLOBALPROC)
IF (LNGLOBALPROC) THEN
  !$ACC ENTER DATA CREATE (SELF%NGLOBALPROC)
  !$ACC UPDATE DEVICE (SELF%NGLOBALPROC)
  !$ACC ENTER DATA ATTACH (SELF%NGLOBALPROC)
ENDIF

LNLOCALINDEX = ALLOCATED (SELF%NLOCALINDEX)
IF (LNLOCALINDEX) THEN
  !$ACC ENTER DATA CREATE (SELF%NLOCALINDEX)
  !$ACC UPDATE DEVICE (SELF%NLOCALINDEX)
  !$ACC ENTER DATA ATTACH (SELF%NLOCALINDEX)
ENDIF

LNLATGPP = ALLOCATED (SELF%NLATGPP)
IF (LNLATGPP) THEN
  !$ACC ENTER DATA CREATE (SELF%NLATGPP)
  !$ACC UPDATE DEVICE (SELF%NLATGPP)
  !$ACC ENTER DATA ATTACH (SELF%NLATGPP)
ENDIF

LNLONGPP = ALLOCATED (SELF%NLONGPP)
IF (LNLONGPP) THEN
  !$ACC ENTER DATA CREATE (SELF%NLONGPP)
  !$ACC UPDATE DEVICE (SELF%NLONGPP)
  !$ACC ENTER DATA ATTACH (SELF%NLONGPP)
ENDIF

LLSPLITLAT = ALLOCATED (SELF%LSPLITLAT)
IF (LLSPLITLAT) THEN
  !$ACC ENTER DATA CREATE (SELF%LSPLITLAT)
  !$ACC UPDATE DEVICE (SELF%LSPLITLAT)
  !$ACC ENTER DATA ATTACH (SELF%LSPLITLAT)
ENDIF

LMYLATS = ALLOCATED (SELF%MYLATS)
IF (LMYLATS) THEN
  !$ACC ENTER DATA CREATE (SELF%MYLATS)
  !$ACC UPDATE DEVICE (SELF%MYLATS)
  !$ACC ENTER DATA ATTACH (SELF%MYLATS)
ENDIF

LNPOSSP = ALLOCATED (SELF%NPOSSP)
IF (LNPOSSP) THEN
  !$ACC ENTER DATA CREATE (SELF%NPOSSP)
  !$ACC UPDATE DEVICE (SELF%NPOSSP)
  !$ACC ENTER DATA ATTACH (SELF%NPOSSP)
ENDIF

LNDIM0G = ALLOCATED (SELF%NDIM0G)
IF (LNDIM0G) THEN
  !$ACC ENTER DATA CREATE (SELF%NDIM0G)
  !$ACC UPDATE DEVICE (SELF%NDIM0G)
  !$ACC ENTER DATA ATTACH (SELF%NDIM0G)
ENDIF

END SUBROUTINE

END SUBMODULE
