SUBMODULE (YOMMP) YOMMP_TMP_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TMP (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TMP), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LLSPLITLAT, LMYLATS, LMYLEVS, LNALLMS, LNBSETLEV, LNDIM0G, LNFRSTLAT, LNGLOBALAT, LNGLOBALINDEX, LNGLOBALPROC
LOGICAL :: LNLATGPP, LNLOCALINDEX, LNLONGPP, LNLSTLAT, LNONL, LNPOSSP, LNPROCM, LNPSURF, LNPTRFRSTLAT, LNPTRLAT
LOGICAL :: LNPTRLL, LNPTRLS, LNPTRLSTLAT, LNPTRMF, LNPTRMS, LNPTRSV, LNPTRSVF, LNSPSTAF, LNSTA, LNUMLL
LOGICAL :: LNUMPP
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUMPP), CDPATH//'%NUMPP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPROCM), CDPATH//'%NPROCM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRMS), CDPATH//'%NPTRMS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NALLMS), CDPATH//'%NALLMS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRLS), CDPATH//'%NPTRLS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRSV), CDPATH//'%NPTRSV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRSVF), CDPATH//'%NPTRSVF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRMF), CDPATH//'%NPTRMF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPSTAF), CDPATH//'%NSPSTAF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUMLL), CDPATH//'%NUMLL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRLL), CDPATH//'%NPTRLL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYLEVS), CDPATH//'%MYLEVS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPSURF), CDPATH//'%NPSURF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSTA), CDPATH//'%NSTA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NONL), CDPATH//'%NONL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRFRSTLAT), CDPATH//'%NPTRFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRLSTLAT), CDPATH//'%NPTRLSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRLAT), CDPATH//'%NPTRLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFRSTLAT), CDPATH//'%NFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLSTLAT), CDPATH//'%NLSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NBSETLEV), CDPATH//'%NBSETLEV'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGLOBALINDEX), CDPATH//'%NGLOBALINDEX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGLOBALAT), CDPATH//'%NGLOBALAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGLOBALPROC), CDPATH//'%NGLOBALPROC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLOCALINDEX), CDPATH//'%NLOCALINDEX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLATGPP), CDPATH//'%NLATGPP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLONGPP), CDPATH//'%NLONGPP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LSPLITLAT), CDPATH//'%LSPLITLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYLATS), CDPATH//'%MYLATS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPSP), CDPATH//'%NPSP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPEC2V), CDPATH//'%NSPEC2V'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPEC2VF), CDPATH//'%NSPEC2VF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPEC2VDDH), CDPATH//'%NSPEC2VDDH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPEC2V_NH), CDPATH//'%NSPEC2V_NH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPEC2V_NHX), CDPATH//'%NSPEC2V_NHX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NBSETSP), CDPATH//'%NBSETSP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFRSTLOFF), CDPATH//'%NFRSTLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYFRSTACTLAT), CDPATH//'%MYFRSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYLSTACTLAT), CDPATH//'%MYLSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRFLOFF), CDPATH//'%NPTRFLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPOSSP), CDPATH//'%NPOSSP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDIM0G), CDPATH//'%NDIM0G'

END SUBROUTINE

END SUBMODULE
