SUBMODULE (YOMMODERRMOD) YOMMODERRMOD_TMODERR_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TMODERR (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TMODERR),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LFSTEPERR, LMSTEPERR, LTSTEPERR
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%LSCALERR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LSCALERR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LTAPERERR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LTAPERERR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NTYPE_MODERR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTYPE_MODERR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NSTEP_MODERR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSTEP_MODERR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NORDER_MODERR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NORDER_MODERR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%NPRTMODERR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NPRTMODERR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TAPERERR_INI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TAPERERR_INI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TAPERERR_END)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TAPERERR_END'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%TSTEP_ERR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%TSTEP_ERR'
ENDIF
KSIZE = KSIZE + ISIZE
LMSTEPERR = ALLOCATED (SELF%MSTEPERR)
IF (LMSTEPERR) THEN
  ISIZE = KIND (SELF%MSTEPERR) * SIZE (SELF%MSTEPERR)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%MSTEPERR'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LTSTEPERR = ALLOCATED (SELF%TSTEPERR)
IF (LTSTEPERR) THEN
  ISIZE = KIND (SELF%TSTEPERR) * SIZE (SELF%TSTEPERR)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%TSTEPERR'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LFSTEPERR = ALLOCATED (SELF%FSTEPERR)
IF (LFSTEPERR) THEN
  ISIZE = KIND (SELF%FSTEPERR) * SIZE (SELF%FSTEPERR)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%FSTEPERR'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END SUBMODULE
