SUBMODULE (YOMPRAD) YOMPRAD_RADIATION_GRID_STRUCT_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_RADIATION_GRID_STRUCT (SELF)

IMPLICIT NONE
CLASS (RADIATION_GRID_STRUCT), TARGET :: SELF
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2

END SUBROUTINE

END SUBMODULE
