SUBMODULE (YOMPHY3) YOMPHY3_TPHY3_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TPHY3 (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TPHY3), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%N_SPBAND), CDPATH//'%N_SPBAND'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RTL), CDPATH//'%RTL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BSFSA), CDPATH//'%BSFSA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BSFSI), CDPATH//'%BSFSI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BSFSN), CDPATH//'%BSFSN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BSFTA), CDPATH//'%BSFTA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BSFTI), CDPATH//'%BSFTI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%BSFTN), CDPATH//'%BSFTN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EARRT), CDPATH//'%EARRT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EOASA), CDPATH//'%EOASA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EOASI), CDPATH//'%EOASI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EOASN), CDPATH//'%EOASN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EOATA), CDPATH//'%EOATA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EOATI), CDPATH//'%EOATI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EOATN), CDPATH//'%EOATN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EODSA), CDPATH//'%EODSA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EODSI), CDPATH//'%EODSI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EODSN), CDPATH//'%EODSN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EODTA), CDPATH//'%EODTA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EODTI), CDPATH//'%EODTI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EODTN), CDPATH//'%EODTN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%EORAY), CDPATH//'%EORAY'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCA), CDPATH//'%GCA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCB), CDPATH//'%GCB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCC), CDPATH//'%GCC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCD4), CDPATH//'%GCD4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GCE4), CDPATH//'%GCE4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GIREC1), CDPATH//'%GIREC1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GIREC2), CDPATH//'%GIREC2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GIREC3), CDPATH//'%GIREC3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GIREC4), CDPATH//'%GIREC4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%QCO2), CDPATH//'%QCO2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RII0), CDPATH//'%RII0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%USAA), CDPATH//'%USAA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%USAI), CDPATH//'%USAI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%USAN), CDPATH//'%USAN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%USBA), CDPATH//'%USBA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%USBI), CDPATH//'%USBI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%USBN), CDPATH//'%USBN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDP), CDPATH//'%VDP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VNP), CDPATH//'%VNP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%REXP_NEB), CDPATH//'%REXP_NEB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_DEL_A), CDPATH//'%FCM_DEL_A'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_DEL_D), CDPATH//'%FCM_DEL_D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_MU_A), CDPATH//'%FCM_MU_A'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_MU_D), CDPATH//'%FCM_MU_D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_N_I), CDPATH//'%FCM_N_I'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_N_L), CDPATH//'%FCM_N_L'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_AI), CDPATH//'%FCM_AI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_AL), CDPATH//'%FCM_AL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_B_AI), CDPATH//'%FCM_B_AI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_B_AL), CDPATH//'%FCM_B_AL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_B_BI), CDPATH//'%FCM_B_BI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_B_BL), CDPATH//'%FCM_B_BL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_DEL_AI), CDPATH//'%FCM_DEL_AI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_DEL_AL), CDPATH//'%FCM_DEL_AL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_DEL_DI), CDPATH//'%FCM_DEL_DI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_DEL_DL), CDPATH//'%FCM_DEL_DL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_MU_AI), CDPATH//'%FCM_MU_AI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_MU_AL), CDPATH//'%FCM_MU_AL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_MU_DI), CDPATH//'%FCM_MU_DI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_MU_DL), CDPATH//'%FCM_MU_DL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_NU_AI), CDPATH//'%FCM_NU_AI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_NU_AL), CDPATH//'%FCM_NU_AL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_NU_DI), CDPATH//'%FCM_NU_DI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_NU_DL), CDPATH//'%FCM_NU_DL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_IWC2DE), CDPATH//'%FCM_IWC2DE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_LWC2RE), CDPATH//'%FCM_LWC2RE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_P_AI), CDPATH//'%FCM_P_AI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_P_AL), CDPATH//'%FCM_P_AL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_P_DI), CDPATH//'%FCM_P_DI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_P_DL), CDPATH//'%FCM_P_DL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_P_GI), CDPATH//'%FCM_P_GI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_P_GL), CDPATH//'%FCM_P_GL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_Q_AI), CDPATH//'%FCM_Q_AI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_Q_AL), CDPATH//'%FCM_Q_AL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_Q_DI), CDPATH//'%FCM_Q_DI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_Q_DL), CDPATH//'%FCM_Q_DL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_Q_GI), CDPATH//'%FCM_Q_GI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FCM_Q_GL), CDPATH//'%FCM_Q_GL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FSM_AA), CDPATH//'%FSM_AA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FSM_BB), CDPATH//'%FSM_BB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FSM_CC), CDPATH//'%FSM_CC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FSM_DD), CDPATH//'%FSM_DD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FSM_EE), CDPATH//'%FSM_EE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FSM_FF), CDPATH//'%FSM_FF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FSM_GG), CDPATH//'%FSM_GG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FSM_HH), CDPATH//'%FSM_HH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FSM_II), CDPATH//'%FSM_II'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GOLCA), CDPATH//'%GOLCA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GOLCB), CDPATH//'%GOLCB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GOLCC), CDPATH//'%GOLCC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_A), CDPATH//'%FGTS_A'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_B), CDPATH//'%FGTS_B'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_C), CDPATH//'%FGTS_C'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_ALPHA), CDPATH//'%FGTS_ALPHA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_DELTA0), CDPATH//'%FGTS_DELTA0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_D), CDPATH//'%FGTS_D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_P00), CDPATH//'%FGTS_P00'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_P), CDPATH//'%FGTS_P'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_Q), CDPATH//'%FGTS_Q'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_OA), CDPATH//'%FGTS_OA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_OB), CDPATH//'%FGTS_OB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_OC), CDPATH//'%FGTS_OC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTS_OD), CDPATH//'%FGTS_OD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_A), CDPATH//'%FGTC_A'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_B), CDPATH//'%FGTC_B'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_C), CDPATH//'%FGTC_C'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_ALPHA), CDPATH//'%FGTC_ALPHA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_DELTA0), CDPATH//'%FGTC_DELTA0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_D), CDPATH//'%FGTC_D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_P00), CDPATH//'%FGTC_P00'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_P), CDPATH//'%FGTC_P'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_Q), CDPATH//'%FGTC_Q'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_OA), CDPATH//'%FGTC_OA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_OB), CDPATH//'%FGTC_OB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_OC), CDPATH//'%FGTC_OC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTC_OD), CDPATH//'%FGTC_OD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_A), CDPATH//'%FGTT_A'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_B), CDPATH//'%FGTT_B'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_C), CDPATH//'%FGTT_C'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_ALPHA), CDPATH//'%FGTT_ALPHA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_DELTA0), CDPATH//'%FGTT_DELTA0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_D), CDPATH//'%FGTT_D'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_P00), CDPATH//'%FGTT_P00'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_P), CDPATH//'%FGTT_P'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_Q), CDPATH//'%FGTT_Q'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_OA), CDPATH//'%FGTT_OA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_OB), CDPATH//'%FGTT_OB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_OC), CDPATH//'%FGTT_OC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FGTT_OD), CDPATH//'%FGTT_OD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FRS_K_SCAT0), CDPATH//'%FRS_K_SCAT0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FRS_P_CRIT), CDPATH//'%FRS_P_CRIT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%FRS_BETA), CDPATH//'%FRS_BETA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLAMB_SOLID), CDPATH//'%RLAMB_SOLID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLAMB_WATER), CDPATH//'%RLAMB_WATER'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMIXD), CDPATH//'%RMIXD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMIXP0), CDPATH//'%RMIXP0'

END SUBROUTINE

END SUBMODULE
