SUBMODULE (YOMPRAD) YOMPRAD_RADIATION_GRID_STRUCT_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_RADIATION_GRID_STRUCT (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (RADIATION_GRID_STRUCT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LGECLO, LGELAM, LGELAT, LGEMU, LGESLO, LMYMS, LNASM0, LNFRSTLAT, LNLOENG, LNLSTLAT
LOGICAL :: LNONL, LNPTRFRSTLAT, LNRGRI, LNSTA, LRIPI, LRLATI, LRLATIG, LRMU, LRSQM2
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NRESOL_ID), CDPATH//'%NRESOL_ID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGPTOT), CDPATH//'%NGPTOT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGPTOTG), CDPATH//'%NGPTOTG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGPTOTMX), CDPATH//'%NGPTOTMX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSPEC2), CDPATH//'%NSPEC2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSMAX), CDPATH//'%NSMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRFLOFF), CDPATH//'%NPTRFLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NUMP), CDPATH//'%NUMP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDLON), CDPATH//'%NDLON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGSAL), CDPATH//'%NDGSAL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGENL), CDPATH//'%NDGENL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGSAH), CDPATH//'%NDGSAH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGENH), CDPATH//'%NDGENH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGLG), CDPATH//'%NDGLG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGSAG), CDPATH//'%NDGSAG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGENG), CDPATH//'%NDGENG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDLSUR), CDPATH//'%NDLSUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFRSTLOFF), CDPATH//'%NFRSTLOFF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDSUR1), CDPATH//'%NDSUR1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NDGSUR), CDPATH//'%NDGSUR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYFRSTACTLAT), CDPATH//'%MYFRSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYLSTACTLAT), CDPATH//'%MYLSTACTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NRGRI), CDPATH//'%NRGRI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLOENG), CDPATH//'%NLOENG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NPTRFRSTLAT), CDPATH//'%NPTRFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NFRSTLAT), CDPATH//'%NFRSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLSTLAT), CDPATH//'%NLSTLAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%MYMS), CDPATH//'%MYMS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NASM0), CDPATH//'%NASM0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NSTA), CDPATH//'%NSTA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NONL), CDPATH//'%NONL'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GELAM), CDPATH//'%GELAM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GELAT), CDPATH//'%GELAT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GECLO), CDPATH//'%GECLO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GESLO), CDPATH//'%GESLO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RMU), CDPATH//'%RMU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RSQM2), CDPATH//'%RSQM2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLATIG), CDPATH//'%RLATIG'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RLATI), CDPATH//'%RLATI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%GEMU), CDPATH//'%GEMU'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%RIPI), CDPATH//'%RIPI'

END SUBROUTINE

END SUBMODULE
