SUBMODULE (YOMRCOEF) YOMRCOEF_TRCOEF_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TRCOEF (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TRCOEF), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LSOLRAD, LTHERRAD, LTRMATSUM, LTRWEIGHT
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LRCOEF), CDPATH//'%LRCOEF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LTLADDIA), CDPATH//'%LTLADDIA'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LGLOBRAD), CDPATH//'%LGLOBRAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NG3SR), CDPATH//'%NG3SR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NGMTR), CDPATH//'%NGMTR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLATWR), CDPATH//'%NLATWR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLATRD), CDPATH//'%NLATRD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLENGSRB), CDPATH//'%NLENGSRB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%NLENGTRB), CDPATH//'%NLENGTRB'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%SOLRAD), CDPATH//'%SOLRAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%THERRAD), CDPATH//'%THERRAD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TRWEIGHT), CDPATH//'%TRWEIGHT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%TRMATSUM), CDPATH//'%TRMATSUM'

END SUBROUTINE

END SUBMODULE
