SUBMODULE (YOMSPHYHIST) YOMSPHYHIST_SPHYS_HIST_TYPE_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_SPHYS_HIST_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (SPHYS_HIST_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRADLWM, LRADLWM5, LTGWDWMSU, LTGWDWMSU5, LTGWDWMSV, LTGWDWMSV5, LYA5, LYI5, LYL5
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LYA5 = ASSOCIATED (SELF%YA5)
IF (LYA5) THEN
  !$ACC EXIT DATA DETACH (SELF%YA5)
  !$ACC EXIT DATA DELETE (SELF%YA5)
ENDIF

LYL5 = ASSOCIATED (SELF%YL5)
IF (LYL5) THEN
  !$ACC EXIT DATA DETACH (SELF%YL5)
  !$ACC EXIT DATA DELETE (SELF%YL5)
ENDIF

LYI5 = ASSOCIATED (SELF%YI5)
IF (LYI5) THEN
  !$ACC EXIT DATA DETACH (SELF%YI5)
  !$ACC EXIT DATA DELETE (SELF%YI5)
ENDIF

LRADLWM = ASSOCIATED (SELF%RADLWM)
IF (LRADLWM) THEN
  !$ACC EXIT DATA DETACH (SELF%RADLWM)
  !$ACC EXIT DATA DELETE (SELF%RADLWM)
ENDIF

LRADLWM5 = ASSOCIATED (SELF%RADLWM5)
IF (LRADLWM5) THEN
  !$ACC EXIT DATA DETACH (SELF%RADLWM5)
  !$ACC EXIT DATA DELETE (SELF%RADLWM5)
ENDIF

LTGWDWMSU = ASSOCIATED (SELF%TGWDWMSU)
IF (LTGWDWMSU) THEN
  !$ACC EXIT DATA DETACH (SELF%TGWDWMSU)
  !$ACC EXIT DATA DELETE (SELF%TGWDWMSU)
ENDIF

LTGWDWMSU5 = ASSOCIATED (SELF%TGWDWMSU5)
IF (LTGWDWMSU5) THEN
  !$ACC EXIT DATA DETACH (SELF%TGWDWMSU5)
  !$ACC EXIT DATA DELETE (SELF%TGWDWMSU5)
ENDIF

LTGWDWMSV = ASSOCIATED (SELF%TGWDWMSV)
IF (LTGWDWMSV) THEN
  !$ACC EXIT DATA DETACH (SELF%TGWDWMSV)
  !$ACC EXIT DATA DELETE (SELF%TGWDWMSV)
ENDIF

LTGWDWMSV5 = ASSOCIATED (SELF%TGWDWMSV5)
IF (LTGWDWMSV5) THEN
  !$ACC EXIT DATA DETACH (SELF%TGWDWMSV5)
  !$ACC EXIT DATA DELETE (SELF%TGWDWMSV5)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
