SUBMODULE (YOMSRFTLAD) YOMSRFTLAD_TSRFTLAD_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_TSRFTLAD (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TSRFTLAD),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LGPTSKIN0, LGPTSKIN9
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
LGPTSKIN0 = ALLOCATED (SELF%GPTSKIN0)
IF (LGPTSKIN0) THEN
  ISIZE = KIND (SELF%GPTSKIN0) * SIZE (SELF%GPTSKIN0)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GPTSKIN0'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LGPTSKIN9 = ALLOCATED (SELF%GPTSKIN9)
IF (LGPTSKIN9) THEN
  ISIZE = KIND (SELF%GPTSKIN9) * SIZE (SELF%GPTSKIN9)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%GPTSKIN9'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (SELF%NGSKIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGSKIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%LREGSF)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LREGSF'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
