SUBMODULE (YOMSTA) YOMSTA_TSTA_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_TSTA (SELF)

IMPLICIT NONE
CLASS (TSTA), TARGET :: SELF
LOGICAL :: LSTDEN, LSTPHI, LSTPRE, LSTPREH, LSTTEM, LSTZ, LSVETAF, LSVETAH

END SUBROUTINE

END SUBMODULE
