SUBMODULE (YOMVDOZ) YOMVDOZ_TVDOZ_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TVDOZ (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TVDOZ), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDHJS), CDPATH//'%VDHJS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDHJH), CDPATH//'%VDHJH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDHNS), CDPATH//'%VDHNS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDHNH), CDPATH//'%VDHNH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDPJS), CDPATH//'%VDPJS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDPJH), CDPATH//'%VDPJH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDPNS), CDPATH//'%VDPNS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDPNH), CDPATH//'%VDPNH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDEJS), CDPATH//'%VDEJS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDEJH), CDPATH//'%VDEJH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDENS), CDPATH//'%VDENS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDENH), CDPATH//'%VDENH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDAJS), CDPATH//'%VDAJS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDAJH), CDPATH//'%VDAJH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDANS), CDPATH//'%VDANS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDANH), CDPATH//'%VDANH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDNJS), CDPATH//'%VDNJS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDNJH), CDPATH//'%VDNJH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDNNS), CDPATH//'%VDNNS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDNNH), CDPATH//'%VDNNH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VOZNJ), CDPATH//'%VOZNJ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VOZHS), CDPATH//'%VOZHS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LRDIFOZ), CDPATH//'%LRDIFOZ'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%LRDEPOZ), CDPATH//'%LRDEPOZ'

END SUBROUTINE

END SUBMODULE
