SUBMODULE (YOMVERT) YOMVERT_TVETA_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_TVETA (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (TVETA), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LVDETA_RATIO, LVETAF, LVETAH, LVETA_H, LVETA_LAITRIQM3D, LVFE_ETAF, LVFE_ETAH, LVFE_RDETAH, LVRDETAH, LVWEI
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VETAH), CDPATH//'%VETAH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VFE_ETAH), CDPATH//'%VFE_ETAH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VETAF), CDPATH//'%VETAF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VFE_ETAF), CDPATH//'%VFE_ETAF'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VFE_RDETAH), CDPATH//'%VFE_RDETAH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VDETA_RATIO), CDPATH//'%VDETA_RATIO'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VRDETAH), CDPATH//'%VRDETAH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VWEI), CDPATH//'%VWEI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VETA_H), CDPATH//'%VETA_H'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (SELF%VETA_LAITRIQM3D), CDPATH//'%VETA_LAITRIQM3D'

END SUBROUTINE

END SUBMODULE
