SUBMODULE (YOMVERT) YOMVERT_TVFE_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_WIPE_TVFE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TVFE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRDDERBF01, LRDDERI, LRDERB, LRDERBF00, LRDERBF01, LRDERBF10, LRDERBF11, LRDERBH00, LRDERBH01, LRDERGW
LOGICAL :: LRDERI, LRINTBF00, LRINTBF11, LRINTC, LRINTE, LRINTG, LRINTGW, LVFE_KNOT
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVFE_KNOT = ALLOCATED (SELF%VFE_KNOT)
IF (LVFE_KNOT) THEN
  !$ACC EXIT DATA DETACH (SELF%VFE_KNOT)
  !$ACC EXIT DATA DELETE (SELF%VFE_KNOT)
ENDIF

LRINTE = ALLOCATED (SELF%RINTE)
IF (LRINTE) THEN
  !$ACC EXIT DATA DETACH (SELF%RINTE)
  !$ACC EXIT DATA DELETE (SELF%RINTE)
ENDIF

LRINTBF00 = ALLOCATED (SELF%RINTBF00)
IF (LRINTBF00) THEN
  !$ACC EXIT DATA DETACH (SELF%RINTBF00)
  !$ACC EXIT DATA DELETE (SELF%RINTBF00)
ENDIF

LRINTBF11 = ALLOCATED (SELF%RINTBF11)
IF (LRINTBF11) THEN
  !$ACC EXIT DATA DETACH (SELF%RINTBF11)
  !$ACC EXIT DATA DELETE (SELF%RINTBF11)
ENDIF

LRDERI = ALLOCATED (SELF%RDERI)
IF (LRDERI) THEN
  !$ACC EXIT DATA DETACH (SELF%RDERI)
  !$ACC EXIT DATA DELETE (SELF%RDERI)
ENDIF

LRDERB = ALLOCATED (SELF%RDERB)
IF (LRDERB) THEN
  !$ACC EXIT DATA DETACH (SELF%RDERB)
  !$ACC EXIT DATA DELETE (SELF%RDERB)
ENDIF

LRDERBF00 = ALLOCATED (SELF%RDERBF00)
IF (LRDERBF00) THEN
  !$ACC EXIT DATA DETACH (SELF%RDERBF00)
  !$ACC EXIT DATA DELETE (SELF%RDERBF00)
ENDIF

LRDERBF01 = ALLOCATED (SELF%RDERBF01)
IF (LRDERBF01) THEN
  !$ACC EXIT DATA DETACH (SELF%RDERBF01)
  !$ACC EXIT DATA DELETE (SELF%RDERBF01)
ENDIF

LRDERBF10 = ALLOCATED (SELF%RDERBF10)
IF (LRDERBF10) THEN
  !$ACC EXIT DATA DETACH (SELF%RDERBF10)
  !$ACC EXIT DATA DELETE (SELF%RDERBF10)
ENDIF

LRDERBF11 = ALLOCATED (SELF%RDERBF11)
IF (LRDERBF11) THEN
  !$ACC EXIT DATA DETACH (SELF%RDERBF11)
  !$ACC EXIT DATA DELETE (SELF%RDERBF11)
ENDIF

LRDERBH00 = ALLOCATED (SELF%RDERBH00)
IF (LRDERBH00) THEN
  !$ACC EXIT DATA DETACH (SELF%RDERBH00)
  !$ACC EXIT DATA DELETE (SELF%RDERBH00)
ENDIF

LRDERBH01 = ALLOCATED (SELF%RDERBH01)
IF (LRDERBH01) THEN
  !$ACC EXIT DATA DETACH (SELF%RDERBH01)
  !$ACC EXIT DATA DELETE (SELF%RDERBH01)
ENDIF

LRDDERI = ALLOCATED (SELF%RDDERI)
IF (LRDDERI) THEN
  !$ACC EXIT DATA DETACH (SELF%RDDERI)
  !$ACC EXIT DATA DELETE (SELF%RDDERI)
ENDIF

LRDDERBF01 = ALLOCATED (SELF%RDDERBF01)
IF (LRDDERBF01) THEN
  !$ACC EXIT DATA DETACH (SELF%RDDERBF01)
  !$ACC EXIT DATA DELETE (SELF%RDDERBF01)
ENDIF

LRINTGW = ALLOCATED (SELF%RINTGW)
IF (LRINTGW) THEN
  !$ACC EXIT DATA DETACH (SELF%RINTGW)
  !$ACC EXIT DATA DELETE (SELF%RINTGW)
ENDIF

LRDERGW = ALLOCATED (SELF%RDERGW)
IF (LRDERGW) THEN
  !$ACC EXIT DATA DETACH (SELF%RDERGW)
  !$ACC EXIT DATA DELETE (SELF%RDERGW)
ENDIF

LRINTG = ALLOCATED (SELF%RINTG)
IF (LRINTG) THEN
  !$ACC EXIT DATA DETACH (SELF%RINTG)
  !$ACC EXIT DATA DELETE (SELF%RINTG)
ENDIF

LRINTC = ALLOCATED (SELF%RINTC)
IF (LRINTC) THEN
  !$ACC EXIT DATA DETACH (SELF%RINTC)
  !$ACC EXIT DATA DELETE (SELF%RINTC)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
