
MODULE MODE_COMPUTE_FUNCTION_THERMO_MF_OPENACC


IMPLICIT NONE


CONTAINS
SUBROUTINE COMPUTE_FUNCTION_THERMO_MF_OPENACC (D, CST, KRR, KRRL, KRRI, OSTATNW&
&, PTH, PR, PEXN, PFRAC_ICE, PPABS, PT, PAMOIST, PATHETA, YDSTACK)
!$ACC ROUTINE (COMPUTE_FUNCTION_THERMO_MF_OPENACC) SEQ
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE MODD_CST,ONLY:CST_T

#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE

TYPE (DIMPHYEX_T), INTENT (IN)::D
TYPE (CST_T), INTENT (IN)::CST
LOGICAL, INTENT (IN)::OSTATNW
INTEGER, INTENT (IN)::KRR
INTEGER, INTENT (IN)::KRRL
INTEGER, INTENT (IN)::KRRI
REAL, INTENT (IN)::PTH(D%NIJT, D%NKT)
REAL, INTENT (IN)::PR(D%NIJT, D%NKT, KRR)
REAL, INTENT (IN)::PEXN(D%NIJT, D%NKT)
REAL, INTENT (IN)::PPABS(D%NIJT, D%NKT)
REAL, INTENT (IN)::PFRAC_ICE(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PT(D%NIJT, D%NKT)
REAL, INTENT (OUT)::PATHETA(D%NIJT, D%NKT)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
REAL, INTENT (OUT)::PAMOIST(D%NIJT, D%NKT)
REAL::ZEPS
fxtran_acdc_temp (REAL, ZLSOCP, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZLVOCP, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZATHETA_I, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZAMOIST_I, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZATHETA_W, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZAMOIST_W, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZDEDT, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZE, (D%NIJT, D%NKT))
fxtran_acdc_temp (REAL, ZCP, (D%NIJT, D%NKT))
INTEGER::JK
INTEGER::JI
INTEGER::JRR
INTEGER::IIJE
INTEGER::IIJB
INTEGER::IKTE
INTEGER::IKTB


YLSTACK = YDSTACK



IF (KIND (ZLSOCP) == 8) THEN
    fxtran_acdc_alloc8 (ZLSOCP)
ELSEIF (KIND (ZLSOCP) == 4) THEN
    fxtran_acdc_alloc4 (ZLSOCP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZLVOCP) == 8) THEN
    fxtran_acdc_alloc8 (ZLVOCP)
ELSEIF (KIND (ZLVOCP) == 4) THEN
    fxtran_acdc_alloc4 (ZLVOCP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZATHETA_I) == 8) THEN
    fxtran_acdc_alloc8 (ZATHETA_I)
ELSEIF (KIND (ZATHETA_I) == 4) THEN
    fxtran_acdc_alloc4 (ZATHETA_I)
ELSE
    STOP 1
ENDIF


IF (KIND (ZAMOIST_I) == 8) THEN
    fxtran_acdc_alloc8 (ZAMOIST_I)
ELSEIF (KIND (ZAMOIST_I) == 4) THEN
    fxtran_acdc_alloc4 (ZAMOIST_I)
ELSE
    STOP 1
ENDIF


IF (KIND (ZATHETA_W) == 8) THEN
    fxtran_acdc_alloc8 (ZATHETA_W)
ELSEIF (KIND (ZATHETA_W) == 4) THEN
    fxtran_acdc_alloc4 (ZATHETA_W)
ELSE
    STOP 1
ENDIF


IF (KIND (ZAMOIST_W) == 8) THEN
    fxtran_acdc_alloc8 (ZAMOIST_W)
ELSEIF (KIND (ZAMOIST_W) == 4) THEN
    fxtran_acdc_alloc4 (ZAMOIST_W)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDEDT) == 8) THEN
    fxtran_acdc_alloc8 (ZDEDT)
ELSEIF (KIND (ZDEDT) == 4) THEN
    fxtran_acdc_alloc4 (ZDEDT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZE) == 8) THEN
    fxtran_acdc_alloc8 (ZE)
ELSEIF (KIND (ZE) == 4) THEN
    fxtran_acdc_alloc4 (ZE)
ELSE
    STOP 1
ENDIF


IF (KIND (ZCP) == 8) THEN
    fxtran_acdc_alloc8 (ZCP)
ELSEIF (KIND (ZCP) == 4) THEN
    fxtran_acdc_alloc4 (ZCP)
ELSE
    STOP 1
ENDIF


JI = D%NIB


IIJE=D%NIJE
IIJB=D%NIJB
IKTB=D%NKTB
IKTE=D%NKTE
ZEPS=CST%XMV/CST%XMD
ZCP(JI,:)=CST%XCPD

IF (KRR>0) THEN

  DO JK=IKTB, IKTE
    
    ZCP (JI, JK)=ZCP (JI, JK)+CST%XCPV*PR (JI, JK, 1)
  
  ENDDO

ENDIF


DO JRR=2, 1+KRRL

  DO JK=IKTB, IKTE
    
    ZCP (JI, JK)=ZCP (JI, JK)+CST%XCL*PR (JI, JK, JRR)
  
  ENDDO

ENDDO


DO JRR=2+KRRL, 1+KRRL+KRRI

  DO JK=IKTB, IKTE
    
    ZCP (JI, JK)=ZCP (JI, JK)+CST%XCI*PR (JI, JK, JRR)
  
  ENDDO

ENDDO


DO JK=IKTB, IKTE
  
  PT (JI, JK)=PTH (JI, JK)*PEXN (JI, JK)
  
ENDDO


IF (KRRL>=1) THEN

  DO JK=IKTB, IKTE
    
    ZLVOCP (JI, JK)=(CST%XLVTT+(CST%XCPV-CST%XCL)*(PT (JI, JK)-CST%XTT))/ZCP (JI, JK)
    ZE (JI, JK)=EXP (CST%XALPW-CST%XBETAW/PT (JI, JK)-CST%XGAMW*ALOG (PT (JI, JK)))
    ZE (JI, JK)=ZE (JI, JK)*ZEPS/(PPABS (JI, JK)-ZE (JI, JK))
    ZDEDT (JI, JK)=(CST%XBETAW/PT (JI, JK)-CST%XGAMW)/PT (JI, JK)*ZE (JI, JK)*(1.+ZE (JI, JK)/ZEPS)

    IF (OSTATNW) THEN
      ZAMOIST_W (JI, JK)=1.0/(1.0+ZDEDT (JI, JK)*ZLVOCP (JI, JK))
      ZATHETA_W (JI, JK)=ZAMOIST_W (JI, JK)*PEXN (JI, JK)*ZDEDT (JI, JK)
    ELSE
      ZAMOIST_W (JI, JK)=0.5/(1.0+ZDEDT (JI, JK)*ZLVOCP (JI, JK))
      ZATHETA_W (JI, JK)=ZAMOIST_W (JI, JK)*PEXN (JI, JK)*((ZE (JI, JK)-PR (JI, JK, 1))*ZLVOCP&
      & (JI, JK)/(1.+ZDEDT (JI, JK)*ZLVOCP (JI, JK))*(ZE (JI, JK)*(1.+ZE (JI, JK)/ZEPS)*(&
      &-2.*CST%XBETAW/PT (JI, JK)+CST%XGAMW)/PT (JI, JK)**2+ZDEDT (JI, JK)*(1.+2.*ZE (JI,&
      & JK)/ZEPS)*(CST%XBETAW/PT (JI, JK)-CST%XGAMW)/PT (JI, JK))-ZDEDT (JI, JK))
    ENDIF

  
  ENDDO


  IF (KRRI>=1) THEN

    DO JK=IKTB, IKTE
      
      ZLSOCP (JI, JK)=(CST%XLSTT+(CST%XCPV-CST%XCI)*(PT (JI, JK)-CST%XTT))/ZCP (JI, JK)
      ZE (JI, JK)=EXP (CST%XALPI-CST%XBETAI/PT (JI, JK)-CST%XGAMI*ALOG (PT (JI, JK)))
      ZE (JI, JK)=ZE (JI, JK)*ZEPS/(PPABS (JI, JK)-ZE (JI, JK))
      ZDEDT (JI, JK)=(CST%XBETAI/PT (JI, JK)-CST%XGAMI)/PT (JI, JK)*ZE (JI, JK)*(1.+ZE (JI, JK)/ZEPS)

      IF (OSTATNW) THEN
        ZAMOIST_I (JI, JK)=1.0/(1.0+ZDEDT (JI, JK)*ZLVOCP (JI, JK))
        ZATHETA_I (JI, JK)=ZAMOIST_I (JI, JK)*PEXN (JI, JK)*ZDEDT (JI, JK)
      ELSE
        ZAMOIST_I (JI, JK)=0.5/(1.0+ZDEDT (JI, JK)*ZLSOCP (JI, JK))
        ZATHETA_I (JI, JK)=ZAMOIST_I (JI, JK)*PEXN (JI, JK)*((ZE (JI, JK)-PR (JI, JK, 1))*ZLSOCP&
        & (JI, JK)/(1.+ZDEDT (JI, JK)*ZLSOCP (JI, JK))*(ZE (JI, JK)*(1.+ZE (JI, JK)/ZEPS)*(&
        &-2.*CST%XBETAI/PT (JI, JK)+CST%XGAMI)/PT (JI, JK)**2+ZDEDT (JI, JK)*(1.+2.*ZE (JI,&
        & JK)/ZEPS)*(CST%XBETAI/PT (JI, JK)-CST%XGAMI)/PT (JI, JK))-ZDEDT (JI, JK))
      ENDIF

    
    ENDDO

  ELSE
    ZAMOIST_I (JI, IKTB:IKTE)=0.
    ZATHETA_I (JI, IKTB:IKTE)=0.
  ENDIF


  DO JK=IKTB, IKTE
    
    PAMOIST (JI, JK)=(1.0-PFRAC_ICE (JI, JK))*ZAMOIST_W (JI, JK)+PFRAC_ICE (JI, JK)*ZAMOIST_I (JI, JK)
    PATHETA (JI, JK)=(1.0-PFRAC_ICE (JI, JK))*ZATHETA_W (JI, JK)+PFRAC_ICE (JI, JK)*ZATHETA_I (JI, JK)
  
  ENDDO

ELSE
  PAMOIST (JI, IKTB:IKTE)=0.
  PATHETA (JI, IKTB:IKTE)=0.
ENDIF


END SUBROUTINE COMPUTE_FUNCTION_THERMO_MF_OPENACC

ENDMODULE MODE_COMPUTE_FUNCTION_THERMO_MF_OPENACC
