INTERFACE
SUBROUTINE LASCAW_CLATURB_OPENACC (YDSL, KFLEV, KPROMA, KST&
&, KEND, KILA, PKHTURB, P3DTW, PCLA, PCLASLD, YDSTACK)
!$ACC ROUTINE (LASCAW_CLATURB_OPENACC) SEQ
USE PARKIND1,ONLY:JPIB, JPIM, JPRB
USE EINT_MOD,ONLY:SL_STRUCT
USE STACK_MOD
USE ABOR1_ACC_MOD
IMPLICIT NONE
TYPE (SL_STRUCT), INTENT (IN)::YDSL
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KILA (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PKHTURB (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::P3DTW (3, 3, YDSL%NDGSAH:YDSL%NDGENH)
REAL (KIND=JPRB), INTENT (INOUT)::PCLA (KPROMA, KFLEV, 3)
REAL (KIND=JPRB), INTENT (INOUT)::PCLASLD (KPROMA, KFLEV, 3)
TYPE(STACK), INTENT (IN) :: YDSTACK
ENDSUBROUTINE LASCAW_CLATURB_OPENACC


END INTERFACE
