INTERFACE
SUBROUTINE GPMPFC_EXPL_PART1 (YDML_GCONF, YDDYN, YDDYNA, KPROMA,    &
& KFLEV, KST, KEND, PGM, P0U, P0V, P0DIV, P0TL, P0TM, P9U, P9V, P0UL, P0VL, P0VOR, P0SPDL, P0SPDM, &
& P0SVDL, P0SVDM, P0NHXL, P0NHXM, P9DIV, P9TL, P9TM, P9SPDL, P9SPDM, P9SVDL, P9SVDM, P0SPL, P0SPM, &
& P9SPL, P9SPM)
USE PARKIND1, ONLY : JPIM, JPRB
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDYN                 , ONLY : TDYN
USE YOMDYNA                , ONLY : TDYNA
IMPLICIT NONE
TYPE(MODEL_GENERAL_CONF_TYPE) ,INTENT(IN)     :: YDML_GCONF
TYPE(TDYN)                    ,INTENT(IN)     :: YDDYN
TYPE(TDYNA)                   ,INTENT(IN)     :: YDDYNA
INTEGER(KIND=JPIM)            ,INTENT(IN)     :: KPROMA
INTEGER(KIND=JPIM)            ,INTENT(IN)     :: KFLEV
INTEGER(KIND=JPIM)            ,INTENT(IN)     :: KST
INTEGER(KIND=JPIM)            ,INTENT(IN)     :: KEND
REAL(KIND=JPRB)               ,INTENT(IN)     :: PGM(KPROMA)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0U(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0V(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0DIV(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0TL(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0TM(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9U(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9V(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0UL(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0VL(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0VOR(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0SPDL(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0SPDM(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0SVDL(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0SVDM(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0NHXL(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0NHXM(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9DIV(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9TL(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9TM(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9SPDL(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9SPDM(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9SVDL(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9SVDM(KPROMA,KFLEV)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0SPL(KPROMA)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P0SPM(KPROMA)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9SPL(KPROMA)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: P9SPM(KPROMA)
END SUBROUTINE GPMPFC_EXPL_PART1







END INTERFACE
