INTERFACE
SUBROUTINE LAPINEA(&
& YDMODEL,YDGEOMETRY,YDCPG_OPTS,YDCPG_BNDS,YDSL,YDCPG_SL1,YDCPG_SL2,YDA_PWRL9,&
& YDMASK_SL2, &
& YDA_KVSEPC,YDA_KVSEPL,&
& YDA_RSAVEDP,YDA_PCCO,YDA_PUF,YDA_PVF,YDA_KL0,YDA_KLH0,YDA_PLSCAW,YDA_PRSCAW,YDA_KL0H,YDA_PLSCAWH,YDA_PRSCAWH,&
& YDA_PSCO,YDVARS,YDA_KNOWENO)
USE TYPE_MODEL             , ONLY : MODEL
USE GEOMETRY_MOD           , ONLY : GEOMETRY
USE EINT_MOD               , ONLY : SL_STRUCT
USE FIELD_VARIABLES_MOD    , ONLY : FIELD_VARIABLES
USE CPG_SL1_TYPE_MOD       , ONLY : CPG_SL1F_TYPE
USE CPG_SL2_TYPE_MOD       , ONLY : CPG_SL2_TYPE
USE CPG_SL_MASK_TYPE_MOD   , ONLY : CPG_SL_MASK_TYPE
USE FIELD_ARRAY_MODULE
USE CPG_OPTS_TYPE_MOD      , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE
IMPLICIT NONE
TYPE(MODEL)                   ,INTENT(IN)     :: YDMODEL
TYPE(GEOMETRY)                ,INTENT(IN)     :: YDGEOMETRY
TYPE(CPG_OPTS_TYPE)           ,INTENT(IN)     :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE)           ,INTENT(IN)     :: YDCPG_BNDS
TYPE(SL_STRUCT)               ,INTENT(IN)     :: YDSL
TYPE(CPG_SL1F_TYPE)           ,INTENT(IN)     :: YDCPG_SL1
TYPE(CPG_SL2_TYPE)            ,INTENT(IN)     :: YDCPG_SL2
TYPE(FIELD_3RB_ARRAY)         ,INTENT(IN)     :: YDA_PWRL9
TYPE(CPG_SL_MASK_TYPE)        ,INTENT(INOUT)  :: YDMASK_SL2
TYPE(FIELD_2IM_ARRAY)         ,INTENT(INOUT)  :: YDA_KVSEPC
TYPE(FIELD_2IM_ARRAY)         ,INTENT(INOUT)  :: YDA_KVSEPL
TYPE(FIELD_4RB_ARRAY)         ,INTENT(INOUT)  :: YDA_RSAVEDP
TYPE(FIELD_4RB_ARRAY)         ,INTENT(IN)     :: YDA_PCCO
TYPE(FIELD_3RB_ARRAY)         ,INTENT(IN)     :: YDA_PUF
TYPE(FIELD_3RB_ARRAY)         ,INTENT(IN)     :: YDA_PVF
TYPE(FIELD_4IM_ARRAY)         ,INTENT(IN)     :: YDA_KL0
TYPE(FIELD_4IM_ARRAY)         ,INTENT(IN)     :: YDA_KLH0
TYPE(FIELD_4RB_ARRAY)         ,INTENT(IN)     :: YDA_PLSCAW
TYPE(FIELD_4RB_ARRAY)         ,INTENT(IN)     :: YDA_PRSCAW
TYPE(FIELD_4IM_ARRAY)         ,INTENT(IN)     :: YDA_KL0H
TYPE(FIELD_4RB_ARRAY)         ,INTENT(IN)     :: YDA_PLSCAWH
TYPE(FIELD_4RB_ARRAY)         ,INTENT(IN)     :: YDA_PRSCAWH
TYPE(FIELD_4RB_ARRAY)         ,INTENT(IN)     :: YDA_PSCO
TYPE(FIELD_VARIABLES)         ,INTENT(INOUT)  :: YDVARS
TYPE(FIELD_3IM_ARRAY)         ,INTENT(IN)     :: YDA_KNOWENO
END SUBROUTINE LAPINEA







END INTERFACE
