INTERFACE

SUBROUTINE RECMWF (YDDIMV, YDMODEL, YDCPG_OPTS, YDCPG_BNDS,     &
& KOZOCL  ,KMACCAERO ,  KAERO     ,                            &
& PALBD   , PALBP    ,  PAPRS     , PAPRSF     ,               &
& PNEB    , PQO3     ,  PQCO2     , PQCH4      , PQN2O   ,     &
& PQNO2   , PQC11    ,  PQC12     , PQC22      , PQCL4   ,     &
& PAER    , PAERO    ,  PAEROCPL  , PDELP      , PEMIS   ,     &
& PMU0M   , PQ       ,  PQSAT     , PQICE      , PQLIQ   ,     &
& PS      , PRR      ,  PLSM      , PT         , PTS     ,     &
& PEMTD   , PEMTU    ,  PTRSO     , PLWFC      , PLWFT   ,     &
& PSWFC   , PSWFT    ,  PSFSWDIR  , PSFSWDIF   , PFSDNN  ,     &
& PFSDNV  , PCTRSO   ,  PCEMTR    , PTRSOD     , PTRSODIR,     &
& PTRSODIF, PPIZA_DST,  PCGA_DST  , PTAUREL_DST,               &
& PAERINDS, PGELAM   ,  PGEMU     , PSWDIR     , PSWDIF  ,     &
& PMU0LU  , PALB     ,  PVRMOON   , PCLDROP    , YSPP_RSWINHF, &
& YSPP_RLWINHF)
USE TYPE_MODEL       , ONLY : MODEL
USE YOMDIMV          , ONLY : TDIMV
USE PARKIND1         , ONLY : JPIM, JPRB
USE SPP_MOD_TYPE     , ONLY : APPLY_SPP, TSPP_CONFIG_TYPE
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
IMPLICIT NONE
TYPE(TDIMV)            ,INTENT(IN)               :: YDDIMV
TYPE(MODEL)            ,INTENT(IN)               :: YDMODEL
TYPE(CPG_OPTS_TYPE)    ,INTENT(IN)               :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE)    ,INTENT(IN)               :: YDCPG_BNDS
INTEGER(KIND=JPIM)     ,INTENT(IN)               :: KOZOCL
INTEGER(KIND=JPIM)     ,INTENT(IN)               :: KMACCAERO
INTEGER(KIND=JPIM)     ,INTENT(IN)               :: KAERO
REAL(KIND=JPRB)        ,INTENT(IN)               :: PGELAM(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PGEMU(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PALBD(YDCPG_OPTS%KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PALBP(YDCPG_OPTS%KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PAPRS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PAPRSF(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PNEB(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQO3(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQCO2(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQCH4(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQN2O(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQNO2(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQC11(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQC12(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQC22(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQCL4(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PAER(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,6)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PAERO(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,KAERO)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PAEROCPL(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDMODEL%YRML_PHY_RAD%YRERAD%NTLW,MERGE (6,0,YDMODEL%YRML_PHY_RAD%YREAERATM%LAERRADCPL))
REAL(KIND=JPRB)        ,INTENT(IN)               :: PAERINDS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PDELP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PEMIS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PMU0M(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQ(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQSAT(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQICE(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PQLIQ(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PLSM(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PT(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PTS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PPIZA_DST(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PCGA_DST(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PTAUREL_DST(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PEMTD(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PEMTU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PTRSO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PCTRSO(YDCPG_OPTS%KLON,0:1)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PCEMTR(YDCPG_OPTS%KLON,0:1)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PTRSOD(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PLWFC(YDCPG_OPTS%KLON,0:1)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PLWFT(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG,1:YDCPG_OPTS%KTSSG+1)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PSWFC(YDCPG_OPTS%KLON,0:1)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PSWFT(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG,1:YDCPG_OPTS%KTSSG+1)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PSFSWDIR(YDCPG_OPTS%KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PSFSWDIF(YDCPG_OPTS%KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PFSDNN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PFSDNV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PTRSODIR(YDCPG_OPTS%KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)        ,INTENT(OUT)              :: PTRSODIF(YDCPG_OPTS%KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PRR(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)        ,INTENT(INOUT)            :: PSWDIR(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)        ,INTENT(INOUT)            :: PSWDIF(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)        ,INTENT(IN)               :: PMU0LU(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(INOUT)            :: PALB(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(INOUT)            :: PVRMOON(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)        ,INTENT(IN)    ,OPTIONAL  :: PCLDROP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
TYPE(TSPP_CONFIG_TYPE) ,INTENT(INOUT) ,OPTIONAL  :: YSPP_RSWINHF,YSPP_RLWINHF
END SUBROUTINE RECMWF







END INTERFACE
