INTERFACE
SUBROUTINE LASURE(&
 & YDGEOMETRY,YDEPHY,YDDYN,YDEDYN,YDPHY,KST,KEND,PMAPPA,PGM,PBT,&
 & PBDT,PREDIV) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHY , ONLY : TEPHY
USE YOMPHY , ONLY : TPHY
USE YEMDYN , ONLY : TEDYN
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(TEDYN) ,INTENT(IN) :: YDEDYN
TYPE(TPHY) ,INTENT(IN) :: YDPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: PMAPPA(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PBT
REAL(KIND=JPRB) ,INTENT(OUT) :: PBDT(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PREDIV(YDGEOMETRY%YRDIM%NPROMA)
END SUBROUTINE LASURE
END INTERFACE
