INTERFACE
SUBROUTINE VERINTS_OPENACC (KPROMA, KST, KEND, KLEVIN, KLEVOUT, PINTE, PIN, POUTS, YDSTACK)
!$ACC ROUTINE (VERINTS_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KLEVOUT
INTEGER (KIND=JPIM), INTENT (IN)::KLEVIN
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
REAL (KIND=JPRD), INTENT (IN)::PINTE (KLEVOUT, KLEVIN)
REAL (KIND=JPRB), INTENT (IN), TARGET::PIN (KPROMA, KLEVIN)
REAL (KIND=JPRD), INTENT (OUT)::POUTS (KPROMA)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
END SUBROUTINE VERINTS_OPENACC


END INTERFACE
