SUBROUTINE VERINT_OPENACC (KPROMA, KST, KEND, KLEVIN, KLEVOUT&
&, PINTE, PIN, POUT, KTYPE, KCHUNK, POUTS, PINS, YDSTACK)
!$ACC ROUTINE (VERINT_OPENACC) SEQ
USE PARKIND1,ONLY:JPRD, JPIM, JPRB

USE YOMLUN,ONLY:NULERR
USE OML_MOD,ONLY:OML_IN_PARALLEL
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


INTEGER (KIND=JPIM), INTENT (IN)::KCHUNK
INTEGER (KIND=JPIM), INTENT (IN)::KTYPE
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KLEVOUT
INTEGER (KIND=JPIM), INTENT (IN)::KLEVIN
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
REAL (KIND=JPRD), INTENT (IN)::PINTE (KLEVOUT, KLEVIN)
REAL (KIND=JPRB), INTENT (IN), TARGET::PIN (KPROMA, KLEVIN)
REAL (KIND=JPRB), INTENT (OUT), TARGET::POUT (KPROMA, KLEVOUT-1)
REAL (KIND=JPRD), INTENT (IN), OPTIONAL, TARGET::POUTS (KPROMA)
REAL (KIND=JPRB), INTENT (IN), OPTIONAL::PINS (KPROMA)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER (KIND=JPIM)::JLEVIN
INTEGER (KIND=JPIM)::JLEVOUT
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLEN
LOGICAL, PARAMETER::LLDOUBLE=JPRB==JPRD
LOGICAL, SAVE::LLSIMPLE_DGEMM=.FALSE.
LOGICAL, PARAMETER::LLVERINT_ON_CPU=.TRUE.
CHARACTER (LEN=8), SAVE::CLENV=''
fxtran_acdc_temp (REAL (KIND=JPRD), ZIN, (KPROMA, KLEVIN))
fxtran_acdc_temp (REAL (KIND=JPRD), ZOUT, (KPROMA, KLEVOUT-1))
fxtran_acdc_temp (REAL (KIND=JPRD), ZIN0, (KPROMA, MERGE (KLEVIN, 0,.NOT.LLDOUBLE)))
fxtran_acdc_temp (REAL (KIND=JPRD), ZOUT0, (KPROMA, MERGE (KLEVOUT-1, 0,.NOT.LLDOUBLE)))
LOGICAL::LLOML_IN_PARALLEL




YLSTACK = YDSTACK



IF (KIND (ZIN0) == 8) THEN
    fxtran_acdc_alloc8 (ZIN0)
ELSEIF (KIND (ZIN0) == 4) THEN
    fxtran_acdc_alloc4 (ZIN0)
ELSE
    STOP 1
ENDIF


IF (KIND (ZOUT0) == 8) THEN
    fxtran_acdc_alloc8 (ZOUT0)
ELSEIF (KIND (ZOUT0) == 4) THEN
    fxtran_acdc_alloc4 (ZOUT0)
ELSE
    STOP 1
ENDIF


JROF = KST



LLOML_IN_PARALLEL=.TRUE.


IF (LLDOUBLE) THEN
#ifndef PARKIND1_SINGLE
  fxtran_acdc_assoc (ZOUT, POUT)
  fxtran_acdc_assoc (ZIN, PIN)
#endif
ELSE
  fxtran_acdc_assoc (ZIN, ZIN0)
  fxtran_acdc_assoc (ZOUT, ZOUT0)

  DO JLEV=1, KLEVIN
    
    ZIN (JROF, JLEV)=REAL (PIN (JROF, JLEV), KIND=JPRD)
  
  ENDDO

ENDIF


ZOUT(JROF,:)=0._JPRD

DO JLEVIN=1, KLEVIN

  DO JLEVOUT=1, KLEVOUT-1
    
    ZOUT (JROF, JLEVOUT)=ZOUT (JROF, JLEVOUT)+PINTE (JLEVOUT, JLEVIN)*ZIN (JROF, JLEVIN)
  
  ENDDO

ENDDO



IF (KTYPE==1) THEN

  IF (PRESENT (PINS)) THEN

    DO JLEV=1, KLEVOUT-1

      

      IF (.NOT.LLDOUBLE) THEN
        POUT (JROF, JLEV)=REAL (ZOUT (JROF, JLEV)-POUTS (JROF), JPRB)+PINS (JROF)
      ELSE
        POUT (JROF, JLEV)=ZOUT (JROF, JLEV)-POUTS (JROF)+PINS (JROF)
      ENDIF

    
    ENDDO

  ELSE

    DO JLEV=1, KLEVOUT-1
      
      POUT (JROF, JLEV)=ZOUT (JROF, JLEV)-POUTS (JROF)
    
    ENDDO

  ENDIF

ELSEIF (KTYPE/=0) THEN
  PRINT *, 'INVALIDKTYPEINVERINT=',KTYPE
  CALL FXTRAN_ACDC_ABORT (' VERINT: ABOR1 CALLED')
ELSEIF (PRESENT (PINS)) THEN

  DO JLEV=1, KLEVOUT-1
    
    POUT (JROF, JLEV)=ZOUT (JROF, JLEV)+PINS (JROF)
  
  ENDDO

ELSEIF (.NOT.LLDOUBLE) THEN

  DO JLEV=1, KLEVOUT-1
    
    POUT (JROF, JLEV)=REAL (ZOUT (JROF, JLEV), KIND=JPRB)
  
  ENDDO

ENDIF


END SUBROUTINE VERINT_OPENACC
