
SUBROUTINE RADAER_OPENACC (YDEAERD, YDERAD, YDPHY, KIDIA, KFDIA, KLON, KLEV, PAPRS, PAPRSF&
&, PT, PTS, PAESEA, PAELAN, PAESOO, PAEDES, PAESUL, PAEVOL, PAER, PAERINDS, YDSTACK)
!$ACC ROUTINE (RADAER_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOEAERD,ONLY:TEAERD
USE YOERAD,ONLY:TERAD
USE YOMPHY,ONLY:TPHY
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TEAERD), INTENT (IN)::YDEAERD
TYPE (TERAD), INTENT (IN)::YDERAD
TYPE (TPHY), INTENT (IN)::YDPHY
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PAESEA (KLON)
REAL (KIND=JPRB), INTENT (IN)::PAELAN (KLON)
REAL (KIND=JPRB), INTENT (IN)::PAESOO (KLON)
REAL (KIND=JPRB), INTENT (IN)::PAEDES (KLON)
REAL (KIND=JPRB), INTENT (IN)::PAESUL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PAEVOL (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PAER (KLON, KLEV, 6)
REAL (KIND=JPRB), INTENT (OUT)::PAERINDS (KLON, KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
fxtran_acdc_temp (REAL (KIND=JPRB), ZTH, (KLON, KLEV+1))
REAL (KIND=JPRB)::ZDPO 
REAL (KIND=JPRB)::ZDPN 
REAL (KIND=JPRB)::ZAEQSO 
REAL (KIND=JPRB)::ZAEQSN 
REAL (KIND=JPRB)::ZAEQLO 
REAL (KIND=JPRB)::ZAEQLN 
REAL (KIND=JPRB)::ZAEQUO 
REAL (KIND=JPRB)::ZAEQUN 
REAL (KIND=JPRB)::ZAEQDO 
REAL (KIND=JPRB)::ZAEQDN 
REAL (KIND=JPRB)::ZAETRO 
REAL (KIND=JPRB)::ZAETRN 
REAL (KIND=JPRB)::ZAEQFO 
REAL (KIND=JPRB)::ZAEQFN 
REAL (KIND=JPRB)::ZTOT 
INTEGER (KIND=JPIM)::JAER
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRB)::ZREPAER
REAL (KIND=JPRB)::ZGRTH
REAL (KIND=JPRB)::ZDPNMO
REAL (KIND=JPRB)::ZAETR


YLSTACK = YDSTACK



IF (KIND (ZTH) == 8) THEN
    fxtran_acdc_alloc8 (ZTH)
ELSEIF (KIND (ZTH) == 4) THEN
    fxtran_acdc_alloc4 (ZTH)
ELSE
    STOP 1
ENDIF


JLON = KIDIA



ZREPAER=1.E-12_JPRB

DO JLEV=2, KLEV
  
  ZTH (JLON, JLEV)=(PT (JLON, JLEV-1)*PAPRSF (JLON, JLEV-1)*(PAPRSF (JLON, JLEV)-PAPRS (JLON&
  &, JLEV))+PT (JLON, JLEV)*PAPRSF (JLON, JLEV)*(PAPRS (JLON, JLEV)-PAPRSF (JLON, JLEV-1&
  &)))*(1.0_JPRB/(PAPRS (JLON, JLEV)*(PAPRSF (JLON, JLEV)-PAPRSF (JLON, JLEV-1))))
  
ENDDO


ZTH (JLON, KLEV+1)=PTS (JLON)
ZTH (JLON, 1)=PT (JLON, 1)-PAPRSF (JLON, 1)*(PT (JLON, 1&
&)-ZTH (JLON, 2))/(PAPRSF (JLON, 1)-PAPRS (JLON, 2))


ZDPO =PAPRS (JLON, 1)

IF (YDERAD%LNEWAER) THEN
  ZAEQSO =PAESEA (JLON)*YDEAERD%CVDAES(1)

  IF (YDPHY%LAEROSUL) THEN
    ZAEQLO =(PAELAN (JLON)+PAESUL (JLON))*YDEAERD%CVDAEL(1)
    ZAEQFO =PAESUL (JLON)*YDEAERD%CVDAEL(1)
  ELSE
    ZAEQLO =PAELAN (JLON)*YDEAERD%CVDAEL(1)
    ZAEQFO =0._JPRB
  ENDIF

  ZAEQUO =PAESOO (JLON)*YDEAERD%CVDAEU(1)
  ZAEQDO =PAEDES (JLON)*YDEAERD%CVDAED(1)
ELSE
  ZAEQSO =YDEAERD%RCAEOPS*PAESEA (JLON)*YDEAERD%CVDAES(1)
  ZAEQLO =YDEAERD%RCAEOPL*PAELAN (JLON)*YDEAERD%CVDAEL(1)
  ZAEQUO =YDEAERD%RCAEOPU*PAESOO (JLON)*YDEAERD%CVDAEU(1)
  ZAEQDO =YDEAERD%RCAEOPD*PAEDES (JLON)*YDEAERD%CVDAED(1)
ENDIF

ZAETRO =1.0_JPRB
ZTOT =0.0_JPRB


DO JLEV=1, KLEV
  
  ZGRTH=ZTH (JLON, JLEV)/ZTH (JLON, JLEV+1)
  ZDPN =PAPRS (JLON, JLEV+1)

  IF (YDERAD%LNEWAER) THEN
    ZAEQSN =PAESEA (JLON)*YDEAERD%CVDAES(JLEV+1)

    IF (YDPHY%LAEROSUL) THEN
      ZAEQLN =(PAELAN (JLON)+PAESUL (JLON))*YDEAERD%CVDAEL(JLEV+1)
      ZAEQFN =PAESUL (JLON)*YDEAERD%CVDAEL(JLEV+1)
    ELSE
      ZAEQLN =PAELAN (JLON)*YDEAERD%CVDAEL(JLEV+1)
      ZAEQFN =0._JPRB
    ENDIF

    ZAEQUN =PAESOO (JLON)*YDEAERD%CVDAEU(JLEV+1)
    ZAEQDN =PAEDES (JLON)*YDEAERD%CVDAED(JLEV+1)
  ELSE
    ZAEQSN =YDEAERD%RCAEOPS*PAESEA (JLON)*YDEAERD%CVDAES(JLEV+1)
    ZAEQLN =YDEAERD%RCAEOPL*PAELAN (JLON)*YDEAERD%CVDAEL(JLEV+1)
    ZAEQUN =YDEAERD%RCAEOPU*PAESOO (JLON)*YDEAERD%CVDAEU(JLEV+1)
    ZAEQDN =YDEAERD%RCAEOPD*PAEDES (JLON)*YDEAERD%CVDAED(JLEV+1)
  ENDIF


  IF (0.5_JPRB*(PAPRS (JLON, JLEV)+PAPRS (JLON, JLEV+1))<999._JPRB) THEN
    ZAETRN =1.0_JPRB
    ZAETRO =1.0_JPRB
  ELSE
    ZAETRN =ZAETRO *(MIN (1.0_JPRB, ZGRTH))**YDEAERD%RCTRPT
  ENDIF

  ZAETR=SQRT (ZAETRN *ZAETRO )
  ZDPNMO=ZDPN -ZDPO 
  ZTOT =ZTOT +ZAETR*ZDPNMO

  IF (YDERAD%LNEWAER) THEN
    PAERINDS (JLON, JLEV)=(1.0_JPRB-ZAETR)*(ZAEQFN -ZAEQFO )
  ENDIF

  PAER (JLON, JLEV, 1)=(1.0_JPRB-ZAETR)*(YDEAERD%RCTRBGA*ZDPNMO+ZAEQLN -ZAEQLO )
  PAER (JLON, JLEV, 2)=(1.0_JPRB-ZAETR)*(ZAEQSN -ZAEQSO )
  PAER (JLON, JLEV, 3)=(1.0_JPRB-ZAETR)*(ZAEQDN -ZAEQDO )
  PAER (JLON, JLEV, 4)=(1.0_JPRB-ZAETR)*(ZAEQUN -ZAEQUO )
  PAER (JLON, JLEV, 5)=ZAETR*YDEAERD%RCVOBGA*ZDPNMO

  IF (YDPHY%LAEROVOL) THEN
    PAER (JLON, JLEV, 6)=ZAETR*ZDPNMO*PAEVOL (JLON)
  ELSE
    PAER (JLON, JLEV, 6)=ZAETR*YDEAERD%RCSTBGA*ZDPNMO
  ENDIF

  
  
  ZDPO =ZDPN 
  ZAEQSO =ZAEQSN 
  ZAEQLO =ZAEQLN 
  ZAEQUO =ZAEQUN 
  ZAEQDO =ZAEQDN 
  ZAETRO =ZAETRN 

  

  IF (YDERAD%LNEWAER) THEN
    
    ZAEQFO =ZAEQFN 
  
  ENDIF

ENDDO


IF (YDPHY%LAEROVOL) THEN
  
  PAER (JLON,:, 6)=PAER (JLON,:, 6)/ZTOT 
  
ENDIF


DO JLEV=1, KLEV

  DO JAER=1, 6
    
    PAER (JLON, JLEV, JAER)=MAX (PAER (JLON, JLEV, JAER), ZREPAER)
  
  ENDDO

ENDDO


IF (YDERAD%LNEWAER) THEN

  DO JLEV=1, KLEV
    
    PAERINDS (JLON, JLEV)=MAX (PAERINDS (JLON, JLEV), ZREPAER)
  
  ENDDO

ENDIF



END SUBROUTINE RADAER_OPENACC
