
SUBROUTINE RADHEAT_OPENACC (YDCST, YDTHF, YDERAD, YDERDI, YDML_PHY_MF, KIDIA, KFDIA, KLON&
&, KLEV, PAPHM1, PEMIS, PEMTED, PMU0, PSOLO, PQM1, PTE, PTRSOL, PTRSOD, PTSM1M, PTSPHY, PTRSODIR&
&, PTRSODIF, PALBD, PALBP, PFRSO, PFRTH, PFRSODS, PFRTHDS, PCEMTR, PCTRSO, PFRSOC, PFRTHC&
&, PSUDU, PSDUR, PDSRP, PSFSWDIR, PSFSWDIF, PFRSOPS, PFRSOFS, PFRSOPT, YDSTACK)
!$ACC ROUTINE (RADHEAT_OPENACC) SEQ
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOERDI,ONLY:TERDI
USE YOERAD,ONLY:TERAD
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TERAD), INTENT (IN)::YDERAD
TYPE (TERDI), INTENT (IN)::YDERDI
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::PAPHM1 (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PEMIS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PEMTED (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PMU0 (KLON)
REAL (KIND=JPRB), INTENT (IN)::PSOLO (KLON)
REAL (KIND=JPRB), INTENT (IN)::PQM1 (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTRSOL (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PTRSOD (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTSM1M (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PTRSODIR (KLON, YDERAD%NSW)
REAL (KIND=JPRB), INTENT (IN)::PTRSODIF (KLON, YDERAD%NSW)
REAL (KIND=JPRB), INTENT (IN)::PALBD (KLON, YDERAD%NSW)
REAL (KIND=JPRB), INTENT (IN)::PALBP (KLON, YDERAD%NSW)
REAL (KIND=JPRB), INTENT (OUT)::PFRSO (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PFRTH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PFRSODS (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PFRTHDS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PCEMTR (KLON, 2)
REAL (KIND=JPRB), INTENT (IN)::PCTRSO (KLON, 2)
REAL (KIND=JPRB), INTENT (OUT)::PFRSOC (KLON, 2)
REAL (KIND=JPRB), INTENT (OUT)::PFRTHC (KLON, 2)
REAL (KIND=JPRB), INTENT (IN)::PSUDU (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSDUR (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PDSRP (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSFSWDIR (KLON, YDERAD%NSW)
REAL (KIND=JPRB), INTENT (OUT)::PSFSWDIF (KLON, YDERAD%NSW)
REAL (KIND=JPRB), INTENT (OUT)::PFRSOPS (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PFRSOFS (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PFRSOPT (KLON)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
REAL (KIND=JPRB)::ZTH4 
REAL (KIND=JPRB)::ZI0 
REAL (KIND=JPRB)::ZFTE 
REAL (KIND=JPRB)::ZFSO 
REAL (KIND=JPRB)::ZFLT 
REAL (KIND=JPRB)::ZFLB 
REAL (KIND=JPRB)::ZDTDIV 
REAL (KIND=JPRB)::ZDTDT 
INTEGER (KIND=JPIM)::JSW
INTEGER (KIND=JPIM)::JL
INTEGER (KIND=JPIM)::JK
INTEGER (KIND=JPIM)::ILONS
REAL (KIND=JPRB)::ZTMST
REAL (KIND=JPRB)::ZRII0
REAL (KIND=JPRB)::ZCONS3
REAL (KIND=JPRB)::ZCONS1
REAL (KIND=JPRB)::ZBUD


JL = KIDIA



ZTMST=PTSPHY
ZCONS1=YDERDI%RRAE*(YDERDI%RRAE+2.0_JPRB)
ZCONS3=YDCST%RG/YDCST%RCPD
ILONS=KFDIA-KIDIA+1
ZBUD=1.0_JPRB
ZRII0=YDML_PHY_MF%YRPHY3%RII0

PFRSODS (JL)=0.0_JPRB
PFRSOFS (JL)=0.0_JPRB
PFRSOPS (JL)=0.0_JPRB



IF (PMU0 (JL)>=1.E-10_JPRB) THEN
  ZI0 =PMU0 (JL)*ZRII0*(1._JPRB-PSOLO (JL))
ELSE
  ZI0 =0.0_JPRB
ENDIF



ZFSO =ZI0 *PTRSOL (JL, 1)
ZFTE =PEMTED (JL, 1)
PFRTH (JL, 1)=ZFTE 
PFRSO (JL, 1)=ZFSO 
PFRTHC (JL, 1)=PCEMTR (JL, 1)
PFRSOC (JL, 1)=ZI0 *PCTRSO (JL, 1)


DO JK=1, KLEV
  
  ZFLT =ZFSO +ZFTE 
  ZFSO =ZI0 *PTRSOL (JL, JK+1)

  IF (JK==KLEV.AND.ZFSO <1.E-15_JPRB) THEN
    ZFSO =1.E-15_JPRB
  ENDIF

  ZFTE =PEMTED (JL, JK+1)
  ZFLB =ZFSO +ZFTE 
  ZDTDIV =1.0_JPRB/((PAPHM1 (JL, JK+1)-PAPHM1 (JL, JK))*(1.0_JPRB+YDTHF%RVTMP2*PQM1 (JL, JK)))
  ZDTDT =-ZCONS3*(ZFLB -ZFLT )*ZDTDIV 
  PTE (JL, JK)=PTE (JL, JK)+ZDTDT 
  
  
  PFRTH (JL, JK+1)=ZFTE 
  PFRSO (JL, JK+1)=ZFSO 
  
ENDDO


PFRTHC (JL, 2)=PCEMTR (JL, 2)
PFRSOC (JL, 2)=ZI0 *PCTRSO (JL, 2)


PDSRP (JL)=ZI0 *PSUDU (JL)

IF (PDSRP (JL)>=YDERDI%RSUNDUR) THEN
  PSDUR (JL)=1.0_JPRB
ELSE
  PSDUR (JL)=0.0_JPRB
ENDIF

ZTH4 =YDCST%RSIGMA*PTSM1M (JL)**4
PFRTHDS (JL)=(PEMTED (JL, KLEV+1)+PEMIS (JL)*ZTH4 )/PEMIS (JL)
PFRSOPT (JL)=ZI0 


IF (YDML_PHY_MF%YRARPHY%LMSE.OR.YDML_PHY_MF%YRPHY%LHLRADUPD) THEN

  DO JSW=1, YDERAD%NSW
    
    ZFSO =MAX (ZI0 *PTRSODIR (JL, JSW), 1.E-15_JPRB)
    PSFSWDIR (JL, JSW)=ZFSO /(1.0_JPRB-PALBP (JL, JSW))
    ZFSO =MAX (ZI0 *PTRSODIF (JL, JSW), 1.E-15_JPRB)
    PSFSWDIF (JL, JSW)=ZFSO /(1.0_JPRB-PALBD (JL, JSW))
    PFRSOPS (JL)=PFRSOPS (JL)+PSFSWDIR (JL, JSW)
    PFRSOFS (JL)=PFRSOFS (JL)+PSFSWDIF (JL, JSW)
    PFRSODS (JL)=PFRSODS (JL)+PSFSWDIF (JL, JSW)+PSFSWDIR (JL, JSW)
  
  ENDDO

ELSE
  
  PFRSODS (JL)=ZI0 *PTRSOD (JL)
  
ENDIF



END SUBROUTINE RADHEAT_OPENACC
