SUBROUTINE GPTF2_EXPL_2TL (YDGEOMETRY, KST, KEND, LDFSTEP, P0U, P0V, P9U, P9V)

!**** *GPTF2_EXPL_2TL*

!     Author.
!     -------
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 28-11-2022

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : DR_HOOK, LHOOK, JPHOOK

USE GEOMETRY_MOD , ONLY : GEOMETRY

IMPLICIT NONE

TYPE(GEOMETRY)      ,INTENT(IN)               :: YDGEOMETRY
INTEGER(KIND=JPIM)  ,INTENT(IN)               :: KST
INTEGER(KIND=JPIM)  ,INTENT(IN)               :: KEND
LOGICAL             ,INTENT(IN)               :: LDFSTEP
REAL(KIND=JPRB)     ,INTENT(INOUT) ,OPTIONAL  :: P0U(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)     ,INTENT(INOUT) ,OPTIONAL  :: P0V(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)     ,INTENT(INOUT) ,OPTIONAL  :: P9U(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)     ,INTENT(INOUT) ,OPTIONAL  :: P9V(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)

INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('GPTF2_EXPL_2TL',0,ZHOOK_HANDLE)

IF(LDFSTEP) THEN
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=KST,KEND
      P9U(JROF,JLEV) = P0U(JROF,JLEV)
      P9V(JROF,JLEV) = P0V(JROF,JLEV)
    ENDDO
  ENDDO
ENDIF

IF (LHOOK) CALL DR_HOOK('GPTF2_EXPL_2TL',1,ZHOOK_HANDLE)

END SUBROUTINE GPTF2_EXPL_2TL
