INTERFACE
SUBROUTINE LAPINEB_L_RDRY_VD (YDVARS, YDMODEL, YDGEOMETRY, YDCPG_BNDS, PRT1)
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (INOUT)::PRT1 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
ENDSUBROUTINE
END INTERFACE
