INTERFACE
SUBROUTINE LAPINEB_LRDBBC (YDVARS, YDCPG_SL2, YDGEOMETRY, YDCPG_BNDS&
&, PVST1, POROGL_SR, PDPHI9, PDBBC9, PUST1, POROGM_SR, PGWS9)
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_SL2_TYPE_MOD,ONLY:CPG_SL2_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (CPG_SL2_TYPE), INTENT (IN)::YDCPG_SL2
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (INOUT)::PVST1 (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::POROGL_SR (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::PDPHI9 (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::PDBBC9 (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::PUST1 (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::POROGM_SR (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::PGWS9 (YDGEOMETRY%YRDIM%NPROMA)
ENDSUBROUTINE
END INTERFACE
