SUBROUTINE LARCINB_LLCOMAD (LDCOMAD, YDCPG_SL1, JFLD, YDCPG_GFLF&
&, KASLB1, YDML_DYN, YDGEOMETRY, YDCPG_BNDS, PLSCAW, KL0)
USE PARKIND1,ONLY:JPIM, JPRB
USE CPG_SL1_TYPE_MOD,ONLY:CPG_SL1F_TYPE
USE CPG_GFL_TYPE_MOD,ONLY:CPG_GFL_TYPE, CPG_GFLSL_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE MODEL_DYNAMICS_MOD,ONLY:MODEL_DYNAMICS_TYPE
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

LOGICAL, INTENT (INOUT)::LDCOMAD
TYPE (CPG_SL1F_TYPE), INTENT (IN)::YDCPG_SL1
INTEGER (KIND=JPIM), INTENT (INOUT)::JFLD
TYPE (CPG_GFL_TYPE), INTENT (INOUT)::YDCPG_GFLF
INTEGER (KIND=JPIM), INTENT (IN)::KASLB1
TYPE (MODEL_DYNAMICS_TYPE), INTENT (IN)::YDML_DYN
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (IN)::PLSCAW (YDGEOMETRY%YRDIM%NPROMA&
&, YDGEOMETRY%YRDIMV%NFLEVG, YDML_DYN%YYTLSCAW%NDIM)
INTEGER (KIND=JPIM), INTENT (IN)::KL0 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG, 0:3)
#include "laitlif.intfb.h"
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('LARCINB_LLCOMAD', 0, ZHOOK_HANDLE)
CALL LAITLIF (YDML_DYN%YYTLSCAW, KASLB1, YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY&
&%YRDIMV%NFLEVG, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, KL0, LDCOMAD, PLSCAW&
&, YDCPG_SL1%GFL (JFLD)%P_F, YDCPG_GFLF%GFL (JFLD)%P, LDADD=.TRUE.)
IF (LHOOK) CALL DR_HOOK ('LARCINB_LLCOMAD', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
