SUBROUTINE LASSIE_SITNU (YDVARS, YDCPG_OPTS, YDDYN, YDGEOMETRY&
&, YDCST, YDCPG_BNDS, PTOD0, PGAGT0L, PSDIV0, PGAGT0M)
USE YOMCST,ONLY:TCST
USE PARKIND1,ONLY:JPIM, JPRB
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE YOMDYN,ONLY:TDYN
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (TDYN), INTENT (IN)::YDDYN
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (TCST), INTENT (IN)::YDCST
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
REAL (KIND=JPRB), INTENT (INOUT)::PTOD0 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PGAGT0L (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSDIV0 (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (INOUT)::PGAGT0M (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
#include "sitnu_gp.intfb.h"
#include "sigam_gp.intfb.h"
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('LASSIE_SITNU', 0, ZHOOK_HANDLE)
CALL SITNU_GP (YDCST, YDGEOMETRY, YDDYN, YDCPG_OPTS%KLON, YDGEOMETRY%YRDIMV%NFLEVG&
&, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDVARS%DIV%T0, PTOD0, PSDIV0)
CALL SIGAM_GP (YDCST, YDGEOMETRY, YDDYN, YDCPG_OPTS%KLON, YDGEOMETRY%YRDIMV%NFLEVG&
&, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, PGAGT0L, YDVARS%T%DL, YDVARS%SP%DL)
CALL SIGAM_GP (YDCST, YDGEOMETRY, YDDYN, YDCPG_OPTS%KLON, YDGEOMETRY%YRDIMV%NFLEVG&
&, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, PGAGT0M, YDVARS%T%DM, YDVARS%SP%DM)
IF (LHOOK) CALL DR_HOOK ('LASSIE_SITNU', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
