MODULE UTIL_PARAM_LIMA_COLD_T_MOD

USE MODD_PARAM_LIMA_COLD, ONLY : PARAM_LIMA_COLD_T

INTERFACE SAVE
MODULE PROCEDURE SAVE_PARAM_LIMA_COLD_T
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_PARAM_LIMA_COLD_T
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_PARAM_LIMA_COLD_T
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_PARAM_LIMA_COLD_T
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_PARAM_LIMA_COLD_T
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_PARAM_LIMA_COLD_T
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_PARAM_LIMA_COLD_T
END INTERFACE


CONTAINS

SUBROUTINE SAVE_PARAM_LIMA_COLD_T (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (PARAM_LIMA_COLD_T), INTENT (IN), TARGET :: YD
LOGICAL :: LXKER_N_SSCS
WRITE (KLUN) YD%XLBEXI
WRITE (KLUN) YD%XLBI
WRITE (KLUN) YD%XLBEXS
WRITE (KLUN) YD%XLBS
WRITE (KLUN) YD%XNS
WRITE (KLUN) YD%XAI
WRITE (KLUN) YD%XBI
WRITE (KLUN) YD%XC_I
WRITE (KLUN) YD%XDI
WRITE (KLUN) YD%XF0I
WRITE (KLUN) YD%XF2I
WRITE (KLUN) YD%XC1I
WRITE (KLUN) YD%XF0IS
WRITE (KLUN) YD%XF1IS
WRITE (KLUN) YD%XAS
WRITE (KLUN) YD%XBS
WRITE (KLUN) YD%XCS
WRITE (KLUN) YD%XDS
WRITE (KLUN) YD%XCCS
WRITE (KLUN) YD%XCXS
WRITE (KLUN) YD%XF0S
WRITE (KLUN) YD%XF1S
WRITE (KLUN) YD%XC1S
WRITE (KLUN) YD%XLBDAS_MIN
WRITE (KLUN) YD%XLBDAS_MAX
WRITE (KLUN) YD%XFVELOS
WRITE (KLUN) YD%XTRANS_MP_GAMMAS
WRITE (KLUN) YD%XFSEDRI
WRITE (KLUN) YD%XFSEDCI
WRITE (KLUN) YD%XFSEDRS
WRITE (KLUN) YD%XFSEDCS
WRITE (KLUN) YD%XFSEDS
WRITE (KLUN) YD%XEXSEDS
WRITE (KLUN) YD%XNUC_DEP
WRITE (KLUN) YD%XEXSI_DEP
WRITE (KLUN) YD%XEX_DEP
WRITE (KLUN) YD%XNUC_CON
WRITE (KLUN) YD%XEXTT_CON
WRITE (KLUN) YD%XEX_CON
WRITE (KLUN) YD%XMNU0
WRITE (KLUN) YD%XRHOI_HONH
WRITE (KLUN) YD%XCEXP_DIFVAP_HONH
WRITE (KLUN) YD%XCOEF_DIFVAP_HONH
WRITE (KLUN) YD%XRCOEF_HONH
WRITE (KLUN) YD%XCRITSAT1_HONH
WRITE (KLUN) YD%XCRITSAT2_HONH
WRITE (KLUN) YD%XTMIN_HONH
WRITE (KLUN) YD%XTMAX_HONH
WRITE (KLUN) YD%XDLNJODT1_HONH
WRITE (KLUN) YD%XDLNJODT2_HONH
WRITE (KLUN) YD%XC1_HONH
WRITE (KLUN) YD%XC2_HONH
WRITE (KLUN) YD%XC3_HONH
WRITE (KLUN) YD%XC_HONC
WRITE (KLUN) YD%XR_HONC
WRITE (KLUN) YD%XTEXP1_HONC
WRITE (KLUN) YD%XTEXP2_HONC
WRITE (KLUN) YD%XTEXP3_HONC
WRITE (KLUN) YD%XTEXP4_HONC
WRITE (KLUN) YD%XTEXP5_HONC
WRITE (KLUN) YD%XCSCNVI_MAX
WRITE (KLUN) YD%XLBDASCNVI_MAX
WRITE (KLUN) YD%XRHORSMIN
WRITE (KLUN) YD%XDSCNVI_LIM
WRITE (KLUN) YD%XLBDASCNVI_LIM
WRITE (KLUN) YD%XC0DEPSI
WRITE (KLUN) YD%XC1DEPSI
WRITE (KLUN) YD%XR0DEPSI
WRITE (KLUN) YD%XR1DEPSI
WRITE (KLUN) YD%XSCFAC
WRITE (KLUN) YD%X0DEPI
WRITE (KLUN) YD%X2DEPI
WRITE (KLUN) YD%X0DEPS
WRITE (KLUN) YD%X1DEPS
WRITE (KLUN) YD%XEX0DEPS
WRITE (KLUN) YD%XEX1DEPS
WRITE (KLUN) YD%XDICNVS_LIM
WRITE (KLUN) YD%XLBDAICNVS_LIM
WRITE (KLUN) YD%XC0DEPIS
WRITE (KLUN) YD%XC1DEPIS
WRITE (KLUN) YD%XR0DEPIS
WRITE (KLUN) YD%XR1DEPIS
WRITE (KLUN) YD%XCOLEXIS
WRITE (KLUN) YD%XAGGS_CLARGE1
WRITE (KLUN) YD%XAGGS_CLARGE2
WRITE (KLUN) YD%XAGGS_RLARGE1
WRITE (KLUN) YD%XAGGS_RLARGE2
WRITE (KLUN) YD%XFIAGGS
WRITE (KLUN) YD%XEXIAGGS
WRITE (KLUN) YD%XACCS1
WRITE (KLUN) YD%XSPONBUDS1
WRITE (KLUN) YD%XSPONBUDS2
WRITE (KLUN) YD%XSPONBUDS3
WRITE (KLUN) YD%XSPONCOEFS2
WRITE (KLUN) YD%XKER_ZRNIC_A1
WRITE (KLUN) YD%XKER_ZRNIC_A2
WRITE (KLUN) YD%XSELFI
WRITE (KLUN) YD%XCOLEXII
LXKER_N_SSCS = ALLOCATED (YD%XKER_N_SSCS)
WRITE (KLUN) LXKER_N_SSCS
IF (LXKER_N_SSCS) THEN
  WRITE (KLUN) LBOUND (YD%XKER_N_SSCS)
  WRITE (KLUN) UBOUND (YD%XKER_N_SSCS)
  WRITE (KLUN) YD%XKER_N_SSCS
ENDIF
WRITE (KLUN) YD%XCOLSS
WRITE (KLUN) YD%XCOLEXSS
WRITE (KLUN) YD%XFNSSCS
WRITE (KLUN) YD%XLBNSSCS1
WRITE (KLUN) YD%XLBNSSCS2
WRITE (KLUN) YD%XSCINTP1S
WRITE (KLUN) YD%XSCINTP2S
WRITE (KLUN) YD%NSCLBDAS
WRITE (KLUN) YD%XAUTO3
WRITE (KLUN) YD%XAUTO4
WRITE (KLUN) YD%XLAUTS
WRITE (KLUN) YD%XLAUTS_THRESHOLD
WRITE (KLUN) YD%XITAUTS
WRITE (KLUN) YD%XITAUTS_THRESHOLD
WRITE (KLUN) YD%XTEXAUTI
WRITE (KLUN) YD%XCONCI_MAX
WRITE (KLUN) YD%XFREFFI
WRITE (KLUN) YD%XALPHA1
WRITE (KLUN) YD%XALPHA2
WRITE (KLUN) YD%XBETA1
WRITE (KLUN) YD%XBETA2
WRITE (KLUN) YD%XNU10
WRITE (KLUN) YD%XNU20
END SUBROUTINE

SUBROUTINE LOAD_PARAM_LIMA_COLD_T (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (PARAM_LIMA_COLD_T), INTENT (OUT), TARGET :: YD
INTEGER :: IL2(2), IU2(2)
LOGICAL :: LXKER_N_SSCS
READ (KLUN) YD%XLBEXI
READ (KLUN) YD%XLBI
READ (KLUN) YD%XLBEXS
READ (KLUN) YD%XLBS
READ (KLUN) YD%XNS
READ (KLUN) YD%XAI
READ (KLUN) YD%XBI
READ (KLUN) YD%XC_I
READ (KLUN) YD%XDI
READ (KLUN) YD%XF0I
READ (KLUN) YD%XF2I
READ (KLUN) YD%XC1I
READ (KLUN) YD%XF0IS
READ (KLUN) YD%XF1IS
READ (KLUN) YD%XAS
READ (KLUN) YD%XBS
READ (KLUN) YD%XCS
READ (KLUN) YD%XDS
READ (KLUN) YD%XCCS
READ (KLUN) YD%XCXS
READ (KLUN) YD%XF0S
READ (KLUN) YD%XF1S
READ (KLUN) YD%XC1S
READ (KLUN) YD%XLBDAS_MIN
READ (KLUN) YD%XLBDAS_MAX
READ (KLUN) YD%XFVELOS
READ (KLUN) YD%XTRANS_MP_GAMMAS
READ (KLUN) YD%XFSEDRI
READ (KLUN) YD%XFSEDCI
READ (KLUN) YD%XFSEDRS
READ (KLUN) YD%XFSEDCS
READ (KLUN) YD%XFSEDS
READ (KLUN) YD%XEXSEDS
READ (KLUN) YD%XNUC_DEP
READ (KLUN) YD%XEXSI_DEP
READ (KLUN) YD%XEX_DEP
READ (KLUN) YD%XNUC_CON
READ (KLUN) YD%XEXTT_CON
READ (KLUN) YD%XEX_CON
READ (KLUN) YD%XMNU0
READ (KLUN) YD%XRHOI_HONH
READ (KLUN) YD%XCEXP_DIFVAP_HONH
READ (KLUN) YD%XCOEF_DIFVAP_HONH
READ (KLUN) YD%XRCOEF_HONH
READ (KLUN) YD%XCRITSAT1_HONH
READ (KLUN) YD%XCRITSAT2_HONH
READ (KLUN) YD%XTMIN_HONH
READ (KLUN) YD%XTMAX_HONH
READ (KLUN) YD%XDLNJODT1_HONH
READ (KLUN) YD%XDLNJODT2_HONH
READ (KLUN) YD%XC1_HONH
READ (KLUN) YD%XC2_HONH
READ (KLUN) YD%XC3_HONH
READ (KLUN) YD%XC_HONC
READ (KLUN) YD%XR_HONC
READ (KLUN) YD%XTEXP1_HONC
READ (KLUN) YD%XTEXP2_HONC
READ (KLUN) YD%XTEXP3_HONC
READ (KLUN) YD%XTEXP4_HONC
READ (KLUN) YD%XTEXP5_HONC
READ (KLUN) YD%XCSCNVI_MAX
READ (KLUN) YD%XLBDASCNVI_MAX
READ (KLUN) YD%XRHORSMIN
READ (KLUN) YD%XDSCNVI_LIM
READ (KLUN) YD%XLBDASCNVI_LIM
READ (KLUN) YD%XC0DEPSI
READ (KLUN) YD%XC1DEPSI
READ (KLUN) YD%XR0DEPSI
READ (KLUN) YD%XR1DEPSI
READ (KLUN) YD%XSCFAC
READ (KLUN) YD%X0DEPI
READ (KLUN) YD%X2DEPI
READ (KLUN) YD%X0DEPS
READ (KLUN) YD%X1DEPS
READ (KLUN) YD%XEX0DEPS
READ (KLUN) YD%XEX1DEPS
READ (KLUN) YD%XDICNVS_LIM
READ (KLUN) YD%XLBDAICNVS_LIM
READ (KLUN) YD%XC0DEPIS
READ (KLUN) YD%XC1DEPIS
READ (KLUN) YD%XR0DEPIS
READ (KLUN) YD%XR1DEPIS
READ (KLUN) YD%XCOLEXIS
READ (KLUN) YD%XAGGS_CLARGE1
READ (KLUN) YD%XAGGS_CLARGE2
READ (KLUN) YD%XAGGS_RLARGE1
READ (KLUN) YD%XAGGS_RLARGE2
READ (KLUN) YD%XFIAGGS
READ (KLUN) YD%XEXIAGGS
READ (KLUN) YD%XACCS1
READ (KLUN) YD%XSPONBUDS1
READ (KLUN) YD%XSPONBUDS2
READ (KLUN) YD%XSPONBUDS3
READ (KLUN) YD%XSPONCOEFS2
READ (KLUN) YD%XKER_ZRNIC_A1
READ (KLUN) YD%XKER_ZRNIC_A2
READ (KLUN) YD%XSELFI
READ (KLUN) YD%XCOLEXII
READ (KLUN) LXKER_N_SSCS
IF (LXKER_N_SSCS) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (YD%XKER_N_SSCS (IL2(1):IU2(1), IL2(2):IU2(2)))
  READ (KLUN) YD%XKER_N_SSCS
ENDIF
READ (KLUN) YD%XCOLSS
READ (KLUN) YD%XCOLEXSS
READ (KLUN) YD%XFNSSCS
READ (KLUN) YD%XLBNSSCS1
READ (KLUN) YD%XLBNSSCS2
READ (KLUN) YD%XSCINTP1S
READ (KLUN) YD%XSCINTP2S
READ (KLUN) YD%NSCLBDAS
READ (KLUN) YD%XAUTO3
READ (KLUN) YD%XAUTO4
READ (KLUN) YD%XLAUTS
READ (KLUN) YD%XLAUTS_THRESHOLD
READ (KLUN) YD%XITAUTS
READ (KLUN) YD%XITAUTS_THRESHOLD
READ (KLUN) YD%XTEXAUTI
READ (KLUN) YD%XCONCI_MAX
READ (KLUN) YD%XFREFFI
READ (KLUN) YD%XALPHA1
READ (KLUN) YD%XALPHA2
READ (KLUN) YD%XBETA1
READ (KLUN) YD%XBETA2
READ (KLUN) YD%XNU10
READ (KLUN) YD%XNU20
END SUBROUTINE


SUBROUTINE COPY_PARAM_LIMA_COLD_T (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (PARAM_LIMA_COLD_T), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LXKER_N_SSCS

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF


































































































LXKER_N_SSCS = ALLOCATED (YD%XKER_N_SSCS)
IF (LXKER_N_SSCS) THEN
  !$ACC ENTER DATA CREATE (YD%XKER_N_SSCS)
  !$ACC UPDATE DEVICE (YD%XKER_N_SSCS)
  !$ACC ENTER DATA ATTACH (YD%XKER_N_SSCS)
ENDIF
























END SUBROUTINE

SUBROUTINE HOST_PARAM_LIMA_COLD_T (YD)

IMPLICIT NONE
TYPE (PARAM_LIMA_COLD_T), TARGET :: YD
LOGICAL :: LXKER_N_SSCS


























































































































END SUBROUTINE

     

SUBROUTINE CRC64_PARAM_LIMA_COLD_T (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (PARAM_LIMA_COLD_T), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LXKER_N_SSCS
WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBEXI), CDPATH//'%XLBEXI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBI), CDPATH//'%XLBI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBEXS), CDPATH//'%XLBEXS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBS), CDPATH//'%XLBS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XNS), CDPATH//'%XNS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XAI), CDPATH//'%XAI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XBI), CDPATH//'%XBI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC_I), CDPATH//'%XC_I'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XDI), CDPATH//'%XDI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XF0I), CDPATH//'%XF0I'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XF2I), CDPATH//'%XF2I'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC1I), CDPATH//'%XC1I'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XF0IS), CDPATH//'%XF0IS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XF1IS), CDPATH//'%XF1IS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XAS), CDPATH//'%XAS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XBS), CDPATH//'%XBS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCS), CDPATH//'%XCS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XDS), CDPATH//'%XDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCCS), CDPATH//'%XCCS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCXS), CDPATH//'%XCXS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XF0S), CDPATH//'%XF0S'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XF1S), CDPATH//'%XF1S'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC1S), CDPATH//'%XC1S'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBDAS_MIN), CDPATH//'%XLBDAS_MIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBDAS_MAX), CDPATH//'%XLBDAS_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFVELOS), CDPATH//'%XFVELOS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XTRANS_MP_GAMMAS), CDPATH//'%XTRANS_MP_GAMMAS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFSEDRI), CDPATH//'%XFSEDRI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFSEDCI), CDPATH//'%XFSEDCI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFSEDRS), CDPATH//'%XFSEDRS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFSEDCS), CDPATH//'%XFSEDCS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFSEDS), CDPATH//'%XFSEDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XEXSEDS), CDPATH//'%XEXSEDS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XNUC_DEP), CDPATH//'%XNUC_DEP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XEXSI_DEP), CDPATH//'%XEXSI_DEP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XEX_DEP), CDPATH//'%XEX_DEP'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XNUC_CON), CDPATH//'%XNUC_CON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XEXTT_CON), CDPATH//'%XEXTT_CON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XEX_CON), CDPATH//'%XEX_CON'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XMNU0), CDPATH//'%XMNU0'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XRHOI_HONH), CDPATH//'%XRHOI_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCEXP_DIFVAP_HONH), CDPATH//'%XCEXP_DIFVAP_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCOEF_DIFVAP_HONH), CDPATH//'%XCOEF_DIFVAP_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XRCOEF_HONH), CDPATH//'%XRCOEF_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCRITSAT1_HONH), CDPATH//'%XCRITSAT1_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCRITSAT2_HONH), CDPATH//'%XCRITSAT2_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XTMIN_HONH), CDPATH//'%XTMIN_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XTMAX_HONH), CDPATH//'%XTMAX_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XDLNJODT1_HONH), CDPATH//'%XDLNJODT1_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XDLNJODT2_HONH), CDPATH//'%XDLNJODT2_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC1_HONH), CDPATH//'%XC1_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC2_HONH), CDPATH//'%XC2_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC3_HONH), CDPATH//'%XC3_HONH'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC_HONC), CDPATH//'%XC_HONC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XR_HONC), CDPATH//'%XR_HONC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XTEXP1_HONC), CDPATH//'%XTEXP1_HONC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XTEXP2_HONC), CDPATH//'%XTEXP2_HONC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XTEXP3_HONC), CDPATH//'%XTEXP3_HONC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XTEXP4_HONC), CDPATH//'%XTEXP4_HONC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XTEXP5_HONC), CDPATH//'%XTEXP5_HONC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCSCNVI_MAX), CDPATH//'%XCSCNVI_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBDASCNVI_MAX), CDPATH//'%XLBDASCNVI_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XRHORSMIN), CDPATH//'%XRHORSMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XDSCNVI_LIM), CDPATH//'%XDSCNVI_LIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBDASCNVI_LIM), CDPATH//'%XLBDASCNVI_LIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC0DEPSI), CDPATH//'%XC0DEPSI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC1DEPSI), CDPATH//'%XC1DEPSI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XR0DEPSI), CDPATH//'%XR0DEPSI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XR1DEPSI), CDPATH//'%XR1DEPSI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XSCFAC), CDPATH//'%XSCFAC'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%X0DEPI), CDPATH//'%X0DEPI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%X2DEPI), CDPATH//'%X2DEPI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%X0DEPS), CDPATH//'%X0DEPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%X1DEPS), CDPATH//'%X1DEPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XEX0DEPS), CDPATH//'%XEX0DEPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XEX1DEPS), CDPATH//'%XEX1DEPS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XDICNVS_LIM), CDPATH//'%XDICNVS_LIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBDAICNVS_LIM), CDPATH//'%XLBDAICNVS_LIM'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC0DEPIS), CDPATH//'%XC0DEPIS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XC1DEPIS), CDPATH//'%XC1DEPIS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XR0DEPIS), CDPATH//'%XR0DEPIS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XR1DEPIS), CDPATH//'%XR1DEPIS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCOLEXIS), CDPATH//'%XCOLEXIS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XAGGS_CLARGE1), CDPATH//'%XAGGS_CLARGE1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XAGGS_CLARGE2), CDPATH//'%XAGGS_CLARGE2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XAGGS_RLARGE1), CDPATH//'%XAGGS_RLARGE1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XAGGS_RLARGE2), CDPATH//'%XAGGS_RLARGE2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFIAGGS), CDPATH//'%XFIAGGS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XEXIAGGS), CDPATH//'%XEXIAGGS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XACCS1), CDPATH//'%XACCS1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XSPONBUDS1), CDPATH//'%XSPONBUDS1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XSPONBUDS2), CDPATH//'%XSPONBUDS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XSPONBUDS3), CDPATH//'%XSPONBUDS3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XSPONCOEFS2), CDPATH//'%XSPONCOEFS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XKER_ZRNIC_A1), CDPATH//'%XKER_ZRNIC_A1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XKER_ZRNIC_A2), CDPATH//'%XKER_ZRNIC_A2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XSELFI), CDPATH//'%XSELFI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCOLEXII), CDPATH//'%XCOLEXII'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XKER_N_SSCS), CDPATH//'%XKER_N_SSCS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCOLSS), CDPATH//'%XCOLSS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCOLEXSS), CDPATH//'%XCOLEXSS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFNSSCS), CDPATH//'%XFNSSCS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBNSSCS1), CDPATH//'%XLBNSSCS1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLBNSSCS2), CDPATH//'%XLBNSSCS2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XSCINTP1S), CDPATH//'%XSCINTP1S'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XSCINTP2S), CDPATH//'%XSCINTP2S'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NSCLBDAS), CDPATH//'%NSCLBDAS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XAUTO3), CDPATH//'%XAUTO3'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XAUTO4), CDPATH//'%XAUTO4'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLAUTS), CDPATH//'%XLAUTS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XLAUTS_THRESHOLD), CDPATH//'%XLAUTS_THRESHOLD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XITAUTS), CDPATH//'%XITAUTS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XITAUTS_THRESHOLD), CDPATH//'%XITAUTS_THRESHOLD'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XTEXAUTI), CDPATH//'%XTEXAUTI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XCONCI_MAX), CDPATH//'%XCONCI_MAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFREFFI), CDPATH//'%XFREFFI'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XALPHA1), CDPATH//'%XALPHA1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XALPHA2), CDPATH//'%XALPHA2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XBETA1), CDPATH//'%XBETA1'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XBETA2), CDPATH//'%XBETA2'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XNU10), CDPATH//'%XNU10'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XNU20), CDPATH//'%XNU20'

END SUBROUTINE

SUBROUTINE WIPE_PARAM_LIMA_COLD_T (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (PARAM_LIMA_COLD_T), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LXKER_N_SSCS

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF


































































































LXKER_N_SSCS = ALLOCATED (YD%XKER_N_SSCS)
IF (LXKER_N_SSCS) THEN
  !$ACC EXIT DATA DETACH (YD%XKER_N_SSCS)
  !$ACC EXIT DATA DETACH (YD%XKER_N_SSCS)
ENDIF
























LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_PARAM_LIMA_COLD_T (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (PARAM_LIMA_COLD_T),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LXKER_N_SSCS

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%XLBEXI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBEXI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBEXS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBEXS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XNS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XNS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XAI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC_I)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC_I'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XDI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XF0I)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XF0I'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XF2I)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XF2I'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC1I)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC1I'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XF0IS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XF0IS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XF1IS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XF1IS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XAS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCCS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCCS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCXS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCXS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XF0S)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XF0S'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XF1S)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XF1S'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC1S)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC1S'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBDAS_MIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBDAS_MIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBDAS_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBDAS_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFVELOS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFVELOS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTRANS_MP_GAMMAS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTRANS_MP_GAMMAS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFSEDRI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFSEDRI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFSEDCI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFSEDCI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFSEDRS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFSEDRS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFSEDCS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFSEDCS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFSEDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFSEDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XEXSEDS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEXSEDS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XNUC_DEP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XNUC_DEP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XEXSI_DEP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEXSI_DEP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XEX_DEP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEX_DEP'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XNUC_CON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XNUC_CON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XEXTT_CON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEXTT_CON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XEX_CON)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEX_CON'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XMNU0)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XMNU0'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XRHOI_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRHOI_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCEXP_DIFVAP_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCEXP_DIFVAP_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCOEF_DIFVAP_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCOEF_DIFVAP_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XRCOEF_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRCOEF_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCRITSAT1_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCRITSAT1_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCRITSAT2_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCRITSAT2_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTMIN_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTMIN_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTMAX_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTMAX_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDLNJODT1_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XDLNJODT1_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDLNJODT2_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XDLNJODT2_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC1_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC1_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC2_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC2_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC3_HONH)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC3_HONH'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC_HONC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC_HONC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XR_HONC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XR_HONC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTEXP1_HONC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTEXP1_HONC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTEXP2_HONC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTEXP2_HONC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTEXP3_HONC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTEXP3_HONC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTEXP4_HONC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTEXP4_HONC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTEXP5_HONC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTEXP5_HONC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCSCNVI_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCSCNVI_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBDASCNVI_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBDASCNVI_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XRHORSMIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XRHORSMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDSCNVI_LIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XDSCNVI_LIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBDASCNVI_LIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBDASCNVI_LIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC0DEPSI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC0DEPSI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC1DEPSI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC1DEPSI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XR0DEPSI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XR0DEPSI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XR1DEPSI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XR1DEPSI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSCFAC)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSCFAC'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%X0DEPI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%X0DEPI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%X2DEPI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%X2DEPI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%X0DEPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%X0DEPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%X1DEPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%X1DEPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XEX0DEPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEX0DEPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XEX1DEPS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEX1DEPS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XDICNVS_LIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XDICNVS_LIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBDAICNVS_LIM)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBDAICNVS_LIM'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC0DEPIS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC0DEPIS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XC1DEPIS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XC1DEPIS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XR0DEPIS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XR0DEPIS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XR1DEPIS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XR1DEPIS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCOLEXIS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCOLEXIS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XAGGS_CLARGE1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAGGS_CLARGE1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XAGGS_CLARGE2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAGGS_CLARGE2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XAGGS_RLARGE1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAGGS_RLARGE1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XAGGS_RLARGE2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAGGS_RLARGE2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFIAGGS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFIAGGS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XEXIAGGS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XEXIAGGS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XACCS1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XACCS1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSPONBUDS1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSPONBUDS1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSPONBUDS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSPONBUDS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSPONBUDS3)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSPONBUDS3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSPONCOEFS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSPONCOEFS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XKER_ZRNIC_A1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XKER_ZRNIC_A1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XKER_ZRNIC_A2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XKER_ZRNIC_A2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSELFI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSELFI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCOLEXII)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCOLEXII'
ENDIF
KSIZE = KSIZE + ISIZE
LXKER_N_SSCS = ALLOCATED (YD%XKER_N_SSCS)
IF (LXKER_N_SSCS) THEN
  ISIZE = KIND (YD%XKER_N_SSCS) * SIZE (YD%XKER_N_SSCS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%XKER_N_SSCS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
ISIZE = KIND (YD%XCOLSS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCOLSS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCOLEXSS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCOLEXSS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFNSSCS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFNSSCS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBNSSCS1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBNSSCS1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLBNSSCS2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLBNSSCS2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSCINTP1S)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSCINTP1S'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XSCINTP2S)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XSCINTP2S'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NSCLBDAS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NSCLBDAS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XAUTO3)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAUTO3'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XAUTO4)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XAUTO4'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLAUTS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLAUTS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XLAUTS_THRESHOLD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XLAUTS_THRESHOLD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XITAUTS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XITAUTS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XITAUTS_THRESHOLD)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XITAUTS_THRESHOLD'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XTEXAUTI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XTEXAUTI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XCONCI_MAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XCONCI_MAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFREFFI)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFREFFI'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XALPHA1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XALPHA1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XALPHA2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XALPHA2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBETA1)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBETA1'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XBETA2)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XBETA2'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XNU10)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XNU10'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XNU20)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XNU20'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
