MODULE UTIL_TFIELDMETADATA_MOD

USE MODD_FIELD, ONLY : TFIELDMETADATA

INTERFACE SAVE
MODULE PROCEDURE SAVE_TFIELDMETADATA
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TFIELDMETADATA
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TFIELDMETADATA
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TFIELDMETADATA
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TFIELDMETADATA
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TFIELDMETADATA
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TFIELDMETADATA
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TFIELDMETADATA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TFIELDMETADATA), INTENT (IN), TARGET :: YD

WRITE (KLUN) YD%CMNHNAME
WRITE (KLUN) YD%CSTDNAME
WRITE (KLUN) YD%CLONGNAME
WRITE (KLUN) YD%CUNITS
WRITE (KLUN) YD%CCOMMENT
WRITE (KLUN) YD%NGRID
WRITE (KLUN) YD%NTYPE
WRITE (KLUN) YD%NDIMS
WRITE (KLUN) YD%NDIMLIST
WRITE (KLUN) YD%NFILLVALUE
WRITE (KLUN) YD%XFILLVALUE
WRITE (KLUN) YD%NVALIDMIN
WRITE (KLUN) YD%NVALIDMAX
WRITE (KLUN) YD%XVALIDMIN
WRITE (KLUN) YD%XVALIDMAX
WRITE (KLUN) YD%CDIR
WRITE (KLUN) YD%CLBTYPE
WRITE (KLUN) YD%LTIMEDEP
END SUBROUTINE

SUBROUTINE LOAD_TFIELDMETADATA (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TFIELDMETADATA), INTENT (OUT), TARGET :: YD

READ (KLUN) YD%CMNHNAME
READ (KLUN) YD%CSTDNAME
READ (KLUN) YD%CLONGNAME
READ (KLUN) YD%CUNITS
READ (KLUN) YD%CCOMMENT
READ (KLUN) YD%NGRID
READ (KLUN) YD%NTYPE
READ (KLUN) YD%NDIMS
READ (KLUN) YD%NDIMLIST
READ (KLUN) YD%NFILLVALUE
READ (KLUN) YD%XFILLVALUE
READ (KLUN) YD%NVALIDMIN
READ (KLUN) YD%NVALIDMAX
READ (KLUN) YD%XVALIDMIN
READ (KLUN) YD%XVALIDMAX
READ (KLUN) YD%CDIR
READ (KLUN) YD%CLBTYPE
READ (KLUN) YD%LTIMEDEP
END SUBROUTINE


SUBROUTINE COPY_TFIELDMETADATA (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TFIELDMETADATA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (YD)
  !$ACC UPDATE DEVICE (YD)
ENDIF


















END SUBROUTINE

SUBROUTINE HOST_TFIELDMETADATA (YD)

IMPLICIT NONE
TYPE (TFIELDMETADATA), TARGET :: YD



















END SUBROUTINE

     

SUBROUTINE CRC64_TFIELDMETADATA (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
TYPE (TFIELDMETADATA), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CMNHNAME), CDPATH//'%CMNHNAME'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CSTDNAME), CDPATH//'%CSTDNAME'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CLONGNAME), CDPATH//'%CLONGNAME'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CUNITS), CDPATH//'%CUNITS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CCOMMENT), CDPATH//'%CCOMMENT'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NGRID), CDPATH//'%NGRID'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NTYPE), CDPATH//'%NTYPE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDIMS), CDPATH//'%NDIMS'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NDIMLIST), CDPATH//'%NDIMLIST'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NFILLVALUE), CDPATH//'%NFILLVALUE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XFILLVALUE), CDPATH//'%XFILLVALUE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NVALIDMIN), CDPATH//'%NVALIDMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%NVALIDMAX), CDPATH//'%NVALIDMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XVALIDMIN), CDPATH//'%XVALIDMIN'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%XVALIDMAX), CDPATH//'%XVALIDMAX'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CDIR), CDPATH//'%CDIR'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%CLBTYPE), CDPATH//'%CLBTYPE'

WRITE (KLUN, '(Z16.16," ",A)') FCRC64 (YD%LTIMEDEP), CDPATH//'%LTIMEDEP'

END SUBROUTINE

SUBROUTINE WIPE_TFIELDMETADATA (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TFIELDMETADATA), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF


















LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TFIELDMETADATA (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TFIELDMETADATA),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%CMNHNAME) * LEN (YD%CMNHNAME)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CMNHNAME'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CSTDNAME) * LEN (YD%CSTDNAME)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CSTDNAME'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CLONGNAME) * LEN (YD%CLONGNAME)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CLONGNAME'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CUNITS) * LEN (YD%CUNITS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CUNITS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CCOMMENT) * LEN (YD%CCOMMENT)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CCOMMENT'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NGRID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NGRID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NTYPE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NTYPE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDIMS)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDIMS'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NDIMLIST) * SIZE (YD%NDIMLIST)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NDIMLIST'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NFILLVALUE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NFILLVALUE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XFILLVALUE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XFILLVALUE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NVALIDMIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NVALIDMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NVALIDMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NVALIDMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XVALIDMIN)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XVALIDMIN'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%XVALIDMAX)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%XVALIDMAX'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CDIR) * LEN (YD%CDIR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CDIR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%CLBTYPE) * LEN (YD%CLBTYPE)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%CLBTYPE'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%LTIMEDEP)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LTIMEDEP'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END MODULE
