SUBROUTINE CPXFU_OUTLINE_002 (YDCPG_BNDS, YDCPG_MISC, YDCPG_OPTS, YDMF_PHYS_OUT, YDXFU, LDGST, LDGST2&
&, PXNUCLS, PXNVCLS, PXUCLS, PXUGST, PXVCLS, PXVGST, PNUMEAN, PNVMEAN, PUMEAN, PVMEAN)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_OUT_TYPE
USE YOMXFU,ONLY:TXFU
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_MISC_TYPE), INTENT (IN)::YDCPG_MISC
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_OUT_TYPE), INTENT (IN)::YDMF_PHYS_OUT
TYPE (TXFU), INTENT (INOUT)::YDXFU
LOGICAL, INTENT (INOUT)::LDGST (YDCPG_OPTS%KLON)
LOGICAL, INTENT (INOUT)::LDGST2 (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PXNUCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PXNVCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PXUCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PXUGST (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PXVCLS (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (IN)::PXVGST (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PNUMEAN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PNVMEAN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PUMEAN (YDCPG_OPTS%KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PVMEAN (YDCPG_OPTS%KLON)
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('CPXFU_OUTLINE_002', 0, ZHOOK_HANDLE)

IF (YDXFU%YNEBT%LACTIVE) THEN
  YDXFU%NEBT (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDCPG_MISC%CLCT (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YFEVL%LACTIVE) THEN
  YDXFU%FEVL (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%FEVL (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, 1)
ENDIF


IF (YDXFU%YFONTE%LACTIVE) THEN
  YDXFU%FONTE (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%FONTE (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YFCHSP%LACTIVE) THEN
  YDXFU%FCHSP (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%FCHSP (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, 1)
ENDIF


IF (YDXFU%YFLWSP%LACTIVE) THEN
  YDXFU%FLWSP (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%FLWSP (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YRUISS%LACTIVE) THEN
  YDXFU%RUISS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%RUISS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YRUISP%LACTIVE) THEN
  YDXFU%RUISP (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%RUISP (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YFEVV%LACTIVE) THEN
  YDXFU%FEVV (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%FEVV (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YFTR%LACTIVE) THEN
  YDXFU%FTR (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%FTR (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YRUISL%LACTIVE) THEN
  YDXFU%RUISL (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%RUISL (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YNBCON%LACTIVE) THEN
  YDXFU%NBCON (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%CLCC (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YNBHAU%LACTIVE) THEN
  YDXFU%NBHAU (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%CLCH (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YNBMOY%LACTIVE) THEN
  YDXFU%NBMOY (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%CLCM (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YNBBAS%LACTIVE) THEN
  YDXFU%NBBAS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%CLCL (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YCAPE%LACTIVE) THEN
  YDXFU%CAPE (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%CAPE (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YCTOP%LACTIVE) THEN
  YDXFU%CTOP (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%CTOP (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YMOCON%LACTIVE) THEN
  YDXFU%MOCON (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%MOCON (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YCLPH%LACTIVE) THEN
  YDXFU%CLPH (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%CLPH (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YCLPHMF%LACTIVE) THEN
  YDXFU%CLPHMF (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%CLPHMF (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YVMAXTH%LACTIVE) THEN
  YDXFU%VMAXTH (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%VMAXTH (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YVEIN%LACTIVE) THEN
  YDXFU%VEIN (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%VEIN (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YMRT%LACTIVE) THEN
  YDXFU%MRT (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%MRT (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YTCLS%LACTIVE) THEN
  YDXFU%TCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%TCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YSIC%LACTIVE) THEN
  YDXFU%SIC (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT%SIC (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YSNWDE%LACTIVE) THEN
  YDXFU%SNWDE (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%SNWDE (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YQCLS%LACTIVE) THEN
  YDXFU%QCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDMF_PHYS_OUT&
  &%QCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
ENDIF


IF (YDXFU%YUGST%LACTIVE) THEN

  IF (YDXFU%LXXGST) THEN

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA

      IF (LDGST (JLON)) THEN
        YDXFU%UGST (JLON)=PXUGST (JLON)
      ENDIF

    ENDDO

  ELSE
    YDXFU%UGST (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PXUGST (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ENDIF

ENDIF


IF (YDXFU%YVGST%LACTIVE) THEN

  IF (YDXFU%LXXGST) THEN

    DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA

      IF (LDGST (JLON)) THEN
        YDXFU%VGST (JLON)=PXVGST (JLON)
      ENDIF

    ENDDO

  ELSE
    YDXFU%VGST (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PXVGST (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ENDIF

ENDIF


IF (YDXFU%YUGST2%LACTIVE.AND.YDXFU%LXXGST2) THEN

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA

    IF (LDGST2 (JLON)) THEN
      YDXFU%UGST2 (JLON)=PXUGST (JLON)
    ENDIF

  ENDDO

ENDIF


IF (YDXFU%YVGST2%LACTIVE.AND.YDXFU%LXXGST2) THEN

  DO JLON=YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA

    IF (LDGST2 (JLON)) THEN
      YDXFU%VGST2 (JLON)=PXVGST (JLON)
    ENDIF

  ENDDO

ENDIF


IF (YDXFU%YUCLS%LACTIVE) THEN

  IF (YDXFU%LXMWINDCLS) THEN
    YDXFU%UCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PUMEAN (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ELSE
    YDXFU%UCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PXUCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ENDIF

ENDIF


IF (YDXFU%YVCLS%LACTIVE) THEN

  IF (YDXFU%LXMWINDCLS) THEN
    YDXFU%VCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PVMEAN (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ELSE
    YDXFU%VCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PXVCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ENDIF

ENDIF


IF (YDXFU%YNUCLS%LACTIVE) THEN

  IF (YDXFU%LXMWINDCLS) THEN
    YDXFU%NUCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PNUMEAN (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ELSE
    YDXFU%NUCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PXNUCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ENDIF

ENDIF


IF (YDXFU%YNVCLS%LACTIVE) THEN

  IF (YDXFU%LXMWINDCLS) THEN
    YDXFU%NVCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PNVMEAN (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ELSE
    YDXFU%NVCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=PXNVCLS (YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)
  ENDIF

ENDIF

IF (LHOOK) CALL DR_HOOK ('CPXFU_OUTLINE_002', 1, ZHOOK_HANDLE)
ENDSUBROUTINE
