MODULE CPLNG_TYPES_MOD

!$ACDC methods 


   USE PARKIND1, ONLY: JPIM
   USE PARKIND_OCEAN, ONLY : JPRO

   IMPLICIT NONE

   PRIVATE

   PUBLIC CPLNG_FLD_TYPE

   TYPE CPLNG_FLD_TYPE
      INTEGER(KIND=JPIM),ALLOCATABLE :: ID(:,:)
      CHARACTER(LEN=128)             :: NAME
      INTEGER(KIND=JPIM)             :: TYPE
      INTEGER(KIND=JPIM)             :: INOUT
      INTEGER(KIND=JPIM)             :: STAGE
      INTEGER(KIND=JPIM)             :: NUM_LVL
      INTEGER(KIND=JPIM)             :: NUM_CAT
      REAL(KIND=JPRO),   ALLOCATABLE :: D(:,:,:)
   CONTAINS
PROCEDURE :: COPY => COPY_CPLNG_FLD_TYPE
PROCEDURE :: CRC64 => CRC64_CPLNG_FLD_TYPE
PROCEDURE :: HOST => HOST_CPLNG_FLD_TYPE
PROCEDURE :: LOAD => LOAD_CPLNG_FLD_TYPE
PROCEDURE :: SAVE => SAVE_CPLNG_FLD_TYPE
PROCEDURE :: SIZE => SIZE_CPLNG_FLD_TYPE
PROCEDURE :: WIPE => WIPE_CPLNG_FLD_TYPE
END TYPE CPLNG_FLD_TYPE

INTERFACE

MODULE SUBROUTINE COPY_CPLNG_FLD_TYPE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE CRC64_CPLNG_FLD_TYPE (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE HOST_CPLNG_FLD_TYPE (SELF)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE LOAD_CPLNG_FLD_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE SAVE_CPLNG_FLD_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION SIZE_CPLNG_FLD_TYPE (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE WIPE_CPLNG_FLD_TYPE (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (CPLNG_FLD_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE CPLNG_TYPES_MOD
