SUBMODULE (MODEL_ATMOS_OCEAN_COUPLING_MOD) MODEL_ATMOS_OCEAN_COUPLING_MOD_MODEL_ATMOS_OCEAN_COUPLING_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE HOST_MODEL_ATMOS_OCEAN_COUPLING_TYPE (SELF)

IMPLICIT NONE
CLASS (MODEL_ATMOS_OCEAN_COUPLING_TYPE), TARGET :: SELF

CALL SELF%YRMCC%HOST ()

CALL SELF%YRCOM%HOST ()

CALL SELF%YRCOU%HOST ()

END SUBROUTINE

END SUBMODULE
