SUBMODULE (MODEL_DIAGNOSTICS_MOD) MODEL_DIAGNOSTICS_MOD_MODEL_DIAGNOSTICS_TYPE_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE LOAD_MODEL_DIAGNOSTICS_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (MODEL_DIAGNOSTICS_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SELF%YRCDDH%LOAD (KLUN)
CALL SELF%YRLDDH%LOAD (KLUN)
CALL SELF%YRMDDH%LOAD (KLUN)
CALL SELF%YRSDDH%LOAD (KLUN)
CALL SELF%YRTDDH%LOAD (KLUN)
CALL SELF%YRGPDDH%LOAD (KLUN)
CALL SELF%YRPADDH%LOAD (KLUN)
CALL SELF%YRSPDDH%LOAD (KLUN)
END SUBROUTINE


END SUBMODULE
