MODULE TYPE_SPGEOM

!$ACDC methods 


! Module for spectral geometry structures.

USE PARKIND1 , ONLY : JPIM, JPRB

!     ------------------------------------------------------------------

IMPLICIT NONE
PRIVATE

SAVE

! GMR     : coefficients for spectral multiplication by GM.
! SCGMAP  : coefficients for multiplication by (GM**2) in spectral space (global model).
! ESCGMAP : coefficients for multiplication by (GM**2) in spectral space (LAM model).

TYPE, PUBLIC :: TSPGEOM
REAL(KIND=JPRB),ALLOCATABLE :: GMR(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: SCGMAP(:,:)
REAL(KIND=JPRB) :: ESCGMAP(3)
CONTAINS
FINAL :: TSPGEOM_FINAL
PROCEDURE :: COPY => COPY_TSPGEOM
PROCEDURE :: CRC64 => CRC64_TSPGEOM
PROCEDURE :: HOST => HOST_TSPGEOM
PROCEDURE :: LOAD => LOAD_TSPGEOM
PROCEDURE :: SAVE => SAVE_TSPGEOM
PROCEDURE :: SIZE => SIZE_TSPGEOM
PROCEDURE :: WIPE => WIPE_TSPGEOM
END TYPE TSPGEOM

!!TYPE(TSPGEOM), POINTER,PUBLIC :: YSPGEOM => NULL()

INTERFACE

MODULE SUBROUTINE COPY_TSPGEOM (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TSPGEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE CRC64_TSPGEOM (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (TSPGEOM), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE HOST_TSPGEOM (SELF)

IMPLICIT NONE
CLASS (TSPGEOM), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE LOAD_TSPGEOM (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
CLASS (TSPGEOM), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE SAVE_TSPGEOM (SELF, KLUN)

IMPLICIT NONE
CLASS (TSPGEOM), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION SIZE_TSPGEOM (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TSPGEOM),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE WIPE_TSPGEOM (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TSPGEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

CONTAINS

SUBROUTINE TSPGEOM_FINAL(THIS)
  TYPE(TSPGEOM) :: THIS
  ! If we don't add this, we may get a internal compiler error
END SUBROUTINE TSPGEOM_FINAL

END MODULE TYPE_SPGEOM
