SUBMODULE (TYPE_MODEL) TYPE_MODEL_MODEL_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION SIZE_MODEL (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (MODEL),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LYRCST

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (SELF%LINEAR_MODEL)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%LINEAR_MODEL'
ENDIF
KSIZE = KSIZE + ISIZE
JSIZE = 0
ISIZE = SELF%YRML_GCONF%SIZE (CLPATH//'%YRML_GCONF', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_GCONF'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_AOC%SIZE (CLPATH//'%YRML_AOC', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_AOC'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_DYN%SIZE (CLPATH//'%YRML_DYN', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_DYN'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_PHY_G%SIZE (CLPATH//'%YRML_PHY_G', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_PHY_G'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_PHY_EC%SIZE (CLPATH//'%YRML_PHY_EC', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_PHY_EC'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_PHY_SLIN%SIZE (CLPATH//'%YRML_PHY_SLIN', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_PHY_SLIN'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_PHY_AER%SIZE (CLPATH//'%YRML_PHY_AER', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_PHY_AER'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_PHY_RAD%SIZE (CLPATH//'%YRML_PHY_RAD', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_PHY_RAD'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_PHY_STOCH%SIZE (CLPATH//'%YRML_PHY_STOCH', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_PHY_STOCH'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_PHY_MF%SIZE (CLPATH//'%YRML_PHY_MF', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_PHY_MF'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_CHEM%SIZE (CLPATH//'%YRML_CHEM', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_CHEM'
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_DIAG%SIZE (CLPATH//'%YRML_DIAG', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_DIAG'
ENDIF
JSIZE = 0
ISIZE = SELF%YREWCOU%SIZE (CLPATH//'%YREWCOU', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YREWCOU'
ENDIF
LYRCST = ASSOCIATED (SELF%YRCST)
IF (LYRCST) THEN
  JSIZE = 0
  ISIZE = SELF%YRCST%SIZE (CLPATH//'%YRCST', .FALSE.)
  JSIZE = JSIZE + ISIZE
  KSIZE = KSIZE + ISIZE
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
    WRITE (*, *) TRIM (CLPATH)//'%YRCST'
  ENDIF
ENDIF
JSIZE = 0
ISIZE = SELF%YRML_LBC%SIZE (CLPATH//'%YRML_LBC', .FALSE.)
JSIZE = JSIZE + ISIZE
KSIZE = KSIZE + ISIZE
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') JSIZE
  WRITE (*, *) TRIM (CLPATH)//'%YRML_LBC'
ENDIF
ISIZE = KIND (SELF%MOBJECT_ID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%MOBJECT_ID'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (SELF%COBJECT_ID) * LEN (SELF%COBJECT_ID)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%COBJECT_ID'
ENDIF
KSIZE = KSIZE + ISIZE
END FUNCTION

END SUBMODULE
