MODULE YOEDBUG

!$ACDC methods 


USE PARKIND1  ,ONLY : JPIM

IMPLICIT NONE

SAVE

!     -------------------------------------------------
!*    ** *YOEDBUG* - CONTROL OPTIONS FOR DEBUGGING HELP
!     -------------------------------------------------

TYPE :: TEDBUG
INTEGER(KIND=JPIM) :: KSTPDBG(10), NSTPDBG
CONTAINS
PROCEDURE :: COPY => COPY_TEDBUG
PROCEDURE :: CRC64 => CRC64_TEDBUG
PROCEDURE :: HOST => HOST_TEDBUG
PROCEDURE :: LOAD => LOAD_TEDBUG
PROCEDURE :: SAVE => SAVE_TEDBUG
PROCEDURE :: SIZE => SIZE_TEDBUG
PROCEDURE :: WIPE => WIPE_TEDBUG
END TYPE TEDBUG

!!TYPE(TEDBUG), POINTER :: YREDBUG => NULL()

!     ------------------------------------------------------------------
INTERFACE

MODULE SUBROUTINE COPY_TEDBUG (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEDBUG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE CRC64_TEDBUG (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (TEDBUG), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE HOST_TEDBUG (SELF)

IMPLICIT NONE
CLASS (TEDBUG), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE LOAD_TEDBUG (SELF, KLUN)

IMPLICIT NONE
CLASS (TEDBUG), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE SAVE_TEDBUG (SELF, KLUN)

IMPLICIT NONE
CLASS (TEDBUG), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION SIZE_TEDBUG (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TEDBUG),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE WIPE_TEDBUG (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TEDBUG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YOEDBUG

