MODULE YOERIP

!$ACDC methods 


USE PARKIND1  ,ONLY : JPRB

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------

!*    Real time related variables for ECMWF radiation: updated UPDTIER and UPDTIM

!     RCODECM: COSINE OF THE DECLINATION
!     RSIDECM:   SINE OF THE DECLINATION

!     RCOVSRM: COSINE OF TRUE SOLAR TIME
!     RSIVSRM:   SINE OF TRUE SOLAR TIME

!     RSOVRM:  Solar time in seconds at centre of radiation timestep
!              (GMT + equation of time)
!     RWSOVRM: As RSOVRM but in radians

TYPE :: TERIP
REAL(KIND=JPRB) :: RCODECM
REAL(KIND=JPRB) :: RSIDECM
REAL(KIND=JPRB) :: RCOVSRM
REAL(KIND=JPRB) :: RSIVSRM
REAL(KIND=JPRB) :: RSOVRM
REAL(KIND=JPRB) :: RWSOVRM


CONTAINS
PROCEDURE :: COPY => COPY_TERIP
PROCEDURE :: CRC64 => CRC64_TERIP
PROCEDURE :: HOST => HOST_TERIP
PROCEDURE :: LOAD => LOAD_TERIP
PROCEDURE :: SAVE => SAVE_TERIP
PROCEDURE :: SIZE => SIZE_TERIP
PROCEDURE :: WIPE => WIPE_TERIP
END TYPE TERIP

!!TYPE(TERIP), POINTER :: YRERIP => NULL()

!     ------------------------------------------------------------------
INTERFACE

MODULE SUBROUTINE COPY_TERIP (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TERIP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE CRC64_TERIP (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (TERIP), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE HOST_TERIP (SELF)

IMPLICIT NONE
CLASS (TERIP), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE LOAD_TERIP (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
CLASS (TERIP), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE SAVE_TERIP (SELF, KLUN)

IMPLICIT NONE
CLASS (TERIP), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION SIZE_TERIP (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TERIP),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE WIPE_TERIP (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TERIP), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YOERIP
