SUBMODULE (YOMDGRADIENT) YOMDGRADIENT_TGRADIENT_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE LOAD_TGRADIENT (SELF, KLUN)

IMPLICIT NONE
CLASS (TGRADIENT), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SELF%YPTR%LOAD (KLUN)
END SUBROUTINE


END SUBMODULE
