MODULE YOMLOUIS

!$ACDC methods 


USE PARKIND1  ,ONLY : JPRB

IMPLICIT NONE

SAVE

TYPE TLOUIS
!*
!  ---------------------------------------------------------------------
!  This comdeck contains the fit of R in QNSE scheme
!  ---------------------------------------------------------------------

!R at neutrality
REAL(KIND=JPRB) :: RLOUIS_S0=0.136_JPRB
REAL(KIND=JPRB) :: PLOUIS_S0=0.130_JPRB

!fit of R(Ri) for QNSE
!unstable stratification
REAL(KIND=JPRB) :: RLOUIS_GU1=-2.67_JPRB
REAL(KIND=JPRB) :: RLOUIS_GU2=-6.15_JPRB
REAL(KIND=JPRB) :: PLOUIS_GU1=-1.13_JPRB
REAL(KIND=JPRB) :: PLOUIS_GU2=-3.80_JPRB

!stable stratification
REAL(KIND=JPRB) :: RLOUIS_GS1=1.0_JPRB
REAL(KIND=JPRB) :: RLOUIS_GS2=2.08_JPRB
REAL(KIND=JPRB) :: RLOUIS_GS3=1.0_JPRB
REAL(KIND=JPRB) :: RLOUIS_GS4=2.7_JPRB
REAL(KIND=JPRB) :: PLOUIS_GS1=1.0_JPRB
REAL(KIND=JPRB) :: PLOUIS_GS2=1.93_JPRB
REAL(KIND=JPRB) :: PLOUIS_GS3=1.1_JPRB
REAL(KIND=JPRB) :: PLOUIS_GS4=3.55_JPRB

CONTAINS
PROCEDURE :: COPY => COPY_TLOUIS
PROCEDURE :: CRC64 => CRC64_TLOUIS
PROCEDURE :: HOST => HOST_TLOUIS
PROCEDURE :: LOAD => LOAD_TLOUIS
PROCEDURE :: SAVE => SAVE_TLOUIS
PROCEDURE :: SIZE => SIZE_TLOUIS
PROCEDURE :: WIPE => WIPE_TLOUIS
END TYPE TLOUIS

TYPE(TLOUIS), POINTER :: YRLOUIS => NULL()

INTERFACE

MODULE SUBROUTINE COPY_TLOUIS (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TLOUIS), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE CRC64_TLOUIS (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (TLOUIS), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE HOST_TLOUIS (SELF)

IMPLICIT NONE
CLASS (TLOUIS), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE LOAD_TLOUIS (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
CLASS (TLOUIS), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE SAVE_TLOUIS (SELF, KLUN)

IMPLICIT NONE
CLASS (TLOUIS), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION SIZE_TLOUIS (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TLOUIS),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE WIPE_TLOUIS (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TLOUIS), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YOMLOUIS
