MODULE YOMPADDH

!$ACDC methods 


USE PARKIND1  ,ONLY : JPIM

IMPLICIT NONE

SAVE

TYPE :: TPADDH
INTEGER(KIND=JPIM),ALLOCATABLE:: NGLALIST(:,:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NGPUMASK(:,:)
CONTAINS
PROCEDURE :: COPY => COPY_TPADDH
PROCEDURE :: CRC64 => CRC64_TPADDH
PROCEDURE :: HOST => HOST_TPADDH
PROCEDURE :: LOAD => LOAD_TPADDH
PROCEDURE :: SAVE => SAVE_TPADDH
PROCEDURE :: SIZE => SIZE_TPADDH
PROCEDURE :: WIPE => WIPE_TPADDH
END TYPE TPADDH

!!TYPE(TPADDH), POINTER :: YRPADDH => NULL()

INTERFACE

MODULE SUBROUTINE COPY_TPADDH (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TPADDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE CRC64_TPADDH (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (TPADDH), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE HOST_TPADDH (SELF)

IMPLICIT NONE
CLASS (TPADDH), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE LOAD_TPADDH (SELF, KLUN)

IMPLICIT NONE
CLASS (TPADDH), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE SAVE_TPADDH (SELF, KLUN)

IMPLICIT NONE
CLASS (TPADDH), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION SIZE_TPADDH (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TPADDH),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE WIPE_TPADDH (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TPADDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YOMPADDH
