SUBMODULE (YOMPHY) YOMPHY_TPHY_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE COPY_TPHY (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TPHY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

CALL SELF%YRDPRECIPS%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRDVISI%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRDWET%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YRCAPE%COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

END SUBMODULE
