MODULE YOMSPDDH

!$ACDC methods 


USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------

!*    Spectral arrays used in Horizontal Diffusion (HD):
!     and Semi-Implicit (SI) DDH tendencies.

! -   ARRAYS

TYPE :: TSPDDH
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDHD_VOR(:,:) ! for vorticity
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDHD_DIV(:,:) ! for divergence
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDHD_T(:,:)   ! for temperature
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDHD_SPD(:,:) ! for NH pressure departure
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDHD_SVD(:,:) ! for NH vertical divergence
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDHD_SNHX(:,:)! for NH "X" part of divergence
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDHD_GFL(:,:,:) ! for specific humidity

REAL(KIND=JPRB),ALLOCATABLE:: SPTNDSI_VOR(:,:) ! for vorticity
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDSI_DIV(:,:) ! for divergence
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDSI_T(:,:)   ! for temperature
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDSI_SPD(:,:) ! for NH pressure departure
REAL(KIND=JPRB),ALLOCATABLE:: SPTNDSI_SVD(:,:) ! for NH vertical divergence
CONTAINS
PROCEDURE :: COPY => COPY_TSPDDH
PROCEDURE :: CRC64 => CRC64_TSPDDH
PROCEDURE :: HOST => HOST_TSPDDH
PROCEDURE :: LOAD => LOAD_TSPDDH
PROCEDURE :: SAVE => SAVE_TSPDDH
PROCEDURE :: SIZE => SIZE_TSPDDH
PROCEDURE :: WIPE => WIPE_TSPDDH
END TYPE TSPDDH

!!TYPE(TSPDDH), POINTER :: YRSPDDH => NULL()

!     ------------------------------------------------------------------
INTERFACE

MODULE SUBROUTINE COPY_TSPDDH (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TSPDDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE CRC64_TSPDDH (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (TSPDDH), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE HOST_TSPDDH (SELF)

IMPLICIT NONE
CLASS (TSPDDH), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE LOAD_TSPDDH (SELF, KLUN)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
CLASS (TSPDDH), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE SAVE_TSPDDH (SELF, KLUN)

IMPLICIT NONE
CLASS (TSPDDH), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION SIZE_TSPDDH (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TSPDDH),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE WIPE_TSPDDH (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TSPDDH), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE YOMSPDDH
