SUBROUTINE SISKAPI_SINGLEBLOCK (YDCST, YDGEOMETRY, YDDYN&
&, YDDYNA, KLON, KLEV, KIDIA, KFDIA, PIN, POUT, LDACC)
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE YOMCST,ONLY:TCST
USE YOMDYN,ONLY:TDYN
USE YOMDYNA,ONLY:TDYNA
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE FXTRAN_ACDC_STACK_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (TDYN), INTENT (IN)::YDDYN
TYPE (TDYNA), INTENT (IN)::YDDYNA
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (IN)::PIN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::POUT (KLON, KLEV)
LOGICAL, INTENT (IN) :: LDACC
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRB)::ZSUM (KLON)
REAL (KIND=JPRB)::ZFAC
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK

!$ACC DATA &
!$ACC&CREATE (ZSUM) &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (PIN, POUT, YDCST, YDDYN, YDDYNA, YDGEOMETRY) 

IF (LHOOK) CALL DR_HOOK ('SISKAPI_SINGLEBLOCK', 0, ZHOOK_HANDLE)
ZFAC=0.0_JPRB

IF (YDDYNA%LNHQE.AND.YDDYN%LNHQE_SOLVER_SP)  THEN
  ZFAC=YDCST%RKAPPA-1.0_JPRB
ENDIF


!$ACC PARALLEL LOOP GANG VECTOR &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JLEV, JLON) 


DO JLON = KIDIA, KFDIA
  
  ZSUM (JLON)=0.0_JPRB

  DO JLEV=1, KLEV
    POUT (JLON, JLEV)=(PIN (JLON, JLEV)-ZFAC*(YDDYN%SILNPR_NH (JLEV)*YDDYN%SIRDEL_NH&
    & (JLEV))*ZSUM (JLON))/(1.0_JPRB+ZFAC*YDDYN%SIALPH_NH (JLEV))
    ZSUM (JLON)=ZSUM (JLON)+YDDYN%SIDELP_NH (JLEV)*POUT (JLON, JLEV)
  ENDDO

  
ENDDO

IF (LHOOK) CALL DR_HOOK ('SISKAPI_SINGLEBLOCK', 1, ZHOOK_HANDLE)
!$ACC END DATA

ENDSUBROUTINE SISKAPI_SINGLEBLOCK
