MODULE MODI_CONVECT_CLOSURE_ADJUST_SHAL_OPENACC
INTERFACE

SUBROUTINE CONVECT_CLOSURE_ADJUST_SHAL_OPENACC (CVPEXT, D,&
& PADJ, PUMF, PZUMF, PUER, PZUER, PUDR, PZUDR, YDSTACK)
!$ACC ROUTINE (CONVECT_CLOSURE_ADJUST_SHAL_OPENACC) SEQ
USE MODD_CONVPAREXT,ONLY:CONVPAREXT
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
TYPE (CONVPAREXT), INTENT (IN)::CVPEXT
TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PADJ(D%NIT)
REAL, INTENT (INOUT)::PUMF(D%NIT, D%NKT)
REAL, INTENT (INOUT)::PZUMF(D%NIT, D%NKT)
REAL, INTENT (INOUT)::PUER(D%NIT, D%NKT)
REAL, INTENT (INOUT)::PZUER(D%NIT, D%NKT)
REAL, INTENT (INOUT)::PUDR(D%NIT, D%NKT)
REAL, INTENT (INOUT)::PZUDR(D%NIT, D%NKT)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
END SUBROUTINE CONVECT_CLOSURE_ADJUST_SHAL_OPENACC

END INTERFACE
END MODULE
