MODULE MODI_CONVECT_TRIGGER_SHAL_OPENACC
INTERFACE

SUBROUTINE CONVECT_TRIGGER_SHAL_OPENACC (CVP_SHAL, CVPEXT, CST, D, PPRES, PTH, PTHV, PTHES, PRV, PW&
&, PZ, PTKECLS, PTHLCL, PTLCL, PRVLCL, PWLCL, PZLCL, PTHVELCL, KLCL, KDPL, KPBL, OTRIG, YDSTACK)
!$ACC ROUTINE (CONVECT_TRIGGER_SHAL_OPENACC) SEQ
USE MODD_CST,ONLY:CST_T
USE MODD_CONVPAR_SHAL,ONLY:CONVPAR_SHAL
USE MODD_CONVPAREXT,ONLY:CONVPAREXT
USE MODD_DIMPHYEX,ONLY:DIMPHYEX_T
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
TYPE (CONVPAR_SHAL), INTENT (IN)::CVP_SHAL
TYPE (CONVPAREXT), INTENT (IN)::CVPEXT
TYPE (CST_T), INTENT (IN)::CST
TYPE (DIMPHYEX_T), INTENT (IN)::D
REAL, INTENT (IN)::PTKECLS(D%NIT)
REAL, INTENT (IN)::PTHV(D%NIT, D%NKT)
REAL, INTENT (IN)::PTH(D%NIT, D%NKT)
REAL, INTENT (IN)::PTHES(D%NIT, D%NKT)
REAL, INTENT (IN)::PRV(D%NIT, D%NKT)
REAL, INTENT (IN)::PPRES(D%NIT, D%NKT)
REAL, INTENT (IN)::PZ(D%NIT, D%NKT)
REAL, INTENT (IN)::PW(D%NIT, D%NKT)
REAL, INTENT (OUT)::PTHLCL(D%NIT)
REAL, INTENT (OUT)::PTLCL(D%NIT)
REAL, INTENT (OUT)::PRVLCL(D%NIT)
REAL, INTENT (OUT)::PWLCL(D%NIT)
REAL, INTENT (OUT)::PZLCL(D%NIT)
REAL, INTENT (OUT)::PTHVELCL(D%NIT)
LOGICAL, INTENT (OUT)::OTRIG(D%NIT)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
INTEGER, INTENT (INOUT)::KLCL(D%NIT)
INTEGER, INTENT (INOUT)::KDPL(D%NIT)
INTEGER, INTENT (INOUT)::KPBL(D%NIT)
END SUBROUTINE CONVECT_TRIGGER_SHAL_OPENACC

END INTERFACE
END MODULE
