
SUBROUTINE GPCTY_EXPL_OPENACC (YDVFE, YDCVER, KPROMA, KST, KEND, KFLEV, LDRUBC, YDVAB&
&, YDVETA, PU, PV, PD, PEVT, PSPL, PSPM, PRPREF, PDPHYCTY, PDELP, PLNPR, PRDELP, PALPH&
&, PRTGR, PRPRE, PRPP, PEVEL, PVVEL, PPSDIV, PPSDVBC, PDIVDP, YDSTACK)
!$ACC ROUTINE (GPCTY_EXPL_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMVERT,ONLY:TVFE, TVAB, TVETA
USE YOMCVER,ONLY:TCVER
#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (TVFE), INTENT (IN)::YDVFE
TYPE (TCVER), INTENT (IN)::YDCVER
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
LOGICAL, INTENT (IN)::LDRUBC
TYPE (TVAB), INTENT (IN)::YDVAB
TYPE (TVETA), INTENT (IN)::YDVETA
REAL (KIND=JPRB), INTENT (IN)::PU (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PD (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PEVT (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PSPL (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PSPM (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PRPREF (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN), OPTIONAL::PDPHYCTY (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PALPH (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PLNPR (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PRPP (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PRPRE (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PRTGR (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PPSDIV (KPROMA, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PVVEL (KPROMA, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PEVEL (KPROMA, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDIVDP (KPROMA, 0:KFLEV)
TYPE(STACK), INTENT (IN) :: YDSTACK
TYPE(STACK) :: YLSTACK
REAL (KIND=JPRB), INTENT (OUT)::PPSDVBC (KPROMA, 0:KFLEV)
REAL (KIND=JPRB)::ZSDIV (KPROMA, 0:KFLEV+1)
REAL (KIND=JPRB)::ZPSDIVFE (KPROMA)
REAL (KIND=JPRB)::ZVP (KPROMA, KFLEV)
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JROF


#include "verdisint_openacc.intfb.h"
INTEGER (KIND=JPIM) :: JLON

YLSTACK = YDSTACK



JLON = KIDIA



IF (LDRUBC.AND.YDCVER%LVERTFE)  THEN
    CALL ABOR1_ACC ('GPCTY_EXPL: BAD OPTIONS')
ENDIF


DO JLEV=1, KFLEV
  ZVP (KST:KEND, JLEV)=PU (KST:KEND, JLEV)*PSPL (KST:KEND)+PV (KST:KEND, JLEV)*PSPM (KST:KEND)
ENDDO


IF (PRESENT (PDPHYCTY)) THEN

  DO JLEV=1, KFLEV
    PDIVDP (KST:KEND, JLEV)=PD (KST:KEND, JLEV)*PDELP (KST:KEND, JLEV)+YDVAB%VDELB &
    &(JLEV)*ZVP (KST:KEND, JLEV)-PDPHYCTY (KST:KEND, JLEV)*PDELP (KST:KEND, JLEV)
  ENDDO

ELSE

  DO JLEV=1, KFLEV
    PDIVDP (KST:KEND, JLEV)=PD (KST:KEND, JLEV)*PDELP (KST:KEND&
    &, JLEV)+YDVAB%VDELB (JLEV)*ZVP (KST:KEND, JLEV)
  ENDDO

ENDIF

PPSDIV (KST:KEND, 0)=0.0_JPRB

IF (YDCVER%LVERTFE) THEN

  DO JLEV=1, KFLEV
    ZSDIV (KST:KEND, JLEV)=PDIVDP (KST:KEND, JLEV)*YDVETA%VFE_RDETAH (JLEV)
  ENDDO

  ZSDIV (KST:KEND, 0)=0.0_JPRB
  ZSDIV (KST:KEND, KFLEV+1)=0.0_JPRB
  CALL VERDISINT_OPENACC (YDVFE, YDCVER,'ITOP','11', KPROMA, KST, KEND, KFLEV&
  &, ZSDIV, PPSDIV (:, 1:KFLEV), POUTS=ZPSDIVFE, YDSTACK=YLSTACK)
ELSE

  DO JLEV=1, KFLEV

    DO JROF=KST, KEND
      PPSDIV (JROF, JLEV)=PPSDIV (JROF, JLEV-1)+PDIVDP (JROF, JLEV)
    ENDDO

  ENDDO

ENDIF


IF (LDRUBC) THEN

  IF (YDCVER%LVERTFE) THEN

    DO JROF=KST, KEND
      PPSDVBC (JROF, KFLEV)=ZPSDIVFE (JROF)-PEVT (JROF)
    ENDDO

  ELSE

    DO JLEV=0, KFLEV

      DO JROF=KST, KEND
        PPSDVBC (JROF, JLEV)=PPSDIV (JROF, JLEV)-PEVT (JROF)
      ENDDO

    ENDDO

  ENDIF

ELSE

  IF (YDCVER%LVERTFE) THEN

    DO JROF=KST, KEND
      PPSDVBC (JROF, KFLEV)=ZPSDIVFE (JROF)
    ENDDO

  ELSE

    DO JLEV=0, KFLEV

      DO JROF=KST, KEND
        PPSDVBC (JROF, JLEV)=PPSDIV (JROF, JLEV)
      ENDDO

    ENDDO

  ENDIF

ENDIF


IF (YDCVER%LVERTFE) THEN

  DO JLEV=1, KFLEV

    DO JROF=KST, KEND
      PEVEL (JROF, JLEV)=YDVAB%VBF (JLEV)*ZPSDIVFE (JROF)-PPSDIV (JROF, JLEV)
    ENDDO

  ENDDO

ELSE

  DO JLEV=1, KFLEV-1

    DO JROF=KST, KEND
      PEVEL (JROF, JLEV)=YDVAB%VBH (JLEV)*PPSDIV (JROF, KFLEV)-PPSDIV (JROF, JLEV)
    ENDDO

  ENDDO

ENDIF

PEVEL (KST:KEND, 0)=0.0_JPRB

IF (.NOT.YDCVER%LVERTFE)  THEN
    PEVEL (KST:KEND, KFLEV)=0.0_JPRB
ENDIF


IF (LDRUBC) THEN

  IF (YDCVER%LVERTFE) THEN
    CALL ABOR1_ACC (' GPCTY_EXPL: VFE not coded for LRUBC.')
  ELSE

    DO JLEV=0, KFLEV
      PEVEL (KST:KEND, JLEV)=PEVEL (KST:KEND, JLEV)+(1.0_JPRB-YDVAB%VBH (JLEV))*PEVT (KST:KEND)
    ENDDO

  ENDIF

ENDIF


IF (YDCVER%LVERTFE) THEN

  DO JLEV=1, KFLEV

    DO JROF=KST, KEND
      PVVEL (JROF, JLEV)=(YDVAB%VBF (JLEV)*ZVP (JROF, JLEV)-PPSDIV (JROF, JLEV))*PRPREF (JROF, JLEV)
    ENDDO

  ENDDO

ELSE

  DO JLEV=1, KFLEV

    DO JROF=KST, KEND
      PVVEL (JROF, JLEV)=PRTGR (JROF, JLEV)*ZVP (JROF, JLEV)-PRDELP (JROF, JLEV)*PALPH&
      & (JROF, JLEV)*YDVAB%VDELB (JLEV)*ZVP (JROF, JLEV)-PALPH (JROF, JLEV)*PD (JROF&
      &, JLEV)-PRDELP (JROF, JLEV)*PPSDVBC (JROF, JLEV-1)*PLNPR (JROF, JLEV)
    ENDDO

  ENDDO

ENDIF



ENDSUBROUTINE GPCTY_EXPL_OPENACC
