
SUBROUTINE GPGRP_EXPL_OPENACC (YDGEOMETRY, KST, KEND, PRT, PRTL, PRTM, PREL, PREM, PRTGR, PALPH&
&, PHIHL, PHIHM, PHIFL, PHIFM, PSGRTL, PSGRTM, PALPHPLL_DER, PALPHPLM_DER, YDSTACK)
!$ACC ROUTINE (GPGRP_EXPL_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE GEOMETRY_MOD,ONLY:GEOMETRY
#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
REAL (KIND=JPRB), INTENT (IN)::PRT (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PRTL (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PRTM (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PREL (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (IN)::PREM (YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB), INTENT (IN)::PRTGR (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PALPH (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PHIHL (YDGEOMETRY%YRDIM%NPROMA, 0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PHIHM (YDGEOMETRY%YRDIM%NPROMA, 0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PHIFL (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PHIFM (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSGRTL (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (OUT)::PSGRTM (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PALPHPLL_DER (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PALPHPLM_DER (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
TYPE(STACK), INTENT (IN) :: YDSTACK
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV

INTEGER (KIND=JPIM) :: JLON

JLON = KIDIA





IF (YDGEOMETRY%YRVERT_GEOM%YRCVER%LVERTFE) THEN

  DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

    DO JROF=KST, KEND
      PSGRTL (JLON, JLEV)=PHIFL (JLON, JLEV)+PRT (JLON, JLEV)*PRTGR (JLON, JLEV)*PREL (JLON)
      PSGRTM (JLON, JLEV)=PHIFM (JLON, JLEV)+PRT (JLON, JLEV)*PRTGR (JLON, JLEV)*PREM (JLON)
    ENDDO

  ENDDO

ELSE

  DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG

    DO JROF=KST, KEND
      PSGRTL (JLON, JLEV)=PHIHL (JLON, JLEV)+(PALPH (JLON, JLEV)*PRTL&
      & (JLON, JLEV)+PALPHPLL_DER (JLON, JLEV)*PRT (JLON, JLEV))
      PSGRTM (JLON, JLEV)=PHIHM (JLON, JLEV)+(PALPH (JLON, JLEV)*PRTM&
      & (JLON, JLEV)+PALPHPLM_DER (JLON, JLEV)*PRT (JLON, JLEV))
    ENDDO

  ENDDO

ENDIF




ENDSUBROUTINE GPGRP_EXPL_OPENACC
