SUBROUTINE GPHLWI_OPENACC (LDVERTFE, KFLEV, KPROMA, KST, KEND&
&, PLNPR, PALPH, PRDETAH, PDETA_RATIO, PWW, YDSTACK)
!$ACC ROUTINE (GPHLWI_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

LOGICAL, INTENT (IN)::LDVERTFE
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
REAL (KIND=JPRB), INTENT (IN)::PLNPR (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PALPH (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDETAH (KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDETA_RATIO (KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PWW (KPROMA, 0:KFLEV)
TYPE(STACK), INTENT (IN) :: YDSTACK
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV

INTEGER (KIND=JPIM) :: JLON

JLON = KIDIA



IF (LDVERTFE) THEN

  DO JLEV=1, KFLEV-1

    DO JROF=KST, KEND
      PWW (JROF, JLEV)=(PDETA_RATIO (JLEV)*PRDETAH (JLEV))/((PDETA_RATIO &
      &(JLEV+1)*PRDETAH (JLEV+1))+(PDETA_RATIO (JLEV)*PRDETAH (JLEV)))
    ENDDO

  ENDDO

ELSE

  DO JLEV=1, KFLEV-1

    DO JROF=KST, KEND
      PWW (JROF, JLEV)=(PLNPR (JROF, JLEV+1)-PALPH (JROF, JLEV+1))/(PLNPR&
      & (JROF, JLEV+1)-PALPH (JROF, JLEV+1)+PALPH (JROF, JLEV))
    ENDDO

  ENDDO

ENDIF


DO JROF=KST, KEND
  PWW (JROF, KFLEV)=1.0_JPRB
ENDDO



ENDSUBROUTINE GPHLWI_OPENACC
