SUBROUTINE GPHLUV_EXPL_OPENACC (YDDIMV, KPROMA, KST, KEND, PU, PV, PWWI, PUH, PVH, YDSTACK)
!$ACC ROUTINE (GPHLUV_EXPL_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMDIMV,ONLY:TDIMV
#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (TDIMV), INTENT (IN)::YDDIMV
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
REAL (KIND=JPRB), INTENT (IN)::PU (KPROMA, YDDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PV (KPROMA, YDDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PWWI (KPROMA, 0:YDDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PUH (KPROMA, 0:YDDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PVH (KPROMA, 0:YDDIMV%NFLEVG)
TYPE(STACK), INTENT (IN) :: YDSTACK
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JROF
REAL (KIND=JPRB)::ZWW

INTEGER (KIND=JPIM) :: JLON

JLON = KIDIA





DO JLEV=1, YDDIMV%NFLEVG-1

  DO JROF=KST, KEND
    ZWW=PWWI (JROF, JLEV)
    PUH (JROF, JLEV)=ZWW*PU (JROF, JLEV)+(1.0_JPRB-ZWW)*PU (JROF, JLEV+1)
    PVH (JROF, JLEV)=ZWW*PV (JROF, JLEV)+(1.0_JPRB-ZWW)*PV (JROF, JLEV+1)
  ENDDO

ENDDO

PUH (KST:KEND, 0)=PU (KST:KEND, 1)
PVH (KST:KEND, 0)=PV (KST:KEND, 1)
PUH (KST:KEND, YDDIMV%NFLEVG)=PU (KST:KEND, YDDIMV%NFLEVG)
PVH (KST:KEND, YDDIMV%NFLEVG)=PV (KST:KEND, YDDIMV%NFLEVG)



ENDSUBROUTINE GPHLUV_EXPL_OPENACC
