SUBROUTINE GPHPRE_EXPL_OPENACC (YDCVER, TOPPRES, YDCST, KPROMA, KFLEV, KST, KEND, YDVAB, PRESH, PRESF&
&, LHSET, LDELP, LALPHA, LRTGR, LRPP, PDELP, PLNPR, PRDELP, PALPH, PRTGR, PRPRE, PRPP, YDSTACK)
!$ACC ROUTINE (GPHPRE_EXPL_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOMVERT,ONLY:TVAB
USE YOMCVER,ONLY:TCVER
#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (TCVER), INTENT (IN)::YDCVER
REAL (KIND=JPRB), INTENT (IN)::TOPPRES
TYPE (TCST), INTENT (IN)::YDCST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
TYPE (TVAB), INTENT (IN)::YDVAB
REAL (KIND=JPRB), INTENT (INOUT)::PRESH (KPROMA, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PRESF (KPROMA, KFLEV)
LOGICAL, INTENT (IN), OPTIONAL::LRPP
LOGICAL, INTENT (IN), OPTIONAL::LRTGR
LOGICAL, INTENT (IN), OPTIONAL::LALPHA
LOGICAL, INTENT (IN), OPTIONAL::LDELP
LOGICAL, INTENT (IN), OPTIONAL::LHSET
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PALPH (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PRDELP (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PLNPR (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PDELP (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PRPP (KPROMA, KFLEV)
TYPE(STACK), INTENT (IN) :: YDSTACK
TYPE(STACK) :: YLSTACK
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PRPRE (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PRTGR (KPROMA, KFLEV)
#include "gphpre_expl_vertfe0_openacc.intfb.h"
#include "gphpre_expl_vertfe1_openacc.intfb.h"
INTEGER (KIND=JPIM)::JLEV
LOGICAL::LLHSET

INTEGER (KIND=JPIM) :: JLON

YLSTACK = YDSTACK



JLON = KIDIA


LLHSET=.FALSE.

IF (PRESENT (LHSET))  THEN
    LLHSET=LHSET
ENDIF


IF (.NOT.LLHSET) THEN

  DO JLEV=0, KFLEV-1
    PRESH (KST:KEND, JLEV)=YDVAB%VAH (JLEV)+YDVAB%VBH (JLEV)*PRESH (KST:KEND, KFLEV)
  ENDDO

ENDIF


IF (YDCVER%LVERTFE) THEN
  CALL GPHPRE_EXPL_VERTFE1_OPENACC (YDCVER, TOPPRES, YDCST, KPROMA, KFLEV&
  &, KST, KEND, YDVAB, PRESH, PRESF, LHSET, LDELP, LALPHA, LRTGR, LRPP, PDELP&
  &, PLNPR, PRDELP, PALPH, PRTGR, PRPRE, PRPP, YDSTACK=YLSTACK)
ELSE
  CALL GPHPRE_EXPL_VERTFE0_OPENACC (YDCVER, TOPPRES, YDCST, KPROMA, KFLEV&
  &, KST, KEND, YDVAB, PRESH, PRESF, LHSET, LDELP, LALPHA, LRTGR, LRPP, PDELP&
  &, PLNPR, PRDELP, PALPH, PRTGR, PRPRE, PRPP, YDSTACK=YLSTACK)
ENDIF



ENDSUBROUTINE GPHPRE_EXPL_OPENACC
