SUBROUTINE LARCHE_OPENACC (YDTCCO, YDTSCO, KPROMA, KST, KEND, KFLEV, KSTTYP&
&, PDSTRET, PC2M1, PC2P1, PI, PDEPI, PLOCEN, PMUCEN, PSCO, KROT, PCCO&
&, PRCOLON, PRSILON, PGECLO, PGEMU, PGESLO, PGSQM2, YDSTACK)
!$ACC ROUTINE (LARCHE_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB, JPRD

USE INTDYNSL_MOD,ONLY:TSCO, TCCO
#include "stack.h"
USE STACK_MOD
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE (TCCO), INTENT (IN)::YDTCCO
TYPE (TSCO), INTENT (IN)::YDTSCO
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KSTTYP
REAL (KIND=JPRB), INTENT (IN)::PDSTRET
REAL (KIND=JPRB), INTENT (IN)::PC2M1
REAL (KIND=JPRB), INTENT (IN)::PC2P1
REAL (KIND=JPRB), INTENT (IN)::PI
REAL (KIND=JPRB), INTENT (IN)::PDEPI
REAL (KIND=JPRB), INTENT (IN)::PLOCEN
REAL (KIND=JPRB), INTENT (IN)::PMUCEN
REAL (KIND=JPRB), INTENT (IN)::PSCO (KPROMA, KFLEV, YDTSCO%NDIM)
INTEGER (KIND=JPIM), INTENT (IN)::KROT
REAL (KIND=JPRB), INTENT (OUT)::PCCO (KPROMA, KFLEV, YDTCCO%NDIM)
REAL (KIND=JPRD), INTENT (IN)::PRCOLON (KPROMA)
REAL (KIND=JPRD), INTENT (IN)::PRSILON (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PGECLO (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PGEMU (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PGESLO (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PGSQM2 (KPROMA)
TYPE(STACK), INTENT (IN) :: YDSTACK
LOGICAL::LLSTR
REAL (KIND=JPRD)::ZPDSTRET
REAL (KIND=JPRD)::ZPC2M1
REAL (KIND=JPRD)::ZPC2P1
REAL (KIND=JPRD)::ZPI
REAL (KIND=JPRD)::ZPDEPI
REAL (KIND=JPRD)::ZPSCO (KPROMA, KFLEV, YDTSCO%NDIM)
REAL (KIND=JPRD)::ZTMP1 (KPROMA)
REAL (KIND=JPRD)::ZTMP2 (KPROMA)
REAL (KIND=JPRD)::ZTMP4 (KPROMA)
REAL (KIND=JPRD)::ZTMP5 (KPROMA)
REAL (KIND=JPRD)::ZTMP6 (KPROMA)
REAL (KIND=JPRD)::ZTMP7 (KPROMA)
REAL (KIND=JPRD)::ZTMP8 (KPROMA)
REAL (KIND=JPRD)::ZTMP9 (KPROMA)
REAL (KIND=JPRD)::ZZA (KPROMA)
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRD)::ZPIH52
REAL (KIND=JPRD)::ZPIH
REAL (KIND=JPRD)::ZANGLE
REAL (KIND=JPRD)::ZZZ
REAL (KIND=JPRD)::ZZY
REAL (KIND=JPRD)::ZZX
REAL (KIND=JPRD)::ZZW
REAL (KIND=JPRD)::ZZP
REAL (KIND=JPRD)::ZYY
REAL (KIND=JPRD)::ZXX
REAL (KIND=JPRD)::ZSINLA
REAL (KIND=JPRD)::ZSINCO
REAL (KIND=JPRD)::ZSA
REAL (KIND=JPRD)::ZQ
REAL (KIND=JPRD)::ZPSLOP
REAL (KIND=JPRD)::ZPSLAP
REAL (KIND=JPRD)::ZPCLOP
REAL (KIND=JPRD)::ZPCLAP
REAL (KIND=JPRD)::ZP
REAL (KIND=JPRD)::ZMU
REAL (KIND=JPRD)::ZFACT2
REAL (KIND=JPRD)::ZFACT1
REAL (KIND=JPRD)::ZEPS1
REAL (KIND=JPRD)::ZEPS
REAL (KIND=JPRD)::ZDI
REAL (KIND=JPRD)::ZDECO
REAL (KIND=JPRD)::ZCOSLR
REAL (KIND=JPRD)::ZCOSLA
REAL (KIND=JPRD)::ZCOSL2
REAL (KIND=JPRD)::ZCOSCO
REAL (KIND=JPRD)::ZCA
REAL (KIND=JPRD)::Z1STT
REAL (KIND=JPRD)::Z1ST

INTEGER (KIND=JPIM) :: JLON

JLON = KIDIA


ZPDSTRET=PDSTRET
ZPC2M1=PC2M1
ZPC2P1=PC2P1
ZPI=PI
ZPDEPI=PDEPI
ZPSCO (KST:KEND, 1:KFLEV, 1:YDTSCO%NDIM)=PSCO (KST:KEND, 1:KFLEV, 1:YDTSCO%NDIM)
ZEPS=100._JPRD*EPSILON (ZEPS)
ZEPS1=100.0_JPRD*TINY (1.0_JPRD)
LLSTR=(ABS (0.5_JPRD*PDSTRET-1.0_JPRD)>ZEPS1)
ZANGLE=SQRT (0.5_JPRD)
ZPIH=0.5_JPRD*PI
ZPIH52=2.5_JPRD*PI

IF (KSTTYP==1.AND.(.NOT.LLSTR)) THEN

  DO JLEV=1, KFLEV

    DO JROF=KST, KEND
      ZCOSLR=SQRT (ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO&
      &)+ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO))
      ZCOSLR=MAX (ZEPS, ZCOSLR)
      ZCOSCO=ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)
      ZSINCO=ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
      ZCOSLA=ZCOSLR
      ZTMP7 (JROF)=ZCOSLA
      ZXX=PRCOLON (JROF)*ZCOSCO-PRSILON (JROF)*ZSINCO
      ZYY=PRSILON (JROF)*ZCOSCO+PRCOLON (JROF)*ZSINCO
      ZTMP5 (JROF)=SIGN (1.0_JPRD, ZYY)
      ZTMP8 (JROF)=SIGN (1.0_JPRD, ZXX)
      ZTMP6 (JROF)=MAX (-1.0_JPRD, MIN (1.0_JPRD, ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)))
      ZTMP4 (JROF)=MAX (-1.0_JPRD, MIN (1.0_JPRD, ZXX/ZCOSLA))
      ZZA (JROF)=MAX (-1.0_JPRD, MIN (1.0_JPRD, ZYY/ZCOSLA))
    ENDDO


    DO JROF=KST, KEND
      ZTMP6 (JROF)=ASIN (ZTMP6 (JROF))
      ZTMP4 (JROF)=ACOS (ZTMP4 (JROF))
      ZTMP9 (JROF)=ASIN (ZZA (JROF))
    ENDDO


    DO JROF=KST, KEND
      PCCO (JROF, JLEV, YDTCCO%M_RLAT)=ZTMP6 (JROF)
      PCCO (JROF, JLEV, YDTCCO%M_RLON)=MERGE (MOD (PI+ZTMP5 (JROF)*(ZTMP4 (JROF)-PI), PDEPI&
      &), MOD (ZPIH52+ZTMP8 (JROF)*(ZTMP9 (JROF)-ZPIH), PDEPI), ABS (ZZA (JROF))>=ZANGLE)
    ENDDO


    IF (KROT==1) THEN

      DO JROF=KST, KEND
        ZDECO=1.0_JPRD/(1.0_JPRD+ZPSCO (JROF, JLEV, YDTSCO%M_COPHI))
        Z1ST=1.0_JPRD/ZTMP7 (JROF)
        PCCO (JROF, JLEV, YDTCCO%M_RQX)=(PGSQM2 (JROF)*ZTMP7 (JROF)+(1.0_JPRD+PGEMU (JROF)*ZPSCO&
        & (JROF, JLEV, YDTSCO%M_SINLA))*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*Z1ST)*ZDECO
        PCCO (JROF, JLEV, YDTCCO%M_RQY)=-(PGEMU (JROF)+ZPSCO (JROF, JLEV, YDTSCO&
        &%M_SINLA))*(ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*Z1ST)*ZDECO
      ENDDO

    ENDIF

  ENDDO

ELSEIF (KSTTYP==1.AND.LLSTR) THEN

  DO JLEV=1, KFLEV

    DO JROF=KST, KEND
      ZCOSLR=SQRT (ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO&
      &)+ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO))
      ZTMP5 (JROF)=MAX (ZEPS, ZCOSLR)
      ZFACT1=1.0_JPRD/(ZPC2P1-ZPC2M1*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA))
      ZFACT2=ZPDSTRET*ZFACT1
      ZCOSCO=ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*ZFACT2
      ZSINCO=ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*ZFACT2
      ZCOSLA=ZTMP5 (JROF)*ZFACT2
      ZSINLA=(ZPC2P1*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)-ZPC2M1)*ZFACT1
      ZXX=PRCOLON (JROF)*ZCOSCO-PRSILON (JROF)*ZSINCO
      ZTMP4 (JROF)=PRSILON (JROF)*ZCOSCO+PRCOLON (JROF)*ZSINCO
      ZTMP1 (JROF)=MAX (-1.0_JPRD, MIN (1.0_JPRD, ZSINLA))
      ZTMP2 (JROF)=MAX (-1.0_JPRD, MIN (1.0_JPRD, ZXX/ZCOSLA))
    ENDDO


    DO JROF=KST, KEND
      PCCO (JROF, JLEV, YDTCCO%M_RLAT)=ASIN (ZTMP1 (JROF))
      PCCO (JROF, JLEV, YDTCCO%M_RLON)=ZPI+SIGN (1.0_JPRD, ZTMP4 (JROF))*(ACOS (ZTMP2 (JROF))-ZPI)
    ENDDO


    DO JROF=KST, KEND
      PCCO (JROF, JLEV, YDTCCO%M_RLON)=MOD (PCCO (JROF, JLEV, YDTCCO%M_RLON), ZPDEPI)
    ENDDO


    IF (KROT==1) THEN

      DO JROF=KST, KEND
        ZDECO=1.0_JPRD/(1.0_JPRD+ZPSCO (JROF, JLEV, YDTSCO%M_COPHI))
        Z1ST=1.0_JPRD/ZTMP5 (JROF)
        PCCO (JROF, JLEV, YDTCCO%M_RQX)=(PGSQM2 (JROF)*ZTMP5 (JROF)+(1.0_JPRD+PGEMU (JROF)*ZPSCO&
        & (JROF, JLEV, YDTSCO%M_SINLA))*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*Z1ST)*ZDECO
        PCCO (JROF, JLEV, YDTCCO%M_RQY)=-(PGEMU (JROF)+ZPSCO (JROF, JLEV, YDTSCO&
        &%M_SINLA))*(ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*Z1ST)*ZDECO
      ENDDO

    ENDIF

  ENDDO

ELSEIF (KSTTYP==2) THEN
  ZPSLAP=PMUCEN
  ZPCLAP=SQRT (1.0_JPRD-REAL (PMUCEN, JPRD)*REAL (PMUCEN, JPRD))
  ZPSLOP=SIN (REAL (PLOCEN, JPRD))
  ZPCLOP=COS (REAL (PLOCEN, JPRD))

  DO JLEV=1, KFLEV

    DO JROF=KST, KEND
      ZZY=PGESLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)&
      &+PGECLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
      ZZX=PGECLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)&
      &-PGESLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
      ZZZ=ZZX*ZPCLOP+ZPSLOP*ZZY
      ZZP=ZPSLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)+ZPCLAP*ZZZ
      ZDI=1.0_JPRD/(ZPC2P1-ZPC2M1*ZZP)
      ZYY=ZPDSTRET*ZDI*(-ZPCLOP*ZZY+ZPSLOP*ZZX)
      ZXX=ZPDSTRET*ZDI*(ZPCLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)-ZPSLAP*ZZZ)
      ZCOSLA=SQRT (ZXX*ZXX+ZYY*ZYY)
      ZCOSLA=MAX (ZEPS, ZCOSLA)
      ZSINLA=-(ZPC2M1-ZPC2P1*ZZP)*ZDI
      ZTMP4 (JROF)=ZYY
      ZTMP1 (JROF)=MAX (-1.0_JPRD, MIN (1.0_JPRD, ZSINLA))
      ZTMP2 (JROF)=MAX (-1.0_JPRD, MIN (1.0_JPRD, ZXX/ZCOSLA))
    ENDDO


    DO JROF=KST, KEND
      PCCO (JROF, JLEV, YDTCCO%M_RLAT)=ASIN (ZTMP1 (JROF))
      PCCO (JROF, JLEV, YDTCCO%M_RLON)=ZPI+SIGN (1.0_JPRD, ZTMP4 (JROF))*(ACOS (ZTMP2 (JROF))-ZPI)
    ENDDO


    DO JROF=KST, KEND
      PCCO (JROF, JLEV, YDTCCO%M_RLON)=MOD (PCCO (JROF, JLEV, YDTCCO%M_RLON), ZPDEPI)
    ENDDO


    IF (KROT==1) THEN

      DO JROF=KST, KEND
        ZZY=PGESLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)&
        &+PGECLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
        ZZX=PGECLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)&
        &-PGESLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
        ZCOSL2=ZZY*ZZY+ZZX*ZZX
        ZCOSLR=SQRT (ZCOSL2)
        ZCOSLR=MAX (ZEPS, ZCOSLR)
        ZZZ=ZZX*ZPCLOP+ZPSLOP*ZZY
        ZZP=ZPSLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)+ZPCLAP*ZZZ
        ZDI=1.0_JPRD/(ZPC2P1-ZPC2M1*ZZP)
        ZYY=ZPDSTRET*ZDI*(-ZPCLOP*ZZY+ZPSLOP*ZZX)
        ZXX=ZPDSTRET*ZDI*(ZPCLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)-ZPSLAP*ZZZ)
        ZCOSLA=SQRT (ZXX*ZXX+ZYY*ZYY)
        ZCOSLA=MAX (ZEPS, ZCOSLA)
        ZDECO=1.0_JPRD/(1.0_JPRD+ZPSCO (JROF, JLEV, YDTSCO%M_COPHI))
        Z1ST=1.0_JPRD/ZCOSLR
        Z1STT=Z1ST/ZCOSLA
        ZP=(PGSQM2 (JROF)*ZCOSLR+(1.0_JPRD+PGEMU (JROF)*ZPSCO (JROF, JLEV, YDTSCO&
        &%M_SINLA))*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*Z1ST)*ZDECO
        ZQ=-(PGEMU (JROF)+ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)&
        &)*(ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*Z1ST)*ZDECO
        ZCA=ZPDSTRET*ZDI*(ZPSLAP*ZCOSL2-ZPCLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)*ZZZ)*Z1STT
        ZSA=-ZYY*ZPCLAP*Z1STT
        PCCO (JROF, JLEV, YDTCCO%M_RQX)=ZP*ZCA+ZQ*ZSA
        PCCO (JROF, JLEV, YDTCCO%M_RQY)=ZQ*ZCA-ZP*ZSA
      ENDDO

    ENDIF

  ENDDO

ENDIF



ENDSUBROUTINE LARCHE_OPENACC
