MODULE BR_INTRINSICS

USE, INTRINSIC :: ISO_C_BINDING

IMPLICIT NONE

INTEGER, PARAMETER :: JPRD = 8, JPRM = 4

PRIVATE 

PUBLIC :: BR_SIN
PUBLIC :: BR_COS
PUBLIC :: BR_TAN
PUBLIC :: BR_ASIN
PUBLIC :: BR_ACOS
PUBLIC :: BR_ATAN
PUBLIC :: BR_SINH
PUBLIC :: BR_COSH
PUBLIC :: BR_TANH
PUBLIC :: BR_ASINH
PUBLIC :: BR_ACOSH
PUBLIC :: BR_ATANH
PUBLIC :: BR_LOG
PUBLIC :: BR_LOG10
PUBLIC :: BR_EXP
PUBLIC :: BR_ERF
PUBLIC :: BR_ERFC
PUBLIC :: BR_GAMMA
PUBLIC :: BR_LOG_GAMMA
PUBLIC :: BR_ATAN2
PUBLIC :: BR_POW

INTERFACE
PURE REAL(KIND=C_DOUBLE) FUNCTION BR_SIN_C(P) BIND(C,NAME="br_sin")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_COS_C(P) BIND(C,NAME="br_cos")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_TAN_C(P) BIND(C,NAME="br_tan")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_ASIN_C(P) BIND(C,NAME="br_asin")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_ACOS_C(P) BIND(C,NAME="br_acos")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_ATAN_C(P) BIND(C,NAME="br_atan")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_SINH_C(P) BIND(C,NAME="br_sinh")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_COSH_C(P) BIND(C,NAME="br_cosh")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_TANH_C(P) BIND(C,NAME="br_tanh")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_ASINH_C(P) BIND(C,NAME="br_asinh")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_ACOSH_C(P) BIND(C,NAME="br_acosh")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_ATANH_C(P) BIND(C,NAME="br_atanh")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_LOG_C(P) BIND(C,NAME="br_log")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_EXP_C(P) BIND(C,NAME="br_exp")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_GAMMA_C(P) BIND(C,NAME="br_gamma")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_LOG_GAMMA_C(P) BIND(C,NAME="br_log_gamma")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_ERF_C(P) BIND(C,NAME="br_erf")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

PURE REAL(KIND=C_DOUBLE) FUNCTION BR_ERFC_C(P) BIND(C,NAME="br_erfc")
!$ACC ROUTINE SEQ
IMPORT C_DOUBLE
REAL(KIND=C_DOUBLE), VALUE, INTENT(IN) :: P
END FUNCTION

END INTERFACE

INTERFACE BR_SIN
  MODULE PROCEDURE BR_SIN_RM
  MODULE PROCEDURE BR_SIN_RD
END INTERFACE

INTERFACE BR_COS
  MODULE PROCEDURE BR_COS_RM
  MODULE PROCEDURE BR_COS_RD
END INTERFACE

INTERFACE BR_TAN
  MODULE PROCEDURE BR_TAN_RM
  MODULE PROCEDURE BR_TAN_RD
END INTERFACE

INTERFACE BR_ASIN
  MODULE PROCEDURE BR_ASIN_RM
  MODULE PROCEDURE BR_ASIN_RD
END INTERFACE

INTERFACE BR_ACOS
  MODULE PROCEDURE BR_ACOS_RM
  MODULE PROCEDURE BR_ACOS_RD
END INTERFACE

INTERFACE BR_ATAN
  MODULE PROCEDURE BR_ATAN_RM
  MODULE PROCEDURE BR_ATAN_RD
END INTERFACE

INTERFACE BR_SINH
  MODULE PROCEDURE BR_SINH_RM
  MODULE PROCEDURE BR_SINH_RD
END INTERFACE

INTERFACE BR_COSH
  MODULE PROCEDURE BR_COSH_RM
  MODULE PROCEDURE BR_COSH_RD
END INTERFACE

INTERFACE BR_TANH
  MODULE PROCEDURE BR_TANH_RM
  MODULE PROCEDURE BR_TANH_RD
END INTERFACE

INTERFACE BR_ASINH
  MODULE PROCEDURE BR_ASINH_RM
  MODULE PROCEDURE BR_ASINH_RD
END INTERFACE

INTERFACE BR_ACOSH
  MODULE PROCEDURE BR_ACOSH_RM
  MODULE PROCEDURE BR_ACOSH_RD
END INTERFACE

INTERFACE BR_ATANH
  MODULE PROCEDURE BR_ATANH_RM
  MODULE PROCEDURE BR_ATANH_RD
END INTERFACE

INTERFACE BR_LOG
  MODULE PROCEDURE BR_LOG_RM
  MODULE PROCEDURE BR_LOG_RD
END INTERFACE

INTERFACE BR_LOG10
  MODULE PROCEDURE BR_LOG10_RM
  MODULE PROCEDURE BR_LOG10_RD
END INTERFACE

INTERFACE BR_EXP
  MODULE PROCEDURE BR_EXP_RM
  MODULE PROCEDURE BR_EXP_RD
END INTERFACE

INTERFACE BR_ATAN2
  MODULE PROCEDURE BR_ATAN2_RM
  MODULE PROCEDURE BR_ATAN2_RD
END INTERFACE

INTERFACE BR_POW
  MODULE PROCEDURE BR_POWRR_RM
  MODULE PROCEDURE BR_POWRR_RD
  MODULE PROCEDURE BR_POWRN_RM
  MODULE PROCEDURE BR_POWRN_RD
  MODULE PROCEDURE BR_POWNN
END INTERFACE

INTERFACE BR_ERF
  MODULE PROCEDURE BR_ERF_RM
  MODULE PROCEDURE BR_ERF_RD
END INTERFACE

INTERFACE BR_ERFC
  MODULE PROCEDURE BR_ERFC_RM
  MODULE PROCEDURE BR_ERFC_RD
END INTERFACE

INTERFACE BR_GAMMA
  MODULE PROCEDURE BR_GAMMA_RM
  MODULE PROCEDURE BR_GAMMA_RD
END INTERFACE

INTERFACE BR_LOG_GAMMA
  MODULE PROCEDURE BR_LOG_GAMMA_RM
  MODULE PROCEDURE BR_LOG_GAMMA_RD
END INTERFACE

CONTAINS

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_SIN_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_SIN_RM = BR_SIN_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_COS_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_COS_RM = BR_COS_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_TAN_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_TAN_RM = BR_TAN_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_ASIN_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_ASIN_RM = BR_ASIN_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_ACOS_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_ACOS_RM = BR_ACOS_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_ATAN_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_ATAN_RM = BR_ATAN_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_SINH_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_SINH_RM = BR_SINH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_COSH_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_COSH_RM = BR_COSH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_TANH_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_TANH_RM = BR_TANH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_ASINH_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_ASINH_RM = BR_ASINH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_ACOSH_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_ACOSH_RM = BR_ACOSH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_ATANH_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_ATANH_RM = BR_ATANH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_LOG_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_LOG_RM = BR_LOG_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_LOG10_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_LOG10_RM = BR_LOG_C(REAL(P,KIND=C_DOUBLE))/BR_LOG_C(REAL(10.,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_EXP_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_EXP_RM = BR_EXP_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_ERF_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_ERF_RM = BR_ERF_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_ERFC_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_ERFC_RM = BR_ERFC_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_GAMMA_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_GAMMA_RM = BR_GAMMA_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_LOG_GAMMA_RM(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: P
BR_LOG_GAMMA_RM = BR_LOG_GAMMA_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_SIN_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_SIN_RD = BR_SIN_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_COS_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_COS_RD = BR_COS_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_TAN_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_TAN_RD = BR_TAN_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_ASIN_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_ASIN_RD = BR_ASIN_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_ACOS_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_ACOS_RD = BR_ACOS_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_ATAN_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_ATAN_RD = BR_ATAN_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_SINH_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_SINH_RD = BR_SINH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_COSH_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_COSH_RD = BR_COSH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_TANH_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_TANH_RD = BR_TANH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_ASINH_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_ASINH_RD = BR_ASINH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_ACOSH_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_ACOSH_RD = BR_ACOSH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_ATANH_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_ATANH_RD = BR_ATANH_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_LOG_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_LOG_RD = BR_LOG_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_LOG10_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_LOG10_RD = BR_LOG_C(REAL(P,KIND=C_DOUBLE))/BR_LOG_C(REAL(10.,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_EXP_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_EXP_RD = BR_EXP_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_ERF_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_ERF_RD = BR_ERF_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_ERFC_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_ERFC_RD = BR_ERFC_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_GAMMA_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_GAMMA_RD = BR_GAMMA_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_LOG_GAMMA_RD(P)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: P
BR_LOG_GAMMA_RD = BR_LOG_GAMMA_C(REAL(P,KIND=C_DOUBLE))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_ATAN2_RM (PA, PB)
!$ACC ROUTINE SEQ

REAL (KIND=JPRM), INTENT(IN) :: PA, PB

REAL (KIND=JPRD) , PARAMETER :: PI = 3.1415926535897932384626433832795_JPRD

IF (PB > 0.0) THEN 
  BR_ATAN2_RM = BR_ATAN(PA/PB)
ELSE IF ((PB < 0.0_JPRM) .AND. (PA >= 0.0_JPRM)) THEN
  BR_ATAN2_RM = BR_ATAN(PA/PB) + PI
ELSE IF ((PB < 0.0_JPRM) .AND. (PA < 0.0_JPRM)) THEN
  BR_ATAN2_RM = BR_ATAN(PA/PB) - PI
ELSE IF ((PB == 0.0_JPRM) .AND. (PA > 0.0_JPRM)) THEN
  BR_ATAN2_RM = PI / 2.0_JPRM 
ELSE IF ((PB == 0.0_JPRM) .AND. (PA < 0.0_JPRM)) THEN
  BR_ATAN2_RM = 0.0_JPRM - (PI / 2.0_JPRM)
ELSE IF ((PB == 0.0_JPRM) .AND. (PA == 0.0_JPRM)) THEN
  BR_ATAN2_RM = 0.0_JPRM
END IF

END FUNCTION BR_ATAN2_RM

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_POWRR_RM(PVAL, PPOW)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: PVAL, PPOW
BR_POWRR_RM = BR_EXP (PPOW * BR_LOG (PVAL))
END FUNCTION

ELEMENTAL REAL (KIND=JPRM) FUNCTION BR_POWRN_RM(PVAL, KPOW)
!$ACC ROUTINE SEQ
REAL (KIND=JPRM), INTENT(IN) :: PVAL
INTEGER, INTENT (IN) :: KPOW
INTEGER :: J
BR_POWRN_RM = 1._JPRM
DO J = 1, KPOW
  BR_POWRN_RM = BR_POWRN_RM * PVAL
ENDDO
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_ATAN2_RD (PA, PB)
!$ACC ROUTINE SEQ

REAL (KIND=JPRD), INTENT(IN) :: PA, PB

REAL (KIND=JPRD) , PARAMETER :: PI = 3.1415926535897932384626433832795_JPRD

IF (PB > 0.0) THEN 
  BR_ATAN2_RD = BR_ATAN(PA/PB)
ELSE IF ((PB < 0.0_JPRD) .AND. (PA >= 0.0_JPRD)) THEN
  BR_ATAN2_RD = BR_ATAN(PA/PB) + PI
ELSE IF ((PB < 0.0_JPRD) .AND. (PA < 0.0_JPRD)) THEN
  BR_ATAN2_RD = BR_ATAN(PA/PB) - PI
ELSE IF ((PB == 0.0_JPRD) .AND. (PA > 0.0_JPRD)) THEN
  BR_ATAN2_RD = PI / 2.0_JPRD 
ELSE IF ((PB == 0.0_JPRD) .AND. (PA < 0.0_JPRD)) THEN
  BR_ATAN2_RD = 0.0_JPRD - (PI / 2.0_JPRD)
ELSE IF ((PB == 0.0_JPRD) .AND. (PA == 0.0_JPRD)) THEN
  BR_ATAN2_RD = 0.0_JPRD
END IF

END FUNCTION BR_ATAN2_RD

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_POWRR_RD(PVAL, PPOW)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: PVAL, PPOW
BR_POWRR_RD = BR_EXP (PPOW * BR_LOG (PVAL))
END FUNCTION

ELEMENTAL REAL (KIND=JPRD) FUNCTION BR_POWRN_RD(PVAL, KPOW)
!$ACC ROUTINE SEQ
REAL (KIND=JPRD), INTENT(IN) :: PVAL
INTEGER, INTENT (IN) :: KPOW
INTEGER :: J
BR_POWRN_RD = 1._JPRD
DO J = 1, KPOW
  BR_POWRN_RD = BR_POWRN_RD * PVAL
ENDDO
END FUNCTION

ELEMENTAL INTEGER FUNCTION BR_POWNN (KVAL, KPOW)
!$ACC ROUTINE SEQ
INTEGER, INTENT(IN) :: KVAL, KPOW
INTEGER :: J
BR_POWNN = 1
DO J = 1, KPOW
  BR_POWNN = BR_POWNN * KVAL
ENDDO
END FUNCTION

END MODULE
