MODULE FXTRAN_ACDC_GEMV_MOD_SINGLEBLOCK

!
! Copyright 2025 Meteo-France
! All rights reserved
! philippe.marguinaud@meteo.fr
!

IMPLICIT NONE

PRIVATE

PUBLIC :: FXTRAN_ACDC_GEMV_SINGLEBLOCK

CONTAINS

SUBROUTINE FXTRAN_ACDC_GEMV_SINGLEBLOCK (KIDIA, KFDIA, TRANSA, TRANSB, M, N, K, ALPHA, A, &
                                       & LDA, B, LDB, BETA, C, LDC, LDDONE, LDACC)

USE FXTRAN_ACDC_BLAS_MOD
USE FXTRAN_ACDC_ABORT_MOD

                                ! VERINTS
INTEGER     :: KIDIA
INTEGER     :: KFDIA
CHARACTER*1 :: TRANSA           ! 'N'
CHARACTER*1 :: TRANSB           ! 'T'
INTEGER     :: M                ! KPROMA
INTEGER     :: N                ! 1
INTEGER     :: K                ! KLEVIN
REAL*8      :: ALPHA            ! 1.0_JPRD
REAL*8      :: A (:, :)         ! ZIN
INTEGER     :: LDA              ! KPROMA
REAL*8      :: B (:, :)         ! PINTE
INTEGER     :: LDB              ! KLEVOUT
REAL*8      :: BETA             ! 0.0_JPRB
REAL*8      :: C (:)            ! POUTS
INTEGER     :: LDC              ! KPROMA
LOGICAL     :: LDDONE
LOGICAL     :: LDACC

INTEGER :: JM, JN, JK
CHARACTER (LEN=*), PARAMETER :: CLNAME = 'FXTRAN_ACDC_GEMV'

IF (TRANSA /= 'N') CALL FXTRAN_ACDC_ABORT (CLNAME)
IF (TRANSB /= 'T') CALL FXTRAN_ACDC_ABORT (CLNAME)

CALL FXTRAN_ACDC_CHECKCONTIGUOUS (A, CLNAME)
CALL FXTRAN_ACDC_CHECKCONTIGUOUS (B, CLNAME)
CALL FXTRAN_ACDC_CHECKCONTIGUOUS (C, CLNAME)

IF (LDA /= SIZE (A, 1)) CALL FXTRAN_ACDC_ABORT (CLNAME)
IF (LDB /= SIZE (B, 1)) CALL FXTRAN_ACDC_ABORT (CLNAME)
IF (LDC /= SIZE (C, 1)) CALL FXTRAN_ACDC_ABORT (CLNAME)
IF (KIDIA /= 1) CALL FXTRAN_ACDC_ABORT (CLNAME)
IF (ALPHA /= 1._8) CALL FXTRAN_ACDC_ABORT (CLNAME)
IF (BETA /= 0._8) CALL FXTRAN_ACDC_ABORT (CLNAME)

IF (USE_SIMPLE_DGEMM ()) THEN

#ifdef _FXTRAN_USE_OPENACC
!$ACC PARALLEL LOOP GANG VECTOR PRESENT (A, B, C) PRIVATE (JK, JN, JM) IF(LDACC) 
#endif

  DO JM = KIDIA, KFDIA
    C (JM) = 0.
    DO JK = 1, K
      C (JM) = C (JM) + B (LDB , JK) * A (JM, JK)
    ENDDO
  ENDDO

ELSE

  IF (LDACC) THEN
#ifdef _FXTRAN_USE_CUBLAS
!$ACC DATA PRESENT (A, B, C)
!$ACC HOST_DATA USE_DEVICE (A, B, C)
    CALL CHECKCUBLAS (&
      & CUBLASDGEMM_V2 (GETCUHANDLE (), CUBLAS_OP_N, CUBLAS_OP_T, M, N, K, &
      &          ALPHA, A (1, 1),   LDA, &
      &                 B (LDB, 1), LDB, &
      &          BETA,  C (1),      LDC))
!$ACC END HOST_DATA
!$ACC END DATA

    CALL CHECKCUSTREAM
#endif
  ELSE
    CALL DGEMM ('N','T', M, N, K, ALPHA, A(1,1), LDA, B(LDB,1), LDB, BETA, C(1), LDC)
  ENDIF

ENDIF

LDDONE = .TRUE.

END SUBROUTINE

END MODULE
