SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_OMP_OPTS_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE CRC64_CPG_SURF_OMP_OPTS_TYPE (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (CPG_SURF_OMP_OPTS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YTO%CRC64 (KLUN, CDPATH//'%YTO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSO%CRC64 (KLUN, CDPATH//'%YSO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YUO%CRC64 (KLUN, CDPATH//'%YUO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVO%CRC64 (KLUN, CDPATH//'%YVO'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
