SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_VHD_OPTS_TYPE_LOAD_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE LOAD_CPG_SURF_VHD_OPTS_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (CPG_SURF_VHD_OPTS_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SELF%YTCCH%LOAD (KLUN)
CALL SELF%YSCCH%LOAD (KLUN)
CALL SELF%YBCCH%LOAD (KLUN)
CALL SELF%YPBLH%LOAD (KLUN)
CALL SELF%YSPSH%LOAD (KLUN)
CALL SELF%YQSH%LOAD (KLUN)
CALL SELF%YPCL%LOAD (KLUN)
CALL SELF%YPSL%LOAD (KLUN)
CALL SELF%YPCN%LOAD (KLUN)
CALL SELF%YPSN%LOAD (KLUN)
CALL SELF%YEVA%LOAD (KLUN)
END SUBROUTINE


END SUBMODULE
