SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_SBP_OPTS_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE HOST_CPG_SURF_SBP_OPTS_TYPE (SELF)

IMPLICIT NONE
CLASS (CPG_SURF_SBP_OPTS_TYPE), TARGET :: SELF

CALL SELF%YT%HOST ()

CALL SELF%YQ%HOST ()

CALL SELF%YTL%HOST ()

END SUBROUTINE

END SUBMODULE
