SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_VDD_OPTS_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE CRC64_CPG_SURF_VDD_OPTS_TYPE (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (CPG_SURF_VDD_OPTS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YLSP%CRC64 (KLUN, CDPATH//'%YLSP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCP%CRC64 (KLUN, CDPATH//'%YCP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSF%CRC64 (KLUN, CDPATH//'%YSF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YFZRA%CRC64 (KLUN, CDPATH//'%YFZRA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YBLD%CRC64 (KLUN, CDPATH//'%YBLD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSHF%CRC64 (KLUN, CDPATH//'%YSSHF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSLHF%CRC64 (KLUN, CDPATH//'%YSLHF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YNEE%CRC64 (KLUN, CDPATH//'%YNEE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YGPP%CRC64 (KLUN, CDPATH//'%YGPP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YREC%CRC64 (KLUN, CDPATH//'%YREC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMSL%CRC64 (KLUN, CDPATH//'%YMSL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSP%CRC64 (KLUN, CDPATH//'%YSP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCC%CRC64 (KLUN, CDPATH//'%YTCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10U%CRC64 (KLUN, CDPATH//'%Y10U'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10V%CRC64 (KLUN, CDPATH//'%Y10V'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y2T%CRC64 (KLUN, CDPATH//'%Y2T'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y2D%CRC64 (KLUN, CDPATH//'%Y2D'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y2SH%CRC64 (KLUN, CDPATH//'%Y2SH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSR%CRC64 (KLUN, CDPATH//'%YSSR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTR%CRC64 (KLUN, CDPATH//'%YSTR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTSR%CRC64 (KLUN, CDPATH//'%YTSR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTTR%CRC64 (KLUN, CDPATH//'%YTTR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YEWSS%CRC64 (KLUN, CDPATH//'%YEWSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YNSSS%CRC64 (KLUN, CDPATH//'%YNSSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YE%CRC64 (KLUN, CDPATH//'%YE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YPEV%CRC64 (KLUN, CDPATH//'%YPEV'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCCC%CRC64 (KLUN, CDPATH//'%YCCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLCC%CRC64 (KLUN, CDPATH//'%YLCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMCC%CRC64 (KLUN, CDPATH//'%YMCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YHCC%CRC64 (KLUN, CDPATH//'%YHCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLGWS%CRC64 (KLUN, CDPATH//'%YLGWS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMGWS%CRC64 (KLUN, CDPATH//'%YMGWS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YGWD%CRC64 (KLUN, CDPATH//'%YGWD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMX2T%CRC64 (KLUN, CDPATH//'%YMX2T'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMN2T%CRC64 (KLUN, CDPATH//'%YMN2T'//TRIM(CLIND))

CLIND = ''
CALL SELF%YRO%CRC64 (KLUN, CDPATH//'%YRO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSRO%CRC64 (KLUN, CDPATH//'%YSRO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSRO%CRC64 (KLUN, CDPATH//'%YSSRO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YALB%CRC64 (KLUN, CDPATH//'%YALB'//TRIM(CLIND))

CLIND = ''
CALL SELF%YIEWSS%CRC64 (KLUN, CDPATH//'%YIEWSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YINSSS%CRC64 (KLUN, CDPATH//'%YINSSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YISSHF%CRC64 (KLUN, CDPATH//'%YISSHF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YIE%CRC64 (KLUN, CDPATH//'%YIE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YINEE%CRC64 (KLUN, CDPATH//'%YINEE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YIGPP%CRC64 (KLUN, CDPATH//'%YIGPP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YIREC%CRC64 (KLUN, CDPATH//'%YIREC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YICH4%CRC64 (KLUN, CDPATH//'%YICH4'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCSF%CRC64 (KLUN, CDPATH//'%YCSF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLSSF%CRC64 (KLUN, CDPATH//'%YLSSF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMXTPR%CRC64 (KLUN, CDPATH//'%YMXTPR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMNTPR%CRC64 (KLUN, CDPATH//'%YMNTPR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTPR%CRC64 (KLUN, CDPATH//'%YTPR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLSRR%CRC64 (KLUN, CDPATH//'%YLSRR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCRR%CRC64 (KLUN, CDPATH//'%YCRR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLSSFR%CRC64 (KLUN, CDPATH//'%YLSSFR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCSFR%CRC64 (KLUN, CDPATH//'%YCSFR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YPTYPE%CRC64 (KLUN, CDPATH//'%YPTYPE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YILSPF%CRC64 (KLUN, CDPATH//'%YILSPF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZ0F%CRC64 (KLUN, CDPATH//'%YZ0F'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLZ0H%CRC64 (KLUN, CDPATH//'%YLZ0H'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVIWVE%CRC64 (KLUN, CDPATH//'%YVIWVE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVIWVN%CRC64 (KLUN, CDPATH//'%YVIWVN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCW%CRC64 (KLUN, CDPATH//'%YTCW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCWV%CRC64 (KLUN, CDPATH//'%YTCWV'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCLW%CRC64 (KLUN, CDPATH//'%YTCLW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCIW%CRC64 (KLUN, CDPATH//'%YTCIW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCRW%CRC64 (KLUN, CDPATH//'%YTCRW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCSW%CRC64 (KLUN, CDPATH//'%YTCSW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCSLW%CRC64 (KLUN, CDPATH//'%YTCSLW'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSRD%CRC64 (KLUN, CDPATH//'%YSSRD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTRD%CRC64 (KLUN, CDPATH//'%YSTRD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSRDC%CRC64 (KLUN, CDPATH//'%YSSRDC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTRDC%CRC64 (KLUN, CDPATH//'%YSTRDC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YBLH%CRC64 (KLUN, CDPATH//'%YBLH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSUND%CRC64 (KLUN, CDPATH//'%YSUND'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSPAR%CRC64 (KLUN, CDPATH//'%YSPAR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSUVB%CRC64 (KLUN, CDPATH//'%YSUVB'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSFDIR%CRC64 (KLUN, CDPATH//'%YSFDIR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSCDIR%CRC64 (KLUN, CDPATH//'%YSCDIR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSDSRP%CRC64 (KLUN, CDPATH//'%YSDSRP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCAPE%CRC64 (KLUN, CDPATH//'%YCAPE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMUCAPE%CRC64 (KLUN, CDPATH//'%YMUCAPE'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMLCAPE50%CRC64 (KLUN, CDPATH//'%YMLCAPE50'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMLCAPE100%CRC64 (KLUN, CDPATH//'%YMLCAPE100'//TRIM(CLIND))

CLIND = ''
CALL SELF%YPDEPL%CRC64 (KLUN, CDPATH//'%YPDEPL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCAPES%CRC64 (KLUN, CDPATH//'%YCAPES'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTROPOTP%CRC64 (KLUN, CDPATH//'%YTROPOTP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTSRC%CRC64 (KLUN, CDPATH//'%YTSRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTTRC%CRC64 (KLUN, CDPATH//'%YTTRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSRC%CRC64 (KLUN, CDPATH//'%YSSRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTRC%CRC64 (KLUN, CDPATH//'%YSTRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YES%CRC64 (KLUN, CDPATH//'%YES'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSMLT%CRC64 (KLUN, CDPATH//'%YSMLT'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10FG%CRC64 (KLUN, CDPATH//'%Y10FG'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10FGCV%CRC64 (KLUN, CDPATH//'%Y10FGCV'//TRIM(CLIND))

CLIND = ''
CALL SELF%YI10FG%CRC64 (KLUN, CDPATH//'%YI10FG'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLSPF%CRC64 (KLUN, CDPATH//'%YLSPF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTCO3%CRC64 (KLUN, CDPATH//'%YTCO3'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVIMD%CRC64 (KLUN, CDPATH//'%YVIMD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSPARC%CRC64 (KLUN, CDPATH//'%YSPARC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSTINC%CRC64 (KLUN, CDPATH//'%YSTINC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCBASE%CRC64 (KLUN, CDPATH//'%YCBASE'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y0DEGL%CRC64 (KLUN, CDPATH//'%Y0DEGL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YM10DEGL%CRC64 (KLUN, CDPATH//'%YM10DEGL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVISIH%CRC64 (KLUN, CDPATH//'%YVISIH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCIN%CRC64 (KLUN, CDPATH//'%YCIN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMLCIN50%CRC64 (KLUN, CDPATH//'%YMLCIN50'//TRIM(CLIND))

CLIND = ''
CALL SELF%YMLCIN100%CRC64 (KLUN, CDPATH//'%YMLCIN100'//TRIM(CLIND))

CLIND = ''
CALL SELF%YKINDEX%CRC64 (KLUN, CDPATH//'%YKINDEX'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTTINDEX%CRC64 (KLUN, CDPATH//'%YTTINDEX'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCBASEA%CRC64 (KLUN, CDPATH//'%YCBASEA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCTOPC%CRC64 (KLUN, CDPATH//'%YCTOPC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZTWETB0%CRC64 (KLUN, CDPATH//'%YZTWETB0'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZTWETB1%CRC64 (KLUN, CDPATH//'%YZTWETB1'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y100U%CRC64 (KLUN, CDPATH//'%Y100U'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y100V%CRC64 (KLUN, CDPATH//'%Y100V'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y200U%CRC64 (KLUN, CDPATH//'%Y200U'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y200V%CRC64 (KLUN, CDPATH//'%Y200V'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZUST%CRC64 (KLUN, CDPATH//'%YZUST'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10NU%CRC64 (KLUN, CDPATH//'%Y10NU'//TRIM(CLIND))

CLIND = ''
CALL SELF%Y10NV%CRC64 (KLUN, CDPATH//'%Y10NV'//TRIM(CLIND))

CLIND = ''
CALL SELF%YDNDZN%CRC64 (KLUN, CDPATH//'%YDNDZN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YDNDZA%CRC64 (KLUN, CDPATH//'%YDNDZA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YDCTB%CRC64 (KLUN, CDPATH//'%YDCTB'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTPLB%CRC64 (KLUN, CDPATH//'%YTPLB'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTPLT%CRC64 (KLUN, CDPATH//'%YTPLT'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODSS%CRC64 (KLUN, CDPATH//'%YODSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODDU%CRC64 (KLUN, CDPATH//'%YODDU'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODOM%CRC64 (KLUN, CDPATH//'%YODOM'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODBC%CRC64 (KLUN, CDPATH//'%YODBC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODSU%CRC64 (KLUN, CDPATH//'%YODSU'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODNI%CRC64 (KLUN, CDPATH//'%YODNI'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODAM%CRC64 (KLUN, CDPATH//'%YODAM'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODSOA%CRC64 (KLUN, CDPATH//'%YODSOA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODVFA%CRC64 (KLUN, CDPATH//'%YODVFA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODVSU%CRC64 (KLUN, CDPATH//'%YODVSU'//TRIM(CLIND))

CLIND = ''
CALL SELF%YODTOACC%CRC64 (KLUN, CDPATH//'%YODTOACC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YAEPM1%CRC64 (KLUN, CDPATH//'%YAEPM1'//TRIM(CLIND))

CLIND = ''
CALL SELF%YAEPM25%CRC64 (KLUN, CDPATH//'%YAEPM25'//TRIM(CLIND))

CLIND = ''
CALL SELF%YAEPM10%CRC64 (KLUN, CDPATH//'%YAEPM10'//TRIM(CLIND))

CLIND = ''
CALL SELF%YUVBED%CRC64 (KLUN, CDPATH//'%YUVBED'//TRIM(CLIND))

CLIND = ''
CALL SELF%YUVBEDCS%CRC64 (KLUN, CDPATH//'%YUVBEDCS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLITOTI%CRC64 (KLUN, CDPATH//'%YLITOTI'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLICGI%CRC64 (KLUN, CDPATH//'%YLICGI'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
