SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_VFD_OPTS_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_CPG_SURF_VFD_OPTS_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (CPG_SURF_VFD_OPTS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YZ0F%ACDC_CRC64 (KLUN, CDPATH//'%YZ0F'//TRIM(CLIND))

CLIND = ''
CALL SELF%YALBF%ACDC_CRC64 (KLUN, CDPATH//'%YALBF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YEMISF%ACDC_CRC64 (KLUN, CDPATH//'%YEMISF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YGETRL%ACDC_CRC64 (KLUN, CDPATH//'%YGETRL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLSM%ACDC_CRC64 (KLUN, CDPATH//'%YLSM'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVEG%ACDC_CRC64 (KLUN, CDPATH//'%YVEG'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVRLAN%ACDC_CRC64 (KLUN, CDPATH//'%YVRLAN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVRLDI%ACDC_CRC64 (KLUN, CDPATH//'%YVRLDI'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSIG%ACDC_CRC64 (KLUN, CDPATH//'%YSIG'//TRIM(CLIND))

CLIND = ''
CALL SELF%YALBSF%ACDC_CRC64 (KLUN, CDPATH//'%YALBSF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLAN%ACDC_CRC64 (KLUN, CDPATH//'%YLAN'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSST%ACDC_CRC64 (KLUN, CDPATH//'%YSST'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSSS%ACDC_CRC64 (KLUN, CDPATH//'%YSSS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLZ0H%ACDC_CRC64 (KLUN, CDPATH//'%YLZ0H'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCVL%ACDC_CRC64 (KLUN, CDPATH//'%YCVL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCO2TYP%ACDC_CRC64 (KLUN, CDPATH//'%YCO2TYP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCVH%ACDC_CRC64 (KLUN, CDPATH//'%YCVH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCUR%ACDC_CRC64 (KLUN, CDPATH//'%YCUR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTVL%ACDC_CRC64 (KLUN, CDPATH//'%YTVL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YTVH%ACDC_CRC64 (KLUN, CDPATH//'%YTVH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLAIL%ACDC_CRC64 (KLUN, CDPATH//'%YLAIL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YLAIH%ACDC_CRC64 (KLUN, CDPATH//'%YLAIH'//TRIM(CLIND))

CLIND = ''
CALL SELF%YFWET%ACDC_CRC64 (KLUN, CDPATH//'%YFWET'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSOTY%ACDC_CRC64 (KLUN, CDPATH//'%YSOTY'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCLK%ACDC_CRC64 (KLUN, CDPATH//'%YCLK'//TRIM(CLIND))

CLIND = ''
CALL SELF%YDL%ACDC_CRC64 (KLUN, CDPATH//'%YDL'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCI%ACDC_CRC64 (KLUN, CDPATH//'%YCI'//TRIM(CLIND))

CLIND = ''
CALL SELF%YUCUR%ACDC_CRC64 (KLUN, CDPATH//'%YUCUR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YVCUR%ACDC_CRC64 (KLUN, CDPATH//'%YVCUR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YZ0RLF%ACDC_CRC64 (KLUN, CDPATH//'%YZ0RLF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCGPP%ACDC_CRC64 (KLUN, CDPATH//'%YCGPP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YCREC%ACDC_CRC64 (KLUN, CDPATH//'%YCREC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSDFOR%ACDC_CRC64 (KLUN, CDPATH//'%YSDFOR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YALUVP%ACDC_CRC64 (KLUN, CDPATH//'%YALUVP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YALUVD%ACDC_CRC64 (KLUN, CDPATH//'%YALUVD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YALNIP%ACDC_CRC64 (KLUN, CDPATH//'%YALNIP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YALNID%ACDC_CRC64 (KLUN, CDPATH//'%YALNID'//TRIM(CLIND))

CLIND = ''
CALL SELF%YFP1%ACDC_CRC64 (KLUN, CDPATH//'%YFP1'//TRIM(CLIND))

CLIND = ''
CALL SELF%YSO2DD%ACDC_CRC64 (KLUN, CDPATH//'%YSO2DD'//TRIM(CLIND))

CLIND = ''
CALL SELF%YDMSO%ACDC_CRC64 (KLUN, CDPATH//'%YDMSO'//TRIM(CLIND))

CLIND = ''
CALL SELF%YURBF%ACDC_CRC64 (KLUN, CDPATH//'%YURBF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YFCA1%ACDC_CRC64 (KLUN, CDPATH//'%YFCA1'//TRIM(CLIND))

CLIND = ''
CALL SELF%YFCA2%ACDC_CRC64 (KLUN, CDPATH//'%YFCA2'//TRIM(CLIND))

CLIND = ''
CALL SELF%YAERDEP%ACDC_CRC64 (KLUN, CDPATH//'%YAERDEP'//TRIM(CLIND))

CLIND = ''
CALL SELF%YAERLTS%ACDC_CRC64 (KLUN, CDPATH//'%YAERLTS'//TRIM(CLIND))

CLIND = ''
CALL SELF%YAERSCC%ACDC_CRC64 (KLUN, CDPATH//'%YAERSCC'//TRIM(CLIND))

CLIND = ''
CALL SELF%YDSF%ACDC_CRC64 (KLUN, CDPATH//'%YDSF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YNUDM%ACDC_CRC64 (KLUN, CDPATH//'%YNUDM'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
