SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_V2D_OPTS_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_CPG_SURF_V2D_OPTS_TYPE (SELF)

IMPLICIT NONE
CLASS (CPG_SURF_V2D_OPTS_TYPE), TARGET :: SELF

CALL SELF%YOCDEP%ACDC_HOST ()

CALL SELF%YUSTRC%ACDC_HOST ()

CALL SELF%YVSTRC%ACDC_HOST ()

END SUBROUTINE

END SUBMODULE
