SUBMODULE (CPG_GFL_TYPE_MOD) CPG_GFL_TYPE_MOD_CPG_GFL_3D_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_CPG_GFL_3D_TYPE (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (CPG_GFL_3D_TYPE), TARGET :: SELF
LOGICAL :: LF_P
LF_P = ASSOCIATED (SELF%F_P)
IF (LF_P) THEN
  CALL HOST_FIELD_3RB (SELF%F_P)
ENDIF

END SUBROUTINE

END SUBMODULE
