SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_VND_OPTS_TYPE_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_SAVE_CPG_SURF_VND_OPTS_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (CPG_SURF_VND_OPTS_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SELF%YTOP%ACDC_SAVE (KLUN)
CALL SELF%YBAS%ACDC_SAVE (KLUN)
CALL SELF%YACPR%ACDC_SAVE (KLUN)
CALL SELF%YACCPR%ACDC_SAVE (KLUN)
CALL SELF%YACCPR5%ACDC_SAVE (KLUN)
END SUBROUTINE

END SUBMODULE
