SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_SGP_OPTS_TYPE_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_CPG_SURF_SGP_OPTS_TYPE (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (CPG_SURF_SGP_OPTS_TYPE), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
CLIND = ''
CALL SELF%YF%ACDC_CRC64 (KLUN, CDPATH//'%YF'//TRIM(CLIND))

CLIND = ''
CALL SELF%YA%ACDC_CRC64 (KLUN, CDPATH//'%YA'//TRIM(CLIND))

CLIND = ''
CALL SELF%YR%ACDC_CRC64 (KLUN, CDPATH//'%YR'//TRIM(CLIND))

CLIND = ''
CALL SELF%YT%ACDC_CRC64 (KLUN, CDPATH//'%YT'//TRIM(CLIND))

CLIND = ''
CALL SELF%YW%ACDC_CRC64 (KLUN, CDPATH//'%YW'//TRIM(CLIND))

END SUBROUTINE

END SUBMODULE
