SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_V2D_OPTS_TYPE_SAVE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE SAVE_CPG_SURF_V2D_OPTS_TYPE (SELF, KLUN)

IMPLICIT NONE
CLASS (CPG_SURF_V2D_OPTS_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL SELF%YOCDEP%SAVE (KLUN)
CALL SELF%YUSTRC%SAVE (KLUN)
CALL SELF%YVSTRC%SAVE (KLUN)
END SUBROUTINE

END SUBMODULE
