SUBMODULE (CPG_OPTS_TYPE_MOD) CPG_OPTS_TYPE_MOD_CPG_SURF_SLP_OPTS_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_CPG_SURF_SLP_OPTS_TYPE (SELF)

IMPLICIT NONE
CLASS (CPG_SURF_SLP_OPTS_TYPE), TARGET :: SELF

CALL SELF%YLICT%ACDC_HOST ()

CALL SELF%YLMLT%ACDC_HOST ()

CALL SELF%YLTLT%ACDC_HOST ()

CALL SELF%YLBLT%ACDC_HOST ()

CALL SELF%YLSHF%ACDC_HOST ()

CALL SELF%YLICD%ACDC_HOST ()

CALL SELF%YLMLD%ACDC_HOST ()

END SUBROUTINE

END SUBMODULE
