SUBMODULE (CPG_DDH_TND_TYPE_MOD) CPG_DDH_TND_TYPE_MOD_CPG_DDH_TND_TYPE_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_CPG_DDH_TND_TYPE (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (CPG_DDH_TND_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
CALL SELF%YSI%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YHD%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%YSL%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE

END SUBMODULE
