SUBMODULE (CPG_DDH_TND_TYPE_MOD) CPG_DDH_TND_TYPE_MOD_CPG_TNDHD_DDH_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_CPG_TNDHD_DDH_TYPE (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (CPG_TNDHD_DDH_TYPE), TARGET :: SELF
LOGICAL :: LF_NHX, LF_PD, LF_Q, LF_T, LF_U, LF_V, LF_VD, LZDATA_GFL, LZDATA_GMV, LZVIEW_GFL
LOGICAL :: LZVIEW_GMV

LF_U = ASSOCIATED (SELF%F_U)
IF (LF_U) THEN
  CALL HOST_FIELD_3RB (SELF%F_U)
ENDIF

LF_V = ASSOCIATED (SELF%F_V)
IF (LF_V) THEN
  CALL HOST_FIELD_3RB (SELF%F_V)
ENDIF

LF_T = ASSOCIATED (SELF%F_T)
IF (LF_T) THEN
  CALL HOST_FIELD_3RB (SELF%F_T)
ENDIF

LF_PD = ASSOCIATED (SELF%F_PD)
IF (LF_PD) THEN
  CALL HOST_FIELD_3RB (SELF%F_PD)
ENDIF

LF_VD = ASSOCIATED (SELF%F_VD)
IF (LF_VD) THEN
  CALL HOST_FIELD_3RB (SELF%F_VD)
ENDIF

LF_NHX = ASSOCIATED (SELF%F_NHX)
IF (LF_NHX) THEN
  CALL HOST_FIELD_3RB (SELF%F_NHX)
ENDIF

LF_Q = ASSOCIATED (SELF%F_Q)
IF (LF_Q) THEN
  CALL HOST_FIELD_3RB (SELF%F_Q)
ENDIF

END SUBROUTINE

END SUBMODULE
