SUBMODULE (FIELD_VARIABLES_MOD) FIELD_VARIABLES_MOD_FIELD_VARIABLES_CRC64_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_CRC64_FIELD_VARIABLES (SELF, KLUN, CDPATH)
USE FXTRAN_ACDC_CRC64_INTRINSIC_MOD, ONLY : FCRC64 => FXTRAN_ACDC_CRC64
IMPLICIT NONE
CLASS (FIELD_VARIABLES), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
INTEGER :: J1
LOGICAL :: LAERAOT, LAERLISI, LAERO, LAEROCLIM, LAEROUT, LCHEM, LEDRP, LEMIS3D, LERA40, LEXT
LOGICAL :: LEZDIAG, LFORC, LGFL_PTR, LGHG, LLIMA, LNOGW, LSLDIA, LUVP
CLIND = ''
CALL SELF%U%ACDC_CRC64 (KLUN, CDPATH//'%U'//TRIM(CLIND))

CLIND = ''
CALL SELF%V%ACDC_CRC64 (KLUN, CDPATH//'%V'//TRIM(CLIND))

CLIND = ''
CALL SELF%T%ACDC_CRC64 (KLUN, CDPATH//'%T'//TRIM(CLIND))

CLIND = ''
CALL SELF%DIV%ACDC_CRC64 (KLUN, CDPATH//'%DIV'//TRIM(CLIND))

CLIND = ''
CALL SELF%VOR%ACDC_CRC64 (KLUN, CDPATH//'%VOR'//TRIM(CLIND))

CLIND = ''
CALL SELF%SPD%ACDC_CRC64 (KLUN, CDPATH//'%SPD'//TRIM(CLIND))

CLIND = ''
CALL SELF%SVD%ACDC_CRC64 (KLUN, CDPATH//'%SVD'//TRIM(CLIND))

CLIND = ''
CALL SELF%CSPDNL%ACDC_CRC64 (KLUN, CDPATH//'%CSPDNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%CSPNL%ACDC_CRC64 (KLUN, CDPATH//'%CSPNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%CSVDPT%ACDC_CRC64 (KLUN, CDPATH//'%CSVDPT'//TRIM(CLIND))

CLIND = ''
CALL SELF%CTNL%ACDC_CRC64 (KLUN, CDPATH//'%CTNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%CTPT%ACDC_CRC64 (KLUN, CDPATH//'%CTPT'//TRIM(CLIND))

CLIND = ''
CALL SELF%CUNL%ACDC_CRC64 (KLUN, CDPATH//'%CUNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%CUPT%ACDC_CRC64 (KLUN, CDPATH//'%CUPT'//TRIM(CLIND))

CLIND = ''
CALL SELF%CVNL%ACDC_CRC64 (KLUN, CDPATH//'%CVNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%CVPT%ACDC_CRC64 (KLUN, CDPATH//'%CVPT'//TRIM(CLIND))

CLIND = ''
CALL SELF%CVWVNL%ACDC_CRC64 (KLUN, CDPATH//'%CVWVNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%DPHI%ACDC_CRC64 (KLUN, CDPATH//'%DPHI'//TRIM(CLIND))

CLIND = ''
CALL SELF%EDOT%ACDC_CRC64 (KLUN, CDPATH//'%EDOT'//TRIM(CLIND))

CLIND = ''
CALL SELF%GW%ACDC_CRC64 (KLUN, CDPATH//'%GW'//TRIM(CLIND))

CLIND = ''
CALL SELF%NHX%ACDC_CRC64 (KLUN, CDPATH//'%NHX'//TRIM(CLIND))

CLIND = ''
CALL SELF%NHY%ACDC_CRC64 (KLUN, CDPATH//'%NHY'//TRIM(CLIND))

CLIND = ''
CALL SELF%SGRTL%ACDC_CRC64 (KLUN, CDPATH//'%SGRTL'//TRIM(CLIND))

CLIND = ''
CALL SELF%SGRTM%ACDC_CRC64 (KLUN, CDPATH//'%SGRTM'//TRIM(CLIND))

CLIND = ''
CALL SELF%SPDNL%ACDC_CRC64 (KLUN, CDPATH//'%SPDNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%SPDNL_SI%ACDC_CRC64 (KLUN, CDPATH//'%SPDNL_SI'//TRIM(CLIND))

CLIND = ''
CALL SELF%SPNL%ACDC_CRC64 (KLUN, CDPATH//'%SPNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%SPNL_SI%ACDC_CRC64 (KLUN, CDPATH//'%SPNL_SI'//TRIM(CLIND))

CLIND = ''
CALL SELF%SVDNL_SI%ACDC_CRC64 (KLUN, CDPATH//'%SVDNL_SI'//TRIM(CLIND))

CLIND = ''
CALL SELF%TNL%ACDC_CRC64 (KLUN, CDPATH//'%TNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%TNL_SI%ACDC_CRC64 (KLUN, CDPATH//'%TNL_SI'//TRIM(CLIND))

CLIND = ''
CALL SELF%UNL%ACDC_CRC64 (KLUN, CDPATH//'%UNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%UNL_SI%ACDC_CRC64 (KLUN, CDPATH//'%UNL_SI'//TRIM(CLIND))

CLIND = ''
CALL SELF%VNL%ACDC_CRC64 (KLUN, CDPATH//'%VNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%VNL_SI%ACDC_CRC64 (KLUN, CDPATH//'%VNL_SI'//TRIM(CLIND))

CLIND = ''
CALL SELF%VWVNL%ACDC_CRC64 (KLUN, CDPATH//'%VWVNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%CURHS%ACDC_CRC64 (KLUN, CDPATH//'%CURHS'//TRIM(CLIND))

CLIND = ''
CALL SELF%CVRHS%ACDC_CRC64 (KLUN, CDPATH//'%CVRHS'//TRIM(CLIND))

CLIND = ''
CALL SELF%CTRHS%ACDC_CRC64 (KLUN, CDPATH//'%CTRHS'//TRIM(CLIND))

CLIND = ''
CALL SELF%CSPDRHS%ACDC_CRC64 (KLUN, CDPATH//'%CSPDRHS'//TRIM(CLIND))

CLIND = ''
CALL SELF%CSVDRHS%ACDC_CRC64 (KLUN, CDPATH//'%CSVDRHS'//TRIM(CLIND))

CLIND = ''
CALL SELF%NHXNL%ACDC_CRC64 (KLUN, CDPATH//'%NHXNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%CNHXNL%ACDC_CRC64 (KLUN, CDPATH//'%CNHXNL'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_U%ACDC_CRC64 (KLUN, CDPATH//'%PCF_U'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_V%ACDC_CRC64 (KLUN, CDPATH//'%PCF_V'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_T%ACDC_CRC64 (KLUN, CDPATH//'%PCF_T'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_SPD%ACDC_CRC64 (KLUN, CDPATH//'%PCF_SPD'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_SVD%ACDC_CRC64 (KLUN, CDPATH//'%PCF_SVD'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_NHX%ACDC_CRC64 (KLUN, CDPATH//'%PCF_NHX'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_SP%ACDC_CRC64 (KLUN, CDPATH//'%PCF_SP'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_CP%ACDC_CRC64 (KLUN, CDPATH//'%PCF_CP'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_UP%ACDC_CRC64 (KLUN, CDPATH//'%PCF_UP'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_VP%ACDC_CRC64 (KLUN, CDPATH//'%PCF_VP'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_TP%ACDC_CRC64 (KLUN, CDPATH//'%PCF_TP'//TRIM(CLIND))

CLIND = ''
CALL SELF%SP%ACDC_CRC64 (KLUN, CDPATH//'%SP'//TRIM(CLIND))

CLIND = ''
CALL SELF%SPNL2%ACDC_CRC64 (KLUN, CDPATH//'%SPNL2'//TRIM(CLIND))

CLIND = ''
CALL SELF%PREHYDS%ACDC_CRC64 (KLUN, CDPATH//'%PREHYDS'//TRIM(CLIND))

CLIND = ''
CALL SELF%DBBC%ACDC_CRC64 (KLUN, CDPATH//'%DBBC'//TRIM(CLIND))

CLIND = ''
CALL SELF%CSPPT%ACDC_CRC64 (KLUN, CDPATH//'%CSPPT'//TRIM(CLIND))

CLIND = ''
CALL SELF%CSPNL2%ACDC_CRC64 (KLUN, CDPATH//'%CSPNL2'//TRIM(CLIND))

CLIND = ''
CALL SELF%CSPRHS%ACDC_CRC64 (KLUN, CDPATH//'%CSPRHS'//TRIM(CLIND))

CLIND = ''
CALL SELF%GWS%ACDC_CRC64 (KLUN, CDPATH//'%GWS'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_BBC%ACDC_CRC64 (KLUN, CDPATH//'%PCF_BBC'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_DPHI%ACDC_CRC64 (KLUN, CDPATH//'%PCF_DPHI'//TRIM(CLIND))

CLIND = ''
CALL SELF%PCF_GWS%ACDC_CRC64 (KLUN, CDPATH//'%PCF_GWS'//TRIM(CLIND))

CLIND = ''
CALL SELF%Q%ACDC_CRC64 (KLUN, CDPATH//'%Q'//TRIM(CLIND))

CLIND = ''
CALL SELF%I%ACDC_CRC64 (KLUN, CDPATH//'%I'//TRIM(CLIND))

CLIND = ''
CALL SELF%L%ACDC_CRC64 (KLUN, CDPATH//'%L'//TRIM(CLIND))

CLIND = ''
CALL SELF%IMF%ACDC_CRC64 (KLUN, CDPATH//'%IMF'//TRIM(CLIND))

CLIND = ''
CALL SELF%LMF%ACDC_CRC64 (KLUN, CDPATH//'%LMF'//TRIM(CLIND))

CLIND = ''
CALL SELF%LCONV%ACDC_CRC64 (KLUN, CDPATH//'%LCONV'//TRIM(CLIND))

CLIND = ''
CALL SELF%ICONV%ACDC_CRC64 (KLUN, CDPATH//'%ICONV'//TRIM(CLIND))

CLIND = ''
CALL SELF%RCONV%ACDC_CRC64 (KLUN, CDPATH//'%RCONV'//TRIM(CLIND))

CLIND = ''
CALL SELF%SCONV%ACDC_CRC64 (KLUN, CDPATH//'%SCONV'//TRIM(CLIND))

CLIND = ''
CALL SELF%IRAD%ACDC_CRC64 (KLUN, CDPATH//'%IRAD'//TRIM(CLIND))

CLIND = ''
CALL SELF%LRAD%ACDC_CRC64 (KLUN, CDPATH//'%LRAD'//TRIM(CLIND))

CLIND = ''
CALL SELF%S%ACDC_CRC64 (KLUN, CDPATH//'%S'//TRIM(CLIND))

CLIND = ''
CALL SELF%R%ACDC_CRC64 (KLUN, CDPATH//'%R'//TRIM(CLIND))

CLIND = ''
CALL SELF%G%ACDC_CRC64 (KLUN, CDPATH//'%G'//TRIM(CLIND))

CLIND = ''
CALL SELF%H%ACDC_CRC64 (KLUN, CDPATH//'%H'//TRIM(CLIND))

CLIND = ''
CALL SELF%TKE%ACDC_CRC64 (KLUN, CDPATH//'%TKE'//TRIM(CLIND))

CLIND = ''
CALL SELF%TTE%ACDC_CRC64 (KLUN, CDPATH//'%TTE'//TRIM(CLIND))

CLIND = ''
CALL SELF%EFB1%ACDC_CRC64 (KLUN, CDPATH//'%EFB1'//TRIM(CLIND))

CLIND = ''
CALL SELF%EFB2%ACDC_CRC64 (KLUN, CDPATH//'%EFB2'//TRIM(CLIND))

CLIND = ''
CALL SELF%EFB3%ACDC_CRC64 (KLUN, CDPATH//'%EFB3'//TRIM(CLIND))

CLIND = ''
CALL SELF%A%ACDC_CRC64 (KLUN, CDPATH//'%A'//TRIM(CLIND))

CLIND = ''
CALL SELF%AMF%ACDC_CRC64 (KLUN, CDPATH//'%AMF'//TRIM(CLIND))

CLIND = ''
CALL SELF%O3%ACDC_CRC64 (KLUN, CDPATH//'%O3'//TRIM(CLIND))

CLIND = ''
CALL SELF%SRC%ACDC_CRC64 (KLUN, CDPATH//'%SRC'//TRIM(CLIND))

CLIND = ''
CALL SELF%MXL%ACDC_CRC64 (KLUN, CDPATH//'%MXL'//TRIM(CLIND))

CLIND = ''
CALL SELF%SHTUR%ACDC_CRC64 (KLUN, CDPATH//'%SHTUR'//TRIM(CLIND))

CLIND = ''
CALL SELF%FQTUR%ACDC_CRC64 (KLUN, CDPATH//'%FQTUR'//TRIM(CLIND))

CLIND = ''
CALL SELF%FSTUR%ACDC_CRC64 (KLUN, CDPATH//'%FSTUR'//TRIM(CLIND))

CLIND = ''
CALL SELF%CPF%ACDC_CRC64 (KLUN, CDPATH//'%CPF'//TRIM(CLIND))

CLIND = ''
CALL SELF%SPF%ACDC_CRC64 (KLUN, CDPATH//'%SPF'//TRIM(CLIND))

CLIND = ''
CALL SELF%CVGQ%ACDC_CRC64 (KLUN, CDPATH//'%CVGQ'//TRIM(CLIND))

CLIND = ''
CALL SELF%QVA%ACDC_CRC64 (KLUN, CDPATH//'%QVA'//TRIM(CLIND))

LGHG = ALLOCATED (SELF%GHG)
IF (LGHG) THEN
  DO J1 = LBOUND (SELF%GHG, 1), UBOUND (SELF%GHG, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%GHG (J1)%ACDC_CRC64 (KLUN, CDPATH//'%GHG'//TRIM(CLIND))
  ENDDO
ENDIF

LCHEM = ALLOCATED (SELF%CHEM)
IF (LCHEM) THEN
  DO J1 = LBOUND (SELF%CHEM, 1), UBOUND (SELF%CHEM, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%CHEM (J1)%ACDC_CRC64 (KLUN, CDPATH//'%CHEM'//TRIM(CLIND))
  ENDDO
ENDIF

LAERO = ALLOCATED (SELF%AERO)
IF (LAERO) THEN
  DO J1 = LBOUND (SELF%AERO, 1), UBOUND (SELF%AERO, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%AERO (J1)%ACDC_CRC64 (KLUN, CDPATH//'%AERO'//TRIM(CLIND))
  ENDDO
ENDIF

CLIND = ''
CALL SELF%LRCH4%ACDC_CRC64 (KLUN, CDPATH//'%LRCH4'//TRIM(CLIND))

LFORC = ALLOCATED (SELF%FORC)
IF (LFORC) THEN
  DO J1 = LBOUND (SELF%FORC, 1), UBOUND (SELF%FORC, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%FORC (J1)%ACDC_CRC64 (KLUN, CDPATH//'%FORC'//TRIM(CLIND))
  ENDDO
ENDIF

LEZDIAG = ALLOCATED (SELF%EZDIAG)
IF (LEZDIAG) THEN
  DO J1 = LBOUND (SELF%EZDIAG, 1), UBOUND (SELF%EZDIAG, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%EZDIAG (J1)%ACDC_CRC64 (KLUN, CDPATH//'%EZDIAG'//TRIM(CLIND))
  ENDDO
ENDIF

LERA40 = ALLOCATED (SELF%ERA40)
IF (LERA40) THEN
  DO J1 = LBOUND (SELF%ERA40, 1), UBOUND (SELF%ERA40, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%ERA40 (J1)%ACDC_CRC64 (KLUN, CDPATH//'%ERA40'//TRIM(CLIND))
  ENDDO
ENDIF

LNOGW = ALLOCATED (SELF%NOGW)
IF (LNOGW) THEN
  DO J1 = LBOUND (SELF%NOGW, 1), UBOUND (SELF%NOGW, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%NOGW (J1)%ACDC_CRC64 (KLUN, CDPATH//'%NOGW'//TRIM(CLIND))
  ENDDO
ENDIF

LEMIS3D = ALLOCATED (SELF%EMIS3D)
IF (LEMIS3D) THEN
  DO J1 = LBOUND (SELF%EMIS3D, 1), UBOUND (SELF%EMIS3D, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%EMIS3D (J1)%ACDC_CRC64 (KLUN, CDPATH//'%EMIS3D'//TRIM(CLIND))
  ENDDO
ENDIF

LEDRP = ALLOCATED (SELF%EDRP)
IF (LEDRP) THEN
  DO J1 = LBOUND (SELF%EDRP, 1), UBOUND (SELF%EDRP, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%EDRP (J1)%ACDC_CRC64 (KLUN, CDPATH//'%EDRP'//TRIM(CLIND))
  ENDDO
ENDIF

LSLDIA = ALLOCATED (SELF%SLDIA)
IF (LSLDIA) THEN
  DO J1 = LBOUND (SELF%SLDIA, 1), UBOUND (SELF%SLDIA, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%SLDIA (J1)%ACDC_CRC64 (KLUN, CDPATH//'%SLDIA'//TRIM(CLIND))
  ENDDO
ENDIF

LAERAOT = ALLOCATED (SELF%AERAOT)
IF (LAERAOT) THEN
  DO J1 = LBOUND (SELF%AERAOT, 1), UBOUND (SELF%AERAOT, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%AERAOT (J1)%ACDC_CRC64 (KLUN, CDPATH//'%AERAOT'//TRIM(CLIND))
  ENDDO
ENDIF

LAERLISI = ALLOCATED (SELF%AERLISI)
IF (LAERLISI) THEN
  DO J1 = LBOUND (SELF%AERLISI, 1), UBOUND (SELF%AERLISI, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%AERLISI (J1)%ACDC_CRC64 (KLUN, CDPATH//'%AERLISI'//TRIM(CLIND))
  ENDDO
ENDIF

LAEROUT = ALLOCATED (SELF%AEROUT)
IF (LAEROUT) THEN
  DO J1 = LBOUND (SELF%AEROUT, 1), UBOUND (SELF%AEROUT, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%AEROUT (J1)%ACDC_CRC64 (KLUN, CDPATH//'%AEROUT'//TRIM(CLIND))
  ENDDO
ENDIF

LAEROCLIM = ALLOCATED (SELF%AEROCLIM)
IF (LAEROCLIM) THEN
  DO J1 = LBOUND (SELF%AEROCLIM, 1), UBOUND (SELF%AEROCLIM, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%AEROCLIM (J1)%ACDC_CRC64 (KLUN, CDPATH//'%AEROCLIM'//TRIM(CLIND))
  ENDDO
ENDIF

LUVP = ALLOCATED (SELF%UVP)
IF (LUVP) THEN
  DO J1 = LBOUND (SELF%UVP, 1), UBOUND (SELF%UVP, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%UVP (J1)%ACDC_CRC64 (KLUN, CDPATH//'%UVP'//TRIM(CLIND))
  ENDDO
ENDIF

CLIND = ''
CALL SELF%PHYCTY%ACDC_CRC64 (KLUN, CDPATH//'%PHYCTY'//TRIM(CLIND))

CLIND = ''
CALL SELF%RSPEC%ACDC_CRC64 (KLUN, CDPATH//'%RSPEC'//TRIM(CLIND))

CLIND = ''
CALL SELF%SDSAT%ACDC_CRC64 (KLUN, CDPATH//'%SDSAT'//TRIM(CLIND))

CLIND = ''
CALL SELF%CVV%ACDC_CRC64 (KLUN, CDPATH//'%CVV'//TRIM(CLIND))

CLIND = ''
CALL SELF%RKTH%ACDC_CRC64 (KLUN, CDPATH//'%RKTH'//TRIM(CLIND))

CLIND = ''
CALL SELF%RKTQV%ACDC_CRC64 (KLUN, CDPATH//'%RKTQV'//TRIM(CLIND))

CLIND = ''
CALL SELF%RKTQC%ACDC_CRC64 (KLUN, CDPATH//'%RKTQC'//TRIM(CLIND))

CLIND = ''
CALL SELF%UOM%ACDC_CRC64 (KLUN, CDPATH//'%UOM'//TRIM(CLIND))

CLIND = ''
CALL SELF%UAL%ACDC_CRC64 (KLUN, CDPATH//'%UAL'//TRIM(CLIND))

CLIND = ''
CALL SELF%DOM%ACDC_CRC64 (KLUN, CDPATH//'%DOM'//TRIM(CLIND))

CLIND = ''
CALL SELF%DAL%ACDC_CRC64 (KLUN, CDPATH//'%DAL'//TRIM(CLIND))

CLIND = ''
CALL SELF%UEN%ACDC_CRC64 (KLUN, CDPATH//'%UEN'//TRIM(CLIND))

CLIND = ''
CALL SELF%UNEBH%ACDC_CRC64 (KLUN, CDPATH//'%UNEBH'//TRIM(CLIND))

LLIMA = ALLOCATED (SELF%LIMA)
IF (LLIMA) THEN
  DO J1 = LBOUND (SELF%LIMA, 1), UBOUND (SELF%LIMA, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%LIMA (J1)%ACDC_CRC64 (KLUN, CDPATH//'%LIMA'//TRIM(CLIND))
  ENDDO
ENDIF

CLIND = ''
CALL SELF%FSD%ACDC_CRC64 (KLUN, CDPATH//'%FSD'//TRIM(CLIND))

LEXT = ALLOCATED (SELF%EXT)
IF (LEXT) THEN
  DO J1 = LBOUND (SELF%EXT, 1), UBOUND (SELF%EXT, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%EXT (J1)%ACDC_CRC64 (KLUN, CDPATH//'%EXT'//TRIM(CLIND))
  ENDDO
ENDIF

CLIND = ''
CALL SELF%GEOMETRY%ACDC_CRC64 (KLUN, CDPATH//'%GEOMETRY'//TRIM(CLIND))

CLIND = ''
CALL SELF%ECPHYS%ACDC_CRC64 (KLUN, CDPATH//'%ECPHYS'//TRIM(CLIND))

CLIND = ''
CALL SELF%RADIATION%ACDC_CRC64 (KLUN, CDPATH//'%RADIATION'//TRIM(CLIND))

LGFL_PTR = ALLOCATED (SELF%GFL_PTR)
IF (LGFL_PTR) THEN
  DO J1 = LBOUND (SELF%GFL_PTR, 1), UBOUND (SELF%GFL_PTR, 1)
    WRITE (CLIND, '("(",I0,")")') J1
    CALL SELF%GFL_PTR (J1)%ACDC_CRC64 (KLUN, CDPATH//'%GFL_PTR'//TRIM(CLIND))
  ENDDO
ENDIF

END SUBROUTINE

END SUBMODULE
