SUBMODULE (MF_PHYS_TYPE_MOD) MF_PHYS_TYPE_MOD_MF_PHYS_FOR_TYPE_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_MF_PHYS_FOR_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (MF_PHYS_FOR_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_Q, LF_T, LF_U, LF_V
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
LF_U = ASSOCIATED (SELF%F_U)
IF (LF_U .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_U)
  !$ACC ENTER DATA ATTACH (SELF%F_U)
ENDIF

LF_V = ASSOCIATED (SELF%F_V)
IF (LF_V .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_V)
  !$ACC ENTER DATA ATTACH (SELF%F_V)
ENDIF

LF_T = ASSOCIATED (SELF%F_T)
IF (LF_T .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_T)
  !$ACC ENTER DATA ATTACH (SELF%F_T)
ENDIF

LF_Q = ASSOCIATED (SELF%F_Q)
IF (LF_Q .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_Q)
  !$ACC ENTER DATA ATTACH (SELF%F_Q)
ENDIF

END SUBROUTINE

END SUBMODULE
