SUBMODULE (MF_PHYS_SURFACE_TYPE_MOD) MF_PHYS_SURFACE_TYPE_MOD_MF_PHYS_SURF_TYPE_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_MF_PHYS_SURF_TYPE (SELF)

IMPLICIT NONE
CLASS (MF_PHYS_SURF_TYPE), TARGET :: SELF

CALL SELF%GSP_SB%ACDC_HOST ()

CALL SELF%GSP_SG%ACDC_HOST ()

CALL SELF%GSP_SL%ACDC_HOST ()

CALL SELF%GSP_RR%ACDC_HOST ()

CALL SELF%GSP_CL%ACDC_HOST ()

CALL SELF%GSP_OM%ACDC_HOST ()

CALL SELF%GSP_EP%ACDC_HOST ()

CALL SELF%GSP_X2%ACDC_HOST ()

CALL SELF%GSP_CI%ACDC_HOST ()

CALL SELF%GSD_VF%ACDC_HOST ()

CALL SELF%GSD_VH%ACDC_HOST ()

CALL SELF%GSD_VK%ACDC_HOST ()

CALL SELF%GSD_VP%ACDC_HOST ()

CALL SELF%GSD_VV%ACDC_HOST ()

CALL SELF%GSD_VA%ACDC_HOST ()

CALL SELF%GSD_VN%ACDC_HOST ()

CALL SELF%GSD_V2%ACDC_HOST ()

CALL SELF%GSD_V3%ACDC_HOST ()

CALL SELF%GSD_VD%ACDC_HOST ()

CALL SELF%GSD_SM%ACDC_HOST ()

CALL SELF%GSD_WS%ACDC_HOST ()

CALL SELF%GSD_WW%ACDC_HOST ()

CALL SELF%GSD_PF%ACDC_HOST ()

CALL SELF%GSD_XA%ACDC_HOST ()

CALL SELF%GSD_DI%ACDC_HOST ()

CALL SELF%GSD_XP%ACDC_HOST ()

CALL SELF%GSD_XP2%ACDC_HOST ()

CALL SELF%GSD_X2%ACDC_HOST ()

CALL SELF%GSD_SFO%ACDC_HOST ()

CALL SELF%GSD_SFL%ACDC_HOST ()

CALL SELF%GSD_VC%ACDC_HOST ()

END SUBROUTINE

END SUBMODULE
