SUBMODULE (SURFACE_VIEWS_DIAGNOSTIC_MODULE) SURFACE_VIEWS_DIAGNOSTIC_MODULE_SURFACE_VIEW_GROUP_SATSIM_WIPE_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE WIPE_SURFACE_VIEW_GROUP_SATSIM (SELF, LDDELETED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VIEW_GROUP_SATSIM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LF_CLBT, LF_CSBT, LF_GROUP, LVARIABLE_GROUP

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LVARIABLE_GROUP = ASSOCIATED (SELF%VARIABLE_GROUP)
IF (LVARIABLE_GROUP) THEN
  !$ACC EXIT DATA DETACH (SELF%VARIABLE_GROUP)
  CALL SELF%VARIABLE_GROUP%WIPE (LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  !$ACC EXIT DATA DETACH (SELF%VARIABLE_GROUP)
ENDIF

LF_CLBT = ASSOCIATED (SELF%F_CLBT)
IF (LF_CLBT .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_CLBT)
ENDIF

LF_CSBT = ASSOCIATED (SELF%F_CSBT)
IF (LF_CSBT .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_3RB (SELF%F_CSBT)
ENDIF

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL WIPE_FIELD_4RB (SELF%F_GROUP)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE

END SUBMODULE
