SUBMODULE (SURFACE_VARIABLES_MOD) SURFACE_VARIABLES_MOD_SURFACE_VARIABLE_GROUP_LAKEB_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE HOST_SURFACE_VARIABLE_GROUP_LAKEB (SELF)
USE FIELD_UTIL_MODULE

IMPLICIT NONE
CLASS (SURFACE_VARIABLE_GROUP_LAKEB), TARGET :: SELF
LOGICAL :: LF_GROUP
CALL SELF%VLICT%HOST ()

CALL SELF%VLMLT%HOST ()

CALL SELF%VLTLT%HOST ()

CALL SELF%VLBLT%HOST ()

CALL SELF%VLSHF%HOST ()

CALL SELF%VLICD%HOST ()

CALL SELF%VLMLD%HOST ()

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_3RB (SELF%F_GROUP)
ENDIF

END SUBROUTINE

END SUBMODULE
