SUBMODULE (SURFACE_VARIABLES_MOD) SURFACE_VARIABLES_MOD_SURFACE_VARIABLE_GROUP_VPRECIP2_HOST_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_HOST_SURFACE_VARIABLE_GROUP_VPRECIP2 (SELF)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VARIABLE_GROUP_VPRECIP2), TARGET :: SELF
LOGICAL :: LF_GROUP
CALL SELF%VPRECIP2%ACDC_HOST ()

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP) THEN
  CALL HOST_FIELD_4RB (SELF%F_GROUP)
ENDIF

END SUBROUTINE

END SUBMODULE
