SUBMODULE (SURFACE_VARIABLES_MOD) SURFACE_VARIABLES_MOD_SURFACE_VARIABLE_GROUP_VDIAG_COPY_SMOD

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE ACDC_COPY_SURFACE_VARIABLE_GROUP_VDIAG (SELF, LDCREATED, LDFIELDAPI)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (SURFACE_VARIABLE_GROUP_VDIAG), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1, J2
LOGICAL :: LF_GROUP, LV10FG6, LVAERODIAG, LVAERO_WVL_DIAG, LVLICGA6, LVLITOTA6, LVMN2T6, LVMNTPR6, LVMX2T6, LVMXCAP6
LOGICAL :: LVMXCAPS6, LVMXTPR6, LVPTYPEOCC6, LVTCCHEM, LVTCGHG
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
CALL SELF%VLSP%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCP%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSF%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VFZRA%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VBLD%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSSHF%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSLHF%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VNEE%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VGPP%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VREC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMSL%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSP%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTCC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V10U%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V10V%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V2T%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V2D%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V2SH%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSSR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSTR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTSR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTTR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VEWSS%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VNSSS%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VE%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VPEV%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCCC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VLCC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMCC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VHCC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VLGWS%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMGWS%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VGWD%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMX2T%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMN2T%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LVMX2T6 = ALLOCATED (SELF%VMX2T6)
IF (LVMX2T6) THEN
  !$ACC ENTER DATA CREATE (SELF%VMX2T6)
  !$ACC UPDATE DEVICE (SELF%VMX2T6)
  DO J1 = LBOUND (SELF%VMX2T6, 1), UBOUND (SELF%VMX2T6, 1)
    CALL SELF%VMX2T6 (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VMX2T6)
ENDIF

LVMN2T6 = ALLOCATED (SELF%VMN2T6)
IF (LVMN2T6) THEN
  !$ACC ENTER DATA CREATE (SELF%VMN2T6)
  !$ACC UPDATE DEVICE (SELF%VMN2T6)
  DO J1 = LBOUND (SELF%VMN2T6, 1), UBOUND (SELF%VMN2T6, 1)
    CALL SELF%VMN2T6 (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VMN2T6)
ENDIF

CALL SELF%VRO%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSRO%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSSRO%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VALB%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VIEWSS%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VINSSS%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VISSHF%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VIE%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VINEE%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VIGPP%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VIREC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VICH4%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCSF%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VLSSF%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMXTPR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMNTPR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LVMXTPR6 = ALLOCATED (SELF%VMXTPR6)
IF (LVMXTPR6) THEN
  !$ACC ENTER DATA CREATE (SELF%VMXTPR6)
  !$ACC UPDATE DEVICE (SELF%VMXTPR6)
  DO J1 = LBOUND (SELF%VMXTPR6, 1), UBOUND (SELF%VMXTPR6, 1)
    CALL SELF%VMXTPR6 (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VMXTPR6)
ENDIF

LVMNTPR6 = ALLOCATED (SELF%VMNTPR6)
IF (LVMNTPR6) THEN
  !$ACC ENTER DATA CREATE (SELF%VMNTPR6)
  !$ACC UPDATE DEVICE (SELF%VMNTPR6)
  DO J1 = LBOUND (SELF%VMNTPR6, 1), UBOUND (SELF%VMNTPR6, 1)
    CALL SELF%VMNTPR6 (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VMNTPR6)
ENDIF

CALL SELF%VTPR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VLSRR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCRR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VLSSFR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCSFR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VPTYPE%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VILSPF%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VZ0F%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VLZ0H%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VVIWVE%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VVIWVN%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTCW%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTCWV%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTCLW%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTCIW%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTCRW%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTCSW%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTCSLW%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSSRD%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSTRD%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSSRDC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSTRDC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VBLH%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSUND%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSPAR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSUVB%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSFDIR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSCDIR%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSDSRP%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCAPE%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMUCAPE%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMLCAPE50%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMLCAPE100%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VPDEPL%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCAPES%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LVMXCAP6 = ALLOCATED (SELF%VMXCAP6)
IF (LVMXCAP6) THEN
  !$ACC ENTER DATA CREATE (SELF%VMXCAP6)
  !$ACC UPDATE DEVICE (SELF%VMXCAP6)
  DO J1 = LBOUND (SELF%VMXCAP6, 1), UBOUND (SELF%VMXCAP6, 1)
    CALL SELF%VMXCAP6 (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VMXCAP6)
ENDIF

LVMXCAPS6 = ALLOCATED (SELF%VMXCAPS6)
IF (LVMXCAPS6) THEN
  !$ACC ENTER DATA CREATE (SELF%VMXCAPS6)
  !$ACC UPDATE DEVICE (SELF%VMXCAPS6)
  DO J1 = LBOUND (SELF%VMXCAPS6, 1), UBOUND (SELF%VMXCAPS6, 1)
    CALL SELF%VMXCAPS6 (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VMXCAPS6)
ENDIF

CALL SELF%VTROPOTP%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTSRC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTTRC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSSRC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSTRC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VES%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSMLT%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V10FG%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LV10FG6 = ALLOCATED (SELF%V10FG6)
IF (LV10FG6) THEN
  !$ACC ENTER DATA CREATE (SELF%V10FG6)
  !$ACC UPDATE DEVICE (SELF%V10FG6)
  DO J1 = LBOUND (SELF%V10FG6, 1), UBOUND (SELF%V10FG6, 1)
    CALL SELF%V10FG6 (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%V10FG6)
ENDIF

CALL SELF%V10FGCV%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VI10FG%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VLSPF%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTCO3%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VVIMD%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSPARC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VSTINC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCBASE%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V0DEGL%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VM10DEGL%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VVISIH%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCIN%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMLCIN50%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VMLCIN100%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VKINDEX%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTTINDEX%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCBASEA%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VCTOPC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VZTWETB0%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VZTWETB1%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LVTCGHG = ALLOCATED (SELF%VTCGHG)
IF (LVTCGHG) THEN
  !$ACC ENTER DATA CREATE (SELF%VTCGHG)
  !$ACC UPDATE DEVICE (SELF%VTCGHG)
  DO J1 = LBOUND (SELF%VTCGHG, 1), UBOUND (SELF%VTCGHG, 1)
    CALL SELF%VTCGHG (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VTCGHG)
ENDIF

LVTCCHEM = ALLOCATED (SELF%VTCCHEM)
IF (LVTCCHEM) THEN
  !$ACC ENTER DATA CREATE (SELF%VTCCHEM)
  !$ACC UPDATE DEVICE (SELF%VTCCHEM)
  DO J1 = LBOUND (SELF%VTCCHEM, 1), UBOUND (SELF%VTCCHEM, 1)
    CALL SELF%VTCCHEM (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VTCCHEM)
ENDIF

LVAERODIAG = ALLOCATED (SELF%VAERODIAG)
IF (LVAERODIAG) THEN
  !$ACC ENTER DATA CREATE (SELF%VAERODIAG)
  !$ACC UPDATE DEVICE (SELF%VAERODIAG)
  DO J2 = LBOUND (SELF%VAERODIAG, 2), UBOUND (SELF%VAERODIAG, 2)
    DO J1 = LBOUND (SELF%VAERODIAG, 1), UBOUND (SELF%VAERODIAG, 1)
      CALL SELF%VAERODIAG (J1, J2)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
    ENDDO
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VAERODIAG)
ENDIF

LVAERO_WVL_DIAG = ALLOCATED (SELF%VAERO_WVL_DIAG)
IF (LVAERO_WVL_DIAG) THEN
  !$ACC ENTER DATA CREATE (SELF%VAERO_WVL_DIAG)
  !$ACC UPDATE DEVICE (SELF%VAERO_WVL_DIAG)
  DO J2 = LBOUND (SELF%VAERO_WVL_DIAG, 2), UBOUND (SELF%VAERO_WVL_DIAG, 2)
    DO J1 = LBOUND (SELF%VAERO_WVL_DIAG, 1), UBOUND (SELF%VAERO_WVL_DIAG, 1)
      CALL SELF%VAERO_WVL_DIAG (J1, J2)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
    ENDDO
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VAERO_WVL_DIAG)
ENDIF

CALL SELF%V100U%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V100V%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V200U%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V200V%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VZUST%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V10NU%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%V10NV%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VDNDZN%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VDNDZA%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VDCTB%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTPLB%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VTPLT%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODSS%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODDU%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODOM%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODBC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODSU%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODNI%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODAM%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODSOA%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODVFA%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODVSU%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VODTOACC%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VAEPM1%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VAEPM25%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VAEPM10%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VUVBED%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VUVBEDCS%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VLITOTI%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL SELF%VLICGI%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LVLITOTA6 = ALLOCATED (SELF%VLITOTA6)
IF (LVLITOTA6) THEN
  !$ACC ENTER DATA CREATE (SELF%VLITOTA6)
  !$ACC UPDATE DEVICE (SELF%VLITOTA6)
  DO J1 = LBOUND (SELF%VLITOTA6, 1), UBOUND (SELF%VLITOTA6, 1)
    CALL SELF%VLITOTA6 (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VLITOTA6)
ENDIF

LVLICGA6 = ALLOCATED (SELF%VLICGA6)
IF (LVLICGA6) THEN
  !$ACC ENTER DATA CREATE (SELF%VLICGA6)
  !$ACC UPDATE DEVICE (SELF%VLICGA6)
  DO J1 = LBOUND (SELF%VLICGA6, 1), UBOUND (SELF%VLICGA6, 1)
    CALL SELF%VLICGA6 (J1)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VLICGA6)
ENDIF

LVPTYPEOCC6 = ALLOCATED (SELF%VPTYPEOCC6)
IF (LVPTYPEOCC6) THEN
  !$ACC ENTER DATA CREATE (SELF%VPTYPEOCC6)
  !$ACC UPDATE DEVICE (SELF%VPTYPEOCC6)
  DO J2 = LBOUND (SELF%VPTYPEOCC6, 2), UBOUND (SELF%VPTYPEOCC6, 2)
    DO J1 = LBOUND (SELF%VPTYPEOCC6, 1), UBOUND (SELF%VPTYPEOCC6, 1)
      CALL SELF%VPTYPEOCC6 (J1, J2)%ACDC_COPY (LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
    ENDDO
  ENDDO
  !$ACC ENTER DATA ATTACH (SELF%VPTYPEOCC6)
ENDIF

LF_GROUP = ASSOCIATED (SELF%F_GROUP)
IF (LF_GROUP .AND. LLFIELDAPI) THEN
  CALL COPY_FIELD_3RB (SELF%F_GROUP)
  !$ACC ENTER DATA ATTACH (SELF%F_GROUP)
ENDIF

END SUBROUTINE

END SUBMODULE
