SUBMODULE (VARIABLE_MODULE) VARIABLE_MODULE_VARIABLE_2RD_SIZE_SMOD

IMPLICIT NONE

CONTAINS

MODULE FUNCTION ACDC_SIZE_VARIABLE_2RD (SELF, CDPATH, LDPRINT) RESULT (KSIZE)
USE FIELD_UTIL_MODULE
IMPLICIT NONE
CLASS (VARIABLE_2RD),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
CLASS (VARIABLE_BASE), POINTER :: YLSUPER
LOGICAL :: LFDL, LFDL9, LFDM, LFDM9, LFPC_PH, LFPH9, LFT0, LFT1, LFT9
LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
YLSUPER => SELF
KSIZE = KSIZE + YLSUPER%ACDC_SIZE (CLPATH, LLPRINT)
END FUNCTION

END SUBMODULE
