
SUBROUTINE ACDRAG_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PAPRS, PAPRSF, PDELP, PNBVNO&
&, PRDELP, PU, PV, PRCORI, PGETRL, PGWDCS, PVRLAN, PVRLDI, PSTRDU, PSTRDV, PRAPTRAJ, YDSTACK)
!$ACC ROUTINE (ACDRAG_OPENACC) SEQ
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB, JPRD

USE YOMCST,ONLY:TCST
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PNBVNO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRCORI (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGETRL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGWDCS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLAN (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLDI (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDU (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRAPTRAJ (KLON, 0:KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
REAL (KIND=JPRB)::ZZCV 
REAL (KIND=JPRB)::ZZCU 
REAL (KIND=JPRB)::ZZCR 
REAL (KIND=JPRB)::ZZBB 
REAL (KIND=JPRB)::ZZAA 
REAL (KIND=JPRB)::ZWGHTK 
REAL (KIND=JPRB)::ZVSUR 
REAL (KIND=JPRB)::ZUSUR 
REAL (KIND=JPRB)::ZUSR 
REAL (KIND=JPRB)::ZTST2 
REAL (KIND=JPRB)::ZTST1 
REAL (KIND=JPRB)::ZSUSR 
REAL (KIND=JPRB)::ZSUMV 
REAL (KIND=JPRB)::ZSUMU 
REAL (KIND=JPRB)::ZSUMF 
REAL (KIND=JPRB)::ZSUMD 
REAL (KIND=JPRB)::ZSUM 
REAL (KIND=JPRB)::ZSTVS 
REAL (KIND=JPRB)::ZSTUS 
REAL (KIND=JPRB)::ZSTS 
REAL (KIND=JPRB)::ZSTM 
REAL (KIND=JPRB)::ZREF 
REAL (KIND=JPRB)::ZPR2 
REAL (KIND=JPRB)::ZPR1 
REAL (KIND=JPRB)::ZOBST 
REAL (KIND=JPRB)::ZFACS 
REAL (KIND=JPRB)::ZDS2 
REAL (KIND=JPRB)::ZDS1 
fxtran_acdc_temp (REAL (KIND=JPRB), ZWGHT, (KLON, 0:KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZV, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZU, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZRAPP, (KLON, 0:KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZPOID, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZNFNO, (KLON, 0:KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZIPOI, (KLON, KLEV))
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::ITOP
REAL (KIND=JPRB)::ZRZR
REAL (KIND=JPRB)::ZZPR
REAL (KIND=JPRB)::ZX
REAL (KIND=JPRB)::ZVSTAR
REAL (KIND=JPRB)::ZUSTAR
REAL (KIND=JPRB)::ZTUNE
REAL (KIND=JPRB)::ZTEST
REAL (KIND=JPRB)::ZTEMPF 
REAL (KIND=JPRB)::ZRZ
REAL (KIND=JPRB)::ZPRRAP
REAL (KIND=JPRB)::ZPBLF
REAL (KIND=JPRB)::ZPBL
REAL (KIND=JPRB)::ZLIFTG
REAL (KIND=JPRB)::ZLIFT
REAL (KIND=JPRB)::ZGDTI
REAL (KIND=JPRB)::ZGDT
REAL (KIND=JPRB)::ZFORCL
REAL (KIND=JPRB)::ZFORCB
REAL (KIND=JPRB)::ZFORCA
REAL (KIND=JPRB)::ZEPS6
REAL (KIND=JPRB)::ZEPS5
REAL (KIND=JPRB)::ZEPS4
REAL (KIND=JPRB)::ZEPS3
REAL (KIND=JPRB)::ZEPS2
REAL (KIND=JPRB)::ZEPS1
REAL (KIND=JPRB)::ZDX
REAL (KIND=JPRB)::ZDV
REAL (KIND=JPRB)::ZDU
REAL (KIND=JPRB)::ZDIFSV
REAL (KIND=JPRB)::ZDIFSU
REAL (KIND=JPRB)::ZDIFSR
REAL (KIND=JPRB)::ZDEL2
REAL (KIND=JPRB)::ZDEL1
REAL (KIND=JPRB)::ZD
REAL (KIND=JPRB)::ZBETA
REAL (KIND=JPRB)::ZAUSR
REAL (KIND=JPRB)::ZARGLI
REAL (KIND=JPRB)::ZALTI
REAL (KIND=JPRB)::ZALPHA
REAL (KIND=JPRB)::ZALP2
REAL (KIND=JPRB)::ZALP1
REAL (KIND=JPRB)::ZA
REAL (KIND=JPRB)::ZCOS 


YLSTACK = YDSTACK



IF (KIND (ZWGHT) == 8) THEN
    fxtran_acdc_alloc8 (ZWGHT)
ELSEIF (KIND (ZWGHT) == 4) THEN
    fxtran_acdc_alloc4 (ZWGHT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZV) == 8) THEN
    fxtran_acdc_alloc8 (ZV)
ELSEIF (KIND (ZV) == 4) THEN
    fxtran_acdc_alloc4 (ZV)
ELSE
    STOP 1
ENDIF


IF (KIND (ZU) == 8) THEN
    fxtran_acdc_alloc8 (ZU)
ELSEIF (KIND (ZU) == 4) THEN
    fxtran_acdc_alloc4 (ZU)
ELSE
    STOP 1
ENDIF


IF (KIND (ZRAPP) == 8) THEN
    fxtran_acdc_alloc8 (ZRAPP)
ELSEIF (KIND (ZRAPP) == 4) THEN
    fxtran_acdc_alloc4 (ZRAPP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZPOID) == 8) THEN
    fxtran_acdc_alloc8 (ZPOID)
ELSEIF (KIND (ZPOID) == 4) THEN
    fxtran_acdc_alloc4 (ZPOID)
ELSE
    STOP 1
ENDIF


IF (KIND (ZNFNO) == 8) THEN
    fxtran_acdc_alloc8 (ZNFNO)
ELSEIF (KIND (ZNFNO) == 4) THEN
    fxtran_acdc_alloc4 (ZNFNO)
ELSE
    STOP 1
ENDIF


IF (KIND (ZIPOI) == 8) THEN
    fxtran_acdc_alloc8 (ZIPOI)
ELSEIF (KIND (ZIPOI) == 4) THEN
    fxtran_acdc_alloc4 (ZIPOI)
ELSE
    STOP 1
ENDIF


JLON = KIDIA



PRAPTRAJ (JLON,:)=0.0
ZGDT=YDCST%RG*YDML_PHY_MF%YRPHY2%TSPHY
ZGDTI=1.0_JPRB/ZGDT

IF (YDML_PHY_MF%YRPHY0%GWDPROF==0.0_JPRB) THEN
  ZZPR=0.5_JPRB
ELSE
  ZZPR=((1.0_JPRB+YDML_PHY_MF%YRPHY0%GWDPROF)*LOG (1.0_JPRB+YDML_PHY_MF%YRPHY0&
  &%GWDPROF)-YDML_PHY_MF%YRPHY0%GWDPROF)/YDML_PHY_MF%YRPHY0%GWDPROF**2
ENDIF

ZLIFT=YDML_PHY_MF%YRPHY0%GWDLT*YDML_PHY_MF%YRPHY2%TSPHY/(YDML_PHY_MF%YRPHY0%HOBST*ZZPR)
ZLIFTG=YDML_PHY_MF%YRPHY0%GWDLT/(YDML_PHY_MF%YRPHY0%HOBST*ZZPR)

IF (.NOT.YDML_PHY_MF%YRPHY%LGLT) THEN
  ZLIFTG=0.0_JPRB
ENDIF

ZALP1=0.75_JPRB+0.25_JPRB*LOG (16._JPRB)
ZALP2=3.5_JPRB*YDCST%RPI-LOG (16._JPRB)-8._JPRB
ZDEL1=2.75_JPRB-0.75_JPRB*LOG (16._JPRB)
ZDEL2=-0.25_JPRB*YDCST%RPI-LOG (16._JPRB)+4._JPRB
ZEPS1=1.E-06_JPRB
ZEPS2=1.E-04_JPRB
ZEPS3=1.E-09_JPRB
ZEPS4=1.E-05_JPRB
ZEPS5=1.E-02_JPRB

IF (JPRB==JPRD) THEN
  ZEPS6=1.E-12_JPRB
ELSE
  ZEPS6=1.E-6_JPRB
ENDIF

ZARGLI=1.E+06_JPRB
ZBETA=MIN (YDML_PHY_MF%YRPHY0%GWDVALI, 1.0_JPRB-ZEPS6)

DO JLEV=KTDIA, KLEV
  
  ZPOID (JLON, JLEV)=PDELP (JLON, JLEV)*ZGDTI
  ZIPOI (JLON, JLEV)=PRDELP (JLON, JLEV)*ZGDT
  ZWGHT (JLON, JLEV)=0.0_JPRB
  
ENDDO


ZOBST =MIN (PAPRS (JLON, KLEV)-PAPRSF (JLON, KTDIA), MAX (PAPRS (JLON, KLEV)-PAPRSF&
& (JLON, KLEV), YDML_PHY_MF%YRPHY0%HOBST*PGETRL (JLON)*PGWDCS (JLON)))
ZWGHT (JLON, KLEV)=(PAPRS (JLON, KLEV)-PAPRSF (JLON, KLEV))/ZOBST 
ZWGHT (JLON, KLEV)=ZWGHT (JLON, KLEV)*(1.0_JPRB-ZBETA)
ZWGHTK =ZWGHT (JLON, KLEV)
ZSUMU =ZWGHT (JLON, KLEV)*PU (JLON, KLEV)
ZSUMV =ZWGHT (JLON, KLEV)*PV (JLON, KLEV)
ZSUMF =ZWGHT (JLON, KLEV)*PNBVNO (JLON, KLEV)

ZTEST=1.0_JPRB
ITOP=KLEV

DO JLEV=KLEV-1, KTDIA,-1

  IF (ZTEST/=0.0_JPRB) THEN
    ITOP=JLEV
    
    ZWGHT (JLON, JLEV)=MAX (0.0_JPRB,(PAPRSF (JLON, JLEV+1)-MAX &
    &(PAPRSF (JLON, JLEV), PAPRS (JLON, KLEV)-ZOBST ))/ZOBST )
    ZALTI=MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRS (JLON, JLEV))/ZOBST )
    ZWGHT (JLON, JLEV)=ZWGHT (JLON, JLEV)*(1.0_JPRB-ZBETA*((1.0_JPRB&
    &-ZALTI)/(1.0_JPRB+YDML_PHY_MF%YRPHY0%GWDPROF*ZALTI)))
    ZWGHTK =ZWGHTK +ZWGHT (JLON, JLEV)
    ZSUMU =ZSUMU +0.5_JPRB*ZWGHT (JLON, JLEV)*(PU (JLON, JLEV)+PU (JLON, JLEV+1))
    ZSUMV =ZSUMV +0.5_JPRB*ZWGHT (JLON, JLEV)*(PV (JLON, JLEV)+PV (JLON, JLEV+1))
    ZSUMF =ZSUMF +ZWGHT (JLON, JLEV)*PNBVNO (JLON, JLEV)
  
  ENDIF

  ZTEST=0.0_JPRB
  
  ZTEST=ZTEST+ZWGHT (JLON, JLEV)
  
ENDDO


DO JLEV=KTDIA, KLEV
  
  ZWGHT (JLON, JLEV)=ZWGHT (JLON, JLEV)*(1.0_JPRB/ZWGHTK )
  
ENDDO


ZSUMU =ZSUMU *(1.0_JPRB/ZWGHTK )
ZSUMV =ZSUMV *(1.0_JPRB/ZWGHTK )
ZSUMF =ZSUMF *(1.0_JPRB/ZWGHTK )


IF (YDML_PHY_MF%YRPHY%NPHYREP/=0.AND.YDML_PHY_MF%YRPHY%NPHYREP/=-2)  THEN
  ITOP=KTDIA
ENDIF


ZNFNO (JLON, KLEV)=SQRT (MAX (0.0_JPRB, ZSUMF ))
ZPBLF=1.0_JPRB-MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRSF (JLON, KLEV))/ZOBST )
ZU (JLON, KLEV)=PU (JLON, KLEV)+ZPBLF*(ZSUMU -PU (JLON, KLEV))
ZV (JLON, KLEV)=PV (JLON, KLEV)+ZPBLF*(ZSUMV -PV (JLON, KLEV))


DO JLEV=KLEV-1, KTDIA,-1
  
  ZPBL=1.0_JPRB-MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRS (JLON, JLEV))/ZOBST )
  ZNFNO (JLON, JLEV)=SQRT (MAX (0.0_JPRB, PNBVNO (JLON, JLEV)+ZPBL*(ZSUMF -PNBVNO (JLON, JLEV))))
  ZPBLF=1.0_JPRB-MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRSF (JLON, JLEV))/ZOBST )
  ZU (JLON, JLEV)=PU (JLON, JLEV)+ZPBLF*(ZSUMU -PU (JLON, JLEV))
  ZV (JLON, JLEV)=PV (JLON, JLEV)+ZPBLF*(ZSUMV -PV (JLON, JLEV))
  
ENDDO


ZUSTAR=ZSUMU *COS (2.0_JPRB*PVRLDI (JLON))+ZSUMV *SIN (2.0_JPRB*PVRLDI (JLON))
ZVSTAR=ZSUMU *SIN (2.0_JPRB*PVRLDI (JLON))-ZSUMV *COS (2.0_JPRB*PVRLDI (JLON))
ZA=PVRLAN (JLON)**2+0.5_JPRB*(4._JPRB*(1.0_JPRB-PVRLAN (JLON))*(1.0_JPRB+ZALP1*PVRLAN (JLON))+PVRLAN&
& (JLON)*LOG (1.0_JPRB/MAX (ZEPS1, PVRLAN (JLON)))*(1.0_JPRB+ZALP2*PVRLAN (JLON)))/YDCST%RPI
ZD=0.5_JPRB*(4._JPRB*(1.0_JPRB-PVRLAN (JLON))*(1.0_JPRB+ZDEL1*PVRLAN (JLON))-3._JPRB*PVRLAN (JLON&
&)*LOG (1.0_JPRB/MAX (ZEPS1, PVRLAN (JLON)))*(1.0_JPRB+ZDEL2*PVRLAN (JLON)))/YDCST%RPI
ZUSUR =ZA*ZSUMU +ZD*ZUSTAR
ZVSUR =ZA*ZSUMV +ZD*ZVSTAR
ZSUSR =MAX (ZEPS2, ZSUMU *ZUSUR +ZSUMV *ZVSUR )
ZUSR =SQRT (ZUSUR **2+ZVSUR **2)
ZFACS =ZNFNO (JLON, KLEV)/ZSUSR **3
ZRAPP (JLON, KLEV)=1.0_JPRB
ZSTUS =YDML_PHY_MF%YRPHY0%GWDSE*PGWDCS (JLON)**2*ZNFNO (JLON, KLEV)*PGETRL (JLON)*ZUSUR 
ZSTVS =YDML_PHY_MF%YRPHY0%GWDSE*PGWDCS (JLON)**2*ZNFNO (JLON, KLEV)*PGETRL (JLON)*ZVSUR 
ZTST1 =1.0_JPRB
ZPR1 =PAPRSF (JLON, KLEV)
ZSUM =(PAPRS (JLON, KLEV)-PAPRSF (JLON, KLEV))*ZNFNO (JLON, KLEV)*ZUSR /ZSUSR 
ZTST2 =1.0_JPRB
ZPR2 =PAPRSF (JLON, KLEV)
ZREF =1.0_JPRB
ZTUNE=YDML_PHY_MF%YRPHY0%GWDBC*(ZUSR **2/ZSUSR )**2
ZTEMPF =ZUSR /MAX (ZEPS5, ZTUNE*YDML_PHY_MF%YRPHY0%HOBST&
&*PGETRL (JLON)*PGWDCS (JLON)*ZNFNO (JLON, KLEV))
ZZBB =MAX (0.0_JPRB, 1.0_JPRB-MAX (ZTEMPF , ZEPS6))
ZZAA =YDML_PHY_MF%YRPHY0%GWDCD*ZZBB *ZTUNE*(1.0_JPRB-ZZBB )

IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
  ZSTUS =ZSTUS *(1.0_JPRB-ZZBB )/MAX (1.0_JPRB, ZTEMPF )
  ZSTVS =ZSTVS *(1.0_JPRB-ZZBB )/MAX (1.0_JPRB, ZTEMPF )
  ZZAA =YDML_PHY_MF%YRPHY0%GWDCD*ZZBB 
ENDIF



DO JLEV=0, KLEV
  
  PRAPTRAJ (JLON, JLEV)=YDML_PHY_MF%YRPHY0%GWDSE*PGWDCS (JLON)**2*ZNFNO (JLON, KLEV)*PGETRL (JLON)

  

  IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
    
    PRAPTRAJ (JLON, JLEV)=PRAPTRAJ (JLON, JLEV)*(1.0_JPRB-ZZBB )/MAX (1.0_JPRB, ZTEMPF )
  
  ENDIF

ENDDO


DO JLEV=KLEV-1, KTDIA,-1
  
  ZAUSR=0.5_JPRB*((ZU (JLON, JLEV)+ZU (JLON, JLEV+1))*ZUSUR&
  & +(ZV (JLON, JLEV)+ZV (JLON, JLEV+1))*ZVSUR )
  ZPRRAP=ZFACS *ZAUSR**3/MAX (ZEPS3, ZNFNO (JLON, JLEV))
  ZRAPP (JLON, JLEV)=MAX (0.0_JPRB, MIN (ZRAPP (JLON, JLEV+1), ZPRRAP))
  ZTST1 =ZTST1 *MAX (0.0_JPRB, SIGN (1.0_JPRB, ZPRRAP-1.0_JPRB))
  ZPR1 =ZPR1 +ZTST1 *(PAPRSF (JLON, JLEV)-ZPR1 )
  ZSUM =ZSUM +ZTST1 *(PAPRSF (JLON, JLEV+1)-PAPRSF (JLON,&
  & JLEV))*ZNFNO (JLON, JLEV)*ZUSR /MAX (ZEPS2, ZAUSR)
  ZTST2 =ZTST2 *(1.0_JPRB-MAX (0.0_JPRB, SIGN (1.0_JPRB, 0.0_JPRB-ZNFNO (JLON, JLEV))))
  ZPR2 =ZPR2 +ZTST2 *(PAPRSF (JLON, JLEV)-ZPR2 )
  ZREF =ZREF +ZTST2 *(ZRAPP (JLON, JLEV)-ZREF )
  
ENDDO


PSTRDU (JLON, KTDIA-1)=0.0_JPRB
PSTRDV (JLON, KTDIA-1)=0.0_JPRB
ZRAPP (JLON, KTDIA-1)=0.0_JPRB
PRAPTRAJ (JLON, KTDIA-1)=0.0_JPRB
ZSTM =1.0_JPRB/SQRT (1.0_JPRB+MAX (0.0_JPRB, SIGN (1.0_JPRB, ZPR1 -ZPR2 -ZEPS4))*YDML_PHY_MF&
&%YRPHY0%GWDAMP*(2.0_JPRB*SIN (MIN (ZARGLI, ZSUM ))+YDML_PHY_MF%YRPHY0%GWDAMP))

IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
  ZSTM =ZSTM /(1.0_JPRB-ZZBB )
  ZREF =ZREF /(1.0_JPRB-ZZBB )
ENDIF

ZDS1 =MAX (0.0_JPRB, ZSTM -1.0_JPRB)/(PAPRS (JLON, KLEV)-ZPR1 )
ZSTS =MIN (ZREF *(1.0_JPRB-ZTST2 ), ZSTM )
ZDS2 =ZSTS /(PAPRS (JLON, KLEV)-ZPR2 )


ZZCR =ZRAPP (JLON, KLEV)*ZSTM 


DO JLEV=KTDIA, KLEV
  
  ZRAPP (JLON, JLEV)=ZDS2 *MAX (0.0_JPRB, PAPRS (JLON, JLEV)-ZPR2 )+MAX (0.0_JPRB, MIN &
  &(ZSTM , ZRAPP (JLON, JLEV)+ZDS1 *MAX (0.0_JPRB, PAPRS (JLON, JLEV)-ZPR1 ))-ZSTS )
  ZRZ=(PAPRS (JLON, KLEV)-PAPRS (JLON, JLEV))/MAX (ZEPS4, ZZBB&
  & *YDML_PHY_MF%YRPHY0%HOBST*PGETRL (JLON)*PGWDCS (JLON))

  IF (.NOT.YDML_PHY_MF%YRPHY%LNEWD) THEN
    ZZCR =ZRAPP (JLON, JLEV)
    ZRZR=1.0_JPRB
    ZRZ=MIN (1.0_JPRB, ZRZ)
  ELSE
    ZRZR=SQRT (ZZBB /(1.0_JPRB+ZRZ**2*ZZBB *(1.0_JPRB-ZZBB )))
  ENDIF

  ZRAPP (JLON, JLEV)=ZRAPP (JLON, JLEV)+ZZCR *(ZZAA *SQRT (MAX (0.0_JPRB,(1.0_JPRB&
  &-ZRZ*ZRZR)**3/(1.0_JPRB+ZRZ*YDML_PHY_MF%YRPHY0%GWDPROF*ZZBB ))))
  
ENDDO


ZZCR =ZRAPP (JLON, KTDIA-1)


DO JLEV=KTDIA, KLEV
  
  ZDIFSR=ZRAPP (JLON, JLEV)-ZZCR 
  ZZCR =ZRAPP (JLON, JLEV)
  ZALTI=MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRSF (JLON, JLEV))/ZOBST )
  ZRAPP (JLON, JLEV)=ZRAPP (JLON, JLEV-1)+ZDIFSR*(1.0_JPRB+ZLIFTG*(1.0_JPRB&
  &-ZALTI)/(1.0_JPRB+ZALTI*YDML_PHY_MF%YRPHY0%GWDPROF))*(1.0_JPRB-ZBETA*&
  &((1.0_JPRB-ZALTI)/(1.0_JPRB+YDML_PHY_MF%YRPHY0%GWDPROF*ZALTI)))
  PSTRDU (JLON, JLEV)=ZRAPP (JLON, JLEV)*ZSTUS 
  PSTRDV (JLON, JLEV)=ZRAPP (JLON, JLEV)*ZSTVS 
  PRAPTRAJ (JLON, JLEV)=PRAPTRAJ (JLON, JLEV)*ZRAPP (JLON, JLEV)
  
ENDDO


ZSUMD =0.5_JPRB*ZWGHT (JLON, ITOP)*ZIPOI (JLON, ITOP)*(ZRAPP (JLON, ITOP)-ZRAPP (JLON, ITOP-1))


DO JLEV=ITOP+1, KLEV
  
  ZSUMD =ZSUMD +0.5_JPRB*(ZWGHT (JLON, JLEV)+ZWGHT (JLON, JLEV-1))&
  &*ZIPOI (JLON, JLEV)*(ZRAPP (JLON, JLEV)-ZRAPP (JLON, JLEV-1))
  
ENDDO


ZSUMD =ZSUMD +0.5_JPRB*ZWGHT (JLON, KLEV)*ZIPOI (JLON&
&, KLEV)*(ZRAPP (JLON, KLEV)-ZRAPP (JLON, KLEV-1))


ZSUMD =ZSUMD *SQRT (ZSTUS **2+ZSTVS **2)
ZRAPP (JLON, KLEV)=1.0_JPRB/(1.0_JPRB+ZSUMD *ZUSR /ZSUSR )


DO JLEV=KTDIA, KLEV
  
  PSTRDU (JLON, JLEV)=PSTRDU (JLON, JLEV)*ZRAPP (JLON, KLEV)
  PSTRDV (JLON, JLEV)=PSTRDV (JLON, JLEV)*ZRAPP (JLON, KLEV)
  PRAPTRAJ (JLON, JLEV)=PRAPTRAJ (JLON, JLEV)*ZRAPP (JLON, KLEV)
  
ENDDO


DO JLEV=KTDIA, KLEV
  
  ZDU=ZIPOI (JLON, JLEV)*(PSTRDU (JLON, JLEV-1)-PSTRDU (JLON, JLEV))
  ZDV=ZIPOI (JLON, JLEV)*(PSTRDV (JLON, JLEV-1)-PSTRDV (JLON, JLEV))
  ZDX=ZIPOI (JLON, JLEV)*(ZUSUR *PSTRDU (JLON, JLEV)+ZVSUR *PSTRDV (JLON, JLEV))
  ZX=ZUSUR *PU (JLON, JLEV)+ZVSUR *PV (JLON, JLEV)
  ZALPHA=1.0_JPRB/(1.0_JPRB+ZDX/MAX (ZEPS2, ZX))
  PSTRDU (JLON, JLEV)=PSTRDU (JLON, JLEV-1)-ZPOID (JLON, JLEV)*ZALPHA*ZDU
  PSTRDV (JLON, JLEV)=PSTRDV (JLON, JLEV-1)-ZPOID (JLON, JLEV)*ZALPHA*ZDV
  
ENDDO


ZZCU =PSTRDU (JLON, KTDIA-1)
ZZCV =PSTRDV (JLON, KTDIA-1)


DO JLEV=KTDIA, KLEV
  
  ZDIFSU=PSTRDU (JLON, JLEV)-ZZCU 
  ZDIFSV=PSTRDV (JLON, JLEV)-ZZCV 
  ZZCU =PSTRDU (JLON, JLEV)
  ZZCV =PSTRDV (JLON, JLEV)
  ZALTI=MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRSF (JLON, JLEV))/ZOBST )
  ZFORCL=ZLIFT*PRCORI (JLON)*(1.0_JPRB-ZALTI)/(1.0_JPRB+ZALTI*YDML_PHY_MF%YRPHY0%GWDPROF)
  ZFORCA=ZFORCL/(1.0_JPRB+0.25_JPRB*ZFORCL**2)
  ZFORCB=0.5_JPRB*ZFORCL*ZFORCA
  PSTRDU (JLON, JLEV)=PSTRDU (JLON, JLEV-1)+ZDIFSU+ZPOID (JLON&
  &, JLEV)*(ZFORCB*PU (JLON, JLEV)-ZFORCA*PV (JLON, JLEV))
  PSTRDV (JLON, JLEV)=PSTRDV (JLON, JLEV-1)+ZDIFSV+ZPOID (JLON&
  &, JLEV)*(ZFORCB*PV (JLON, JLEV)+ZFORCA*PU (JLON, JLEV))
  
ENDDO



END SUBROUTINE ACDRAG_OPENACC
