
SUBROUTINE ACHMTLS_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KLEV, PAPHI&
&, PAPHIF, PAPRS, PAPRSF, PR, PT, PU, PV, PTS, PQS, PDPHIT, PGZ0, PGZ0H, LDCLS&
&, PNBVNO, PMRIPP, PCPS, PGWDCS, PLHS, PZPCLS, PCD, PCDN, YDSTACK)
!$ACC ROUTINE (ACHMTLS_OPENACC) SEQ
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (IN)::PAPHI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPHIF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PR (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PQS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGZ0 (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGZ0H (KLON)
REAL (KIND=JPRB), INTENT (IN)::PDPHIT (KLON)
LOGICAL, INTENT (IN)::LDCLS
REAL (KIND=JPRB), INTENT (OUT)::PNBVNO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMRIPP (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCPS (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PGWDCS (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PLHS (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PZPCLS (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PCD (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PCDN (KLON)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPRB)::ZRS 
REAL (KIND=JPRB)::ZSTABV 
REAL (KIND=JPRB)::ZRTI 
REAL (KIND=JPRB)::ZDPHI 
REAL (KIND=JPRB)::ZEPS
REAL (KIND=JPRB)::ZRI
REAL (KIND=JPRB)::ZSTAB
REAL (KIND=JPRB)::ZLOI
REAL (KIND=JPRB)::ZLOS
REAL (KIND=JPRB)::ZDID
REAL (KIND=JPRB)::ZCD
REAL (KIND=JPRB)::ZPD
REAL (KIND=JPRB)::ZDS
REAL (KIND=JPRB)::ZSTA
REAL (KIND=JPRB)::ZCD0
REAL (KIND=JPRB)::ZRZD
REAL (KIND=JPRB)::ZU
REAL (KIND=JPRB)::ZCIS
REAL (KIND=JPRB)::Z3BC
REAL (KIND=JPRB)::Z2B
REAL (KIND=JPRB)::ZUSURIC
REAL (KIND=JPRB)::ZMU
REAL (KIND=JPRB)::ZRVMD
REAL (KIND=JPRB)::ZCPVMD

#include "fcttrm.func.h"

JLON = KIDIA



ZEPS=EPSILON (1.0_JPRB)*100.0_JPRB
ZCPVMD=YDCST%RCPV-YDCST%RCPD
ZRVMD=YDCST%RV-YDCST%RD

ZDPHI =PAPHIF (JLON, KLEV)-PAPHI (JLON, KLEV)

ZUSURIC=YDML_PHY_MF%YRPHY0%USURIC*YDML_PHY_MF%YRPHY0%USURICL
Z2B=2.0_JPRB*YDML_PHY_MF%YRPHY0%EDB
Z3BC=3._JPRB*YDML_PHY_MF%YRPHY0%EDB*YDML_PHY_MF%YRPHY0%EDC

PZPCLS (JLON)=PAPRS (JLON, KLEV)+(PAPRSF (JLON, KLEV)-PAPRS (JLON, KLEV))*PDPHIT (JLON)/ZDPHI 
PLHS (JLON)=FOLH (PTS (JLON), 0.0_JPRB)
PCPS (JLON)=YDCST%RCPD+ZCPVMD*PQS (JLON)
ZRS =YDCST%RD+ZRVMD*PQS (JLON)
ZRTI =2.0_JPRB/(PR (JLON, KLEV)*PT (JLON, KLEV)+YDCST%RKAPPA*ZDPHI +ZRS *PTS (JLON))
ZSTABV =ZDPHI *(PR (JLON, KLEV)*PT (JLON, KLEV)+YDCST%RKAPPA*ZDPHI -ZRS *PTS (JLON))*ZRTI 

IF (YDML_PHY_MF%YRPHY%LCOEFK_TOMS) THEN
  ZCIS=PU (JLON, KLEV)**2+PV (JLON, KLEV)**2+(YDML_PHY_MF%YRPHY0%GCISMIN*ZDPHI /YDCST%RG)**2
  ZU=SQRT (ZCIS)
  ZRZD=1.0_JPRB+ZDPHI /PGZ0 (JLON)
  PCDN (JLON)=(YDML_PHY_MF%YRPHY0%VKARMN/LOG (ZRZD))**2
  ZMU=LOG (PGZ0 (JLON)/PGZ0H (JLON))
  ZCD0=(YDML_PHY_MF%YRPHY1%GCZ0H(0, 1)+ZMU*(YDML_PHY_MF%YRPHY1%GCZ0H(1, 1)+ZMU*(YDML_PHY_MF%YRPHY1&
  &%GCZ0H(2, 1)+ZMU*YDML_PHY_MF%YRPHY1%GCZ0H(3, 1))))/(1.5_JPRB*YDML_PHY_MF%YRPHY0%EDC)
  ZPD=(YDML_PHY_MF%YRPHY1%GCZ0H(0, 2)+ZMU*(YDML_PHY_MF%YRPHY1%GCZ0H(1, 2)+ZMU*(YDML_PHY_MF&
  &%YRPHY1%GCZ0H(2, 2)+ZMU*YDML_PHY_MF%YRPHY1%GCZ0H(3, 2))))-0.5_JPRB
  ZCD=ZCD0*ZRZD**ZPD
  ZSTA=ZSTABV /(1.0_JPRB+ZUSURIC*MAX (0.0_JPRB, ZSTABV )/ZCIS)
  ZSTAB=MAX (0.0_JPRB, SIGN (1.0_JPRB, ZSTA))
  ZDS=SQRT (ZCIS+YDML_PHY_MF%YRPHY0%EDD/YDML_PHY_MF%YRPHY0%EDK*ABS (ZSTA))
  ZDID=1.0_JPRB/(ZU+ZCD*Z3BC*PCDN (JLON)*SQRT (ABS (ZSTA)*ZRZD))
  ZLOS=ZCIS*ZDS/(ZU*ZDS+Z2B*ABS (ZSTA))
  ZLOI=ZU-Z2B*ZSTA*ZDID
  PCD (JLON)=(ZLOI+ZSTAB*(ZLOS-ZLOI))*PCDN (JLON)/ZU
  ZRI=ZSTA/ZCIS
  PMRIPP (JLON, KLEV)=SIGN (MAX (ZEPS, ABS (ZRI)), ZRI)
ENDIF



IF (LDCLS) THEN
  
  PNBVNO (JLON, KLEV)=ZSTABV /(PAPRS (JLON, KLEV)*ZRTI *ZDPHI )**2
  PGWDCS (JLON)=PAPRS (JLON, KLEV)*ZRTI 
  
ENDIF



END SUBROUTINE ACHMTLS_OPENACC
