
SUBROUTINE ACMICRO_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA,&
& KLEV, PNEBST, PT, PQL, PQI, PTS, PNEIJ, PLSM, PAUTOL, PAUTOI, YDSTACK)
!$ACC ROUTINE (ACMICRO_OPENACC) SEQ
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::PNEBST (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQI (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PNEIJ (KLON)
REAL (KIND=JPRB), INTENT (IN)::PLSM (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PAUTOL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PAUTOI (KLON, KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
REAL (KIND=JPRB)::ZFACICE
REAL (KIND=JPRB)::ZBETA
REAL (KIND=JPRB)::ZARG2
REAL (KIND=JPRB)::ZARG1
REAL (KIND=JPRB)::ZQCR
REAL (KIND=JPRB)::ZDUM
REAL (KIND=JPRB)::ZALPH
REAL (KIND=JPRB)::ZCAUT
REAL (KIND=JPRB)::ZQI
REAL (KIND=JPRB)::ZQL
fxtran_acdc_temp (REAL (KIND=JPRB), ZEFFA, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZDELT, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZAUTOI, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZAUTOL, (KLON, KLEV))
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON


YLSTACK = YDSTACK



IF (KIND (ZEFFA) == 8) THEN
    fxtran_acdc_alloc8 (ZEFFA)
ELSEIF (KIND (ZEFFA) == 4) THEN
    fxtran_acdc_alloc4 (ZEFFA)
ELSE
    STOP 1
ENDIF


IF (KIND (ZDELT) == 8) THEN
    fxtran_acdc_alloc8 (ZDELT)
ELSEIF (KIND (ZDELT) == 4) THEN
    fxtran_acdc_alloc4 (ZDELT)
ELSE
    STOP 1
ENDIF


IF (KIND (ZAUTOI) == 8) THEN
    fxtran_acdc_alloc8 (ZAUTOI)
ELSEIF (KIND (ZAUTOI) == 4) THEN
    fxtran_acdc_alloc4 (ZAUTOI)
ELSE
    STOP 1
ENDIF


IF (KIND (ZAUTOL) == 8) THEN
    fxtran_acdc_alloc8 (ZAUTOL)
ELSEIF (KIND (ZAUTOL) == 4) THEN
    fxtran_acdc_alloc4 (ZAUTOL)
ELSE
    STOP 1
ENDIF


JLON = KIDIA



ZARG1=2.0_JPRB*YDML_PHY_MF%YRPHY0%RQICRMAX*(1.0_JPRB-0.999_JPRB)/(YDML_PHY_MF&
&%YRPHY0%RQICRMAX-YDML_PHY_MF%YRPHY0%RQICRMIN)-1.0_JPRB
ZARG2=2.0_JPRB*(YDML_PHY_MF%YRPHY0%RQICRMAX-1.5_JPRB*YDML_PHY_MF%YRPHY0%RQICRMIN&
&)/(YDML_PHY_MF%YRPHY0%RQICRMAX-YDML_PHY_MF%YRPHY0%RQICRMIN)-1.0_JPRB
ZARG1=0.5_JPRB*LOG (ABS ((1.0_JPRB+ZARG1)/(1.0_JPRB-ZARG1)))
ZARG2=0.5_JPRB*LOG (ABS ((1.0_JPRB+ZARG2)/(1.0_JPRB-ZARG2)))
ZALPH=(ZARG1-ZARG2)/(YDML_PHY_MF%YRPHY0%RQICRT2-YDML_PHY_MF%YRPHY0%RQICRT1)
ZBETA=ZARG1-YDML_PHY_MF%YRPHY0%RQICRT2*ZALPH

DO JLEV=KTDIA, KLEV
  
  ZDELT (JLON, JLEV)=PT (JLON, JLEV)-YDCST%RTT
  ZEFFA (JLON, JLEV)=EXP (YDML_PHY_MF%YRPHY0%RAUTSBET*ZDELT (JLON, JLEV))
  
ENDDO


DO JLEV=KTDIA, KLEV
  
  ZQL=MAX (0.0_JPRB, PQL (JLON, JLEV)/PNEBST (JLON, JLEV))
  ZQI=MAX (0.0_JPRB, PQI (JLON, JLEV)/PNEBST (JLON, JLEV))
  ZCAUT=YDML_PHY_MF%YRPHY0%RAUTEFR
  ZDUM=(1.0_JPRB-EXP (-ZCAUT*YDML_PHY_MF%YRPHY2%TSPHY))*(ZQL&
  &-YDML_PHY_MF%YRPHY0%RQLCR)/YDML_PHY_MF%YRPHY2%TSPHY
  ZAUTOL (JLON, JLEV)=MAX (0.0_JPRB, ZDUM)
  ZCAUT=YDML_PHY_MF%YRPHY0%RAUTEFS*ZEFFA (JLON, JLEV)
  ZQCR=YDML_PHY_MF%YRPHY0%RQICRMAX-(YDML_PHY_MF%YRPHY0%RQICRMAX-YDML_PHY_MF%YRPHY0&
  &%RQICRMIN)*0.5_JPRB*(1.0_JPRB+TANH (ZALPH*ZDELT (JLON, JLEV)+ZBETA))
  ZFACICE=PLSM (JLON)*PNEIJ (JLON)+(1.0_JPRB-PLSM (JLON))*MAX (0.0_JPRB&
  &, SIGN (1.0_JPRB, YDML_PHY_MF%YRPHY1%TMERGL-PTS (JLON)))
  ZQCR=ZQCR*(1.0_JPRB-ZFACICE*(1.0_JPRB-YDML_PHY_MF%YRPHY0%RQICRSN))
  ZDUM=(1.0_JPRB-EXP (-ZCAUT*YDML_PHY_MF%YRPHY2%TSPHY))*(ZQI-ZQCR)/YDML_PHY_MF%YRPHY2%TSPHY
  ZAUTOI (JLON, JLEV)=MAX (0.0_JPRB, ZDUM)
  PAUTOL (JLON, JLEV)=ZAUTOL (JLON, JLEV)*PNEBST (JLON, JLEV)
  PAUTOI (JLON, JLEV)=ZAUTOI (JLON, JLEV)*PNEBST (JLON, JLEV)
  
ENDDO



END SUBROUTINE ACMICRO_OPENACC
