
SUBROUTINE ACNEBCOND_OPENACC (YDCST, YDRIP, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV&
&, LDREDPR, YDSTA, PAPHI, PAPHIF, PAPRSF, PCP, PR, PDELP, PQ, PQI, PQL, PQW, PT, PNCV,&
& PGM, PTS, PQCS, PNEBCOND, PHCRICS, PRHOUT, PQSATS, PRMF, PQCS0, PNEBS0, YDSTACK)
!$ACC ROUTINE (ACNEBCOND_OPENACC) SEQ
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB, JPRD

USE YOMCST,ONLY:TCST
USE YOMRIP,ONLY:TRIP
USE YOMSTA,ONLY:TSTA
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TRIP), INTENT (IN)::YDRIP
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
LOGICAL, INTENT (IN)::LDREDPR
TYPE (TSTA), INTENT (IN)::YDSTA
REAL (KIND=JPRB), INTENT (IN)::PAPHI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPHIF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PR (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQI (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQW (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PNCV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGM (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTS (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PQCS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PNEBCOND (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PHCRICS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQSATS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRMF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRHOUT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQCS0 (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PNEBS0 (KLON, KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
fxtran_acdc_temp (REAL (KIND=JPRB), ZLSTMP, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZHCUTMP, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZSHALTEMP, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZS, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZRHL, (KLON, KLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZQTOT, (KLON, KLEV))
REAL (KIND=JPRB)::ZMESHEXP 
REAL (KIND=JPRB)::ZS2 
REAL (KIND=JPRB)::ZS1 
REAL (KIND=JPRB)::ZRMF 
REAL (KIND=JPRB)::ZC 
REAL (KIND=JPRB)::ZB 
REAL (KIND=JPRB)::ZA 
REAL (KIND=JPRB)::ZNEB1 
REAL (KIND=JPRB)::ZSITER 
REAL (KIND=JPRB)::ZX0 
REAL (KIND=JPRB)::ZAW 
REAL (KIND=JPRB)::ZDC 
INTEGER (KIND=JPIM)::ILIQ 
INTEGER (KIND=JPIM)::JLEV2
INTEGER (KIND=JPIM)::ILEV
INTEGER (KIND=JPIM)::JITER
INTEGER (KIND=JPIM)::IITER
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
LOGICAL::LLWHOLE
REAL (KIND=JPRB)::ZZDIST2
REAL (KIND=JPRB)::ZLS
REAL (KIND=JPRB)::ZLV
REAL (KIND=JPRB)::ZLEFF
REAL (KIND=JPRB)::ZSIGS
REAL (KIND=JPRB)::ZTLIQ
REAL (KIND=JPRB)::ZRDSRV
REAL (KIND=JPRB)::ZSQRT6
REAL (KIND=JPRB)::ZFRACON
REAL (KIND=JPRB)::ZWEIGHT
REAL (KIND=JPRB)::ZADJI
REAL (KIND=JPRB)::ZADJL
REAL (KIND=JPRB)::ZCONI
REAL (KIND=JPRB)::ZCONL
REAL (KIND=JPRB)::ZTESTB
REAL (KIND=JPRB)::ZRMLOC
REAL (KIND=JPRB)::ZDQVN
REAL (KIND=JPRB)::ZQVN
REAL (KIND=JPRB)::ZNEBM1
REAL (KIND=JPRB)::ZALF
REAL (KIND=JPRB)::ZQI
REAL (KIND=JPRB)::ZQL
REAL (KIND=JPRB)::ZQ
REAL (KIND=JPRB)::ZQVCS
REAL (KIND=JPRB)::ZIRNEB
REAL (KIND=JPRB)::ZRNEB
REAL (KIND=JPRB)::ZNEBT
REAL (KIND=JPRB)::ZDENOM
REAL (KIND=JPRB)::ZESN
REAL (KIND=JPRB)::ZDESDTM
REAL (KIND=JPRB)::ZRHDIF
REAL (KIND=JPRB)::ZSTIMEINC
REAL (KIND=JPRB)::ZONEMRHCRIT
REAL (KIND=JPRB)::ZSIGMAZ
REAL (KIND=JPRB)::ZDRHDZ
REAL (KIND=JPRB)::ZRHIN
REAL (KIND=JPRB)::ZRHD
REAL (KIND=JPRB)::ZCLD
REAL (KIND=JPRB)::ZEPSILO
REAL (KIND=JPRB)::ZSIGMASTAB
REAL (KIND=JPRB)::ZSIGMA
REAL (KIND=JPRB)::ZTEST
REAL (KIND=JPRB)::ZZRHC
REAL (KIND=JPRB)::ZNIM
REAL (KIND=JPRB)::ZNCVNEB
REAL (KIND=JPRB)::ZDELTAP
REAL (KIND=JPRB)::ZDS
REAL (KIND=JPRB)::ZFACTC
REAL (KIND=JPRB)::ZFACTB
REAL (KIND=JPRB)::ZFACTA
REAL (KIND=JPRB)::ZFACT0
REAL (KIND=JPRB)::ZFACT
REAL (KIND=JPRB)::ZDCRI
REAL (KIND=JPRB)::ZDNEB
REAL (KIND=JPRB)::ZRAT2
REAL (KIND=JPRB)::ZNEB0
REAL (KIND=JPRB)::ZRATQ
REAL (KIND=JPRB)::ZRHC
REAL (KIND=JPRB)::ZQCST
REAL (KIND=JPRB)::ZMESH
REAL (KIND=JPRB)::ZLESEFS
REAL (KIND=JPRB)::ZLESEFR
REAL (KIND=JPRB)::ZLEN0
REAL (KIND=JPRB)::ZZ
REAL (KIND=JPRB)::ZTKLEV
REAL (KIND=JPRB)::ZALFI
REAL (KIND=JPRB)::ZQXRAL
REAL (KIND=JPRB)::ZDXN
REAL (KIND=JPRB)::ZXN
REAL (KIND=JPRB)::ZFAC
REAL (KIND=JPRB)::ZDNII
REAL (KIND=JPRB)::ZNPI
REAL (KIND=JPRB)::ZNI
REAL (KIND=JPRB)::ZESP
REAL (KIND=JPRB)::ZESATL
REAL (KIND=JPRB)::ZESAT
REAL (KIND=JPRB)::ZEPS5
REAL (KIND=JPRB)::ZEPS4
REAL (KIND=JPRB)::ZEPS3
REAL (KIND=JPRB)::ZEPS2
REAL (KIND=JPRB)::ZEPS1

#include "fctdoi.func.h"
#include "fcttrm.func.h"
#include "acnebsm_openacc.intfb.h"

YLSTACK = YDSTACK



IF (KIND (ZLSTMP) == 8) THEN
    fxtran_acdc_alloc8 (ZLSTMP)
ELSEIF (KIND (ZLSTMP) == 4) THEN
    fxtran_acdc_alloc4 (ZLSTMP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZHCUTMP) == 8) THEN
    fxtran_acdc_alloc8 (ZHCUTMP)
ELSEIF (KIND (ZHCUTMP) == 4) THEN
    fxtran_acdc_alloc4 (ZHCUTMP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZSHALTEMP) == 8) THEN
    fxtran_acdc_alloc8 (ZSHALTEMP)
ELSEIF (KIND (ZSHALTEMP) == 4) THEN
    fxtran_acdc_alloc4 (ZSHALTEMP)
ELSE
    STOP 1
ENDIF


IF (KIND (ZS) == 8) THEN
    fxtran_acdc_alloc8 (ZS)
ELSEIF (KIND (ZS) == 4) THEN
    fxtran_acdc_alloc4 (ZS)
ELSE
    STOP 1
ENDIF


IF (KIND (ZRHL) == 8) THEN
    fxtran_acdc_alloc8 (ZRHL)
ELSEIF (KIND (ZRHL) == 4) THEN
    fxtran_acdc_alloc4 (ZRHL)
ELSE
    STOP 1
ENDIF


IF (KIND (ZQTOT) == 8) THEN
    fxtran_acdc_alloc8 (ZQTOT)
ELSEIF (KIND (ZQTOT) == 4) THEN
    fxtran_acdc_alloc4 (ZQTOT)
ELSE
    STOP 1
ENDIF


JLON = KIDIA





IF (JPRB==JPRD) THEN
  ZEPS1=1.E-14_JPRB
  ZEPS5=1.E-12_JPRB
ELSE
  ZEPS1=1.E-06_JPRB
  ZEPS5=1.E-06_JPRB
ENDIF

ZEPS2=1.E-02_JPRB
ZEPS3=1.E-20_JPRB
ZEPS4=1.E-10_JPRB
ZSQRT6=SQRT (6._JPRB)
ZRDSRV=YDCST%RD/YDCST%RV
ZWEIGHT=1.0_JPRB-EXP (-YDML_PHY_MF%YRPHY2%TSPHY/YDML_PHY_MF%YRPHY0%ADJTAU)
ZQXRAL=YDML_PHY_MF%YRPHY0%QXRAL_ADJ
ZLESEFR=1._JPRB/YDML_PHY_MF%YRPHY0%SCLESPR**YDML_PHY_MF%YRPHY0%RHCEXPDX
ZLESEFS=1._JPRB/YDML_PHY_MF%YRPHY0%SCLESPS**YDML_PHY_MF%YRPHY0%RHCEXPDX
IITER=3

DO JLEV=KTDIA, KLEV
  
  PRMF (JLON, JLEV)=FONICE (PT (JLON, JLEV), YDML_PHY_MF%YRPHY0%RDTFAC)
  
ENDDO


IF (YDML_PHY_MF%YRPHY%LXRCDEV) THEN
  
  ZMESHEXP =(YDML_PHY_MF%YRPHY0%REFLRHC/(YDML_PHY_MF%YRPHY0&
  &%TEQH*PGM (JLON)))**YDML_PHY_MF%YRPHY0%RHCEXPDX

  

  DO JLEV=KTDIA, KLEV
    
    ZLEN0=1.0_JPRB/(PRMF (JLON, JLEV)*ZLESEFS+(1.0_JPRB-PRMF (JLON, JLEV))*ZLESEFR)
    PHCRICS (JLON, JLEV)=((YDML_PHY_MF%YRPHY0%HUCRED*YDML_PHY_MF%YRPHY0%RHUC (JLEV&
    &)+1.0_JPRB-YDML_PHY_MF%YRPHY0%HUCRED)*ZMESHEXP +ZLEN0)/(ZMESHEXP +ZLEN0)
  
  ENDDO

ENDIF


IF (YDML_PHY_MF%YRPHY%LSMGCDEV) THEN
  ZFACT0=(YDML_PHY_MF%YRPHY0%RETAMIN*(YDML_PHY_MF%YRPHY0%RETAMIN-1.0_JPRB))**2
  ZFACTA=(2.0_JPRB*YDML_PHY_MF%YRPHY0%RETAMIN-1.0_JPRB)
  ZFACTB=(1.0_JPRB-3._JPRB*YDML_PHY_MF%YRPHY0%RETAMIN**2)
  ZFACTC=(3._JPRB*YDML_PHY_MF%YRPHY0%RETAMIN-2.0_JPRB)*YDML_PHY_MF%YRPHY0%RETAMIN
  ZDCRI=(YDML_PHY_MF%YRPHY0%RHCRIT2-YDML_PHY_MF%YRPHY0%RHCRIT1)/ZFACT0
  
  ZFACT=ZDCRI*(1.0_JPRB-YDML_PHY_MF%YRPHY0%GRHCMOD*EXP &
  &(-1.0_JPRB/(YDML_PHY_MF%YRPHY0%TEQH*PGM (JLON))))
  ZA =ZFACTA*ZFACT
  ZB =ZFACTB*ZFACT
  ZC =ZFACTC*ZFACT

  

  DO JLEV=1, KLEV
    
    PHCRICS (JLON, JLEV)=YDML_PHY_MF%YRPHY0%RHCRIT2+YDSTA%SVETAF (JLEV&
    &)*(ZC +YDSTA%SVETAF (JLEV)*(ZB +YDSTA%SVETAF (JLEV)*ZA ))
  
  ENDDO

ENDIF


IF (YDML_PHY_MF%YRPHY%LXRCDEV) THEN
  ZALFI=1._JPRB/ZQXRAL

  DO JLEV=KTDIA, KLEV
    
    ZDC =1._JPRB-PHCRICS (JLON, JLEV)
    ZAW =ZALFI*SQRT (ZDC /PQW (JLON, JLEV))
    ZX0 =MAX (0._JPRB,(PQ (JLON, JLEV)+PQL (JLON, JLEV)+PQI &
    &(JLON, JLEV))/PQW (JLON, JLEV)-PHCRICS (JLON, JLEV))
    ZDNII=1._JPRB/SQRT (SQRT (PHCRICS (JLON, JLEV)))
    ZXN=PNCV (JLON, JLEV)*(ZDC +ZAW *ZDNII)
    ZDXN=(1._JPRB-PNCV (JLON, JLEV))*ZDC +ZAW *ZDNII*(1._JPRB+PNCV (JLON&
    &, JLEV)*(ZDNII-0.25_JPRB*ZDC /PHCRICS (JLON, JLEV)-1.5_JPRB))
    ZSITER =MAX (1._JPRB, MAX (0._JPRB,(1._JPRB+0.5_JPRB*(ZX0 -ZXN)/MAX (ZEPS1, ZDXN)))**2)

    

    DO JITER=1, IITER
      
      ZNCVNEB=1._JPRB-PNCV (JLON, JLEV)
      ZNI=1._JPRB-(1._JPRB/ZSITER )
      ZNIM=1._JPRB-(ZNCVNEB/ZSITER )
      ZNPI=1._JPRB-ZDC *(1._JPRB/ZSITER )
      ZDNII=1._JPRB/(SQRT (SQRT (ZNPI))-ZNI)
      ZFAC=ZAW /(ZDC *SQRT (ZSITER ))
      ZXN=ZDC *ZNIM*(1._JPRB+(ZFAC*ZDNII))
      ZDXN=(ZDC /ZSITER **2)*(ZNCVNEB+(ZFAC*ZDNII)*(ZNCVNEB+ZNIM*(ZDNII*(1._JPRB&
      &-0.25_JPRB*ZDC *SQRT (SQRT (ZNPI))/ZNPI)-0.5_JPRB*ZSITER )))
      ZSITER =MAX (1._JPRB, MAX (0._JPRB,(ZSITER +0.5_JPRB*(ZX0 -ZXN)/MAX (ZEPS1, ZDXN)))**2/ZSITER )
    
    ENDDO

    
    PNEBCOND (JLON, JLEV)=1._JPRB-(1._JPRB/ZSITER )
    PQSATS (JLON, JLEV)=PQW (JLON, JLEV)
    PRHOUT (JLON, JLEV)=PQ (JLON, JLEV)/PQSATS (JLON, JLEV)
    PNEBS0 (JLON, JLEV)=MIN (1.0_JPRB-ZEPS1, MAX (PNEBCOND (JLON, JLEV), ZEPS1))
  
  ENDDO


  DO JLEV=KTDIA, KLEV
    
    ZNEBT=PNEBCOND (JLON, JLEV)+PNCV (JLON, JLEV)-PNEBCOND (JLON, JLEV)*PNCV (JLON, JLEV)
    ZZ=MAX (0.0_JPRB, SIGN (1.0_JPRB, ZNEBT-ZEPS4))
    ZRNEB=ZZ*PNEBCOND (JLON, JLEV)/(ZNEBT+(1.0_JPRB-ZZ))
    ZZ=MAX (0.0_JPRB, SIGN (1.0_JPRB, PNEBCOND (JLON, JLEV)-ZEPS4))
    ZIRNEB=ZZ*ZNEBT/(PNEBCOND (JLON, JLEV)+(1.0_JPRB-ZZ))
    ZQVCS=MAX (0.0_JPRB, PQ (JLON, JLEV)-PQW (JLON, JLEV)*(PNEBCOND (JLON,&
    & JLEV)+PNCV (JLON, JLEV)-PNEBCOND (JLON, JLEV)*PNCV (JLON, JLEV)))
    ZQ=(PQ (JLON, JLEV)-ZQVCS)*ZRNEB+ZQVCS/MAX (ZEPS4, 1.0_JPRB-PNCV (JLON, JLEV))
    ZADJL=ZWEIGHT*((1.0_JPRB-PRMF (JLON, JLEV))*(PQL (JLON, JLEV)+PQI (JLON, JLEV))-PQL (JLON, JLEV))
    ZQL=(PQL (JLON, JLEV)+ZADJL)*ZRNEB
    ZADJI=ZWEIGHT*(PRMF (JLON, JLEV)*(PQL (JLON, JLEV)+PQI (JLON, JLEV))-PQI (JLON, JLEV))
    ZQI=(PQI (JLON, JLEV)+ZADJI)*ZRNEB
    ZALF=ZQI/MAX (ZEPS4, ZQL+ZQI)
    ZNEBM1=1.0_JPRB-PNEBCOND (JLON, JLEV)
    ZQVN=PQW (JLON, JLEV)*(1.0_JPRB+(PHCRICS (JLON, JLEV)-1.0_JPRB)*ZNEBM1)
    ZDQVN=ZQ-ZQVN
    ZTEST=MAX (0.0_JPRB, SIGN (1.0_JPRB, ZQVN-(ZQ+ZQL+ZQI)))
    ZTESTB=MAX (0.0_JPRB, SIGN (1.0_JPRB, ZDQVN))
    ZRMLOC=(1.0_JPRB-ZTESTB)*ZALF+ZTESTB*PRMF (JLON, JLEV)
    ZCONL=(1.0_JPRB-ZRMLOC)*(1.0_JPRB-ZTEST)*ZDQVN-ZTEST*ZQL
    ZCONI=ZRMLOC*(1.0_JPRB-ZTEST)*ZDQVN-ZTEST*ZQI
    ZCONL=(1.0_JPRB-PNCV (JLON, JLEV))*ZCONL
    ZCONI=(1.0_JPRB-PNCV (JLON, JLEV))*ZCONI
    PQCS (JLON, JLEV)=(MAX (0.0_JPRB, ZQL+ZCONL)+MAX (0.0_JPRB, ZQI+ZCONI))*ZIRNEB
    PQCS0 (JLON, JLEV)=PQCS (JLON, JLEV)
  
  ENDDO

ENDIF


IF (YDML_PHY_MF%YRPHY%LSMGCDEV) THEN

  DO JLEV=KTDIA, KLEV-1
    
    ZQTOT (JLON, JLEV)=PQI (JLON, JLEV)+PQL (JLON, JLEV)+PQ (JLON, JLEV)
    ZS (JLON, JLEV)=PCP (JLON, JLEV)*PT (JLON, JLEV)+PAPHIF (JLON, JLEV)
    ZESATL=FOEW (PT (JLON, JLEV), 0.0_JPRB)
    ZESAT=ZESATL*(1.0_JPRB-PRMF (JLON, JLEV))+FOEW (PT (JLON, JLEV), 1.0_JPRB)*PRMF (JLON, JLEV)
    ZESP=ZESATL/PAPRSF (JLON, JLEV)
    ZRHL (JLON, JLEV)=ZQTOT (JLON, JLEV)/FOQS (ZESP)
    ZESP=ZESAT/PAPRSF (JLON, JLEV)
    PQSATS (JLON, JLEV)=FOQS (ZESP)
  
  ENDDO


  

  IF (YDML_PHY_MF%YRPHY%NSMTBOT==0) THEN
    ZTKLEV=(PTS (JLON)+PT (JLON, KLEV))*0.5_JPRB
  ELSE
    ZTKLEV=PT (JLON, KLEV)
  ENDIF

  ZRMF =PRMF (JLON, KLEV)
  PRMF (JLON, KLEV)=FONICE (ZTKLEV, YDML_PHY_MF%YRPHY0%RDTFAC)
  ZQTOT (JLON, KLEV)=PQI (JLON, KLEV)+PQL (JLON, KLEV)+PQ (JLON, KLEV)
  ZS (JLON, KLEV)=PCP (JLON, KLEV)*ZTKLEV+PAPHIF (JLON, KLEV)
  ZESATL=FOEW (ZTKLEV, 0.0_JPRB)
  ZESAT=ZESATL*(1.0_JPRB-PRMF (JLON, KLEV))+FOEW (ZTKLEV, 1.0_JPRB)*PRMF (JLON, KLEV)
  ZESP=ZESATL/PAPRSF (JLON, KLEV)
  ZRHL (JLON, KLEV)=ZQTOT (JLON, KLEV)/FOQS (ZESP)
  ZESP=ZESAT/PAPRSF (JLON, KLEV)
  PQSATS (JLON, KLEV)=FOQS (ZESP)

  

  IF (YDML_PHY_MF%YRPHY%LSMTPS) THEN

    DO JLEV=KTDIA, KLEV
      
      ZS1 =(ZQTOT (JLON, JLEV)/PQSATS (JLON, JLEV))*PDELP (JLON, JLEV)
      ZS2 =PDELP (JLON, JLEV)
      ILIQ =MAX (0, SIGN (1, 1-NINT (1000._JPRB*PRMF (JLON, JLEV))))
      
      ILEV=MIN (JLEV+YDML_PHY_MF%YRPHY0%NSMTPB, KLEV)

      DO JLEV2=JLEV+1, ILEV
        
        ZDS=ZS (JLON, JLEV2)-ZS (JLON, JLEV)
        ZDELTAP=MAX (0.0_JPRB, SIGN (1.0_JPRB, ZDS))*PDELP (JLON, JLEV2)
        ZS1 =ZS1 +(ZDELTAP*ILIQ )*ZRHL (JLON, JLEV2)
        ZS2 =ZS2 +(ZDELTAP*ILIQ )
      
      ENDDO

      ILEV=MAX (JLEV-YDML_PHY_MF%YRPHY0%NSMTPA, KTDIA)

      DO JLEV2=ILEV, JLEV-1
        
        ZDS=ZS (JLON, JLEV)-ZS (JLON, JLEV2)
        ZDELTAP=MAX (0.0_JPRB, SIGN (1.0_JPRB, ZDS))*PDELP (JLON, JLEV2)
        ZS1 =ZS1 +(ZDELTAP*ILIQ )*ZRHL (JLON, JLEV2)
        ZS2 =ZS2 +(ZDELTAP*ILIQ )
      
      ENDDO

      
      ZZ=MAX (0.0_JPRB, SIGN (1.0_JPRB, ZS1 -ZEPS1))*MAX (0.0_JPRB&
      &, SIGN (1.0_JPRB, ZQTOT (JLON, JLEV)-ZEPS1))
      PQSATS (JLON, JLEV)=ZZ*ZS2 /(ZS1 +(1.0_JPRB-ZZ))*ZQTOT&
      & (JLON, JLEV)+(1.0_JPRB-ZZ)*PQSATS (JLON, JLEV)
    
    ENDDO

  ENDIF

  
  PRMF (JLON, KLEV)=ZRMF 

  

  DO JLEV=KTDIA, KLEV
    
    ZQCST=PQI (JLON, JLEV)+PQL (JLON, JLEV)
    ZRHC=PHCRICS (JLON, JLEV)
    ZRATQ=ZQTOT (JLON, JLEV)/PQSATS (JLON, JLEV)
    ZZRHC=MIN (ZRHC, 1.0_JPRB-ZEPS1)
    ZRATQ=MAX (ZZRHC, MIN (2.0_JPRB-ZZRHC, ZRATQ))
    ZRAT2=(ZRATQ-1.0_JPRB)/(1.0_JPRB-ZZRHC)
    ZLV=FOLH (PT (JLON, JLEV), 0._JPRB)
    ZLS=FOLH (PT (JLON, JLEV), 1._JPRB)
    ZLEFF=ZLV*(1.0_JPRB-PRMF (JLON, JLEV))+ZLS*PRMF (JLON, JLEV)
    ZTLIQ=PT (JLON, JLEV)-(ZLV*PQL (JLON, JLEV)+ZLS*PQI (JLON, JLEV))/PCP (JLON, JLEV)
    ZSIGS=(1.0_JPRB-ZRHC)/ZSQRT6*PQSATS (JLON, JLEV)/(1.0_JPRB+ZLEFF*ZLEFF*PQSATS&
    & (JLON, JLEV)*ZRDSRV/PR (JLON, JLEV)/ZTLIQ/ZTLIQ/PCP (JLON, JLEV))
    ZTEST=MAX (0.0_JPRB, SIGN (1.0_JPRB, ZRATQ-1.0_JPRB))
    PNEBCOND (JLON, JLEV)=ZTEST*(1.0_JPRB-0.5_JPRB*(1.0_JPRB-ZRAT2&
    &)**2)+(1.0_JPRB-ZTEST)*(0.5_JPRB*(1.0_JPRB+ZRAT2)**2)
    PQCS (JLON, JLEV)=(ZTEST*(6.0_JPRB*ZRAT2+(1.0_JPRB-ZRAT2&
    &)**3)+(1.0_JPRB-ZTEST)*(1.0_JPRB+ZRAT2)**3)/ZSQRT6
    PQCS (JLON, JLEV)=PQCS (JLON, JLEV)*ZSIGS
    ZNEBT=PNEBCOND (JLON, JLEV)+PNCV (JLON, JLEV)-PNEBCOND (JLON, JLEV)*PNCV (JLON, JLEV)
    ZZ=MAX (0.0_JPRB, SIGN (1.0_JPRB, ZNEBT-ZEPS1))
    ZFRACON=ZZ*PNCV (JLON, JLEV)/(ZNEBT+(1.0_JPRB-ZZ))
    PQCS (JLON, JLEV)=(PQCS (JLON, JLEV)**2+(ZQCST*ZFRACON&
    &)**2)/MAX (ZEPS1,(PQCS (JLON, JLEV)+ZQCST*ZFRACON))
    PQCS0 (JLON, JLEV)=PQCS (JLON, JLEV)
    PNEBCOND (JLON, JLEV)=MAX (PNEBCOND (JLON, JLEV), ZEPS2&
    &*MAX (0.0_JPRB, SIGN (1.0_JPRB, ZQCST-ZEPS3)))
    PNEBCOND (JLON, JLEV)=PNEBCOND (JLON, JLEV)/(1.0_JPRB+(PAPHI (JLON&
    &, JLEV-1)-PAPHI (JLON, JLEV))/YDML_PHY_MF%YRPHY0%RDPHIC)
    PNEBS0 (JLON, JLEV)=MIN (1.0_JPRB-ZEPS1, MAX (PNEBCOND (JLON, JLEV), ZEPS1))
    PRHOUT (JLON, JLEV)=PQ (JLON, JLEV)/PQSATS (JLON, JLEV)
  
  ENDDO


  IF (YDML_PHY_MF%YRPHY%NSMDNEB==1) THEN
    
    ZNEB1 =0._JPRB

    

    DO JLEV=KTDIA, KLEV-1
      
      ZNEB0=0.5_JPRB*(PNEBCOND (JLON, JLEV)+PNEBCOND (JLON, JLEV+1))
      PNEBCOND (JLON, JLEV)=(ZNEB1 +ZNEB0+PNEBCOND (JLON, JLEV)*2.0_JPRB)*0.25_JPRB
      ZNEB1 =ZNEB0
      PNEBS0 (JLON, JLEV)=MIN (1.0_JPRB-ZEPS1, MAX (PNEBCOND (JLON, JLEV), ZEPS1))
    
    ENDDO

    
    ZNEB0=PNEBCOND (JLON, KLEV)
    PNEBCOND (JLON, KLEV)=(ZNEB1 +ZNEB0+PNEBCOND (JLON, KLEV)*2.0_JPRB)*0.25_JPRB
    PNEBS0 (JLON, KLEV)=MIN (1.0_JPRB-ZEPS1, MAX (PNEBCOND (JLON, KLEV), ZEPS1))
  
  ELSEIF (YDML_PHY_MF%YRPHY%NSMDNEB==2) THEN
    
    ZNEB1 =0._JPRB

    

    DO JLEV=KTDIA, KLEV
      
      ZNEB0=PNEBCOND (JLON, JLEV)
      ZDNEB=ZNEB0-ZNEB1 
      ZNEB1 =ZNEB1 +SIGN (MIN (ABS (ZDNEB), YDML_PHY_MF%YRPHY0%RSMDNEBX), ZDNEB)
      PNEBCOND (JLON, JLEV)=ZNEB1 
      PNEBS0 (JLON, JLEV)=MIN (1.0_JPRB-ZEPS1, MAX (PNEBCOND (JLON, JLEV), ZEPS1))
    
    ENDDO

  ENDIF

ENDIF


IF (YDML_PHY_MF%YRPHY%LSMITH_CDEV) THEN
  CALL ACNEBSM_OPENACC (YDCST, YDML_PHY_MF%YRPHY0, KIDIA, KFDIA, KLON, KTDIA, KLEV, PT, PQ, PQL, PQI&
  &, PAPHI, PAPRSF, PCP, PR, PGM, YDSTA, PQCS, PNEBCOND, PHCRICS, PRMF, PQSATS, YDSTACK=YLSTACK)

  IF (YDML_PHY_MF%YRPHY%L3MT) THEN

    DO JLEV=KTDIA, KLEV
      
      PNEBCOND (JLON, JLEV)=MAX (PNEBCOND (JLON, JLEV), ZEPS2*MAX&
      & (0.0_JPRB, SIGN (1.0_JPRB, PQCS (JLON, JLEV)-ZEPS3)))
      PNEBCOND (JLON, JLEV)=PNEBCOND (JLON, JLEV)/(1.0_JPRB+(PAPHI (JLON&
      &, JLEV-1)-PAPHI (JLON, JLEV))/YDML_PHY_MF%YRPHY0%RDPHIC)
      PNEBS0 (JLON, JLEV)=MIN (1.0_JPRB-ZEPS1, MAX (PNEBCOND (JLON, JLEV), ZEPS1))
      PNEBCOND (JLON, JLEV)=MIN (1.0_JPRB, MAX (PNEBCOND (JLON, JLEV), 0.0_JPRB))
      ZNEBT=PNEBCOND (JLON, JLEV)+PNCV (JLON, JLEV)-PNEBCOND (JLON, JLEV)*PNCV (JLON, JLEV)
      ZQCST=PQI (JLON, JLEV)+PQL (JLON, JLEV)
      PQCS (JLON, JLEV)=(ZQCST*PNCV (JLON, JLEV)+PQCS (JLON, JLEV)*(1._JPRB&
      &-PNCV (JLON, JLEV))*PNEBCOND (JLON, JLEV))/MAX (ZEPS4, ZNEBT)
      PQCS0 (JLON, JLEV)=PQCS (JLON, JLEV)
      PRHOUT (JLON, JLEV)=PQ (JLON, JLEV)/PQSATS (JLON, JLEV)
    
    ENDDO

  ELSE

    DO JLEV=KTDIA, KLEV
      
      PNEBCOND (JLON, JLEV)=MIN (1.0_JPRB-ZEPS5, MAX (PNEBCOND (JLON, JLEV), ZEPS5))
      PNEBS0 (JLON, JLEV)=PNEBCOND (JLON, JLEV)
      PQCS0 (JLON, JLEV)=PQCS (JLON, JLEV)
      PRHOUT (JLON, JLEV)=PQ (JLON, JLEV)/PQSATS (JLON, JLEV)
    
    ENDDO

  ENDIF

ENDIF



END SUBROUTINE ACNEBCOND_OPENACC
