SUBROUTINE APL_ARPEGE_MWAVE_PARALLEL (YDCPG_MISC, YDMF_PHYS, YDCPG_BNDS, YDCPG_OPTS, YDPHYSMWAVE)

USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE YOMHOOK,ONLY:DR_HOOK, JPHOOK, LHOOK
USE YOE_PHYS_MWAVE,ONLY:TEPHYSMWAVE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE PARKIND1
USE FXTRAN_ACDC_ARRAY_COPY_MOD
USE FXTRAN_ACDC_GPUMEM_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE


TYPE (CPG_MISC_TYPE), INTENT (IN)::YDCPG_MISC
TYPE (MF_PHYS_TYPE), INTENT (IN)::YDMF_PHYS
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (TEPHYSMWAVE), INTENT (INOUT)::YDPHYSMWAVE
CLASS (FIELD_3RB), POINTER :: YL_ZCOVPTOT
REAL (KIND=JPRB), POINTER::ZCOVPTOT (:,:,:)
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JLON
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
INTEGER(KIND=JPIM) :: JBLK
TYPE(CPG_BNDS_TYPE) :: YLCPG_BNDS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_FIELD_API
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_PARALLEL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_COMPUTE
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLOFFSET
REAL (KIND=JPRB), POINTER :: Z_YDCPG_MISC_NEB(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDCPG_MISC_QICE(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDCPG_MISC_QLI(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FPLCL(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FPLCN(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FPLSL(:,:,:)
REAL (KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_FPLSN(:,:,:)
#include "abor1.intfb.h"
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL', 0, ZHOOK_HANDLE)

CALL FXTRAN_ACDC_GPUMEMSTAT (__FILE__, __LINE__, "BEGIN")


IF (LHOOK) CALL DR_HOOK ('CREATE_TEMPORARIES',0,ZHOOK_HANDLE_FIELD_API)
CALL FIELD_NEW (YL_ZCOVPTOT, UBOUNDS=[YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, YDCPG_OPTS&
&%JBLKMAX], LBOUNDS=[1, 1, YDCPG_OPTS%JBLKMIN], PERSISTENT=.TRUE.)
IF (LHOOK) CALL DR_HOOK ('CREATE_TEMPORARIES',1,ZHOOK_HANDLE_FIELD_API)

IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0',0,ZHOOK_HANDLE_PARALLEL)

IF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMP','APL_ARPEGE_MWAVE_PARALLEL:0')) THEN
  
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
  ZCOVPTOT => GET_HOST_DATA_RDWR (YL_ZCOVPTOT)
  Z_YDCPG_MISC_NEB => GET_HOST_DATA_RDONLY (YDCPG_MISC%F_NEB)
  Z_YDCPG_MISC_QICE => GET_HOST_DATA_RDONLY (YDCPG_MISC%F_QICE)
  Z_YDCPG_MISC_QLI => GET_HOST_DATA_RDONLY (YDCPG_MISC%F_QLI)
  Z_YDMF_PHYS_OUT_FPLCL => GET_HOST_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLCL)
  Z_YDMF_PHYS_OUT_FPLCN => GET_HOST_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLCN)
  Z_YDMF_PHYS_OUT_FPLSL => GET_HOST_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLSL)
  Z_YDMF_PHYS_OUT_FPLSN => GET_HOST_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLSN)
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
  
  CALL YLCPG_BNDS%INIT (YDCPG_OPTS)
  !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JLON, YDPHYSMWAVE) FIRSTPRIVATE (YLCPG_BNDS)

  DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
    CALL YLCPG_BNDS%UPDATE (JBLK)
    
    ZCOVPTOT (:,:, JBLK)=0.0_JPRB

    DO JLEV=1, YDCPG_OPTS%KFLEVG

      DO JLON=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA

        IF (JLEV>0) THEN

          IF (ABS (0.5*(Z_YDMF_PHYS_OUT_FPLSL (JLON, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSL (JLON, JLEV-1, JBLK))+0&
            &.5*(Z_YDMF_PHYS_OUT_FPLSN (JLON, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSN (JLON, JLEV-1, JBLK))+0.5*(Z_YDMF_PHYS_OUT_FPLCN&
            & (JLON, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLCN (JLON, JLEV-1, JBLK))+0.5*(Z_YDMF_PHYS_OUT_FPLCL (JLON, JLEV&
            &, JBLK)+Z_YDMF_PHYS_OUT_FPLCL (JLON, JLEV-1, JBLK)))>=1.E-25_JPRB) THEN

            IF (JLEV==1_JPIM) THEN
              ZCOVPTOT (JLON, JLEV, JBLK)=1.0_JPRB-((1.0_JPRB-ZCOVPTOT (JLON, JLEV, JBLK&
              &))*(1.0_JPRB-Z_YDCPG_MISC_NEB (JLON, JLEV, JBLK))/1.E-06_JPRB)
            ELSE
              ZCOVPTOT (JLON, JLEV, JBLK)=1.0_JPRB-((1.0_JPRB-ZCOVPTOT (JLON, JLEV-1, JBLK))*(1.0_JPRB&
              &-MAX (Z_YDCPG_MISC_NEB (JLON, JLEV, JBLK), Z_YDCPG_MISC_NEB (JLON, JLEV-1, JBLK)))/&
              &(1.0_JPRB-MIN (Z_YDCPG_MISC_NEB (JLON, JLEV-1, JBLK), 1.0_JPRB-1.E-06_JPRB)))
            ENDIF

            ZCOVPTOT (JLON, JLEV, JBLK)=MAX (ZCOVPTOT (JLON, JLEV, JBLK), 0.1_JPRB)
          ENDIF

        ENDIF

        YDPHYSMWAVE%P (JLON, JLEV, 1)=Z_YDCPG_MISC_QLI (JLON, JLEV, JBLK)
        YDPHYSMWAVE%P (JLON, JLEV, 2)=Z_YDCPG_MISC_QICE (JLON, JLEV, JBLK)
        YDPHYSMWAVE%P (JLON, JLEV, 3)=Z_YDCPG_MISC_NEB (JLON, JLEV, JBLK)
        YDPHYSMWAVE%P (JLON, JLEV, 4)=0.5*(Z_YDMF_PHYS_OUT_FPLSL (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSL (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 5)=0.5*(Z_YDMF_PHYS_OUT_FPLSN (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSN (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 6)=0.5*(Z_YDMF_PHYS_OUT_FPLCL (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLCL (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 7)=0.5*(Z_YDMF_PHYS_OUT_FPLCN (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLCN (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 8)=ZCOVPTOT (JLON, JLEV, JBLK)
      ENDDO

    ENDDO


    DO JLON=YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA
      YDPHYSMWAVE%P (JLON, 1, 9)=0._JPRB
      YDPHYSMWAVE%P (JLON, 2, 9)=0._JPRB
      YDPHYSMWAVE%P (JLON, 3:YDCPG_OPTS%KFLEVG, 9)=0._JPRB
    ENDDO

  ENDDO

  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

  IF (FXTRAN_ACDC_LSYNCHOST ('APL_ARPEGE_MWAVE_PARALLEL:0')) THEN
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
    ZCOVPTOT => GET_HOST_DATA_RDWR (YL_ZCOVPTOT)
    Z_YDCPG_MISC_NEB => GET_HOST_DATA_RDWR (YDCPG_MISC%F_NEB)
    Z_YDCPG_MISC_QICE => GET_HOST_DATA_RDWR (YDCPG_MISC%F_QICE)
    Z_YDCPG_MISC_QLI => GET_HOST_DATA_RDWR (YDCPG_MISC%F_QLI)
    Z_YDMF_PHYS_OUT_FPLCL => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLCL)
    Z_YDMF_PHYS_OUT_FPLCN => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLCN)
    Z_YDMF_PHYS_OUT_FPLSL => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLSL)
    Z_YDMF_PHYS_OUT_FPLSN => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLSN)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ENDIF

  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
  ZCOVPTOT => NULL ()
  Z_YDCPG_MISC_NEB => NULL ()
  Z_YDCPG_MISC_QICE => NULL ()
  Z_YDCPG_MISC_QLI => NULL ()
  Z_YDMF_PHYS_OUT_FPLCL => NULL ()
  Z_YDMF_PHYS_OUT_FPLCN => NULL ()
  Z_YDMF_PHYS_OUT_FPLSL => NULL ()
  Z_YDMF_PHYS_OUT_FPLSN => NULL ()
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
  
  
ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPSINGLECOLUMN','APL_ARPEGE_MWAVE_PARALLEL:0')) THEN
  
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
  ZCOVPTOT => GET_HOST_DATA_RDWR (YL_ZCOVPTOT)
  Z_YDCPG_MISC_NEB => GET_HOST_DATA_RDONLY (YDCPG_MISC%F_NEB)
  Z_YDCPG_MISC_QICE => GET_HOST_DATA_RDONLY (YDCPG_MISC%F_QICE)
  Z_YDCPG_MISC_QLI => GET_HOST_DATA_RDONLY (YDCPG_MISC%F_QLI)
  Z_YDMF_PHYS_OUT_FPLCL => GET_HOST_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLCL)
  Z_YDMF_PHYS_OUT_FPLCN => GET_HOST_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLCN)
  Z_YDMF_PHYS_OUT_FPLSL => GET_HOST_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLSL)
  Z_YDMF_PHYS_OUT_FPLSN => GET_HOST_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLSN)
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
  
  !$OMP PARALLEL DO PRIVATE (JBLK, JLEV, JLON, YDPHYSMWAVE, YLCPG_BNDS)

  DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

    

    

    DO JLON = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
      YLCPG_BNDS%KIDIA = JLON
      YLCPG_BNDS%KFDIA = JLON
      
      ZCOVPTOT (JLON,:, JBLK)=0.0_JPRB

      DO JLEV=1, YDCPG_OPTS%KFLEVG

        

        IF (JLEV>0) THEN

          IF (ABS (0.5*(Z_YDMF_PHYS_OUT_FPLSL (JLON, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSL (JLON, JLEV-1, JBLK))+0&
            &.5*(Z_YDMF_PHYS_OUT_FPLSN (JLON, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSN (JLON, JLEV-1, JBLK))+0.5*(Z_YDMF_PHYS_OUT_FPLCN&
            & (JLON, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLCN (JLON, JLEV-1, JBLK))+0.5*(Z_YDMF_PHYS_OUT_FPLCL (JLON, JLEV&
            &, JBLK)+Z_YDMF_PHYS_OUT_FPLCL (JLON, JLEV-1, JBLK)))>=1.E-25_JPRB) THEN

            IF (JLEV==1_JPIM) THEN
              ZCOVPTOT (JLON, JLEV, JBLK)=1.0_JPRB-((1.0_JPRB-ZCOVPTOT (JLON, JLEV, JBLK&
              &))*(1.0_JPRB-Z_YDCPG_MISC_NEB (JLON, JLEV, JBLK))/1.E-06_JPRB)
            ELSE
              ZCOVPTOT (JLON, JLEV, JBLK)=1.0_JPRB-((1.0_JPRB-ZCOVPTOT (JLON, JLEV-1, JBLK))*(1.0_JPRB&
              &-MAX (Z_YDCPG_MISC_NEB (JLON, JLEV, JBLK), Z_YDCPG_MISC_NEB (JLON, JLEV-1, JBLK)))/&
              &(1.0_JPRB-MIN (Z_YDCPG_MISC_NEB (JLON, JLEV-1, JBLK), 1.0_JPRB-1.E-06_JPRB)))
            ENDIF

            ZCOVPTOT (JLON, JLEV, JBLK)=MAX (ZCOVPTOT (JLON, JLEV, JBLK), 0.1_JPRB)
          ENDIF

        ENDIF

        YDPHYSMWAVE%P (JLON, JLEV, 1)=Z_YDCPG_MISC_QLI (JLON, JLEV, JBLK)
        YDPHYSMWAVE%P (JLON, JLEV, 2)=Z_YDCPG_MISC_QICE (JLON, JLEV, JBLK)
        YDPHYSMWAVE%P (JLON, JLEV, 3)=Z_YDCPG_MISC_NEB (JLON, JLEV, JBLK)
        YDPHYSMWAVE%P (JLON, JLEV, 4)=0.5*(Z_YDMF_PHYS_OUT_FPLSL (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSL (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 5)=0.5*(Z_YDMF_PHYS_OUT_FPLSN (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSN (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 6)=0.5*(Z_YDMF_PHYS_OUT_FPLCL (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLCL (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 7)=0.5*(Z_YDMF_PHYS_OUT_FPLCN (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLCN (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 8)=ZCOVPTOT (JLON, JLEV, JBLK)
      
      ENDDO

      
      YDPHYSMWAVE%P (JLON, 1, 9)=0._JPRB
      YDPHYSMWAVE%P (JLON, 2, 9)=0._JPRB
      YDPHYSMWAVE%P (JLON, 3:YDCPG_OPTS%KFLEVG, 9)=0._JPRB
    
    ENDDO

  ENDDO

  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

  IF (FXTRAN_ACDC_LSYNCHOST ('APL_ARPEGE_MWAVE_PARALLEL:0')) THEN
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
    ZCOVPTOT => GET_HOST_DATA_RDWR (YL_ZCOVPTOT)
    Z_YDCPG_MISC_NEB => GET_HOST_DATA_RDWR (YDCPG_MISC%F_NEB)
    Z_YDCPG_MISC_QICE => GET_HOST_DATA_RDWR (YDCPG_MISC%F_QICE)
    Z_YDCPG_MISC_QLI => GET_HOST_DATA_RDWR (YDCPG_MISC%F_QLI)
    Z_YDMF_PHYS_OUT_FPLCL => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLCL)
    Z_YDMF_PHYS_OUT_FPLCN => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLCN)
    Z_YDMF_PHYS_OUT_FPLSL => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLSL)
    Z_YDMF_PHYS_OUT_FPLSN => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLSN)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ENDIF

  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
  ZCOVPTOT => NULL ()
  Z_YDCPG_MISC_NEB => NULL ()
  Z_YDCPG_MISC_QICE => NULL ()
  Z_YDCPG_MISC_QLI => NULL ()
  Z_YDMF_PHYS_OUT_FPLCL => NULL ()
  Z_YDMF_PHYS_OUT_FPLCN => NULL ()
  Z_YDMF_PHYS_OUT_FPLSL => NULL ()
  Z_YDMF_PHYS_OUT_FPLSN => NULL ()
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
  
  
ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCSINGLECOLUMN','APL_ARPEGE_MWAVE_PARALLEL:0')) THEN
  
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
  ZCOVPTOT => GET_DEVICE_DATA_RDWR (YL_ZCOVPTOT)
  Z_YDCPG_MISC_NEB => GET_DEVICE_DATA_RDONLY (YDCPG_MISC%F_NEB)
  Z_YDCPG_MISC_QICE => GET_DEVICE_DATA_RDONLY (YDCPG_MISC%F_QICE)
  Z_YDCPG_MISC_QLI => GET_DEVICE_DATA_RDONLY (YDCPG_MISC%F_QLI)
  Z_YDMF_PHYS_OUT_FPLCL => GET_DEVICE_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLCL)
  Z_YDMF_PHYS_OUT_FPLCN => GET_DEVICE_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLCN)
  Z_YDMF_PHYS_OUT_FPLSL => GET_DEVICE_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLSL)
  Z_YDMF_PHYS_OUT_FPLSN => GET_DEVICE_DATA_RDONLY (YDMF_PHYS%OUT%F_FPLSN)
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
  
  
    !$ACC PARALLEL LOOP GANG &
    !$ACC&PRESENT (YDCPG_OPTS, YFXTRAN_ACDC_STACK, ZCOVPTOT, Z_YDCPG_MISC_NEB, &
    !$ACC&         Z_YDCPG_MISC_QICE, Z_YDCPG_MISC_QLI, Z_YDMF_PHYS_OUT_FPLCL, &
    !$ACC&         Z_YDMF_PHYS_OUT_FPLCN, Z_YDMF_PHYS_OUT_FPLSL, Z_YDMF_PHYS_OUT_FPLSN) &
    !$ACC&PRIVATE (JBLK) &
    !$ACC&VECTOR_LENGTH (YDCPG_OPTS%KLON) 
    
    DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
    
    
    
    !$ACC LOOP VECTOR &
    !$ACC&PRIVATE (JLEV, JLON, YDPHYSMWAVE, YLCPG_BNDS) 

    

    DO JLON = 1, MIN (YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1) * YDCPG_OPTS%KLON)
      YLCPG_BNDS%KIDIA = JLON
      YLCPG_BNDS%KFDIA = JLON
      
      ZCOVPTOT (JLON,:, JBLK)=0.0_JPRB

      DO JLEV=1, YDCPG_OPTS%KFLEVG

        

        IF (JLEV>0) THEN

          IF (ABS (0.5*(Z_YDMF_PHYS_OUT_FPLSL (JLON, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSL (JLON, JLEV-1, JBLK))+0&
            &.5*(Z_YDMF_PHYS_OUT_FPLSN (JLON, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSN (JLON, JLEV-1, JBLK))+0.5*(Z_YDMF_PHYS_OUT_FPLCN&
            & (JLON, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLCN (JLON, JLEV-1, JBLK))+0.5*(Z_YDMF_PHYS_OUT_FPLCL (JLON, JLEV&
            &, JBLK)+Z_YDMF_PHYS_OUT_FPLCL (JLON, JLEV-1, JBLK)))>=1.E-25_JPRB) THEN

            IF (JLEV==1_JPIM) THEN
              ZCOVPTOT (JLON, JLEV, JBLK)=1.0_JPRB-((1.0_JPRB-ZCOVPTOT (JLON, JLEV, JBLK&
              &))*(1.0_JPRB-Z_YDCPG_MISC_NEB (JLON, JLEV, JBLK))/1.E-06_JPRB)
            ELSE
              ZCOVPTOT (JLON, JLEV, JBLK)=1.0_JPRB-((1.0_JPRB-ZCOVPTOT (JLON, JLEV-1, JBLK))*(1.0_JPRB&
              &-MAX (Z_YDCPG_MISC_NEB (JLON, JLEV, JBLK), Z_YDCPG_MISC_NEB (JLON, JLEV-1, JBLK)))/&
              &(1.0_JPRB-MIN (Z_YDCPG_MISC_NEB (JLON, JLEV-1, JBLK), 1.0_JPRB-1.E-06_JPRB)))
            ENDIF

            ZCOVPTOT (JLON, JLEV, JBLK)=MAX (ZCOVPTOT (JLON, JLEV, JBLK), 0.1_JPRB)
          ENDIF

        ENDIF

        YDPHYSMWAVE%P (JLON, JLEV, 1)=Z_YDCPG_MISC_QLI (JLON, JLEV, JBLK)
        YDPHYSMWAVE%P (JLON, JLEV, 2)=Z_YDCPG_MISC_QICE (JLON, JLEV, JBLK)
        YDPHYSMWAVE%P (JLON, JLEV, 3)=Z_YDCPG_MISC_NEB (JLON, JLEV, JBLK)
        YDPHYSMWAVE%P (JLON, JLEV, 4)=0.5*(Z_YDMF_PHYS_OUT_FPLSL (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSL (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 5)=0.5*(Z_YDMF_PHYS_OUT_FPLSN (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLSN (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 6)=0.5*(Z_YDMF_PHYS_OUT_FPLCL (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLCL (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 7)=0.5*(Z_YDMF_PHYS_OUT_FPLCN (JLON&
        &, JLEV, JBLK)+Z_YDMF_PHYS_OUT_FPLCN (JLON, JLEV-1, JBLK))
        YDPHYSMWAVE%P (JLON, JLEV, 8)=ZCOVPTOT (JLON, JLEV, JBLK)
      
      ENDDO

      
      YDPHYSMWAVE%P (JLON, 1, 9)=0._JPRB
      YDPHYSMWAVE%P (JLON, 2, 9)=0._JPRB
      YDPHYSMWAVE%P (JLON, 3:YDCPG_OPTS%KFLEVG, 9)=0._JPRB
    
    ENDDO

  ENDDO

  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

  IF (FXTRAN_ACDC_LSYNCHOST ('APL_ARPEGE_MWAVE_PARALLEL:0')) THEN
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
    ZCOVPTOT => GET_HOST_DATA_RDWR (YL_ZCOVPTOT)
    Z_YDCPG_MISC_NEB => GET_HOST_DATA_RDWR (YDCPG_MISC%F_NEB)
    Z_YDCPG_MISC_QICE => GET_HOST_DATA_RDWR (YDCPG_MISC%F_QICE)
    Z_YDCPG_MISC_QLI => GET_HOST_DATA_RDWR (YDCPG_MISC%F_QLI)
    Z_YDMF_PHYS_OUT_FPLCL => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLCL)
    Z_YDMF_PHYS_OUT_FPLCN => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLCN)
    Z_YDMF_PHYS_OUT_FPLSL => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLSL)
    Z_YDMF_PHYS_OUT_FPLSN => GET_HOST_DATA_RDWR (YDMF_PHYS%OUT%F_FPLSN)
    IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
    
    
  ENDIF

  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
  ZCOVPTOT => NULL ()
  Z_YDCPG_MISC_NEB => NULL ()
  Z_YDCPG_MISC_QICE => NULL ()
  Z_YDCPG_MISC_QLI => NULL ()
  Z_YDMF_PHYS_OUT_FPLCL => NULL ()
  Z_YDMF_PHYS_OUT_FPLCN => NULL ()
  Z_YDMF_PHYS_OUT_FPLSL => NULL ()
  Z_YDMF_PHYS_OUT_FPLSN => NULL ()
  IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
  
  
ELSE
    CALL ABOR1 ('APL_ARPEGE_MWAVE_PARALLEL: NOT METHOD WAS FOUND')
ENDIF

IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL:0',1,ZHOOK_HANDLE_PARALLEL)


CALL FXTRAN_ACDC_GPUMEMSTAT (__FILE__, __LINE__, "END")

IF (LHOOK) CALL DR_HOOK ('DELETE_TEMPORARIES',0,ZHOOK_HANDLE_FIELD_API)
IF (ASSOCIATED (YL_ZCOVPTOT)) CALL FIELD_DELETE (YL_ZCOVPTOT)
IF (LHOOK) CALL DR_HOOK ('DELETE_TEMPORARIES',1,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('APL_ARPEGE_MWAVE_PARALLEL', 1, ZHOOK_HANDLE)
END SUBROUTINE APL_ARPEGE_MWAVE_PARALLEL
