INTERFACE

SUBROUTINE ACVPPKF(YDCST, YDML_PHY_MF, YDCPG_BNDS, YDCPG_OPTS, KTDIA, PAPRSF, PAPHIF, PDELP,  PR, PT, &
& PQ, PQL, PQI, PU, PV, PCP, PTKE, PDIFCQ, PDIFCS, PFCCQL, PFCCQN, PPRODTH, KNLAB,  PQCPP, PNEBPP,    &
& KNND)
USE MODEL_PHYSICS_MF_MOD, ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1            , ONLY : JPIM, JPRB
USE YOMCST              , ONLY : TCST
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
IMPLICIT NONE
TYPE(TCST)                  ,INTENT(IN)     :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE) ,INTENT(IN)     :: YDML_PHY_MF
TYPE(CPG_BNDS_TYPE)         ,INTENT(IN)     :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)         ,INTENT(IN)     :: YDCPG_OPTS
INTEGER(KIND=JPIM)          ,INTENT(IN)     :: KTDIA
REAL(KIND=JPRB)             ,INTENT(IN)     :: PAPRSF(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PAPHIF(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PDELP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PR(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PT(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PQ(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PQL(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PQI(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PU(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PCP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(IN)     :: PTKE(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(INOUT)  :: PDIFCQ(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(INOUT)  :: PDIFCS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(INOUT)  :: PFCCQL(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(INOUT)  :: PFCCQN(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(INOUT)  :: PPRODTH(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
INTEGER(KIND=JPIM)          ,INTENT(OUT)    :: KNLAB(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(INOUT)  :: PQCPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)             ,INTENT(INOUT)  :: PNEBPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
INTEGER(KIND=JPIM)          ,INTENT(OUT)    :: KNND(YDCPG_OPTS%KLON)
END SUBROUTINE ACVPPKF







END INTERFACE
