SUBROUTINE CPG_END_SFC_PARALLEL (YDMODEL, YDCPG_OPTS, YDCPG_BNDS, YDMF_PHYS_SURF, KUPTRA)

USE YOMHOOK,ONLY:DR_HOOK, JPHOOK, LHOOK
USE TYPE_MODEL,ONLY:MODEL
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE PARKIND1
USE FXTRAN_ACDC_ARRAY_COPY_MOD
USE FXTRAN_ACDC_GPUMEM_MOD
USE UTIL_MF_PHYS_SURF_TYPE_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE


TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
INTEGER (KIND=JPIM), INTENT (IN)::KUPTRA
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
INTEGER (KIND=JPIM) :: JLON
INTEGER(KIND=JPIM) :: JBLK
TYPE(CPG_BNDS_TYPE) :: YLCPG_BNDS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_FIELD_API
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_PARALLEL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_COMPUTE
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLOFFSET
#include "abor1.intfb.h"
IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL', 0, ZHOOK_HANDLE)

CALL FXTRAN_ACDC_GPUMEMSTAT (__FILE__, __LINE__, "BEGIN")


IF (LHOOK) CALL DR_HOOK ('CREATE_TEMPORARIES',0,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('CREATE_TEMPORARIES',1,ZHOOK_HANDLE_FIELD_API)

IF ((YDMODEL%YRML_DYN%YRDYN%NCURRENT_ITER==0).AND.YDCPG_OPTS%LDIAB) THEN

  IF (.NOT.YDCPG_OPTS%LCONFX) THEN

    IF (YDMODEL%YRML_DYN%YRDYNA%LTWOTL) THEN
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1',0,ZHOOK_HANDLE_PARALLEL)

      IF (FXTRAN_ACDC_LPARALLELMETHOD ('UPDATEVIEW','CPG_END_SFC_PARALLEL:SET0TO1')) THEN
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
        CALL ACDC_HOST (YDMF_PHYS_SURF)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
        
        CALL YLCPG_BNDS%INIT (YDCPG_OPTS)

        DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
          CALL YDMF_PHYS_SURF%UPDATE_VIEW (JBLK)
          CALL YLCPG_BNDS%UPDATE (JBLK)
          
          CALL YDMF_PHYS_SURF%SET0TO1 (YDCPG_OPTS, YLCPG_BNDS)
        ENDDO

        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

        IF (FXTRAN_ACDC_LSYNCHOST ('CPG_END_SFC_PARALLEL:SET0TO1')) THEN
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPMETHOD','CPG_END_SFC_PARALLEL:SET0TO1')) THEN
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
        
        CALL YDMF_PHYS_SURF%SET0TO1_HOST_PARALLEL (YDCPG_OPTS, YLCPG_BNDS)
        
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

        IF (FXTRAN_ACDC_LSYNCHOST ('CPG_END_SFC_PARALLEL:SET0TO1')) THEN
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCMETHOD','CPG_END_SFC_PARALLEL:SET0TO1')) THEN
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
        
        CALL YDMF_PHYS_SURF%SET0TO1_DEVICE_PARALLEL (YDCPG_OPTS, YLCPG_BNDS)
        
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

        IF (FXTRAN_ACDC_LSYNCHOST ('CPG_END_SFC_PARALLEL:SET0TO1')) THEN
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ELSE
          CALL ABOR1 ('CPG_END_SFC_PARALLEL: NOT METHOD WAS FOUND')
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:SET0TO1',1,ZHOOK_HANDLE_PARALLEL)
    ELSE
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT',0,ZHOOK_HANDLE_PARALLEL)

      IF (FXTRAN_ACDC_LPARALLELMETHOD ('UPDATEVIEW','CPG_END_SFC_PARALLEL:PHTFILT')) THEN
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
        CALL ACDC_HOST (YDMF_PHYS_SURF)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
        
        CALL YLCPG_BNDS%INIT (YDCPG_OPTS)

        DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
          CALL YDMF_PHYS_SURF%UPDATE_VIEW (JBLK)
          CALL YLCPG_BNDS%UPDATE (JBLK)
          
          CALL YDMF_PHYS_SURF%PHTFILT (YDMODEL%YRML_DYN%YRDYN, YDCPG_OPTS, YLCPG_BNDS)
        ENDDO

        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

        IF (FXTRAN_ACDC_LSYNCHOST ('CPG_END_SFC_PARALLEL:PHTFILT')) THEN
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPMETHOD','CPG_END_SFC_PARALLEL:PHTFILT')) THEN
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
        
        CALL YDMF_PHYS_SURF%PHTFILT_HOST_PARALLEL (YDMODEL%YRML_DYN%YRDYN, YDCPG_OPTS, YLCPG_BNDS)
        
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

        IF (FXTRAN_ACDC_LSYNCHOST ('CPG_END_SFC_PARALLEL:PHTFILT')) THEN
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCMETHOD','CPG_END_SFC_PARALLEL:PHTFILT')) THEN
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
        
        CALL YDMF_PHYS_SURF%PHTFILT_DEVICE_PARALLEL (YDMODEL%YRML_DYN%YRDYN, YDCPG_OPTS, YLCPG_BNDS)
        
        
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

        IF (FXTRAN_ACDC_LSYNCHOST ('CPG_END_SFC_PARALLEL:PHTFILT')) THEN
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
          IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
          
          
        ENDIF

        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ELSE
          CALL ABOR1 ('CPG_END_SFC_PARALLEL: NOT METHOD WAS FOUND')
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:PHTFILT',1,ZHOOK_HANDLE_PARALLEL)
    ENDIF

  ELSEIF (YDMODEL%YRML_DYN%YRDYNA%LTWOTL.AND.YDMODEL%YRML_PHY_G%YRDPHY%LDIRCLSMOD.AND.(KUPTRA>0)) THEN
    IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1',0,ZHOOK_HANDLE_PARALLEL)

    IF (FXTRAN_ACDC_LPARALLELMETHOD ('UPDATEVIEW','CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1')) THEN
      
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
      CALL ACDC_HOST (YDMF_PHYS_SURF)
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
      
      CALL YLCPG_BNDS%INIT (YDCPG_OPTS)

      DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
        CALL YDMF_PHYS_SURF%UPDATE_VIEW (JBLK)
        CALL YLCPG_BNDS%UPDATE (JBLK)
        
        CALL YDMF_PHYS_SURF%GSP_CL%SET0TO1 (YDCPG_OPTS, YLCPG_BNDS)
      ENDDO

      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

      IF (FXTRAN_ACDC_LSYNCHOST ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1')) THEN
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENMPMETHOD','CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1')) THEN
      
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
      
      CALL YDMF_PHYS_SURF%GSP_CL%SET0TO1_HOST_PARALLEL (YDCPG_OPTS, YLCPG_BNDS)
      
      
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

      IF (FXTRAN_ACDC_LSYNCHOST ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1')) THEN
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ELSEIF (FXTRAN_ACDC_LPARALLELMETHOD ('OPENACCMETHOD','CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1')) THEN
      
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:GET_DATA',0,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:GET_DATA',1,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:COMPUTE',0,ZHOOK_HANDLE_COMPUTE)
      
      CALL YDMF_PHYS_SURF%GSP_CL%SET0TO1_DEVICE_PARALLEL (YDCPG_OPTS, YLCPG_BNDS)
      
      
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:COMPUTE',1,ZHOOK_HANDLE_COMPUTE)

      IF (FXTRAN_ACDC_LSYNCHOST ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1')) THEN
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:SYNCHOST',0,ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:SYNCHOST',1,ZHOOK_HANDLE_FIELD_API)
        
        
      ENDIF

      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:NULLIFY',0,ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1:NULLIFY',1,ZHOOK_HANDLE_FIELD_API)
      
      
    ELSE
        CALL ABOR1 ('CPG_END_SFC_PARALLEL: NOT METHOD WAS FOUND')
    ENDIF

    IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL:GSP_CL_SET0TO1',1,ZHOOK_HANDLE_PARALLEL)
  ENDIF

ENDIF


CALL FXTRAN_ACDC_GPUMEMSTAT (__FILE__, __LINE__, "END")

IF (LHOOK) CALL DR_HOOK ('DELETE_TEMPORARIES',0,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('DELETE_TEMPORARIES',1,ZHOOK_HANDLE_FIELD_API)
IF (LHOOK) CALL DR_HOOK ('CPG_END_SFC_PARALLEL', 1, ZHOOK_HANDLE)
END SUBROUTINE CPG_END_SFC_PARALLEL
