
SUBROUTINE GNHPRE_OPENACC (YDGEOMETRY, KPDVAR, KPROMA, KFLEV, KST, KEND,&
& PSPD, PREF, PKAP, PNHPREF, PNHPPI, PRNHPPI, PDEP, PEQCHAF, YDSTACK)
!$ACC ROUTINE (GNHPRE_OPENACC) SEQ
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB

#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
INTEGER (KIND=JPIM), INTENT (IN)::KPDVAR
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
REAL (KIND=JPRB), INTENT (IN)::PSPD (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PREF (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN), OPTIONAL::PKAP
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PNHPREF (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL, TARGET::PNHPPI (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PRNHPPI (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PDEP (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (OUT), OPTIONAL::PEQCHAF (KPROMA, KFLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV
fxtran_acdc_temp (REAL (KIND=JPRB), ZNHPPI0, (KPROMA, KFLEV))
fxtran_acdc_temp (REAL (KIND=JPRB), ZNHPPI, (KPROMA, KFLEV))
REAL (KIND=JPRB)::Z1SKAP


YLSTACK = YDSTACK



IF (KIND (ZNHPPI0) == 8) THEN
    fxtran_acdc_alloc8 (ZNHPPI0)
ELSEIF (KIND (ZNHPPI0) == 4) THEN
    fxtran_acdc_alloc4 (ZNHPPI0)
ELSE
    STOP 1
ENDIF


JROF = KST



IF ((KPDVAR==3.OR.PRESENT (PEQCHAF)).AND.(.NOT.PRESENT (PKAP))) THEN
  CALL FXTRAN_ACDC_ABORT (' GNHPRE: missing optional input arguments!')
ENDIF


IF (PRESENT (PNHPPI)) THEN
  fxtran_acdc_assoc (ZNHPPI, PNHPPI)
ELSE
  fxtran_acdc_assoc (ZNHPPI, ZNHPPI0)
ENDIF


IF (KPDVAR==2) THEN

  DO JLEV=1, KFLEV
    
    ZNHPPI (JROF, JLEV)=EXP (PSPD (JROF, JLEV))
  
  ENDDO


  IF (PRESENT (PKAP).AND.PRESENT (PEQCHAF)) THEN

    DO JLEV=1, KFLEV
      
      PEQCHAF (JROF, JLEV)=EXP (PKAP*PSPD (JROF, JLEV))
    
    ENDDO

  ENDIF

ELSEIF (KPDVAR==3) THEN

  DO JLEV=1, KFLEV
    
    Z1SKAP=1.0_JPRB/PKAP
    ZNHPPI (JROF, JLEV)=EXP (LOG (1.0_JPRB+PKAP*PSPD (JROF, JLEV))*Z1SKAP)
  
  ENDDO


  IF (PRESENT (PEQCHAF)) THEN

    DO JLEV=1, KFLEV
      
      PEQCHAF (JROF, JLEV)=1.0_JPRB+PKAP*PSPD (JROF, JLEV)
    
    ENDDO

  ENDIF

ENDIF


IF (PRESENT (PNHPREF)) THEN

  DO JLEV=1, KFLEV
    
    PNHPREF (JROF, JLEV)=ZNHPPI (JROF, JLEV)*PREF (JROF, JLEV)
  
  ENDDO

ENDIF


IF (PRESENT (PRNHPPI)) THEN

  DO JLEV=1, KFLEV
    
    PRNHPPI (JROF, JLEV)=1.0_JPRB/ZNHPPI (JROF, JLEV)
  
  ENDDO

ENDIF


IF (PRESENT (PDEP)) THEN

  DO JLEV=1, KFLEV
    
    PDEP (JROF, JLEV)=(ZNHPPI (JROF, JLEV)-1.0_JPRB)*PREF (JROF, JLEV)
  
  ENDDO

ENDIF


END SUBROUTINE GNHPRE_OPENACC
