SUBROUTINE GPRT_OPENACC (LDSPRT, KPROMA, KST, KEND, KLEV, PRD, PRV,&
& PR, PT, PTL, PTM, PQL, PQM, PRT, PRTL, PRTM, PRL, PRM, YDSTACK)
!$ACC ROUTINE (GPRT_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB

#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


LOGICAL, INTENT (IN)::LDSPRT
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::PRD
REAL (KIND=JPRB), INTENT (IN)::PRV
REAL (KIND=JPRB), INTENT (IN)::PR (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTL (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTM (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQL (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQM (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRT (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRTL (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRTM (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (IN), OPTIONAL::PRL (KPROMA, KLEV)
REAL (KIND=JPRB), INTENT (IN), OPTIONAL::PRM (KPROMA, KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRB)::ZR


JROF = KST


ZR=PRV-PRD

DO JLEV=1, KLEV
  
  PRT (JROF, JLEV)=PR (JROF, JLEV)*PT (JROF, JLEV)
  
ENDDO


IF (LDSPRT) THEN

  DO JLEV=1, KLEV
    
    PRTL (JROF, JLEV)=PRD*PTL (JROF, JLEV)
    PRTM (JROF, JLEV)=PRD*PTM (JROF, JLEV)
  
  ENDDO

ELSEIF (PRESENT (PRL)) THEN

  DO JLEV=1, KLEV
    
    PRTL (JROF, JLEV)=PRL (JROF, JLEV)*PT (JROF, JLEV)+PR (JROF, JLEV)*PTL (JROF, JLEV)
    PRTM (JROF, JLEV)=PRM (JROF, JLEV)*PT (JROF, JLEV)+PR (JROF, JLEV)*PTM (JROF, JLEV)
  
  ENDDO

ELSE

  DO JLEV=1, KLEV
    
    PRTL (JROF, JLEV)=ZR*PT (JROF, JLEV)*PQL (JROF, JLEV)+PR (JROF, JLEV)*PTL (JROF, JLEV)
    PRTM (JROF, JLEV)=ZR*PT (JROF, JLEV)*PQM (JROF, JLEV)+PR (JROF, JLEV)*PTM (JROF, JLEV)
  
  ENDDO

ENDIF


END SUBROUTINE GPRT_OPENACC
