SUBROUTINE LARCHE_OPENACC (YDTCCO, YDTSCO, KPROMA, KST, KEND, KFLEV, KSTTYP&
&, PDSTRET, PC2M1, PC2P1, PI, PDEPI, PLOCEN, PMUCEN, PSCO, KROT, PCCO&
&, PRCOLON, PRSILON, PGECLO, PGEMU, PGESLO, PGSQM2, YDSTACK)
!$ACC ROUTINE (LARCHE_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB, JPRD

USE INTDYNSL_MOD,ONLY:TSCO, TCCO
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (TCCO), INTENT (IN)::YDTCCO
TYPE (TSCO), INTENT (IN)::YDTSCO
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KSTTYP
REAL (KIND=JPRB), INTENT (IN)::PDSTRET
REAL (KIND=JPRB), INTENT (IN)::PC2M1
REAL (KIND=JPRB), INTENT (IN)::PC2P1
REAL (KIND=JPRB), INTENT (IN)::PI
REAL (KIND=JPRB), INTENT (IN)::PDEPI
REAL (KIND=JPRB), INTENT (IN)::PLOCEN
REAL (KIND=JPRB), INTENT (IN)::PMUCEN
REAL (KIND=JPRB), INTENT (IN)::PSCO (KPROMA, KFLEV, YDTSCO%NDIM)
INTEGER (KIND=JPIM), INTENT (IN)::KROT
REAL (KIND=JPRB), INTENT (OUT)::PCCO (KPROMA, KFLEV, YDTCCO%NDIM)
REAL (KIND=JPRD), INTENT (IN)::PRCOLON (KPROMA)
REAL (KIND=JPRD), INTENT (IN)::PRSILON (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PGECLO (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PGEMU (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PGESLO (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PGSQM2 (KPROMA)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
LOGICAL::LLSTR
REAL (KIND=JPRD)::ZPDSTRET
REAL (KIND=JPRD)::ZPC2M1
REAL (KIND=JPRD)::ZPC2P1
REAL (KIND=JPRD)::ZPI
REAL (KIND=JPRD)::ZPDEPI
fxtran_acdc_temp (REAL (KIND=JPRD), ZPSCO, (KPROMA, KFLEV, YDTSCO%NDIM))
REAL (KIND=JPRD)::ZTMP1 
REAL (KIND=JPRD)::ZTMP2 
REAL (KIND=JPRD)::ZTMP4 
REAL (KIND=JPRD)::ZTMP5 
REAL (KIND=JPRD)::ZTMP6 
REAL (KIND=JPRD)::ZTMP7 
REAL (KIND=JPRD)::ZTMP8 
REAL (KIND=JPRD)::ZTMP9 
REAL (KIND=JPRD)::ZZA 
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRD)::ZPIH52
REAL (KIND=JPRD)::ZPIH
REAL (KIND=JPRD)::ZANGLE
REAL (KIND=JPRD)::ZZZ
REAL (KIND=JPRD)::ZZY
REAL (KIND=JPRD)::ZZX
REAL (KIND=JPRD)::ZZW
REAL (KIND=JPRD)::ZZP
REAL (KIND=JPRD)::ZYY
REAL (KIND=JPRD)::ZXX
REAL (KIND=JPRD)::ZSINLA
REAL (KIND=JPRD)::ZSINCO
REAL (KIND=JPRD)::ZSA
REAL (KIND=JPRD)::ZQ
REAL (KIND=JPRD)::ZPSLOP
REAL (KIND=JPRD)::ZPSLAP
REAL (KIND=JPRD)::ZPCLOP
REAL (KIND=JPRD)::ZPCLAP
REAL (KIND=JPRD)::ZP
REAL (KIND=JPRD)::ZMU
REAL (KIND=JPRD)::ZFACT2
REAL (KIND=JPRD)::ZFACT1
REAL (KIND=JPRD)::ZEPS1
REAL (KIND=JPRD)::ZEPS
REAL (KIND=JPRD)::ZDI
REAL (KIND=JPRD)::ZDECO
REAL (KIND=JPRD)::ZCOSLR
REAL (KIND=JPRD)::ZCOSLA
REAL (KIND=JPRD)::ZCOSL2
REAL (KIND=JPRD)::ZCOSCO
REAL (KIND=JPRD)::ZCA
REAL (KIND=JPRD)::Z1STT
REAL (KIND=JPRD)::Z1ST


YLSTACK = YDSTACK



IF (KIND (ZPSCO) == 8) THEN
    fxtran_acdc_alloc8 (ZPSCO)
ELSEIF (KIND (ZPSCO) == 4) THEN
    fxtran_acdc_alloc4 (ZPSCO)
ELSE
    STOP 1
ENDIF


JROF = KST


ZPDSTRET=PDSTRET
ZPC2M1=PC2M1
ZPC2P1=PC2P1
ZPI=PI
ZPDEPI=PDEPI
ZPSCO (JROF, 1:KFLEV, 1:YDTSCO%NDIM)=PSCO (JROF, 1:KFLEV, 1:YDTSCO%NDIM)
ZEPS=100._JPRD*EPSILON (ZEPS)
ZEPS1=100.0_JPRD*TINY (1.0_JPRD)
LLSTR=(ABS (0.5_JPRD*PDSTRET-1.0_JPRD)>ZEPS1)
ZANGLE=SQRT (0.5_JPRD)
ZPIH=0.5_JPRD*PI
ZPIH52=2.5_JPRD*PI

IF (KSTTYP==1.AND.(.NOT.LLSTR)) THEN

  DO JLEV=1, KFLEV
    
    ZCOSLR=SQRT (ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO&
    &)+ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO))
    ZCOSLR=MAX (ZEPS, ZCOSLR)
    ZCOSCO=ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)
    ZSINCO=ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
    ZCOSLA=ZCOSLR
    ZTMP7 =ZCOSLA
    ZXX=PRCOLON (JROF)*ZCOSCO-PRSILON (JROF)*ZSINCO
    ZYY=PRSILON (JROF)*ZCOSCO+PRCOLON (JROF)*ZSINCO
    ZTMP5 =SIGN (1.0_JPRD, ZYY)
    ZTMP8 =SIGN (1.0_JPRD, ZXX)
    ZTMP6 =MAX (-1.0_JPRD, MIN (1.0_JPRD, ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)))
    ZTMP4 =MAX (-1.0_JPRD, MIN (1.0_JPRD, ZXX/ZCOSLA))
    ZZA =MAX (-1.0_JPRD, MIN (1.0_JPRD, ZYY/ZCOSLA))
    
    
    ZTMP6 =ASIN (ZTMP6 )
    ZTMP4 =ACOS (ZTMP4 )
    ZTMP9 =ASIN (ZZA )
    
    
    PCCO (JROF, JLEV, YDTCCO%M_RLAT)=ZTMP6 
    PCCO (JROF, JLEV, YDTCCO%M_RLON)=MERGE (MOD (PI+ZTMP5 *(ZTMP4 -PI), PDEPI&
    &), MOD (ZPIH52+ZTMP8 *(ZTMP9 -ZPIH), PDEPI), ABS (ZZA )>=ZANGLE)

    

    IF (KROT==1) THEN
      
      ZDECO=1.0_JPRD/(1.0_JPRD+ZPSCO (JROF, JLEV, YDTSCO%M_COPHI))
      Z1ST=1.0_JPRD/ZTMP7 
      PCCO (JROF, JLEV, YDTCCO%M_RQX)=(PGSQM2 (JROF)*ZTMP7 +(1.0_JPRD+PGEMU (JROF)*ZPSCO&
      & (JROF, JLEV, YDTSCO%M_SINLA))*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*Z1ST)*ZDECO
      PCCO (JROF, JLEV, YDTCCO%M_RQY)=-(PGEMU (JROF)+ZPSCO (JROF, JLEV, YDTSCO&
      &%M_SINLA))*(ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*Z1ST)*ZDECO
    
    ENDIF

  ENDDO

ELSEIF (KSTTYP==1.AND.LLSTR) THEN

  DO JLEV=1, KFLEV
    
    ZCOSLR=SQRT (ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO&
    &)+ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO))
    ZTMP5 =MAX (ZEPS, ZCOSLR)
    ZFACT1=1.0_JPRD/(ZPC2P1-ZPC2M1*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA))
    ZFACT2=ZPDSTRET*ZFACT1
    ZCOSCO=ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*ZFACT2
    ZSINCO=ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*ZFACT2
    ZCOSLA=ZTMP5 *ZFACT2
    ZSINLA=(ZPC2P1*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)-ZPC2M1)*ZFACT1
    ZXX=PRCOLON (JROF)*ZCOSCO-PRSILON (JROF)*ZSINCO
    ZTMP4 =PRSILON (JROF)*ZCOSCO+PRCOLON (JROF)*ZSINCO
    ZTMP1 =MAX (-1.0_JPRD, MIN (1.0_JPRD, ZSINLA))
    ZTMP2 =MAX (-1.0_JPRD, MIN (1.0_JPRD, ZXX/ZCOSLA))
    
    
    PCCO (JROF, JLEV, YDTCCO%M_RLAT)=ASIN (ZTMP1 )
    PCCO (JROF, JLEV, YDTCCO%M_RLON)=ZPI+SIGN (1.0_JPRD, ZTMP4 )*(ACOS (ZTMP2 )-ZPI)
    
    
    PCCO (JROF, JLEV, YDTCCO%M_RLON)=MOD (PCCO (JROF, JLEV, YDTCCO%M_RLON), ZPDEPI)

    

    IF (KROT==1) THEN
      
      ZDECO=1.0_JPRD/(1.0_JPRD+ZPSCO (JROF, JLEV, YDTSCO%M_COPHI))
      Z1ST=1.0_JPRD/ZTMP5 
      PCCO (JROF, JLEV, YDTCCO%M_RQX)=(PGSQM2 (JROF)*ZTMP5 +(1.0_JPRD+PGEMU (JROF)*ZPSCO&
      & (JROF, JLEV, YDTSCO%M_SINLA))*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*Z1ST)*ZDECO
      PCCO (JROF, JLEV, YDTCCO%M_RQY)=-(PGEMU (JROF)+ZPSCO (JROF, JLEV, YDTSCO&
      &%M_SINLA))*(ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*Z1ST)*ZDECO
    
    ENDIF

  ENDDO

ELSEIF (KSTTYP==2) THEN
  ZPSLAP=PMUCEN
  ZPCLAP=SQRT (1.0_JPRD-REAL (PMUCEN, JPRD)*REAL (PMUCEN, JPRD))
  ZPSLOP=SIN (REAL (PLOCEN, JPRD))
  ZPCLOP=COS (REAL (PLOCEN, JPRD))

  DO JLEV=1, KFLEV
    
    ZZY=PGESLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)&
    &+PGECLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
    ZZX=PGECLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)&
    &-PGESLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
    ZZZ=ZZX*ZPCLOP+ZPSLOP*ZZY
    ZZP=ZPSLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)+ZPCLAP*ZZZ
    ZDI=1.0_JPRD/(ZPC2P1-ZPC2M1*ZZP)
    ZYY=ZPDSTRET*ZDI*(-ZPCLOP*ZZY+ZPSLOP*ZZX)
    ZXX=ZPDSTRET*ZDI*(ZPCLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)-ZPSLAP*ZZZ)
    ZCOSLA=SQRT (ZXX*ZXX+ZYY*ZYY)
    ZCOSLA=MAX (ZEPS, ZCOSLA)
    ZSINLA=-(ZPC2M1-ZPC2P1*ZZP)*ZDI
    ZTMP4 =ZYY
    ZTMP1 =MAX (-1.0_JPRD, MIN (1.0_JPRD, ZSINLA))
    ZTMP2 =MAX (-1.0_JPRD, MIN (1.0_JPRD, ZXX/ZCOSLA))
    
    
    PCCO (JROF, JLEV, YDTCCO%M_RLAT)=ASIN (ZTMP1 )
    PCCO (JROF, JLEV, YDTCCO%M_RLON)=ZPI+SIGN (1.0_JPRD, ZTMP4 )*(ACOS (ZTMP2 )-ZPI)
    
    
    PCCO (JROF, JLEV, YDTCCO%M_RLON)=MOD (PCCO (JROF, JLEV, YDTCCO%M_RLON), ZPDEPI)

    

    IF (KROT==1) THEN
      
      ZZY=PGESLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)&
      &+PGECLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
      ZZX=PGECLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)&
      &-PGESLO (JROF)*ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)
      ZCOSL2=ZZY*ZZY+ZZX*ZZX
      ZCOSLR=SQRT (ZCOSL2)
      ZCOSLR=MAX (ZEPS, ZCOSLR)
      ZZZ=ZZX*ZPCLOP+ZPSLOP*ZZY
      ZZP=ZPSLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)+ZPCLAP*ZZZ
      ZDI=1.0_JPRD/(ZPC2P1-ZPC2M1*ZZP)
      ZYY=ZPDSTRET*ZDI*(-ZPCLOP*ZZY+ZPSLOP*ZZX)
      ZXX=ZPDSTRET*ZDI*(ZPCLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)-ZPSLAP*ZZZ)
      ZCOSLA=SQRT (ZXX*ZXX+ZYY*ZYY)
      ZCOSLA=MAX (ZEPS, ZCOSLA)
      ZDECO=1.0_JPRD/(1.0_JPRD+ZPSCO (JROF, JLEV, YDTSCO%M_COPHI))
      Z1ST=1.0_JPRD/ZCOSLR
      Z1STT=Z1ST/ZCOSLA
      ZP=(PGSQM2 (JROF)*ZCOSLR+(1.0_JPRD+PGEMU (JROF)*ZPSCO (JROF, JLEV, YDTSCO&
      &%M_SINLA))*ZPSCO (JROF, JLEV, YDTSCO%M_COSCO)*Z1ST)*ZDECO
      ZQ=-(PGEMU (JROF)+ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)&
      &)*(ZPSCO (JROF, JLEV, YDTSCO%M_SINCO)*Z1ST)*ZDECO
      ZCA=ZPDSTRET*ZDI*(ZPSLAP*ZCOSL2-ZPCLAP*ZPSCO (JROF, JLEV, YDTSCO%M_SINLA)*ZZZ)*Z1STT
      ZSA=-ZYY*ZPCLAP*Z1STT
      PCCO (JROF, JLEV, YDTCCO%M_RQX)=ZP*ZCA+ZQ*ZSA
      PCCO (JROF, JLEV, YDTCCO%M_RQY)=ZQ*ZCA-ZP*ZSA
    
    ENDIF

  ENDDO

ENDIF


END SUBROUTINE LARCHE_OPENACC
