SUBROUTINE LATTEX_TNT_OPENACC (YDGEOMETRY, YDLDDH, YDDYN, KST, KEND, KXLAG, PESGP, PESGM&
&, PXT9, PMOY1X, PXSI9, PXSI0, PXT1, PXL0, PXL9, PXLF9, PSIDDHXT1, PSIDDHXL0, YDSTACK)
!$ACC ROUTINE (LATTEX_TNT_OPENACC) SEQ
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMDYN,ONLY:TDYN
USE YOMLDDH,ONLY:TLDDH
#include "fxtran_acdc_stack.h"
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE


TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (TDYN), INTENT (IN)::YDDYN
TYPE (TLDDH), INTENT (IN)::YDLDDH
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KXLAG
REAL (KIND=JPRB), INTENT (IN)::PESGP
REAL (KIND=JPRB), INTENT (IN)::PESGM
REAL (KIND=JPRB), INTENT (IN)::PXT9 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PMOY1X (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)::PXSI9 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PXSI0 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PXT1 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PXL0 (YDGEOMETRY%YRDIM%NPROMA&
&, YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN)
REAL (KIND=JPRB), INTENT (INOUT)::PXL9 (YDGEOMETRY%YRDIM%NPROMA&
&, YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN)
REAL (KIND=JPRB), INTENT (INOUT)::PXLF9 (YDGEOMETRY%YRDIM%NPROMA&
&, YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN)
REAL (KIND=JPRB), INTENT (INOUT)::PSIDDHXT1 (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (INOUT)::PSIDDHXL0 (YDGEOMETRY%YRDIM&
&%NPROMA, YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
REAL (KIND=JPRB)::ZMOYXNL 
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV


JROF = KST







DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
  
  ZMOYXNL =PMOY1X (JROF, JLEV)+PXSI0 (JROF, JLEV)

  

  IF (KXLAG==2) THEN

    IF (YDDYN%NSPLTHOI/=0) THEN
      
      PXT1 (JROF, JLEV)=PXT1 (JROF, JLEV)+PESGP*ZMOYXNL -PESGP*PXSI0 (JROF, JLEV)
      PXL9 (JROF, JLEV)=PXL9 (JROF, JLEV)+PXT9 (JROF, JLEV)
      PXLF9 (JROF, JLEV)=PXLF9 (JROF, JLEV)+PESGM*ZMOYXNL -PESGM*PXSI9 (JROF, JLEV)
    
    ELSE
      
      PXT1 (JROF, JLEV)=PXT1 (JROF, JLEV)+PESGP*ZMOYXNL -PESGP*PXSI0 (JROF, JLEV)
      PXL9 (JROF, JLEV)=PXL9 (JROF, JLEV)+PXT9 (JROF, JLEV)+PESGM*ZMOYXNL -PESGM*PXSI9 (JROF, JLEV)
    
    ENDIF

  ELSEIF (KXLAG>=3) THEN
    
    PXL0 (JROF, JLEV)=PXL0 (JROF, JLEV)+PESGM*ZMOYXNL -PESGM*PXSI9 (JROF, JLEV)
    PXT1 (JROF, JLEV)=PXT1 (JROF, JLEV)+PESGP*ZMOYXNL -PESGP*PXSI0 (JROF, JLEV)
    PXL9 (JROF, JLEV)=PXL9 (JROF, JLEV)+PXT9 (JROF, JLEV)
  
  ENDIF

  
  PXSI0 (JROF, JLEV)=PESGP*PXSI0 (JROF, JLEV)
  
ENDDO


IF (YDLDDH%LRSIDDH) THEN

  IF (KXLAG>=3) THEN

    DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
      
      PSIDDHXL0 (JROF, JLEV)=PSIDDHXL0 (JROF, JLEV)+PESGM*PXSI0 (JROF, JLEV)-PESGM*PXSI9 (JROF, JLEV)
    
    ENDDO

  ENDIF


  DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVG
    
    PSIDDHXT1 (JROF, JLEV)=PSIDDHXT1 (JROF, JLEV)+PESGP*PXSI0 (JROF, JLEV)
  
  ENDDO

ENDIF




END SUBROUTINE LATTEX_TNT_OPENACC
