INTERFACE
SUBROUTINE ROTUVGEO_OPENACC (KFLEV, KPROMA, KST, KEND, PGNORDM&
&, PGNORDL, PU, PV, PRU, PRV, LDIR, LDADD, LDSUB, YDSTACK)
!$ACC ROUTINE (ROTUVGEO_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
INTEGER (KIND=JPIM), INTENT (IN)::KEND
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
LOGICAL, INTENT (IN)::LDIR
LOGICAL, INTENT (IN), OPTIONAL::LDSUB
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
LOGICAL, INTENT (IN), OPTIONAL::LDADD
REAL (KIND=JPRB), INTENT (IN)::PGNORDL (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PGNORDM (KPROMA)
REAL (KIND=JPRB), INTENT (IN)::PU (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PRU (KPROMA, KFLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PRV (KPROMA, KFLEV)
END SUBROUTINE ROTUVGEO_OPENACC


END INTERFACE
