INTERFACE
SUBROUTINE MEANWIND_XFU_OPENACC (KLON, KIDIA, KFDIA, KMEANSTEPS&
&, PXFU, PXFV, PXU, PXV, PMWINDCALC, ZUM, ZVM, YDSTACK)
!$ACC ROUTINE (MEANWIND_XFU_OPENACC) SEQ
USE PARKIND1,ONLY:JPIM, JPRB
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KMEANSTEPS
REAL (KIND=JPRB), INTENT (IN)::PXFU (KLON)
REAL (KIND=JPRB), INTENT (IN)::PXFV (KLON)
REAL (KIND=JPRB), INTENT (IN)::PXU (KLON)
REAL (KIND=JPRB), INTENT (IN)::PXV (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PMWINDCALC (KLON)
REAL (KIND=JPRB), INTENT (OUT)::ZUM (KLON)
REAL (KIND=JPRB), INTENT (OUT)::ZVM (KLON)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
END SUBROUTINE MEANWIND_XFU_OPENACC


END INTERFACE
