MODULE MODD_FIELD

!$ACDC methods 

  USE MODD_PARAMETERS, ONLY: NGRIDUNKNOWN, NMNHNAMELGTMAX, NSTDNAMELGTMAX
  IMPLICIT NONE
  INTEGER, PARAMETER :: NMNHDIM_UNKNOWN             = -2
  INTEGER, PARAMETER :: NMNHMAXDIMS = 6 ! Cannot be less than 6
  INTEGER,PARAMETER :: TYPEUNDEF = -1, TYPEINT = 1, TYPELOG = 2, TYPEREAL = 3, TYPECHAR = 4, TYPEDATE = 5
!
TYPE TFIELDMETADATA
  CHARACTER(LEN=NMNHNAMELGTMAX) :: CMNHNAME  = '' !Name of the field (for MesoNH, non CF convention)
  CHARACTER(LEN=NSTDNAMELGTMAX) :: CSTDNAME  = '' !Standard name (CF convention)
  CHARACTER(LEN=32)  :: CLONGNAME = '' !Long name (CF convention)
  CHARACTER(LEN=40)  :: CUNITS    = '' !Canonical units (CF convention)
  CHARACTER(LEN=100) :: CCOMMENT  = '' !Comment (for MesoNH, non CF convention)
  INTEGER            :: NGRID     = NGRIDUNKNOWN !Localization on the model grid
  INTEGER            :: NTYPE     = TYPEUNDEF !Datatype
  INTEGER            :: NDIMS     = 0  !Number of dimensions
  INTEGER, DIMENSION(NMNHMAXDIMS) :: NDIMLIST = NMNHDIM_UNKNOWN ! List of dimensions of the data field
  !
  INTEGER            :: NFILLVALUE =  -2147483647            !Fill value for integer fields
  REAL               :: XFILLVALUE =  9.9692099683868690e+36 !Fill value for real fields
  INTEGER            :: NVALIDMIN  = -2147483646 !Minimum valid value for integer fields
  INTEGER            :: NVALIDMAX  =  2147483647 !Maximum valid value for integer fields
  REAL               :: XVALIDMIN  = -1.E36 !Minimum valid value for real fields
  REAL               :: XVALIDMAX  =  1.E36 !Maximum valid value for real fields
  CHARACTER(LEN=2)   :: CDIR      = '' !Type of the data field (XX,XY,--...)
  CHARACTER(LEN=4)   :: CLBTYPE   = 'NONE' !Type of the lateral boundary (LBX,LBY,LBXU,LBYV)
  LOGICAL            :: LTIMEDEP  = .FALSE. !Is the field time-dependent?
CONTAINS
PROCEDURE :: COPY => COPY_TFIELDMETADATA
PROCEDURE :: CRC64 => CRC64_TFIELDMETADATA
PROCEDURE :: HOST => HOST_TFIELDMETADATA
PROCEDURE :: LOAD => LOAD_TFIELDMETADATA
PROCEDURE :: SAVE => SAVE_TFIELDMETADATA
PROCEDURE :: SIZE => SIZE_TFIELDMETADATA
PROCEDURE :: WIPE => WIPE_TFIELDMETADATA
END TYPE TFIELDMETADATA
INTERFACE

MODULE SUBROUTINE COPY_TFIELDMETADATA (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TFIELDMETADATA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
END SUBROUTINE

MODULE SUBROUTINE CRC64_TFIELDMETADATA (SELF, KLUN, CDPATH)
USE CRC64_INTRINSIC, ONLY : FCRC64 => CRC64

IMPLICIT NONE
CLASS (TFIELDMETADATA), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
END SUBROUTINE

MODULE SUBROUTINE HOST_TFIELDMETADATA (SELF)

IMPLICIT NONE
CLASS (TFIELDMETADATA), TARGET :: SELF
END SUBROUTINE

MODULE SUBROUTINE LOAD_TFIELDMETADATA (SELF, KLUN)

IMPLICIT NONE
CLASS (TFIELDMETADATA), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE SUBROUTINE SAVE_TFIELDMETADATA (SELF, KLUN)

IMPLICIT NONE
CLASS (TFIELDMETADATA), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
END SUBROUTINE

MODULE FUNCTION SIZE_TFIELDMETADATA (SELF, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
CLASS (TFIELDMETADATA),     INTENT (IN), TARGET :: SELF
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: KSIZE
END FUNCTION

MODULE SUBROUTINE WIPE_TFIELDMETADATA (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
CLASS (TFIELDMETADATA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
END SUBROUTINE


END INTERFACE

END MODULE MODD_FIELD
