INTERFACE
SUBROUTINE CPGLAG (YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_SL2, YDCPG_DDH_TNDHD, YDMODEL, &
& YDVARS,  LDCONFX, YDDDH, YDA_PGPSTRESS, YDTDDH, PTRAJEC, PTRAJEC_OOPS)
USE GEOMETRY_MOD           , ONLY : GEOMETRY
USE YOMTRAJ                , ONLY : TRAJ_TYPE, LPRTTRAJ, LTRAJSAVE, LTRAJSLAG
USE YOMTRAJ_OOPS           , ONLY : TRAJ_TYPE_OOPS, LTRAJSAVE_OOPS, LTRAJSLAG_OOPS
USE DDH_MIX                , ONLY : TYP_DDH
USE FIELD_VARIABLES_MOD    , ONLY : FIELD_VARIABLES
USE TYPE_MODEL             , ONLY : MODEL
USE CPG_OPTS_TYPE_MOD      , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_SL2_TYPE_MOD       , ONLY : CPG_SL2_TYPE
USE CPG_DDH_TND_TYPE_MOD   , ONLY : CPG_TNDHD_DDH_TYPE
USE FIELD_ARRAY_MODULE
USE YOMTDDH                , ONLY : TTDDH
IMPLICIT NONE
TYPE(GEOMETRY)                ,INTENT(IN)               :: YDGEOMETRY
TYPE(MODEL)                   ,INTENT(IN)               :: YDMODEL
TYPE(FIELD_VARIABLES)         ,INTENT(INOUT)            :: YDVARS
TYPE(CPG_BNDS_TYPE)           ,INTENT(IN)               :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)           ,INTENT(IN)               :: YDCPG_OPTS
TYPE(CPG_SL2_TYPE)            ,INTENT(IN)               :: YDCPG_SL2
TYPE(CPG_TNDHD_DDH_TYPE)      ,INTENT(INOUT)            :: YDCPG_DDH_TNDHD
LOGICAL                       ,INTENT(IN)               :: LDCONFX
TYPE(TYP_DDH)                 ,INTENT(INOUT)            :: YDDDH
TYPE(FIELD_4RB_ARRAY)         ,INTENT(IN)               :: YDA_PGPSTRESS
TYPE(TTDDH)                   ,INTENT(INOUT)            :: YDTDDH
TYPE(TRAJ_TYPE)               ,INTENT(INOUT) ,OPTIONAL  :: PTRAJEC
TYPE(TRAJ_TYPE_OOPS)          ,INTENT(INOUT) ,OPTIONAL  :: PTRAJEC_OOPS
END SUBROUTINE CPGLAG







END INTERFACE
