INTERFACE
SUBROUTINE RECMWF_OUTLINE_002 (YDCPG_BNDS, YDCPG_OPTS, YDMODEL, PRLWINHF)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE TYPE_MODEL,ONLY:MODEL
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK

IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MODEL), INTENT (IN)::YDMODEL
REAL (KIND=JPRB), INTENT (INOUT)::PRLWINHF (YDCPG_OPTS%KLON)
ENDSUBROUTINE
END INTERFACE
